### ISSUE TITLE
Feature request: Enable backup only for selected cluster resources

### ISSUE THREAD

**Issue by mwieczorek** [vmware-tanzu/velero#1033]
Right now we can only set `--include-cluster-resources=true/false`. So all cluster resources or none are stored in the backup

I'd like to be able to select cluster resources (kinds) which ark will backup.

**Comment by skriss** [comment]
@mwieczorek you should be able to use the `--included-resources` and `--excluded-resources` to control this.

**Comment by mwieczorek** [comment]
I didn’t describe that well.
I’d like to get backup of one (or more) selected namespace and one (or more) selected cluster resource. 
If I use —include-resources=SomeClusterResource all other namespaced resources are not in the backup.

As a workaround I just make 2 backups. 
But I was wondering if you consider such change (I know it may add some complexity...)

**Comment by skriss** [comment]
Ah, ok, this makes sense and is a limitation we realized when we implemented the `--include-cluster-resources` flag.  Do you have any thoughts on what the UX might look like for this?

**Comment by ncdc** [comment]
We should also think about #589 and #590 as part of this discussion

**Comment by mwieczorek** [comment]
I'd prefer to stay with include/exclude, and not depend only on the selector. In my use-case, I'd like to backup whole namespace, regardless if some resources were labeled or someone forgot about it.

Also, I'd treat cluster-scoped and non-cluster scoped resources separately:
```
--include-cluster-resources stringArray   cluster-scoped resources to include in the backup, formatted as resource.group, such as storageclasses.storage.k8s.io (default: none, use '*' for all resources)
--include-resources stringArray    namespaced resources to include in the backup, formatted as resource.group, such as networkpolicies.networking.k8s.io (default: all resources)

--exclude-cluster-resources stringArray   cluster-scoped resources to exclude from the backup, formatted as resource.group, such as storageclasses.storage.k8s.io (default: none)
--exclude-resources stringArray    namespaced resources to exclude from the backup, formatted as resource.group, such as networkpolicies.networking.k8s.io (default: none)
```
Filtering should first process includes and then excludes (so, for example, I can set `--include-cluster-resources * --exclude-cluster-resources storageclasses.storage.k8s.io` to backup all cluster scope resources except storageclasses

Also, I like Andy's idea to reduce the number of flags and use f.e. `--cluster-resources-filter *,-storageclasses.storage.k8s.io` notation to get the same result as in the example above.

**Comment by eleanor-millman** [comment]
Closing until we hear more interest. Might fall out of multi-tenancy. Workaround is to use labels for cluster-resources.
