### ISSUE TITLE
can pods created by a DaemonSet be excluded from backups?

### ISSUE THREAD

**Issue by mattnworb** [vmware-tanzu/velero#1037]
We recently had a need to restore a cluster from a backup, which worked pretty great overall (thank you for Ark!).

We noticed after the restore that, for a DaemonSet we run for `fluentd`, twice as many pods existed than we expected - one set of pods that were created by the DaemonSet, and another set of fluentd pods that were not attached to the DaemonSet but did have the label `ark-restore: <name of backup>` indicating that those Pods were restored from the backup.

Is it possible to configure Ark to exclude Pods created by DaemonSets from being backed up, since the post-restore DaemonSet will manage to create one pod-per-node on its own?

**Comment by ncdc** [comment]
@mattnworb sorry for the delay in responding! We'll take a look and get back to you as soon as we can. Thanks for your patience!

**Comment by mattnworb** [comment]
Hi @ncdc thanks for the reply and looking into this!

The operation in question that led to me creating this issue was in fact a true recovery - Ark restored both the DaemonSet and all of the Pods in the (original) cluster that were created by the DaemonSet. 

What we noticed after the Ark restore was complete was that we ended up with 2x as many pods for this DaemonSet as we expected - the N pods that the restored DaemonSet created, one per node, and the N pods that had been in the backup. The latter half of these pods were not being managed by the (restored) DaemonSet as you pointed out.

In the case I am thinking of, I would be happy if Ark could be configured to not bother to backup pods that were created by DaemonSets - I'd be confident that a restored DaemonSet would create the necessary pods after being restored.

**Comment by eleanor-millman** [comment]
Gnarly and hard and we will wait until we hear more users feeling this pain before we re-open.

**Comment by sseago** [comment]
FYI, as a workaround you could create a pod RestoreItemAction that excludes pods with DaemonSet OwnerReference, or depending on your use case, perhaps exclude *all* pods with owner references, since the owning DaemonSet, Deployment, etc. will recreate the pod on restore.

**Comment by sseago** [comment]
I've observed the same problem with DaemonSet pods if the pod isn't excluded from restore.

**Comment by joyartoun** [comment]
I'm hitting this problem, we have alerts that are always active because velero backs up pods that belong to daemonsets which we don't care about.

**Comment by sule26** [comment]
Solutions?

**Comment by kaovilai** [comment]
You could in the daemonset pod template include a label (not part of matchLabels) that velero can exclude by label?
