### ISSUE TITLE
Support for multiple different provider credentials

### ISSUE THREAD

**Issue by jaxxstorm** [vmware-tanzu/velero#1064]
**Describe the solution you'd like**
In v0.10.0, the ability to specify multiple backup locations we created. This is an excellent step forward for redundancy, however in practice it's only possible to backup to multiple locations within the same provider.

If you want to backup to say, minio and AWS S3, you'll more than likely have different API keys for each bucket in the different provider. As far as I can tell (unless I'm missing something) only a single set of credentials can be provided to a deployment.

This can be solved by running multiple deployments in different namespaces, but as the number grows this might become unwieldy. It would be good if the keys for a specific provider could be moved into the BackupStorageProvider itself, rather than in the deployment

**Environment:**

- Ark version (use `ark version`): v0.10.0
- Kubernetes version (use `kubectl version`): v1.12.0
- Kubernetes installer & version: digitalocean

**Comment by jenting** [comment]
@zubron I guess this issue could be closed?

**Comment by zubron** [comment]
Ooh, I wasn't aware of this issue. Thanks, @jenting! Yes, this can be closed now as it was handled in #3304.
