### ISSUE TITLE
Colored output 

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#1082]
This is a branch off of #987.

We should decide if we want colored output and, if so, which output should be colored vs not.

**Comment by nzoueidi** [comment]
I suggest to color the output of `Phase` and `Validation error`  to red when the operation has been failed and if the operation has been succeeded, the color will be green.

What do you think? 
cc @rosskukulinski @ncdc @carlisia

**Comment by rosskukulinski** [comment]
It seems reasonable to me, but I'm not sure what the current best practices are in terms of accessibility for red/green color deficiency people.

**Comment by ncdc** [comment]
It would probably make sense to add something like `--colorized=false` or something

**Comment by ncdc** [comment]
Also if it's not a TTY, it should not display the escape codes for colorization (easy to do)

**Comment by carlisia** [comment]
@nzoueidi I'm on board with that, good sugestion.

Please keep in mind: https://github.com/heptio/velero/issues/987#issuecomment-441680773

**Comment by carlisia** [comment]
Hey @nzoueidi, did you still want to work on this?

**Comment by astrieanna** [comment]
Hey @carlisia, is this issue still ready to be worked on?

It sounds like the asks are:
* In the output of `describe`, make the value for the field Validation errors red for all values != none. (from #987)
* In the output of `describe`, color the output of Phase and Validation error red when the operation fails and  green when it succeeds.
* Only output the colorizing escape codes when writing to a TTY.
* Add a command-line argument `--colorized=false`; do not output color when that's set to false.

Is that correct?

**Comment by carlisia** [comment]
Hi @astrieanna that is entirely accurate. and if you run `velero describe` you will see the 3 commands that use it. Thank you!

**Comment by mike1808** [comment]
Hey, we added few colors to `Phase` and `Validation errors` field for backups. Also, we made the name to be in bold to catch an eye if you're viewing multiple backups. 

Here are the examples of completed and failed backups:

![Screen Shot 2021-01-13 at 3 10 08 PM](https://user-images.githubusercontent.com/3942554/104521401-ad4cdc80-55b1-11eb-800f-77b4d32d912c.png)
![Screen Shot 2021-01-13 at 3 10 26 PM](https://user-images.githubusercontent.com/3942554/104521406-b047cd00-55b1-11eb-9297-4dff50e59a54.png)

Let us know what do you think.

**Comment by carlisia** [comment]
Hey @mike1808, this LGTM. You may go ahead with it.
