### ISSUE TITLE
Enhance Ark to deal correctly with fsfreeze privileges

### ISSUE THREAD

**Issue by egagala** [vmware-tanzu/velero#1103]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

In https://github.com/heptio/ark/blob/master/examples/nginx-app/with-pv.yaml security context of pod is set to `privileged: true` to add permissions needed for fsfreeze.

However if your Kubernetes cluster is set with recommended (see CIS benchmarking) security setting "DenyEscalatingExec" it prevents Ark backup hooks from execution and backup fails. You'll get an error: `pods \"nginx-deployment-7d675cdc9b-jjlh9\" is forbidden: cannot exec into or attach to a privileged container`

Ark should deliver `fsfreeze` solution dealing with K8S security best practises.

**Environment:**

- Ark version (use `ark version`): v0.10.0

**Comment by skriss** [comment]
There's an upstream effort to add an `ExecutionHook` API -- see https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20190120-execution-hook-design.md.  We'll likely move Velero to using that API once it's available.  As such, I'm going to close this item out.

**Comment by cortopy** [comment]
@skriss any chance of reopening this issue?

The proposal for the ExecutionHook moved [here](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/962-execution-hook#implementation-history-1) but the issue linked to track implementation went stale and is now closed

There doesn't seem to be any traction on that area

In my opinion, this is a huge security loophole that Velero is forcing on users. Any pod with a `fsfreeze` container would have to run as privileged, thus leading to one of the worst security setups in the kubernetes landscape

maybe the proposal from @ncdc nearly three years ago is worth considering?
