### ISSUE TITLE
404 on docs site with renamed files in earlier versions

### ISSUE THREAD

**Issue by Bradamant3** [vmware-tanzu/velero#1126]
**What steps did you take and what happened:**
- navigate to docs site, go to master or v1.10/get-started
- navigate with version picker to v9
- encounter 404

**What did you expect to happen:**
See earlier version of same content

**Fix needed**
Provide appropriate redirects. We have the right Jekyll plugin enabled but first efforts to implement failed.

**Comment by Bradamant3** [comment]
attempted a fix in #1121 but produced no result. Snippet here bc this is headed in the right direction, just not there yet (this particular case for gh-pages branch, v0.9.0/quickstart.md):
`---
redirect_from: "/get-started/"
---
`

**Comment by nrb** [comment]
This has been fixed in both our Jekyll and Hugo implementations, closing.
