### ISSUE TITLE
RFE: Allow other restic repository backends

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#1178]
**Describe the solution you'd like**
Our code expects that restic snapshots are stored in the BackupStorageLocation used by the backup. Our server code hard-codes logic to determine restic URLs for AWS, Azure, and GCP ObjectStores.

We should consider expanding the supported restic backends to everything restic supports. For example, one user on Slack requested the ability to use NFS (I'm guessing this would just be restic's local directory support). If we do this, we'd probably need to amend BackupStorageLocation to allow the user to specify the restic repo location 100% by hand (and prevent the controller from overwriting it).

We should also probably add a method to ObjectStore to return a restic-compatible URL for the repository location.

Finally, we'd need to explore how to configure credentials for all of the different restic backends.

**Anything else you would like to add:**
Somewhat related to #939

**Environment:**

- Ark version (use `ark version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by eleanor-millman** [comment]
Closing since we don't want to do things that are restic-exclusive.
