### ISSUE TITLE
Consider creating a homebrew tap using goreleaser

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#1219]
There's an `ark` homebrew formula, and we should maintain parity with that.

**Comment by nrb** [comment]
Draft PR at https://github.com/Homebrew/homebrew-core/pull/37130

**Comment by nrb** [comment]
goreleaser [can generate](https://goreleaser.com/homebrew/) these for us, but the caveat is that the formula must live outside homebrew’s core repo inside of a [tap](https://docs.brew.sh/Taps).

I don’t want to create a separate brew repo, but would it be worth maybe using this repo as a tap so that goreleaser handles this process for us? @skriss @carlisia

**Comment by carlisia** [comment]
I have never looked into adding a program to homebrew so I'm pretty unfamiliar. Do users see any different behavior from having the formula in an external repo vs in the homebrew repo?

I saw this note at the foot of the linked page, what does it mean?: 

```
Note that GoReleaser does not yet generate a valid homebrew-core formula. The generated formulas are meant to be published as homebrew taps, and in their current form will not be accepted in any of the official homebrew repositories.
```

And last question I have is, if we publish the formula on this repo, will it be easily transffered when we move to a new org?

**Comment by nrb** [comment]
Users will have to run a command to add the tap repo, and we will have to change it when the org changes. That’s a good point!

That note from GoReleaser means that the formula files it makes won’t be accepted into the core Homebrew repo - files GoRelease makes *must* be in a separate repo from that.

**Comment by carlisia** [comment]
So I think the tradeoffs of doing in our repo are:

- more control/flexibility to update (pro)
- users will need to run an additional command to add the tap (con)

**Comment by nrb** [comment]
I'm going to close this for now, as we have the Homebrew release script for the central Homebrew repo.
