### ISSUE TITLE
SSE-KMS for restic backups

### ISSUE THREAD

**Issue by ac-hibbert** [vmware-tanzu/velero#1263]
**What steps did you take and what happened:**

I have enabled SSE-KMS using kmsKeyId field in BackupStorageLocation. The Backups folder (K8S resources) is encrypted but it seems that the data in the restic folder is not

**What did you expect to happen:**

SSE-KMS for restic

**Comment by skriss** [comment]
Thanks for the issue report @hibbert.  It looks like `restic` does not support SSE-KMS natively.  It might be possible to get support for it if we switch to using [rclone](https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#other-services-via-rclone) as the backend for `restic`.

**Comment by hibbert** [comment]
Thanks for the reply. Looking for some increased security around restic backups this and/or https://github.com/heptio/velero/issues/1053 would be good

**Comment by eleanor-millman** [comment]
Closed since we are avoiding restic-exclusive work.
