### ISSUE TITLE
Move validation from controllers to pkg/backup, pkg/restore

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#131]
Make the validation the first thing we do in Backup() and Restore(). WDYT @skriss?

**Comment by skriss** [comment]
yeah, makes sense to me to put it in the library

**Comment by rosskukulinski** [comment]
Internal development enhancement, but this is P1 because right now we have backup and restore logic split in 2 different packages. In addition, if anyone wants to vendor ark to do backups/restores, it's not pretty. We want a self-contained package for each.

**Comment by skriss** [comment]
Here's an initial mini-design for this issue:

**Goals**
- Move all backup/restore-processing logic into `pkg/backup`, `pkg/restore` respectively so there's a single entrypoint for running a backup/restore which can be more easily tested, vendored, etc.
- Make controllers "dumb" - only responsible for watching for new/updated custom resources, enqueuing them, and dequeueing them and passing them to the appropriate packages for work

**Non-Goals**
- Full refactoring of `pkg/backup` & `pkg/restore`.  The goal of this initial effort is just to draw a clear boundary around the end-to-end backup/restore processes.  From there, integration tests can be written against this boundary to provide guardrails for refactoring the implementations.
- Similar refactoring for other controllers.  This should probably be undertaken later, but first priority is for core backup and restore flows.

**Design**
Entrypoints to packages should be very simple:
```go
// <pkg/backup>
type Pipeline interface {
    Execute(namespace, name string) error
}
```
- Backup pipeline will:
  - Ensure API object exists
  - Ensure API object has the correct phase for processing (blank or `New`)
  - Default unspecified API object fields
    - `.spec.ttl`
    - `.spec.storageLocation`
    - `.spec.volumeSnapshotLocations`
    - `.status.version`
  - Validate API object spec
    - included/excluded resources
    - included/excluded namespaces
    - backup storage location
    - volume snapshot locations
  - Update API object's status to either `FailedValidation` (with errors) or `InProgress`
  - Instantiate all the things
  - Run API-scraping & related actions/hooks
  - Upload artifacts (archive, log, volumesnapshots file) to storage
  - Update API object's final status
- Restore pipeline will work similarly (to be detailed after going through backup pipeline & learning from it)

**Comment by eleanor-millman** [comment]
Closing because it should naturally fall out of the Astrolabe work if we do that.
