### ISSUE TITLE
Support for retention-policy in GCP 

### ISSUE THREAD

**Issue by arianitu** [vmware-tanzu/velero#1422]
**Describe the solution you'd like**
In GCP, you have the ability to set a retention-policy for a bucket. This means, there is no way to delete a backup until that retention-policy is passed. 

For example, if you set a retention-policy to 14 days, the data in the bucket cannot be deleted until the 14 days pass. There is nothing to override this.

It's very useful if you want to prevent backups from being deleted by a third party hacker, or to comply with laws.

 The issue is, Velero does not function under this model:

```
time="2019-05-01T17:59:39Z" level=warning msg="Error updating backup store revision" backup=cluster-monthly-backup-20190501175557 bucket=velero-backups error="error updating revision file: rpc error: code = Unknown desc = googleapi: Error 403: Object 'velero-backups/metadata/revision' is subject to bucket's retention policy and cannot be deleted, overwritten or archived until 2019-05-16T10:41:44.818458602-07:00, forbidden" error.file="/go/src/github.com/heptio/velero/pkg/persistence/object_store.go:388" error.function="github.com/heptio/velero/pkg/persistence.(*objectBackupStore).putRevision" logSource="pkg/persistence/object_store.go:206" prefix=
```

**Anything else you would like to add:**

Is it possible to have metadata per backup instead of storing a central metadata object that updates on each backup?

**Environment:**

- Velero version (use `velero version`):

Client:
	Version: v1.0.0-alpha.2
	Git commit: dda76b05a8f970ee03bc7fa5bee35bef2f70127f
Server:
	Version: v1.0.0-alpha.2

- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:47Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
GKE

- Cloud provider or hardware configuration:
GKE

- OS (e.g. from `/etc/os-release`):
GKE

**Comment by arianitu** [comment]
This has broken backups on this cluster I believe. I am unsure of how to uninstall and restart over without a retention policy.

New backups don't take snapshots properly (it says backup already exists.) and you cannot delete any backups since they forever are stuck on Deleting since they can't be removed from the Retention Policy.

Is there any way to uninstall Velero and restart from scratch so I can do backups again?

**Comment by arianitu** [comment]
Apologies, the snapshot breaking was due to me setting snapshotLocation incorrectly in the VolumeSnapshotLocation manifest. 

Is there a way to change the $BUCKET for GCP and forcefully delete backups so Velero doesn't list them anymore.

**Comment by arianitu** [comment]
I believe I can do this:

- Create a new bucket
- Give access via:

```
 gsutil iam ch serviceAccount:$SERVICE_ACCOUNT_EMAIL:objectAdmin gs://${BUCKET}
```

Then change 

```
kubectl edit BackupStorageLocation -n velero
```

to the new bucket.

How does Velero manage and track backups tho, specifically in `velero backup get`. I don't really want to put Velero in an inconsistent state if i pull the old bucket store from underneath it.

**Comment by arianitu** [comment]
I believe this may be a bit of a difficult change since shouldSync uses the revision to determine if the backup should be synced.

https://github.com/heptio/velero/blob/master/pkg/controller/backup_sync_controller.go#L94

I am unsure exactly what the controller is doing here. shouldSync compares the cluster revision to the revision in the backup to do something, perhaps dump the data?

Either way, for this to work, a new revision would be required to be made on a per backup basis instead of using a global one I think?

**Comment by skriss** [comment]
If you do what you described in https://github.com/heptio/velero/issues/1422#issuecomment-488372178, you should be OK - Velero will notice that there is no revision file in object storage, so will proceed with the sync, as part of which the existing Backup CRDs in the cluster will be deleted since there are no corresponding backups in the revised BackupStorageLocation.

**Comment by arianitu** [comment]
@skriss that worked, cool.

It would be nice for Velero to handle this since right now since if my credentials were to be exposed, it could lead to data loss with a malicious party.

With a retention policy, it's impossible to delete buckets.

**Comment by skriss** [comment]
@arianitu with the latest release, we've stopped using the `metadata/revision` file, which I believe was the thing that was causing issues for you with the retention policy.  I've done a quick test using a bucket with a retention policy and everything seems to work fine (apart from `velero backup delete`, obviously).

I'm going to close this out as resolved, but feel free to reach out again as needed.

**Comment by tpoindessous** [comment]
For future reference : it's not supported anymore 

https://velero.io/docs/v1.12/backup-reference/ "Cannot support backup data immutability"

linked from : https://github.com/vmware-tanzu/velero/issues/6422
