### ISSUE TITLE
Ability to rename backups

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#1456]
Since we preclude the user from creating a backup if it already exists, they have to delete it first before creating one with that same name. Maybe they want to keep it around and could just rename it if we give them this ability.

**Comment by eleanor-millman** [comment]
@carlisia We are inclined to close this because this is a fair amount of work and there is a workaround. Are you ok with this?

**Comment by carlisia** [comment]
👍 

It can always be reopened if it becomes important.
