### ISSUE TITLE
velero restore describe xxx --details provides no additional snapshot details

### ISSUE THREAD

**Issue by cormachogan** [vmware-tanzu/velero#1477]
**What steps did you take and what happened:**
When working with Velero 1.0.0-RC and Portworx RC plugin, I noticed that the command *velero restore describe xxx* and *velero restore describe xxx --details* return exactly the same information

**What did you expect to happen:**
As per the *velero backup describe xxx* and *velero backup describe xxx --details* commands, I expected the --details to provide additional snapshot related information.

**The output of the following commands will help us better understand what's going on**:
`cormac@pks-cli:~$ velero restore describe cassandra-restore
Name:         cassandra-restore
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:  Completed

Backup:  cassandra

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto
cormac@pks-cli:~$ velero restore describe cassandra-restore --details
Name:         cassandra-restore
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:  Completed

Backup:  cassandra

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto
`

**Anything else you would like to add:**
I discussed this with @nrb in slack. Nolan walked the code and saw the problem - the details are only used for the podvolumerestores portion, which wouldn't be available with my Portworx deployment. 

Nolan recommended filing an issue to help track it, though it may be marked as a known issue for the 1.0 release

**Environment:**

- Velero version (use `velero version`):  1.0.0-RC
- Kubernetes version (use `kubectl version`): 1.14.1
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from `/etc/os-release`): 6.7U3 (pre-release)
- Portworx version: 2.0.3.4-0c0bbe4
- Portworx plugin for Velero: portworx/velero-plugin:1.0.0-rc1

**Comment by nrb** [comment]
This is also present with vSphere volumes now, as Velero specifically only looks at PodVolumeBackups, our Snapshots file, and CSI VolumeSnapshots/VolumeSnapshotContents. This should be expanded to allow description of snapshots from various plugin sources.

**Comment by eleanor-millman** [comment]
Closing because will be handled by https://github.com/vmware-tanzu/velero/issues/3758
