### ISSUE TITLE
bash completion not working on macos

### ISSUE THREAD

**Issue by ali5ter** [vmware-tanzu/velero#1505]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
source <(velero completion bash)

**What did you expect to happen:**
expect that tab completion shows available velero subcommands but just shows all files in current dir...

$ velero
Display all 106 possibilities? (y or n)

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I created rudimentary velero bash completion script using cli_taxo which works and can be found at https://raw.githubusercontent.com/ali5ter/cli_taxo/master/exp4/results/velero_completion.sh

**Environment:**

- Velero version (use `velero version`): v1.0.0-rc.1
- Kubernetes version (use `kubectl version`): v1.14.1
- Kubernetes installer & version:
- Cloud provider or hardware configuration: VMware CloudPKS
- OS (e.g. from `/etc/os-release`): MacOS 10.14.4

**Comment by nrb** [comment]
Hm, I'm unable to reproduce this on my Linux machine:

```
x1c in /home/nrb/Downloads
% bash
[nrb@x1c Downloads]$ soue^C
[nrb@x1c Downloads]$ source <(velero completion bash)
[nrb@x1c Downloads]$ velero
backup             client             delete             install            restore            snapshot-location
backup-location    completion         describe           plugin             schedule           version
bug                create             get                restic             server
[nrb@x1c Downloads]$ velero
backup             client             delete             install            restore            snapshot-location
backup-location    completion         describe           plugin             schedule           version
bug                create             get                restic             server
[nrb@x1c Downloads]$ velero
backup             client             delete             install            restore            snapshot-location
backup-location    completion         describe           plugin             schedule           version
bug                create             get                restic             server
[nrb@x1c Downloads]$ velero
backup             client             delete             install            restore            snapshot-location
backup-location    completion         describe           plugin             schedule           version
bug                create             get                restic             server
[nrb@x1c Downloads]$ velero
backup             client             delete             install            restore            snapshot-location
backup-location    completion         describe           plugin             schedule           version
bug                create             get                restic             server
```

zsh integration works, as well. @skriss or @carlisia could you try this out?

**Comment by carlisia** [comment]
Yes, the `velero` + tab does not work on my mac/bash.

**Comment by jonasrosland** [comment]
Same result, on Mac.

```
$ bash
bash-3.2$ velero
LICENSE   examples/ velero
```

Using ZSH:
```
$ velero
LICENSE    examples/  velero*
```

**Comment by cblecker** [comment]
Velero uses the cobra library, which is the same library kubectl uses. The [docs for kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion) should also apply to Velero. Note that using the homebrew formula for Velero, completion is working.

**Comment by skriss** [comment]
Sounds like we should update our docs (maybe just the CLI help text) to cover the necessary prereqs

**Comment by cpanato** [comment]
@skriss i can work on that as well sounds quick win
