### ISSUE TITLE
Explicit NodePort values defined in Helm charts are deleted during restoration

### ISSUE THREAD

**Issue by Rathgore** [vmware-tanzu/velero#1512]
**What steps did you take and what happened:**

1. Deploy a Helm chart containing a K8s `Service` with explicitly defined NodePort port values.
1. Create a Velero backup of the service.
1. Delete the service.
1. Restore the backup of the service.
1. Note that the explicit NodePort port values are removed, and new, random port numbers are assigned.

**What did you expect to happen:**

Explicitly defined NodePort values should be restored from the backup.

**Anything else you would like to add:**

This appears to be caused by the `deleteNodePorts` function (see below). As written it looks for the presence of the `kubectl`-specific annotation `kubectl.kubernetes.io/last-applied-configuration` which it uses to restore the port values. Only `kubectl` creates this annotation so the port restoration fails when using other deployment methods such as Helm:

https://github.com/heptio/velero/blob/a111eed2af8c0bb37ecd6d682b3faad116fbad2f/pkg/restore/service_action.go#L70-L100

A potential solution would be to support reading a custom annotation on K8s services that would direct Velero to preserve and not delete any custom port values.

**Possible workarounds:**

* Use `helm template` and pipe through `kubectl apply`. This won't work for us as we depend on the release management features of Helm.
* Create a _Restore Item Action_ Velero plugin to force the restoration of the NodePort values. It is unclear to me if this plugin would execute at the right stage so that these values would be preserved and not just removed again in the final restore.

**Environment:**

- Velero version (use `velero version`): 

```
Client:
	Version: v1.0.0
	Git commit: 72f5cadc3a865019ab9dc043d4952c9bfd5f2ecb
Server:
	Version: v1.0.0
```
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.13", GitCommit:"954ff68d59e9dc62fa8252ffa9023a90ff8a358c", GitTreeState:"clean", BuildDate:"2019-02-13T11:03:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by skriss** [comment]
@Rathgore thanks for the issue report - your analysis looks correct. The challenge is knowing whether or not the NodePort value was explicitly specified by the user, or auto-assigned by the system. In the absence of being able to figure this out systematically for all cases, I agree that giving the user some kind of control over whether these get restored or not probably makes sense.

**Comment by Rathgore** [comment]
Thanks @skriss. I am tempted to pursue writing a plugin as a workaround. Would a _Restore Item Action_ plugin work in this case? Does it execute after `deleteNodePorts`?

**Comment by bernardomk** [comment]
Same issue here. I don't know how velero restore works but the port  looks fine in the json, so it's really weird that this is only happening with services created by helm charts.
