### ISSUE TITLE
Update defaultRestorePriorities for CSI resources

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#1565]
When restoring a CSI volume, the following resources should be restored before PVCs, in order to properly hook up references:

* volumesnapshotcontents.snapshot.storage.k8s.io
* volumesnapshot.snapshot.storage.k8s.io
* volumesnapshoclass.snapshot.storage.k8s.io 

A more complete list looks like this:

```go
var defaultRestorePriorities = []string{
    "namespaces",
    "storageclasses",
    "customresourcedefinitions",
    "volumesnapshotclass.snapshot.storage.k8s.io",
    "volumesnapshotcontents.snapshot.storage.k8s.io",
    "volumesnapshots.snapshot.storage.k8s.io",
    "persistentvolumes",
    "persistentvolumeclaims",
    "secrets",
    "configmaps",
    "serviceaccounts",
    "limitranges",
    "pods",
    "replicaset",
}
```

**Comment by skriss** [comment]
For the prototype phase, we should consider just having users use the `--restore-resource-priorities` flag on the `velero server` command to configure this.

**Comment by nrb** [comment]
Yeah, that’s totally reasonable.

I’ll update docs and move this out of the v1.1 milestone.
