### ISSUE TITLE
Include CSI snapshot details in backup describe command

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#1568]
The `describe` commands currently have no way to display VolumeSnapshot/VolumeSnapshotContents associated with a given backup or restore.

On the server side, the following needs to change:

* persistBackup will be extended to query for all VolumeSnapshots associated with the backup, and persist the list to JSON.
* BackupStore.PutBackup will receive an additional argument, volumeSnapshots io.Reader, that contains the JSON representation of VolumeSnapshots. This will be written to a file named csi-snapshots.json.gz.

On the client side:

* DescribeBackupStatus will be extended to download the csi-snapshots.json.gz file for processing. GitHub Issue 1568 captures this work.
* A new describeCSIVolumeSnapshots function should be added to the output package that knows how to render the included VolumeSnapshot names referenced in the csi-snapshots.json.gz file.

**Comment by skriss** [comment]
Are there any other low-cost options here that are "good enough" for the prototype?  I don't think we need a super-polished UX for the prototype phase - adding labels/annotations to the backup CR, or a `kubectl get volumesnapshots -l foo=bar` sample command, etc. could work fine for the prototype phase. If we do end up needing to do this or any other in-tree code changes for the prototype, though, I imagine we want to set up a branch specifically for the prototype that likely will never get merged into master, that prototype testers can build and use to exercise the functionality.

**Comment by nrb** [comment]
This is more long term, hence the P2 label. IMO it doesn’t need to be in the prototype, but will be necessary for full support, so we could even move it out of v1.1.

That said, if a namespace is deleted, the volumesnapshots won’t be around to kubectl get. They’re stored in the same namespace the PVC is in.

**Comment by skriss** [comment]
OK, yeah, makes sense. I think it'd be fine if for the prototype we just expected users to "know" which snapshots were in their backups. Definitely a must-have for GA, though.
