### ISSUE TITLE
Add instructions to make changes to the website

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#1573]
No where do we point to the instructions for how to run our website locally. This should be part of how to make website related contributions, ie, be sure to run your changes locally.

The instructions are here: https://github.com/heptio/velero/blob/master/site/README-JEKYLL.md

Need to add an entry to that somewhere obvious.

Other instructions:
- Maybe mention we disabled the use of separators for blog posts (see https://github.com/heptio/velero/pull/1578)

- ~Take a screenshot of the working change (so the reviewer doesn't have to pull the branch and check)~ Add instruction to verify changes using Netlify preview feature.

**Comment by jonasrosland** [comment]
I think this could live under "More information" in the docs, after the FAQ, what do you think?

**Comment by carlisia** [comment]
I think there should be an item parallel to "More Information" named "Contribute". Under that we would have to think about what to list but everything related to contributing to the code base and website.

**Comment by jonasrosland** [comment]
I like that idea. I know @seemonicago was working on updates to the instructions, perhaps that could be the first item under the "Contributing" item then.

**Comment by carlisia** [comment]
Thanks @nrb: `This URL, https://velero.io/docs, ex: https://velero.io/docs/support-matrix/ will automatically go to latest`.

**Comment by skriss** [comment]
Closed by #2032
