### ISSUE TITLE
Consider downloading all metadata files as part of `velero backup download`

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero#1619]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Currently, `velero backup download` only downloads the backup tarball. We should consider also downloading all of the metadata files (the backup CR YAML, volumesnapshots, etc), so that in theory the complete file set could be re-uploaded to object storage and restored by another Velero instance.

**Comment by eleanor-millman** [comment]
Closing because subset of #1492
