### ISSUE TITLE
Use same service account as k8s on GKE

### ISSUE THREAD

**Issue by drzero42** [vmware-tanzu/velero#1639]
**Describe the solution you'd like**
On GKE I create a GCP service account that my cluster runs under. I give this service account access to my GCS bucket for backups. Instead of having to export the service account key and specifically adding it to Velero, it would be nice if Velero could just use the metadata server and run as the service account that the k8s cluster is using.

**Anything else you would like to add:**
This use-case is already in use for other software running in k8s. The example is external-dns. I just give the service account that my k8s cluster is running under, permission to administrate Cloud DNS, and ask for the correct scope during creation of the cluster. Then external-dns does not need an explicit key file to interact with Cloud DNS, when running in my cluster.

**Environment:**

- Velero version (use `velero version`): 1.0.0
- Kubernetes version (use `kubectl version`): 1.14
- Kubernetes installer & version: GKE
- Cloud provider or hardware configuration: Google Cloud Platform

**Comment by skriss** [comment]
Thanks for the report @drzero42 ! We'll investigate this some more  and update here.

**Comment by thefirstofthe300** [comment]
Likely duplicate: https://github.com/heptio/velero/issues/1657

**Comment by skriss** [comment]
@drzero42 we've added support for [GKE Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) in the latest release, which according to Google is their recommended approach to providing identity to workloads running in a cluster.

Does this address your request? If so, we can close this issue out, but if not, let us know (and why not).

**Comment by drzero42** [comment]
@skriss Sounds like it will definitely address my problem. Any documentation or maybe a link to a PR for this feature? I don't see it listed in the changelog for 1.2.0.

**Comment by skriss** [comment]
You're right, we missed a changelog on this one.

Here are GKE's docs on Workload Identity:
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

And here are the docs for setting up Velero using Workload Identity:
https://github.com/vmware-tanzu/velero-plugin-for-gcp#option-2-set-permissions-with-using-workload-identity-optional

**Comment by skriss** [comment]
I'm going to speculatively close this out given the above, but feel free to reopen if needed!

**Comment by drzero42** [comment]
@skriss Thank you, the documentation looks great :)
