### ISSUE TITLE
Add "Velero on vSphere" section for install and configuration for Kubernetes w/CNS on 6.7U3

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#1697]
We need documentation for how to install and configure Velero to backup/restore Kubernetes on vSphere with the CNS CSI driver and Restic.

**Comment by fferencik** [comment]
Exactly. Im struggling to install Velero v1.0.0 on VMware PKS 1.3.0-build.126 / NSX 2.3 on top of the VMware vSphere 6.5.0. I miss instructions specifically for vSphere / PKS. I have received 'An error occurred: some backup storage locations are invalid: backup store for location “default” is invalid: rpc error: code = Unknown desc = NoSuchBucket: The specified bucket does not exist
       status code: 404' via 'kubectl logs deployment/velero -n velero'.

**Comment by nrb** [comment]
@dsu-igeek CNS/CSI only covers the persistent volumes; do you have a recommendation on what to use for object storage? Is there an S3-compatible API in the storage stack?

**Comment by dsu-igeek** [comment]
We do not have an object store as part of the standard vSphere stack unfortunately.

**Comment by dsu-igeek** [comment]
FYI, the draft doc is here: https://github.com/dsu-igeek/velero/blob/master/site/docs/master/vsphere-config.md

@fferencik - the doc is written for generic K8S and Kubernetes, if you can give some feedback on what areas would help you, I can work with the Pivotal team to add some stuff.  The install for vSphere has been pretty generic for us so far.  I think the error you're seeing means the object store configuration is not working.

**Comment by fferencik** [comment]
@dsu-igeek I have discussed this with Cormac Hogan @cormachogan and succeeded based on his blog post https://cormachogan.com/2019/08/08/setting-up-velero-1-0-0-to-backup-k8s-on-vsphere-pks/ . Only thing I had to add was DNAT rule to access NodePort.

**Comment by cormachogan** [comment]
Note that this PR is to have Velero work with restic and the new out-of-tree **vSphere CSI driver for Kubernetes**, which will be available very shortly. To date, VMware has been using an in-tree driver called the VCP, short for vSphere Cloud Provider. This is the driver found on PKS, as well as other distros such as OpenShift when deployed on vSphere. However, it doesn't seem like the instructions will differ from those that I documented on the blog.

**Comment by dsu-igeek** [comment]
No, there shouldn’t be any differences.
