### ISSUE TITLE
Removing backups with kubectl does not trigger velero-server backup removal

### ISSUE THREAD

**Issue by invidian** [vmware-tanzu/velero#1712]
**What steps did you take and what happened:**
- create full backup with `velero backup create test`
- wait for backup to complete
- remove backup using kubectl: `kubectl delete backups test -n velero`

**What did you expect to happen:**
- Azure snapshot and data in blob storage should be removed

**The output of the following commands will help us better understand what's going on**:

Velero server does not produce any logs on delete operation

**Anything else you would like to add:**
Creating subsequent backups fails with following message:
```
time="2019-07-31T12:55:48Z" level=error msg="backup failed" controller=backup error="backup already exists in object storage" error.file="/go/src/github.com/heptio/velero/pkg/controller/backup_controller.go:484" error.function="github.com/heptio/velero/pkg/controller.(*backupController).runBackup" key=velero/test logSource="pkg/controller/backup_controller.go:230"
```

Snapshots are still visible in Azure, so manual cleanup is required.

I also wasn't able to find any information in the docs, that using `kubectl` for taking backups is not recommended.

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.0.0
	Git commit: 72f5cadc3a865019ab9dc043d4952c9bfd5f2ecb
Server:
	Version: v1.0.0
``
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: AKS
- Cloud provider or hardware configuration: Azure

**Comment by skriss** [comment]
@invidian yes - if you want to delete the backup including all data in object/block storage, use `velero backup delete`.  As you said, using `kubectl delete` will only delete the custom resource.

I agree this is probably not documented well, and we should probably add something to explain the hows and whys.

**Comment by invidian** [comment]
>@invidian yes - if you want to delete the backup including all data in object/block storage, use velero backup delete. As you said, using kubectl delete will only delete the custom resource.

Thanks for confirmation @skriss. And do you know if there are any implications from **creating** backups, schedules etc using `kubectl`?

**Comment by skriss** [comment]
Creates via `kubectl` are fine. You can also `velero backup create ... -o yaml` to generate a YAML spec for a backup, which you can later apply using `kubectl`.

**Comment by turkenh** [comment]
What I understand from the [source code](https://github.com/vmware-tanzu/velero/blob/master/pkg/cmd/cli/backup/delete.go#L117), deletions are triggered via another crd called [`DeleteBackupRequest`](https://github.com/vmware-tanzu/velero/blob/master/pkg/apis/velero/v1/delete_backup_request.go#L57).

So, if you want to use kubectl (or go client) to delete a backup, you need to create `DeleteBackupRequest` instead of deleting `Backup` resource.

**Comment by framled** [comment]
there are no documentation about those resources.

**Comment by eleanor-millman** [comment]
@a-mccarthy Changing this to be a documentation issue.

**Comment by kumars17** [comment]
> Creates via `kubectl` are fine. You can also `velero backup create ... -o yaml` to generate a YAML spec for a backup, which you can later apply using `kubectl`.

Do you know the "kind" value to use for this 

> What I understand from the [source code](https://github.com/vmware-tanzu/velero/blob/master/pkg/cmd/cli/backup/delete.go#L117), deletions are triggered via another crd called [`DeleteBackupRequest`](https://github.com/vmware-tanzu/velero/blob/master/pkg/apis/velero/v1/delete_backup_request.go#L57).
> 
> So, if you want to use kubectl (or go client) to delete a backup, you need to create `DeleteBackupRequest` instead of deleting `Backup` resource.

Do you know the "Kind" value to use with "DeleteBAckupRequest". I am tryng with Kind: Backup and it throws error telling that backup already exist even thou, the request is 'DeleteBackuprequest'

**Comment by invidian** [comment]
With more K8s experience now, I guess velero could set a finalizer on `Backup` object, then generate a `DeleteBackupRequest` for the user if `deletionTimestamp` is set on `Backup` object while reconciling it.

**Comment by dsu-igeek** [comment]
We made the deletion an explicit request rather than being triggered by deletion because deletion of a namespace will delete all of the resources.  This means that if we implemented deletion when the Backup resource was deleted, uninstalling Velero and deleting its namespace would delete all of the actual backups.  It's a pretty common use case to backup a cluster, remove all of the resources and then restore into another cluster.

**Comment by invidian** [comment]
@dsu-igeek thanks for the explanation. I was thinking also about maybe blocking `kubectl` from removing the `Backup` CR, but I guess this may block the namespace deletion, so it doesn't make much sense.

Perhaps there could be a validating webhook generating a warning if the Backup object has been removed without associated DeleteBackupRequest? This way at least clients would be informed, that removing backup does not actually remove a backup. Or maybe this fact could be documented at least? I don't see any documentation about removing the backups either.

In any case, thank you for clarifying that this has been a deliberate decision. I don't insist on the above, so feel free to close this issue.

**Comment by a-mccarthy** [comment]
Just to clarify here, we'd like to make sure that the docs cover more details about deleting backups, specifically:

*  `kubectl delete backups` will delete the backup resource, so no more of that specific backup will be taken, but none of the backups take by that backup resource will be deleted
* Using `velero backup delete` will delete the backup resource including all data in object/block storage
* Creating a `DeleteBackupRequest` delete the backup resource including all data in object/block storage. You can use  kubectl to create a `DeleteBackupRequest`

my code snippets are definitely not accurate, but I want to make sure i understand the gist of what we want to add to the docs :) 

cc: @dsu-igeek

**Comment by zubron** [comment]
@a-mccarthy Yep, the different flows that you've outlined above are correct :) I would just suggest a slight correction to the first point as a backup resource in the cluster corresponds to one backup only (it does not result in subsequent backups being taken):
- `kubectl delete backup` will delete the backup custom resource only and will not delete any associated data from object/block storage

**Comment by a-mccarthy** [comment]
We should add this to the backup reference page as a new section, https://velero.io/docs/v1.8/backup-reference/, like "Deleting backups" to clarying how deleting works, and provide more context for users on how to delete backups

* `kubectl delete backup` will delete the backup custom resource only and will not delete any associated data from object/block storage
* Using `velero backup delete` will delete the backup resource including all data in object/block storage
* Creating a `DeleteBackupRequest` delete the backup resource including all data in object/block storage. You can use kubectl to create a `DeleteBackupRequest`
