### ISSUE TITLE
Clarify implications of removing restore object

### ISSUE THREAD

**Issue by invidian** [vmware-tanzu/velero#1715]
**Describe the problem/challenge you have**

If you restore a lot of backups, sometimes you want to clean up `restore` objects. However, currently the documentation does not say what happens when you remove `restore` object. Having that clarified would be great.

**Describe the solution you'd like**

The clear documentation of what restore object represents and what happens when user removes it would be great.

**Comment by skriss** [comment]
A `restore` object represents a restore operation. Deleting it via `velero restore delete` will delete the custom resource representing it, along with its individual log & results files, but *will not* delete any objects that were created by it from your cluster.

Deleting it via `kubectl -n velero delete restore` will delete the custom resource representing the restore, but *will not* delete log/results files from object storage, or any objects that were created by the restore in your cluster.
