### ISSUE TITLE
Restic backup is repeated as many times as the number of pods in a deployment for RWX volumes

### ISSUE THREAD

**Issue by vitobotta** [vmware-tanzu/velero#1744]
**What steps did you take and what happened:**
I have installed the NFS server provisioner in order to have a ReadWriteMany volume shared by multiple pods in a deployment. I have annotated the deployment/pods so that Restic can back up the shared volume, but the Restic backup is repeated for each pod.

**What did you expect to happen:**
One backup only should be done for the same volume regardless of how many pods are sharing it.

**Environment:**

- Velero version (use `velero version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.14.3
- Kubernetes installer & version: Rancher 2.2.6
- Cloud provider or hardware configuration: Hetzner Cloud
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by vitobotta** [comment]
It's not just the backup repeated multiple times... restore doesn't work at all because Restic attempts to restore the same volume for all the pods at the same time. So backup is not usable at all with RWX...

**Comment by skriss** [comment]
Thanks for the report @vitobotta, sorry this isn't working. I think we could add code to the backup process to track whether we've backed up a PVC yet using restic, and if so, skip it if it's ever encountered again.

**Comment by vitobotta** [comment]
Thanks, that would be great. For now I have found an alternative for my app's user uploads which is MInio. Object store seems to work fine for what I need to do so for now I keep the data in a volume managed by a single Minio pod and then use Velero to back up Minio. But it would be nice to be able to back up a shared file system as well for flexibility.

**Comment by sseago** [comment]
I've actually been able to restore RWX volumes without running into this problem. I'm not sure whether it's a race condition or if it's dependent on volume type. I was restoring to a CSI Cephfs volume, and the PVC was shared by three pods. In my test case, it was a relatively small volume with an even smaller (but non-empty) amount of data.
