### ISSUE TITLE
Feature Request: Annotate pods as critical during backups to resolve issues with descheduler/HPA

### ISSUE THREAD

**Issue by echel0n** [vmware-tanzu/velero#1752]
**Describe the problem/challenge you have**
Scheduled backups on a cluster that uses descheduler or HPA will sometimes result in not being able to locate the pod volume due to the pod being re-scheduled.

**Describe the solution you'd like**
Add in the ability to set "scheduler.alpha.kubernetes.io/critical-pod" annotation prior to performing pod backup then remove after backup has been completed.

**Environment:**

- Velero version (use `velero version`): v1.1.0-beta.1
- Kubernetes version (use `kubectl version`): v1.15.0
- Kubernetes installer & version: kubeadm / v1.15.0
- Cloud provider or hardware configuration: 3 node cluster
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.2 LTS

**Comment by skriss** [comment]
@echel0n are you looking to be able to add this annotation to your workload's pods? or to the velero pods? or both?

**Comment by echel0n** [comment]
both would be good so descheduler doesn't kill the pods during backup or restore

**Comment by skriss** [comment]
xref #1770
