### ISSUE TITLE
Feature Request: Ability to restore volumes+PVCs in a different AWS AZ 

### ISSUE THREAD

**Issue by emayssat** [vmware-tanzu/velero#1755]
Velero is awesome to backup and restore kubernetes objects.
That being said, beyond simple backup and restore operations, we investigated whether velero could help in the case of an AWS AZ failure. Unfortunately, with the current implementation, it does not appear to be supported.

Indeed, in the backup metadata, I found that the AZ is hardcoded in the volumesnapshot file, e.g. nginx-backup-20190810055750-volumesnapshots.json.gz and in the corresponding PVC manifests, stored and compressed in the manifest archive, e.g. nginx-backup-20190810055750.tar.gz

**Describe the solution you'd like**
Although velero does not support it, I edited the volumesnapshot and manifest archives manually, and was successfully able to restore my stateful sets in another AZ (us-east-2b) than the one they originated from (us-east-2a). 

At this time, I do not see anything in the 'velero restore create' command that would support the feature. But that's where I would expect to see the command line option.

Could it be possible for velero to support the feature?
Yes! 
In my case, the manual metadata changes I executed were rather simple.
Nothing in my installation is specific, therefore I believe a generic solution is possible.  

**Anything else you would like to add:**
Awesome tool!

**Environment:**

- Velero version (use `velero version`): v1.1.0-beta.1
- Kubernetes version (use `kubectl version`): EKS 1.13
- Kubernetes installer & version: eksctl
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): AWS AMIs, generic cluster deployed with eksctl.

**Comment by moelsh-thoughtworks** [comment]
So as if version 1.2.0, this is still not implemented and the "hack" above works. Just change the az in both the files specified. Please notice that you need to change in the persistentvolume (not the persistentvolumeclaim) resource.

**Comment by dsu-igeek** [comment]
Merged into #3772

**Comment by PaperElmo** [comment]
unable to restore with another zone within the same region after modified the files
modified the az:
-volumesnapshots.json.gz
.tar.gz\resources\persistentvolumes\cluster\pv.json
.tar.gz\resources\persistentvolumes\v1-preferredversion\cluster\pv.json

and returned the error during restoring `zero items to be restored: directory "/tmp/1087314176/resources": does not exist`
