### ISSUE TITLE
Tighten File/Folder Permissions 

### ISSUE THREAD

**Issue by davissp14** [vmware-tanzu/velero#1758]
Our code-scan picked up a few places where file/directory permissions are a bit more open than they should be. 

**Client Config**
https://github.com/heptio/velero/blob/master/pkg/client/config.go#L70
https://github.com/heptio/velero/blob/master/pkg/client/config.go#L66

**Pod Volume Restore Controller**
https://github.com/heptio/velero/blob/master/pkg/controller/pod_volume_restore_controller.go#L365

**Issue Template Gen**
https://github.com/heptio/velero/blob/master/hack/issue-template-gen/main.go#L32

**Comment by skriss** [comment]
Can you add what you think the permissions *should* be for each of these?

**Comment by skriss** [comment]
@davissp14 just following up here.

**Comment by jnaulty** [comment]
For the config file, it should be `0600`
For the config file _directory, permission should be `0700`

**Comment by ashish-amarnath** [comment]
addressed by #2199
