### ISSUE TITLE
ensure pod volume is empty before restic restore

### ISSUE THREAD

**Issue by prydonius** [vmware-tanzu/velero#1764]
See conversation on Slack: https://kubernetes.slack.com/archives/C6VCGP4MT/p1565817791421900

Restic will overwrite any files from a backup that already exist in a volume on restore. Whilst this is expected for Restic, it might not make sense in Velero's usecase. To be consistent with cloud-provider snapshot restores, we should check to ensure that a pod volume is empty before attempting to restore into it. This way, we never accidentally overwrite any existing files in a volume and can expect the restored volume to only contain files that were in the backup. Does this sound like an okay expectation?

Additionally if we know the directory is empty, we can calculate the progress of a restore based on the size of the directory and size of the full backup (#1749).

**Comment by skriss** [comment]
I think we decided that this isn't an issue, as PVs will be dynamically provisioned (empty) on a restic restore, and things like `emptyDir` will also be recreated as the pod is restored - is there anything else to follow up on here?

**Comment by prydonius** [comment]
I haven't tried it, but what happens if you try to use a gitRepo volume, or some other type of volume that might pull in additional files before the init-containers? Just a thought, I know the gitRepo volume isn't really used and I don't know of any other volume types that do this. I'm happy closing this out if we don't think it's worth investigating this more.

**Comment by skriss** [comment]
closing this one out as I don't think there's an action item here, but we can reopen as needed.

:wave: adnan :)
