### ISSUE TITLE
Document using Velero with two remote clusters

### ISSUE THREAD

**Issue by rbankston** [vmware-tanzu/velero#1766]
**Describe the problem/challenge you have**
Document the configuration needed for backing up a remote cluster including the need to use the CLI to point to the remote cluster to initiate and control the backup along with a minimum set of manifests for the local and remote backup.

**Describe the solution you'd like**
Documented steps to configure Velero to take backups in a remote cluster

**Anything else you would like to add:**
Useful for systems like Gardener or OpenStack with a remote cluster native to the design

**Comment by eleanor-millman** [comment]
We are handling this with the multi cluster work.
