### ISSUE TITLE
Define printer columns for Velero CRDs for kubectl interoperability

### ISSUE THREAD

**Issue by prydonius** [vmware-tanzu/velero#1780]
Currently, the Velero CLI shows more information than `kubectl`:

```
$ velero get backups
NAME                  STATUS      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
manual-3              Completed   2019-08-06 15:26:22 -0700 PDT   15d       default            app=nginx

$ kubectl get backups -n velero
NAME                  AGE
manual-3              14d
```

We can define `additionalPrinterColumns` in Velero CRDs to customise the output when using `kubectl` to show the same information. Other tools also use this information to present more information, such as [Octant](https://github.com/vmware/octant), so this would create a consistent UX across these tools.

See https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns

**Comment by prydonius** [comment]
As we are now using _controller-tools_, we can use kubebuilder annotations for generating additional printer columns for CRDs: https://book.kubebuilder.io/reference/generating-crd.html#additional-printer-columns

**Comment by zubron** [comment]
For most of the columns, it seems like it will be straightforward to include them in the `additionalPrinterColumns`. However, some of the data presented by Velero undergoes processing as part of being printed in the table. For example, the value for `EXPIRES` column shown above is calculated from [either the `.status.expiration` field or `.spec.ttl.duration](https://github.com/vmware-tanzu/velero/blob/main/pkg/cmd/util/output/backup_printer.go#L87-L93).

As far as I can tell, there isn't a way with [JSONPath syntax](https://kubernetes.io/docs/reference/kubectl/jsonpath/) to replicate such output, or even to have conditional values printed, unless there's some trick that I'm missing?

If we can't include those fields in the same way - should we just omit them from the `additionalPrinterColumns`?
