### ISSUE TITLE
velero pod is restarting when each backup is done and backups are in "In Progress" state

### ISSUE THREAD

**Issue by apostoa** [vmware-tanzu/velero#1802]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

- I've noticed in one of the test clusters where we run velero that the server pods are having multiple restarts. https://gist.github.com/apostoa/9d260cc4e994b6354e0c537872f20d8e

- After I've checked the Backups, I've seen that they are showing "In progress" state and aren't uploaded to S3 bucket. https://gist.github.com/apostoa/e44616878826fbd4bd183ef14bf3d521

**What did you expect to happen:**

- To have the Backups in status "Completed" and have them uploaded to S3 bucket. 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- I've checked the velero pods : 
https://gist.github.com/apostoa/d1e48eb210ed8b8875892aac68d90054

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

- We run velero (with 2 replicas) currently on 4 clusters from testing environment and all the backups are uploaded to a common S3 bucket.

- The issues encounters only on one of the clusters -> devstacks.

- I deleted the pods, redeploy the release and still the issue persist.

- I've seen it in the velero pods the Error (which appears after several backups are taken and pods are restarted): https://gist.github.com/apostoa/438b4f31cf99e4a18248f87140a39a13

**Environment:**

- Velero version (use `velero version`): v1.0.0
- Kubernetes version (use `kubectl version`):Client Version:v1.15.0/Server Version: "v1.12.7"
- Kubernetes installer & version: v1.12.7
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):Ubuntu 16.04.6 LTS (Xenial Xerus)

**Comment by apostoa** [comment]
Any idea please ? :(

**Comment by xlstefan** [comment]
In the specified log:
`time="2019-08-24T17:46:48Z" level=error msg="Error getting backup metadata from backup store" backup=velero-testbackup-devtools-20190824161513 backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = error getting object backups/velero-testbackup-devtools-20190824161513/velero-backup.json: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: 1293181E4A3E4325, host id: v7BWm9xfMEYs8oBPJWVX6KbY2LBCTR5N+lWUF5dcHEnNztvyyCvyZLs3G+YSTRAatEwqzeq4n8g=" error.file="/go/src/github.com/heptio/velero/pkg/persistence/object_store.go:223" error.function="github.com/heptio/velero/pkg/persistence.(*objectBackupStore).GetBackupMetadata" logSource="pkg/controller/backup_sync_controller.go:208"
`
Does the key exist?

**Comment by apostoa** [comment]
Those keys does not exists anymore because TTL is set to 90 min so actually the "old" backups are deleted..so basically it succeeds to delete the k8s backups but all the new ones are failing, but this error occurs after several backups are done and at each backup the velero pods are restarted.
Maybe a cause could be that we have a common bucket for 3 environments ? The weird part is that in velero pods from devstacks i see the missing keys from smoketest for example.

**Comment by apostoa** [comment]
Another errors seen on velero pods today : ```time="2019-08-29T09:30:55Z" level=error msg="Error in syncHandler, re-adding item to queue" controller=backup-deletion error="error patching DeleteBackupRequest: deletebackuprequests.velero.io \"velero-testbackup-devstacks-20190829080017-psgz7\" not found" error.file="/go/src/github.com/heptio/velero/pkg/controller/backup_deletion_controller.go:494" error.function="github.com/heptio/velero/pkg/controller.(*backupDeletionController).patchDeleteBackupRequest" key=kube-system/velero-testbackup-devstacks-20190829080017-psgz7 logSource="pkg/controller/generic_controller.go:137"
time="2019-08-29T09:30:55Z" level=error msg="Error in syncHandler, re-adding item to queue" controller=backup-deletion error="error patching DeleteBackupRequest: deletebackuprequests.velero.io \"velero-testbackup-smoketest-20190829080017-tf7k6\" not found" error.file="/go/src/github.com/heptio/velero/pkg/controller/backup_deletion_controller.go:494" error.function="github.com/heptio/velero/pkg/controller.(*backupDeletionController).patchDeleteBackupRequest" key=kube-system/velero-testbackup-smoketest-20190829080017-tf7k6 logSource="pkg/controller/generic_controller.go:137"```

**Comment by apostoa** [comment]
@nrb any thoughts on the issue above ?

**Comment by nrb** [comment]
>We run velero (with 2 replicas) currently on 4 clusters from testing environment and all the backups are uploaded to a common S3 bucket.

Currently, velero with more than 1 replica is not well-tested or supported, unfortunately.

Also, the backups for each cluster should at least be within their own prefix in the bucket; having multiple clusters write to the same bucket isn't supported. See our [FAQ](https://velero.io/docs/v1.1.0/faq/#im-using-velero-in-multiple-clusters-should-i-use-the-same-bucket-to-store-all-of-my-backups) about setting up multiple clusters with one bucket.

**Comment by apostoa** [comment]
@nrb thanks a lot for you answer. We will try to have the backups created for each cluster within their own prefix in the bucket.

**Comment by skriss** [comment]
Please update here on if that resolves your issue!

**Comment by skriss** [comment]
Closing this out, feel free to reach out again if needed.

**Comment by apostoa** [comment]
Hello! I have followed the recommendation to created different prefixes for the clusters of testing environment but the problem(another error this time) still appears in *devstacks* cluster. I have attached the velero pod logs here . https://gist.github.com/apostoa/ec36cf55b038d1ef9610e38ccbc07413

**Comment by carlisia** [comment]
@apostoa it seems you have having memory issues. 

In the next release we will have new flags that will let you adjust memory settings for Velero. They are these flags:

```
      --velero-pod-cpu-limit string                CPU limit for Velero pod. A value of "0" is treated as unbounded. Optional. (default "1000m")
      --velero-pod-cpu-request string              CPU request for Velero pod. A value of "0" is treated as unbounded. Optional. (default "500m")
      --velero-pod-mem-limit string                memory limit for Velero pod. A value of "0" is treated as unbounded. Optional. (default "256Mi")
      --velero-pod-mem-request string              memory request for Velero pod. A value of "0" is treated as unbounded. Optional. (default "128Mi")
```

**Comment by apostoa** [comment]
@carlisia thanks you for your quick answer. 

Indeed i increased the memory but unfortunately i still got errors only on this cluster which i posted here: https://gist.github.com/apostoa/59f1c5b85c049908546d1d2264d989ae

The backups still get "In Progress" state without getting into the S3 bucket.

The BackupStorageLocation seems to be created correctly on the cluster : https://gist.github.com/apostoa/6a5b6e0b1479d4904b28c189e2409927 

but the prefix/folder "devstacks" does not appear to be created in S3 bucket( I think is because no backup got in "Completed" phase in order to be pushed into AWS S3 bucket)

**Comment by carlisia** [comment]
@apostoa correct, the prefix/folder won't be created until a first backup for it completes. And the sync is failing because the revision file does not yet exist, since that first backup was not yet created. We need to figure out why your backup is stuck.

Can you please give me the output for `velero backup describe <backupname>`?

**Comment by apostoa** [comment]
@carlisia Yes, i have all the existing backups now "In Progress" state.
The output is here for one of them: https://gist.github.com/apostoa/1ae9ca97b3a13680ef2905bd87090179

The strange thing is that the velero pod restarts when each backup is taken.
I was looking with "kubectl describe pod <velero>" and it shows "OOMKilled" reason even if a lot of memory is allocated (around 800 MB is the limit and the maximum used was 400 MB)

**Comment by carlisia** [comment]
Hi @apostoa sorry, please create a new backup and copy the Velero log. I mainly want to see what happens in between that and the `sync` output you gave me.

**Comment by apostoa** [comment]
@carlisia i have attached here the logs before and after the backup: https://gist.github.com/apostoa/58ecaf187b481f14a79143e74b15d823 

Let me know if i can provide more useful information.

**Comment by apostoa** [comment]
@carlisia Today i made the following steps in order to produce more outcome which i guess could be useful for investigation.
1.  delete the velero release
2. redeploy
3. there were created new backups but two of them with status "Partially Failed" and uploaded into the S3 bucket and the rest of them "In Progress" state
4. The velero pod restarted and it has status "OOMKilled" although it does not consume more than 400 MB and what i've noticed is that when the velero pod restarted the Backup created was with status "In Progress"

**Comment by skriss** [comment]
Could you try increasing the pod's memory request? Looks like you have it at `200Mi`

**Comment by apostoa** [comment]
@skriss @carlisia The memory request increased does not solve the issue. At first backup it gets ```oomkilled``` but it does not hit the memory limit as you can see in the picture attached.

https://gist.github.com/apostoa/ab74faf394d75390f4eee88208008009

![image](https://user-images.githubusercontent.com/35599450/65250623-876b1100-dafe-11e9-9231-a79cb3cbd707.png)

```$ kubectl get backups.velero.io
NAME                                         AGE
velero-testbackup-devstacks-20190919132619   25m
velero-testbackup-devstacks-20190919133651   25m
velero-testbackup-devstacks-20190919134551   16m
velero-testbackup-devstacks-20190919140019   1m```

The first 2 backups are created with status "Partially Failed'' and uploaded to S3 bucket and the next 2 remain "In Progress" state.

**Comment by apostoa** [comment]
@skriss @carlisia any ideea of the issue? :( 

``` Command:
      /velero
    Args:
      server
    State:          Running
      Started:      Fri, 20 Sep 2019 17:31:43 +0300
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Fri, 20 Sep 2019 17:30:07 +0300
      Finished:     Fri, 20 Sep 2019 17:31:42 +0300
    Ready:          True
    Restart Count:  1
    Limits:
      cpu:     1
      memory:  1536Mi
    Requests:
      cpu:        500m
      memory:     800Mi
    Environment:  <none>```

**Comment by skriss** [comment]
Hmm. The next thing I might look at is what other pods are running on the node that the velero pod is scheduled on - I wonder if the node is coming under resource pressure due to other workloads, and the Velero pod is the one that's getting killed. You could also try bumping up the pod priority.

**Comment by skriss** [comment]
OK, that's pretty strange and I'm honestly not sure what's going on. Let me re-review all of the data you've posted and see if I can come up with any other hypotheses. Really not sure why it would be getting OOMkilled if (a) the node isn't overcommitted and (b) the Velero pod isn't reaching its limits.

**Comment by skriss** [comment]
@apostoa were you ever able to make any progress here? the only other thing I can think of doing is removing all limits from the velero pods and seeing if the behavior is any different.

**Comment by skriss** [comment]
Closing this out as inactive - sorry we weren't able to get to the bottom of this! Let us know if there's anything further we can help with.

**Comment by apostoa** [comment]
@skriss sorry not letting you know that finally worked :) It seems that was something related to our cluster (did not found the root cause yet) but using one replica and using separate folders  for each of the environments in testing worked. Thanks again for help!
