### ISSUE TITLE
Add Q&A to FAQ

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#1809]
Opening this issue to collect, review, and periodically update our FAQ page.

**Comment by carlisia** [comment]
Q: We use K8s on prem.  Is it possible to use Velero to backup an on prem K8s cluster to NFS or some other PV we have?

A: Currently Velero can't write the k8s YAML directly to a file system. You'd need an object storage API in front it. Example using Minio:

There is even an example deployment https://github.com/heptio/velero/blob/master/examples/minio/00-minio-deployment.yaml

**Comment by carlisia** [comment]
Q: Does velero _need_ cluster-admin level access?

A: It depends on what you're backing up, but it can't get PVs or any other cluster-scoped objects otherwise

and it needs read access for taking backups, but write access for restores

**Comment by carlisia** [comment]
Q: Can I use Velero to backup that cluster on GKE and then restore those resources on a cluster from a different provider

A: Yes, with some limitations. https://velero.io/docs/v1.3.2/migration-case/ has some details. 

If you have persistent volume data to migrate, you need to use velero’s restic integration to migrate it (https://velero.io/docs/v1.3.2/restic/). Also, if there are any provider-specific configurations (usually around storage/networking), you might have to modify those by hand or write plugins to modify them.

**Comment by a-mccarthy** [comment]
@carlisia do we still want to keep this issue open now that we are using the wiki for the FAQs?

**Comment by carlisia** [comment]
Good point. If all of these FAQs are in the wiki we can close this.

**Comment by a-mccarthy** [comment]
hmm i dont seem them in the wiki page. Are they all still relevant to recent versions? 

I dont appear to have access to edit the wiki :(

**Comment by a-mccarthy** [comment]
@carlisia I've updated the [FAQ general page](https://github.com/vmware-tanzu/velero/wiki/General-FAQ) with these questions. Any future FAQs should be placed in the the Wiki.

Closing this issue :)
