### ISSUE TITLE
Move AWS plugin into its own repo

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#1817]
TODOs:

- [x] build with all dependencies
- [x] build image (https://console.cloud.google.com/gcr/images/heptio-images/GLOBAL/plugin-aws)
- [x] add docs
- [ ] test with a cluster

**Comment by skriss** [comment]
@carlisia should we close this out as resolved and add any follow-ups as issues in https://github.com/vmware-tanzu/velero-plugin-for-aws?

**Comment by carlisia** [comment]
Yes, closing.
