### ISSUE TITLE
Helm chart: better document plugin installation, credentials secret creation

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#1819]

**Comment by skriss** [comment]
So looking at this, there is already a section for adding init containers (i.e. plugin containers) -- see https://github.com/helm/charts/blob/master/stable/velero/values.yaml#L23. We could probably improve the docs, but the functionality is there.

**Comment by carlisia** [comment]
Also, add this bit of documentation: https://github.com/vmware-tanzu/velero/pull/1964/commits/8caa16feb9c60abbc16e30610cff540da40534c1#r337656095

**Comment by skriss** [comment]
@carlisia just checking in to see if you're actively working on this?

**Comment by carlisia** [comment]
Yes

**Comment by skriss** [comment]
ok great, thx!

**Comment by carlisia** [comment]
WIP until Velero v1.2.0 release: https://github.com/helm/charts/pull/18492

**Comment by skriss** [comment]
@carlisia you should be OK to proceed now!

**Comment by skriss** [comment]
Helm PR has merged.
