### ISSUE TITLE
Delay in noticing backup storage location credentials changes

### ISSUE THREAD

**Issue by alexander-demichev** [vmware-tanzu/velero#1824]
When credentials file is kept as secret and secret gets updated, it takes about 2 minutes for velero to notice these changes. Reason for this delay is kubelet sync period + ttl of cache(https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically). This delay causes backups to fail.

My proposed solution is to keep credentials file in a normal volume, because secret volumes are read-only. Then velero can track the secret changes and update credentials file. I prototyped a solution that works for my installation - https://gist.github.com/alexander-demichev/1575abc5a1dd9b2c150f81abab1c477c , code was placed in `pkg/cmd/server/server.go` - https://github.com/fusor/velero/blob/fusor-dev/pkg/cmd/server/server.go#L312 . 

I would like to get some opinions on this, does the concept look ok for improving it and opening a PR?

**Comment by skriss** [comment]
xref #1655

**Comment by eleanor-millman** [comment]
Closing because too much work for the demand we've heard for it.
