### ISSUE TITLE
Add --no-default-storage-location flag to velero install to enable velero deployment without default BSL

### ISSUE THREAD

**Issue by betta1** [vmware-tanzu/velero#1853]
**Describe the problem/challenge you have**
Similar to the --no-secret flag that was added with v1.1.0, it would be great to have an additional cli flag to allow running velero install without specifying a bucket and provider, something like:
 
               velero install --no-default-storage-location --no-secret

This will provide greater flexibility when installing velero for scenarios where a default backup storage location is not necessarily required at deployment time.  

**Describe the solution you'd like**
an additional cli flag --no-default-storage-location:

               velero install --no-default-storage-location --no-secret

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.1.0
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by nrb** [comment]
Thanks Antony!

some high-level thoughts:

* This will require a flag on `velero server` to skip the BSL checks; the flag on `install` would just control whether or not that argument is added.
* The Helm chart will need to expose the `velero server` option

Also, a question:

Currently, the velero pod will crashloop until the first BSL is created, at which point it should successfully start up. Is there currently a problem with that behavior?

**Comment by nrb** [comment]
One thing that is inconsistent in the server's behavior right now is that when a BSL exists and is then deleted, the Velero server doesn't crash.

I think, at the very least, the behavior should be consistent in both the case where the BSL doesn't exist at startup and in the case where the BSL is deleted after the server's running.

I think the crash behavior at startup was largely a way to signal to users that their install wasn't usable until a (valid) BSL existed.

**Comment by betta1** [comment]
> Also, a question:
> 
> Currently, the velero pod will crashloop until the first BSL is created, at which point it should successfully start up. Is there currently a problem with that behavior? 
I don't foresee a problem with this behavior atm -- once the first BSL is created and velero pod starts running, then we should be good to start processing backups. Also to your first bullet point, adding a flag to velero server to skip BSL checks will help with this by ensuring velero server doesn't go into a crashloop when there's no default BSL.

**Comment by nrb** [comment]
I suppose I don't see an issue with the server crashlooping if there's not a BSL, personally, as it is required for Velero to do work.

And I think the server flag is necessary to get the requested behavior - just adding the flag on `velero install` won't do much, since the check for the BSL happens inside the `velero server` process in the pod, not in the `velero install` invocation.

Another question - are you planning on using `velero install` itself, or the `install` package?

**Comment by betta1** [comment]
> And I think the server flag is necessary to get the requested behavior - just adding the flag on `velero install` won't do much, since the check for the BSL happens inside the `velero server` process in the pod, not in the `velero install` invocation.

You're right, in our case we want to utilize the cli to install velero without having to provide the bucket for the default BSL since this bucket doesn't exist yet at velero install time and will only be created after velero deployment.

> Another question - are you planning on using `velero install` itself, or the `install` package?
We're planning on using the velero install itself mostly since it makes versioning easier ... would you recommend the install package instead?

**Comment by skriss** [comment]
We could consider doing the following:
- move the default BSL and BSL validation checks out of server startup, and into the backup process (as pre-validation checks)
- if only one BSL is defined, automatically use that as the default for backups that don't specify it (this means the `--default-backup-storage-location` server flag is not required in this scenario)

This would allow the velero server to start up without any BSLs, but any backups created would end up in the `FailedValidation` phase until a BSL was created.

Additionally, we could look at implementing #1094 and using that to display whether there are valid BSLs in existence.

Thoughts?

**Comment by skriss** [comment]
Huh, I was doing some testing here - Velero doesn't crashloop if there's no BSL or the one specified  in `--default-backup-storage-location` doesn't exist - it just logs a warning and fails validation for backups.

**Comment by betta1** [comment]
You're right, what we observed is the Velero pod goes into crashloop when we provide dummy values for the bucket and provider when running Velero install command. When we delete this dummy default BSL then the pod doesn't crashloop but only logs the error. This works for us as a workaround for now and we'll still like to contribute support to allow running velero install without having to configure a default BSL.
