### ISSUE TITLE
Partially Failed backups are unable to be restored from when using --from-schedule flag

### ISSUE THREAD

**Issue by krisdock** [vmware-tanzu/velero#1858]
**What steps did you take and what happened:**

Scheduled backups are resulting in "Partially Failed" status due to a Pod in Pending status that references a non-existent PVC. They are then unable to restore from that backup. 

**What did you expect to happen:**

To be able to restore from a "partially failed" backup. They expect the object to end up in the same status as it was when backed up (failing to schedule due to non-existent PVC), but not completely block the ability to get an otherwise successful backup that can be restored from.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`

```
apiVersion: velero.io/v1
kind: Backup
metadata:
creationTimestamp: "2019-09-09T13:00:41Z"
generation: 3
labels:
velero.io/schedule-name: periodic-cluster-backup-abhsurek-test-cluster
velero.io/storage-location: default
name: periodic-cluster-backup-abhsurek-test-cluster-20190909130041
namespace: kube-system
resourceVersion: "8878552"
selfLink: /apis/velero.io/v1/namespaces/kube-system/backups/periodic-cluster-backup-abhsurek-test-cluster-20190909130041
uid: d4119b01-d301-11e9-b0c4-fa163ec506c4
spec:
excludedNamespaces: null
excludedResources: null
hooks:
resources: null
includeClusterResources: null
includedNamespaces:
- '*'
includedResources: null
labelSelector: null
storageLocation: default
ttl: 12h0m0s
volumeSnapshotLocations:
- aws-default
status:
completionTimestamp: "2019-09-09T13:00:49Z"
errors: 1
expiration: "2019-09-10T01:00:41Z"
phase: PartiallyFailed
startTimestamp: "2019-09-09T13:00:41Z"
validationErrors: null
version: 1
volumeSnapshotsAttempted: 0
volumeSnapshotsCompleted: 0
warnings: 0
```

The problem resource:

```
Events:
Type Reason Age From Message
---- ------ ---- ---- -------
Warning FailedScheduling 108s (x2629 over 2d17h) default-scheduler persistentvolumeclaim "grafana-data" not found
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 

v1.0.0

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by skriss** [comment]
@krisdock when you say "They are then unable to restore from that backup." -- what's the error/problem when running `velero restore create --from-backup periodic-cluster-backup-abhsurek-test-cluster-20190909130041`?

**Comment by krisdock** [comment]
@skriss 

```
restore status: FailedValidation
err: [No completed backups found for schedule]
```

**Comment by skriss** [comment]
Ah, ok. So it looks like they were using the `--from-schedule` flag for the restore, and I can see that the code for that specifically looks for the most recent backup with a status of "Completed". We can consider changing the logic for that flag, though I'm not yet sure that we want to.

If they run `velero restore create --from-backup abhsurek-test-cluster-20190909130041`, they should be able to restore that specific backup even though it's "PartiallyFailed". Are there issues if they use that form of the command?

**Comment by krisdock** [comment]
@skriss The customer tried with `--from-backup` and that was successful. I think we can safely say this issue is narrowly related to the way the `--from-schedule` flag functions differently than expected by not working with Partially Failed backups the way `--from-backup` does.

**Comment by krisdock** [comment]
One last note:

In the scenario stated (missing PVC with the Pod referencing it in Pending status), the customer would like to confirm that "Partially Failed" is the correct status.

**Comment by skriss** [comment]
> In the scenario stated (missing PVC with the Pod referencing it in Pending status), the customer would like to confirm that "Partially Failed" is the correct status.

As we've defined it, "Partially Failed" is the correct status here -- *any* error trying to back up an item or its related items results in a partial failure. We can have a discussion about whether non-existent referenced items should be warnings in the logs but not "partial failures" -- but as of now, yes, this is the status I'd expect it to end up in.

**Comment by krisdock** [comment]
Thanks for the confirmation on that.

**Comment by krisdock** [comment]
relaying their message regarding the functionality of the `--from-schedule` flag:

```
Also, please tell them that restore from --schedule becomes a useless functionality if it can only restore from Completed backups and not from Partially Failed backups.

If this is the case, why would anyone try to restore from --schedule ??

A person would rather create a "for" loop to manually loop through all the backups, pick up recent backup and then do restore from --backup.
Eventually, restore from --schedule becomes a redundant feature.

I see a serious discrepancy here if restore from --schedule is not allowed to restore from Partially Failed backups, but restore from --backup is.
```

**Comment by skriss** [comment]
Action items:
- clarify in docs
- add flag to `velero restore create --from-schedule`, `--allow-partially-failed`?
- should a reference to a non-existent PVC result in an error?

**Comment by shabx** [comment]
@skriss is there a rough estimate on when this issue will be delivered that we can provide to the customer? They are asking for that.

**Comment by skriss** [comment]
@shabx I think we could get a change for either this issue, or #1878, into v1.2, which is scheduled to come out by ~end of October. We still need to decide on the exact solution here.

**Comment by shabx** [comment]
@skriss wanted to check if we still can implement this for the 1.2 milestone?

**Comment by skriss** [comment]
@shabx we were able to get this into `v1.2.0-beta.1` which was just shipped - specifically, we added an `--allow-partially-failed` flag to `velero restore create` which, if specified when also using `--from-schedule`, will restore the most recent backup from the schedule that's *either* Completed or PartiallyFailed.

If the user has bandwidth to test the beta release, that'd be great; otherwise, keep an eye out for the official `v1.2.0` release in 1-2 weeks.
