### ISSUE TITLE
Adding plugin runtime dependency

### ISSUE THREAD

**Issue by betta1** [vmware-tanzu/velero#1860]
**Describe the problem/challenge you have**
I have an object store plugin that has a dependency on Kerberos runtime libraries, specifically libgssapi-krb5-2. Currently in order to run the plugin I modified the Velero Dockerfile to add this dependency as part of apt-get install, like so:
       
     ‘apt-get install -y --no-install-recommends ca-certificates wget bzip2 libgssapi-krb5-2 && \’ 

 and built a custom image that I use with my Velero deployment. Is it ok to check in this change upstream? I want to be able to make use of velero plugin add <image>  to easily install the plugin without extra configurations.

**Describe the solution you'd like**
Add plugin runtime dependency  to Velero image via apt-get so that I can make use of velero plugin add <image>  to easily install the plugin without extra configurations.

**Anything else you would like to add:**
N/A

**Environment:**

- Velero version (use `velero version`): v1.1.0
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by prydonius** [comment]
We discussed this a bit on Slack: https://kubernetes.slack.com/archives/C6VCGP4MT/p1568057264170700. Ideally we can find a way to make this work without needing to add the library to the Velero image. One potential way is to have plugins run in sidecars instead of copying them over in the init-containers, that way plugin providers can include any necessary dependencies in their images.

cc @skriss @nrb @carlisia

**Comment by skriss** [comment]
@betta1 have you been able to come up with a workaround on this?

**Comment by betta1** [comment]
Yes, our plugin copies the required dependencies to a directory under /plugins and we then set LD_LIBRARY_PATH env var to have the libraries dynamically loaded when the Velero pod starts. I see #1893 added LD_LIBRARY_PATH env var to the deployment, so this will fix the issue (also 1893 provides a generic solution to this so probably the need to shift plugins to sidecars isn't high priority atm ).

**Comment by skriss** [comment]
OK, great. I'll probably close this issue and create a separate one to track the idea of using sidecars for plugin execution.
