### ISSUE TITLE
Restic repository NotReady

### ISSUE THREAD

**Issue by eyalzek** [vmware-tanzu/velero#1863]
We're using velero to backup the cluster, including google cloud NFS volumes created by `nfs-provisioner`. We noticed that in some cases a restic repository is marked as `NotReady` with the message: `repository master key and config already initialized` - I find this rather weird since the repository was already set up and at least one backup was created in the past. Why would `velero` try to initialize the restic repo once again?

This is more of an operational question, is there a way to "reset" the state of the repository within velero and get it to `Ready` again without deleting the contents of the repository within the bucket? I tried deleting only the lock and restarting the velero pod (and all the restic DS pods) but that doesn't seem to have any effect.

Another thing I've noticed is that in some cases the `velero` pod was evicted, can this be the cause of the repositories going into `NotReady` state?

**Comment by skriss** [comment]
@eyalzek what version of Velero are you running (`velero version`)?

It sounds like there's a stale repository lock around, though you indicated you've deleted the lock, so I'm not entirely sure without more detail. We made several improvements to repository lifecycle handing in v1.1 (including stale-lock checking) that may help.

**Comment by eyalzek** [comment]
Running version 0.11.0, will update to latest in the following days. I managed to get the repository to a ready state again by making sure there are no lock in the repository, exporting the repository resource (`resticrepositories.velero.io`), deleting it, then recreating it - this put the repository's state to `new`. After that I triggered a manual backup for resources that utilize that repository and the backup failed - but after some time the state of the repo went back to `Ready`. I'm not sure if that last step was necessary, but I'm honestly not sure what triggers velero's verification of repositories...

**Comment by skriss** [comment]
@eyalzek have you been able to try with a more recent version, i.e. v1.1?

**Comment by eyalzek** [comment]
@skriss we just upgraded a couple of days ago, yesterday I saw a similar behavior one of the repositories going to a `NotReady` state, so that part still happens (not sure why). Though after deleting the lock and recreating the repository (by deleting and recreating the resource with `kubectl`), velero immediately verified the repo and it went back to `Ready`, so that part works better. I'll try to pay attention if this happens again and to figure out the cause of the repository becoming unready.

**Comment by skriss** [comment]
Can you grab the error from the repo when it goes to a NotReady state (`velero restic repo get -o yaml` shold include it)?

**Comment by eyalzek** [comment]
@skriss the error is:
```
error running command=restic snapshots --repo=gs:REPONAME:/restic/REPONAME --password-file=/tmp/velero-restic-credentials-REPONAME --cache-dir=/scratch/.cache/restic --last, stdout=, stderr=Fatal: unable to create lock in backend: repository is already locked exclusively by PID 819 on velero-746d96bfd-wjfg7 by  (UID 0, GID 0)
```

The pod `velero-746d96bfd-wjfg7` was evicted due the memory pressure (the pod was using ~4gb of memory) so the error message makes sense, I guess it got evicted while performing a back up and didn't clean up after itself. I will investigate why the memory usage goes so high in this cluster (we use velero on multiple cluster and this issue happens only there). It seems to be a recurring event:

```
$ kubectl get pods |grep velero | grep Evicted | wc -l
673
```

....

**Comment by skriss** [comment]
Got it, OK, that's helpful. That stale lock *will* be cleaned up eventually by Velero (we added stale lock checking/removal via `restic unlock` in v1.1), but it can take ~30 minutes before restic recognizes it as stale.

We should also look into whether we can have restic gracefully release those locks if a pod is evicted.

**Comment by skriss** [comment]
`restic prune` can definitely use a fair amount of memory, so that makes sense. And yes, it's true that if it never completes successfully, the restic repo size will keep growing which will only increase the amount of mem needed over time for `restic prune`.

It's hard to provide specific recommendations for requests/limits when restic is used, since the needs can vary a lot based on data volumes. I'd suggest trying to capture actual resources used over time and seeing if you can come up with some values based on that.

**Comment by eyalzek** [comment]
I upgraded our kubernetes cluster to 1.14.2, ever since then the velero pods are getting evicted constantly for ephemeral storage. I suppose it's because of the `emptyDir` mount on `/scratch`? What's stored there exactly? I've been bumping the resources requests/limits for it every time and it still gets evicted:
`Pod ephemeral local storage usage exceeds the total limit of containers 1Gi.`

**Comment by skriss** [comment]
Restic uses that for client-side caches; if you have large repositories I could see the usage of that exceeding 1Gi. Unfortunately I don't really have any specific recommendations for how much space you might need there.

**Comment by skriss** [comment]
Closing this out as inactive; feel free to reach out again as needed!

**Comment by eyalzek** [comment]
Just to update, I mounted a PVC for `/scratch` and scheduled velero to an ad-hoc node with ~10gb of memory just to see how it goes. The scratch volume has about ~80gb of data. It took a couple of days for the maintenance of that restic repo to actually go through and even after that, the memory usage of the pod didn't really improve. At this point we're going to stop using restic for backing up NFS volumes because it's just not good enough. I don't even want to know what will happen when I try to restore from one of these backups.....

![image](https://user-images.githubusercontent.com/6243438/67144703-e5b01e80-f279-11e9-8b1c-2e8cfc9a5181.png)
