### ISSUE TITLE
Non-existent items should not cause backup to be PartiallyFailed

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero#1878]
xref #1858 

During a backup, if we have, for example, a pod that references a non-existent PVC, the backup will be `PartiallyFailed` because the PVC doesn't exist.

Arguably, the non-existence of the PVC should not cause the backup to fail. It's not Velero's job to validate the API resources, just to back them up as-is.

**Comment by skriss** [comment]
@prydonius @carlisia interested in your thoughts here -- right now, if a backup item action plugin returns an "additional item" to back up, and then that additional item is found to not exist in the cluster, the backup records an error and results in a `PartiallyFailed` state.

We could change the backup code to check for not-found errors when trying to back up additional items (https://github.com/vmware-tanzu/velero/blob/master/pkg/backup/item_backupper.go#L349-L352), and just log warnings for those scenarios.

Do you think this makes sense? I'm leaning towards yes, but want to get your thoughts.

**Comment by prydonius** [comment]
Do we consider `PartiallyFailed` to be a failed state or a warning state? I'm concerned that a `Completed` status could mislead a user into thinking that their backup, including any associated volumes, were successfully backed up. What if they're not aware that their PVC/PV is missing?

Would a new, less urgent-sounding, state make more sense? For example, `CompletedWithWarnings`? Could `PartiallyFailed` be renamed to something less urgent-sounding (I'm not sure what other scenarios lead to that state).

**Comment by carlisia** [comment]
I agree with @prydonius. It makes me concerned if we could keep running backups of things that were supposed to be there but weren't, then the user didn't know and, oops.

I read the restore issue referenced in the description. How about we add a flag `--allow-partially-failed` that when true would allow velero to continue backing up?

**Comment by skriss** [comment]
It's intended to indicate that the user needs to look at the backup and decide if it's usable or not - so more of a warning than a failure. FWIW, I originally wanted to call it `CompletedWithWarnings` but got overruled :)

In this scenario, though, I really don't see this as an error from the Velero perspective. If a pod references a non-existent PVC, and we back up the pod (including that reference), then not being able to back up a PVC that doesn't exist isn't an error in the backup - we backed up what was there, and there was no volume to back up. It *is* potentially an error in their configuration, but I don't think that's Velero's job to detect?

@carlisia yes #1858 is related too - if we decide that this kind of scenario *should* result in `PartiallyFailed`, then the user wants to be able to restore it using the `--from-schedule` flag, which currently selects the most recent `Completed` backup. We could go at it from that side too - just didn't want to add a new API field if we didn't need to.

**Comment by skriss** [comment]
Sounds like we probably need to have more discussion on this before deciding what to do though - I'll add it to next week's open discussion agenda.

**Comment by skriss** [comment]
Another way we could approach this is rather than doing a blanket ignore of not-found errors when backing up additional items, we could add code to the "add PVC from pod" backup item action that checks if the PVC referred to by the pod actually exists; if it does, return it as an additional item; if not, don't return any additional item to back up.

The benefit of this is that it's more context-aware -- we know that in this specific scenario, a "not-found" error is not actually an error. The downside is we'd have to add logic like this to every plugin that could potentially have this issue (I believe some of the RBAC-related item actions have similar issues).

**Comment by carlisia** [comment]
Yes, discussing this next week will be great 👍

**Comment by cblecker** [comment]
@skriss @carlisia @prydonius Wondering if there was any conclusion to this?

A thought: in the case of a PVC being missing, you're not actually missing any data from the backup -- it literally doesn't exist, so it isn't possible to back it up. So in this case, a `Completed` might be fine. This came up in the case of a platform provider backing up data from the cluster, but without direct control to modify tenant workloads. If a tenant misconfigures their workload with a PVC that isn't defined, then it can fail the cluster-wide backup.

**Comment by skriss** [comment]
@cblecker we did not resolve this, no.

I do personally agree that we should not flag these things as errors in Velero, but I'm not sure we had reached consensus as a team.

This would be a great item to bring up in the open discussion at our [weekly community meeting](https://velero.io/community/), if you're able to join!

If not, let's continue discussing here and see if we can get to a resolution.

**Comment by skriss** [comment]
We discussed this in today's community call and came to a consensus that: 

- non-existent items should not cause a backup to fail or partially fail
- they *should* be logged as warnings, so that there is some visibility around them (the backup CR gets updated with a warning count when the backup completes, and it's displayed in the CLI)
- it'd be nice to have `velero backup describe --details` automatically show warnings, similarly to how `velero restore describe --details` does. This is slightly more complicated than it may sound, because the backends for how backup/restore warnings are stored are different. There's an issue logged to reconcile them (https://github.com/vmware-tanzu/velero/issues/286).

Some implementation notes:
- https://github.com/vmware-tanzu/velero/blob/master/pkg/backup/item_backupper.go#L342-L345 is where we get any additional items returned from plugins from the API.
- I *believe* that what we want to do is add a check for a 404 error there, and if found, log a warning / don't return an error

**Comment by skriss** [comment]
Throwing this into the mix as a relatively small fix for 1.5 consideration

**Comment by skriss** [comment]
@cblecker did you have any interest in working on a fix here?

**Comment by cblecker** [comment]
@skriss I won't have time in the short term to, unfortunately. If there is someone else with cycles, that would be great.

**Comment by skriss** [comment]
OK, no worries. Hope to see you back again as a contributor before too long!
