### ISSUE TITLE
Migrate to go modules

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#1886]
As of Go v1.13, [modules](https://blog.golang.org/go1.13) are the default dependency management tool.

Upstream dependencies like [apimachinery](https://github.com/kubernetes/apimachinery/blob/master/go.mod), [client-go](https://github.com/kubernetes/client-go/blob/master/go.mod), and the [AWS SDK](https://github.com/aws/aws-sdk-go-v2/blob/master/go.mod) have moved.

Velero should adopt go modules as well in order to keep moving forward with the ecosystem.

**Comment by nrb** [comment]
The migration path from `dep` is documented at https://blog.golang.org/migrating-to-go-modules.

**Comment by nrb** [comment]
Vladimir Vivien has also written up a document on migrating for client-go specifically. https://medium.com/programming-kubernetes/using-go-modules-with-kubernetes-api-and-client-go-projects-2f3fdd5589a

**Comment by skriss** [comment]
:+1: if someone has spare time and wants to try out the migration, that'd be great!

**Comment by nrb** [comment]
I'm trying it now :)

Getting hit by https://github.com/kubernetes/kubernetes/issues/79384 and git.apache.org giving 403 at the moment.

**Comment by nrb** [comment]
To fix the apache error, we'll need to add `replace git.apache.org/thrift.git => github.com/apache/thrift v0.0.0-20180902110319-2566ecd5d999` to our eventual go.mod. Apache's moved from their git server to github mirrors.

**Comment by nrb** [comment]
https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-521493597 appears to help in pulling in the various kubernetes components at the appropriate version, but it's unsuccessful on my Fedora machine with v1.15.3. I'm not sure if it's a `sed` issue or not.
