### ISSUE TITLE
Create an upgrade script for updating plugins

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#1889]
See https://github.com/heptio/velero/pull/1870#discussion_r323783953.

**Comment by skriss** [comment]
Related to this, we'll also need instructions for upgrading from v1.1 to v1.2 -- users will need to add the plugins for the first time.

**Comment by skriss** [comment]
I'm going to move this to v1.3 since it won't be an issue until then.

**Comment by eleanor-millman** [comment]
Closing this because plugin changes will take care of this.
