### ISSUE TITLE
Support Schedules for restores

### ISSUE THREAD

**Issue by mshivanna** [vmware-tanzu/velero#1891]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
Currently velero schedules are only for backups. Good to have schedules for restores too.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
One valid use case i can think of is to clone production data and resources to a staging environment for testing. Since we need to have up to date data/resources synced with production schedules for restores will help achieve this goal.

**Comment by skriss** [comment]
Related to this, I would love to see "Schedules" leverage Kubernetes' native `CronJob` - where the CronJob would simply trigger a backup or restore on the specified schedule. I'm not sure if this means the Velero Schedule CRD would go away, or if it would become a lightweight wrapper/controller for the CronJob CRD. Using this approach could make implementing this feature easier.

**Comment by chasebolt** [comment]
Also would :heart: to have this feature. Great way to validate backups by restoring production to staging nightly.

**Comment by panpan0000** [comment]
+1.   with `schedule`  for restore, it would make cross-cluster DR(main/standby cluster ) much more easier.
for example: I could schedule a backup in main cluster,  and schedule restore in standby cluster.
Simple cronjob only is not enough , you would be required to choose one among many backup points.(default latest one). And more over, the schedule restore may also include the spec "override" for standby cluster infrastructure differences.

but anyway, `kasten`  has a feature : “restore after import” option. Aka, we can schedule `import` backup data from another cluster , and then `restore` it automatically.  

In many enterprise use cases, main/standby cluster strategy is popular.  this feature would be  ~loved~.

last but not least, I feel so impressive to find velero, a cloud-native tools and such a small team to make this great achievement.

**Comment by eleanor-millman** [comment]
Closing because not currently a good use case for Velero.
