### ISSUE TITLE
Back up roles/role bindings from other namespaces that relate to a given service account

### ISSUE THREAD

**Issue by fei922** [vmware-tanzu/velero#1902]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
I deployed [k8s service-catalog](https://github.com/kubernetes-sigs/service-catalog) on clusterA. Now I want to backup  service-catalog and restore it to clusterB.

When the restore is complete，service catalog pod's status is CrashLoopBackOff. Because serviceaccount and secrets on cluster A does not have permission to access resources of cluster B.
```
root@master-1:~/velero-v1.1.0# kubectl get po -n public 
NAME                                               READY   STATUS             RESTARTS   AGE
catalog-catalog-apiserver-5fbc5fd76c-6rzg9         1/2     CrashLoopBackOff   365        31h
root@master-1:~/velero-v1.1.0# 
root@master-1:~/velero-v1.1.0# 
root@master-1:~/velero-v1.1.0# 
root@master-1:~/velero-v1.1.0# kubectl logs -f --tail 10 -n public catalog-catalog-apiserver-5fbc5fd76c-6rzg9 -c apiserver
I0924 16:50:14.235256       1 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: service-catalog/v0.1.37 (linux/amd64) kubernetes/c6a2cef" 'https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication'
I0924 16:50:14.242177       1 round_trippers.go:405] GET https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication 403 Forbidden in 6 milliseconds
I0924 16:50:14.242199       1 round_trippers.go:411] Response Headers:
I0924 16:50:14.242203       1 round_trippers.go:414]     Content-Type: application/json
I0924 16:50:14.242206       1 round_trippers.go:414]     X-Content-Type-Options: nosniff
I0924 16:50:14.242209       1 round_trippers.go:414]     Content-Length: 403
I0924 16:50:14.242212       1 round_trippers.go:414]     Date: Tue, 24 Sep 2019 08:50:14 GMT
I0924 16:50:14.242410       1 request.go:942] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps \"extension-apiserver-authentication\" is forbidden: User \"system:serviceaccount:public:service-catalog-apiserver\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\"","reason":"Forbidden","details":{"name":"extension-apiserver-authentication","kind":"configmaps"},"code":403}
W0924 16:50:14.242715       1 authentication.go:246] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLE_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
Error: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:public:service-catalog-apiserver" cannot get resource "configmaps" in API group "" in the namespace "kube-system"

```
**so How to handle backup migration with serviceaccount and secret ？**

**What did you expect to happen:**
When I restore, serviceaccount can become available in cluster b, or is there any other scheme to generate usable serviceaccount in cluster B?

**Environment:**

- Velero version (use `velero version`):  v1.1.0
- Kubernetes version (use `kubectl version`):  v1.13.5

**Comment by skriss** [comment]
@fei922 have you tried restoring the RBAC objects  as well (roles+bindings, clusterroles+bindings)? The ones used by your service account should be backed up automatically when you back up the service account, so you'd just need to ensure they got restored as well.

**Comment by fei922** [comment]
@skriss  The  RBAC objects  used by service account looks like backing up automatically when I back up the service account.  There are RBAC objects in restoring cluster.
```
root@master-1:~/velero-v1.1.0# kubectl get roles.rbac.authorization.k8s.io -n public -l velero.io/backup-name=test-public
NAME                                                      AGE
servicecatalog.k8s.io:cluster-info-configmap              3d15h
servicecatalog.k8s.io:leader-locking-controller-manager   3d15h
root@master-1:~/velero-v1.1.0# 
root@master-1:~/velero-v1.1.0# kubectl get rolebindings.rbac.authorization.k8s.io -n public -l velero.io/backup-name=test-public
NAME                                                 AGE
service-catalog-controller-manager-cluster-info      3d15h
service-catalog-controller-manager-leader-election   3d15h
root@master-1:~/velero-v1.1.0# 
root@master-1:~/velero-v1.1.0# kubectl get clusterroles.rbac.authorization.k8s.io -n public -l velero.io/backup-name=test-public
NAME                                       AGE
servicecatalog.k8s.io:apiserver            3d15h
servicecatalog.k8s.io:controller-manager   3d15h
root@master-1:~/velero-v1.1.0# 
root@master-1:~/velero-v1.1.0# kubectl get clusterrolebindings.rbac.authorization.k8s.io -n public -l velero.io/backup-name=test-public
NAME                                             AGE
servicecatalog.k8s.io:apiserver                  3d15h
servicecatalog.k8s.io:apiserver-auth-delegator   3d15h
servicecatalog.k8s.io:controller-manager         3d15h
```

**Comment by skriss** [comment]
`Error: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:public:service-catalog-apiserver" cannot get resource "configmaps" in API group "" in the namespace "kube-system"`

^^ There must be some missing RBAC that allows your SA to access configmaps in the `kube-system` namespace - can you track down which role that is in your source cluster?

**Comment by fei922** [comment]
@skriss thanks,  I found that the following resource object is missing. 
```
kind: RoleBinding
metadata:
  name: servicecatalog.k8s.io:apiserver-authentication-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: service-catalog-apiserver
  namespace: public
```

**Why is this resource object not backed up together?**

**Comment by skriss** [comment]
Hmm, interesting. So this is a `Role` and `RoleBinding` in a different namespace from the service account. We don't currently have code to pull these in -- we only have code that pulls in related `ClusterRoles`/`ClusterRoleBindings`.

This scenario can get tricky -- on backup, if you specify `--include-namespaces public`, would it be appropriate to pull in roles/rolebindings from another namespace? What about on restore? We'll definitely have to think about this some more.

In the interim, you could: create a second backup that captures these RBAC objects, and restore it alongside your main backup; label all of the objects that you want to back up, and then use a label selector rather than a namespace selector to capture everything; or write a custom backup item action plugin that adds these roles/rolebindings to the backup.

**Comment by fei922** [comment]
Thank you, I will try it.

**Comment by carlisia** [comment]
Hey @fei922, please let us know if the instructions were helpful. For now I'll go ahead and close this ticket, we can always reopen it if the problem persisted.

**Comment by carlisia** [comment]
Ok, reopening because I just noticed the "needs product" label.
