### ISSUE TITLE
Revisit install & configuration UX

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero#1910]
Moved/created all items that we decided to address in the near term into a new Epic here: https://github.com/vmware-tanzu/velero/issues/2419

Issues not part of that effort were left attached to this Epic.

Original post:
---
A number of issues/questions have come up over the past weeks as we've planned for moving the in-tree cloud provider plugins out:

- should plugins be able to be installed as part of `velero install`, or separately?
- should `velero install` support configuring arbitrary BSL/VSL combinations (i.e. any number of each, different providers, etc.)?
- how should `velero install` be aware of env vars that different provider plugins require? (right now we just hardcode the AWS/Azure/GCP ones)
- can we clarify naming -- image, provider, plugin name, etc.?
- there's currently a special case for Azure + restic, where a set of restic-specific env vars need to be set with storage account name and key, which is likely going to remain hardcoded in upstream Velero - how do we deal with situations like this?
- should the velero server be able to start up with no BSLs/VSLs defined? If so, how do we communicate to the user that it's "running" but has no configuration yet?

We need to take a holistic look at the install & configuration experience and think about what we want it to look like. Many of these changes may be breaking.

**Comment by skriss** [comment]
xref #1853

**Comment by nrb** [comment]
Would it perhaps make sense to update the BackupStorageLocation/VolumeSnapshotLocation `Spec.Provider` field to be called `Spec.Plugin`? This would make the connection between the location and the plugin that utilizes its information much more clear.

This doesn't solve the ambiguity that the value in that field is a name within the plugin code and only exposed via documentation, however.

If this is something others would like, I would think we could deprecate `provider` and write `plugin` with `velero install`, then remove `provider` completely in 2.0.

**Comment by skriss** [comment]
xref #1967

**Comment by skriss** [comment]
User feedback from Slack:

"I originally installed it when following docs for 1.1.0, which was straight forward.
before you had examples for aws, gcp, etc, on the guide.
Now the guide is disjointed, and leaves you to guess a few things.
I think at very least the section for ‘Install and configure the server components’, where it says “To install and configure the Velero server components, follow the provider-specific instructions documented by your storage provider.” My version would be broken, bad english with run-ons. lol but would be nice if it said to explicitly say to expect to find the documentation in repo for storage provider plugin of your choice.
Clicking on the “your storage provider” and the ’Providers” page just lists plugins, and links for plugin documentation. But it doesn’t say anything about installation instructions anywhere.
I understand the logic of splitting install instructions per plugin. but finding installation instructions for the whole software on the plugin repo is odd in my opinion. I’d expect to find installation instructions of the plugin itself on its repo, but not instructions on how to install the software with that plugin entirely on the repo.
Actually a good example would be Certbot (certbot.eff.org).  you want to install certbot? okay.. here is the command…..   just plug the name of the dns plugin you need right after this flag…."

**Comment by carlisia** [comment]
I am adding another debugging issue wrt installation that might help us with this reorg:

![image](https://user-images.githubusercontent.com/16508/68793928-cd29ee80-0602-11ea-95e5-3b6de68e7611.png)

One action item here: clarify what plugin to use with on-prem installations

**Comment by nrb** [comment]
>One action item here: clarify what plugin to use with on-prem installations

While I think for the majority of on-prem installations will use the AWS plugin for object storage since Minio and Noobaa implement the S3 API, that's not guaranteed in all cases. Still, saying that is probably better than what we have now.

**Comment by skriss** [comment]
FYI, I converted this issue to an epic and added a bunch of related issues to it. I'm not saying we should tackle each individual issue as written - we need to think holistically about the UX here and come up with a design, then break it out with the right set of sub-tasks.

**Comment by carlisia** [comment]
Can we pick a community meeting to talk (or start talking) about/designing this and maybe put out a CTA for people to join if they are interested in helping with the UX?

**Comment by nrb** [comment]
I'm for that - maybe Dec 3rd, so we get past KubeCon and US Thanksgiving slump?

**Comment by skriss** [comment]
Of course - please add it to the agenda! I do think we should do some more work on this during v1.3 - at a minimum, design.

We could definitely consider splitting out the "install" step vs. the "configure" step -- so `velero install` sets up the namespace, RBAC, deployment, etc., but does not add any external plugins, BSL/VSL definitions, etc., and then separately, have provider-specific steps to configure BSL/VSLs, add plugins, add provider credentials, etc.

If we want to go that route, we'll likely need to:
- allow the velero server to startup without any BSLs defined
- have some clear way to indicate to the user that Velero is not yet usable until a BSL/plugin is configured
- add BSL/VSL controllers that watch for and validate new BSL/VSLs as they're created
- decide out how to add provider credentials (i.e. the `cloud-credentials` secret) and env vars to the Velero deployment/daemonset after they've already been created
- etc..

Just throwing this out there as food for thought. We can pick this up more deliberately in the coming weeks.

**Comment by nrb** [comment]
Another proposal - what if we put out some binaries with these changes to solitic feedback? I'm not sure they'd be alphas, but I would like to iterate on these changes with artifacts before an actual release. What do others think of that?

**Comment by skriss** [comment]
yeah, would definitely be good to find some users who can help alpha-test the changes

**Comment by carlisia** [comment]
Ref: https://github.com/vmware-tanzu/velero/issues/2152#issuecomment-567146761

**Comment by carlisia** [comment]
Note: a good case for `s/configure/install`: https://github.com/vmware-tanzu/velero/pull/2155/files#diff-31224e312bb639f88a40a97daf5f2d40R40

**Comment by carlisia** [comment]
Maybe related: https://github.com/vmware-tanzu/velero/issues/1027#issuecomment-572201120

**Comment by ashish-amarnath** [comment]
@carlisia are you suggesting we have have a separate `velero configure` command, different from `velero install`?
If you are not, I would like to suggest that! :)

**Comment by carlisia** [comment]
Haha. Yes I am! Thanks for the input, seems to make sense.

**Comment by carlisia** [comment]
Related (status cmd): https://github.com/vmware-tanzu/velero/issues/1094

**Comment by carlisia** [comment]
These issues mentioned in this PR have been moved to their own ticket:

Velero location plugins and env variables: https://github.com/vmware-tanzu/velero/issues/2402

Enable plugins to pass environment variables required by restic: https://github.com/vmware-tanzu/velero/issues/2386

**Comment by skriss** [comment]
@carlisia I think this umbrella issue can probably be closed out now, as all of the relevant work has been opened in separate issues and you have another epic that tracks that work. Do you agree?

**Comment by carlisia** [comment]
Yes! Closing.
