### ISSUE TITLE
Migrate from GCR to DockerHub

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#1912]
The `velero` organization exists now, but we'll need to get the image names redefined in our Makefile.

Additionally, it _may_ make sense to push to both GCR and DockerHub for some amount of time, but preferably that would be on the order of a month or so.

**Comment by nrb** [comment]
In terms of ordering, this can be done after the GitHub org move, but before splitting out plugins.

**Comment by skriss** [comment]
So we'll have `velero/velero`, `velero/velero-restic-restore-helper`, and `velero/fsfreeze-pause`, right?

**Comment by nrb** [comment]
That's my understanding, yes. Then the 3 sets of plugins for AWS, GCP, and Azure. And possibly `velero/velero-builder`, if we want that.

**Comment by skriss** [comment]
We could consider manually pushing up a `v1.0` and `v1.1` tag there if we wanted, too.

**Comment by nrb** [comment]
I think that's a good idea. The furthest back I would advocate going would be `v0.11`, so that users that may still be running Ark will have a way forward.

**Comment by skriss** [comment]
@prydonius I'm moving this into the current release and assigning you. I'd like to have v1.2, along with the new plugin images, be published on docker hub. We've also talked about keeping the existing GCR images up for now. I'm not sure yet whether we want to push v1.2 up there as well, or if we just want to leave the existing images around for now for posterity - open to input.

**Comment by prydonius** [comment]
@skriss sounds good, thanks. It would be pretty trivial to repush all the existing tags to Docker Hub. That said, our old releases hardcode the existing GCR images, so we'd presumably need to keep it around for some time.

**Comment by prydonius** [comment]
From the discussion this morning:

- we'll stop pushing new images to GCR
- we'll manually push v1.0.0+ tags to Docker Hub

**Comment by skriss** [comment]
Also: the existing GCR bucket will stay around indefinitely, so no big concerns there.

**Comment by prydonius** [comment]
TODO:
- [ ] update Travis to push to Docker Hub instead of GCR (#1966)
- [ ] manually push v1.0, v1.1 and latest up to Docker Hub
- [ ] update references to gcr.io/heptio-images -> velero/

**Comment by skriss** [comment]
Just wanted to make sure the plugin repos are on your radar too? the AWS one should be ready to be set up, with GCP and Azure to follow soon (cc @carlisia for timing).

**Comment by prydonius** [comment]
@skriss thanks for the reminder, added to the TODO list

**Comment by skriss** [comment]
alright, got successful `master` image pushes for all 3 plugins!

**Comment by skriss** [comment]
@prydonius just checking to see if you're able to tackle the remaining items on the TODO list in the next day or so, or if you'd like me to help out here

**Comment by prydonius** [comment]
@skriss yep sorry, I'll circle back to this tomorrow, should be fairly quick changes!

**Comment by prydonius** [comment]
I've manually pushed v1.0.0, v1.1.0 and latest for velero/velero, velero/fsfreeze-pause and velero/velero-restic-restore-helper.

**Comment by skriss** [comment]
I added #1989 for removing the GCR push artifacts down the road, so we can consider this issue closed once #1988 merges.

**Comment by prydonius** [comment]
@skriss sgtm, I'm okay keeping the push key and script in the repo until we're sure we want to remove it.
