### ISSUE TITLE
Add ability to specify order of backup and restore of Persistent Volumes

### ISSUE THREAD

**Issue by yashbhutwala** [vmware-tanzu/velero#1917]
**Describe the problem/challenge you have**
I would like to be able to specify the order of backup and restore of Persistent Volumes.  For my use-case, the order in which the state of two different databases is captured is very important.

**Comment by nrb** [comment]
This would be an interesting capability to add, but would like input for @VMmore on roadmap timing.

**Comment by yashbhutwala** [comment]
The workaround I'm doing now, is creating a separate backup with 1st level of PVs, and a separate backup for the second step.  And then applying the restore in reverse order.

**Comment by nrb** [comment]
@phuongatemc Does your ordering enhancement fix this issue?

**Comment by phuongatemc** [comment]
@nrb Yes, the Velero 1.5.1 work for for us.

**Comment by nrb** [comment]
@yashbhutwala See https://github.com/vmware-tanzu/velero/pull/2724 for how to specify an ordering for resources on backup now. This is not yet supported on restore, though.
