### ISSUE TITLE
Make explicit the diff between backup describe and restore describe

### ISSUE THREAD

**Issue by yashbhutwala** [vmware-tanzu/velero#1918]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]

There is a diff between namespaces included as well as resources excluded in `backup describe` and `restore describe` that makes it unclear to the user.  It'd be nice to add some notes in the restore to make it explicit that some resources are exclueded by default in restore. 3 of these are Velero resources - backups, restores, and resticrepositories.  Also, add a message to `included namespaces` in restore.

Result of backup describe
```
Name:         yb-backup-0
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  Completed

Namespaces:
  Included:  yb-onprem
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-09-27 11:32:35 -0400 EDT
Completed:  2019-09-27 11:32:50 -0400 EDT

Expiration:  2019-10-27 11:32:35 -0400 EDT

Persistent Volumes: <none included>

Restic Backups:
  Completed:
    yb-backup/postgresql-675cc47d87-brx5t: postgresdb
```

Result of restore describe:
```
Name:         yb-backup-0-20190927114106
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:  InProgress

Backup:  yb-backup-0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Restic Restores:
  New:
    yb/postgresql-675cc47d87-brx5t: postgresdb
```

**Comment by nrb** [comment]
There's a subtle difference between the field on a backup and a restore.

On a backup, `Included Namespaces: *` means "back up all namespaces found in the cluster."

On a restore, `Included Namespaces: *` means "restore all namespaces found in the backup."

I think clarifying the wording on the restore description to be something like "All namespaces found in backup" or something may help reduce confusion versus using `*`.

**Comment by eleanor-millman** [comment]
Closing because it appears done.
