### ISSUE TITLE
Make backup/restore logs more user-friendly

### ISSUE THREAD

**Issue by mqsoh** [vmware-tanzu/velero#1928]
**Describe the problem/challenge you have**
I just want to share some frustration I just had with a failed cluster migration. The restore information looks like this:

```
NAME                                 BACKUP                STATUS            WARNINGS   ERRORS   CREATED                         SELECTOR
influxdb-migration2-20191002133625   influxdb-migration2   PartiallyFailed   4          1        2019-10-02 13:36:25 +0000 UTC   <none>
```

4 warnings and 1 error but every line has `level=info` and there are literally no lines with the words "warn" or "error".

```
$ velero restore logs influxdb-migration2-20191002133625 | grep -i warn
1 $ velero restore logs influxdb-migration2-20191002133625 | grep -i error
1 $
```

Every line has redundant and unhelpful information, i.e. `logSource` (I don't know your code.) and `restore` (literally the thing I'm looking at). I tried a stupid sed to reduce it to the information I needed (`sed 's/time="//; s/" level=info msg="/ /; s/" logSource=.\+//'`) which works for most lines but not all.

In this specific case I'm missing one volume among 6. I have pairs like "attempting to restore"/"successfully restored" for 5 of them but the 6 just isn't mentioned until later when it says the PV is already there (but it's not?).

**Describe the solution you'd like**
My own application logs look like this. I know what they mean; each entry in the log refers to a specific code path and I can dig through the code and spot bugs pretty quickly. When I open a bug report for my actual issue, I'm sure you'll be able to do the same.

I think there should be logs tailored for the end user. Non-structured messages that describe the state as the program currently sees it, the changes that it thinks it needs, and the words "error" and "warning" *in* those types of messages.

**Anything else you would like to add:**
If one of my coworkers wasn't out of town, I think they would see the problem immediately. I'm not very good at anything, so maybe take it with a grain of salt.

Also, I'm not asking for help with my issue. I'll make a ticket once I feel I've done my due dilligence. I'm making a suggestion about the friendliness of the logs.

**Environment:**

- Velero version (use `velero version`): 1.0.0
- Kubernetes version (use `kubectl version`): 1.12.9
- Kubernetes installer & version: migrating from 1.11.x to 1.12.x
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): ubuntu 18.04

**Comment by eleanor-millman** [comment]
Closing because we are doing this incrementally.
