### ISSUE TITLE
Update to community page

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#1933]
Update community page to contain up to date community meeting information and add a link to the ongoing HackMD dock.

**Comment by jonasrosland** [comment]
Should I include the move of all meeting notes and links to content from `velero-community` as well?

**Comment by carlisia** [comment]
Let's not link to that repo at all please.

**Comment by skriss** [comment]
I'd be fine either clearing the slate on old meeting notes/links/etc, or moving those into the consolidated HackMD for posterity -- not sure what others think. cc @nrb @prydonius

**Comment by skriss** [comment]
Then going fwd all notes & recording links can just go into the HackMD, so we don't need to constantly be updating the website.

**Comment by carlisia** [comment]
I don't think it's worth moving them, but I'm not against it.

**Comment by skriss** [comment]
Yeah, same - I'm totally fine just dropping them if everyone else is.

**Comment by carlisia** [comment]
Yes, as as long as we keep adding the community recordings to our playlist, it will show up on the website in the embedded YT thingy.

**Comment by jonasrosland** [comment]
The point of having the meeting notes is that they're searchable because they're text. Videos aren't as searchable (yet).

**Comment by nrb** [comment]
I agree with Jonas - the point was to have a searchable reference that didn't require skipping around a video to find information. If we're considering deleting the past notes, then I question the value of taking them at all.

My preference would be to have them live somewhere new, not completely lost.

**Comment by skriss** [comment]
So migrate them into the HackMD?

**Comment by nrb** [comment]
Yeah, moving them to the HackMD accomplishes the archiving and also means we don't have to update the site every week.

**Comment by skriss** [comment]
WFM
