### ISSUE TITLE
Error backing up a serviceaccount resource

### ISSUE THREAD

**Issue by echel0n** [vmware-tanzu/velero#1940]
Below is the following error I get every time I perform a backup.

Backup Error:
```
time="2019-10-06T07:02:11Z" level=info msg="Backing up item" backup=velero/backup-2019-10-06-0000 group=v1 logSource="pkg/backup/item_backupper.go:162" name=rook-ceph-osd namespace=rook-ceph resource=serviceaccounts
time="2019-10-06T07:02:11Z" level=info msg="Executing custom action" backup=velero/backup-2019-10-06-0000 group=v1 logSource="pkg/backup/item_backupper.go:310" name=rook-ceph-osd namespace=rook-ceph resource=serviceaccounts
time="2019-10-06T07:02:11Z" level=info msg="Adding clusterrole rook-ceph-osd and clusterrolebinding rook-ceph-osd to additionalItems since serviceaccount rook-ceph/rook-ceph-osd is a subject" backup=velero/backup-2019-10-06-0000 cmd=/velero logSource="pkg/backup/service_account_action.go:95" pluginName=velero
time="2019-10-06T07:02:11Z" level=info msg="Backing up item" backup=velero/backup-2019-10-06-0000 group=v1 logSource="pkg/backup/item_backupper.go:162" name=rook-ceph-osd namespace=rook-ceph resource=serviceaccounts
time="2019-10-06T07:02:11Z" level=info msg="1 errors encountered backup up item" backup=velero/backup-2019-10-06-0000 group=v1 logSource="pkg/backup/resource_backupper.go:260" name=rook-ceph-osd namespace= resource=serviceaccounts
time="2019-10-06T07:02:11Z" level=error msg="Error backing up item" backup=velero/backup-2019-10-06-0000 error="clusterroles.rbac.authorization.k8s.io \"rook-ceph-osd\" not found" error.file="/go/src/github.com/heptio/velero/pkg/backup/item_backupper.go:331" error.function="github.com/heptio/velero/pkg/backup.(*defaultItemBackupper).executeActions" group=v1 logSource="pkg/backup/resource_backupper.go:264" name=rook-ceph-osd namespace= resource=serviceaccounts
```

**Environment:**

- Velero version: 
Client:
        Version: v1.1.0
        Git commit: a357f21aec6b39a8244dd23e469cc4519f1fe608
Server:
        Version: v1.1.0

- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by skriss** [comment]
It seems like your service account `rook-ceph/rook-ceph-osd` is a subject in a clusterrolebinding (`rook-ceph-osd`) that refers to a nonexistent clusterrole (`rook-ceph-osd`).

Can you confirm that's the case? If so, removing the clusterrolebinding to this nonexistent cluster role should make the error go away.

We also have #1878 to change Velero's behavior when nonexistent related items are found.

**Comment by echel0n** [comment]
The clusterrole `rook-ceph-osd` does actually exist

**Comment by skriss** [comment]
huh, that's strange. Could you provide the YAML for the `rook-ceph-osd` cluster role and cluster role binding?

**Comment by skriss** [comment]
Pinging to see if you can provide the YAML

**Comment by echel0n** [comment]
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2019-10-14T07:05:38Z"
  name: rook-ceph-osd
  resourceVersion: "97355248"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/rook-ceph-osd
  uid: a818ced8-8938-484f-991c-089fdfd9f723
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2019-09-13T13:26:47Z"
  name: rook-ceph-osd
  resourceVersion: "75816160"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/rook-ceph-osd
  uid: 17671411-79c2-4ab7-9c40-911967d1dbfe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-osd
subjects:
- kind: ServiceAccount
  name: rook-ceph-osd
  namespace: rook-ceph
```

**Comment by echel0n** [comment]
FYI oddly enough this issue seems to have resolved it self or at least is no longer happening for now, backups are completing successfully, not sure what changed.

**Comment by skriss** [comment]
Hmm, odd. The only suspicious thing I see is that in the YAML you provided, the ClusterRole has a creationTimstamp of October 14 (after you originally reported the issue), whereas the CRB is from Sept 13. Otherwise, everything looks fine.

I'm going to close this issue out but please reopen if it appears again!
