### ISSUE TITLE
Release schedule 

### ISSUE THREAD

**Issue by jweldonca** [vmware-tanzu/velero#1941]
**Describe the problem/challenge you have**
Is there a release roadmap or sometime when we can expect the next release?

**Describe the solution you'd like** 
A Release plan or new version released soon.

**Comment by skriss** [comment]
@jweldonca we're currently planning to release `v1.2` around the end of October. We try to ship a new release every 2-3 months, but we're not strictly date-driven. You can take a look at our [ZenHub board](https://app.zenhub.com/workspaces/velero-5c59c15e39d47b774b5864e3/board?repos=99143276,112385197,150626909) to see what our backlog looks like. Hope that helps!

**Comment by jweldonca** [comment]
@skriss that is great thanks, do you release betas any sooner?

**Comment by skriss** [comment]
We generally do, yes, as soon as we're feature-complete. Keep an eye out in slack/this repo for announcements.
