### ISSUE TITLE
Velero backup fails on Openshift due to trying to back up API group that fails to be discovered

### ISSUE THREAD

**Issue by ashoks27** [vmware-tanzu/velero#1943]
**What steps did you take and what happened:**
I have tried to take a entire cluster backup of openshift cluster and it fails with below error. Is there any specific Service broker ,  need to be installed. Please advise.

[root@XXXX etc]# velero backup logs backup1 |grep -i error
time="2019-10-07T12:12:07Z" level=warning msg="Failed to discover group: servicecatalog.k8s.io/v1beta1" backup=velero/backup1 cmd=/velero error="the server is currently unable to handle the request" logSource="pkg/discovery/helper.go:154" pluginName=velero
time="2019-10-07T12:12:19Z" level=error msg="Error listing items" backup=velero/backup1 error="the server is currently unable to handle the request" error.file="/go/src/github.com/heptio/velero/pkg/backup/resource_backupper.go:227" error.function="github.com/heptio/velero/pkg/backup.(*defaultResourceBackupper).backupResource" group=servicecatalog.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:227" namespace= resource=serviceclasses
time="2019-10-07T12:12:19Z" level=error msg="Error listing items" backup=velero/backup1 error="the server is currently unable to handle the request" error.file="/go/src/github.com/heptio/velero/pkg/backup/resource_backupper.go:227" error.function="github.com/heptio/velero/pkg/backup.(*defaultResourceBackupper).backupResource" group=servicecatalog.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:227" namespace= resource=serviceinstances
time="2019-10-07T12:12:19Z" level=error msg="Error listing items" backup=velero/backup1 error="the server is currently unable to handle the request" error.file="/go/src/github.com/heptio/velero/pkg/backup/resource_backupper.go:227" error.function="github.com/heptio/velero/pkg/backup.(*defaultResourceBackupper).backupResource" group=servicecatalog.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:227" namespace= resource=clusterservicebrokers
time="2019-10-07T12:12:19Z" level=error msg="Error listing items" backup=velero/backup1 error="the server is currently unable to handle the request" error.file="/go/src/github.com/heptio/velero/pkg/backup/resource_backupper.go:227" error.function="github.com/heptio/velero/pkg/backup.(*defaultResourceBackupper).backupResource" group=servicecatalog.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:227" namespace= resource=serviceplans
time="2019-10-07T12:12:19Z" level=error msg="Error listing items" backup=velero/backup1 error="the server is currently unable to handle the request" error.file="/go/src/github.com/heptio/velero/pkg/backup/resource_backupper.go:227" error.function="github.com/heptio/velero/pkg/backup.(*defaultResourceBackupper).backupResource" group=servicecatalog.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:227" namespace= resource=servicebindings
time="2019-10-07T12:12:19Z" level=error msg="Error listing items" backup=velero/backup1 error="the server is currently unable to handle the request" error.file="/go/src/github.com/heptio/velero/pkg/backup/resource_backupper.go:227" error.function="github.com/heptio/velero/pkg/backup.(*defaultResourceBackupper).backupResource" group=servicecatalog.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:227" namespace= resource=servicebrokers
time="2019-10-07T12:12:19Z" level=error msg="Error listing items" backup=velero/backup1 error="the server is currently unable to handle the request" error.file="/go/src/github.com/heptio/velero/pkg/backup/resource_backupper.go:227" error.function="github.com/heptio/velero/pkg/backup.(*defaultResourceBackupper).backupResource" group=servicecatalog.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:227" namespace= resource=clusterserviceclasses
time="2019-10-07T12:12:19Z" level=error msg="Error listing items" backup=velero/backup1 error="the server is currently unable to handle the request" error.file="/go/src/github.com/heptio/velero/pkg/backup/resource_backupper.go:227" error.function="github.com/heptio/velero/pkg/backup.(*defaultResourceBackupper).backupResource" group=servicecatalog.k8s.io/v1beta1 logSource="pkg/backup/resource_backupper.go:227" namespace= resource=clusterserviceplans

**What did you expect to happen:**
Error less backup completion.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`

* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`

[root@XXXX etc]# velero describe backup backup1
Name:         backup1
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  PartiallyFailed (run `velero backup logs backup1` for more information)

Errors:    8
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-10-07 08:12:06 -0400 EDT
Completed:  2019-10-07 08:12:19 -0400 EDT

Expiration:  2019-11-06 07:12:06 -0500 EST

Persistent Volumes: <none included>

* `velero backup logs <backupname>`

* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**

Backup for any specific namespace is completing without any error , but its failing when backup is initiating for entire cluster.

**Environment:**

- Velero version (use `velero version`): Version 1.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 
- Kubernetes installer & version: Openshift
[velero_backup_logs.txt](https://github.com/vmware-tanzu/velero/files/3698147/velero_backup_logs.txt)

- Cloud provider or hardware configuration: 
- OS (e.g. from `/etc/os-release`): Redhat 7.4

**Comment by skriss** [comment]
Hmm, that's odd. It looks like the `servicecatalog.k8s.io/v1beta1` API group is installed in the cluster, but perhaps the extension API server is not available to service requests to it. In that case, the API group *should* be getting ignored while taking backups, but it appears that's not the case.

Do you know why the API group is installed, but not responding to requests?

**Comment by skriss** [comment]
@ashoks27 just checking to see if you need any more help here.

**Comment by ashoks27** [comment]
Hi Steve, Thanks for the followup here. I am yet to work on this issue , please close this , I will reopen if I need any further help.

OnceAgain thanks for your support.
