### ISSUE TITLE
Feature: disable use of presigned urls.

### ISSUE THREAD

**Issue by ajohnstone** [vmware-tanzu/velero#1945]
**Describe the problem/challenge you have**
Presigned URLs are used in a number of places throughout the Velero codebase. Presigned URLs are explicitly forbidden from use at my place of work and flagged within compliance controls and remediated.

**Describe the solution you'd like**
Support not using pre-signed urls, in this case aws.

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`):

**Comment by nrb** [comment]
Hi @ajohnstone, can you provide a source for this? Where are they forbidden?

**Comment by ajohnstone** [comment]
Presigned URLs are explicitly forbidden from use at my place of work and flagged within compliance controls and remediated. The reason for this is due to exfiltration. Hope this makes a bit more sense.

These are used in:

* velero backup logs
* velero restore logs
* etc


A sample policy for s3 denying pre-signed urls.
```
{
   "Version": "2012-10-17",
   "Statement": [
         {
               "Sid": "Allow only requests that use Authorization header for request authentication. Deny POST or presigned URL requests.",
               "Effect": "Deny",
               "Principal": "*",
               "Action": "s3:*",
               "Resource": "arn:aws:s3:::examplebucket3/*",
               "Condition": {
                     "StringNotEquals": {
                           "s3:x-amz-content-sha256": "UNSIGNED-PAYLOAD"
                     }
               }
         },

         {
               "Sid": "Allow only requests that use Authorization header for request authentication. Deny POST or presigned URL requests.",
               "Effect": "Deny",
               "Principal": "*",
               "Action": "s3:*",
               "Resource": "arn:aws:s3:::examplebucket3/*",
               "Condition": {
                     "StringNotEquals": {
                           "s3:authType": "REST-HEADER"
                     }
               }
         }
   ]
}
```

**Comment by skriss** [comment]
@ajohnstone it's possible to disable the download request controller, which is the one that provisions pre-signed URLS, using the `--disable-controllers=download-request` flag to `velero server` (the command that the Velero deployment runs).  To be clear, disabling this controller means that `velero backup/restore logs`, `velero backup download`, etc. will not work.

Does this meet your need, or are you suggesting something else?

**Comment by skriss** [comment]
@ajohnstone does the approach in the previous comment work for you?

**Comment by skriss** [comment]
Closing this out as inactive/we've provided a possible solution, feel free to reach out again as needed.
