### ISSUE TITLE
Feature: `velero restore` - support excluding resources and resource items with a label and/or regex.

### ISSUE THREAD

**Issue by ajohnstone** [vmware-tanzu/velero#1946]
**Describe the problem/challenge you have**
Support excluding resources and resource items with a label and/or regex          `

**Describe the solution you'd like**
Whilst you can use a label selector to include resources, there is no way to exclude specific resources.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.1.0
- Kubernetes version (use `kubectl version`): 
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
@ajohnstone you can use the `notin` syntax to achieve this - i.e. `velero restore create --selector 'backup notin (ignore)'`. See https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement for more details on this.

Does this meet your need?

**Comment by ajohnstone** [comment]
Yes, wasn’t aware it supported this, perfect :)
