### ISSUE TITLE
Pods attempted to be blindly restored.

### ISSUE THREAD

**Issue by ajohnstone** [vmware-tanzu/velero#1949]
**What steps did you take and what happened:**
Deployments -> ReplicaSet -> pods

Pods are attempting to be restored that are created as part of a deployment. Deployment -> ReplicaSets. As such they should not be restored.

Pods that are created stand alone MUST be backed up and restored.

schedules/jobs should again with related pods should not be restored.

**What did you expect to happen:**

 Pods from a ReplicaSet MUST not be restored.

Pods that are created stand alone MUST be backed up and restored.

schedules/jobs should again with related pods MUST not be restored.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.1.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by prydonius** [comment]
Hi @ajohnstone, is there any particular reason you think that the Pods owned by another workload kind should not be restored? It is safe to restore these Pods, the ReplicaSet controller will adopt them correctly on restore.

**Comment by skriss** [comment]
@ajohnstone could you provide some more information here per https://github.com/vmware-tanzu/velero/issues/1949#issuecomment-539643580?

**Comment by skriss** [comment]
Closing this out as inactive, feel free to reach out again as needed.
