### ISSUE TITLE
Restoring the same service with a nodeport errors with ‘“istio-ingressgateway” is invalid: spec.ports[0].nodePort: Invalid value: 30001: provided port is already allocated’

### ISSUE THREAD

**Issue by ajohnstone** [vmware-tanzu/velero#1950]
**What steps did you take and what happened:**
Restoring the same service with a nodeport errors with ‘“istio-ingressgateway” is invalid: spec.ports[0].nodePort: Invalid value: 30001: provided port is already allocated’

**What did you expect to happen:**
Same object being applied should not fail. 
Currently flags in results as an error.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.1.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by prydonius** [comment]
Hmm, I wasn't able to reproduce this for a Service with a NodePort using the nginx example in this repository. Can you provide the steps you took so I can try to reproduce.

**Comment by skriss** [comment]
@ajohnstone looks like we're waiting for more info here to be able to reproduce.

**Comment by skriss** [comment]
Closing as inactive, feel free to reach out again as needed.

**Comment by jenting** [comment]
I could reproduce this issue with the following steps:

1. Backup a cluster with [dex](https://github.com/dexidp/dex/blob/master/examples/k8s/dex.yaml) installed
2. Create a new cluster and deploy [dex](https://github.com/dexidp/dex/blob/master/examples/k8s/dex.yaml) manually
3. Restore the cluster from the backup

Then, restore with the error log
```
error restoring dex: Service \"dex\" is invalid: spec.ports[0].nodePort: Invalid value: 32000: provided port is already allocated
```
