### ISSUE TITLE
Velero_POD_AKS_not running _CrashLoopBackOff error  

### ISSUE THREAD

**Issue by sarinbarnabas** [vmware-tanzu/velero#1958]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

**What did you expect to happen:**
Planning to use Velero as a backup solution for AKS persistent volumes . But getting error when trying to install Velero using the below command.

velero install \
    --provider azure \
    --bucket $BLOB_CONTAINER \
    --secret-file ./credentials-velero \
    --backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID[,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID] \
    --snapshot-location-config apiTimeout="30"[,resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID]

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
Output:

An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = config has invalid keys [subscriptionId]; valid keys are [resourceGroup storageAccount bucket prefix]

* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): velero version
Client:
        Version: v1.1.0
        Git commit: a357f21aec6b39a8244dd23e469cc4519f1fe608
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Azure (AKS)
- OS (e.g. from `/etc/os-release`): (Linux/Ubuntu)

**Comment by skriss** [comment]
@sarinbarnabas it looks like you're following the wrong version of the documentation. Since you're installing velero v1.1, please use the v1.1-tagged docs here: https://velero.io/docs/v1.1.0/azure-config/.

In particular, velero v1.1 does not support specifying `subscriptionId` in the backup location config or snapshot location config. That will be coming out in v1.2.
