### ISSUE TITLE
Velero debugging documentation missing: https://velero.io/docs/master/debugging-install/0

### ISSUE THREAD

**Issue by archmangler** [vmware-tanzu/velero#1960]
**What steps did you take and what happened:**

Tried to access velero debugging instructions for azure: 

https://velero.io/docs/master/debugging-install/0

**What did you expect to happen:**

The documentation should ideally be there.

**The output of the following commands will help us better understand what's going on**:

https://velero.io/docs/master/debugging-install/0

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

n/a

**Comment by skriss** [comment]
Where did you get this link from? The correct link is `https://velero.io/docs/master/debugging-install/` but I'm not finding the `/0` anywhere..

**Comment by archmangler** [comment]
Hi, pictured below:

![image](https://user-images.githubusercontent.com/3898404/66758735-77620980-eed1-11e9-881d-1c3fbc59e6ff.png)

**Comment by skriss** [comment]
Got it, thanks.

**Comment by skriss** [comment]
cc @carlisia let's try to fix these broken links as part of docs cleanup once we extract the Azure code.

**Comment by skriss** [comment]
Actually, I'll just fix these now, and we can update them when we sweep for all links to `azure-config.md`.

**Comment by archmangler** [comment]
Hi, in the meantime, is that piece of documentation available at all ?

**Comment by skriss** [comment]
Yes - that link should point to https://velero.io/docs/master/azure-config/

**Comment by carlisia** [comment]
Copy that.
