### ISSUE TITLE
Unparsable error with custom restic helper image with extra ":"  in name (registry port)

### ISSUE THREAD

**Issue by cognoz** [vmware-tanzu/velero#1972]
**What steps did you take and what happened:**
I created configmap in velero namespace from this page https://velero.io/docs/master/restic/
as image in data.image I use 
```yaml
data:
  image: nexus-registry.domain.domain:18116/heptio-images/velero-restic-restore-helper:v1.1.0
```
(Image was pushed to this registry)

After creating restore, I see these messages in log:
> level=warning msg="Plugin config contains unparseable image name" cmd=/velero image="nexus-registry.domain.domain:18116/heptio-images/velero-restic-restore-helper:v1.1.0" logSource="pkg/restore/restic_restore_action.go:171" pluginName=velero pod=test-velero/coffee-679f7c7698-r7rvr restore=velero/velero-restore-6
time="2019-10-17T07:50:24Z" level=info msg="Using image \"gcr.io/heptio-images/velero-restic-restore-helper:v1.1.0\"" cmd=/velero logSource="pkg/restore/restic_restore_action.go:105" pluginName=velero pod=test-velero/coffee-679f7c7698-r7rvr restore=velero/velero-restore-6

So, my custom image from private registry is not used during restore (I believe it has to do with extra ':' for port definition in the image name)

**What did you expect to happen:**
Image name was parsed correctly

**Environment:**
- Velero version (use `velero version`):
v1.1.0 
- Kubernetes version (use `kubectl version`):
v1.11.0+d4cacc0

**Comment by skriss** [comment]
Yep, looks like you're right, the code doesn't work properly when a custom port is used.

Do you have any interest in contributing a fix here?

**Comment by cognoz** [comment]
> Yep, looks like you're right, the code doesn't work properly when a custom port is used.
> 
> Do you have any interest in contributing a fix here?

Definitely yes but I'm not experienced in GO, really  
So. it can be a mess)

**Comment by Panplumousse** [comment]
Hello 

i have exactly the same issu.
In my case it isn't possible to connect my node to internet
i need to use internal registry with port 

thx a lot for help

**Comment by cognoz** [comment]
@skriss can U help me with build?) 
https://travis-ci.org/vmware-tanzu/velero/builds/602756623?utm_source=github_status&utm_medium=notification

If I ran 'make test' locally, nothing happens, so just don't get it - how to test

**Comment by skriss** [comment]
It looks like an existing test case (https://github.com/vmware-tanzu/velero/blob/master/pkg/restore/restic_restore_action_test.go#L73) is now being caught by the code you added, so it's result has changed. I would recommend changing `not:valid:image` to something else -- perhaps adding yet another `:` to it would make sense.

Not sure why this test wouldn't be failing for you when running `make test`, though - can you show the output you're getting? What about if you run `go test ./...`?

**Comment by cognoz** [comment]
> It looks like an existing test case (https://github.com/vmware-tanzu/velero/blob/master/pkg/restore/restic_restore_action_test.go#L73) is now being caught by the code you added, so it's result has changed. I would recommend changing `not:valid:image` to something else -- perhaps adding yet another `:` to it would make sense.
> 
> Not sure why this test wouldn't be failing for you when running `make test`, though - can you show the output you're getting? What about if you run `go test ./...`?

OK, I fixed this test case, thx. 
PS. Cannot confirm, why I didn't get anything from `make test` on last friday, as today I got the same error as on CI.

**Comment by cognoz** [comment]
> It looks like an existing test case (https://github.com/vmware-tanzu/velero/blob/master/pkg/restore/restic_restore_action_test.go#L73) is now being caught by the code you added, so it's result has changed. I would recommend changing `not:valid:image` to something else -- perhaps adding yet another `:` to it would make sense.
> 
> Not sure why this test wouldn't be failing for you when running `make test`, though - can you show the output you're getting? What about if you run `go test ./...`?

results running make test:
?       github.com/vmware-tanzu/velero/pkg/plugin/velero/mocks  [no test files]
ok      github.com/vmware-tanzu/velero/pkg/podexec      0.017s
ok      github.com/vmware-tanzu/velero/pkg/restic       0.017s
?       github.com/vmware-tanzu/velero/pkg/restic/mocks [no test files]
ok      github.com/vmware-tanzu/velero/pkg/restore      0.185s
?       github.com/vmware-tanzu/velero/pkg/restore/mocks        [no test files]
....
Success!

Go test needs a lot of dependencies, can not run it right now. I'll look at this test case later
