### ISSUE TITLE
Problem installing velero from local build : OCI runtime create failed

### ISSUE THREAD

**Issue by jweldonca** [vmware-tanzu/velero#1973]
Running on azure

1) Built from source following [these instructions ](https://velero.io/docs/v1.1.0/build-from-source/)
2) `make all-containers`
3) pushed velero-builder image to my repository
4) Ran the following command with correct variables
```
velero install \
    --provider azure \
    --bucket $BLOB_CONTAINER \
    --secret-file ./credentials-velero \
    --backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID[,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID] \
    --snapshot-location-config apiTimeout=<YOUR_TIMEOUT>[,resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID]
```
```
 
**What did you expect to happen:**

Velero to be installed 

**OUTPUT**:

  Normal   Scheduled  12m                  default-scheduler                  Successfully assigned velero/velero-c498dcb9-ms6sd to aks-agentpool-34951837-2
  Warning  Failed     11m (x4 over 11m)    kubelet, aks-agentpool-34951837-2  Error: failed to start container "velero": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/velero\": stat /velero: no such file or directory": unknown

**Comment by skriss** [comment]
re: step #3 - you want to use the `velero` image, not the `velero-builder` one. I'm guessing this is your issue?

**Comment by skriss** [comment]
Closing as inactive. Feel free to reopen as needed.

**Comment by Miraj50** [comment]
Hi, reopening this as I am facing this in my system too.

My system: WSL Ubuntu 20.04

Steps to reproduce:
1. Run `make local` to create the binary (_output/bin/linux/amd64/velero)
2. Create velero image by running `docker build . -f Dockerfile_cicd -t localvelero:v1`
The contents of Dockerfile_cicd are :
```
FROM gcr.io/distroless/base-debian11:nonroot
COPY /_output /
USER nonroot:nonroot
```
3. Push the image to Azure Container Registry
4. Install velero using its locally downloaded helm chart, but the image pointing to ours
```
image:
  repository: myacr.azurecr.io/localvelero
  tag: v1
```

After running helm install, I 'describe' the failed pod in k9s and I see this error:
`failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/velero": stat /velero: no such file or directory: unknown`

![image](https://user-images.githubusercontent.com/23695844/193888803-1e3255b0-83da-445f-9546-de3f64eb7d62.png)

Can someone please tell me if there's something I am missing here? How do I get my local built velero image running?

Thank you!
