### ISSUE TITLE
Support for dual-stack clusters and running Velero in IPv6

### ISSUE THREAD

**Issue by VMmore** [vmware-tanzu/velero#1975]
**Describe the problem/challenge you have**
I would like to ensure that Velero runs successfully in a dual-stack cluster generally, and connecting with IPv6 locations for backups and snapshots.

**Describe the solution you'd like**
Velero should run successfully in a dual stack cluster with ipFamily set to IPv4 or IPv6. Velero should accept and successfully backup and restore to locations that have IPv6 endpoints.

**Environment:**

- Velero version (use `velero version`): >v1.2
- Kubernetes version (use `kubectl version`): >=Kubernetes v1.16

**Comment by reasonerjt** [comment]
I managed to get an IPv6 single stack cluster from internal infra.
I successfully deployed minio to this cluster, exposed as nodepart to serve IPv6.  
After cherrypicking some fixes, https://github.com/reasonerjt/velero/tree/ipv6-e2e
I successfully ran the e2e test using this minio as object storage.  
[report.xml.zip](https://github.com/vmware-tanzu/velero/files/7004842/report.xml.zip)
I think this verifies the main functionality of velero on IPv6.

**Comment by reasonerjt** [comment]
Per discussion, in v1.7 timeframe we'll only verify the single stack env.

I'll keep this open to track the work for dual-stack and move it out of v1.7 milestone.

**Comment by dsu-igeek** [comment]
@reasonerjt will check with TKG team to see when "E" TKG release will support dual stack

**Comment by mcwumbly** [comment]
We have a tracking issue here: https://github.com/vmware-tanzu/tanzu-framework/issues/616 

Initial support was merged in this PR: https://github.com/vmware-tanzu/tanzu-framework/pull/617

There are a number of dependencies we are currently blocked on before we can deliver this is a form we consider "complete". Until then it may just be best to wait.

_However_ if there's a desire to start validation sooner, we could support you in hand rolling testbeds on vSphere. Another complementary approach to consider is to use KinD for initial validation and/or ongoing validation in CI for the velero project.

**Comment by reasonerjt** [comment]
@mcwumbly 
Sorry for the late reply.
Instead of the hand rolling testbeds, I'd rather wait for readily available testbeds.

**Comment by reasonerjt** [comment]
Verified the functionality by running E2E test suite on y IPv4, IPv6 dual stack env provisioned by internal infra.
[report.xml.zip](https://github.com/vmware-tanzu/velero/files/7923238/report.xml.zip)
