### ISSUE TITLE
AWS SKD upgrade | IRSA awareness

### ISSUE THREAD

**Issue by redradrat** [vmware-tanzu/velero#2010]
**Describe the problem/challenge you have**
In order to utilize the AWS OIDC provider, an upgrade of the AWS SDK dependency is needed. As outlined by @mhausenblas in https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/ this allows for mapping IAM to serviceaccounts without the need of additional translation (kiam, kube2iam).

**Describe the solution you'd like**
Bump the AWS golang SDK to `v1.23.13`.
https://github.com/aws/aws-sdk-go/releases/tag/v1.23.13

**Environment:**

- Velero version (use `velero version`): v1.2.0-beta.1
- Kubernetes version (use `kubectl version`): 1.14.6
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
we can definitely do this, though I *believe* that the newly-extracted plugin code already has a sufficiently high SDK version to support this -- see https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/master/Gopkg.toml#L30.

**Comment by redradrat** [comment]
Nevermind me being stupid... Yes the new plugin already is built with a newer SDK. I'm closing this. **As of `v1.2.0-beta.1`, with the new aws plugin, leveraging OIDC to map serviceaccouts to IAM roles is possible.** For whomever want's to go that path too. :)
