### ISSUE TITLE
enable sorting `velero backup get` output by  fields other than name

### ISSUE THREAD

**Issue by mad01** [vmware-tanzu/velero#2020]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Leats assume that you create three schedules. like this 
```
velero schedule create hourly-backup --schedule "8 * * * *"
velero schedule create backup-hourly --schedule "8 * * * *"
velero schedule create demo-backup --schedule "8 * * * *"
```
after some backups have happened and you do `velero backup get` the order or the backups are named order or the name of the backup.  This will look something like this. (i have removed a few collums since they did not bring any info in this case)
```
NAME                             CREATED                          EXPIRES  
backup-hourly-20191028150014     2019-10-28 16:00:14 +0100 CET    28d      
backup-hourly-20191028130014     2019-10-28 14:00:14 +0100 CET    28d      
.
.
backup-hourly-20191015140039     2019-10-15 16:00:39 +0200 CEST   15d      
backup-hourly-20191015122036     2019-10-15 14:20:36 +0200 CEST   15d      
demo-backup-20191028150014       2019-10-28 16:00:25 +0100 CET    28d      
demo-backup-20191028100014       2019-10-28 11:00:23 +0100 CET    28d      
.
.
demo-backup-20191018140028       2019-10-18 16:00:37 +0200 CEST   18d      
demo-backup-20191018130153       2019-10-18 15:02:04 +0200 CEST   18d      
hourly-backup-20191029220815     2019-10-29 23:08:15 +0100 CET    29d      
hourly-backup-20191029170815     2019-10-29 18:08:15 +0100 CET    29d      
.
.
hourly-backup-20191018130828     2019-10-18 15:08:28 +0200 CEST   18d      
hourly-backup-20191018115634     2019-10-18 13:56:34 +0200 CEST   18d      
```

**What did you expect to happen:**
What is expected to happen is that i get a list sorted by created time. During an incident i want to have all the latest at the end of the list or at the top. That will not be the case if you have multiple schedules.

The default behaviour is to sort by name since that is what we get from k8s that might be okay with just a few but after a month there can be ~700 backups if you do hourly and then if they are mixed it can be hard to find the last one. 

what i would like is to have the option to sort by backup creation time even if default sorting is by name of backup

**Environment:**

- Velero version (use `velero version`): 
Client:
	Version: v1.1.0
	Git commit: a357f21aec6b39a8244dd23e469cc4519f1fe608
Server:
	Version: master

- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.10", GitCommit:"8cea5f8ae165065f0d35e5de5dfa2f73617f02d1", GitTreeState:"clean", BuildDate:"2019-10-05T00:08:10Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version: gke
- Cloud provider or hardware configuration: google

**Comment by skriss** [comment]
thanks for the request @mad01, we'll take a look! do you have any interest in working on a PR for this?

**Comment by mad01** [comment]
took a look on the source. Could take a look and se if i can get something working. 

@skriss what would be the suggested way for this to work? Do you think the default should just be sort by created ts or as an option?

**Comment by skriss** [comment]
I could see sorting by created timestamp being a better default. Sorting by name is nice in that it keeps all backups from a given schedule together, but other than that it can potentially be very unhelpful. @nrb @carlisia @prydonius thoughts?

Couple other thoughts:
- it would be nice to have a flag like `--sort-by`, similar to `kubectl get`, that allows passing field names in as args, so we can support sorting by arbitrary fields. I know `kubectl` uses JSONPath to specify these -- need to figure out if that's appropriate here.
- there's both the `creationTimestamp` in metadata, and the `startTimestamp` in the status. The former is Kubernetes-assigned whenever the CR is created. This could get weird if you're importing backups into a cluster from an object storage bucket - the `creationTimestamp` will be ~now, whereas the `startTimestamp` would be the time in the past when the backup was actually processed. On the other hand, `startTimestamp` won't be populated at all until a velero controller starts processing the custom resource.

**Comment by carlisia** [comment]
Yes, this is a good idea. 

I think valid values for the `sort-by` flag should be the same columns that we get with `velero backup get`, which are `NAME   STATUS   CREATED   EXPIRES   STORAGE LOCATION   SELECTOR`.

If we do that ^, then the default sort should be by `created`, since `startTimestamp` is not one of the columns.

**Comment by prydonius** [comment]
I would love to get a point to where `kubectl get` and `velero get` are the same. I wonder if it's worth exploring having `velero get` call out to the relevant `kubectl get` command, and that way we could leverage the sorting by kubectl. We could of course add some helper flags so users don't need to specify the JSONPath, but we can then translate it to JSONPath and pass it to `kubectl get`. What do you think?

**Comment by mad01** [comment]
based on the feedback on the issue. i don't think i know enough for get something working right now. if someone else like to pick it feel free

**Comment by skriss** [comment]
xref #1780

**Comment by eleanor-millman** [comment]
Closing because there are other ways of doing this.

**Comment by zarelit** [comment]
@eleanor-millman why is this closed? Is there a way that does not involve parsing the tabular output?

**Comment by eleanor-millman** [comment]
@dsu-igeek was the engineer who suggested this action. He might be able to give more detail. @reasonerjt also might be able to respond.

**Comment by zarelit** [comment]
@dsu-igeek @reasonerjt any idea on how to do this without resorting to external tooling?
