### ISSUE TITLE
Restore within openshift namespaces does not respect groups id

### ISSUE THREAD

**Issue by philipp1992** [vmware-tanzu/velero#2023]
**What steps did you take and what happened:**
I created a backup of my openshift cluster with volume backup of glusterfs using restic.
When i restore the backup, the PVC will request a new dynamic glusterfs volume on the new cluster and the restic data is restored with the correct uid to the new PVC.

Here is an example of a restored file:
-rw-r--r--    1 10004800 2088          3785 Oct 30 15:28 modules.json

When i execute "id" within the restored container, i can see, that the groups id now differs from the backuped container:

$ id
uid=1000480000 gid=0(root) groups=2009,1000480000

Since velero / restic is not chowning the restored files to the new groups-id, we now have a permissions problem.

**What did you expect to happen:**

I expected velero to either create the new namespace / pods with the old uid and group id or to chown the restored files to the new group id

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

openshift 3.11
kubernetes 1.11
velero 1.0.0

**Comment by prydonius** [comment]
@philipp1992 is this because OpenShift randomises the extra group id for the container? If I remember correctly, OpenShift guarantees the gid to be 0, so one solution would be to have your containers chown the files you want to backup to gid 0. They will get restored with the same gid which the new restored container will have permissions to access.

**Comment by carlisia** [comment]
Hi @philipp1992, did you have a chance to try the suggestion above? Please let us know!

**Comment by philipp1992** [comment]
Actually its correct that openshift randomizes the GID, so it's not a problem of velero at all. We solved this by setting the GID to a fixed value. It would be great if this could be included as a hint in the velero documentation. Thanks.
