### ISSUE TITLE
add "Upgrading to 1.2" page with detailed instructions

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero#2028]
Right now in our docs we have an "Upgrading to 1.1" page that's listed in the TOC under "Install" - https://velero.io/docs/master/upgrade-to-1.1/. Let's replace this with an "Upgrading to 1.2" page.

- Image is now `velero/velero` (update for both deployment and daemonset if using restic)
- Need to add separate plugin image to deployment if using AWS/Azure/GCP
- anything else?

cc @carlisia @prydonius @nrb

**Comment by skriss** [comment]
One thing to think about here - how can we get the structural schema applied to existing CRDs (i.e. for the upgrade user case)?

**Comment by nrb** [comment]
> One thing to think about here - how can we get the structural schema applied to existing CRDs (i.e. for the upgrade user case)?

I wonder if it would make sense to make `velero install` emit just the CRD info and pipe it into `kubectl apply`. It's a code change and probably an added flag, but I _think_ the work would be pretty minimal.

I know we have an issue for a `velero upgrade` command, but I think that's a larger chunk of work that would delay the release more.

**Comment by prydonius** [comment]
@nrb that sounds like a quick and easy solution for this right now, I'm happy to pick that up.

Agree that going forward we should look at working on a `velero upgrade` command.

**Comment by skriss** [comment]
@nrb you're saying something like `velero install --resources crds --dry-run -o yaml`, and then have the user `kubectl apply` that?

If so (or similar) that sounds reasonable to me. Agree `velero upgrade` is too big to try to tackle now.

@prydonius it'd be great if you could tackle that. If you want to take the rest of the upgrade docs, that's great too - if not (I know you've got KubeCon prep), I can take the documentation and will just plug in this new command when ready.

**Comment by prydonius** [comment]
@skriss sounds good, splitting the work on the command and upgrade docs makes sense to me, I can take the command :+1:.

For the command, `velero install --resources <>` implies it would work for any resources. Perhaps a subcommand of `velero install crds`, or perhaps even `velero upgrade crds` to handle the specific CRD case for now would be more clear?

`velero upgrade crds` could also do the `kubectl apply` part for the user, but happy to also keep this simple and just output yaml that can be piped to `kubectl apply`.

**Comment by skriss** [comment]
OK sounds good on work split.

I'd probably stick with `velero install crds` for now, supporting the `--dry-run -o yaml` options, for simplicity, and tackle `upgrade` holistically down the road.

**Comment by nrb** [comment]
Yeah, I was thinking of either a subcommand or flag for crds only, not any resource that we could possibly make.

**Comment by prydonius** [comment]
Thinking about this more, I think a `--crds-only` flag will be the easiest thing to do.

**Comment by prydonius** [comment]
Actually, a flag poses some issues with the other flags that `velero install` requires, I'll see if it theres a sane way to work around that, otherwise a sub-command makes more sense here.
