### ISSUE TITLE
Kubernetes complaining about schedule.velero.io yaml value types

### ISSUE THREAD

**Issue by vsantos** [vmware-tanzu/velero#2030]
**What steps did you take and what happened:**
Running the schedule command after a fresh install results on the following error:

```
./velero schedule create all-cluster \
    --schedule="0 0 * * *" \
    --include-resources '*' \
    --include-namespaces '*' \
    --include-cluster-resources=true \
    --ttl 72h \
    --labels entireCluster=true
```

```
An error occurred: Schedule.velero.io "daily-backup" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"velero.io/v1", "kind":"Schedule", "metadata":map[string]interface {}{"creationTimestamp":"2019-10-31T16:51:58Z", "generation":1, "name":"daily-backup", "namespace":"velero", "uid":"c06b0aec-fbfe-11e9-ace7-0ad2a34949ea"}, "spec":map[string]interface {}{"schedule":"0 */6 * * *", "template":map[string]interface {}{"excludedNamespaces":interface {}(nil), "excludedResources":interface {}(nil), "hooks":map[string]interface {}{"resources":interface {}(nil)}, "includeClusterResources":interface {}(nil), "includedNamespaces":[]interface {}{"*"}, "includedResources":interface {}(nil), "labelSelector":interface {}(nil), "storageLocation":"", "ttl":"72h0m0s", "volumeSnapshotLocations":interface {}(nil)}}, "status":map[string]interface {}{"lastBackup":interface {}(nil), "phase":"", "validationErrors":interface {}(nil)}}: validation failure list:

spec.template.volumeSnapshotLocations in body must be of type array: "null"
status.phase in body should be one of [New Enabled FailedValidation]
status.validationErrors in body must be of type array: "null"
```

I am using the AWS integration for tarball upload to s3 bucket. Can you please point me to some direction?

**What did you expect to happen:**
A scheduler object to be created successfully. 

**Anything else you would like to add:**
Im seeing a few type errors from Kubernetes such as `spec.template.volumeSnapshotLocations in body must be of type array: "null"` or `status.phase in body should be one of [New Enabled FailedValidation]`. Maybe it's something up to my Kubernetes' version?

**Environment:**

- Velero version (use `velero version`): 1.1.0
- Velero features (use `velero client config get features`): None
- Kubernetes version (use `kubectl version`): 1.16 (client) and 1.14.16 (server)
- Kubernetes installer & version: eks
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): MacOS (binary client) and Amazon Linux to the Kubernetes' Nodes

**Comment by skriss** [comment]
@prydonius could you help dig into this? sounds similar to #2001 but I'm not sure why this would be coming up with v1.1...

**Comment by skriss** [comment]
@vsantos have you installed `v1.2.0-beta.1`, or a custom build from `master`, in this cluster at any point in the past? It sounds like perhaps you have an early version of the CRD structural schema applied in your cluster (which is a v1.2 feature, not part of v1.1), but before we fixed some bugs with it.

If that's the case, you may want to consider removing everything and doing a fresh install with v1.1.

**Comment by vsantos** [comment]
@skriss sorry about that, it was exactly the case. I started with `v1.2.0-beta.1` and just moved back to `v1.1`. Totally my fault. I remove it every Velero's CRDs and the resources are running fine.

**Comment by arianitu** [comment]
@skriss I'm running into this. I have velero v1.2.0 installed, what do I do to fix it?

**Comment by arianitu** [comment]
@skriss I'm using the actual Go API, I am not using the CLI.

In the newer versions, do we have to specify TypeMeta or something for it to work correctly?

**Comment by skriss** [comment]
@arianitu have you applied the v1.2 CRD definitions to your cluster? `velero install --crds-only --dry-run -o yaml` will show you the YAML for those.

**Comment by arianitu** [comment]
@skriss I had the old Go API and had to update the package!
