### ISSUE TITLE
restic init issue

### ISSUE THREAD

**Issue by mshack70** [vmware-tanzu/velero#2040]
**What steps did you take and what happened:**
I'm trying velero for first time.  First I installed velero without restic, did some backup/restores of kubernetes namespaces and that worked great.  Next I wanted to try backing up annotated volumes as well with restic.

Our backend is s3 compatible (works fine with velero).  When I redo the install with the --use-restic, I get the daemonset installed properly.  However when I try a backup of a namespace with annotated volumes, I see errors in the velero logs such as:

time="2019-11-04T20:47:18Z" level=error msg="Error backing up item" backup=velero/gitlab-ce.11042019-2047 error="restic repository is not ready: error running command=restic init --repo=s3:http://<S3_SERVER_REDACTED>/k8s-jfk3-backups/restic/gitlab-ce --password-file=/tmp/velero-restic-credentials-gitlab-ce197882169 --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: create key in repository at s3:http://<S3_SERVER_REDACTED>/k8s-jfk3-backups/restic/gitlab-ce failed: client.PutObject: Transfering payloads in multiple chunks using aws-chunked is not supported.\n\n: exit status 1" error.file="/go/src/github.com/heptio/velero/pkg/restic/repository_ensurer.go:186" error.function="github.com/heptio/velero/pkg/restic.(*repositoryEnsurer).EnsureRepo" group=v1 logSource="pkg/backup/resource_backupper.go:264" name=gitlab-ce-gitlab-ce-6745469f66-clfw4 namespace=gitlab-ce resource=pods

**What did you expect to happen:**
Not sure as this is my first attempt.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

$ kc -n velero get pods
NAME                      READY   STATUS    RESTARTS   AGE
restic-fhlx8              1/1     Running   0          72m
restic-fzfwd              1/1     Running   0          72m
restic-jcjms              1/1     Running   0          72m
restic-lwwhn              1/1     Running   0          72m
restic-ml6sx              1/1     Running   0          72m
restic-ntc4j              1/1     Running   0          72m
velero-5cc55f7ff6-qsvfc   1/1     Running   0          72m

$ velero restic  repo get
NAME                      STATUS     LAST MAINTENANCE
gitlab-ce-default-bnxtc   NotReady   <never>

$ velero backup describe gitlab-ce.11042019-2047
Name:         gitlab-ce.11042019-2047
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  PartiallyFailed (run `velero backup logs gitlab-ce.11042019-2047` for more information)

Errors:    3
Warnings:  0

Namespaces:
  Included:  gitlab-ce
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-11-04 20:47:16 +0000 GMT
Completed:  2019-11-04 20:47:19 +0000 GMT

Expiration:  2019-12-04 20:47:16 +0000 GMT

Persistent Volumes: <none included>

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
$ velero version
Client:
	Version: v1.1.0
	Git commit: a357f21aec6b39a8244dd23e469cc4519f1fe608
Server:
	Version: v1.1.0

- Velero features (use `velero client config get features`): 
$ velero client config get features
features: <NOT SET>

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:12:15Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", Build

- Kubernetes installer & version:

- Cloud provider or hardware configuration:
onprem
- OS (e.g. from `/etc/os-release`):
 centos 7.6/7 based

**Comment by skriss** [comment]
hmm. I wonder if this means your object storage backend is not compatible with restic. Could you try using the `restic` CLI directly to create a repository and some backups? https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#amazon-s3 should point you in the right direction.

**Comment by mshack70** [comment]
Sure i'll give that a try.  I thought since the s3 backend worked with velero, it might also work with restic as well..., probably bad assumption.

**Comment by mshack70** [comment]
It looks like our backend s3 has ssl disabled.  When trying restic cli, it looks like it uses https.  

Tunnel Connection Failed

I'm not sure though why the error when trying this thru velero seems to indicated more of an issue with chunked data, vs. https.

Is there a way to force http connection when using restic with velero?

**Comment by skriss** [comment]
Yes, you can specify an `http` URL directly - for restic itself, see the last paragraph of https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#amazon-s3.

If your backend has SSL disabled, then you can specify a custom `s3Url` in your BackupStorageLocation's `spec.config` -- see https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/master/backupstoragelocation.md for an example. The restic repo identifier will be derived based on this base URL.

**Comment by mshack70** [comment]
Thanks. Yeah I had been using http for the backupstoragelocation.  I tried restic cli again and get same error.

 restic -r s3:http://<swift storage>/k8s-jfk3-backups/restic/gitlab-ce init  --no-lock
enter password for new repository:
enter password again:
Fatal: create key in repository at s3:http://<swift storage>/k8s-jfk3-backups/restic/gitlab-ce failed: client.PutObject: Transfering payloads in multiple chunks using aws-chunked is not supported.

I guess the backend we are using may not be compatible...

**Comment by skriss** [comment]
Sounds like not - if you can, can you tell us which backend it is?

We have #1178 and #1253 in the backlog for adding support for additional backends - it's possible #1253 in particular could help in your scenario.

**Comment by mshack70** [comment]
I also had updated velero to 1.2 so error similar...

time="2019-11-12T18:30:12Z" level=error msg="Error backing up item" backup=velero/gitlab-ce.test error="restic repository is not ready: error running command=restic init --repo=s3:http://<swift storage>/k8s-jfk3-backups/restic/gitlab-ce --password-file=/tmp/velero-restic-credentials-gitlab-ce483566212 --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: create key in repository at s3:http://<swift storage>/k8s-jfk3-backups/restic/gitlab-ce failed: client.PutObject: Transfering payloads in multiple chunks using aws-chunked is not supported.\n\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/repository_ensurer.go:144" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryEnsurer).EnsureRepo" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=gitlab-ce-gitlab-ce-6745469f66-clfw4 namespace=gitlab-ce resource=pods


The backend s3 we use, is pretty much same as openstack swift.

**Comment by skriss** [comment]
Ah, OK. Perhaps running minio.io would be an option for you? That's well-tested with velero. You can also check out the full list of compatible providers: https://velero.io/docs/v1.2.0/supported-providers/

I'm not sure there's much else to be done here - I'm going to close this issue out, but feel free to reach out again as needed!
