### ISSUE TITLE
fsfreeze: /var/log/nginx: freeze failed: Operation not supported

### ISSUE THREAD

**Issue by basic39** [vmware-tanzu/velero#2042]
**What steps did you take and what happened:**
Hi, I am trying to backup the nginx-example from https://velero.io/docs/master/hooks/, but I get this error message:
fsfreeze: /var/log/nginx: freeze failed: Operation not supported

All steps: https://www.notion.so/Velero-Backup-steps-for-github-001af720b26e46f1aa9069888d2748f2

**What did you expect to happen:**
Backup with hooks without error.

**The output of the following commands will help us better understand what's going on**:
velero backup logs nginx-backup
https://gist.github.com/basic39/cc068239c0fec921fbd503f633550e11

**Anything else you would like to add:**
If I run manualy "/sbin/fsfreeze --freeze /var/log/nginx" in the fsfreeze container, I get the same error.
If I delete the hook-part from the annotations, it works

**Environment:**
- Velero version (use `velero version`): 1.1.0
- Kubernetes version (use `kubectl version`): Server 1.13 Client 1.16
- Kubernetes installer & version: Rancher
- Cloud provider or hardware configuration: Trident as persistent storage class

**Comment by basic39** [comment]
Maybe I figured it out.
Does fsfreeze generally support nfs? If not, what is the alternative to fsfreeze for consistent backups of application with nfs persistent volumes?

**Comment by skriss** [comment]
@basic39 maybe you have application-specific commands to quiesce the application? It really depends on your workload and consistency requirements. `fsfreeze` is just intended as an example, but not necessarily applicable for all use cases.

**Comment by basic39** [comment]
@skriss yes. I just want to know the best practices for backup with velero. 
So there is not a general way to many consistent backups without writing application-specific hooks, right? Even if we would use something other instead of restic or trident?

**Comment by skriss** [comment]
It's usually application-specific, and if your app doesn't support quiescing, then `fsfreeze` is often a reasonable approach. Beyond that, I don't have any further recommendations.

**Comment by skriss** [comment]
you can also always not execute any pre/post hooks, and accept a potentially inconsistent backup.

**Comment by skriss** [comment]
I'm closing this out - feel free to reach out again as needed!

**Comment by rahulgit1988** [comment]
> Maybe I figured it out.
> Does fsfreeze generally support nfs? If not, what is the alternative to fsfreeze for consistent backups of application with nfs persistent volumes?

This is my question as well, facing same issue.
Just saw this issue is closed, is there any workaround?
