### ISSUE TITLE
Restore a specific PVC by name

### ISSUE THREAD

**Issue by abhinavsinha1991** [vmware-tanzu/velero#2043]
**Describe the problem/challenge you have**

I would like to restore a specific PVC from a full-namespace backup(with volume snapshots).

Currently if i execute the command: 
`velero restore create --from-backup bd-ns-azure-backup1 --include-resources pvc --wait`
, Velero restores all the PVCs.

**Describe the solution you'd like**

I would like to be able to do:
`velero restore create --from-backup bd-ns-azure-backup1 --include-resources pvc/my-desired-pvc --wait
`

**Anything else you would like to add:**

NA.

**Environment:**

- Velero version (use `velero version`): `v1.2.0-beta.1`
- Kubernetes version (use `kubectl version`): 
```
   Client Version: v1.15.0
   Server Version: v1.14.6
```
- Kubernetes installer & version: `NA (using AKS)`
- Cloud provider or hardware configuration: `Azure`
- OS (e.g. from `/etc/os-release`): `Not sure`

**Comment by skriss** [comment]
@abhinavsinha1991 thanks for submitting the request. We already have #904 in the backlog to cover restoring items by name, so I'm going to close this issue as a duplicate. Please follow along there!

**Comment by konvergence** [comment]
Hi all,

I have a namespace with 2 statefulsets One for Tomcat and One postgres.
I try to restore only postgres with the following workflow : 

scale 0 tomcat and scale 0 postgres
delete pvc-postgres

run velero restore.

Normally Velero should not restore existing objects.
Bu here velero stay freezed during restore of the pvc-tomcat ? why ?

It should to try restore  pvc-tomcat if it ever exist ....
By this way you shoud be able to restore only pvc-postgres
