### ISSUE TITLE
Using a S3 provider not AWS, Azure or GCP

### ISSUE THREAD

**Issue by LostInBrittany** [vmware-tanzu/velero#2045]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I am trying to install Velero on an [OVHcloud Managed Kubernetes](https://www.ovh.com/world/public-cloud/kubernetes/) cluster, using OVHcloud as S3 provider.

I have created the S3 bucket, and I have verified it works. 
I have created the `credentials-velero` file, with the `aws_access_key` and `aws_secret_access_key` fields that work on my S3 bucket.

The problem is when I try to install Velero, it asks me for a S3 provider with the `--provider` option, and this options seems to only support `aws`, `azure` or `gcp` values.

How could I use another S3 provider?

**What did you expect to happen:**

I expected to be able to install Velero using any S3 provider :)

**Comment by LostInBrittany** [comment]
I have found [this page](https://velero.io/docs/v1.1.0/ibm-config/) that seems to solve the issue by using `--provider aws` and then specifying in the `--backup-location-config` option the `s3Url` of my providers S3 endpoint...

**Comment by skriss** [comment]
yes, that's right @LostInBrittany - use `aws` as the provider, and provide the custom config you need for your provider in config params. If you have any further issues getting that set up, let us know!
