### ISSUE TITLE
Velero fails trying to back up a non-existing disk/pv/pvc

### ISSUE THREAD

**Issue by chirag-jog** [vmware-tanzu/velero#2047]
**What steps did you take and what happened:**
I have a GKE cluster and i am trying to use GKE to backup the cluster. I ran the `velero backup create <backup-name>` command

**What did you expect to happen:**
Back up to be successful but it failed because it is searching for a non-existing disk, pv and pvc.

**The output of the following commands will help us better understand what's going on**:
```
time="2019-11-05T18:13:09Z" level=error msg="Error backing up item" backup=velero/inf-k8s-uw1c-cluster-backup-20191105 error="error getting volume info: rpc error: code = Unknown desc = googleapi: Error 404: The resource 'projects/xxxxx-178216/zones/us-west1-c/disks/gke-inf-k8s-uw1c-621db-pvc-b0b25ad6-c431-11e9-b1b5-42010a8a00a6' was not found, notFound" group=v1 logSource="pkg/backup/resource_backupper.go:264" name=datadir-rawq-v1-0 namespace= resource=persistentvolumeclaims
```

* `kubectl logs deployment/velero -n velero`
Logs: https://gist.github.com/chirag-jog/3b2380075326087acd204551b0453877
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
https://gist.github.com/chirag-jog/82da49a80ad2f6c97a3defc89ac5ba26
* `velero backup logs <backupname>`
https://gist.github.com/chirag-jog/faa33f77d4f33a90e0f5e60cd0ff0fff

**Environment:**

- Velero version (use `velero version`): v1.1
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.12.9-gke.15
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`):

**Comment by prydonius** [comment]
Thanks for sharing the logs @chirag-jog. Could you also share the output of `kubectl get pv`, just to confirm that those PVs don't exist in the cluster?

**Comment by skriss** [comment]
closing this out as inactive - feel free to reach out again if needed.
