### ISSUE TITLE
[This is not an issue] Restaure a subset of data

### ISSUE THREAD

**Issue by ahmedjami** [vmware-tanzu/velero#2051]
Hello,
I want to know if Velero offers the possibility to restore a subset of data.
Considering a Volume that is backup by velero and wich containe 5 directories, there is an option wich allows to restore only 1 directory ?
Thanks.

**Comment by ahmedjami** [comment]
I see that this option exists with restic 
https://restic.readthedocs.io/en/latest/050_restore.html
restic -r /srv/restic-repo restore 79766175 --target /tmp/restore-work --include /work/foo

**Comment by skriss** [comment]
@ahmedjami no, velero does not support this. If you need to restore only a subset of a volume backed up with velero+restic, you'll need to use the `restic` CLI manually to access your backup and get the files you need.
