### ISSUE TITLE
Restoring Statefulset (e.g couchbase) leads to  "Multi-Attach error for volume"

### ISSUE THREAD

**Issue by archmangler** [vmware-tanzu/velero#2053]
**What steps did you take and what happened:**

Restoring and recovering non-Statefulset applications is successful but with a Statefulset, only backup, restore and not recovery is successful:

1. Backup a namespace containing a single statefulset (couchbase) running 1 replica only.
2. Delete the namespace completely.
3. Restore from the backup of the namespace

Result:

- The single pod remains in ContainerCreating
- Two PVs are created associated with the pod
- A single PVC is created in the "Lost" state
- The following error is seen in the event log:

```
23m         Warning   FailedAttachVolume       pod/couchbase-0                             Multi-Attach error for volume "pvc-1b9860c6-0208-11ea-b826-5a269cbf3473" Volume is already exclusively attached to one node and can't be attached to another
14m         Warning   FailedMount              pod/couchbase-0                             Unable to mount volumes for pod "couchbase-0_lolcorp-uat-az1-test-cbdeploy(f7092210-0231-11ea-b826-5a269cbf3473)": timeout expired waiting for volumes to attach or mount for pod "lolcorp-uat-az1-test-cbdeploy"/"couchbase-0". list of unmounted volumes=[datadir]. list of unattached volumes=[datadir default-token-xdl76]
```

To fix this situation after the restore, I use this series of steps (derived through experimentation):

```
1. scale the statefuleset down to 0
2. delete the pvc
3. delete the pv (and any duplicate PVs)
4. scale statefuleset up to one
5. Wait for pvc, pv then pod to slowly come up
```

Question: What is the correct way to configure statefulset restores to avoid this situation?

**What did you expect to happen:**

- PVC, PV and POD would be restored along with the namespace
- The single PV would mount successfully
- Only one claim would be associated with the PV and pod
- The statefuleset pod would transition to "Running"

**The output of the following commands will help us better understand what's going on**:

(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`

* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`

* `velero backup logs <backupname>`

* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`

* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):

```
0.1.1
```

- Velero features (use `velero client config get features`):

```
features: <NOT SET>
```

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"
```

- Kubernetes installer & version:

Azure Kubernetes: AKS

- Cloud provider or hardware configuration:

Azure

- OS (e.g. from `/etc/os-release`):

Ubuntu 18.

**Comment by skriss** [comment]
@archmangler apologies for the long delay on this issue - have you been able to resolve this?

If not, what is the reclaim policy on your storage class/PV for the stateful set? I'm unable to reproduce this when using a storage class with a `Delete` reclaim policy, but I do see similar (though not identical) behavior when using a `Retain` reclaim policy. Curious if this is consistent with your experience?

**Comment by archmangler** [comment]
@skriss - thanks for the response, this only occurs with reclaim policy of "Retain" (which actually makes sense). We've since just decided to change the storage class reclaim policy to "Delete".
