### ISSUE TITLE
Consider removing the `fsfreeze-pause` container image

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero#2056]
We should consider removing the `fsfreeze-pause` container image that we're currently building/publishing out of our repo.

We could easily replace it in our nginx examples with a vanilla `ubuntu:bionic` image, whose entrypoint is the sleep loop that we have here: https://github.com/vmware-tanzu/velero/blob/master/Dockerfile-fsfreeze-pause#L19.

It's also not even necessary to have it in its own container for example purposes -- the `fsfreeze` command is available in the `nginx` image. But, it is useful to show how to use a sidecar for hook purposes, so I'd rather leave it.

If we drop our `fsfreeze-pause` image, we'll get some simplification and speedup in our build/deploy process.

@carlisia @prydonius @nrb WDYT? can you think of any reason why we'd want/need to keep this around?

**Comment by nrb** [comment]
I think it's useful to have _an_ example container, but you're right, it doesn't need to be ours. In the past, the benefit of ours might have been a slimmer image, but I'm not so sure that's true if we're not using alpine.

So I'm :+1: for using a base Ubuntu image with a sleep loop.
