### ISSUE TITLE
allow time zone to be specified

### ISSUE THREAD

**Issue by haoshuwei** [vmware-tanzu/velero#2061]
We can know that `velero create schedule NAME --schedule=xxx` is using UTC time by default, should we support to let users set a timezone by themselves?

**Comment by haoshuwei** [comment]
@skriss any comments on this question?

**Comment by sunny0826** [comment]
I implemented this feature by modifying the time zone of the docker image: `velero /velero`. Is there any other more elegant method?

**Comment by skriss** [comment]
@sunny0826 that seems like a reasonable approach. We could also consider adding a server flag to specify the time zone if that's something that folks are interested in.

**Comment by sunny0826** [comment]
> @sunny0826 that seems like a reasonable approach. We could also consider adding a server flag to specify the time zone if that's something that folks are interested in.

@skriss that's great

**Comment by diemus** [comment]
it would be great if we can choose timezone , the backup is name as velero-xxx-{utc time}. hope it could be a local time format

**Comment by reddiablo85** [comment]
any progress on this....would be great to be able to adjust the TZ from the Velero side as we´ve clusters across various timezones

**Comment by FreeZhang61** [comment]
I have the same problem,  I want to create the schedule by Asia/Shanghai  timezone

**Comment by FreeZhang61** [comment]
@sunny0826  Thank you,  I solve this  problem with the same way

**Comment by nrb** [comment]
https://github.com/vmware-tanzu/velero/pull/2944 allows for specifying the timezone now. This will be released in v1.6.0, expected in December 2020.
