### ISSUE TITLE
the velero client in velero/velero:v1.2.0 doesn't match the version v1.2.0

### ISSUE THREAD

**Issue by haoshuwei** [vmware-tanzu/velero#2067]
When we run a velero deployment using image `velero/velero:v1.2.0`,  exec to enter the pod and then run command `/velero version`, we can see information listed as below:
```
Client:
	Version: v1.1.0
	Git commit: a357f21aec6b39a8244dd23e469cc4519f1fe608
Server:
	Version: v1.1.0
```

`Version` should be `v1.2.0`, is it correct?

**Comment by skriss** [comment]
@haoshuwei I'm unable to reproduce this - could you show the YAML for the deployment and the specific pod you're exec'ing into?

FYI, here's the output I get after following the same steps you supplied:

```
nobody@velero-58754d7b6d-tttn8:/$ /velero version
Client:
	Version: v1.2.0
	Git commit: 5d008491bbf681658d3e372da1a9d3a21ca4c03c
Server:
	Version: v1.2.0
```

**Comment by haoshuwei** [comment]
@skriss  Sorry, my sync to my image repositry with the wrong source image. Close the issue
