### ISSUE TITLE
Fails Cluster Migration due to partial failure in Backup

### ISSUE THREAD

**Issue by asishr14** [vmware-tanzu/velero#2072]
**What steps did you take and what happened:**
Cluster Migration from 1 to 2 fails due to partial failure in cluster 1.
Failure in Cluster 1 is due to

level=error msg="Error backing up item" backup=velero/liveservices error="clusterroles.rbac.authorization.k8s.io \"system:auth-delegator\" not found" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:351" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*defaultItemBackupper).executeActions" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=metrics-server namespace= resource=serviceaccounts

**What did you expect to happen:**
Though with partial failure of backup in cluster 1, backup to be available for restoring in Cluster 2

**Environment:**
- Velero version - 1.2.0
- Kubernetes version: 1.11.5
- Cloud provider or hardware configuration: Azure

**Comment by skriss** [comment]
@asishr14 you should still be able to restore this backup in cluster 2, using `velero restore create --from-backup <NAME>`. Is there a specific error you're getting when you try to restore?

Also, it sounds like you have a `ClusterRoleBinding` that references the nonexistent `ClusterRole` `system:auth-delegator`. You can run `kubectl get clusterrolebindings -A -o wide | grep system:auth-delegator` to find it and (probably) delete it since it's not valid.

**Comment by asishr14** [comment]
> you should still be able to restore this backup in cluster 2, using velero restore create --from-backup <NAME>. Is there a specific error you're getting when you try to 

Yes it cannot find the backup, i tried using the --allow-partial-failed flag as well.
Note:: I am using same backup location and secrets for both the clusters.

>You can run kubectl get clusterrolebindings -A -o wide | grep system:auth-delegator to find it and (probably) delete it since it's not valid.

I found the metrics-server:system:auth-delegator and removed it, but after that backups are failing with
 level=error msg="Error backing up item" backup=velero/liveservices error="clusterroles.rbac.authorization.k8s.io \"system:auth-delegator\" not found" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:351" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*defaultItemBackupper).executeActions" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=metrics-server namespace= resource=serviceaccounts

**Comment by skriss** [comment]
Are there any cluster role bindings referencing this cluster role? Can you provide the output of:

```
kubectl get clusterrole system:auth-delegator

kubectl get clusterrolebindings -o wide | grep system:auth-delegator
```

**Comment by asishr14** [comment]
> kubectl get clusterrole system:auth-delegator

Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "system:auth-delegator" not found

> kubectl get clusterrolebindings -o wide | grep system:auth-delegator


`NAME                                                               AGE    ROLE                                                                   USERS   GROUPS                                         SERVICEACCOUNTS
addon-http-application-routing-nginx-ingress-clusterrole-binding   247d   ClusterRole/addon-http-application-routing-nginx-ingress-clusterrole                                                          kube-system/addon-http-application-routing-nginx-ingress-serviceaccount
addon-http-application-routing-viewer                              247d   ClusterRole/addon-http-application-routing-external-dns                                                                       kube-system/addon-http-application-routing-external-dns
kured                                                              129d   ClusterRole/kured                                                                                                             kube-system/kured
metrics-server:system:auth-delegator                               11d    ClusterRole/system:auth-delegator                                                                                             kube-system/metrics-server
nginx-ingress-clusterrole-nisa-binding                             62d    ClusterRole/nginx-ingress-clusterrole                                                                                         ingress-nginx/nginx-ingress-serviceaccount
omsagentclusterrolebinding                                         357d   ClusterRole/omsagent-reader                                                                                                   kube-system/omsagent
system:aks-client-node-proxier                                     269d   ClusterRole/system:node-proxier                                                system:nodes
system:aks-client-nodes                                            269d   ClusterRole/system:node                                                        system:nodes
system:discovery                                                   357d   ClusterRole/system:discovery                                                   system:authenticated, system:unauthenticated
system:kube-dns-autoscaler                                         307d   ClusterRole/system:kube-dns-autoscaler                                                                                        kube-system/kube-dns-autoscaler
system:metrics-server                                              357d   ClusterRole/system:metrics-server                                                                                             kube-system/metrics-server
velero                                                             11d    ClusterRole/cluster-admin                                                                                                     velero/velero`

**Comment by skriss** [comment]
It looks like there's still at least one cluster role binding in there that tries to use the nonexistent `system:auth-delegator` cluster role (`metrics-server:system:auth-delegator 11d ClusterRole/system:auth-delegator kube-system/metrics-server`).  If you delete it, the velero error will go away.

**Comment by asishr14** [comment]
@skriss: It is being added again as soon as I delete it. Causing velero to fail again with same error

`NAME                                                               AGE    ROLE                                                                   USERS   GROUPS                                         SERVICEACCOUNTS
                                                                                                       kube-system/kured
metrics-server:system:auth-delegator                               61s    ClusterRole/system:auth-delegator                                                                                             kube-system/metrics-server
nginx-ingress-clusterrole-nisa-binding                             62d    ClusterRole/nginx-ingress-clusterrole`

**Comment by skriss** [comment]
OK, I'm not sure where that would be coming from, but if you can resolve that, you shouldn't get errors with velero.

We also have #1878 for a related issue - if you have comments on that, please add them there!

I'm going to close this out as the above two avenues should cover your issue. Feel free to reach out again as needed.
