### ISSUE TITLE
Backup remains in "InProgress"

### ISSUE THREAD

**Issue by chirag-jog** [vmware-tanzu/velero#2074]
While backing up certain namespaces in velero, the backup remains in "InProgress" state.
The server logs show the following error:

```time="2019-11-20T20:40:09Z" level=error msg="error updating backup's final status" controller=backup error="error patching backup: Backup.velero.io \"kubecon-demo-backup-1\" is invalid: metadata.labels: Invalid value: \"rabbitmq-gke-k8s-uw1-gcp-e49e70-pvc-bdc08e25-4809-11e8-b06b-42010a8a021c\": must be no more than 63 characters" error.file="/go/src/github.com/heptio/velero/pkg/controller/backup_controller.go:272" error.function=github.com/heptio/velero/pkg/controller.patchBackup key=velero/kubecon-demo-backup-1 logSource="pkg/controller/backup_controller.go:248"```

**Comment by skriss** [comment]
@chirag-jog I took a look at the code and I think I see what's going on here. We're inadvertently adding some labels to `Backup` custom resources that are actually intended to be tags on PV snapshots. It's happening at https://github.com/vmware-tanzu/velero/blob/master/pkg/backup/item_backupper.go#L459-L464 -- the cause is that in the first line, we're getting a reference to the `Backup's` labels map, rather than a deep copy of it.

This is definitely a bug and we'll look to ship a fix in the next release. Thanks for reporting!

**Comment by chirag-jog** [comment]
I have tested this branch https://github.com/skriss/velero/tree/fix-2074 and it's still not working for me. I tried to take velero backup for the entire cluster and it got stuck in `In Progress` state. Doesn't show logs until it's finished processing.

**Comment by rendhalver** [comment]
I am seeing the same problems here when backing up all Namespaces.
I can backup the test namespace from the example in the repo.

I will do some digging and see if I get the same issues with other Namespaces.

**Comment by rendhalver** [comment]
I created a backup for each namespace in on of our clusters and the backup for `kube-system` is still sitting at InProgress.
I vaguely remember something like this happening at my last job when we were setting up Ark.
I will try and work out what is causing the problems and report here.

**Comment by rendhalver** [comment]
I tried several backups with different results.
If I backup each namespace individually they all work except for `default` and `kube-system`.
The errors I see in `default` look like this.
```
time="2019-11-28T03:23:35Z" level=info msg="Backing up resource" backup=velero/backup-test-default group=extensions/v1beta1 logSource="pkg/backup/resource_backupper.go:106" resource=networkpolicies
time="2019-11-28T03:23:35Z" level=info msg="Skipping resource because it cohabitates and we've already processed it" backup=velero/backup-test-default cohabitatingResource1=networkpolicies.extensions cohabitatingResource2=networkpolicies.networking.k8s.io group=extensions/v1beta1 logSource="pkg/backup/resource_backupper.go:149" resource=networkpolicies
```
I can't get the errors for `kube-system` because it doesn't progress past `InProgress`.

I tried a backup for the whole cluster that excluded `kube-system` and that was stuck at `InProgress`
I also tried excluding system resources and got the same result.
I also tried just one Namespace and system and I get similar errors to what I got with default and no cluster.

For the record our cluster is quite old so that may be part of the problem.
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:14:38Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:05:01Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by skriss** [comment]
@chirag-jog can you provide the velero pod logs when using the fix branch?

**Comment by chirag-jog** [comment]
[velero_pod_logs.txt](https://github.com/vmware-tanzu/velero/files/3920391/velero_pod_logs.txt)
@skriss please find attached pod logs. I have deployed velero container image based on fix-2074 branch

**Comment by skriss** [comment]
Based on the following log line, it looks like the container that's running has the v1.2.0 code, not the PR code:

```
time="2019-11-27T08:32:34Z" level=info msg="Starting Velero server v1.2.0 (5d008491bbf681658d3e372da1a9d3a21ca4c03c)" logSource="pkg/cmd/server/server.go:173"
```

I also don't see any logs related to running a backup and having it be stuck.

I've pushed an image, `steveheptio/velero:fix-2074` that you can use to test this.  You should be able to run the following to update your velero deployment:

```
kubectl -n velerocj set image deploy/velero velero=steveheptio/velero:fix-2074
```

**Comment by chirag-jog** [comment]
> Based on the following log line, it looks like the container that's running has the v1.2.0 code, not the PR code:
> 
> ```
> time="2019-11-27T08:32:34Z" level=info msg="Starting Velero server v1.2.0 (5d008491bbf681658d3e372da1a9d3a21ca4c03c)" logSource="pkg/cmd/server/server.go:173"
> ```
> 
> I also don't see any logs related to running a backup and having it be stuck.
> 
> I've pushed an image, `steveheptio/velero:fix-2074` that you can use to test this. You should be able to run the following to update your velero deployment:
> 
> ```
> kubectl -n velerocj set image deploy/velero velero=steveheptio/velero:fix-2074
> ```

/home/aditi/Desktop/velero_fix_2074.txt
Plz find attached pod logs. Used steveheptio/velero:fix-2074 image and now Velero server fix-2074 is being used but still backup remains in "InProgress"

**Comment by skriss** [comment]
@chirag-jog can you please include the server log during the execution of the backup? I need more information.

**Comment by chirag-jog** [comment]
[velero_fix_2074.txt](https://github.com/vmware-tanzu/velero/files/3945951/velero_fix_2074.txt)

**Comment by skriss** [comment]
@chirag-jog this log file doesn't cover any backups running -- I'm trying to see what the logs are indicating during a backup. Can you do the following:

- `kubectl -n velerocj scale deploy/velero --replicas 0`
- `kubectl -n velerocj scale deploy/velero --replicas 1`
- `velero backup create debug-backup ...` (add the flags you've used previously)
- wait for some time, see what phase the previous backup ends up on
- provide me with the output of `kubectl -n velerocj logs deploy/velero`

Thanks!

**Comment by chirag-jog** [comment]
I tried re-installing velero and then updated the deployment with your image steveheptio/velero:fix-2074. But now velero pod is going into CrashLoopBackOff state and throws error `An error occurred: some backup storage locations are invalid: error getting backup store for location "default": unable to locate ObjectStore plugin named velero.io/gcp`

**Comment by skriss** [comment]
You need to add the GCP plugin - run `velero plugin add velero/velero-plugin-for-gcp:v1.0.0`

**Comment by chirag-jog** [comment]
[velero-fix-2074-logs.txt](https://github.com/vmware-tanzu/velero/files/3966260/velero-fix-2074-logs.txt)

Created new backup which got stuck in "In Progress". Attached are the server logs for the same

**Comment by skriss** [comment]
@chirag-jog that log *still* doesn't show the backup even starting - I need to see the logs from during the execution of the backup to be able to debug your issue any further. You should see a log statement like "Setting up backup log" around the beginning of the execution.

It would also be helpful if you could turn on debug logging for the velero server -- https://velero.io/docs/v1.2.0/troubleshooting/#getting-velero-debug-logs will show you how to do this.
