### ISSUE TITLE
PRE Hooks: Execute a command on a pod different to the pod annotate

### ISSUE THREAD

**Issue by ahmedjami** [vmware-tanzu/velero#2076]
Hi,
I want to know if it's possible to execute a command within a pod/container different to pod that we have annotate to backup?
My use case is:
1- Deploy 2 pods pod-1 & pod-2 that mounts the same PV-1 (the first pod-1 contains a cassandra image) plus a PV-2 specific to pod-2
2- Annotate pod-2 to be ready for backup with Velero
3- Configure a pre hooks to run a command (specific to cassandra) on pod-1
4- Configure a pre hooks to copy generated files from cassandra to from the shared PV -1to PV-2.
4- Launch a valero-backup on pod-2

Thanks

Thanks.

**Comment by skriss** [comment]
@ahmedjami you can certainly specify hooks on both pod-1 and pod-2, however there's no way to (a) force pod-1's hook to be executed before pod-2's; or (b) have pod-2 be backed up between pod-1's pre and post hooks (if that's relevant for you).

**Comment by skriss** [comment]
Closing this out - feel free to reach out again as needed.
