### ISSUE TITLE
Velero Documentation for schedule not complete

### ISSUE THREAD

**Issue by IlonkaO** [vmware-tanzu/velero#2079]
After updating Velero from 1.1.0 to 1.2.0 I tried to create a schedule object. During this I recognised that in the official documentation https://velero.io/docs/v1.2.0/api-types/schedule/ the entry "template" is completely missing.
After changing my Yaml file and add the template section fpr the backup definition, everything works fine.

**What did you expect to happen: A documentation with the template section** 

**Environment:**

- Velero version (use `velero version`): v1.2.0
- Velero features (use `velero client config get features`): NOT SET
- Kubernetes version (use `kubectl version`): v1.14
- Kubernetes installer & version: OpenShift 3.11
- Cloud provider or hardware configuration: on prem 3 master, 3 infra, and different count of worker
- OS (e.g. from `/etc/os-release`): RHEL 7.6

**Comment by skriss** [comment]
thanks for the docs bug report @IlonkaO! We'd love to have a fix contributed, if you're interested.
