### ISSUE TITLE
Add Chocolatey install for Windows CLI

### ISSUE THREAD

**Issue by kyschouv** [vmware-tanzu/velero#2081]
**Describe the problem/challenge you have**
Installing the CLI on Windows is cumbersome, and most other Kubernetes CLI tools we use can be installed via Chocolatey.

**Describe the solution you'd like**
It would be great to have a [Chocolatey](https://chocolatey.org/) install for Windows CLI users.

- OS (e.g. from `/etc/os-release`): Windows 10

**Comment by skriss** [comment]
@kyschouv thanks for filing the request - do you have any interest in helping out on this?

**Comment by kyschouv** [comment]
Possibly? It should just be a matter of packaging up the exe (I think as a NuGet package) and then copying it to the Chocolatey bin directory (and removing it on uninstall). I haven't made one before though, and I'm not sure if I'll have the opportunity to get to it for a while (we have a lot of post-Kubecon followup we're working on, among other projects - and while Velero is top of the list, there's a lot of other work to do).

**Comment by adamrushuk** [comment]
I've just had the Windows Velero CLI package approved on Chocolatey: https://chocolatey.org/packages/velero

I'll look into automating the releases shortly.
