### ISSUE TITLE
What's the Principle of Persistent Volumes backup and restore? 

### ISSUE THREAD

**Issue by duyanghao** [vmware-tanzu/velero#2084]
Hi, I am confused about the Principle of Persistent Volumes backup and restore? Is it using [CSI Volume Cloning FEATURE](https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/)?

**Comment by skriss** [comment]
@duyanghao we do not currently use CSI (but we're planning to start integrating with its volume snapshot feature in v1.3).  Velero has its own set of storage provider plugins that provide snapshot/restore functionality. See https://velero.io/docs/v1.2.0/supported-providers/ for details.

Closing this out, but feel free to reach out again as needed. It may be easier to discuss further on slack as well (#velero in Kubernetes slack)
