### ISSUE TITLE
Install velero with Minio running behind proxy 

### ISSUE THREAD

**Issue by adityagu0910** [vmware-tanzu/velero#2086]
I would like to install velero with my minio server accessible using my proxy server.
so is there a way to specify http proxy argument(**http_proxy=MY_PROXY_URL** ) while installing velero like below.

`velero install --provider aws --bucket <bucket name> --secret-file /opt/ibm/media/icp-backup/velero-v1.0.0-linux-amd64/credentials-velero --use-volume-snapshots=false --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://IP:PORT **http_proxy=MY_PROXY_URL** --velero-pod-mem-limit 2Gi --velero-pod-mem-request 2Gi --use-restic`

Or may be there is a way to configure BackupStorageLocation crds with proxy arguments

**Comment by skriss** [comment]
@adityagu0910 I believe you'll need to manually edit your velero deployment/daemonset to include this env var.

**Comment by adityagu0910** [comment]
Thanks 
I tried with env variables and I am getting below error 
`An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = RequestError: send request failed
caused by: Get https://s3.service.gocloud.gov.on.ca/minio/sus-icp-uat-backup?delimiter=%2F&list-type=2&prefix=: x509: certificate signed by unknown authority`

and when i add flag **insecureSkipTLSVerify: "true"** in backupstoragelocation, it gives below error
`An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = RequestError: send request failed
caused by: Get https://s3.service.gocloud.gov.on.ca/minio/sus-icp-uat-backup?delimiter=%2F&list-type=2&prefix=: dial tcp: lookup s3.service.gocloud.gov.on.ca on 172.16.128.10:53: no such host
`

Any suggestion on why it is not able to redirect properly to ingress url of minio while using insecureSkipTLSVerify ?

**Comment by adityagu0910** [comment]
I was able to connect by mounting my ingress cert in velero deployment and restic daemonset.
Create cert - 
`kubectl --namespace=velero create secret generic velero-minio-cert --from-file=minio.crt`
Add volume mounts -
   `     - mountPath: /etc/ssl/certs/minio.crt
          name: velero-minio-cert
          subPath: minio.crt`
Add volumes -
  `    - name: velero-minio-cert
        secret:
          defaultMode: 420
          secretName: velero-minio-cert
`
For proxy, I added variables - no proxy is required, if you want to connect to your pod.
 `       - name: HTTP_PROXY
          value: http://MYPROXYHOST:80
        - name: HTTPS_PROXY
          value: http://MYPROXYHOST:80
        - name: NO_PROXY
          value: 172.16.128.1
`

**Comment by skriss** [comment]
xref #1027

**Comment by skriss** [comment]
closing out.

**Comment by jhuisss** [comment]
> 

Hi, I face the same issue and I'm so glad there is a workaround provided several years ago, but what is the proxy server is a https proxy with cacert? How can I pass the cacert to velero deployment? Because if I don't pass the proxy cert to velero, the bsl will report error:
```
  status:
    lastSyncedTime: "2022-11-10T05:01:55Z"
    lastValidationTime: "2022-11-10T09:39:17Z"
    message: |-
      BackupStorageLocation "default" is unavailable: rpc error: code = Unknown desc = RequestError: send request failed
      caused by: Get "https://**:9000/jhui-velero?delimiter=%2F&list-type=2&prefix=": proxyconnect tcp: x509: certificate signed by unknown authority
    phase: Unavailable
```

I have passed the https minio server's cacert to bsl's spec.objectStorage. caCert, but I have no idea how to pass https proxy cert to velero.

Any clue?
