### ISSUE TITLE
Manage the restic cache dir more effectively

### ISSUE THREAD

**Issue by crdemon09** [vmware-tanzu/velero#2087]
**/scratch/.cache/restic/restic-check-cache-* folder is too huge**
Can we somehow disable a restic cache using velero?

**Solution**
velero restic --no-cache

**Anything else you would like to add:**
The size is growing up really quick while doing a schedule backup, with 4GB of neo4j database - I have /scratch folder in 2 days - 13G and then velero pod got "Evicted"

**Environment:**

- Velero version 1.0.0
- Kubernetes version 1.14
- Cloud provider or hardware configuration:
- OS CentOS

**Comment by crdemon09** [comment]
Small update - I think it's related to this [BUG](https://github.com/vmware-tanzu/velero/issues/1659)

**Comment by skriss** [comment]
We don't currently have a way to disable the restic cache; you could consider mounting a PV into the velero pod to use for the scratch dir, instead of using an empty dir.

**Comment by Davidsod** [comment]
@skriss thanks for the answer. What would be the downsides in that case?

**Comment by skriss** [comment]
I don't think there are really any downsides apart from the cost of the persistent storage. It's possible that you'll still run into issues where the cache eventually exceeds the size of the PV - I'm not sure off the top of my head.

**Comment by eleanor-millman** [comment]
Closing because workaround exists.
