### ISSUE TITLE
Labelling of objects that have PVC's that we want backed up. PATCH the Deployment

### ISSUE THREAD

**Issue by andragabr** [vmware-tanzu/velero#2089]
Hello, there is a possibility to create backups for:
1. A full namespace backup including Database and LDAP
2. Only a database backup
using different selectors and labels via the middlewares helm chart and patching the deployment, not the pod?
The instructions from documentation were to PATCH the POD. But I don't want to do that, instead, I should either:
- PATCH the Deployment.
- Add the labels via the middlewares helm chart (preferred method)

Until now I only know this method of backing-up:
Take a backup of the entire namespace
velero backup create <bkp-name> --include-namespaces <namespace-name>
Annotate the pods you’d like to take the backup of and only those volume names specified will be taken for backup. The form of the command is below
kubectl -n <namespace-name> annotate pod/<MYSQL_POD_NAME> backup.velero.io/backup-volumes=mysql-persistent-storage
But I am interested if there is any patch or hack to annotate the deployment not the pod?
Cheers

**Comment by skriss** [comment]
@andragabr you can also put the annotations in your deployment's pod template (i.e. `.spec.template.metadata.annotations`), so that any pod created for that deployment will have the annotation. Does that answer your question?

**Comment by skriss** [comment]
Closing this out as inactive - feel free to reach out again as needed.
