### ISSUE TITLE
Restore progress

### ISSUE THREAD

**Issue by kstewart** [vmware-tanzu/velero#21]
Similar to #20, do something similar to periodically update the progress of a restore.

**Comment by ncdc** [comment]
Idea: store per-restore log file to object storage. Add `ark restore log` command to retrieve it.

**Comment by nrb** [comment]
We now have the `ark restore logs` command, but it retrieves finished logs vs providing a progress update.

Pulling over some details from the comments on #20, it would be possible to store the number of items in a backup on the backup metadata, which would help with restoring when the entire backup is being restored, though doing a selective restore would still need to do some filtering.

I like the idea of some generic 'progress' struct that applies to both backups and restores.

**Comment by ncdc** [comment]
Is it worth considering using Kubernetes `events` for this? They have a pretty short TTL, but could be used on the fly to see what's going on. They could be used in addition to status field updates, perhaps.

**Comment by nrb** [comment]
That would make sense to me. A restore/backup could generate an `EventSeries` for that restore and external processes could look for that series to be in the `Finished` state to know when to stop monitoring.

Depending on how much information we want to report and when in the restore process, we could potentially used the `Related` field to link to the most recent object restored.

**Comment by ncdc** [comment]
It wouldn't work quite like that. The events could contain data such as `starting to restore pods`, `starting to restore pod/foo`, `finished restoring pod/foo`, `finished restoring pods`, and so on. A watcher that wants to know when a restore is done would look at the restore's `status.phase`.

An alternative that doesn't use events is to periodically update some field(s) on the restore's `status` related to progress, as described in #20. I am always concerned, however, about unbounded lists and maps in our data types, given the etcd per item size limit. (The unbounded bits here would be # of api groups and resources.)

**Comment by jhamilton1** [comment]
Adding a suggestion to this issue. Can the "ark get restore <restore>" command output that a non kube-system namespace did not restore because the namespace already existed and contained the pods to be restored?

**Comment by ncdc** [comment]
@jhamilton1 we wouldn't show that in `ark get restore` as that's meant to be a high-level summary that lists the restores and their statuses. We could put it in `ark describe restore`. If we do that, it would go as a per-namespace error (which we already have support for). I think this RFE belongs in #691 as part of the timeout discussion (after we exceed the timeout, record an error).

**Comment by jhamilton1** [comment]
@ncdc okay I will make a not on #691
