### ISSUE TITLE
"object logged as error does not satisfy error interface" crashes pod and backup fails

### ISSUE THREAD

**Issue by duffn** [vmware-tanzu/velero#2100]
**What steps did you take and what happened:**

- Run a cluster in GKE with master version 1.12.10-gke.17.
- Installed Velero and the GCP plugin successfully via the instructions at https://github.com/vmware-tanzu/velero-plugin-for-gcp.
- Ran

```
velero backup create test-backup-kube-system-ns --include-namespaces kube-system
```
- Receive an error and the velero pod crashes and restarts. The backup is stuck in `InProgress`.

```
time="2019-12-03T17:45:36Z" level=info msg="Backing up item" backup=velero/test-backup-kube-system-ns group=v1 logSource="pkg/backup/item_backupper.go:169" name="system:controller:ttl-controller" namespace= resource=clusterroles.rbac.authorization.k8s.io
time="2019-12-03T17:45:36Z" level=debug msg="Executing pre hooks" backup=velero/test-backup-kube-system-ns group=v1 logSource="pkg/backup/item_backupper.go:171" name="system:controller:ttl-controller" namespace= resource=clusterroles.rbac.authorization.k8s.io
time="2019-12-03T17:45:36Z" level=debug msg="Skipping action because it does not apply to this resource" backup=velero/test-backup-kube-system-ns group=v1 logSource="pkg/backup/item_backupper.go:311" name="system:controller:ttl-controller" namespace= resource=clusterroles.rbac.authorization.k8s.io
time="2019-12-03T17:45:36Z" level=debug msg="Skipping action because it does not apply to this resource" backup=velero/test-backup-kube-system-ns group=v1 logSource="pkg/backup/item_backupper.go:311" name="system:controller:ttl-controller" namespace= resource=clusterroles.rbac.authorization.k8s.io
time="2019-12-03T17:45:36Z" level=debug msg="Skipping action because it does not apply to this resource" backup=velero/test-backup-kube-system-ns group=v1 logSource="pkg/backup/item_backupper.go:311" name="system:controller:ttl-controller" namespace= resource=clusterroles.rbac.authorization.k8s.io
time="2019-12-03T17:45:36Z" level=debug msg="Executing post hooks" backup=velero/test-backup-kube-system-ns group=v1 logSource="pkg/backup/item_backupper.go:247" name="system:controller:ttl-controller" namespace= resource=clusterroles.rbac.authorization.k8s.io
time="2019-12-03T17:45:36Z" level=debug msg="Executing post hooks" backup=velero/test-backup-kube-system-ns group=v1 logSource="pkg/backup/item_backupper.go:247" name=ttl-controller namespace=kube-system resource=serviceaccounts
time="2019-12-03T17:45:36Z" level=info msg="Backing up resource" backup=velero/test-backup-kube-system-ns group=v1 logSource="pkg/backup/resource_backupper.go:106" resource=configmaps
time="2019-12-03T17:45:36Z" level=info msg="Listing items" backup=velero/test-backup-kube-system-ns group=v1 logSource="pkg/backup/resource_backupper.go:227" namespace=kube-system resource=configmaps
time="2019-12-03T17:45:39Z" level=debug msg="plugin process exited" backup=velero/test-backup-kube-system-ns cmd=/velero error="signal: killed" logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" path=/velero pid=236
Failed to fire hook: object logged as error does not satisfy error interface
Failed to fire hook: object logged as error does not satisfy error interface
time="2019-12-03T17:45:39Z" level=debug msg="plugin process exited" backup=velero/test-backup-kube-system-ns cmd=/plugins/velero-plugin-for-gcp error="signal: killed" logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" path=/plugins/velero-plugin-for-gcp pid=246
```

**What did you expect to happen:**

I expect velero to backup `kube-system` successfully. It backs up all other namespaces in the cluster without error.

**The output of the following commands will help us better understand what's going on**:

All output is here: https://gist.github.com/duffn/a490a50c952c794dd84ad89ab69b998f

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

All output is here: https://gist.github.com/duffn/a490a50c952c794dd84ad89ab69b998f

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
@duffn apologies, this slipped through over the holidays. Is this still an issue? If so, does it happen consistently? Could you try removing resource requests/limits from the Velero deployment and see if it continues to happen?

**Comment by skriss** [comment]
@duffn just checking in again to see if we can get some more info here.

**Comment by duffn** [comment]
I gave up on it at that point, but if I revisit again and can recreate the problem, I will report back.

**Comment by skriss** [comment]
I'm going to close this issue out for now, but please do report back if you get a chance.

**Comment by duffn** [comment]
I reinstalled velero in a development cluster, attempted to backup `kube-system` again with the default deployment and it failed in the same way.

I did remove the resource limits from the deployment as requested and the backup did, in fact, complete successfully then.

**Comment by abh** [comment]
I see the same for what it's worth -- "Failed to fire hook: object logged as error does not satisfy error interface"

**Comment by nrb** [comment]
@skriss Was this fixed by #2487?

**Comment by skriss** [comment]
well, the "Failed to fire hook: object logged as error does not satisfy error interface" message shouldn't come up anymore after #2487, yeah, but it sounds like the underlying problem for the OP was that the plugin process was being killed due to exceeding memory and/or CPU limits.

**Comment by duffn** [comment]
I'm coming back to say I've tested again with the newest Velero version.

```
Client:
	Version: v1.5.1
	Git commit: -
Server:
	Version: v1.5.1
```

I did not even try with the default resource constraints, however I doubled the CPU and memory limits from what is in the docs, and everything does seem to work.
