### ISSUE TITLE
Velero Backup failed - dial tcp 172.21.XXX.XXX:9000: i/o timeout

### ISSUE THREAD

**Issue by mohennekarim** [vmware-tanzu/velero#2105]
time="2019-12-05T07:03:52Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:355" namespace=velero
time="2019-12-05T07:03:52Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:361" namespace=velero
time="2019-12-05T07:03:54Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:390"
time="2019-12-05T07:03:57Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:424"
time="2019-12-05T07:03:57Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:431"
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = RequestError: send request failed
caused by: Get http://172.21.XXX.XXX:9000/velero?delimiter=%!F(MISSING)&list-type=2&prefix=: dial tcp 172.21.XXX.XXX:9000: i/o timeout

root@xx01:/etc/velero# kubectl get pods --all-namespaces|grep -i velero
velero                   restic-257wv                                                     1/1     Running             0          12m
velero                   restic-5s879                                                     1/1     Running             0          12m
velero                   restic-qcng8                                                     1/1     Running             0          12m
velero                   restic-w2v9v                                                     1/1     Running             0          12m
velero                   restic-zgvwb                                                     1/1     Running             0          12m
velero                   velero-db6459bb-8j7lx                                            0/1     CrashLoopBackOff    4          12m

root@xx01:/etc/velero# velero backup get
NAME          STATUS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
zingzing-bkp   New      0001-01-01 00:00:00 +0000 UTC   29d                          <none>

**Comment by skriss** [comment]
@mohennekarim can you confirm that the IP address you're using for minio is in fact reachable from a pod in the velero namespace?

**Comment by skriss** [comment]
Closing this out as inactive - feel free to reach out again as needed.
