### ISSUE TITLE
Unable to restore namespaces from one cluster to another in different region in aws,pvc's lost

### ISSUE THREAD

**Issue by nandeeshb09** [vmware-tanzu/velero#2107]
*Unable to restore namespaces from one cluster to another in different region in aws,pvc's lost
Is this implemented in newer version?.
We want to have namespace level backup and restore in different region with different cluster.
This we need it for disaster recovery purpose.(to restore the data in different region)

If yes , then which version this is possible?. 

appreciate your help.

**Comment by skriss** [comment]
@nandeeshb09 cross-region restores are not supported with AWS -- the main issue is that the volume snapshots are located in the source region and can't be restored in the target region without first being copied there.

I believe some folks have found manual workarounds to support this, where they manually copy the snapshots to the new region, then update Velero's metadata to point to the new region - I'd try searching through old issues to see if you can find the references.

**Comment by nandeeshb09** [comment]
thanks for the update

**Comment by skriss** [comment]
I'm going to close this out. Feel free to reach out again as needed.
