### ISSUE TITLE
Velero Java Client

### ISSUE THREAD

**Issue by MuhammadBilal789** [vmware-tanzu/velero#2110]
Hi,
I am working on a Java project and I need Velero for backup of kubernetes cluster but the problem is that there is no Velero Java client that I can use.

Can you please help me with that
Thanks

**Comment by skriss** [comment]
@MuhammadBilal789 sorry, we don't have a Java client and we're unlikely to be developing one in the foreseeable future.  You'll likely need to use the Kubernetes REST API directly, to access Velero's CRDs.
