### ISSUE TITLE
Trigger backups based on k8s events

### ISSUE THREAD

**Issue by nzoueidi** [vmware-tanzu/velero#2111]
**Describe the problem/challenge you have**
I would like to trigger backup(s) based on a delete/remove (CrashLoopBackOff, Terminating, Err, OOMKilled, etc) event(s).

**Describe the solution you'd like**
A custom controller where it use the k8s (watch) api to capture the previous events of the k8s objects, and trigger a velero backup for these component(s) that are being deleted/terminated.

**Comment by nrb** [comment]
Thanks @nzoueidi! I think this is a great idea, though I'm not sure it will get into Velero core in a timely manner unless a community member owns it. That, or it could be designed as an external controller submitting backups.

I'm certainly happy to help guide if you want to work on getting it to Velero core, or maybe work on something external then do a design document or present to the community after that's done.

**Comment by nzoueidi** [comment]
Thank you @nrb. I am already working on the design to how we could implement it in Velero core. I will open a draft PR soon.

**Comment by nrb** [comment]
Awesome! Look forward to seeing and discussing it.

**Comment by skriss** [comment]
closing this out per https://github.com/vmware-tanzu/velero/pull/2119#issuecomment-579379960
