### ISSUE TITLE
PartiallyFailed Backup with volume snapshot due to azure multiple resource group issue

### ISSUE THREAD

**Issue by ArundathiGV** [vmware-tanzu/velero#2117]
I had created AKS cluster 1.13 version cluster in resourcegroup1 and deployed velero with env 'AZURE_RESOURCE_GROUP' set to resourcegroup1. When I tried to take backup with volume snapshots of a namespace which had Persistent Volume Claims configured in that, it partially failed with following error

`time="2019-12-11T10:13:06Z" level=error msg="Error backing up item" backup=velero/test-3 error="error getting volume info: rpc error: code = Unknown desc = compute.DisksClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/disks/kubernetes-dynamic-pvc-dadad52d-18bd-11ea-be3c-7a85dbd6aab2' under resource group 'resourcegroup1' was not found.\"" group=v1 logSource="pkg/backup/resource_backupper.go:269" name=nginx-5b94c8c989-8vjrw namespace=aks-test resource=pods`

In aks when we create a pvc, the disks are created in a new resource group which will be in the format `MC_<resourcegroup>_<clustername>_<region>`. Because of which I'm getting above error as my cluster, velero and storage account is in one resource group and the disks are created in another resource group.

**Comment by skriss** [comment]
@ArundathiGV per https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#get-resource-group-for-persistent-volume-snapshots, you'll want to set `AZURE_RESOURCE_GROUP` to the name of the auto-generated `MC_...` resource group that contains all of your AKS cluster resources.

**Comment by skriss** [comment]
Also note that if you want to store the snapshots in a *different* resource group than the `MC_...` one, you can specify an alternate one as part of your `VolumeSnapshotLocation` config -- see https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/master/volumesnapshotlocation.md for documentation on that. By default, the snapshots will be stored in the same resource group as where the disks are.

**Comment by skriss** [comment]
closing this out as we've responded - feel free to reach out again as needed!

**Comment by HamzaK8s** [comment]
I'm facing the same issue with the latest version of velero v1.2.0 on Azure using helm chart I'm getting 
```
level=error msg="Error backing up item" backup=velero/nginxbackup-1581605115813 error="error getting volume info: rpc error: code = Unknown desc = compute.DisksClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/disks/test-dynamic-pvc-733d52b3-4e6f-11ea-a996-000d3ad8e11e' under resource group 'k8s-backup' was not found.\"" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=nginx-deployment-69564d5786-m9dl5 namespace= resource=pods
```
I configured the `volumesnapshotlocation` as follows:
```
apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: VolumeSnapshotLocation
  metadata:
    creationTimestamp: "2020-02-13T14:15:14Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: velero
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: velero
      helm.sh/chart: velero-2.8.1
    name: default
    namespace: velero
    resourceVersion: "2459531"
    selfLink: /apis/velero.io/v1/namespaces/velero/volumesnapshotlocations/default
    uid: 40f192cf-4e6b-11ea-ad19-000d3ad815e3
  spec:
    config:
      apiTimeout: 15m
      resourceGroup: k8s-rgroup
    provider: azure
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

and the `BackupStorageLocation`
```
apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    creationTimestamp: "2020-02-13T14:15:14Z"
    generation: 84
    labels:
      app.kubernetes.io/instance: velero
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: velero
      helm.sh/chart: velero-2.8.1
    name: default
    namespace: velero
    resourceVersion: "2474103"
    selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/default
    uid: 40e489e8-4e6b-11ea-ad19-000d3ad815e3
  spec:
    config:
      resourceGroup: k8s-backup
      storageAccount: veleromigration
    objectStorage:
      bucket: velero
    provider: azure
  status:
    lastSyncedTime: "2020-02-13T15:39:09.6370355Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
Normally it should locate for disk in `k8s-rgroup` and store the snapshots in `k8s-backup`, but it does the opposite 
do you have any idea @skriss  ?

Thanks

**Comment by skriss** [comment]
@HamzaK8s what value do you have in the `AZURE_RESOURCE_GROUP` key in the `cloud-credentials` secret?

**Comment by HamzaK8s** [comment]
@skriss Thank you, I finally resolved the problem

The documentation was not that clear on this part.

I have another issue on the helm chart. The `envFrom` field for Azure does not work 

If keep the `envFrom`, I'm getting the following errors:
```
time="2020-02-13T14:18:04Z" level=error msg="Error backing up item" backup=velero/ark-test-ns4-1581603471 error="pod volume backup failed: error setting restic cmd env: error getting azure restic env vars: unable to get all required environment variables: the following keys do not have values: AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_SUBSCRIPTION_ID" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:182" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=nginx-deployment-864c87c896-8zfgs namespace=ark-test-ns4-1581603471 resource=pods
```
Deleting manually it fixes the problem. Should I create an Issue on helm-chart repo ?

**Comment by skriss** [comment]
yeah, please create an issue in the chart repo, thanks!

**Comment by ashish-amarnath** [comment]
@HamzaK8s re:
> The documentation was not that clear on this part.

Can you please share what part of the documentation wasn't clear. Also PRs welcome 🙂🙏

**Comment by mereddy22** [comment]
i'm having similar issue with velero 1.4.0 backups are in failed state.
AKS version 1.15.10 and velero version 1.4.0.
velero and storage account is in one resource group.

time="2020-05-27T21:45:55Z" level=info msg="1 errors encountered backup up item" backup=velero/rahulbackup logSource="pkg/backup/backup.go:444" name=kube-prometheus-grafana-0
time="2020-05-27T21:45:55Z" level=error msg="Error backing up item" backup=velero/rahulbackup error="error getting volume info: rpc error: code = Unknown desc = compute.DisksClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/disks/kubernetes-dynamic-pvc-e4d62e31-40e6-47f0-9f4a-ed1763736cc2' under resource group 'TEST_STORAGE-VELEROBACKUP_COMPUTE_RG_01' was not found.\"" logSource="pkg/backup/backup.go:448" name=kube-prometheus-grafana-0
time="2020-05-27T21:46:01Z" level=info msg="Processing item" backup=velero/rahulbackup logSource="pkg/backup/backup.go:371" name=kube-prometheus-prometheus-kube-apiserver-error namespace=monitoring progress= resource=prometheusrules.monitoring.coreos.com
time="2020-05-27T21:46:01Z" level=info msg="Backing up item" backup=velero/rahulbackup logSource="pkg/backup/item_backupper.go:119" name=kube-prometheus-prometheus-kube-apiserver-error namespace=monitoring resource=prometheusrules.monitoring.coreos.com
time="2020-05-27T21:46:01Z" level=info msg="Backed up 621 items out of an estimated total of 688 (estimate will change throughout the backup)" backup=velero/rahulbackup logSource="pkg/backup/backup.go:411" name=kube-prometheus-prometheus-kube-apiserver-error namespace=monitoring progress= resource=prometheusrules.monitoring.coreos.com

Thanks for the help

**Comment by ashish-amarnath** [comment]
@mereddy22 
https://github.com/vmware-tanzu/velero/issues/2117#issuecomment-585825662

**Comment by agateaux** [comment]
Hi,
I'm facing the same kind of issue, but my resource groups seem to be correct.
Velero version : 1.6.3
Azure plugin version : 1.2.1
The error :
`time="2021-09-09T13:09:14Z" level=error msg="Error backing up item" backup=velero/infra-backup error="error getting volume info: rpc error: code = Unknown desc = compute.DisksClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/disks/kubernetes-dynamic-pvc-7f6f8fae-d170-4cff-ad1e-eb6197116ce0' under resource group 'kube-cluster-staging' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\"" logSource="pkg/backup/backup.go:431" name=data-vault-2`
My resource group in backupStorageLocation and volumeSnapshotLocation: `infra`. It's the one where I created my Azure Blob Storage.
My resource group in AZURE_RESOURCE_GROUP: `kube-cluster-staging`. It's the one of my AKS cluster.

Could it be a access right issue ?

**Comment by agateaux** [comment]
So after a lot of digging in examples, it's just a small phrase we should really take care of : 
`WARNING: If you're using AKS, AZURE_RESOURCE_GROUP must be set to the name of the auto-generated resource group that is created when you provision your cluster in Azure, since this is the resource group that contains your cluster's virtual machines/disks.`
It's really not the resource group you specified manually and visible in front of your AKS cluster, it's a Azure generated one you can get with this command : 
`az aks show --query nodeResourceGroup --name <aks-cluster-name> --resource-group <aks-resource-group-manualy-specified> --output tsv`

**Comment by 105636046** [comment]
this is worked for me as well.

**Comment by marradecki** [comment]
Definitely we should be precise in documentation for AKS, there are two different groups to be set as @agateaux mentioned `AZURE_RESOURCE_GROUP` and `AZURE_BACKUP_RESOURCE_GROUP` that should be set to the group where cluster resites. At least this worker for me.
