### ISSUE TITLE
Add search to the website

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#2124]
The website, especially the docs, can really use a search function.

**Comment by carlisia** [comment]
@jonasrosland would you like to take this on?

**Comment by jonasrosland** [comment]
I'll try to tackle this during next week.
I think https://docsearch.algolia.com/ would fit the bill for us.

**Comment by s-pace** [comment]
Great idea indeed 🚀 

Congratulations, your search is now ready!
I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:

- Copy the following CSS/JS snippets and add them to your page

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
apiKey: '3d80f66bb5ecf85f8e2760caef383f24',
indexName: 'velero',
inputSelector: '### REPLACE ME ####',
algoliaOptions: { 'facetFilters': ["version:$VERSION"] },
debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```
- Add a search input in your page if you don't have any yet. Then update the inputSelector value in JS snippet to a CSS selector that targets your search input field.

- Replace `$VERSION` with the version you want to search on.
The list of possible version is hardcoded in the config.
So as of today you have: `master`, `v0.10.0`, `v0.11.0`, `v0.3.0`, `v0.4.0`, `v0.5.0`, `v0.6.0`, `v0.7.0`, `v0.7.1`, `v0.8.0`, `v0.8.1`, `v0.9.0`, `v1.0.0`, `v1.1.0`, `v1.2.0`, `v1.3.0`, `v1.3.1`

For example if you want to refine the search to the version "master" just specify: 
```js
'facetFilters': ["version:master"]
```

- Optionally customize the look and feel [by following the DocSearch documentation](See https://community.algolia.com/docsearch/styling.html)
- You can also [check your configuration in our GitHub repository](https://github.com/algolia/docsearch-configs/blob/master/configs/velero.json)

Please open a pull request if want to leverage your configuration!

Feel free to get back to us if you have any issues or questions regarding the integration.

We'd also be happy to get your feedback and thoughts about DocSearch - so we can continue to improve it.

Have a nice day :)

**Comment by jonasrosland** [comment]
Fantastic comment and assistance @s-pace !
Will try to get this rolling ASAP, thank you!
