### ISSUE TITLE
adjust `velero backup describe` output for nonexistent resource list

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero#2125]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Run `velero backup describe` on an in-progress backup, see:

```
...
Resource List:  <backup resource list not found, this could be because this backup was taken prior to Velero 1.1.0>
...
```

**What did you expect to happen:**

I think we should tweak how this is displayed to users -- we could show a simple "<not found>" text, or just not display the line at all, if a resource list isn't found. There are many potential reasons why a resource list might not exist:

- backup hasn't completed yet
- backup was taken prior to v1.1.0
- resource list failed to upload when backup was taken
- etc.

Velero version (use `velero version`): v1.2.0

**Comment by prydonius** [comment]
Agreed, given we can't differentiate between the last two, it might be better to just remove the line.
