### ISSUE TITLE
Unable to download the CLI

### ISSUE THREAD

**Issue by eladh** [vmware-tanzu/velero#2129]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Following the instruction - unable to download the CLI tgz , for example :
https://github.com/vmware-tanzu/velero/releases/tag/v1.2.0
 just redirect back to the release page

**What did you expect to happen:**
download tgz with the CLI binary

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
@eladh the downloads are at the bottom of the release page, under "Assets", e.g.:

https://github.com/vmware-tanzu/velero/releases/download/v1.2.0/velero-v1.2.0-darwin-amd64.tar.gz
https://github.com/vmware-tanzu/velero/releases/download/v1.2.0/velero-v1.2.0-linux-amd64.tar.gz
