### ISSUE TITLE
Create basic end-to-end test with KinD

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2131]
I don't think we initially need to solve all these cases with 1 PR, but we should do the following:

* Install Velero via `velero install`
* Run a backup of a namespace
* Restore that namespace
* Validate that namespace and all resources were restored
* Validate data inside the volume was restored
* Tear down cluster

Some things we'll need to ensure:

* Buckets are provisioned and cleaned up dynamically
* Snapshots are cleaned up in order to ensure lower billing costs
* Full e2e tests should probably only run on a periodic basis, not every PR.

**Comment by nrb** [comment]
IMO, for the first pass, we don't need snapshots being captured. Just installation and k8s objects backups. That's more than we have today.

**Comment by carlisia** [comment]
>Buckets are provisioned and cleaned up dynamically

Maybe this can be done by scripting the setup of MinIO running on Docker, alongside Kind.

I wanted to drop some resources I've come across:

## evntest
https://book.kubebuilder.io/reference/writing-tests.html

Examples:
- https://github.com/kubernetes-sigs/cluster-api/tree/master/controllers
- https://github.com/microsoft/azure-databricks-operator/tree/master/controllers

It can point to a locally built etcd/apiserver binaries (CI/CD* probably wants this), or can point to an existing cluster (probably ideal for local development, not sure if this or using the built binaries would be faster/better).

* Maybe packaging the etcd and apiserver binaries in a docker container used by a github action would work.

It works with other testing packages that test in the BDD style. I personally think this is a plus, we could benefit from laying out the behavior to test from the time of spec'ing.

## rigging
https://github.com/n3wscott/rigging

Example:
- https://github.com/n3wscott/rigging/tree/master/example

It "leverages lightly templated yaml files". The knative folks are trying to get it into that project. @n3wscott has offered to showcase.

**Comment by carlisia** [comment]
This issue is sorta related in a sense if we are boing to boot up kind to run e2e tests, we might be able to use the same cluster to run integration tests: https://github.com/vmware-tanzu/velero/issues/2518

**Comment by ashish-amarnath** [comment]
Writing down outcomes from some of the discussions we've had around this.

1. We want to decouple cluster provisioning from running of the e2e tests
1. We want to open source the e2e tests for our users to run them if they choose to.
1. All contributors should be able to and be encouraged to run and add e2e tests.
1. Allow users to select which tests they want to run. (something like ginkgo.skip) For example: 
    1. Users may be running on a specific cloud provider and may want to run tests only for that particular cloud provider. Similarly when running in no cloud provider.

**Comment by ashish-amarnath** [comment]
PR #3060 adds a framework for the e2e tests
