### ISSUE TITLE
Openshift randomizes the GID

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#2134]
It would be helpful to document that OS randomizes the gid. For more context:

https://github.com/vmware-tanzu/velero/issues/2023

**Comment by philipp1992** [comment]
Corresponding openshift documentation. 

https://docs.openshift.com/enterprise/3.1/install_config/persistent_storage/pod_security_context.html#fsgroup

**Comment by a-mccarthy** [comment]
We should add a note to the Restic Openshift install section, https://velero.io/docs/v1.5/restic/#install-restic to note that Openshift randomizes group IDs, so when restoring a backup, it will have a randomized GID unless you set the GID. We should also point users to the opeenshift docs that explain this in more detail (see previous comment)

**Comment by a-mccarthy** [comment]
per [this comment](https://github.com/vmware-tanzu/velero/pull/4883#issuecomment-1135077089) on the PR, closing this issue as "wont fix", if you feel like this is still something we should document, please re-open this issue or open a new one. thanks!
