### ISSUE TITLE
Ensure CSI volume restores (same cluster) work

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2140]
Along with the [CSI plug-ins](https://github.com/vmware-tanzu/velero-plugin-for-csi), ensure that restores from a CSI-backed snapshot recreate data in a new persistent volume in same cluster.

This can be achieved by deleting a backed up namespace, then restoring from a back up.

**Comment by ashish-amarnath** [comment]
https://github.com/kubernetes-csi/external-snapshotter/issues/274

**Comment by skriss** [comment]
closed by https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/18
