### ISSUE TITLE
Define and document the `EnableCSI` feature flag

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2142]
Feature flags were introduced with #1798, and we should use this to keep the beta functionality from breaking existing code for our users.

This issue can be considered closed when there's a check for the flag and there's a page documenting the flag's existence - it doesn't need to be too complicated.

**Comment by ashish-amarnath** [comment]
@nrb  Is the idea here to have the feature flag threaded through from the velero client CLI to the server or are the feature flags to be passed to starting the server? To do the former, we'll have to update the definition of the backup CRD and for that reason, I don't think this was the intention. Then, this means we intend to pass the feature flags to the server to control whether or not to use the csi plugin. I think we can do this w/o the feature flags; by not passing the csi plugin in the velero server cli command. WDYT?

**Comment by nrb** [comment]
> Is the idea here to have the feature flag threaded through from the velero client CLI to the server or are the feature flags to be passed to starting the server?

Both, but the idea isn't to communicate via the `Backup` request.

The idea is outlined in the design doc [in this section](https://github.com/vmware-tanzu/velero/blob/master/design/csi-snapshots.md#velero-server-changes). I would like that any logic changes in the velero server process be explicitly enabled, not inferred from plugin inclusion.

Using the feature flag also means that any users not using CSI should be protected from those beta features that are directly in the server code, not in the plugin.

On the client side, we'll need to enable `velero describe` to output information about CSI snapshots in a backup. As such, [this section](https://github.com/vmware-tanzu/velero/blob/master/design/csi-snapshots.md#velero-client-changes) mentions using the feature flag. For the client, the user could use `velero client config set features enableCSI` once to write it into their client-side configuration instead of including it in every command. This is documented as part of the global `--features` argument.

Does that help explain this issue more?

**Comment by tvvignesh** [comment]
@nrb @ashish-amarnath Thanks for this. But, how do we enable feature flags via the helm chart? I have created an issue to ask the same here: https://github.com/vmware-tanzu/helm-charts/issues/105

Also, I am running rook on ceph-csi on top of GCE PD CSI driver (https://cloud.google.com/kubernetes-engine/docs/how-to/gce-pd-csi-driver) in the latest GKE version available in regular channel (1.15.9-gke.24) - Is this supported? Thanks.
