### ISSUE TITLE
Allow cross-namespace restore of CSI snapshots

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2143]
PR #1779 allowed users to restore a snapshot into a different namespace if they were remapping that namespace during a restore.

In order to maintain feature parity, Velero's CSI support should allow users to do the same.

This will likely entail cloning at least the associated `VolumeSnapshot`, and maybe copying the `VolumeSnapshotContent` object, as these two are often in a 1:1 relationship and the `VolumeSnapshotContent` object is what holds the `snapshotHandle` reference.

**Comment by nrb** [comment]
Note that native CSI support for this is planned, but I do not know where it is in the roadmap yet.

**Comment by nrb** [comment]
https://github.com/kubernetes/enhancements/pull/643 is the upstream KEP, and is currently planned for design (but not implementation) during the v1.18 cycle

**Comment by ashish-amarnath** [comment]
Related upstream issues:
https://github.com/kubernetes-csi/external-snapshotter/issues/274
https://github.com/kubernetes-csi/external-snapshotter/issues/273

**Comment by nrb** [comment]
Don't forget KEP 1112 - that may be more relevant.

**Comment by nrb** [comment]
I think we should look at moving this out of v1.4's beta and into v1.5. Thoughts @ashish-amarnath and @skriss?

**Comment by skriss** [comment]
I'm fine with considering it non-release-blocking, yeah.

**Comment by ashish-amarnath** [comment]
From the outset, it seems like a simple change to address this. Need to check some of my assumptions though. I am OK w/ moving this out of 1.4.

**Comment by sshende-catalogicsoftware** [comment]
Submitted a PR for review: https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/82
It is a very small change.

**Comment by arianitu** [comment]
Following up on this, we originally pushed the namespace remapping feature for in-tree volumes and want to help with getting the CSI one in as well. The namespace remapping feature on the original did lead to some security issues, so I can help review remapping behaviour in the CSI plugin as well.

Are there any blockers on this or need assistance? Is the PR from @sshende-catalogicsoftware a valid fix?

**Comment by ashish-amarnath** [comment]
This has been fixed with https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/82
Closing this as done
