### ISSUE TITLE
sync backups' VolumeSnapshotContents into the cluster as part of the backup sync controller

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2145]
Given https://github.com/vmware-tanzu/velero-plugin-for-csi/issues/4, there's a scenario where we may run into an orphaned snapshot.

Assuming a backup is created, with a VolumeSnapshot & a VolumeSnapshotContent in the tarball stored in object storage.

Next, delete the cluster from which the backup was created. Create a new cluster.

Sync the backups in to the new cluster, but do not restore any of the VolumeSnapshots/VolumeSnapshotContents.

From there, as `Backup`s expire, they will be garbage collected. However, if the VolumeSnapshots/VolumeSnapshotContents that reference any garbage collected Backups are restored, what happens to them? Will Kubernetes automatically delete them?

**Comment by skriss** [comment]
Another thought - we talked about and discarded the idea of importing `VolumeSnapshots` into the cluster as part of the backup sync controller's processing, mainly because these are namespaced resources and that might require creating workload namespaces in the cluster, which would be weird. However - should we consider syncing `VolumeSnapshotContents` into the cluster (which are cluster-scoped)? Does that help at all here?

**Comment by nrb** [comment]
Given #2302, I think it might make sense to do that now.

It probably also makes sense to look for the associated `Backup` and/or `VolumeSnapshotContents` when creating a `VolumeSnapshot` on restore and skip restoring if it doesn't exist.

**Comment by skriss** [comment]
I updated the issue title assuming that we want to go down the path of syncing `VolumeSnapshots` into the cluster, but feel free to comment if you see other paths.

**Comment by skriss** [comment]
@nrb @ashish-amarnath I think we've decided against doing this, so this issue can be closed - right?

**Comment by skriss** [comment]
@nrb @ashish-amarnath we need to decide if we're going to do this. I think it potentially still makes sense, since without it we still have the issue of orphaning storage snapshots in certain scenarios (take backup/snapshots in cluster A, lose cluster A, import backups into cluster B, expire backup from cluster B before it's restored -- storage snapshots are now orphaned).

Thoughts?

**Comment by ashish-amarnath** [comment]
Syncing the volumesnapshotcontents into the cluster  to do cleanup in the storage provider makes sense. However, to do that we will have to add the `velero.io/backup-name` label on the volumesnapshotcontents we backup. Or we could sync both volumesnapshots and volumesnapshotcontents and trigger the deletion of the volumesnapshotcontents through the volumesnapshots. I bring this up here to check if we also want to sync the volumesnapshots as @nrb mentioned.

**Comment by nrb** [comment]
Yeah, since there's a possibility have having orphaned storage-level snapshots without syncing CSI objects, I think that at the very least the VSCs need to be synced in, so we have a snapshotHandle.

That way, we don't have to recreate any namespaces or anything. Recreating user-controlled namespaces seems like it starts to violate a boundary into the user workloads, just to account for Velero-created objects. It would mean that our deletion could would need to be aware of these imported-but-not-restored VSCs and select for them, too.

I would also propose, to keep work to a minimum, we get them from the json.gz file that was uploaded in #2323. That way, we don't download the whole backup file and extract in during sync.

**Comment by ashish-amarnath** [comment]
Now, with https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/47, we have the ability to discover just the volumesnapshotcontents that were created during the backup. Once PR #2411 is merged, I'll extend the functionality to make the backup deletion controller take another pass to delete orphaned volumesnapshotcontents.

I think it makes sense to sync volumesnapshots only if the workload namespace exists and volumesnapshotcontents always.
