### ISSUE TITLE
Cannot Get Resource List in Backup

### ISSUE THREAD

**Issue by guiguan** [vmware-tanzu/velero#2146]
**What steps did you take and what happened:**
After a successful backup, when query the backup using `velero backup describe test-backup --details`, I got:

```
Resource List:  <error getting backup resource list: timed out waiting for download URL>
```

The query was slow. On the velero server, I got bunch of:

```
time="2019-12-17T04:38:28Z" level=error msg="Error in syncHandler, re-adding item to queue" controller=downloadrequest error="unsupported download target kind "BackupResourceList"" error.file="/go/src/github.com/heptio/velero/pkg/persistence/object_store.go:366" error.function="github.com/heptio/velero/pkg/persistence.(*objectBackupStore).GetDownloadURL" key=dev/test-backup-20191217153825 logSource="pkg/controller/generic_controller.go:137"
```

**What did you expect to happen:**
It should give me a list of resources in a backup

**Environment:**

- Velero version (use `velero version`): 

```
Client:
        Version: v1.2.0
        Git commit: -
Server:
        Version: v1.0.0
```

- Velero features (use `velero client config get features`): 

```
features: <NOT SET>
```

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-gke.17", GitCommit:"27b48e2b4c9535d185ec945c6a513537e4d116cf", GitTreeState:"clean", BuildDate:"2019-10-21T20:10:26Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

gcp

- OS (e.g. from `/etc/os-release`):

macOS 10.15.1

**Comment by skriss** [comment]
@guiguan this feature was added in v1.1 - so you'll need to upgrade your server to at least v1.1 (but recommend v1.2). See the following for upgrade instructions:

https://velero.io/docs/v1.2.0/upgrade-to-1.2/
https://velero.io/docs/v1.1.0/upgrade-to-1.1/

Feel free to reach out again if you're having further issues.

**Comment by guiguan** [comment]
@skriss oh, I forgot to do `helm repo update` when install the `velero` helm chart. Now it works fine. Thanks!
