### ISSUE TITLE
add an env named `ALIBABA_CLOUD_CREDENTIALS_FILE`

### ISSUE THREAD

**Issue by haoshuwei** [vmware-tanzu/velero#2152]
Can I work to add an env named `ALIBABA_CLOUD_CREDENTIALS_FILE` in [pkg/install/deployment.go](https://github.com/vmware-tanzu/velero/blob/master/pkg/install/deployment.go) and [pkg/install/daemonset.go](https://github.com/vmware-tanzu/velero/blob/master/pkg/install/daemonset.go) which will be used by [velero-plugin-for-alibabacloud](https://github.com/AliyunContainerService/velero-plugin) ?

**Comment by nrb** [comment]
Hi @haoshuwei

A few things:

1) Yes, for now I think a PR adding that env var would be fine. Please note that as part of #1910, we're going to look at ways for plugins to inform Velero of the credentials they need, so this is unlikely to be a permanent solution. However, I don't know when the new approach will be ready, likely not until v1.4 at the earliest. 
1) Please also make a PR for this to the [chart](https://github.com/vmware-tanzu/helm-charts/tree/master/charts/velero)
1) Could you add the [`velero-plugin`](https://github.com/topics/velero-plugin) topic to your GitHub repo? This will help users find your plugin in the list more easily.

**Comment by nrb** [comment]
cc @carlisia
