### ISSUE TITLE
Daemonset is not creating pods on new nodes after k8s cluster restore

### ISSUE THREAD

**Issue by Sushma10037017** [vmware-tanzu/velero#2153]
Hi, We restored our k8s cluster using velero and after restore we are seeing vpc-cni daemonset is not creating pods on new nodes. No related logs found in kubernetes controller manager logs as well. 

We are using 
1. k8s version v1.14.9 
2. vpc cni version(amazon-k8s-cni) v1.4.0
3. velero version v1.1.0

Observed the same issue in two of our restored clusters where the same setup is working fine in other normal k8s clusters.
Any help to figure out this issue is greatly appreciated. Thanks in advance!

**Comment by nrb** [comment]
Hi @Sushma10037017 

Can you provide the output of `velero restore logs <restore name>` and `velero restore describe --details <restore name>` to begin troubleshooting?

**Comment by skriss** [comment]
Closing this out as inactive, feel free to reach out again as needed.
