### ISSUE TITLE
Commercial support for Velero? 

### ISSUE THREAD

**Issue by paulcarlton-ww** [vmware-tanzu/velero#2161]
Does vmware or any other company  provide commercial support for Velero?

**Comment by nrb** [comment]
Hi @paulcarlton-ww, VMware does indeed provide commercial support for Velero via our Tanzu Kubernetes Grid offering. All of the Tanzu open source projects are covered, as is mentioned in our [support matrix](https://kb.vmware.com/s/article/67389).

I'm going to close this issue as I believe this answers your question, but feel free to re-open it if I'm mistaken.

**Comment by michmike** [comment]
hi @paulcarlton-ww and anyone looking at this thread in the future. if you are interested in commercial support for Velero by VMware, contact me privately either in the CNCF or the Kubernetes slack. my username is `m2`. thanks!
