### ISSUE TITLE
Better document schedule logic

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2164]
From a [Slack question](https://kubernetes.slack.com/archives/C6VCGP4MT/p1576878205057100)

>consider a case I have made a backup schedule for daily backup at 3:00 am morning, now the Question .... Suppose on 21 Dec the Schedule was created at 1 am and 1st  backup was successful, so will it Schedule run  backup again same day at 3 am or will start running from next day.

We should have a document describing a few example schedule scenarios to help understand how schedules work, so that this question can be more easily answered in the future.

**Comment by ashish-amarnath** [comment]
Copying @nrb's answer from slack:
> When you use velero create schedule, it shouldn't trigger a backup right away - it should instead wait until the next due period.
So if you created a schedule that runs at 3am at 1am Dec 21, it would not create the first backup until 3am Dec 21.
If you created the schedule at 1am Dec 21, then ran velero create backup --from-schedule <schedule name> at 1:01am Dec 21, it would trigger a backup using the specified schedule's backup parameters and run at the next schedule time. So it would run starting at 1:01am and 3am Dec 21, assuming the 1:01am run was finished.

**Comment by ashish-amarnath** [comment]
https://kubernetes.slack.com/archives/C6VCGP4MT/p1576878205057100
