### ISSUE TITLE
Cluster Migration Documentation not clear - Unusable

### ISSUE THREAD

**Issue by archmangler** [vmware-tanzu/velero#2167]
**Describe the problem/challenge you have**

The documentation link on cluster migration here:

https://velero.io/docs/master/migration-case/

a) Does not indicate how to specify the new backup location when restoring a backup from the newly created backup location that points to the-cluster-that-must-be-migrated. Should it be passed as an argument to the "velero create restore from <backup> ...." command?

Because of this the attempt to migrate the cluster stops at the point where the second backup location pointing to the source cluster's container is created. There does not seem to be a way to indicate that the backup desired must come from the newly created backup location.

b) There does not seem to be clear documentation on specifying additional backup locations for each cloud vendor (Azure in my case). This makes the migration process even more uncertain.

Note: This test is being carried out on azure cloud.

**Describe the solution you'd like**

- Demonstrate using exact commands in the documentation how the second backup location is created, including the authentication configuration, for each of the major cloud vendors (Azure, AWS, etc ...)
- Demonstrate the exact command(s) use to restore a backup from a particular storage location.

**Anything else you would like to add:**

The velero command to restore from a particular backup doesn't seem to include an option to specify the exact backup location (container) from which the backup must be extracted. It's hard to understand how the documented migration process will work without this feature.

Some clarification would be appreciated here.

**Environment:**

- Velero version (use `velero version`):

v1.1.0

- Kubernetes version (use `kubectl version`):

1.14.8

- Kubernetes installer & version:

AKS 1.14.8

- Cloud provider or hardware configuration:

Azure, Azure blob storage

- OS (e.g. from `/etc/os-release`):

Ubuntu Linux

**Comment by eleanor-millman** [comment]
Note for engineers working on this: https://velero.io/docs/v1.8/migration-case/ is the newest link to the migration docs

**Comment by a-mccarthy** [comment]
@reasonerjt can you provide an update here, are we still planning to work on this for 1.9?
