### ISSUE TITLE
Backup of particular storage with a single namespace

### ISSUE THREAD

**Issue by saiharshitachava** [vmware-tanzu/velero#2184]
**What steps did you take and what happened:**

This is rather a how to question..I dint find any documentation for this..

Does anybody know how can we take a backup of single namespace along with particular storage class
When I take a namespace backup now it doesnt come with storage class and with out my nfs storage  class my pv and pvc are not working as expected..

If I include cluster-resources there is a lot coming in..though there is lot coming can I pick the storage class I need as part of restore?

I ran the below commands to try this

velero backup create pvtest2 --include-namespaces veleropvtest --snapshot-volumes --include-cluster-resources=true --include-resources=storageclasses

It only takes the storage class as backup and not the namespace..

**Comment by skriss** [comment]
@saiharshitachava unfortunately you can't do exactly what you're trying to do out-of-the-box with Velero.  You could try one of the following options:

- use `--include-cluster-resources` on backup to get all cluster resources, then on restore, specifically restore storage classes (via `--include-resources storageclasses`), followed by a subsequent restore of your namespace (via `--include-namespaces`).
- set up a unique label on your NFS storage class, then do one backup of storageclasses that uses the label selector to only get the NFS storage class, and a separate backup of your namespace. Then you'd do two restores.
- write a custom backup item action plugin that backs up the storage class used by a PV as an "additional item". More details on plugins here: https://velero.io/docs/v1.2.0/overview-plugins/ and https://velero.io/docs/v1.2.0/custom-plugins/

Hopefully one of these is workable for you.

**Comment by skriss** [comment]
Closing this out, but feel free to reach out again as needed.

**Comment by saiharshitachava** [comment]
Can you ellaborate more on the second option on how can I get a single storage class.Something like below would work in getting a single storage class?

velero backup create test --include resources storageclasses --label-selector app=test?

**Comment by skriss** [comment]
@saiharshitachava yes, that's right. As long as the `app=test` label is *only* on the NFS storage class, this should give you just that storage class.
