### ISSUE TITLE
unable to find summary in restic backup command output

### ISSUE THREAD

**Issue by never1701** [vmware-tanzu/velero#2185]
**What steps did you take and what happened:**
We have a daily backup of our cluster with 273 persistent volumes. We are seeing separate restic errors on 2 volumes in particular.  Same error with same volumes but all the pvs are deployed with the same helm chart aside from namespace.  

time="2020-01-10T02:21:42Z" level=error msg="Error backing up item" backup=velero/cluster-daily-20200110020017 error="pod volume backup failed: error getting volume path on host: expected one matching path, got 0" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:182" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=primary-65d4dcd848-nzczm namespace= resource=pods

 

time="2020-01-10T02:28:37Z" level=error msg="Error backing up item" backup=velero/cluster-daily-20200110020017 error="pod volume backup failed: error running restic backup, stderr=: unable to find summary in restic backup command output" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:182" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=primary-68dd48b4d7-lprj7 namespace= resource=pods

Errors follow volumes if backed up as single namespace backups.  
schedule command: 
 velero schedule create cluster-daily --schedule="0 6 * * *" --snapshot-volumes=false --exclude-namespaces flowable

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
https://gist.github.com/never1701/6546d747a652dca4cbc5bf9d97471ef7
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
https://gist.github.com/never1701/a95f9a9bc88dfaac9ba57ec7efe75f4a

**Anything else you would like to add:**
We have seen these errors before, during those times we resolved them by deleting the velero deployment and the bucket and starting from scratch.  For fsdb-1644 namespace deployment does match the format for hostPath and was successfully backing up until 5 days ago.  

Basic troubleshooting of restarting velero and restic pods done.  Comparing pod config in the case of the hostPath complaint.  

fsdb-2880 was just added on 1/8/20 and has never completed but I do see the restic repo created in GCS but with no data.   

**Environment:**

- Velero version (use `velero version`): v.1.2
- Kubernetes version (use `kubectl version`): v1.14.6
- Cloud provider or hardware configuration: GCS
- OS (e.g. from `/etc/os-release`): centos

**Comment by never1701** [comment]
Pod output for fsdb-1644 
https://gist.github.com/never1701/ed0abffed6952de6cb92cad5c6f0826d

**Comment by never1701** [comment]
pod output for fsdb-2880 
https://gist.github.com/never1701/237d537f163bd55b31a03d063646a122

**Comment by never1701** [comment]
Resolved the issue with "pod volume backup failed: error getting volume path on host: expected one matching path, got 0"  I observed that we had one running pod and one evicted pod for that namespace.  Deleting the evicted pod allowed the restic backup to complete normally.

**Comment by never1701** [comment]
Updated description to reflect remaining unresolved restic issue.

**Comment by florianbegusch** [comment]
Is the restic's daemonset allowed to access the podvolume mount path?  
I suggest to check whether restic does not have permission to access it. As a side-note, in Openshift the daemonset has to be  ["privileged"](https://velero.io/docs/v1.2.0/restic/#instructions) (securityContext in openshift).  
If it is not I do also get:
```shell 
error="pod volume backup failed: error running restic backup, stderr=: unable to find summary in restic backup command output
```

**Comment by never1701** [comment]
@florianbegusch thanks for the hint.  Didn't end up being security but a bad volume mount.  DF reported the mount and pod didn't throw any errors but reading and writing to the pv failed with i/o errors.  Restarted the pod and everything is good now.  Got a successful backup of the pv with velero.  Thanks!
