### ISSUE TITLE
Unable to create lock in backend

### ISSUE THREAD

**Issue by Stolr** [vmware-tanzu/velero#2193]
**What steps did you take and what happened:**

I deleted multiple backups.

`velero backup delete  tools-b-gitlab-backup-pr-20200110012032 tools-b-gitlab-backup-pr-20200112012003 tools-b-gitlab-backup-pr-20200113012004`

One was deleted successfuly and the two others are stucks :
```
tools-b-gitlab-backup-pr-20200112012003       Deleting                     2020-01-12 02:20:03 +0100 CET   4d        default            <none>
tools-b-gitlab-backup-pr-20200110012032       Deleting                     2020-01-10 02:20:32 +0100 CET   2d        default            <none>
```
` velero backup describe  tools-b-gitlab-backup-pr-20200110012032`

```
Deletion Attempts (1 failed):
  2020-01-14 10:19:15 +0100 CET: Processed
  Errors:
    restic repository is not ready: error running command=restic snapshots --repo=s3:http://oca-miniolb.oca.local/velero/tools-b/restic/ok106-gitlab-pr --password-file=/tmp/velero-restic-credentials-ok106-gitlab-pr375672370 --cache-dir=/scratch/.cache/restic --last, stdout=, stderr=Fatal: unable to create lock in backend: repository is already locked exclusively by PID 1115 on velero-79845659c-bwb25 by  (UID 0, GID 0)
lock was created at 2020-01-14 09:16:35 (40.790581918s ago)
storage ID 8526648a
: exit status 1
    restic repository is not ready: error running command=restic snapshots --repo=s3:http://oca-miniolb.oca.local/velero/tools-b/restic/ok106-gitlab-pr --password-file=/tmp/velero-restic-credentials-ok106-gitlab-pr375672370 --cache-dir=/scratch/.cache/restic --last, stdout=, stderr=Fatal: unable to create lock in backend: repository is already locked exclusively by PID 1115 on velero-79845659c-bwb25 by  (UID 0, GID 0)
lock was created at 2020-01-14 09:16:35 (40.790581918s ago)
storage ID 8526648a
: exit status 1
```

Theses locks happens very often. Most of the time I need to wait for the lock to be deleted ( around 30mins each time ).

**Comment by skriss** [comment]
@Stolr what version of velero are you using? The velero server logs prior to this happening would also be helpful, preferably at debug level (https://velero.io/docs/v1.2.0/troubleshooting/#getting-velero-debug-logs).

**Comment by skriss** [comment]
@Stolr just checking to see if you could provide the additional info requested, thanks.

**Comment by skriss** [comment]
Closing this out as inactive, feel free to reach out again if you can provide additional info.

**Comment by maoyangLiu** [comment]
@Stolr  I met the same question, have you solved it
