### ISSUE TITLE
restic pod will restart when the restic backup command return error.

### ISSUE THREAD

**Issue by wukaiying** [vmware-tanzu/velero#2213]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
file name: pkg/restic/exec_commands.go at line 88
if the `cmd.Stdout` return nil, `getLastLine(stdoutBuf.Bytes())` will make the go func panic, it cased restic pod restart.
```go
func RunBackup(backupCmd *Command, log logrus.FieldLogger, updateFunc func(velerov1api.PodVolumeOperationProgress)) (string, string, error) {
	// buffers for copying command stdout/err output into
	stdoutBuf := new(bytes.Buffer)
	stderrBuf := new(bytes.Buffer)

	// create a channel to signal when to end the goroutine scanning for progress
	// updates
	quit := make(chan struct{})

	cmd := backupCmd.Cmd()

	cmd.Stdout = stdoutBuf
	cmd.Stderr = stderrBuf

	cmd.Start()

	go func() {
		ticker := time.NewTicker(backupProgressCheckInterval)
		for {
			select {
			case <-ticker.C:
				lastLine := getLastLine(stdoutBuf.Bytes())
				stat, err := decodeBackupStatusLine(lastLine)
``` 

**What did you expect to happen:**
restic pod not need restart, and show the  error log in restic pod about `cmd.Stderr`

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
Client: 1.2.0
Server: 1.2.0
- Velero features (use `velero client config get features`): 
features: <NOT SET>
- Kubernetes version (use `kubectl version`):

- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
macos mojave 10.14.6

**Comment by skriss** [comment]
@wukaiying I believe we've fixed this with #2231, so closing this out - feel free to reopen as needed. Note that this fix is included in the `v1.3.0-beta.1` release and will officially ship with `v1.3.0`.
