### ISSUE TITLE
unable to install velero client in ubuntu. no tarball found.

### ISSUE THREAD

**Issue by Chams91** [vmware-tanzu/velero#2220]

**Comment by skriss** [comment]
@Chams91 you'll need to use "option 2" at https://velero.io/docs/v1.2.0/basic-install/#install-the-cli to download the release tarball from github, extract it, and move it to a location in your `$PATH`.

**Comment by skriss** [comment]
Feel free to reach out again if you have further issues!

**Comment by Chams91** [comment]
i do believe the documentation along with the github readme page should be updated As nothing indicates the tarball name. i tried "wget https://github.com/vmware-tanzu/velero/releases/tag/v1.2.0/velero-v1.2.0-linux-amd64.tar.gz" but that isn´t a valid file. plz advice as i am having real problems installing the cli. i tried v1.1.0 but i guess it is not supported.

**Comment by skriss** [comment]
If you go to the release (https://github.com/vmware-tanzu/velero/releases/latest), at the bottom under "Assets" you'll see all the tarballs for the different platforms. Assuming you want linux/amd64 -- the right one is https://github.com/vmware-tanzu/velero/releases/download/v1.2.0/velero-v1.2.0-linux-amd64.tar.gz
