### ISSUE TITLE
Failing to connect to velero server

### ISSUE THREAD

**Issue by jnaulty** [vmware-tanzu/velero#2232]
**What steps did you take and what happened:**
Tried to run `velero version`

**What did you expect to happen:**
A response from the client and server printing to console the versions they are running.

**The output of the following commands will help us better understand what's going on**:

* `velero version`
```
➜  ~ velero version                         
Client:
        Version: v1.2.0
        Git commit: 5d008491bbf681658d3e372da1a9d3a21ca4c03c
<error getting server version: timed out waiting for server status request to be processed>
```
* `kubectl logs deployment/velero -n velero`
```
E0130 19:53:49.255161       1 reflector.go:125] github.com/vmware-tanzu/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.BackupStorageLocation: Get https://172.20.0.1:443/apis/velero.io/v1/namespaces/velero/backupstoragelocations?limit=500&resourceVersion=0: http2: no cached connection was available
E0130 19:53:49.256312       1 reflector.go:125] github.com/vmware-tanzu/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.Backup: Get https://172.20.0.1:443/apis/velero.io/v1/namespaces/velero/backups?limit=500&resourceVersion=0: http2: no cached connection was available
E0130 19:53:49.257522       1 reflector.go:125] github.com/vmware-tanzu/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.ServerStatusRequest: Get https://172.20.0.1:443/apis/velero.io/v1/namespaces/velero/serverstatusrequests?limit=500&resourceVersion=0: http2: no cached connection was available
```

* `velero get backup`
```
➜  ~ velero get backup
NAME   STATUS   CREATED   EXPIRES   STORAGE LOCATION   SELECTOR
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.2.0
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`):
```
kubectl version --short 
Client Version: v1.17.2
Server Version: v1.12.10-eks-aae39f
```
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04 (bionic)

**Comment by carlisia** [comment]
Hey @jnaulty could you run `velero install` again?

**Comment by jnaulty** [comment]
I installed with `helm`

**Comment by carlisia** [comment]
Yes, hard to tell what brought you to this point, but I suspecting restarting the installation or restarting something would get it going. Closing it!
