### ISSUE TITLE
fails to restore a PV in a new cluster in a new Project on GKE

### ISSUE THREAD

**Issue by izzie88** [vmware-tanzu/velero#2245]
i successfully created a backup of a namespace in cluster A in project A in GCP

When i try to restore the backup in Cluster B in Project B, the PV fails to restore giving the error:
cluster:  error restoring persistentvolumes/pvc-78e468b5-65ed-11e9-9128-4201aca8000a: persistentvolumes "pvc-78e468b5-65ed-11e9-9128-4201aca8000a" is forbidden: error querying GCE PD volume restore-c94fe172-71ab-4794-a663-5c4b9bf5b86e: GCE persistent disk not found: diskName="restore-c94fe172-71ab-4794-a663-5c4b9bf5b86e" zone="us-west2-a"

* `kubectl logs deployment/velero -n velero`:
    https://gist.github.com/izzie88/af44712c32b4bde056daf485ce20ec01
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
      https://gist.github.com/izzie88/abf8a6c27c0e2a3c07c5b888998abf0e
* `velero backup logs <backupname>`
     https://gist.github.com/izzie88/10d840a2f6414c497b295feda0d09b77
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
    https://gist.github.com/izzie88/e08c3d68e2350d1f9ce80fa790aeadc4
* `velero restore logs <restorename>`
     https://gist.github.com/izzie88/c6524d3e8f4802bf5825c9f46ea8454a

the issue i thin i am having is restoring a deployment that has a dynamic PV on GKE.
I get this error when restore is completed.
luster:  error restoring persistentvolumes/pvc-78e468b5-65ed-11e9-9128-4201aca8000a: persistentvolumes "pvc-78e468b5-65ed-11e9-9128-4201aca8000a" is forbidden: error querying GCE PD volume restore-96b59d07-d36d-4def-a5d4-d343643b45c1: GCE persistent disk not found: diskName="restore-96b59d07-d36d-4def-a5d4-d343643b45c1" zone="us-west2-a"
every other deployment that does not have a PV restores just fine.

**Environment:**

- Velero version (use `velero version`): 
  Client:
        Version: v1.0.0
        Git commit: -
Server:
        Version: v1.0.0
- Velero features (use `velero client config get features`): 
   features: <NOT SET>
- Kubernetes version (use `kubectl version`):
   Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Pla
tform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.23", GitCommit:"93457f9dac45d5f95c2c609232e1ff2343c72684", GitTreeState:"clean", BuildDate:"2020-01-14T06:01:01Z", GoVersion:"go1.12.11b4", Compil
er:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
   1.13.11-gke.23
- Cloud provider or hardware configuration:
   Google
- OS (e.g. from `/etc/os-release`):
  PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by carlisia** [comment]
I'd like to start here: long shot maybe, but could this be your problem? 

https://acloud.guru/forums/kubernetes-deep-dive/discussion/-LOgoJnxCa74TbTuD1Ie/GKE:%20disk%20not%20found%20although%20it%20is%20created

**Comment by skriss** [comment]
@izzie88 my best guess is that this is related to doing a cross-project restore. Have you followed the detailed instructions at https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/master/examples/gcp-projects.md?

I know one important part of this is configuring the right `project` in your VolumeSnapshotLocation's config in the cluster you're restoring to. You can find more documentation on this at https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/master/volumesnapshotlocation.md.

Let us know if you get this resolved!

**Comment by skriss** [comment]
@izzie88 were you able to get this working?

**Comment by izzie88** [comment]
Hello,

I got this resolved following the examples.

Many thanks for the assistance.

**Comment by skriss** [comment]
glad you got it working - closing this out as resolved.

**Comment by harikrim** [comment]
Hi @skriss 
Facing same issue even though i have configured right project

**Comment by trangnt-98** [comment]
face issue same with @harikrim, have any help, please @carlisia ?

**Comment by jgacek-baracoda** [comment]
I have the same issue as @devpaops - disk is created in custom snapshot location project. Not in the project where I want to restore.
