### ISSUE TITLE
[Question] How to use restic with s3 (minio) as backend? 

### ISSUE THREAD

**Issue by NeXT405** [vmware-tanzu/velero#2250]
I can not find any informations about this in the documentation. 

At the moment velero works great in my cluster even with restic enabled. But for restic I would like to use s3 as backend as well. 

According to this issue it seems to be possible:
https://github.com/vmware-tanzu/velero/issues/2198

Is there a part in the documnetation or an example to set this up? 

Thanks in advance.

**Comment by carlisia** [comment]
Hi, yes, that's possible. Please take a look at this instruction: https://velero.io/docs/v1.2.0/contributions/minio/.

Closing this for now, we can reopen if needed.
