### ISSUE TITLE
Velero backup delete doesnt work  for partially failed backup

### ISSUE THREAD

**Issue by binnythomas-1989** [vmware-tanzu/velero#2253]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
velero backup has partially failed. Hence tried removing the backup 

velero backup delete ci-s1e2prod-20200207001018 
Are you sure you want to continue (Y/N)? Y
An error occurred: DeleteBackupRequest.velero.io "ci-s1e2prod-20200207001018-jcl8x" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"velero.io/v1", "kind":"DeleteBackupRequest", "metadata":map[string]interface {}{"creationTimestamp":"2020-02-07T11:26:45Z", "generateName":"ci-s1e2prod-20200207001018-", "generation":1, "labels":map[string]interface {}{"velero.io/backup-name":"ci-s1e2prod-20200207001018", "velero.io/backup-uid":"b42a8eba-4946-11ea-8733-fa163e18a7f2"}, "name":"ci-s1e2prod-20200207001018-jcl8x", "namespace":"velero", "uid":"b931c5be-499c-11ea-9699-fa163e0d66f3"}, "spec":map[string]interface {}{"backupName":"ci-s1e2prod-20200207001018"}, "status":map[string]interface {}{"errors":interface {}(nil), "phase":""}}: validation failure list:
status.phase in body should be one of [New InProgress Processed]

**What did you expect to happen:**
i expected the backup to be deleted.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

```
velero backup get ci-s1e2prod-20200207001018
NAME                         STATUS                      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
ci-s1e2prod-20200207001018   PartiallyFailed (1 error)   2020-02-07 00:10:18 +0000 GMT   2d        s1e2-validation    <none>
```

```
 velero backup logs  ci-s1e2prod-20200207001018
An error occurred: DownloadRequest.velero.io "ci-s1e2prod-20200207001018-20200207121233" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"velero.io/v1", "kind":"DownloadRequest", "metadata":map[string]interface {}{"creationTimestamp":"2020-02-07T12:12:33Z", "generation":1, "name":"ci-s1e2prod-20200207001018-20200207121233", "namespace":"velero", "uid":"1f247288-49a3-11ea-8733-fa163e18a7f2"}, "spec":map[string]interface {}{"target":map[string]interface {}{"kind":"BackupLog", "name":"ci-s1e2prod-20200207001018"}}, "status":map[string]interface {}{"downloadURL":"", "expiration":interface {}(nil), "phase":""}}: validation failure list:
status.phase in body should be one of [New Processed]
bintho01@C02YH0BNJHD5 artifactory $ velero get backup | grep ci-s1e2prod-20200207001018
ci-s1e2prod-20200207001018                      PartiallyFailed (1 error)   2020-02-07 00:10:18 +0000 GMT   2d        s1e2-validation    <none>
```
```
velero describe backup ci-s1e2prod-20200207001018
Name:         ci-s1e2prod-20200207001018
Namespace:    velero
Labels:       velero.io/schedule-name=ci-s1e2prod
              velero.io/storage-location=s1e2-validation
Annotations:  <none>

Phase:  PartiallyFailed (run `velero backup logs ci-s1e2prod-20200207001018` for more information)

Errors:    1
Warnings:  0

Namespaces:
  Included:  ci
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  s1e2-validation

Snapshot PVs:  true

TTL:  72h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-02-07 00:10:18 +0000 GMT
Completed:  2020-02-07 01:10:20 +0000 GMT

Expiration:  2020-02-10 00:10:18 +0000 GMT

Persistent Volumes: <none included>
```

```
velero backup logs ci-s1e2prod-20200207001018
An error occurred: DownloadRequest.velero.io "ci-s1e2prod-20200207001018-20200207121605" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"velero.io/v1", "kind":"DownloadRequest", "metadata":map[string]interface {}{"creationTimestamp":"2020-02-07T12:16:05Z", "generation":1, "name":"ci-s1e2prod-20200207001018-20200207121605", "namespace":"velero", "uid":"9d8037dc-49a3-11ea-9699-fa163e0d66f3"}, "spec":map[string]interface {}{"target":map[string]interface {}{"kind":"BackupLog", "name":"ci-s1e2prod-20200207001018"}}, "status":map[string]interface {}{"downloadURL":"", "expiration":interface {}(nil), "phase":""}}: validation failure list:
status.phase in body should be one of [New Processed]
bintho01@C02YH0BNJHD5 artifactory $ 
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  v1.2
    image: velero/velero:v1.2.0

- Velero features (use `velero client config get features`):  
- Kubernetes version (use `kubectl version`): 1.14

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by carlisia** [comment]
Hey @binnythomas-1989, this is definitely supposed to work!

![image](https://user-images.githubusercontent.com/16508/74075574-e2c37000-49c7-11ea-8618-625eb72ae6ad.png)

Take a look at this discussion and maybe remove all the velero CRDs, or remove everything and reinstall Velero 1.2.0, to make sure the CRD schema is up to date:

https://github.com/vmware-tanzu/velero/issues/2030#issuecomment-548546454

**Comment by binnythomas-1989** [comment]
The issue was around client and server version miss match. Its fixed.
