### ISSUE TITLE
Missing PV snapshot in GKE causes odd restore behavior

### ISSUE THREAD

**Issue by gorzek** [vmware-tanzu/velero#2255]
**What steps did you take and what happened:**

Note, we are operating on GKE.

We have a script which scales down our Kubernetes applications to zero replicas so there's no disk activity when we snapshot them.

Our backup is run like so:

`
  velero backup create \
    "${BACKUP_NAME}" \
    --include-cluster-resources=true \
    --exclude-resources=storageclasses.storage.k8s.io \
    --include-resources persistentvolumeclaims,persistentvolumes \
    --snapshot-volumes=true \
    --exclude-namespaces=clu-inf-all,clu-inf-tls,velero,default \
    --ttl="${BACKUP_TTL}" \
    --alsologtostderr \
    --wait
`

We then restored this backup to the same cluster, using this command:

`
  velero restore create \
  --from-backup "${BACKUP_NAME}" \
  --allow-partially-failed=true \
  --exclude-resources=storageclasses.storage.k8s.io \
  --include-resources persistentvolumeclaims,persistentvolumes \
  --restore-volumes=true \
  --exclude-namespaces=clu-inf-all,clu-inf-tls,velero,default \
  --alsologtostderr \
  --wait
`

We received this error during the restore:

```
Name:         prs-st2-snapshot-mon-feb-03-2020-16h-05m-20200207140517
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:  PartiallyFailed (run 'velero restore logs prs-st2-snapshot-mon-feb-03-2020-16h-05m-20200207140517' for more information)

Errors:
  Velero:     <none>
  Cluster:  error executing PVAction for persistentvolumes/pvc-387c41e0-0d25-11ea-b5bc-42010ae6ff03: rpc error: code = Unknown desc = googleapi: Error 404: The resource 'projects/prs-com-st2-9963-64099/global/snapshots/gke-prs-st2-ge4-001-56-pvc-ec48bfee-0d1c-4a55-a5fd-488f57a5d51c' was not found, notFound
  Namespaces: <none>

Backup:  prs-st2-snapshot-mon-feb-03-2020-16h-05m

Namespaces:
  Included:  *
  Excluded:  clu-inf-all, clu-inf-tls, velero, default

Resources:
  Included:        persistentvolumeclaims, persistentvolumes
  Excluded:        storageclasses.storage.k8s.io, nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  true
```

The restore log also says:

```
{"cmd":"/velero","level":"info","logSource":"pkg/restore/add_pv_from_pvc_action.go:66","msg":"Adding PV pvc-387c41e0-0d25-11ea-b5bc-42010ae6ff03 as an additional item to restore","pluginName":"velero","restore":"velero/prs-st2-snapshot-mon-feb-03-2020-16h-05m-20200207140517","time":"2020-02-07T14:05:40Z"}
{"level":"info","logSource":"pkg/restore/restore.go:800","msg":"Skipping persistentvolumes/pvc-387c41e0-0d25-11ea-b5bc-42010ae6ff03 because it's already been restored.","restore":"velero/prs-st2-snapshot-mon-feb-03-2020-16h-05m-20200207140517","time":"2020-02-07T14:05:40Z"}
```

What it appears happened is that disk snapshot `gke-prs-st2-ge4-001-56-pvc-ec48bfee-0d1c-4a55-a5fd-488f57a5d51c` went missing or was never created. We have 21 PVs in this cluster, and we have snapshots for 20 of them. It is unclear whether the snapshot originally failed--if so, the backup logs do not report it:

```
{"backup":"velero/prs-st2-snapshot-mon-feb-03-2020-16h-05m","group":"v1","level":"info","logSource":"pkg/backup/item_backupper.go:169","msg":"Backing up item","name":"pvc-387c41e0-0d25-11ea-b5bc-42010ae6ff03","namespace":"","resource":{"Group":"","Resource":"persistentvolumes"},"time":"2020-02-03T16:05:27Z"}
{"backup":"velero/prs-st2-snapshot-mon-feb-03-2020-16h-05m","group":"v1","level":"info","logSource":"pkg/backup/item_backupper.go:395","msg":"Executing takePVSnapshot","name":"pvc-387c41e0-0d25-11ea-b5bc-42010ae6ff03","namespace":"","resource":{"Group":"","Resource":"persistentvolumes"},"time":"2020-02-03T16:05:27Z"}
{"backup":"velero/prs-st2-snapshot-mon-feb-03-2020-16h-05m","group":"v1","level":"info","logSource":"pkg/backup/item_backupper.go:446","msg":"Got volume ID for persistent volume","name":"pvc-387c41e0-0d25-11ea-b5bc-42010ae6ff03","namespace":"","persistentVolume":"pvc-387c41e0-0d25-11ea-b5bc-42010ae6ff03","resource":{"Group":"","Resource":"persistentvolumes"},"time":"2020-02-03T16:05:27Z","volumeSnapshotLocation":"default"}
{"backup":"velero/prs-st2-snapshot-mon-feb-03-2020-16h-05m","group":"v1","level":"info","logSource":"pkg/backup/item_backupper.go:466","msg":"Getting volume information","name":"pvc-387c41e0-0d25-11ea-b5bc-42010ae6ff03","namespace":"","persistentVolume":"pvc-387c41e0-0d25-11ea-b5bc-42010ae6ff03","resource":{"Group":"","Resource":"persistentvolumes"},"time":"2020-02-03T16:05:27Z","volumeID":"gke-prs-st2-ge4-001-56-pvc-387c41e0-0d25-11ea-b5bc-42010ae6ff03"}
{"backup":"velero/prs-st2-snapshot-mon-feb-03-2020-16h-05m","group":"v1","level":"info","logSource":"pkg/backup/item_backupper.go:472","msg":"Snapshotting persistent volume","name":"pvc-387c41e0-0d25-11ea-b5bc-42010ae6ff03","namespace":"","persistentVolume":"pvc-387c41e0-0d25-11ea-b5bc-42010ae6ff03","resource":{"Group":"","Resource":"persistentvolumes"},"time":"2020-02-03T16:05:27Z","volumeID":"gke-prs-st2-ge4-001-56-pvc-387c41e0-0d25-11ea-b5bc-42010ae6ff03"}
{"backup":"velero/prs-st2-snapshot-mon-feb-03-2020-16h-05m","group":"v1","level":"info","logSource":"pkg/backup/item_backupper.go:163","msg":"Skipping item because it's already been backed up.","name":"pvc-387c41e0-0d25-11ea-b5bc-42010ae6ff03","namespace":"","resource":{"Group":"","Resource":"persistentvolumes"},"time":"2020-02-03T16:05:48Z"}
```

The final message in that log section suggests that it may have been skipped, despite being present? However, we received `already been backed up` messages for 18 of the 21 PVs, and the rest were fine, so that is not a likely factor.

The restore log only says that the PV wasn't restored because it already had been, but again, that occurs 18 times in the restore log and did not seem to affect any other PVs. (It is possible the PVs did not change between the snapshot and the restore, in which case this would make sense.)

**What did you expect to happen:**

We expected the PV to be properly restored from the snapshot. Instead, the snapshot was missing, and while `velero describe backup` accurately noted this, the actual restore logs did not. We are as yet uncertain why the snapshot is missing, if it was ever created, but it's concerning that the restoration process does not verify the existence of all snapshots before attempting a restore.

**Environment:**

- Velero version (use `velero version`): 2.1.0
- Velero features (use `velero client config get features`):  <NOT SET>
- Kubernetes version (use `kubectl version`): client 1.15.9, server 1.14.8-gke.33
- Kubernetes installer & version: 1.14.8-gke.33
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 9 (stretch) (container)

I have tried to provide the most relevant lots to save space, but let me know if further log detail is needed.

**Comment by carlisia** [comment]
This sounds related: https://github.com/vmware-tanzu/velero/issues/2212

**Comment by gorzek** [comment]
I agree, this looks like the same issue given that Velero recorded success and no errors were reported, but one of the snapshots was missing.

**Comment by skriss** [comment]
@gorzek see https://github.com/vmware-tanzu/velero/issues/2212#issuecomment-588477821 - if you could try this out too, maybe we can shed some more light on what's going on

**Comment by skriss** [comment]
@gorzek were you able to test this out?

**Comment by gorzek** [comment]
Not yet, hopefully next week.

**Comment by skriss** [comment]
closing this out as inactive, feel free to reach out again as needed.
