### ISSUE TITLE
better document using `spec.publicUrl` to access logs/backups from minIO

### ISSUE THREAD

**Issue by a4nowgh** [vmware-tanzu/velero#2256]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
This occurs after when using minIO storage location.  

velero backup create <jobName> --storage-location <minIO_storage>

velero backup describe <jobName> --details

Output:
Request List: request failed: garbled special characters/encoding repeat repeat etc...

The rest of the output looks OK

NOTE: I am able to perform successful restores with this backup

**What did you expect to happen:**
Show Request List

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Resource lists from backups to my other non-minIO S3-Compliant bucket display OK

**Environment:**
- minIO Version: 2019-04-17T17:41:56Z
- minIO Release-tag: RELEASE.2019-04-17T17-41-56Z
- Velero version: v1.2.0
- Velero features:
- Kubernetes Client version: v1.15.3
- Kubernetes Server version: v1.14.6
- Cloud provider or hardware configuration: aws
- OS: Ubuntu 18.04.3 LTS

**Comment by carlisia** [comment]
Hm this is odd. Mind dumping the actual output, it might be helpful to see.

Is this an on-prem cluster you are backing up?

**Comment by a4nowgh** [comment]
Yes, this is an on-prem cluster we are backing up to.  Below is the requested output...thx

./velero backup describe minio-backup --details
Name: minio-backupNamespace: veleroLabels:    velero.io/storage-location=minioAnnotations: <none>
Phase:  Completed
Namespaces:  Included: grafana  Excluded: <none>
Resources:  Included: *  Excluded: <none>  Cluster-scoped: auto
label selector: <none>
Storage Location: minio
Snapshot PVs: auto
TTL: 720h0m0s
Hooks: <none>
Backup Format Version: 1
Started: XXXXXCompleted: XXXXX

Expiration: XXXXX
Resource List: <error getting backup resource list: request failed: garbled garbled garbled....
Persistent Volumes: <none included>
Restic Backups:  Completed:    grafana/grafana-56d485dbb8-8rhqf: config, ldap, storage

    On Friday, February 7, 2020, 7:43:25 PM EST, Carlisia Campos <notifications@github.com> wrote:  
 
 
Hm this is odd. Mind dumping the actual output, it might be helpful to see.

Is this an on-prem cluster you are backing up?

**Comment by nrb** [comment]
@a4nowgh Are you using https on your Minio installation?

**Comment by a4nowgh** [comment]
Yes.

    On Monday, February 10, 2020, 11:56:41 AM EST, Nolan Brubaker <notifications@github.com> wrote:  
 
 
@a4nowgh Are you using https on your Minio installation?

**Comment by nrb** [comment]
Here's my guess - the Velero client is using your BackupStorageLocation's `spec.config.s3url`, which is an https URL, and getting the encrypted contents. If you add an http URL to `spec.config.publicUrl`, the velero client should be able to download the resource list in readable format.

If my suspicion is correct, then the `velero restore logs` and `velero backup logs` commands should also return encrypted values.

The reason this happens is that with AWS S3 buckets, Velero requests 1-time use signed URLs for downloads. Minio doesn't support this, so a workaround is to use the `publicURL` config value.

This used to be documented, but appears to have been dropped as things have moved around. I'll get a PR in for it. The closest we have right now is https://velero.io/docs/v1.2.0/contributions/minio/#work-with-ingress.

**Comment by a4nowgh** [comment]
It works OK now!  

Thanks very much for your help!!  Any documentation updated to reflect this would be great...

    On Monday, February 10, 2020, 4:03:42 PM EST, Nolan Brubaker <notifications@github.com> wrote:  
 
 
Here's my guess - the Velero client is using your BackupStorageLocation's spec.config.s3url, which is an https URL, and getting the encrypted contents. If you add an http URL to spec.config.publicUrl, the velero client should be able to download the resource list in readable format.

If my suspicion is correct, then the velero restore logs and velero backup logs commands should also return encrypted values.

The reason this happens is that with AWS S3 buckets, Velero requests 1-time use signed URLs for downloads. Minio doesn't support this, so a workaround is to use the publicURL config value.

This used to be documented, but appears to have been dropped as things have moved around. I'll get a PR in for it. The closest we have right now is https://velero.io/docs/v1.2.0/contributions/minio/#work-with-ingress.

**Comment by nrb** [comment]
@a4nowgh Did you change your Minio installation to use HTTP only, or did you add a HTTP endpoint?
