### ISSUE TITLE
Prometheus Metrics on Restic Volume Backups

### ISSUE THREAD

**Issue by connorearl** [vmware-tanzu/velero#2262]
**Describe the problem/challenge you have**
I currently am looking to create monitoring or a dashboard on what volumes are being backed up. I hope to compare this with other volume info from prometheus to get a better idea on what might be missed that we need to backup (Someone forgot to add an annotation etc.)

**Describe the solution you'd like**
It would be great if we can just export the restic backups section when describing backups with --details to a prometheus friendly format. The existing pod volume snapshots from prometheus look interesting, but they show nothing for restic. Something like that could work too.

**Environment:**

- Velero version (use `velero version`): 1.2.0
- Kubernetes version (use `kubectl version`): 1.16.3
- Kubernetes installer & version: kubeadm 1.16.3
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.04

**Comment by HaveFun83** [comment]
https://github.com/restic/restic/issues/1878

**Comment by ashish-amarnath** [comment]
@connorearl and @HaveFun83 we now have the necessary scaffolding to add metrics for restic backup. https://github.com/vmware-tanzu/velero/pull/2719
Please feel free to add more metrics.

**Comment by eleanor-millman** [comment]
Looks like it was resolved.
