### ISSUE TITLE
Specify Snapshot Retention Policy Using YAML-based Definition

### ISSUE THREAD

**Issue by archmangler** [vmware-tanzu/velero#2268]
**Describe the problem/challenge you have**

- No way to specify snapshot retention policies on  a per namespace basis. This results in unmanageable numbers of snapshots building up in Azure cloud storage.
- Therefore we have to manage snapshots on the storage side, which is non-ideal.

**Describe the solution you'd like**

- A similar configuration mechanism to backup schedules: Specify retention policy in yamll format on a namespace.
- Ability to specify schedules of this granularity:

```
Dev: retain 7 daily snapshots, retain 2 weekly snapshots
Prod: retain 30 daily snapshots, 12 monthly snapshots, 7 yearly snapshots
```

**Anything else you would like to add:**

I see restic supports snapshot retention management https://restic.readthedocs.io/en/latest/060_forget.html

NOTE: There does not appear to be documentation on the velero website discussion snapshot retention.

**Environment:**

ALL

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by archmangler** [comment]
Thanks @skriss.

**Comment by asoltesz** [comment]
Proper retention policies are a pretty big missing feature in Velero IMHO.

--ttl and defining a lot of different schedules is just not a great solution at all. 

First of all, it is cumbersome as hell.

Secondly, in case you define a daily, weekly, monthly, and yearly schedules there will be days when the backup schedule gets executed 4 times (once a year), 3 times (every month), 2 times (every week).

Possibly, Restic should be the endpoint manager of all of the Velero backup elements and this should be trusted on it. AFAIK, Restic has proper retention management with age, tag and duration retention types.
