### ISSUE TITLE
need help installing and backup velero

### ISSUE THREAD

**Issue by nzncngz** [vmware-tanzu/velero#2275]
Hi,
**What steps did you take and what happened:**
For backup and restore tests I create  a wordpress senario same
https://blog.kubernauts.io/backup-and-restore-of-kubernetes-applications-using-heptios-velero-with-restic-and-rook-ceph-as-2e8df15b1487
I will hope backup and restore completed successfull to Velero.

**What did you expect to happen:**
Backup completed successfull. When restoring steps;
namespace,pv and pvs returned successfull but pod state is initialized(I waited one weeks  but pods were initialized.
root@ubuntu:~/rook/cluster/examples/kubernetes# kubectl get pods -n wordpress
NAME                               READY   STATUS     RESTARTS   AGE
wordpress-7b6c4c79bb-mwzfm         0/1     Init:0/1   0          3m21s
wordpress-mysql-6887bf844f-whc84   0/1     Init:0/1   0          3m21s
FAIL;
root@ubuntu:~/rook/cluster/examples/kubernetes# kubectl describe pods wordpress-7b6c4c79bb-kckrt -n wordpress
Events:
  Type     Reason                  Age                From                          Message
  ----     ------                  ----               ----                          -------
  Warning  FailedScheduling        20m (x7 over 21m)  default-scheduler             pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
  Normal   Scheduled               20m                default-scheduler             Successfully assigned wordpress/wordpress-7b6c4c79bb-kckrt to worker3.5ghvl.local
  Normal   SuccessfulAttachVolume  20m                attachdetach-controller       AttachVolume.Attach succeeded for volume "pvc-333c2451-50e3-11ea-8217-566fe47a0010"
  Normal   Pulled                  20m                kubelet, worker3.5ghvl.local  Container image "gcr.io/heptio-images/velero-restic-restore-helper:v0.11.1" already present on machine
  Normal   Created                 20m                kubelet, worker3.5ghvl.local  Created container
  Normal   Started                 20m                kubelet, worker3.5ghvl.local  Started container

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
(https://github.com/vmware-tanzu/velero/files/4204397/deployments.log)

* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
(https://github.com/vmware-tanzu/velero/files/4204388/backupdescribe.txt)

* `velero backup logs <backupname>`
(https://github.com/vmware-tanzu/velero/files/4204386/backuplogs.txt)

* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
(https://github.com/vmware-tanzu/velero/files/4204385/restoredescribe.txt)

* `velero restore logs <restorename>`
(https://github.com/vmware-tanzu/velero/files/4204384/restorelogs.txt)

**Anything else you would like to add:**
Velero uses for backup Minio.Minio set on Vmware.
I am using storage Rook+Ceph.For installation steps on below;
https://blog.kubernauts.io/backup-and-restore-of-kubernetes-applications-using-heptios-velero-with-restic-and-rook-ceph-as-2e8df15b1487
I have already install Minio on Vmware so referenced Minio IP,user,pass for 00-minio-deployment,storageclass.yaml.
Velero connected successfull to Minio.

**Environment:**

- Velero version (use `velero version`): 
root@ubuntu:~#  velero version
Client:
        Version: v0.11.0
        Git commit: ab2fc65c02ecdcb9bb1690e3afe67a3b3196aebc
Server:
        Version: v0.11.0

- Velero features (use `velero client config get features`): 
root@ubuntu:~# velero client config get features
features: <NOT SET>
- Kubernetes version (use `kubectl version`):
root@ubuntu:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
Rancher type install

- Cloud provider or hardware configuration:K8s settings on Ovirt 4.3.5.
Kubernetes enviroment;
total 8 machines.
3 master node,3 worker node,1 RKE and 1 NFS server.
- OS (e.g. from `/etc/os-release`):
root@ubuntu:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by skriss** [comment]
@nzncngz I would strongly advise upgrading to the latest version of velero, v1.2.0. We don't really support the pre-1.0 versions anymore.

https://github.com/vmware-tanzu/velero/releases/tag/v1.2.0

**Comment by skriss** [comment]
It looks like you're using rancher - you'll need to modify the restic `DaemonSet` that's created in the `velero` namespace to use a different hostPath mount than the default. See the `rancherOS` section here: https://velero.io/docs/v1.2.0/restic/#instructions. You can use `kubectl -n velero edit daemonset/restic` to edit the definition.

**Comment by skriss** [comment]
@nzncngz were you able to resolve this?

**Comment by nzncngz** [comment]
Hi,
I saw the message late sorry.I am using velero 1.2.0 version.
I deployed two deployment https://blog.kubernauts.io/backup-and-restore-of-kubernetes-applications-using-heptios-velero-with-restic-and-rook-ceph-as-2e8df15b1487.
Pods is running but;
ERROR

pod has unbound immediate PersistentVolumeClaims
pod is runnning but;
root@master1:~/rook/cluster/examples/kubernetes# kubectl describe pods wordpress-7b6c4c79bb-7rkwg -n wordpress
Name: wordpress-7b6c4c79bb-7rkwg
Namespace: wordpress
Priority: 0
PriorityClassName:
Node: worker2.5ghvl.local/10.154.2.175
Start Time: Fri, 21 Feb 2020 12:12:40 +0300
Labels: app=wordpress
pod-template-hash=7b6c4c79bb
tier=frontend
Annotations: cni.projectcalico.org/podIP: 10.52.4.34/32
Status: Running
IP: 10.52.4.34
Controlled By: ReplicaSet/wordpress-7b6c4c79bb
Containers:
wordpress:
Container ID: docker://731db18f421f9b0da03a5aa1a55ac965e06a12c54f15740e806a96b287b4e944
Image: wordpress:4.6.1-apache
Image ID: docker-pullable://wordpress@sha256:44902067a29a0535bfcf97a7be489dba4d6bd5d74ccd4a86bfac9da4f3f1dc57
Port: 80/TCP
Host Port: 0/TCP
State: Running
Started: Fri, 21 Feb 2020 12:13:23 +0300
Ready: True
Restart Count: 0
Environment:
WORDPRESS_DB_HOST: wordpress-mysql
WORDPRESS_DB_PASSWORD: changeme
Mounts:
/var/run/secrets/kubernetes.io/serviceaccount from default-token-xtx82 (ro)
/var/www/html from wordpress-persistent-storage (rw)
Conditions:
Type Status
Initialized True
Ready True
ContainersReady True
PodScheduled True
Volumes:
wordpress-persistent-storage:
Type: PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
ClaimName: wp-pv-claim
ReadOnly: false
default-token-xtx82:
Type: Secret (a volume populated by a Secret)
SecretName: default-token-xtx82
Optional: false
QoS Class: BestEffort
Node-Selectors:
Tolerations: node.kubernetes.io/not-ready:NoExecute for 300s
node.kubernetes.io/unreachable:NoExecute for 300s
Events:
Type Reason Age From Message

Warning FailedScheduling (x6 over ) default-scheduler pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
Normal Scheduled default-scheduler Successfully assigned wordpress/wordpress-7b6c4c79bb-7rkwg to worker2.5ghvl.local
Normal SuccessfulAttachVolume attachdetach-controller AttachVolume.Attach succeeded for volume "pvc-4c991a2a-548a-11ea-9ea7-566fe47a006a"
Normal Pulling kubelet, worker2.5ghvl.local pulling image "wordpress:4.6.1-apache"
Normal Pulled kubelet, worker2.5ghvl.local Successfully pulled image "wordpress:4.6.1-apache"
Normal Created kubelet, worker2.5ghvl.local Created container
Normal Started kubelet, worker2.5ghvl.local Started container

**Comment by skriss** [comment]
@nzncngz did you make the `hostPath` change that I linked to in this comment (https://github.com/vmware-tanzu/velero/issues/2275#issuecomment-587692843)?

**Comment by nzncngz** [comment]
I am using version https://rook.io/docs/rook/v1.2/ceph-quickstart.html.
I shared backup before and later files.
(https://github.com/vmware-tanzu/velero/files/4237179/information.docx)

**Comment by skriss** [comment]
If you're using rancher, you need to do the rancher-specific steps in https://velero.io/docs/v1.2.0/restic/#instructions

**Comment by nzncngz** [comment]
I don't see any yaml set on velero v1.2.0 about restric.
root@master1:~# tar -zxvf velero-v1.2.0-linux-amd64.tar.gz
velero-v1.2.0-linux-amd64/LICENSE
velero-v1.2.0-linux-amd64/examples/README.md
velero-v1.2.0-linux-amd64/examples/minio
velero-v1.2.0-linux-amd64/examples/minio/00-minio-deployment.yaml
velero-v1.2.0-linux-amd64/examples/nginx-app
velero-v1.2.0-linux-amd64/examples/nginx-app/README.md
velero-v1.2.0-linux-amd64/examples/nginx-app/base.yaml
velero-v1.2.0-linux-amd64/examples/nginx-app/with-pv.yaml
velero-v1.2.0-linux-amd64/velero
root@master1:~# mv velero-v1.2.0-linux-amd64/velero /usr/local/bin/
root@master1:~# nano velero-v1.2.0-linux-amd64/examples/minio/00-minio-deployment.yaml
root@master1:~# kubectl create -f velero-v1.2.0-linux-amd64/examples/minio/00-minio-deployment.yaml
namespace/velero created
deployment.apps/minio created
service/minio created
job.batch/minio-setup created
root@master1:~# kubectl set image \
>   --namespace velero \
>   daemonset/restic restic=velero/velero:v1.2.0
Error from server (NotFound): daemonsets.extensions "restic" not found
root@master1:~# kubectl -n velero edit daemonset/restic
Error from server (NotFound): daemonsets.extensions "restic" not found
root@master1:~#

**Comment by skriss** [comment]
You definitely had the restic daemonset deployed as of your original comment, since there were restic backups created there.

If you reinstalled using `velero install`, you need to use the `--use-restic` flag. You can re-run the `velero install` command that you ran, with that flag, to add the restic DaemonSet.

I would strongly encourage you to spend some time reading the install + restic docs, as we cover all of this information there:

https://velero.io/docs/v1.2.0/basic-install/
https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/master/README.md (if you're using an S3-compatible object store)
https://velero.io/docs/v1.2.0/restic/

**Comment by nzncngz** [comment]
Hi,
Kubernetes OS rancher is not ubuntu 18.04.That's all I used rke for deployment.I don't sure installing velero and minio.
root@master1:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
------------------------------------------------

Minio and velero install referencing https://github.com/justmeandopensource/kubernetes/blob/master/docs/setup-velero-notes.md
Minio install
I am setting Minio on Ovirt
IP:10.154.12.10
user/pass:minioadmin/minioadmin
on 10.154.12.10 vm;
docker pull minio/minio
docker run --name minio -p 9000:9000 -v data:/data minio/minio server /data
------------------------------------------------------------------------------------
Velero installing (on master machine)
 wget https://github.com/vmware-tanzu/velero/releases/download/v1.2.0/velero-v1.2.0-linux-amd64.tar.gz
tar -zxvf  velero-v1.2.0-linux-amd64.tar.gz
mv  velero-v1.2.0-linux-amd64/velero /usr/local/bin/
cd  /root/velero-v1.2.0-linux-amd64/examples/minio
root@master1:~/velero-v1.2.0-linux-amd64/examples/minio# kubectl create -f 00-minio-deployment.yaml
namespace/velero created
deployment.apps/minio created
service/minio created
job.batch/minio-setup created

I am changing  00-minio-deployment.yaml(IP,user,pass)(not support yaml file upload)
(https://github.com/vmware-tanzu/velero/files/4240664/00-minio-deployment.txt)

cat <<EOF>> minio.credentials
[default]
aws_access_key_id=minioadmin
aws_secret_access_key=minioadmin
EOF
ERROR
root@master1:~# velero install    --provider aws    --bucket velero    --secret-file ./minio.credentials    --backup-location-config region=minio,s3ForcePathStyle=true,s3Url=http://10.154.12.10:9000
An error occurred: --plugins flag is required

**Comment by nzncngz** [comment]
Hi again,
All problems are resolved.
On below command running for Velero installing;
velero install --provider aws --bucket kubedemo --secret-file ./minio.credentials --backup-location-config region=minio,s3ForcePathStyle=true,s3Url=http://10.154.12.10:9000 --plugins velero/velero-plugin-for-aws:v1.0.0 --use-restic --wait


Thanks.
