### ISSUE TITLE
Prometheus alerting of failed_backups_total

### ISSUE THREAD

**Issue by error399** [vmware-tanzu/velero#2276]
We are using prometheus for velero monitoring in grafana we see failed_backups_total of 2. When using `velero get backups `all backups (daily and hourly) habe the STATUS completed. Even `velero backup describe` shows no errors in the backups

Expected behaviour is that if all backups are completed according to velero cmd, the failed_backupd_total should have a count of 0

**Environment:**

- Velero version (use `velero version`): Client:
	                                                             Version: v1.2.0
	                                                             Git commit: -
                                                               Server:
	                                                              Version: v1.2.0

- Kubernetes version (use `kubectl version`): client: v1.17.1, server: v1.14.9-eks-c0eccc
- Kubernetes installer & version: EKS

**Comment by ashish-amarnath** [comment]
@error399 
Assuming that you are referring to the `backup_failure_total` metric. This counter is incremented if the backup ends up in a `velerov1api.BackupPhaseFailed` state. This can happen for a variety of reasons, including, a conflict in your backup object store location, or if there are critical errors that were encountered during a backup.

Here are a few things you could check to help us troubleshoot.
1. Identify, from prometheus metrics, when the counter was incremented.
2. Based on the time at which this metric was incremented, inspect:
    a. The corresponding backup and backup logs to identify the cause of failure
    b. Inspect logs from the velero pod to find out what errors were encountered while performing a backup.

We'll be able to help out better with this information.

**Comment by error399** [comment]
Thank you had a tought over the issue and found out that by limiting the the queries to a range I have the results I expect without loosing the historical data.
