### ISSUE TITLE
TTL not working 

### ISSUE THREAD

**Issue by gogovan-vincentngai** [vmware-tanzu/velero#2277]
**What steps did you take and what happened:**
--ttl seems not work or i miss config/understand something ?
As from my understand the --ttl will control how long will a backup alive 
However when i test deploy the backup with let say --ttl 5m 
Things no going to my expected 

**What did you expect to happen:**
I expected it will help delete the backup from gcp storage and disk snapshot
But none of them does  

**The output of the following commands will help us better understand what's going on**:
 **velero backup logs test-ttl2 | grep -v level=info**
or
 **velero backup logs test-ttl2 | grep error** 
get me nothing (seems everything running fine)

**velero backup describe test-ttl2 --details**
Backup Format Version:  1
Started:    2020-02-16 01:24:54 +0800 HKT
Completed:  2020-02-16 01:24:59 +0800 HKT
Expiration:  2020-02-16 01:29:54 +0800 HKT

**Environment:**

- Velero version v1.2.0 
- Kubernetes version (use `kubectl version`): v1.13.12-gke.25
- Cloud provider or hardware configuration: GKE

**Comment by skriss** [comment]
hey @gogovan-vincentngai - the "GC controller" which detects expired backups and deletes them, only runs once per hour. So, if you have a backup with a TTL of 5m, it may take up to 65m for it to be deleted.  Please try letting some time pass and see if things behave as expected!

If this behavior doesn't meet your needs, feel free to file a separate enhancement request explaining further.

Closing this one out. Feel free to reach out again as needed!

**Comment by jenting** [comment]
@skriss I think it would be nice to describe GC controller run once per hour in the document, WDYT?

**Comment by skriss** [comment]
Agree, it'd be nice to document somewhere.

**Comment by ErikXu** [comment]
@skriss Maybe you can add the description in this link, thanks!
https://velero.io/docs/v1.7/how-velero-works/#set-a-backup-to-expire
