### ISSUE TITLE
Installing v1.2.0 failing with error NoCredentialProviders

### ISSUE THREAD

**Issue by ndemeshchenko** [vmware-tanzu/velero#2278]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Installing velero 1.2.0 on k8s 1.14 by these commands:

```helm repo add vmware-tanzu https://vmware-tanzu.github.io/helm-charts && \
kubectl create namespace velero && \
helm install --namespace velero \
    --set image.repository=velero/velero \
    --set configuration.provider=velero.io/aws \
    --set-file credentials.secretContents.cloud=/Users/user/.aws/cred-velero \
        --set configuration.backupStorageLocation.name=aws \
        --set configuration.backupStorageLocation.bucket=blah-blah-aaaz-k8s-backup \
        --set image.repository=velero/velero \
        --set image.pullPolicy=IfNotPresent \
        --set initContainers[0].name=velero-plugin-for-aws \
        --set initContainers[0].image=velero/velero-plugin-for-aws:v1.0.0 \
        --set initContainers[0].volumeMounts[0].mountPath=/target \
        --set initContainers[0].volumeMounts[0].name=plugins \
        velero vmware-tanzu/velero
```

After it, the pod is failing with the following error NoCredentialProviders. However, I was able to check in the container and it has the correct mounted /credentials/cloud file with valid aws secret and key.

> INFO[0000] setting log-level to INFO                     logSource="pkg/cmd/server/server.go:171"
INFO[0000] Starting Velero server v1.2.0 (5d008491bbf681658d3e372da1a9d3a21ca4c03c)  logSource="pkg/cmd/server/server.go:173"
INFO[0000] No feature flags enabled                      logSource="pkg/cmd/server/server.go:177"
INFO[0000] registering plugin                            command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
INFO[0000] registering plugin                            command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
INFO[0000] registering plugin                            command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
INFO[0000] registering plugin                            command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
INFO[0000] registering plugin                            command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
INFO[0000] registering plugin                            command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
INFO[0000] registering plugin                            command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/cluster-role-bindings
INFO[0000] registering plugin                            command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
INFO[0000] registering plugin                            command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
INFO[0000] registering plugin                            command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
INFO[0000] registering plugin                            command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
INFO[0000] registering plugin                            command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
INFO[0000] registering plugin                            command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
INFO[0000] registering plugin                            command=/plugins/velero-plugin-for-aws kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
INFO[0000] registering plugin                            command=/plugins/velero-plugin-for-aws kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
INFO[0000] Checking existence of namespace               logSource="pkg/cmd/server/server.go:337" namespace=velero
INFO[0000] Namespace exists                              logSource="pkg/cmd/server/server.go:343" namespace=velero
INFO[0001] Checking existence of Velero custom resource definitions  logSource="pkg/cmd/server/server.go:372"
INFO[0001] All Velero custom resource definitions exist  logSource="pkg/cmd/server/server.go:406"
INFO[0001] Checking that all backup storage locations are valid  logSource="pkg/cmd/server/server.go:413"
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

**What did you expect to happen:**
Successful installation

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.2.0
- Velero features (use `velero client config get features`): aws plugin
- Kubernetes version (use `kubectl version`): v1.14.6
- Kubernetes installer & version: kubespray
- Cloud provider or hardware configuration: 
- OS (e.g. from `/etc/os-release`): Centos 7

**Comment by jenting** [comment]
The `configuration.provider` should be `aws`, not `velero.io/aws`.

**Comment by ndemeshchenko** [comment]
thx @jenting, yeah, tried `aws` as well but same error

**Comment by mynktl** [comment]
Can you verify if `/Users/user/.aws/cred-velero` has the following format?
```
[default]
aws_access_key_id=<AWS_ACCESS_KEY_ID>
aws_secret_access_key=<AWS_SECRET_ACCESS_KEY>
```

**Comment by skriss** [comment]
@ndemeshchenko were you able to resolve this?

**Comment by skriss** [comment]
closing out as inactive. feel free to reach out again as needed.
