### ISSUE TITLE
Error backing up ClusterRoleBinding object

### ISSUE THREAD

**Issue by markrity** [vmware-tanzu/velero#2281]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
When I backup a whole cluster using schedule or manually , I get an error on backing up specific ClusterRole object.

From backup logs it says that it can't find it and it looks like it can't get the right namespace for it.
'namespace=' , it looks for it without using the right name space (logs and deployment conf for that object will be added)

**What did you expect to happen:**
That it will find it at correct namespace.

**The output of the following commands will help us better understand what's going on**:
Object configuration:
https://pastebin.com/Tr9XWnEA
Logs for that specific object:
https://pastebin.com/tyt02gHL

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
Client:
	Version: v1.2.0
	Git commit: -
Server:
	Version: v1.2.0
- Velero features (use `velero client config get features`): 
features: <NOT SET>
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5"
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc"
- Cloud provider or hardware configuration: AWS EKS , backed up to s3 bucket.
- OS (e.g. from `/etc/os-release`): macOs Cataline 10.15.3 (19D76)

**Comment by skriss** [comment]
@markrity does the ClusterRole `k8s-cloudwatch-adapter:custom-metrics-reader` exist? (what does kubectl get clusterrole k8s-cloudwatch-adapter:custom-metrics-reader -A` show?)

Usually this comes up when you have an invalid RoleBinding/ClusterRoleBinding that references a nonexistent Role/ClusterRole, and it can be resolved by either deleting the invalid binding, or creating the missing role/clusterrole.

**Comment by markrity** [comment]
@skriss You are right, I was sure I checked if that ClusterRole exists, but it doesn't ...
Thanks!

Can you please explain why manual backup fail completly  if this error presents , but scheduled backups do not fail.?

**Comment by skriss** [comment]
> Can you please explain why manual backup fail completly if this error presents , but scheduled backups do not fail.?

Hmm, that is surprising. That would lead me to believe that the scheduled backups are not including this ClusterRoleBinding/ClusterRole. Does the manual backup have the same spec (namespaces, resources, label selector) as the scheduled backup?

**Comment by markrity** [comment]
@skriss I'm doing a complete cluster backup , both manual and scheduled. 
Without specifying any specific namespaces/resources or lables.

**Comment by skriss** [comment]
K, I'm not sure why you'd get different results then. If you want to debug this further - do you have logs for each of the backups?

**Comment by skriss** [comment]
@markrity just checking in to see if you wanted to debug further, and if so, if you could provide the requested logs. If not, feel free to close out the issue.

**Comment by markrity** [comment]
@skriss 
I plan to debug it myself later, so lets close this issue for now :)
