### ISSUE TITLE
Velero 1.2 - Restic issue Please reduce your request\nLoad(<lock/ab6beb6c24>, 0, 0) 

### ISSUE THREAD

**Issue by Stolr** [vmware-tanzu/velero#2285]
Hi ,

Just install fresh install of velero 1.2.0.

Getting some error while trying to backup my gitlab data .

Log from Restic : 

kubectl logs -f restic-j7d2r
 
```
```

My PV size is about 200Gb. Is there a limitation on size ?

Thanks

**Comment by skriss** [comment]
@Stolr while there's not a hard limit, a backup of this size with restic would take many minutes, especially the first backup, but you should be able to get a completed one with patience :)

It looks like the logs didn't paste properly - could you dump them into a gist and include a link?

**Comment by Stolr** [comment]
https://gist.github.com/Stolr/34cb854ccada602091148a86356fe29d

**Comment by skriss** [comment]
Hmm, it sounds like your object store is throttling requests. Is this something you can control/configure on the server side?

**Comment by Stolr** [comment]
So you mean this is probably an issue related to minio ?

This is weird because it was working before using 1.2.0.

But Yes , I'll let you know tomorrow I'll check if minio is ok ( might be also the load balancer )

**Comment by Stolr** [comment]
Could not reproduce,.
