### ISSUE TITLE
Restic index not deleting after Backup Job Deleted

### ISSUE THREAD

**Issue by a4nowgh** [vmware-tanzu/velero#2289]
**What steps did you take and what happened:**
When the following command is issued:
velero backup delete <jobName>

The associated index (<bucketName>/restic/<Namespace>/index/<INDEX ID> does not get deleted in my S3 Compliant backup storage.

The associated snapshot (<bucketName>/restic/<Namespace>/snapshots/<SNAPSHOT ID> does get deleted OK.

**What did you expect to happen:**
The associated index (<bucketName>/restic/<Namespace>/index/<INDEX ID> should  be deleted also.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- minIO Version: 2019-04-17T17:41:56Z
- minIO Release-tag: RELEASE.2019-04-17T17-41-56Z
- Velero version: v1.2.0
- Velero features:
- Kubernetes Client version: v1.15.3
- Kubernetes Server version: v1.14.6
- Cloud provider or hardware configuration: aws
- OS: Ubuntu 18.04.3 LTS

**Comment by skriss** [comment]
@a4nowgh Velero runs `restic prune` every `7d` by default, which will remove any unused blocks of data from the restic repo and I believe from the index as well.  We only run it once a week because it requires an exclusive repo lock, and can take some time depending on the repo size.

You can tune the frequency by modifying the `spec.maintenanceFrequency` on your `ResticRepository` resource, via `kubectl -n velero edit resticrepository.velero.io <NAME>`.

I think that should explain the behavior you're seeing - let us know if that's the case.

**Comment by a4nowgh** [comment]
OK.  So I set the 'maintenanceFrequency' to 10 minutes temporarily for a quicker result resulting in the following:

kubectl -n velero describe resticrepository.velero.io <NAME>
Name:     <NAME>
Namespace:  velero
.........
Spec:
  Backup Storage Location: default
  Maintenance Frequency:  0h5m0s
  Restic Identifier: <RESTIC_IDENTIFIER>
  volume Namespace:  <NAMESPACE>
Status:
   Last Maintenance Time: <TIMESTAMP>
   Message:  error running command=restic prune --repo=<REPO> --password-file=<PASSFILE> --cache-dir="/scratch/.cache/restic, stdout=counting files in repo
, stderr=List(data) returned error, retrying after 440.328595ms: Delimiter must be a single character
List(data) returned error, retrying after 440.328595ms: Delimiter must be a single character
(repeated several times)
: exit status 1
  Phase: Ready
Events: <none>

**Comment by a4nowgh** [comment]
The above was test was performed with velero binary versions v1.2.0 and v1.3.0-beta.2 with the same end result.

**Comment by ashish-amarnath** [comment]
@a4nowgh looks like the `prune` command is unable to run successfully. 
```
 Delimiter must be a single character List(data) returned error
```
I am not sure if your restic repository is corrupted. Can you please try to run `restic check` to confirm.

If you are able to easily repro this, can you please share how so that I can look into what might be happening?

**Comment by jenting** [comment]
To me, I encounter the issue when fetch the blob config. Should I set up the Azure blob container to public?

```
$ kubectl describe resticrepository

Status:
  Last Maintenance Time:  2020-02-27T08:01:28Z
  Message:                error running command=restic prune --repo=azure:velero:/restic/kube-system --password-file=/tmp/velero-restic-credentials-kube-system054408806 --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: unable to open config file: blob.GetProperties: Head https://velero0a031d06a585.blob.core.windows.net/velero/restic/kube-system/config: read tcp 10.244.5.15:48818->20.150.34.4:443: read: connection reset by peer
Is there a repository at the following location?
azure:velero:/restic/kube-system
: exit status 1
```

**Comment by skriss** [comment]
Closing this out as inactive, feel free to reach out again as needed.
