### ISSUE TITLE
Velero behavior when multiple clusters in multiple kubeconfig files

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#2300]
**Describe the problem/challenge you have**
When having multiple clusters with their configs spread into separate `.kube/config_xxx` files, it seems Velero will use the cluster that was last loaded, which might not be the one the user wants. See the loading order in the log output below.

The cluster where Velero was running was the `kind-config-development` cluster, which was also the set context. However, whenever trying any Velero operation against the cluster api, an `An error occurred: Unauthorized` error happened. Simply deleting the `kind-config-staging` cluster fixed the problem. 

Note: this probably doesn't happen when the configs are all in the `.kube/config` file. 

Desired behavior: Velero should check for the set context and use that as the default.

Optionally: allow for the user to set the context to be used with each command, much like we allow them to set the namespace.

Shoutout to @ashish-amarnath for helping troubleshoot this.

```
> velero create backup 1 -v=9                 ⎈ no config
I0225 11:29:48.586997   25317 loader.go:359] Config loaded from file:  /Users/carlisia/.kube/kind-config-development
I0225 11:29:48.587832   25317 loader.go:359] Config loaded from file:  /Users/carlisia/.kube/kind-config-staging
I0225 11:29:48.599421   25317 request.go:947] Request Body: {"kind":"Backup","apiVersion":"velero.io/v1","metadata":{"name":"1","namespace":"velero","creationTimestamp":null},"spec":{"includedNamespaces":["*"],"ttl":"720h0m0s","hooks":{}},"status":{}}
I0225 11:29:48.601973   25317 round_trippers.go:419] curl -k -v -XPOST  -H "Accept: application/json, */*" -H "Content-Type: application/json" -H "User-Agent: velero/ (darwin/amd64) -" 'https://localhost:57379/apis/velero.io/v1/namespaces/velero/backups'
I0225 11:29:49.522343   25317 round_trippers.go:438] POST https://localhost:57379/apis/velero.io/v1/namespaces/velero/backups 401 Unauthorized in 920 milliseconds
I0225 11:29:49.522398   25317 round_trippers.go:444] Response Headers:
I0225 11:29:49.522407   25317 round_trippers.go:447]     Content-Type: application/json
I0225 11:29:49.522414   25317 round_trippers.go:447]     Content-Length: 129
I0225 11:29:49.522421   25317 round_trippers.go:447]     Date: Tue, 25 Feb 2020 19:29:49 GMT
I0225 11:29:49.522494   25317 request.go:947] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
An error occurred: Unauthorized
```

**Environment:**

- Velero version (use `velero version`): v1.2.0
- Cloud provider or hardware configuration: Kind

**Comment by skriss** [comment]
sounds similar to #2097, but haven't dug in deeply so may be different but related.

**Comment by carlisia** [comment]
It looks exactly the same to me.

The separate config files might be loaded in different order (and maybe cached?) so that might be an explanation in that issue for the same scenario working in one case but not the other.

I'll close this!
