### ISSUE TITLE
Update backup deletion controller to find and delete VolumeSnapshot/VolumeSnapshotContents objects

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2302]
The backup deletion controller should be updated to find any `VolumeSnapshot` and `VolumeSnapshotContents` objects associated with a Velero `Backup` and delete them when the Velero `Backup` is deleted, either manually or via a TTL expiration.

Old description from when we assumed `OwnerRefs` could cross namespaces follows. This won't work because Velero assumes all of its `Backup`s will live in its own namespace, while the `VolumeSnapshot` will be in the same namespaces as their PVCs and `VolumeSnapshotContents` objects will be cluster-scoped.

~Per [the design document](https://github.com/vmware-tanzu/velero/blob/master/design/csi-snapshots.md#garbage-collection-and-deletion), we want to set an ownerRef to the Velero Backup that creates the VolumeSnapshot and VolumeSnapshotContent so that they will be automatically deleted by Kubernetes garbage collection when that backup no longer exists.~

**Comment by skriss** [comment]
Couple notes for implementation:

- we need to make sure we handle the scenario where we just synced backups into a brand new cluster, meaning the VolumeSnapshot CRs don't exist in the cluster yet
- we probably need a `velero.io/backup-name` label on *at least* the VolumeSnapshots, and maybe the VolumeSnapshotContents. Right now, it looks like we're adding an annotation to the VolumeSnapshot with this, but labels make filtering easy.

**Comment by nrb** [comment]
> we probably need a velero.io/backup-name label on at least the VolumeSnapshots, and maybe the VolumeSnapshotContents. Right now, it looks like we're adding an annotation to the VolumeSnapshot with this, but labels make filtering easy.

Yeah, my assumption on #2323 was that both would have a label, so I could use a label selector when trying to upload them.

**Comment by ashish-amarnath** [comment]
The backup deletion controller will not have to delete the volumesnapshotcontent objects. Instead, just deleting the volumesnapshot should suffice. The volumesnapshotcontents will get deleted or retained based on the deletion policy of the volumesnapshotcontent.

So the backup deletion controller will have to discover the volumesnapshots using a label selector and delete just those volumesnapshots.

**Comment by ashish-amarnath** [comment]
Capturing notes from discussions:
Volumesnapshotcontents will also be labeled with the backup name. Making them discoverable, in case the associated volumesnapshot objects are deleted outside the scope of velero, leaving the volumesnapshotcontents dangling. These discoverable dangling volumesnapshotcontents will also be deleted when the backup is deleted.
