### ISSUE TITLE
Installation of v1.3.0 fails on Kubernetes 1.14

### ISSUE THREAD

**Issue by bgagnon** [vmware-tanzu/velero#2311]
**What steps did you take and what happened:**
Tried to install Velero v1.3.0 on a K8S 1.14 cluster.

**What did you expect to happen:**
Successful installation; [the documentation](https://velero.io/docs/v1.3.0/basic-install/#prerequisites) says that Kubernetes 1.10+ is supported.

**Error messages**

Every CRD returns an error when going through `kubectl apply`:

```
[error validating "build\\manifests\\velero\\crd\\backups.velero.io-customresourcedefinition.json":
error validating data: ValidationError(CustomResourceDefinition.spec):
unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec;
if you choose to ignore these errors, turn validation off with --validate=false,
```

**Environment:**

- Velero v1.3.0
- Kubernetes v1.14.1
- Kubernetes client v1.15.4

**Comment by bgagnon** [comment]
This option was first introduced in K8S 1.15; this explains the failure on 1.14.
* 1.14: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#customresourcedefinitionspec-v1beta1-apiextensions-k8s-io
* 1.15: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#customresourcedefinitionspec-v1beta1-apiextensions-k8s-io

**Comment by skriss** [comment]
@bgagnon you can provide the `--validate=false` flag to `kubectl apply` to bypass this error. We have this documented for 1.13 and earlier clusters (see https://velero.io/docs/v1.3.0/customize-installation/#generate-yaml-only), but looks like we need to update that to apply to 1.14 and earlier.
