### ISSUE TITLE
Question: Is it necessary to back up v1/Events?

### ISSUE THREAD

**Issue by dharmab** [vmware-tanzu/velero#2316]
We're looking for ways to reduce the size of our backups as a workaround for https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/issues/26. I noticed in the backup logs that a very large number of `v1/Event` objects are backed up:

```
[kube]$ velero backup logs hourly-k8s-backup-20200226020036 | grep "Backing up item" | grep "group=v1" | grep "resource=events" | wc -l
   59086
```

What are the risks (if any) of excluding Events from a backup job?

**Comment by skriss** [comment]
I would think it's fine to exclude them from the backup unless there's some specific reason that you want to capture them, as they're intended to be ephemeral anyway. In fact Velero has hard-coded logic to not *restore* them. 

We could consider adding similar logic to not back them up, though our general approach is to err on the side of backing up more.  In the interim, you can exclude them using the `--exclude-resources` flag.
