### ISSUE TITLE
Repeated backup of the same CSI workload should not leave orphan resources

### ISSUE THREAD

**Issue by ashish-amarnath** [vmware-tanzu/velero#2325]
While performing backups, for CSI workloads, custom resources of VolumeSnapshot API will be created.
Repeated backups of these workloads should not leave orphaned resources of the VolumeSnapshot API behind.

**Comment by skriss** [comment]
@ashish-amarnath can you describe this issue a little more? where would the orphaned resources come from? Is this related to #2302, which will handle properly deleting a backup's related VS/VSCs?

**Comment by ashish-amarnath** [comment]
This is the scenario:
1. A namespace is repeatedly backed up, say on a schedule. This will create multiple `volumesnapshots` in the namespace and `volumesnapshotcontents` in the cluster. 
1. Latest backup of the namespace will contain the `volumesnapshots` created from all the previous backups, each referring to `volumesnapshotcontents` created as part of their respective backups. This backup, however will not contain the `volumesnapshotcontents` from the previous backups.
1. Restoring from the latest backup will create all the `volumesnapshots` and the `volumesnapshotscontents` will be missing for all but one of the `volumesnapshots`

E.g.
These are the `volumensapshotcontent` references from the `volumesnapshots` on restoring from latest backup.
```
kcn csi-app get volumesnapshot  -ojson | jq -r .items[].spec.source.volumeSnapshotContentName | sort -u
snapcontent-01ab4685-9282-49e2-ba23-3e397623a59d
snapcontent-0acb4915-a6a5-4073-a5b4-68250ee68c02
snapcontent-0c801009-93c4-4a34-802c-f78780907855
snapcontent-0cca07da-7983-43aa-be91-c11ca21d9c74
snapcontent-19067cbe-1cc0-4c29-87be-1d5ab43e8de5
snapcontent-19eb35d1-4c8e-4afc-818c-ca2b25779456
snapcontent-2e2e3975-f73f-4a15-8941-853f9209618f
snapcontent-31476fc4-f450-41a2-8434-357dca54005f
snapcontent-38742800-41d8-4e4b-8557-903a5269ae09
snapcontent-3ceb8da2-8c09-479f-bcfa-91aa1ae4af02
snapcontent-3e42b283-23a5-4fca-bb4b-1a2798aff5eb
snapcontent-4dd600d9-0ed2-4b1a-86bf-7b08ef460bb4
snapcontent-53cc27f3-b213-460a-9ae4-71aca24bb5a7
snapcontent-5b2b05ce-f4a3-42e2-a302-ef185d5a0f03
snapcontent-68058e25-db96-48c6-a7bc-cc9b3ee0b8a5
snapcontent-68b45390-13c2-4e9e-a7ae-19698389b427
snapcontent-7b7caeec-99cd-4593-924d-52ec29dc8066
snapcontent-8b70660c-d81e-4dde-b53a-08bfc57aad59
snapcontent-8dddcedc-d390-4566-ae5e-61aa30eaf828
snapcontent-9a6e3e69-4206-41e3-b355-1acc036175c0
snapcontent-9dee5fda-ed02-4db1-ae8b-ede6139e396c
snapcontent-a163e1c7-890e-44c7-8b32-b00042b32403
snapcontent-a84eda5c-753a-4b1c-aa81-0980364bdcf4
snapcontent-aa4d2b12-c2a8-4a05-a53b-fbfa2a92a307
snapcontent-af090b2d-fe27-409f-9939-80ab1cb935c4
snapcontent-b06b462a-fea1-4a16-b08d-54bebb0c419f
snapcontent-b70d9ba8-e207-4958-9966-e501433df1c3
snapcontent-cafabcf8-6aae-42d5-af5f-c48d9746a894
snapcontent-ebaf83a0-fd03-43eb-a030-bc57665729a7
snapcontent-ef866577-06d2-4c97-b892-07f44b1f5b13
snapcontent-f5fc15ff-33cd-42b8-ba92-6b12dd5f8100
```

These are the `volumesnapshotcontents` that will exist in the cluster:
```
 kc get volumesnapshotcontent
NAME                                               READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER                VOLUMESNAPSHOTCLASS      VOLUMESNAPSHOT         AGE
snapcontent-0acb4915-a6a5-4073-a5b4-68250ee68c02   true         0             Retain           hostpath.csi.k8s.io   csi-hostpath-snapclass   velero-csi-pvc-ldhmz   26m
snapcontent-af090b2d-fe27-409f-9939-80ab1cb935c4   true         1073741824    Retain           hostpath.csi.k8s.io   csi-hostpath-snapclass   velero-csi-pvc-zg7hf   144m
```

The `volumesnapshots` referring to non-existent `volumesnapshotcontents` are the "orphaned" resources that I was referring to.

**Comment by ashish-amarnath** [comment]
Considering that the `volumesnapshotcontents` are restored before `volumesnapshots` https://github.com/vmware-tanzu/velero/blob/master/pkg/cmd/server/server.go#L461 fix for this issue would be not to restore `volumesnapshot` if the linked `volumesnapshotcontent` does not exist.

**Comment by skriss** [comment]
Got it, thanks for the additional info. A couple questions I'm thinking about here:

1) Should we treat VolumeSnapshotContents as additional items to be backed up for VolumeSnapshots, similarly to how we automatically include the PV when a PVC is backed up? This would apply to pre-existing VolumeSnapshots that exist in the cluster at backup time.
2) Should we **exclude** previous Velero-created VolumeSnapshots/VolumeSnapshotContents from a backup? Or, alternately, exclude them during a restore?

**Comment by ashish-amarnath** [comment]
> 1. Should we treat VolumeSnapshotContents as additional items to be backed up for VolumeSnapshots, similarly to how we automatically include the PV when a PVC is backed up? This would apply to pre-existing VolumeSnapshots that exist in the cluster at backup time.

We backup `volumesnapshots` and `volumesnapshotcontents` as additional items when backing up PVCs.

> 2. Should we exclude previous Velero-created VolumeSnapshots/VolumeSnapshotContents from a backup? Or, alternately, exclude them during a restore?

I would prefer to exclude them during backup. To do this we can use the labels/annotations (can't remember which) to do the filtering. This will probably have to be done in a backupItemAction plugin for `volumesnapshots`

**Comment by skriss** [comment]
> > Should we treat VolumeSnapshotContents as additional items to be backed up for VolumeSnapshots, similarly to how we automatically include the PV when a PVC is backed up? This would apply to pre-existing VolumeSnapshots that exist in the cluster at backup time.
> 
> We backup volumesnapshots and volumesnapshotcontents as additional items when backing up PVCs.

To clarify, my question was related to your comment that "Latest backup of the namespace will contain the volumesnapshots created from all the previous backups, each referring to volumesnapshotcontents created as part of their respective backups. *This backup, however will not contain the volumesnapshotcontents from the previous backups.*"

If, when we back up an existing VolumeSnapshot, we back up the VolumeSnapshotContent that it's bound to as a related item (just like for PVC->PV), then we won't end up with dangling references.  This would be for pre-existing VolumeSnapshot CRs in the namespace; I'm **not** talking about the flow for where we're creating new snapshots of PVCs as part of the backup.

This is relevant for non-Velero-created VolumeSnapshots as well, so even if we do #2 (exclude previous Velero-created snapshots), we probably still want to do this backing up of the related VSC.

**Comment by ashish-amarnath** [comment]
Ah! Based on that here is my proposal. We'll fix the dangling vsc reference by including it in the backup. and the same will be restored as well. You are right.. this is required to backup volumesnapshots created outside of velero.
We can address the "backup should not include volumensnapshot object from earlier backups" in a different PR.

**Comment by ashish-amarnath** [comment]
Based on the above discussion. The dangling VSCs are preserved in the cluster to keep the volumesnapshots, in the storage provider, discoverable to the cluster operators. We will revisit this decision, should these dangling volumesnapshotcontents become a problem. I am OK with closing this issue for now and reopening it later, if required.
 @skriss and @nrb  WDYT?
This def is not a P1 important now.

**Comment by ashish-amarnath** [comment]
Just to clarify: The dangling VSCs are now being caused because for every dynamic volumesnapshot, in the backup, we create a corresponding volumesnapshotcontent on restore for static binding. For that reason, this, IMO, is not an issue anymore.

**Comment by ashish-amarnath** [comment]
Closing this issue.
