### ISSUE TITLE
Ensure backup and restore of volumesnapshots created outside of velero work

### ISSUE THREAD

**Issue by ashish-amarnath** [vmware-tanzu/velero#2326]
What will be the guarantees over such volumesnapshots, considering that requirements over their DeletionPolicy cannot be enforced.

**Comment by skriss** [comment]
A few thoughts here:

- we want to make sure we differentiate between VS/VSC that were created by Velero as part of a backup, and VS/VSC that already existed in the cluster
- I would *think* that, during a restore, we want to trigger the "import" case, rather that triggering new snapshots to be created. So, we still need to tweak non-Velero VS/VSC specs in a similar manner to what we're doing for the Velero ones, to e.g. allow VSC to use an existing storage snapshot as a datasource, and to allow the VS to use the VSC as the data source.

If the underlying storage snapshot no longer exists on restore, we could:
1. restore it as-is and assume that the VSC itself will report errors via its status. The VSC will get an error like this:

```json
"status": {
    "error": {
      "message": "Failed to check and update snapshot content: failed to list snapshot for content vsc-for-invalid-snapshot: \"can not find snapshot for snapshotID <snapshot-handle>\"",
      "time": "2020-03-20T15:21:28Z"
    },
    "readyToUse": false
  }
```

2. During the VSC restore, wait for the binding to the snapshot to happen, and report a Velero warning/error if it fails. This code would likely need to go in core Velero, although perhaps it could go in the VolumeSnapshot restore plugin (which would run *after* the VSC has already been restored).

**Comment by skriss** [comment]
We also need to make sure we **don't** label these non-Velero snapshots with the backup label, so that we don't end up deleting them when we delete the Velero backup.

**Comment by ashish-amarnath** [comment]
This PR https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/31 fixes this issue.
Closing this issue as the referenced PR has been merged
