### ISSUE TITLE
Log level is not propagated to plugin

### ISSUE THREAD

**Issue by bgagnon** [vmware-tanzu/velero#2327]
**What steps did you take and what happened:**
In my plugin code, I use the logrus logger provided by the plugin framework. I use it to log messages at the _debug_ level (`log.Debug(...)`).

In the main `velero` container, I also added the `--log-level=debug` and `--log-format=json` flags. This successfully enabled debug-level logging for velero itself, but not for the plugin. 

**What did you expect to happen:**
I would expect debug-level messages from plugins to show in the velero container stdout/stderr output when `--log-level=debug`, [as documented](https://velero.io/docs/v1.3.0/custom-plugins/).

**The output of the following commands will help us better understand what's going on**:

The first few lines of the `velero` container confirm that JSON format and debug format have been applied:

```
velero-695fc99fd9-fjfzl velero {"level":"info","logSource":"pkg/cmd/server/server.go:171","msg":"setting log-level to DEBUG","time":"2020-03-06T03:40:00Z"}
velero-695fc99fd9-fjfzl velero {"level":"info","logSource":"pkg/cmd/server/server.go:173","msg":"Starting Velero server v1.3.0 (8fec8ed7fb8b4776b191753497eafeb47f2f9136)","time":"2020-03-06T03:40:00Z"}
velero-695fc99fd9-fjfzl velero {"level":"info","logSource":"pkg/cmd/server/server.go:177","msg":"No feature flags enabled","time":"2020-03-06T03:40:00Z"}
velero-695fc99fd9-fjfzl velero {"args":["/velero","run-plugins","--log-level","debug"],"cmd":"/velero","level":"debug","logSource":"pkg/plugin/clientmgmt/logrus_adapter.go:74","msg":"starting plugin","path":"/velero","time":"2020-03-06T03:40:00Z"}
velero-695fc99fd9-fjfzl velero {"cmd":"/velero","level":"debug","logSource":"pkg/plugin/clientmgmt/logrus_adapter.go:74","msg":"plugin started","path":"/velero","pid":19,"time":"2020-03-06T03:40:00Z"}
velero-695fc99fd9-fjfzl velero {"cmd":"/velero","level":"debug","logSource":"pkg/plugin/clientmgmt/logrus_adapter.go:74","msg":"waiting for RPC address","path":"/velero","time":"2020-03-06T03:40:00Z"}
velero-695fc99fd9-fjfzl velero {"cmd":"/velero","level":"debug","logSource":"pkg/plugin/framework/server.go:172","msg":"Setting log level to DEBUG","pluginName":"velero","time":"2020-03-06T03:40:00Z"}
velero-695fc99fd9-fjfzl velero {"cmd":"/velero","level":"debug","logSource":"pkg/plugin/clientmgmt/logrus_adapter.go:74","msg":"using plugin","time":"2020-03-06T03:40:00Z","version":2}
velero-695fc99fd9-fjfzl velero {"address":"/tmp/plugin338219849","cmd":"/velero","level":"debug","logSource":"pkg/plugin/clientmgmt/logrus_adapter.go:74","msg":"plugin address","network":"unix","pluginName":"velero","time":"2020-03-06T03:40:00Z"}
```

Later, I also have the confirmation that the `--log-level` flag is passed to the plugin subprocess:

```
velero-695fc99fd9-drjnz velero {"args":["/plugins/velero-plugin-openstack","--log-level","debug"],"cmd":"/plugins/velero-plugin-openstack","controller":"backup-sync","level":"debug","logSource":"pkg/plugin/clientmgmt/logrus_adapter.go:74","msg":"starting plugin","path":"/plugins/velero-plugin-openstack","time":"2020-03-06T04:12:00Z"}
```

**Anything else you would like to add:**
I'm not sure _any_ logging messages from plugins are relayed by velero, actually.

**Environment:**
Velero v1.3.0

**Comment by skriss** [comment]
@bgagnon I actually just submitted some PRs to fix this in the AWS/GCP/Azure plugins too - take a look for the fix: https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/31

Closing this out as that should fix things for you, but feel free to reach out again as needed.

**Comment by bgagnon** [comment]
I applied the same patch to my plugin and it worked perfectly. Thanks!
