### ISSUE TITLE
[Custom CA] Enable ability to install Velero with a custom CA bundle

### ISSUE THREAD

**Issue by dymurray** [vmware-tanzu/velero#2333]
**Describe the problem/challenge you have**
There needs to be a mechanism that at install time, a user can specify a custom CA bundle. This custom CA bundle should be injected in to the Velero deployment, the Restic Daemonset, and configured for the Velero client.

**Describe the solution you'd like**
A user is given a new flag at install time `--cacert` which allows them to specify a custom CA bundle. This CA bundle will be included as an environment variable for the Velero deployment, and stored in the internal system store for the restic pod.

The cert will also need to be passed into the client configuration.

**Comment by mansam** [comment]
Based on how https://github.com/vmware-tanzu/velero/pull/2353 works, it doesn't seem necessary to me to set an environment variable or install the certificate into the pods; I think that having the installer flag set the caCert field on the BSL would probably cover it. I've put together a draft PR with the approach I have in mind: https://github.com/vmware-tanzu/velero/pull/2368

**Comment by dymurray** [comment]
+1 that makes sense to me!

**Comment by skriss** [comment]
Seems fine to me, especially if just using the BSL field works for your use case.
