### ISSUE TITLE
velero pod in CrashLoopBackOff when installed on a cluster with 150 workers 

### ISSUE THREAD

**Issue by lgayatri** [vmware-tanzu/velero#2340]
**What steps did you take and what happened:**
1. Created a k8s cluster with 3 masters and 150 workers.
2. Installed velero with restic
3. All 150 restic pods are up and running
` ~/velero-v1.3.1-linux-amd64 ]# kubectl get pods -n velero --kubeconfig=gc-kc  | grep restic | grep Running | wc -l
150
`
4. velero pod is in CLB
`kubectl get pods -n velero --kubeconfig=gc-kc  | grep -v restic
NAME                      READY   STATUS             RESTARTS   AGE
velero-6bc97c9cdb-q7sgb   0/1     CrashLoopBackOff   7          30m
`
5. describe says:
`kubectl describe  pods velero-6bc97c9cdb-q7sgb -n velero --kubeconfig=gc-kc
Name:           velero-6bc97c9cdb-q7sgb
Namespace:      velero
Priority:       0
Node:           cluster1-workers-0-74b86b4d9b-csrkv/10.244.22.183
Start Time:     Thu, 12 Mar 2020 09:44:18 +0000
Labels:         component=velero
                deploy=velero
                pod-template-hash=6bc97c9cdb
Annotations:    cni.projectcalico.org/podIP: 192.0.245.38/32
                kubernetes.io/psp: vmware-system-privileged
                prometheus.io/path: /metrics
                prometheus.io/port: 8085
                prometheus.io/scrape: true
Status:         Running
IP:             192.0.245.38
Controlled By:  ReplicaSet/velero-6bc97c9cdb
Init Containers:
  velero-plugin-for-aws:
    Container ID:   docker://05096284347ab7b0f542dadaae77771b87a4fe5d6cc8a4a74ee880f9d700d844
    Image:          velero/velero-plugin-for-aws:master
    Image ID:       docker-pullable://velero/velero-plugin-for-aws@sha256:e4697f6cdcc316fa3a1fb156756eca44e36e0c966b5b878bb473bfba05b88657
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 12 Mar 2020 09:48:29 +0000
      Finished:     Thu, 12 Mar 2020 09:48:29 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /target from plugins (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from velero-token-nvszq (ro)
Containers:
  velero:
    Container ID:  docker://99f22649d1b9c2b9d7a09f728b6581726cd840f47efcc1a4d10e66632fbd4a4e
    Image:         velero/velero:v1.3.1
    Image ID:      docker-pullable://velero/velero@sha256:0c74f1d552ef25a4227e582f4c0e6b3db3402abe196595ee9442ceeb43b99696
    Port:          8085/TCP
    Host Port:     0/TCP
    Command:
      /velero
    Args:
      server
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 12 Mar 2020 10:05:46 +0000
      Finished:     Thu, 12 Mar 2020 10:07:50 +0000
    Ready:          False
    Restart Count:  6
    Limits:
      cpu:     1
      memory:  256Mi
    Requests:
      cpu:     500m
      memory:  128Mi
    Environment:
      VELERO_SCRATCH_DIR:              /scratch
      VELERO_NAMESPACE:                velero (v1:metadata.namespace)
      LD_LIBRARY_PATH:                 /plugins
      GOOGLE_APPLICATION_CREDENTIALS:  /credentials/cloud
      AWS_SHARED_CREDENTIALS_FILE:     /credentials/cloud
      AZURE_CREDENTIALS_FILE:          /credentials/cloud
      ALIBABA_CLOUD_CREDENTIALS_FILE:  /credentials/cloud
    Mounts:
      /credentials from cloud-credentials (rw)
      /plugins from plugins (rw)
      /scratch from scratch (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from velero-token-nvszq (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  plugins:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  scratch:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  cloud-credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cloud-credentials
    Optional:    false
  velero-token-nvszq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  velero-token-nvszq
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason          Age                From                                          Message
  ----     ------          ----               ----                                          -------
  Normal   Scheduled       26m                default-scheduler                             Successfully assigned velero/velero-6bc97c9cdb-q7sgb to cluster1-workers-0-74b86b4d9b-csrkv
  Warning  Failed          25m                kubelet, cluster1-workers-0-74b86b4d9b-csrkv  Failed to pull image "velero/velero-plugin-for-aws:master": rpc error: code = Unknown desc = context canceled
  Warning  Failed          25m                kubelet, cluster1-workers-0-74b86b4d9b-csrkv  Error: ErrImagePull
  Normal   SandboxChanged  25m                kubelet, cluster1-workers-0-74b86b4d9b-csrkv  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling         23m (x2 over 26m)  kubelet, cluster1-workers-0-74b86b4d9b-csrkv  Pulling image "velero/velero-plugin-for-aws:master"
  Normal   Pulled          22m                kubelet, cluster1-workers-0-74b86b4d9b-csrkv  Successfully pulled image "velero/velero-plugin-for-aws:master"
  Normal   Created         22m                kubelet, cluster1-workers-0-74b86b4d9b-csrkv  Created container velero-plugin-for-aws
  Normal   Started         22m                kubelet, cluster1-workers-0-74b86b4d9b-csrkv  Started container velero-plugin-for-aws
  Normal   Pulling         22m                kubelet, cluster1-workers-0-74b86b4d9b-csrkv  Pulling image "velero/velero:v1.3.1"
  Normal   Pulled          22m                kubelet, cluster1-workers-0-74b86b4d9b-csrkv  Successfully pulled image "velero/velero:v1.3.1"
  Normal   Created         15m (x4 over 22m)  kubelet, cluster1-workers-0-74b86b4d9b-csrkv  Created container velero
  Normal   Started         15m (x4 over 22m)  kubelet, cluster1-workers-0-74b86b4d9b-csrkv  Started container velero
  Warning  BackOff         15m (x4 over 15m)  kubelet, cluster1-workers-0-74b86b4d9b-csrkv  Back-off restarting failed container
  Normal   Pulled          14m (x4 over 18m)  kubelet, cluster1-workers-0-74b86b4d9b-csrkv  Container image "velero/velero:v1.3.1" already present on machine
  Warning  Failed          6m9s               kubelet, cluster1-workers-0-74b86b4d9b-csrkv  Error: context deadline exceeded
`

**What did you expect to happen:**
Velero pod should be running. The default limits could be falling short.
`   Limits:
      cpu:     1
      memory:  256Mi
    Requests:
      cpu:     500m
      memory:  128Mi
`
* `kubectl logs deployment/velero -n velero`
`
 kubectl logs  velero-6bc97c9cdb-q7sgb -n velero --kubeconfig=gc-kc
time="2020-03-12T10:19:59Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:171"
time="2020-03-12T10:19:59Z" level=info msg="Starting Velero server v1.3.1 (0665b05321eefeb7b7fdd6984750745b7429774f)" logSource="pkg/cmd/server/server.go:173"
time="2020-03-12T10:19:59Z" level=info msg="No feature flags enabled" logSource="pkg/cmd/server/server.go:177"
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-remap-version
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/cluster-role-bindings
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-preserve-fields
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2020-03-12T10:19:59Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-03-12T10:20:00Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2020-03-12T10:20:00Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2020-03-12T10:20:00Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:337" namespace=velero
time="2020-03-12T10:20:00Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:343" namespace=velero
time="2020-03-12T10:20:02Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:372"
time="2020-03-12T10:20:06Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:406"
time="2020-03-12T10:20:06Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:413"

`

- Velero version (use `velero version`): 
`./velero version --kubeconfig=gc-kc
Client:
        Version: v1.3.1
        Git commit: 0665b05321eefeb7b7fdd6984750745b7429774f
`
- Velero features (use `velero client config get features`): 
` ./velero client config get features --kubeconfig=gc-kc
features: <NOT SET>
`
- Kubernetes version (use `kubectl version`):
`kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5+vmware.1", GitCommit:"eb17abcff8c0deb0a97d60bdb1f1b524b8c4e492", GitTreeState:"clean", BuildDate:"2019-10-16T00:03:05Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`
@ashish-amarnath

**Comment by lgayatri** [comment]
if --restic is not provided, velero pod comes up fine

**Comment by skriss** [comment]
@lgayatri is that the complete log that you get when the pod crashes? No error messages at the very end? `kubectl -n velero logs deploy/velero --previous` *might* get you some more information.

Just to confirm -- if you run the exact same `velero install` command, but omit `--use-restic` -- the server pod does not crash?

**Comment by lgayatri** [comment]
Yes @skriss, its the complete log.  If I omit --use-restic, velero pod does not crash.

**Comment by skriss** [comment]
If the `kubectl logs --previous` command I provided doesn't give any more information, then  we can try:

- upping the requests/limits
- I can provide a custom image with more logging added, that could help us pinpoint where it's failing

**Comment by lgayatri** [comment]
Sure @skriss

**Comment by skriss** [comment]
@lgayatri were you able to try this with the custom image?

**Comment by skriss** [comment]
closing this out as inactive, feel free to reopen as/when needed.

**Comment by m287867** [comment]
Hi, 

anyone got a solution for this issue ? i'am still facing the same.
