### ISSUE TITLE
Multiple backup schedules

### ISSUE THREAD

**Issue by gadelkareem** [vmware-tanzu/velero#2347]
I need to have one backup that runs hourly for the last day and another to run every day for the last 2 months. Is it possible with the current config?

**Comment by skriss** [comment]
@gadelkareem yes, you can create as many schedules as you'd like, for example:

```
velero schedule create hourly --schedule "@every 1h" --ttl 24h
velero schedule create daily --schedule "@every 24h" --ttl 1440h # TTL of 60 days
```
