### ISSUE TITLE
Reflect schedule annotations to backups for more flexibility storing metadata

### ISSUE THREAD

**Issue by turkenh** [vmware-tanzu/velero#2348]
**Describe the problem/challenge you have**
We need to store some metadata along with the backup like some spec indicating how we actually creating/managing that cluster. This spec includes Kubernetes version as well as versions/configs of components that we installed on the cluster.

Currently, it is possible to store some metadata with labels and labels on schedule is[ reflected to backups](https://github.com/vmware-tanzu/velero/blob/master/pkg/builder/backup_builder.go#L78-L85) and velero stores whole backup resource including the labels. This is good for storing some metadata but label length is limited to 63 chars.

**Describe the solution you'd like**
Annotations on velero schedule should also be reflected to backups created from them. This way we would have more flexibility on keeping metadata of backups.

**Anything else you would like to add:**
I would expect this to be a simple change without breaking any existing flow, hope we can have this soon :)

**Environment:**

- Velero version (use `velero version`): v1.2.0
- Kubernetes version (use `kubectl version`): v1.17.3
- Kubernetes installer & version: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by funkycode** [comment]
I created PR (still draft) and it seems to fail on the part that was not changed if someone can help me to understand what can be wrong as the change is really small

**Comment by funkycode** [comment]
I made Pr but seems like I'm missing something as it didn't pass tests.
From my understanding backup doesn't have annotation and possible backup from scheduler is populated with empty map for annotations.
