### ISSUE TITLE
Test and document behavior when backing up applications deployed by Helm

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2351]
As a maintainer, I know Velero does not fully support restoring Helm 2-managed applications such that Helm/Tiller can track and account for them, but I don't have those specifics. This should be tested and any issues documented. Given Helm 2's deprecation status, I don't know that this will be fixed, but if we document issues it would also make it easier for someone to develop a plugin to address them, given the huge catalog that already exists based on Helm 2.

Additionally, we should test applications (preferably the same ones) with Helm 3 to see what the differences are when the application is restored. Given Helm 3's design removes Tiller, it could be that there are fewer issues with restoring these applications since there's no in-cluster objects to re-associate.

**Comment by nrb** [comment]
Current findings:

On a Helm 2 installation, the ConfigMaps that specify a release appear to continue working if Tiller is restored or deployed before the ConfigMaps are.

If the ConfigMaps are restore before the Tiller server is running, Tiller does not detect them, and the releases are orphaned.

It is possible to restore Tiller first out of a full cluster backup by restoring the `kube-system` namespace before any others, but that assumes that a) Tiller is in the `kube-system` namespace and b) no releases are being managed in that namespace.

**Comment by jenting** [comment]
Start from velero helm-chart 2.15.0, Velero no longer supports Helm v2 since it's deprecated in November 2020.

**Comment by nrb** [comment]
I think this will be addressed via https://github.com/vmware-tanzu/velero/pull/3466 if we can inspect the Helm Chart and associated resources and record the whole object graph.
