### ISSUE TITLE
Backup of K8s PersistentVolumeClaim and PersistentVolumeClaim only

### ISSUE THREAD

**Issue by Suberri** [vmware-tanzu/velero#2352]
**What steps did you take and what happened:**
I want. to backup only the PVs and the PVCs that are on my cluster
I have executed the following command 
velero backup create pvbackup --include-resources PersistentVolumeClaim.*,PersistentVolume.*

It seems that Velero did a backup of all the cluster resources
  
**What did you expect to happen:**
I expected a backup of only the PVs and PVCs

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
~$ velero backup describe pvbackup  --details
Name:         pvbackup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  Completed

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        PersistentVolumeClaim.*, PersistentVolume.*
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-03-17 12:03:32 -0400 EDT
Completed:  2020-03-17 12:04:02 -0400 EDT

Expiration:  2020-04-16 12:03:32 -0400 EDT

Resource List:
  admissionregistration.k8s.io/v1beta1/MutatingWebhookConfiguration:
    - cluster-cm-cert-manager-webhook
    - monitoring-prometheus-oper-admission
    - pod-identity-webhook
  admissionregistration.k8s.io/v1beta1/ValidatingWebhookConfiguration:
    - cluster-cm-cert-manager-webhook
    - image-admission-config
    - monitoring-prometheus-oper-admission
  apiextensions.k8s.io/v1beta1/CustomResourceDefinition:
    - alertmanagers.monitoring.coreos.com
    - backups.velero.io
    - backupstoragelocations.velero.io
    - certificaterequests.cert-manager.io
    - certificates.cert-manager.io
    - challenges.acme.cert-manager.io
    - clusterimagepolicies.securityenforcement.admission.vpcx.jnj.com
    - clusterissuers.cert-manager.io
    - deletebackuprequests.velero.io
    - downloadrequests.velero.io
    - eniconfigs.crd.k8s.amazonaws.com
    - imagepolicies.securityenforcement.admission.vpcx.jnj.com
    - issuers.cert-manager.io
    - orders.acme.cert-manager.io
    - podmonitors.monitoring.coreos.com
    - podvolumebackups.velero.io
    - podvolumerestores.velero.io
    - prometheuses.monitoring.coreos.com
    - prometheusrules.monitoring.coreos.com
    - resticrepositories.velero.io
    - restores.velero.io
    - schedules.velero.io
    - serverstatusrequests.velero.io
    - servicemonitors.monitoring.coreos.com
    - thanosrulers.monitoring.coreos.com
    - volumesnapshotlocations.velero.io
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
~velero version
Client: Version: v1.1.0. Git commit: a357f21
Server: Version: v1.3.1
-
- Velero features (use `velero client config get features`): 
~$ velero client config get features
features: <NOT SET>
- Kubernetes version (use `kubectl version`):
~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
~$
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
I wasn't actually able to reproduce this, but can you try again with:

```
velero backup create pvbackup-2 --include-resources pvc,pv
```

Can you also include the output of `velero version`, as requested in the template?

**Comment by Suberri** [comment]
Hi Skriss, thank you for your input. 
Below please find the output to the command you sent me and our velero version  
~$ velero version
Client:   Version: v1.1.0.  Git commit: a357f21aec6b39a8244dd23e469cc4519f1fe608
Server:  Version: v1.3.1
-----------------
~$ velero backup create pvbackup-2 --include-resources pvc,pv
Backup request "pvbackup-2" submitted successfully.

~$ velero backup describe pvbackup-2  --details
....
Resource List:  <backup resource list not found, this could be because this backup was taken prior to Velero 1.1.0>

**Comment by skriss** [comment]
Was the backup complete when you ran the describe command? The full output would be helpful. If it did not complete for some reason, the output of `velero backup logs pvbackup-2` and/or `kubectl -n velero logs deploy/velero` would be helpful. If it did eventually complete, what does the `describe` output show now?

**Comment by Suberri** [comment]
Hi Skriss. 
Thanks.
cmd:  velero backup create pvbackup-2 --include-resources pvc,pv
It seems that the command worked. Please confirm  
Log file attached:
[pvbackup-2.describe.log](https://github.com/vmware-tanzu/velero/files/4349696/pvbackup-2.describe.log)
[pvbackup-2.log](https://github.com/vmware-tanzu/velero/files/4349697/pvbackup-2.log)

**Comment by skriss** [comment]
Yep, looks right.

**Comment by skriss** [comment]
closing this out!

**Comment by Suberri** [comment]
Thanks again
