### ISSUE TITLE
Issu with volume backup restic/velero

### ISSUE THREAD

**Issue by Panplumousse** [vmware-tanzu/velero#2354]
Hello,

We encounter errors when saving certain volumes in our kubernetes "icp cloud" cluster

For some volumes in a specific namespaces (I specify that these volumes are not huge 1GB), we have a timeout

We tried to pass this volume in ReadWriteMany instead of ReadWriteOnce but it's the same

Velero version: 1.3.0
error log:

velero backup logs backup-namespace-kube-system-20200318-2 |grep error

time="2020-03-18T14:14:09Z" level=error msg="Error backing up item" backup=velero/backup-namespace-kube-system-20200318-2 error="timed out waiting for all PodVolumeBackups to complete" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:172" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:287" name=monitoring-prometheus-alertmanager-797c6fb674-grnqs namespace=kube-system resource=pods

velero pod logs :

time="2020-03-18T14:14:09Z" level=info msg="1 errors encountered backup up item" backup=velero/backup-namespace-kube-system-20200318-2 group=v1 logSource="pkg/backup/resource_backupper.go:283" name=monitoring-prometheus-alertmanager-797c6fb674-grnqs namespace=kube-system resource=pods

time="2020-03-18T14:14:09Z" level=error msg="Error backing up item" backup=velero/backup-namespace-kube-system-20200318-2 error="timed out waiting for all PodVolumeBackups to complete" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:172" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:287" name=monitoring-prometheus-alertmanager-797c6fb674-grnqs namespace=kube-system resource=pods

podvolumebackups

[root@vcli01plbbb001 pprod]# kubectl -n velero get podvolumebackups -l velero.io/backup-name=backup-namespace-kube-system-20200318-2 -o yaml
apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: PodVolumeBackup
  metadata:
    annotations:
      velero.io/pvc-name: monitoring-prometheus-alertmanager
    creationTimestamp: "2020-03-18T13:14:10Z"
    generateName: backup-namespace-kube-system-20200318-2-
    generation: 1
    labels:
      velero.io/backup-name: backup-namespace-kube-system-20200318-2
      velero.io/backup-uid: 51779740-691a-11ea-9bab-005056bca3d7
      velero.io/pvc-uid: d58502c6-4ca6-11ea-8d08-005056bc5103
    name: backup-namespace-kube-system-20200318-2-s4mgj
    namespace: velero
    ownerReferences:
    - apiVersion: velero.io/v1
      controller: true
      kind: Backup
      name: backup-namespace-kube-system-20200318-2
      uid: 51779740-691a-11ea-9bab-005056bca3d7
    resourceVersion: "36279630"
    selfLink: /apis/velero.io/v1/namespaces/velero/podvolumebackups/backup-namespace-kube-system-20200318-2-s4mgj
    uid: 5b031d87-691a-11ea-9546-005056bc5103
  spec:
    backupStorageLocation: default
    node: 10.255.82.48
    pod:
      kind: Pod
      name: monitoring-prometheus-alertmanager-797c6fb674-grnqs
      namespace: kube-system
      uid: 9a6e23f1-6903-11ea-9bab-005056bca3d7
    repoIdentifier: s3:http://******/velero/restic/kube-system
    tags:
      backup: backup-namespace-kube-system-20200318-2
      backup-uid: 51779740-691a-11ea-9bab-005056bca3d7
      ns: kube-system
      pod: monitoring-prometheus-alertmanager-797c6fb674-grnqs
      pod-uid: 9a6e23f1-6903-11ea-9bab-005056bca3d7
      pvc-uid: d58502c6-4ca6-11ea-8d08-005056bc5103
      volume: storage-volume
    volume: storage-volume
  status:
    progress: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

we need help :(
thx a lot
regards

**Comment by skriss** [comment]
It seems like the PodVolumeBackup is not being picked up for processing. Can you confirm that there is a restic daemonset pod (in the `velero` namespace) on the same node as the `monitoring-prometheus-alertmanager-797c6fb674-grnqs` pod? If so, can you get the logs for the restic daemonset pod?

**Comment by Panplumousse** [comment]
Hello , 
you are right.

In fact in ibm cloud private , kubernetes architecture is separated into nodes roles. 
Many "Worker" nodes  with all the "client" application 
Many "Master" nodes with the heart of the solution 
Many "Management" nodes with the monitoring tools of which prometheus is a part.

So velero and 3 pods restics are on my workers nodes and prometheus is likely to be on one of the three management nodes

if I understand correctly this is the problem. Is there a solution to work around this problem?

thx a lot

**Comment by Panplumousse** [comment]
of course i also need to backup the applications on the worker nodes i can't just install velero on the management nodes

**Comment by skriss** [comment]
If you want to use velero+restic to back up volumes, then you need to allow the restic daemonset to schedule pods on *all* nodes where target workloads are running. So sounds like you need to allow the restic daemonset to schedule pods on the management nodes if you want to back up workloads running there. There's no other workaround here, this is a requirement for velero+restic to work.

**Comment by skriss** [comment]
I'm going to close this out, but feel free to reach out again as needed, thanks!
