### ISSUE TITLE
Restore a backup originally made on different storage account

### ISSUE THREAD

**Issue by kwaazaar** [vmware-tanzu/velero#2357]
**Describe the problem/challenge you have**
I want to take a backup from a Kubernetes cluster and restore it on another cluster. This seems like a pretty standard use-case, but somehow I cannot find any documentation.
In general, I want backups to be portable.

**Describe the solution you'd like**
See description: more documentation.

**Comment by skriss** [comment]
@kwaazaar see https://velero.io/docs/v1.3.1/migration-case/.

We're happy to accept documentation PRs, if you have improvements in mind!

**Comment by skriss** [comment]
clsoing this out as inactive, feel free to reach out again as needed!
