### ISSUE TITLE
Can't install velero correcly with s3 bucket

### ISSUE THREAD

**Issue by Mikael-Lelouch** [vmware-tanzu/velero#2360]
Hello,

I try to install a velero on my K8S Cluster with two different command : 

```
 velero install --provider aws \
	--bucket backup-velero-mle \
	--secret-file ./secret_aws \
	--use-volume-snapshots=true \
	--backup-location-config region="us-east-2",s3ForcePathStyle="true",s3Url=http://backup-velero-mle.s3-website.us-east-2.amazonaws.com \
	--snapshot-location-config region=":default-placement" \
	--use-restic
	
	
	velero install --provider aws --bucket backup-velero-mle --secret-file ./secret_aws --use-volume-snapshots=false --backup-location-config region=us-east 2,s3ForcePathStyle="true",s3Url=https://backup-velero-mle.s3.us-east-2.amazonaws.com
```

But I have the same error in the pod logs.
Please see below the screenshot: 
<img width="1581" alt="Screenshot 2020-03-22 at 18 04 39" src="https://user-images.githubusercontent.com/51024624/77255469-efdeaa80-6c67-11ea-961a-dea3feb68e90.png">

I have a secret file with access key and secret key also. 

My velero version : Client:
        Version: v1.3.1
        Git commit: 0665b05321eefeb7b7fdd6984750745b7429774f

Do you know what's is the issue

**Comment by skriss** [comment]
@Mikael-Lelouch it looks like you're using AWS S3. If so, you don't need to specify the `s3Url` or `s3ForcePathStyle` in your `--backup-location-config` flag. The URL will be determined automatically.

**Comment by skriss** [comment]
closing this out as inactive, feel free to reach out again as needed!
