### ISSUE TITLE
Velero plugin for CSI should backup volumesnapshotcontents

### ISSUE THREAD

**Issue by ashish-amarnath** [vmware-tanzu/velero#2371]
Velero plugin for CSI should backup volumesnapshotcontents that:
1. Have DeletionPolity: `Retain`
2. Do not have a valid `Spec.VolumeSnapshotRef`.
    Definition of validity: volumesnapshot being referenced should exist and it's UID should match with `Spec.VolumesnapshotRef.UID`
 

cc @nrb @skriss @carlisia

**Comment by nrb** [comment]
To clarify why this issue exists:

Velero doesn't walk from VolumeSnapshots to VolumeSnapshotContents when it did not make the objects, which is what this issue covers. Is that correct, Ashish?

**Comment by ashish-amarnath** [comment]
The plugin does not differentiate between volumesnapshots created by velero and those created outside of velero. The backup item action for volumesnapshots handles both these cases. PR https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/31

The reason for this issue is to backup volumesnapshots, cluster-scoped resource, that exists without an accompanying volumesnapshot. This can happen when the DeletetionPolicy is Retain and the original volumesnapshot no longer exists.

**Comment by nrb** [comment]
>The reason for this issue is to backup volumesnapshots, cluster-scoped resource, that exists without an accompanying volumesnapshot.

Theoretically that should happen automatically when the user selects the entire cluster, or uses `--include-cluster-resources=true`, shouldn't it?

Are there cases besides the two I just mentioned where we would want a Content object that doesn't have an associate VolumeSnapshot?

**Comment by ashish-amarnath** [comment]
You are right, using `--include-cluster-resources=true` will back the volumesnapshotcontents.
However, `volumesnapshotcontent` objects which are bound to volumesnapshots should not be backed up as they will be backed up by walking the volumesnapshot to volumesnapshotcontent link.
Only volumesnapshotcontents that are unbound to a volumesnapshot should be backed up.

"Velero plugin for CSI should only backup unbound volumesnapshotcontents" is probably a better title for this issiue

**Comment by nrb** [comment]
> Only volumesnapshotcontents that are unbound to a volumesnapshot should be backed up.

I think I'm still confused.

It sounds like you want to back these up when backing up a namespace that exists, but no longer has the VolumeSnapshot object?

In that scenario, is the VolumeSnapshotContents object still relevant, since it's not referred to from within the namespace? It seems like this is breaking some of the known behavior of Velero by backing up a namespace and a resource that had been referred to, but no longer is.

What's the goal of backing up that Content's object?

**Comment by ashish-amarnath** [comment]
The scenario I am thinking of here is, we are running a backup with cluster scope, with `--include-cluster-resources=true`, and we discover volumesnapshotcontent objects in the cluster.
There will be 2 kinds of volumesnapshotcontent objects:
1. those that are bound to a volumesnapshot: these will be backed up as additional resources of the volumesnapshot objects that they are bound to. For that reason these should not backed up explicitly. This issue is mostly about not backing these volumesnapshotcontents.
2. those that are holding a dangling reference to a volumesnapshot: these however, will need to be backed up.

So the fix here will be to implement a BackupItemAction plugin for volumesnapshotcontents that will inspect the volumesnapshotcontents and return the item only if it is unbound and return nil otherwise.

**Comment by nrb** [comment]
`--include-cluster-resources=true` would automatically query them from the API server regardless, wouldn't it? So they'd be backed up anyway?

I think I'm missing why an unbound contents object needs to be backed up. You're assuming that it must, but I'm not following. Are these unbound Contents objects ones Velero made, or would this apply to any VolumeSnapshotContents objects, regardless of origin?

**Comment by ashish-amarnath** [comment]
Yes, all volumesnapshotcontents will get backed up when `--include-cluster-resources=true` is used.
But, we don't want to backup all volumesnapshotcontents. Specifically, those that are bound to a volumesnapshot. So we will want to run logic to make this decision to selectively backup only unbound volumesnapshotcontents.

The unbound volumesnapshotcontents should be backed up to allow them to be reused to create volumes from. Think about a cluster migration scenario. If we don't back these up, then volumesnapshotcontents that exist (and can be used to create volumes from) in source cluster but don't exist in the destination cluster. 

This will apply to any volumesnapshotcontents, regardless of its origin.

**Comment by skriss** [comment]
> There will be 2 kinds of volumesnapshotcontent objects:

> 1. those that are bound to a volumesnapshot: these will be backed up as additional resources of the volumesnapshot objects that they are bound to. For that reason these should not backed up explicitly. This issue is mostly about not backing these volumesnapshotcontents.

I don't think we need a plugin for this, since if the VolumeSnapshotContent has already been backed up as a related item of a VolumeSnapshot, then it won't be backed up again while Velero is directly backing up VolumeSnapshotContents. There is a similar use case for PVCs->PVs, which works correctly. Specifically, when we reach [this block of code](https://github.com/vmware-tanzu/velero/blob/master/pkg/backup/item_backupper.go#L162-L166) for the VolumeSnapshotContent, if it's already been backed up as a related item, then it won't be backed up a second time.

**Comment by skriss** [comment]
@ashish-amarnath should this issue be closed now?

**Comment by ashish-amarnath** [comment]
Yes, this can now be closed.
