### ISSUE TITLE
Add 3rd party controller to build an automatic way to backup all volume resources in the cluster

### ISSUE THREAD

**Issue by duyanghao** [vmware-tanzu/velero#2375]
**Describe the problem/challenge you have**
Refers to #2355 
> > Is there a do-one-command or automatic way for us to backup all persistent volume resources in the cluster? Right now, we have to add relevant annotations to all of pods with pv resources in cluster, which is complicated and unpractical in a production environment.
> 
> Velero doesn't have a built-in command to do this, you'd need to write your own script/automation. You could check out this community project: https://github.com/bitsbeats/velero-pvc-watcher

**Describe the solution you'd like**
Build an automatic way to backup all volume resources in the cluster

**Anything else you would like to add:**
@skriss To solve this, I have created a repo called [velero-volume-controller](https://github.com/duyanghao/velero-volume-controller), which is a Kubernetes controller for velero that detects and adds relevant backup annotation to pods with volumes. Could you take a look at this and add it to the 3rd party controller part in the [velero Restic Integration docs](https://velero.io/docs/v1.3.1/restic/)?

![velero-volume-controller](https://user-images.githubusercontent.com/12867714/77872058-76067c80-7278-11ea-95e8-7c09f419b6b3.png)

**Comment by carlisia** [comment]
Related:
- https://github.com/vmware-tanzu/velero/issues/605
- https://github.com/vmware-tanzu/velero/issues/1871

**Comment by carlisia** [comment]
I added this topic to our community meeting tomorrow (3/31): https://hackmd.io/Jq6F5zqZR7S80CeDWUklkA?both#March-31-2020.

**Comment by nrb** [comment]
@duyanghao Do you to continue supporting this controller? Is it commercially backed?

**Comment by duyanghao** [comment]
> @duyanghao Do you to continue supporting this controller? Is it commercially backed?

Yeah. Currently, our team plans to use this controller combined with [velero Restic Integration](https://velero.io/docs/v1.3.1/restic/) to backup and restore Kubernetes clusters in a production environment.

**Comment by skriss** [comment]
FYI we already have https://github.com/vmware-tanzu/velero/blob/master/site/docs/master/restic.md#3rd-party-controller in our docs. I don't see any issue with linking to third-party community projects, we should just be clear about ownership.

**Comment by skriss** [comment]
btw, this looks like a neat project @duyanghao!

**Comment by duyanghao** [comment]
> FYI we already have https://github.com/vmware-tanzu/velero/blob/master/site/docs/master/restic.md#3rd-party-controller in our docs. I don't see any issue with linking to third-party community projects, we should just be clear about ownership.

@skriss I guess you mistake my meaning of `add it to the 3rd party controller part`. What I want to say is that maybe velero official can add [velero-volume-controller](https://github.com/duyanghao/velero-volume-controller) to the list of [velero restic 3rd party controller](https://github.com/vmware-tanzu/velero/blob/master/site/docs/master/restic.md#3rd-party-controller) as an option to build an automatic way to backup all volume resources in the cluster
