### ISSUE TITLE
Restic - add support setting Azure Storage Account Key via configuration

### ISSUE THREAD

**Issue by jaygridley** [vmware-tanzu/velero#2376]
**Describe the problem/challenge you have**

There is a PR pending in Velero's Azure plugin https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/32. The same support for setting Storage Account Key via configuration should be added into `pkg/restic/azure.go`

**Describe the solution you'd like**

Implement the same approach as in https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/32.

**Environment:**

- Velero version (use `velero version`): 1.13.1
- Kubernetes version (use `kubectl version`): 1.16.7
- Kubernetes installer & version: PaaS
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04

**Comment by carlisia** [comment]
Ah, you are probably right. @skriss please confirm, and I can get this in.

**Comment by skriss** [comment]
Yep, we need to make a similar change in velero core to make this work for restic.

**Comment by skriss** [comment]
https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/32 is now merged.
