### ISSUE TITLE
don't add `caCert` to object store config if it's empty

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero#2379]
#2353 added support for a `caCert` field as part of BackupStorageLocations. https://github.com/vmware-tanzu/velero/blob/master/pkg/persistence/object_store.go#L117 adds it to the object store `Config` so it can be used during an ObjectStore plugin's `Init(..)` function.

I think we should *only* pass it if it's non-empty, because otherwise it will potentially break validation for community plugins that haven't updated their velero dependency to use the updated validation method that allows `caCert` as a config key.

**Comment by skriss** [comment]
@nrb do you want to take this one? If not I can tackle it, just LMK.

**Comment by nrb** [comment]
@skriss I can tackle it today

**Comment by skriss** [comment]
sounds good!
