### ISSUE TITLE
Ubuntu bionic vulnerabilities

### ISSUE THREAD

**Issue by Annegies** [vmware-tanzu/velero#2384]
The latest release of the ubuntu image solved a lot of vulnerabilities.

Would it be possible to bump the base image to ubuntu:20.04?

**Comment by carlisia** [comment]
@skriss / @nrb WDYT? I can do that if you think we should.

**Comment by nrb** [comment]
That seems like a good idea, though according to https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule, it's not due to release until April 23

**Comment by nrb** [comment]
Double checking on https://hub.docker.com/_/ubuntu, `latest` is still pointing to 18.04, too.

**Comment by Annegies** [comment]
Oh, i might've jumped the gun on that one. Didn't check the official release. 
Thanks for responding, i'll close the issue for now. Can i assume this is on the radar for when it's released?

**Comment by nrb** [comment]
I think we can add it for v1.4 backlog rather than closing it. Thanks for raising it!

**Comment by skriss** [comment]
focal's now out, so I think we should be fine to do this update.
