### ISSUE TITLE
Bug with restic restauration

### ISSUE THREAD

**Issue by Panplumousse** [vmware-tanzu/velero#2385]
**What steps did you take and what happened:**
We have put annotation in deploy to backup pv with restic 

For exemple:
_"metadata:
      annotations:
        backup.velero.io/backup-volumes: cam-bpd-appdata-pv"_

We have made a full backup of a "services" namespace with the command:
This save includes PV with restic

velero backup create backup-namespace-services-20200401-0 --include-namespaces services

Log : 
[root@vcli01plbbb001 ~]# more backup-services-describe.log
Name:         backup-namespace-services-20200401-0
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  Completed

Namespaces:
  Included:  services
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-04-01 17:04:06 +0200 CEST
Completed:  2020-04-01 17:04:50 +0200 CEST

Expiration:  2020-05-01 17:04:06 +0200 CEST

....
....
Persistent Volumes: <none included>

Restic Backups:
  Completed:
    services/cam-bpd-mariadb-5bfcfd58-9jvft: cam-bpd-appdata-pv

**What did you expect to happen:**

We have delete some deploy , some services some pv and some data in our pv
and try to restore object 

velero restore create --from-backup backup-namespace-services-20200401-0

And restore was stuck in phase : InProgress for long time 

Name:         backup-namespace-services-20200401-0-20200401203931
Namespace:    velero
Labels:       <none>
Annotations:  <none>
Phase:  InProgress
Backup:  backup-namespace-services-20200401-0
Namespaces:
  Included:  *
  Excluded:  <none>
Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto
Namespace mappings:  <none>
Label selector:  <none>
Restore PVs:  auto

Restic Restores:
  New:
    services/cam-bpd-mariadb-5bfcfd58-9jvft: cam-bpd-appdata-pv

After timeout restore partialy failed 

Errors:
  Velero:   timed out waiting for all PodVolumeRestores to complete
            timed out waiting for all PodVolumeRestores to complete
  Cluster:    <none>
  Namespaces: <none>

The podvolumerestore describe 

Name:         backup-namespace-services-20200401-0-20200401203931-wjtnj
Namespace:    velero
Labels:       velero.io/pod-uid=21473fa4-7448-11ea-855b-005056bccba3
              velero.io/restore-name=backup-namespace-services-20200401-0-20200401203931
              velero.io/restore-uid=204cae13-7448-11ea-855b-005056bccba3
Annotations:  <none>
API Version:  velero.io/v1
Kind:         PodVolumeRestore
Metadata:
  Creation Timestamp:  2020-04-01T18:39:33Z
  Generate Name:       backup-namespace-services-20200401-0-20200401203931-
  Generation:          2
  Owner References:
    API Version:     velero.io/v1
    Controller:      true
    Kind:            Restore
    Name:            backup-namespace-services-20200401-0-20200401203931
    UID:             204cae13-7448-11ea-855b-005056bccba3
  Resource Version:  40304035
  Self Link:         /apis/velero.io/v1/namespaces/velero/podvolumerestores/backup-namespace-services-20200401-0-20200401203931-wjtnj
  UID:               214c47fe-7448-11ea-855b-005056bccba3
Spec:
  Backup Storage Location:  default
  Pod:
    Kind:           Pod
    Name:           cam-bpd-mariadb-5bfcfd58-9jvft
    Namespace:      services
    UID:            21473fa4-7448-11ea-855b-005056bccba3
  Repo Identifier:  s3:http://10.255.82.57:32000/velero/restic/services
  Snapshot ID:      52045e40
  Volume:           cam-bpd-appdata-pv
Status:
  Progress:
Events:  <none>

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

Log restore

[root@vcli01plbbb001 staging]# velero restore logs backup-namespace-services-20200401-0-20200401182233 |grep error
time="2020-04-01T16:22:33Z" level=warning msg="unable to restore additional item" additionalResource=persistentvolumes additionalResourceName=services-backup-app-cam-mongodb-e3db3 additionalResourceNamespace= error="stat /tmp/217178136/resources/persistentvolumes/cluster/services-backup-app-cam-mongodb-e3db3.json: no such file or directory" logSource="pkg/restore/restore.go:1062" restore=velero/backup-namespace-services-20200401-0-20200401182233
time="2020-04-01T17:22:33Z" level=error msg="unable to successfully complete restic restores of pod's volumes" error="timed out waiting for all PodVolumeRestores to complete" logSource="pkg/restore/restore.go:1287" restore=velero/backup-namespace-services-20200401-0-20200401182233
time="2020-04-01T17:22:33Z" level=error msg="unable to successfully complete restic restores of pod's volumes" error="timed out waiting for all PodVolumeRestores to complete" logSource="pkg/restore/restore.go:1287" restore=velero/backup-namespace-services-20200401-0-20200401182233

Looks like changing the name of the pods is problematic.

In fact to make deployment restore tests have been deleted, the restoration recreated them but the names of the pods are dynamically renewed

the name of the new pod is no longer the same as that associated with the pv in the podvolumebackup and podvolume restore

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version : Version: v1.3.0
- Velero features : features: <NOT SET>
- Kubernetes version : Major:"1", Minor:"13", GitVersion:"v1.13.5"
- Kubernetes installer & version:
- Cloud provider or hardware configuration: ICP Ubm cloud private
- OS (e.g. from `/etc/os-release`):

**Comment by Panplumousse** [comment]
to complete diagnostique i put some logs 👍 
[podvolumerestore.log](https://github.com/vmware-tanzu/velero/files/4426289/podvolumerestore.log)

**Comment by ostkrok** [comment]
We've also encountered a similar issue when we tried to restore our staging environment to a new cluster. However, we're not using restic and we're not backing up the data from the PVC:s, so I'm not entirely sure that it's the same issue.

But our logs also show that `no such file` error.

```
time="2020-04-15T08:59:49Z" level=warning msg="unable to restore additional item" additionalResource=persistentvolumeclaims additionalResourceName=data-rabbitmq-rabbitmq-ha-0 additionalResourceNamespace=default error="stat /tmp/703035285/resources/persistentvolumeclaims/namespaces/default/data-rabbitmq-rabbitmq-ha-0.json: no such file or directory" logSource="pkg/restore/restore.go:965" restore=velero/velero-default-20200415001019-20200415105937
```

This isn't a big issue for us, so we won't be looking into it ourselves, but we'll gladly send you more info/logs if that would help you diagnose this.

**Comment by ashish-amarnath** [comment]
@Panplumousse and @ostkrok Thank you for opening this issue and chiming in.
It looks like a restore item action plugin is requesting an item to be restored which doesn't exist.

To help us understand the problem better, can you please:
1. Download the backup using
```
velero backup download <your-backup-name> -o <path-to-save-backup>/<backup-name>.tar.gz
```
2. Extract the contents of the backup
```
tar xvzf <path-to-save-backup>/<backup-name>.tar.gz
```
3. Share the output of 
```
ls -l /resources/persistentvolumes/cluster/
```

**Comment by skriss** [comment]
I'm going to close this out as it's been inactive, but feel free to reach out again as needed.

**Comment by vishrantgupta** [comment]
I am able to reproduce this issue with the latest velero 1.7.0 version. I have attached the velero logs and below is the output of ls -l /resources/persistentvolumes/cluster/`

```
time="2021-11-25T22:53:05Z" level=warning msg="unable to restore additional item" additionalResource=persistentvolumeclaims additionalResourceName=backup-data-postgres-br-proxy-0 additionalResourceNamespace=default error="stat /tmp/359441963/resources/persistentvolumeclaims/namespaces/default/backup-data-postgres-br-proxy-0.json: no such file or directory" logSource="pkg/restore/restore.go:1165" restore=velero/restore-postgres-backup-2021-11-25.16-46-not-pv-a132d
```

```
5023 ~> tree
.
├── metadata
│   └── version
└── resources
    ├── persistentvolumeclaims
    │   ├── namespaces
    │   │   └── default
    │   │       └── backup-data-postgres-br-proxy-0.json
    │   └── v1-preferredversion
    │       └── namespaces
    │           └── default
    │               └── backup-data-postgres-br-proxy-0.json
    └── persistentvolumes
        ├── cluster
        │   └── postgres-br-proxy-pv-0.json
        └── v1-preferredversion
            └── cluster
                └── postgres-br-proxy-pv-0.json

12 directories, 5 files
```

[velero.log.txt](https://github.com/vmware-tanzu/velero/files/7605468/velero.log.txt)
