### ISSUE TITLE
Bug backup restore with restic

### ISSUE THREAD

**Issue by Panplumousse** [vmware-tanzu/velero#2387]
**What steps did you take and what happened:**
Hello 
when we make restore with restic on some PV we have see some lost of data 
We have make backup of application monitoring-prometheus label
with pv monitoring-prometheus  (this pv is in NFS path on netapp
[restic-restore.log](https://github.com/vmware-tanzu/velero/files/4422198/restic-restore.log)
[velero-backup.log](https://github.com/vmware-tanzu/velero/files/4422199/velero-backup.log)
[velero-pod.log](https://github.com/vmware-tanzu/velero/files/4422200/velero-pod.log)
[velero-restore.log](https://github.com/vmware-tanzu/velero/files/4422203/velero-restore.log)

describe backup  >
velero backup describe backup-label-monitoring-prometheus-20200402-0 --details
Name:         backup-label-monitoring-prometheus-20200402-0
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>
Phase:  InProgress
Namespaces:
  Included:  *
  Excluded:  <none>
Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto
Label selector:  app=monitoring-prometheus
Storage Location:  default
Snapshot PVs:  auto
TTL:  720h0m0s
Hooks:  <none>
Backup Format Version:  1
Started:    2020-04-02 15:09:21 +0200 CEST
Completed:  <n/a>
Expiration:  2020-05-02 15:09:21 +0200 CEST
Resource List:  <backup resource list not found>
Persistent Volumes: <none included>
Restic Backups:
  Completed:
    kube-system/monitoring-prometheus-79696cbcb9-qd6mn: storage-volume
[root@vcli01plbbb001 monitoring]# velero backup describe backup-label-monitoring-prometheus-20200402-0 --details
Name:         backup-label-monitoring-prometheus-20200402-0
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>
Phase:  Completed
Namespaces:
  Included:  *
  Excluded:  <none>
Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto
Label selector:  app=monitoring-prometheus
Storage Location:  default
Snapshot PVs:  auto
TTL:  720h0m0s
Hooks:  <none>
Backup Format Version:  1
Started:    2020-04-02 15:09:21 +0200 CEST
Completed:  2020-04-02 15:10:36 +0200 CEST
Expiration:  2020-05-02 15:09:21 +0200 CEST
Resource List:
  apiextensions.k8s.io/v1beta1/CustomResourceDefinition:
    - alertrules.monitoringcontroller.cloud.ibm.com
    - certificates.certmanager.k8s.io
  apps/v1/ControllerRevision:
    - kube-system/monitoring-prometheus-nodeexporter-79897dbccf
  apps/v1/DaemonSet:
    - kube-system/monitoring-prometheus-nodeexporter
  apps/v1/Deployment:
    - kube-system/monitoring-prometheus
    - kube-system/monitoring-prometheus-collectdexporter
    - kube-system/monitoring-prometheus-elasticsearchexporter
    - kube-system/monitoring-prometheus-kubestatemetrics
  apps/v1/ReplicaSet:
    - kube-system/monitoring-prometheus-79696cbcb9
    - kube-system/monitoring-prometheus-7fc6b58947
    - kube-system/monitoring-prometheus-collectdexporter-f7b8f5449
    - kube-system/monitoring-prometheus-elasticsearchexporter-58f8b65556
    - kube-system/monitoring-prometheus-kubestatemetrics-68b89bb48d
  certmanager.k8s.io/v1alpha1/Certificate:
    - kube-system/monitoring-monitoring-elasticsearch-exporter-client-certs
    - kube-system/monitoring-monitoring-exporter-certs
  extensions/v1beta1/Ingress:
    - kube-system/monitoring-prometheus-alertmanager-ingress
    - kube-system/monitoring-prometheus-ingress
  monitoringcontroller.cloud.ibm.com/v1/AlertRule:
    - kube-system/elasticsearch-cluster-health
    - kube-system/failed-jobs
    - kube-system/high-cpu-usage
    - kube-system/node-memory-usage
    - kube-system/pods-restarting
    - kube-system/pods-terminated
  rbac.authorization.k8s.io/v1/ClusterRole:
    - monitoring-prometheus
  rbac.authorization.k8s.io/v1/ClusterRoleBinding:
    - monitoring-prometheus
  v1/ConfigMap:
    - kube-system/monitoring-monitoring-router-entry-config
    - kube-system/monitoring-prometheus
    - kube-system/monitoring-prometheus-alertmanager
    - kube-system/monitoring-prometheus-exporter-router-nginx-config
    - kube-system/monitoring-prometheus-lua-script-config
    - kube-system/monitoring-prometheus-router-nginx-config
    - trident/monitoring-prometheus
  v1/Endpoints:
    - kube-system/monitoring-prometheus
    - kube-system/monitoring-prometheus-collectdexporter
    - kube-system/monitoring-prometheus-elasticsearchexporter
    - kube-system/monitoring-prometheus-kubestatemetrics
    - kube-system/monitoring-prometheus-nodeexporter
  v1/PersistentVolume:
    - kube-system-monitoring-prometheus-29754
    - kube-system-monitoring-prometheus-alertmanager-2973a
  v1/PersistentVolumeClaim:
    - kube-system/monitoring-prometheus
    - kube-system/monitoring-prometheus-alertmanager
  v1/Pod:
    - kube-system/monitoring-prometheus-79696cbcb9-qd6mn
    - kube-system/monitoring-prometheus-collectdexporter-f7b8f5449-nz7q2
    - kube-system/monitoring-prometheus-elasticsearchexporter-58f8b65556-2qggd
    - kube-system/monitoring-prometheus-kubestatemetrics-68b89bb48d-8g4gb
    - kube-system/monitoring-prometheus-nodeexporter-4zq9n
    - kube-system/monitoring-prometheus-nodeexporter-7kxbj
    - kube-system/monitoring-prometheus-nodeexporter-7w85p
    - kube-system/monitoring-prometheus-nodeexporter-7zrsn
    - kube-system/monitoring-prometheus-nodeexporter-8rpp4
    - kube-system/monitoring-prometheus-nodeexporter-cdj9z
    - kube-system/monitoring-prometheus-nodeexporter-fh82w
    - kube-system/monitoring-prometheus-nodeexporter-g54xs
    - kube-system/monitoring-prometheus-nodeexporter-ghfsw
    - kube-system/monitoring-prometheus-nodeexporter-qdslt
    - kube-system/monitoring-prometheus-nodeexporter-rl2mf
    - kube-system/monitoring-prometheus-nodeexporter-sczs8
  v1/Service:
    - kube-system/monitoring-prometheus
    - kube-system/monitoring-prometheus-collectdexporter
    - kube-system/monitoring-prometheus-elasticsearchexporter
    - kube-system/monitoring-prometheus-kubestatemetrics
    - kube-system/monitoring-prometheus-nodeexporter
Persistent Volumes: <none included>
Restic Backups:
  Completed:
    kube-system/monitoring-prometheus-79696cbcb9-qd6mn: storage-volume

describe  restore 

elero restore describe backup-label-monitoring-prometheus-20200402-0-20200402151404 --details
Name:         backup-label-monitoring-prometheus-20200402-0-20200402151404
Namespace:    velero
Labels:       <none>
Annotations:  <none>
Phase:  Completed
Warnings:
  Velero:     <none>
  Cluster:  could not restore, persistentvolumes "kube-system-monitoring-prometheus-alertmanager-2973a" already exists. Warning: the in-cluster version is different than the backed-up version.
  Namespaces:
    kube-system:  could not restore, pods "monitoring-prometheus-collectdexporter-f7b8f5449-nz7q2" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, pods "monitoring-prometheus-kubestatemetrics-68b89bb48d-8g4gb" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, pods "monitoring-prometheus-nodeexporter-4zq9n" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, pods "monitoring-prometheus-nodeexporter-7kxbj" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, pods "monitoring-prometheus-nodeexporter-7w85p" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, pods "monitoring-prometheus-nodeexporter-7zrsn" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, pods "monitoring-prometheus-nodeexporter-8rpp4" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, pods "monitoring-prometheus-nodeexporter-cdj9z" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, pods "monitoring-prometheus-nodeexporter-fh82w" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, pods "monitoring-prometheus-nodeexporter-g54xs" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, pods "monitoring-prometheus-nodeexporter-ghfsw" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, pods "monitoring-prometheus-nodeexporter-qdslt" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, pods "monitoring-prometheus-nodeexporter-rl2mf" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, pods "monitoring-prometheus-nodeexporter-sczs8" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, endpoints "monitoring-prometheus-elasticsearchexporter" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, services "monitoring-prometheus-collectdexporter" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, services "monitoring-prometheus-elasticsearchexporter" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, services "monitoring-prometheus-kubestatemetrics" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, services "monitoring-prometheus-nodeexporter" already exists. Warning: the in-cluster version is different than the backed-up version.
Backup:  backup-label-monitoring-prometheus-20200402-0
Namespaces:
  Included:  *
  Excluded:  <none>
Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto
Namespace mappings:  <none>
Label selector:  <none>
Restore PVs:  auto
Restic Restores:
  Completed:
    kube-system/monitoring-prometheus-79696cbcb9-qd6mn: storage-volume

data before backup
191M    ./01E4VBTN1ZVEXQK00G1A2XSXVV
216M    ./01E4VHTKWY2SCQQQX2V3JMPPKT
2.4G     ./wal

data after restore 
12K      ./01E4VBTN1ZVEXQK00G1A2XSXVV
69M     ./01E4VHTKWY2SCQQQX2V3JMPPKT
2.3G    ./wal
4.0K    ./.velero
4.3G    .

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Environment:

Velero version : Version: v1.3.0
Velero features : features:
Kubernetes version : Major:"1", Minor:"13", GitVersion:"v1.13.5"
Kubernetes installer & version:
Cloud provider or hardware configuration: ICP Ubm cloud private
OS (e.g. from /etc/os-release):

**Comment by carlisia** [comment]
@skriss I could use a hand with this one.

**Comment by ashish-amarnath** [comment]
@Panplumousse I don't see any errors on the velero operations.

Also, looks like the `wal` directory was backed up and restore accurately.

But, looks like the bug that you are trying to report is that the difference in size of `01E4VBTN1ZVEXQK00G1A2XSXVV` and `01E4VHTKWY2SCQQQX2V3JMPPKT`.

Are they files on the same volume? Can you please share the deployment/pod spec of the workload that you are trying to backup.

**Comment by skriss** [comment]
I'm going to close this out as it looks inactive, but feel free to reach out again as needed.
