### ISSUE TITLE
OpenEBS - skipping pvc because it's already been restored

### ISSUE THREAD

**Issue by Wolvenmoon** [vmware-tanzu/velero#2391]
**What steps did you take and what happened:**
Oh hey. It's my first time filing one of these! Please pardon any formatting issues! 

Attempting to restore from a backup results in claims that persistent volume claims are already restored. They are not restored and the persistent volume is marked 'lost'.

**What did you expect to happen:**
The restoration of the backup to result in the pvc being recreated under the same name it was backed up as (pvc-ac1cc1a5-469d-46bc-a876-bb3bd8770305).

**The output of the following commands will help us better understand what's going on**:

[* `kubectl logs deployment/velero -n velero` ](https://gist.github.com/Wolvenmoon/49dded191f3e00fcb43592274d597802)

[* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`](https://gist.github.com/Wolvenmoon/616ac3c6f58aba7d4680a8daf3611d7a)

[* `velero backup logs <backupname>`](https://gist.github.com/Wolvenmoon/9e784c563e746b809dca80533d623877)

[* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`](https://gist.github.com/Wolvenmoon/884ab69df33b2dc0d6caf6096a6f367c)

[* `velero restore logs <restorename>`](https://gist.github.com/Wolvenmoon/c1d2fa251c202eafd6ed3dcce0513acb)

**Anything else you would like to add:**
[My minio, velero, and other potentially relevant configuration files as well as my exact command execution, in case it helps.](https://gist.github.com/Wolvenmoon/b84e1e5701e55d60dcdc82960b227b8b)

The backed up data is visible in minio, I've attached it as a zip, here,
[velero-backups-nginx-example.zip](https://github.com/vmware-tanzu/velero/files/4423036/velero-backups-nginx-example.zip)

**Environment:**

- Velero version (use `velero version`): 
Client:
        Version: v1.3.1
        Git commit: 0665b05321eefeb7b7fdd6984750745b7429774f
Server:
        Version: v1.3.1

- Velero features (use `velero client config get features`): 
features: <NOT SET>

Note: velero plugin add openebs/velero-plugin:ci was used, though I've also tried the 1.6.0, latest, and 1.6.0-velero_1.0.0 tags with no luck.

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version: 
Rancher 2.3.6, RKE 1.0.4, Helm 3.0.3

- Cloud provider or hardware configuration: 
Bare-metal install on top of Ubuntu using Rancher w/ Flannel overlay. 3 nodes, internal network is 192.168.20.1/24, external is 192.168.15.1/24. Other info available if needed!

- OS (e.g. from `/etc/os-release`): 
Ubuntu 18.04 LTS

Thank you for your time!

**Comment by skriss** [comment]
@mynktl could you help out here? It seems like maybe on restore, the plugin assumes the target namespace for the PVC already exists?

**Comment by Wolvenmoon** [comment]
Is there anything else I can do that may be helpful in resolving this?

**Comment by skriss** [comment]
@mynktl any chance you can help look into this?

**Comment by mynktl** [comment]
Hi @Wolvenmoon 
As @skriss mentioned You need to create a namespace before restoring openebs cstor volume. 

>the pod is frozen giving an "unable to attach or mount volumes, timed out waiting for the condition" error

openebs cstor volume is iscsi base volume. So once you set the targetip for replica, replica will connect to target pod and after that kubelet will mount the PV for pod. From https://gist.github.com/Wolvenmoon/589899620b094051b2ad6b62e87785da I'm seeing that mount is successful for PV.

>I can't tell if it restored data to the new PVC or not.

velero-plugin creates a zfs snapshot for the backup. So you can check if your data is restored or not by checking the snapshot list through `zfs snapshot list -t all`. It seems you are already aware of this. https://gist.github.com/Wolvenmoon/589899620b094051b2ad6b62e87785da#file-cstor-disk-pool-zfs-get-io-openebs-targetip-pvc-service-ip

If you are having still issue, feel free to report at https://github.com/openebs/velero-plugin/issues or you can ask in openebs-community.slack.com. 
Thanks!

**Comment by skriss** [comment]
I'm going to close this out per @mynktl's response, but feel free to reach out again as needed (it seems like https://github.com/openebs/velero-plugin/issues would be the best place to direct further questions).

**Comment by Wolvenmoon** [comment]
Alrighty, I finally had a chance to sit down with this.

So, I figured this out and am going to give the exact bash voodoo I used so that the next Googler has the exact fix.

kubectl delete namespace minecraft
kubectl create namespace minecraft
velero restore create mcrestore --from-backup mcbackup --restore-volumes=true


Let's say you end up with a persistent volume claim pvc-3514ffd3-aae7-48ea-a9a1-0f46a713aed2.

You're going to need to jump into your cstor disk pool pod I.E.

kubectl exec -it cstor-disk-pool-47ea-6f45d4b557-l7nj5 -c cstor-pool -n openebs -- bash

run zfs get io.openebs:targetip

Note cstor-2770ce17-1acd-4e89-8a5a-880dfab821ab/pvc-3514ffd3-aae7-48ea-a9a1-0f46a713aed2     has no targetip and the source=default

Check your restored Minecraft pod. It's going to throw a waitforattach failed message and tell you the portal address it's trying to get to, in my case, 10.43.70.7.

In the cstor disk pool pod, run a

zfs set io.openebs:targetip=10.43.70.7 cstor-2770ce17-1acd-4e89-8a5a-880dfab821ab/pvc-3514ffd3-aae7-48ea-a9a1-0f46a713aed2 


Note that this is covered here, https://docs.openebs.io/docs/next/ugcstor.html but I got the notion after reading many dozens of guides that this is only needed when restoring a backup from a source cluster that is different from the destination cluster.


You can check to see if this is happening to you after restoring a Velero backup by running iscsiadm -m session -P 3.

Under the interface section, look for Iface IPaddress: <empty> and iSCSI Session State: FAILED. This indicates you need to set your target ip.

If you receive an error message like:

MountVolume.WaitForAttach failed for volume "pvc-1c29b0b6-98bf-4f2c-b1f6-a1922653835b" : failed to get any path for iscsi disk, last err seen: iscsi: failed to attach disk: Error: iscsiadm: Could not login to [iface: default, target: iqn.2016-09.com.openebs.cstor:pvc-1c29b0b6-98bf-4f2c-b1f6-a1922653835b, portal: 10.43.195.133,3260]. iscsiadm: initiator reported error (8 - connection timed out) iscsiadm: Could not log into all portals Logging in to [iface: default, target: iqn.2016-09.com.openebs.cstor:pvc-1c29b0b6-98bf-4f2c-b1f6-a1922653835b, portal: 10.43.195.133,3260] (multiple) (exit status 8)" 


then you will want to check this out.

Good luck to any future Googlers. Hopefully it's feasible to automatically set iscsi target IP addresses in restored volumes in the future!

Thanks, all!
