### ISSUE TITLE
add documentation page for custom CA bundle functionality

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero#2396]
ref https://github.com/vmware-tanzu/velero/pull/2364#issuecomment-607344810

cc @mansam

**Comment by skriss** [comment]
@mansam just checking in here to see if you'd be able to add the requested documentation page, thaks!

**Comment by mansam** [comment]
hey @skriss, I am still planning to add it, just had some other stuff on my plate. Will be getting to it as soon as possible.
