### ISSUE TITLE
restic not initializing

### ISSUE THREAD

**Issue by mshack70** [vmware-tanzu/velero#2410]
**What steps did you take and what happened:**
we've been testing velero against an s3 backend (cohesity vendor) to backup kubernetes namespace metadata, and also annotated pods which have a volume to backup (via restic).  This is using the velero client/server new versions 1.3.2.

While velero works perfectly fine backing up the namespace to s3, if attempting to backup a volume within a pod, restic throws init errors and we're having trouble figuring out why (as velero has no issue creating/writing to buckets....etc).

**What did you expect to happen:**
Expected restic to backup the volume of an annotated pod to S3 backend.

**The output of the following commands will help us better understand what's going on**:

Here is the portion of velero logs which shows the error (i'm going to replace our internal hostname with S3SERVER):
time="2020-04-09T21:06:04Z" level=info msg="Initializing restic repository" controller=restic-repository logSource="pkg/controller/restic_repository_controller.go:156" name=mariadb-default-dqw6z namespace=velero

time="2020-04-09T21:06:04Z" level=info msg="1 errors encountered backup up item" backup=velero/mike-restictest01 group=v1 logSource="pkg/backup/resource_backupper.go:283" name=mariadb-slave-0 namespace=mariadb resource=pods
time="2020-04-09T21:06:04Z" level=error msg="Error backing up item" backup=velero/mike-restictest01 error="restic repository is not ready: error running command=restic init --repo=s3:https://S3SERVER:3000/velero/restic/mariadb --password-file=/tmp/velero-restic-credentials-mariadb966855465 --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: create repository at s3:https://S3SERVER:3000/velero/restic/mariadb failed: client.BucketExists: Head https://S3SERVER:3000/velero/: net/http: invalid header field value \"AWS4-HMAC-SHA256 Credential=R7aZ3BJKSroriLrD_d44uvsQNCbmEkzpju0swndNHD8/20200409//velero\\n/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=83d673545497e41f6873cf6b5d24b82a7310072b76007b1d22deaf8744a8df06\" for key Authorization\n\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/repository_ensurer.go:186" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryEnsurer).EnsureRepo" group=v1 logSource="pkg/backup/resource_backupper.go:287" name=mariadb-slave-0 namespace=mariadb resource=pods

**Anything else you would like to add:**

Just to reiterate, velero alone (no restic) is able to backup/restore to/from S3 just fine.

**Environment:**

- Velero version (use `velero version`): 
$ velero version
Client:
	Version: v1.3.2
	Git commit: 55a9914a3e4719fb1578529c45430a8c11c28145
Server:
	Version: v1.3.2
- Velero features (use `velero client config get features`): 

- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version: 1.13
- Cloud provider or hardware configuration: on prem
- OS (e.g. from `/etc/os-release`): centos 7.7

**Comment by mshack70** [comment]
The log from the s3 storage api looks to be showing:

/home/cohesity/logs/bridge_exec.ERROR:E0409 10:04:31.878022 20713 s3_handler.cc:1860] [InvalidArgument]: Credential field R7aZ3BJKSroriLrD_d44uvsQNCbmEkzpju0swndNHD8/20200409//velero/s3/aws4_request is malformed

In our case, 
R7aZ3BJKSroriLrD_d44uvsQNCbmEkzpju0swndNHD8 is the aws access ID.

**Comment by skriss** [comment]
@mshack70 it might be easiest to debug this by first trying restic directly against your S3-compatible backend, without Velero, to ensure that it's compatible.

See https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#amazon-s3 for some info on how to do that. Ideally you can use the same credentials as you were trying to use with Velero.

Let me know if you can get any additional info from this.

**Comment by mshack70** [comment]
If i try with restic cmd like example:

1) export my creds
2) $ restic -r s3:S3SERVER:3000/velero/restic/mariadb init

Fatal: create repository at s3:https://S3SERVER:3000/velero/restic/mariadb failed: client.BucketExists: Head https://S3SERVER:3000/velero/: net/http: invalid header field value "AWS4-HMAC-SHA256 Credential=R7aZ3BJKSroriLrD_d44uvsQNCbmEkzpju0swndNHD8/20200415//velero\n/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=d581e34689c0c3d3e71938242dae8353e424b2c03a72c11b9efcd12d2e55af46" for key Authorization

**Comment by ashish-amarnath** [comment]
@mshack70 can you try the suggestion from https://github.com/stashed/stash/issues/547#issuecomment-411355399

**Comment by skriss** [comment]
Closing this out as inactive. Please try out the above suggestion if you're still having an issue.
