### ISSUE TITLE
Retry Backup with Updated Credentials

### ISSUE THREAD

**Issue by rohandvora** [vmware-tanzu/velero#2414]
**What steps did you take and what happened:**
We use temporary credentials with Velero which are updated every 30 mins. We update the `cloud-credentials` secret with the new credentials every 30 mins. If a backup starts before the credentials are updated and completes after the credentials are updated, the backup will fail as it uses the older credentials even when the newer credentials are available in the secret. 

**What did you expect to happen:**
Velero should retry Backups with the latest credentials available if it fails to upload using the current credentials.

**Environment:**

- Velero version (use `velero version`): v1.3.0
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: Kind
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): All

**Comment by skriss** [comment]
Couple notes:
- Velero mounts the `cloud-credentials` secret into its pod as a volume, and relies on the kubelet to update the volume when the secret contents change. There's potentially a ~1m delay (ref. https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L91) in that process
- We *could* directly query the Kubernetes API for the contents of the secret, which would not be subject to any delay
- Since all of the connection setup happens inside the plugins, any logic to do this would probably have to go inside the AWS plugin (and any others that we want such logic for)
- Some users don't use credentials files for AWS (kube2iam, kiam, EKS IAM-backed service accounts), we'd need to make sure we don't break those users

**Comment by skriss** [comment]
@rohandvora have you looked at overlapping the lifespans of the temporarily credentials, so that the old credentials are still valid for some time after the secret is updated with the new credentials? That should minimize the issue, although in the case of a long-running backup there could still be problems.

**Comment by skriss** [comment]
Another optimization we could look at: for backup, we instantiate the backup store [here](https://github.com/vmware-tanzu/velero/blob/master/pkg/controller/backup_controller.go#L537), which would set up the AWS API client using the credentials. This is before the backup really runs. We don't actually upload anything until [here](https://github.com/vmware-tanzu/velero/blob/master/pkg/controller/backup_controller.go#L615). We could re-instantiate the backup store at the end of the backup, just before uploading, to minimize the duration between instantiation and upload. This would better handle the scenario where the secret contents were updated during the backup's execution. However, it still wouldn't account for the ~1m kubelet lag in reloading the volume, *if* the old credentials were already expired by the time the secret was updated.

**Comment by nrb** [comment]
> Since all of the connection setup happens inside the plugins, any logic to do this would probably have to go inside the AWS plugin (and any others that we want such logic for)

It'd have to be duplicated around restic operations too, wouldn't it?

**Comment by skriss** [comment]
> > Since all of the connection setup happens inside the plugins, any logic to do this would probably have to go inside the AWS plugin (and any others that we want such logic for)

> It'd have to be duplicated around restic operations too, wouldn't it?

Yeah, probably, which has its own challenges. I'm not sure how restic would handle having the credentials expire mid-backup, and re-starting a restic backup from the beginning is probably not desirable.

**Comment by nrb** [comment]
Yeah, we wouldn't want to completely restart restic operation I wouldn't think. I'd think for restic, we would end up doing something very similar to what we do now as a secret mount.

The other option for restic would be to use a restic proxy within the cluster, but then again, that just moves the issue around.

**Comment by rohandvora** [comment]
> @rohandvora have you looked at overlapping the lifespans of the temporarily credentials, so that the old credentials are still valid for some time after the secret is updated with the new credentials? That should minimize the issue, although in the case of a long-running backup there could still be problems.

Yes. We do this currently. We rotate credentials before they expire with sufficient time in between.  We were concerned about long-running backups which start when the older credentials hadn't expired and complete after they expire. In this case, the last step which puts the objects in the storage would fail, right? I am not sure if the AWS plugin watches on the secret file and reads it dynamically before it attempts to perform a PUT Object operation.

**Comment by rohandvora** [comment]
> Another optimization we could look at: for backup, we instantiate the backup store [here](https://github.com/vmware-tanzu/velero/blob/master/pkg/controller/backup_controller.go#L537), which would set up the AWS API client using the credentials. This is before the backup really runs. We don't actually upload anything until [here](https://github.com/vmware-tanzu/velero/blob/master/pkg/controller/backup_controller.go#L615). We could re-instantiate the backup store at the end of the backup, just before uploading, to minimize the duration between instantiation and upload. This would better handle the scenario where the secret contents were updated during the backup's execution. However, it still wouldn't account for the ~1m kubelet lag in reloading the volume, which would be problematic _if_ the old credentials were already expired by the time the secret was updated. If the old credentials were still valid for a few minutes **after** when the secret was updated, then this should work pretty well.

I think this should work. We do ensure that credentials are refreshed well in advance. So we wouldn't get into the state where the older credentials expired.

**Comment by ashish-amarnath** [comment]
@rohandvora This issue is now fixed.
This is not in a release yet, but you should be able to use `velero/velero:master` to get this fix.

**Comment by rohandvora** [comment]
Thanks a ton for the fix! @skriss @carlisia @ashish-amarnath
