### ISSUE TITLE
Namespace is blank in error logs

### ISSUE THREAD

**Issue by jamiebuxxx** [vmware-tanzu/velero#2430]
**What steps did you take and what happened:**
When looking through the logs of a failed backup, I noticed that error messages do not specify which namespace the offending issue is in.

Command to view the logs:
```
velero backup logs cluster-backup-20200413120056 | less
```
By piping to `less`, it's easier to search for errors. Here is an example of an error. 

```
time="2020-04-13T19:52:31Z" level=info msg="1 errors encountered backup up item" backup=kube-system/cluster-backup-20200413120056 group=v1 logSource="pkg/backup/resource_backupper.go:283" name=datadir-mongodb-mongodb-replicaset-0 namespace= resource=persistentvolumeclaims
``` 

As you can see, `namespace=` is blank. 

**What did you expect to happen:**
Since successfully backed up data shows the namespace, I would expect that error message would show show the namespace as well.
```
time="2020-04-13T19:52:31Z" level=info msg="Skipping item because it's already been backed up." backup=kube-system/cluster-backup-20200413120056 group=v1 logSource="pkg/backup/item_backupper.go:163" name=test-dev-mongodb-replicaset-1 namespace=sandbox resource=persistentvolumeclaims
```
 This would be helpful when trying to fix the issue by knowing where to start. 

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.3.1
	Git commit: 0665b05321eefeb7b7fdd6984750745b7429774f
Server:
	Version: v1.3.1
```
- Kubernetes version (use `kubectl version`):
`v1.14.8`
- Cloud provider or hardware configuration:
AWS

**Comment by skriss** [comment]
thanks for reporting this, it should definitely be populated for namespaced resources. I'll see if I can track this down.
