### ISSUE TITLE
Failed to discover group: custom.metrics.k8s.io/v1beta1" error="the server is currently unable to handle the request

### ISSUE THREAD

**Issue by shreegolang** [vmware-tanzu/velero#2434]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

velero not able to discover the custom.metrics.k8s.io/v1beta1
time="2020-04-14T16:05:58Z" level=warning msg="Failed to discover group: custom.metrics.k8s.io/v1beta1" error="the server is currently unable to handle the request" logSource="pkg/discovery/helper.go:154"

**What did you expect to happen:**
it should discover the "custom.metrics.k8s.io/v1beta1"

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
time="2020-04-14T16:00:50Z" level=warning msg="Failed to discover group: custom.metrics.k8s.io/v1beta1" error="the server is currently unable to handle the request" logSource="pkg/discovery/helper.go:154"
time="2020-04-14T16:05:58Z" level=warning msg="Failed to discover group: custom.metrics.k8s.io/v1beta1" error="the server is currently unable to handle the request" logSource="pkg/discovery/helper.go:154"
time="2020-04-14T16:11:05Z" level=warning msg="Failed to discover group: custom.metrics.k8s.io/v1beta1" error="the server is currently unable to handle the request" logSource="pkg/discovery/helper.go:154"
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`

Name:         shree-testing-20200414113942
Namespace:    velero
Labels:       velero.io/backup=shree-testing-20200414113942
              velero.io/pv=pvc-a2a8866b-172d-11ea-9aef-4201ac1b1fea
              velero.io/storage-location=velero-cluster-backup
Annotations:  <none>

Phase:  PartiallyFailed (run `velero backup logs shree-testing-20200414113942` for more information)

Errors:    2
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        lables=prometheus-adapter
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  velero-cluster-backup

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-04-14 11:39:42 +0700 WIB
Completed:  2020-04-14 11:51:49 +0700 WIB

Expiration:  2020-05-14 11:39:42 +0700 WIB

Persistent Volumes:  437 of 437 snapshots completed successfully (specify --details for more information)

* `velero backup logs <backupname>`
time="2020-04-14T04:51:49Z" level=info msg="Skipping resource because it cohabitates and we've already processed it" backup=velero/shree-testing-20200414113942 cohabitatingResource1=networkpolicies.extensions cohabitatingResource2=networkpolicies.networking.k8s.io group=extensions/v1beta1 logSource="pkg/backup/resource_backupper.go:147" resource=networkpolicies
time="2020-04-14T04:51:49Z" level=info msg="Backing up resource" backup=velero/shree-testing-20200414113942 group=extensions/v1beta1 logSource="pkg/backup/resource_backupper.go:104" resource=deployments
time="2020-04-14T04:51:49Z" level=info msg="Skipping resource because it cohabitates and we've already processed it" backup=velero/shree-testing-20200414113942 cohabitatingResource1=deployments.extensions cohabitatingResource2=deployments.apps group=extensions/v1beta1 logSource="pkg/backup/resource_backupper.go:147" resource=deployments
time="2020-04-14T04:51:49Z" level=info msg="Backing up resource" backup=velero/shree-testing-20200414113942 group=extensions/v1beta1 logSource="pkg/backup/resource_backupper.go:104" resource=replicasets
time="2020-04-14T04:51:49Z" level=info msg="Skipping resource because it cohabitates and we've already processed it" backup=velero/shree-testing-20200414113942 cohabitatingResource1=replicasets.extensions cohabitatingResource2=replicasets.apps group=extensions/v1beta1 logSource="pkg/backup/resource_backupper.go:147" resource=replicasets
time="2020-04-14T04:51:49Z" level=info msg="Backing up resource" backup=velero/shree-testing-20200414113942 group=extensions/v1beta1 logSource="pkg/backup/resource_backupper.go:104" resource=daemonsets
time="2020-04-14T04:51:49Z" level=info msg="Skipping resource because it cohabitates and we've already processed it" backup=velero/shree-testing-20200414113942 cohabitatingResource1=daemonsets.extensions cohabitatingResource2=daemonsets.apps group=extensions/v1beta1 logSource="pkg/backup/resource_backupper.go:147" resource=daemonsets

* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
velero version
Client:
	Version: v1.1.0
	Git commit: a357f21aec6b39a8244dd23e469cc4519f1fe608
Server:
	Version: v1.1.0
- Velero features (use `velero client config get features`): 

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version: 1.14.10-gke.27
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by skriss** [comment]
@shreegolang you would have to check on the status of your metrics API server; this indicates that the Kubernetes discovery API is returning an error when trying to get the resources within this API group. This is not a velero error per-se; we're just reporting the error coming back from your Kubernetes API server.

**Comment by shreegolang** [comment]
@skriss i didn't understand could you please provide me an example.

**Comment by skriss** [comment]
@shreegolang it looks like you have the custom metrics server API group installed in your cluster but it's not responding. I don't know the details of your setup, but take a look at https://github.com/kubernetes-sigs/custom-metrics-apiserver.

You can run the following via `kubectl` to see if the API group seems to be working:
```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1"
```

If you get the issue with the API group resolved, then Velero would be able to back it up just fine.

Closing this out as this is not a Velero issue.

**Comment by shreegolang** [comment]
Thanks @skriss
