### ISSUE TITLE
Velero restore PartiallyFailed for backup containing dynamic admission webhooks (prometheus-operator)

### ISSUE THREAD

**Issue by mordowiciel** [vmware-tanzu/velero#2443]
**What steps did you take and what happened:**

1) Installed [prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) Helm chart into empty `monitoring` namespace with admission webhooks enabled by default.
2) Performed a backup of whole monitoring namespace:
`velero backup create monitoring-backup-with-webhooks --include-namespaces monitoring --storage-location aws`
3) Performed a restore of the backup created in the step above.
`velero restore create --from-backup monitoring-backup-with-webhooks`
4) Checked the restore status to discover it was _PartiallyFailed_.

`velero restore describe monitoring-backup-with-webhooks-20200418164656`
https://gist.github.com/mordowiciel/0ca09251a5224af9ac7c8aef92e1e119

`velero restore logs monitoring-backup-with-webhooks-20200418164656`
https://gist.github.com/mordowiciel/3bf45bd4e24de296aa44a5699b53d71b

**Anything else you would like to add:**

After analysing the logs I've provided above, I can see that the problem lies in the order in which the resources are restored. Velero tries to restore Prometheus rules first, which results in calls to the webhooks to the prometheus-operator-operator service which hasn't been restored yet:

> time="2020-04-18T14:47:07Z" level=info msg="error restoring prometheus-operator-node.rules: Internal error occurred: failed calling webhook \"prometheusrulemutate.monitoring.coreos.com\": Post https://prometheus-operator-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=30s: service \"prometheus-operator-operator\" not found" logSource="pkg/restore/restore.go:1199" restore=velero/monitoring-backup-with-webhooks-20200418164656

The prometheus-operator-operator service is restored at the very end of the restore operation:
> time="2020-04-18T14:47:09Z" level=info msg="Attempting to restore Service: prometheus-operator-operator" logSource="pkg/restore/restore.go:1136" restore=velero/monitoring-backup-with-webhooks-20200418164656

**Environment:**

- Velero version (use `velero version`): 
**1.3.2**
- Velero features (use `velero client config get features`): 
**features: NOT SET**
- Kubernetes version (use `kubectl version`):
**Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"windows/amd64"}**
**Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}**
- Cloud provider or hardware configuration: 
**EKS (k8s version 1.14)**
- OS (e.g. from `/etc/os-release`):
**Microsoft Windows 10 Enterprise (10.0.17763 Build 17763)**

**Comment by ashish-amarnath** [comment]
Thanks for the write-up and the analysis @mordowiciel!
The priorities for performing the resource restoration is governed by https://github.com/vmware-tanzu/velero/blob/master/pkg/cmd/server/server.go#L483-L502
As a work around, you should be able to override this default to restore the rules after the necessary services have been restored.
Can you give that a try?

**Comment by mordowiciel** [comment]
Hi, thanks for the reply!

I've looked at the link you provided and checked how the corresponding steps were executed during my restore. 

What surprised me is that the list of steps seems to be incomplete. The description of default restore policy ends on `replicasets.apps` resource, while in the logs I've provided I can clearly see that after the replicasets, the other resources which are not mentioned in restore policy are also restored - for example `daemonsets.apps`, `deployments.apps`, `endpoints`, `ingresses`, and various custom resources like problematic `PrometheusRule `that I've mentioned in the first post.

In order to resolve my issue, I'd need to restore resource `services` before restoring `prometheusrules.monitoring.coreos.com`. Could you tell me how can I override the default restore policy settings in my Velero config?

**Comment by ashish-amarnath** [comment]
The restore priorities may be overridden using this flag to the velero server. https://github.com/vmware-tanzu/velero/blob/master/pkg/cmd/server/server.go#L207

**Comment by skriss** [comment]
closing this out as it has been responded to. Feel free to reach out again as needed.
