### ISSUE TITLE
Document regression testing cases

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2447]
We should document regression test cases that will eventually run on top of the e2e clusters made from #2131.

Feel free to add to this list.

I'll start with one:

 * Confirm successful restoration of ElasticSearch CRDs (#2383)

**Comment by nrb** [comment]
@ashish-amarnath I know you were interested in this topic, too. Right now I'm just capturing high level cases, not necessarily step-by-step instructions.

**Comment by ashish-amarnath** [comment]
Confirm: Velero CRDs can be applied in Various versions of Kubernetes.
Decide the list of Kubernetes versions that we want to support
