### ISSUE TITLE
restic: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by davidp1404** [vmware-tanzu/velero#2459]
I've deployed velero 1.2 with restic integration on k8s 1.16.3 (centos7). After having successful backups I started to retrieve errors like this:

$ velero backup logs daily-20200425000025 | grep -i error
time="2020-04-25T01:57:37Z" level=info msg="1 errors encountered backup up item" backup=velero/daily-20200425000025 group=v1 logSource="pkg/backup/resource_backupper.go:284" name=mysqldb-1 namespace=prod resource=pods
time="2020-04-25T01:57:37Z" level=error msg="Error backing up item" backup=velero/daily-20200425000025 error="pod volume backup failed: error running restic backup, stderr=panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7b82c8]\n\ngoroutine 32 [running]:\ngithub.com/restic/restic/internal/repository.(*Index).ID(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/restic/internal/repository/index.go:377 +0x38\ngithub.com/restic/restic/internal/repository.(*Repository).LoadIndex.func5(0x8, 0xe6c288)\n\t/restic/internal/repository/repository.go:467 +0xce\ngolang.org/x/sync/errgroup.(*Group).Go.func1(0xc00035f140, 0xc0005c0980)\n\t/restic/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x57\ncreated by golang.org/x/sync/errgroup.(*Group).Go\n\t/restic/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66\n: unable to find summary in restic backup command output" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:182" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=mysqldb-1 namespace=prod resource=pods
time="2020-04-25T02:08:57Z" level=info msg="Backing up item" backup=velero/daily-20200425000025 group=monitoring.coreos.com/v1 logSource="pkg/backup/item_backupper.go:169" name=prom-prometheus-operator-kube-apiserver-error namespace=monitoring resource=prometheusrules.monitoring.coreos.com

The error is reported only for a pvc (mysql-1), the other pod of the statefulset (between others) is backed fine.

velero backup describe daily-20200425000025 --details
...
Restic Backups:
  Completed:
    prod/alt-redis-master-0: redis-data
    prod/mysqldb-0: data
    prod/nfs-server-provisioner-0: data
  Failed:
    prod/mysqldb-1: data

-----
The repo is provisioned is:
$ velero restic repo get prod-default-kf5wm -o yaml
apiVersion: velero.io/v1
kind: ResticRepository
metadata:
  creationTimestamp: 2020-03-04T11:34:28Z
  generateName: prod-default-
  generation: 11
  labels:
    velero.io/storage-location: default
    velero.io/volume-namespace: prod
  name: prod-default-kf5wm
  namespace: velero
  resourceVersion: "32000784"
  selfLink: /apis/velero.io/v1/namespaces/velero/resticrepositories/prod-default-kf5wm
  uid: 5d44cd5a-8a31-4985-9bf4-5f3e0ac71b04
spec:
  backupStorageLocation: default
  maintenanceFrequency: 168h0m0s
  resticIdentifier: s3:https://****.******.***/k8svelerov1/restic/prod
  volumeNamespace: prod
status:
  lastMaintenanceTime: 2020-04-22T12:48:41Z
  phase: Ready

My latest successful backup was on the day before the last maintenance:
$ velero backup describe daily-20200422000037 --details
Name:         daily-20200422000037
Namespace:    velero
Labels:       velero.io/schedule-name=daily
              velero.io/storage-location=default
Annotations:  <none>
Phase:  Completed
Namespaces:
  Included:  prod, monitoring, metallb-system
  Excluded:  <none>
Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto
...
Restic Backups:
  Completed:
    prod/alt-redis-master-0: redis-data
    prod/mysqldb-0: data
    prod/mysqldb-1: data
    prod/nfs-server-provisioner-0: data

-----
I've upgraded to the latest version but the problem is still there:
$ kubectl -n velero exec -it velero-5944f87854-pcx98 bash
nobody@velero-5944f87854-pcx98:/$ ./velero version
Client:
	Version: v1.3.2
	Git commit: 55a9914a3e4719fb1578529c45430a8c11c28145
Server:
	Version: v1.3.2
nobody@velero-5944f87854-pcx98:/$ restic version
restic 0.9.6 compiled with go1.13.4 on linux/amd64

**Comment by ashish-amarnath** [comment]
This may be another instance of https://github.com/vmware-tanzu/velero/issues/2507

**Comment by ashish-amarnath** [comment]
You are hitting this bug in restic https://github.com/restic/restic/issues/2345
We'll have to wait for restic to fix this bug.

**Comment by davidp1404** [comment]
Hello, just share that after upgrading velero to v1.3.2 the backups are fine again.
Thanks you all for your help and comments.

**Comment by mereddy22** [comment]
@ashish-amarnath i'm getting this similar error on velero backup
**Velero version 1.4.0**
**AKS version 1.15.10**

NAME             STATUS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
firstbackup      Failed   2020-06-01 18:53:07 +0000 UTC   29d       default            <none>
firstbackup-11   Failed   2020-06-01 19:00:35 +0000 UTC   29d       default            <none>

**Error from the velero logs**
time="2020-06-01T19:00:55Z" level=info msg="Processing item" backup=velero/firstbackup-11 logSource="pkg/backup/backup.go:371" name=kube-prometheus-prometheus-kube-apiserver-error namespace=monitoring progress= resource=prometheusrules.monitoring.coreos.com
time="2020-06-01T19:00:55Z" level=info msg="Backing up item" backup=velero/firstbackup-11 logSource="pkg/backup/item_backupper.go:119" name=kube-prometheus-prometheus-kube-apiserver-error namespace=monitoring resource=prometheusrules.monitoring.coreos.com
time="2020-06-01T19:00:55Z" level=info msg="Backed up 622 items out of an estimated total of 657 (estimate will change throughout the backup)" backup=velero/firstbackup-11 logSource="pkg/backup/backup.go:411" name=kube-prometheus-prometheus-kube-apiserver-error namespace=monitoring progress= resource=prometheusrules.monitoring.coreos.com

Name:         firstbackup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.15.10
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=15

Phase:  Failed (run `velero backup logs firstbackup` for more information)

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-06-01 18:53:07 +0000 UTC
Completed:  2020-06-01 18:53:29 +0000 UTC

Expiration:  2020-07-01 18:53:07 +0000 UTC

Total items to be backed up:  656
Items backed up:              656

is the #restic fixed the bug?
should I downgrade to try in 1.3.2 velero version?

**Comment by ashish-amarnath** [comment]
@mereddy22 
The bug in restic, https://github.com/restic/restic/issues/2345, hasn't been fixed.
Switching to Velero 1.3.2 is not going to fix this.

**Comment by mereddy22** [comment]
@ashish-amarnath is there any way to exclude namespace=monitoring from the backup and also in schedule everyday backup.

**Comment by ashish-amarnath** [comment]
Yes, please take a look at our go docs here https://pkg.go.dev/github.com/vmware-tanzu/velero/pkg/apis/velero/v1?tab=doc#BackupSpec
for more details

**Comment by mereddy22** [comment]
@ashish-amarnath  all our backups are in failed state.
i'm seeing this in the pod log

time="2020-06-01T21:31:50Z" level=error msg="backup failed" controller=backup error="[rpc error: code = Unavailable desc = transport is closing, rpc error: code = Unavailable desc = connection error: desc = \"transport: error while dialing: dial unix /tmp/plugin632572141: connect: connection refused\"]" key=velero/thirdbackup logSource="pkg/controller/backup_controller.go:273"

all our backups are failing.

firstbackup      Failed   2020-06-01 18:53:07 +0000 UTC   29d       default            <none>
firstbackup-11   Failed   2020-06-01 19:00:35 +0000 UTC   29d       default            <none>
secondbackup     Failed   2020-06-01 19:30:51 +0000 UTC   29d       default            <none>
thirdbackup      Failed   2020-06-01 21:31:27 +0000 UTC   29d       default            <none>

can you provide the command or steps to exclude the monitoring or any particular namespaces in the velero installed clusters.
