### ISSUE TITLE
Restoring using different image registry

### ISSUE THREAD

**Issue by MatteoManzoni** [vmware-tanzu/velero#2460]
During a Disaster Recovery of a our cluster we should be able to restore pointing a image registry different from the one defined in our backed-up manifests.
This feature can be used in many contexts such as: restoring an on prem cluster in EKS switching from on prem registry to ECR populated with prepushed images.

To workaround this missing feature we are evaluating the use of a service exposing an internal registry to leverage the internal resolution of the cluster.
(This workaround preclude the use of ECR)

**Comment by ashish-amarnath** [comment]
If I understand your question correctly, the ask is to be able to patch image names on the container spec with a different registry for the images.
We might not be able to do that in the core velero code. However, you should be able to write a very simple RestoreItemAction plugin that will do that for you. Suggest referring to our [plugins documentation](https://velero.io/docs/v1.3.2/custom-plugins/) for more information.

If you would like help getting started on the plugin implementation, hit us up on #velero channel in kubernetes slack. You can also attend our weekly community meetings to connect with us. Info on that is available here https://velero.io/community

**Comment by MatteoManzoni** [comment]
Thank you! I will certainly ask for help once I start writing the plugin.
