### ISSUE TITLE
Investigate moving multiarch builds to docker buildx

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2464]
As pointed out in [this comment](https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/36#issuecomment-616093128), the [`docker buildx`](https://docs.docker.com/buildx/working-with-buildx/) command could simplify our Dockerfile pipeline when it comes to multiarch builds.

We should investigate this, as it could make adding more architectures easier down the line, both for core Velero and plugins.

**Comment by ashish-amarnath** [comment]
This was resolved by https://github.com/vmware-tanzu/velero/pull/2754
Closing this issue.
