### ISSUE TITLE
Unable to do backup on few clusters

### ISSUE THREAD

**Issue by surekhakallam** [vmware-tanzu/velero#2475]
hi...
we are able to take backup and restore on few setups but we are unable to do on some other setups..... We use the same OS for all our clusters and we are using vsphere ... Still we are able to take backup and restore them backup on few of our clusters but unable to take on few.. is there anything that will stop or block for taking backup's can you please tell us ... The one error which we found is as follows....

pod volume backup failed: error getting volume path on host: expected one matching path, got 0

**Comment by ashish-amarnath** [comment]
This looks like a dup of #2506 
Closing this one out. Please re-open if this is a different problem.
