### ISSUE TITLE
Allow selecting namespaces to backup on a NS label instead of the NS names

### ISSUE THREAD

**Issue by titou10titou10** [vmware-tanzu/velero#2477]
`velero backup create`allows to backup:
- all resources from namespaces included by their names:`--include-namespaces`
- resources that match a certain label :`--selector` (possibly more restricted by the`--include-namespaces` above)

What we need is to backup everything belonging to namespaces that have specifically a certain label attached, ie select the namespaces to backup based on an label assigned directly to the namespace, instead of their names

Is there a way to do this?

If not, it would be something like adding a new parameter for this:  `--include-namespaces-selector`?
Thx

**Comment by skriss** [comment]
@titou10titou10 unfortunately Velero does not currently support this. 

We do already have a feature request for this in the backlog - see https://github.com/vmware-tanzu/velero/issues/503. I'm going to close that one out and leave this one open for tracking. 

Are you interested in working on a contribution here? If so, we can discuss more on what the design for this would look like.

**Comment by bsctl** [comment]
Having a namespace label selector for all the objects in that namespace, would be a great improvement usage of Velero.

**Comment by eleanor-millman** [comment]
Closing because will be handled when  #2413 is implemented.
