### ISSUE TITLE
Velero backup and restore logs with tailing option

### ISSUE THREAD

**Issue by prasenforu** [vmware-tanzu/velero#2482]
Instead of complete the backup & restore, logs are not available.

```Logs for restore "velero-restore-london-cluster-30-04-2020-05-38-34" are not available until it's finished processing. Please wait until the restore has a phase of Completed or Failed and try again.```

it will be good if we can tail live logs.

**Comment by ashish-amarnath** [comment]
In the 1.4 release, we now have a way to track the progress of a backup operation using the backup describe command.
Further, you are also able to tail the logs from the velero server pod using `kubectl -n velero logs -f deploy/velero`

We are unable to implement this at the moment. PRs are welcome :)

**Comment by ashish-amarnath** [comment]
I am going to close this issue. Please re-open if you would like to work on this.
