### ISSUE TITLE
How can I add additional metrics

### ISSUE THREAD

**Issue by Samet-MohamedAmin** [vmware-tanzu/velero#2485]
I'm using velero helm installation. I'm using velero for backup and restore kubernetes objects and I'm exposing the metrics to grafana.
It works fine. But I need additional metrics such as the application name and the namespace.
Is ther any way to expose additional metrics?

- Velero version (use `velero version`):
```
$ velero version
Client:
        Version: v1.3.1
        Git commit: 0665b05321eefeb7b7fdd6984750745b7429774f
```
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by skriss** [comment]
@Samet-MohamedAmin any additional metrics would need to be added in the Velero code base.

**Comment by konvergence** [comment]
Hi,
To complete the request, it will really usefull to have tags on the backup name or the schedule name
To be able to make alerts on which backup is in error

**Comment by ashish-amarnath** [comment]
We do have have the schedule name as a label on the metrics. So you should be able to track the success and setup alerting for backups made under a schedule.
Further, all the backups that are not part of a schedule will have `""` as their schedule label. 

Adding any further labeling on the metrics will have to be done in the Velero code base.

I don't think the application names and the application namespaces should be labels on backup status metrics as a backup can span multiple applications and namespaces. If you have a use case, please share it with us during our weekly community call and we can suggest work arounds or evaluate how best to support. your use case. Details about the community call is available here https://velero.io/community/

**Comment by ashish-amarnath** [comment]
@Samet-MohamedAmin and @konvergence 
If either of you would like to work on adding more metrics the code is available in [`pkg/metrics`](https://github.com/vmware-tanzu/velero/blob/master/pkg/metrics/metrics.go) 
Thanks in advance 😄
