### ISSUE TITLE
Document v1.4 upgrade process

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2495]
This is just a list of items that need to be documented for users to upgrade for v1.4 specifically. Please update the description to add anything missing.

 * [ ] Update CRDs so that the progress fields are included (#2440)

**Comment by skriss** [comment]
I took a quick look through the changelogs and the item you listed is the only one that comes to mind other than tag bumps, but I'll keep an eye out for anything else.

**Comment by skriss** [comment]
See https://velero.io/docs/v1.2.0/upgrade-to-1.2/ for a past instance where we needed to update the CRDs. We should be able to do the same for this release.

**Comment by skriss** [comment]
I'll plan to get a doc in for this today or tomorrow, unless someone beats me to it.
