### ISSUE TITLE
Add a Tilt setup for rapid local development

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#2501]
**Why:** Have one additional way to easily and quickly to build/run/test the Velero code base. Good for anyone contributing to Velero, but especially good for newcomers to the code base. Main results: 1) the setup will only consist of a few, easy items and 2) continuous code changes would require no manual interactions to deploy the code.

**How:** Set up Tilt to: rebuild binaries (triggered based on files the user specifies for Tilt to watch), send any new binary to the pod, and restart the pod after every change.

**Examples:**
Cluster API's documentation of their setup:
https://cluster-api.sigs.k8s.io/developer/tilt.html

Andy Goldstein gave a 20min demo of how the Cluster API tilt setup is done/used:
https://www.youtube.com/watch?v=EVEA5NnrucU&t=140s

**Comment by ashish-amarnath** [comment]
@carlisia I think we can move this to a later release. WDYT?

**Comment by carlisia** [comment]
Yes, thank you. I thought I was gonna have more slack this cycle but, nope. Moved to 1.6, I this this might go a long way in helping newcomers boot up and run a development environment so maybe should be done sooner rather than later. But that can be changed.
