### ISSUE TITLE
Check for apiextensions.k8s.io/v1beta1 before using a v1beta1 CRD client

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2504]
**Describe the problem/challenge you have**
The upstream [CRD code](https://github.com/kubernetes/apiextensions-apiserver/blob/99685ba23021e88fc9a771f029157b348fd92bab/pkg/apis/apiextensions/v1beta1/types.go#L380) states that v1beta1 is planned for removal in v1.19.

**Describe the solution you'd like**
Velero should check the apiextensions.k8s.io/v1beta1 endpoint before using a client for it. We don't want to invoke a client for an unsupported endpoint.

**Comment by angelbarrera92** [comment]
```

WARN - velero.yml - CustomResourceDefinition/backups.velero.io: API apiextensions.k8s.io/v1beta1 for CustomResourceDefinition is deprecated in 1.19, use apiextensions.k8s.io/v1 instead.
--
```

1.19 deprecates v1beta1 api.
Is there any plan to release a new version migrating from v1beta1 to v1 to support Kubernetes 1.19?
Thanks!
