### ISSUE TITLE
Update velero server version

### ISSUE THREAD

**Issue by yogeek** [vmware-tanzu/velero#2508]
**What steps did you take and what happened:**

I had a 1.3.0 Velero server previously installed from velero CLI 1.3.0 on a cluster.
I wanted to update to 1.3.2.
First, I updated the velero CLI :
```
Client:
	Version: v1.3.2
	Git commit: 55a9914a3e4719fb1578529c45430a8c11c28145
Server:
	Version: v1.3.0
```

then I executed again my install command :
```
velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.0.0 \
    --no-secret \
    --pod-annotations iam.amazonaws.com/role=${KUBE2IAM_ROLE_NAME} \
    --bucket ${BUCKET_NAME} \
    --wait
```

But Velero has not been updated :
```
Client:
	Version: v1.3.2
	Git commit: 55a9914a3e4719fb1578529c45430a8c11c28145
Server:
	Version: v1.3.0
```

Yet, the documentation of the CLI mention that the velero "image-version" is supposed to be the `1.3.2`
```
velero install -h
[...]
--image string         image to use for the Velero and restic server pods. Optional. (default "velero/velero:v1.3.2")
[...]
```

**What did you expect to happen:**

I expected Velero to be updated to 1.3.2  

**Environment:**

- Velero version : cf. above
- Velero features (use `velero client config get features`): 
```
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
kubectl version                                                                                                     
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"
```
- Kubernetes installer & version: kubeadm 
- Cloud provider or hardware configuration: AWS EC2 ubuntu

**Comment by skriss** [comment]
xref #1087

**Comment by yogeek** [comment]
@skriss do you think having 2 different commands to manage the installation and the upgrade phase is a good idea ? 
In my case for example, velero is one of many addons that are installed on my K8S clusters with a Jenkins pipeline than is idempotent, and I do want to handle differently the initial install and the update of the tools. 
To update a tool, I only modify a environment variable pointing to the tool version, push the code and the pipeline is launched on the cluster : if the tool is installed, it is updated, if not it is installed.

I would find more intuitive to have a behaviour closer to `kubectl apply` (or other similar "cloud-native" CLI) where `velero install` manage both the first install and the update by applying the YAML generated by the CLI.

**Comment by nrb** [comment]
@yogeek The plan is to deprecate `velero install` in favor of more explicit tools that handle this better. Right now, `velero install` only checks that a Deployment exists; it does not do anything more detailed than that.

Are you saying your preference would be that you want initial installation and upgrading to be the exact same command?

**Comment by yogeek** [comment]
@nrb yes indeed, it seems to me that currently, a 'Declarative ' approach like `kubectl apply` is preferable (over an 'Imperative' approach like `kubectl create`)

Otherwise, we will always have to check if velero is installed first to know which command we have to call.

**Comment by yogeek** [comment]
Additionnal notes : I tried the `velero install [...] --dry-run -o yaml | kubectl apply -f -` method (mentionned in velero Slack channel) to cover both cases (install & update) but it caused an error for the install phase because the manifests are all applied at the same time and the CRDs are not finished to be created when the corresponding CustomResources are applied... so the classic race condition between CRD and resources occurs with this solution.

For now, I cannot find a proper way to handle both cases similarly (and to me `velero install` should address that like istioctl does that for Istio for example)

**Comment by skriss** [comment]
@yogeek I've updated #1087 per your comments and linked to this issue from there. I'm going to close this one out as a duplicate, and we'll track the other one going forward.
