### ISSUE TITLE
Ability to keep a backup from being garbage collected

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#251]
Add the ability to preserve a backup. This could mean one of a few things:

- be able to specify a ttl of 0 == never expire
- be able to change a backup's expiration after it's been created
- be able to mark a backup as pinned/preserved so that the expiration is ignored

**Comment by skriss** [comment]
Personally I like the UX of pin/unpin. We might want to reset the expiration upon unpin, otherwise unpinning an expired backup could result in a near-immediate GC, which might not be desirable.

**Comment by lypht** [comment]
Feature request: The ability to ship a preserved backup to a source of record separate from the primary backup location for audits/reference.

**Comment by ncdc** [comment]
That will be covered by #103

**Comment by rosskukulinski** [comment]
Yes! Simple is best here.

I think the key flag here is the “Pin / Unpin” action.  Pinning a backup should apply a label to the backup, such that a replication policy can be configured to match pinned backups.

Specifying a ttl of 0 automatically sets the Pin flag

Changing a backup’s expiration after it’s been created feels like a different feature/issue to me.

**Comment by bastoker** [comment]
Is there any update on the pin/unpin front? I'm curious if I can change or delete the TTL and expiration from deBackup CRD?

**Comment by skriss** [comment]
@bastoker we haven't implemented this feature yet, no.

You *can* always manually edit the TTL/expiration of a backup, e.g. `kubectl -n velero edit backup.velero.io <NAME>`. Note that the `status.expiration` field is the one that Velero will actually look at to determine when to delete expired backups.
