### ISSUE TITLE
Document airgapped installation

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2513]
While we have a page for on-prem installations at https://velero.io/docs/v1.3.2/on-premises/, we should add the following:

 * How to get velero & plugin images into an airgapped registry
 * Get the on-premises/airgapped page back in the TOC

Use https://sonobuoy.io/docs/master/airgap/ as a starting point

This should be ready with v1.4 GA, but not necessarily a blocker for 1.4.beta1.

**Comment by skriss** [comment]
@nrb i'm not considering this release-blocking since it's general docs, but it'd be good to knock this out soon.
