### ISSUE TITLE
Document Velero feature flags

### ISSUE THREAD

**Issue by ashish-amarnath** [vmware-tanzu/velero#2515]
+1 for keeping the feature flag list small.
But we should also have a way for users to discover feature flags. That's the problem I am looking to solve here and this was the easiest way to do that today.
Some options for us to consider:
1. having a features page on the website
2. having a CLI command list all features

My vote is for option2

_Originally posted by @ashish-amarnath in https://github.com/vmware-tanzu/velero/pull/2511_

**Comment by a-mccarthy** [comment]
@ashish-amarnath can you comment here if this is still needed? Do you still think this is better as a CLI update than as docs?

**Comment by eleanor-millman** [comment]
Closing, let's just keep these in the release notes.
