### ISSUE TITLE
Investigate new integration test possibilities

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#2518]
Why? Because mocks argh.

Below are options not for e2e, not for unit testing, but for integration testing.

# Integration testing

## evntest
https://book.kubebuilder.io/reference/writing-tests.html

Examples:
- https://github.com/kubernetes-sigs/cluster-api/tree/master/controllers
- https://github.com/microsoft/azure-databricks-operator/tree/master/controllers

Requirements
- it can point to a locally built etcd/apiserver binaries (probably the more CI/CD friendly)
- or can point to an existing/running cluster 

Note: Maybe packaging the etcd and apiserver binaries in a docker container used by a github action would work.

It works with other testing packages that test in the BDD style. I personally think this is a plus, we could benefit from laying out the behavior to test from the time of spec'ing.

Only for controllers.

## rigging
https://github.com/n3wscott/rigging

Examples:
- https://github.com/n3wscott/rigging/tree/master/example
- https://github.com/mattmoor/mink/blob/master/.github/workflows/minkind.yaml (GH action that runs e2e tests in kind)

It "leverages lightly templated yaml files". The knative folks are trying to get it into that project (https://github.com/knative/sample-controller/pull/175). @n3wscott has offered to showcase.

Fork of https://github.com/manifestival/manifestival.

Requirements
- needs a running cluster.

## KUTTL

https://kuttl.dev/

**Comment by eleanor-millman** [comment]
Closing because we expect to focus on E2E for the next few releases, but happy to revisit this after.
