### ISSUE TITLE
Velero restore PVC in "lost" state 

### ISSUE THREAD

**Issue by philipp1992** [vmware-tanzu/velero#2519]
Ive installed Velero 1.3.1 with restic and aws provider (using minio) to backup my rook-ceph PVCs.
Storageclass reclaim policy is "delete"

After creating a backup, i can confirm from the size of the bucket, that restic data gets backuped.
Also logs show no errors.

When i do a restore with:

`velero restore create --from-backup=test` the following happens:

1: all kubernetes objects from the backuped namespace get restored instantly
2: the PVCs are now "LOST"
3: Backup stuck in progress, because its waiting for the PVCs to be bound.

```
NAME                                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
data-90557299-1e03-4008-a5fd-4407992d513b-6-mariadb-0              Lost     pvc-5d3d491e-9a63-419e-a2b8-f5b66c44f234   0                         rook-ceph-block   23m
data-duemmling-mariadb-0                                           Lost     pvc-e5fcd976-8111-43f0-9616-f2e07d6dd4b4   0                         rook-ceph-block   23m
duemmling-datacastle-nextcloud                                     Lost     pvc-9462618b-4628-4ab2-bd0b-905f9846f8ce   0                         rook-ceph-block   23m
redis-data-90557299-1e03-4008-a5fd-4407992d513b-6-redis-master-0   Lost     pvc-8d8a1bd0-ef6b-4c3d-acb2-81518358472c   0                         rook-ceph-block   23m
redis-data-duemmling-redis-master-0                                Lost     pvc-a22943e0-1162-4efa-a6e8-cc09cc7fd067   0                         rook-ceph-block   23m
```

How can i tell velero to not restore the PVCs with their old PV (which does not exist in case of disaster recovery) but instead request a new PVC, when will then create a new PV?

Ive also tried with the flag `--restore-volumes` but same result.

**Comment by skriss** [comment]
@philipp1992 can you provide the output of `velero backup describe test --details`? I'm curious to see if you have restic backups that appear there.

**Comment by skriss** [comment]
Looks like this is inactive, so closing it out. Feel free to reach out again as needed.

**Comment by iyurev** [comment]
> Ive installed Velero 1.3.1 with restic and aws provider (using minio) to backup my rook-ceph PVCs.
> Storageclass reclaim policy is "delete"
> 
> After creating a backup, i can confirm from the size of the bucket, that restic data gets backuped.
> Also logs show no errors.
> 
> When i do a restore with:
> 
> `velero restore create --from-backup=test` the following happens:
> 
> 1: all kubernetes objects from the backuped namespace get restored instantly
> 2: the PVCs are now "LOST"
> 3: Backup stuck in progress, because its waiting for the PVCs to be bound.
> 
> ```
> NAME                                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
> data-90557299-1e03-4008-a5fd-4407992d513b-6-mariadb-0              Lost     pvc-5d3d491e-9a63-419e-a2b8-f5b66c44f234   0                         rook-ceph-block   23m
> data-duemmling-mariadb-0                                           Lost     pvc-e5fcd976-8111-43f0-9616-f2e07d6dd4b4   0                         rook-ceph-block   23m
> duemmling-datacastle-nextcloud                                     Lost     pvc-9462618b-4628-4ab2-bd0b-905f9846f8ce   0                         rook-ceph-block   23m
> redis-data-90557299-1e03-4008-a5fd-4407992d513b-6-redis-master-0   Lost     pvc-8d8a1bd0-ef6b-4c3d-acb2-81518358472c   0                         rook-ceph-block   23m
> redis-data-duemmling-redis-master-0                                Lost     pvc-a22943e0-1162-4efa-a6e8-cc09cc7fd067   0                         rook-ceph-block   23m
> ```
> 
> How can i tell velero to not restore the PVCs with their old PV (which does not exist in case of disaster recovery) but instead request a new PVC, when will then create a new PV?
> 
> Ive also tried with the flag `--restore-volumes` but same result.

Hi, Did you solve that problem? I’ve faced with exact similar  problem.

**Comment by philipp1992** [comment]
nope

> > Ive installed Velero 1.3.1 with restic and aws provider (using minio) to backup my rook-ceph PVCs.
> > Storageclass reclaim policy is "delete"
> > After creating a backup, i can confirm from the size of the bucket, that restic data gets backuped.
> > Also logs show no errors.
> > When i do a restore with:
> > `velero restore create --from-backup=test` the following happens:
> > 1: all kubernetes objects from the backuped namespace get restored instantly
> > 2: the PVCs are now "LOST"
> > 3: Backup stuck in progress, because its waiting for the PVCs to be bound.
> > ```
> > NAME                                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
> > data-90557299-1e03-4008-a5fd-4407992d513b-6-mariadb-0              Lost     pvc-5d3d491e-9a63-419e-a2b8-f5b66c44f234   0                         rook-ceph-block   23m
> > data-duemmling-mariadb-0                                           Lost     pvc-e5fcd976-8111-43f0-9616-f2e07d6dd4b4   0                         rook-ceph-block   23m
> > duemmling-datacastle-nextcloud                                     Lost     pvc-9462618b-4628-4ab2-bd0b-905f9846f8ce   0                         rook-ceph-block   23m
> > redis-data-90557299-1e03-4008-a5fd-4407992d513b-6-redis-master-0   Lost     pvc-8d8a1bd0-ef6b-4c3d-acb2-81518358472c   0                         rook-ceph-block   23m
> > redis-data-duemmling-redis-master-0                                Lost     pvc-a22943e0-1162-4efa-a6e8-cc09cc7fd067   0                         rook-ceph-block   23m
> > ```
> > 
> > 
> > How can i tell velero to not restore the PVCs with their old PV (which does not exist in case of disaster recovery) but instead request a new PVC, when will then create a new PV?
> > Ive also tried with the flag `--restore-volumes` but same result.
> 
> Hi, Did you solve that problem? I’ve faced with exact similar problem.

nope
