### ISSUE TITLE
Unable to properly restore  Kubernetes service catalog objects 

### ISSUE THREAD

**Issue by koundinyabs** [vmware-tanzu/velero#2528]
**What steps did you take and what happened:**
Backed up a K8s cluster with the latest Kubernetes service catalog (0.3.0-beta.2 which happens to use CRDs) installed on it that was also used to provision an external Postgres service isntance. A restore was then attempted. However, the restored service instance from the service catalog backup is not automatically relinking to the existing external service instance (Postgres database in this case), but it instead attempts to provision the same external database instance.  

##Testing Process

**Creating Service Catalog Resources:**
* Registered Postgres service broker.
* Created a Postgres service instance.
* Created a service binding for this service instance which also implicitly creating k8s secret.

**Back up command**

```
$ velero backup create service-catalog  --include-resources "clusterservicebrokers.servicecatalog.k8s.io,clusterserviceclasses.servicecatalog.k8s.io,clusterserviceplans.servicecatalog.k8s.io,serviceinstances.servicecatalog.k8s.io,servicebindings.servicecatalog.k8s.io,secrets" –wait
```

**Deleting Service Catalog Resources:**
To simulate the data lost in the cluster and leave the external service instance (Postgres database) orphaned, we need to update the service broker resource to use the wrong port, so the service catalog controller could not connect to the Postgres service broker when forcibly deleting the service catalog resources.
1. Deleted the service binding for Postgres instance which also implicitly deleting the secret.
1. Deleted the Postgres service instance.
1. Deregistered the Postgres service broker.

Checked the Postgres server and made sure that we still have the database created as part of the service instance provisioning.

**Restoring Service Catalog Resources from the Backup:**

`$ velero restore create --from-backup service-catalog --wait
`

**Problem with Service Instance after Restore:**
When checking on the service catalog resources after the restore process is finished, the service instance has failed status,
 
```
$ kubectl get serviceinstances
NAME             CLASS                            PLAN            STATUS                AGE
pg-instance-01   ClusterServiceClass/dev-pg-sid   dev-pg-devpid   ProvisionCallFailed   11h
```
**NOTE**: Status is `ProvisionCallFailed`

And with the following error found in the event logs of the service instance,
 
```
Events:
  Type     Reason               Age                From                                Message
  ----     ------               ----               ----                                -------
  Warning  RetryBackoff         47s (x2 over 47s)  service-catalog-controller-manager  Delaying provision retry, next attempt will be after 2020-04-09 09:27:35.267307237 +0000 UTC m=+9.164867324
  Warning  RetryBackoff         46s (x2 over 46s)  service-catalog-controller-manager  Delaying provision retry, next attempt will be after 2020-04-09 09:27:37.662463581 +0000 UTC m=+11.560023671
  Warning  RetryBackoff         44s (x2 over 44s)  service-catalog-controller-manager  Delaying provision retry, next attempt will be after 2020-04-09 09:27:41.867657212 +0000 UTC m=+15.765217309
  Warning  RetryBackoff         39s (x2 over 39s)  service-catalog-controller-manager  Delaying provision retry, next attempt will be after 2020-04-09 09:27:50.020582426 +0000 UTC m=+23.918142515
  Warning  RetryBackoff         31s (x2 over 31s)  service-catalog-controller-manager  Delaying provision retry, next attempt will be after 2020-04-09 09:28:06.174067452 +0000 UTC m=+40.071627550
  Warning  ProvisionCallFailed  15s (x6 over 48s)  service-catalog-controller-manager  Error provisioning ServiceInstance of ClusterServiceClass (K8S: "dev-pg-sid" ExternalName: "dev-pg") at ClusterServiceBroker "dev-postgres-broker": Status: 409; ErrorMessage: <nil>; Description: <nil>; ResponseError: <nil>
  Warning  RetryBackoff         15s (x2 over 15s)  service-catalog-controller-manager  Delaying provision retry, next attempt will be after 2020-04-09 09:28:38.352269746 +0000 UTC m=+72.249829834
```
 
It looked like when the service instance is restored back to the cluster, the service catalog controller detects the instance as a new resource to be added, and thus tried to call the Postgres service broker to provision the same service instance (database) which already existed.  
 
Service Catalog Controller Log:
`I0409 09:27:32.450718       1 controller_instance.go:147] ServiceInstance "backing-services/pg-instance-01" v8370686: Received ADD event: {"kind":"ServiceInstance","apiVersion":"servicecatalog.k8s.io/v1beta1","metadata":{"name":"pg-instance-01","namespace":"backing-services","selfLink":"/apis/servicecatalog.k8s.io/v1beta1/namespaces/backing-services/serviceinstances/pg-instance-01","uid":"869f424d-7a43-11ea-b06a-1ed9bdd25d7a","resourceVersion":"8370686","generation":1,"creationTimestamp":"2020-04-09T09:21:42Z","labels":{"servicecatalog.k8s.io/spec.clusterServiceClassRef.name":"5b35f3e6aba00e259a808e4aa9aef33c4f6e1914049179faadb87b96","servicecatalog.k8s.io/spec.clusterServicePlanRef.name":"d11059f11f8149fe477a6d4bace1b2c69ad423c54cdf47c8a137f2d5","velero.io/backup-name":"service-catalog","velero.io/restore-name":"service-catalog-20200409022129"},"finalizers":["kubernetes-incubator/service-catalog"]},"spec":{"clusterServiceClassName":"dev-pg-sid","clusterServicePlanName":"dev-pg-devpid","parameters":{},"externalID":"20198954-1445-4600-ad3e-d083d3faadd6","userInfo":{"username":"system:serviceaccount:velero:velero","uid":"83b3507e-72de-11ea-8e09-7e6ebe78e9a7","groups":["system:serviceaccounts","system:serviceaccounts:velero","system:authenticated"]},"updateRequests":0},"status":{"conditions":null,"asyncOpInProgress":false,"orphanMitigationInProgress":false,"reconciledGeneration":0,"observedGeneration":0,"provisionStatus":"","deprovisionStatus":"","lastConditionState":"","userSpecifiedPlanName":"","userSpecifiedClassName":""}}
` 
Postgres Service Broker Log:
```
2020-04-09 10:01:43.292  INFO 1418 --- [http-nio-8080-exec-8] c.e.c.b.p.d.ServiceInstanceRepository    : Trying to get service instance, instance id is 20198954-1445-4600-ad3e-d083d3faadd6
2020-04-09 10:01:43.293 DEBUG 1418 --- [http-nio-8080-exec-8] o.s.jdbc.core.JdbcTemplate               : Executing prepared SQL query
2020-04-09 10:01:43.293 DEBUG 1418 --- [http-nio-8080-exec-8] o.s.jdbc.core.JdbcTemplate               : Executing prepared SQL statement [SELECT * FROM t_service_instance WHERE serviceInstanceId = ?]
2020-04-09 10:01:43.304 DEBUG 1418 --- [http-nio-8080-exec-8] c.e.c.b.p.d.ServiceInstanceRepository    : Get service instance information from database:
serviceDefinitionId=dev-pg-sid
serviceInstanceId=20198954-1445-4600-ad3e-d083d3faadd6
planId=dev-pg-devpid
organizationGuid=32bce1b5-8f8d-4ed5-a559-ecdb4cc4465a
spaceGuid=9f224685-749f-11ea-8e09-7e6ebe78e9a7
2020-04-09 10:01:43.305  INFO 1418 --- [http-nio-8080-exec-8] c.e.c.b.pg.service.PGInstanceService     : The service instance already exists.

```

Also scaling down the service catalog controller to 0 before the restore and scaling it back up again after the restore did not help either.

**Conclusion:** The restored service instance from the service catalog backup is not automatically relinked to the existing external service instance (Postgres database in this case), but attempted to provision the same external database instance instead.  

**What did you expect to happen:**

The restored service instance from the service catalog backup automatically relinks to the existing external service instance (Postgres database in this case), rather than attempt to provision the same external database instance.  

**Anything else you would like to add:**

**Note**: Check out the [following note about service catalog migration](https://github.com/kubernetes-sigs/service-catalog/blob/master/docs/migration-apiserver-to-crds.md) . Based on the steps described, it looks like there is a way to backup and then restore the service catalog resources with properly linked to externally existing service instances. Maybe after the restore, additional changes are warranted, and thus the service catalog resources such as service instances need to be updated in such a way telling the controller to link to the external database instance instead of creating the same instance.

**Environment:**

To be added shortly.

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by ashish-amarnath** [comment]
Summarizing the issue here:
Service catalog allows in-cluster applications to use managed services outside of Kubernetes.
The backup and restore of CRDs of the service catalog API objects should preserve links to the out-of-cluster entities on a velero backup and restore the links on a velero restore.

@koundinyabs: Please pitch in with any details that I may have missed in my summary.

The service catalog controller seems to be storing state in the CRD's status that gets stripped on restore. We might need a restore action plugin for service catalog API objects to handle this scenario.

**Comment by koundinyabs** [comment]
@ashish-amarnath That is very well summarized. 

Do you need more details on the velero and K8s version?
