### ISSUE TITLE
adjust `velero backup describe` output for CSI snapshots

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero#2531]
I have the CSI feature flags enabled, but I took a backup in a namespace that didn't have any CSI volumes. The output looks like:

```
...
Velero-Native Snapshots: <none included>

Restic Backups:
  Completed:
    nginx-example/nginx-deployment-f96b7fd86-k64w6: nginx-logs
CSI Volume Snapshots:
```

I think we should:
- add another newline above "CSI Volume Snapshots" for spacing (PVBs do so [here](https://github.com/vmware-tanzu/velero/blob/2a144ec3b3c2fd1fe6ebbd154fdec59dda117604/pkg/cmd/util/output/backup_describer.go#L91-L92) but CSI does not [here](https://github.com/vmware-tanzu/velero/blob/2a144ec3b3c2fd1fe6ebbd154fdec59dda117604/pkg/cmd/util/output/backup_describer.go#L96)
- add a `<none included>` description [here](https://github.com/vmware-tanzu/velero/blob/master/pkg/cmd/util/output/backup_describer.go#L500-L504) if there are no CSI snapshots in the backup, to match Velero-Native snapshots
- probably move CSI Volume Snapshots up above restic, so it's just below Velero-Native Snapshots, I think this is slightly better in terms of organization

**Comment by nrb** [comment]
Changes sound good to me with one exception - as I'm writing them, putting the `<none included>` message [here](https://github.com/vmware-tanzu/velero/blob/master/pkg/cmd/util/output/backup_describer.go#L495) makes more sense to me, since we have the length to report whether details were requested or not.
