### ISSUE TITLE
dial tcp: lookup bucket.s3.ap-southest-1.amazonaws.com on x.x.x.x:53: no such host

### ISSUE THREAD

**Issue by edgardang** [vmware-tanzu/velero#2536]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
My issue is facing when install velero
I'm trying install velero with aws provider with command:
`velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.0.0 --bucket velero-backup-cluster --backup-location-config region=ap-southest-1 --snapshot-location-config region=ap-southest-1 --secret-file ./credentials-velero`

but when check log it showing error:
Command: `kubectl logs deployment/velero -n velero` 
Error: `An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = RequestError: send request failed
caused by: Get https://velero-backup-cluster.s3.ap-southest-1.amazonaws.com/?delimiter=%2F&list-type=2&prefix=: dial tcp: lookup velero-backup-cluster.s3.ap-southest-1.amazonaws.com on 10.43.0.10:53: no such host`

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

*` aws credentials `**: credentials-velero
![image](https://user-images.githubusercontent.com/64779913/81925285-81d0b700-960a-11ea-9e31-9c0cdc84f6e6.png)

Please help me fix error.

** I followed this document: https://github.com/vmware-tanzu/velero-plugin-for-aws **

**Environment:**

- Velero version (use `velero version`): v1.3.2
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.15.5
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): 18.04

**Comment by ishworgurung** [comment]
Is DNS functional to begin with :question:

**Comment by ashish-amarnath** [comment]
@ishworgurung looks like you are using the incorrect region name `ap-southest-1`, the correct region name is `ap-southeast-1`.
Can you also please clarify where you are running Velero from, where is your kubernetes cluster located?
Suggest confirming network connectivity from your kubernetes cluster to aws s3.

**Comment by skriss** [comment]
Closing this out as it looks like the region name typo was the culprit, feel free to reach out again as needed.
