### ISSUE TITLE
--cacert prevents pod deployment from running

### ISSUE THREAD

**Issue by jcwimer** [vmware-tanzu/velero#2555]
**What steps did you take and what happened:**
Install Velero with:
```
#!/bin/bash
./velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.0.0 \
    --bucket k8s-velero-backup \
    --secret-file /root/minio-creds \
    --cacert /root/rke/s3.cert \
    --use-volume-snapshots=false \
    --use-restic \
    --wait \
    --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=https://${MINIO_HOST}
```

That fails:
` kubectl logs deploy/velero -n velero`
```
time="2020-05-21T14:56:03Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:437"
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = config has invalid keys [caCert]; valid keys are [region s3Url publicUrl kmsKeyId s3ForcePathStyle signatureVersion profile serverSideEncryption insecureSkipTLSVerify bucket prefix]
```

**What did you expect to happen:**
--cacert to work. 

**Anything else you would like to add:**
If I remove --cacert  and add `,insecureSkipTLSVerify="true"` the install succeeds. The problem with that is restic now will not work because it does not trust my https server.

**Environment:**

- Velero version (use `velero version`): 
```
Client:
        Version: v1.4.0-beta.1
        Git commit: 8bf75bd4f28b27483ba2d7954ab61f406d8a7db5
<error getting server version: timed out waiting for server status request to be processed>
```
- Kubernetes version (use `kubectl version`): 1.16.8
- Kubernetes installer & version: rke latest
- Cloud provider or hardware configuration: openstack
- OS (e.g. from `/etc/os-release`): ubuntu xenial

**Comment by skriss** [comment]
@jcwimer this feature has not been released yet, it will be part of next week's v1.4.0 release. If you want to try it out for now, you can use `v1.4.0-beta.1` (https://github.com/vmware-tanzu/velero/releases/tag/v1.4.0-beta.1)

**Comment by jcwimer** [comment]
I'm using `v1.1.0-beta.1` release. I must be missing the `v1.1.0-beta.1` tag of the AWS plugin. How do I define that?

**Comment by skriss** [comment]
In your `velero install` command, you have `    --plugins velero/velero-plugin-for-aws:v1.0.0 \`, you'd need to change that to `--plugins velero/velero-plugin-for-aws:v1.1.0-beta.1`.

But, if you already have velero installed, you can simply swap out the plugin version with:

```
velero plugin remove velero/velero-plugin-for-aws:v1.0.0
velero plugin add velero/velero-plugin-for-aws:v1.1.0-beta.1
```

**Comment by jcwimer** [comment]
Nevermind I see. I'll try and report back.

**Comment by jcwimer** [comment]
@skriss thanks so much for responding. The ca is working and so is restic 👍

**Comment by skriss** [comment]
awesome, thanks for testing it out!
