### ISSUE TITLE
velero get backups --selector not working

### ISSUE THREAD

**Issue by momon** [vmware-tanzu/velero#2558]
I will probably come out looking real stupid after this but for the love of my life I seem unable to figure out why this isn't working:

```
usr@cc:~$ velero get backups
NAME                        STATUS      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
dpl-name1          Completed   2020-05-21 16:16:53 +0000 UTC   29d       default            a-label-selector=a-label-selector-value
dpl-name2   Completed   2020-05-21 17:34:55 +0000 UTC   29d       default            a-label-selector=a-label-selector-value
usr@cc:~$ velero get backups --selector a-label-selector=a-label-selector-value
usr@cc:~$ 
```
The last command above returns empty: ??????????????

Shouldn't velero get backups --selector a-label-selector=a-label-selector-value show me the two backups that have the same label selector?

```
Client:
        Version: v1.3.2
        Git commit: 55a9914a3e4719fb1578529c45430a8c11c28145
Server:
        Version: v1.3.2
```

**Comment by skriss** [comment]
hey @momon, the `--selector` flag on `velero get backups` will filter to Backups that have that set of **labels** applied (i.e. `.metadata.labels`). This is **different** than the Backup's label selector (i.e. `.spec.labelSelector`), which tells Velero what objects from the cluster the backup should capture.

You can use `velero get backups --show-labels` to see an additional column with the labels that each backup has applied to it. That would be what `--selector` filters on.

There is no way through the CLI to filter to backups that all share a common label selector; you'd have to `grep` or `jq` to do that.

I'm going to close this out, but feel free to reach out again if that's not clear or you need more info.
