### ISSUE TITLE
Setup with Azure Storage Account Access Key not working

### ISSUE THREAD

**Issue by dannyyy** [vmware-tanzu/velero#2563]
**What steps did you take and what happened:**
1. Configured the Helm Chart `values.yaml` according to the documentation for azure.
2. Create the file `credentials-velero` with the following content  
```
AZURE_STORAGE_ACCOUNT_ACCESS_KEY=<KEY>
AZURE_CLOUD_NAME=AzurePublicCloud
```
3. Run `helm install velero vmware-tanzu/velero -f values.yaml -n velero --set-file credentials.secretContents.cloud=./credentials-velero`

**What did you expect to happen:**
Pods were able to startup without error. What I get is:
`time="2020-05-23T10:31:52Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:413"
An error occurred: some backup storage locations are invalid: error getting backup store for location "azure": rpc error: code = Unknown desc = unable to get all required environment variables: the following keys do not have values: AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_SUBSCRIPTION_ID`

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`  
see above

**Anything else you would like to add:**
I also tried to add the required variables to the `credentials-velero` file with porper values, despite `AZURE_CLINET_ID` and `AZURE_CLIENT_SECRET`. Those I had left blank (empty value). Then I got:
```
time="2020-05-23T10:13:36Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:413"
An error occurred: some backup storage locations are invalid: error getting backup store for location "azure": rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/****/resourceGroups/****/providers/Microsoft.Storage/storageAccounts/****/listKeys?api-version=2018-02-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier 'EMPTY' was not found in the directory '****'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: ad8a2292-0910-4f37-9135-42f4a809e000\r\nCorrelation ID: d585fe5f-7ecd-4c6d-91b7-ab0eba61a5aa\r\nTimestamp: 2020-05-23 10:13:37Z","error_codes":[700016],"timestamp":"2020-05-23 10:13:37Z","trace_id":"ad8a2292-0910-4f37-9135-42f4a809e000","correlation_id":"d585fe5f-7ecd-4c6d-91b7-ab0eba61a5aa","error_uri":"https://login.microsoftonline.com/error?code=700016"}
```

**Environment:**

- Velero version (use `velero version`):  
`Client:
	Version: v1.3.2
	Git commit: -
<error getting server version: timed out waiting for server status request to be processed>`
- Kubernetes version (use `kubectl version`):  
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0+k3s.1", GitCommit:"0f644650f5d8e9f091629f860b342f221c46f6d7", GitTreeState:"clean", BuildDate:"2020-01-06T23:22:38Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}`
- Kubernetes installer & version:  
`k3s`
- Cloud provider or hardware configuration:  
`On-Prem`
- OS (e.g. from `/etc/os-release`):  
`Ubuntu 18.04`

**Comment by skriss** [comment]
@dannyyy this feature has not officially been released yet. If you want to use it, you can try using Velero v1.4.0-beta.1, and the Azure plugin v1.1.0-beta.1. We'll be shipping GA versions of each of these this week.

[This similar issue](https://github.com/vmware-tanzu/velero/issues/2272) has some additional info that may be helpful if you run into any problems while using those versions.

I'm going to close this out, but feel free to reach out again as needed.
