### ISSUE TITLE
Update Velero Uninstall doc for Helm

### ISSUE THREAD

**Issue by ezYakaEagle442** [vmware-tanzu/velero#2567]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

At [https://velero.io/docs/v1.3.2/uninstalling/](https://velero.io/docs/v1.3.2/uninstalling/) it is mentionned :

kubectl delete namespace/velero clusterrolebinding/velero
kubectl delete crds -l component=velero

**What did you expect to happen:**

I would have expect 2 uninstall ways as there are 2 install modes , also the component=velero selector does not look correct, check with :

kubectl  get crds -l app.kubernetes.io/name=velero -o wide

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The complete uninstall could look lie this :
```sh

helm uninstall velero -n $velero_ns
helm ls -n $velero_ns -o yaml

kubectl delete namespace $velero_ns clusterrolebinding/velero
kubectl delete crds -l component=velero

az storage container delete -n $BLOB_CONTAINER --account-name $AZURE_STORAGE_ACCOUNT_ID
az storage account delete --name $AZURE_STORAGE_ACCOUNT_ID -g $rg_name -y
az ad app delete --id velero-$appName
```

**Environment:**

- Velero version (use `velero version`): v1.3.2
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.16.7
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Azure / AKS 1.16.7
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
I think we should update the core Velero uninstall docs to include a link to the [Helm chart uninstall section](https://github.com/vmware-tanzu/helm-charts/tree/master/charts/velero#uninstall-velero), and then ensure that those instructions are correct.

@ezYakaEagle442 are you interested in working on the PRs for this?

**Comment by Lirt** [comment]
I would also like to ask for concise way to remove velero without removing backups physically.

If I delete `velero` namespace in which are all Velero-CRD resources (also backups), they will got deleted and this will most likely remove all physical backups in backupstoragelocation as well.

Is there an option to remove velero without removing the backups? If yes, it would help to know the proper way to do this.

**Comment by carlisia** [comment]
@Lirt deleting backup storage locations or uninstalling Velero will not delete the physical backups. 

For reference: https://velero.io/docs/v1.4/how-velero-works/#object-storage-sync.

**Comment by Lirt** [comment]
I tried to delete backup using `velero backup delete velero-full-backup-<timestamp>` and it got deleted also from storage. I am using Minio backend. I don't know what will be the order of deletion when I delete whole namespace as suggested in uninstall guide, but for me it looks very non-deterministic and I think real backups could be easily removed this way.

**Comment by carlisia** [comment]
Correct, `velero backup delete` is a command meant to delete backups from storage. Uninstalling Velero or the `velero` namespace` is not. For reference: https://velero.io/docs/v1.4/how-velero-works/#object-storage-sync:

> If there is a properly formatted backup file in the storage bucket, but no corresponding backup resource in the Kubernetes API, Velero synchronizes the information from object storage to Kubernetes.

**Comment by Lirt** [comment]
Sorry, for that @carlisia , thank you for help :-).

**Comment by jenting** [comment]
Currently, the [Velero doc](https://velero.io/docs) links the helm-based installation/uninstallation to helm chart GitHub repo, please refer to https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/README.md, both helm2 and helm3 covered.
