### ISSUE TITLE
velero schedule --help command modification

### ISSUE THREAD

**Issue by prasenforu** [vmware-tanzu/velero#2568]
Not an bug but looks like typo for ```velero schedule``` command

```
$velero create schedule --help
The --schedule flag is required, in cron notation, using UTC time:

| Character Position | Character Period | Acceptable Values |
| -------------------|:----------------:| -----------------:|
| 1                  | Minute           | 0-59,*            |
| 2                  | Hour             | 0-23,*            |
| 3                  | Day of Month     | 1-31,*            |
| 4                  | Month            | 1-12,*            |
| 5                  | Day of Week      | 0-7,*             |
```

Look at row ```5```, it says ``` 0-7,*```. I think it should be  ```0-6```

**Comment by sophalHong** [comment]
I think it should be 1-7.

**Comment by prasenforu** [comment]
In general cron practice it should be 0-6

**Comment by prasenforu** [comment]
(0 =sunday to 6 =saturday)

**Comment by kobayashi** [comment]
Hello, 
Do I have chance to take this issue?

**Comment by danielthrasher** [comment]
Is this still available?  Mind if I get assigned this one and complete it?

**Comment by danielthrasher** [comment]
If this is still available,  I have created a PR as well for it.

https://github.com/vmware-tanzu/velero/pull/2676

**Comment by ashish-amarnath** [comment]
@kobayashi apologies for not seeing your comment earlier. Thank you for offering to help on this issue. For future reference, any issue without an active PR for it is available to work on.
