### ISSUE TITLE
Clarify the distinction of cloud vs. on-premises in README overview

### ISSUE THREAD

**Issue by akutz** [vmware-tanzu/velero#2575]
**Describe the problem/challenge you have**
Currently the Velero README has an overview section that begins with the following:

> Velero (formerly Heptio Ark) gives you tools to back up and restore your Kubernetes cluster resources and persistent volumes. You can run Velero with a cloud provider or on-premises

The distinction between "cloud provider" and "on-premises" is unclear. Traditionally EKS or GCE are "cloud providers" and solutions like vSphere or OpenStack would be considered "on-prem." However, vSphere *does* have a [Kubernetes cloud provider](https://github.com/kubernetes/cloud-provider-vsphere), as does [OpenStack](https://github.com/kubernetes/cloud-provider-openstack).

**Describe the solution you'd like**
It would be nice if some examples were given that explain the distinction between "cloud-provider" and "on-premises."

**Anything else you would like to add:**
NA

**Environment:**
NA

**Comment by nrb** [comment]
Thanks for the report @akutz! I think the intention was _public_ cloud providers vs an on-premises installation.

Would adding the word "public" help provide that clarity for you?

**Comment by akutz** [comment]
Hi @nrb,

> I think the intention was public cloud providers vs an on-premises installation.

Makes sense.

> Would adding the word "public" help provide that clarity for you?

I think so. I'd love to know what others think. I also think "others", in this context, should be people not immediately steeped in Kubernetes. Regardless, I think adding "public" does move the messaging in the right direction.

**Comment by akutz** [comment]
Hi @nrb,

How about "public, cloud platform" instead of "provider"?

**Comment by nrb** [comment]
I'm fine with that wording! I know "provider" has been contentious, and we've been working to slowly remove it from our documentation and code. So I'm in favor of making this change to the README and the https://velero.io/docs/v1.3.2/on-premises/ page, if necessary.

**Comment by akutz** [comment]
FWIW, I think it would also need to be updated at https://velero.io/docs/v1.3.2/index.html as well.

**Comment by nrb** [comment]
Yeah, the index page is generated from the README, so that should be taken care of.

**Comment by skriss** [comment]
So replace "You can run Velero with a cloud provider or on-premises" with "You can run Velero with a public cloud platform or on-premises"? WFM.

**Comment by nrb** [comment]
Added change to README in #2579 and [the v1.4.0 index](https://github.com/vmware-tanzu/velero/pull/2577/files#diff-1199f51c0dac8b8e08853149473e5a20R7)
