### ISSUE TITLE
Run multiple backup and restores concurrently

### ISSUE THREAD

**Issue by VolkerKozlowski** [vmware-tanzu/velero#2582]
**Describe the problem/challenge you have**
Run multiple backups and restores concurrently. Currently a long running backup or restore blocks others from being executed.

**Describe the solution you'd like**
It would be good to have a parallel processing of different backups and restores to achieve more scaleability.

**Environment:**

- Kubernetes
- Openshift

**Comment by skriss** [comment]
@VolkerKozlowski thanks for filing the issue! We already have #487, so I'm going to close this issue out in favor of that. If you have any additional input for #487 or #1653 (our current view of what the implementation of this should look like), please comment on those!
