### ISSUE TITLE
velero and restic pods are not resolving DNS names

### ISSUE THREAD

**Issue by Seb0042** [vmware-tanzu/velero#2590]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
I configured the backup-location with a name like this: minio.mydomain:9000

I have the following error message when velero starts:
An error occurred: some backup storage locations are invalid: backup store for location "minio" is invalid: rpc error: code = Unknown desc = RequestError: send request failed
caused by: Get https://minio.mydomain:9000/velero?delimiter=%2F&list-type=2&prefix=: dial tcp: lookup minio-agv.gfi.network on external_dns_ip:53: no such host

**What did you expect to happen:**
velero and restic pods resolving correctly the name

NOTE: this happens only with velero and restic. All the others pod in the cluster work.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Here is my DNS architecture if it can helps:

Pods are configured to send requests to nodelocaldns.
Nodelocaldns is configured to answer or to transfer to coredns.
Coredns is configured to answer, rewrite (minio.mydomain in minio.ns.svc.cluster) or to transfer to the /etc/resolv.conf of the master.

In this case the path would be 'velero container' -> nodelocaldns -> coredns (rewrite then answer) -> nodelocaldns -> 'velero container'.
But it seems to be 'velero container' -> nodelocaldns -> coredns (not found?) -> resolv.conf (not found).

I have Gitlab using the same Minio on this cluster and it works (and other applications).

**Environment:**

- Velero version (use `velero version`):  v1.4.0
- Velero features (use `velero client config get features`): N/A 
- Kubernetes version (use `kubectl version`): v.1.18.2
- Kubernetes installer & version: kubedam, v1.18.2
- Cloud provider or hardware configuration: VMWare virtual machines
- OS (e.g. from `/etc/os-release`):  CentOS Linux release 7.8.2003 (Core)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Seb0042** [comment]
OK, found the issue, it's not velero related but may be to the version of Ubuntu used for the containers. The DNS client seems to be more strict so I had to add a configuration that rewrites the response also, like this in coredns:

rewrite stop {         
    name regex  minio\.mydomain\.$ minio.myns.svc.mycluster
    answer name minio-myns.svc.mycluster minio.mydomain
 }

**Comment by Seb0042** [comment]
My bad, issue still here, even if the name is correctly resolved in the container

**Comment by Seb0042** [comment]
OK, sorry, good now,  just too impatient, dnscache wasn't cleared.

**Comment by rpstreef** [comment]
this issue still exists, on the `describe` GET action, it will erroneously use host system DNS. 

you should not have to edit coredns rewrite rules when internal DNS names are applied properly.

```bash
Backup Volumes:
  <error getting backup volume info: Get "http://minio.insight-prose:9000/insight-prose-postgres-backup/backups/test3/test3-volumeinfo.json.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240717%2Fminio%2Fs3%2Faws4_request&X-Amz-Date=20240717T015549Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=63ccf13e02b928cf98bddce0665756c5dcadea4947ba33afed23fff2387f71f4": dial tcp: lookup minio.insight-prose on 8.8.8.8:53: no such host>
```
