### ISSUE TITLE
Unable to debug hook

### ISSUE THREAD

**Issue by alexgeek** [vmware-tanzu/velero#2593]
**What steps did you take and what happened:**

I've added a hook to my plastic scm deployment to call "cm admin readonly enter" before and "cm admin readonly leave" after the backup.

I've tried a few ways of writing out the hooks:

```
pre.hook.backup.velero.io/command: '[ "/usr/bin/cm", "admin readonly enter" ]'
```

```
pre.hook.backup.velero.io/command: '[ "/usr/bin/cm", "admin", "readonly", "enter" ]'
```

```
pre.hook.backup.velero.io/command: '[ "/bin/bash", "-c", "cm admin readonly enter" ]'
```

But I get errors like the following:

```
level=error msg="Error executing hook" backup=dev-ndw-002/test-backup error="command terminated with exit code 1" hookPhase=pre hookSource=annotation hookType=exec logSource="pkg/backup/item_hook_handler.go:100" name=plasticscm-deployment-658559d5bf-s88m2 namespace=dev-ndw-002 resource=pods
time="2020-06-01T14:26:59Z" level=error msg="Error backing up item" backup=dev-ndw-002/test-backup error="command terminated with exit code 1" logSource="pkg/backup/backup.go:454" name=plasticscm-deployment-658559d5bf-s88m2
```

```
time="2020-06-01T13:36:54Z" level=error msg="Error executing hook" backup=dev-ndw-002/test-backup error="command terminated with exit code 126" hookPhase=pre hookSource=annotation hookType=exec logSource="pkg/backup/item_hook_handler.go:100" name=plasticscm-deployment-5584c7c88f-tlq4z namespace=dev-ndw-002 resource=pods
time="2020-06-01T13:36:54Z" level=error msg="Error backing up item" backup=dev-ndw-002/test-backup error="command terminated with exit code 126" logSource="pkg/backup/backup.go:454" name=plasticscm-deployment-5584c7c88f-tlq4z
```

Is there a way to see the output of the commands? Also do the commands run with the same environment as the first container in the pod? 

**What did you expect to happen:**

The hook to succeed or at least see some logging output from the failed command.

**Environment:**

- Velero version (use `velero version`): 

```
Client:
        Version: v1.4.0
        Git commit: 5963650c9d64643daaf510ef93ac4a36b6483392
Server:
        Version: v1.4.0
```

- Velero features (use `velero client config get features`):  N/A
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.5-gke.6", GitCommit:"de3e4dcd39464bc1601edd66681e663bff1fe530", GitTreeState:"clean", BuildDate:"2020-05-12T16:10:21Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by TheKangaroo** [comment]
Hi @alexgeek, how did you fix you issue?
I got a similar issuer and I don't know how to debug the hook command.
I get `command terminated with exit code 126` and after some research I think this happens, when you unsuccessfully try to exec a command inside a container.

**Comment by alexgeek** [comment]
> Hi @alexgeek, how did you fix you issue?
> I got a similar issuer and I don't know how to debug the hook command.
> I get `command terminated with exit code 126` and after some research I think this happens, when you unsuccessfully try to exec a command inside a container.

I ended up using something like the following:

```
post.hook.backup.velero.io/command: '[ "/bin/bash", "-c", "cm admin readonly leave" ]'
```

**Comment by TheKangaroo** [comment]
I will try that, thank you @alexgeek  :)

**Comment by TheKangaroo** [comment]
Worked for me too, thanks @alexgeek
