### ISSUE TITLE
Enable PVC and PV with content restore using restic

### ISSUE THREAD

**Issue by dejwsz** [vmware-tanzu/velero#2598]
**Describe the problem/challenge you have**
If you use restic it is not possible to restore PVC with PV only with its content having the rest of objects and a project in place.

**Describe the solution you'd like**
Some restore subcommand to restore only a volume or volumes with content. So if you have some project where you can scale down deployments, statefulsets etc. and then you can remove PVC and bring back some old version of it with related PV and start everything up.

**Current solution does not work using restic**
So this does not work - it creates PVC and PV but without any content, PV is clean.
velero restore create --from-backup  BACKUP_NAME --include-namespaces SOURCE_PROJECT_NAME --restore-volumes=true --include-resources persistentvolumeclaims,persistentvolumes

**Environment:**
- Velero version - 1.3.2
- Openshift 3.11

**Comment by nrb** [comment]
Hi @dejwsz - this sounds like you might be looking for a "data-only" restore, where you leave all kubernetes objects/metadata alone except for the PV/PVC, and recreate the data on the volume.

Is that correct?

If it is, we have this documented as #504 and it's something we need to get designed. You can add a 👍 to the description to show your support for it ([as described in our recent update to the contributor documentation](https://velero.io/docs/v1.4/start-contributing/#start-contributing), and add a comment to give any more details you'd like for your use case. This will help us work on prioritizing it for our roadmap.

**Comment by dejwsz** [comment]
OK I did it, thanks!

**Comment by skriss** [comment]
:+1: thanks for commenting there. I'm going to close this issue out since it's a dupe, but we'll track it in #504.
