### ISSUE TITLE
timeout on pre hook error

### ISSUE THREAD

**Issue by Seb0042** [vmware-tanzu/velero#2599]
**What steps did you take and what happened:**
I added annotations on the pod to be saved. As it has a prehook command that can exceeds 30 seconds I add a number above 30 for timeout.
```
metadata:
  annotations:
    backup.velero.io/backup-volumes: backup-test
    pre.hook.backup.velero.io/command: '["/bin/bash","/extras/velero_backup.bash"]'
    pre.hook.backup.velero.io/container: test
    pre.hook.backup.velero.io/timeout: "300"
```

When I launch the velero backup create I have an error about timeout on the prehook command.
```
time="2020-06-02T16:47:41Z" level=error msg="Error executing hook" backup=production-system/test error="timed out after 30s" error.file="/github.com/vmware-tanzu/velero/pkg/pod
exec/pod_command_executor.go:168" error.function="github.com/vmware-tanzu/velero/pkg/podexec.(*defaultPodCommandExecutor).ExecutePodCommand" hookPhase=pre hookSource=annotation
 hookType=exec logSource="pkg/backup/item_hook_handler.go:100" name=mypod namespace=myns resource=pods
time="2020-06-02T16:47:41Z" level=error msg="Error backing up item" backup=production-system/test error="timed out after 30s" error.file="/github.com/vmware-tanzu/velero/pkg/po
dexec/pod_command_executor.go:168" error.function="github.com/vmware-tanzu/velero/pkg/podexec.(*defaultPodCommandExecutor).ExecutePodCommand" logSource="pkg/backup/backup.go:45
4" name=mypod

```

**What did you expect to happen:**
I expect that timeout of 300 seconds would be applied.
NOTE: when I change the timeout, I have to put "" around the number. I if don't do that I have an error because (int64 instead of a string).

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `velero backup describe <backupname>` :
```
Name:         test
Namespace:    velero
Labels:       velero.io/storage-location=minio
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.18.2
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18

Phase:  PartiallyFailed (run `velero backup logs test` for more information)

Errors:    2
Warnings:  0

Namespaces:
  Included:  production-app
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  minio

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-06-02 16:47:10 +0000 UTC
Completed:  2020-06-02 16:47:42 +0000 UTC

Expiration:  2020-07-02 16:47:10 +0000 UTC

Total items to be backed up:  271
Items backed up:              271

Velero-Native Snapshots: <none included>
```
- `velero backup logs <backupname>`: can't give you all the logs, too much to anonymize. I gave the two lines with error above.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
Client:
        Version: v1.4.0
        Git commit: 5963650c9d64643daaf510ef93ac4a36b6483392
Server:
        Version: v1.4.0

- Velero features (use `velero client config get features`): N/A 
- Kubernetes version (use `kubectl version`): v1.18.2
- Kubernetes installer & version: kubeadm v1.18.2
- Cloud provider or hardware configuration: Vmware virtual machines
- OS (e.g. from `/etc/os-release`): CentOS 7

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by nrb** [comment]
Hi @Seb0042.

`    pre.hook.backup.velero.io/timeout: "300"` requires a unit at the end; it doesn't automatically apply one. So the appropriate value would be `"300s"`.

I looked at the code really quickly, and it appears there's a [TODO for us to explicitly log this](https://github.com/vmware-tanzu/velero/blob/master/pkg/backup/item_hook_handler.go#L195). I'll open a PR to do that.

**Comment by Seb0042** [comment]
Thank you.
