### ISSUE TITLE
Investigate ytt + kapp

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#2606]
Investigate these tools to understand how to make the new CLI changes compatible with them.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
I think we can close this out. While ytt would be nice, it's pretty niche. kapp can apply most any YAML, so if we can plan nicely with standard YAML and Helm, we're covered there.
