### ISSUE TITLE
Don't create a backup immediately after creating a schedule

### ISSUE THREAD

**Issue by aakhundov** [vmware-tanzu/velero#2612]
**Describe the problem/challenge you have**

As a part of setting up a clean kubernetes cluster with the intention of restoring an existing velero backup onto it, I create a velero `Schedule` for further backups (to the same destination, where my existing backup resides). Schedule creation triggers an immediate backup of the clean cluster, which is not required and, to some extent, interferes with the existing backup assets (e.g., creates a superfluous backup record and alters restic repos). Also the time a new `Schedule` is created is not necessarily a good time for taking a backup.

**Describe the solution you'd like**

I've failed to find a flag for skipping the immediate backup: both within `Schedule` [definition](https://velero.io/docs/v1.4/api-types/schedule/) and among other configuration options. Maybe it would make sense to add such a flag (e.g., `immediateBackup: true`) to the `Schedule` definition. The default behaviour would stay like it is now, but those who don't want an immediate backup on schedule creation could configure it to be skipped.

**Environment:**

- Velero version (use `velero version`): 1.4.0
- Kubernetes version (use `kubectl version`): 1.17.4
- Kubernetes installer & version: kubeadm 1.17.4
- Cloud provider or hardware configuration: currently, VMs
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by skriss** [comment]
xref #1980

**Comment by dsu-igeek** [comment]
Duplicate of #1980, fixed by https://github.com/vmware-tanzu/velero/pull/4281
