### ISSUE TITLE
Unable to take backup of specific pod 

### ISSUE THREAD

**Issue by DebashisMondal** [vmware-tanzu/velero#2616]
In my namespace "test-namespace" there are multiple pods are running. But I want to take backup of only one pod named "test-pod".

How can we take the backup of specific resource of specific resource type. In my environment the pod has no level.

**Comment by skriss** [comment]
Response from google group message:

Velero doesn't support backing up resources by name. However, you can use a label selector that only matches the pod you're interested in:

```
velero backup create my-backup --include-namespaces test-namespace --include-resources pods --selector mykey=myval
```

In this example, your pod would need to be labeled with `mykey=myval`.

We do have a related unprioritized enhancement request around restoring items by name - see https://github.com/vmware-tanzu/velero/issues/904 and please add any comments/upvotes there.
