### ISSUE TITLE
The restic Pods are unable to start in kubernetes cluster.

### ISSUE THREAD

**Issue by FaridHub** [vmware-tanzu/velero#2623]
**Steps taken**
I have downloaded Velero, started as it is given in the examples folder, I was trying to back up elastic search pod running. Is behind a proxy and it's a corporate server, SO, I need to install velero along with corporate proxy. 

1. I am unable to see any option on how to add proxy to velero while "velero install ....." 
2. I have mentioned restic and with minio support at the time of installing it. 
However, the restic pods are failing, unable to see the logs as they are unable to start. 
I am getting below events in K8

[root@vr02s0002 ~]# **kc get events -n velero**
LAST SEEN   TYPE      REASON              OBJECT                         MESSAGE
3m17s       Warning   DNSConfigForming    pod/minio-7b4ff54f67-l2hng     Search Line limits were exceeded, some search paths have been omitted, the applied search line is:
velero.svc.cluster.local svc.cluster.local cluster.local <server details>
<unknown>   Normal    Scheduled           pod/restic-748hr               Successfully assigned velero/restic-748hr to <corporate node>
5m          Warning   DNSConfigForming    pod/restic-748hr               Search Line limits were exceeded, some search paths have been omitted, the applied search line is:
velero.svc.cluster.local svc.cluster.local cluster.local  <node>

38m         Normal    Pulling             pod/restic-748hr               Pulling image "velero/velero:v1.4.0"
38m         Warning   Failed              pod/restic-748hr               Failed to pull image "velero/velero:v1.4.0": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
38m         Warning   Failed              pod/restic-748hr               Error: ErrImagePull
38m         Normal    BackOff             pod/restic-748hr               Back-off pulling image "velero/velero:v1.4.0"
38m         Warning   Failed              pod/restic-748hr               Error: ImagePullBackOff
<unknown>   Normal    Scheduled           pod/restic-c92f5               Successfully assigned velero/restic-c92f5 to <corporate nOde>
4m35s       Warning   DNSConfigForming    pod/restic-c92f5               Search Line limits were exceeded, some search paths have been omitted, the applied search line is:
velero.svc.cluster.local svc.cluster.local cluster.local <node>
40m         Normal    Pulled              pod/restic-c92f5               Container image "velero/velero:v1.4.0" already present on machine
40m         Normal    Created             pod/restic-c92f5               Created container restic
40m         Normal    Started             pod/restic-c92f5               Started container restic
<unknown>   Normal    Scheduled           pod/restic-hshxt               Successfully assigned velero/restic-hshxt to <node>
4m51s       Warning   DNSConfigForming    pod/restic-hshxt               Search Line limits were exceeded, some search paths have been omitted, the applied search line is:
velero.svc.cluster.local svc.cluster.local cluster.local <node>
38m         Normal    Pulling             pod/restic-hshxt               Pulling image "velero/velero:v1.4.0"
38m         Warning   Failed              pod/restic-hshxt               Failed to pull image "velero/velero:v1.4.0": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
38m         Warning   Failed              pod/restic-hshxt               Error: ErrImagePull
38m         Normal    BackOff             pod/restic-hshxt               Back-off pulling image "velero/velero:v1.4.0"
38m         Warning   Failed              pod/restic-hshxt               Error: ImagePullBackOff
<unknown>   Normal    Scheduled           pod/restic-mzdwg               Successfully assigned velero/restic-mzdwg to <node>
5m1s        Warning   DNSConfigForming    pod/restic-mzdwg               Search Line limits were exceeded, some search paths have been omitted, the applied search line is:
velero.svc.cluster.local svc.cluster.local cluster.local <node>
38m         Normal    Pulling             pod/restic-mzdwg               Pulling image "velero/velero:v1.4.0"
38m         Warning   Failed              pod/restic-mzdwg               Failed to pull image "velero/velero:v1.4.0": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
38m         Warning   Failed              pod/restic-mzdwg               Error: ErrImagePull
38m         Normal    BackOff             pod/restic-mzdwg               Back-off pulling image "velero/velero:v1.4.0"
38m         Warning   Failed              pod/restic-mzdwg               Error: ImagePullBackOff
40m         Normal    SuccessfulCreate    daemonset/restic               Created pod: restic-c92f5
40m         Normal    SuccessfulCreate    daemonset/restic               Created pod: restic-hshxt
40m         Normal    SuccessfulCreate    daemonset/restic               Created pod: restic-mzdwg
40m         Normal    SuccessfulCreate    daemonset/restic               Created pod: restic-748hr
<unknown>   Normal    Scheduled           pod/velero-7c6db486cf-w49rl    Successfully assigned velero/velero-7c6db486cf-w49rl to <node>

**I am expecting it to take backup**
> **velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.0.0 --bucket velero --secret-file ~/.credential-velero --use-restic --use-volume-snapshots=false --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://minio.velero.svc:9000**

> **velero backup create esback --include-namespaces default --wait**
The process goes on forever and doesn't end.

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version: 1.18
- Cloud provider or hardware configuration:
- OS (Centos 8:

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by skriss** [comment]
I see multiple lines like:

> 38m Warning Failed pod/restic-748hr Failed to pull image "velero/velero:v1.4.0": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Which indicates that there's a problem pulling the velero Docker image. Are you normally able to connect to Docker Hub from your cluster? Or do you need to use an internal registry?

**Comment by FaridHub** [comment]
I am unable to reach the registry of docker due to proxy blockage. Is there any way of configuring proxy in the command line along with **velero install**.
I have tried with set environment variables in local but no luck. Also tried with editing velero pod yaml and added http_proxy and https_proxy, even this didnt work. 
Kindly advise how to operate velero behind a corporate proxy...

**Comment by ashish-amarnath** [comment]
@FaridHub I would suggest working with your IT team to allow traffic to docker hub.
Alternatively, you can also setup an internal container image registry. Refer [Air-gapped deployments
section of this doc](https://velero.io/docs/v1.4/on-premises/#on-premises-environments)

You could also build your own velero images and load them into your image registry.

Unfortunately, we are unable to assist you further with this issue to connect to docker.

I am closing this issue, please feel free to reopen or reach out to us on slack if you have more questions.
