### ISSUE TITLE
backups.velero.io already exists

### ISSUE THREAD

**Issue by balajir24** [vmware-tanzu/velero#2626]
Hi,

We are using azure provider. While installing Velero through helm, we are getting below error.

We cloned the repo and executing below command. added the secret as well. 

helm upgrade --namespace velero --install velero . -f values.yaml
Release "velero" does not exist. Installing it now.
Error: release velero failed: customresourcedefinitions.apiextensions.k8s.io "backups.velero.io" already exists

**Comment by ashish-amarnath** [comment]
@balajir24 Looks like you have a stale CRDs left over from a prior installation of velero, that may not be managed by helm.
Please remove the CRD using `kubectl delete crd backups.velero.io` and retry.

**Comment by ashish-amarnath** [comment]
@balajir24 I am going to close this issue for inactivity. Please feel free to reach out or re-open if further assistance is needed.
