### ISSUE TITLE
Backing up local K8S cluster on local server disk/NFS

### ISSUE THREAD

**Issue by shubhammicrosoft1** [vmware-tanzu/velero#2630]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
Can we backup Local K8S cluster on a mounted server disk or NFS servers local in the environment

**Describe the solution you'd like**
- Velero version (use `velero version`): Client: Version: v1.4.0
- Kubernetes version (use `kubectl version`): 1.18
- Kubernetes installer & version: K8S installation & version v1.18.3
- Cloud provider or hardware configuration: Local K8S installation on Linux server , Ubuntu 16.04
- OS (e.g. from `/etc/os-release`): 
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by shubhammicrosoft1** [comment]
Is there a documentation already available

**Comment by ashish-amarnath** [comment]
@shubhammicrosoft1 We don't have an object store plugin that can persist backups onto local filesystem. However, you might be able to use our [example object sore plugin](https://github.com/vmware-tanzu/velero-plugin-example/blob/master/internal/plugin/objectstoreplugin.go) that persists backups on the pod's local filesystem or you might want to look at running an instance of minio running with persistent volume backed by NFS for storage. Details on setting up velero with minio is available on our [docs website](https://velero.io/docs/v1.4/contributions/minio/).

**Comment by shubhammicrosoft1** [comment]
Thanks @ashish-amarnath . I was thinking to use velero install command & wanted to specify backup-storage location . How can we use azure storage blob location when we need to backup this local server kubernetes cluster

**Comment by ashish-amarnath** [comment]
@shubhammicrosoft1 To use an azure blog store as your object store you can use our [velero-plugin-for-microsoft-azure](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#install-and-start-velero)

**Comment by shubhammicrosoft1** [comment]
Thanks @ashish-amarnath : It worked like a charm 👍 
Can we also change the backup locations to migrate our EKS & GKE Kubernetes clusters to AKS or do we also need to do some changes ?
If there is a documentation around it ?

**Comment by ashish-amarnath** [comment]
We have this document that scratches the surface of cross cluster migration https://velero.io/docs/v1.4/migration-case/.
For migration across providers is a little more trickier wrt mapping credentials and access to the object store. You will have to update the manifests of the deployment to setup credentials for different object stores. In your case, you will have to setup Velero running in your EKS/GKE cluster with Azure credentials to have backups persisted into azure blob store.

Also, to migrate persistent volumes across providers, you can use our [restic integration](https://velero.io/docs/v1.4/restic/)

**Comment by ashish-amarnath** [comment]
@shubhammicrosoft1 I am closing this issue. If you need further assistance please feel free to reach out.
