### ISSUE TITLE
Setting up Velero Server am unable to deploy successfully Job

### ISSUE THREAD

**Issue by MSidda** [vmware-tanzu/velero#2631]
While deploying minio Example Kubernetes job failing Crashloopback off error showing

please help me

**Comment by ashish-amarnath** [comment]
Hi @MSidda can you please provide more details:
1. What scenario are you trying to run?
2. Where are you seeing errors during installation or performing backup and restore operations?
3. What are the actual errors?

**Comment by ashish-amarnath** [comment]
@MSidda I am going to close this issue for inactivity. Please feel free to reach out and reopen if you need further assistance.
