### ISSUE TITLE
PVC backup doesn't happen when pod restarts and changes name

### ISSUE THREAD

**Issue by ac-hibbert** [vmware-tanzu/velero#2634]
**What steps did you take and what happened:**

This is when using the restic feature. When a backup runs the persistent volume backup is related to the pod name and if the pod restarts it will not backup this pods volume.

**What did you expect to happen:**

Some kind of retry or picking up the new pod name. The pod runs in a deployment so the start part is the same just the end part is different.

**Environment:**

- Velero version (use `velero version`): 
```
v1.3.1
```
- Velero features (use `velero client config get features`): 
```
$ velero client config get features
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
EKS
- Cloud provider or hardware configuration:
AWS EKS
- OS (e.g. from `/etc/os-release`):
Amazon Linux 2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ashish-amarnath** [comment]
@hibbert thank you for raising this issue.
To backup pod volumes using restic, the main Velero backup process inspects each pod it is backing up to discover volumes to backup using restic. On discovering a volume to be backed up using restic, a `podVolumeBackup` object is created that will cause the restic daemon set pod, that mounts /var/lib/kublet/pods` to run restic commands to backup the specific volume. 
So there is a very tight coupling between the pod, and the restic backup process. For that reason, I am not sure how feasible retry would be in this scenario, especially if the pod, on restart, relocates to another node in the cluster.

**Comment by hibbert** [comment]
Any updates on this?

**Comment by ashish-amarnath** [comment]
@hibbert Supporting this scenario will require implementing retries into the back up process. That is not currently on our roadmap.

**Comment by carlisia** [comment]
Hey @hibbert we will keep this issue open for future reference and analysis if it's something we should add to the roadmap. It is not something that we can decide at this moment if we will add or not.

I know it's far from ideal, but we do have a new feature that allows for backing up all volumes in a pod automatically (https://velero.io/docs/main/restic/#to-back-up). Between that + scheduling maybe it will make it easier with some scripting in the mix.

**Comment by hibbert** [comment]
Hi @carlisia thanks it would be really useful to us.

We'd be happy to change to automatically backup all volumes in a pod, all our PVCs need backing up. I'm not sure what you mean by "Between that + scheduling maybe it will make it easier with some scripting in the mix." though. Could you elaborate. For us our backup is rather long (see #2115) it's usually someone upgrading their app which causes the restart which causes this problem.

**Comment by eleanor-millman** [comment]
Closing because as Carlisia and Ashish said, this is not currently on our roadmap.
