### ISSUE TITLE
Restore empty namespace

### ISSUE THREAD

**Issue by priyansh08** [vmware-tanzu/velero#2643]
**Describe the problem/challenge you have**
A platform operator may have prepared a namespace in a cluster for future workloads. 
When they want to migrate the cluster, Velero does not restore an empty namespace, leading to incomplete restoration of the cluster

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ashish-amarnath** [comment]
There is an existing issue open for this https://github.com/vmware-tanzu/velero/issues/1970
Closing this one in favor of #1970
