### ISSUE TITLE
Custom plugin for a CRD that doesn't exist applies to all resources

### ISSUE THREAD

**Issue by dymurray** [vmware-tanzu/velero#2644]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
I wrote a restore plugin for `imagetags.image.openshift.io` resources. This plugin was skipping the restore of all `imagetags` resources. I tested this plugin on a cluster where the `imagetags.image.openshift.io` resource doesn't exist and this plugin was applied to *ALL* resources.

**What did you expect to happen:**
I expected the plugin to only run when restoring `imagetag` resources and to not run if there were no `imagetags`.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

Here'es the relevant error from the restore logs:
```
time="2020-06-17T17:37:09Z" level=info msg="Executing item action for pods" logSource="pkg/restore/restore.go:1030" restore=openshift-migration/fcff7170-b0c0-11ea-a85f-af1109c53a1d-gx27s
time="2020-06-17T17:37:09Z" level=info msg="[imagetag-restore] skipping restore of imagetag" cmd=/plugins/velero-plugins logSource="/go/src/github.com/konveyor/openshift-velero-plugin/velero-plugins/imagetag/restore.go:23" pluginName=velero-plugins restore=openshift-migration/fcff7170-b0c0-11ea-a85f-af1109c53a1d-gx27s
time="2020-06-17T17:37:09Z" level=info msg="Skipping restore of Pod: stage-mysql-1-zhnpf-sz2fm because a registered plugin discarded it" logSource="pkg/restore/restore.go:1043" restore=openshift-migration/fcff7170-b0c0-11ea-a85f-af1109c53a1d-gx27s
```
You can see the resource is a pod, and the imagetag plugin contains:
```
func (p *RestorePlugin) AppliesTo() (velero.ResourceSelector, error) {                                                                                       
        return velero.ResourceSelector{
                IncludedResources: []string{"imagetags"},
        }, nil                                                                                                                                               
}
```
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I confirmed this was an issue by substituting `imagetags` for `foobars`. It still happened so I believe this bug occurs with any CRD that doesn't exist in the cluster where the restore is occurring.

**Environment:**

- Velero version (use `velero version`): v1.3
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.16
- Kubernetes installer & version: OpenShift
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment]
I imagine what's going on is that the IncludedResources slice may be filtering out resources that don't exist and, if the resulting resource list is empty, velero is treating it as if the user had specified an empty list, which would mean "match everything". A list which, when filtered, results in an empty list should map to "match nothing", while "match everything" should only apply if the user supplied an empty list.

**Comment by nrb** [comment]
I _think_ this is the same as what https://github.com/vmware-tanzu/velero/pull/2462 fixed. We saw this when using the CSI plugin on a cluster without the CSI CRDs installed.

This fix was included in Velero v1.4.0; have you noticed the behavior there?

**Comment by sseago** [comment]
@nrb This looks like it's exactly what we're seeing. We're still on 1.3.2. Upgrading to 1.4 is on our to-do list, and I guess it's just been bumped up. Thanks. I think this issue can probably be closed.

**Comment by ashish-amarnath** [comment]
@sseago and @dymurray  1.4 definitely has the fix. Closing this issue.
