### ISSUE TITLE
Chart incompatible

### ISSUE THREAD

**Issue by Sam8301-arch** [vmware-tanzu/velero#2646]
Hello Guys!

Quick question, is chart incompatible with Tiller v2.9.1? Getting below error while installing chart?"Error: Chart incompatible with Tiller v2.9.1" Any idea how to move ahead on this?

**Comment by ashish-amarnath** [comment]
Can you please confirm you are using the helm chart at https://github.com/vmware-tanzu/helm-charts?

**Comment by Sam8301-arch** [comment]
Thanks for the feedback Ashish. I am getting this error
"manifest_sorter.go:192:
info: skipping unknown hook: "crd-install" with helm3. Is it fixed or any
idea how to move around on this?

**Comment by ashish-amarnath** [comment]
Based on https://github.com/datawire/ambassador/issues/2057#issuecomment-560007192. this log message can be safely ignored.

I was able install velero into my cluster using helm3 following instructions from https://github.com/vmware-tanzu/helm-charts/blob/master/charts/velero/README.md#using-helm-3

E.g.: 
```
$ kubectl get crds
No resources found in default namespace.

source <FILE_WITH_VALUES_FOR_VARS>
helm install --namespace velero \
--set configuration.provider=aws \
--set-file credentials.secretContents.cloud=<PATH_TO_CREDS_FILE> \
--set configuration.backupStorageLocation.name=aws \
--set configuration.backupStorageLocation.bucket=$BUCKET \
--set configuration.backupStorageLocation.config.region=$REGION \
--set image.repository=velero/velero \
--set image.pullPolicy=IfNotPresent \
--set initContainers[0].name=velero-plugin-for-aws \
--set initContainers[0].image=velero/velero-plugin-for-aws:v1.1.0 \
--set initContainers[0].volumeMounts[0].mountPath=/target \
--set initContainers[0].volumeMounts[0].name=plugins \
--generate-name \
vmware-tanzu/velero
```

**Comment by Sam8301-arch** [comment]
I am still getting warning/error after following the steps but the velero
server is still not up and running after following steps.
"kubectl get deployment/velero-1592774546 -n velero

NAME                READY   UP-TO-DATE   AVAILABLE   AGE
velero-1592774546   0/1     1            0           9m32s "

**Comment by ashish-amarnath** [comment]
Can you please share the output of kubectl-n velero get po deploy/velero and
Kubectl -n velero describe po deploy/velero?

**Comment by Sam8301-arch** [comment]
kubectl -n velero get pods velero-1592776490-f7654cbd8-245lr

NAME                                READY   STATUS             RESTARTS
AGE

velero-1592776490-f7654cbd8-245lr   0/1     CrashLoopBackOff   36
164m


kubectl -n velero describe pods/velero-1592776490-f7654cbd8-245lr

Name:           velero-1592776490-f7654cbd8-245lr

Namespace:      velero

Priority:       0

Node:           ip-10-0-x-xxx.ap-southeast-2.compute.internal/10.0.2.xx

Start Time:     Sun, 21 Jun 2020 21:54:53 +0000

Labels:         app.kubernetes.io/instance=velero-1592776490

                app.kubernetes.io/managed-by=Helm

                app.kubernetes.io/name=velero

                helm.sh/chart=velero-2.12.0

                name=velero

                pod-template-hash=f7654cbd8

Annotations:    cni.projectcalico.org/podIP: xxx.xxx.xxx.xx/xx

                prometheus.io/path: /metrics

                prometheus.io/port: 8085

                prometheus.io/scrape: true

Status:         Running

IP:             xxx.xxx.xxx.xx

Controlled By:  ReplicaSet/velero-1592776490-f7654cbd8

Init Containers:

  velero-plugin-for-aws:

    Container ID:
docker://32cc7f99cf67c933cd78bb42d5cd9eab9f517e98d41dba0eadfc652d1053a948

    Image:          velero/velero-plugin-for-aws:v1.0.0

    Image ID:       docker-pullable://velero/velero-plugin-for-aws@sha256
:12a0af53302006830616bf0f743d64a05cdfb0cf2c2a10980c06c4831a359f05

    Port:           <none>

    Host Port:      <none>

    State:          Terminated

      Reason:       Completed

      Exit Code:    0

      Started:      Sun, 21 Jun 2020 21:54:54 +0000

      Finished:     Sun, 21 Jun 2020 21:54:54 +0000

    Ready:          True

    Restart Count:  0

    Environment:    <none>

    Mounts:

      /target from plugins (rw)

      /var/run/secrets/kubernetes.io/serviceaccount from
velero-1592776490-server-token-kwbhs (ro)

Containers:

  velero:

    Container ID:
docker://1d844388f5a8da8b35d419854fce0b9a7172752b2520590668a4935f8bb61fdc

    Image:         velero/velero:v1.4.0

    Image ID:      docker-pullable://velero/velero@sha256
:6c85efba541fab1fe6aa7e6585bdbc898b990eb4e8de7b493e5fd7c6f1b676f0

    Port:          8085/TCP

    Host Port:     0/TCP

    Command:

      /velero

    Args:

      server

    State:          Waiting

      Reason:       CrashLoopBackOff

    Last State:     Terminated

      Reason:       Error

      Exit Code:    1

      Started:      Mon, 22 Jun 2020 00:36:42 +0000

      Finished:     Mon, 22 Jun 2020 00:36:45 +0000

    Ready:          False

    Restart Count:  36

    Environment:

      VELERO_SCRATCH_DIR:           /scratch

      VELERO_NAMESPACE:             velero (v1:metadata.namespace)

      LD_LIBRARY_PATH:              /plugins

      AWS_SHARED_CREDENTIALS_FILE:  /credentials/cloud

    Mounts:

      /credentials from cloud-credentials (rw)

      /plugins from plugins (rw)

      /scratch from scratch (rw)

      /var/run/secrets/kubernetes.io/serviceaccount from
velero-1592776490-server-token-kwbhs (ro)

Conditions:

  Type              Status

  Initialized       True

  Ready             False

  ContainersReady   False

  PodScheduled      True

Volumes:

  cloud-credentials:

    Type:        Secret (a volume populated by a Secret)

    SecretName:  velero-1592776490

    Optional:    false

  plugins:

    Type:       EmptyDir (a temporary directory that shares a pod's
lifetime)

    Medium:

    SizeLimit:  <unset>

  scratch:

    Type:       EmptyDir (a temporary directory that shares a pod's
lifetime)

    Medium:

    SizeLimit:  <unset>

  velero-1592776490-server-token-kwbhs:

    Type:        Secret (a volume populated by a Secret)

    SecretName:  velero-1592776490-server-token-kwbhs

    Optional:    false

QoS Class:       BestEffort

Node-Selectors:  <none>

Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s

                 node.kubernetes.io/unreachable:NoExecute for 300s

Events:

  Type     Reason   Age                     From
                        Message

  ----     ------   ----                    ----
                        -------

  Normal   Pulled   42m (x29 over 162m)     kubelet,
ip-xx-x-x-xxx.ap-southeast-2.compute.internal  Container image
"velero/velero:v1.4.0" already present on machine

  Warning  BackOff  2m42s (x728 over 162m)  kubelet,
ip-xx-x-x-xxx.ap-southeast-2.compute.internal  Back-off restarting failed
container

**Comment by ashish-amarnath** [comment]
@Sam8301-arch The pod is in a crashloop. Can you please inspect the logs to identify what is causing the pod to crash?
or share the logs from `kubectl -n velero logs deploy/velero`

**Comment by Sam8301-arch** [comment]
kubectl -n velero logs deploy/velero-xxx

time="2020-06-22T20:25:29Z" level=info msg="setting log-level to INFO"
logSource="pkg/cmd/server/server.go:177"

time="2020-06-22T20:25:29Z" level=info msg="Starting Velero server v1.4.0
(5963650c9d64643daaf510ef93ac4a36b6483392)"
logSource="pkg/cmd/server/server.go:179"

time="2020-06-22T20:25:29Z" level=info msg="No feature flags enabled"
logSource="pkg/cmd/server/server.go:183"

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=BackupItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/crd-remap-version

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=BackupItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=BackupItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=BackupItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/service-account

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/add-pv-from-pvc

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/add-pvc-from-pod

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/change-pvc-node-selector

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/change-storage-class

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/cluster-role-bindings

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/crd-preserve-fields

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/role-bindings

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/service-account

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/plugins/velero-plugin-for-aws kind=VolumeSnapshotter
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws

time="2020-06-22T20:25:29Z" level=info msg="registering plugin"
command=/plugins/velero-plugin-for-aws kind=ObjectStore
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws

time="2020-06-22T20:25:29Z" level=info msg="Checking existence of
namespace" logSource="pkg/cmd/server/server.go:361" namespace=velero

time="2020-06-22T20:25:29Z" level=info msg="Namespace exists"
logSource="pkg/cmd/server/server.go:367" namespace=velero

time="2020-06-22T20:25:32Z" level=info msg="Checking existence of Velero
custom resource definitions" logSource="pkg/cmd/server/server.go:396"

time="2020-06-22T20:25:32Z" level=info msg="All Velero custom resource
definitions exist" logSource="pkg/cmd/server/server.go:430"

time="2020-06-22T20:25:32Z" level=info msg="Checking that all backup
storage locations are valid" logSource="pkg/cmd/server/server.go:437"

An error occurred: some backup storage locations are invalid: backup store
for location "default" is invalid: rpc error: code = Unknown desc =
AccessDenied: Access Denied

status code: 403, request id: xxx, host id: xxx/xxx

**Comment by Sam8301-arch** [comment]
FYI, i have used "helm3 install vmware-tanzu/velero --namespace velero
--set configuration.provider=aws --set-file
credentials.secretContents.cloud=/xx/xxx/credentials-velero --set
configuration.backupStorageLocation.bucket=velero830 --set
configuration.backupStorageLocation.config.region=ap-southeast-2 --set
image.repository=velero/velero --set image.tag=v1.4.0 --set
image.pullPolicy=IfNotPresent --set
initContainers[0].name=velero-plugin-for-aws --set
initContainers[0].image=velero/velero-plugin-for-aws:v1.1.0 --set
initContainers[0].volumeMounts[0].mountPath=/target --set
initContainers[0].volumeMounts[0].name=plugins --generate-name"

And followed instruction to create S3 bucket and user creation mentioned in
URL "https://velero.io/docs/v1.0.0/aws-config/"

**Comment by ashish-amarnath** [comment]
@Sam8301-arch 
So the pod is crashing because the credentials provided to velero is either has insufficient  permissions or is not correct.

Can you please confirm that the IAM user has the correct privileges from the AWS console?

Also, please confirm that the `cloud-credentials` secret exists in the `velero` namespace and that its contents are accurate?
- `kubectl -n velero get secrets`
- `kubectl -n velero get secrets cloud-credentials -ojson | jq .data.cloud -r | base64 --decode`

**Comment by Sam8301-arch** [comment]
permissions are created as per AWS URL on velero site. i didn't put
credentials in the namespace as not mention in the steps. i have put it now
but still no luck. please see below

kubectl create secret generic credentials-velero --namespace velero
--from-file credentials-velero


kubectl -n velero get secrets

NAME                                      TYPE
    DATA   AGE

credentials-velero                        Opaque
    1      8m45s

default-token-t6q9n
kubernetes.io/service-account-token   3      43h

sh.helm.release.v1.velero-1592797000.v1   helm.sh/release.v1
    1      43h

velero-1592797000                         Opaque
    1      43h

velero-1592797000-server-token-xszf6
kubernetes.io/service-account-token   3      43h

**Comment by ashish-amarnath** [comment]
@Sam8301-arch Is the pod still in crashloop?
Can you please share the output of `kubectl -n velero logs  deploy/velero`

**Comment by Sam8301-arch** [comment]
yes still in the same loop

kubectl -n velero logs deploy/velero-1592956022

time="2020-06-23T23:49:18Z" level=info msg="setting log-level to INFO"
logSource="pkg/cmd/server/server.go:177"

time="2020-06-23T23:49:18Z" level=info msg="Starting Velero server v1.4.0
(5963650c9d64643daaf510ef93ac4a36b6483392)"
logSource="pkg/cmd/server/server.go:179"

time="2020-06-23T23:49:18Z" level=info msg="No feature flags enabled"
logSource="pkg/cmd/server/server.go:183"

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=BackupItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/crd-remap-version

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=BackupItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=BackupItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=BackupItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/service-account

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/add-pv-from-pvc

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/add-pvc-from-pod

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/change-pvc-node-selector

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/change-storage-class

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/cluster-role-bindings

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/crd-preserve-fields

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/role-bindings

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/velero kind=RestoreItemAction
logSource="pkg/plugin/clientmgmt/registry.go:100" name=
velero.io/service-account

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/plugins/velero-plugin-for-aws kind=VolumeSnapshotter
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws

time="2020-06-23T23:49:18Z" level=info msg="registering plugin"
command=/plugins/velero-plugin-for-aws kind=ObjectStore
logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws

time="2020-06-23T23:49:18Z" level=info msg="Checking existence of
namespace" logSource="pkg/cmd/server/server.go:361" namespace=velero

time="2020-06-23T23:49:18Z" level=info msg="Namespace exists"
logSource="pkg/cmd/server/server.go:367" namespace=velero

time="2020-06-23T23:49:21Z" level=info msg="Checking existence of Velero
custom resource definitions" logSource="pkg/cmd/server/server.go:396"

time="2020-06-23T23:49:25Z" level=info msg="All Velero custom resource
definitions exist" logSource="pkg/cmd/server/server.go:430"

time="2020-06-23T23:49:25Z" level=info msg="Checking that all backup
storage locations are valid" logSource="pkg/cmd/server/server.go:437"

An error occurred: some backup storage locations are invalid: backup store
for location "default" is invalid: rpc error: code = Unknown desc =
AccessDenied: Access Denied

status code: 403, request id: xxx, host id: xx

>

**Comment by ashish-amarnath** [comment]
Still indicating that there is a problem with the credentials.
Can you confirm that the contents are right? It should be of the following format
```
[default]
aws_access_key_id=<AWS_ACCESS_KEY_ID>
aws_secret_access_key=<AWS_SECRET_ACCESS_KEY>
```

**Comment by Sam8301-arch** [comment]
yes same format yesterday i have created another keys and even after that
it didn't work.

>

**Comment by ashish-amarnath** [comment]
I am not sure what is going on but the `403` definitely indicates a problem with your credentials.

**Comment by Sam8301-arch** [comment]
so put dummy values in the credentials file and then recreate the namespace
and then it gives me below message


"An error occurred: some backup storage locations are invalid: backup store
for location "default" is invalid: rpc error: code = Unknown desc =
InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in
our records.

status code: 403, request id: xxx, host id: xx"

**Comment by ashish-amarnath** [comment]
This to me, indicates that your credentials are correct, but the IAM user may not have access to the S3 bucket.
Can you try using the aws cli with these credentials to run `aws s3 ls`?

**Comment by Sam8301-arch** [comment]
So I created a user and assign a policy(on velero site) to that user and
group. Let me install aws-cli and check from there too.

**Comment by Sam8301-arch** [comment]
yes i can access it, with the same user

*razhar@dev-manager*:*~*$ /usr/local/bin/aws s3 ls

2020-04-14 03:08:09 xx

2020-06-16 19:13:42 xx

2020-04-09 22:49:07 xx

2020-06-16 19:53:06 xxx

2019-09-22 21:58:18 xxx

2019-08-19 21:39:53 xxx

2020-06-16 21:31:46 xx

2020-06-16 21:31:47 xx

2019-12-19 01:08:19 xx

2020-05-15 03:26:23 xx

2020-06-16 21:31:47 xx

2020-06-16 21:31:48 fx

2020-06-16 21:31:48 fxx

2019-09-05 02:56:14 xx

2019-12-03 20:27:41 xx

2020-06-16 23:56:56 xx

2020-06-16 23:56:56 xx

2019-05-28 03:43:25 xx

2019-05-28 03:43:44 xx

2019-11-13 19:22:34 xx

2020-06-17 00:32:01 xx

2019-09-24 04:42:26 xx

2020-01-07 02:51:10 xx

2020-06-17 01:52:42 xx

2020-06-22 03:16:16 xx

>

**Comment by ashish-amarnath** [comment]
What about the exact bucket?

**Comment by Sam8301-arch** [comment]
yes bucket as well at the end of the list.  i can see the entry from aws
console as well

**Comment by ashish-amarnath** [comment]
I know you checked this, but can you check the contents of the secret? Sometimes the character combinations in the access key and the secret contain special characters that can cause this. Also, `aws_access_key_id` and `aws_secret_access_key ` should both be lower case. Another thing you might want to try is have no whitespace on either side of the `=`.

Unfortunately I don't know exactly what might be wrong.

**Comment by Sam8301-arch** [comment]
Finally it's working now. I have make the bucket public and it worked after
that so i have checked policy.json file and got the issue from there.

>

**Comment by ashish-amarnath** [comment]
Glad to have this working for you! I am going to close this issue. Please feel free to reach out if you need more assistance.
