### ISSUE TITLE
Velero: How fsfreeze to configure in pre/post hook with the container image which doesn't have fsfreeze binary?

### ISSUE THREAD

**Issue by rahulgit1988** [vmware-tanzu/velero#2647]
**What steps did you take and what happened:**
We would like to know the behaviour of fsfreeze in pre/post hook. and what happen if the container is not having the fsfreeze binary.
In other words..
If user has to add fsfreeze to pre/post hook by their own, how can pre/post hook be configured with the container image which doesn't have fsfreeze binary?

**What did you expect to happen:**
In case fsfreeze binary is not present, then freeze command will not executed on target conatiner and hooks feature doesnt work at all, so is there any work arround?

**The output of the following commands will help us better understand what's going on**:
Additioanlly we have tried to setup pre/post hook with fsfreeze using the example mentioned in below URL, but hooks are not working.
https://velero.io/docs/master/hooks/ >> examples/nginx-app/with-pv.yaml

**Anything else you would like to add:**
1-What other ways to establish a rest point for filesystem(fsfreeze) in pre/post hook, if conatiner is having the fsfreeze binary.
2- The underline Host OS is RHEL Core OS, and fsfreeze conainer image is ubuntu:bionic, is it causing the failure of hook mentioned in >> examples/nginx-app/with-pv.yaml

**Environment:**

- Velero version (use `velero version`):  Latest
- Velero features (use `velero client config get features`): hook
- Kubernetes version (use `kubectl version`): latest
- OS (e.g. from `/etc/os-release`): RHEL core os

**Comment by l0wl3vel** [comment]
You have two options:

1. Build a container with the fsfreeze in it
2. Install the binary with the hook

**Comment by ashish-amarnath** [comment]
@rahulgit1988 backup pre and post hooks are configured to run commands from within the container during a backup. It is assumed that these commands, setup in the hooks, are valid executables from within the container.
There is no other workaround to remediate missing executables other than what @l0wl3vel has mentioned.

I am going to close this issue, please feel free to reach out/ re-open if further assistance is required.
