### ISSUE TITLE
Request for all prehooks to be executed before volume snapshot

### ISSUE THREAD

**Issue by laura-chen** [vmware-tanzu/velero#2652]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
We are using Velero for a disaster recovery solution and in order to do online backups, we specify a prehook on two pods to suspend writes on databases before a backup and a post hook to resume writes afterwards. 

Since the backups take place on a per-object basis, it is possible for there to be data inconsistency if, while writes are suspended for the DBs from one volume, writes are continuing for the DBs for another volume that has not yet been backed up. 

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
We would love the ability to execute prehooks before backups begin and post-hooks after all backups are complete so that all databases are suspended during backup and resume afterwards.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.4.0
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"a02f27a", GitTreeState:"clean", BuildDate:"2020-04-13T12:04:13Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
Red Hat Enterprise Linux 7.6

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ashish-amarnath** [comment]
@laura-chen Thanks for reporting this.
Currently, the main backup controller in Velero is a single worker controller, meaning things get backed up one at a time. 

Also, I am not fully aware of your app architecture. But it seems to me like, the database is resource shared by two pods. For that reason, you may want to consider backing up the database by itself and not as part of backing up the application pod writing to the database.

**Comment by carlisia** [comment]
@laura-chen as stated above, the unit of operation is one backup or restore at a time, we don't have an architecture that could easily accomodate having a sequence of pre-hooks, then backups, then restores, then post-hooks. I am going to close the issue, feel free to open issues if/when you need further help.
