### ISSUE TITLE
Convert BackupTracker controller to the kubebuilder framework

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#2657]
**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
@carlisia I can take this one if you'd like

**Comment by carlisia** [comment]
Yes sure. But... is this a controller? After I listed it I looked at the code and it looks like something that is not a controller. Doesn't (seem to) have a reconcile loop. If I'm wrong, yes please take this one.

**Comment by nrb** [comment]
It is not - it's a struct that's used to track things in the backup controller, not a controller by itself. Gonna close this issue out :)

**Comment by carlisia** [comment]
1 down!! :)
