### ISSUE TITLE
Add flag(like --dry-run -oyaml) to generate yaml for some commands

### ISSUE THREAD

**Issue by SomtochiAma** [vmware-tanzu/velero#2662]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
Currently, if I want to schedule or restore a backup, I have to write the CRD from scratch, which isn't too bad but more error-prone

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
A flag(just like --dry-run -oyaml for the `install` command) which outputs the YAML file that the command would have created

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
Hi @SomtochiAma and @pietervincken

If you take a look at `velero schedule create --help`, there's a `-o/--output` argument for getting the JSON or YAML.

`  -o, --output string                                   Output display format. For create commands, display the object but do not send it to the server. Valid formats are 'table', 'json', and 'yaml'. 'table' is not valid for the install command.`

This argument is on any `create` sub-command.

Hopefully this is helpful!

**Comment by carlisia** [comment]
We will also be adding that for the new install related commands we are going to add: https://github.com/vmware-tanzu/velero/issues/2432

**Comment by SomtochiAma** [comment]
Oh, that's great! Thank you!
