### ISSUE TITLE
Velero restore is not working correctly with SAN backend

### ISSUE THREAD

**Issue by NiveditaKumari14** [vmware-tanzu/velero#2664]
**What steps did you take and what happened:**
I have created a backend using "san" and below is the details of other resources:
StorageClass: Retain
VolumeSnapshotClass: Retain
then created PVC and Pod inside namespace retain-retain-namespace.

[core@host-192-168-75-38 san-backend]$ oc get pods
NAME             READY   STATUS    RESTARTS   AGE
csi-new-pod-11   1/1     Running   0          3m51s

Velero Backup creation:
===============
 [core@host-192-168-75-38 san-backend]$ velero create backup policy-retain-retain-san --include-namespaces retain-retain-namespace --snapshot-volumes=true --wait
Backup request "policy-retain-retain-san" submitted successfully.
Waiting for backup to complete. You may safely press ctrl-c to stop waiting - your backup will continue in the background.
.....................................................
Backup completed with status: Completed. You may check for more information using the commands `velero backup describe policy-retain-retain-san` and `velero backup logs policy-retain-retain-san`.

**What did you expect to happen:**
I expect that all resources in namespace is restored successfully 

I am getting below error:
Pod stuck in ContainerCreating   state.
After describing pods detail getting below error:

[core@host-192-168-75-38 trident-installer]$ oc get pods
NAME             READY   STATUS              RESTARTS   AGE
csi-new-pod-11   0/1     ContainerCreating   0          65s
Events:
  Type     Reason                  Age                From                         Message
  ----     ------                  ----               ----                         -------
  Warning  FailedScheduling        64s (x5 over 81s)  default-scheduler            error while running "VolumeBinding" filter plugin for pod "csi-new-pod-11": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled               63s                default-scheduler            Successfully assigned retain-retain-namespace/csi-new-pod-11 to host-192-168-75-64
  Normal   SuccessfulAttachVolume  61s                attachdetach-controller      AttachVolume.Attach succeeded for volume "pvc-504fb641-088d-411d-a52a-e4fe6aaa3555"
  Warning  FailedMount             7s (x7 over 56s)   kubelet, host-192-168-75-64  MountVolume.MountDevice failed for volume "pvc-504fb641-088d-411d-a52a-e4fe6aaa3555" : rpc error: code = Internal desc = iSCSI session error: could not run iSCSI discovery: exit status 20

Environment:**

Velero version (use velero version): 1.1.0
Kubernetes version (use kubectl version): Server 1.13 Client 1.16
Kubernetes installer & version: Rancher
Cloud provider or hardware configuration: Trident as persistent storage class

**Comment by ashish-amarnath** [comment]
@NiveditaKumari14 The error you are seeing is from your storage driver and not Velero per-say. Here is an issue I found that might be related to what you are seeing https://github.com/NetApp/trident/issues/407.

I am going to close this issue as this is unrelated to Velero. Please feel free to reach out to us if you have more questions.
