### ISSUE TITLE
Document "in-place" migration use case

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2665]
**Describe the problem/challenge you have**
Velero can help users upgrade their Kubernetes cluster to a new version without making snapshots of volumes, but this case is not documented.

This is especially relevant in on-premises/air-gapped installations that have a capped amount of storage.

**Describe the solution you'd like**
Add a new use case that describes how to upgrade a Kubernetes cluster version without taking a snapshot of volumes, instead using the existing volumes "in-place."

This will work because in this case, Velero is using the PersistentVolume's `volumeID` as-is, without trying to make a snapshot or create a new volume on restore.

**Anything else you would like to add:**

* PVs should have their deletionPolicy set to `Retain` so that the volume is kept on the storage platform even after the PersistentVolume document is deleted.
* The backup should be made with `snapshot-volumes=false`, so that the PersistentVolume's `volumeID` is perserved and no snapshot/volumeID remapping is done on restore.
* Document should note that the current Kubernetes cluster should be stopped/deleted before starting the restore on the new cluster - otherwise, there will be contention on the volume since the two Kubernetes clusters are not aware of each other, and two PersistentVolumes will be pointing to the same volume on storage.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by eleanor-millman** [comment]
Closing this for now because 1) this would require a lot of testing and engineering time and 2) I haven't had anyone asking me for this. Will consider re-opening if I see lots of demand for this feature.
