### ISSUE TITLE
Restore only pod volume using Restic

### ISSUE THREAD

**Issue by avishaiNB** [vmware-tanzu/velero#2668]
Is it possible to backup only the PV that is annotated in the pod without actually backing up the pod (resource) or any other resource for that matter?

I created a backup of elastic pv.
Then i created a new k8s cluster with elastic install on it.
I tried to restore the backup of the volume from the other cluster.

i got this errors:
```
$ ./velero restore describe elasticsearch-devserver-restore
Name:         elasticsearch-devserver-restore
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:  Completed

Warnings:
  Velero:     <none>
  Cluster:    <none>
  Namespaces:
    default:  stat /tmp/183602585/resources/persistentvolumeclaims/namespaces/default/elasticsearch-master-elasticsearch-master-0.json: no such file or directory
              stat /tmp/183602585/resources/persistentvolumeclaims/namespaces/default/es-snap-repo-pvc.json: no such file or directory
              could not restore, pods "elasticsearch-master-0" already exists. Warning: the in-cluster version is different than the backed-up version.
              stat /tmp/183602585/resources/persistentvolumeclaims/namespaces/default/elasticsearch-master-elasticsearch-master-1.json: no such file or directory
              stat /tmp/183602585/resources/persistentvolumeclaims/namespaces/default/es-snap-repo-pvc.json: no such file or directory
              could not restore, pods "elasticsearch-master-1" already exists. Warning: the in-cluster version is different than the backed-up version.

Backup:  elasticsearch-backup-v1

Namespaces:
  Included:  all namespaces found in the backup
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto
```

beside the differences in the versions, is it even possible to migrate only the data into an existing (same claim name) volume ?

Thanks.

**Comment by ashish-amarnath** [comment]
@avishaiNB Thanks for reporting this issue. We currently don't have this implemented and have https://github.com/vmware-tanzu/velero/issues/504, similar to your ask, on our backlog. We don't have an ETA for this yet. We will keep the issue #504 updated once we do.

We are now using using issue voting for prioritizing our back log. Please feel free to upvote this issue and #504 


Vote on this issue!

This is an invitation to the Velero community to vote on issues, you can see the project's top voted issues listed here.
Use the "reaction smiley face" up to the right of this comment to vote.

👍 for "I would like to see this bug fixed as soon as possible"
👎 for "There are more important bugs to focus on right now"

**Comment by ashish-amarnath** [comment]
Considering that this is a duplicate issue and that the two issues have been linked. I am going to close this issue to avoid upvote fragmentation.
Please feel free to reach out if you have more questions.
