### ISSUE TITLE
While backing up custom resource, auto include the CRD in the backup

### ISSUE THREAD

**Issue by ashish-amarnath** [vmware-tanzu/velero#2673]
context dump: https://kubernetes.slack.com/archives/C6VCGP4MT/p1593205549061900

**What steps did you take and what happened:**
While backing up custom resources, the corresponding CRD are not included in the backup without the `--include-cluster-resources` flag.
Further, even if the backup does included CRDs, they are not restored if the restore did use the `--include-cluster-resources` 
flag.

**What did you expect to happen:**
Backing up and restore of custom resources should auto include the corresponding CRDs in their respective operations.

TODOs:
- [x] Verify behavior mentioned above is true. It is expected that a fix for this is already available.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

cc @ncdc

**Comment by ashish-amarnath** [comment]
Quick update on this.
So the CRDs are included as part of the backup even without the `--include-cluster-resources` flag as reported in this issue.
The code that does this is https://github.com/vmware-tanzu/velero/blob/master/pkg/backup/backup.go#L421-L428
Further more the restore flow also attempts to restore the CRDs.  

However, the custom resources were not being restored because the restoring of the CRDs would fail because of https://github.com/vmware-tanzu/velero/issues/2682 which in turn would result in failure of the restoration of the custom resources with a discovery failure error.

I am putting up a fix to https://github.com/vmware-tanzu/velero/issues/2682 which should also address this issue.

**Comment by ashish-amarnath** [comment]
PR https://github.com/vmware-tanzu/velero/pull/2683 has been merged and that should have solved this issue.
Closing this issue.

**Comment by JohnnyCrazy** [comment]
So just to be sure about if I hit this issue currently:

Is it true that backing up and restoring CRDs with 1.40 is not working? I'm currently experimenting backing up/restoring and one of my cluster components is `cert-manager`, which is using CRDs to save LE certificates. After a backup and restore, I was not able to find any certificates.

**Comment by nrb** [comment]
@JohnnyCrazy It was an issue in v1.4.0, yes. v1.4.2 should have fixed it.

**Comment by rahul-mereddy** [comment]
should I need to include flag `--include-cluster-resources` during the backup and restore in velero version 1.8.0?

During the recent velero backup and restore on GKE cluster we are seeing CRD's are missing during the restore.

how do I know if the velero backup or restore did the crd's restored?

**Comment by sseago** [comment]
@rahul-mereddy You should create a separate issue for this. See my answer on the closed PR I replied to, but really this should be a separate question/issue, since closed issues/PRs will generally not be monitored for new responses. I'm not sure whether you're asking a question about how things should work or providing a bug report saying that they're not working as promised, but repeating my other reply on how things should be working here. If this isn't what you're seeing, feel free to open a new issue/bug report describing the problem:
```
if include-cluster-resources is true, then all cluster-scoped resources will be backed up, regardless of whether they're relevant to the namespaces being backed up, which means all CRDs should be included. If it's set to false then no cluster-scoped resources will be included, including CRDs. If it's nil (the default value), then only relevant cluster-scoped resources will be included. For CRDs, this means that if a CR for mytype.myorg.org is backed up, then the mytype.myorg.org CRD will be backed up as well, but irrelevanttype.myorg.org will not be backed up.
```
