### ISSUE TITLE
add Started and Completed time in the restore operation

### ISSUE THREAD

**Issue by luwang-vmware** [vmware-tanzu/velero#2687]
**Describe the problem/challenge you have**
velero backup has Started and Completed time to clear know how long it takes. But in the restore operation, I do not see it. Is it possible to add it in the restore as well? So user can clearly see how long it takes during restore, specially the pods with PV attached.

**Describe the solution you'd like**
velero restore can show Started and Completed time

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
@luwang-vmware You're right, this was definitely an oversight when we added the timestamps to the backup information!

I'm going to slate this for the v1.6 milestone, but it may be moved up depending on how busy the team is, and it's a great observability and reporting tool.

cc @stephbman for visibility.

**Comment by luwang-vmware** [comment]
Thanks @nrb.  It is great that it is in the to-do list.  I also understand the prioritizing of tasks.

**Comment by thejasbabu** [comment]
@nrb @luwang-vmware Do we want to capture the Completed time for failed restore operation? I can contribute to add these to `RestoreStatus`

**Comment by nrb** [comment]
This was resolved by PR #2748

**Comment by luwang-vmware** [comment]
Thanks @thejasbabu and @nrb. I will have a try. BTW, is the fix in velero1.4.2?

**Comment by nrb** [comment]
@luwang-vmware No, this will be in v1.5.0, however.

We're aiming to ship a beta for v1.5.0 soon.
