### ISSUE TITLE
PodVolumeRestore not created on velero restore create

### ISSUE THREAD

**Issue by michael-niemand** [vmware-tanzu/velero#2688]
**What steps did you take and what happened:**

1. Have a workload with 2 volumes
2. Have them backed up properly including said volumes (backup has Completed state, volumes are in the annotation with their volume name. PodVolumeBackup objects are there and are in Completed phase)
3. create a restore using
`velero restore create --from-backup=fresubin-dev-backup-schedule-20200703080016 --include-cluster-resources=false --restore-volumes=true` (tried without --include-cluster-resources=false, too - only want the volumes though)
4. Cluster Objects being restored (or skipped if there already)
5. volumes not being restored, PodVolumeRestore object is not being created, even though there are PodVolumeBackup objects for each backup. 

**What did you expect to happen:**

Cluster objects as well as volumes being restored

**The output of the following commands will help us better understand what's going on**:
See gist for detailed output: https://gist.github.com/michael-niemand/6b8ca27003508708c01efc5d81bb56cd

**Environment:**

- Velero version (use `velero version`): 
Client:
	Version: v1.4.0
	Git commit: 5963650c9d64643daaf510ef93ac4a36b6483392
Server:
	Version: v1.4.0

- Velero features (use `velero client config get features`): 
features: <NOT SET>
(using only the Azure Plugin and --use-restic = true)

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a2cfecc33f6911261fb8a670d2df2714094002a6", GitTreeState:"clean", BuildDate:"2020-05-29T21:50:25Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
1.16.9
- Cloud provider or hardware configuration:
AKS
- OS (e.g. from `/etc/os-release`):
Ubuntu 18.04 LTS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by michael-niemand** [comment]
TIL there must not be any traces of the objects that have been backed, otherwise the volumes are not being restored - is that the case?

**Comment by ashish-amarnath** [comment]
Sorry about the latency here. Looking at this now.

**Comment by ashish-amarnath** [comment]
@michael-niemand This is what I saw when I re-ran the steps you reported in this issue.
I saw that the pod volume restores get created.
```bash
$ kcv get podvolumerestores
NAME                      AGE
b1-20200808133105-g9k2d   13m
b1-20200808133105-tr44n   13m
```

But the pod volume restore controller wasn't able to make progress 
```bash
$ kcv get podvolumerestores  -ojson | jq .items[].status
{
  "progress": {}
}
{
  "progress": {}
}
```

This was because the associated persistent volumes weren't restored.
```
time="2020-08-08T20:31:06Z" level=info msg="Not restoring item because it's cluster-scoped" groupResource=persistentvolumes logSource="pkg/restore/restore.go:818" name=pvc-b7a1dd16-bdbc-4d33-9ed6-6e637084ce12 namespace= restore=velero/b1-20200808133105
time="2020-08-08T20:31:07Z" level=info msg="Not restoring item because it's cluster-scoped" groupResource=persistentvolumes logSource="pkg/restore/restore.go:818" name=pvc-d3e94f8b-2c6d-40dd-9b32-301a5c94f095 namespace= restore=velero/b1-20200808133105
```

**Comment by michael-niemand** [comment]
Thanks for the reply! I haven't followed that path further - we switched to VolumeSnapshots in the meantime. But what could it mean when the associated PVs weren't restored? I saw that log message but disregarded it since it was just info level. Is that a permission issue? Are the PVs supposed to be restored?

**Comment by ashish-amarnath** [comment]
Restic restores pod volumes by "unpacking" the backup from the restic repo into the restored volume.
Now in this case, because the volumes weren't restored, restic doesn't have a destination volume to "unpack" the backup into. The volumes are not restored because of the `--include-cluster-resources=false` flag.

I am going to close this issue. But please re-open or reach out if you have more questions.
