### ISSUE TITLE
Providing '/' in namespace leads to a crash

### ISSUE THREAD

**Issue by rohandvora** [vmware-tanzu/velero#2690]
**What steps did you take and what happened:**
Running the following command leads to velero pod crashing. The backup gets stuck in `in-progress` state.
`velero backup create backup-3 --include-namespaces /`

**What did you expect to happen:**
Though the namespace isn't valid, the expected behavior would be to fail the backup with validation error.

**The output of the following commands will help us better understand what's going on**:
- `kubectl logs deployment/velero -n velero`
https://gist.github.com/rohandvora/c1d7a39445bafef63650c2bf4d5c2d45
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/source-cluster-k8s-gitversion: v1.17.4+vmware.1
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "17"
  creationTimestamp: "2020-07-06T16:57:27Z"
  generation: 2
  labels:
    velero.io/storage-location: test-cred-dp
  name: backup-3
  namespace: velero
  resourceVersion: "19813238"
  selfLink: /apis/velero.io/v1/namespaces/velero/backups/backup-3
  uid: 830d4ccb-a37e-45d7-a3a1-29f8081e131b
spec:
  hooks: {}
  includedNamespaces:
  - /
  storageLocation: test-cred-dp
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - default-aws
status:
  expiration: "2020-08-05T16:57:27Z"
  formatVersion: 1.1.0
  phase: InProgress
  startTimestamp: "2020-07-06T16:57:27Z"
  version: 1
```

**Environment:**

- Velero version (use `velero version`): `v1.4.0`
- Velero features (use `velero client config get features`):  `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4+vmware.1", GitCommit:"2e240196fa7251c7f1ff96392db857c281f534e5", GitTreeState:"clean", BuildDate:"2020-04-16T04:00:11Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: VMWare Tanzu provisioned cluster.
- Cloud provider or hardware configuration: VMWare Tanzu provisioned cluster.

**Comment by ashish-amarnath** [comment]
@rohandvora were you expecting all the namespaces to be backedup?
`/` is not a valid kubernetes namespace name.
Kubernetes resource should be a valid DNS-1123 label- consisting of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character.
If your intention was to backup all namespaces, then you can use `*`

Closing this issue. Please reopen or reach out if you have more questions.

**Comment by ashish-amarnath** [comment]
It could also be possible that you were expecting Velero to handle this error more gracefully than a crash.
Reopening to clarify.

**Comment by rohandvora** [comment]
Hey @ashish-amarnath. Yup. I was expecting Velero to handle this error more gracefully rather than crashing. Though / is not a valid name, there is no validation being done. Though we expect users to provide a valid namespace, not doing so shouldn't lead to a crash. Having said that, this isn't a critical bug blocking us, but would be good to fix it 🙂

**Comment by Divya063** [comment]
I would like to pick this up.

**Comment by codegold79** [comment]
I haven't looked at the code yet, but it seems validation should happen both in the client-side as well as on the server-side. I'll try to make that happen.
