### ISSUE TITLE
mongodb pvc snapshot backup are not proper

### ISSUE THREAD

**Issue by veera2019** [vmware-tanzu/velero#2692]
Hi,
  Mongodb pvc having more that 3GB data , but after taking backup in snapshot it's showing in 29 bytes of data only, it's not taking entire pvc data backup, what is the way to take entire mongodb pvc data backup?
We are running this commands to take backup

 Note: we are trying to take backup from on-prem servers.
velero backup create full-cluster-backup-aws --storage-location aws

Thanks
VeeraReddy

**Comment by carlisia** [comment]
I assume you are using restic?

Here's how you do that with version 1.4: https://velero.io/docs/v1.4/restic/#back-up

For the upcoming 1.5 release, we added an option to select all, and opt-out: I suspect you are not specifying the pod volumes to be backed up. 


https://velero.io/docs/master/restic/#to-back-up

**Comment by vinayus** [comment]
If these are statically provisioned PV, then it is suggested to use restic as said above and hopefully you have annotated the pod with respective volume names.

**Comment by carlisia** [comment]
Hi @veera2019 this is likely an issue of lack of annotation. I will close this issue but please reopen if you still haven't figured it out. Thanks.
