### ISSUE TITLE
Velero HA azure

### ISSUE THREAD

**Issue by balajir24** [vmware-tanzu/velero#2694]
Maintainer EDIT (@ashish-amarnath ) addressing insensitive language and using primary and secondary.

Hi,

We are using AKS cluster and We have enabled the HA for Velero ie primary and secondary.  We have defined the backup and snapshot location for master UK south and for secondary US east.

But for secondary, snapshot is storing in the same region only ie UK south. We need to store these snapshots in the US east region.

We have the separate resource group for each region.

Primary - UK south
Secondary - US east

Please help on this.

**Comment by balajir24** [comment]
Hi,

Could you please update on this.

**Comment by nrb** [comment]
Hi @balajir24, I'm not entirely sure what you mean by a secondary/primary for Velero. Do you have 2 deployments of Velero? Two replicas of Velero within the deployment?

Right now, Velero should only be deployed as a single pod within a cluster. We have expanding our concurrency support [on our roadmap](https://github.com/vmware-tanzu/velero/blob/master/ROADMAP.md) for later this year.

**Comment by balajir24** [comment]
@nrb 

We have enabled 2 snapshot locations for high availability in Velero.

**root@e1ef4189a42c:~:516 $ velero snapshot-location get
NAME            PROVIDER
azure-default   velero.io/azure
slave           velero.io/azure**

regions for snapshot-location

_azure-default - UK south
slave - US east_

We are using separate resource group for each snapshot-location.

If we are taking snapshot through slave snapshot-location(region-> US east), the snapshots are creating in UK south region only. It should create snapshot in US east region.

Please help on this.

**Comment by nrb** [comment]
@balajir24 Can you provide me with the commands you used to create the backups and output of the `velero backup get <backup name> -o yaml` of affected backups?

Unfortunately I'm not able to advise you with the limited information here.

**Comment by balajir24** [comment]
@nrb 

We are using Azure. I used below command to create backup. It is executed successfully. But snapshot is not storing in us east region. It is storing in uk-south region.

```velero backup create timescale-backup-003 --include-namespaces test --storage-location slave --volume-snapshot-locations slave
```

resourceGroup `test-backups` present in us east region only.

 velero snapshot-location get slave -o yaml
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"velero.io/v1","kind":"VolumeSnapshotLocation","metadata":{"annotations":{},"name":"slave","namespace":"velero"},"spec":{"config":{"resourceGroup":"test-backups","subscriptionId":"1b904ab8-95f7-4f14-9af7-a6f8633a8b3c"},"provider":"velero.io/azure"}}
  creationTimestamp: "2020-07-01T13:05:21Z"
  generation: 6
  name: slave
  namespace: velero
  resourceVersion: "10828536"
  selfLink: /apis/velero.io/v1/namespaces/velero/volumesnapshotlocations/slave
  uid: eb320b4e-8620-4beb-8514-eab8b6b74e22
spec:
  config:
    resourceGroup: test-backups
    subscriptionId: 1b904ab8-95f7-4f14-9af7-a6f8633a8b3c
  provider: velero.io/azure
status: {}


```
velero backup get timescale-backup-003 -o yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/source-cluster-k8s-gitversion: v1.15.10
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "15"
  creationTimestamp: "2020-07-17T05:21:38Z"
  generation: 6
  labels:
    velero.io/storage-location: slave
  name: timescale-backup-003
  namespace: velero
  resourceVersion: "14144112"
  selfLink: /apis/velero.io/v1/namespaces/velero/backups/timescale-backup-003
  uid: 4f1dc987-3e73-4b51-85f4-610756e66a79
spec:
  hooks: {}
  includedNamespaces:
  - test
  storageLocation: slave
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - slave
status:
  completionTimestamp: "2020-07-17T05:21:53Z"
  expiration: "2020-08-16T05:21:38Z"
  formatVersion: 1.1.0
  phase: Completed
  progress:
    itemsBackedUp: 14
    totalItems: 14
  startTimestamp: "2020-07-17T05:21:38Z"
  version: 1
  volumeSnapshotsAttempted: 1
  volumeSnapshotsCompleted: 1
```

**Comment by balajir24** [comment]
@nrb Any update on this?

**Comment by ashish-amarnath** [comment]
@balajir24 Are your disks in US-East (secondary) or UK-South (primary)?
This is what the azure plugin does to create snapshots of volumes
https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/velero-plugin-for-microsoft-azure/volume_snapshotter.go#L263-L274

The snapshots go to the same location that the disks are located in.

**Comment by balajir24** [comment]
@ashish-amarnath disks present in UK-South (primary) only.

**Comment by nrb** [comment]
@balajir24 Right now, Velero does not replicate disk snapshots across regions. On GCP, with regional disks, it does support cross-availability zone restore, but that's a GCP-specific feature.

As Ashish mentioned, Velero takes a snapshot that is stored in the same region as the disk itself.

We have long term plans to address this with #103, but for now, Velero is working as designed. You can add a 👍 to #103 to help raise visibility, and that will factor into our backlog and roadmap planning.
