### ISSUE TITLE
An error occurred: unknown flag: --default-volumes-to-restic

### ISSUE THREAD

**Issue by gonzalo** [vmware-tanzu/velero#2695]
Following the instructions to enable and use restic integration for AWS and velero I cannot use the flag --default-volumes-to-restic in both installation or backup commands (https://velero.io/docs/master/customize-installation/ https://velero.io/docs/master/restic/)

Tested on mac and linux

```
./velero version
Client:
	Version: v1.4.0
	Git commit: 5963650c9d64643daaf510ef93ac4a36b6483392
```
```
velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.1.0 \
    --bucket $VELERO_BUCKET \
    --backup-location-config region=$AWS_REGION \
    --snapshot-location-config region=$AWS_REGION \
    --use-restic \
    --default-volumes-to-restic \
    --secret-file ./velero-credentials
...
An error occurred: unknown flag: --default-volumes-to-restic
```
Also 
```
velero backup create tst-gonzalo-`date "+%Y-%m-%d-%H-%M-%S"` --default-volumes-to-restic --ttl 1h --include-namespaces tst-gonzalo
…
An error occurred: unknown flag: --default-volumes-to-restic
```

**Comment by iohenkies** [comment]
Same here. Removed everything and installed 1.3.1 instead of 1.4.0: same problem

**Comment by gonzalo** [comment]
I've found the answer... you looked the same document as me and it's for **master** branch not 1.4 release. Checkout the 1.4 docs https://velero.io/docs/v1.4/customize-installation/ and https://velero.io/docs/v1.4/restic/ and you won't see any reference to that flag.

**Comment by iohenkies** [comment]
Thanks! So we need to annotate every pod/deployment?

**Comment by carlisia** [comment]
@ashish-amarnath going to assign this to you, maybe the docs could be improved.

**Comment by ashish-amarnath** [comment]
@gonzalo The feature you are trying to use has not been released. You are referring to the docs for the code in the master branch and running the release 1.3.2 and 1.4.0

This feature will be part of the 1.5 release of Velero, eta Aug 2020

I am going to close this issue. Please reach out if you have more questions or would like to run this feature in a non-prod environment .
