### ISSUE TITLE
Velero CSI documentation confusion

### ISSUE THREAD

**Issue by raghavendrabhat** [vmware-tanzu/velero#2707]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

The CSI related documentation in velero project (https://velero.io/docs/master/csi/) says this in the last paragraph.

VolumeSnapshotContents will have a DeletionPolicy of Retain for the life of the Velero backup in order to prevent them from being deleted on the storage system. When the Velero backup expires, the VolumeSnapshot objects will be deleted and the VolumeSnapshotContent objects will be updated to have a DeletionPolicy of Delete, in order to free space on the storage system.

The above information is a bit confusing. Because, it leads to an expectation that when a velero backup is taken (with CSI enabled), the "volumeSnapshotContent" objects that are associated with the backup would have a DelectionPolicy of "Retain" (i.e. I expected that the DeletionPolicy of the "volumeSnapshotContent" objects from the source cluster would be changed to Retain). In fact with this expectation (or understanding) when I deleted a namespace running a stateful app whose backup was taken via velero, the "volumeSnapshotContent" objects were removed. Later the restore operation failed as the original "volumeSnapshot" and "volumeSnapshotContent" objects were deleted as part of the namespace deletion.

I believe the paragraph from the documentation intend to say that the "volumeSnapshotContent" objects that are stored in the object storage as part of the backup operation would have their deletion policy set to Retain. But the paragram leads to an understanding that the snapshots taken in the storage cluster (i.e. source kubernetes cluster from which the backup was taken) will be retained even when the namespace of the PVC (to which the snapshot belongs to) is deleted. 

Appreciate any clarifications if the above interpretation is not correct. 

**What did you expect to happen:**

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): master and 1.4
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.17.0
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ashish-amarnath** [comment]
@raghavendrabhat Thanks for bringing up this issue. I've put up a PR #2765  to make the docs more clear. PTAL.

**Comment by ashish-amarnath** [comment]
PR #2765 that clarifies this has been merged. Closing this issue. Please feel free to engage with us if you have more questions.
