### ISSUE TITLE
Velero restore for PV using Trident CSI - failed to provision volume from the snapshot 

### ISSUE THREAD

**Issue by Rahulnz** [vmware-tanzu/velero#2708]
**What steps did you take and what happened:**
In the K8s test cluster, I created a namespace called wordpress, using helm chart wordpress was installed. Velero and minio are already installed and configured in the backup namespace. PersistentVolumes are created and presented by trident (NetApp storage). Trident CSI is configured and allows to take snapshots.

I took backup of the wordpress namespace 

•	Backup shows that snapshot is ready to be used..

user1@test-jh01:~$ velero backup describe wp-14-01 -n backup --details
Name:         wp-14-01
Namespace:    backup
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.18.2
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18

Phase:  Completed

Namespaces:
  Included:  wordpress
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-07-14 15:50:46 +1200 NZST
Completed:  2020-07-14 15:51:18 +1200 NZST

Expiration:  2020-08-13 15:50:46 +1200 NZST

Resource List:
  acme.cert-manager.io/v1alpha3/Order:
    - wordpress/wordpress-ingress-tls-515449749-434667254
  apiextensions.k8s.io/v1/CustomResourceDefinition:
    - certificaterequests.cert-manager.io
    - certificates.cert-manager.io
    - orders.acme.cert-manager.io
  apps/v1/ControllerRevision:
    - wordpress/wordpress-site-mariadb-b4fc5757
  apps/v1/Deployment:
    - wordpress/wordpress-site
  apps/v1/ReplicaSet:
    - wordpress/wordpress-site-b54b569cb
  apps/v1/StatefulSet:
    - wordpress/wordpress-site-mariadb
  cert-manager.io/v1alpha3/Certificate:
    - wordpress/wordpress-ingress-tls
  cert-manager.io/v1alpha3/CertificateRequest:
    - wordpress/wordpress-ingress-tls-515449749
  discovery.k8s.io/v1beta1/EndpointSlice:
    - wordpress/wordpress-site-5lqb4
    - wordpress/wordpress-site-mariadb-kbkd4
  extensions/v1beta1/Ingress:
    - wordpress/ingress-wp
  networking.k8s.io/v1beta1/Ingress:
    - wordpress/ingress-wp
  snapshot.storage.k8s.io/v1beta1/VolumeSnapshot:
    - wordpress/velero-data-wordpress-site-mariadb-0-7wmf5
    - wordpress/velero-wordpress-site-svx69
  snapshot.storage.k8s.io/v1beta1/VolumeSnapshotClass:
    - csi-snapclass
  snapshot.storage.k8s.io/v1beta1/VolumeSnapshotContent:
    - snapcontent-5a634b18-8d95-4ac4-bd6d-f714d16c4838
    - snapcontent-a4846776-ebbd-4734-b0ba-e76bdca09381
  v1/ConfigMap:
    - wordpress/wordpress-site-mariadb
    - wordpress/wordpress-site-mariadb-tests
  v1/Endpoints:
    - wordpress/wordpress-site
    - wordpress/wordpress-site-mariadb
  v1/Event:
    - wordpress/data-wordpress-site-mariadb-0.1621816c1b159341
    - wordpress/data-wordpress-site-mariadb-0.1621816c1bce7bdc
    - wordpress/data-wordpress-site-mariadb-0.1621816c72a7a426
    - wordpress/data-wordpress-site-mariadb-0.1621816c7317f06e
    - wordpress/ingress-wp.1621816c36e308f7
    - wordpress/ingress-wp.1621816c36e6a280
    - wordpress/ingress-wp.1621816c36f16446
    - wordpress/wordpress-ingress-tls-515449749.1621816c2dd51f53
    - wordpress/wordpress-ingress-tls-515449749.1621816c2ebf9338
    - wordpress/wordpress-ingress-tls-515449749.1621816e82c2cd0f
    - wordpress/wordpress-site-b54b569cb-s565b.1621816c2804cc79
    - wordpress/wordpress-site-b54b569cb-s565b.1621816c2881eb94
    - wordpress/wordpress-site-b54b569cb-s565b.1621816c2ce77f9e
    - wordpress/wordpress-site-b54b569cb-s565b.1621816d2b2d7ce3
    - wordpress/wordpress-site-b54b569cb-s565b.1621816d2ea0b904
    - wordpress/wordpress-site-b54b569cb-s565b.1621816f1c87d5b0
    - wordpress/wordpress-site-b54b569cb-s565b.1621816f21c2514b
    - wordpress/wordpress-site-b54b569cb-s565b.1621816f28758fff
    - wordpress/wordpress-site-b54b569cb-s565b.16218176778dfc28
    - wordpress/wordpress-site-mariadb-0.1621816c2abc24de
    - wordpress/wordpress-site-mariadb-0.1621816c2b2c90bb
    - wordpress/wordpress-site-mariadb-0.1621816c43be003c
    - wordpress/wordpress-site-mariadb-0.1621816d66c08720
    - wordpress/wordpress-site-mariadb-0.1621816d6bbf0d45
    - wordpress/wordpress-site-mariadb-0.1621817135fb08c8
    - wordpress/wordpress-site-mariadb-0.162181713a1e2a36
    - wordpress/wordpress-site-mariadb-0.162181713f28121c
    - wordpress/wordpress-site.1621816c1c4f4d37
    - wordpress/wordpress-site.1621816c1c9add4c
    - wordpress/wordpress-site.1621816cd8bdb000
    - wordpress/wordpress-site.1621816cd9445a62
  v1/Namespace:
    - wordpress
  v1/PersistentVolume:
    - pvc-3e414d2a-5827-496c-9af2-696c38ecdf76
    - pvc-f67d8dad-c3f6-4972-9623-c1498eab1aa6
  v1/PersistentVolumeClaim:
    - wordpress/data-wordpress-site-mariadb-0
    - wordpress/wordpress-site
  v1/Pod:
    - wordpress/wordpress-site-b54b569cb-s565b
    - wordpress/wordpress-site-mariadb-0
  v1/Secret:
    - wordpress/default-token-kktw7
    - wordpress/sh.helm.release.v1.wordpress-site.v1
    - wordpress/wordpress-ingress-tls
    - wordpress/wordpress-site
    - wordpress/wordpress-site-mariadb
  v1/Service:
    - wordpress/wordpress-site
    - wordpress/wordpress-site-mariadb
  v1/ServiceAccount:
    - wordpress/default

Velero-Native Snapshots: <none included>

CSI Volume Snapshots:
Volume Snapshot Content snapcontent-0a33c7e3-c5db-4cc7-ae79-ef808a5b77f4 cannot be described because its status is nil
Volume Snapshot Content snapcontent-145679bf-cffe-42e1-a45e-b5d839fcea3d cannot be described because its status is nil
Volume Snapshot Content snapcontent-211bd68e-cf96-445c-a342-388666748213 cannot be described because its status is nil
Volume Snapshot Content snapcontent-3eb784f1-5875-43f2-8607-2d2ce8e785c6 cannot be described because its status is nil
Snapshot Content Name: snapcontent-5a634b18-8d95-4ac4-bd6d-f714d16c4838
  Storage Snapshot ID: pvc-f67d8dad-c3f6-4972-9623-c1498eab1aa6/snapshot-5a634b18-8d95-4ac4-bd6d-f714d16c4838
  Snapshot Size (bytes): 8589934592
  Ready to use: true
Volume Snapshot Content snapcontent-5e3dfb6a-85b6-4b63-b55c-2108db5b6ef1 cannot be described because its status is nil
Volume Snapshot Content snapcontent-6b54fcc0-b7fd-4a03-a9cd-fe585fc6e657 cannot be described because its status is nil
Volume Snapshot Content snapcontent-6bfef4ea-926f-48f8-833b-2c8d7d9837a8 cannot be described because its status is nil
Volume Snapshot Content snapcontent-6d58d3b7-a320-458c-8606-af70bc0d89fa cannot be described because its status is nil
Snapshot Content Name: snapcontent-a4846776-ebbd-4734-b0ba-e76bdca09381
  Storage Snapshot ID: pvc-3e414d2a-5827-496c-9af2-696c38ecdf76/snapshot-a4846776-ebbd-4734-b0ba-e76bdca09381
  Snapshot Size (bytes): 10737418240
  Ready to use: true
Volume Snapshot Content snapcontent-ad5f0557-1022-4b18-b8f6-17ed6e04c51e cannot be described because its status is nil
Volume Snapshot Content snapcontent-baaaa29c-ab52-4773-8dfb-9ba7d08adaa5 cannot be described because its status is nil
Volume Snapshot Content snapcontent-c0126bdd-4e68-4940-a5f7-ec98103e63cf cannot be described because its status is nil
Volume Snapshot Content snapcontent-c3fe7492-7187-40a7-a973-007cb1e94708 cannot be described because its status is nil
Volume Snapshot Content snapcontent-c9f53a90-337c-4064-8730-91b399157f70 cannot be described because its status is nil
Volume Snapshot Content snapcontent-d7813753-7a42-47f5-975f-9fec68c81ee4 cannot be described because its status is nil
Volume Snapshot Content snapcontent-e287f20c-0361-4a47-ae50-8da69b27ecd2 cannot be described because its status is nil
Volume Snapshot Content snapcontent-f0f1e0e1-0e8b-42ed-bb6c-7ff7744acf4e cannot be described because its status is nil

•	Volumesnapshotcontent shows “true” for readytouse column

![image](https://user-images.githubusercontent.com/44512749/87388339-b8ba4d80-c5f8-11ea-8498-52eb3836d076.png)

•	volumesnapshot shows “true” for readytouse 
![image](https://user-images.githubusercontent.com/44512749/87388380-cc65b400-c5f8-11ea-80c1-2648519701e0.png)

•	Restoring entire namespace from the backup 

user1@test-jh01:~$ velero restore create --from-backup wp-14-01 -n backup
Restore request "wp-14-01-20200714162002" submitted successfully.
Run `velero restore describe wp-14-01-20200714162002` or `velero restore logs wp-14-01-20200714162002` for more details.

•	Restore describe 

user1@test-jh01:~$ velero restore describe wp-14-01-20200714162002 -n backup
Name:         wp-14-01-20200714162002
Namespace:    backup
Labels:       <none>
Annotations:  <none>

Phase:  Completed

Warnings:
  Velero:     <none>
  Cluster:  could not restore, customresourcedefinitions.apiextensions.k8s.io "certificaterequests.cert-manager.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "certificates.cert-manager.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "orders.acme.cert-manager.io" already exists. Warning: the in-cluster version is different than the backed-up version.
  Namespaces: <none>

Backup:  wp-14-01

Namespaces:
  Included:  all namespaces found in the backup
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

•	It fails to provision volume with storageclass

user1@test-jh01:~$ kubectl get events -n wordpress
LAST SEEN   TYPE      REASON                 OBJECT                                                MESSAGE
0s          Normal    ExternalProvisioning   persistentvolumeclaim/data-wordpress-site-mariadb-0   waiting for a volume to be created, either by external provisioner "csi.trident.netapp.io" or manually created by system administrator
22s         Normal    Provisioning           persistentvolumeclaim/data-wordpress-site-mariadb-0   External provisioner is provisioning volume for claim "wordpress/data-wordpress-site-mariadb-0"
22s         Warning   ProvisioningFailed     persistentvolumeclaim/data-wordpress-site-mariadb-0   failed to provision volume with StorageClass "netapp-general": error getting handle for DataSource Type VolumeSnapshot by Name velero-data-wordpress-site-mariadb-0-7wmf5: snapshot velero-data-wordpress-site-mariadb-0-7wmf5 is not Ready
50s         Normal    CREATE                 ingress/ingress-wp                                    Ingress wordpress/ingress-wp
50s         Normal    CREATE                 ingress/ingress-wp                                    Ingress wordpress/ingress-wp
50s         Normal    CREATE                 ingress/ingress-wp                                    Ingress wordpress/ingress-wp
50s         Normal    OrderCreated           certificaterequest/wordpress-ingress-tls-515449749    Created Order resource wordpress/wordpress-ingress-tls-515449749-434667254
40s         Warning   OrderFailed            certificaterequest/wordpress-ingress-tls-515449749    Failed to wait for order resource wordpress/wordpress-ingress-tls-515449749-434667254 to become ready: order is in "errored" state
<unknown>   Warning   FailedScheduling       pod/wordpress-site-b54b569cb-s565b                    running "VolumeBinding" filter plugin for pod "wordpress-site-b54b569cb-s565b": pod has unbound immediate PersistentVolumeClaims
<unknown>   Warning   FailedScheduling       pod/wordpress-site-b54b569cb-s565b                    running "VolumeBinding" filter plugin for pod "wordpress-site-b54b569cb-s565b": pod has unbound immediate PersistentVolumeClaims
<unknown>   Warning   FailedScheduling       pod/wordpress-site-b54b569cb-s565b                    running "VolumeBinding" filter plugin for pod "wordpress-site-b54b569cb-s565b": pod has unbound immediate PersistentVolumeClaims
<unknown>   Warning   FailedScheduling       pod/wordpress-site-mariadb-0                          running "VolumeBinding" filter plugin for pod "wordpress-site-mariadb-0": pod has unbound immediate PersistentVolumeClaims
<unknown>   Warning   FailedScheduling       pod/wordpress-site-mariadb-0                          running "VolumeBinding" filter plugin for pod "wordpress-site-mariadb-0": pod has unbound immediate PersistentVolumeClaims
<unknown>   Warning   FailedScheduling       pod/wordpress-site-mariadb-0                          running "VolumeBinding" filter plugin for pod "wordpress-site-mariadb-0": pod has unbound immediate PersistentVolumeClaims
0s          Normal    ExternalProvisioning   persistentvolumeclaim/wordpress-site                  waiting for a volume to be created, either by external provisioner "csi.trident.netapp.io" or manually created by system administrator
22s         Normal    Provisioning           persistentvolumeclaim/wordpress-site                  External provisioner is provisioning volume for claim "wordpress/wordpress-site"
50s         Warning   ProvisioningFailed     persistentvolumeclaim/wordpress-site                  failed to provision volume with StorageClass "netapp-general": error getting handle for DataSource Type VolumeSnapshot by Name velero-wordpress-site-svx69: snapshot velero-wordpress-site-svx69 not bound
22s         Warning   ProvisioningFailed     persistentvolumeclaim/wordpress-site                  failed to provision volume with StorageClass "netapp-general": error getting handle for DataSource Type VolumeSnapshot by Name velero-wordpress-site-svx69: snapshot velero-wordpress-site-svx69 is not Ready

•	The snapshot’s READYTOUSE state becomes false 

![image](https://user-images.githubusercontent.com/44512749/87388447-ef906380-c5f8-11ea-979e-226ee0db5b00.png)

**What did you expect to happen:**
Velero provisioning a volume using a volumesnapshot (which was in the ready state)

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n backup `
https://gist.github.com/Rahulnz/d39183f764440d301791ddd93bf91070
- `velero backup logs <backupname>`
https://gist.github.com/Rahulnz/98621ae93bb6b1b8e2d07d05fbd3e50e
- `velero restore logs <restorename>`
https://gist.github.com/Rahulnz/e06c215c1e9228318ae643456f9bf155

**Anything else you would like to add:**
There are 2 different storageclasses Netapp-general and Netapp-Perf. both storageclasses got similar information except netapp-general is a default class

**Environment:**

- Velero version (use `velero version`): 
Client:
        Version: v1.4.0
        Git commit: 5963650c9d64643daaf510ef93ac4a36b6483392
Server:
        Version: v1.4.0

- Velero features (use `velero client config get features`): 

features: EnableCSI

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:

- Cloud provider or hardware configuration:
 On-premise, vms created using vCloud 

- OS (e.g. from `/etc/os-release`):
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ashish-amarnath** [comment]
@Rahulnz Here are a few things to try:
1. Confirm if Trident supports Kubernetes snapshot beta APIs https://kubernetes.io/docs/concepts/storage/volume-snapshots/. It wasn't clear to me from their docs at https://netapp-trident.readthedocs.io/en/stable-v19.01/kubernetes/trident-csi.html#csi-overview
1. Please set the `DeletionPolicy` on the volumesnapshot class that Velero uses to `Retain` this will ensure that the volume snapshots are preserved for the lifetime of the Velero backup, even in the event of the namespace loss. FYI we've addressed the known limitation https://github.com/vmware-tanzu/velero-plugin-for-csi/issues/17 and the fix will be part of the next release of the cycle. You can get the fix right away by switching to the `velero/velero-plugin-for-csi:main` image.
1. If you continue to experience the issue after following the above steps, please inspect the CSI driver log to understand what might be happening in the storage system.

**Comment by Rahulnz** [comment]
Thanks for the reply @ashish-amarnath , Trident supports Kubernetes snapshot beta APIs as per https://netapp-trident.readthedocs.io/en/stable-v20.04/kubernetes/operations/tasks/volumes.html#on-demand-volume-snapshots
I was not aware of limitation as per point2 so I change the volumesnapshot class DeletionPolicy to "Retain" and I was successfully able to restore entire namespace using snapshots.  
I still see that in the Minio bucket snapshotcontent is "null", so does that mean Velero will not be coping volumesnapshot to the object storage? Can we use it for the DR and creating a same namespace in other cluster?
Thanks again for all your help.

**Comment by ashish-amarnath** [comment]
With the CSI snapshot support, the snapshot operations are triggered by the creation of the `VolumeSnapshot` objects. The snapshot operation on the volumes, however, are performed by the CSI driver, in this case, the Trident driver and are stored in the storage system and not in the BackupStorageLocation, which in your case, is minio. So, yes Velero will not be copying the VolumeSnapshot to the object-store.

Because the Trident storage system is external to the kuberentes cluster, VolumeSnapshote can be restored in the same namespace in a different cluster as long as both clusters have access to the Trident storage system.

**Comment by ashish-amarnath** [comment]
I am going to close this issue as you are now able to successfully backup and restore using the CSI snapshots.
Please feel free to re-open if you have more questions.

**Comment by Rahulnz** [comment]
Thanks Ashish for your all help in resolving this issue. I really
appreciate your detailed response and problem diagnosis.
Rahul
