### ISSUE TITLE
Velero backup is taking forever in a large cluster

### ISSUE THREAD

**Issue by melanco** [vmware-tanzu/velero#2715]
Hello, 

I'm currently managing a large Openshift 3.11.129 cluster. Over 300 namespaces, 500~ Running pods etcetc. And trying to use velero to do a full backup of all namespace, all resources but it's taking forever.

I am using velero 1.12

The backup is only saying "InProgress" but it's been running for over 24 hours now. Is this normal behaviour ? Is there a way to get better information on where the backup is at ? Like a more precise status ? 

Thanks,

**Comment by melanco** [comment]
I'm at 48 hours now for the same backup :)

**Comment by carlisia** [comment]
Hi @melanco. If you are able to upgrade to version 1.4 (https://github.com/vmware-tanzu/velero/releases/tag/v1.4.0), you''ll have a new feature that reports the backup progress.

**Comment by melanco** [comment]
Hi @carlisia, Is this feature working with Openshift ? 

I updated velero to v1.4.2 and there is not much more new information. 

Here is a copy of the output of the commands using either the oc client or velero client to query the velero API. 

[velero_output.txt](https://github.com/vmware-tanzu/velero/files/4949622/velero_output.txt)

Am I missing something ? 

Let me know,

**Comment by ashish-amarnath** [comment]
@melanco to obtain the backup progress information, you will need to update the Backup CRD on your Velero installation.
```bash
velero install --crds-only --dry-run -o yaml | kubectl apply -f -
```
This will let you track the progress of the backup.

**Comment by carlisia** [comment]
Yes, @melanco I forgot that you have to also update the CRDs. Please let us know if you get any insight from that.

**Comment by melanco** [comment]
Hi @carlisia @ashish-amarnath 

Thanks for the replies.

Still the same issue even after applying the CRDs.

[logs-backup.txt](https://github.com/vmware-tanzu/velero/files/4989874/logs-backup.txt)

Logs attached. Still only says "InProgress", I tried deleting the old backup and restarting a new one with the logs above but nothing new.

Let me know what I can do.

Regards,

Olivier

**Comment by carlisia** [comment]
Have you been able to do a small backup from this cluster?

**Comment by melanco** [comment]
Hi @carlisia, yes, small backups work. (with for example, 2-3 namespaces)

Didin't try much more than that though.

**Comment by melanco** [comment]
Trying a backup with 23 namespaces right now just to see what it would do.

Regards,

**Comment by melanco** [comment]
Backup completed with no errors. Took about 1min20secs
Started:    2020-07-28 13:51:30 -0400 EDT
Completed:  2020-07-28 13:52:52 -0400 EDT

Expiration:  2020-08-27 13:51:30 -0400 EDT

Total items to be backed up:  4102
Items backed up:              4102

**Comment by carlisia** [comment]
@nrb what are our debug steps to investigate this? I was doing a search on slack but didn't find anything useful.

tld;dr: Openshift 3.11.129 cluster. Over 300 namespaces, 500~ Running pods etcetc, backup stuck InProgress forever.

**Comment by carlisia** [comment]
@melanco please make sure you have proper resource limits allocated. 

There's a PR open with a more helpful documentation on how to do that: https://github.com/vmware-tanzu/velero/blob/b3101e7f77f3eade2473868bc4e92d5f1245dcfe/site/docs/main/customize-installation.md#customize-resource-requests-and-limits

**Comment by ashish-amarnath** [comment]
@melanco here is another issue that is similar to what you are seeing https://github.com/vmware-tanzu/velero/issues/2435
I think the suggestion I can make is to try taking backups are a finer grain instead of backing up the whole cluster at once.

**Comment by ashish-amarnath** [comment]
@melanco Sorry you are having issues with this at the moment. We plan to add concurrency support in the upcoming releases that should help speed up backups.
I am closing this issue but feel free to reach out if you need more assistance.

**Comment by flouthoc** [comment]
@ashish-amarnath I think this issue still persists. Faced this while taking full cluster backup on EKS , its been more than 24hrs backup is still showing `Inprogress`. We are using version `1.5.2`.

Also i think a feature `Show logs for backups with status as InProgress` should be extremely helpful here.
