### ISSUE TITLE
Define new restore hook annotation constants

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2728]
The constants for "normal" hooks will be:

```
    post.hook.restore.velero.io/container
    post.hook.restore.velero.io/command
    post.hook.restore.velero.io/on-error
    post.hook.restore.velero.io/exec-timeout
    post.hook.restore.velero.io/wait-timeout
```

And for init containers:
```
    init.hook.restore.velero.io/timeout
    init.hook.restore.velero.io/initContainers

```

**Comment by ashish-amarnath** [comment]
I wasn't able to find, from the e design doc, what `post.hook.restore.velero.io/wait-timeout` will be used for.

For init containers, we will need annotation keys for container-image, container-name, container-command.
I am not sure what the timeout will do for init containers, won't the pod be just stay in `Init: x/y` state till the init containers have completed execution?

**Comment by nrb** [comment]
The `timeout` should be when to consider the command failed and abort to my understanding. That would apply to either the initContainer or inline restore hooks. For initContainers, the failure mode may be a little different though.

@marccampbell and @areed does that match your understanding?

**Comment by ashish-amarnath** [comment]
The question was about the wait-timeout

________________________________

**Comment by areed** [comment]
The idea behind `post.hook.restore.velero.io/wait-timeout` was waiting for the container to start so that the hook could be run in it. The whole restore is blocked on the output of the restore hook so at some point if the pod is stuck on Init or ImagePullBackoff the entire Restore can be marked completed in a Partially Failed state rather than hanging forever.

**Comment by ashish-amarnath** [comment]
That makes sense. Thanks for clarifying @areed!

**Comment by areed** [comment]
> I am not sure what the timeout will do for init containers, won't the pod be just stay in Init: x/y state till the init containers have completed execution?

Yes, the init timeout would be for the Restore to give up waiting for the outcome of the initContainer. It would only be useful if the restore is going to include the init container logs in the Restore log or mark the Restore as Partially Failed if the initContainer fails to succeed within a certain amount of time. Unless either of those is required I think the init timeout can be dropped from the design.

**Comment by areed** [comment]
> For init containers, we will need annotation keys for container-image, container-name, container-command.

Would it be useful to have the full `init.hook.restore.velero.io/initContainers` json annotation also so that folks could provide env vars, volumeMounts, resource limits, etc. without having to use the Restore spec?

**Comment by ashish-amarnath** [comment]
@areed sorry I missed your comment. Now that PR #2750 is merged, can we go with using the annotation for basic scenarios where the user is just providing a container image and a command to run and for a more customized scenario use the Restore spec?

**Comment by areed** [comment]
> @areed sorry I missed your comment. Now that PR #2750 is merged, can we go with using the annotation for basic scenarios where the user is just providing a container image and a command to run and for a more customized scenario use the Restore spec?

Yes, that'll work!
