### ISSUE TITLE
Velero backup timeout after 3 hours of backing up a PV

### ISSUE THREAD

**Issue by mikelmao** [vmware-tanzu/velero#2733]
**What steps did you take and what happened:**
When I try to run a test backup which includes all nodes in my default namespace (including Jenkins pod), It fails with error that it timed out.  I have changed the timout time to 3 hours but still same issue. The PV is only a couple of hundred MB so it should not take very long. If I remove the annotation from my pod to backup without the PV it works without any issues.

Following error:
```
time="2020-07-20T21:45:22Z" level=info msg="1 errors encountered backup up item" backup=velero/test-backup1 logSource="pkg/backup/backup.go:444" name=jenkins-58cbd4c575-n4m6t
time="2020-07-20T21:45:22Z" level=error msg="Error backing up item" backup=velero/test-backup1 error="timed out waiting for all PodVolumeBackups to complete" error.file="/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:172" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:448" name=jenkins-58cbd4c575-n4m6t

```

**What did you expect to happen:**
I expected to have a backup of the PV on Wasabi using the S3 protocol

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
https://pastebin.com/QK9RDpmm
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
https://pastebin.com/G5DDDLtq
- `velero backup logs <backupname>`
https://pastebin.com/3cPmaHWG

**Anything else you would like to add:**
I am not sure on how to continue debugging this as I am new to Velero and Kubernetes and this error seems very generalized.

**Environment:**

- Velero version (use `velero version`): 
```
Client:
        Version: v1.4.2
        Git commit: 56a08a4d695d893f0863f697c2f926e27d70c0c5
Server:
        Version: v1.4.0
```

- Velero features (use `velero client config get features`): 
```
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by nrb** [comment]
@mikelmao From your velero server logs, I see this entry:

`time="2020-07-20T18:44:39Z" level=warning msg="Velero restic daemonset not found; restic backups/restores will not work until it's created" logSource="pkg/cmd/server/server.go:509"`

If you were using `velero install`, you'll need the `--use-restic` flag to install the DaemonSet, which will provide restic support.

I'll close this issue out for now, but please re-open it if you have any further issues.
