### ISSUE TITLE
Document backup flow

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#274]
Include info about discovery, api groups, resources, items, pre/post hooks, custom actions, additional items, etc.

**Comment by ddebrunner** [comment]
Is there any initial documentation about the flow currently, or where to look to try and figure out the flow (e.g. when are pre/post hooks executed when multiple pods exist)?

**Comment by a-mccarthy** [comment]
@nrb and I were just talking about making improvements to the backup docs, https://velero.io/docs/v1.5/how-velero-works/#backup-workflow, to make them more clear. We should make sure that the velero docs cover backups in enough detail

**Comment by eleanor-millman** [comment]
Closing until we hear more demand.
