### ISSUE TITLE
Questions about backup-locations and secret-file

### ISSUE THREAD

**Issue by henkypunky** [vmware-tanzu/velero#2744]
Hi guys, I have a couple of questions related to backup-locations:

1. Can you have backup-locations of different providers (e.g. AWS + GCP) configured in parallel? If yes, how to handle the --secret-file?
2. When you add a backup-location retroactively with "velero backup-location create", how to specify the additional credentials needed for the new backup-location? Apparently secret-file can only be specified at velero install time?
3. In the secret-file, what is the meaning of [default]? Is it always like this or is it matched against the name of the backup-location?
4. It is stated in the docs that you can only have one set of credentials per provider. Can you confirm? Are there plans to change this in near future?

Thanks for your support!

**Comment by nrb** [comment]
1) Yes, you can. However, it is an advanced option not directly supported via `velero install`. You will have to edit the Velero `Deployment` YAML. `velero install` assumes the most common scenario, which is using a single cloud platform. You can get the YAML that's submitted by `velero install` and customize it via the `--dry-run -o yaml` options. The `velero backup-location create` command also has a `-o yaml` option that will output the YAML it would submit without actually sending it to the server.
2) You will have to manually configure Velero via the Kubernetes YAML, not via the `velero` commands.
In short, you will need to create unique `Secret`s with the secret data in `data.cloud`, and alter the mount points within the Velero `Deployment` to put these in unique mount points. This isn't necessarily a Velero-specific thing, but something related to using Kubernetes in general. You'll see with my answer to question 4 that we do want to make this easier, though.
3) The secret file format is not something that Velero implements - it is specific to each cloud platform which is used by the applicable plugin. Based on your question, I think you're referring to AWS's format. `[default]` refers to the default profile inside of their secret file. AWS allows for multiple profiles to be inside their secret files. GCP, on the other hand, uses a JSON file.
4) It is on our [roadmap](https://github.com/vmware-tanzu/velero/blob/master/ROADMAP.md), yes. We have a [design document](https://github.com/vmware-tanzu/velero/pull/2403) open for it, though the implementation is still to be determined.

**Comment by henkypunky** [comment]
@nrb Thanks for quick and comprehensive response!
