### ISSUE TITLE
Question about pvc migration

### ISSUE THREAD

**Issue by amehub** [vmware-tanzu/velero#2745]
**Describe the problem/challenge you have**
Existing k8s cluster
Gluster storage - servers external to K8S
K8s -> Gluster using heketi 

Want to migrate the pv data to a new gluster

Have built a new gluster cluster

Need to recreate storage classes to point to new gluster
Manually copy data off pods
Stop pods
Delete pvc
Recreate pvc
Start pod
Copy data back into pv

**Describe the solution you'd like**
An automated solution to backup named pod or all pod pv data and migrate the pvc to a new gluster.

**Anything else you would like to add:**
Want to keep the existing pvc names so no changes are required to pods.  
Hence delete pvc, recreate pvc to new storage class pointing to new gluster

**Environment:**

- Velero version - na
- Kubernetes version - 1.18 
- Kubernetes installer & version: Kubespray 
- Cloud provider or hardware configuration: Hardware
- OS (e.g. from `/etc/os-release`):  Ububntu 18.04.03

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
I think our [storage class remapping support](https://velero.io/docs/v1.4/restore-reference/#changing-pvpvc-storage-classes) and [restic integration](https://velero.io/docs/v1.4/restic/) may be helpful to you. To my knowledge, there's no Gluster plugins for Velero.

If those two don't fit your needs, then I think this will be a feature request that we'd need to slot into our roadmap at some point.
