### ISSUE TITLE
Latest velero client does not recognize --default-volumes-to-restic flag

### ISSUE THREAD

**Issue by codebard** [vmware-tanzu/velero#2752]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Trying to install velero client from latest release per Digitalocean's guide.

https://www.digitalocean.com/community/tutorials/how-to-back-up-and-restore-a-kubernetes-cluster-on-digitalocean-using-velero 

Using below custom install command:

velero install \
  --provider velero.io/aws \
  --bucket psitesclusterbackup \
  --plugins velero/velero-plugin-for-aws:v1.0.0,digitalocean/velero-plugin:v1.0.0 \
  --backup-location-config s3Url=https://sfo2.digitaloceanspaces.com,region=sf02 \
  --secret-file=./examples/cloud-credentials \
  --use-volume-snapshots=true \
    --use-restic \
    --default-volumes-to-restic \
    --restic-pod-cpu-request 100m

**What did you expect to happen:**

Be able to install velero with --use-restic and --default-volumes-to-restic  flags.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

No output since cant install velero with the flag. The errors it gives are below:

Error: unknown flag: --default-volumes-to-restic

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  v1.4.2
- Velero features (use `velero client config get features`):  features: <NOT SET>

- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", B                           uildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", B                           uildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
- Cloud provider or hardware configuration: Digitalocean Kubernetes 1.15
- OS (e.g. from `/etc/os-release`): CentOS Linux release 7.8.2003 (Core)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by nrb** [comment]
This option will be available in Velero v1.5.0, it was not released in v1.4.2.
