### ISSUE TITLE
when restore the one namespace, the namespace is teminated after creating.

### ISSUE THREAD

**Issue by jinxinxin163** [vmware-tanzu/velero#2756]
I firstly backup a namespace from clusterA, and then restore it to clusterB. The backup process is no problem but the restore process says "PartiallyFailed": 
`root@jinxin:/app/cloud/k8s/test# velero restore get
NAME                                BACKUP               STATUS            WARNINGS   ERRORS   CREATED                         SELECTOR
xpp-ensaas-service-20200724035007   xpp-ensaas-service   PartiallyFailed   8          120      2020-07-24 11:50:07 +0800 CST   <none>
`
my backup command is following: 
`# velero backup create xpp-ensaas-service --include-namespaces ensaas-service  --include-cluster-resources --exclude-resources customresourcedefinitions.apiextensions.k8s.io`
my restore command is following:
`# velero restore create --from-backup xpp-ensaas-service`
At the beginning of restore process, velero create the namespace "ensaas-service", but I don't known why and when it is  deleted. And errors occurs:
`time="2020-07-24T03:50:34Z" level=info msg="Restoring resource 'controllerrevisions.apps' into namespace 'ensaas-service'" logSource="pkg/restore/restore.go:667" restore=velero/xpp-ensaas-service-20200724035007
time="2020-07-24T03:50:34Z" level=info msg="Getting client for apps/v1, Kind=ControllerRevision" logSource="pkg/restore/restore.go:711" restore=velero/xpp-ensaas-service-20200724035007
[jin.log](https://github.com/vmware-tanzu/velero/files/4970393/jin.log)

time="2020-07-24T03:50:34Z" level=info msg="Attempting to restore ControllerRevision: speaker-59ccccbb49" logSource="pkg/restore/restore.go:1016" restore=velero/xpp-ensaas-service-20200724035007
time="2020-07-24T03:50:34Z" level=info msg="error restoring speaker-59ccccbb49: controllerrevisions.apps \"speaker-59ccccbb49\" is forbidden: unable to create new content in namespace ensaas-service because it is being terminated" logSource="pkg/restore/restore.go:1079" restore=velero/xpp-ensaas-service-20200724035007`

how can i successfully do the restore process ? Thank you !

**Comment by nrb** [comment]
@jinxinxin163 Did you inspect the namespace itself? I don't see anything in the restore log that indicates that Velero issued a deletion, nor does Velero have support for deleting objects currently. It looks like resources first failed around line 827 of your log, so some things were getting restored prior to that.

Were you the only user of the cluster?

**Comment by ashish-amarnath** [comment]
@jinxinxin163 I am going to close this issue for inactivity. But feel free to re-open once you have the info @nrb asked for.
