### ISSUE TITLE
Error while performing full cluster restore using velero .

### ISSUE THREAD

**Issue by MadhuMahalingappa** [vmware-tanzu/velero#2757]
**What steps did you take and what happened:**
Getting PartiallyFailed error while performing restore of OCP cluster using velero , there were no issues during the time of backup though.

**What did you expect to happen:**
Expected for restore to get completed without any issues.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`

- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`

kubectl get restore/fulllcusterbackup2-20200724134024 -n velero -o yaml
apiVersion: velero.io/v1
kind: Restore
metadata:
  creationTimestamp: "2020-07-24T08:10:25Z"
  generation: 3
  name: fulllcusterbackup2-20200724134024
  namespace: velero
  resourceVersion: "5313689"
  selfLink: /apis/velero.io/v1/namespaces/velero/restores/fulllcusterbackup2-20200724134024
  uid: 04040494-23ee-4258-88cc-e986cbc6c4bb
spec:
  backupName: fulllcusterbackup2
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  includedNamespaces:
  - '*'
status:
  errors: 1
  phase: PartiallyFailed
  warnings: 608

- `velero restore logs <restorename>`

velero restore logs fulllcusterbackup2-20200724134024
msg="error restoring multus.openshift.io: ValidatingWebhookConfiguration.admissionregistration.k8s.io \"multus.openshift.io\" is invalid: webhooks[0].sideEffects: Unsupported value: \"Unknown\": supported values: \"None\", \"NoneOnDryRun\"" logSource="pkg/restore/restore.go:1133" restore=velero/fulllcusterbackup2-20200724134024

**Anything else you would like to add:**

#velero get restore
NAME                                BACKUP               STATUS            WARNINGS   ERRORS   CREATED                         SELECTOR
fulllcusterbackup2-20200724134024   fulllcusterbackup2   PartiallyFailed   608        1        2020-07-24 13:40:25 +0530 IST   <none>

Logs of restore :

#velero restore logs fulllcusterbackup2-20200724134024
msg="error restoring multus.openshift.io: ValidatingWebhookConfiguration.admissionregistration.k8s.io \"multus.openshift.io\" is invalid: webhooks[0].sideEffects: Unsupported value: \"Unknown\": supported values: \"None\", \"NoneOnDryRun\"" logSource="pkg/restore/restore.go:1133" restore=velero/fulllcusterbackup2-20200724134024

**Environment:**

- Velero version (use `velero version`):  v1.4.0
- Velero features (use `velero client config get features`): Not Set
- Kubernetes version (use `kubectl version`):

#kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2+45a4ac4", GitCommit:"45a4ac4", GitTreeState:"clean", BuildDate:"2020-06-29T06:31:08Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:  kubernetes v1.11.0+d4cacc0
- Cloud provider or hardware configuration: VMware instances
- OS (e.g. from `/etc/os-release`): Core OS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by nrb** [comment]
You may want to update your installation to v1.4.2 and try to restore again. v1.4.0 has some issues with restoring CRDs.

If that does not work, https://konveyor.github.io/ is a set of Velero plugins for OpenShift that have support for OpenShift CRDs. This may be required in order to properly restore the CRDs.

**Comment by ashish-amarnath** [comment]
@MadhuMahalingappa I assume you were able to resolve this issue following Nolan's suggestions.
- Upgrade to Velero 1.4.2 release. You will have to recreate your backup with this release as the bug fix was in the backup path.
- Use the Velero plugins for OpenShift to support restore ordering of the OpenShift CRDs.

I am going to close this issue. But feel free to reach out if you have more questions or if the suggestions didn't work.

**Comment by emilianoorengo** [comment]
Same error here using Velero 1.4.2, Openshift 4.5.8 over Azure. Actually, 2 errors (and 928 warnings):

- time="2020-09-14T16:09:42Z" level=info msg="error restoring router-default: Internal error occurred: failed to allocate requested HealthCheck NodePort 30282: provided port is already allocated" 

- time="2020-09-14T16:10:00Z" level=info msg="error restoring multus.openshift.io: ValidatingWebhookConfiguration.admissionregistration.k8s.io \"multus.openshift.io\" is invalid: webhooks[0].sideEffects: Unsupported value: \"Unknown\": supported values: \"None\", \"NoneOnDryRun\"" logSource="pkg/restore/restore.go:1133" restore=velero/test03-20200914130002

**Comment by Henning-GitHub** [comment]
I'm seeing the multus.openshift.io error, too.
On both of these environments:

- Openshift 4.5.19 / Velero v1.4.3
- Openshift 4.6.17 / Velero v1.5.2

time="2021-03-16T04:27:28Z" level=info msg="error restoring multus.openshift.io: ValidatingWebhookConfiguration.admissionregistration.k8s.io \"multus.openshift.io\" is invalid: webhooks[0].sideEffects: Unsupported value: \"Unknown\": supported values: \"None\", \"NoneOnDryRun\"" logSource="pkg/restore/restore.go:1170" restore=spp-velero/spprestore-k8s-cb14f050-5b69-4b1c-9319-277c15dba0e3
