### ISSUE TITLE
remove hardcoded svc and netpol shortcut mappings

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero#276]
https://github.com/heptio/ark/blob/master/third_party/kubernetes/pkg/kubectl/cmd/util/shortcut_expander.go#L87

This should be able to be removed now since the upstream PR to add these has been merged:
https://github.com/kubernetes/kubernetes/pull/49128

**Comment by ncdc** [comment]
This is in Kubernetes v1.8.0 and later. We'll need to keep this in Ark until we no longer support v1.8.0.
