### ISSUE TITLE
[Question] Method or plugin for MySql / MariaDB database backup with Restic

### ISSUE THREAD

**Issue by asoltesz** [vmware-tanzu/velero#2763]
I couldn't find info in the documentation about this. (and my Google-foo also failed me on this one even though Mysql is very popular with Kubernetes-capable applications like Wordpress)

I am aware  that there are dedicated DB operators for properly handling backup/restore of even large Mysql-compatible databases. However, for small databases it would be nice to have a Velero plugin (or at least documented method) that allows a reliable backup purely with Velero, without investing time/resources into a full-blown DB operator.

For example, the Wordpress Helm chart deploys an "embedded" style MariaDB instance if no external DB is specified. Many-many Wordpress sites are small (small/mid size company sites) so the database will also be small and simply dumping it every day is perfectly feasible.

Dumping the database seems to be the only way to get a consistent, online Mysql backup since a Restic backup will result in an inconsistent file set if the database is captured under load. Stopping the workloads using the MySQL database may also be an option in some cases, although results in service disruption which is almost always frown upon.

1)
Is there a way to dump the database to the PVC before that gets backed up?
Is there a way to restore the database from the dump after the PVC has been restored but before the database becomes available?

2)
If 1) is not feasible, is there a way to stop some specific deployments before the Velero backup and restart it afterwards?

**Comment by carlisia** [comment]
Related: https://github.com/vmware-tanzu/velero/issues/1150

Related: https://github.com/vmware-tanzu/velero/pull/2699

**Comment by ashish-amarnath** [comment]
@asoltesz We have some resources on our website with blogs on how to use Velero to backup MariaDB. These are available at https://velero.io/resources/ and I am referring in particular to https://docs.bitnami.com/tutorials/backup-restore-data-mariadb-galera-kubernetes/
Hope this can give you an idea on how to use Velero to backup MariaDB.

**Comment by ashish-amarnath** [comment]
Also, here are two posts about backing up MySQL with WordPress. But I think you can ignore the wordpress application and get ideas to backup just MySQL
https://blog.kubernauts.io/backup-and-restore-of-kubernetes-applications-using-heptios-velero-with-restic-and-rook-ceph-as-2e8df15b1487
https://medium.com/@Sandeepkallazhi/velero-backup-restore-for-k8s-stateful-applications-managed-by-operators-8fd9c732ffcc

**Comment by ashish-amarnath** [comment]
I am going to close this issue as your question has been answered. Please feel free to re-open should have more questions or need help with using Velero.

**Comment by ashish-amarnath** [comment]
I see there are couple of questions that I didn't answer.
> Is there a way to dump the database to the PVC before that gets backed up?

Yes, you can use backup hooks https://velero.io/docs/v1.4/hooks/ to extend Velero to perform custom actions before a backup.

> Is there a way to restore the database from the dump after the PVC has been restored but before the database becomes available?

Not yet, we are working on building restore hooks to support this. The design for this feature is available at https://github.com/vmware-tanzu/velero/blob/main/design/restore-hooks.md

**Comment by asoltesz** [comment]
@ashish-amarnath Thanks for the info, I will review them

**Comment by asoltesz** [comment]
@ashish-amarnath 

> 
> Also, here are two posts about backing up MySQL with WordPress. But I think you can ignore the wordpress application and get ideas to backup just MySQL
> https://blog.kubernauts.io/backup-and-restore-of-kubernetes-applications-using-heptios-velero-with-restic-and-rook-ceph-as-2e8df15b1487
> https://medium.com/@Sandeepkallazhi/velero-backup-restore-for-k8s-stateful-applications-managed-by-operators-8fd9c732ffcc

Regarding this article:
https://blog.kubernauts.io/backup-and-restore-of-kubernetes-applications-using-heptios-velero-with-restic-and-rook-ceph-as-2e8df15b1487

I do not see how this is a correct MySQL/MariaDB backup. 

It seems to simply take a Restic backup while the database is online. The backup will be inconsistent and restore will result in a currupt database if the database was under any kind of significant load while the backup was taken. It should minimally stop the whole workload (Wordpress+MariaDB) before taking the backup. 

Do I miss something? Where is the protection against capturing the database in an inconsistent state?

**Comment by cortex3** [comment]
@asoltesz how did you end up implementing this? I'm surprised to see that most guides I find simply backup the PV via restic while the DB is active.

**Comment by Nils98Ar** [comment]
@asoltesz I would be interested as well!

**Comment by niclashoyer** [comment]
@cortex3 @Nils98Ar as far as I understand this can be solved by using pre/post hooks and mysql queries. The [example in the docs](https://velero.io/docs/v1.10/backup-hooks/) uses `FLUSH TABLES WITH READ LOCK` in the pre hook. AFAIK a post hook with `UNLOCK_TABLES` is also required.

On another note MariaDB also includes special [backup commands](https://mariadb.com/kb/en/backup-stage/), which are more useful to get a consistent file state. This would be pre `BACKUP STAGE BLOCK_COMMIT` and post `BACKUP STAGE END`.

**Comment by Chewie** [comment]
Unfortunately, it seems the MariaDB backup commands assume everything is done across the same connection, and [releases the backup stages upon disconnect](https://mariadb.com/kb/en/backup-stage/#notes).

As such, the post hook will fail with a 'You must start backup with "BACKUP STAGE START"', and presumably the lock acquired on the pre hook was immediately released before the actual snapshot.

We'd need a way to use the same connection for both hooks, but I'm at a loss as to how to do that.

**Comment by Nils98Ar** [comment]
Our current approach is using mysqldump with credentials from environment variables: https://mariadb.com/kb/en/mariadb-docker-environment-variables

**Backup**
1. [pre hook](https://velero.io/docs/v1.11/backup-hooks/#pre-hooks): mysqldump into file
2. do backup
3. [post hook](https://velero.io/docs/v1.11/backup-hooks/#post-hooks): delete file

Currently we use annotations but it might also be useful to configure the hooks via yaml when defining [backups](https://velero.io/docs/v1.11/api-types/backup#definition)  or [schedules](https://velero.io/docs/v1.11/api-types/#schedule).

**Restore**
1. do restore
1. [post hook](https://velero.io/docs/v1.11/restore-hooks/#specifying-exec-restore-hooks-as-pod-annotations): load mysqldump file into database and delete file

Currently we use annotations for that but you could also configure the hooks via yaml when defining the [restore](https://velero.io/docs/v1.11/api-types/restore/#definition).

I could provide more detailed commands/ annotations later if needed.

**Comment by BourneHUST** [comment]
> annotations
Hi, I'm trying to backup mysql instance running on docker. Why did you mysqldump to file in pre hook and delete it in post hook? Is that for preventing backup corrupt or database inconsistent? Could you provide more detailed commands/ annotations when you are free? Thank you so much.😊
