### ISSUE TITLE
Activate --default-volumes-to-restic without reinstalling 

### ISSUE THREAD

**Issue by Panplumousse** [vmware-tanzu/velero#2781]
**Describe the problem/challenge you have**
Is not really a problem is a question about velero installation

**Describe the solution you'd like**
I am using velero / restic in production and would like to change the way volumes are backed up.

I would like to activate the option: --default-volumes-to-restic
without reinstalling velero, maybe by modifying the velero "deploy".

Could you tell me how can imake this modification

thank you in advance

- Velero 1.3.2

**Comment by ashish-amarnath** [comment]
@Panplumousse Thanks for asking for this feature.
Have you considered using the `--default-volumes-to-restic` flag on the `velero backup create` command to use this feature on a per backup basis instead of enabling it for all the backups?
You can find out more about this on our docs website at https://velero.io/docs/main/restic/ under the "Using the opt-out approach" section

**Comment by Panplumousse** [comment]
Hello

yes i have check that but i use schedule for backup and i dont know where put this flag option in schedule yaml

**Comment by ashish-amarnath** [comment]
Wrt schedules, the `--default-volumes-to-restic` flag was not getting passed from the `velero schedule create` command to the `BackupSpec` I have a PR https://github.com/vmware-tanzu/velero/pull/2776 that should fix that for you.

**Comment by nrb** [comment]
To answer the question about modifying the velero deployment, you can use `kubectl edit` or `kubectl patch` to modify the Velero deployment's arguments.

`velero install` currently does not modify deployed Kubernetes objects, and will eventually be deprecated in favor of a new command (`velero config`) that can.

**Comment by Panplumousse** [comment]
@nrb 
Thx for you answer , but where in deployement i have to put information and witch information , for use --default-volumes-to-restic

thx a lot

**Comment by ashish-amarnath** [comment]
@Panplumousse the `--default-volumes-to-restic` is a command-line flag to the `velero` container 
```bash
$ kubectl -n velero get deploy velero -ojson | jq .spec.template.spec.containers[0].args
[
  "server",
  "--features=",
  "--default-volumes-to-restic=true"
]

$ kubectl -n velero get deploy velero -ojson | jq .spec.template.spec.containers[0].args[2]
"--default-volumes-to-restic=true"
```

**Comment by Panplumousse** [comment]
@ashish-amarnath  thx for your feed back

from which version of velero this functionality is present I am currently in 1.3.2 
and when i try to modify deploy i receive this error :

Error: unknown flag: --default-volumes-to-restic
Usage:
  velero server [flags] ....

thx a lot

**Comment by ashish-amarnath** [comment]
This feature isn’t available in a release yet. It will be available from the upcoming 1.5 release eta end of aug 2020

________________________________

**Comment by Panplumousse** [comment]
@ashish-amarnath ok thx a lot

**Comment by ashish-amarnath** [comment]
@Panplumousse I don't think there is any further action item on this PR. I'll close this out. Feel free to reach out if you have more questions.
