### ISSUE TITLE
not able to get all required env vars for aks

### ISSUE THREAD

**Issue by harsh2202** [vmware-tanzu/velero#2783]
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = unable to get all required environment variables: the following keys do not have values: AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_SUBSCRIPTION_ID
Using HELM 3

using helm install --name velero --namespace velero --set-file credentials.secretContents.cloud=./credentials-velero --generate-name

AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
AZURE_TENANT_ID=${AZURE_TENANT_ID}
AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
AZURE_CLOUD_NAME=AzurePublicCloud
EOF

Also, decoded base64 value, the values of secret which comes out similar as above.... so it's secret is correct and even variable values are correct ....

**Comment by ashish-amarnath** [comment]
@harsh2202 Can you please confirm if you are using the latest version of the velero-plugin-for-microsfot-azure?
This is the latest release https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/releases/tag/v1.1.0
The container image for this release is available on [velero docker hub](https://hub.docker.com/layers/velero/velero-plugin-for-microsoft-azure/v1.1.0/images/sha256-adbdea5073f7598423e8a710db1178d5f1f91734b176148a50890dc498ff3d32?context=repo).

If you are not using the latest, then I'd recommend that you do that. I know we made a few fixes around credential handling for the release.

**Comment by harsh2202** [comment]
Hi Ashish,
I've been using the same release, I also pulled the images in advance.. still seeing the issue...

Thnx
H

**Comment by ashish-amarnath** [comment]
Here are a few things to try to troubleshoot and narrow down the problem:
1. Confirm that the credentials file you are using doesn't have leading or trailing whitespaces and are like 
```
AZURE_STORAGE_ACCOUNT_ACCESS_KEY=<VALUES>
AZURE_STORAGE_ACCOUNT=<VALUES>
AZURE_CLOUD_NAME=<VALUES>
AZURE_SUBSCRIPTION_ID=<VALUES>
AZURE_TENANT_ID=<VALUES>
AZURE_CLIENT_ID=<VALUES>
AZURE_CLIENT_SECRET=<VALUES>
AZURE_RESOURCE_GROUP=<VALUES>
```
without ` ` on either side of `=`

2. If that doesn't work, then can you please try to install Velero using the `velero install` command 
```bash
$ velero install --help | grep -A 18 "Examples:"
Examples:
	# velero install --provider gcp --plugins velero/velero-plugin-for-gcp:v1.0.0 --bucket mybucket --secret-file ./gcp-service-account.json

	# velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.0.0 --bucket backups --secret-file ./aws-iam-creds --backup-location-config region=us-east-2 --snapshot-location-config region=us-east-2

	# velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.0.0 --bucket backups --secret-file ./aws-iam-creds --backup-location-config region=us-east-2 --snapshot-location-config region=us-east-2 --use-restic

	# velero install --provider gcp --plugins velero/velero-plugin-for-gcp:v1.0.0 --bucket gcp-backups --secret-file ./gcp-creds.json --wait

	# velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.0.0 --bucket backups --backup-location-config region=us-west-2 --snapshot-location-config region=us-west-2 --no-secret --pod-annotations iam.amazonaws.com/role=arn:aws:iam::<AWS_ACCOUNT_ID>:role/<VELERO_ROLE_NAME>

	# velero install --provider gcp --plugins velero/velero-plugin-for-gcp:v1.0.0 --bucket gcp-backups --secret-file ./gcp-creds.json --velero-pod-cpu-request=1000m --velero-pod-cpu-limit=5000m --velero-pod-mem-request=512Mi --velero-pod-mem-limit=1024Mi

	# velero install --provider gcp --plugins velero/velero-plugin-for-gcp:v1.0.0 --bucket gcp-backups --secret-file ./gcp-creds.json --restic-pod-cpu-request=1000m --restic-pod-cpu-limit=5000m --restic-pod-mem-request=512Mi --restic-pod-mem-limit=1024Mi

	# velero install --provider azure --plugins velero/velero-plugin-for-microsoft-azure:v1.0.0 --bucket $BLOB_CONTAINER --secret-file ./credentials-velero \
	--backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID[,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID] --snapshot-location-config apiTimeout=<YOUR_TIMEOUT>[,resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID]
```

**Comment by harsh2202** [comment]
Hi Ashish,

using velero I'm able to install however, I have been looking way to install velero using "helm chart" on AKS cluster... below creds file I'm using...
$USERNAME='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
$AZURE_SUBSCRIPTION_ID='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
$AZURE_RESOURCE_GROUP='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
$AZURE_CLIENT_SECRET='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
$AZURE_TENANT_ID='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
$AZURE_CLIENT_ID='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
$AZURE_CLOUD_NAME=AzurePublicCloud

Moreover, the only way I can use is using azure service principle, can't authenticate using either storage keys or AAD options..
Also the specific feature, I 'm interested just to backup of my PVs only... Hope, I 'm able to explain the stuff I m doing...

**Comment by ashish-amarnath** [comment]
Were you able to resolve the problem? I am curious to know what the resolution was.

________________________________

**Comment by harsh2202** [comment]
Yes.. as stated above... in my azure service principle there were few special character in the password.. which were not being encoded rightly... so I changed my azure service principle password without special character and it was able to recognize all the values available in the cred file.....

**Comment by ashish-amarnath** [comment]
Thank you for clarifying.
