### ISSUE TITLE
Install v1.0.0 not successfully

### ISSUE THREAD

**Issue by leiw324** [vmware-tanzu/velero#2785]
Hello,

k8s version:
Client Version: v1.18.3
Server Version: v1.18.3

velero version:
Client:
        Version: v1.0.0
        Git commit: 72f5cadc3a865019ab9dc043d4952c9bfd5f2ecb

CentOS version:
CentOS Linux release 7.8.2003 (Core)

**What steps did you take and what happened:**
I am following this guideline: https://github.com/justmeandopensource/kubernetes/blob/master/docs/setup-velero-notes.md

But I run velero install --provider aws --bucket kubedemo --secret-file ./minio.credentials --backup-location-config region=minio,s3ForcePathStyle=true,s3Url=http://10.0.10.131:9000

Error:
Deployment/velero: attempting to create resource
An error occurred:

Error installing Velero. Use `kubectl logs deploy/velero -n velero` to check the deploy logs: Error creating resource Deployment/velero: the server could not find the requested resource

**What did you expect to happen:**
This video: https://www.youtube.com/watch?v=C9hzrexaIDA <-- 17:04 can successfully install, but I can't?

Thanks

**Comment by ashish-amarnath** [comment]
@leiw324 It is not clear to me if the `velero install` command failed or did velero fail to start?
If `velero install` command failed, then can you please share the output of the command?
If the velero pod failed to start or kept crashing, then can you please share the output of `kubectl logs deploy/velero -n velero`.

Also, looks like you are trying to install a very old version of Velero and I would suggest following the official docs from https://velero.io/docs/v1.4/contributions/minio/ to perform an evaluation install of the latest release of Velero.

**Comment by leiw324** [comment]
Hello,

Thank you for the reply, please take a look on the screenshot:
![image](https://user-images.githubusercontent.com/33790160/89709957-d2f60a00-d9b1-11ea-81cc-290e3dbcd1f0.png)
This is minio Bucket:
![image](https://user-images.githubusercontent.com/33790160/89709991-00db4e80-d9b2-11ea-9acd-0a8e7a4645fd.png)
Thanks

**Comment by leiw324** [comment]
I just tried v1.4.2, but need plugins?
![image](https://user-images.githubusercontent.com/33790160/89710076-9c6cbf00-d9b2-11ea-86b9-7fb5b2fcf67f.png)

**Comment by leiw324** [comment]
Hello,

I just tried with plugins command successfully installed v1.4.2
![image](https://user-images.githubusercontent.com/33790160/89712352-e78ece00-d9c2-11ea-9d6b-f67c984da097.png)

**Comment by ashish-amarnath** [comment]
Thank you for confirming. I am going to close this issue as resolved.

**Comment by leiw324** [comment]
Hello,

I have 1.4.2 issue: https://github.com/vmware-tanzu/velero/issues/2857

Now I back to here to try install v1.0.0, how can I fix it ?

Thanks
