### ISSUE TITLE
Skip volume backup

### ISSUE THREAD

**Issue by whitepiratebaku** [vmware-tanzu/velero#2790]
Hi dear community, I have velero 1.4.2 as I know this version of velero supports opt-in method to backup volumes` data.Which I have annotated pods so velero can take volume data backup. Now I have two storage locations.For second location I only want to take config backup but not volume data.Is there any way I can tell "velere create backup" that dont take volume data.

**Comment by ashish-amarnath** [comment]
Yes, it is possible to have Velero skip volume snapshotting.
To do that you will use the `SnapshotVolumes ` field in the BackupSpec https://pkg.go.dev/github.com/vmware-tanzu/velero@v1.4.2/pkg/apis/velero/v1?tab=doc#BackupSpec.

This can also be set to false using `--snapshot-volumes=false` option to the `velero backup create` command .

I am going to close this issue as the question has been answered. Please feel free to reach out if you have more questions. https://velero.io/community/

**Comment by whitepiratebaku** [comment]
Thank you for replying.I have already tried that but it did not help.I do not use volume snapshotting ,when I installed velero I used --use-volume-snapshots=false. but enabled --use-restic. My environment is bare metal not cloud.I just annotated pods through deployment and I was able to get volume data backups.But I have two backup locations and I want only one of them keep volume data.
