### ISSUE TITLE
Restic restores fail because restic-restore-helper unable to start

### ISSUE THREAD

**Issue by ashish-amarnath** [vmware-tanzu/velero#2801]
**What steps did you take and what happened:**

Restoring pods using volumes backed by restic fails when using `velero/velero-restic-restore-helper:main` as the image for`velero-restic-restore-helper` 

1. Take a backup using restic
2. Delete backed up namespace
3. Override the default image for velero-restic-restore-helper from `velero/velero-restic-restore-helper:latest` to `velero/velero-restic-restore-helper:main` by creating the below config map

```yaml
apiVersion: v1
data:
  image: velero/velero-restic-restore-helper:main
kind: ConfigMap
metadata:
  labels:
    velero.io/plugin-config: "true"
    velero.io/restic: RestoreItemAction
  name: restic-plugin-config
  namespace: velero
```
4. Restore from backup
The backed-up pod is restored with the init container:

The InitContainer fails with the below error.
```bash
$ kcn csi-app get po -w
NAME       READY   STATUS     RESTARTS   AGE
csi-app1   0/1     Init:0/1   0          2s
csi-app1   0/1     Init:RunContainerError   0          7s
csi-app1   0/1     Init:RunContainerError   1          8s
csi-app1   0/1     Init:CrashLoopBackOff    1          9s
^C

$ kcn csi-app describe po csi-app1 | grep -A30 "Events"

Events:
  Type     Reason                  Age                From                                Message
  ----     ------                  ----               ----                                -------
  Normal   Scheduled               94s                default-scheduler                   Successfully assigned csi-app/csi-app1 to velero-test-control-plane
  Normal   SuccessfulAttachVolume  94s                attachdetach-controller             AttachVolume.Attach succeeded for volume "pvc-a015a308-5377-44c5-992a-f76539edaae9"
  Normal   SuccessfulAttachVolume  94s                attachdetach-controller             AttachVolume.Attach succeeded for volume "pvc-456ac87b-573e-42b6-893b-998e8382ca49"
  Normal   Pulling                 90s                kubelet, velero-test-control-plane  Pulling image "velero/velero-restic-restore-helper:main"
  Normal   Pulled                  87s                kubelet, velero-test-control-plane  Successfully pulled image "velero/velero-restic-restore-helper:main"
  Normal   Created                 46s (x4 over 87s)  kubelet, velero-test-control-plane  Created container restic-wait
  Warning  Failed                  46s (x4 over 87s)  kubelet, velero-test-control-plane  Error: failed to create containerd task: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/${BIN}\": stat /${BIN}: no such file or directory": unknown
  Normal   Pulled                  46s (x3 over 87s)  kubelet, velero-test-control-plane  Container image "velero/velero-restic-restore-helper:main" already present on machine
  Warning  BackOff                 7s (x8 over 86s)   kubelet, velero-test-control-plane  Back-off restarting failed container

```

**What did you expect to happen:**
Pod should have been successfully restored.

**Anything else you would like to add:**
The reason for this regression is most likely because the `ENTRYPOINT` for the `velero-restic-restore-helper` is parameterized in the [Dockerfile](https://github.com/vmware-tanzu/velero/blob/main/Dockerfile#L68) and isn't getting resolved as expected.

This issue isn't seen with running `velero` because the velero deployment overrides the `ENTRYPOINT` by supplying the `command` in the pod/container spec.
Further, setting the `command` in the initContainer spec to `/velero-restic-restore-helper` for the intContainer solves this problem.

This problem doesn't exist when using `velero/velero-restic-restore-helper:latest` as the image for the `velero-restic-restore-helper`

**Environment:**
- Velero Image: `veleri/velero:main`
- Velero Restic Restore Helper: `velero/velero-restic-restore-helper:main`

cc @nrb @carlisia

**Comment by nrb** [comment]
> This problem doesn't exist when using velero/velero-restic-restore-helper:latest as the image for the velero-restic-restore-helper

That makes sense, because the latest image wasn't built with this iteration of the Dockerfile. It should be the v1.4.2 version.

**Comment by ashish-amarnath** [comment]
Yes, that is what I intended to say but didn't state that explicitly 😄

**Comment by badalk** [comment]
Is this still an issue with 1.6.2? I am facing this error
