### ISSUE TITLE
doc: describes how to install Velero on a vSphere environment using non-vSphere plugin

### ISSUE THREAD

**Issue by guillierf** [vmware-tanzu/velero#2818]
hello,

having a doc page that describes how to install Velero on a vSphere environment using non-vSphere plugin would be helpful. In that case, Restic needs to be installed for both vCP and CSI storage plugin

**Comment by nrb** [comment]
@guillierf To my knowledge vSphere does not use the Velero CSI plugin. It uses its own plugin based on the CNS stack, which doesn't support CSI's snapshot APIs.

I just want to clarify that language because the state of CSI support on vSphere right now is a little confusing.

**Comment by eleanor-millman** [comment]
Closing because this is just a generic install.
