### ISSUE TITLE
Checking restic repository for stale locks makes a lot of s3 api calls

### ISSUE THREAD

**Issue by tsufeki** [vmware-tanzu/velero#2820]
**Describe the problem/challenge you have**
Checking restic repository for stale locks runs `restic unlock` every [5 minutes](https://github.com/vmware-tanzu/velero/blob/c663ce15ab468b21a19336dcc38acf3280853361/pkg/controller/restic_repository_controller.go#L89) for each ResticRepository. This makes ~100 s3 api calls per hour per repository, essentially doing nothing of value.

I'm using velero for a toy project with Backblaze B2 and I want to stay in their free plan, but my 9 repositories burn through the daily api calls cap in few hours.

**Describe the solution you'd like**
Please consider making stale lock check interval configurable (something like `--restic-stale-lock-check-period=12h` option) or changing the approach to something less api calls-heavy.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
```
Client:
        Version: v1.4.2
        Git commit: 56a08a4d695d893f0863f697c2f926e27d70c0c5
Server:
        Version: v1.4.2
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"archive", BuildDate:"2020-07-16T09:08:46Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6+k3s1", GitCommit:"6f56fa1d68a5a48b8b6fdefa8eb7ead2015a4b3a", GitTreeState:"clean", BuildDate:"2020-07-16T20:46:15Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: k3s v1.18.6+k3s1
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux bullseye/sid

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by eleanor-millman** [comment]
Closing because avoiding restic-only work.

**Comment by Lyndon-Li** [comment]
Indeed, Velero checks for stale locks every 5 min, this will increase the backend storage access. Velero could make this longer, because as the design, Velero regard a lock as stale when it exists longer than 30 minutes.
However, only change Velero's behavior won't fix the problem ultimately, because Restic itself maintains the lock in a [`refreshLock` go routine](https://github.com/restic/restic/blob/master/cmd/restic/lock.go#:~:text=time.Minute-,func,-refreshLocks(wg), which recreates the lock every 5 min.
