### ISSUE TITLE
Randomly failed to execute hook with error "unable to upgrade connection: pod does not exist"

### ISSUE THREAD

**Issue by phuongatemc** [vmware-tanzu/velero#2826]
On our database application pods, we added Hook annotation with quiesce command specified.  When we backup the namespace, the pods are backup and the quiesce/unquiesce command in the Hook were executed properly.  But once awhile, we hit error below and backup failed.

 time="2020-06-15T19:34:03Z" level=error msg*="Error executing hook"* backup=velero-ppdm/mysql-cluster1-2020-06-15-12-32-31-mysql-cluster1 error="unable to upgrade connection: pod does not exist" group=v1 hookPhase=pre hookSource=annotation hookType=exec logSource="pkg/backup/item_hook_handler.go:100" name=mysql-cluster-master-0 namespace=mysql-cluster1 resource=pods

When we hit this error, the pod's status does not show any restart or any pod's error.  The network configuration should be correct because this pod has been successfully backup and only hit this error randomly.

**Environment:**
- velero/velero:v1.3.2
- Kubernetes version (use `kubectl version`): 1.17

**Comment by ashish-amarnath** [comment]
@phuongatemc Thanks for reporting this. I am not sure how to proceed with investigating this. Can you please gather more information about the cluster state and state of Velero when this happens? 
Also, when this happens do you have to retry the backup operation?

**Comment by phuongatemc** [comment]
The problem occurs at random and it works with retry (not immediately).  The backups were scheduled to run every hour on a cluster with a few dozens of pods and multiple backups (up to 5) may be executed in parallel.  We cannot capture the Velero status of when it fail.
I think this is not a problem with Velero but it seems to be the problem of kubelet component where the command was sent to be executed.  I don't remember exactly the data path but Velero podexec package library would create a connection to kubelet on the node that currently host the pod's container and that kubelet would execute the command.  The problem seems to be somewhere around the time when the podexec code trying to establish connection (and fail).  It may randomly hit some network error at this point.

**Comment by ashish-amarnath** [comment]
@phuongatemc 
I am going to close this issue. Please re-open once you have more information about when this issue occurs and how it can be reproduced.
If you have more questions please reach out to us.
