### ISSUE TITLE
Removing Dead Code

### ISSUE THREAD

**Issue by RobbieJVMW** [vmware-tanzu/velero#2841]
Running the code though linter to clean up redundant & dead code.  
First pass as part of general code clean up activities.

**Comment by ashish-amarnath** [comment]
@RobbieJVMW Thank you for reporting this.
For this to be actionable can you please provide more information:
1. What linting software did you use? How to get it? How to run it?
1. What was the output of the linter?

**Comment by nrb** [comment]
Is this a duplicate of #2397?

**Comment by carlisia** [comment]
I'll answer, yes it is! @RobbieJVMW please list which package(s) you will be cleaning up when you have a chance.

**Comment by ashish-amarnath** [comment]
should we close this issue and as this will be addressed in #2397

**Comment by RobbieJVMW** [comment]
Happy for you to map it over to #2397, I'll get to listing the package next week I'm away home this coming week. As this is my first contrib to the project I'll need some guidance following your guidelines I expect.

**Comment by carlisia** [comment]
Two people were interested in tackling #2397 so depending on how this develops it'd be best to have two separate issues. Ideally each issue would list what packages are being cleaned up.

**Comment by RobbieJVMW** [comment]
I'll start with : 

pkg/controller/
pkg/metrics/
pkg/restic/

quickly clean up dead code - mostly as a learning exercise for myself to learn how you folks like to do things / learn the processes.  Then move onto more investing bits of code. 

@carlisia do you which issue to you want me to associate with ?

**Comment by carlisia** [comment]
@RobbieJVMW I am terribly sorry I dropped the ball on this. Would you still be able to do it? If yes, please open a new issue and list these packages, thank you.

**Comment by carlisia** [comment]
Sorry, correcting myself: don't open a new issue, let's use THIS issue to track the packages you listed.

**Comment by RobbieJVMW** [comment]
no worries, yes still happy to work on this.  I won't be in a position to start until next week.
