### ISSUE TITLE
ToC documentation links not working

### ISSUE THREAD

**Issue by adamrushuk** [vmware-tanzu/velero#2846]
**What steps did you take and what happened:**

The Table of Contents links at the top of documentation pages no longer work, eg:

- https://velero.io/docs/v1.4/basic-install/
- https://velero.io/docs/v1.4/customize-installation/

Looking at the source you can see the `href` is blank, eg: `<a href="">Basic Install</a>`

**What did you expect to happen:**

The links used to work and navigate to the specified location on page.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by carlisia** [comment]
Hi @a-mccarthy, is this something you could look into fixing for us?

**Comment by nrb** [comment]
This is on the "Customizing Install" page, too.

In a call with @a-mccarthy, looks like we need to add a Hugo macro from https://gohugo.io/content-management/toc to do this for all pages.

**Comment by adamrushuk** [comment]
Thanks for fixing 👍
