### ISSUE TITLE
Backup status NEW and backup won't delete

### ISSUE THREAD

**Issue by leiw324** [vmware-tanzu/velero#2857]
Hello,

k8s version:
![image](https://user-images.githubusercontent.com/33790160/90984102-8d3a6380-e5a5-11ea-9fbe-ef77501e4800.png)
CentOS version:
![image](https://user-images.githubusercontent.com/33790160/90984111-99262580-e5a5-11ea-8642-d6a84cece057.png)
velero version:
![image](https://user-images.githubusercontent.com/33790160/90984120-a5aa7e00-e5a5-11ea-9635-9d215f32cf53.png)
Backup on NEW status:
![image](https://user-images.githubusercontent.com/33790160/90984133-bc50d500-e5a5-11ea-9c1b-9b39d069679d.png)
![image](https://user-images.githubusercontent.com/33790160/90984140-c8d52d80-e5a5-11ea-9590-301c9211f089.png)
The backup cannot delete:
![image](https://user-images.githubusercontent.com/33790160/90984148-d5598600-e5a5-11ea-9d98-bacd8a5f0ff0.png)
Thanks

**Comment by nrb** [comment]
@leiw324 From these screenshots, it doesn't look like the velero server is running within the cluster - the output of `velero version` only includes the client.

If you run `kubectl get deployment/velero -n velero`, what is the output?

Also, what about the output of `kubectl get pods -n velero`?

**Comment by leiw324** [comment]
Hello,

I am testing velero with mino, the following command which I installed velero.

velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.1.0 --bucket bucketdemo --secret-file ./minio.credentials --use-restic --backup-location-config region=minio,s3ForcePathStyle=true,s3Url=http://10.0.10.195:32000

Yes, the server has error
![image](https://user-images.githubusercontent.com/33790160/91191988-0366d380-e728-11ea-8e81-f0de21b5db36.png)
kubectl get deployment/velero -n velero
![image](https://user-images.githubusercontent.com/33790160/91192036-0eb9ff00-e728-11ea-8f8b-1b4fe434183f.png)

Thanks

**Comment by ashish-amarnath** [comment]
@leiw324 Velero is not running in your cluster and from the logs you posted, looks like velero doesn't have the correct credentials to connect to the MinIO object-store. Please refer to our docs https://velero.io/docs/v1.4/contributions/minio/ for instructions to setup Velero using MinIO as the object-store.
Because Velero is not running in your cluster, there are no controllers running to process the backup. This is the reason for the backups being stuck in the `New` phase.

I am going to close this issue. Feel free to reach out if you need further assistance.

**Comment by leiw324** [comment]
Hello,

I know what happened, because I typo aws_access_key_id when installing minio.

But now I can't backup grafana.
![image](https://user-images.githubusercontent.com/33790160/91326277-baca1b80-e7f6-11ea-8a16-b8eb726adf64.png)
![image](https://user-images.githubusercontent.com/33790160/91326440-ec42e700-e7f6-11ea-845b-ff4df21ec19a.png)
![image](https://user-images.githubusercontent.com/33790160/91326404-e1885200-e7f6-11ea-9dca-4bba3c2ad961.png)

Logs:
https://paste.ubuntu.com/p/jXQT8WcHZw/

Thanks

**Comment by ashish-amarnath** [comment]
The backup `PartiallyFailed` because of this error
```
time="2020-08-26T15:46:23Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/firstbackup error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:76" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:448" name=pvc-0aca4526-de5a-4a5a-9817-0304991f9377 namespace= persistentVolume=pvc-0aca4526-de5a-4a5a-9817-0304991f9377 resource=persistentvolumes volumeSnapshotLocation=default
```

You are probably missing the `--snapshot-location-config` flag to the `velero install` command.
Please refer to our documentation https://github.com/vmware-tanzu/velero-plugin-for-aws for the complete `velero install` command.

**Comment by leiw324** [comment]
Hello,

velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.1.0 --bucket bucketdemo --secret-file ./minio.credentials --use-restic --backup-location-config region=minio --snapshot-location-config region=minio,s3ForcePathStyle=true,s3Url=http://10.0.10.195:32000
![image](https://user-images.githubusercontent.com/33790160/91458602-4bb4fb80-e8b8-11ea-9710-3f7bc4cc11b6.png)

I re-run the backup, but the status still is NEW.
![image](https://user-images.githubusercontent.com/33790160/91458624-540d3680-e8b8-11ea-95d8-f8b4da2eda09.png)
![image](https://user-images.githubusercontent.com/33790160/91458651-5cfe0800-e8b8-11ea-83da-c0100a1cec2f.png)

Still running ?
![image](https://user-images.githubusercontent.com/33790160/91458928-a9e1de80-e8b8-11ea-8f78-76aa2667f68d.png)

Thanks

**Comment by leiw324** [comment]
2 hrs ...

**Comment by ashish-amarnath** [comment]
@leiw324 the screenshots are a little hard to read. For future reference, please provide information in text format.
Can you please share the output of
1. `kubectl get deployment/velero -n velero` 
2. `kubectl -n velero get pods`
3. `kubectl -n velero logs deploy/velero`

**Comment by leiw324** [comment]
Hello:

https://paste.ubuntu.com/p/B3RhCxThyM/

The logs showing:
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = RequestError: send request failed
caused by: Get https://bucketdemo.s3.minio.amazonaws.com/?delimiter=%2F&list-type=2&prefix=: dial tcp: lookup bucketdemo.s3.minio.amazonaws.com on 10.96.0.10:53: no such host

Here is my installation command:
velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.1.0 --bucket bucketdemo --secret-file ./minio.credentials --use-restic --backup-location-config region=minio --snapshot-location-config region=minio,s3ForcePathStyle=true,s3Url=http://10.0.10.195:32000

Thanks

**Comment by leiw324** [comment]
Hello,

Can someone help?

Thanks

**Comment by leiw324** [comment]
Anybody home?

**Comment by ashish-amarnath** [comment]
@leiw324 appreciate your patience here.
Is your MinIO service running at `bucketdemo.s3.minio.amazonaws.com` endpoint?
It probably is not. It is possible that you are running with a stale backup storage location.
You can use the output of `kubectl -n velero get backupstoragelocation -oyaml` to confirm.

Suggest `kubectl delete ns velero` and reinstalling it.

**Comment by leiw324** [comment]
Hello,

![image](https://user-images.githubusercontent.com/33790160/92299856-ca7cf900-ef88-11ea-988f-988024643e44.png)
I have restart a lot of time, can I change coredns to fix it ? if yes, can someone teach me?

Thanks

**Comment by leiw324** [comment]
Can somebody help? thanks
