### ISSUE TITLE
disaster recovery on a new cluster fails, k8s rook-ceph

### ISSUE THREAD

**Issue by haroonb** [vmware-tanzu/velero#2860]
**What steps did you take and what happened:**
I have a k8s cluster with 3 workers and some deployments and generated data. The storage is rook-ceph. 
I installed velero and created a schedule which backed up all my data every hour.
We would like to test disaster recovery so I deleted the k8s completely and created completely new vms. I setup k8s and rook-ceph in the new cluster and tried to restore from a backup.

It seems, that the restore was a success, but the statuefulsets/depoyments are stuck and won't come up.

**What did you expect to happen:**
I expected the velero to restore all the services.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
http://ix.io/2v5l
- `velero backup logs <backupname>`
https://gist.github.com/haroonb/9b8212e81b2f597015ab6483ed8d1908
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
http://ix.io/2v5n
- `velero restore logs <restorename>`
http://ix.io/2v5m

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
- `kubectl describe po acid-postgres-cluster`
http://ix.io/2v5r
- `kubectl get pv,pvc`
http://ix.io/2v5s

**Environment:**

- Velero version (use `velero version`): 
Client: Version: v1.4.2   Git commit: 56a08a4d695d893f0863f697c2f926e27d70c0c5
Server:        Version: v1.4.2
- Velero features (use `velero client config get features`): 
features: NOT SET
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Ubuntu 18.04.5 LTS - Linux devops-m1 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ashish-amarnath** [comment]
@haroonb The only errors on your restore are because some of the resources that were being restored already existed in the cluster. So that seems fine.
Looking at the output of `kubect get pv, pvc` it seems like the persistent volumes claims were restored correctly and volumes were correctly provisioned to satisfy those claims.
The velero operations are working as expected.

Can you please share: what volumesnapshotter plugin you are using?

However, errors indicate that the kubelet is trying to mount the correct volume but is running into errors. Here are a few things to troubleshoot.
1. Confirm that the `PVC` backed up are identical to the PVCs restored. You can inspect the resources in the backup by downloading the backup using `velero backup download`
1. Inspect the volume provider's logs for any errors that can prevent the kubelet from mounting the volume.

**Comment by haroonb** [comment]
Thanks for the reply @ashish-amarnath. We are using aws snapshotter in version 1.10 the exact command to install velero was

 `velero install --use-restic --provider aws --plugins velero/velero-plugin-for-aws:v1.1.0 --bucket backup --secret-file velero.cred --use-volume-snapshots=true --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://10.10.0.1:9000/`

The PVC in the backup looks fine to me.
https://gist.github.com/haroonb/81d6371ef4e61215f8313bc4d6ae4f7d

I could't find anything referring to volumes in the rook-ceph-operator logs.
http://ix.io/2vbv

This is a new cluster btw, but the same issue. Velero has no issues, if I restore a backup to the cluster I made it on, but in a new cluster seems fail. I thought maybe we had to do things different or in another order.

**Comment by ashish-amarnath** [comment]
@haroonb I am not familiar with the rook setup. But, seems like there is a rook controller, maybe running as a daemonset, that might be responsible for mounting volumes into pods. This may also be called the csi-attacher. Can you please look in that logs for any errors.

Also, searching the internet for the error I found https://tracker.ceph.com/issues/43649 
```bash
$ echo -n "pvc-f66c662d-5453-4539-8999-dfac5f36771a" |wc
       0       1      40
```

From Velero's perspective, however, the backup and restore are both working as expected. I don't see any issue there.

**Comment by dsu-igeek** [comment]
Closing this, please re-open if the problem continues.
