### ISSUE TITLE
Access to remote Velero cluster

### ISSUE THREAD

**Issue by ironknight78** [vmware-tanzu/velero#2868]
I'm having issues understanding something: Is it possible to install velero server on a remote cluster, and create backup resources remotely with the velero cli? Maybe through the KUBECONFIG env variable?

Thank you in advance.

**Comment by ashish-amarnath** [comment]
Hi @ironknight78 
You should be able to use the Velero CLI is intended to be run outside the cluster.
The CLI will use your kubeconfig either from the `KUBECONFIG` env var or using the `--kubeconfig` command line flag.

I am closing this issue as resolved as your question has been answered. Please reach out if you have more questions.
