### ISSUE TITLE
Expose controller metrics

### ISSUE THREAD

**Issue by bgagnon** [vmware-tanzu/velero#2873]
**Describe the problem/challenge you have**
We have log entries indicating that an `Backup` object references a `BackupStorageLocation` that no longer exists:

```json
{
  "controller":"gc-controller",
  "error":"error getting backup storage location: backupstoragelocation.velero.io \"default\" not found", 
  "error.file":"/go/src/github.com/vmware-tanzu/velero/pkg/controller/gc_controller.go:144", 
  "error.function":"github.com/vmware-tanzu/velero/pkg/controller.(*gcController).processQueueItem",
  "key":"runway-backup/default-20200718080037",
  "level":"error",
  "logSource":"pkg/controller/generic_controller.go:137",
  "msg":"Error in syncHandler, re-adding item to queue",
  "time":"2020-08-27T15:59:44Z"
}
```

There is no corresponding counter metric that would allow us to alert on this condition. This issue is not so much about this particular error conditions above, but a general point about the lack of metrics for internal controller behavior.

**Describe the solution you'd like**
Standard controller metrics (HTTP calls and status codes made to the K8S API) could suffice, otherwise some specialized `velero_` time series for each handled error:

- attempts
- failures

That way, a rate can be computed and a threshold can be set for alerting.

**Comment by ashish-amarnath** [comment]
@bgagnon Thanks for reporting this. We need to expose the metrics of BSL availability from the BSL controller.
