### ISSUE TITLE
Sync `Schedule` CRs into clusters

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2876]
**Describe the problem/challenge you have**
Currently, Velero doesn't sync `Schedule` custom resources across clusters, only the `Backup` custom resources that were generated by that `Schedule`. This can be somewhat surprising to users, and is also lossy in the event of a total cluster loss - the original schedule has to be recreated from scratch.

**Describe the solution you'd like**
The `Schedule` objects should be synced into clusters via the `BackupStorageLocation` so that users can observe them with `velero schedule get` on clusters other than the ones where the `Schedule` was original defined.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ashish-amarnath** [comment]
We should also sync `Restore` CRs.
see https://github.com/vmware-tanzu/velero/issues/2697 for more details

**Comment by dsu-igeek** [comment]
This is useful but we definitely need to think through the use cases before implementing this.  A common use case is to create a test cluster from a backup and this would cause it to start executing backups so we would need some controls.
