### ISSUE TITLE
Backups and restores not adopted when the velero pod is restarted

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2877]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

When the `velero` deployment pod restarts, any backup or restore action that was in progress is effectively abandoned, because the controller loops only look for `Phase: New` custom resources.

The challenge here is knowing where a backup was in its process in order to resume.

Moving to a worker pod design may help here, as the controller pods restarting will only affect grabbing work off the queue rather than the running backup/restore jobs.

**What did you expect to happen:**

The `velero` deployment restarting should not interrupt running backup and restore operations.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
Dup of https://github.com/vmware-tanzu/velero/issues/4503
