### ISSUE TITLE
Windows container

### ISSUE THREAD

**Issue by cloudcafetech** [vmware-tanzu/velero#2878]
Now a windows container becoming popular, any plan for using in windows container ?

I assume restic has already released windows binary. 

Found some nice work for windows using restic 👍 https://github.com/kmwoley/restic-windows-backup

**Comment by perithompson** [comment]
Has there been any progress on this?

**Comment by perithompson** [comment]
Are there any updates on this?

**Comment by Lyndon-Li** [comment]
dup with #4266
