### ISSUE TITLE
Velero deployment in IBM Kubernetes service

### ISSUE THREAD

**Issue by venkatmarella** [vmware-tanzu/velero#2885]
Deployed Velero in IBM IKS cluster (IKS version 1.16.14_1544) by following https://velero.io/docs/v1.4/contributions/ibm-config/

kc get pods -n velero
NAME                      READY   STATUS             RESTARTS   AGE
velero-7c6d9bb58d-bgfm9   0/1     CrashLoopBackOff   1408       5d1h

kc logs velero-7c6d9bb58d-bgfm9 -n velero
time="2020-09-01T15:21:43Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:177"
time="2020-09-01T15:21:43Z" level=info msg="Starting Velero server v1.4.2 (56a08a4d695d893f0863f697c2f926e27d70c0c5)" logSource="pkg/cmd/server/server.go:179"
time="2020-09-01T15:21:43Z" level=info msg="1 feature flags enabled []" logSource="pkg/cmd/server/server.go:181"
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-remap-version
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-pvc-node-selector
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/cluster-role-bindings
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-preserve-fields
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2020-09-01T15:21:44Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2020-09-01T15:21:44Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:361" namespace=velero
time="2020-09-01T15:21:44Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:367" namespace=velero
time="2020-09-01T15:21:46Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:396"
time="2020-09-01T15:21:46Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:430"
time="2020-09-01T15:21:46Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:437"
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = SerializationError: failed to unmarshal error message
	status code: 404, request id: , host id:
caused by: UnmarshalError: failed to unmarshal error message
	00000000  3c 21 44 4f 43 54 59 50  45 20 68 74 6d 6c 3e 0a  |<!DOCTYPE html>.|
00000010  3c 68 74 6d 6c 20 6c 61  6e 67 3d 22 65 6e 22 3e  |<html lang="en">|
00000020  0a 3c 68 65 61 64 3e 0a  3c 6d 65 74 61 20 63 68  |.<head>.<meta ch|
00000030  61 72 73 65 74 3d 22 75  74 66 2d 38 22 3e 0a 3c  |arset="utf-8">.<|
00000040  74 69 74 6c 65 3e 45 72  72 6f 72 3c 2f 74 69 74  |title>Error</tit|
00000050  6c 65 3e 0a 3c 2f 68 65  61 64 3e 0a 3c 62 6f 64  |le>.</head>.<bod|
00000060  79 3e 0a 3c 70 72 65 3e  43 61 6e 6e 6f 74 20 47  |y>.<pre>Cannot G|
00000070  45 54 20 2f 76 32 2f 65  6e 64 70 6f 69 6e 74 73  |ET /v2/endpoints|
00000080  2f 6b 69 73 2d 63 6c 75  73 74 65 72 2d 62 61 63  |/kis-cluster-bac|
00000090  6b 75 70 3c 2f 70 72 65  3e 0a 3c 2f 62 6f 64 79  |kup</pre>.</body|
000000a0  3e 0a 3c 2f 68 74 6d 6c  3e 0a                    |>.</html>.|

caused by: expected element type <Error> but have <html>

**Environment:**
$ velero version
Client:
	Version: v1.4.2
	Git commit: -
<error getting server version: timed out waiting for server status request to be processed>

Please let me know if you need any more details.

**Comment by nrb** [comment]
@venkatmarella Are you able to reach the bucket provided as the `s3Url` manually with `curl` or some other utility using the same credentials given to Velero?

Also, can you provide the output of `velero get storage-location default -o yaml`?

**Comment by venkatmarella** [comment]
$ velero get backup-locations -o yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  creationTimestamp: "2020-08-24T15:28:21Z"
  generation: 1
  labels:
    component: velero
  name: default
  namespace: velero
  resourceVersion: "72938519"
  selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/default
  uid: 74cd2d91-ac55-4f22-90ce-ca716ba46c92
spec:
  config:
    region: us-geo
    s3ForcePathStyle: "true"
    s3Url: https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints
  objectStorage:
    bucket: kis-cluster-backup
  provider: aws
status: {}

**Comment by venkatmarella** [comment]
$ curl -v https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints
*   Trying 169.60.148.30...
* TCP_NODELAY set
* Connected to control.cloud-object-storage.cloud.ibm.com (169.60.148.30) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=ny; L=Armonk; O=INTERNATIONAL BUSINESS MACHINES CORPORATION; OU=IBM Cloud Object Storage; CN=control.cloud-object-storage.cloud.ibm.com
*  start date: Oct  9 00:00:00 2019 GMT
*  expire date: Oct 13 12:00:00 2021 GMT
*  subjectAltName: host "control.cloud-object-storage.cloud.ibm.com" matched cert's "control.cloud-object-storage.cloud.ibm.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /v2/endpoints HTTP/1.1
> Host: control.cloud-object-storage.cloud.ibm.com
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 01 Sep 2020 19:44:13 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 7140
< Connection: keep-alive
< X-Request-Id: 97ca530e-1724-4325-a902-c8d3892d767e
< X-Content-Type-Options: nosniff
< X-XXS-Protection: 1; mode=block
< ETag: W/"1be4-L51O+WM6lU1guAIuZ76t7H4wCW8"
<
{"identity-endpoints":{"iam-token":"iam.cloud.ibm.com","iam-policy":"iampap.cloud.ibm.com"},"service-endpoints":{"cross-region":{"us":{"public":{"us-geo":"s3.us.cloud-object-storage.appdomain.cloud","Dallas":"s3.dal.us.cloud-object-storage.appdomain.cloud","Washington":"s3.wdc.us.cloud-object-storage.appdomain.cloud","San Jose":"s3.sjc.us.cloud-object-storage.appdomain.cloud"},"private":{"us-geo":"s3.private.us.cloud-object-storage.appdomain.cloud","Dallas":"s3.private.dal.us.cloud-object-storage.appdomain.cloud","Washington":"s3.private.wdc.us.cloud-object-storage.appdomain.cloud","San Jose":"s3.private.sjc.us.cloud-object-storage.appdomain.cloud"},"direct":{"us-geo":"s3.direct.us.cloud-object-storage.appdomain.cloud","Dallas":"s3.direct.dal.us.cloud-object-storage.appdomain.cloud","Washington":"s3.direct.wdc.us.cloud-object-storage.appdomain.cloud","San Jose":"s3.direct.sjc.us.cloud-object-storage.appdomain.cloud"}},"eu":{"public":{"eu-geo":"s3.eu.cloud-object-storage.appdomain.cloud","Amsterdam":"s3.ams.eu.cloud-object-storage.appdomain.cloud","Frankfurt":"s3.fra.eu.cloud-object-storage.appdomain.cloud","Milan":"s3.mil.eu.cloud-object-storage.appdomain.cloud"},"private":{"eu-geo":"s3.private.eu.cloud-object-storage.appdomain.cloud","Amsterdam":"s3.private.ams.eu.cloud-object-storage.appdomain.cloud","Frankfurt":"s3.private.fra.eu.cloud-object-storage.appdomain.cloud","Milan":"s3.private.mil.eu.cloud-object-storage.appdomain.cloud"},"direct":{"eu-geo":"s3.direct.eu.cloud-object-storage.appdomain.cloud","Amsterdam":"s3.direct.ams.eu.cloud-object-storage.appdomain.cloud","Frankfurt":"s3.direct.fra.eu.cloud-object-storage.appdomain.cloud","Milan":"s3.direct.mil.eu.cloud-object-storage.appdomain.cloud"}},"ap":{"public":{"ap-geo":"s3.ap.cloud-object-storage.appdomain.cloud","Tokyo":"s3.tok.ap.cloud-object-storage.appdomain.cloud","Seoul":"s3.seo.ap.cloud-object-storage.appdomain.cloud","Hong Kong":"s3.hkg.ap.cloud-object-storage.appdomain.cloud"},"private":{"ap-geo":"s3.private.ap.cloud-object-storage.appdomain.cloud","Tokyo":"s3.private.tok.ap.cloud-object-storage.appdomain.cloud","Seoul":"s3.private.seo.ap.cloud-object-storage.appdomain.cloud","Hong Kong":"s3.private.hkg.ap.cloud-object-storage.appdomain.cloud"},"direct":{"ap-geo":"s3.direct.ap.cloud-object-storage.appdomain.cloud","Tokyo":"s3.direct.tok.ap.cloud-object-storage.appdomain.cloud","Seoul":"s3.direct.seo.ap.cloud-object-storage.appdomain.cloud","Hong Kong":"s3.direct.hkg.ap.cloud-object-storage.appdomain.cloud"}}},"regional":{"us-south":{"public":{"us-south":"s3.us-south.cloud-object-storage.appdomain.cloud"},"private":{"us-south":"s3.private.us-south.cloud-object-storage.appdomain.cloud"},"direct":{"us-south":"s3.direct.us-south.cloud-object-storage.appdomain.cloud"}},"us-east":{"public":{"us-east":"s3.us-east.cloud-object-storage.appdomain.cloud"},"private":{"us-east":"s3.private.us-east.cloud-object-storage.appdomain.cloud"},"direct":{"us-east":"s3.direct.us-east.cloud-object-storage.appdomain.cloud"}},"eu-gb":{"public":{"eu-gb":"s3.eu-gb.cloud-object-storage.appdomain.cloud"},"private":{"eu-gb":"s3.private.eu-gb.cloud-object-storage.appdomain.cloud"},"direct":{"eu-gb":"s3.direct.eu-gb.cloud-object-storage.appdomain.cloud"}},"eu-de":{"public":{"eu-de":"s3.eu-de.cloud-object-storage.appdomain.cloud"},"private":{"eu-de":"s3.private.eu-de.cloud-object-storage.appdomain.cloud"},"direct":{"eu-de":"s3.direct.eu-de.cloud-object-storage.appdomain.cloud"}},"jp-tok":{"public":{"jp-tok":"s3.jp-tok.cloud-object-storage.appdomain.cloud"},"private":{"jp-tok":"s3.private.jp-tok.cloud-object-storage.appdomain.cloud"},"direct":{"jp-tok":"s3.direct.jp-tok.cloud-object-storage.appdomain.cloud"}},"au-syd":{"public":{"au-syd":"s3.au-syd.cloud-object-storage.appdomain.cloud"},"private":{"au-syd":"s3.private.au-syd.cloud-object-storage.appdomain.cloud"},"direct":{"au-syd":"s3.direct.au-syd.cloud-object-storage.appdomain.cloud"}}},"single-site":{"ams03":{"public":{"ams03":"s3.ams03.cloud-object-storage.appdomain.cloud"},"private":{"ams03":"s3.private.ams03.cloud-object-storage.ap* Connection #0 to host control.cloud-object-storage.cloud.ibm.com left intact
pdomain.cloud"},"direct":{"ams03":"s3.direct.ams03.cloud-object-storage.appdomain.cloud"}},"che01":{"public":{"che01":"s3.che01.cloud-object-storage.appdomain.cloud"},"private":{"che01":"s3.private.che01.cloud-object-storage.appdomain.cloud"},"direct":{"che01":"s3.direct.che01.cloud-object-storage.appdomain.cloud"}},"mel01":{"public":{"mel01":"s3.mel01.cloud-object-storage.appdomain.cloud"},"private":{"mel01":"s3.private.mel01.cloud-object-storage.appdomain.cloud"},"direct":{"mel01":"s3.direct.mel01.cloud-object-storage.appdomain.cloud"}},"osl01":{"public":{"osl01":"s3.osl01.cloud-object-storage.appdomain.cloud"},"private":{"osl01":"s3.private.osl01.cloud-object-storage.appdomain.cloud"},"direct":{"osl01":"s3.direct.osl01.cloud-object-storage.appdomain.cloud"}},"tor01":{"public":{"tor01":"s3.tor01.cloud-object-storage.appdomain.cloud"},"private":{"tor01":"s3.private.tor01.cloud-object-storage.appdomain.cloud"},"direct":{"tor01":"s3.direct.tor01.cloud-object-storage.appdomain.cloud"}},"sao01":{"public":{"sao01":"s3.sao01.cloud-object-storage.appdomain.cloud"},"private":{"sao01":"s3.private.sao01.cloud-object-storage.appdomain.cloud"},"direct":{"sao01":"s3.direct.sao01.cloud-object-storage.appdomain.cloud"}},"seo01":{"public":{"seo01":"s3.seo01.cloud-object-storage.appdomain.cloud"},"private":{"seo01":"s3.private.seo01.cloud-object-storage.appdomain.cloud"},"direct":{"seo01":"s3.direct.seo01.cloud-object-storage.appdomain.cloud"}},"mon01":{"public":{"mon01":"s3.mon01.cloud-object-storage.appdomain.cloud"},"private":{"mon01":"s3.private.mon01.cloud-object-storage.appdomain.cloud"},"direct":{"mon01":"s3.direct.mon01.cloud-object-storage.appdomain.cloud"}},"mex01":{"public":{"mex01":"s3.mex01.cloud-object-storage.appdomain.cloud"},"private":{"mex01":"s3.private.mex01.cloud-object-storage.appdomain.cloud"},"direct":{"mex01":"s3.direct.mex01.cloud-object-storage.appdomain.cloud"}},"sjc04":{"public":{"sjc04":"s3.sjc04.cloud-object-storage.appdomain.cloud"},"private":{"sjc04":"s3.private.sjc04.cloud-object-storage.appdomain.cloud"},"direct":{"sjc04":"s3.direct.sjc04.cloud-object-storage.appdomain.cloud"}},"mil01":{"public":{"mil01":"s3.mil01.cloud-object-storage.appdomain.cloud"},"private":{"mil01":"s3.private.mil01.cloud-object-storage.appdomain.cloud"},"direct":{"mil01":"s3.direct.mil01.cloud-object-storage.appdomain.cloud"}},"hkg02":{"public":{"hkg02":"s3.hkg02.cloud-object-storage.appdomain.cloud"},"private":{"hkg02":"s3.private.hkg02.cloud-object-storage.appdomain.cloud"},"direct":{"hkg02":"s3.direct.hkg02.cloud-object-storage.appdomain.cloud"}},"par01":{"public":{"par01":"s3.par01.cloud-object-storage.appdomain.cloud"},"private":{"par01":"s3.private.par01.cloud-object-storage.appdomain.cloud"},"direct":{"par01":"s3.direct.par01.cloud-object-storage.appdomain.cloud"}},"sng01":{"public":{"sng01":"s3.sng01.cloud-object-storage.appdomain.cloud"},"private":{"sng01":"s3.private.sng01.cloud-object-storage.appdomain.cloud"},"direct":{"sng01":"s3.direct.sng01.cloud-object-storage.appdomain.cloud"}}}}}* Closing connection 0

**Comment by tnakajo** [comment]
@nrb Can you help us further?

**Comment by tnakajo** [comment]
@venkatmarella Can you put screenshots to show the bucket name and the object storage endpoint are correct to @nrb and Verlero team?
```
/usr/local/bin/velero install \
--provider aws \
--bucket kis-cluster-backup \
--secret-file ./credentials-velero \
--use-volume-snapshots=false \
--plugins velero/velero-plugin-for-aws:v1.1.0 \
--backup-location-config region=us-geo,s3ForcePathStyle="true",s3Url=https://s3.us.cloud-object-storage.appdomain.cloud
```

**Comment by venkatmarella** [comment]
<img width="1434" alt="Screen Shot 2020-09-04 at 7 27 43 AM" src="https://user-images.githubusercontent.com/31638107/92239782-2cead200-ee81-11ea-8e97-08cd2d93c910.png">
<img width="1436" alt="Screen Shot 2020-09-04 at 7 28 28 AM" src="https://user-images.githubusercontent.com/31638107/92239815-37a56700-ee81-11ea-9008-46aa7e65dd6b.png">
![image](https://user-images.githubusercontent.com/31638107/92240040-94088680-ee81-11ea-84d2-cfffb85bb8f9.png)

**Comment by venkatmarella** [comment]
<img width="1439" alt="Screen Shot 2020-09-04 at 7 42 50 AM" src="https://user-images.githubusercontent.com/31638107/92240542-65d77680-ee82-11ea-8e88-c091d8dcd026.png">
<img width="1440" alt="Screen Shot 2020-09-04 at 7 43 15 AM" src="https://user-images.githubusercontent.com/31638107/92240575-74259280-ee82-11ea-902e-4670e524ecfc.png">

**Comment by venkatmarella** [comment]
@nrb, could you please help us here?

**Comment by venkatmarella** [comment]
Identified the issue, the binary installed with brew is causing problem, downloaded from git repo and working as expected.
