### ISSUE TITLE
？Do we want to continue halting when trying to disable a controller that doesn't exist in the disableable list

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#2889]
When a user passes in a configuration setting to disable a controller, and that setting does not match the controller name of one of the disableable controllers, the server logs with a `Fatalf`.

The question is: do we want to continue this behavior? Or is this too austere?

Discussion thread:
https://github.com/vmware-tanzu/velero/pull/2838#discussion_r480284830

**Comment by nrb** [comment]
I vote yes - the user should be notified that they are trying to disable something that doesn't exist.

If we don't halt, then we end up running a controller that they didn't want, because it wasn't matched against the incorrectly-entered name.
