### ISSUE TITLE
change the args on deployments before restoring by the velero

### ISSUE THREAD

**Issue by mushdavtyan** [vmware-tanzu/velero#2893]
I want to change some arguments on deployments or change NFS server parameters on PV before restoring.

- :+1: for "The project would be better with this feature added"

**Comment by nrb** [comment]
@mushdavtyan This sounds like you're trying to alter resources on restore, which is covered by https://github.com/vmware-tanzu/velero/issues/474. I'm going to close this issue as a duplicate, but please feel free to add your use case a comment.
