### ISSUE TITLE
Release 1.4.2 seems to use apiVersion extensions/v1beta1 for the deployment of velero in kubernetes 1.15.11

### ISSUE THREAD

**Issue by bryantidd** [vmware-tanzu/velero#2897]
**What steps did you take and what happened:**
velero install

**What did you expect to happen:**
deployment yaml would have apiVersion apps/v1

**The output of the following commands will help us better understand what's going on**:
- `kubectl edit deployment/velero -n velero`

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-08-04T18:10:45Z"
  generation: 2
  labels:
    component: velero
  name: velero
  namespace: velero
  resourceVersion: "15409609"
  selfLink: /apis/extensions/v1beta1/namespaces/velero/deployments/velero
  uid: d0cfefb0-d67d-11ea-aeec-005056a8e177

**Anything else you would like to add:**
Concern about running in 1.16 and greater kubernetes 

**Environment:**

- Velero version (use `velero version`): 1.4.2
- Velero features (use `velero client config get features`):  
- Kubernetes version (use `kubectl version`): 1.15.11
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: On-premise physical cluster
- OS (e.g. from `/etc/os-release`): RHEL 8

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by jenting** [comment]
That's because the deployment resource belongs to both API group `apps` and `extensions` at Kubernetes 1.15.
The kubectl default choose the `extensions` API group (I think it's controlled by kube-apiserver), you could try
```
kubectl get deploy.apps
or
kubectl get deploy.v1.apps
```
to get `apps/v1` API group.

**Comment by nrb** [comment]
As Jenting mentioned, this is controlled by the Kubernetes API server. Velero itself installs the v1 apps version of a Deployment, but v1.15 of Kubernetes defaults to the `extensions` API group.

If you need to retrieve the Deployment from the `apps/v1` group, you can get it by doing the following:

```
mbp16 in /Users/nrb/go/src/github.com/vmware-tanzu/velero (git) main
% k get deploy.apps/velero -n velero -o yaml | head -n 5
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"

mbp16 in /Users/nrb/go/src/github.com/vmware-tanzu/velero (git) main
% k get nodes
NAME                 STATUS   ROLES    AGE   VERSION
kind-control-plane   Ready    master   89s   v1.15.11
```
