### ISSUE TITLE
MINIO/Velero: The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by dk-do** [vmware-tanzu/velero#2902]
**What steps did you take and what happened:**
We installed Velero and attached it to MinIO.
We started a backup and it finished with:

```
Phase:  Completed

Errors:    0
Warnings:  1
```

The warning is:
```
Resource List:  <error getting backup resource list: request failed: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>backups/30min-20200904140032/30min-20200904140032-resource-list.json.gz</Key><BucketName>qs-velero</BucketName><Resource>/qs-velero/backups/30min-20200904140032/30min-20200904140032-resource-list.json.gz</Resource><RequestId>16319AF803FB57E5</RequestId><HostId>4a766349-4385-489b-a79f-ef4dfa4dedde</HostId></Error>>
```

**What did you expect to happen:**
We don't know why this happens. In prior tests we recognized that this error occurs if the password contains several special letters. But the password here only contains numbers, small and capital letters. 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```
Name:         30min-20200904140032
Namespace:    velero
Labels:       velero.io/schedule-name=30min
              velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.18.3
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18

Phase:  Completed

Errors:    0
Warnings:  1

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2020-09-04 16:00:32 +0200 CEST
Completed:  2020-09-04 16:06:48 +0200 CEST

Expiration:  2020-10-04 16:00:32 +0200 CEST

Total items to be backed up:  4281
Items backed up:              4281

Resource List:  <error getting backup resource list: request failed: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>backups/30min-20200904140032/30min-20200904140032-resource-list.json.gz</Key><BucketName>qs-velero</BucketName><Resource>/qs-velero/backups/30min-20200904140032/30min-20200904140032-resource-list.json.gz</Resource><RequestId>16319B55F20B2799</RequestId><HostId>4a766349-4385-489b-a79f-ef4dfa4dedde</HostId></Error>>

Velero-Native Snapshots: <none included>

Restic Backups:
  Completed:
    default/acid-postgres-cluster-0: pgdata
    default/acid-postgres-cluster-1: pgdata
    default/acid-postgres-cluster-2: pgdata
    default/elasticsearch-master-0: elasticsearch-master
    default/elasticsearch-master-1: elasticsearch-master
    default/elasticsearch-master-2: elasticsearch-master
    default/etcd-0: data
    default/etcd-1: data
    default/etcd-2: data
    default/mongodb-mongodb-replicaset-0: datadir
    default/mongodb-mongodb-replicaset-1: datadir
    default/mongodb-mongodb-replicaset-2: datadir
    default/storageservicev2-59b454db74-p29dt: storageservice
    kafka/kafka-cluster-kafka-0: data
    kafka/kafka-cluster-kafka-1: data
    kafka/kafka-cluster-kafka-2: data
    kafka/kafka-cluster-zookeeper-0: data
    kafka/kafka-cluster-zookeeper-1: data
    kafka/kafka-cluster-zookeeper-2: data
    monitoring/grafana-core-845fdb884c-ksdv8: grafana-persistent-storage
    monitoring/prometheus-core-7cb58fb97b-tnxbh: data
    redis/rfr-redisfailover-persistent-0: redisfailover-persistent-data
    redis/rfr-redisfailover-persistent-1: redisfailover-persistent-data
    redis/rfr-redisfailover-persistent-2: redisfailover-persistent-data

```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
```
Client:
        Version: v1.4.2
        Git commit: 56a08a4d695d893f0863f697c2f926e27d70c0c5
Server:
        Version: v1.4.2
```

- Velero features (use `velero client config get features`): 

`features: <NOT SET>`

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: none - baremetal/upstream
- Cloud provider or hardware configuration: Private Cloud
- OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by dsu-igeek** [comment]
In order to get the resource list, we generate a presigned S3 URL in the Velero server and return that to the client, which then downloads directly from the Minio S3 server.  I tried with our Minio install and verified that this works, at least in our configuration.  There could be some issue with how the URL is being generated or perhaps the Minio configuration is preventing you from downloading directly.

You mention that you tried various passwords.  Have any of the passwords you've used worked for this?

Let's try verifying that you can create and download a presigned URL from your Minio server.

You can generate a presigned URL using the AWS CLI.  Instructions are here - https://docs.aws.amazon.com/cli/latest/reference/s3/presign.html  You'll need to have the AWS CLI configured to work with your Minio server - https://docs.minio.io/docs/aws-cli-with-minio.html

The S3 object that the velero backup describe command is trying to download is the resource-list json.  This will be named /<bucket name>/backups/<backup-name>/<backup-name>-resource-list.json.gz

Please see if you can generate a presigned URL with the AWS S3 client and use it.  If that works we can debug further on the Velero side.  If it doesn't, there's an issue with the Minio server.

**Comment by nrb** [comment]
@dk-do Please also verify that your clock settings are in sync.

**Comment by carlisia** [comment]
I'm closing this issue. @dk-do there are some suggestions for you to try (above) but feel free to reopen if you are still having problems.
