### ISSUE TITLE
velero 1.5.0 release tag missing

### ISSUE THREAD

**Issue by chenrui333** [vmware-tanzu/velero#2903]
👋  It looks like velero 1.5.0 release was deleted some time ago. Raise an issue in here for confirmation. Thanks!

Kind of relates to https://github.com/Homebrew/homebrew-core/pull/60300

**Comment by nrb** [comment]
@chenrui333 v1.5.0 is not actually released yet, and the tag was created by mistake. It should be out tomorrow.

**Comment by chenrui333** [comment]
Sounds good, thank you!
