### ISSUE TITLE
PV related snapshot data is not deleted from restic folder when deleting backup

### ISSUE THREAD

**Issue by luwang-vmware** [vmware-tanzu/velero#2904]
**What steps did you take and what happened:**
I am using velero1.4.2 + restic for backup/restore statefulset workload in vsphere env(using VCP)
velero backup and velero restore work as expected. When I am deleting velero backup ***,  the files are deleted in backup folder in minio, but the related folder of  PV snapshot data still exist in restic folder. I am not sure whether it is by design.

1. before velero backup delete, check on the minio.
```
root@localhost:/minio_data/velero/restic# ls
velero-1t-2
root@localhost:/minio_data/velero/restic# ls /minio_data/velero/backups/
1t  1t-new  velero-1t-2
```
2. delete backup
```
root@5b4128c429eb:~# velero backup delete velero-1t-2 --confirm
Request to delete backup "velero-1t-2" submitted successfully.
The backup will be fully deleted after all associated data (disk snapshots, backup files, restores) are removed.
```
3. check minio again.
```
root@localhost:/minio_data/velero/restic# ls /minio_data/velero/backups/
1t  1t-new
root@localhost:/minio_data/velero/restic# ls 
velero-1t-2
```

**What did you expect to happen:**
I regard the related files are deleted from restic folder as well. Not sure whether my expectation is supported in the velero design.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by nrb** [comment]
@luwang-vmware There is a restic repository management controller that prunes the restic repositories at regular intervals (default, weekly). The prune operation goes through and removes un-used data.

It is not run often because it requires a lock on the repositories, which blocks backup operations.
