### ISSUE TITLE
How to Integrate velero with Azure Stack

### ISSUE THREAD

**Issue by sawansharma005** [vmware-tanzu/velero#2909]
**Describe the problem/challenge you have**
I am trying to integrate velero with azure stack.

**Describe the solution you'd like**
I couldn't find it on google, if we can integrate the velero with azure stack. If it is possible, could you share the link of how we can do this.

I tried to use the same configuration as we do for azure, but it's giving us an error of subscription not found. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version: 1.4.2
- Kubernetes version (use `kubectl version`): aks engine setup cluster(1.15.9)
- Kubernetes installer & version:
- Cloud provider or hardware configuration: azure stack
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by cshaw5** [comment]
👍

**Comment by ashish-amarnath** [comment]
@sawansharma005 This is not something that the Velero team has had a chance to try azure stack yet.
Looks like @cshaw5 was able to make some progress. The error there shows that the `velero-plugin-for-microsoft-azure` is unable to connect to the object-store. Is there a possibility that your cloud-credentials secret are incorrect?

**Comment by sawansharma005** [comment]
Hi Ashish,

We already tried what @cshaw5 has pasted, and got the same error.

`An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = unable to parse azure cloud name environment variable: autorest/azure: There is no cloud environment matching the name "AZURESTACK"`

With **AzurePublicCloud**, velero couldn't find the subscription in azure(which is actually ok). So I wanted to know, like, is there any way by which we can point to azure stack to hold the velero backup, any plugin or something?

**Comment by dsu-igeek** [comment]
Looks like this will need a code change to fix and there may be other issues beyond what I've identified so far.  I opened a PR against the Azure plugin to track this.  https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/issues/78

For the moment, I recommend using the Azure public cloud object store.

**Comment by bernardyoung** [comment]
The same problem occurred when docking with AzureChinaCloud
Environment:
Velero version: 1.5.2
Azure plugin: 1.1.1

**Comment by dsu-igeek** [comment]
@bernardyoung That sounds like a different root cause.  You're not using Azure Stack, correct?  AzureChinaCloud should work so we can investigate that but need some more info.  Please open a new PR and add log files.
