### ISSUE TITLE
The latest backup and schedule are not equal：schedule.status.lastBackup and backup.metadata.creationTimestamp

### ISSUE THREAD

**Issue by Cweiping** [vmware-tanzu/velero#2912]
The latest backup and schedule are not equal：

schedule.status.lastBackup and backup.metadata.creationTimestamp

I want to use this method to confirm that the current backup is up to date.

**Comment by nrb** [comment]
I see why this is happening, and it makes sense, though I'm not 100% sure how to fix it at the moment.

The Schedule controller sets the `LastBackup` value when it submits the request for a Backup to be made. The Backup's `CreationTimestamp` is populated by the Kubernetes API server when it receives the request over the network. Thus, there is going to be some skew.

I think we need to address the goal of confirming that the latest backup from a schedule is up-to-date, though I don't know that it will necessarily be tied directly to these fields.

**Comment by Cweiping** [comment]
> I see why this is happening, and it makes sense, though I'm not 100% sure how to fix it at the moment.
> 
> The Schedule controller sets the `LastBackup` value when it submits the request for a Backup to be made. The Backup's `CreationTimestamp` is populated by the Kubernetes API server when it receives the request over the network. Thus, there is going to be some skew.
> 
> I think we need to address the goal of confirming that the latest backup from a schedule is up-to-date, though I don't know that it will necessarily be tied directly to these fields.

Thank you for your reply. Yes, as I know. I think it's reasonable
