### ISSUE TITLE
Does not work with missing but valid kubeconfig

### ISSUE THREAD

**Issue by bryanlarsen** [vmware-tanzu/velero#292]
If your kubernetes is configured so that you can access it without a kubeconfig, ark throws the error: "An error occurred: invalid configuration: no configuration has been provided"

"kubectl config view" gives

```
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

In this scenario, kubectl accesses the kubernetes API on http://localhost:8080/ but ark doesn't.

It's easy to fix by populating ~/.kube/config.  

I'd be satisfied if there was a more helpful error message.   In my case I was looking for some sort of missing ark specific configuration since I had ruled out kubeconfig since kubectl was working fine.

Version: v0.6.0
Git commit: v0.6.0
Git tree state: clean

**Comment by ncdc** [comment]
Hi @bryanlarsen, thanks for reporting this. I've been in the weeds of the code that produces this error before, so we should be able to fix it so you can use Ark without a kubeconfig file.

**Comment by ncdc** [comment]
Actually, that behavior (defaulting to localhost:8080) is currently marked as deprecated in the client-go code. What if we did this:

1. If you've specified a kubeconfig, Ark makes sure it exists. If it doesn't exist, print an error that it's not found
1. If you haven't specified a kubeconfig, check if ~/.kube/config exists, and print an error if it doesn't

Would that work?

**Comment by bryanlarsen** [comment]
That's acceptable to me.   A better error message would have helped me a lot -- once I actually knew what was going on it was trivial to fix.

**Comment by ncdc** [comment]
Ok thanks, we'll plan to do this. Or would you be interested in contributing a PR? 😄

**Comment by ncdc** [comment]
> If you haven't specified a kubeconfig, check if ~/.kube/config exists, and print an error if it doesn't

Upon further reflection, this logic is only valid when running the ark cli. The server needs to be able to function even if --kubeconfig, $KUBECONFIG, and ~/.kube/config are all empty/missing (it uses the in-cluster configuration). So we'll need to make sure we don't break the server with a change here.

**Comment by ncdc** [comment]
There is work ongoing to remove the `localhost:8080` defaulting (https://github.com/kubernetes/kubernetes/pull/62469). We can still provide a better error message here.
