### ISSUE TITLE
Be more verbose about PV deletion timeout

### ISSUE THREAD

**Issue by danielkucera** [vmware-tanzu/velero#2923]
I presume following line should have higher loglevel to be visible even without debug logging as it is final state:
https://github.com/vmware-tanzu/velero/blob/718a94ad0565731780c904d27d09f27936f6b7d9/pkg/restore/restore.go#L616

See also https://github.com/vmware-tanzu/velero-plugin-for-vsphere/issues/167

**Comment by kannanvr** [comment]
Please assign it to me. I am interested to contribute

**Comment by MadhavJivrajani** [comment]
Hi, 

Would a logging level of `Info` be sufficient for this?

**Comment by MadhavJivrajani** [comment]
Draft PR: https://github.com/vmware-tanzu/velero/pull/3289
