### ISSUE TITLE
Change Image Name while Restoring Deployments In Target Cluster

### ISSUE THREAD

**Issue by rajivml** [vmware-tanzu/velero#2927]
HI,

I have a use case where I have migrate an pretty big kubernetes cluster from GKE to AKS. 

The thing am not able to figure out is, on GCP we are using google container registry and all the GKE deployments points to the images located in google cloud registry.

Now before the restore, I will sync all the docker images present under GCS to Azure container registry. But at the time of restoring the backup onto AKS cluster , I have to change the image Names under deployments to point to Azure container registry instead of google container registry.

Any idea how can i achieve this ?

**Comment by zubron** [comment]
Hi :wave: One option is to create your own [`RestoreItemAction` plugin](https://velero.io/docs/v1.5/custom-plugins/) which allows you to execute your own logic on resources as they are being restored. In this case you could modify the container registry being used on each pod/container before it is restored in your new cluster. We also have an [example repo](https://github.com/vmware-tanzu/velero-plugin-example) which shows you how to create your own plugins.

We have had some other requests though for a more general purpose way of how to easily edit resources on restore but we don't have that built into the project.
