### ISSUE TITLE
Missing namespace in suggest velero commands

### ISSUE THREAD

**Issue by bclermont** [vmware-tanzu/velero#2934]
Velero 1.4.2

```shell
velero backup create test --from-schedule=myschedule -n kube-system
Creating backup from schedule, all other filters are ignored.
Backup request "test" submitted successfully.
Run `velero backup describe test` or `velero backup logs test` for more details.
```

the command suggested is invalid as the namespace isn't specified:

```shell
velero backup describe test
An error occurred: backups.velero.io "test" not found
```

it should contains `-n $namespace`

**Comment by nrb** [comment]
@bclermont You can fix this with `velero client config set namespace kube-system`, which remove the need for `-n` on `backup create`, too.

Generally, `-n` is not needed because the vast majority of our users use the default.
