### ISSUE TITLE
Velero fails to find PVC volumes

### ISSUE THREAD

**Issue by choey-nebula** [vmware-tanzu/velero#2939]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I'm performing a backup on my EKS cluster like so:
`velero backup create ega-test-backup --include-namespaces ega`

This namespace has a number of deployments, services, and statefulsets - all of which appear to backup properly.  The PVC volumes do not, and the backup status is `PartiallyFailed`.

**What did you expect to happen:**

I expected all deployments, services, statefulsets, associated pods, and PVC persistent storage to backup without error.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

In the case of all persistent storage volumes (5 in my case), the log states that it could not be found:
`time="2020-09-15T22:34:34Z" level=info msg="1 errors encountered backup up item" backup=velero/ega-test-backup5 logSource="pkg/backup/backup.go:444" name=ega-mysql-pxc-0
time="2020-09-15T22:34:34Z" level=error msg="Error backing up item" backup=velero/ega-test-backup5 error="error getting volume info: rpc error: code = Unknown desc = InvalidVolume.NotFound: The volume 'vol-0a0b26fef3b039eb8' does not exist.\n\tstatus code: 400, request id: 712e833c-54cd-4a66-b7d9-9826890cb56e" logSource="pkg/backup/backup.go:448" name=ega-mysql-pxc-0`

- However, using kubectl I can show that a volume with this ID does exist:

[velero-volume-id-exists.txt](https://gist.githubusercontent.com/choey-nebula/bf6e20459a03d9135e093cfcc36409d2/raw/109f04a0401f388377746bf0b230ed481408d8ea/velero-volume-id-exists.txt)

- `kubectl logs deployment/velero -n velero`

[velero-deployment-logs.txt](https://gist.githubusercontent.com/choey-nebula/1db4152c26d302e62758d2e079b58fb0/raw/9676f34a77cc34aa4a3693557875a0a902457b8a/velero-deployment-logs.txt)

- `velero backup describe <backupname>`

[velero-backup-describe.txt](https://gist.githubusercontent.com/choey-nebula/1db4152c26d302e62758d2e079b58fb0/raw/9676f34a77cc34aa4a3693557875a0a902457b8a/velero-backup-describe.txt)

- `velero backup logs <backupname>`

[velero-backup-logs.txt](https://gist.githubusercontent.com/choey-nebula/1db4152c26d302e62758d2e079b58fb0/raw/9676f34a77cc34aa4a3693557875a0a902457b8a/velero-backup-logs.txt)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 

`
Client:
	Version: v1.4.2
	Git commit: -
Server:
	Version: v1.4.2
`

- Velero features (use `velero client config get features`): 

`features: <NOT SET>`

- Kubernetes version (use `kubectl version`):

`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-065dce", GitCommit:"065dcecfcd2a91bd68a17ee0b5e895088430bd05", GitTreeState:"clean", BuildDate:"2020-07-16T01:44:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}`

- Kubernetes installer & version:

Kubernetes version 1.17

- Cloud provider or hardware configuration:

AWS EKS Cluster

- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ashish-amarnath** [comment]
The error you are seeing here is coming from the `DescribeVolumes` API from the aws go sdk. The 400 error indicates that this is a client error. 
From the output of `> k describe pvc mysql-data-ega-mysql-pxc-0 -n ega` the volume you are attempting to snapshot is in `us-east-2`.
>     VolumeID:   aws://us-east-2a/vol-0a0b26fef3b039eb8

Can you please confirm the `region` in the [`VolumeSnapshotLocation`](https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/main/volumesnapshotlocation.md) is also `us-east-2`?

**Comment by nrb** [comment]
@choey-nebula are you able to provide the information Ashish requested for an affected cluster?

**Comment by carlisia** [comment]
I'm closing this issue. @choey-nebula feel free to reopen if you are still having problems.

**Comment by dbdavisson** [comment]
I have this issue also, I am backing up from an EKS cluster in us-east-1 and the backupstorage location is aws bucket in us-east-1, i tried backup storage location first in us-east-2 and then saw this thread, and changed it to us-east-1, but get the same results.

Are you saying the error messages are cosmetic and are ok? I have velero installed on Azure AKS cluster and storage location is also us-east1, aws bucket and get no errors, both velero installs are 1.6.0

**Comment by Manjudhv** [comment]
Hi @carlisia , I need your help I am still facing issue Velero backup to identifying volume dose not existed, I need your help to fix this issue

**Comment by Manjudhv** [comment]
> The error you are seeing here is coming from the `DescribeVolumes` API from the aws go sdk. The 400 error indicates that this is a client error. From the output of `> k describe pvc mysql-data-ega-mysql-pxc-0 -n ega` the volume you are attempting to snapshot is in `us-east-2`.
> 
> > ```
> > VolumeID:   aws://us-east-2a/vol-0a0b26fef3b039eb8
> > ```
> 
> Can you please confirm the `region` in the [`VolumeSnapshotLocation`](https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/main/volumesnapshotlocation.md) is also `us-east-2`?

Hi I am also facing same issue could you plz let me know how to identification

**Comment by Manjudhv** [comment]
> The error you are seeing here is coming from the `DescribeVolumes` API from the aws go sdk. The 400 error indicates that this is a client error. From the output of `> k describe pvc mysql-data-ega-mysql-pxc-0 -n ega` the volume you are attempting to snapshot is in `us-east-2`.
> 
> > ```
> > VolumeID:   aws://us-east-2a/vol-0a0b26fef3b039eb8
> > ```
> 
> Can you please confirm the `region` in the [`VolumeSnapshotLocation`](https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/main/volumesnapshotlocation.md) is also `us-east-2`?

Hi,

Plz ping me I need your help
still I am facing velero backup issue I could not identify that volume dose not exist.

**Comment by paltaa** [comment]
Hey, having the same issue, backing up from aws eks and PVC has old persistent volume id and new ones are note created, so new PVC in cluster 2 cannot find it

**Comment by githubguy00** [comment]
Also facing this issue, any answers?

**Comment by ugurcemozturk** [comment]
> I have this issue also, I am backing up from an EKS cluster in us-east-1 and the backupstorage location is aws bucket in us-east-1, i tried backup storage location first in us-east-2 and then saw this thread, and changed it to us-east-1, but get the same results.
> 
> Are you saying the error messages are cosmetic and are ok? I have velero installed on Azure AKS cluster and storage location is also us-east1, aws bucket and get no errors, both velero installs are 1.6.0

Backup storage location is just for the static files and metadata, not related with PVCs. You should check your snapshot location config.
