### ISSUE TITLE
Release instructions improvements

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#2945]
1) naming of the docs folder for a release that is not a GA release.

https://velero.io/docs/v1.5/release-instructions/#changelog-and-docs-pr (items 5 and 6).

Discussion: https://github.com/vmware-tanzu/velero/pull/2931#discussion_r487295472

**Comment by carlisia** [comment]
@nrb / @zubron / @jonasrosland: if you remember anything else from the release process yesterday that needs to be updated in the doc, please add it here (before we forget!). Thanks.

**Comment by zubron** [comment]
I made these notes quickly during the call, hopefully I captured things correctly:

- Need to update the location of the changelog script in the Makefile
- Step 3: The instructions for handling the CHANGELOG.md file were a bit unclear for me. On GA, the "unreleased" section needs to be removed?
- Step 6: The path for the prerelease TOC is incorrect, should be site/data/**docs**/<pre-release>-toc.yaml
- Step 7: "Update" means to update the all version usage in the page to use the newest version. e.g. from 1.5.0-rc.1 to 1.5.0

**Comment by a-mccarthy** [comment]
@zubron was this issue completed as part of PR #2954 or is there more work to be done on the release docs?

**Comment by zubron** [comment]
There are still a few things that need to be addressed here but I think that it'll be up to folks involved in the release process to write up.

@nrb In going through the release process again recently - was there anything else that came up that we need to fix or add?

**Comment by nrb** [comment]
@zubron The release instructions held up for the most part, though on the `release-1.4` branch some of the dry-run/publish logic didn't work. It appeared that, somehow, the script started to use the one in the `release-1.4` branch instead of the one I actually started from the `main` branch, so I had to go back to the v1.4 series instructions there.

**Comment by nrb** [comment]
>  Step 3: The instructions for handling the CHANGELOG.md file were a bit unclear for me. On GA, the "unreleased" section needs to be removed?

Yeah. The `changelogs/unreleased` directory holds the files for any changes that haven't actually been released. These need to be cleaned out at GA or the changelogs script will reprocess them on the next release, making it look like they've been released twice.

**Comment by carlisia** [comment]
I lost track of this. Anyone knows if it's been all or mostly addressed, can we close this?

**Comment by nrb** [comment]
I think point 3 is covered by this line:

```
Under “Development release”:

    Should contain only the latest pre-release
    Move any prior pre-release into “Older releases”
```

So I'll close this for now and we can revisit.
