### ISSUE TITLE
`velero` command without subcommand returns error

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#2946]
**What steps did you take and what happened:**
Running `velero` without a subcommand now returns an error.

**What did you expect to happen:**
`velero` without a subcommand should return a help message, but no error.

**The output of the following commands will help us better understand what's going on**:

**Anything else you would like to add:**
This appears to be from Cobra v0.0.6, specifically https://github.com/spf13/cobra/blob/v0.0.6/command.go#L957. We need to check for this error and not bubble it up.

**Environment:**

- Velero version (use `velero version`): v1.5.1

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment]
This was reported as an issue in spf13/cobra#1056 as is fixed in the [0.0.7](https://github.com/spf13/cobra/releases/tag/v0.0.7) release so hopefully it's enough to just upgrade the version we're using.

**Comment by nrb** [comment]
Forgot to add a fixes string in the PR. This was closed by #2947.
