### ISSUE TITLE
CR restore regression in 1.4.2

### ISSUE THREAD

**Issue by sseago** [vmware-tanzu/velero#2948]
**What steps did you take and what happened:**
Velero restore with CR and CRD in backup sometimes fails to restore the CR.
In my case, backup was from a Kubernetes 1.16.2 cluster (OpenShift 4.2), and restore was to a Kubernetes 1.17.1 cluster (OpenShift 4.4), but since it's a restore error, restore version is probably more relevant.
Backup of a namespace with one running Deployment, one CRD defined, and a CR of the CRD's type in the namespace.
This is the data to back up to reproduce: https://gist.github.com/sseago/e67a060a07cb20affd1e9fe4a7fb14a6
Back up this namespace (CRD will be pulled in as related to the CR), delete the `mycrdtests` namespace and the `deploycustoms.samplecontroller.k8s.io` CRD, and restore.

**What did you expect to happen:**
CR should be restored along with everything else. Instead, the CR was not restored

**The output of the following commands will help us better understand what's going on**:
Relevant error message from Velero:
```
time="2020-09-14T13:48:24Z" level=info msg="Skipping restore of resource because it cannot be resolved via discovery" logSource="pkg/restore/restore.go:383" resource=deploycustoms.samplecontroller.k8s.io restore=openshift-migration/d0865710-f690-11ea-9a47-e12d786f434f-5w6wc
```

**Anything else you would like to add:**
It's a race condition, so it may not always reproduce. Basically the following commit broke the "wait for CRDs to be ready" funcitonality, as well as the "refresh discovery helper after loading CRDs": 
https://github.com/vmware-tanzu/velero/pull/2683/commits/9d246297b800c1ee24ae9983d1e331efdafa25ff

The reason for this is that the string comparison for "is this a CRD restore?" now fails because "customresourcedefinition" != "CustomResourceDefinition". Either `kuberesource.CustomResourceDefinitions` needs to be reverted to using a lowercase Resource name, or the equals tests in restoreItem (linked below) need to compare in a case-insensitive way:
https://github.com/vmware-tanzu/velero/blob/main/pkg/restore/restore.go#L469
https://github.com/vmware-tanzu/velero/blob/main/pkg/restore/restore.go#L1167

**Environment:**

- Velero version (use `velero version`): 1.4.2
- Kubernetes version (use `kubectl version`): 1.17.1 (OpenShift 4.4)
- Cloud provider or hardware configuration: AWS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by rnrsr** [comment]
i can verify this on the mentioned issue #2632 - it nearly always misses _some_ CRs on the first restore attempt, so i have to run it twice.

**Comment by sseago** [comment]
Actually, case-insensitive test won't work since we're comparing "CustomResourceDefinition" with "customresourcedefinitions". I think this needs to be changed back to the original "customresourcedefinition" and the code that needed the CamelCase "Kind" form fixed to not use the Resource field here, since the Resource field is not the same as the Kind. I think this is the line of code that required the "Kind" form:
https://github.com/vmware-tanzu/velero/blob/main/pkg/backup/remap_crd_version_action.go#L114
```
betaCRD.Kind = kuberesource.CustomResourceDefinitions.Resource
```
I think this needs to use some other method of pulling the string "CustomResourceDefinition".

**Comment by sseago** [comment]
Fix posted at https://github.com/vmware-tanzu/velero/pull/2949

Restoring the proper lowercase plural Resource string for CRDs fixes "wait for CRDs to be ready" and "refresh discovery helper after loading CRD". The update to remap_crd_version_action no longer attempts to use the CRD Resource field as a Kind, so the lowercase doesn't break that anymore.
