### ISSUE TITLE
restic-wait init pod stuck when restoring statefulset with restic plugin

### ISSUE THREAD

**Issue by wanghuok** [vmware-tanzu/velero#2956]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

**i tried to test velero backup and restore on entire cluster:**
1. i create 2 clusters with 3 master nodes and 5 worker nodes respectively
2. in src cluster, i create 50 namespaces, 100 deployments with 2 replicas, 100 loadbalancers
3. additionally, i create 5 ns, each has 1 statefulset with 2 replicas, each replica has 1G pv
4. also, i create 2 ns, each has 1 statefulset with 1 replica, 10G pv
5. write data to the 1G PV and 10G PV seperatly.
6. verify db write correctly
7. annotate pods with pv, and so on for the rest:
`kubectl --context=pks-st-10 -n velero-test-1g-1 annotate pod/postgres-wl-1-0 backup.velero.io/backup-volumes=postgredb
kubectl --context=pks-st-10 -n velero-test-1g-1 annotate pod/postgres-wl-1-1 backup.velero.io/backup-volumes=postgredb`
8. backup entire cluster is succeed:
`velero --kubecontext pks-st-10 backup create wa-bk-2`
logs are uploaded here: https://gist.github.com/wanghuok/9da292ad60b81281edf3d2e86a62dd3f
9. restore to dst cluster: pks-st-11:
`velero --kubecontext pks-st-11 restore create wa-rs-2 --from-backup wa-bk-2`
10. restore failed with PartiallyFailed:
`Name:         wa-rs-2
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:  PartiallyFailed (run 'velero restore logs wa-rs-2' for more information)

Warnings:
  Velero:     <none>
  Cluster:  could not restore, customresourcedefinitions.apiextensions.k8s.io "backups.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "backupstoragelocations.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "deletebackuprequests.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "downloadrequests.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "podvolumebackups.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "podvolumerestores.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "resticrepositories.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "restores.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "schedules.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "serverstatusrequests.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "volumesnapshotlocations.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, validatingwebhookconfigurations.admissionregistration.k8s.io "validator.pksapi.io" already exists. Warning: the in-cluster version is different than the backed-up version.
  Namespaces:
    default:      could not restore, endpoints "kubernetes" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, endpointslices.discovery.k8s.io "kubernetes" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, services "kubernetes" already exists. Warning: the in-cluster version is different than the backed-up version.
    kube-system:  could not restore, secrets "metrics-server-certs" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, configmaps "extension-apiserver-authentication" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, endpoints "kube-controller-manager" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, endpoints "kube-dns" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, endpoints "kube-scheduler" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, endpoints "metrics-server" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, leases.coordination.k8s.io "kube-controller-manager" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, leases.coordination.k8s.io "kube-scheduler" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, services "kube-dns" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, services "metrics-server" already exists. Warning: the in-cluster version is different than the backed-up version.
    pks-system:   could not restore, secrets "event-controller" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, secrets "fluent-bit" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, secrets "pks-ca" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, secrets "validator" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, configmaps "fluent-bit" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, configmaps "telemetry-config-map" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, endpoints "fluent-bit" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, endpoints "validator" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, services "fluent-bit" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, services "validator" already exists. Warning: the in-cluster version is different than the backed-up version.
    velero:       could not restore, podvolumebackups.velero.io "velero-10g-csi-1-k22lw" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-10g-csi-10-gkjvw" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-10g-csi-2-zrn74" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-10g-csi-3-r8zh2" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-10g-csi-4-l6fr9" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-10g-csi-5-znmd7" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-10g-csi-6-xhqq5" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-10g-csi-7-brh8q" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-10g-csi-8-rsfmq" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-10g-csi-9-7pnzx" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-1-4qx92" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-10-9pjqd" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-100-gx4r5" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-11-5h97t" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-12-7k78n" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-13-7l87r" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-14-t24pp" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-15-2s6ph" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-16-bm28b" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-17-6gzk5" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-18-qfjqj" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-19-8qcbp" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-2-dvzd2" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-20-rxwn8" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-21-98m9v" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-22-ztg4q" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-23-lckkj" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-24-g7kq7" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-25-kzskg" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-26-flhwc" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-27-55lq2" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-28-dns5d" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-29-lczcs" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-3-2wckw" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-30-p65kn" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-31-tlmqs" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-32-g5cgz" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-33-kz7zc" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-34-nn7wl" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-35-jmt2j" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-36-nxfsr" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-37-9mqq4" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-38-zj7wk" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-39-dc8c2" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-4-ghk8c" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-40-rh8wf" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-41-2zdzf" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-42-x8894" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-43-zkdg5" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-44-qcgz9" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-45-r94zs" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-46-pnddb" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-47-w8cbh" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-48-jjrxn" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-49-sx99x" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-5-tjhf4" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-50-h562w" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-51-8khgh" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-52-gtr77" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-53-m9pml" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-54-f5vwg" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-55-6qcrd" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-56-8rwmd" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-57-x7vg9" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-58-fv9rq" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-59-ktmvb" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-6-8dbzg" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-60-fzvqb" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-61-cxdbr" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-62-h2n2q" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-63-zctfg" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-64-gslkt" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-65-sgd97" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-66-qnfsf" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-67-65mhb" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-68-dztm7" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-69-8n5bf" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-7-brvp7" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-70-k26bj" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-71-zqdkq" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-72-c69j9" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-73-7mhjz" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-74-v58q8" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-75-vkk8b" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-76-bt28b" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-77-rh4mg" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-78-568fd" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-79-j75qk" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-8-lhrw2" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-80-k547c" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-81-948fk" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-82-cvq88" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-83-r48rb" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-84-vxln2" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-85-5k7px" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-86-89zbz" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-87-r2ldw" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-88-pxgpv" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-89-zfvj7" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-9-zd8bt" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-90-tm5w6" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-91-fzdd4" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-92-k96rm" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-93-88wqm" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-94-xss8j" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-95-4ctpq" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-96-xfg97" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-97-v2ngh" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-98-6ftw8" already exists. Warning: the in-cluster version is different than the backed-up version.
                  could not restore, podvolumebackups.velero.io "velero-1g-csi-99-n5lc8" already exists. Warning: the in-cluster version is different than the backed-up version.

Errors:
  Velero:  pod volume restore failed: error restoring volume: error running restic restore, cmd=restic restore --repo=s3:http://20.20.224.27:9000/velero/restic/velero-test-10g-2 --password-file=/tmp/velero-restic-credentials-velero-test-10g-2756621964 --cache-dir=/scratch/.cache/restic 91d60576 --target=., stdout=, stderr=: error getting snapshot size: error running command, stderr=Fatal: error loading snapshot: no matching ID found
: exit status 1
    pod volume restore failed: error restoring volume: error running restic restore, cmd=restic restore --repo=s3:http://20.20.224.27:9000/velero/restic/velero-test-10g-1 --password-file=/tmp/velero-restic-credentials-velero-test-10g-1463948514 --cache-dir=/scratch/.cache/restic 0086386c --target=., stdout=, stderr=: error getting snapshot size: error running command, stderr=Fatal: error loading snapshot: no matching ID found
: exit status 1
  Cluster:    <none>
  Namespaces: <none>

Backup:  wa-bk-2

Namespaces:
  Included:  all namespaces found in the backup
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Restic Restores:
  Completed:
    velero-test-1g-1/postgres-wl-1-0: postgredb
    velero-test-1g-1/postgres-wl-1-1: postgredb
    velero-test-1g-2/postgres-wl-2-0: postgredb
    velero-test-1g-2/postgres-wl-2-1: postgredb
    velero-test-1g-3/postgres-wl-3-0: postgredb
    velero-test-1g-3/postgres-wl-3-1: postgredb
    velero-test-1g-4/postgres-wl-4-0: postgredb
    velero-test-1g-4/postgres-wl-4-1: postgredb
    velero-test-1g-5/postgres-wl-5-0: postgredb
    velero-test-1g-5/postgres-wl-5-1: postgredb
  Failed:
    velero-test-10g-1/postgres-wl-1-0: postgredb
    velero-test-10g-2/postgres-wl-2-0: postgredb
`

11. in failed ns , you can see pods are stuck in init status:
` kubectl --context pks-st-11 get pods -n velero-test-10g-1 -o wide`

`
NAME              READY   STATUS     RESTARTS   AGE   IP            NODE                                   NOMINATED NODE   READINESS GATES
`

`postgres-wl-1-0   0/2     Init:0/1   0          40m   10.10.9.130   aa8df14d-57b4-40af-bd51-a1c5b7daf27c   <none>           <none>`

12. check logs of that pod:
`kubectl --context pks-st-11 logs postgres-wl-1-0 -c restic-wait -n velero-test-10g-1 | tail -10 `
output:
`Not found: /restores/postgredb/.velero/39b9590e-1122-4ceb-a842-953b958af77c`
details are uploaded here: https://gist.github.com/wanghuok/9da292ad60b81281edf3d2e86a62dd3f

**What did you expect to happen:**
restore should be succeed.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
logs are uploaded here: https://gist.github.com/wanghuok/9da292ad60b81281edf3d2e86a62dd3f

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use velero version):
Version: v1.4.2_vmware.1

- Velero features (use velero client config get features):
features: <NOT SET>

- Kubernetes version (use kubectl version):
1.18.5
Kubernetes installer & version:

- Cloud provider or hardware configuration:
VCP

- OS (e.g. from /etc/os-release):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by nrb** [comment]
Based on the errors, it looks like this was only the 2 10gb PVs. A sample:

`    pod volume restore failed: error restoring volume: error running restic restore, cmd=restic restore --repo=s3:http://20.20.224.27:9000/velero/restic/velero-test-10g-1 --password-file=/tmp/velero-restic-credentials-velero-test-10g-1463948514 --cache-dir=/scratch/.cache/restic 0086386c --target=., stdout=, stderr=: error getting snapshot size: error running command, stderr=Fatal: error loading snapshot: no matching ID found`

Can you provide the annotation command that you used for the 10g PVs? I don't see them in the command supplied in the report (`kubectl --context=pks-st-10 -n velero-test-1g-1 annotate pod/postgres-wl-1-0 backup.velero.io/backup-volumes=postgredb kubectl --context=pks-st-10 -n velero-test-1g-1 annotate pod/postgres-wl-1-1 backup.velero.io/backup-volumes=postgredb`)

**Comment by wanghuok** [comment]
Hello, @nrb :

annotation command used for 10g pv same as 1g pv:
`kubectl --context=pks-st-10 -n velero-test-10g-1 annotate pod/postgres-wl-1-0 backup.velero.io/backup-volumes=postgredb`

i think it has nothing to do with pv size.

in previous test, 2 ns failed with same error message with this time when restore cluster. one ns is 1g pv, the other is 10g pv

**Comment by nrb** [comment]
@wanghuok Thanks. I didn't expect that it actually had to do with PV size, I just wanted to be sure there wasn't inconsistency in the commands run.

**Comment by wanghuok** [comment]
Hello, @nrb Is there any new progress?

**Comment by zubron** [comment]
Hi @wanghuok. I'd like to check that the snapshot that is being restored exists in your storage location, that will help us in determining why this error is being triggered.

Can you verify that the snapshot ID of your `PodVolumeRestore ` is `91d60576`. You can check this by running: 
```
kubectl -n velero get podvolumerestores -lvelero.io/restore-name=wa-rs-2 -ojson | jq .items[].spec

```
and checking the `SnapshotID` field.

If it matches, can you check the following path in your storage location `/restic/velero-test-10g-2/snapshots/` for a file beginning with the snapshot ID `91d60576`? Can you also repeat this process for the other restore that fails (checking `/restic/velero-test-10g-1/snapshots/` for a file beginning with `0086386c`)?

These are the snapshots that restic is attempting to restore but can't find. Thanks!

**Comment by vivekwalia28** [comment]
Hi,I am still facing the above mentioned issue even after doing all the steps mentioned.
Could you please help me?
**Environment:**

    Velero version (use velero version):
    Version: v1.6.0

    Velero features (use velero client config get features):
    features: N/A

    Kubernetes version (use kubectl version):
    1.21.1
    
    OS (e.g. from /etc/os-release): Ubuntu 20.04


Error I am getting:

time="2021-06-09T18:25:54Z" level=error msg="unable to successfully complete restic restores of pod's volumes" error="pod volume restore failed: error restoring volume: error running restic restore, cmd=restic restore --repo=s3:http://192.168.226.130:31149/bucket1/restic/nginx-test --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic e9eb6980 --target=., stdout=restoring <Snapshot e9eb6980 of [/host_pods/7c6d3940-2743-47a7-9b8f-0b36dad6bbb4/volumes/kubernetes.io~projected/kube-api-access-wmcr6] at 2021-06-06 19:42:26.25307776 +0000 UTC by root@velero> to .\n, stderr=ignoring error for /..data: Symlink: symlink ..2021_06_06_18_54_11.103621391 /host_pods/a3562c2c-d8ba-4772-8d7d-af5c62e976f1/volumes/kubernetes.io~projected/kube-api-access-wmcr6/..data: file exists\nignoring error for /ca.crt: Symlink: symlink ..data/ca.crt /host_pods/a3562c2c-d8ba-4772-8d7d-af5c62e976f1/volumes/kubernetes.io~projected/kube-api-access-wmcr6/ca.crt: file exists\nignoring error for /namespace: Symlink: symlink ..data/namespace /host_pods/a3562c2c-d8ba-4772-8d7d-af5c62e976f1/volumes/kubernetes.io~projected/kube-api-access-wmcr6/namespace: file exists\nignoring error for /token: Symlink: symlink ..data/token /host_pods/a3562c2c-d8ba-4772-8d7d-af5c62e976f1/volumes/kubernetes.io~projected/kube-api-access-wmcr6/token: file exists\nFatal: There were 4 errors\n\n: exit status 1" logSource="pkg/restore/restore.go:1358" restore=velero/restore1
