### ISSUE TITLE
Velero POD deployment is getting crashed

### ISSUE THREAD

**Issue by elangocse** [vmware-tanzu/velero#2959]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

We have deployed Velero in our kube cluster engine which is running in Azure stack environment. The Velero platform we installed : "velero-v1.4.2-linux-amd64". 
Later using the command  _velero install_ we deployed kube deployment which is getting crashed.

**What did you expect to happen:**

We need Velero should be up & running and further we should take backup of the K8 cluster.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

`time="2020-09-21T13:49:18Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2020-09-21T13:49:18Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
time="2020-09-21T13:49:18Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2020-09-21T13:49:18Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-09-21T13:49:18Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-microsoft-azure kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2020-09-21T13:49:18Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-microsoft-azure kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2020-09-21T13:49:18Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:361" namespace=velero
time="2020-09-21T13:49:18Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:367" namespace=velero
time="2020-09-21T13:49:21Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:396"
time="2020-09-21T13:49:21Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:430"
time="2020-09-21T13:49:21Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:437"
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxx-nonprod-velero-backup-RG/providers/Microsoft.Storage/storageAccounts/xxxxnonprodvelerobackup/listKeys?api-version=2018-02-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/841b03e5-xxxxxxxxxxxxxxxx/oauth2/token?api-version=1.0: dial tcp: i/o timeout'`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**velero version**
Client:
        Version: v1.4.2
        Git commit: 56a08a4d695d893f0863f697c2f926e27d70c0c5
<error getting server version: timed out waiting for server status request to be processed>

 **kubectl version --short**
Client Version: v1.14.8
Server Version: v1.14.8

**OS Release**
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"

 **velero client config get features**
features:<NOT SET>

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by nrb** [comment]
Hi @elangocse - are you using ADFS by chance? Doing some research, it appears that this error can manifest when accessing ADFS resources.

Have you seen this regularly, or has it been a one-time event?

**Comment by elangocse** [comment]
@nrb 

You mean Active directory federated services. Nope I am not using it.
We are running AKS in Azure Stack to deploy Velero as a POD deployment for cluster backup. 

The POD is getting crashed regularly. Its coming up and after a min or two, it getting crashed again with above error. 
We are trying to connect Azure storage which is running in Azure public cloud from AKS Master node which is running in a Azure Stack. Not sure is it related to any network connectivity from Stack to Azure public cloud.

How to troubleshoot the issue ? Do we have any other alternate solution to backup K8 cluster. 

Thanks
Elango Boopathy.

**Comment by elangocse** [comment]
Hi

Could you please through some lights on this issue ? Its a blocker now and not able to move further.

**Comment by nrb** [comment]
I'm not familiar with Azure Stack, though I suppose network connectivity isn't out of the question.

Are you able to reach the Azure blob storage URLs with `curl` or `wget` from within the Azure Stack cluster? You may have to install a container that has this utility and use [`kubectl exec`](https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/) to troubleshoot it, as the Velero pod does not come with it pre-installed and runs as the `nobody` user, without permissions to install more programs.

I would expect `curl` or `wget` to fail with permissions errors against those URLs if you do not provide the appropriate tokens, but they shouldn't timeout like Velero did if there's no network issues.

**Comment by ashish-amarnath** [comment]
@elangocse Here is another issue reporting a similar error. https://github.com/Azure/AKS/issues/222
This, apparently happens when the Azure Service Principal may have expired.
https://github.com/Azure/AKS/issues/222#issuecomment-497427600
Can you please follow steps from https://docs.microsoft.com/en-us/azure/aks/update-credentials to see if that works for you?

**Comment by carlisia** [comment]
I'm closing this issue. @elangocse there seems to be a workaround for this but feel free to reopen if you still have any problems.
