### ISSUE TITLE
Cannot install Velero CRDs without kubectl apply --validate=false

### ISSUE THREAD

**Issue by Panplumousse** [vmware-tanzu/velero#2964]
What steps did you take and what happened:**
I tried to update the velero version from 1.3.2 to 1.5.1

**I tried to update the velero version from 1.3.2 to 1.5.1, the velero pod starts up correctly but
when I do a velero version with cli client I get this :

Client:
Version: v1.5.1
Git commit: 87d86a4
Server:
Version:
server version is empty

when i try to get version directly in pod , i have same things

$ ./velero version
Client:
Version: v1.5.1
Git commit: 87d86a4
Server:
Version:

the pod log has many errors

Kubelet 1.13.5
Kubernetes API server 1.13.5
Kubernetes control manager 1.13.5
Kubernetes pause 3.1
Kubernetes proxy 1.13.5
Kubernetes scheduler 1.13.5
kube_state_metrics 1.2.0

 in fist time i have update CRDs , with following documentation but many errors , i had forced to pass --validate=false agrgument
velero install --crds-only --dry-run -o yaml | kubectl -n velero apply -f - --validate=false

LOG WITHOUT validate=false

velero install --crds-only --dry-run -o yaml | kubectl -n velero apply -f -
error: error validating "STDIN": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.excludedNamespaces): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.excludedResources): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.hooks.properties.resources): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.includeClusterResources): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.includedNamespaces): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.includedResources): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.labelSelector): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.snapshotVolumes): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.completionTimestamp): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.expiration): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.startTimestamp): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.validationErrors): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.backupSyncPeriod): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.lastSyncedTime): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.errors): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.expiration): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.completionTimestamp): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.startTimestamp): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.completionTimestamp): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.startTimestamp): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.lastMaintenanceTime): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.excludedNamespaces): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.excludedResources): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.includeClusterResources): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.includedNamespaces): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.includedResources): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.labelSelector): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.restorePVs): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.validationErrors): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.template.properties.excludedNamespaces): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.template.properties.excludedResources): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.template.properties.hooks.properties.resources): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.template.properties.includeClusterResources): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.template.properties.includedNamespaces): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.template.properties.includedResources): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.template.properties.labelSelector): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.template.properties.snapshotVolumes): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.lastBackup): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.plugins): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.status.properties.processedTimestamp): unknown field "nullable" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec]; if you choose to ignore these errors, turn validation off with --validate=false

log with validate= false

velero install --crds-only --dry-run -o yaml | kubectl -n velero apply -f - --validate=false
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/backups.velero.io configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/backupstoragelocations.velero.io configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/deletebackuprequests.velero.io configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/downloadrequests.velero.io configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/podvolumebackups.velero.io configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/podvolumerestores.velero.io configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/resticrepositories.velero.io configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/restores.velero.io configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/schedules.velero.io configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/serverstatusrequests.velero.io configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
customresourcedefinition.apiextensions.k8s.io/volumesnapshotlocations.velero.io configured

podvolumebackups.velero.io 2020-09-21T13:21:25Z
podvolumerestores.velero.io 2020-09-21T13:21:25Z
resticrepositories.velero.io 2020-09-21T13:21:25Z
restores.velero.io 2020-09-21T13:21:25Z
schedules.velero.io 2020-09-21T13:21:25Z
serverstatusrequests.velero.io 2020-09-21T13:21:25Z

In second time i had deleted all velero release and namespace
and install fresh but exactly the same

**Comment by zubron** [comment]
Unfortunately, `preserveUnknownFields` is only valid in Kubernetes v1.15+ and `nullable` is only valid in Kubernetes v1.14+. Given that you are running v1.13, these are unknown fields to the server and so the warning is being reported. This has already been encountered in #2077 and #2311. The outcome from those issues was to use the workaround `--validate=false` which you are already using. This is documented here: https://velero.io/docs/v1.5/customize-installation/#generate-yaml-only.

Usually this error would only be encountered when customising the velero install, however the upgrade instructions for both v1.4 and v1.5 instruct users to update the CRDs by directly applying the CRD yaml generated by `velero install`. These docs should be updated to inform users that they should use `--validate=false` if running Kubernetes v1.14 or earlier.

**Comment by zubron** [comment]
I've opened #2969 to address the documentation issue.

**Comment by Panplumousse** [comment]
hello ty for reply,
but for issu about i can't view server version with command:  velero version is it the same kind of probleme ?

**Comment by zubron** [comment]
The missing server version was an issue with our 1.5 beta release, however was resolved for the 1.5.1 release. Can you confirm that you have updated the image on the Velero deployment to the latest version using `kubectl get deployment/velero -n velero -o wide`? The image for the deployment should be `velero/velero:v1.5.1`. I've noticed that on a 1.3 installation, if I only update the CRDs and not the image, the reported server version will be empty.

**Comment by plum59** [comment]
hello i just check and it seems good velero version 

i have this message in server log 

velero-587c4fc947-s2kw4 velero] time="2020-09-21T13:34:15Z" level=error msg="Unable to update the request" controller=serverstatusrequest error="the server could not find the requested resource (patch serverstatusrequests.velero.io velero-cli-wb24d)" error.file="/go/src/github.com/vmware-tanzu/velero/internal/velero/serverstatusrequest.go:49" error.function="github.com/vmware-tanzu/velero/internal/velero.(*ServerStatus).PatchStatusProcessed" logSource="pkg/controller/server_status_request_controller.go:89" phase= serverStatusRequest=velero/velero-cli-wb24d
[velero-587c4fc947-s2kw4 velero] time="2020-09-21T13:34:15Z" level=error msg="Unable to update the request" controller=serverstatusrequest error="the server could not find the requested resource (patch serverstatusrequests.velero.io velero-cli-vbp6l)" error.file="/go/src/github.com/vmware-tanzu/velero/internal/velero/serverstatusrequest.go:49" error.function="github.com/vmware-tanzu/velero/internal/velero.(*ServerStatus).PatchStatusProcessed" logSource="pkg/controller/server_status_request_controller.go:89" phase= serverStatusRequest=velero/velero-cli-vbp6l

**Comment by Panplumousse** [comment]
Hello i had this kind of message to

My fatal issu is link to backup location i think:

 level=error msg="Error patching backup location's last-synced time" backupLocation=aws controller=backup-sync error="the server could not find the requested resource (patch backupstoragelocations.velero.io aws)" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_sync_controller.go:311" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*backupSyncController).run" logSource="pkg/controller/backup_sync_controller.go:311"

at begin i had not update image of init container aws with new version 1.1.0
but now i had update it but i receive same error

**Comment by carlisia** [comment]
@Panplumousse running `velero install --crds-only --dry-run -o yaml | kubectl apply -f -` should resolve your problem.

**Comment by carlisia** [comment]
@plum59 running `velero install --crds-only --dry-run -o yaml | kubectl apply -f -` should resolve your problem.

**Comment by carlisia** [comment]
If anyone continues to have issues, please open an issue and provide the output of:

- `velero server`
- `kubectl get crd -n velero`
- the command used to install Velero
