### ISSUE TITLE
Custom metadata from Velero hooks

### ISSUE THREAD

**Issue by yaronp68** [vmware-tanzu/velero#2973]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
This ER is about adding the ability to write custom metadata to the backup file from hooks and plugins using an additional argument or method.

### The use case
When Velero backs-up a pod with its data it treats it as a blackbox. It only knows what K8s knows about the pod. This is a good approach that makes Velero very generic and effective. However, in the same manner that users need to perform some custom actions on a pod before backing it up (done via hooks), they sometimes need to have additional information in the backup that will help them understand what they are about to restore and what will be the implications of restoring a stateful pod.

### Here's an example: 
Our team is in charge of using Velero to backup a product named Tanzu Application Service (aka TAS)
As a central part of this task we are backing up a relational database that contains the TAS Cloud Controller data.
Kubernetes (and hence Velero) knows nothing about the database data or structure. For Velero the Cloud Controller DB is a pod with a PV attached to it.
For the user on the other hand, the information in the DB is crucial. When the user restores a db PV, the data going back into the DB will be the state of the application.
In our case the user is a platform operator providing services to application developers. In the database there is information about the names & the ownership of the applications that can help the operator understand what is about to be restored.
We wanted to have this information inside the Velero backup in order to allow for the operator to be able to know what kind of state is inside the backup of the data and once restored, to diff between the old system and the new system and see if everything had been fully restored. Because we could not do that, we wrote the information from a hook into the Velero log file which is also stored in the backup location. We had to add some user steps that are external to velero to help our user to extract the information from Velero log file.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
### The proposed solution
We would like to propose the following changes to Velero:

1. An addition to the backup file structure for storing custom metadata
2. Additional mechanisms for writing the custom metadata
3. Additional mechanisms for reading the custom metadata

### Storing the metadata: Changes to the Velero Backup File 
Velero backup file format is described  [here](https://velero.io/docs/v1.4/output-file-format/)

Currently, each backup file is stored in its own subdirectory in the bucket specified in the Velero server configuration. 
This subdirectory includes an additional file called velero-backup.json. 
The JSON file lists all information about your associated Backup resource, including any default values.

We propose one of the following options:

- Adding a custom section to the JSON file
- Alternatively adding a custom text file with structure that is known for the parsing client for each resource that is backed up and wants to add custom metadata 

### Option 1: Additional section to the JSON (velero-backup.json)
**Pros:**

- No additional files
- Small change to the velero codebase to get this to work

**Cons:**

- The metadata should probably be limited in size and escaped so it does not break the JSON
- Metadata is not local to particular resources. Instead, metadata is always stored at the granularity of a whole backup.
- Without context, this additional key in the json file with seemingly arbitrary data may not make a lot of sense and be confusing.

### Option 2: Separate text file per resource
**Pros:**

- Can have any content (won’t be parsed by anything)
- No size limitation 	
- Metadata can be stored at the same granularity as hooks

**Cons:**

- Slightly more complex logic 

### Writing the metadata
**Changes to Velero Hooks**
Velero backup hooks are described [here](https://velero.io/docs/v1.4/hooks/). In particular, note the pre.hook.backup.velero.io/command and post.hook.backup.velero.io/command hooks. These can be extended to offer the hook author the opportunity to write metadata into a file.

Velero should set the environment variable `VELERO_BACKUP_METADATA_FILE` to the full path to a file into which the hook command can choose to write metadata. If the hook command terminates successfully, and if the file has been written to, then the contents of that file should be written to the metadata storage for this resource.

**Changes to Velero Plugins**
[This github issue](https://github.com/vmware-tanzu/velero/issues/2483) suggests one option for updating Velero plugins -- but makes some assumptions about where the data will ultimately live. If the data lives in the backup object, then we only need to make that object writable from within the plugin.

If the data lives elsewhere, we may need to introduce a new (optional?) parameter to the backup item plugin method

### Reading the metadata: changes to Velero Describe
We propose that `velero describe backups` gain an additional flag `-c`, which will show custom metadata for whichever resource is being described.

This could be used in conjunction with the existing `-l` selector flag as follows:

`velero describe backups -c -l my-deployment`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
Hi @yaronp68, I think this is a reasonable request and certainly something we need to work with your team on.

Right now, we do have a `plugins` directory in the backup storage location that plugins can write to that the vSphere plugin is leveraging. I don't think this will be the entirety of the solution, but perhaps at least part of it.

I did some searching through our docs and it looks like while we implemented this, we didn't document it, so I'll file an issue to get it documented in our custom plugins page.

**Comment by nrb** [comment]
Re-reading the issue, the `plugins` directory isn't sufficient for what you're asking.

Changes to the `backup.json` file will be at the CRD level - so we'll have to se if we can put arbitrary data there.

**Comment by michmike** [comment]
we are prioritizing this work for 1.7 release of Velero.
after 1.6 is tied down, @nrb will reply with some of the guard rails of this implementation for feedback.

**Comment by nrb** [comment]
@xing-yang and @lintongj FYI, since I know you're interested in the output for `velero describe` too. We should make sure whatever we implement for both the vSphere plugin and TAS.

**Comment by dsu-igeek** [comment]
Moving this forward to 2.0.  I think this should be handled by TAS presenting an Astrolabe snapshot API.  Diffs between snapshots is something that is TAS specific and could be handled by a TAS utility, this is not a core Velero function.  We'll be able to add any custom data that you like as part of the Astrolabe snapshot metadata (https://github.com/vmware-tanzu/astrolabe)
