### ISSUE TITLE
Scheduled backups automatically deleted when ArgoCD deploys Velero

### ISSUE THREAD

**Issue by javanthropus** [vmware-tanzu/velero#2975]
**What steps did you take and what happened:**

We are trying to use ArgoCD to deploy most resources into our clusters, and we're using the vmware-tanzu/velero helm chart to enable that.  We include schedule definitions in the chart's `values.yaml` so that they are created automatically.

A Backup resource created from the resulting Schedule resource inherits all of the tags from the Schedule resource, including one that ArgoCD uses to identify resources it directly creates: `argocd.argoproj.io/instance`.  ArgoCD then sees the Backup resource, sees that it is not part of the set of resources ArgoCD continues to need to create, and then prunes it.  As a result, scheduled backups fail.

Note that backups created manually *not* using one of the automatically created Schedule resources as a template work correctly.  They are not seen by ArgoCD and can persist indefinitely.

**What did you expect to happen:**

Backup resources are ignored by ArgoCD so that they can complete and persist.

**Anything else you would like to add:**

Including the ability to define the tags (and potentially annotations) for Backup resources via the Schedule template as an alternative to only pulling them from the Schedule resource itself would avoid this problem.  To preserve backward compatibility, continue with the current behavior unless a list of labels (potentially empty) is provided.  If the list is provided, even if empty, use that list to set the labels for the Backup resource that is created.

**Environment:**

- Velero version (use `velero version`):
     ```
    Client:
        Version: v1.4.2
        Git commit: 56a08a4d695d893f0863f697c2f926e27d70c0c5
    Server:
        Version: v1.4.2
    ```
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`):
    ```
    Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", 
    GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", 
    GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
    ```
- Kubernetes installer & version: cluster-api v0.3.9
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by igorcezar** [comment]
One way to solve this is using ArgoCD [resource.exclusions](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#resource-exclusioninclusion) as stated in [this issue](https://github.com/argoproj/argo-cd/issues/1472). 

The best solution would be to configure this at the application level, but at cluster scope also solves the problem.

**Comment by igorcezar** [comment]
#3127 fixes the problem of Backups resources being pruned. Backups will now be synced in ArgoCD by inserting OwnerReference of Schedules, just the same way that Pods and Deployments works.

**Comment by carlisia** [comment]
Ah, thanks for bringing that up @igorcezar!

There were quite a few upvotes on this, it would be great to get an additional confirmation if that code change will solve this issue. It will be released on v1.6, some point in January, or please try it from source.

**Comment by igorcezar** [comment]
Before the fix in #3127 ArgoCD detected Backups resources (because of the labels Backups inherits from Schedule) but they were all Out of Sync because they don't exist in Git Repo that ArgoCD is syncing.

![velero-backup-outofsync](https://user-images.githubusercontent.com/10411165/102666699-572d7a80-4166-11eb-838f-03ed265c76f5.jpg)

After the fix, Backups resources created by Schedules have the OwnerReference parameter in their manifest, which makes it a child resource of the Schedule, so ArgoCD sees no problem in it.

![velero-backup-sync](https://user-images.githubusercontent.com/10411165/102666677-4d0b7c00-4166-11eb-9392-4e5007b9453d.jpg)

**Comment by carlisia** [comment]
Alright, this seems to have resolved it. We can always look into this again "in case" someone has a different outcome.

Thank you for this!

**Comment by obeyler** [comment]
I use argocd v2.0.3 and velero 1.6.2  I still have backup marked as OutOfSync (requires pruning)

![image](https://user-images.githubusercontent.com/23224162/129591592-341e8856-975e-4a03-8082-df2e0d3d28b0.png)

I didn't use ArgoCD resource.exclusions, Shall I use it to solve this  or it should be solved without exclusion ?

**Comment by igorcezar** [comment]
@obeyler did you upgrade the schedule CRD in the cluster?

And if you use velero CLI you must also upgrade it to v1.6.

**Comment by obeyler** [comment]
@igorcezar 
I installed velero by helm chart
    version: 2.23.5
    repository: https://vmware-tanzu.github.io/helm-charts
I set in value.yaml 
`upgradeCRDs: false ` because if I don't do that argocd always says that  the crd are out of sync.

**Comment by obeyler** [comment]
I found why It was the old backup who still stay as not sync, the new one make with 'useOwnerReferencesInBackup: true' flag are well sync.
Thanks !

**Comment by KingCrunch** [comment]
> I set in value.yaml
> upgradeCRDs: false because if I don't do that argocd always says that the crd are out of sync.

Same here. It seems, that velero itself updates the CRDs, but they are not the same as the ones from the helm chart. The Helm Charts CRDs seems to be more up-to-date

**Comment by Azword** [comment]
> There is a wrinkle with the solution used to close this issue that may not have been considered. Namely, when schedule resources are deleted, the backup resources that are owned by them are also deleted by the k8s garbage collector. With regard to backup resources, this is likely to cause some surprise since it may be desirable to preserve the backup resources independently of the schedule resources.
> 
> This solution gives Argo users no option though. The only way to prevent Argo deleting the backup resources is to enable the `useOwnerReferencesInBackup`. If the users want to replace the schedule resource later but preserve the backups until their TTLs otherwise expire, the users must manually edit the backups to remove the ownerReference setting.

I totally agree with your comment, i'm running the same problem in production.

The `useOwnerReferencesInBackup` works perfectly until you came up to the moment where you need to delete the application, all the backups are gonna be deleted. 

I've tried the solution where you use argocd's hooks on Backup manifest, but it didn't seems to work, did you find a proper solution to preserver your backups after the deletion of an app ?

**Comment by javanthropus** [comment]
We just set `useOwnerReferencesInBackup` and suffer the consequences.  Fortunately, we don't need to replace schedule resources very often, but the solution I suggested in the description of this issue would be more ideal and more in line with how Deployment resources work for labeling pods they create and how CronJob resources work to label Jobs they create.
