### ISSUE TITLE
velero restore failed with volume token not found

### ISSUE THREAD

**Issue by AkhilaDamera** [vmware-tanzu/velero#2982]
**What steps did you take and what happened:**
I have backed up a vault cluster namespace which has AzureFileshare pvc's with one of the pod volumes as below:

```
$ kubectl get pod/vault-0 -n hashicorp-vault -o yaml

    volumeMounts:
    - mountPath: /vault/data
      name: data
    - mountPath: /vault/config
      name: config
    - mountPath: /home/vault
      name: home
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: vault-token-7c4br

  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-vault-0
  - configMap:
      defaultMode: 420
      name: vault-config
    name: config
  - emptyDir: {}
    name: home
  - name: vault-token-7c4br
    secret:
      defaultMode: 420
      secretName: vault-token-7c4br
```
I have used velero with restic and have annotated the pods before creating the backup: 
```
kubectl -n hashicorp-vault annotate pod/vault-0 backup.velero.io/backup-volumes=data,config,home,vault-token-7c4br
```
After creating the backup, deleting the namespace and while restoring the error stated as below:

```
error: 
$ velero restore logs vault-backup-20200922222147 | grep error
time="2020-09-23T02:21:49Z" level=info msg="error restoring vault-0: Pod \"vault-0\" is invalid: spec.initContainers[0].volumeMounts[1].name: Not found: \"vault-token-7c4br\"" logSource="pkg/restore/restore.go:1152" restore=velero/vault-backup-20200922222147
```
When i looked into the pod information the token has changed to vault-token-cgchc and the pods were failed to initialize.
How to backup the persistent volumes with secret token values which changes after the backup and failing during restore?

**What did you expect to happen:**
Velero should restore the pvc volumes(vault-token-7c4br) successfully.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  1.5.1
- Velero features (use `velero client config get features`): Not Set
- Kubernetes version (use `kubectl version`): 1.17.9
- Cloud provider or hardware configuration: azure aks

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by carlisia** [comment]
This seems to have enough information to investigate. Might come down to answering this question:

> How to backup the persistent volumes with secret token values which changes after the backup and failing during restore?

**Comment by nrb** [comment]
@AkhilaDamera Thanks for the report! The cause for this is because Velero ignores any volumes with `-token-` in their name under the assumption that they are Kubernetes tokens.

However, this is a demonstration of a case where that assumption is incorrect.

I'm not super familiar with Vault, do you know if it's possible to name the volume mounts something else as a workaround?

**Comment by AkhilaDamera** [comment]
@nrb The `vault-token-` is created by the kubernetes and automatically mounted within the pod using the kubernetes service account for authentication. This sa token is createdafter the deployment of vault and the code I have will auto-initialize the vault.

I have tried the workaround but it doesn't seems working as the velero is not able to restore the old token pod volume config and the restore failing with vault pods installed but not initialized as it requires the same token which it has auto initialize configured for.
