### ISSUE TITLE
[BUG] Velero not backuping Rook+Ceph correctly

### ISSUE THREAD

**Issue by WaterKnight1998** [vmware-tanzu/velero#2984]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

 I am trying to backup my kubernetes cluster with Velero+Restic.

In that cluster I deployed [Rook+Ceph with PVC](https://rook.io/docs/rook/v1.4/ceph-cluster-crd.html). In that cluster I created an [Object Storage](https://rook.io/docs/rook/v1.4/ceph-object.html)

The volumes of Rook Ceph in PVC has `volumeMode: Block`.

When I restore the backup with velero. My Rook+Ceph is not starting correctly and buckets lost the information. I think that `volumeMode: Block` is the problem.

**What did you expect to happen:**
Rook+Ceph cluster should start again withouth loosing information in the buckets.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
```
Client:
        Version: v1.5.1
        Git commit: 87d86a45a6ca66c6c942c7c7f08352e26809426c
Server:
        Version: v1.4.2
```
- Velero features (use `velero client config get features`): 
```
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.6300", GitCommit:"eb6985a7ebfd53457b0b91ba08fac07597bb87af", GitTreeState:"clean", BuildDate:"2020-09-15T09:20:11Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE with Ubuntu nodes

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by mikosa** [comment]
I imagine Restic was also deployed?

**Comment by carlisia** [comment]
Hey @WaterKnight1998, can you please retry this operation, this time with a matching version of Velero on both client and server? So, either both versions should be 1.4 or both 1.5. Then send us your logs. Thanks.

**Comment by ashish-amarnath** [comment]
@WaterKnight1998 Considering that you were able to document this at https://github.com/rook/rook/pull/6365
Are you still facing this issue?

**Comment by carlisia** [comment]
I'll close this issue. @WaterKnight1998 feel free to reopen if you still need help.
