### ISSUE TITLE
Installation error: Code=\"InvalidSubscriptionId\" Message=\"The provided subscription identifier 'XXXX-XXXX-XXXX]' is malformed or invalid

### ISSUE THREAD

**Issue by RuBiCK** [vmware-tanzu/velero#2987]
**What steps did you take and what happened:**
Fresh install following the setup documents and using velero install (without helm)

```
velero install \
    --provider azure \
    --plugins velero/velero-plugin-for-microsoft-azure:v1.1.0 \
    --bucket $BLOB_CONTAINER \
    --secret-file ./credentials-velero \
    --backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID[,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID] \
    --snapshot-location-config apiTimeout=240[,resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID] \
    --use-restic \
    --wait

```
The deployment logs show this error:

```
time="2020-10-05T09:06:17Z" level=error msg="Error getting a backup store" backupstoragelocation=default controller=backupstoragelocation error="rpc error: code = Unknown desc = storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"InvalidSubscriptionId\" Message=\"The provided subscription identifier 'READACTED]' is malformed or invalid.\"" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:213" error.function=main.getStorageAccountKey logSource="pkg/controller/backupstoragelocation_controller.go:82"
```
The problem seems to be with `SubscriptionId` that contains a `]`

Related with Issue #1959 that was closed by the user without explaining the solution

**What did you expect to happen:**
I expect the installation to work or be able to change the configuration. I would like to change the subscription ID that the error refers to and this is I have tested so far trying to modify that variable:
* Credentials file is fine
* There is no secrets containing that configuration
* Removed square brackets and install again
* Removed deployment and daemonset and reinstall 

How is supposed I should change the configuration that the error shows as not correct? 
is it ok the configuration documentation using square brackets?

```
    --backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID[,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID] \
    --snapshot-location-config apiTimeout=240[,resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID] \

```

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
See error log entry above

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I think the documentation is not clear. Is the square bracket mandatory or it's a placeholder for some kind of optional parameters?
How the configuration could be modified if credentials file is correctly configured (without square brackets)?

**Environment:**

- Velero version (use `velero version`):  v1.5.1
- Velero features (use `velero client config get features`): NOT SET
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"37c06f456fdb4d25e402b5fbcb72cd6a77a021a9", GitTreeState:"clean", BuildDate:"2020-09-18T21:59:14Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Azure

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by RuBiCK** [comment]
The information that incorrectly placed I was able to change editing de CRD.

As an improvement, I think it should perform some sanity checks before creating the CRD and the possibility to modify the information provided

**Comment by kikolouro** [comment]
Sill got this error today, can you help me resolved it? Do you still remember it? What CRD do i need to change?

**Comment by AndriiPasternak1989** [comment]
I've got the same issue. Could you please advise on what needs to be changed to get this working?
