### ISSUE TITLE
Provider for Openstack Swift/Cinder

### ISSUE THREAD

**Issue by lukastopiarz** [vmware-tanzu/velero#2988]
**Describe the problem/challenge you have**
No provider for Openstack Swift or Cinder storage backend (Or I didn't find any)

**Describe the solution you'd like**
I would highly appreciate provider for Openstack Swift object store

**Anything else you would like to add:**
no

**Environment:**

- Velero version (use `velero version`): 1.4
- Kubernetes version (use `kubectl version`): v1.11.0+d4cacc0
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Openstack
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by pierredadt** [comment]
Hi @lukastopiarz 

I'm currently trying to find a solution to this.  
For your information, here is what I found : 
- https://github.com/Lirt/velero-plugin-swift/  
Up to date and functional ObjectStore for Swift (used for resources backups and eventually restic<sup>[1]</sup> volume backups)
- https://hub.docker.com/r/ciscosso/velero-plugin-openstack
Deprecated ObjectStore for Swift and BlockStore for Cinder.  
Those might be functional but are only compatible with older Velero releases (Ark)
- [1] It seems there is an issue with restic repositories provisioning and communication at the moment, at least in my case. [I already troubleshot the issue](https://github.com/Lirt/velero-plugin-swift/issues/5) and I now have to create an issue here and present it to Velero in a clearer way. 

I'd love to see a community grow around Velero for Openstack, and help in the implementation of a complete plugin (BlockStore + ObjectStore), maybe from the work of https://github.com/Lirt/velero-plugin-swift, so please keep in touch!

**Comment by carlisia** [comment]
@lukastopiarz it is not on our plans to implement/support any additional plugins for Velero. We would love to see the community adding them however.

I added a discussion topic to our next community meeting (tomorrow) asking if we should add the Swift plugin above (thanks for the research @pierredadt!) to our list of plugins, in case you want to attend:

https://hackmd.io/Jq6F5zqZR7S80CeDWUklkA?view

**Comment by Lirt** [comment]
Hello,

I am maintainer of the [swift plugin](https://github.com/Lirt/velero-plugin-swift/). It was done as non-fork, but shares code from the [cisco-sso implementation[(https://github.com/cisco-sso/velero-plugin-openstack) with fixes/updates/addons that were missing after they stopped supporting it and plugin interface changed.

Currently it lacks implementation of block storage (cinder volume backups), but I think I can manage to implement this if you decide, that it is official community supported plugin.

After that I can probably take the role of maintainer.

**Comment by cidsasaki** [comment]
@Igorcezar veja este plugin para o openstack.

**Comment by carlisia** [comment]
@Lirt thank you. Is there any chance you could join our community meeting today?

**Comment by Lirt** [comment]
@carlisia Okay, I will be there.

**Comment by nrb** [comment]
@Lirt @lukastopiarz As discussed in our community meeting, the core maintainer team doesn't have plans to add any OpenStack plugins.

To my knowledge, the Cisco implementation is abandoned - they worked on it, but then dropped it. It may be used as a reference, but it's no longer maintained.

If you'd like for the OpenStack plugin to be documented on our site, please open a PR to add it to the following files as a community supported plugin:

* Add a new file in https://github.com/vmware-tanzu/velero/tree/main/site/content/plugins/list
* Add an entry in https://github.com/vmware-tanzu/velero/blob/main/site/content/docs/main/supported-providers.md and https://github.com/vmware-tanzu/velero/blob/main/site/content/docs/v1.5/supported-providers.md (the latest supported version)

Finally, you can add the `velero-plugin` topic to show up in this list: https://github.com/topics/velero-plugin

Once the PR is merged, it'll then show up with links out to your repository and documentation on our site.

Thanks for your interest and for picking up the OpenStack plugin!
