### ISSUE TITLE
Velero to support active failover to reduce the downtime

### ISSUE THREAD

**Issue by gowrisankar22** [vmware-tanzu/velero#2990]
It would be certainly very nice to mitigate the downtime via an active failover approach. This will be a worth feature add for velero.
https://kubernetes.slack.com/archives/C6VCGP4MT/p1602004864147000

**Comment by eleanor-millman** [comment]
Closing because this will likely not be covered in Velero, but we hope to enable other data protection products in the k8s space to do this well.
