### ISSUE TITLE
Add the ability to add the docker images to the backup as well

### ISSUE THREAD

**Issue by mfuxi** [vmware-tanzu/velero#2994]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
I would like to be able to backup and restore an air-gap cluster from one data center to another cluster in a different data center
For that I must have the docker images together with all the other Kubernetes objects backup

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
The user should be able to add in his backup command another flag something like --images which would then also backup the images into the object storage which he configured.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This is an addition to this issue which was closed a year ago:
https://github.com/vmware-tanzu/velero/issues/464

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by devops-42** [comment]
I'd appreciate (and up-vote) if such a feature would be implemented :)

**Comment by veerendra2** [comment]
Any update on this feature?

**Comment by khandg** [comment]
Is this feature included in the roadmap? This would definitely help and restore can be done without relying on container registry!
