### ISSUE TITLE
Backup to Restic REST server

### ISSUE THREAD

**Issue by stevefan1999-personal** [vmware-tanzu/velero#3000]
**Describe the problem/challenge you have**
I would like to backup to a cheap storage server that unfortunately requires me to use rclone and the Restic REST remote repository to sit in between. Basically it means Velero -> Snapshot -> Restic REST remote repo -> Rclone -> cheap storage server. However, I don't see a clear instruction or indication during my consulation to the documentation for whether this is possible.

Also I uses OpenEBS. Is it possible to combine OpenEBS CSI snapshot to backup the cStor snapshot to the remote rclone-based Restic REST as well? So one copy for local (OpenEBS snapshot) and another one (Restic to cheap storage server) for multi-tier backup (The cheap storage server would be what we call it "cold storage"). This is how I also wanted to mitigate risks by spreading the snapshot replicas over different places.

**Describe the solution you'd like**
If this is not implemented, let's do this!
If this is implemented out of the box, would someone like to document it, nice and clean?

**Environment:**

- Velero version (use `velero version`):
```
Client:
        Version: v1.5.1
        Git commit: 87d86a45a6ca66c6c942c7c7f08352e26809426c
Server:
        Version: v1.5.1
```
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
OpenEBS (with CSI)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by stevefan1999-personal** [comment]
#1178

**Comment by carlisia** [comment]
Hey @stevefan1999-personal, none of what you are asking about is currently possible with Velero. 

We will keep this issue open for a while until we can make a decision about it. Right now I can't say that this would be implemented.

**Comment by dsu-igeek** [comment]
We don't want to add additional Restic features at this time.
