### ISSUE TITLE
Update hashicorp/go-plugin dependency

### ISSUE THREAD

**Issue by sshende-catalogicsoftware** [vmware-tanzu/velero#3009]
**What steps did you take and what happened:**
Installed Velero and triggered the backup for all namespaces. The backup failed with error messages in log files.

**What did you expect to happen:**
For the backup to finish with phase "Completed"

**Anything else you would like to add:**

- The cluster has 1000's of Custom resources which we call "kcas" belonging to group version "cc/v1".

- The backup logs show this error message:

time="2020-10-12T14:29:20Z" level=info msg="Getting items for group" backup=cio/5f84683622c8a8f3fd63b645 group=cc/v1 logSource="pkg/backup/item_collector.go:76"
time="2020-10-12T14:29:20Z" level=info msg="Getting items for resource" backup=cio/5f84683622c8a8f3fd63b645 group=cc/v1 logSource="pkg/backup/item_collector.go:165" resource=kcas
time="2020-10-12T14:29:20Z" level=info msg="Listing items" backup=cio/5f84683622c8a8f3fd63b645 group=cc/v1 logSource="pkg/backup/item_collector.go:291" namespace= resource=kcas
time="2020-10-12T14:29:23Z" level=error msg="Error listing items" backup=cio/5f84683622c8a8f3fd63b645 error="rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (3939450546 vs. 2147483647)" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_collector.go:294" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*itemCollector).getResourceItems" group=cc/v1 logSource="pkg/backup/item_collector.go:294" namespace= resource=kcas

- Is there a configurable parameter to set the maxReceiveMessageSize for gRPC calls? Any other way?

**Environment:**

- Velero version: 1.5.1 
- Kubernetes version 1.18

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by carlisia** [comment]
Hey @sshende-catalogicsoftware, I would try increasing the memory limit on the Velero deployment. There may be a couple of defaults that aren't playing nice together. Let us know if that fixes things.

Instructions: https://velero.io/docs/v1.5/customize-installation/#customize-resource-requests-and-limits

**Comment by ashish-amarnath** [comment]
@sshende-catalogicsoftware We currently don't offer a way to customize the grpc message size for the plugin client.
This is not a limit that many of our users have hit.

However, we should consider updating our [hashicorp/go-plugin](/hashicorp/go-plugin) dependency from
`github.com/hashicorp/go-plugin v0.0.0-20190610192547-a1bc61569a26` to the latest release because there is a fix that might be useful for this. https://github.com/hashicorp/go-plugin/commit/6d2a5564f60a0ff22a42428aa9fdfe48dfeac8df

**Comment by ashish-amarnath** [comment]
I am going to add this to our backlog with the "Enhancement/User" label and remove the "Needs Investigation" label.

**Comment by eleanor-millman** [comment]
Should be addressed by #3710
