### ISSUE TITLE
'velero backup/restore delete' does not remove Disks in Azure cluster

### ISSUE THREAD

**Issue by jbmassicotte** [vmware-tanzu/velero#3010]
I deployed velero in an Azure cluster, following instructions from https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure, using the service principal option. I use velero to backup a namespace which includes Disks (Managed Disks and Azure Files).

Velero works as expected except it leaves behind in the ‘node resource group’  (the group containing the VMs and the disks) a bunch of Disks named ‘kubernetes-dynamic-pvc-XXX’, as well as a bunch of Disks named ‘restore-XXX’, even after having deleted all velero backups and all velero restores. 

What is the trick for getting velero to delete these?

**Comment by jbmassicotte** [comment]
After closer look I discovered this was not an issue with velero, but rather, an issue with my application that leaves behind unused pvc's.

**Comment by carlisia** [comment]
Thanks for letting us know! 👍
