### ISSUE TITLE
Restore is not failing when trying to restore a namespace which does not exist in backup

### ISSUE THREAD

**Issue by email2smohanty** [vmware-tanzu/velero#3013]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
- Created a velero backup which consists of 2 namespaces named `default` and `openshift`
- By mistake when I am restoring namespace `openldap`  which does not exist in backup then the restore is getting complete without any error

**What did you expect to happen:**
- I am expecting as I am trying to restore a namespace `openldap` which does not exist in the backup then the restore should fail with proper error

**Environment:**

- Velero version (use `velero version`): 
Client:
        Version: v1.4.2
Server:
        Version: v1.5.1
- Velero features (use `velero client config get features`):

**Comment by carlisia** [comment]
Hey @email2smohanty, thanks for the report.

Can you please send me the command you used to do the restore? Thank you.

**Comment by email2smohanty** [comment]
@carlisia please find my restore command below

```
velero create restore openshift-operators-restore --from-backup openshift-operators-backup --include-namespaces openshift-operators --include-cluster-resources=true
```

**Comment by nrb** [comment]
@email2smohanty Thanks for the information!

I think this is a reasonable request to enhance Velero. I'll get it moved into the backlog.

**Comment by ashish-amarnath** [comment]
I fully understand why this is happening. Considering that this has not been moved into our backlog it requires no further investigation. Hence removing "Needs Investigation".
