### ISSUE TITLE
Add a warning to the `velero version` cmd when versions don't match

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3017]
I've been seeing a few issues opened with a mismatch in version between Velero client and server. I think there's sufficient coupling between the two that it (the mismatch) could originate the problems being reported.

The `velero version` command should verify any mismatch and warn. Not sure how strong this warning should be. Should it be: "will not work, please update [whichever has the lower version]"?

**Comment by cvhariharan** [comment]
Hi, I can pick this up if this is up for grabs.

**Comment by carlisia** [comment]
Yes, go for it!

**Comment by cvhariharan** [comment]
Here, the warning should be thrown if the versions are not same for the cli and server right?

**Comment by carlisia** [comment]
Yes. I think we should do the match on the minor version only, not the patch. Example: 1.4.1 and 1.4.2 would be a match.
