### ISSUE TITLE
Velero Cluster Migration - Get Access Denied on the  S3 bucket source

### ISSUE THREAD

**Issue by konvergence** [vmware-tanzu/velero#3019]
**What steps did you take and what happened:**

* I try to make a backup restore between 2 cluster
* I follow the doc https://velero.io/docs/v1.5/migration-case/
* I have 2 clusters
  * source : k8s-admin with an S3 user `velero-k8s-admin` and ACL full-control on the bucket `velero-k8s-admin-bucket`
  * target : k8s-rancher with an S3 user `velero-k8s-rancher` and ACL full-control on the bucket `velero-k8s-rancher-bucket`

  * an additional ACL read have been  put to the bucket `velero-k8s-admin-bucket` for the S3 user `velero-k8s-rancher`
```
$  s3cmd -c   info s3://velero-k8s-admin-bucket
s3://velero-k8s-admin-bucket/ (bucket):
   Location:  my-store
   Payer:     BucketOwner
   Expiration Rule: none
   Policy:    none
   CORS:      none
   ACL:       velero-k8s-admin: FULL_CONTROL
   ACL:       velero-k8s-rancher: READ
```

* I check that  the S3 user `velero-k8s-rancher`can read the bucket `velero-k8s-admin-bucket`

```
$ s3cmd ls s3://velero-k8s-admin-bucket/
                       DIR   s3://velero-k8s-admin-bucket/backups/
                       DIR   s3://velero-k8s-admin-bucket/restic/
                       DIR   s3://velero-k8s-admin-bucket/restores
```

* I add a new backup-location to the velero-k8s-rancher

 ```
 velero -n velero-rook backup-location create velero-k8s-admin \
        --access-mode ReadOnly \
        --bucket velero-k8s-admin-bucket \
        --provider aws \
        --config region=region=us-east-1,s3ForcePathStyle=true,s3Url=https://lab-k8s-s3.shuttle-cloud.com/,publicUrl=https://lab-k8s-s3.shuttle-cloud.com/
```

```
$ velero -n velero-rook backup-location get
NAME               PROVIDER   BUCKET/PREFIX               PHASE       LAST VALIDATED                  ACCESS MODE
default            aws        velero-k8s-rancher-bucket   Available   2020-10-20 09:51:20 +0000 UTC   ReadWrite
velero-k8s-admin   aws        velero-k8s-admin-bucket     Available   2020-10-20 09:51:20 +0000 UTC   ReadOnly
```

**What did you expect to happen:**

* I shoud be able to see the bacup from the velero-k8s-admin
* But when I check the velero logs I get this error 

```
time="2020-10-20T09:41:19Z" level=error msg="Error getting backup metadata from backup store" backup=backup-test-ceph-rbd backupLocation=velero-k8s-admin controller=backup-sync error="rpc error: code = Unknown desc = error getting object backups/backup-test-ceph-rbd/velero-backup.json: AccessDenied: \n\tstatus code: 403, request id: tx000000000000000024659-005f8eb0bf-5891d-my-store, host id: " error.file="/go/src/github.com/vmware-tanzu/velero/pkg/persistence/object_store.go:261" error.function="github.com/vmware-tanzu/velero/pkg/persistence.(*objectBackupStore).GetBackupMetadata" logSource="pkg/controller/backup_sync_controller.go:209" 
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 

```
Client:
        Version: v1.5.1
        Git commit: 87d86a45a6ca66c6c942c7c7f08352e26809426c
Server:
        Version: v1.5.1
```
- Velero features (use `velero client config get features`): 

```
features: <NOT SET>
```

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version:` rancher 2.4.5 rke

- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
````

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by konvergence** [comment]
Some news ...

I tried some updates, but I still the error "Access Denied"

* I change the backup-location, cause of bad region

```
velero -n velero-rook backup-location create velero-k8s-admin \
       --access-mode ReadOnly \
       --bucket velero-k8s-admin-bucket \
       --provider aws \
       --config region=region=us-east-1,s3ForcePathStyle=true,s3Url=https://lab-k8s-s3.shuttle-cloud.com/,publicUrl=https://lab-k8s-s3.shuttle-cloud.com/
```
* I force FULL_CONTROL ACL on the bucket for velero-k8s-rancher
```
$ s3cmd info s3://velero-k8s-admin-bucket/
s3://velero-k8s-admin-bucket/ (bucket):
   Location:  my-store
   Payer:     BucketOwner
   Expiration Rule: none
   Policy:    none
   CORS:      none
   ACL:       velero-k8s-admin: FULL_CONTROL
   ACL:       velero-k8s-rancher: FULL_CONTROL

```

**Comment by konvergence** [comment]
Hi all,

I made some test with minio instead of radosgw and it works !!
```
k8s-rancher@lab-k8s-admin:~$ velero -n velero-rook backup-location get
NAME               PROVIDER   BUCKET/PREFIX               PHASE       LAST VALIDATED                  ACCESS MODE
default            aws        velero-k8s-rancher-bucket   Available   2020-10-20 16:17:59 +0000 UTC   ReadWrite
velero-k8s-admin   aws        velero-k8s-admin-bucket     Available   2020-10-20 16:18:08 +0000 UTC   ReadOnly
k8s-rancher@lab-k8s-admin:~$ velero -n velero-rook get backup
NAME                   STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
backup-test-ceph-rbd   Completed   0        0          2020-10-20 16:11:00 +0000 UTC   29d       velero-k8s-admin   <none>
````


So the issue is well on the ACL side with radosgw

**Comment by konvergence** [comment]
Sorry, I didn't try the restore . But with minio, have another ACL issue.

I can see the backup from the source backup-location
But When I try a restrore I get this error

```
de = Unknown desc = error putting object restores/backup-test-ceph-rbd-20201020164202/restore-backup-test-ceph-rbd-20201020164202-results.gz: AccessDenied: Access Denied.\n\tstatus code: 403, request id: 163FC0EE915F1551, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:257" error.function="main.(*ObjectStore).PutObject" logSource="pkg/controller/restore_controller.go:518"
```

the velero target use an S3 user that have a full access to his bucket (velero-k8s-rancher) bu readonly access on the source s3 (velero-k8s-admin)

Does velero try to write "restore information" into the source S3 ?

**Comment by konvergence** [comment]
I confirm that after modify acl on minio
I discover that velero write restore information into the <S3 source>/restore

That is for me a bug. Because the backup-location is in "ReadOnly". Velero should write the restore information into the default backup-location

**Comment by zubron** [comment]
Hi @konvergence - given that you've opened a feature request issue to address this in #3026, I don't think there's anything else actionable from the Velero team here so I'm going to close this issue in favour of that new one. Feel free to reopen though if there is something separate that needs to be addressed here.

**Comment by konvergence** [comment]
Sorry
But how to explain that velero write /restores into the source bucket. And also write into /restic into the source bucket

**Comment by zubron** [comment]
Hi @konvergence. Velero does not separate the backup and restore data at this time. When you perform a backup from a particular backup storage location, the logs and results for restores from those backups are written to the same storage location. In your case, you would likely need to grant permissions to the `velero-k8s-rancher` user to write to the `velero-k8s-admin-bucket` as a workaround.
