### ISSUE TITLE
Missing Image from Documentation for Backup Workflow

### ISSUE THREAD

**Issue by blueelvis** [vmware-tanzu/velero#3020]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

1. Visited [https://velero.io/docs/v1.5/how-velero-works/](https://velero.io/docs/v1.5/how-velero-works/)
2. Scroll down to the section of **Backup Workflow**

You will notice that the image doesn't load and give a HTTP 404.

**What did you expect to happen:**
An image is displayed with the Backup Workflow.

**Comment by dsu-igeek** [comment]
Thanks!
