### ISSUE TITLE
Restic volume backups don't work because restic repositories are never initialized

### ISSUE THREAD

**Issue by pierredadt** [vmware-tanzu/velero#3021]
**What steps did you take and what happened:**  
When using objectstore/restic for volumes backups, Velero doesn't automaticaly create the needed restic repositories and volumes backups fail.

- Install Velero 1.5 with restic enabled  
```shell
$ velero install \     
  --use-restic \             
  --use-volume-snapshots=false \
  --no-default-backup-location \
  --namespace=velero
```
- Install [Velero plugin for Openstack Swift](https://github.com/Lirt/velero-plugin-swift/) v0.1.1
  - `$ velero plugin add lirt/velero-plugin-swift:v0.1.1`
  - Inject Openstack authentication variables in Velero
- Create a bucket in Swift for resources backups (`velero-backups`)
- Create a bucket in Swift for restic volume backups (`velero-volumes`)
- Create a default BackupStorageLocation referencing those
```shell
$ cat <<EOF | k -n velero apply -f -
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  config:
    resticRepoPrefix: swift:velero-volumes:/public/
  objectStorage:
    bucket: velero-backups
    prefix: public
  provider: swift
EOF
```
- Annotate a pod for a restic volume backup  
```shell
$ k -n test-velero annotate pod ubuntu-75d9d656-29mbr backup.velero.io/backup-volumes=test-vol
pod/ubuntu-75d9d656-29mbr annotated
$ k -n test-velero get pods ubuntu-75d9d656-29mbr -o yaml | grep -A 1 "annotations:\| volumes:"
  annotations:
    backup.velero.io/backup-volumes: test-vol
--
  volumes:
  - name: test-vol
```
- Create a backup of the test-velero namespace 
```shell
$ velero backup create test-velero-backup --include-namespaces=test-velero
```
- The backup partially fails because of the restic volume backup. The `resticrepositories.velero.io` resource is created in kubernetes, but there is no restic repositorie created in Openstack Swift.
The restic repository is never initialized and Velero fails to communicate with it when trying `lock`/`check`/`snapshot` commands.

**What did you expect to happen:**  
When ensuring the restic repository is available, Velero should initialize it if not found.  
Once created by Velero, the restic repo should be `Ready` and the backup should work as intended.

**The output of the following commands will help us better understand what's going on**:  

- [`kubectl logs deployment/velero -n velero`](https://gist.github.com/pierredadt/b24d4218bd6a10bc0d73f9515b451662#file-velero-logs)
- [`velero backup describe <backupname>`](https://gist.github.com/pierredadt/b24d4218bd6a10bc0d73f9515b451662#file-backup-description)
- [`velero backup logs <backupname>`](https://gist.github.com/pierredadt/b24d4218bd6a10bc0d73f9515b451662#file-backup-logs)
- (No restore created)
- [`kubectl describe resticrepositories.velero.io -n velero`](https://gist.github.com/pierredadt/b24d4218bd6a10bc0d73f9515b451662#file-resticrepository-description)

**Anything else you would like to add:**
- The plugin used for Openstack Swift object storage is functionnal
- When triggering the backup, a `resticrepositories.velero.io` is created in the Velero namespace for the `test-velero` restic backup but it's `NotReady`
- The step that's not working should be:
  - The restic repository controller initializes the `resticrepositories.velero.io` ("Initializing restic repository")<sup>[[1](https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/restic_repository_controller.go#L157)]</sup>  
  - It then ensures the repo actually exists trying to connect to it (`restic snapshot --last` command)<sup>[[2](https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/restic_repository_controller.go#L192)][[3](https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/restic_repository_controller.go#L205-L219)][[4](https://github.com/vmware-tanzu/velero/blob/28a46d3a8b4903ffa6a60b2076821e88e8f6983d/pkg/restic/repository_manager.go#L186-L198)]</sup>  
  - As the repo doesn't exist, the error message should contain `Is there a repository at the following location?`. When detecting this message, Velero should initializes the repo<sup>[[5](https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/restic_repository_controller.go#L211-L213)]</sup>
  - During next checks, the repo should be available, the `resticrepositories.velero.io` phase should be `Ready`, and the restic backup should work
- With the given configuration, trying the same process as above with the restic docker gives the following result:
```shell
$ docker run -ti --env-file os_envs.env -v /tmp/velero:/cache -v /tmp/password.txt:/tmp/password.txt restic/restic:0.9.6 snapshots --repo=swift:velero-volumes:/public/test-velero --password-file=/tmp/password.txt --cache-dir=/cache --last
Fatal: unable to open config file: conn.Object: Object Not Found
Is there a repository at the following location?
swift:velero-volumes:/public/test-velero
```

**Environment:**

- Velero version: 
```shell
$ velero version
Client:
	Version: v1.5.1
	Git commit: 87d86a45a6ca66c6c942c7c7f08352e26809426c
Server:
	Version: v1.5.1
```
- Velero features:
```shell
$ velero client config get features
features: <NOT SET>
``` 
- Kubernetes version (use `kubectl version`):
```shell 
$ k version     
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
```shell
Kubespray v2.12.0
```
- Cloud provider or hardware configuration:
```shell
OVH Openstack
```
- OS (e.g. from `/etc/os-release`):
```shell
Container Linux by CoreOS 2345.3.0 (Rhyolite), kernel 4.19.106-coreos
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ashish-amarnath** [comment]
@pierredadt Looking at the error
```
time="2020-10-20T10:35:41Z" level=error msg="Error checking repository for stale locks" controller=restic-repository error="error running command=restic unlock --repo=swift:velero-volumes:/public/test-velero --password-file=/tmp/velero-restic-credentials-test-velero912516622 --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: unable to open repo at swift:velero-volumes:/public/test-velero: conn.Authenticate: Bad Request\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/repository_manager.go:286" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryManager).exec" logSource="pkg/controller/restic_repository_controller.go:144" name=test-velero-default-xksgg namespace=velero
```

From the error message this seems like an issue authenticating with the object store where the restic repository is to be created.

Considering that you are using `lirt/velero-plugin-swift:v0.1.1`, a plugin that is not supported by the Velero team it is difficult to troubleshoot and make remidial suggestions on possible issues.
Here is a link to configure this plugin correctly. https://github.com/Lirt/velero-plugin-swift#configure that you might find useful.

Also suggest engaging with folks in https://github.com/Lirt/velero-plugin-swift to get better suggestions.

I am going to close this issue as this is not actionable by the Velero team. Please re-open or reach out if you have further questions.

**Comment by pierredadt** [comment]
@ashish-amarnath 
Please have a look at https://github.com/Lirt/velero-plugin-swift/issues/5 and reconsider
I 'am already talking with Lirt, we troubleshot the issue from the plugin perspective, and the reason I even come here knowing I'm using an unsupported plugin is because I already made the actions you're talking about.

There is no reason I'd come to your repo and place an issue without looking at my plugins beforehand.

**Comment by ashish-amarnath** [comment]
@pierredadt I did look at the details in this issue and now also the issue from the velero-plugin-swift repo.

Based on you BackupStorageLocation
```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  config:
    resticRepoPrefix: swift:velero-volumes:/public/
  objectStorage:
    bucket: velero-backups
    prefix: public
  provider: swift
```
and the code that generates the restic repository identifier [`GetRepoIdentifier`](https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/restic_repository_controller.go#L169) and the `restic/` subdirectories is coming from 
[`subdirs`](https://github.com/vmware-tanzu/velero/blob/main/pkg/persistence/object_store_layout.go#L40).

The restic repository identifier has to be in the format `<PROVIDER>:<BUCKET>:/restic/<NAMESPACE>` which in this case should be `swift:velero-backups:/restic/test-velero` not sure where `swift:velero-volumes:/public/test-velero` is coming from. 

I would also suggest creating a backup storage location using another bucket or another prefix to see if there was any stale data in the bucket that you are trying to use.

The storage and the plugin are both abstract to us, making remote troubleshooting and debugging extra difficult. 
Considering that we already have a growing support backlog for the things that we do support, our spare support bandwidth is rather limited at the moment. For that reason, unfortunately, we might not be able to fully help you with this and re-open this issue.

You can also try posting about this in our [#velero](https://kubernetes.slack.com/archives/C6VCGP4MT) slack channel to see if there are other folks in the community who might offer some troubleshooting/debugging steps. If there are changes that have to be made to Velero to accommodate this, we will definitely consider those when proposed.

It might help if you would drop by during our office hours with this to try and troubleshoot this.

You can find information about our office hours on [our community page](https://velero.io/community)

**Comment by pierredadt** [comment]
@ashish-amarnath many thanks for taking the time to look at the orginal issue and give details on your analysis, it means a lot!

> The restic repository identifier has to be in the format <PROVIDER>:<BUCKET>:/restic/<NAMESPACE> which in this case should be swift:velero-backups:/restic/test-velero not sure where swift:velero-volumes:/public/test-velero is coming from

Installing via `--provider --plugin --bucket` does not generate a complete BackupStorageLocation, so the `config.resticRepoPrefix` was set in accordance with what I understood of the Velero/restic configuration. The sources references you gave me are enlightening, and I now understand better how all of this is supposed to behave.

For you info, respecting the models `<PROVIDER>:<BUCKET>:/` or `<PROVIDER>:<BUCKET>:/restic/` for `config.resticRepoPrefix` didn't help, the errors and logs are still the same.

---

> The storage and the plugin are both abstract to us, making remote troubleshooting and debugging extra difficult.

I totally understand the difficulties here, and Openstack being one of the rare free and opensource cloud/infrastructure provider, if not the only one, I feel it is extremely important to support it (a lot of people have self-hosted and self-managed clusters over Openstack for security or financial motives). 

That's the reason I engaged with Lirt in the first place: I want to see a complete and functional solution for Openstack emerge (objectstore backups, blockstore volume snapshots AND restic volume backups), and I'm ready to help with the process.

I'm far from fluent in golang but I can help with test cases and debugging using my infrastructure. 

I'll have a look at the Slack, and keep in touch with Lirt, and I really hope we all can help each other bringing 100% of Velero capabilities to Openstack clusters.

**Comment by iruizr7** [comment]
For anyone digging in the issues in order to debug restic backups to openstack swift. It's tricky, but it works.
Installing Velero from Helm, using the following `values.yaml` content, it installs and works correctly.
```
deployRestic: true
snapshotsEnabled: false
credentials:
  extraSecretRef: "velero-credentials"
configuration:
  provider: community.openstack.org/openstack
  backupStorageLocation:
    bucket: velero-hot-backups
    prefix: public_resources
    config:
      resticRepoPrefix: swift:velero-hot-backups:/restic/velero
initContainers:
  - name: velero-plugin-openstack
    image: lirt/velero-plugin-for-openstack:v0.3.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
```

But the `resticRepoPrefix` ***HAS** to be that exact way, no other creative forms. Just a little bit finicky.
