### ISSUE TITLE
[AKS] [Velero] Velero deployment configuration with "SET" - No Velero pods deployed !

### ISSUE THREAD

**Issue by JeremyBouchet** [vmware-tanzu/velero#3022]
**What steps did you take and what happened:**
I try to declare the configuration of Velero with the usage of "SET" as you can see below but when I deployed this one with Terraform no deployment and no pods were deployed :

`resource "helm_release" "velero" {
  depends_on = [kubernetes_secret.velero_cloud_credentials]

  name       = "velero"
  chart      = "velero"
  repository = "https://vmware-tanzu.github.io/helm-charts"
  version    = "2.12.0"
  namespace  = kubernetes_namespace.velero.metadata[0].name
  timeout    = 1200

  set {
    name  = "velero.credentials.existingSecret"
    value = kubernetes_secret.velero_cloud_credentials.metadata.0.name
  }

  set {
    name = "velero.configuration.backupStorageLocation.name"
    value = "azure"
  }`

**What did you expect to happen:**
I expected that a Velero deployment and Velero pods would have been created.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
Error from server (NotFound): deployments.apps "velero" not found
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
No Velero pods...
- `velero backup logs <backupname>`
No Velero pods...
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
No Velero pods...
- `velero restore logs <restorename>`
No Velero pods...

**Anything else you would like to add:**
- Velero is deployed with Terraform v. 0.12.29 and with helm v. 3.2.4

- You can see below my declaration of the Velero resource in Terraform files :

`resource "helm_release" "velero" {
  depends_on = [kubernetes_secret.velero_cloud_credentials]

  name       = "velero"
  chart      = "velero"
  repository = "https://vmware-tanzu.github.io/helm-charts"
  version    = "2.12.0"
  namespace  = kubernetes_namespace.velero.metadata[0].name
  timeout    = 1200

  set {
    name  = "velero.credentials.existingSecret"
    value = kubernetes_secret.velero_cloud_credentials.metadata.0.name
  }

  set {
    name = "velero.configuration.backupStorageLocation.name"
    value = "azure"
  }

  set {
    name  = "velero.configuration.backupStorageLocation.config.resourceGroup"
    value = azurerm_resource_group.velero_backup.name
  }

  set {
    name  = "velero.configuration.backupStorageLocation.config.storageAccount"
    value = azurerm_storage_account.velero_backup.name
  }

  set {
    name  = "velero.configuration.backupStorageLocation.bucket"
    value = azurerm_storage_container.velero_backup.name
  }

  set {
    name = "velero.configuration.volumeSnapshotLocation.name"
    value = "azure"
  }
  
  set {
    name  = "velero.configuration.volumeSnapshotLocation.config.resourceGroup"
    value = azurerm_kubernetes_cluster.aks_02.node_resource_group
  }

  set {
    name  = "velero.schedules.lbn.schedule"
    value = "0 0 * * *"
  }

  set {
    name  = "velero.schedules.lbn.template.ttl"
    value = "720h"
  }

  set {
    name  = "velero.schedules.lbn.template.includedNamespaces"
    value = "*"
  }

  set {
    name  = "velero.schedules.lbn.template.snapshotVolumes"
    value = true
  }

}
`

**Environment:**

- Velero version (use `velero version`): 1.5.1
- Velero features (use `velero client config get features`): not possible (Velero is not deployed)
- Kubernetes version (use `kubectl version`): Server : 1.17.9 and client : 1.16.15
- Kubernetes installer & version: AKS 1.17.9
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): aks-ubuntu-1604-2020-q3 (2020.09.23)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ashish-amarnath** [comment]
@JeremyBouchet Installation using terraform is not an install method that we currently support and are unfortunately not able to make suggestions or troubleshoot. Please refer to https://velero.io/docs/v1.5/basic-install/ for all the supported install options.

You might also want to install using the supported installation options and then transition to using terraform.

I am going to close this issue. Please re-open or reach out if we can help with anything Velero related.

**Comment by seboss666** [comment]
Hello,
We are just using terraform as a helper, it's using the helm provider that is meant to be a supported installation method (or else you should not provide https://vmware-tanzu.github.io/helm-charts/) . We don't exclude a problem with some of the parameters, and this is where you can provide insight on what should be included that we may omit.
