### ISSUE TITLE
[Query|Question]Restore Hook init container execution priority w.r.t pods init container

### ISSUE THREAD

**Issue by rahulgit1988** [vmware-tanzu/velero#3028]
This Is just a query about the priority of init container execition in restore hook.
As per Velero Doc:
_*InitContainer Restore Hooks*
Use an InitContainer hook to add init containers into a pod before it’s restored. You can use these init containers to run any setup needed for the pod to resume running from its backed-up state._

As per restore hook design Doc:
https://github.com/vmware-tanzu/velero/blob/main/design/restore-hooks.md
_If initContainers are specified for a pod, Velero will inject the containers into the beginning of the pod's initContainers list._

Please confirm what will the priority order of init container execution, Which one will be run first?
Example: 
Restore hook ===>Hook Injected Init container ====>Pods Init Container===>Pod Run======>

**Comment by ashish-amarnath** [comment]
@rahulgit1988 Thanks for reporting this. I have PR #3030 to clarify this documentation.
Pasting the answer here for quick reference.
>The InitContainer added by the restore hook will be the first init container in the `podSpec` of the restored pod.
In the case where the pod had volumes backed up using restic, then, the restore hook InitContainer will be added after the `restic-wait` InitContainer.
