### ISSUE TITLE
Velero will not start working with self-signed certificates and Minio

### ISSUE THREAD

**Issue by veikesaar** [vmware-tanzu/velero#3032]
**What steps did you take and what happened:**
Installed the Velero backup solution that needs to work with a local Minio cluster over HTTPS that uses a self-signed certificate to a local Kubernetes Cluster according to [Quick start evaluation install with Minio](https://velero.io/docs/v1.5/contributions/minio/) and [Use Velero with a storage provider secured by a self-signed certificate](https://velero.io/docs/main/self-signed-certificates/). However the backups do not work, as the logs indicate that the BackupStorageLocation custom resource has an invalid key - caCert. 

Commands that I ran:

Command to install Velero:
velero install \\
    --provider aws \\
    --plugins velero/velero-plugin-for-aws:v1.0.0 \\
    --bucket velero \\
    --secret-file ./credentials-velero \\
    --use-volume-snapshots=true \\
    --use-restic  \\
    --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=https://minio.domain.local \\
    --snapshot-location-config region="default" \\
    --cacert ./bundle.pem

The command to make the actual backup:
velero backup create test1 --namespace=dash

**What did you expect to happen:**
Upon running the create backup command, a backup would be created and stored in the Minio cluster.

**The output of the following commands will help us better understand what's going on**:
Logs:
https://gist.github.com/veikesaar/3aeeeb658c3cce7c3d7f7bc66acc4192

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
An error occurred: backups.velero.io "test" not found
- `velero backup logs <backupname>`
Backup "test" does not exist.
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
An error occurred: restores.velero.io "test" not found
- `velero restore logs <restorename>`
Restore "test" does not exist.

**Anything else you would like to add:**
I did get it to work on another cluster where we do not use a Minio cluster and so could use HTTP over port 9000 and it works just fine.

**Environment:**

- Velero version (use `velero version`): Client and server v1.5.1
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.16.4
- Kubernetes installer & version: kubeadm v1.16.4
- Cloud provider or hardware configuration: Own hardware, 2x CPUs and 4GB RAM on Master and 2x CPUs and 16GB RAM on workers
- OS (e.g. from `/etc/os-release`): CentOS Linux release 7.7.1908 (Core)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by jenting** [comment]
@veikesaar I think you have to bump velero-plugin-for-aws version to v1.1.0, the v1.0.0 does not supports custom CA certificate.

**Comment by ashish-amarnath** [comment]
@veikesaar
Please follow @jenting's suggestion to use the `v1.1.0` version of the `velero-plugin-for-aws`.
Further, you can also find instructions on how to setup minio with a custom ca cert to work with Velero on our [FAQ](https://github.com/vmware-tanzu/velero/wiki/Contributing-FAQ#how-do-i-use-minio-with-https-using-a-custom-ca-as-an-object-store-for-velero)? Please use these to verify your setup.

**Comment by veikesaar** [comment]
@jenting suggestion to upgrade the `velero-plugin-for-aws` to `v1.1.0` did solve the issue of `config has invalid keys [caCert];`. Also, @ashish-amarnath your FAQ link is much appreciated. Thank you both for answering so quickly.

However, I am stuck now on another issue. When I install velero with the command, that I got from the FAQ. The logs are unfortunately kind of nondescript on the underlying issue. 

I install Velero and start getting in the logs errors about the storage being inaccessible. The credentials are correct, double checked. When I try to make a backup, it states that it started, but nothing appears in Minio and no backups are really created. The output of the describe commands are the same as before.

* Command used:
velero install \\
    --provider aws \\
    --plugins velero/velero-plugin-for-aws:v1.1.0 \\
    --bucket velero \\
    --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=https://minio.domain.local \\
    --snapshot-location-config region=default \\
    --secret-file ./credentials-velero \\
    --image velero/velero:main \\
    --cacert ./bundle.pem

velero backup create test --namespace=dash

* Logs:
 https://gist.github.com/veikesaar/6c49c4526653b8159a090740cd8b8469

* What I hoped for:
Velero gets installed on K8s cluster and would allow the creation of backups.

**Comment by jenting** [comment]
@veikesaar Have you tried the newest release version v1.5.2?

**Comment by veikesaar** [comment]
@jenting Thank you for bring into my attention that there was a new version available. I upgraded, but alas the problem persists - the logs continue showing the same error: 

level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"

Is there any way to increase the logging level, i.e. get it to debug? Maybe I could see what the root of the problem might be then in the Velero pod logs?

**Comment by ashish-amarnath** [comment]
@veikesaar This has instructions on how to enable debug logging https://velero.io/docs/v1.5/troubleshooting/#getting-velero-debug-logs

**Comment by ashish-amarnath** [comment]
@veikesaar I suggest running this with debug logging to get more info about what might be happening.

**Comment by veikesaar** [comment]
@ashish-amarnath I have added the command necessary to get the log to show debug level issues, but unfortunately I could not read out the root cause from it. I have included a link to the logs below. 

* Logs:
https://gist.github.com/veikesaar/be06401d605560cf8c540a2906c11a18

**Comment by ashish-amarnath** [comment]
@veikesaar Looking at the logs, I don't see any errors that may have occurred.
These log lines
```
time="2020-10-26T13:50:09Z" level=debug msg="Verifying backup storage location" backupstoragelocation=default controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:98"
time="2020-10-26T13:50:09Z" level=debug msg="Backup location verified and it is valid" backupstoragelocation=default controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:110"
```
suggest that the default backup storage location has been validated and is "online" or "available".

Are you seeing any errors when you run `velero backup create`, `velero backup get`, or `velero backup download`?

**Comment by veikesaar** [comment]
@ashish-amarnath Could this be an issue with Minio being clustered? I thought at first, that it might be due to the fact that I was using HTTPS to connect, but I also tried to change the s3Url to directly Minio port 9000 and using HTTP. Still the same issue. I will try tomorrow in the same environment to setup a single not clustered Minio server and test the config against that.

`velero backup create test --namespace=dash`
`Backup request "test" submitted successfully.`

`velero backup get test`
`An error occurred: backups.velero.io "test" not found`

`velero backup download test`
`An error occurred: backups.velero.io "test" not found`

**Comment by ashish-amarnath** [comment]
@veikesaar Yes, please try to repro this in a simple environment before expanding scope.
I took another look at the logs that you shared earlier but didn't find logs pertaining to running the `velero backup create` command.
Can you also please share logs from the velero deployment from the time the `velero backup create` command was run?

**Comment by veikesaar** [comment]
@ashish-amarnath So I figured it out. The problem was that I was using the `--namespace` flag to indicate which namespace I would like to have the backup made of, but in Velero's case it is used to indicate the namespace Velero itself should work in. The correct flag to use is `--include-namespaces`. After that the backup is made of the selected namespace and stored in Minio, including when Minio is clustered and serving over HTTPS behind a load balancer. `velero backup create` also worked without problems. 

The unfortunate thing is that in the Velero pod's logs there is still the message that there are no backup locations available after making the backups. Is there a possibility to remove this log entry, as it could act as a red herring in future troubleshooting.  I also will link the logs of the successful attempt:

* Command:
`velero backup create dash --include-namespaces dash`
`velero backup describe dash`

Name:         dash
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.16.4
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=16

Phase:  Completed

Errors:    0
Warnings:  0

Namespaces:
  Included:  dash
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2020-10-27 09:50:37 +0200 EET
Completed:  2020-10-27 09:50:39 +0200 EET

Expiration:  2020-11-26 09:50:37 +0200 EET

Total items to be backed up:  37
Items backed up:              37

Velero-Native Snapshots: <none included>

* Logs:
https://gist.github.com/veikesaar/86eb7450e24db68428bace1da3d13bab#file-logs-from-velero-txt

**Comment by ashish-amarnath** [comment]
@veikesaar Thank you for confirming. THe fact that you are able to take successful backups is an indication that the backup storage location is available.
I am guessing that you are referring to this log message
```
time="2020-10-27T07:50:25Z" level=info msg="No backup locations were ready to be verified" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:120"
```

I can understand how that log message can be confusing. I will be fixing that in a PR with other log message cleanup.
I am going to close this issue as resolved. Please reach out if you have more questions or need more help.
