### ISSUE TITLE
Do we require minio installed on each cluster separately where we are using velero for backup and restore.

### ISSUE THREAD

**Issue by Shilpa418** [vmware-tanzu/velero#3038]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I have installed velero with minio storage successfully on one of my OCP cluster.
Now I installed velero on some other cluster, I want to use same Minio storage installed earlier to use here as well for taking backups.

I tried running below command to install velero:

./velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.0.0 --bucket velero-backup --secret-file ./credentials-velero --use-volume-snapshots=false --use-restic --backup-location-config region=minio,s3ForcePathStyle=true,s3Url=http://minio.velero.svc:9000,publicUrl=http://velero-minio-lb-velero.apps.dev01.ocp.corp.amdocs.com:9000

Installation is successfull.
But velero log will show errors as below:

time="2020-10-23T10:14:41Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = RequestError: send request failed\ncaused by: Get http://minio.velero.svc:9000/velero-backup?delimiter=%2F&list-type=2&prefix=backups%2F: dial tcp: lookup minio.velero.svc on 172.30.0.10:53: no such host" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"

Also tried changing s3Url to be same as publicUrl:http://velero-minio-lb-velero.apps.dev01.ocp.corp.amdocs.com:9000

In this case velero log will show errors as below:

time="2020-10-23T11:05:04Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = SerializationError: failed to decode REST XML response\n\tstatus code: 200, request id: \ncaused by: XML syntax error on line 72: element <meta> closed by </head>" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"

**What did you expect to happen:**

I must be able to use existing minio storage for velero installed on other clusters.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.5.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):v1.16.2+45a4ac4
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by dsu-igeek** [comment]
The s3URL "s3Url=http://minio.velero.svc:9000" is configured to talk to the local minio service in your K8S cluster, but you want to talk to the Minio in the other cluster.  Please set the s3URL parameter to http://velero-minio-lb-velero.apps.dev01.ocp.corp.amdocs.com:9000.  The publicURL is required if your s3URL is accessible outside the cluster.  Closing for now, please re-open if this doesn't fix your issue.
