### ISSUE TITLE
Add link to the sample yaml config files to "Examples" docs page

### ISSUE THREAD

**Issue by mamiu** [vmware-tanzu/velero#3040]
**Describe the problem/challenge you have**
The [Examples page](https://velero.io/docs/v1.5/examples/) in the docs just says:

> After you set up the Velero server, try these examples:

...without mentioning where these files come from. It's not as obvious as it could be.

**Describe the solution you'd like**

Make it more obvious. E.g.

```bash
# clone the examples
git clone https://github.com/vmware-tanzu/velero.git

# then the examples from the docs page (but with `velero` at the beginning of the path):
kubectl apply -f velero/examples/nginx-app/base.yaml
# etc. (all the other commands from the page)

# remove velero git repository after using the examples
rm -rf ./velero
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by MadhavJivrajani** [comment]
Hi,
Can I work on this?

**Comment by zubron** [comment]
Hi @MadhavJivrajani! Of course, that would be great :) I'll assign the issue to you. Let us know if you need any assistance.
