### ISSUE TITLE
[Advice] Plugin example - storing map of snapshots/volumes

### ISSUE THREAD

**Issue by Lirt** [vmware-tanzu/velero#3041]
Hello Velero community,

I'm implementing Openstack plugin for Velero and I have a question about the [plugin example repository](https://github.com/vmware-tanzu/velero-plugin-example).

In the plugin example you encourage developers to create object for [Snapshot](https://github.com/vmware-tanzu/velero-plugin-example/blob/main/internal/plugin/volumesnapshotterplugin.go#L38) and [Volume](https://github.com/vmware-tanzu/velero-plugin-example/blob/main/internal/plugin/volumesnapshotterplugin.go#L32) that is then used (and stored) as a [map in Snapshotter object](https://github.com/vmware-tanzu/velero-plugin-example/blob/main/internal/plugin/volumesnapshotterplugin.go#L47). 

My question here is what happens when Velero restarts? I assume the map of volumes and snapshots will be lost. What looks like an issue for me is that the example uses these maps in multiple places and relies on it:
- [GetVolumeInfo](https://github.com/vmware-tanzu/velero-plugin-example/blob/main/internal/plugin/volumesnapshotterplugin.go#L103)
- [CreateVolumeFromSnapshot](https://github.com/vmware-tanzu/velero-plugin-example/blob/main/internal/plugin/volumesnapshotterplugin.go#L84)

I checked how are other plugins implementing this interface and none of them (AWS, GCP, Azure) is storing any snapshot/volume related information and relies solely on API calls to get the snapshot/volume state.

Should I store any information in those objects or is it actually a bad practice to do so?

**Comment by dsu-igeek** [comment]
The plugins get restarted quite frequently, at least once per backup, so any in-memory structures are going to be lost.  The other plug-ins rely on the storage system to maintain snapshots.

It's important to consider how snapshot "durability" is achieved.  When you're making a backup, you will want to be able to recover from scenarios like the loss of the primary storage.  If the snapshot is not made "durable" and only stored in the primary storage then you're not really making a backup.  My understanding is that OpenStack is only going to take a local snapshot, not move it to another storage system.  We faced similar challenges with vSphere and in the Velero Plug-in for vSphere (https://github.com/vmware-tanzu/velero-plugin-for-vsphere) and inside the plug-in we move data to S3.

**Comment by dsu-igeek** [comment]
Let's take additional discussion to the group or Slack channel (https://velero.io/community/)

**Comment by Lirt** [comment]
My question is code-oriented. The storage I meant was using golang [in-memory variable](https://github.com/vmware-tanzu/velero-plugin-example/blob/main/internal/plugin/volumesnapshotterplugin.go#L47) to store list of volumes or snapshots (their names, types, AZ, iops as in [example](https://github.com/vmware-tanzu/velero-plugin-example/blob/main/internal/plugin/volumesnapshotterplugin.go#L32)).

The durability in Openstack is handled by making volume from snapshot (basically backup). There is no issue with this.

Can we reopen? If I am right, we should change the plugin example to not really store the volume/state in variables, but rely on API calls and recheck the state of snapshot or volume all the time functions are called .
