### ISSUE TITLE
How up to modify the expire time of a backup

### ISSUE THREAD

**Issue by jbmassicotte** [vmware-tanzu/velero#3042]
Here is a situation:

I have a backup which is about to expire, but realize I need to keep it past the scheduled expiration date. **How can I do that?**

I tried ‘kubectl edit’ to extend the TTL value of the backup resource, but velero seemed to ignore that new value and proceeded to deleting the backup.

I want to emphasize how real this need is. We have lots of data and cannot afford keeping large amount of data for too long. Imagine we have a major failure that requires time to rebuilt the environment. By the time we are ready to restore the backup the expiration date might have gone by.

**Comment by ashish-amarnath** [comment]
@jbmassicotte 
As you may already know, you can use the `--ttl` flag to the `velero backup create` command.

Now, wrt to extending the expiration of the backup there are two scenarios. I will elaborate on each of them in detail below.
1. Backups created in the same cluster.
    These are the backups created to backup workloads running in the cluster. These are created using the `velero backup create` command.
    TTL for these can be controlled using the `--ttl` flag to the same command.
    The expiration for these backups can be updated using the `kubectl -n velero edit backup <backupName>` command. This update will be honored by Velero. Here is an example.
    ```bash
    $ velero backup create b4 --include-namespaces csi-app --ttl 7m --wait
    Backup request "b4" submitted successfully.
    Waiting for backup to complete. You may safely press ctrl-c to stop waiting - your backup will continue in the background.
    .......
    Backup completed with status: Completed. You may check for more information using the commands `velero backup describe b4` and `velero backup logs b4`.
    $ velero backup get
    NAME   STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
    b4     Completed   0        0          2020-10-26 14:06:28 -0700 PDT   6m        default            <none>
    ```
    The logs from the backup gc-controller indicating the 6m expiry
    ```
    time="2020-10-26T21:10:40Z" level=debug msg="Backup has not expired yet, skipping" backup=velero/b4 controller=gc expiration="2020-10-26 14:13:28 +0000 UTC" logSource="pkg/controller/gc_controller.go:131"
    ```
    Now updating the expiry on the backup `b4` using the command `kubectl -n velero edit backup b4`
    ```bash
    $ velero backup get
    NAME   STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
    b4     Completed   0        0          2020-10-26 14:06:28 -0700 PDT   2y        default            <none>
    ```
    Again the logs from the backup gc-controller indicating the 2y expiry
    ```
    time="2020-10-26T21:10:50Z" level=debug msg="Backup has not expired yet, skipping" backup=velero/b4 controller=gc expiration="2022-10-26 21:13:28 +0000 UTC" logSource="pkg/controller/gc_controller.go:131"
    ```

1. Backups synced into a the cluster from an install, or reinstall of Velero
The `kubectl -n velero edit backup b4` command, above, updated the object in the cluster. However, the backup objects, are also persisted into BackupStorgeLocation at the time of backup creation and not updated. These backups are sync-ed into the cluster on reinstalling Velero into the same cluster or on installing Velero in a another cluster that uses the same BSL.
Similar to the example above, reinstalling Velero will reset the backup `b4`'s expiry to it's original value and will eventually be deleted once the backup gc-controller runs, by default this runs every hour.
    ```
    $ velero backup get
    NAME   STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
    b4     Completed   0        0          2020-10-26 14:06:28 -0700 PDT   50m ago   default            <none
    ```

Once the objects are sync-ed into the cluster it is possible to edit the backup to preserve the extension of the expiry. However it is not possible to extend expiry of backups that have already expired.

I understand that persisting the edits to the expiry of a backup object can be very useful. I am going to mark this issue as a user enhancement with long term important.

**Comment by jbmassicotte** [comment]
@ashish-amarnath  
Thank you for the detailed answer. Please see my 3 questions below.

Regarding scenario #1:

I was editing value spec.ttl in the backup resource but it appears the right value to edit is status.expiration. **Right?**
Having a velero command to update the expiration time would certainly be more desirable but I can certainly live with the above trick.

Regarding scenario #2:

This is clearly more complicated. I can imagine losing the entire cluster, and having to rebuild the cluster. By the time I reinstall velero, and attempt to restore our backed up namespace from the BackupStorageLocation, the backup might have an expired date, which would cause velero to delete the backup before I have a chance to restore our namespace. **Right?**

So having the ability to temporarily disable the expiry function would meet our need. **Is there any way to do so right now?** Hacked up solutions are totally acceptable for the time being.

**Comment by ashish-amarnath** [comment]
@jbmassicotte Here are the answers.

Q1: Yes, you will need to edit the `.status.expiration` field of the backup object.
I understand that having a command to update/extend the expiration of the backup will be useful. Unfortunately, `kubectl -n velero edit backup` is the best thing we have atm. I'll create another user enhancement issue for the `velero backup expiry-extend` command

Q2: You can start the velero server in restore only mode using the `--restore-only` flag to the `velero install` command. This will disable the gc controller ensuring that none of the backups are garbage collected.

```
time="2020-10-30T00:35:02Z" level=info msg="Restore only mode - not starting the backup, schedule, delete-backup, or GC controllers" logSource="pkg/cmd/server/server.go:799"
```
Here is an example of backups that expired 6h ago still exist in the cluster after starting velero in restore only mode.
```bash
$ velero backup get
NAME                STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
b1                  Completed   0        0          2020-10-27 17:26:23 -0700 PDT   27d       default            <none>
s1-20201029183011   Completed   0        0          2020-10-29 11:30:11 -0700 PDT   6h ago    default            <none>
s1-20201029182711   Completed   0        0          2020-10-29 11:27:11 -0700 PDT   6h ago    default            <none>
```

**Comment by jbmassicotte** [comment]
@ashish-amarnath 
Oh very cool. Ability to start velero in restore only mode (which I was not aware of), combined with the ability to edit the expiration time of an existing backup fully meet my needs. Thank you again for taking the time to answer.

**Comment by emcay** [comment]
Question, editing .status.expiration it does seem to stop velero from trying to "delete" a backup. However, when using "velero get backup" it still shows a "deleting" status. Is there a way to fix that?

**Comment by xeruf** [comment]
I edited expiration and ttl on a backup of generation 3 which was created from another cluster (the current one creates generation 21 backups) but it is still not recogniced by Velero at all, not appearing as a Kubernetes Backup resource. Am I doing something wrong?

**Comment by xeruf** [comment]
The issue was in the configuration of the tool I worked with ^^ https://open.greenhost.net/stackspin/stackspin/-/blob/main/flux2/apps/velero-config/backupstoragelocation.yaml#L17
