### ISSUE TITLE
Generate RPM & Deb packages for Velero CLI

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#3043]
**Describe the problem/challenge you have**
Installing the Velero CLI involves downloading the binary and putting it in the appropriate directory (/usr/local/bin recommended).  There is not automatic update and installation requires multiple steps.

**Describe the solution you'd like**
Generate RPM and Deb packages to install the CLI in a consistent manner and manage versions.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by tharun208** [comment]
@dsu-igeek I like to work on this. I am also thinking of adding `velero` to homebrew. is this fine?
