### ISSUE TITLE
Not found the velero backup in another OpenShift cluster B

### ISSUE THREAD

**Issue by bjlvfei** [vmware-tanzu/velero#3044]
Hi Team,

we want to realize the DR velero solution between two OpenShift clusters. Cluster A and B share the same bucket name, cluster B only has readonly access mode to it. But the cluster B not found any backup. Any idea about it?  I'm have created the velero backup for cluster A as below.

Cluster A:
velero backup-location get 
NAME      PROVIDER   BUCKET/PREFIX       PHASE       LAST VALIDATED                  ACCESS MODE
default   aws        dswesb-uat-velero   Available   2020-10-27 09:57:29 +0800 CST   ReadWrite

kubectl -n velero get backupstoragelocation default -o yaml                                                                                    
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  creationTimestamp: 2020-10-22T04:11:18Z
  generation: 1
  labels:
    component: velero
  name: default
  namespace: velero
  resourceVersion: "124491113"
  selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/default
  uid: 364a9019-2b38-4fdc-891c-cf28babc1677
spec:
  config:
    region: us-east
    s3Url: http://s3.us-east.cloud-object-storage.appdomain.cloud
  objectStorage:
    bucket: dswesb-uat-velero
  provider: aws
status:
  lastSyncedTime: 2020-10-27T02:00:30Z
  lastValidationTime: 2020-10-27T02:00:30Z
  phase: Available

velero backup get          
NAME                             STATUS            ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
backup-uat-project               PartiallyFailed   21       0          2020-10-26 15:42:55 +0800 CST   29d       default            <none>
dr-daily-backup                  Deleting          1        0          2020-10-19 16:58:10 +0800 CST   22d       default            <none>
dr-daily-backup-20201027000001   Completed         0        0          2020-10-27 08:00:01 +0800 CST   29d       default            <none>
dr-daily-backup-20201026000001   Completed         0        0          2020-10-26 08:00:01 +0800 CST   28d       default            <none>
dr-daily-backup-20201025000001   Completed         0        0          2020-10-25 08:00:01 +0800 CST   27d       default            <none>
dr-daily-backup-20201024000000   Completed         0        0          2020-10-24 08:00:00 +0800 CST   26d       default            <none>
dr-daily-backup-20201023000000   Completed         0        0          2020-10-23 08:00:00 +0800 CST   25d       default            <none>
dr-daily-backup-20201022000000   Completed         0        0          2020-10-22 08:00:00 +0800 CST   24d       default            <none>
dr-daily-backup-20201021000059   Completed         0        0          2020-10-21 08:00:59 +0800 CST   23d       default            <none>
dr-daily-backup-20201020000059   Completed         0        0          2020-10-20 08:00:59 +0800 CST   22d       default            <none>
dr-daily-backup-20201019090035   Completed         0        0          2020-10-19 20:59:07 +0800 CST   22d       default            <none>
righttime                        PartiallyFailed   24       0          2020-10-26 18:28:43 +0800 CST   29d       default            <none>

The last backup righttime which already send the backup data to bucket 
- apiVersion: velero.io/v1
  kind: PodVolumeBackup
  metadata:
    annotations:
      velero.io/pvc-name: customer-migration-out
    creationTimestamp: 2020-10-26T10:39:20Z
    generateName: righttime-
    generation: 3
    labels:
      velero.io/backup-name: righttime
      velero.io/backup-uid: e68607fa-f270-4d32-a7a1-7e2395b6933b
      velero.io/pvc-uid: 10b03873-43d3-4ed1-acd7-0ce5f24d1aa5
    name: righttime-wkm58
    namespace: velero
    ownerReferences:
    - apiVersion: velero.io/v1
      controller: true
      kind: Backup
      name: righttime
      uid: e68607fa-f270-4d32-a7a1-7e2395b6933b
    resourceVersion: "123697735"
    selfLink: /apis/velero.io/v1/namespaces/velero/podvolumebackups/righttime-wkm58
    uid: 03fd5eed-6ee2-4084-b656-39fd3a4b0e82
  spec:
    backupStorageLocation: default
    node: 10.65.216.168
    pod:
      kind: Pod
      name: customer-migration-asc-job-1603707900-rm7pt
      namespace: uat
      uid: d8ef5940-9c62-400c-857e-6f107eb286b8
    repoIdentifier: s3:http://s3.us-east.cloud-object-storage.appdomain.cloud/dswesb-uat-velero/restic/uat
    tags:
      backup: righttime
      backup-uid: e68607fa-f270-4d32-a7a1-7e2395b6933b
      ns: uat
      pod: customer-migration-asc-job-1603707900-rm7pt
      pod-uid: d8ef5940-9c62-400c-857e-6f107eb286b8
      pvc-uid: 10b03873-43d3-4ed1-acd7-0ce5f24d1aa5
      volume: cos-out
    volume: cos-out

Cluster B:

kubectl -n velero get backupstoragelocation default -o yaml                      
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  creationTimestamp: 2020-10-26T10:18:24Z
  generation: 1
  name: default
  namespace: velero
  resourceVersion: "18437377"
  selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/default
  uid: c594a6db-0c8e-439b-a72d-726c7f221a36
spec:
  accessMode: ReadOnly
  config:
    region: us-east
    s3Url: http://s3.us-east.cloud-object-storage.appdomain.cloud
  objectStorage:
    bucket: dswesb-uat-velero
    prefix: restic
  provider: aws
status:
  lastValidationTime: 2020-10-27T01:37:30Z
  phase: Unavailable

velero backup-location get             
NAME      PROVIDER   BUCKET/PREFIX              PHASE         LAST VALIDATED                  ACCESS MODE
default   aws        dswesb-uat-velero/restic   Unavailable   2020-10-27 09:37:30 +0800 CST   ReadOnly

Thanks in Advance!

Levi

**Comment by bjlvfei** [comment]
Environment:
    Velero version 
   Client:
	Version: v1.5.1
	Git commit: -
Server:
	Version: v1.5.1

    OpenShift version 4.3.35_1539
    Cloud provider or hardware configuration: restic

**Comment by ashish-amarnath** [comment]
@bjlvfei can you please inspect logs from Velero to check for any errors reported by the backup-storage-location controller?
You can obtain logs from the velero pod using `kubectl -n velero logs deploy/velero`.
This is going to help us determine what is causing Velero in Cluster B to consider the backup storage location as unavailable.

**Comment by bjlvfei** [comment]
Hi @ashish-amarnath 

Sorry too late to response, I have checked the the log in Cluster B as below. There is only one backup-location for share. I think it's need to create another backup-location for Cluster B itself. Is right?

time="2020-11-02T03:12:38Z" level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"
time="2020-11-02T03:12:38Z" level=warning msg="The specified default backup location named \"default\" is unavailable; for convenience, be sure to configure it properly or make another backup location that is available the default" backupstoragelocation=default controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:105"
time="2020-11-02T03:12:38Z" level=error msg="Current backup storage locations available/unavailable/unknown: 0/1/0, Backup location \"default\" is unavailable: rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: 9c4453ac-e4a8-47b8-b4d1-22563c523452, host id: )" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:152"
time="2020-11-02T03:12:38Z" level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"
time="2020-11-02T03:12:38Z" level=info msg="No backup locations were ready to be verified" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:120"
time="2020-11-02T03:12:38Z" level=error msg="Current backup storage locations available/unavailable/unknown: 0/1/0)" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:154"
time="2020-11-02T03:12:55Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: 25fcf6d3-d053-4329-ba36-31b40bec0dca, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"
time="2020-11-02T03:13:26Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: de9968b0-e1b8-4fc7-ba3b-8597f753c031, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"
time="2020-11-02T03:13:56Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: 46bdcec6-35bb-443a-beed-cfc351d1306c, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"
time="2020-11-02T03:14:26Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: 0d02aed0-fafe-4fb6-aeeb-fb87e927ee96, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"
time="2020-11-02T03:14:56Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: bd4e86de-ff21-4421-a962-55521cd4e19e, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"
I1102 03:15:15.407765       1 request.go:621] Throttling request took 1.034949334s, request: GET:https://172.21.0.1:443/apis/operator.openshift.io/v1?timeout=32s
time="2020-11-02T03:15:26Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: 513c3605-eae7-455e-aa69-a599ef3e69c9, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"
time="2020-11-02T03:15:56Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: a4e4f631-c495-4b13-a81f-3fd148f1b18f, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"
time="2020-11-02T03:16:26Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: d851ef10-d43d-4758-9a15-9a06c9fe46b3, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"
time="2020-11-02T03:16:57Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: 1c6ab7bd-8bc7-49fc-afee-18caffaeda78, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"
time="2020-11-02T03:17:27Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: c944375d-ccec-4296-911f-2f4d543b216e, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"
time="2020-11-02T03:17:57Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: 85802674-be27-4ad2-864c-1d638475fafe, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"
time="2020-11-02T03:18:27Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: 57a0feb5-7073-443a-9215-a66477607828, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"
time="2020-11-02T03:18:57Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: 87048f18-4eab-411d-8507-d5c27a3e13f8, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175

How the backup-location name link to Cluster B?

Levi
Thanks!

**Comment by bjlvfei** [comment]
Cluster A
I'm reinstall the velero server and it's backup files as below in Cluster A
the velero install command line was 

velero install \ 
--provider aws --plugins velero/velero-plugin-for-aws:v1.0.0 \
--bucket dswesb-fvt-velero \
--secret-file ./cloud-credentials \
--use-volume-snapshots=false \
--backup-location-config region=us-east,s3Url=http://s3.us-east.cloud-object-storage.appdomain.cloud \
--dry-run -o yaml > velero-fvt.yaml

velero backup get
NAME                        STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
backup-fvt                  Deleting    1        0          2020-10-16 18:33:05 +0800 CST   10d       default            <none>
backup-fvt-20201105000005   Completed   0        0          2020-11-05 08:00:05 +0800 CST   29d       default            <none>
backup-fvt-20201104083050   Failed      0        0          2020-11-04 16:30:50 +0800 CST   29d       default            <none>
backup-fvt-20201027000004   Completed   0        0          2020-10-27 08:00:04 +0800 CST   20d       default            <none>
backup-fvt-20201026000004   Completed   0        0          2020-10-26 08:00:04 +0800 CST   19d       default            <none>
backup-fvt-20201025000003   Completed   0        0          2020-10-25 08:00:03 +0800 CST   18d       default            <none>
backup-fvt-20201024000003   Completed   0        0          2020-10-24 08:00:03 +0800 CST   17d       default            <none>
backup-fvt-20201023000003   Completed   0        0          2020-10-23 08:00:03 +0800 CST   16d       default            <none>
backup-fvt-20201022000002   Completed   0        0          2020-10-22 08:00:02 +0800 CST   15d       default            <none>
backup-fvt-20201021121627   Completed   0        0          2020-10-21 20:16:27 +0800 CST   15d       default            <none>


Cluster B 
I'm using the same BackupStorageLocation in velero-fvt.yaml as Cluster A and reinstall the BackupStorageLocation yaml file in Cluster B. BTW, I'm add the " prefix: backups" in the yaml file. please check backup-location default and the bucket already shared with Cluster A. 


velero backup-location get                         
NAME         PROVIDER   BUCKET/PREFIX               PHASE         LAST VALIDATED                  ACCESS MODE
default      aws        dswesb-fvt-velero/backups   Unavailable   2020-11-05 09:45:14 +0800 CST   ReadOnly
dswesb-uat   aws        dswesb-velero               Unavailable   2020-11-05 09:45:14 +0800 CST   ReadWrite


 kubectl get backupstoragelocations -o yaml 
apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"velero.io/v1","kind":"BackupStorageLocation","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"component":"velero"},"name":"default","namespace":"velero"},"spec":{"config":{"region":"us-east","s3Url":"http://s3.us-east.cloud-object-storage.appdomain.cloud"},"objectStorage":{"bucket":"dswesb-fvt-velero","prefix":"backups"},"provider":"aws"}}
    creationTimestamp: 2020-11-04T15:18:15Z
    generation: 3
    labels:
      component: velero
    name: default
    namespace: velero
    resourceVersion: "21552452"
    selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/default
    uid: 4bbb4bfd-c680-41ee-8520-182b408313aa
  spec:
    accessMode: ReadOnly
    config:
      region: us-east
      s3Url: http://s3.us-east.cloud-object-storage.appdomain.cloud
    objectStorage:
      bucket: dswesb-fvt-velero
      prefix: backups
    provider: aws
  status:
    lastSyncedTime: 2020-11-05T01:44:13Z
    lastValidationTime: 2020-11-05T01:44:13Z
    phase: Unavailable
- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    creationTimestamp: 2020-11-03T10:11:31Z
    generation: 1
    name: dswesb-uat
    namespace: velero
    resourceVersion: "21552451"
    selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/dswesb-uat
    uid: a51df5c4-2082-4c7e-ac14-0e6155d3479a
  spec:
    accessMode: ReadWrite
    config:
      region: us-south
      s3Url: http://s3.us-south.cloud-object-storage.appdomain.cloud
    objectStorage:
      bucket: dswesb-velero
    provider: aws
  status:
    lastSyncedTime: 2020-11-05T01:42:42Z
    lastValidationTime: 2020-11-05T01:44:13Z
    phase: Unavailable
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

the velero deployment log where found this "[backup-fvt-20201021121627 backup-fvt-20201022000002 backup-fvt-20201023000003 ...])" it's seems found the backup files in Cluster A. But run the command line "velero backup get" which still not list backup files in Cluster B. 

time="2020-11-05T01:42:43Z" level=warning msg="Invalid backup locations detected: available/unavailable/unknown: 1/1/0, )" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:157"
time="2020-11-05T01:43:12Z" level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"
time="2020-11-05T01:43:12Z" level=info msg="No backup locations were ready to be verified" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:120"
time="2020-11-05T01:43:12Z" level=warning msg="Invalid backup locations detected: available/unavailable/unknown: 1/1/0, )" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:157"
time="2020-11-05T01:43:43Z" level=error msg="Error listing backups in backup store" backupLocation=dswesb-uat controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: 559ecb18-b41b-4c3b-a080-98295698113b, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"
time="2020-11-05T01:43:47Z" level=info msg="Processing new ServerStatusRequest" controller=serverstatusrequest logSource="pkg/controller/server_status_request_controller.go:86" phase= serverStatusRequest=velero/velero-cli-cmvbl
time="2020-11-05T01:44:13Z" level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"
time="2020-11-05T01:44:13Z" level=error msg="Error listing backups in backup store" backupLocation=dswesb-uat controller=backup-sync error="rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: e6777c94-04c4-4318-9efe-f57082866c74, host id: " error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:175"
time="2020-11-05T01:44:13Z" level=warning msg="The specified default backup location named \"default\" is unavailable; for convenience, be sure to configure it properly or make another backup location that is available the default" backupstoragelocation=default controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:105"
time="2020-11-05T01:44:13Z" level=error msg="Current backup storage locations available/unavailable/unknown: 0/2/0, Backup location \"dswesb-uat\" is unavailable: rpc error: code = Unknown desc = AccessDenied: Access Denied\n\tstatus code: 403, request id: 9ee459e1-4ce1-491c-9281-4a8fc40063c6, host id: ; Backup location \"default\" is unavailable: Backup store contains 9 invalid top-level directories: [backup-fvt-20201021121627 backup-fvt-20201022000002 backup-fvt-20201023000003 ...])" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:152"
time="2020-11-05T01:44:13Z" level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"
time="2020-11-05T01:44:13Z" level=info msg="No backup locations were ready to be verified" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:120"
time="2020-11-05T01:44:13Z" level=error msg="Current backup storage locations available/unavailable/unknown: 0/2/0)" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:154"
time="2020-11-05T01:44:13Z" level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"
time="2020-11-05T01:44:13Z" level=info msg="No backup locations were ready to be verified" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:120"
time="2020-11-05T01:44:13Z" level=error msg="Current backup storage locations available/unavailable/unknown: 0/2/0)" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:154

velero backup get
NAME              STATUS             ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
mysql-integrate   Deleting           0        0          2020-10-22 18:27:22 +0800 CST   16d       default            <none>
uat-backup        FailedValidation   0        0          <nil>                           29d       default            <none>

I have few questions 
why the backup files not list in Cluster B? 
How to add or config the BackupStorageLocation for Cluster B if the default BSL was used to share with Cluster A?
Any idea? please let me know if you need any information. Thanks!

Levi

**Comment by bjlvfei** [comment]
I have resolved this issue after using the cross region bucket.  I'm will close this issue now.

Levi
Thanks!
