### ISSUE TITLE
Have a way to modify nodeSelector when restoring

### ISSUE THREAD

**Issue by sagor999** [vmware-tanzu/velero#3052]
**Describe the problem/challenge you have**
I have Cluster A, that uses `nodeSelector`.
I want to restore into Cluster B, that doesn't use nodeSelector or doesn't have similar labels as Cluster A has.

**Describe the solution you'd like**
Similar to `velero.io/change-storage-class: RestoreItemAction` I would like to be able to remap nodeSelector labels when restoring, or have a way to completely delete any labels in nodeSelector.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
1.5.1
- Kubernetes version (use `kubectl version`):
1.17.3
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by brian-singer** [comment]
I also need this feature, actually I am trying to find a workaround.

**Comment by eleanor-millman** [comment]
Closing because will be covered by #474

**Comment by usamacheema786** [comment]
can we exclude nodeSelectors while restoring?
