### ISSUE TITLE
Add documentation for using Velero with cluster api

### ISSUE THREAD

**Issue by a-mccarthy** [vmware-tanzu/velero#3054]
We should investigate and add documentation for how to use Velero and cluster api

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by a-mccarthy** [comment]
cc: @ashish-amarnath

**Comment by ashish-amarnath** [comment]
Adding this here for reference.
https://github.com/vmware-tanzu/velero/issues/2554

**Comment by ashish-amarnath** [comment]
@a-mccarthy I found this to be documented here https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.2/vmware-tanzu-kubernetes-grid-12/GUID-mgmt-clusters-backup-restore-mgmt-cluster.html
