### ISSUE TITLE
Velero restore get-> started and completed timestamp is <nil>

### ISSUE THREAD

**Issue by akshaymandke** [vmware-tanzu/velero#3058]
**What steps did you take and what happened:**

- Installed velero and performed steps to create backup and restore.

- Created backup and associated restore for namespace.

- Executed **velero restore get**  and verified the values under **Started** and **completed** columns.
 

**What did you expect to happen:**

When user executes velero restore get -> the values under STARTED and COMPLETED columns should not be nil and should display correct values.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `velero restore get demorestore`

NAME             BACKUP          STATUS        STARTED      COMPLETED    ERRORS   WARNINGS     CREATED                                    SELECTOR
demorestore  demobkp       Completed     nil                 nil                    0                    0             2020-11-09 11:35:28 +0530 IS  <none>

![image](https://user-images.githubusercontent.com/60071112/98529902-38ed7880-22a4-11eb-9b64-6abf3055da73.png)

**Anything else you would like to add:**

It was observed that the restores were created successfully and did not hamper the restoration process.
The issue persists for restores created from both scheduled and manual backups.

**Environment:**

- Velero version (use `velero version`): 1.5.2
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"37c06f456fdb4d25e402b5fbcb72cd6a77a021a9", GitTreeState:"clean", BuildDate:"2020-09-18T21:59:14Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
- Cloud provider or hardware configuration: AKS
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by carlisia** [comment]
Hey @akshaymandke, this is a bit odd. It's not something I have been able to reproduce. Would you please send me the entire output of: 

- `velero version`
- `kubectl get restores.velero.io`

**Comment by carlisia** [comment]
@akshaymandke this issue has been inactive for while so I'm closing it. Feel free to reopen if it's still happening.
