### ISSUE TITLE
--default-restic-prune-frequency does not have any effect , resticrepo is always created with default value (168h0m0s) even after passing different value

### ISSUE THREAD

**Issue by noeljose2020** [vmware-tanzu/velero#3062]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
installed velero using helm chart in kubernetes enviornment and passed ---default-restic-prune-frequency=24h0m0s , 
created a schedule , resticrepo got created with default maintenance frequency it did not pick  the value passed 

output of resticrepo
Name:         test-default-ljppp
Namespace:    test
Labels:       velero.io/storage-location=default
              velero.io/volume-namespace=test
Annotations:  <none>
API Version:  velero.io/v1
Kind:         ResticRepository
Metadata:
  Creation Timestamp:  2020-11-10T13:41:34Z
  Generate Name:       test-default-
  Generation:          3
  Resource Version:    12812120
  Self Link:           /apis/velero.io/v1/namespaces/test/resticrepositories/test-default-ljppp
  UID:                 a35707ad-8e2c-4dc1-adc9-47c207fe082e
Spec:
  Backup Storage Location:  default
  Maintenance Frequency:    168h0m0s
  Restic Identifier:        s3:
  Volume Namespace:         test
Status:
  Last Maintenance Time:  2020-11-10T13:41:39Z
  Phase:                  Ready
Events:                   <none>
**What did you expect to happen:**
expected resticrepo will get created with the passed value

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.51.
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by nrb** [comment]
@noeljose2020 Thanks for the report - we've heard about this from other people and I think the argument isn't be passed from the command line into the configuration properly.

**Comment by eleanor-millman** [comment]
@ashish-amarnath Are you still working on this? We are just trying to figure out status while we are triaging.

**Comment by ashish-amarnath** [comment]
I am not working on this. Unassigning myself.

**Comment by eleanor-millman** [comment]
@dsu-igeek Since Ashish is no longer working on this, does this change your triage? Right now, it is "current".

**Comment by ghilman27** [comment]
any update on this

**Comment by eleanor-millman** [comment]
@dsu-igeek is on vacation this week. I'll check in with him next week and then update you.
