### ISSUE TITLE
Improve docs on encryption

### ISSUE THREAD

**Issue by a-mccarthy** [vmware-tanzu/velero#3065]
**Describe the problem/challenge you have**
How does Velero handle encryption? Does it encrypt anything by default?

**Describe the solution you'd like**
We should add docs describing encryption.

Velero's backups are split into 2 pieces - the metadata stored in object storage, and snapshots/backups of the persistent volume data. Right now, Velero itself does not encrypt either, instead relying on the native mechanisms in the object and snapshot systems. A special case is restic, which backs up the persistent volume data at the filesystem level and send it to Velero's object storage.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by a-mccarthy** [comment]
We should add this information under the Limitations/Caveats section on this page, https://velero.io/docs/v1.5/locations/

**Comment by MadhavJivrajani** [comment]
Hi! Can I take this up?
