### ISSUE TITLE
There should be a left menu item expanded for the API

### ISSUE THREAD

**Issue by survivant** [vmware-tanzu/velero#3075]
I'm trying to find the APi for Velero.  I was looking for the Schedule API.  I had to enter Schedule in the searchbar->select schedule..

I arrive here : https://velero.io/docs/v1.5/api-types/schedule/#definition

but in the left menu.. I don't find any reference to where I'm in the API documentation.  

There should be a item in the left menu that shows the Velero API.

**Comment by nrb** [comment]
@survivant I think the link you're looking for is there, see this screenshot. It's under that section. We'll continue to revisit our information architecture, though.

![Screen Shot 2020-11-16 at 3.18.53 PM.png](https://images.zenhubusercontent.com/5b4e374cb69de9433c052d0b/45035afd-a9cc-4514-a0a6-a48fb8f80e0e)
