### ISSUE TITLE
Backup CSI Feature can be dynamically configurable

### ISSUE THREAD

**Issue by nevermore-muyi** [vmware-tanzu/velero#3078]
**Describe the problem/challenge you have**
When I use restic to backup my volume, I can config **defaultVolumesToRestic** is true,but when I use csi snapshot to backup volumes, I must use the command **--features=EnableCSI**,which I think is unreasonable.Because of the different config,I must restart velero when I disable/enable CSI.

**Describe the solution you'd like**
Make the CSI snapshot backup can be configurable like the restic.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
Client:
	Version: v1.5.2
	Git commit: e115e5a191b1fdb5d379b62a35916115e77124a4
Server:
	Version: v1.5.2

- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by Lighting-wings** [comment]
Good idea. This can provide more  convenience for users.

**Comment by neujie** [comment]
Maybe let user to choose when create a backup is a good way,  like restic plugin.

**Comment by neujie** [comment]
Maybe let user to choose csi or restic when create a backup is a good way.

**Comment by ruanchen** [comment]
@nrb Hi, is there any plans about the feature?
thanks.

**Comment by ruzickap** [comment]
Fixing this will allow to combine backups of these two storage types on EKS cluster: 
* [CSI Snapshotter](https://github.com/kubernetes-csi/external-snapshotter) with [Amazon Elastic Block Store (EBS) CSI driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) to do snapshots using Velero
* [Amazon EFS CSI Driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver) (needed for `ReadWriteMany` access mode) with Velero "restic". (Amazon EFS CSI Driver does not support snapshots)

As was mentioned above - you need to reconfigure Velero when you want to combine "CSI snapshots" and "Restic" backups.

**Comment by dsu-igeek** [comment]
CSI snapshotting is currently BETA.  Once CSI snapshot is GA the feature flag will no longer be required.  This is being tracked here - https://github.com/vmware-tanzu/velero/issues/2066 and is planned for the 1.7.0 release currently
