### ISSUE TITLE
Use Velero for On-Premise Kubernetes

### ISSUE THREAD

**Issue by saraAlizadeh** [vmware-tanzu/velero#3079]
**Describe the problem/challenge you have**
I have a kubernetes cluster deployed over vSphere (on-premise). So, I don't use any cloud provider.
Is there any way for me to use velero? I need to have backups of my PVs and my storage is Rook-Ceph.

**Describe the solution you'd like**
I could use an external ceph (or rook-ceph) or glusterfs or local storage as my BackupStorageLocation and VolumeSnapshotLocation.

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`): 18.5
- Kubernetes installer & version: kubeadm
- Cloud provider or hardware configuration: no cloud provider
- OS (e.g. from `/etc/os-release`): Centos 7

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
@saraAlizadeh Yes, [Velero can be used on-prem](https://velero.io/docs/latest/on-premises/#docs), though I'm not aware of any Ceph or GlusterFS plugins.

Right now, using Velero on-prem with Ceph or GlusterFS would require using [restic](https://velero.io/docs/v1.5/restic) to get the volume data.
