### ISSUE TITLE
Velero restic prune flag (--default-restic-prune-frequency) is not working

### ISSUE THREAD

**Issue by crdemon09** [vmware-tanzu/velero#3080]
**What steps did you take and what happened:**
1. Setup velero
2. Specify restic prune flag --default-restic-prune-frequency=24h0m0s
Result: Velero process is running with needed parameters, but still Maintenance Frequency is 168h0m0s
_/velero server --log-level=debug --default-restic-prune-frequency=24h0m0s --restic-timeout=48h_

**What did you expect to happen:**
ResticRepositiry ->Maintenance Frequency should be changed according to value in --default-restic-prune-frequency

**The output of the following commands will help us better understand what's going on**:

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
**kubectl describe ResticRepository**
Spec:
  Backup Storage Location:  default
  Maintenance Frequency:    168h0m0s
  Restic Identifier:        s3:http://minio.default.svc:9000/velerok8s/restic/default
  Volume Namespace:         default

**Environment:**

Velero version 1.4.3

**Comment by nrb** [comment]
This is the same as #3062, closing as a duplicate.
