### ISSUE TITLE
Velero backup failing but in logs no error

### ISSUE THREAD

**Issue by basavarajb** [vmware-tanzu/velero#3086]
**What steps did you take and what happened:**
I followed the mentioned link
https://sysadminas.eu/2019/12/part-3-azure-kubernetes-services-aks-backup-restore-your-aks-data-with-velero/

After executing the backup command  if i look into logs it show Phase: Failed
![image](https://user-images.githubusercontent.com/9286143/99401987-da14a880-290e-11eb-82ed-61915055b4c7.png)
[Backup_logs.txt](https://github.com/vmware-tanzu/velero/files/5554040/Backup_logs.txt)

**Comment by ashish-amarnath** [comment]
@basavarajb Can you please share logs from the Velero deployment by running `kubectl -n velero logs deploy/velero`? That should have some context.
I would suggest bumping up the memory limits on the Velero deployment and trying this again. Instructions to do that is available on our website at https://velero.io/docs/v1.5/customize-installation/#update-resource-requests-and-limits-after-install

**Comment by basavarajb** [comment]
i already attached the logs https://github.com/vmware-tanzu/velero/files/5554040/Backup_logs.txt

Can u have look on it

**Comment by ashish-amarnath** [comment]
@basavarajb I did see the logs you attached. That is the output of `velero backup logs <backup>`. However what I am asking for is the output of `kubectl -n velero logs deploy/velero`.

**Comment by basavarajb** [comment]
![image](https://user-images.githubusercontent.com/9286143/99483889-39150480-2985-11eb-8d6b-a3c8328b58ce.png)

I have repeated message

**Comment by ashish-amarnath** [comment]
Looks like the file providing Velero with credentials to the Azure blog store is incorrectly formatted.
Can you please follow the instructions at https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#option-1-create-service-principal and use the correct format?

**Comment by basavarajb** [comment]
AZURE_SUBSCRIPTION_ID=dfcc4748-16b5-45d9-a344-197544f3a7d7


AZURE_TENANT_ID=xxxxx
AZURE_CLIENT_ID=xxxx
AZURE_CLIENT_SECRET=xxxx
AZURE_RESOURCE_GROUP=MC_AKS-RG_aks-dev_eastus
AZURE_CLOUD_NAME=AzurePublicCloud

My velero credential file contains above mentioned details i followed the details as you mentioned, still im getting same error

**Comment by basavarajb** [comment]
AZURE_SUBSCRIPTION_ID=dfcc4748-16b5-45d9-a344-197544f3a7d7
AZURE_TENANT_ID=35d5d419-099f-47a7-a1e1-c48a613b7474
AZURE_CLIENT_ID=817c05b4-75af-4d1c-bb75-b3817e1cd6d6
AZURE_CLIENT_SECRET=Xj0F~wjBaHAFIJoRbo-YluM4E-9VAo2PEe
AZURE_RESOURCE_GROUP=MC_AKS-RG_aks-dev_eastus
AZURE_CLOUD_NAME=AzurePublicCloud

**Comment by basavarajb** [comment]
is there any way to install veleo using .yaml and substituting credentials.
If it is there please let me know with sample yaml file

**Comment by ashish-amarnath** [comment]
You can run the `velero install` command with the `--dry-run -oyaml` flags to generate the yaml and then apply it yourself.
But I would like to understand why this isn't working for you.
Can you please follow the below troubleshooting steps:
1. Confirm that velero deployment is mounting the `cloud-credentials` secret:
    ```bash
    $ kubectl -n velero get deploy velero -ojson | jq .spec.template.spec.containers[0].volumeMounts
    [
    {
        "mountPath": "/plugins",
        "name": "plugins"
    },
    {
        "mountPath": "/scratch",
        "name": "scratch"
    },
    {
        "mountPath": "/credentials",
        "name": "cloud-credentials"
    }
    ]
    ```
1. Confirm that the `cloud-credentials` secret exists and has the correct content.
    ```bash
    $ kubectl -n velero get secrets cloud-credentials
    NAME                TYPE     DATA   AGE
    cloud-credentials   Opaque   1      11h
    $ kubectl -n velero get secrets cloud-credentials -ojsonpath={.data.cloud} | base64 --decode
    <Output should be your credentials>
    ```
1. Confirm if the correct credentials are mounted into the Velero pod?
    ```bash
    $ kubectl -n velero exec -ti deploy/velero -- bash
    nobody@velero-69f9c874c-l8mqp:/$ cat /credentials/cloud
    <Output should be your credentials>
    ```

**Comment by basavarajb** [comment]
Installed the velero with below command

velero install --provider azure 
--plugins velero/velero-plugin-for-microsoft-azure:v1.1.0 
--bucket velero --secret-file ./credentials-velero 
--backup-location-config resourceGroup=$BACKUP_RESOURCE_GROUP,storageAccount=$BACKUP_STORAGE_ACCOUNT_NAME --snapshot-location-config apiTimeout=5m,resourceGroup=$BACKUP_RESOURCE_GROUP --wait

I getting error as mentioned in the image

What is the possible reason for it.

![image](https://user-images.githubusercontent.com/9286143/99872067-17c24b80-2c05-11eb-8468-62435b4324d3.png)

**Comment by ashish-amarnath** [comment]
This is most likely because the plugin is running out of memory.
Can you please increase the memory resource limits on the Velero pod and try again? 
Instructions for doing that are available at https://velero.io/docs/v1.5/customize-installation/#update-resource-requests-and-limits-after-install

**Comment by basavarajb** [comment]
After increasing  memory resource limits on the Velero pod it worked

Thanks ashish-amarnath

**Comment by jailigao** [comment]
Im having a similar error on my end. I actually created a terraform file for the storage account etc. then after running velero manually i encountered this below:

![image](https://user-images.githubusercontent.com/89129284/144453515-051b9182-0e8a-438b-b635-e1d60aa43397.png)

After a lot of research i was able to run the backup but needs to install it below:

**velero install --provider azure --bucket $azurerm_storage_container.example.name  --secret-file ./main.tf --backup-location-config resourceGroup="unit-testing",storageAccount=$azurerm_storage_account.example.name --snapshot-location-config apiTimeout="5m",resourceGroup="unit-testing",subscriptionId="MFC-Global-Canada-DSDM-CloudEng-Sandbox-S1" --plugins velero/velero-plugin-for-microsoft-azure:v1.0.0**

after running the backup command, it will push through but after checking its status all backup were failed. And also im not seeing it on my blob storage in Azure. Can you help me pls.

![image](https://user-images.githubusercontent.com/89129284/144454286-c761ed22-00e6-4d8d-9a21-64f6cd0678a2.png)
