### ISSUE TITLE
Velero with Helm --generate-name , the "velero plugin add" command fails

### ISSUE THREAD

**Issue by brito-rafa** [vmware-tanzu/velero#3088]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Installed Velero with the following (as per documentation - note the --generate-name)

helm install vmware-tanzu/velero --namespace velero \
--set-file credentials.secretContents.cloud=/Users/rbrito/OneDrive/migrator/credentials-velero \
--set configuration.provider=aws \
--set configuration.backupStorageLocation.bucket=brito-rafa-velero \
--set configuration.backupStorageLocation.config.region=us-east-2 \
--set configuration.backupStorageLocation.prefix=migrator-demo \
--set configuration.volumeSnapshotLocation.name=migrator-volume-snapshot \
--set configuration.volumeSnapshotLocation.config.region=us-east-2 \
--set image.repository=velero/velero \
--set image.tag=v1.5.1 \
--set image.pullPolicy=IfNotPresent \
--set initContainers[0].name=velero-plugin-for-aws \
--set initContainers[0].image=velero/velero-plugin-for-aws:v1.1.0 \
--set initContainers[0].volumeMounts[0].mountPath=/target \
--set initContainers[0].volumeMounts[0].name=plugins \
--generate-name

The deployment.apps under velero namespace has a random name:
$ kubectl get deployments -n velero
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
velero-1605643101   1/1     1            1           17m

When adding my custom plugin using the velero client, it fails because it is looking for the "deployment.apps/velero":
$ velero plugin add rathodamit101/route-2-httpproxy:cm2
An error occurred: deployments.apps "velero" not found

**What did you expect to happen:**

My custom velero plugin to load. The `velero plugin get` is functional:

$ velero plugin get
NAME                                 KIND
velero.io/crd-remap-version          BackupItemAction
velero.io/pod                        BackupItemAction
velero.io/pv                         BackupItemAction
velero.io/service-account            BackupItemAction
velero.io/aws                        ObjectStore
velero.io/add-pv-from-pvc            RestoreItemAction
velero.io/add-pvc-from-pod           RestoreItemAction
velero.io/change-pvc-node-selector   RestoreItemAction
velero.io/change-storage-class       RestoreItemAction
velero.io/cluster-role-bindings      RestoreItemAction
velero.io/crd-preserve-fields        RestoreItemAction
velero.io/init-restore-hook          RestoreItemAction
velero.io/job                        RestoreItemAction
velero.io/pod                        RestoreItemAction
velero.io/restic                     RestoreItemAction
velero.io/role-bindings              RestoreItemAction
velero.io/service                    RestoreItemAction
velero.io/service-account            RestoreItemAction
velero.io/aws                        VolumeSnapshotter

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

$ kubectl logs deployment/velero -n velero
Error from server (NotFound): deployments.apps "velero" not found

$ kubectl logs deployment/velero-1605643101 -n velero | tail -10
time="2020-11-17T20:22:06Z" level=debug msg="waiting for RPC address" cmd=/plugins/velero-plugin-for-aws controller=backupstoragelocation logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" path=/plugins/velero-plugin-for-aws
time="2020-11-17T20:22:06Z" level=debug msg="Setting log level to DEBUG" cmd=/plugins/velero-plugin-for-aws controller=backupstoragelocation logSource="pkg/plugin/framework/server.go:178" pluginName=velero-plugin-for-aws
time="2020-11-17T20:22:06Z" level=debug msg="plugin address" address=/tmp/plugin987047975 cmd=/plugins/velero-plugin-for-aws controller=backupstoragelocation logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" network=unix pluginName=velero-plugin-for-aws
time="2020-11-17T20:22:06Z" level=debug msg="using plugin" cmd=/plugins/velero-plugin-for-aws controller=backupstoragelocation logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" version=2
time="2020-11-17T20:22:06Z" level=debug msg="Backup location not ready to be validated" backupstoragelocation=default controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:87"
time="2020-11-17T20:22:06Z" level=info msg="No backup locations were ready to be verified" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:120"
time="2020-11-17T20:22:06Z" level=debug msg="plugin process exited" cmd=/plugins/velero-plugin-for-aws controller=backupstoragelocation logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" path=/plugins/velero-plugin-for-aws pid=772
time="2020-11-17T20:22:06Z" level=debug msg="plugin exited" cmd=/plugins/velero-plugin-for-aws controller=backupstoragelocation logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74"
time="2020-11-17T20:22:35Z" level=debug msg="Checking for existing backup storage locations to sync into cluster" controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:124"
time="2020-11-17T20:22:35Z" level=debug msg="Checking if backups need to be synced at this time for this location" backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:157"

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.5.1
- Velero features (use `velero client config get features`): 
$ velero client config get features
features: <NOT SET>
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.4-2+a00aae1e6a4a69", GitCommit:"a00aae1e6a4a698595445ec86aab1502a495c1ce", GitTreeState:"clean", BuildDate:"2020-04-22T11:35:29Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by brito-rafa** [comment]
So, removing --generate-name parameter from helm AND adding "velero" as name did the trick.

Suggest tweaking the helm documentation.

```
helm install **velero** vmware-tanzu/velero --namespace velero \
--set-file credentials.secretContents.cloud=/Users/rbrito/OneDrive/migrator/credentials-velero \
--set configuration.provider=aws \
--set configuration.backupStorageLocation.bucket=brito-rafa-velero \
--set configuration.backupStorageLocation.config.region=us-east-2 \
--set configuration.backupStorageLocation.prefix=migrator-demo \
--set configuration.volumeSnapshotLocation.name=migrator-volume-snapshot \
--set configuration.volumeSnapshotLocation.config.region=us-east-2 \
--set image.repository=velero/velero \
--set image.tag=v1.5.1 \
--set image.pullPolicy=IfNotPresent \
--set initContainers[0].name=velero-plugin-for-aws \
--set initContainers[0].image=velero/velero-plugin-for-aws:v1.1.0 \
--set initContainers[0].volumeMounts[0].mountPath=/target \
--set initContainers[0].volumeMounts[0].name=plugins 

NAME: velero
LAST DEPLOYED: Tue Nov 17 14:28:59 2020
NAMESPACE: velero
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

And the command succeded:

```
velero plugin add rathodamit101/route-2-httpproxy:cm2

velero plugin get
NAME                                                          KIND
velero.io/crd-remap-version                                   BackupItemAction
velero.io/pod                                                 BackupItemAction
velero.io/pv                                                  BackupItemAction
velero.io/service-account                                     BackupItemAction
velero.io/aws                                                 ObjectStore
openshift.migrator.tanzu.vmware.com/02-route-restore-plugin   RestoreItemAction

```

**Comment by ashish-amarnath** [comment]
@brito-rafa Thanks for reporting this. This is clearly a bug and at the very least should be documented.
Additionally, we could also use labels to select the velero deployment to `add plugins`.
The labels on the Velero deployment when installed using the `velero install` command are
```
{
  "component": "velero"
}
```
The same, when installed using helm, are
```
{
  "app.kubernetes.io/instance": "velero-1605673207",
  "app.kubernetes.io/managed-by": "Helm",
  "app.kubernetes.io/name": "velero",
  "helm.sh/chart": "velero-2.13.6"
}
```

We could add the `"component": "velero"` label to the Velero deployment installed using helm and use that to select the deployment at https://github.com/vmware-tanzu/velero/blob/main/pkg/cmd/cli/plugin/add.go#L60

**Comment by davemazur** [comment]
Just incurred the same issue and spent a good portion of the day trying to solve.  Definitely should be documented at the very least.

**Comment by codegold79** [comment]
I'll take this issue. Currently (and I'll need to further investigate these paths more fully), I'm thinking of doing the following:
1. Get rid of the `--generate-name` flag in the Helm install. Instead, have Helm name the Velero deployment, "velero". As of now, I can't see a reason to generate random names. And even though, as @brito-rafa reported, removing the flag will fix this issue #3088, I'd still like to make another change.
1. Change Velero to follow the Kubernetes best practice of selecting objects with labels. As @ashish-amarnath suggested, look for the deployment with the `component=velero` label instead of looking for a deployment with the name "velero". I'd like to make that change for anywhere looking for the Velero deployment object and not only change it for when a plugin is added.

**Comment by jenting** [comment]
> 2. Change Velero to follow the Kubernetes best practice of selecting objects with labels. As @ashish-amarnath suggested, look for the deployment with the `component=velero` label instead of looking for a deployment with the name "velero". I'd like to make that change for anywhere looking for the Velero deployment object and not only change it for when a plugin is added.

I'd vote for option 2.

**Comment by codegold79** [comment]
Thanks @jenting for your feedback and assigning this Issue to me. 

I was thinking of doing both 1 and 2 in the list above. 

I see you only chose part 2. Do you see a problem with part 1 where I don't generate a random name? I was thinking we'll set the deployment name to "Velero" and also change Velero so it uses a label to select the Velero deployment.
