### ISSUE TITLE
Velero Restic cache is not shrinking once backup is done

### ISSUE THREAD

**Issue by jwierzbo** [vmware-tanzu/velero#3097]
**What steps did you take and what happened:**
Since 7 days memory usage in velero-restic pod is constant on 14 GB level.
Backup is done only once a day, during night.

**What did you expect to happen:**
Once backup is done, cache should be released.

**The output of the following commands will help us better understand what's going on**:
```schedules:
  daily-backup:
    schedule: "15 0 * * *"
    template:
      volumeSnapshotLocations:
      - aws
      storageLocation: aws
      ttl: "2016h"
      includedNamespaces:
      - '*'
```

**Environment:**

- Velero version (use `velero version`):  1.3.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):  1.14.10
- Kubernetes installer & version:
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
![image-2020-11-18-16-36-45-697](https://user-images.githubusercontent.com/2726393/99552195-00911d00-29bd-11eb-872f-f55f4cd8176d.png)

**Comment by dsu-igeek** [comment]
That's expected behavior with garbage collected languages such as Go.  You can try restarting the Restic pods, if subsequent backups do not use as much memory it should remain lower.
