### ISSUE TITLE
Possible issue with multi-zone statefulsets

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#310]
1. Create a GKE cluster (1.8.7 was the reported version), make sure it spans 2 zones
1. Deploy a statefulset that has nodes in both zones, using pvc claim templates (e.g. https://github.com/kubernetes/charts/tree/master/stable/mongodb-replicaset)
1. Take a backup
1. Delete everything related to the statefulset
1. Restore (should work fine)
1. Restore again

At this point, we should probably hit #192. We have a report that 2 of the 3 volumes in the statefulset restored successfully, while the 3rd briefly showed up in the cloud console, then disappeared.

**Comment by unguiculus** [comment]
The cluster is in `europe-west3-a` with `europe-west3-b` as additional zone. The statefulset had three volumes, two in `europe-west3-b`, one in `europe-west3-a`. The volumes in `europe-west3-b` always restored, that in `europe-west3-a` failed to restore. It quickly showed up with an error in the GCP console and then disappeared again. See screenshot.

![image](https://user-images.githubusercontent.com/925412/36036070-23e236e0-0db9-11e8-8621-180d689f1c15.png)

**Comment by eleanor-millman** [comment]
Closed until we hear that it affects more users.
