### ISSUE TITLE
Velero phase is failed but taking backup.

### ISSUE THREAD

**Issue by doronmak** [vmware-tanzu/velero#3103]
I'm running velero on azure when I run backup describe [NAME]
I got  failed (run `velero backup logs 221120200940` for more information)
but when I see the log there's no error msg only msg like 
Found associated CRD backups.velero.io to add to backup" backup=velero/221120200940 logSource="pkg/backup/backup.go:500"
time="2020-11-22T07:38:29Z" level=info msg=" Skipping item because it's already been backed up." back
when I go to the blob storage on azure I can see the gz file, so I don't know why there's a problem taking backup.

![Screenshot from 2020-11-22 10-23-40](https://user-images.githubusercontent.com/39282767/99898793-e4d39280-2cac-11eb-9643-e97d4de1bdeb.png)

*velero version:
Client:
	Version: v1.5.1
	Git commit: 87d86a45a6ca66c6c942c7c7f08352e26809426c
Server:
	Version: v1.5.1

*Velero features (use `velero client config get features`): 
no set

*Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-20T16:22:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

*os release : 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.1
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

I'm want to be sure that I take a full backup and work. (not sure about the phase)
[221120200940_describe.txt](https://github.com/vmware-tanzu/velero/files/5579255/221120200940_describe.txt)
[221120200940_log.txt](https://github.com/vmware-tanzu/velero/files/5579256/221120200940_log.txt)
[kubectl_velero_logs.txt](https://github.com/vmware-tanzu/velero/files/5579257/kubectl_velero_logs.txt)

**Comment by dsu-igeek** [comment]
It looks like there was an error when it was trying to finalize the upload of the backup.  Please add what you're seeing in the bucket and list out the backup storage locations using `velero backup-location get -o yaml`

Is this failing every time or does it sometimes succeed?

**Comment by dsu-igeek** [comment]
We've also seen issues where the plugin runs out of memory.  Please increase the memory limit on the Velero pod to 512Mi and let us know if that helps.

**Comment by carlisia** [comment]
This issue might have been resolved, closing.

**Comment by MKruger777** [comment]
I am seeing exactly these symptoms. Did the memory increase fix the issue @doronmak  Many thanks! :-)
