### ISSUE TITLE
Backup always PartiallyFailed due to rpc error: code = Unknown desc = InvalidVolume.NotFound 

### ISSUE THREAD

**Issue by woody3549** [vmware-tanzu/velero#3122]
**What steps did you take and what happened:**
Create a new backup.

**What did you expect to happen:**
Backup should be successfull.

**The output of the following commands will help us better understand what's going on**:
time="2020-12-01T17:00:12Z" level=error msg="Error backing up item" backup=velero/velero-cluster-backup-202012011800 error="error getting volume info: rpc error: code = Unknown desc = InvalidVolume.NotFound: The volume 'vol-xxx' does not exist.\n\tstatus code: 400, request id: c9b5b826-fa50-44e0-bcb4-ee57259435a7" logSource="pkg/backup/backup.go:455" name=name

**Environment:**

- Velero version (use `velero version`): 1.5.2
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.14.1
- Kubernetes installer & version: v1.14.1
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Debian

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by carlisia** [comment]
Hi @woody3549, can you please browse through these and see if any of these closed issues apply to your case: https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+InvalidVolume.NotFound+is%3Aclosed.

**Comment by woody3549** [comment]
Hi @carlisia 
I have found and resolved my issue.

Thanks a lot

**Comment by everythings-gonna-be-alright** [comment]
@woody3549 could you provide more details about how you solve this issue ?

**Comment by everythings-gonna-be-alright** [comment]
```
volumeSnapshotLocation:
    name: default
    provider: aws
    config:
      region: eu-west-1
```
FYI: in my case it happened because of wrong region in `volumeSnapshotLocation` config.

**Comment by Manjudhv** [comment]
> Hi @carlisia I have found and resolved my issue.
> 
> Thanks a lot

I need your help I am facing same issue in my environment can help me out of the issue, since 2 weeks I am trying to resolve this let me know anything

**Comment by victoruyy** [comment]
> > Hi @carlisia I have found and resolved my issue.
> > Thanks a lot
> 
> I need your help I am facing same issue in my environment can help me out of the issue, since 2 weeks I am trying to resolve this let me know anything


Hi, for me the solution was to check into the volumesnapshotlocations, there was bad configured the profile that I was using to connect,

Hope this can help you,

Cheers,
Victor
