### ISSUE TITLE
Allow backup NodeName of PodSpec field

### ISSUE THREAD

**Issue by shellwedance** [vmware-tanzu/velero#3123]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]

Is there any specific reason that NodeName is excluded in restoring?
When I commented out the code line who assigns null string to NodeName in restore and built, the restore is completed well.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by carlisia** [comment]
@nrb I don't know the answer to this question. Please chime in when you have a chance.

**Comment by nrb** [comment]
@shellwedance It's excluded because there's no guarantee that the cluster being restored into will have the same nodes as the original cluster, especially in cloud environments.

Can you describe your scenario in more detail? What are you using it for? My understanding of the Kubernetes scheduler was that the node name being retained would mean that the pod would always be tied to that node, and if the node were gone, the pod would never get rescheduled (such as on a new cluster).

**Comment by shellwedance** [comment]
> Can you describe your scenario in more detail? What are you using it for? My understanding of the Kubernetes scheduler was that the node name being retained would mean that the pod would always be tied to that node, and if the node were gone, the pod would never get rescheduled (such as on a new cluster).

My scenario,
- I want to utilize velero as a DR solution in on-prem cloud. The standby cluster is totally same with active cluster; same node number, same node name and even same CPU and memory per node.
- Some products in my cloud require their pods to be scheduled to specific nodes. For example, a pod which mounts specific disk. Currently they use NodeName field.

I think velero should provide general solution to various scenarios such as using NodeName field. And it is user's responsibility to control the backup/restore to be successful. (ex. constructing same cluster or not using NodeName, etc)

**Comment by nrb** [comment]
Thanks @shellwedance, that makes sense.

I think the preferred way to handle this is to use [nodeAffinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity).

Relying on a specific node name is an antipattern and I don't think it makes sense for Velero to support it.
