### ISSUE TITLE
How to backup and restore  k8 cluster using  velero rest APIs ?

### ISSUE THREAD

**Issue by shirishbhalekar** [vmware-tanzu/velero#3124]
I am not able to find a How to documents in Velero ?

I want to check is the restAPIs available for backup and restore ?

Is velero can be used with command line only or any other way we can use it ?

If available then can anybody explain with a example document of how to use it .

Thanks,
Shirish

**Comment by carlisia** [comment]
Hi @shirishbhalekar, Velero does not expose rest APIs for operations, only the CLI. You may use the k8s API via `kubectl` to operate it as well. I hope this helps.

**Comment by shirishbhalekar** [comment]
Thanks for the Update.
Can I get Information about what Kubectl Rest API used inside Velero in any logs.

**Comment by carlisia** [comment]
This is the API information we have documented: https://velero.io/docs/v1.5/api-types/. That and the documentation of the kubectl rest api should give you what you need.
