### ISSUE TITLE
velero snapshotter plugin for Aws EBS

### ISSUE THREAD

**Issue by shubhangisss** [vmware-tanzu/velero#3128]
I want to take backup of AWS EBS volume. As mentioned in the document https://github.com/vmware-tanzu/velero-plugin-for-aws, Velero provides volume snapshotter plugin for AWS EBS but i haven't found it anywhere in the document mentioned above. 

**What did you expect to happen:**
I want to know about the volume snapshotter plugin for AWS EBS using which i can take backup of the ebs volume.

**Environment:**
- Velero version: 1.4.2

**Comment by carlisia** [comment]
Look for snapshot location in that document. Mainly, you have to have this configured as per your settings with AWS: https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/main/volumesnapshotlocation.md. Does this help?

**Comment by nrb** [comment]
This is documented in the README at the location Carlisia pointed out. The plugin combines both AWS object storage and EBS snapshotting into 1 package.
