### ISSUE TITLE
Velero backups stuck InProgress

### ISSUE THREAD

**Issue by woody3549** [vmware-tanzu/velero#3131]
What steps did you take and what happened:
Create a new backup.

What did you expect to happen:
Backup should be successfull.

The output of the following commands will help us better understand what's going on:
backup-20201204040046   InProgress   0        0          2020-12-04 05:00:46 +0100 CET   6d        default            <none>

velero backup describe backup-20201204040046
Name:         backup-20201204040046
Namespace:    velero
Labels:       velero.io/schedule-name=backup
              velero.io/storage-location=default
Annotations:  <none>
Phase:  InProgress
Errors:    0
Warnings:  0
Namespaces:
  Included:  *
  Excluded:  <none>
Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto
Label selector:  <none>
Storage Location:  default
Velero-Native Snapshot PVs:  auto
TTL:  168h0m0s
Hooks:  <none>
Backup Format Version:
Started:    2020-12-04 05:00:46 +0100 CET
Completed:  <n/a>
Expiration:  2020-12-11 05:00:46 +0100 CET
Velero-Native Snapshots: <none included>

velero backup logs backup-20201204040046
Logs for backup "backup-20201204040046" are not available until it's finished processing. Please wait until the backup has a phase of Completed or Failed and try again.

Environment:

    Velero version (use velero version): v1.1.0
    Velero features (use velero client config get features): features:
    Kubernetes version (use kubectl version): v1.14.1
    Kubernetes installer & version: v1.14.1
    Cloud provider or hardware configuration: AWS
    OS (e.g. from /etc/os-release): Debian

Should I consider upgrading velero, please ?

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by carlisia** [comment]
Hey @woody3549, what is the output of `kubectl logs <name of the velero pod> -n velero`?

**Comment by woody3549** [comment]
velero backup logs backup-20201204040046
Logs for backup "backup-20201204040046" are not available until it's finished processing. Please wait until the backup has a phase of Completed or Failed and try again.

**Comment by nrb** [comment]
@woody3549 Did you happen to restart the Velero pod? It looks like it may have crashed and left the backup hung.

You can delete this backup safely with `kubectl delete -n velero backup.velero.io/backup-20201204040046` and retry a new backup to see if the problem happens again.

**Comment by woody3549** [comment]
Hello @nrb,

Still the same, the same problem happens again.
Actually all are stuck:
velero get backups
NAME                            STATUS       ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
backup-20201208040000   InProgress   0        0          2020-12-08 05:00:00 +0100 CET   6d        default            <none>
backup-20201207040043   InProgress   0        0          2020-12-07 05:00:43 +0100 CET   5d        default            <none>
backup-20201206040027   InProgress   0        0          2020-12-06 05:00:27 +0100 CET   4d        default            <none>
backup-20201205040006   InProgress   0        0          2020-12-05 05:00:06 +0100 CET   3d        default            <none>
backup-20201203040028   InProgress   0        0          2020-12-03 05:00:28 +0100 CET   1d        default            <none>
backup-20201202040011   InProgress   0        0          2020-12-02 05:00:11 +0100 CET   19h       default            <none>

What can I do ? is that a good idea to update to latest version ?
Note that it's a production environment.

Thanks and regards

**Comment by woody3549** [comment]
Hello,

Describing the velero pod, I get the following error:

│ Last State:     Terminated                                                                                                                                                                              │      Reason:       OOMKilled                                                                                                                                                                               │       Exit Code:    137                                                                                                                                                                                     │       Started:      Wed, 09 Dec 2020 05:00:52 +0100                                                                                                                                                         │       Finished:     Wed, 09 Dec 2020 11:01:59 +0100

It gets killed to an OutOfMemory error.

Regards,

**Comment by woody3549** [comment]
Hello,

I don't know why but some resources limits were applied to velero deployment.
I have managed to solve the issue.

Thanks
