### ISSUE TITLE
Document resticRepoPrefix

### ISSUE THREAD

**Issue by a-mccarthy** [vmware-tanzu/velero#3136]
**Describe the problem/challenge you have**
We should document the `resticRepoPrefix` and how it should be used.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by qiuming-best** [comment]
resticRepoPrefix is one parameter that [used](https://github.com/vmware-tanzu/velero/blob/v1.8.1/pkg/restic/command.go#L90-L92) by `restic --repo` flag, which specifies the repository that restic to backup to or restore from

The resticRepoPrefix could be returned by [getRepoPrefix](https://github.com/vmware-tanzu/velero/blob/v1.8.1/pkg/restic/config.go#L48-L90) function. If the backend storage provider is AWS, Azure, or GCP, this function will join the configuration from the BSL config into one string that is compatible with restic repository. But if the backend storage provider is not of the three above, the resticRepoPrefix should be [configured](https://github.com/vmware-tanzu/velero/blob/v1.8.1/pkg/restic/config.go#L60) into BSL config.  the BSL config is key-value pairs stored in [map](https://github.com/vmware-tanzu/velero/blob/v1.8.1/pkg/apis/velero/v1/backupstoragelocation_types.go#L32), the key is `resticRepoPrefix`.

Velero defined the [ObjectStore](https://github.com/vmware-tanzu/velero/blob/v1.8.1/pkg/plugin/velero/object_store.go#L26-L65) interface exposes basic object-storage operations required, for the third-party plugins will first initialize configuration by implementing the Init function. In this function, the third-party plugin should [validate](https://github.com/vmware-tanzu/velero/blob/v1.8.1/pkg/plugin/framework/validation.go#L27) all BSL configure map keys. So, not of the three providers should add  `resticRepoPrefix` into validKeys parameters. or even configured in BSL, the validation cannot be passed.

**Comment by qiuming-best** [comment]
@a-mccarthy I've made my comments
