### ISSUE TITLE
AWS Role to be assumed not being read from configuration file.

### ISSUE THREAD

**Issue by jwalters-gpsw** [vmware-tanzu/velero#3142]
### Versions
Version: v1.3.2
AWS Plugin Version: 1.0.1
AWS EKS Version: 1.15

### Description
Though my config file has role_arn and source_profile entries, it does not appear the role is being assumed.

### Details
`$ velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.0.1 --bucket backup-velero  --secret-file ./config`

```
time="2020-04-07T23:01:43Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:413"
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = AccessDenied: Access Denied
```
`./config`
```
[default]
region = us-west-2
role_arn=arn:aws:iam::99999999999:role/IAM_CARole_XXX
source_profile=eks

[profile eks]
aws_access_key_id = AKIAXXXXXXXX
aws_secret_access_key = mfrXXXXXXXXXXXXXXXX
```
### Additional Information
I ran up another pod in the same cluster using the `mesosphere/aws-cli:latest` docker image. Then `exec`ed into the image and copied the same config (pointed to with `AWS_CONFIG_FILE` environment variable ). All the `aws s3` commands worked fine on the bucket.

I suspect the `stscreds.NewCredentials` call needs to be used as described in **Assume Role** section [here](stscreds.NewCredentials).

**Comment by luisdavim** [comment]
I've opened a PR on the AWS plugin to solve this: https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/168

**Comment by danfengliu** [comment]
I'm facing AccessDenied issue, @reasonerjt  will submit a PR to fix it.

**Comment by reasonerjt** [comment]
Seems this is b/c when velero is installed via CLI the credential file is set via environment variable.
This PR should fix the problem:
https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/171

**Comment by reasonerjt** [comment]
Closing this issue as fixed.
