### ISSUE TITLE
Backup searches for disk on the wrong GCP project

### ISSUE THREAD

**Issue by robersongomes** [vmware-tanzu/velero#3147]
**Describe the problem/challenge you have:**

We have multiple GCP projects and we manage all the access using [IAM Folders](https://cloud.google.com/resource-manager/docs/access-control-folders), with one folder for each environment (production/development/staging/qa/etc).
For each environment, we create a folder with all GCP projects for that environment. Service accounts are created on a single GCP project and the permissions are set at folder level.

We have clusters on all GCP projects, so the backup fails because it searches for the disk on the GCP project that the credentials belongs to, instead of searching on the GCP project that the cluster resides.

For example, if the service account is created on `project-one' and the backup is running on a cluster on project `project-two`, we get the following error:
> level=error msg="Error backing up item" backup=velero/backup-1 error="error getting volume info: rpc error: code = Unknown desc = googleapi: Error 404: The resource 'projects/**project-one**/zones/europe-west2-a/disks/my-cluster-pvc-b908200f-3d8f-461e-a51a-b8432bf4cca2' was not found, notFound" group=v1 logSource="pkg/backup/resource_backupper.go:287" name=search-0 namespace= resource=pods

That happens because the project id is retrieved from the credentials file:
https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/v1.0.1/velero-plugin-for-gcp/volume_snapshotter.go#L68

**Describe the solution you'd like:**

I would like to be able to override the project id where the disks are located (or that this information is retrieved from the cluster).

**Environment:**

Velero version: 1.3.2
Velero plugin for GCP version: 1.0.1
Kubernetes version: 1.15
Cloud provider or hardware configuration: GCP/GKE

**Comment by vadasambar** [comment]
Any updates on this?
I am trying to restore clusters from our production GCP project to QA GCP project so that we can test upgrades in a pre prod setup. This issue is a blocker for us.
