### ISSUE TITLE
Support for zone redundant snapshot of Azure Disk

### ISSUE THREAD

**Issue by jaygridley** [vmware-tanzu/velero#3153]
There is a option to create zone redundant snapshots of Azure Disks in regions with availabiltiy zones see https://azure.microsoft.com/en-us/updates/azure-managed-snapshots-images-ga.

**Comment by antonmatsiuk** [comment]
any news on this? The feature would be highly appreciated.

**Comment by stromvirvel** [comment]
Hello @eleanor-millman 
Thanks for the explanation. Does closing this issue means that you're not planning on implementing that feature anymore?

**Comment by eleanor-millman** [comment]
Apologies, not sure why I closed it. I added the icebox label to show that we will not be considering it for the next release or two at least (unless someone outside of the core team wants to work on it!) but did not intend to close it. Thanks for bringing this to my attention @stromvirvel!

**Comment by ywk253100** [comment]
Dup of https://github.com/vmware-tanzu/velero/issues/4608
