### ISSUE TITLE
Least privileges of Service Principal 

### ISSUE THREAD

**Issue by jaygridley** [vmware-tanzu/velero#3154]
The documentation states that the Service Principal used with Velero should have a role Contributor. This role is quite open and some company policies do not allow this. The documentation should be updated to state the least privileges for the Service Principal.

**Comment by seboss666** [comment]
Just an update : in the last months, we applied something we were able to use with only builtin roles (on some subs, we can't create custom roles). Two assignments : storage account contributor on the target storage account, and contributor on cluster_node_resource_group.

When talking with a coworker, we discovered a commit that details the needed permissions to include in a custom role : 
https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/commit/4b74c4eee8cdda8ec1723c69045fb21aae75a9d6

**Comment by horihel** [comment]
thanks @seboss666 .
i think the original criticism was the fact that the Readme mentions those permissions but then the instructions don't use this and just ask you to create a "FullAdmin" SP.
But I assume the amount of possibilities (ServicePrincipal, ManagedPrincipal, AADPodIdentity or not) might also make documenting all of this hard to read in the end.

We used the above information to create the custom roles via terraform and early tests seem to work fine.

**Comment by ywk253100** [comment]
The doc is refined, closing this issue

**Comment by cedricve** [comment]
Any thought on transferring backups between two subscriptions from two different AD's? I got following error when trying this.

ERROR: The access token is from the wrong issuer 'https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/'. It must match the tenant 'https://sts.windows.net/17f561e2-169e-4fa2-9c29-c466fb636c66/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/17f561e2-169e-4fa2-9c29-c466fb636c66' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
