### ISSUE TITLE
Backup Azure Managed Disks from multiple Resource Groups

### ISSUE THREAD

**Issue by cholm321** [vmware-tanzu/velero#3157]
We have an AKS cluster with velero installed in an enterprise setup.

On the cluster we have 
app1     with managed disk in ResourceGroup 1
app2     with managed disk in ResourceGroup 2
app3     with managed disk in ResourceGroup 3

All Resource Groups has the AKS spn as contributor.

We have been poking a little around, but it seem that the ResourceGroup must be specified on velero install.

Have we missed something - is it possible to do all configuration at backup stage?
Or better, let the plugin lookup which ResourceGroup the disks are located by inspecting the pv objects.

**Comment by francois-travais** [comment]
I've the same issue: my AKS cluster is in a resource group while all the nodes, and therefore the PVC disks, are in another. Velero is stuck searching for the disks in AKS cluster instead of the nodes resource group, even if I change the resource group of the `VolumeSnapshotLocation`

**Comment by dploeger** [comment]
Any news about this? It's still valid for Velero helm 2.29.4 / Velero image 1.8.1 and velero plugin for azure v1.4.1 and this makes velero unable to backup dynamic volumes.

**Comment by Chivolta** [comment]
Hi guys, 
Any update? I have similiar use case.

**Comment by dploeger** [comment]
@ashish-amarnath  Reading this again, I believe it's not about multiple credentials.

With Azure, the thing is that the cluster is in resourcegroup "dev" and AKS automatically creates a second resource group like "MC_dev_myk8scluster_europewest" where it puts all the k8s resource it creates for Azure (like the said managed disks for PVCs).

So maybe it's the fault of the azure plugin for velero trying to search for the disks in the wrong resource group.

**Comment by dploeger** [comment]
However, this worked in helm chart 2.15.0 with azure plugin 1.1.0.

**Comment by dploeger** [comment]
Running azure plugin 1.1.0 with the most current helm chart verison 2.29.6 yields no errors but instead skips the PVCs:

```
time="2022-05-23T10:45:14Z" level=info msg="Backing up item" backup=velero/test2 logSource="pkg/backup/item_backupper.go:122" name=pvc-8426a489-4cb1-441e-a144-33ae7e4bfde4 namespace= resource=persistentvolumes
time="2022-05-23T10:45:14Z" level=info msg="Executing takePVSnapshot" backup=velero/test2 logSource="pkg/backup/item_backupper.go:395" name=pvc-8426a489-4cb1-441e-a144-33ae7e4bfde4 namespace= resource=persistentvolumes
time="2022-05-23T10:45:14Z" level=info msg="label \"topology.kubernetes.io/zone\" is not present on PersistentVolume, checking deprecated label..." backup=velero/test2 logSource="pkg/backup/item_backupper.go:422" name=pvc-8426a489-4cb1-441e-a144-33ae7e4bfde4 namespace= persistentVolume=pvc-8426a489-4cb1-441e-a144-33ae7e4bfde4 resource=persistentvolumes
time="2022-05-23T10:45:14Z" level=info msg="label \"failure-domain.beta.kubernetes.io/zone\" is not present on PersistentVolume" backup=velero/test2 logSource="pkg/backup/item_backupper.go:426" name=pvc-8426a489-4cb1-441e-a144-33ae7e4bfde4 namespace= persistentVolume=pvc-8426a489-4cb1-441e-a144-33ae7e4bfde4 resource=persistentvolumes
time="2022-05-23T10:45:14Z" level=info msg="zone info not available in nodeAffinity requirements" backup=velero/test2 logSource="pkg/backup/item_backupper.go:431" name=pvc-8426a489-4cb1-441e-a144-33ae7e4bfde4 namespace= persistentVolume=pvc-8426a489-4cb1-441e-a144-33ae7e4bfde4 resource=persistentvolumes
time="2022-05-23T10:45:14Z" level=info msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/test2 logSource="pkg/backup/item_backupper.go:455" name=pvc-8426a489-4cb1-441e-a144-33ae7e4bfde4 namespace= persistentVolume=pvc-8426a489-4cb1-441e-a144-33ae7e4bfde4 resource=persistentvolumes volumeSnapshotLocation=default
time="2022-05-23T10:45:14Z" level=info msg="Persistent volume is not a supported volume type for snapshots, skipping." backup=velero/test2 logSource="pkg/backup/item_backupper.go:466" name=pvc-8426a489-4cb1-441e-a144-33ae7e4bfde4 namespace= persistentVolume=pvc-8426a489-4cb1-441e-a144-33ae7e4bfde4 resource=persistentvolumes
```

**Comment by dploeger** [comment]
I've forked the charts repo and updated the CRDs for version 2.15.0 to work with current K8s versions: https://github.com/dodevops/tanzu-helm-charts/tree/fix/apiversions

You can download that chart locally and run it with azure-plugin v1.1.0 to make everything work again (and loose features and fixes from more current velero versions obviously) until this is fixed.

**Comment by dploeger** [comment]
Ah, sorry. I just overread the documentation stating that you should use the generated resource group instead of the resource group your cluster is in.

**Comment by snowerem** [comment]
Hi guys,
Any update? WE have similar use case - storage classes in different resource groups and volumes are provisioned. Thats a game changer for Azure backups

**Comment by ywk253100** [comment]
To address this issue, we may need to introduce a new version of the plugin interface which needs the [support of plugin versioning](https://github.com/vmware-tanzu/velero/issues/3285).

And another choice is to use the CSI plugin instead which is going to be GA in v1.9

**Comment by reasonerjt** [comment]
@ywk253100 I think in v1.10 timeframe we may verify if CSI plugin can solve the problem.  If we can solve it via CSI we may consider closing this issue.

**Comment by ywk253100** [comment]
I have verified that this case can be resolved by taking a snapshot with the CSI plugin. For more information about how to use CSI, please refer to the [doc](https://velero.io/docs/v1.9/csi/).

Closing this issue.
