### ISSUE TITLE
Network restrictions on Azure Storage Account not working

### ISSUE THREAD

**Issue by aristosvo** [vmware-tanzu/velero#3158]
When we installed Velero with the Velero plugin for Azure on our AKS cluster in the first place, we didn't restrict our storage on AKS outbound IP, as it was just an experiment.

After this experiment we tried to improve security by restricting to only the outbound IP of our AKS cluster. This doesn't seem to work. AKS documentation refers to account access [here](https://docs.microsoft.com/en-us/azure/aks/troubleshooting#error-when-enabling-allow-access-allow-access-from-selected-network-setting-on-storage-account), but I didn't expect Velero to have the same problem as it runs on the worker nodes.

Any other experiences and/or how to mitigate it?

**Comment by nrb** [comment]
@aristosvo I think the best place for that information right now is in the Azure plugin's README.

**Comment by a-mccarthy** [comment]
To try and summarize here, if you are using AKS and an Azure Storage account in the same region, you need to use [VNET Service Endpoints](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview), as noted in this [issue comment](https://github.com/Azure/AKS/issues/1899#issuecomment-708007553)

> The network restriction option where you whitelist the public IP isn't working, when both resources are in the same region. As the traffic is handled internally in the region itself and never leaves the network via the outbound public IP.

As Nolan mentioned, the best place for this information is on our Azure Plugin's [README](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/README.md)

@aristosvo are you still able to help update the docs for this?

**Comment by aristosvo** [comment]
@a-mccarthy Thanks for notifying! I'm on it, will open an PR in a minute

**Comment by aristosvo** [comment]
@a-mccarthy If you have any feedback: thanks in advance!

I'm not sure whether I should include step-by-step instructions or not.

**Comment by eleanor-millman** [comment]
Closing because fix merged in.
