### ISSUE TITLE
Support for Customer Managed Keys (CMK)

### ISSUE THREAD

**Issue by akcrisp** [vmware-tanzu/velero#3161]
Hi,

Can you confirm if there are any plans to support cmk ? 

https://docs.microsoft.com/en-us/azure/aks/azure-disk-customer-managed-keys

Thanks

Andy

**Comment by nrb** [comment]
@akcrisp This is not on our roadmap and is unlikely to be added soon. The 'Needs Product' label means we need to discuss this with our product management team to prioritize it.

**Comment by eleanor-millman** [comment]
Closing because not on our roadmap for the next couple years.
