### ISSUE TITLE
Annotations are not propagated from schedule to backups

### ISSUE THREAD

**Issue by hudymi** [vmware-tanzu/velero#3164]
**What steps did you take and what happened:**

Defined a `schedule` resource with annotations and labels. Labels are visible on `backup` resources created from the `schedule`, but annotations not. 

**What did you expect to happen:**

Annotations are propagated to the `backup` resources like labels.

**Anything else you would like to add:**

Generally, it would be better to have control witch labels and annotations are propagated to the `backup` resources. Something like with Deployments/Jobs to Pods. In the template, section a metadata section with the ability to define labels/annotations that will be visible on `backup` resources.

**Environment:**

- Velero version (use `velero version`): v1.5.2
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): v1.19.1
- Kubernetes installer & version: kind
- OS (e.g. from `/etc/os-release`): MacOS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ashish-amarnath** [comment]
@hudymi Good news. We have this PR that was merged https://github.com/vmware-tanzu/velero/pull/3067
This will be available in Velero v1.6.

Considering that this issue has been fixed. I am going to close this issue. Please reach out if you have more questions.

**Comment by hudymi** [comment]
@ashish-amarnath thank you 😄

What about creating a separate section for labels/annotations in the `schedule` spec section that will be passed to the `backup`? It may be crucial when you are using a tool that manages cluster state (we are using `qbec`) that has a logic based on labels/annotations. Currently, when labels are propagated from the `schedule` to `backup` it thinks that `backups` are managed by it and want to delete them. Should I create a separate issue for that?
