### ISSUE TITLE
Backup not completed in 24 hours

### ISSUE THREAD

**Issue by guleng** [vmware-tanzu/velero#3175]
**What steps did you take and what happened:**
I have a 300 node k8s cluster
I did(velero backup create  sh-all-12-11-16-30 --exclude-resources job,pod)
This backup has been running for 24 hours and has not been completed

**The output of the following commands will help us better understand what's going on**:

- `kubectl logs deployment/velero -n velero`
`kubectl logs deployment/velero -n velero
time="2020-12-11T08:41:16Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:191"
time="2020-12-11T08:41:16Z" level=info msg="Starting Velero server v1.5.2 (456eb19668f8da603756353d9179b59b5a7bfa04)" logSource="pkg/cmd/server/server.go:193"
time="2020-12-11T08:41:16Z" level=info msg="1 feature flags enabled []" logSource="pkg/cmd/server/server.go:195"
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-remap-version
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-pvc-node-selector
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/cluster-role-bindings
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-preserve-fields
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/init-restore-hook
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2020-12-11T08:41:17Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2020-12-11T08:41:17Z" level=info msg="Checking existence of namespace." logSource="pkg/cmd/server/server.go:380" namespace=velero
time="2020-12-11T08:41:17Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:386" namespace=velero
I1211 08:41:19.549229       1 request.go:621] Throttling request took 1.047821283s, request: GET:https://10.68.0.1:443/apis/monitoring.coreos.com/v1?timeout=32s
time="2020-12-11T08:41:20Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:415"
time="2020-12-11T08:41:25Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:449"
time="2020-12-11T08:41:25Z" level=warning msg="Velero restic daemonset not found; restic backups/restores will not work until it's created" logSource="pkg/cmd/server/server.go:495"
time="2020-12-11T08:41:25Z" level=info msg="Starting controllers" logSource="pkg/cmd/server/server.go:571"
time="2020-12-11T08:41:25Z" level=info msg="Starting metric server at address [:8085]" logSource="pkg/cmd/server/server.go:578"
time="2020-12-11T08:41:25Z" level=info msg="Backup sync period is 1m0s" logSource="pkg/controller/backup_sync_controller.go:76"
time="2020-12-11T08:41:25Z" level=info msg="Waiting for informer caches to sync" logSource="pkg/cmd/server/server.go:836"
time="2020-12-11T08:41:25Z" level=info msg="Done waiting for informer caches to sync" logSource="pkg/cmd/server/server.go:839"
time="2020-12-11T08:41:25Z" level=info msg="Informer cache synced" informer="*v1.DeleteBackupRequest" logSource="pkg/cmd/server/server.go:850"
time="2020-12-11T08:41:25Z" level=info msg="Informer cache synced" informer="*v1.Backup" logSource="pkg/cmd/server/server.go:850"
time="2020-12-11T08:41:25Z" level=info msg="Informer cache synced" informer="*v1.Restore" logSource="pkg/cmd/server/server.go:850"
time="2020-12-11T08:41:25Z" level=info msg="Informer cache synced" informer="*v1.PodVolumeBackup" logSource="pkg/cmd/server/server.go:850"
time="2020-12-11T08:41:25Z" level=info msg="Informer cache synced" informer="*v1.VolumeSnapshotLocation" logSource="pkg/cmd/server/server.go:850"
time="2020-12-11T08:41:25Z" level=info msg="Informer cache synced" informer="*v1.DownloadRequest" logSource="pkg/cmd/server/server.go:850"
time="2020-12-11T08:41:25Z" level=info msg="Informer cache synced" informer="*v1.ResticRepository" logSource="pkg/cmd/server/server.go:850"
time="2020-12-11T08:41:25Z" level=info msg="Informer cache synced" informer="*v1.Schedule" logSource="pkg/cmd/server/server.go:850"
time="2020-12-11T08:41:25Z" level=info msg="Server starting..." logSource="pkg/cmd/server/server.go:896"
time="2020-12-11T08:41:25Z" level=info msg="Starting controller" controller=schedule logSource="pkg/controller/generic_controller.go:76"
time="2020-12-11T08:41:25Z" level=info msg="Starting controller" controller=gc-controller logSource="pkg/controller/generic_controller.go:76"
time="2020-12-11T08:41:25Z" level=info msg="Starting controller" controller=backup logSource="pkg/controller/generic_controller.go:76"
time="2020-12-11T08:41:25Z" level=info msg="Starting controller" controller=backup-sync logSource="pkg/controller/generic_controller.go:76"
time="2020-12-11T08:41:25Z" level=info msg="Starting controller" controller=restic-repository logSource="pkg/controller/generic_controller.go:76"
time="2020-12-11T08:41:25Z" level=info msg="Starting controller" controller=backup-deletion logSource="pkg/controller/generic_controller.go:76"
time="2020-12-11T08:41:25Z" level=info msg="Starting controller" controller=restore logSource="pkg/controller/generic_controller.go:76"
time="2020-12-11T08:41:25Z" level=info msg="Removing existing deletion requests for backup" backup=sh-all-12-11-16-30 controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:469" name=sh-all-12-11-16-30-vqjcv namespace=velero
time="2020-12-11T08:41:25Z" level=info msg="Checking for expired DeleteBackupRequests" controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:592"
time="2020-12-11T08:41:25Z" level=info msg="Starting controller" controller=downloadrequest logSource="pkg/controller/generic_controller.go:76"
time="2020-12-11T08:41:25Z" level=info msg="Done checking for expired DeleteBackupRequests" controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:620"
time="2020-12-11T08:41:25Z" level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"
time="2020-12-11T08:41:25Z" level=error msg="Error in syncHandler, re-adding item to queue" controller=backup-deletion error="error downloading backup: error copying Backup to temp file: rpc error: code = Unknown desc = error getting object backups/sh-all-12-11-16-30/sh-all-12-11-16-30.tar.gz: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: 164F9CE1D60D05DF, host id: " error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/restore_controller.go:558" error.function=github.com/vmware-tanzu/velero/pkg/controller.downloadToTempFile key=velero/sh-all-12-11-16-30-vqjcv logSource="pkg/controller/generic_controller.go:140"
time="2020-12-11T08:41:25Z" level=info msg="Removing existing deletion requests for backup" backup=sh-all-12-11-16-30 controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:469" name=sh-all-12-11-16-30-vqjcv namespace=velero
time="2020-12-11T08:41:25Z" level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"
time="2020-12-11T08:41:25Z" level=info msg="No backup locations were ready to be verified" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:120"
time="2020-12-11T08:41:25Z" level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"
time="2020-12-11T08:41:25Z" level=info msg="No backup locations were ready to be verified" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:120"
time="2020-12-11T08:41:25Z" level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"
time="2020-12-11T08:41:25Z" level=info msg="No backup locations were ready to be verified" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:120"
time="2020-12-11T08:41:25Z" level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"
time="2020-12-11T08:41:25Z" level=info msg="No backup locations were ready to be verified" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:120"
time="2020-12-11T08:41:25Z" level=error msg="Error in syncHandler, re-adding item to queue" controller=backup-deletion error="error downloading backup: error copying Backup to temp file: rpc error: code = Unknown desc = error getting object backups/sh-all-12-11-16-30/sh-all-12-11-16-30.tar.gz: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: 164F9CE1DC9861B4, host id: " error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/restore_controller.go:558" error.function=github.com/vmware-tanzu/velero/pkg/controller.downloadToTempFile key=velero/sh-all-12-11-16-30-vqjcv logSource="pkg/controller/generic_controller.go:140"`

- `kubectl get backup/<backupname> -n velero -o yaml`
```
kubectl get backup/sh-all-12-11-16-40 -n velero -o yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/source-cluster-k8s-gitversion: v1.14.1
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "14"
  creationTimestamp: "2020-12-11T08:41:09Z"
  generation: 2
  labels:
    velero.io/storage-location: default
  name: sh-all-12-11-16-40
  namespace: velero
  resourceVersion: "4010841837"
  selfLink: /apis/velero.io/v1/namespaces/velero/backups/sh-all-12-11-16-40
  uid: 9de8543b-3b8c-11eb-8b89-98039b77743a
spec:
  defaultVolumesToRestic: false
  excludedResources:
  - jobs
  - pods
  hooks: {}
  includedNamespaces:
  - '*'
  storageLocation: default
  ttl: 720h0m0s
status:
  expiration: "2021-01-10T08:41:09Z"
  formatVersion: 1.1.0
  phase: InProgress
  startTimestamp: "2020-12-11T08:41:09Z"
  version: 1
```

**Environment:**

- Velero version (use `velero version`): 1.15.2
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.14.1
- Kubernetes installer & version: Binary
- Cloud provider or hardware configuration: 
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.1 LTS

**Comment by nrb** [comment]
Did you restart the Velero pod by any chance? It looks like the pod has restarted and is trying to delete a nonexistent backup based on this line:


```
time="2020-12-11T08:41:25Z" level=error msg="Error in syncHandler, re-adding item to queue" controller=backup-deletion error="error downloading backup: error copying Backup to temp file: rpc error: code = Unknown desc = error getting object backups/sh-all-12-11-16-30/sh-all-12-11-16-30.tar.gz: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: 164F9CE1DC9861B4, host id: " error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/restore_controller.go:558" error.function=github.com/vmware-tanzu/velero/pkg/controller.downloadToTempFile key=velero/sh-all-12-11-16-30-vqjcv logSource="pkg/controller/generic_controller.go:140"
```

Velero currently has a bug where restarting the pod will cause backups to remain in the `InProgress` state, but not actually have any work happen.

If the backup has been deleted from object storage already, you can safely remove it from the Kubernetes cluster with `kubectl delete -n velero backups.velero.io/sh-all-12-11-16-30`.

**Comment by nrb** [comment]
I think this is a case of https://github.com/vmware-tanzu/velero/issues/2877

**Comment by wu0407** [comment]
same issue , becuase velero pod is oom killed.

**Comment by carlisia** [comment]
Closing this in favor of #2877. Please add any related comment to that issue.
