### ISSUE TITLE
Add flag to the schedule cmd to configure the `useOwnerReferencesInBackup` option

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3176]
PR https://github.com/vmware-tanzu/velero/pull/3127 added an option to add owner reference in a backup when creating it from a schedule. It would be nice to add a flag to the `schedule` to set this value. 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
@matheusjuvelino Will you be able to work on this in January?

**Comment by matheusjuvelino** [comment]
@nrb I believe I already managed to implement it.

the next step is to pull request for this implementation.
