### ISSUE TITLE
Error getting backup store for this location

### ISSUE THREAD

**Issue by lmdkfs** [vmware-tanzu/velero#3178]
i follow this document to run velero server locally: https://velero.io/docs/v1.5/run-locally/
command: `./_output/bin/darwin/amd64/velero server`

encountered the following error:

```
INFO[0016] No backup locations were ready to be verified  controller=backupstoragelocation logSource="/Users/zhuruiqing/data/go-projects/velero/pkg/controller/backupstoragelocation_controller.go:120"
INFO[0021] Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available  controller=backupstoragelocation logSource="/Users/zhuruiqing/data/go-projects/velero/pkg/controller/backupstoragelocation_controller.go:58"
ERRO[0021] Error getting a backup store                  backupstoragelocation=default controller=backupstoragelocation error="unable to locate ObjectStore plugin named velero.io/aws" logSource="/Users/zhuruiqing/data/go-projects/velero/pkg/controller/backupstoragelocation_controller.go:87"
INFO[0021] No backup locations were ready to be verified  controller=backupstoragelocation logSource="/Users/zhuruiqing/data/go-projects/velero/pkg/controller/backupstoragelocation_controller.go:120"
INFO[0031] Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available  controller=backupstoragelocation logSource="/Users/zhuruiqing/data/go-projects/velero/pkg/controller/backupstoragelocation_controller.go:58"
ERRO[0031] Error getting a backup store                  backupstoragelocation=default controller=backupstoragelocation error="unable to locate ObjectStore plugin named velero.io/aws" logSource="/Users/zhuruiqing/data/go-projects/velero/pkg/controller/backupstoragelocation_controller.go:87"
```

backupstoragelocations crds as follows:
```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  creationTimestamp: "2020-12-14T08:50:13Z"
  generation: 1
  labels:
    component: velero
  managedFields:
  - apiVersion: velero.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:component: {}
      f:spec:
        .: {}
        f:objectStorage:
          .: {}
          f:bucket: {}
        f:provider: {}
    manager: velero
    operation: Update
    time: "2020-12-14T08:50:13Z"
  name: default
  namespace: velero
  resourceVersion: "53715056"
  selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/default
  uid: 5296d5f5-9fac-4825-b876-428cf5c67e3b
spec:
  objectStorage:
    bucket: test-1253985742
  provider: aws
```

It is ok in k8s

**Environment:**

- Velero version (use `velero version`):  v1.5.2
- Kubernetes version (use `kubectl version`):1.19.4
- Kubernetes installer & version: 1.18.4
- OS (e.g. from `/etc/os-release`): mac catalina 10.15.7

**Comment by zubron** [comment]
Hi @lmdkfs! When running locally, you will also need to provide a path for velero to find the plugin binaries. By default, velero will look in the directory `/plugins`, which is where the plugins are mounted in the velero deployment.

In this case, as your BSL provider is AWS, it is looking for the [AWS plugin](https://github.com/vmware-tanzu/velero-plugin-for-aws/) binary (`unable to locate ObjectStore plugin named velero.io/aws`). I noticed that we don't provide builds of the binary on our releases page, so you will need to clone that repo and build it locally as well. It uses the same `make` target names so you can go to that directory and run `make local`. Then when running the velero server, you will need to set the `--plugin-dir` flag to the directory where the AWS plugin binary has been built, for example `./_output/bin/darwin/amd64/velero server --plugin-dir </path/to/plugins>/velero-plugin-for-aws/_output/`.

There is an issue with our docs here as it states that this flag is optional, but doesn't state that the plugin binaries need to be present on the machine where you are running the velero server binary. I will open a separate issue for this.

If you are running the server locally for development on the velero project, have you seen our recent changes to [run Velero using Tilt/(https://velero.io/docs/v1.5/tilt/)? This is a simplified development workflow that make it easier to make changes to the velero codebase and have changes built and pushed to a cluster where you are running Velero. If you are interested, please check it out!

I am going to close this issue and open another one for addressing the docs issue. If you have any issues with the guidance here, feel free to reopen.

**Comment by lmdkfs** [comment]
thanks,I found this way yesterday。it works fine.
