### ISSUE TITLE
restore from aws ebs snapshot

### ISSUE THREAD

**Issue by ozbillwang** [vmware-tanzu/velero#3184]
**Describe the problem/challenge you have**
Went through the document in Velero, seems one of backup/restore ways is, backup to and restore from aws s3 bucket.

I don't see the feature to restore from aws ebs snapshot.

The reason why I don't do s3 bucket restore is, 

I have bad experience to take so long time to restore a `/var/jenkins_home` for more than 50GB from S3 bucket. It is not possbile to restore in less than 1~2 hours (RTO and RPO). The copy from s3 to pod takes for ages time. For your reference, Restore a 300MB folder from s3 bucket, takes me 15 ~ 20 minutes. 

If I can go with ebs snapshot/volume solution, the backup and restore would take less than 5 minutes, and I can use the rest time to run the check, when you are on high pressure to get the system back ASAP.

**Describe the solution you'd like**

The reguar backup would be set easily and quickly  if I enable the lifecycle manager on aws ebs directly. I got snapshot daily (/var/jenkins_home) for a EBS volume mounted in jenkins pod which was installed via standard helm chart with StorageClass (aws-ebs provisioner) enabled. 

The aws ebs storageClass creates AWS EBS automatically for Jenkins pod and set PV, and link the PV to PVC as well. 

When do the restore, my plan is to create a new EBS volume from a nominated snapshot, and want to use Velero to restore (or just switch the ebs volume)

**Anything else you would like to add:**
I am not sure if this feature is exist or not. If exist, please guide me the instruction or document.

**Environment:**

- Velero version (use `velero version`): latest 1.5.x
- Kubernetes version (use `kubectl version`): 1.18.x
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
@ozbillwang Velero backups are split into 2 parts - the metadata, which includes Kubernetes metadata, and volume data. [The velero plugin for AWS](https://github.com/vmware-tanzu/velero-plugin-for-aws) includes both. See the documentation there for how to get started with that plugin specifically. Using the combined plugin, you shouldn't need to send EBS data to a bucket.

You can find other supported plugins from our [supported plugins page](https://velero.io/docs/v1.5/supported-providers/)
