### ISSUE TITLE
Velero pod getting crashloopback in IBM Openshift cluster

### ISSUE THREAD

**Issue by mani88451** [vmware-tanzu/velero#3192]
Hi , 

I am trying to install velero in IBM Openshift cluster with IBM S3 Object storage credentials. But getting following error in pod logs

time="2020-12-16T16:06:16Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:168"
time="2020-12-16T16:06:16Z" level=info msg="Starting Velero server v1.1.0 (a357f21aec6b39a8244dd23e469cc4519f1fe608)" logSource="pkg/cmd/server/server.go:170"
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/gcp
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/gcp
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2020-12-16T16:06:16Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2020-12-16T16:06:16Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:336" namespace=velero
time="2020-12-16T16:06:16Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:342" namespace=velero
time="2020-12-16T16:06:26Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:371"
time="2020-12-16T16:06:26Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:405"
time="2020-12-16T16:06:26Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:412"
**An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: Backup store contains invalid top-level directories: [backup ouput]**

my credentials-velero file has following information

[default]
aws_access_key_id = 555XXXXXXXXXXXXXXXXXXXX
aws_secret_access_key = fc2e93XXXXXXXXXXXXXX

Install command 

velero install --bucket gen2-test-backup-restore --provider aws --secret-file ./credentials-velero --backup-location-config region=us-south,s3Url=https://s3.us-south.cloud-XXXXX --snapshot-location-config region=us-south

Please help me here..What wrong am doing.

**Comment by zubron** [comment]
The error is happening because Velero has found unexpected directories in the bucket. In this case it found the directories `backup` and `ouput`. Velero expects that a bucket is either empty, or contains only directories managed Velero (in the case where the bucket was previously used for Velero backups). The bucket used by Velero should _only_ be used by Velero. If this is a new install, with a new bucket, then it should be empty.

**Comment by zubron** [comment]
The error is happening because Velero found unexpected directories in the bucket where it will store the backup data. In this case it found the directories `backup` and `ouput` in the bucket. If storing the data in the root directory of the bucket, then it should only contain directories managed by Velero.

If there is other content in the bucket, you can use the `--prefix` option for `velero install` to instruct velero to store all backup data within a specific directory in the bucket.

**Comment by zubron** [comment]
Hopefully the above instructions help. I am going to close this issue, but if you need further assistance or the instructions don't work for some reason please feel free to reopen!
