### ISSUE TITLE
Update our docs with guidance on storing non-velero data in buckets

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/velero#3193]
> The error is happening because Velero found unexpected directories in the bucket where it will store the backup data. In this case it found the directories `backup` and `ouput` in the bucket. If storing the data in the root directory of the bucket, then it should only contain directories managed by Velero.

> If there is other content in the bucket, you can use the `--prefix` option for `velero install` to instruct velero to store all backup data within a specific directory in the bucket. Again, this directory should only be used by Velero.

_Originally posted by @zubron in https://github.com/vmware-tanzu/velero/issues/3192#issuecomment-746661149_

It's not clear from our docs whether a bucket should _only_ contain velero data or whether a bucket can be multi-purpose as long as the user uses the `--prefix` option.

**Comment by nrb** [comment]
> a bucket can be multi-purpose as long as the user uses the --prefix option.

Yes, this is the intention.

**Comment by nrb** [comment]
To rephrase the current support:

Whichever is the root "folder" for Velero will need to be clean. If no prefix is given, Velero assumes it has control of the full bucket. If it has a prefix, then the bucket is safe for multiple uses.
