### ISSUE TITLE
Should restic backup emptydir

### ISSUE THREAD

**Issue by nevermore-muyi** [vmware-tanzu/velero#3203]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]

***When i use restic to backup volume, it backups emptydir to backend.***

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

***Emptydir is ephemeral resource, so backup it may not be reasonable***

 https://github.com/vmware-tanzu/velero/blob/main/pkg/restic/common.go#L171

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
@nevermore-muyi While technically you're right, `emptyDir`s are supposed to be completely ephemeral, we've found that some users do keep critical workload files in these directories, so we'll continue to back these up for now.

**Comment by guanxingfeng** [comment]
Is it better to make  emptyDir a configurable item in backup?

**Comment by navilg** [comment]
Some time when emptyDir is defined in Volumes section of pod but not mounted on pod (not defined in volume mount section). It partially fails to backup. I am using velero 1.6.2. Has this been fixed in any velero version? @Lyndon-Li
