### ISSUE TITLE
Cleanup residual temporary files

### ISSUE THREAD

**Issue by Lighting-wings** [vmware-tanzu/velero#3204]
Hello, I noticed changes about deletebackupcontroller. The function closeAndRemoveFile is put in front of the function return.
![image](https://user-images.githubusercontent.com/24741946/103073326-68610600-4602-11eb-9853-d06656e34cb4.png)

But I don't think this way can be enough. Because the function  downloadToTempFile is used in two places，restorecontroller and deletebackuprequestcontroller.  I found that the function downloadToTempFile can't return error in time if network interruption occurs when we try to download temporary file. The reason is that velero just sendMsg but not recevieMsg when it invokes plugin's function getObject.
![image](https://user-images.githubusercontent.com/24741946/103073932-782d1a00-4603-11eb-89e0-d6c3d1410cc6.png)
 
We can't know what has been happened until try to copy data from stream. At this time temporary file has been created and maybe received some data. So why not try to delete temporary file when an error occurs during copying. There is no need to judge if the file is nil pointer in closeAndRemoveFile function.
![image](https://user-images.githubusercontent.com/24741946/103074315-4ff1eb00-4604-11eb-86cd-c44f6952803f.png)

That's my personal idea. Please correct it if there are some problems. Thank you.

**Comment by Lighting-wings** [comment]
@ncdc

**Comment by ruanchen** [comment]
Same with me. Maybe velero needs enhance the feature.

**Comment by neujie** [comment]
yeah，I think it’s better to put it in downloadToTempFile.

**Comment by zubron** [comment]
For reference, the code in the BackupDeletionController and the change to check if the file is `nil` in `closeAndRemoveFile` were made in #2993.

You're right in that we don't know about certain errors until we try to copy from the stream and was discussed in https://github.com/vmware-tanzu/velero/pull/2993#discussion_r518118234. We could clean up the file in `downloadToTempFile` in the case where an error occurred, however, we will still need to clean up the file in both the BackupDeletionController and in the RestoreController in the case where the download was successful. It was discussed (https://github.com/vmware-tanzu/velero/pull/2993#discussion_r527268051) and decided that we would leave the call to `closeAndRemoveFile` in the outer scope and instead change the function to handle when a nil file pointer is provided.

If you would like to open a PR to update `downloadToTempFile` in the case where an error occurs, that would be great. Thanks!

**Comment by Lighting-wings** [comment]
Thanks a lot. I have some new ideas with it and will open a PR recently. Would you like to discuss with me when I pull a PR ?

**Comment by zubron** [comment]
Great - thanks for taking this on! I will assign this issue to you.

When submitting a PR, the maintainers of the project will be assigned to review it so we will take a look once it has been created. Please see our documentation on [getting started with contributing](https://velero.io/docs/v1.5/start-contributing/) and our [code standards](https://velero.io/docs/v1.5/code-standards/) which includes more details of the requirements when creating PRs. Thanks! :smile:
