### ISSUE TITLE
How does Velero back up PV data in the namespace？？

### ISSUE THREAD

**Issue by misteruly** [vmware-tanzu/velero#3207]
My default storage is OpenEBS. What do I need to do if I want to migrate pv data from the namespace to a cluster outside ning

[root@master1 ~]# velero version
Client:
        Version: v1.5.2
        Git commit: e115e5a191b1fdb5d379b62a35916115e77124a4
Server:
        Version: v1.5.2

**Comment by nrb** [comment]
@misteruly You would need to use restic in this case, since we do not yet have data movement at the snapshot level. Please refer to https://velero.io/docs/latest/restic/ for more information
