### ISSUE TITLE
Backup and restore between two minikube clusters

### ISSUE THREAD

**Issue by owenthereal** [vmware-tanzu/velero#3217]
**Describe the problem/challenge you have**

I'm looking for a solution to backup a minikube cluster and restore it in CI to speed up its builds. I hope that there is a way to backup a running minikube cluster with k8s software that I install to it. The backup is then restored in CI to avoid reinstalling all the basic software every time. This would immensely shorten the CI build time.

I was pointed to `velero` but I'm unclear whether I would be able to use `velero` for this use case and there is no documentation on the minikube support.

Ref: https://github.com/kubernetes/minikube/issues/9991

**Describe the solution you'd like**

There is documentation on velero's minikube integration, if it supports the mentioned minikube use case.

**Anything else you would like to add:**

N/A

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

N/A

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by zubron** [comment]
Hi @owenthereal. Looking at the issue you referenced, it seems that your concern is that Velero is cloud provider specific. Velero can be run in any Kubernetes cluster v1.10 or later (see https://velero.io/docs/v1.5/basic-install/#prerequisites) but it does require access to object storage to store the the backups and associated artifacts and this is where the provider specific element comes in.

In your case, you could run Velero in your minikube clusters to backup and restore the workloads, but you would need an external object storage to store those backups. Velero supports a number of object storage providers (https://velero.io/docs/v1.5/supported-providers/), so you could use any of those but it does not require you to also run your cluster with those providers. You could use minikube for the clusters, but store your backups in AWS S3 for example.

Hopefully this answers your question. I'm going to close this issue but please feel free to reopen if you need further assistance.

**Comment by masalinas** [comment]
@zubron working with velero it can backup kubernetes resources without any problem but make snapshots of your volume is not easy, you must install addons in minikube to use Volume Snaphots and install velero is particular way. You must have the last versions of minikube and velero and with all of then I didn't have any success ... check the issues in velero to find these problems in minikube
