### ISSUE TITLE
Velero will crash if your backup's excludeNamespaces is "**"

### ISSUE THREAD

**Issue by Lighting-wings** [vmware-tanzu/velero#3222]
Version is v1.5.2.
I noticed that velero supports regular expression when you set `includeNamespaces` and `excludeNamespaces ` of bakcup from code. And then velero will happen to panic if a backup's excludeNamespaces is "\*\*" and `includeNamespaces` is empty. I think this is serious.
The reson is that the function `ValidateIncludesExcludes` use normal way to check these settings and "**" will escape from it. And then the function `getNamespacesToList` will return empty slice. Velero handle namespace first in order to resolve particular case. There is the location where velero will happen to panic.

The file is item_collector.go
![image](https://user-images.githubusercontent.com/24741946/103598434-8f420500-4f3d-11eb-9132-38502901b797.png)

Is that neccessary  to use regular expression in code ? I have doubt with it because velero can't handle it when the setting of `includeNamespaces` is like `default* ` and so on. Velero will log error when handle backup like that.

**Comment by zubron** [comment]
Hi @Lighting-wings. Thanks for reporting this!

Velero doesn't currently wildcard matching for namespaces (see https://github.com/vmware-tanzu/velero/issues/1874). With the current implementation it expects either a list of complete namespaces or a single `*` to indicate that it should include all namespaces. If you specify an excludes list with `*` it will fail validation. It definitely shouldn't be panicking with `**` as the input, so we need to add more validation of the arguments here.

**Comment by Lighting-wings** [comment]
So is there a plan to enhance the ability of wildcard ? In fact, I don't think wildcard matching is neccessary for velero. Maybe velero could abandon this feature in order to higher reliability.

**Comment by Lighting-wings** [comment]
Hello,it seems that the process of backup doesn't adapt to wildcard matching so far, especially execute the backup of namespace. When can this feature be supported if there is a plan about it? Or would this feature be considered to quit? Thank you for your reply.
@zubron
