### ISSUE TITLE
Integrate with Borg Backup

### ISSUE THREAD

**Issue by balibebas** [vmware-tanzu/velero#3223]
**Describe the problem/challenge you have**
CLI and docs show restic integration but not borg.

**Describe the solution you'd like**
I'd like to store my backups with Borg using object-deduplication with data encrypted at rest.

**Anything else you would like to add:**
Borg will save me space and help better protect my data.

**Environment:**

- Velero version (use `velero version`): n/a
- Kubernetes version (use `kubectl version`): 1.19.5
- Kubernetes installer & version: k3sup
- Cloud provider or hardware configuration: DO naked droplets
- OS (e.g. from `/etc/os-release`): Ubuntu 20.10 (Groovy Gorilla)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
Hi @balibebas, thanks for your request.

There are a lot of alternatives for filesystem-level backup utilities that folks could use. We chose to go with restic as it fit well with Velero's existing design.

That being said, at the moment we're not going to be integrating any new utilities directly into Velero any time soon. We've begun brainstorming at a very high level on ways to move the restic integration out of Velero's core and into a more generic, swappable data movement layer. This will be part of Velero's 2.0 design, with details to come in the future.

I'll get a generic issue created for tracking this work and link it here once made.

**Comment by balibebas** [comment]
> We've begun brainstorming at a very high level on ways to move the restic integration out of Velero's core and into a more generic, swappable data movement layer.

That sounds like an even better idea. Thanks. There may be many backup tools, though I doubt you'll find one better than Borg anytime soon.
