### ISSUE TITLE
Why velero use restic

### ISSUE THREAD

**Issue by nevermore-muyi** [vmware-tanzu/velero#3226]
**Describe the problem/challenge you have**
As the title shows, why velero use restic as a backup tools, why not borg or other tools?
Restic is in high performance when backup large files, but if there are so many small files, restic may perform poor.

**Describe the solution you'd like**
Is there any plans that velero support multi backup tools, like borg or duplicity?

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
Hi @nevermore-muyi , thanks for your request.

There are a lot of alternatives for filesystem-level backup utilities that folks could use. We chose to go with restic as it fit well with Velero's existing design.

That being said, at the moment we're not going to be integrating any new utilities directly into Velero any time soon. We've begun brainstorming at a very high level on ways to move the restic integration out of Velero's core and into a more generic, swappable data movement layer. This will be part of Velero's 2.0 design, with details to come in the future.

I'll get a generic issue created for tracking this work and link it here once made.
