### ISSUE TITLE
Add a new data movement layer to Velero's architecture

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#3229]
**Describe the problem/challenge you have**

Velero has restic integration as part of it's core, which is useful for moving filesystem level data between storage providers or when a Velero volume snapshot plugin isn't available for a storage platform. However, since the restic integration is part of Velero's core, this is also challenging should someone like to use an alternative solution such as Borg, Duplicity, or Kopia.

**Describe the solution you'd like**

Velero should provide a more abstract, swappable layer for allowing filesystem data transfer out of persistent volume. This should abstract the following things:

 * the tool used to send the data (for example, replace restic with some other executable)
 * the destination for filesystem data (instead of being forced to use restic repositories, allow using something like Borg scp endpoints)

**Anything else you would like to add:**

An implementation of a data mover already exists in the vSphere plugin. It can be used as a reference for bringing this into Velero.

See issues #3223 and #3226 for requests to add replacement tools to Velero.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
We'll do some investigation in the timeframe of v1.9 to better understand the gap but the actual scope may be different from the OP.

**Comment by reasonerjt** [comment]
We are not going to deliver the feature but only  have the concrete design in v1.10, and that's tracked by another issue.

**Comment by kaovilai** [comment]
Covered by https://github.com/vmware-tanzu/velero/issues/6113 and delivered in v1.12
