### ISSUE TITLE
All backup can't be handled if you set wrong format about ttl using kubectl

### ISSUE THREAD

**Issue by Lighting-wings** [vmware-tanzu/velero#3236]
velero version：1.5.2

I used the command `kubectl apply -f` to create a backup named test01. And I made a mistake when I set ttl. The ttl was set `1h0m0s0`. Then the phase of the backup is always `InProgress`. I tried to use velero client to create another backup named test02. Unfortunately, the second backup can't be handled and it didn't even have the field of phase. I tried third backup and so on. The result was all backup can't be handled.

I think the reason is that velero uses `kubebuilder` to create the yaml file of crds. The type of ttl is `metav1.Duration` in `golanguage` struct. But it is `string` in generated yaml file. 

![image](https://user-images.githubusercontent.com/24741946/104417850-02d4b980-55b1-11eb-8dd7-f33f4fc3d592.png)

![image](https://user-images.githubusercontent.com/24741946/104417914-17b14d00-55b1-11eb-8af3-0007e3c5aa5e.png)

So kubernetes will accept all expression as ttl because it is `string`. However, the informer of k8s tried to unmarshal it as `metav1.Duration` in node's cache. The process of backup will be blocked there because informer tries to unmarshal it all the time.

Do you think velero needs webhooks to validate those problems like this ?

**Comment by carlisia** [comment]
Hi @Lighting-wings, thanks for reporting this. Yes, we should have a validation, we'll look into adding that.

Just to let you know about your other issue: Velero processes backups sequentially (we are working on changing this), so while a backup is `InProgress`, no other backup created after will be processed.

**Comment by Lighting-wings** [comment]
Thanks for replying. I'm sorry for that there is a mistake about my description. The first backup which I set wrong format about ttl is not in the phase of `InProgress`. The phase of it is nothing just like subsequent backups.
