### ISSUE TITLE
Whyt velero use files in directory like "resources/pods/namespaces/nginx-example" rather than "resources/pods/v1-preferredversion/namespaces/nginx-example" to restore?

### ISSUE THREAD

**Issue by Lighting-wings** [vmware-tanzu/velero#3237]
velero version : 1.5.2

Hello, I found that velero must generate file in directory like "resources/pods/namespaces/nginx-example" during the process of backup when I read code. But velero doesn't generate file in directory like   "resources/pods/v1-preferredversion/namespaces/nginx-example" if the version of resource is not equal to preferredVersion. Then velero use files in the former directory to restore. I think it maybe a risk. So would you like to explain it for me ? Thank you.

![image](https://user-images.githubusercontent.com/24741946/104420494-e89cda80-55b4-11eb-8a8b-966b56a39f5b.png)

**Comment by carlisia** [comment]
@nrb do you have an insight on this?
