### ISSUE TITLE
Backup would always be phase of “InProgress” if velero failed to patchBackup

### ISSUE THREAD

**Issue by Lighting-wings** [vmware-tanzu/velero#3239]
velero version : 1.5.2

The function `processBackup` in `backup_controller` just log the error and return nil at the end. Sobackup would always be phase of “InProgress” if velero failed to patchBackup. Maybe there need enhancement about the consistency of backup. Of course, it's just  my personal thought. Do you think about it ?

![image](https://user-images.githubusercontent.com/24741946/104423598-42070880-55b9-11eb-86f4-5925f2400438.png)

**Comment by dsu-igeek** [comment]
If the patch fails it probably means we've got some kind of trouble talking to the API server and there's not much we can do to persist the state.  We should be failing InProgress backups on a server restart and there's probably something else we can do to cleanup without a restart.  We'll log this as a bug, thanks.

**Comment by dsu-igeek** [comment]
Think about this as part of #3533 and how we handle weird failure cases.
