### ISSUE TITLE
If you are seeking support, or have a question, or something is not working: please read this

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3264]
Hello everyone, thanks for stopping by to try and resolve your Velero issues.

We ask that you add your question to our Q&A Discussion forum here:

https://github.com/vmware-tanzu/velero/discussions/categories/community-support-q-a

Going forward, support questions added as issues will be converted to our Q&A Discussion forum.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by nrb** [comment]
Closing this, there's no work to be done and it will stay at the top of the issue list.
