### ISSUE TITLE
Backup fails for PVC with storage provisioner `file.csi.azure.com`

### ISSUE THREAD

**Issue by vaishali-prophecy** [vmware-tanzu/velero#3276]
I followed the steps described here to create backup of azure disks with CSI enabled - https://gist.github.com/ashish-amarnath/b4162d2836a63516540bfa1d24783120

Backup and restore worked perfectly fine for me. Then in this example, I changed PVC storage class to azurefile-csi whose provisioner is 'file.csi.azure.com' and created new volumesnapshotclass corresponding to this provisioner. Creating backup fails with the error - 

`time="2021-01-14T16:58:17Z" level=info msg="Waiting for volumesnapshotcontents snapcontent-982200b8-442b-4748-8d95-edc67502424c to have snapshot handle. Retrying in 5s" backup=velero/csi-b3 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:179" pluginName=velero-plugin-for-csi
time="2021-01-14T16:58:17Z" level=info msg="Waiting for volumesnapshotcontents snapcontent-982200b8-442b-4748-8d95-edc67502424c to have snapshot handle. Retrying in 5s" backup=velero/csi-b3 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:179" pluginName=velero-plugin-for-csi
time="2021-01-14T16:58:17Z" level=error msg="Timed out awaiting reconciliation of volumesnapshot csi-app/velero-pvc-azuredisk-kcp9f" backup=velero/csi-b3 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:188" pluginName=velero-plugin-for-csi
time="2021-01-14T16:58:17Z" level=info msg="1 errors encountered backup up item" backup=velero/csi-b3 logSource="pkg/backup/backup.go:451" name=csi-nginx
time="2021-01-14T16:58:17Z" level=error msg="Error backing up item" backup=velero/csi-b3 error="error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=csi-app, name=velero-pvc-azuredisk-kcp9f): rpc error: code = Unknown desc = timed out waiting for the condition" logSource="pkg/backup/backup.go:455" name=csi-nginx
time="2021-01-14T16:58:17Z" level=info msg="Backed up 4 items out of an estimated total of 20 (estimate will change throughout the backup)" backup=velero/csi-b3 logSource="pkg/backup/backup.go:418" name=csi-nginx namespace=csi-app progress= resource=pods`

**Comment by vaishali-prophecy** [comment]
@ashish-amarnath  Can you please help in resolving this?

**Comment by nrb** [comment]
@vaishali-prophecy Do you know if `files.csi.azure.com` has CSI snapshotting capabilities? If not, you'd have to use restic.

Based on the error we never get an actual CSI snapshot generated for Velero to use.

**Comment by dsu-igeek** [comment]
This would be addressed by #3151, closing
