### ISSUE TITLE
vSphere raw block volume backup restore using Velero

### ISSUE THREAD

**Issue by rahulgit1988** [vmware-tanzu/velero#3277]
**Describe the problem/challenge you have**
As of now there is no way to take the backup of raw block volume using velero, Velero should provide the approach and feature.

**Describe the solution you'd like**
Like CSI/Restic to take backup of cloud provider block volume or CSI backed volume, there should be way to backup Raw block volumes

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.5.1
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by dsu-igeek** [comment]
Raw block volume is not supported on vSphere at the moment.  The vSphere Plug-in for Velero is capable of snapshotting and backing up block volumes so when this is supported on vSphere. you will be able to use the plug-in to backup to S3 compatible storage.
