### ISSUE TITLE
Plugins `log.Debugln` does not print debug lines when in debug mode.

### ISSUE THREAD

**Issue by arianitu** [vmware-tanzu/velero#3284]
**What steps did you take and what happened:**
When debugging our plugin, we attempted to print logs like so:

```
b.log.Debugln("Testing debug")
```

These debug lines would not get printed out, even though the server is in debug mode. We can see that in the logs here:

```
time="2021-01-15T16:39:34Z" level=debug msg="starting plugin" args="[/velero run-plugins --log-level debug]" cmd=/velero logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" path=/velero restore=velero/c6f6b8fc-ebd6-4300-bff9-10decebe213b
```

In this case, the `b.log` refers to:

```
type VolumeSnapshotter struct {
	log                     logrus.FieldLogger
```

**What did you expect to happen:**
`b.log.Debugln` should print out debug lines. We had to use `b.log.Info` to print them out.

**Environment:**

- Velero version (use `velero version`): 

```
Client:
	Version: v1.3.1
	Git commit: -
Server:
	Version: v1.3.1
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by carlisia** [comment]
We'll take a look. In the mean time: does `b.log.Debug` work for you?

**Comment by nrb** [comment]
@arianitu Have you tried with v1.4.0? I know we fixed issues with passing feature flags down, but we may need to be sure that the debug flag is passed down, too.

**Comment by jenting** [comment]
I'm using Velero `v1.5.3` and use `log.Infof`, my plugin log won't output also.

**Comment by eleanor-millman** [comment]
Closing until we get more info.
