### ISSUE TITLE
Allow namespace label to back up sub resources

### ISSUE THREAD

**Issue by jemag** [vmware-tanzu/velero#3288]
**Describe the problem/challenge you have**

Currently it seems that there is no easy way for a cluster administrator to manage backups for multiple teams with different needs (I may be wrong, feel free to provide suggestions upon reading the use case below).

Let's say I have 3 teams (A,B and C) with each their own namespace and their own backup requirements (frequency of backup and backup location). I can easily back up their namespace with the --include-namespaces filter, however, to include PVs associated to their PVC I must also --include-cluster-resources. However, if I --include-cluster-resources that will automatically include all PVs from all teams, not just the PVs associated to this specific team.

To go around that, I would need to make use of labels. Currently, the main downside with labels is the targeting of resources. Ensuring that every resources within a namespace contains the appropriate label seems a bit error prone. Unless perhaps by using a webhook which still seems a bit overkill.

What I would like, is an easy way to split each team backup into different locations, targeting different resources and configured with different frequency.

**Describe the solution you'd like**
Allowing labels on namespace to not only back up the namespace but all the contained resources could help alleviate this issue.

In the presented use case, I could simply apply a label "team=A" to a namespace and to a few cluster resources, like the PVs associated to this specific team, and this should properly target all the resources of the team. I can then set the proper frequency and backup location for that backup/team.

**Anything else you would like to add:**
Right now you cannot combine --include-namespaces with --selector to select both some namespaces and other resources with labels outside of those namespaces since it forms a logical AND, not a logical OR.

---
P.S.: Feel free to suggest existing possibilities that I have not considered for this use case

**Environment:**

- Velero version (use `velero version`): 1.5.2
- Velero features (use `velero client config get features`): NOT SET
- Kubernetes version (use `kubectl version`): 1.18.10
- Cloud provider or hardware configuration: azure AKS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by carlisia** [comment]
Hi @jemag, thank you for this report and request. We will be working on a multi-tenancy design to enable the outcome you are requesting. I will close this issue since we are tracking it here: https://github.com/vmware-tanzu/velero/issues/2587. Please subscribe to that issue to get updates going forward.
