### ISSUE TITLE
velero-plugin-gcp uses the Google API incorrectly leading to failures/bugs in snapshot creation / restores

### ISSUE THREAD

**Issue by arianitu** [vmware-tanzu/velero#3298]
**What steps did you take and what happened:**
velero-plugin-gcp uses the Google API incorrectly leading to issues such as snapshots being created without errors when in fact they have not been created. 

The usage of the Google API inside velero-plugin-gcp does not check for the running operation to complete before returning a success.

See the bug report I made at https://github.com/googleapis/google-api-go-client/issues/832 where the authors show how to correctly use the API by using the `sv.operation` API to watch for operation to finish.

A good idea would be copying what gcp-csi driver does for watching the operation here:

https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/95ffc203e9aabb8d11f3d7d1572d82ea5e5d3b71/pkg/gce-cloud-provider/compute/gce-compute.go#L680

```
func (cloud *CloudProvider) waitForZonalOp(ctx context.Context, opName string, zone string) error {
	// The v1 API can query for v1, alpha, or beta operations.
	svc := cloud.service
	project := cloud.project
	return wait.Poll(3*time.Second, 5*time.Minute, func() (bool, error) {
		pollOp, err := svc.ZoneOperations.Get(project, zone, opName).Context(ctx).Do()
		if err != nil {
			klog.Errorf("WaitForOp(op: %s, zone: %#v) failed to poll the operation", opName, zone)
			return false, err
		}
		done, err := opIsDone(pollOp)
		return done, err
	})
}
```

Here's an example of where it's done incorrectly when making a volume snapshot (at https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/main/velero-plugin-for-gcp/volume_snapshotter.go)

```
	gceSnap := compute.Snapshot{
		Name:        snapshotName,
		Description: getSnapshotTags(tags, disk.Description, b.log),
	}

	if b.snapshotLocation != "" {
		gceSnap.StorageLocations = []string{b.snapshotLocation}
	}

	_, err = b.gce.Disks.CreateSnapshot(b.snapshotProject, volumeAZ, volumeID, &gceSnap).Do()
	if err != nil {
		return "", errors.WithStack(err)
	}
```

This function assumes that CreateSnapshot succeeded, but in fact, it may have failed. In our case, we hit a Quota limit and this function succeeded.

**What did you expect to happen:**
velero-plugin-gcp should use  `svc.ZoneOperations.Get` to see if GCP API operations have in fact completed correctly or else the API could have returned a failure which leads to snapshot failures that look like successes. 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by nrb** [comment]
@arianitu Thanks; right now, Velero doesn't follow up on snapshot API calls due to the time taken to upload to object storage. Our AWS and Azure functionality is the same.

However, since this is a recurring issue, we'll take a look to see how long this might pause operations to wait.

**Comment by eleanor-millman** [comment]
Closing because covered by #3533
