### ISSUE TITLE
Allow Velero to support multiple credentials per storage provider

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#3304]
**Describe the problem/challenge you have**
Currently, Velero can only have 1 credential for a given storage platform, which is limiting if backups should be sent to different locations. For example, if someone is using GCP and wants to send backups to 2 different object storage buckets, this is not currently supported.

**Describe the solution you'd like**
Velero should offer some way to allow all storage provider platforms the ability to utilize multiple credential files. This should work for both volume snapshots and object storage.

**Anything else you would like to add:**
AWS can get around this by specifying profiles in the credential file, but not all file formats offer this support.

Also, restic support should be taken into account as it is currently part of Velero's core, not a plugin.

CSI snapshot support may be tricky here, as the credentials for snapshotting there will reside with the CSI driver itself.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by zubron** [comment]
Fixed in the #3442, #3489, and #3559.

**Comment by zubron** [comment]
Note: updated issue description to remove reference to volume snapshots as this will only affect object storage.
