### ISSUE TITLE
Use smaller footprint image for Velero operator and plugins

### ISSUE THREAD

**Issue by sancyx** [vmware-tanzu/velero#3328]
**Describe the problem/challenge you have**
Latest Velero operator and plugin images based on Ubuntu:focal has some security vulnerability issues.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Provide Dockerfile for an alpine based images. We may eventually contribute the PR for alpine based version. 

**Environment:**

- Velero version (use `velero version`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
@sancyx We're looking at updating Velero's image to use `scratch`, which should alleviate these issues.

We won't be changing to alpine for compliance reasons within VMware, but if `scratch` works, we will pursue that avenue. If not, we'll looking at something like `debian-slim`.

**Comment by sancyx** [comment]
Thanks @nrb, that sound good, scratch based image should be fine.

**Comment by sancyx** [comment]
@nrb BTW do you have an estimated timeline for v1.7.0?

**Comment by dsu-igeek** [comment]
Duplicate of #3500, closing
