### ISSUE TITLE
Upgrade AWS Go sdk to v2

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3338]
https://github.com/aws/aws-sdk-go-v2/releases

**Comment by jglick** [comment]
One thing I noticed when experimenting in https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/90 is that the v2 SDK has a richer system for handling retries, which is rather important here (#1135): `client.DefaultRetryer` replaced with https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/retries-timeouts/.

**Comment by reasonerjt** [comment]
Fixed by
https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/177
https://github.com/vmware-tanzu/velero/pull/6923
