### ISSUE TITLE
can't restore the ebs volume properly

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3342]
@ozbillwang apologies for moving this issue around. We concluded that this one is best kept as an issue vs. discussion. Please subscribe to this issue to get updates.

Link to original: https://github.com/vmware-tanzu/velero/discussions/3247.

**Comment by nrb** [comment]
https://github.com/vmware-tanzu/velero/discussions/3247#discussioncomment-280104

@ozbillwang When you say "By the way, why I can't keep the exist EBS to get restore successfully?," are you referring to the EBS volume?

**Comment by ozbillwang** [comment]
Yes, it is set with **retain** policy

I found, I have to manually delete the original EBS, then I can successfully restore.

**Comment by eleanor-millman** [comment]
Closing because a workaround exists.
