### ISSUE TITLE
Restore PartiallyFailed

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3343]
@kfirfer apologies for moving this issue around. We concluded that this one is best kept as an issue vs. discussion. Please subscribe to this issue to get updates.

Link to the original: https://github.com/vmware-tanzu/velero/discussions/3266.

**Comment by kfirfer** [comment]
@carlisia Thanks !

**Comment by nrb** [comment]
@kfirfer Can you retry with v1.5.3? The restic errors should be resolved with this release.

**Comment by kfirfer** [comment]
@nrb Yes I will retry soon as I can and update here

**Comment by kfirfer** [comment]
@nrb 
Its seems resolved , Thanks !
If its will reproduce, I will reopen
Closed

**Comment by dsu-igeek** [comment]
Thanks, closing for now.
