### ISSUE TITLE
Velero backed up PV Data to Minio and reported an error

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3344]
@misteruly apologies for moving this issue around. We concluded that this one is best kept as an issue vs. discussion. Please subscribe to this issue to get updates.

Link to original: https://github.com/vmware-tanzu/velero/discussions/3244.

**Comment by dsu-igeek** [comment]
@misteruly If you're still having difficulties, we need more information.  Apologies for the move from discussion to issue, this was being asked:

--use-volume-snapshots=true Is that necessary?

No, it is not necessary. Using volume snapshots is only applicable when running on a provider that provides volume snapshotting capabilities, such as on AWS where you are using EBS for your volumes. If you are running on AWS and wish to use volume snapshots, you will also need to configure a VolumeSnapshotLocation. From your install command however, you are using MinIO and restic so volume snapshots will not apply.

From the logs, it looks like it is attempting to take a volume snapshot, did you create a volume snapshot location? It looks like some volumes are being backed up with restic and some are attempting to use snapshots.

Can you retry taking a backup without specifying --snapshot-volumes, e.g velero backup create velero-test-<name> --include-namespaces velero-test.

Also, can you provide the output from the following commands:

velero backup describe velero-test-pvc4 --details
velero restic repo get
velero snapshot-location get
Thanks!

**Comment by eleanor-millman** [comment]
Closing because original reporter didn't reply back. @Gcx44 please create a new issue where we can help you, and please make sure to include all logs that are requested in the new issue instructions.
