### ISSUE TITLE
Restic backup is failing with error "Error creating temp restic credentials file"

### ISSUE THREAD

**Issue by email2smohanty** [vmware-tanzu/velero#3358]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
- Created openshift cluster in aws
- Installed `rabbitmq` sample application which has one persistent storage
- Installed velero on openshift cluster and configured with ibm cloud s3 object storage
- Tried to take backup of `rabbitmq` sample application but backup failed with below error

```
time="2021-01-28T06:44:24Z" level=error msg="Error creating temp restic credentials file" backup=velero/rabitmq-masterbackup controller=pod-volume-backup error="open /tmp/velero-restic-credentials-poco389664145: read-only file system" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/common.go:254" error.function=github.com/vmware-tanzu/velero/pkg/restic.TempCredentialsFile logSource="pkg/controller/pod_volume_backup_controller.go:230" name=rabitmq-masterbackup-28j8r namespace=velero 
```

**What did you expect to happen:**
Backup should be taken properly without any error

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  v1.5.2
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): Server Version: v1.19.0+3b01205, Client Version: v1.18.8
- Kubernetes installer & version:
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment]
Hi @email2smohanty. The temporary file that is created by Velero for restic authentication is only ever written within the velero pod's filesystem however if looks like the filesystem for your velero pod is read-only: `open /tmp/velero-restic-credentials-poco389664145: read-only file system` . Have you applied any security constraints that would make the pod's filesystem read-only?

**Comment by xzlin** [comment]
I have the same issue. My openshift version is 4.5. Velero pod is created by velero install. I applied requirements from restic document https://velero.io/docs/v1.5/restic/
$ oc adm policy add-scc-to-user privileged -z velero -n velero
oc patch ds/restic \
  --namespace velero \
  --type json \
  -p '[{"op":"add","path":"/spec/template/spec/containers/0/securityContext","value": { "privileged": true}}]'
I didn't do anything else.
