### ISSUE TITLE
Set --log-level when installing velero via velero install client

### ISSUE THREAD

**Issue by brito-rafa** [vmware-tanzu/velero#3395]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]

I want to enable --log-level debug on velero server by default during installation time. I do not want to patch/edit velero deployment just to enable debug and slow down my testing process.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
On the velero client, add a parameter "--log-level {debug, info, warning, error}". I think helm installation allows that setting logLevel on values.yaml.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.5.3
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by codegold79** [comment]
@brito-rafa, do you think the [new design for Velero CLI](https://github.com/vmware-tanzu/velero/blob/master/design/cli-install-changes.md) would address this issue? 

In particular, you can see the [commands section](https://github.com/vmware-tanzu/velero/blob/master/design/cli-install-changes.md#commands) with the proposed command

```
velero config --log-level debug
```

**Comment by zubron** [comment]
Thanks for adding those links, @codegold79!

As described in the linked design doc, we are intending to move away from `velero install` to instead have different commands to configure different aspects of the installation. The change to add `velero config server` and adding the new flags such as `--log-level` are being tracked in #2423.

Given that this feature has an open issue, I am going to close this one. If you have any further input or ideas though, we'd appreciate your comments in the other issue :) Thanks!
