### ISSUE TITLE
Add E2E backup/restore test for multiple object store credentials

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#3432]
**Describe the problem/challenge you have**

Per-Backup Storage Location credentials are being introduced in Velero 1.6.  These should be tested

**Describe the solution you'd like**
Have a test that sets up two backup storage locations with different credentials on AWS, Azure and vSphere.
Ensure that backup/restore can occur successfully with both BSLs
Check with Restic and volume snapshots

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by zubron** [comment]
@dsu-igeek Do you think that this can be closed based on the test added in #3559 or would you like to see additional test cases?

**Comment by dsu-igeek** [comment]
I think we should close this and we'll add new tasks as necessary.  Thanks!
