### ISSUE TITLE
Velero with s3 as BackupLocation, running behind proxy: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by aayushrangwala** [vmware-tanzu/velero#3433]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I am running velero from its official [helm chart](https://github.com/vmware-tanzu/helm-charts/tree/main/charts/velero), behind a local (squid) proxy on mac using a self-signed certificate. As per the [docs](https://velero.io/docs/v1.5/self-signed-certificates/#docs) for passing cacert to velero, I am adding it to the `BackupStorageLocation`, but still continuously getting the below error and marked as `Unavailable`. The backup location is s3 and temporary credentials are fine and accessible to the bucket.

`proxyconnect tcp: x509: certificate signed by unknown authority `

```
time="2021-02-08T09:03:20Z" level=error msg="Error listing backups in backup store" backupLocation=sample-bsl controller=backup-sync error="rpc error: code = Unknown desc = RequestError: send request failed\ncaused by: Get https://<bucket-name>s3.us-west-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=<some-prefix>%2Fbackups%2F: proxyconnect tcp: x509: certificate signed by unknown authority" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:331" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:174"
```

Also, the proxy is working fine as I have tried with other urls with and without certificate.
I have tried to run the setup manually also, with velero client and passing the certs file path at the install time but still the same error.
In the velero logs, at the moment of calling the s3 bucket URL, it is throwing error with the certificate signed by unknown authority just like above, and for that call, I am NOT getting any error logs in the proxy.

Although, I am getting the Bad Certificate error, intermittently, like below. 

```
squid-alpine-ssl_1  | 2021/02/09 11:40:07| Error negotiating SSL connection on FD 40: error:14037412:SSL routines:ACCEPT_SR_KEY_EXCH:sslv3 alert bad certificate (1/0)
```

I am sure that this log in the proxy is NOT for the time when velero tried to list the backups and fails with `unknown authority` error as above. I can see these logs, intermittently.

**What did you expect to happen:**

The backup location should be marked as `Available` and processed successfully by the velero pod.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

`kubectl logs deploy/velero -n velero`

```
time="2021-02-09T11:46:07Z" level=error msg="Error getting backup store for this location" backupLocation=dp-unstable-dev controller=backup-sync error="rpc error: code = Unknown desc = unable to determine bucket's region" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/helpers.go:52" error.function=main.GetBucketRegion logSource="pkg/controller/backup_sync_controller.go:167"
time="2021-02-09T11:46:37Z" level=error msg="Error getting backup store for this location" backupLocation=dp-unstable-dev controller=backup-sync error="rpc error: code = Unknown desc = unable to determine bucket's region" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/helpers.go:52" error.function=main.GetBucketRegion logSource="pkg/controller/backup_sync_controller.go:167"
time="2021-02-09T11:47:11Z" level=error msg="Error listing backups in backup store" backupLocation=dp-unstable-dev controller=backup-sync error="rpc error: code = Unknown desc = RequestError: send request failed\ncaused by: Get https://<some-bucket>s3.us-west-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=<some-prefix>%2Fbackups%2F: x509: certificate signed by unknown authority" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:331" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:174"
```

Note: The above error of `unable to determine bucket's region`  is gone once I added the region in BSL manually

**Environment:**

- Velero version: `v1.5.3 both client and server`
- Velero features: `<NOT SET> `
- Kubernetes version: `kubectl version: v1.20 and server: v1.19`
- Kubernetes installer & version: Kind: `kind v0.9.0 go1.15.2 darwin/amd64`
- Cloud provider or hardware configuration: `Mac/OSX`

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment]
Hi @aayushrangwala - I'm not sure that providing the CA cert to velero makes sense for your use case. Typically, the CA cert is given to velero to make connections with S3 compatible storage providers that are secured with a self signed certificate. I don't think it should be required for AWS S3. In your case, the CA cert that you are providing is for your local proxy and so won't be valid for S3 requests. Have you tried this setup without providing the CA cert?

**Comment by dsu-igeek** [comment]
We need more log files to determine what is going on.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`


**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]


**Environment:**

- Velero version (use `velero version`):
- Velero features (use `velero client config get features`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

It will help to see the configuration for your S3 provider.  We need to see what your Squid configuration is.

The Velero AWS plug-in uses the AWS SDK.  A first step to troubleshooting this would be to get the aws CLI to talk with your S3 bucket via the proxy.  Once that is working, we can then work on getting Velero and the AWS plugin working.

**Comment by aayushrangwala** [comment]
> Hi @aayushrangwala - I'm not sure that providing the CA cert to velero makes sense for your use case. Typically, the CA cert is given to velero to make connections with S3 compatible storage providers that are secured with a self signed certificate. I don't think it should be required for AWS S3. In your case, the CA cert that you are providing is for your local proxy and so won't be valid for S3 requests. Have you tried this setup without providing the CA cert?

@zubron Our requirement is that all the applications in a cluster will run behind a proxy and for any external URLs needs to go through proxy. This proxy is configured with a self-signed certificate. So all the request going outside via proxy should be passed with the proxy certificate. Since in the case of velero. it contacts only s3 APIs for backup/snapshot related operations, I found only one way to pass the certs in BSL.

I am not sure how we can achieve that but if this is not the right way, can you please suggest how can I do it.

**Comment by aayushrangwala** [comment]
> We need more log files to determine what is going on.
> 
> **The output of the following commands will help us better understand what's going on**:
> (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
> 
>     * `kubectl logs deployment/velero -n velero`
> 
>     * `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
> 
>     * `velero backup logs <backupname>`
> 
>     * `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
> 
>     * `velero restore logs <restorename>`
> 
> 
> **Anything else you would like to add:**
> [Miscellaneous information that will assist in solving the issue.]
> 
> **Environment:**
> 
>     * Velero version (use `velero version`):
> 
>     * Velero features (use `velero client config get features`):
> 
>     * Kubernetes version (use `kubectl version`):
> 
>     * Kubernetes installer & version:
> 
>     * Cloud provider or hardware configuration:
> 
>     * OS (e.g. from `/etc/os-release`):
> 
> 
> It will help to see the configuration for your S3 provider. We need to see what your Squid configuration is.
> 
> The Velero AWS plug-in uses the AWS SDK. A first step to troubleshooting this would be to get the aws CLI to talk with your S3 bucket via the proxy. Once that is working, we can then work on getting Velero and the AWS plugin working.


@dsu-igeek  S3 provider is AWS and it is configured without any proxy.
[Here](https://gist.github.com/aayushrangwala/59df06bd760b13559dc011ea15b5ae8e) are the logs for velero pods. Since the BSl is not in Available state, I haven't started the backups and stuck.

I have tried with curl to the bucket url from velero ogs which is being used by the velero itself and its working. But when I try to do the `aws s3api list-buckets`  via proxy, even with setting the `HTTPS_PROXY` and `AWS_CA_BUNDLE` env var, it fails with `unknown ca`

**Comment by aayushrangwala** [comment]
@dsu-igeek  @zubron  Debugged some more on this today and found that we needed to pass the [S3 Root CA](https://www.digicert.com/kb/digicert-root-certificates.htm) and [aws ROOT CA1](https://www.amazontrust.com/repository/AmazonRootCA1.pem) along with the proxy CA as the trusted certs in the BSL `caCert` field. It started working But with a catch.

According to the logs first velero plugin tries to determine the region of the bucket and after that it actually tries to validate the BSL using the creds along with cacert. The problem is, while determining the bucket region, plugin doesnot use the cacerts from BSL or infact no configuration is considered for that aws session and failing. Opening a new issue and closing this one.

**Comment by aayushrangwala** [comment]
ref: #3449

**Comment by akshayv3rma** [comment]
@aayushrangwala Can you please let me know how would you pass the AWS root and  S3 CA Cert. Facing the same issue you mentioned above. It will be a great help
