### ISSUE TITLE
Connection error AzureChinaCloud for velero-plugin-for-microsoft-azure

### ISSUE THREAD

**Issue by boehlefeld** [vmware-tanzu/velero#3440]
**What steps did you take and what happened:**
We already using Velero in AzurePublicCloud for k8s resources successfully, but in AzureChinaCloud we fail to setup. 
The configuration is almost default, but see the detailed configuration attached. 

Scenario:
- What: Redis among other volumes
- Where: The resources are located in a different subscription id from where the storage account is located 
- Permission: service principal auth

Velero pod constantly fails to connect to AzureChinaCloud:

- Subscriptions ids, tenant id, client id triple checked.
- A blob upload test using the service principal within a pod located in AzureChinaCloud was successful

**What did you expect to happen:**
Backups from AzureChinaCloud located resources to be transferred to AzureChinaCloud located Azure Storage Account. 

**The output of the following commands will help us better understand what's going on**:

- `kubectl logs deployment/velero -n velero` [logs](https://pastebin.com/sVcuxaYa)
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml` [logs](https://pastebin.com/CncEw0zF)
- `velero backup logs <backupname>` no logs

**Anything else you would like to add:**
- [Helm command used](https://pastebin.com/qn4tNhkA)
- [helm get values output](https://pastebin.com/5SHy2iMX) **updated**
- Credential file used:
```
AZURE_SUBSCRIPTION_ID=AAA***
AZURE_TENANT_ID=BBB***
AZURE_CLIENT_ID=CCC***
AZURE_CLIENT_SECRET=***
AZURE_RESOURCE_GROUP=RG1***
AZURE_CLOUD_NAME=AzureChinaCloud
```

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.5.3
	Git commit: -
Server:
	Version: v1.5.3
```
- Velero features (use `velero client config get features`): 
`features: <NOT SET> `
- Kubernetes version (use `kubectl version`):
> Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"} 
> Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T16:05:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
> Azure Portal
- Cloud provider or hardware configuration:
> AzureChinaCloud
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment]
Hi @boehlefeld - Sorry you're having issue with this.

I know you've said that you've checked all the IDs, but I have noticed this error in the logs: 
```
time="2021-02-09T16:56:57Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.chinacloudapi.cn/subscriptions/EEE***/resourceGroups/RG2***/providers/Microsoft.Storage/storageAccounts/***/listKeys?%24expand=kerb&api-version=2019-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"AADSTS90002: Tenant 'BBB***' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. ***\"error_codes\":[90002]\"error_uri\":\"https://login.microsoftonline.com/error?code=90002\"}" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:213" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:168"
```

In particular, I notice that the URL that is using `EEE***` as the subscription which doesn't match any of the substituted subscription IDs in the helm values you've used. Is there any way for you to validate, perhaps in the Azure UI, that the given Tenant ID exists and has a valid subscription and that that subscription ID is being used?

**Comment by boehlefeld** [comment]
Hi @zubron,

thank you! I didn't triple check the obfuscated version ;-).
The helm get values output is now correct; I've updated the link.

>Is there any way for you to validate, perhaps in the Azure UI, that the given Tenant ID exists and has a valid subscription and that that subscription ID is being used?


azure.portal.cn
- open subscription AAA***
  - Overview
    - 'Parent management group'
      - BBB***
- open subscription EEE***
  - Overview
    - 'Parent management group'
      - BBB***


I fired up an interactive azure-cli shell in the cluster and logged in using the service principal.
Seems legit to me too:
```
[
  {
    "cloudName": "AzureChinaCloud",
    "homeTenantId": "BBB***",
    "id": "AAA***",
    "isDefault": true,
    "managedByTenants": [],
    "name": "***",
    "state": "Enabled",
    "tenantId": "AAA***",
    "user": {
      "name": "CCC***",
      "type": "servicePrincipal"
    }
  },
  {
    "cloudName": "AzureChinaCloud",
    "homeTenantId": "BBB***",
    "id": "EEE***",
    "isDefault": false,
    "managedByTenants": [],
    "name": "***",
    "state": "Enabled",
    "tenantId": "AAA***",
    "user": {
      "name": "CCC***",
      "type": "servicePrincipal"
    }
  }
]
```

Thank you helping me investigating

**Comment by haannnees** [comment]
Any updates on that issue? :)

**Comment by boehlefeld** [comment]
Hi @zubron,

any information missing - 
How can I help investigating?

**Comment by mblaschke** [comment]
The problem is that the plugin is using env var `AZURE_CLOUD_NAME` instead of the official `AZURE_ENVIRONMENT`.
That means that the azure-sdk is fine but the authorizer doesn't know that it should connect to `AzureChinaCloud` so it tries to connect to `AzurePublicCloud`

Workaround: add `AZURE_ENVIRONMENT`  in k8s `Deployment`:

```
    spec:
      containers:
      - args:
        - server
        - --backup-sync-period=1m
        command:
        - /velero
        env:
        - name: AZURE_ENVIRONMENT
          value: AzureChinaCloud
```

**Comment by hmi12** [comment]
so this environment variable must be added after the installation is finished? @mblaschke
