### ISSUE TITLE
Velero is performing an already-expired backup

### ISSUE THREAD

**Issue by sgielen** [vmware-tanzu/velero#3457]
**What steps did you take and what happened:**
I have some old backups in my system that were never performed and have already expired. However, Velero is still performing those backups, and then resets expiry.

The clusterstate schedule creates multiple backups per day, excluding volumes, and with an expiry of 7 days. For quite a while, it created Backup instances but without actually performing the backups, so I have a lot of Backups in the system with status New that have already expired (creation date + TTL < now).

For example, this Backup expired 10 days ago:

```
$ velero get backups | grep -e 202101281237 -e NAME
NAME                           STATUS       ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
clusterstate-20210128123759    New          0        0          <nil>                           10d ago                      <none>
```
```
$  velero get backup clusterstate-20210128123759 -o yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  creationTimestamp: "2021-01-28T12:37:59Z"
  generation: 1
  labels:
    velero.io/schedule-name: clusterstate
  managedFields:
  - apiVersion: velero.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:velero.io/schedule-name: {}
      f:spec:
        .: {}
        f:hooks: {}
        f:includedNamespaces: {}
        f:snapshotVolumes: {}
        f:ttl: {}
      f:status: {}
    manager: velero-server
    operation: Update
    time: "2021-01-28T12:37:59Z"
  name: clusterstate-20210128123759
  namespace: velero
  resourceVersion: "137952128"
  selfLink: /apis/velero.io/v1/namespaces/velero/backups/clusterstate-20210128123759
  uid: f3856ebc-ea7f-4416-bfc4-9d8526b00593
spec:
  hooks: {}
  includedNamespaces:
  - '*'
  snapshotVolumes: false
  ttl: 168h0m0s
status: {}
```

I just restarted the Velero server and it started performing all of these backups. It performed, for example, a backup of an even older `clusterstate-20201208003745` backup. Since it was created 2020-12-08, it should have already expired on 2020-12-15, i.e. approximately 2 months ago.

```
time="2021-02-14T14:35:54Z" level=info msg="Setting up backup log" backup=velero/clusterstate-20201208003745 controller=backup logSource="pkg/controller/backup_controller.go:512"
...
time="2021-02-14T14:35:54Z" level=info msg="Getting backup item actions" backup=velero/clusterstate-20201208003745 logSource="pkg/controller/backup_controller.go:545"
...
time="2021-02-14T14:35:55Z" level=info msg="Writing backup version file" backup=velero/clusterstate-20201208003745 logSource="pkg/backup/backup.go:212"
...
time="2021-02-14T14:36:43Z" level=info msg="Backed up a total of 1953 items" backup=velero/clusterstate-20201208003745 logSource="pkg/backup/backup.go:419" progress=
time="2021-02-14T14:36:43Z" level=info msg="Setting up backup store to persist the backup" backup=velero/clusterstate-20201208003745 logSource="pkg/controller/backup_controller.go:632"
time="2021-02-14T14:36:44Z" level=info msg="Backup completed" controller=backup logSource="pkg/controller/backup_controller.go:642"
```

That Backup is now Completed, but now with an explicit Expiration set in the future again:

```
$ velero get backups | grep -e 20201208003745 -e NAME
NAME                           STATUS       ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
clusterstate-20201208003745    Completed    0        0          2021-02-14 15:35:53 +0100 CET   6d        default            <none>
$ velero get backup clusterstate-20201208003745 -o yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/source-cluster-k8s-gitversion: v1.18.9+k3s1
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "18"
  creationTimestamp: "2020-12-08T00:37:45Z"
  generation: 31
  labels:
    velero.io/schedule-name: clusterstate
    velero.io/storage-location: default
  managedFields:
  - apiVersion: velero.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:velero.io/source-cluster-k8s-gitversion: {}
          f:velero.io/source-cluster-k8s-major-version: {}
          f:velero.io/source-cluster-k8s-minor-version: {}
        f:labels:
          .: {}
          f:velero.io/schedule-name: {}
          f:velero.io/storage-location: {}
      f:spec:
        .: {}
        f:defaultVolumesToRestic: {}
        f:hooks: {}
        f:includedNamespaces: {}
        f:snapshotVolumes: {}
        f:storageLocation: {}
        f:ttl: {}
      f:status:
        .: {}
        f:completionTimestamp: {}
        f:expiration: {}
        f:formatVersion: {}
        f:phase: {}
        f:progress:
          .: {}
          f:itemsBackedUp: {}
          f:totalItems: {}
        f:startTimestamp: {}
        f:version: {}
    manager: velero-server
    operation: Update
    time: "2021-02-14T14:36:44Z"
  name: clusterstate-20201208003745
  namespace: velero
  resourceVersion: "143069960"
  selfLink: /apis/velero.io/v1/namespaces/velero/backups/clusterstate-20201208003745
  uid: 6427f67c-0e77-4538-8e54-c8cd9df31e54
spec:
  defaultVolumesToRestic: false
  hooks: {}
  includedNamespaces:
  - '*'
  snapshotVolumes: false
  storageLocation: default
  ttl: 168h0m0s
status:
  completionTimestamp: "2021-02-14T14:36:43Z"
  expiration: "2021-02-21T14:35:53Z"
  formatVersion: 1.1.0
  phase: Completed
  progress:
    itemsBackedUp: 1953
    totalItems: 1953
  startTimestamp: "2021-02-14T14:35:53Z"
  version: 1
```

**What did you expect to happen:**
When a backup is created, it has a TTL, but not really an expiry date. The behaviour of `velero get backups` is, I think, to compute the expiry date as "creation date + TTL", and I think this makes sense.

However, then, when the backup is actually performed, the expiry is set to "now + TTL" instead of "creation date + TTL". I think that's fine as well.

The surprising behaviour, to me, is that it even starts to perform the backup if now > "creation date + TTL". This now causes all these backups to exist with an expiry of 7 days in the future, even though they were all performed just now. 

**Anything else you would like to add:**
The reason that Velero gets stuck performing these backups sometimes, I think has to do with the integration with the OpenEBS plugin, which sometimes freezes while performing or deleting backups for me (that's issue #2738, for which #2800 is created as an appropriate solution for me).

**Environment:**

- Velero version (use `velero version`): Was 1.5.1, now 1.5.3
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): 1.18.9+k3s1
- Kubernetes installer & version: k3os
- Cloud provider or hardware configuration: Bare-metal
- OS (e.g. from `/etc/os-release`): k3os

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sgielen** [comment]
I think this could be reproduced by creating a Backup object with creation date last week, and setting a TTL less than a week. `velero get backups` would show it as Expired (e.g. "1d ago"), but the Velero daemon would perform the backup nonetheless. Is this expected behaviour?

**Comment by carlisia** [comment]
Iiiiinteresting. I can see how we might have been missing testing this use case. Will look into it.

But, I am very curious, what does this mean: `For quite a while, it created Backup instances but without actually performing the backups`?

Did you do this on purpose? Meaning, did you mean to create the instances but hold off on performing the backup operation? If so, how? And why?

**Comment by carlisia** [comment]
Things to check:

- Delete controller: is it looking at phase and skipping over phases that are `New`
- Regular processing of backups see phase `New` and disregards TTL
- Restore only mode doesn't enable the delete controller
- When backups get created in a cluster that doesn't have controllers to process them
- When Velero is (re)installed not in `restore-only`, all controllers are enabled

**Comment by carlisia** [comment]
> Did you do this on purpose? Meaning, did you mean to create the instances but hold off on performing the backup operation? If so, how? And why?

Nvm this question, it's obvious now in your report that they were created via the scheduling.

**Comment by sgielen** [comment]
> > Did you do this on purpose? Meaning, did you mean to create the instances but hold off on performing the backup operation? If so, how? And why?
> 
> Nvm this question, it's obvious now in your report that they were created via the scheduling.

Yes, the Backup instances were created from schedules, and they did not start because one backup was InProgress for a very long time due to [an unrelated issue](https://github.com/vmware-tanzu/velero/issues/2738). So, Velero thought it was performing a backup for over a month, and when I restarted it, it had a month of already-expired backups to get to. Instead of skipping all the expired ones, as I thought it would, it performed all of them in sequence.
