### ISSUE TITLE
Upgrade Restic to v0.12.0

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#3490]
**Describe the problem/challenge you have**
Latest Rest

**Describe the solution you'd like**
Restic has release v0.12.0 as of Feb 2021.  We should upgrade to this.  https://restic.net/blog/2021-02-14/restic-0.12.0-released/

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by dsu-igeek** [comment]
Will resolve issue https://github.com/vmware-tanzu/velero/issues/2198

**Comment by christian-vent** [comment]
@carlisia @dsu-igeek we're looking for this improvement as well. Can you tell me, when this would be available in a release? I saw the @dsu-igeek added the milestone 1.6.0, but when I check https://github.com/vmware-tanzu/velero/milestone/26 I can't find this item.

**Comment by nrb** [comment]
@christian-vent I just added it to the v1.6.0 milestone.

**Comment by christian-vent** [comment]
Awesome, thanks @nrb
