### ISSUE TITLE
[Epic] Install Velero using Carvel YTT

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#3493]
**Describe the problem/challenge you have**
We would like to be able to install Velero via Carvel

**Describe the solution you'd like**
Carvel template need to be generated that can install Velero in:

- AWS
- Azure
- GCP
- vSphere
- Generic cluster

https://github.com/vmware-tanzu/carvel-ytt

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
Closing as it doesn't require code change in velero OSS.
