### ISSUE TITLE
Using velero and minio, when using the example with pv, it gives an error

### ISSUE THREAD

**Issue by dylanyht** [vmware-tanzu/velero#3509]
**What steps did you take and what happened:**
velero v1.5.3

velero install  --provider aws --plugins velero/velero-plugin-for-aws:v1.1.0 --bucket  velero \
--secret-file ./credentials-velero \
--use-restic \
--default-volumes-to-restic \
--backup-location-config \
region=minio,s3ForcePathStyle="true",s3Url=http://172.16.77.64:9000

I used with-pv.yaml for backup recovery.
After I executed velero backup create nginx-backup --include-namespaces nginx-example, I checked the logs and found that an error was reported

The logs are as follows

# velero backup logs nginx-backup |grep error
time="2021-03-01T01:42:06Z" level=error msg="Error executing hook" backup=velero/nginx-backup error="command terminated with exit code 1" hookPhase=pre hookSource=annotation hookType=exec logSource="internal/hook/item_hook_handler.go:206" name=nginx-deployment-5ccc99bffb-q54nr namespace=nginx-example resource=pods
time="2021-03-01T01:42:06Z" level=error msg="Error backing up item" backup=velero/nginx-backup error="command terminated with exit code 1" logSource="pkg/backup/backup.go:437" name=nginx-deployment-5ccc99bffb-q54nr
time="2021-03-01T01:42:06Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/nginx-backup error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:76" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:449" name=pvc-0faa5e10-0ac3-43fd-acf6-db44a8c8a995 namespace= persistentVolume=pvc-0faa5e10-0ac3-43fd-acf6-db44a8c8a995 resource=persistentvolumes volumeSnapshotLocation=default

cnetos7
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by carlisia** [comment]
Please tell me more about your environment. Is this trying to create an AWS snapshot? Did you intent on using restic for that?
