### ISSUE TITLE
PartiallyFailed Backup because restic issue

### ISSUE THREAD

**Issue by waldo2188** [vmware-tanzu/velero#3513]
**What steps did you take and what happened:**
I have an issue on a schedule backup set on Velero.  
This schedule must backup the volume of a specific pod.  
This volume contains approximately 33 7761 files for a weight of 2GB.  

Only 223728 files are backed up.

Restic fail with the error "signal: killed".

I've check if the restic pod is OOMKiled, but it's not the case.

**What did you expect to happen:**
The full backup of the volume.

**The output of the following commands will help us better understand what's going on**:
https://gist.github.com/waldo2188/b8840be7b8829fc749881ccd1dba3ae4

**Anything else you would like to add:**
It is possible that during backup some files are still being created on the storage media. I don't know if this is of any importance.

I've other schedule backup on this cluster who save 15Gb of data without any problems.

**Environment:**

- Velero version (use `velero version`):  v1.5.3
- Velero features (use `velero client config get features`): NOT SET
- Kubernetes version (use `kubectl version`): v1.20.1
- Kubernetes installer & version: On premise 
- Hardware configuration: 4 CPU 16GbRAM
- OS (e.g. from `/etc/os-release`):Debian GNU/Linux 10 (buster), kernel : Linux 4.19.0-14-amd64

**Comment by dsu-igeek** [comment]
Does it always fail or did only fail once?

**Comment by waldo2188** [comment]
Here are the latest executions of the backup process:
```
$: velero backup get
NAME                                STATUS            ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
some_app-only-20210310050015         Failed            0        0          2021-03-10 06:00:15 +0100 CET   29d       default            app=some_app
some_app-only-20210309050015         PartiallyFailed   2        0          2021-03-09 06:00:15 +0100 CET   28d       default            app=some_app
some_app-only-20210308050015         Completed         0        0          2021-03-08 06:00:15 +0100 CET   27d       default            app=some_app
some_app-only-20210307050010         PartiallyFailed   2        0          2021-03-07 06:00:10 +0100 CET   26d       default            app=some_app
some_app-only-20210306050010         PartiallyFailed   2        0          2021-03-06 06:00:10 +0100 CET   25d       default            app=some_app
some_app-only-20210305050010         Completed         0        0          2021-03-05 06:00:10 +0100 CET   24d       default            app=some_app
some_app-only-20210304050010         PartiallyFailed   2        0          2021-03-04 06:00:10 +0100 CET   23d       default            app=some_app
some_app-only-20210303050009         PartiallyFailed   2        0          2021-03-03 06:00:09 +0100 CET   22d       default            app=some_app
some_app-only-20210302050009         PartiallyFailed   2        0          2021-03-02 06:00:09 +0100 CET   21d       default            app=some_app
some_app-only-20210301092715         PartiallyFailed   2        0          2021-03-01 11:54:14 +0100 CET   21d       default            app=some_app

```

**Comment by dsu-igeek** [comment]
Hmmmm...I will try making some large backups and see if I can reproduce this.  For the other cluster that is successfully backing up 15GB, do you know how many files are involved?

Looks like your target is AWS S3, correct?

**Comment by waldo2188** [comment]
The target was a S3 API of a Swift infrastructure manage by OVH.
But, hum... The datacenter where data was stored burned to the ground...
So, I can't give you more data about this issue. Sorry.

**Comment by wzrdtales** [comment]
not stale, big issue...

**Comment by wzrdtales** [comment]
For some reason velero decides to kill the prune process after just 5 seconds. If I run the command by hand eveything is fine. Very obviously a velero bug.
