### ISSUE TITLE
Restore issue with MutatingWebhookConfiguration v1beta1 API version

### ISSUE THREAD

**Issue by daguilarv** [vmware-tanzu/velero#3516]
**What steps did you take and what happened:**
Restoring v1beta1 MutatingWebhookConfiguration into a v1.19.7 cluster is failing with following error description:
Errors:
  Velero:     <none>
  Cluster:  error restoring mutatingwebhookconfigurations.admissionregistration.k8s.io/add-init-containers-to-spark-pods: MutatingWebhookConfiguration.admissionregistration.k8s.io "add-init-containers-to-spark-pods" is invalid: webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun"
.
It seems the same bug in described https://github.com/vmware-tanzu/velero/issues/2159 for CRDs but for MutatingWebhooksConfiguration. Objects created with v1beta1 API should be restored with the same apiserversion instead of using v1. 

**What did you expect to happen:**

Objects must be properly restored.

**The output of the following commands will help us better understand what's going on**:
velero restore describe disaster-20210303090004-20210303101039                                                                                                            
Name:         disaster-20210303090004-20210303101039
Namespace:    baikal-infra
Labels:       <none>
Annotations:  <none>

Phase:  PartiallyFailed (run 'velero restore logs disaster-20210303090004-20210303101039' for more information)

Warnings:
  -Not relevant-
Errors:
  Velero:     <none>
  Cluster:  error restoring mutatingwebhookconfigurations.admissionregistration.k8s.io/add-init-containers-to-spark-pods: MutatingWebhookConfiguration.admissionregistration.k8s.io "add-init-containers-to-spark-pods" is invalid: webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun"
            error restoring mutatingwebhookconfigurations.admissionregistration.k8s.io/add-tmp-volume-to-spark-pods: MutatingWebhookConfiguration.admissionregistration.k8s.io "add-tmp-volume-to-spark-pods" is invalid: webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun"
            error restoring mutatingwebhookconfigurations.admissionregistration.k8s.io/add-toleration-to-spark-pods: MutatingWebhookConfiguration.admissionregistration.k8s.io "add-toleration-to-spark-pods" is invalid: webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun"
            error restoring mutatingwebhookconfigurations.admissionregistration.k8s.io/aks-webhook-admission-controller: MutatingWebhookConfiguration.admissionregistration.k8s.io "aks-webhook-admission-controller" is invalid: webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun"
            error restoring mutatingwebhookconfigurations.admissionregistration.k8s.io/coredns-deployment-metrics-and-readiness: MutatingWebhookConfiguration.admissionregistration.k8s.io "coredns-deployment-metrics-and-readiness" is invalid: webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun"
            error restoring mutatingwebhookconfigurations.admissionregistration.k8s.io/override-node-selector-to-spark-drivers: MutatingWebhookConfiguration.admissionregistration.k8s.io "override-node-selector-to-spark-drivers" is invalid: webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun"
            error restoring validatingwebhookconfigurations.admissionregistration.k8s.io/elastic-webhook.k8s.elastic.co: ValidatingWebhookConfiguration.admissionregistration.k8s.io "elastic-webhook.k8s.elastic.co" is invalid: [webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun", webhooks[1].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun"]

Backup:  disaster-20210303090004

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

**Environment:**

- Velero version (use `velero version`): 1.5.3
- Velero features (use `velero client config get features`): None
- Kubernetes version (use `kubectl version`): 1.19.7
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Azure AKS deployment
- OS (e.g. from `/etc/os-release`): Ubuntu

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by johannesfrey** [comment]
Hi,

we also ran into this issue when performing a restore of MutatingWebhookConfigurations of [Service Catalog](https://github.com/kubernetes-sigs/service-catalog/blob/master/charts/catalog/templates/webhook-register.yaml) (they still use `admissionregistration.k8s.io/v1beta1`) into a v1.20.5 cluster.

IIRC, the case of for v1beta1 CRDs has been mitigated via the [crd-remap-version plugin](https://github.com/vmware-tanzu/velero/blob/main/pkg/backup/remap_crd_version_action.go#L90).

Would it be feasible to implement such logic in a more "general" way, so that the restore actually restores the version that has been initially deployed to the cluster? Not 100% sure, but those are potential resources that have been deprecated for a while but might still be deployed into clusters in the deprecated version (list generated via [`pluto list-versions`](https://github.com/FairwindsOps/pluto)):

```
KIND                             NAME                                   DEPRECATED IN   REMOVED IN   REPLACEMENT                       COMPONENT
Ingress                          extensions/v1beta1                     v1.14.0         v1.22.0      networking.k8s.io/v1              k8s           
Ingress                          networking.k8s.io/v1beta1              v1.19.0         v1.22.0      networking.k8s.io/v1              k8s           
CustomResourceDefinition         apiextensions.k8s.io/v1beta1           v1.16.0         v1.22.0      apiextensions.k8s.io/v1           k8s           
MutatingWebhookConfiguration     admissionregistration.k8s.io/v1beta1   v1.16.0         v1.22.0      admissionregistration.k8s.io/v1   k8s           
ValidatingWebhookConfiguration   admissionregistration.k8s.io/v1beta1   v1.16.0         v1.22.0      admissionregistration.k8s.io/v1   k8s           
ClusterRoleBinding               rbac.authorization.k8s.io/v1alpha1     v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
ClusterRole                      rbac.authorization.k8s.io/v1alpha1     v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
ClusterRoleBindingList           rbac.authorization.k8s.io/v1alpha1     v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
ClusterRoleList                  rbac.authorization.k8s.io/v1alpha1     v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
Role                             rbac.authorization.k8s.io/v1alpha1     v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
RoleBinding                      rbac.authorization.k8s.io/v1alpha1     v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
RoleList                         rbac.authorization.k8s.io/v1alpha1     v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
RoleBindingList                  rbac.authorization.k8s.io/v1alpha1     v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
ClusterRoleBinding               rbac.authorization.k8s.io/v1beta1      v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
ClusterRole                      rbac.authorization.k8s.io/v1beta1      v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
ClusterRoleBindingList           rbac.authorization.k8s.io/v1beta1      v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
ClusterRoleList                  rbac.authorization.k8s.io/v1beta1      v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
Role                             rbac.authorization.k8s.io/v1beta1      v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
RoleBinding                      rbac.authorization.k8s.io/v1beta1      v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
RoleList                         rbac.authorization.k8s.io/v1beta1      v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
RoleBindingList                  rbac.authorization.k8s.io/v1beta1      v1.17.0         v1.22.0      rbac.authorization.k8s.io/v1      k8s           
```

**Comment by johannesfrey** [comment]
An explicit way to solve this for e.g. MutatingWebhookConfiguration and ValidatingWebhookConfiguration would be to start the Velero server via `--features=EnableAPIGroupVersions` (which ensures that v1beta1 is also backed up) and to define a restore priority ConfigMap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: enableapigroupversions
  namespace: velero
data:
  restoreResourcesVersionPriority: |
    mutatingwebhookconfigurations.admissionregistration.k8s.io=v1beta1,v1
    validatingwebhookconfigurations.admissionregistration.k8s.io=v1beta1,v1
```

**Comment by janeklb** [comment]
> Would it be feasible to implement such logic in a more "general" way, so that the restore actually restores the version that has been initially deployed to the cluster?

This seems like the most desirable behaviour to have when doing 1-1 restores (eg. disaster recovery) +1

**Comment by reasonerjt** [comment]
As for this particular issue, I tried to create a `v1beta1` mutatingwebhookconfigurations

```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: my-test
webhooks:
- name: www.my-test.org
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    url: "https://my-test.org"
  timeoutSeconds: 5
```

After that, if I read the resource via kubectl, it returns the resource in `v1` schema with `sideEffects == Unknown`
```
 k get mutatingwebhookconfiguration my-test -o yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
......
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: Namespaced
  sideEffects: Unknown   <----------!!!!
  timeoutSeconds: 5
  ```
  
  So it seems a bug in kubernetes that the code to handle the conversion of mutatingwebhookconfiguration should not set the invalid value in `sideEffects` 
  
  To fix this issue, velero will add a restoreitemaction  plugin to fix the invalid value.
