### ISSUE TITLE
Velero installation fails for AKS can't get pass "checking namespace"

### ISSUE THREAD

**Issue by luisbtejada** [vmware-tanzu/velero#3526]
Installing velero in Azure kubernetes service with private cluster enabled.

This is the installation command used:
velero install \
--provider azure \
--image velero/velero:v1.2.0 \
--plugins velero/velero-plugin-for-microsoft-azure:v1.0.1 \
--bucket velero \
--secret-file ./credentials-velero \
--backup-location-config resourceGroup="css-preprod-1-westus-1",storageAccount="csspreprod1westus1st1",subscriptionId="52c48814-88e2-4d41-ae63-191e74b07d5b" \
--snapshot-location-config resourceGroup="css-preprod-1-westus-1",subscriptionId="52c48814-88e2-4d41-ae63-191e74b07d5b",apiTimeout=15m \
--velero-pod-cpu-limit="0" --velero-pod-mem-limit="0" \
--velero-pod-mem-request="0" --velero-pod-cpu-request="0"

These are the logs:

(preprod)[super-user@css-suf ~]$ kubectl logs -f deployment/velero -n velero
time="2021-03-04T22:24:55Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:171"
time="2021-03-04T22:24:55Z" level=info msg="Starting Velero server v1.2.0 (5d008491bbf681658d3e372da1a9d3a21ca4c03c)" logSource="pkg/cmd/server/server.go:173"
time="2021-03-04T22:24:55Z" level=info msg="1 feature flags enabled []" logSource="pkg/cmd/server/server.go:175"
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/cluster-role-bindings
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-microsoft-azure kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2021-03-04T22:24:55Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-microsoft-azure kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2021-03-04T22:24:55Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:337" namespace=velero
An error occurred: Get https://10.68.248.1:443/api/v1/namespaces/velero: dial tcp 10.68.248.1:443: i/o timeout

It seems that the installation cannot get pass checking if the namespace velero exists, which it does, and starts restarting inmediately.

**Comment by dsu-igeek** [comment]
You're installing Velero 1.2.0.  Please try with Velero 1.5.3 and Azure plugin 1.1.2

**Comment by luisbtejada** [comment]
@dsu-igeek it still fails:

### The command used:
velero install \
--provider azure \
--image velero/velero:v1.5.3 \
--plugins velero/velero-plugin-for-microsoft-azure:v1.1.2 \
--bucket velero \
--secret-file ./credentials-velero \
--backup-location-config resourceGroup="css-preprod-1-westus-1",storageAccount="csspreprod1westus1st1",subscriptionId="52c48814-88e2-4d41-ae63-191e74b07d5b" \
--snapshot-location-config resourceGroup="css-preprod-1-westus-1",subscriptionId="52c48814-88e2-4d41-ae63-191e74b07d5b",apiTimeout=15m \
--velero-pod-cpu-limit="0" --velero-pod-mem-limit="0" \
--velero-pod-mem-request="0" --velero-pod-cpu-request="0"

### Output: 

CustomResourceDefinition/backups.velero.io: attempting to create resource
CustomResourceDefinition/backups.velero.io: created
CustomResourceDefinition/backupstoragelocations.velero.io: attempting to create resource
CustomResourceDefinition/backupstoragelocations.velero.io: created
CustomResourceDefinition/deletebackuprequests.velero.io: attempting to create resource
CustomResourceDefinition/deletebackuprequests.velero.io: created
CustomResourceDefinition/downloadrequests.velero.io: attempting to create resource
CustomResourceDefinition/downloadrequests.velero.io: created
CustomResourceDefinition/podvolumebackups.velero.io: attempting to create resource
CustomResourceDefinition/podvolumebackups.velero.io: created
CustomResourceDefinition/podvolumerestores.velero.io: attempting to create resource
CustomResourceDefinition/podvolumerestores.velero.io: created
CustomResourceDefinition/resticrepositories.velero.io: attempting to create resource
CustomResourceDefinition/resticrepositories.velero.io: created
CustomResourceDefinition/restores.velero.io: attempting to create resource
CustomResourceDefinition/restores.velero.io: created
CustomResourceDefinition/schedules.velero.io: attempting to create resource
CustomResourceDefinition/schedules.velero.io: created
CustomResourceDefinition/serverstatusrequests.velero.io: attempting to create resource
CustomResourceDefinition/serverstatusrequests.velero.io: created
CustomResourceDefinition/volumesnapshotlocations.velero.io: attempting to create resource
CustomResourceDefinition/volumesnapshotlocations.velero.io: created
Waiting for resources to be ready in cluster...
Namespace/velero: attempting to create resource
Namespace/velero: created
ClusterRoleBinding/velero: attempting to create resource
ClusterRoleBinding/velero: created
ServiceAccount/velero: attempting to create resource
ServiceAccount/velero: created
Secret/cloud-credentials: attempting to create resource
Secret/cloud-credentials: created
BackupStorageLocation/default: attempting to create resource
BackupStorageLocation/default: created
VolumeSnapshotLocation/default: attempting to create resource
VolumeSnapshotLocation/default: created
Deployment/velero: attempting to create resource
Deployment/velero: created
Velero is installed! ⛵ Use 'kubectl logs deployment/velero -n velero' to view the status.

### Logs:

kubectl logs -f deployment/velero -n velero
time="2021-03-09T09:37:05Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:191"
time="2021-03-09T09:37:05Z" level=info msg="Starting Velero server v1.5.3 (123109a3bcac11dbb6783d2758207bac0d0817cb)" logSource="pkg/cmd/server/server.go:193"
time="2021-03-09T09:37:05Z" level=info msg="1 feature flags enabled []" logSource="pkg/cmd/server/server.go:195"
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-remap-version
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-pvc-node-selector
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/cluster-role-bindings
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-preserve-fields
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/init-restore-hook
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-microsoft-azure kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2021-03-09T09:37:05Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-microsoft-azure kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
An error occurred: Get "https://10.68.248.1:443/api?timeout=32s": dial tcp 10.68.248.1:443: i/o timeout


I'm a little lost here, I don't understand why it can't register the plugin or when using a previous version why it can't interact with the API.

**Comment by dsu-igeek** [comment]
Not sure.  Do you know where that 10.68.248.1 was specified?  Is that the Azure endpount?

**Comment by luisbtejada** [comment]
@dsu-igeek Yes, that’s the endpoint of the private AKS.
What I can guess is that the plug-in is having some trouble communicating with the kube api.
