### ISSUE TITLE
Skip backup/restore hook invocation for resource-only backup/restores

### ISSUE THREAD

**Issue by lautenbde** [vmware-tanzu/velero#3529]
**Describe the problem/challenge you have**
It appears that Velero will always invoke hooks on Pods/Containers when according hook annotations are present even when the backup does not involve any volume snapshot (e.g. when --snapshot-volumes=False).

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Hook annotations are ignored if no volume snapshots are in play to avoid unnecessary quiescing.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.5.3
- Kubernetes version (use `kubectl version`): n/a
- Kubernetes installer & version: n/a
- Cloud provider or hardware configuration: n/a
- OS (e.g. from `/etc/os-release`): n/a

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by dsu-igeek** [comment]
Execution hooks are not limited to quiescing, they could be doing other operations needed to backup/restore the pod.  We are planning on introducing application level snapshots that would call quiesce hooks internally, which would get the desired behavior if we skipped the snapshot of the app.
