### ISSUE TITLE
Velero: error parsing backup contents: directory "resources" does not exist

### ISSUE THREAD

**Issue by pranitha89** [vmware-tanzu/velero#3540]
Hi Team,

I am testing velero backup and restore for our AKS cluster persistent volumes.
I am able to backup pvs using the below command successfully 

 velero backup create bu --include-cluster-resources=true --include-resources 'persistentvolumes=pvc-ee198b55-febf-4664-93e2-1e740a99b82e' --snapshot-volumes=true --include-namespaces tst-1234-velero

but while restoring I am getting the error 
"Velero: error parsing backup contents: directory "resources" does not exist"

and if I see the restore logs then it shows like it is successful (see attached logs)
![image](https://user-images.githubusercontent.com/19166921/110323650-2c401d80-8015-11eb-8a9c-d298ebb4326a.png)

please guide me if I am executing wrong commands if so kindly provide the reference document.

**Comment by dsu-igeek** [comment]
It's very difficult to diagnose with incomplete logs.  Please add complete logs as below.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`


**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]


**Environment:**

- Velero version (use `velero version`):
- Velero features (use `velero client config get features`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by pranitha89** [comment]
Thank you for the swift response.

**Please find the logs attached for velero deployment**
[velero-deploy logs.txt](https://github.com/vmware-tanzu/velero/files/6106243/velero-deploy.logs.txt)

**below screenshot is the log for describing backup**
![image](https://user-images.githubusercontent.com/19166921/110426984-0bd39a00-80cd-11eb-8c48-48a442128eb5.png)

**below is backup logs**
[velero backup logs.txt](https://github.com/vmware-tanzu/velero/files/6106269/velero.backup.logs.txt)

**below screenshot is for describing restore**
![image](https://user-images.githubusercontent.com/19166921/110427278-800e3d80-80cd-11eb-84ca-5f2170e537f9.png)

**below screenshot is for restore logs**
![image](https://user-images.githubusercontent.com/19166921/110427531-e7c48880-80cd-11eb-865c-f2030d649c64.png)

Environment:

[P000047@testppocapp001 ~]$ **velero version**
Client:
        Version: v1.2.0
        Git commit: 5d008491bbf681658d3e372da1a9d3a21ca4c03c
Server:
        Version: v1.5.1

[P000047@testppocapp001 ~]$ **velero client config get features**
features: <NOT SET>

[P000047@testppocapp001 ~]$ **kubectl version**
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"c7c4f6ce84bf8535a782b67465807651a4bd649b", GitTreeState:"clean", BuildDate:"2021-01-18T09:49:05Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Cloud provider : Azure**

[P000047@testppocapp001 ~]$ **cat /etc/os-release**
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

kindly let me know if you need further info.

Thank you in advance!

**Comment by dsu-igeek** [comment]
According to the backup log, it didn't backup anything:

```
time="2021-03-08T12:29:39Z" level=info msg="Backed up a total of 0 items" backup=velero/bu logSource="pkg/backup/backup.go:443" progress=
```
The reason it didn't backup anything is the `--include-resources 'persistentvolumes=pvc-ee198b55-febf-4664-93e2-1e740a99b82e' ` option.  That is used for resource names such as deployments or configmaps (https://velero.io/docs/v1.5/resource-filtering/#--include-resources)  There are no resources whose kind match that so it didn't backup anything.  Please try removing that option, if the PVC is referenced from the namespace it should get included.

The restore should give a better error message, so I entered a bug for it #3565.

I'm going to close this issue, please feel free to re-open if there's still an issue.  If you need help with setting flags, etc. please start a discussion.  Thanks!

**Comment by pranitha89** [comment]
Thank you so much for your analysis. Actually I want to work on taking backups and restores of Azure Disks (persistent volumes) only.
Could you please refer any related document for PVs and PVCs only.

Thank you so much in advance!!
