### ISSUE TITLE
Backup CSI Volume Snapshots to S3 (Feature Request)

### ISSUE THREAD

**Issue by haslersn** [vmware-tanzu/velero#3544]
We have a bare-metal Kubernetes cluster with in-cluster rook-ceph storage. For our volume backups we'd like to have the following properties:

1. Volume backups must be taken from atomic snapshots.
2. Volume backups must be stored in a durable storage outside of our cluster, preferably S3.
3. Cross-cluster restores of volume backups must be supported.

We can't use velero-plugin-for-csi, because it doesn't provide (2) and (3), and we can't use the Velero Restic integration, because it doesn't provide (1).

**Proposed solution**

We'd like to see velero-plugin-for-csi having an option to store the snapshot contents in S3. I think this can be realized using Restic as follows: After taking a snapshot, use CSI Volume Cloning in order to create a volume from it. Then mount that volume read-only into a Pod that backs up the data using Restic.

Note that this is widely different from the Velero Restic integration, because it works on a read-only clone of the volume instead of the live volume. This way we maintain property (1) while achieving property (2).

Property (3) can be achieved as follows. When restoring a volume where the snapshot does not exist in the cluster, use Restic in order to restore the volume from S3 instead.

**Question**

Is this something which you would like to see in velero-plugin-for-csi? Or is it more likely that somebody needs to make a fork/third-party solution?

**Environment**

- Kubernetes version: 1.23
- Cloud provider or hardware configuration: bare-metal

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by dsu-igeek** [comment]
This is something that is going to be handled more generally in Velero as we make data movement a part of Velero proper and integrate it with Astrolabe (https://github.com/vmware-tanzu/astrolabe).  This needs to offer the clone/attach snapshot functionality as an option, but on many storage systems clone of a snapshot is a very expensive operation, so when we can, we will use native data path to extract data from snapshots.  This also needs to handle the data movement independently of the snapshot so that we do not stall the backup while data is being copied (the way Restic is handled currently).  We'd welcome involvement, there will be architecture discussions as we move forward.

**Comment by dsu-igeek** [comment]
It will depend on the storage system.  Not all storage systems have native data paths, but EBS has one as well as vSphere.

**Comment by haslersn** [comment]
@dsu-igeek 

> We'd welcome involvement, there will be architecture discussions as we move forward.

When and where do these architecture discussions take place?

**Comment by nrb** [comment]
@haslersn Please join our community meetings, listed on the velero.io/community page.

**Comment by half-life666** [comment]
May I ask what is the current status for this issue? How is the architecture discussions going on? Is there a design doc in progress?   

One thing I'd like to point out is the user scenario (or the export policy), if we look at commercial solutions like kasten, for data export, the user is able to configure backup policy (frequency and retention) for snapshot and the data exported seperately. 

E.g., user can choose snapshot frequency is per hour, retention is 24 hours, then data export frequency 1 export per day, and retention is 7 days.

From my understanding of velero taking snapshot using velero-plugin-for-vsphere:
1. velero can not setup frequency and retention for data export, it's one export per snapshot
2. velero has no idea if the data source is snapshot or exported data


Another aspect is the implementation options, it looks like there still two options:
- major changes in velero-plugin-for-csi 
  As proposed here, velero-plugin-for-csi can implement the volumesnapshotter interface and add restic integration to move data to s3. However, this means velero-plugin-for-csi has to do some similar thing as velero does for restic support, which may not be much work though.
- major changes in velero
  For this option, velero already has restic integration, seems like velero just need to add some extra control for data export/import at backup/restore controllers, however, this option still has relateive large impact for velero base code.

**Comment by jglick** [comment]
> After taking a snapshot, use CSI Volume Cloning in order to create a volume from it. Then mount that volume read-only into a Pod that backs up the data using Restic.

If I understand correctly, such a strategy would also bypass the documented limitation in the Restic integration that it will only work on a volume currently mounted by a pod—making Restic mode barely usable if, for example, you have a `StatefulSet` which is sometimes scaled to zero and sometimes to one replica.

**Comment by haslersn** [comment]
What's the status of this? It seems there's progress on https://github.com/ceph/ceph-csi/issues/2142 which allows the proposed solution to be efficient with Rook Ceph.

**Comment by ywk253100** [comment]
Refer to https://github.com/vmware-tanzu/velero/issues/3229 for the latest status of data mover.

**Comment by haslersn** [comment]
It seems #3229 is more about abstracting the tool used to move data and the storage backend where data is stored. The current design doesn't change how filesystem backups are taken at the source.

In contrast, this feature request is about the data source: instead of reading from a volume attached to a running Pod, data should be read from an atomic snapshot.

**Comment by QuingKhaos** [comment]
Yeah, #3229 has a completely different goal and is independent to this issue. This issue is about efficient data movement with Restic (or any other tool in the future) from an atomic read only CSI snapshot.

**Comment by QuingKhaos** [comment]
Use case: we have CephFS volumes with around ~800Gi and millions of small files (OEM web assets, js, css) and OEM web apps are built and rebuilt depending on changing parameters. The runtime of Restic copying those is okay, but not atomic.

**Comment by TomHellier** [comment]
@Lyndon-Li has there been any progress on this?

**Comment by jsalatiel** [comment]
I am reading the documentation for [csi](https://velero.io/docs/v1.11/csi/) and it appears to me that 3 requirements are somehow implemented. Am i understanding the documentation incorrectly?

_Velero will include the generated VolumeSnapshot and VolumeSnapshotContent objects in the backup tarball, as well as upload all VolumeSnapshots and VolumeSnapshotContents objects in a JSON file to the object storage system.
When Velero synchronizes backups into a new cluster, VolumeSnapshotContent objects and the VolumeSnapshotClass that is chosen to take snapshot will be synced into the cluster as well, so that Velero can manage backup expiration appropriately._

**Comment by sseago** [comment]
@jsalatiel When just using the CSI plugin, while the VS and VSC objects are stored in S3, the actual file bits (the "content" part of VolumeSnapshotContent) only live in the cluster. The datamover feature that we're delivering with 1.12 will take the next step and copy the actual filesystem contents into s3 as well, which will allow restores to other clusters. With the 1.12 datamover, this issue should be able to be closed.

**Comment by jsalatiel** [comment]
Amazing, tks!

**Comment by Lyndon-Li** [comment]
Implemented in v1.12

**Comment by valentin2105** [comment]
Any docs about how to achieve that ? 

My PVC Snapshot are stored on the cluster's Ceph, but how to store them on S3 ?
