### ISSUE TITLE
Velero Installation with --features=EnableCSI fails on AWS

### ISSUE THREAD

**Issue by PRatwani** [vmware-tanzu/velero#3549]
I created a Kubernetes cluster on AWS, and installed CSI driver for EBS as : https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html

After that I started installing "velero 1.5.3"  as per the instructions given at https://github.com/vmware-tanzu/velero-plugin-for-aws. I needed CSI support for taking backups, so I chose EnableCSI option as well.
$ velero install  --provider aws  --plugins velero/velero-plugin-for-aws:v1.1.0,velero/velero-plugin-for-csi:v0.1.2 --bucket $BUCKET --backup-location-config region=$REGION  --snapshot-location-config region=$REGION  --secret-file ./credentials-velero --features=EnableCSI

$echo $REGION; echo $BUCKET
ap-south-1
csi-velero-bucket

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- Output:
- time="2021-03-09T09:28:20Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:191"
time="2021-03-09T09:28:20Z" level=info msg="Starting Velero server v1.5.3 (123109a3bcac11dbb6783d2758207bac0d0817cb)" logSource="pkg/cmd/server/server.go:193"
time="2021-03-09T09:28:20Z" level=info msg="1 feature flags enabled [EnableCSI]" logSource="pkg/cmd/server/server.go:195"
time="2021-03-09T09:28:20Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-remap-version
time="2021-03-09T09:28:20Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
.
.
.
time="2021-03-09T09:28:20Z" level=info msg="Checking existence of namespace." logSource="pkg/cmd/server/server.go:380" namespace=velero
time="2021-03-09T09:28:20Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:386" namespace=velero
I0309 09:28:22.343036       1 request.go:621] Throttling request took 1.047782566s, request: GET:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1beta1?timeout=32s
time="2021-03-09T09:28:23Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:415"
time="2021-03-09T09:28:23Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:449"
time="2021-03-09T09:28:23Z" level=warning msg="Velero restic daemonset not found; restic backups/restores will not work until it's created" logSource="pkg/cmd/server/server.go:495"
time="2021-03-09T09:28:23Z" level=info msg="Starting controllers" logSource="pkg/cmd/server/server.go:571"
time="2021-03-09T09:28:23Z" level=info msg="Starting metric server at address [:8085]" logSource="pkg/cmd/server/server.go:578"
time="2021-03-09T09:28:25Z" level=fatal msg="The 'EnableCSI' feature flag was specified, but CSI API group [snapshot.storage.k8s.io/v1beta1] was not found." logSource="pkg/cmd/server/server.go:555"

- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- $ velero version
Client:
        Version: v1.5.3
        Git commit: 123109a3bcac11dbb6783d2758207bac0d0817cb
Server:
        Version:

- Velero features (use `velero client config get features`): 
- features: <NOT SET>
- Kubernetes version (use `kubectl version`):
- $ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- AWS: EC2 (1Master, 2Worker : t2.medium)
- OS (e.g. from `/etc/os-release`):
- $ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by dsu-igeek** [comment]
It looks like the CSI Snapshot External Controller has not been deployed in your environment.  Some notes here: https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-cis-volume-snapshot-beta/

CSI Snapshotting is still BETA in Velero.  We recommend you use the AWS Volume Snapshotter plug-in instead.
