### ISSUE TITLE
Restoring Restic volume on multiple pods, but only one pod waits for it (v1.4.0)

### ISSUE THREAD

**Issue by cjmaloof** [vmware-tanzu/velero#3552]
We have a volume which is mounted on several different pods, annotated with `backup.velero.io/backup-volumes` so that Restic handles its backup and restore. However, upon restore, only one of these pods (the first to start up, I think) receives a `restic-wait` init container. The rest sometimes start up before the volume has been restored, which can cause problems.

In the restore logs, only the pod with the `restic-wait` container displays "Restic backups for pod found".

Version: 
```
$ velero version
Client:
        Version: v1.5.1
        Git commit: 87d86a45a6ca66c6c942c7c7f08352e26809426c
Server:
        Version: v1.4.0
```

**Comment by dsu-igeek** [comment]
**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`


**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]


**Environment:**

- Velero version (use `velero version`):
- Velero features (use `velero client config get features`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by cjmaloof** [comment]
@dsu-igeek Thanks for updating. Unfortunately the application with the error is proprietary and also big enough that the logs aren't easy to parse. I will try to create a minimal replication scenario when I have some time (not sure when).

Velero version is in the issue description. I'm running the client in Windows 10 Enterprise on Cygwin.
```
$ velero client config get features
features: <NOT SET>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
