### ISSUE TITLE
Scheduler should not create Backups until outstanding backups for the schedule have completed

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#3554]
**What steps did you take and what happened:**
If a scheduled backup time is reached while a previous backup for the schedule is running, a new Backup resource is created.  This can result in multiple Backups being queued that will all get executed together when the queue is unstalled.

**What did you expect to happen:**
Backups should not be queued until any previous backups for the schedule have completed.  

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
Not a stale reopening.

**Comment by blackpiglet** [comment]
This issue is already fixed by PR #5283
