### ISSUE TITLE
Document and test upgrades from v1.4.3 and v1.5.3 to v1.6.0

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#3562]
**Describe the problem/challenge you have**

Full upgrade steps are not documented for v1.5.3 and v1.4.3 to v1.6.0. These should be done before final release.

**Describe the solution you'd like**

Documentation for upgrading to v1.6.0 which should include (but not limited to):

- Any CRD upgrades necessary
- Impacts on restic data

**Anything else you would like to add:**

v1.4.3 instructions should be included since requiring uses to move through 2 versions to get a working update is not possible in some circumstances, such as when Velero is included in a product.

---

 - [x] Update v1.4 doc
 - [x] Update v1.5 doc
 - [x] Update v1.6 doc
 - [x] Test upgrade to v1.6.0

**Comment by carlisia** [comment]
@vmware-tanzu/velero-owners + @jenting: closing this as it has all been done as per https://github.com/vmware-tanzu/velero/issues/3623 and coordination.
