### ISSUE TITLE
Document and test upgrades from v1.5.x and v1.6.x to v1.7.0

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/velero#3563]
**Describe the problem/challenge you have**

Before releasing v1.7.0, we will need upgrade steps for moving from the latest two versions of Velero to v1.7.0

**Describe the solution you'd like**

Documentation should include, but not be limited to, the following:

- Any CRD schema upgrades necessary
- Any plugin compatibility changes
- Any restic impacts

**Comment by zubron** [comment]
Although this has the release blocker label, we can merge the fix for this after RC1.

**Comment by zubron** [comment]
No further changes to the website documentation will be made for this release. The only outstanding item is adding an update to the release notes for plugin developers about how the change to using distroless images may impact them.
