### ISSUE TITLE
Restore of empty backups should have a better failure message

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#3565]
**What steps did you take and what happened:**
Created a backup with no entries in it

`velero backup create empty-backup-1 --include-cluster-resources=true  --include-namespaces tst-1234-velero --include-resources 'persistentvolumes=pvc-ee198b55-febf-4664-93e2-1e740a99b82e'

The include-resources is incorrect and no resources are selected.  The result is a backup with no items:

```
Name:         empty-backup-1
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.19.1+vmware.2
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=19

Phase:  Completed

Errors:    0
Warnings:  0

Namespaces:
  Included:  tst-1234-velero
  Excluded:  <none>

Resources:
  Included:        persistentvolumes=pvc-ee198b55-febf-4664-93e2-1e740a99b82e
  Excluded:        <none>
  Cluster-scoped:  included

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-03-11 15:29:21 -0800 PST
Completed:  2021-03-11 15:29:22 -0800 PST

Expiration:  2021-04-10 16:29:21 -0700 PDT

Total items to be backed up:  0
Items backed up:              0

Velero-Native Snapshots: <none included>
```

If you attempt to restore from this backup, it will fail with 'error parsing backup contents: directory "resources" does not exist'

`velero restore create empty-restore --from-backup empty-backup-1`

`velero restore describe empty-restore`

```
Name:         empty-restore
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:  PartiallyFailed (run 'velero restore logs empty-restore' for more information)

Started:    2021-03-11 15:31:54 -0800 PST
Completed:  2021-03-11 15:31:54 -0800 PST

Errors:
  Velero:   error parsing backup contents: directory "resources" does not exist
  Cluster:    <none>
  Namespaces: <none>

Backup:  empty-backup-1

Namespaces:
  Included:  all namespaces found in the backup
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto
````

**What did you expect to happen:**

Restore should be Failed, not PartiallyFailed
A better error message that explains the restore failed because there were zero items to restore.

**Environment:**

- Velero version (use `velero version`): 1.5.3

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by dkeven** [comment]
Chiming in here, IMHO, since we're able to run an empty backup (which backs up nothing) successfully, would it be more resonable to run an empty restore (which restores nothing) successfully than throwing out an error?

**Comment by cleverhu** [comment]
I tried it. If the backup resources do not exist, the backup items with a length of 0 will be successfully backed up without an error. However, when try to create the restore by the backup an error will be reported. Therefore, I do not know which method is better and I pull a request, I hope you can give me some advice.

**Comment by allenxu404** [comment]
In the consideration of historical empty backups that already existed,  we fix this issue by letting the restore from an empty backup success only with the warning indicating that the backup contains no items to be restored.
