### ISSUE TITLE
Non-Running Pod with PV should be skipped from backup

### ISSUE THREAD

**Issue by levindecaro** [vmware-tanzu/velero#3570]
**Describe the problem/challenge you have**
Completed/Error Cron Pod, BuildConfig Pod in OCP always report backup failed when it has pv/emptydir attached. Restic has no idea to skip those non-running pod. As a result, the backup will always report PartiallyFailed. Although we can bypass  them by annotation, but it is hard to maintain in general.

**Describe the solution you'd like**
Should skip those error/completed pod in restic backup option.

**Environment:**

- Velero version (use `velero version`): 1.5.3
- Kubernetes version (use `kubectl version`): 1.19
- Kubernetes installer & version: OCP 4.6
- Cloud provider or hardware configuration: VMware
- OS (e.g. from `/etc/os-release`): RHCOS 4.6

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by zubron** [comment]
Hi @levindecaro - Thanks for reporting this. This is a known issue with our restic support and we already have an issue open relating to this: #2395.

I am going to close this as a duplicate, but if you have any other info, please leave comments on #2395. Thanks!
