### ISSUE TITLE
PR 3125 Breaks API Group Versions Feature (PR 3133)

### ISSUE THREAD

**Issue by codegold79** [vmware-tanzu/velero#3571]
**What steps did you take and what happened:**
I'm trying to run e2e tests that ensure the API group versions features is working as intended, however, they are not passing. See the latest version of the API group versions e2e tests in PR #3564. When I try to restore Kubernetes non-preferred API group versions, I get this error:

```bash
Errors:
  Namespaces:
    rockbands-src-v2beta1:  error restoring rockbands.music.example.io/rockbands-src-v2beta1/beatles: the server could not find the requested resource
    rockbands-src-v2beta2:  error restoring rockbands.music.example.io/rockbands-src-v2beta2/beatles: the server could not find the requested resource
    rockbands-src-v1:       error restoring rockbands.music.example.io/rockbands-src-v1/beatles: the server could not find the requested resource
```

**What did you expect to happen:**
I expected all API versions that were in the backup tarball file to be restored. None of the errors above should have occurred because I verified v2beta1, v2beta2, and v1 rockband versions were in the tarball.

**More information:**
@zubron and I have found the commit that broke API group versions feature was from PR 3125. 

```git
2021-03-04 16:21 -0500 Pranav Gaikwad              o Restore progress reporting (#3125)
commit c46fe71b12ecc16786676886a64971102527d631
```

PR 3125 removed the changes that I had made in PR 3133 restore.go. See the diffs in pkg/restore/restore.go, lines 749-758: https://github.com/vmware-tanzu/velero/pull/3125/files#diff-e0498755be37b683528e2569667d67818bb676827c420aab49adc62cb6d47fe3L749-L758).

Tagging @pranavgaikwad.

**Vote on this issue!**
- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by dsu-igeek** [comment]
Added P0 because "Hair on fire", what's not to love
