### ISSUE TITLE
GH Action bug: If reviewers already assigned, more keep being added

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3573]
Issue with our auto assign PR reviewers GH action: It works fine until there's an additional operation to the PR, like changing its state to/from WIP, or, very common, adding additional commits.

This happens now that we are limiting the number of reviewers to a subset of the total.

This is a known issue with the GH Action:

https://github.com/kentaro-m/auto-assign-action/issues/16

I'll keep an eye for this fix and update it in our repos.

**Comment by zubron** [comment]
Could we minimise the impact of this by changing the trigger to [not include `synchronize`](https://github.com/vmware-tanzu/velero/blob/main/.github/workflows/auto_assign_prs.yml#L6)? My understanding is that by including that event, this job will run again on every push.

I think we'll still encounter this issue if we re-run the checks for the PR, but this should at least stop it being triggered on every push.

**Comment by zubron** [comment]
Looking at our actions, we also have the [PR labeler job within the file for assigning PRs](https://github.com/vmware-tanzu/velero/blob/main/.github/workflows/auto_assign_prs.yml#L17-L24). I think we want _that_ job to run on every push, so we should separate that out into a different action.

**Comment by carlisia** [comment]
Def worth it trying the first, and def a yes for the second. Let me try to improve this. Thanks for taking a look @zubron.

**Comment by jenting** [comment]
Close it, feel free to reopen if the issue still happens again.
