### ISSUE TITLE
Document manual testing steps

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#3579]
Make a checklist of tests that should be performed by hand before the release is finished.  This is just formalizing the existing steps, no need to add stuff that hasn't been covered in the past.  We should probably keep this as a doc, perhaps TESTING.md but if you think that doesn't work, we can leave it in a google doc or something.

**Comment by carlisia** [comment]
I think keeping it in a TESTING.md file is best for visibility, until we have a better system.
