### ISSUE TITLE
Document when to add a changelog, and when to not

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3589]
Ex: if there was a bug fix on the main branch for an issue that was introduced after the last release, do we add a changelog?

Please add here odd ball instances you are not clear about if they deserve a changelog or not.

**Comment by eleanor-millman** [comment]
Sounds like you don't expect changelogs for website changes?

**Comment by carlisia** [comment]
Correct, website changes and documentation definitely don't get a changelog. Only feature changes that affect the user, bug fixes from a previous version, and breaking changes in the API of our code.
