### ISSUE TITLE
Bug with the Velero uninstall cmd

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3599]
There are some major and minor problems with the uninstall command: https://github.com/vmware-tanzu/velero/blob/main/pkg/cmd/cli/uninstall/uninstall.go#L42-L74

- At each operation, it returns if there is an API error. This has a high potential of leaving behind resources that are still in the cluster only because the code didn't get to the point where they are removed. The solution is to aggregate all (real) errors and return them only at the end.
- An API error is not necessarily an error in this context. Example: a namespace (or any other resource) not found returns an API error, but it should not be considered an actual error of the cmd. In this case a log message is sufficient. Other error types should be distinguished and returned/aggregated as an error.
- The [wait](https://github.com/vmware-tanzu/velero/blob/e9c997839ebbb04688a88ffb981eeb74de51b380/pkg/cmd/cli/uninstall/uninstall.go#L81) for the namespace to be terminated is a Kubernetes anti-pattern.  If this was added because of the e2e tests, then the test is the piece that needs to wait for the resource to be deleted before proceeding, not the cli cmd. Also, it's weird that the uninstall takes way longer than the install. :/ - If this was added for the benefit of the user, again, it's an anti pattern to make the user wait for a resource to change state but if we want to aid the user we can log a message of the ns phase (see below).
- Any new API calls should be added using the kubebuilder/controller runtime framework.

I'm addressing the code issues above + modifying e2e tests that rely on this uninstall.

This is what running `velero uninstall` twice in a row without any (actual) errors could look like:

```
❯ velero uninstall
Velero uninstalled

❯ velero uninstall
Velero installation namespace "velero" is terminating.
Velero installation rolebinding "velero" does not exist, skipping.
Velero CRDs do not exist, skipping.
Velero uninstalled
```

**Comment by dsu-igeek** [comment]
You can make the wait optional in the internal call and add a flag for it.  A lot of our other commands have a --wait CLI option to ensure the operation finishes, if you have time you could plumb that, or open an issue to do it in 1.7
