### ISSUE TITLE
apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated

### ISSUE THREAD

**Issue by mapdegree** [vmware-tanzu/velero#3610]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

**What did you expect to happen:**
No warning or issues reported when using K8S 1.20.2

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

```W0322 09:58:13.884407     297 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 09:58:13.972263     297 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 09:58:14.156566     297 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 09:58:14.250639     297 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 09:58:14.339140     297 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0322 09:58:14.426516     297 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Command we are running is 
`helm install vmware-tanzu/velero --version 2.15.0`

**Environment:**

- Velero version (use `velero version`): 2.15.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.20.2 (Azure AKS)
- Kubernetes installer & version: helm v3.5.3
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): n/a

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment]
Hi @mapdegree. Thanks for raising this. This is something the team is aware of and we are tracking this in #2505. Given that we already have an issue for this, I'm going to close this one as a duplicate.
