### ISSUE TITLE
Velero Backup failed

### ISSUE THREAD

**Issue by AkhilCh308** [vmware-tanzu/velero#3621]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
I've deployed minio and installed velero CLI and velero plugin

```
root@mcds:/etc# velero backup get
NAME     STATUS   ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
backup   Failed   0        0          2021-03-22 17:35:31 +0000 UTC   28d       default            <none>
your     Failed   0        0          2021-03-24 12:52:59 +0000 UTC   29d       default            <none>
root@mcds:/etc# k get all -n velero
NAME                          READY   STATUS      RESTARTS   AGE
pod/minio-5b84955bdd-zg95x    1/1     Running     0          47h
pod/minio-setup-4sgss         0/1     Completed   0          47h
pod/velero-679457dc45-jpmnk   1/1     Running     0          44h
NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/minio     ClusterIP   100.70.41.197   <none>        9000/TCP         47h
service/minio-2   NodePort    100.67.15.84    <none>        9000:31929/TCP   47h
NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/minio    1/1     1            1           47h
deployment.apps/velero   1/1     1            1           44h
NAME                                DESIRED   CURRENT   READY   AGE
replicaset.apps/minio-5b84955bdd    1         1         1       47h
replicaset.apps/velero-679457dc45   1         1         1       44h
NAME                    COMPLETIONS   DURATION   AGE
job.batch/minio-setup   1/1           9s         47h
```
**What did you expect to happen:**

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
time="2021-03-24T12:52:59Z" level=info msg="Getting backup item actions" backup=velero/your logSource="pkg/controller/backup_controller.go:545"
time="2021-03-24T12:53:00Z" level=info msg="Setting up backup store to check for backup existence" backup=velero/your logSource="pkg/controller/backup_controller.go:551"
time="2021-03-24T12:53:00Z" level=error msg="backup failed" controller=backup error="error checking if backup already exists in object storage: rpc error: code = Unknown desc = RequestError: send request failed\ncaused by: Head https://mcds.minio.local:443/velero/backups/your/velero-backup.json: dial tcp: lookup mcds.minio.local on 100.64.0.10:53: no such host" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:562" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*backupController).runBackup" key=velero/your logSource="pkg/controller/backup_controller.go:279"
time="2021-03-24T12:53:05Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code 

- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
root@mcds:/etc# velero backup describe your
Name:         your
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.19.3+vmware.1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=19

Phase:  Failed (run `velero backup logs your` for more information)

Errors:    0
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  tkg-system

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-03-24 12:52:59 +0000 UTC
Completed:  2021-03-24 12:53:00 +0000 UTC

Expiration:  2021-04-23 12:52:59 +0000 UTC

Velero-Native Snapshots: <none included>
root@mcds:/etc#

- `velero backup logs <backupname>`
root@mcds:/etc# velero backup logs your
An error occurred: Get "https://mcds.minio.local:443/velero/backups/your/your-logs.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%!F(MISSING)20210324%!F(MISSING)minio%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20210324T130031Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=3fe6a8f6c8da110fc9556f7eeac4ca60c9078cad8d0faef73d59cfa2a5329c03": x509: certificate signed by unknown authority

The --insecure-skip-tls-verify flag can also be used to accept any TLS certificate for the download, but it is susceptible to man-in-the-middle attacks.

- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by AkhilCh308** [comment]
Also now I've exposed https for minio host  and tried to create backup, following logs are here 

An error occurred: request failed: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>backups/back/back-logs.gz</Key><BucketName>velero</BucketName><Resource>/velero/backups/back/back-logs.gz</Resource><RequestId>166F4AC5B2D453C4</RequestId><HostId>7f149ef3-42f0-441a-b7e6-c4dcffe8ac74</HostId></Error>

**Comment by jakuboskera** [comment]
I've encountered the same issue and root cause was that I specified in `BackupStorageLocation` `.spec.objectStorage.prefix=""`. After changed value from `""` to some non-empty value e.g. `my-cluster`, it started to work.
