### ISSUE TITLE
e2e tests not cleaning up after failures

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3624]
The e2e tests that add k8s resources besides the Velero installation are not removing those resources from the cluster when there is a test failure. This is fine if there is no failure but otherwise it causes the cluster to be in an unexpected state and becomes the source of failure for other tests.

To do: ensure each test removes any added resources at each point where the test can fail.

Also: delete any created backups.

**Comment by ywk253100** [comment]
This should already be fixed by https://github.com/vmware-tanzu/velero/pull/4005 and https://github.com/vmware-tanzu/velero/pull/4007
