### ISSUE TITLE
Managing multi-tenant environment

### ISSUE THREAD

**Issue by sfelix-orange** [vmware-tanzu/velero#3633]
Managing several namespaces in a multi-tenant environment while not being the cluster admin.

We are currently working on a k8s cluster with several namespaces, but without being the cluster admin nor having a cluster role. We would like to be able to backup the pod's volumes in our namespaces using Velero. As is, we were not able to make it work without doing some modifications to Velero's code (see PR https://github.com/vmware-tanzu/velero/pull/3476 and https://github.com/vmware-tanzu/velero/pull/3477).
Is there a way to make it work without having to do these modifications?

Thanks and best regards.

Sebastien

**Environment:**

- Velero version (use `velero version`): TBD
- Kubernetes version: v1.19.3
- Kubernetes installer & version: TBD
- Cloud provider or hardware configuration: TBD
- OS (e.g. from `/etc/os-release`): TBD

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by dsu-igeek** [comment]
We don't believe this is possible at the moment.  There are a lot of features that require admin privileges such as creating CRDs which would be broken.  We are looking at ways to support self-service backups but this will require the cluster admin to allow the operations.  This is being tracked here: https://github.com/vmware-tanzu/velero/issues/2587
