### ISSUE TITLE
Velero Backup gets stuck in "InProgress" status while trying to take backup of stateful app from GKE

### ISSUE THREAD

**Issue by kokileswaran-n** [vmware-tanzu/velero#3636]
**What steps did you take and what happened:**
The velero backup status is showing Inprogress and when tried in the GKE cluster below are the steps followed
 

1. Created Kubernetes Cluster in GKE
2. Created bucket credentials
3. Downloaded Velero from `https://github.com/vmware-tanzu/velero/releases/download/v1.5.3/velero-v1.5.3-linux-amd64.tar.gz `
4. Installed Velero using 
`./velero install --provider aws --bucket xxxxxxxxxxxx --secret-file ./xxxxxxxxxxxx --use-restic --default-volumes-to-restic --backup-location-config region=us-geo,s3ForcePathStyle="true",s3Url=http://xxxxxxxxxxxxxxxxxx --plugins velero/velero-plugin-for-aws:v1.1.0`
5. Installed wordpress stateful application in new namespace. Provided the yaml files in the attachments. The persistent volume used here is 1Gi.
6. Ran the velero backup command
`./velero create backup <backupname> --include-namespaces <namespace>`
7. Checked the status of velero backup and shows in InProgress

**What did you expect to happen:**
The backup was supposed to be in completed state but it got stuck in Inprogress state.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
![velero_deployment_logs](https://user-images.githubusercontent.com/77956559/112715200-14b5cf80-8f05-11eb-95b0-d1de6c155958.png)

- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
![backup_describe](https://user-images.githubusercontent.com/77956559/112715369-cc4ae180-8f05-11eb-94c7-b2b0cb7c108a.png)

- `velero backup logs <backupname>` - Not available
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml` - Not available
- `velero restore logs <restorename>` - Not available

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
- GKE version
![GKE_version](https://user-images.githubusercontent.com/77956559/112715401-fbf9e980-8f05-11eb-8033-ccd69b0325b1.png)
- Velero get backup
![get_backup](https://user-images.githubusercontent.com/77956559/112715411-103de680-8f06-11eb-8f24-f8360887b9e7.png)
- Velero pods
![velero_pods](https://user-images.githubusercontent.com/77956559/112715436-29df2e00-8f06-11eb-81c7-8cb905340411.png)
- Velero backup location
![backup-location](https://user-images.githubusercontent.com/77956559/112715492-7591d780-8f06-11eb-9807-8cfcf7e75415.png)

**Environment:**

- Velero version (use `velero version`): 
![Velero_version](https://user-images.githubusercontent.com/77956559/112715385-dec51b00-8f05-11eb-8785-dc503af4c783.png)

- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kokileswaran-n** [comment]
Good day team do we have update on this issue.

**Comment by zubron** [comment]
Hi @kokileswaran-n - Apologies for the delay in responding to this issue.

Can you provide the full logs for the velero deployment using `kubectl logs deployment/velero -n velero`. We will need to see the full logs rather than just a section of them.

Also, can you check the restic pods which are in pending state (`kubectl describe pod -n velero restic-4wkhf`)? Our restic integration works by running a daemonset so that a restic pod is running on each node in the cluster. This is required so that the volumes that are in use on each node can be read and backed up. If restic is not running on a node, then a request to backup a volume on that node will not be processed. Thanks!
