### ISSUE TITLE
My full cluster backup using velero struck in "InProgress" status from 7 days

### ISSUE THREAD

**Issue by KiranMaheswaram** [vmware-tanzu/velero#3653]
[root@helper-3igi tmp]# velero get backups
NAME                          STATUS                       CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
londoncluster01-backup        InProgress                   2021-03-29 03:52:42 +0000 UTC   26d       default            <none>

----
[root@helper-3igi tmp]# velero backup describe londoncluster01-backup
Name:         londoncluster01-backup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  InProgress

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  included

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2021-03-29 03:52:42 +0000 UTC
Completed:  <n/a>

Expiration:  2021-04-28 03:52:42 +0000 UTC

Persistent Volumes: <none included>

Restic Backups (specify --details for more information):
  Completed:  28
----

Velero deployment logs:

time="2021-03-31T01:54:39Z" level=error msg="Error checking repository for stale locks" controller=restic-repository error="**_error running command=restic unlock --repo=s3:http://minio-velero.xxxxxx/velero/restic/dx-tgcf192 --password-file=/tmp/velero-restic-credentials-dx-tgcf192725208639_** --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: Fatal: config cannot be loaded: ciphertext verification failed\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/repository_manager.go:277" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryManager).exec" logSource="pkg/controller/restic_repository_controller.go:142" name=dx-tgcf192-default-dv748 namespace=velero

**Comment by KiranMaheswaram** [comment]
Hi Team,

Please consider this as high priority and request for the immediate assistance on this

**Comment by KiranMaheswaram** [comment]
Hello Team,

any update please

**Comment by oniram88** [comment]
Hi, I think I have the same error:


ERRO[0135] Error checking repository for stale locks     controller=restic-repo error="error running command=restic unlock --repo=s3:https://s3.XXXX/velero-backup-f7f0f7fa-abbb-4da2-81da-fa52f7e0e8e9/restic/XXXX-592-production --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password, stdout=, stderr=Fatal: unable to open config file: Stat: Access Denied.\nIs there a repository at the following location?\ns3:https://s3.XXX/velero-backup-f7f0f7fa-abbb-4da2-81da-fa52f7e0e8e9/restic/XXX-592-production\n: exit status 1" error.file="/github.com/vmware-tanzu/velero/pkg/restic/repository_manager.go:276" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryManager).exec" logSource="pkg/controller/restic_repository_controller.go:144" name=XXX-592-production-default-ptf4v namespace=velero



checking in the velero container, I can't find the password-file as prompted in the command: ```--password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password ```

Client:
	Version: v1.6.0
	Git commit: 5bd70fd8eef316d220317245e46dc6016c348dce
Server:
	Version: v1.6.0


with 'velero/velero-plugin-for-aws:v1.2.0'

I have just upgraded from velero 1.5 and plugin 1.1
