### ISSUE TITLE
Create a guide for application developers on how to structure their app for Velero backup/restore

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#3654]
**Describe the problem/challenge you have**
When Velero backs up and restores applications we have frequently had issues.  These include CR changes (e.g. the status field is stripped by Velero but the CRD requires it) and quiescing.

**Describe the solution you'd like**
As a first step toward application aware backups we should generate a guide of what Velero does during the backup and restore process and what developers should do in their application to enable correct backup and restore.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by eleanor-millman** [comment]
Closing until we have more asks
