### ISSUE TITLE
Investigate weird install failure of the deletebackuprequests CRD

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3656]
Data points:
- We found a [bug](https://github.com/vmware-tanzu/velero/issues/3600) with the install for v1.6.0
- That bug only happened on my machine.
- We found the source of the problem, and [removed it](https://github.com/vmware-tanzu/velero/pull/3652) from the code path for the v1.6.0 release
- We had different people run [a script ](https://gist.github.com/carlisia/8b76bc24b78efbcd8932c60062babba1) to install/uninstall Velero multiple times in a row to try and reproduce the bug. No one else could reproduce it, while I consistently did. 
- The RC1 was used, so that eliminated any suspicion with the problem being in the locally built binary
- The behavior was consistent even when running against the same AWS cluster.
- Applying the deletebackuprequests CRD with `kubetcl` always worked.
- Installing with v1.5 always worked.

TODO:
- Investigate:
   - Why the removed code caused that issue
   - Why it only happened for one user

**Comment by carlisia** [comment]
c/c @dsu-igeek in case you want to add pointers to this.

**Comment by carlisia** [comment]
Things to try:
- run in debug mode
- look into the stack returned by the api call so see what is triggering the time out
- exclude the deletebackuprequests crd from the installation process
- change the order of installation of the CRDs

**Comment by eleanor-millman** [comment]
Can't reproduce.
