### ISSUE TITLE
Add a multiple credentials use case to the documentation

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3657]
There should be an entry for it in this TOC:

![image](https://user-images.githubusercontent.com/16508/113331741-2ae0d880-92d5-11eb-8c8c-acc53ec5c066.png)

**Comment by carlisia** [comment]
For reference: https://velero.io/docs/v1.6.0-rc.1/locations/#create-a-storage-location-that-uses-unique-credentials

**Comment by eleanor-millman** [comment]
Closing this since we are going reorganize the whole TOC.
