### ISSUE TITLE
Support `kstatus` status fields

### ISSUE THREAD

**Issue by joshmue** [vmware-tanzu/velero#3664]
**Describe the problem/challenge you have**
Trying to get velero working as part of a gitops workflow using flux2. General idea for e. g. disaster recovery is:
1. Flux2 installs velero
1. Flux2 applies a `restores.velero.io`
1. Velero takes care of the heavy lifting regarding restoring the backup
1. When done, Velero patches the status of the `restores.velero.io` to be completed
1. Flux2 checks for the `.status` of the `restores.velero.io`; When it is completed, it continues with further deployments; Possibly takes control of restored workloads.

The problem I see: Flux2/kustomize-controller determines the status of custom resources using `kstatus`, which is not supported yet by velero, I think.

**Describe the solution you'd like**
Implement support for common [kstatus](https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus) conditions in velero CRD's.

**Anything else you would like to add:**
I think it would be a great addition to velero - not only because of the specific use case I described, which may be impossible or hard to do due to factors I did not take into account yet.

If I understand it correctly, using common `kstatus` conditions is the way to go either way as it seems to be propagated by K8s upstream.

I wonder what your take on this is: Do you agree on this? Do you think this could be implemented pretty easily?
If you want, I might also take a look into implementing this (cannot promise anything of course), in case this does not mean huge changes.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by dsu-igeek** [comment]
@joshmue If you have time to look at how to make this work and submit a PR we'd welcome it.  Thanks!

**Comment by joshmue** [comment]
Alright! I'll try to find some time to do it.

**Comment by joshmue** [comment]
Did not find time yet, but still: please unstale :sparkles:

**Comment by joshmue** [comment]
Still: Please unstale :sparkles:
