### ISSUE TITLE
Document steps needed to update Helm for each Velero release

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3679]
- Update the CRDs, adding the label for the Helm chart CRDs (Example: https://github.com/vmware-tanzu/helm-charts/pull/248)
- Bump the Velero version (app version and related tag) on the `Chart.yaml` and `values.yaml` file
- Bump the plugin version on the `values.yaml` file if needed
- Update the "upgrade" instruction and related tag on the `README.md` file
- Test the install with the new version (make sure the CRDs the same as Velero install CRDs, and labeling are correct)
- Test the upgrade to the new version (make sure the CRDs the same as Velero install CRDs, and labeling are correct)

This should be added to our release instructions page (https://velero.io/docs/main/release-instructions/).

c/c @jenting @cpanato what else do we need?

**Comment by eleanor-millman** [comment]
@jenting Are you interested in working on this? We are bumping it from the 1.7 release for now since no one is working on it, but if you can pick it up that would be great!

**Comment by jenting** [comment]
Sure, I'll find time to tackle it.

**Comment by eleanor-millman** [comment]
@jenting Is this still in you backlog? I was reviewing Area/Documentation issues and came across this one. Thanks!

**Comment by jenting** [comment]
> @jenting Is this still in you backlog? I was reviewing Area/Documentation issues and came across this one. Thanks!

Yes, I will find time to address this issue.
