### ISSUE TITLE
Velero - Terraform - AKS- Helm_Release

### ISSUE THREAD

**Issue by karlettoh** [vmware-tanzu/velero#3681]
Hi All,

After going through the documentation and examples online, I've reached a hurdle in getting the deployment to success.
I've set up a rudimentary test terraform project to test this.

However, we recieve:
StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"unauthorized_client\",\"error_description\":\"AADSTS700016: Application with identifier 'XXX-XXX-XXX-XXX' was not found in the directory 'XXXX-XXXX-XXXX-XXXX'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
...
"error_uri\":\"https://login.microsoftonline.com/error?code=700016\"}" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:217" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:175"

[This is the gist for the TF file](https://gist.github.com/karlettoh/2ccae018301f2379c98459d237305757)

I've gone through a ton of example configurations and tried to research online but from what I can see I'm not doing anything different to others? I was wondering if others had some experience and got this kind of set up to work?

Kind regards!

**Comment by adamrushuk** [comment]
I had this working in my lab using a Service Principle, but I've moved over to Managed Identity for auth now.
See my terraform config here:
- https://github.com/adamrushuk/devops-lab/blob/main/terraform/velero_mi_auth.tf
- https://github.com/adamrushuk/devops-lab/blob/main/terraform/velero.tf

**Comment by nrb** [comment]
@kacole2 Please take a look at Adam's notes as we do not officially support Terraform installation.
