### ISSUE TITLE
restic prune should be configurable (max-repack-size/max-unused)

### ISSUE THREAD

**Issue by JensErat** [vmware-tanzu/velero#3691]
**Describe the problem/challenge you have**

restic prune performs some quite heavy operations, and often requires fetching and pushing entire blobs just to remove some bytes in the default configuration (very aggressive prune strategy). This is an issue when your backup target is rather remote, and especially bad if bandwidth to the backup target is limited.

**Describe the solution you'd like**

Restic 0.12 brought some very helpful ways to configure prune: `max-repack-size` and `max-unused`. Especially `max-repack-size` sets an limit per prune run how many bytes may be repacked, which is also an upper limit on how many bytes to transfer. In practice, even a tiny percentage of the backup size.

An example on the effects: I'm running a limit of 100MB repack size per hourly backup on a client computer with about 300GB of partially frequently changing data, and have to fetch and reupload just a few MB with each prune, while at the same time keeping unused space below 1GB.

It would be great if velero would allow to set this limit. Especially with 24/7 servers, a flattened-out delete operation will help at keeping backup time low and preserve bandwith (and potentially object storage transfer cost). I can imagine a solution similar to `--default-restic-prune-frequency`, or replace it with a generic `--restic-prune-args` option (not exactly sure how that one might look like, though).

**Anything else you would like to add:**

#3062 also affects restic prune configuration, where the frequency parameter seems broken

**Environment:**

- Velero version (use `velero version`): 1.6+, having restic 0.12

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by eleanor-millman** [comment]
Closing because we are no longer doing restic-specific improvements.

**Comment by JensErat** [comment]
Is restic integration considered deprecated? I don't find any information on this, but on the other hand the roadmap document still contains "restic improvements" for the future.

**Comment by eleanor-millman** [comment]
It is not depreciated, but we are considering replacing restic with Kopia in the future. So we don't want to do any work that might get ripped out in a few months. And forgive me, the 1.7 roadmap needs to be updated, especially the long-term roadmap items.  @dsu-igeek might have more to add on this topic as well.

**Comment by JensErat** [comment]
Thank you, this is great news. My concern was mostly about "will I have to rethink backup and replace Velero at some time", and don't care about the actual backup engine too much.

I'll stay tuned and check out Kopia!

**Comment by eleanor-millman** [comment]
@JensErat Yes, we certainly don't want to break people who use restic! So I believe the switch to Kopia should be quite painless (if we decide to proceed). And the great thing is that Kopia would also bring additional cloud repositories and incremental backup, which is awesome.
