### ISSUE TITLE
Velero: scheduler showing incorrect information

### ISSUE THREAD

**Issue by crdemon09** [vmware-tanzu/velero#3694]
**What steps did you take and what happened:**
velero schedule describe
Name:         test
Namespace:    default
Phase:  Enabled
Schedule:  1 15 * * 3
Backup Template:
  Namespaces:
    Included:  *
    Excluded:  <none>
  Resources:
    Included:        *
    Excluded:        <none>
    Cluster-scoped:  auto
  Label selector:  test
  Storage Location:
  Snapshot PVs:  auto
  TTL:  720h0m0s
  Hooks:  <none>
Last Backup:  2021-04-19 07:38:05 +0000 UTC

**Last Backup** filed should be empty - since no backup was done yet by a scheduler

**Environment:**

- Velero version (use `1.5.2`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Velero log** creating a backup:
time="2021-05-16T06:40:23Z" level=info msg="Creating schedule check" controller=schedule logSource="pkg/controller/schedule_controller.go:105"
time="2021-05-16T06:40:23Z" level=info msg="Schedule is due, submitting Backup" controller=schedule logSource="pkg/controller/schedule_controller.go:260" nextRunTime="0001-01-01 00:30:00 +0000 UTC" schedule=default/check
time="2021-05-16T06:40:23Z" level=info msg="Setting up backup log" backup=default/check-20210516064023 controller=backup logSource="pkg/controller/backup_controller.go:472"
time="2021-05-16T06:40:23Z" level=info msg="Setting up backup temp file" backup=default/check-20210516064023 logSource="pkg/controller/backup_controller.go:494"
time="2021-05-16T06:40:23Z" level=info msg="Setting up plugin manager" backup=default/check-20210516064023 logSource="pkg/controller/backup_controller.go:501"
time="2021-05-16T06:40:23Z" level=info msg="Getting backup item actions" backup=default/check-20210516064023 logSource="pkg/controller/backup_controller.go:505"
time="2021-05-16T06:40:23Z" level=info msg="Setting up backup store" backup=default/check-20210516064023 logSource="pkg/controller/backup_controller.go:511"
time="2021-05-16T06:40:23Z" level=info msg="Writing backup version file" backup=default/check-20210516064023 logSource="pkg/backup/backup.go:213"
time="2021-05-16T06:40:23Z" level=info msg="Including namespaces: default" backup=default/check-20210516064023 logSource="pkg/backup/backup.go:219"
time="2021-05-16T06:40:23Z" level=info msg="Excluding namespaces: <none>" backup=default/check-20210516064023 logSource="pkg/backup/backup.go:220"
time="2021-05-16T06:40:23Z" level=info msg="Including resources: *" backup=default/check-20210516064023 logSource="pkg/backup/backup.go:223"
time="2021-05-16T06:40:23Z" level=info msg="Excluding resources: <none>" backup=default/check-20210516064023 logSource="pkg/backup/backup.go:224"

root@velero-67654f47c5-hfnf9:/# **./velero schedule describe check**
Name:         check
Namespace:    default
Labels:       <none>
Annotations:  <none>
Phase:  Enabled
Schedule:  */30 * * * *
Backup Template:
  Namespaces:
    Included:  default
    Excluded:  <none>
  Resources:
    Included:        *
    Excluded:        <none>
    Cluster-scoped:  auto
  Label selector:  <none>
  Storage Location:
  Snapshot PVs:  auto
  TTL:  48h0m0s
  Hooks:  <none>
Last Backup:  2021-05-16 06:40:23 +0000 UTC

**Comment by nrb** [comment]
@crdemon09 Please provide log information requested in the issue template.

**Comment by crdemon09** [comment]
@nrb - log has been added.
Let me know if any other details are needed.

**Comment by Davidsod** [comment]
Hi @nrb we're facing the same issue, is there any update on the above?
