### ISSUE TITLE
Design doc for Carvel YTT

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#3709]
Create a design doc for Carvel YTT

Epic: #3493 design work
---
## Knowledge base

Project: [Carvel - Home](https://carvel.dev/)

Good resources:
- [Introducing k14s (Kubernetes Tools): Simple and Composable Tools for Application Deployment](https://tanzu.vmware.com/content/blog/introducing-k14s-kubernetes-tools-simple-and-composable-tools-for-application-deployment)
- [A new take on YAML templating for configuration files – IBM Developer](https://developer.ibm.com/blogs/yaml-templating-tool-to-simplify-complex-configuration-management/)
- [Deploy Kubernetes Applications with the Carvel Suite | Dustin Specker](https://dustinspecker.com/posts/deploy-kubernetes-applications-carvel-suite/)
- [ Introduction to Carvel | Rawkode Live - YouTube](https://www.youtube.com/watch?v=LBCmMTofNxw) 
- [ TGI Kubernetes 079: YTT and Kapp - YouTube](https://www.youtube.com/watch?v=CSglwNTQiYg&t=515s) 
- [Getting Started with Carvel (formerly k14s) | VMware Tanzu Developer Center](https://tanzu.vmware.com/developer/workshops/lab-getting-started-with-carvel/) 

Secondary:
- [CNCF Live Webinar: How to Manage Kubernetes Application Lifecycle Using Carvel | Cloud Native Computing Foundation](https://www.cncf.io/webinars/cncf-live-webinar-how-to-manage-kubernetes-application-lifecycle-using-carvel/) 

## Goal
- Note: goal is to change things in one place and have it used by both carvel tooling and also Helm. 
    - Currently, we update Go code, helm, and then carvel.
    - Maybe have a sed script.
    - 
## Notes on k8s pull policy

- Do we want to have a flag to set the k8s pull policy? Maybe not bc it's just an issue for developers? See what Carvel does. It'd be preferable to do it with Carvel than to modify the [[Velero]] install to add that. Carvel probably has a better way to handle how to configure the whole cluster.
    - This is relevant to get around the issue of "latest" caching when the pull policy is not set to "always". This pertains to caching Velero and plugin images.
    - [[k8s cmds]] [configuration best practices](https://kubernetes.io/docs/concepts/configuration/overview/#container-images)
    - Also: careful about exposing every Velero option with Carvel/yaml so it doesn't become a mess.
    - Reference: [Configuration Best Practices | Kubernetes](https://kubernetes.io/docs/concepts/configuration/overview/#container-images)

**Comment by reasonerjt** [comment]
Closing it b/c it not relevant to velero OSS.
