### ISSUE TITLE
`velero describe backup --details` causes error due to DownloadRequests with the same name

### ISSUE THREAD

**Issue by VincenzoDo** [vmware-tanzu/velero#3716]
**What steps did you take and what happened:**
When trying to retrieve snapshots IDs via 

`velero describe backup mybackup --details`

randomly getting the following error:

`Velero-Native Snapshots:  <error getting snapshot info: downloadrequests.velero.io "mybackup-timestamp" already exists>`

**What did you expect to happen:**
The command should always succeed and not just once every X executions.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Using GCP plugin. If we use the 1.5.4 velero cli the command always succeeds.

We can provide additional details on request.

**Environment:**

- Velero version (use `velero version`): 1.6.0
- Velero features (use `velero client config get features`): -
- Kubernetes version (use `kubectl version`): 1.18.16
- Kubernetes installer & version: GCP

**Comment by zubron** [comment]
Hi @VincenzoDo - sorry you're having problems with this. Could you please provider the velero deployment logs using `kubectl logs deployment/velero -n velero`? We'll need those to diagnose the issue. Thanks!

**Comment by VincenzoDo** [comment]
Hello @zubron, here you go: 
[velero-logs.txt](https://github.com/vmware-tanzu/velero/files/6351103/velero-logs.txt)

**Comment by zubron** [comment]
Hi @VincenzoDo - thanks for sending the logs. I've discovered the source of the issue. When showing detailed backup information we call `downloadrequest.Stream` twice which results in two DownloadRequest objects being created. We generate the name of the DownloadRequest object based on the [name of the backup and a timestamp](https://github.com/vmware-tanzu/velero/blob/main/pkg/cmd/util/downloadrequest/downloadrequest.go#L44-L49) of when the request is being made, where the timestamp has second granularity.  If they are made in very quick succession (within the same second), the names will be duplicated and so there will an error as it already exists.

**Comment by zubron** [comment]
The [backup describer code](https://github.com/vmware-tanzu/velero/blob/main/pkg/cmd/util/output/backup_describer.go#L286-L301) should probably try to reuse the same stream result if it can.

**Comment by carlisia** [comment]
Confirming I'm seeing this too when running (on Kind, have not seen it in AWS). It happens intermittently for me.

**Comment by zubron** [comment]
This has been fixed in #4034.
