### ISSUE TITLE
Azure Plugin - Snapshot Storage Type configurable

### ISSUE THREAD

**Issue by pavb74** [vmware-tanzu/velero#3721]
**Describe the problem/challenge you have**
Currently when you performed Azure disk snapshot using Velero:
- Zone Redundant Storage is automatically used for incremental snapshots
- Local Redundant Storage for full snapshots

There is no way to configure this parameter.
From a security point of view, it would be better to have also full snapshots in ZRS mode. 
This feature is possible from the Azure Portal

**Describe the solution you'd like**
Add a configuration parameter to the VolumeSnapshotLocations to be able to specify the type of storage

**Environment:**

- Velero version : 1.5.4
- Azure Velero plugin version: 1.1.1
- Kubernetes version: 1.19.7
- Cloud provider or hardware configuration: Azure AKS
- OS : Ubuntu 18.04 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by chreichert** [comment]
/reopen
Why has this been closed? I think it is essential to be able to have the Snapshots stored in ZRS mode!
