### ISSUE TITLE
Velero documentation https://velero.io/docs/v1.6/contributions/minio/ mentions wrong aws plugin versions

### ISSUE THREAD

**Issue by bo0ts** [vmware-tanzu/velero#3736]
**What steps did you take and what happened:**

`https://velero.io/docs/v1.6/contributions/minio/` gives the following command to install velero for minio:

```
velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.0.0 \
    --bucket velero \
    --secret-file ./credentials-velero \
    --use-volume-snapshots=false \
    --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://minio.velero.svc:9000
```

**What did you expect to happen:**

`velero/velero-plugin-for-aws:v1.0.0` is not the correct image for velero 1.6. It should be `v1.2.0` or whatever version is appropriate for the given velero version of the documentation.

**Comment by ashish-amarnath** [comment]
@bo0ts Thanks for pointing that out. Would you be interested in contributing a doc fix for this?
