### ISSUE TITLE
Velero configured through Helmv2- NoCredentialProviders: no valid providers in chain

### ISSUE THREAD

**Issue by rahulmajumder86** [vmware-tanzu/velero#3741]
**What steps did you take and what happened:**

I have a legacy EKS cluster where Velero was configured through Helmv2 using "vmware-tanzu/velero ". It worked for few days and later somehow it stopped working. It just came to my notice on last week.

Error: kubectl logs deploy/velero -n velero

**An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors**

The pod is in **CrashLoopBackOff** state.

The YAML file was applied through the Helm command by one of my teammate:
helm repo add vmware-tanzu https://vmware-tanzu.github.io/helm-charts
helm install velero --namespace velero vmware-tanzu/velero -f values.yaml

**What did you expect to happen:**
- Velero pod should be up & running without any error.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
https://gist.github.com/rahulmajumder86/e1fb811feb82556afd768c8413bfdb72

- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
N/A as pod is not starting.
- `velero backup logs <backupname>`
N/A as pod is not starting.
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
N/A
- `velero restore logs <restorename>`
N/A 

**Anything else you would like to add:**
- # Details of the container image to use in the Velero deployment & daemonset :
image:
  repository: velero/velero
  tag: v1.3.1
  pullPolicy: IfNotPresent

# Init containers to add to the Velero deployment's pod spec.: 
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.0.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

**Environment:**

- Velero version (use `velero version`): 
velero version
Client:
	Version: v1.5.3
	Git commit: -
Server:
	Version: 
- Velero features (use `velero client config get features`):  features: <NOT SET>
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-eks-31566f", GitCommit:"31566f851673e809d4d667b7235ed87587d37722", GitTreeState:"clean", BuildDate:"2020-10-20T23:25:14Z", GoVersion:"go1.12.17", Compiler:"gc", Pla

- Cloud provider or hardware configuration: AWS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by rahulmajumder86** [comment]
Please let me know if you need more info. I have tried to recreate the secret type-token but there was no luck.

**Comment by ashish-amarnath** [comment]
@rahulmajumder86 it looks like the issue is being caused by either missing or malformed credentials. Could you please the steps from our troubleshooting guide on our website to troubleshoot this further? Here is a link to that troubleshooting guide https://velero.io/docs/v1.6/troubleshooting/#is-velero-using-the-correct-cloud-credentials
