### ISSUE TITLE
Requirements for the Carvel integration

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/velero#3742]
Epic: #3493 design work
---

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nrb** [comment]
Configuration data from a distribution like TKG should flow into Velero deployments. For example, if deploying TKG on AWS, the Velero variables in ytt should read from that same information.

**Comment by nrb** [comment]
Make sure that generating a Helm Chart is possible from the same base manifests that Carvel will consume; combining helm and Carvel generation in v1.7.0 is a non-goal

**Comment by nrb** [comment]
Being about to use the Carvel info as a source of truth for `velero install`, so that our `install` command is a wrapper around the toolset.

**Comment by carlisia** [comment]
Closing this as it has been done in the TCE repo.
