### ISSUE TITLE
No volume ID returned by volume snapshotter for persistent volume

### ISSUE THREAD

**Issue by matusdav** [vmware-tanzu/velero#3749]
**What steps did you take and what happened:**
velero backup create velerotest  --selector backup=true

The volume snapshot doesn't work. The backup is complete.

**What did you expect to happen:**

The azur snapshot is empty. 

**The output of the following commands will help us better understand what's going on**:

- `kubectl logs deployment/velero -n velero`
time="2021-04-29T11:54:39Z" level=info msg="Executing custom action" backup=velero/velerotest logSource="pkg/backup/item_backupper.go:327" name=task-pv-claim namespace=default resource=persistentvolumeclaims
time="2021-04-29T11:54:39Z" level=info msg="Executing PVCAction" backup=velero/velerotest cmd=/velero logSource="pkg/backup/backup_pv_action.go:49" pluginName=velero
time="2021-04-29T11:54:39Z" level=info msg="Backing up item" backup=velero/velerotest logSource="pkg/backup/item_backupper.go:121" name=task-pv-volume namespace= resource=persistentvolumes
time="2021-04-29T11:54:39Z" level=info msg="Executing takePVSnapshot" backup=velero/velerotest logSource="pkg/backup/item_backupper.go:405" name=task-pv-volume namespace= resource=persistentvolumes
time="2021-04-29T11:54:39Z" level=info msg="label \"topology.kubernetes.io/zone\" is not present on PersistentVolume, checking deprecated label..." backup=velero/velerotest logSource="pkg/backup/item_backupper.go:432" name=task-pv-volume namespace= persistentVolume=task-pv-volume resource=persistentvolumes
time="2021-04-29T11:54:39Z" level=info msg="label \"failure-domain.beta.kubernetes.io/zone\" is not present on PersistentVolume" backup=velero/velerotest logSource="pkg/backup/item_backupper.go:435" name=task-pv-volume namespace= persistentVolume=task-pv-volume resource=persistentvolumes
time="2021-04-29T11:54:39Z" level=info msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/velerotest logSource="pkg/backup/item_backupper.go:458" name=task-pv-volume namespace= persistentVolume=task-pv-volume resource=persistentvolumes volumeSnapshotLocation=default
time="2021-04-29T11:54:39Z" level=info msg="Persistent volume is not a supported volume type for snapshots, skipping." backup=velero/velerotest logSource="pkg/backup/item_backupper.go:469" name=task-pv-volume namespace= persistentVolume=task-pv-volume resource=persistentvolumes
time="2021-04-29T11:54:39Z" level=info msg="Backed up 5 items out of an estimated total of 5 (estimate will change throughout the backup)" backup=velero/velerotest logSource="pkg/backup/backup.go:394" name=ubuntu-back-69f87f745-c27jw namespace=default progress= resource=pods
time="2021-04-29T11:54:39Z" level=info msg="Backed up a total of 5 items" backup=velero/velerotest logSource="pkg/backup/backup.go:419" progress=
time="2021-04-29T11:54:39Z" level=info msg="Setting up backup store to persist the backup" backup=velero/velerotest logSource="pkg/controller/backup_controller.go:654"
time="2021-04-29T11:54:40Z" level=info msg="Backup completed" backup=velero/velerotest controller=backup logSource="pkg/controller/backup_controller.go:664"

**Anything else you would like to add:**
My pv doesn't detect ... i think. I work with the label/selector command.

**Environment:**
- Velero version : Version: v1.6.0
- Velero features (use `velero client config get features`):  features: <NOT SET>
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"4d62230f10af41cec2851b5b113874f6d2098297", GitTreeState:"clean", BuildDate:"2021-03-22T23:01:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version: AKS
- 
- Cloud provider : AZURE

**Comment by matusdav** [comment]
velero backup describe velerotest
Name:         velerotest
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.18.14
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18

Phase:  Completed

Errors:    0
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  backup=true

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-04-29 13:54:37 +0200 CEST
Completed:  2021-04-29 13:54:39 +0200 CEST

Expiration:  2021-05-29 13:54:37 +0200 CEST

Total items to be backed up:  5
Items backed up:              5

Velero-Native Snapshots: <none included>

**Comment by matusdav** [comment]
velero backup logs velerotest 

empty

**Comment by dsu-igeek** [comment]
Which version of the Azure plug-in is installed?

**Comment by gauravpatel2016** [comment]
We have similar issue with AWS

**Comment by k1ng440** [comment]
same issue with GKE
