### ISSUE TITLE
[Upload Progress Monitoring Epic #3533] Defer upload of velero-backup.json until uploads have completed

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#3756]
The upload progress monitoring design (Epic #3533) uses the presence of the velero-backup.json object in the object store as a signal that all uploads have completed or failed and the backup is in a final state.  Move the creation of the velero-backup.json to happen when the backup resource phase is set to a terminal state.  Refer to upload-progress.md for additional details.

**Comment by reasonerjt** [comment]
As #4467 still have some unresolved comments, and we wanna avoid making big change to backup/restore workflow after v1.9 FC

Moving all the related issues to milestone v1.10
