### ISSUE TITLE
velero aws plugin unable to list all the backups from the s3 store

### ISSUE THREAD

**Issue by alaypatel07** [vmware-tanzu/velero#3771]
**What steps did you take and what happened:**

1. A non-aws s3 server was used as BSL
2. The velero-plugin-for-aws uses `ListObjectsV2Pages` to check for all the backups in the remote s3 store. https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/fc739f74690e62b59b24e67fb89ee1739d5f6c34/velero-plugin-for-aws/object_store.go#L354
3. The debug logs for velero was turned on and it returned it returns 555 as the backup count

```
[alpatel@alpatel postgres-operator]$ oc logs -f velero-6dc4479d7d-r2vtc | grep backupCount
time="2021-04-28T23:24:34Z" level=debug msg="Got backups from backup store" backupCount=555 
```

4. However when I use the `s3cmd` cli, it returned  788 as the backup count.
    ```
    $ s3cmd -c ~/s3-bucket.cfg ls s3://migration/velero/backups/ | wc -l
       788
    ```
5. We drilled down further to debug the problem the following was the root cause:
    1. Internally the `ListObjectsV2Pages` calls the ListObjectsV2 S3 api https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html
    2. However the server was returning with ListObjects (version 1) response. https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html
    3. In both ListObjectsV2 and ListObjects the `isTruncated` field on the response indicates that there are more than 1 pages of response
    4. The ListObjectsV2Pages decides whether there are more pages by looking at the `nextContinuousToken` field in the response https://github.com/aws/aws-sdk-go/blob/b9d2b59a417d8332de5d8a598976dc27416a4443/aws/request/request_pagination.go#L160. 
    5. However, in this case, the server was returning ListObjects response, which specifies `marker` field as the token for next page.
    6. The above-explained mismatch resulted in velero processing only the first page of the response, while skipping the rest ~230ish backups
    7. when s3cmd cli was ran with --debug flag on, it used the pagination using the V1 fields (i.e. `marker`) which is why it was giving the right results with the same server/bucket

**What did you expect to happen:**
Expected velero to be able to list all the backups given that s3cmd cli is able to list it

**Anything else you would like to add:**
There is an issue filed against the aws-go-sdk [here](https://github.com/aws/aws-sdk-go/issues/3892) to return an explicit Error type on mismatched results in case of the V2 API, however, until that issue is closed, this mismatch can be handled at the plugin level in this way https://github.com/konveyor/velero-plugin-for-aws/pull/12 

**Environment:**

- Velero version (use `velero version`):  1.5
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by jenting** [comment]
IIRC, the GCE does not support `ListObjectsV2`.
- https://issuetracker.google.com/issues/155109631
- https://stackoverflow.com/questions/45638871/is-the-listobjectsv2-api-call-implemented-in-google-cloud-storage
- https://cloud.google.com/storage/docs/migrating#migration-simple

**Comment by alaypatel07** [comment]
Thanks, @jenting from the issue tracker link it looks like ListObjectV2 will return `NotImplemented` error so it is better in the sense it will not provide 1/2 baked data, but will explicitly error out. 

That said, it looks like the backups_sync_controller will still break with that error.

**Comment by sseago** [comment]
This issue shouldn't be closed as stale.
