### ISSUE TITLE
Metrics Not Reporting Correctly

### ISSUE THREAD

**Issue by reddiablo85** [vmware-tanzu/velero#3797]
Version: 1.5.1 

Issue: Exposed Metrics do not match real state

Logs: Here is output from velero:8085/metrics
[root@test-os-67466d8677-mw8df /]$$$ curl 172.16.4.21:8085/metrics
$$$ HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
$$$ TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 1.1844e-05
go_gc_duration_seconds{quantile="0.25"} 2.2196e-05
go_gc_duration_seconds{quantile="0.5"} 2.698e-05
go_gc_duration_seconds{quantile="0.75"} 3.3635e-05
go_gc_duration_seconds{quantile="1"} 0.001442233
go_gc_duration_seconds_sum 0.036869264
go_gc_duration_seconds_count 1049
$$$ HELP go_goroutines Number of goroutines that currently exist.
$$$ TYPE go_goroutines gauge
go_goroutines 173
$$$ HELP go_info Information about the Go environment.
$$$ TYPE go_info gauge
go_info{version="go1.14.9"} 1
$$$ HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
$$$ TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 1.4001856e+07
$$$ HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
$$$ TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 5.557592704e+09
$$$ HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
$$$ TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 2.364714e+06
$$$ HELP go_memstats_frees_total Total number of frees.
$$$ TYPE go_memstats_frees_total counter
go_memstats_frees_total 3.4763869e+07
$$$ HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
$$$ TYPE go_memstats_gc_cpu_fraction gauge
go_memstats_gc_cpu_fraction 9.698141381511024e-06
$$$ HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
$$$ TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 5.996816e+06
$$$ HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
$$$ TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 1.4001856e+07
$$$ HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
$$$ TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 1.13074176e+08
$$$ HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
$$$ TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 1.9144704e+07
$$$ HELP go_memstats_heap_objects Number of allocated objects.
$$$ TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 75210
$$$ HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
$$$ TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 1.10010368e+08
$$$ HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
$$$ TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 1.3221888e+08
$$$ HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
$$$ TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.6209003072429793e+09
$$$ HELP go_memstats_lookups_total Total number of pointer lookups.
$$$ TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
$$$ HELP go_memstats_mallocs_total Total number of mallocs.
$$$ TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 3.4839079e+07
$$$ HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
$$$ TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 13888
$$$ HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
$$$ TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
$$$ HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
$$$ TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 290088
$$$ HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
$$$ TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 573440
$$$ HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
$$$ TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 1.9120384e+07
$$$ HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
$$$ TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 1.618638e+06
$$$ HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
$$$ TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 1.998848e+06
$$$ HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
$$$ TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 1.998848e+06
$$$ HELP go_memstats_sys_bytes Number of bytes obtained from system.
$$$ TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 1.4478772e+08
$$$ HELP go_threads Number of OS threads created.
$$$ TYPE go_threads gauge
go_threads 14
$$$ HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
$$$ TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 107.56
$$$ HELP process_max_fds Maximum number of open file descriptors.
$$$ TYPE process_max_fds gauge
process_max_fds 1.048576e+06
$$$ HELP process_open_fds Number of open file descriptors.
$$$ TYPE process_open_fds gauge
process_open_fds 13
$$$ HELP process_resident_memory_bytes Resident memory size in bytes.
$$$ TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.19414784e+08
$$$ HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
$$$ TYPE process_start_time_seconds gauge
process_start_time_seconds 1.6208027785e+09
$$$ HELP process_virtual_memory_bytes Virtual memory size in bytes.
$$$ TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 8.40105984e+08
$$$ HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
$$$ TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes -1
$$$ HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
$$$ TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
$$$ HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
$$$ TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 69
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
$$$ HELP velero_backup_attempt_total Total number of attempted backups
$$$ TYPE velero_backup_attempt_total counter
velero_backup_attempt_total{schedule=""} 1
velero_backup_attempt_total{schedule="velero-daily"} 2
velero_backup_attempt_total{schedule="velero-hourly"} 5
$$$ HELP velero_backup_deletion_attempt_total Total number of attempted backup deletions
$$$ TYPE velero_backup_deletion_attempt_total counter
velero_backup_deletion_attempt_total{schedule=""} 0
velero_backup_deletion_attempt_total{schedule="velero-daily"} 1
velero_backup_deletion_attempt_total{schedule="velero-hourly"} 4
$$$ HELP velero_backup_deletion_failure_total Total number of failed backup deletions
$$$ TYPE velero_backup_deletion_failure_total counter
velero_backup_deletion_failure_total{schedule=""} 0
velero_backup_deletion_failure_total{schedule="velero-daily"} 0
velero_backup_deletion_failure_total{schedule="velero-hourly"} 0
$$$ HELP velero_backup_deletion_success_total Total number of successful backup deletions
$$$ TYPE velero_backup_deletion_success_total counter
velero_backup_deletion_success_total{schedule=""} 0
velero_backup_deletion_success_total{schedule="velero-daily"} 1
velero_backup_deletion_success_total{schedule="velero-hourly"} 4
$$$ HELP velero_backup_duration_seconds Time taken to complete backup, in seconds
$$$ TYPE velero_backup_duration_seconds histogram
velero_backup_duration_seconds_bucket{schedule="velero-daily",le="60"} 0
velero_backup_duration_seconds_bucket{schedule="velero-daily",le="300"} 0
velero_backup_duration_seconds_bucket{schedule="velero-daily",le="600"} 0
velero_backup_duration_seconds_bucket{schedule="velero-daily",le="900"} 1
velero_backup_duration_seconds_bucket{schedule="velero-daily",le="1800"} 1
velero_backup_duration_seconds_bucket{schedule="velero-daily",le="3600"} 1
velero_backup_duration_seconds_bucket{schedule="velero-daily",le="7200"} 1
velero_backup_duration_seconds_bucket{schedule="velero-daily",le="10800"} 1
velero_backup_duration_seconds_bucket{schedule="velero-daily",le="14400"} 1
velero_backup_duration_seconds_bucket{schedule="velero-daily",le="+Inf"} 1
velero_backup_duration_seconds_sum{schedule="velero-daily"} 698
velero_backup_duration_seconds_count{schedule="velero-daily"} 1
velero_backup_duration_seconds_bucket{schedule="velero-hourly",le="60"} 0
velero_backup_duration_seconds_bucket{schedule="velero-hourly",le="300"} 0
velero_backup_duration_seconds_bucket{schedule="velero-hourly",le="600"} 0
velero_backup_duration_seconds_bucket{schedule="velero-hourly",le="900"} 1
velero_backup_duration_seconds_bucket{schedule="velero-hourly",le="1800"} 2
velero_backup_duration_seconds_bucket{schedule="velero-hourly",le="3600"} 2
velero_backup_duration_seconds_bucket{schedule="velero-hourly",le="7200"} 2
velero_backup_duration_seconds_bucket{schedule="velero-hourly",le="10800"} 2
velero_backup_duration_seconds_bucket{schedule="velero-hourly",le="14400"} 2
velero_backup_duration_seconds_bucket{schedule="velero-hourly",le="+Inf"} 2
velero_backup_duration_seconds_sum{schedule="velero-hourly"} 1950
velero_backup_duration_seconds_count{schedule="velero-hourly"} 2
$$$ HELP velero_backup_failure_total Total number of failed backups
$$$ TYPE velero_backup_failure_total counter
velero_backup_failure_total{schedule=""} 1
velero_backup_failure_total{schedule="velero-daily"} 1
velero_backup_failure_total{schedule="velero-hourly"} 3
$$$ HELP velero_backup_last_successful_timestamp Last time a backup ran successfully, Unix timestamp in seconds
$$$ TYPE velero_backup_last_successful_timestamp gauge
velero_backup_last_successful_timestamp{schedule=""} 1.620736694e+09
velero_backup_last_successful_timestamp{schedule="velero-daily"} 1.620864742e+09
velero_backup_last_successful_timestamp{schedule="velero-hourly"} 1.620897288e+09
$$$ HELP velero_backup_partial_failure_total Total number of partially failed backups
$$$ TYPE velero_backup_partial_failure_total counter
velero_backup_partial_failure_total{schedule=""} 0
velero_backup_partial_failure_total{schedule="velero-daily"} 0
velero_backup_partial_failure_total{schedule="velero-hourly"} 0
$$$ HELP velero_backup_success_total Total number of successful backups
$$$ TYPE velero_backup_success_total counter
velero_backup_success_total{schedule=""} 0
velero_backup_success_total{schedule="velero-daily"} 1
velero_backup_success_total{schedule="velero-hourly"} 2
$$$ HELP velero_backup_tarball_size_bytes Size, in bytes, of a backup
$$$ TYPE velero_backup_tarball_size_bytes gauge
velero_backup_tarball_size_bytes{schedule="velero-daily"} 8.998132e+06
velero_backup_tarball_size_bytes{schedule="velero-hourly"} 9.187545e+06
$$$ HELP velero_backup_total Current number of existent backups
$$$ TYPE velero_backup_total gauge
velero_backup_total 52
$$$ HELP velero_backup_validation_failure_total Total number of validation failed backups
$$$ TYPE velero_backup_validation_failure_total counter
velero_backup_validation_failure_total{schedule=""} 0
velero_backup_validation_failure_total{schedule="velero-daily"} 0
velero_backup_validation_failure_total{schedule="velero-hourly"} 0
$$$ HELP velero_restore_attempt_total Total number of attempted restores
$$$ TYPE velero_restore_attempt_total counter
velero_restore_attempt_total{schedule=""} 0
velero_restore_attempt_total{schedule="velero-daily"} 0
velero_restore_attempt_total{schedule="velero-hourly"} 0
$$$ HELP velero_restore_failed_total Total number of failed restores
$$$ TYPE velero_restore_failed_total counter
velero_restore_failed_total{schedule=""} 0
velero_restore_failed_total{schedule="velero-daily"} 0
velero_restore_failed_total{schedule="velero-hourly"} 0
$$$ HELP velero_restore_partial_failure_total Total number of partially failed restores
$$$ TYPE velero_restore_partial_failure_total counter
velero_restore_partial_failure_total{schedule=""} 0
velero_restore_partial_failure_total{schedule="velero-daily"} 0
velero_restore_partial_failure_total{schedule="velero-hourly"} 0
$$$ HELP velero_restore_success_total Total number of successful restores
$$$ TYPE velero_restore_success_total counter
velero_restore_success_total{schedule=""} 0
velero_restore_success_total{schedule="velero-daily"} 0
velero_restore_success_total{schedule="velero-hourly"} 0
$$$ HELP velero_restore_total Current number of existent restores
$$$ TYPE velero_restore_total gauge
velero_restore_total 0
$$$ HELP velero_restore_validation_failed_total Total number of failed restores failing validations
$$$ TYPE velero_restore_validation_failed_total counter
velero_restore_validation_failed_total{schedule=""} 0
velero_restore_validation_failed_total{schedule="velero-daily"} 0
velero_restore_validation_failed_total{schedule="velero-hourly"} 0
$$$ HELP velero_volume_snapshot_attempt_total Total number of attempted volume snapshots
$$$ TYPE velero_volume_snapshot_attempt_total counter
velero_volume_snapshot_attempt_total{schedule=""} 0
velero_volume_snapshot_attempt_total{schedule="velero-daily"} 0
velero_volume_snapshot_attempt_total{schedule="velero-hourly"} 0
$$$ HELP velero_volume_snapshot_failure_total Total number of failed volume snapshots
$$$ TYPE velero_volume_snapshot_failure_total counter
velero_volume_snapshot_failure_total{schedule=""} 0
velero_volume_snapshot_failure_total{schedule="velero-daily"} 0
velero_volume_snapshot_failure_total{schedule="velero-hourly"} 0
$$$ HELP velero_volume_snapshot_success_total Total number of successful volume snapshots
$$$ TYPE velero_volume_snapshot_success_total counter
velero_volume_snapshot_success_total{schedule=""} 0
velero_volume_snapshot_success_total{schedule="velero-daily"} 0
velero_volume_snapshot_success_total{schedule="velero-hourly"} 0
[root@test-os-67466d8677-mw8df /]$$$ 

and here is output from "velero get backups" on same cluster:
[root@gdcslxrcpadm01t ~]# velero get backups
NAME                           STATUS            ERRORS   WARNINGS   CREATED                          EXPIRES   STORAGE LOCATION   SELECTOR
test02                         Completed         0        0          2021-05-11 11:32:09 +0200 CEST   27d       default            <none>
test03                         PartiallyFailed   1        0          2021-05-11 14:16:49 +0200 CEST   28d       default            <none>
test04                         Completed         0        0          2021-05-11 14:28:01 +0200 CEST   28d       default            <none>
test05                         Deleting          0        0          2021-05-12 08:54:25 +0200 CEST   28d       default            <none>
test06                         Failed            0        0          2021-05-12 09:00:24 +0200 CEST   28d       default            <none>
velero-daily-20210513000044    Completed         0        0          2021-05-13 02:00:44 +0200 CEST   29d       default            <none>
velero-daily-20210512065944    Failed            0        0          2021-05-12 08:59:46 +0200 CEST   28d       default            <none>
velero-daily-20210511200022    PartiallyFailed   2        0          2021-05-11 22:00:22 +0200 CEST   28d       default            <none>
velero-daily-20210511130022    Completed         0        0          2021-05-11 15:00:22 +0200 CEST   28d       default            <none>
velero-daily-20210511085926    InProgress        0        0          2021-05-11 10:59:28 +0200 CEST   27d       default            <none>
velero-daily-20210511000007    Completed         0        0          2021-05-11 02:00:07 +0200 CEST   27d       default            <none>
velero-daily-20210510000007    Completed         0        0          2021-05-10 02:00:07 +0200 CEST   26d       default            <none>
velero-daily-20210509000007    Completed         0        0          2021-05-09 02:00:07 +0200 CEST   25d       default            <none>
velero-daily-20210508000006    Completed         0        0          2021-05-08 02:00:06 +0200 CEST   24d       default            <none>
velero-daily-20210507000006    Completed         0        0          2021-05-07 02:00:06 +0200 CEST   23d       default            <none>
velero-daily-20210506000006    Completed         0        0          2021-05-06 02:00:06 +0200 CEST   22d       default            <none>
velero-daily-20210505000006    Completed         0        0          2021-05-05 02:00:06 +0200 CEST   21d       default            <none>
velero-daily-20210504000005    Completed         0        0          2021-05-04 02:00:05 +0200 CEST   20d       default            <none>
velero-daily-20210503000005    Completed         0        0          2021-05-03 02:00:05 +0200 CEST   19d       default            <none>
velero-daily-20210430000009    Completed         0        0          2021-04-30 02:00:09 +0200 CEST   16d       default            <none>
velero-daily-20210429000009    Completed         0        0          2021-04-29 02:00:09 +0200 CEST   15d       default            <none>
velero-daily-20210428000009    Completed         0        0          2021-04-28 02:00:09 +0200 CEST   14d       default            <none>
velero-daily-20210427000008    Completed         0        0          2021-04-27 02:00:08 +0200 CEST   13d       default            <none>
velero-daily-20210426000008    Completed         0        1          2021-04-26 02:00:08 +0200 CEST   12d       default            <none>
velero-daily-20210425000008    Completed         0        1          2021-04-25 02:00:08 +0200 CEST   11d       default            <none>
velero-daily-20210424000008    Completed         0        0          2021-04-24 02:00:08 +0200 CEST   10d       default            <none>
velero-daily-20210423000008    Completed         0        0          2021-04-23 02:00:08 +0200 CEST   9d        default            <none>
velero-daily-20210422000007    Completed         0        0          2021-04-22 02:00:07 +0200 CEST   8d        default            <none>
velero-daily-20210421000007    Completed         0        0          2021-04-21 02:00:07 +0200 CEST   7d        default            <none>
velero-daily-20210420000007    Completed         0        0          2021-04-20 02:00:07 +0200 CEST   6d        default            <none>
velero-daily-20210419000007    Completed         0        0          2021-04-19 02:00:07 +0200 CEST   5d        default            <none>
velero-daily-20210418000007    Completed         0        0          2021-04-18 02:00:07 +0200 CEST   4d        default            <none>
velero-daily-20210416000006    Completed         0        0          2021-04-16 02:00:06 +0200 CEST   2d        default            <none>
velero-daily-20210415000006    Completed         0        0          2021-04-15 02:00:06 +0200 CEST   1d        default            <none>
velero-daily-20210414000006    Completed         0        0          2021-04-14 02:00:06 +0200 CEST   14h       default            <none>
velero-hourly-20210513090044   Completed         0        0          2021-05-13 11:00:44 +0200 CEST   6d        default            <none>
velero-hourly-20210512150044   Completed         0        0          2021-05-12 17:00:44 +0200 CEST   6d        default            <none>
velero-hourly-20210511150022   PartiallyFailed   1        0          2021-05-11 17:00:22 +0200 CEST   5d        default            <none>
velero-hourly-20210510150007   Completed         0        0          2021-05-10 17:00:07 +0200 CEST   4d        default            <none>
velero-hourly-20210510120007   Completed         0        0          2021-05-10 14:00:07 +0200 CEST   4d        default            <none>
velero-hourly-20210509150007   Completed         0        0          2021-05-09 17:00:07 +0200 CEST   3d        default            <none>
velero-hourly-20210509120007   Completed         0        0          2021-05-09 14:00:07 +0200 CEST   3d        default            <none>
velero-hourly-20210509090007   Completed         0        0          2021-05-09 11:00:07 +0200 CEST   2d        default            <none>
velero-hourly-20210508150006   Completed         0        0          2021-05-08 17:00:06 +0200 CEST   2d        default            <none>
velero-hourly-20210508120006   Completed         0        0          2021-05-08 14:00:06 +0200 CEST   2d        default            <none>
velero-hourly-20210508090006   Completed         0        0          2021-05-08 11:00:06 +0200 CEST   1d        default            <none>
velero-hourly-20210507150006   Completed         0        0          2021-05-07 17:00:06 +0200 CEST   1d        default            <none>
velero-hourly-20210507120006   Completed         0        0          2021-05-07 14:00:06 +0200 CEST   1d        default            <none>
velero-hourly-20210507090006   Completed         0        0          2021-05-07 11:00:06 +0200 CEST   23h       default            <none>
velero-hourly-20210506150006   Completed         0        0          2021-05-06 17:00:06 +0200 CEST   5h        default            <none>
velero-hourly-20210506120006   Completed         0        0          2021-05-06 14:00:06 +0200 CEST   2h        default            <none>
velero-hourly-20210506090006   Completed         0        0          2021-05-06 11:00:06 +0200 CEST   48m ago   default            <none>

metric for total backups is correct (velero_backup_total 52)
However, metrics for failed backups (velero_backup_failure_total) is completely off...as is metric for partially failed (velero_backup_partial_failure_total)

any thoughts? am I missing something?

**Comment by zubron** [comment]
The `velero_backup_total` metric is a [gauge](https://prometheus.io/docs/concepts/metric_types/#gauge) which means that it can go up and down. It is currently set on each [sync of the backups](https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/backup_controller.go#L172) which means that it will be set to the current number of backups that Velero knows about in Object Storage.

The other two metrics, `velero_backup_failure_total` and `velero_backup_partial_failure_total` are [counters](https://prometheus.io/docs/concepts/metric_types/#counter) which mean that they will only ever increase. There are a few things that might be happening here:
 * The Velero server was restarted after the partial backup failures occurred (maybe after 2021-05-11). This would mean the counters were reset but the backups were synced into the server which is why they appear under `velero_backup_total` but the counters are lower.
 * For some of the failed backups,  the `velero_backup_failure_total` was incremented but the backups were deleted. As the counters can't decrease, they will remain higher than the current number of failed backups. This would cause the backup total and the failed totals to be out of sync.
 
Was the Velero server restarted? Did you delete any of the failed backups?

My understanding with counters as well is that you should not rely on their values directly, more how those values change over time (for example looking at [`rate`](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) or [`increase`](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase)).

I don't think there is necessarily an issue here, but let us know about the server restarts/backup deletions as that will give us more info. Thanks!

**Comment by dfsdevops** [comment]
I'm having the same issue, with partially failed backup counter. I can live with the counter being reset during restarts, but the problem is that if there are, say, 5 backups from 2 weeks ago that failed, after restarting the server the counter starts at 0 and goes 0, 1, 2, 3, 4 (every time a backup runs) instead of reflecting an accurate number since the last restart. So even if my backups have been squeaky clean for the past week, the metrics for partially failed backups continue to increase (I don't know if they level out at some point, had a few pod reschedules so I haven't seen if it ever levels out).
