### ISSUE TITLE
Check that E2E tests work in Kind cluster setup with IPV6

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#3804]
**Describe the problem/challenge you have**
We need to learn if there are any IPV6 incompatibilities in Velero.  First step is to run the E2E tests in a Kind IPV6 cluster.

**Describe the solution you'd like**
Create an IPV6 Kind cluster.  Instructions from TKG Gabriel Rosenhouse for how to do this are:

> summary steps for an IPv6 Kind cluster:
> We’ve only done IPv6 Kind on Linux machines, not on Macs, so YMMV there
> Update your docker daemon config to enable IPv6
> Make a kind Cluster YAML file, e.g.
> kind: Cluster
> apiVersion: kind.x-k8s.io/v1alpha4
> networking:
>   ipFamily: ipv6
> 4. Run kind create cluster --config=ipv6-cluster.yaml
> Resources:
> the “Networking” section of the Kind docs
> the #kind channel on K8s slack

Run the E2E tests against the resulting cluster and investigate any issues.

**Comment by nrb** [comment]
Clarifying this request:

* Test an IPv6 cluster and log any issues. We don't need to dive deep into any within the context of this issue.
* We're not looking to support a "dual stack" mode, aka a cluster with IPv4 and IPv6. This is for a cluster on *only* IPv6

**Comment by ashish-amarnath** [comment]
Also consider a scenario where a MinIO, used as a BSL, is setup is outside the cluster and uses an IPV4 endpoint. Need to confirm that Velero installed in an IPV6 cluster can communicate with the MinIO endpoint

**Comment by reasonerjt** [comment]
Closing per https://github.com/vmware-tanzu/velero/issues/1975#issuecomment-900834151
