### ISSUE TITLE
Velero thinks PV is previously restored and skips it but it's not.

### ISSUE THREAD

**Issue by annagavrielatou** [vmware-tanzu/velero#3816]
**What steps did you take and what happened:**
I was following Velero's TKGIs [stateful-ns](https://docs.pivotal.io/tkgi/1-9/velero-statefulset-ns.html) and [statefulset-label](https://docs.pivotal.io/tkgi/1-9/velero-statefulset-label.html) doing the same for our statefulset. Restic is used with Velero.

Difference is that our persistent volume is provisioned using a custom operator. The operator creates local PersistentVolume objects and also creates StorageClasses. The statefulset pods use volumeClaimTemplates that reference one of these StorageClasses. In your TKGIs, the PVs are provisioned by kubernetes.io/vsphere-volume. Does Velero support PVs that are not provisioned by that?

The error we were getting when restoring our PV (together with everything else) was:"Skipping persistentvolumes/br-proxy-pv-0 because it's already been restored" but the PV was not restord in the cluster. This looks like a bug as regardless whether our type of PV is supported or not by Velero, Velero thinks the PV is restored without checking if it actually exists in the cluster.

We ended up using a workaround with 2 backups (first with PV,PVC only, second with everything else excluding PV,PVC) and 2 restores (first with PV, PVC only, second for everything else excluding PV,PVC). This way PV is restored successfully in the first phase and in the second phase, the contents of it are restored together with everything else.

**What did you expect to happen:**
Expected for the PV to be restored together with the other elements of the backup and its contents as well.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

  - velero image used: docker.io/velero/velero:v1.6.0
  - resticRestoreHelper image used: docker.io/velero/velero-restic-restore-helper:v1.6.0
  - velero.initContainers[0].image used: "docker.io/velero/velero-plugin-for-aws:v1.2.0
  - Velero helm chart used as a sub-chart.
  - Restic is enabled.
  - kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
@annagavrielatou if you are a tkgi user, have you contact VMware's GSS support first?

**Comment by reasonerjt** [comment]
@annagavrielatou I'm new to this project and I find it a little confusing.
It would be helpful if you could elaborate on how your operator works, do you create a CR in k8s and the operator will create the PV and SC?  If that's the case I think you should make sure the CR is restored first and let the operator do the remaining work?

I agree the log message is a bit misleading.

@zubron @dsu-igeek could you also chime in?  I recall you mentioned velero doesn't work well when there are operators in the k8s cluster.   Do you consider this issue one of those cases?

**Comment by annagavrielatou** [comment]
Thanks @reasonerjt for looking at this.

So our operator creates a PV and SC for every CR we create based on a CRD. At restore time, we create the CR again. So a new PV is created. Then we delete that new PV because we want to restore the old one we backed up using Velero. Does this make sense?

**Case 1 (problematic):** So CR exists but new PV is deleted. Then if I run restore command of Velero using Restic from a backup with PV&PVC included, restore of PV fails with the error I mentioned in my original ticket. 

**Case 2 (workaround):** With the same prerequisites (CR existed, new PV deleted), if I run restore command of Velero without using Restic from a backup that ONLY had PV&PVC, restore succeeds and PV is restored with all the contents in. Secondly I run restore command of Velero again using Restic from a backup that had everything else but PV&PVC. Second restore succeeds as well. 

As a result, it seems that there is a difference between Case 1 and Case 2. It seems to me that it has to do with the Restic involvement in restore (Case 1) and not the fact that we use a custom operator to create our PVs as in Case 2, Velero is able to do the restore.

Also this error that restore of PV fails because it's already restored, needs to be fixed ASAP.

Please let me know if you have more questions or if I can help further.
Thank you!

**Comment by dsu-igeek** [comment]
This is not going to work because the local PVs cannot be provisioned by Velero.

**Comment by annagavrielatou** [comment]
I believe the last comment does not explain much about all these that I've reported in this ticket. Please re-open it and close it only if both sides are happy with the provided explanations.

It works for Velero restore with PV,PVC only but not for Restic restore when a pod and PV,PVC are included. So it must be Restic related. What do you mean by "this is not going to work"? It works for Velero but not for Restic. Why?

Which are the cases that are supported officially by Velero? I've only see vSphere provisioned PVs mentioned in the examples.

Also what about the log that is incorrect saying that the PV is already restored. Isn't this going to be fixed?

Thanks,
Anna

**Comment by eleanor-millman** [comment]
@annagavrielatou We on the Velero team are stretched quite thinly right now and unfortunately cannot resolve all tickets we are getting in (this may change in the future as we ramp up new team members, but this is our current state). @dsu-igeek was trying to at least get you a response to your ticket. We'll do our best to help you more, but please keep in mind that the maintainers are doing their best given everything that is on their plates right now.

**Comment by annagavrielatou** [comment]
@eleanor-millman I appreciate the team is stretched but the ticket needs to remain open in order to be re-visited later based on your priorities. The response I got doesn't cover almost any of my questions and the bugs I reported. Can you please re-open it?
