### ISSUE TITLE
pod are in pending state

### ISSUE THREAD

**Issue by themonaminor** [vmware-tanzu/velero#3822]
when restoring in cluster 2 from cluster 1, the PV , PVC are restored.
but pods are in pending state.

Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  6m     default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  6m     default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  6m     default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  5m38s  default-scheduler  0/3 nodes are available: 3 node(s) had volume node affinity conflict.

how to reproduce:-

cluster1:-

get backup

cluster2:

create restore from above created backup.

**Comment by zubron** [comment]
Hi @themonaminor - We're going to need logs to discover what's going on.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Comment by dsu-igeek** [comment]
@themonaminor Please re-open with logs if you still need help
