### ISSUE TITLE
Unable to extend timeout for backup resources

### ISSUE THREAD

**Issue by tomelliot16** [vmware-tanzu/velero#3824]
This might be a feature request in the end.
**What steps did you take and what happened:**
While running a periodic backup consistently we hit a timeout when collecting the resource secrets. We end up with a partial failed backup which is missing secrets. There doesn't seem to be an easy way to extend the timeout.

**What did you expect to happen:**
We expected to find a way to extend the timeout but couldn't find it in the documentation.

**The output of the following commands will help us better understand what's going on**:
```
"time=\\"2021-05-24T18:12:21Z\\" level=error msg=\\"Error listing items\\"  error=\\"the server was unable to return a response in the time allotted, but may still be processing the request\\" error.file=\\"/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_collector.go:294\\" error.function=\\"github.com/vmware-tanzu/velero/pkg/backup.(*itemCollector).getResourceItems\\" group=v1 logSource=\\"pkg/backup/item_collector.go:294\\" namespace= resource=secrets\
```

**Anything else you would like to add:**
Looks like there is a timeout option that can be added here.
https://github.com/vmware-tanzu/velero/blob/main/pkg/backup/item_collector.go#L292

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
@tomelliot16 
I'm new to this project but IMO generally speaking there can be a timeout whenever a request is sent to api-server?  I'm not sure if you should expose such low level parm to users.

And could you let us know why the request in this issue took such a long time?

**Comment by tomelliot16** [comment]
@reasonerjt Hi yeah so yeah you're correct however. We are hitting limits due to the lack of pagination it seems. There doesn't seem like there is support currently to allow us to not get a timeout due to the volume of secrets we have on the cluster. Also additionally velero backups are not kind to the api-server when backing up.

**Comment by zubron** [comment]
This may be solved by #262.

**Comment by eleanor-millman** [comment]
@reasonerjt was this indeed solved by 262 as Bridget suggested?

**Comment by reasonerjt** [comment]
@eleanor-millman We haven't hit any timeout issue in our test, nor did I hear any feedbackup from users regarding such issue other than this one.

@tomelliot16 Could you please clarify if this has been fixed with latest velero?

**Comment by eleanor-millman** [comment]
Great, we can then close this unless @tomelliot16 has seen issues still. Thanks!

**Comment by reasonerjt** [comment]
We have run some perf test to backup tens of thousands of resources and didn't hit timeout issue.
Nor do I think allowing user to set the timeout for API server is a good idea for B/R tool.
I'm closing this issue, please open new issue when you see such problem again.
