### ISSUE TITLE
error getting volume info

### ISSUE THREAD

**Issue by aberenshtein** [vmware-tanzu/velero#3837]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Created a backup for a namespace that contains PVCs. The backup `PartiallyFailed` and when I checked the logs I noticed this error ` error="error getting volume info: rpc error: code = Unknown desc = RequestError: send request failed\ncaused by: Post https://ec2.us-west-2.amazonaws.com/: http: server gave HTTP response to HTTPS client" logSource="pkg/backup/backup.go:431" name=loki2-0`

I checked the IAM user policy and it has both  ` "ec2:DescribeVolumes","ec2:DescribeSnapshots",`.
I also checked that the volumeSnapshotLocation and verified it is set to `us-west-2`

** extra logs **
`time="2021-05-31T18:17:15Z" level=info msg="label \"topology.kubernetes.io/zone\" is not present on PersistentVolume, checking deprecated label..." backup=velero/logging3 logSource="pkg/backup/item_backupper.go:432" name=pvc-41285a26-c13b-41bf-bba6-b35f36ac7110 namespace= persistentVolume=pvc-41285a26-c13b-41bf-bba6-b35f36ac7110 resource=persistentvolumes
time="2021-05-31T18:17:15Z" level=info msg="Got volume ID for persistent volume" backup=velero/logging3 logSource="pkg/backup/item_backupper.go:462" name=pvc-41285a26-c13b-41bf-bba6-b35f36ac7110 namespace= persistentVolume=pvc-41285a26-c13b-41bf-bba6-b35f36ac7110 resource=persistentvolumes volumeSnapshotLocation=default
time="2021-05-31T18:17:15Z" level=info msg="Getting volume information" backup=velero/logging3 logSource="pkg/backup/item_backupper.go:483" name=pvc-41285a26-c13b-41bf-bba6-b35f36ac7110 namespace= persistentVolume=pvc-41285a26-c13b-41bf-bba6-b35f36ac7110 resource=persistentvolumes volumeID=vol-0e73031019899ab43
time="2021-05-31T18:17:15Z" level=info msg="1 errors encountered backup up item" backup=velero/logging3 logSource="pkg/backup/backup.go:427" name=loki2-0
time="2021-05-31T18:17:15Z" level=error msg="Error backing up item" backup=velero/logging3 error="error getting volume info: rpc error: code = Unknown desc = RequestError: send request failed\ncaused by: Post https://ec2.us-west-2.amazonaws.com/: http: server gave HTTP response to HTTPS client" logSource="pkg/backup/backup.go:431" name=loki2-0
ti`

**What did you expect to happen:**

Backup to succedd 

**Environment:**

- Velero version (use `velero version`): v1.6.0
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): v1.16.13
- Kubernetes installer & version: kop 1.16.4
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`): macOS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by AlwaySummit** [comment]
Hi guys, I'm hitting the same issue here. I guess it is because the out-of-tree volume plugin doesn't set the labels correctly. Given this circumstance, I'm wondering if velero can adjust the logic to retrieve zone information from somewhere else simultaneously? For example:
```
nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.gke.io/zone
          operator: In
          values:
          - europe-west1-c
```

**Comment by k1ng440** [comment]
Hi, i have the same issue with the GCP

**Comment by andersondario** [comment]
I was getting a similar error on GKE
`label \"topology.kubernetes.io/zone\" is not present on PersistentVolume, checking deprecated label...`

To solve that, I had to label the PV with that label. Example:
`kubectl label persistentvolumes dummy-db-pv-volume topology.kubernetes.io/zone=us-central1-a`

**Reference**
https://github.com/vmware-tanzu/velero/blob/4de4d3783313e61d15e676a260ec400393a848e2/pkg/backup/item_backupper.go#L442
