### ISSUE TITLE
Partially failed backups when trying to backup pods whose status is completed

### ISSUE THREAD

**Issue by zynpsnltrkk** [vmware-tanzu/velero#3838]
What steps did you take and what happened:
I took a backup from test ns and I got particially failed. 
```
velero -n velero backup create test-1 --include-namespaces test --default-volumes-to-restic --wait

velero -n velero backup describe test-1 --details
Errors: Restic Backups:
  Completed:
    test/postgresql-0: data
  Failed:
    test/clear-cached-documents-cron-1621602000-74chx: mnt-data
```
and when I look at clear-cached-documents-cron pod, it was a completed pod triggered by cronjob.
```
kubectl get po -n test
NAME                                       READY   STATUS      RESTARTS   AGE
clear-cached-documents-cron-1621602000-74chx   0/1     Completed   0          19h
...
mte-controller-7b9c64fdbf-hlb79            1/1     Running     0          19h
mte-worker-set-0                           1/1     Running     0          19h
mte-worker-set-1                           1/1     Running     0          19h
mte-worker-set-2                           1/1     Running     0          19h
...
```
Velero logs:
```
time="2021-05-11T11:43:26Z" level=error msg="Error backing up item" backup=rc-system/transact-daily-backup-20210511114324 error="pod volume backup failed: error getting volume path on host: expected one matching path, got 0" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:179" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:455" name=clear-cached-documents-cron-1621602000-74chx
```
restic logs:
```
Error uniquely identifying volume path, expected one matching path, got 0
```
when I destroyed all completed pods, I could take backup successfully from test ns.

What did you expect to happen:
Velero should skip them to get a successful backup or a more specific error message would be nice. What I deduced from this result was velero cannot take backups of the completed pods because they are not really in the running state.

Environment:
- velero version: 
Client:
  Version: v1.5.3
Server:
  Version: v1.5.2
- Velero features (use `velero client config get features`): velero client config get features
features: <NOT SET>
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
baremetal
- OS (e.g. from `/etc/os-release`):
 Ubuntu 18.04

**Comment by zubron** [comment]
Hi @zynpsnltrkk - Thanks for reporting this. Yes, you are correct in that we cannot take restic backups of pods that are `Completed`. The pod needs to be in a `Running` state for it to work. We have a few other issues open related to this, e.g. #2395.

I am going to close this as a duplicate, but if you have any other info, please leave comments on #2395. Thanks!
