### ISSUE TITLE
After restart, Velero pod does not pick up Backups that are "In-Progress"

### ISSUE THREAD

**Issue by phuongatemc** [vmware-tanzu/velero#3852]
This relates to bug https://github.com/vmware-tanzu/velero/issues/3851 in which the Velero Pod is restarted due to OOM error.
To reproduce this problem, we can create a namespace with large number of resources (like 10,000 Secret, ServiceAccount etc.) and run Backup.  After less than a minute, Velero Pod would restart because of OOM (give Velero pod memory is anywhere from 128MB to 512MB).
After Velero Pod restarted, the Backup CR is stuck in "In-Progress" phase forever because the Velero Pod doesn't pick up any Backup CR that is in "In-Progress" state. 

I think Velero Pod should pick up these Backup CRs and fail them.

**Comment by phuongatemc** [comment]
This looks similar to https://github.com/vmware-tanzu/velero/issues/3131

**Comment by zubron** [comment]
This is a known issue: #2877. I'm going to close this but please add any new info to that issue. Thanks!
