### ISSUE TITLE
restore persistentVolume to PersistentVolumeClaim with larger size

### ISSUE THREAD

**Issue by amos-baron** [vmware-tanzu/velero#3854]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
I have a persistent volume I would like to restore into a pvc with a larger size

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
an option to resize the restored pvc or restore pv data to an existing pvc.

**Comment by kaovilai** [comment]
This might be already solvable through [resource modifier](https://github.com/vmware-tanzu/velero/pulls?q=is%3Apr+%22resource+modifier%22+is%3Aclosed+) https://velero.io/docs/main/restore-resource-modifiers/

**Comment by kaovilai** [comment]
rough investigation..

  1. Restore Item Actions Execute First (restore.go:1314-1371)
    - The PVC restore item action (pvc_action.go) runs at this stage
    - It creates a DataDownload CR with the PVC name and namespace
    - The DataDownload references the original PVC name that will be created
  2. Resource Modifiers Apply Second (restore.go:1454-1455)
    - Resource modifiers are applied AFTER restore item actions
    - They modify the PVC object including potentially the storage size
  3. PVC Gets Created in Cluster (restore.go:1514)
    - The modified PVC (with any resource modifier changes) is created
  4. DataDownload Controller Processes
    - DataDownload controller picks up the CR
    - Retrieves the target PVC from cluster (data_download_controller.go:827)
    - Calls generic_restore exposer
  5. Generic Restore Creates Intermediate PVC
    - Creates restore PVC inheriting size from target PVC (generic_restore.go:619)
    - The target PVC at this point already has resource modifier changes applied


  This means if you use a resource modifier like:
  version: v1
  resourceModifierRules:
  - conditions:
      groupResource: persistentvolumeclaims
      resourceNameRegex: ".*"
    patches:
    - operation: replace
      path: "/spec/resources/requests/storage"
      value: "100Gi"

  The workflow would be:
  1. PVC restore item action creates DataDownload CR pointing to PVC "my-pvc"
  2. Resource modifier changes PVC size from 10Gi to 100Gi
  3. PVC "my-pvc" created in cluster with 100Gi
  4. DataDownload controller retrieves "my-pvc" (now 100Gi)
  5. Generic restore creates intermediate restore PVC also with 100Gi
