### ISSUE TITLE
AWS plugin does not validate configuration until operations are tried

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#3858]
**What steps did you take and what happened:**
If incorrect values (bad password, etc) are given to the plug-in, the plug-in will start successfully but then fail when a snapshot or object store operation occurs.  

**What did you expect to happen:**

The plug-in should validate the config at init time and log any errors.  This way the user can find out immediately if there are any problems with their configuration.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment]
Does this mean that the backup will still be attempted even if the BackupStorageLocation has the phase "Unavailable"? Also, is this specific to AWS or are all Object store plugins are affected?
