### ISSUE TITLE
Restore of a successful backup fails if triggered immediately after the backup completes using GCS as the storage location.

### ISSUE THREAD

**Issue by thomasdevos69** [vmware-tanzu/velero#3862]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Restore of a successful backup fails if triggered immediately after the backup completes using GCS as the storage location.

**What did you expect to happen:**

-- Restore should happen successfully once the backup has reported being complete successfully.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

-- The backup and Restore functionality uses the CRD through the K8s API server (Fabric8). 
-- Attached is a response from a Restore - The only message we get is "FailedValidation" with "["Error retrieving backup: backup.velero.io \"cmp-backup-1623321435069\" not found"]" 
-- When we look on GCS then this backup does exist. 
-- velero restore logs <restorename> => no logs "Restore "cmp-backup-1623321435069-1623321464263" does not exist." 
- velero backup 
[backup.log](https://github.com/vmware-tanzu/velero/files/6630675/backup.log)
- velero describe backup 
[describe_backup.log](https://github.com/vmware-tanzu/velero/files/6630685/describe_backup.log)
- kubectl logs velero - Target cluster 
[kubectl-velero-target.log](https://github.com/vmware-tanzu/velero/files/6630700/kubectl-velero-target.log)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

-- Backup/Restore happens on two different clusters (OCP being the source and GKE the target) and uses GCS as the common storage location. 
-- A 40 seconds delay before triggering the restore seems to increase the success rate to 100% (initial results) 

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

Velero 1.6 on both GKE and OCP

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
[velero_api_response.txt](https://github.com/vmware-tanzu/velero/files/6630629/velero_api_response.txt)

**Comment by zubron** [comment]
Velero requires that a backup Custom Resource object exists in the cluster to restore from. When you perform a backup, the backup tarball will be in the object storage, but it will not be synced to the new cluster right away. The sync process happens every minute and you can check if the backup is available in the new cluster by running `velero get backups` against it.

If you would like the sync to run more frequently, you can modify the [`config.backupSyncPeriod` of the BackupStorageLocation](https://velero.io/docs/v1.6/api-types/backupstoragelocation/) that you are trying to restore from.

Hopefully this solves your issue. I am going to close this, but feel free to reopen if you have problems with this solution.

**Comment by thomasdevos69** [comment]
Thanks for the explanation and the support!
