### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by SergioTeco** [vmware-tanzu/velero#3874]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

https://velero.io/docs/master/api-types/volumesnapshotlocation/

PAGE NOT FOUND

**Comment by zubron** [comment]
Hi 👋 where did you get this link? If some of our documentation has this broken link, we will need to know the location so we can fix it :)

**Comment by reasonerjt** [comment]
I believe this is caused by branch renaming, this link works:
https://velero.io/docs/main/api-types/volumesnapshotlocation/

I'm closing this issue.
