### ISSUE TITLE
The supported K8s version(s) are not specified for 1.6

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/velero#3881]
Can we please document the version(s) of K8s that work with 1.6? 

I would suggest the following language:
Velero 1.6.1 was tested against Kubernetes 1.21. We suspect that 1.6.1 will also work with Kubernetes 1.12 - 1.20, but be aware that we have not tested these combinations.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by eleanor-millman** [comment]
@dsu-igeek or @zubron Are you able to comment with the required information? Thanks!

**Comment by eleanor-millman** [comment]
@zubron @dsu-igeek Am I correct that 1.6.1 was tested against 1.21?

**Comment by a-mccarthy** [comment]
@eleanor-millman is there more we want to add to this https://github.com/vmware-tanzu/velero#velero-compatibility-matrix?  recently updated by https://github.com/vmware-tanzu/velero/pull/4502

**Comment by eleanor-millman** [comment]
You are suggesting that we can just close this issue because we have updated the compatibility matrix? If so, then I agree. Thanks! @a-mccarthy
