### ISSUE TITLE
rss link blindly appends /blog/index.html

### ISSUE THREAD

**Issue by nhomble** [vmware-tanzu/velero#3882]
**What steps did you take and what happened:**
1. visit https://velero.io/
2. clicked `see all posts` to see the blog, browser went to https://velero.io/blog/
3. clicked RSS icon to check for xml
4. was navigated to https://velero.io/blog/blog/index.xml (404)

**What did you expect to happen:**
Go directly to https://velero.io/blog/index.xml

**Comment by zubron** [comment]
It looks like the RSS link is wrong: https://github.com/vmware-tanzu/velero/blob/main/site/config.yaml#L58
It is `blog/index.xml` when it should be `/blog/index.xml`.

**Comment by Patil2099** [comment]
I would love to take this up

**Comment by eleanor-millman** [comment]
@Patil2099 Thank you!
