### ISSUE TITLE
Lots of small changes suggested for docs

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/velero#3887]
- https://velero.io/docs/v1.6/supported-providers/ -  Under Provider, please change the "VMware vSphere" and "Container Storage Interface (CSI) links be to definition pages: https://www.vmware.com/ca/products/vsphere.html and https://kubernetes.io/blog/2019/01/15/container-storage-interface-ga/   Right now they currently link to the github page for the plugins, but the same link is under the plugins column, so it is redundant.

- https://github.com/vmware-tanzu/velero/releases/tag/v1.6.0-rc.2 (or for all release links, if possible). Under the "Download" header, instead of linking to the page it is on, please replace with text "Scroll to the bottom of the page for downloadable binaries" (or something similar if that text is not quite correct). If you can provide a link to the bottom of the page with the binaries, even better!

- In the PR default text, say “Created a changelog file or added /kind changelog-not-required as a comment on this pull request” (I added “as a comment on this pull request”)

- https://velero.io/docs/v1.6/basic-install/ suggests that the Velero CLI can be installed EITHER with brew OR by downloading the tarball (two options). But https://velero.io/docs/v1.6/contributions/minio/ seems to suggest that first you download the tarball, then you do brew. I think that this page is wrong and should make it clear that there are two options for installing the Velero CLI, either with the tarball or brew. If I am right, then please tweak the headers:  a big header that says "Install the Velero CLI" and then two subheaders that say "Option 1: GitHub release" and "Option 2: MacOS - Homebrew".

- https://velero.io/docs/v1.6/contributions/minio/  mentions “Velero directory” but later says “local directory”. Are those the same thing? If so, please clarify (probably should change "local directory" to "Velero directory")

- https://velero.io/docs/v1.6/contributions/minio/   Under the header "Set up server" it says “[Expose Minio outside your cluster][31]” with no link. Would this make sense to link to the header "Expose Minio outside your cluster with a Service"? If so, please link (and get rid of the square brackets and the random "31").

- https://velero.io/docs/v1.6/contributions/minio/ In “Set up the server”, step 2, please add the following text somewhere after the velero install example:
"This example assumes you have named your Minio bucket "velero". "

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by eleanor-millman** [comment]
@a-mccarthy FYI.

**Comment by jonasrosland** [comment]
I can make some of these changes.

**Comment by neha-viswanathan** [comment]
Hi @eleanor-millman @jonasrosland can I pick this one up?

**Comment by eleanor-millman** [comment]
@neha-viswanathan , we'd love for you to, thank you!

**Comment by neha-viswanathan** [comment]
@eleanor-millman for pt 2: I don't have access to edit the releases info.

**Comment by eleanor-millman** [comment]
@reasonerjt Is this something you can help @neha-viswanathan with? If not, @neha-viswanathan , I can move that one to a different issue so this one can be closed once you make your PR. Thanks again for your help!

**Comment by neha-viswanathan** [comment]
@eleanor-millman sure thanks! Shall I replicate these changes on the 1.7 documentation as well?

**Comment by eleanor-millman** [comment]
@neha-viswanathan if it's not hard, then that would be great (since 1.8 won't be released until end of January). Thank you!
