### ISSUE TITLE
Add test cases Velero Installation and General Backup/Restore on AWS into E2E tests

### ISSUE THREAD

**Issue by yanji09** [vmware-tanzu/velero#3895]
**Describe the problem/challenge you have**
Currently Velero needs to run a set of manual tests during a release. https://velero.io/docs/v1.6/manual-testing/
Manual testing is inefficient and not easily repeatable. It is also prone to inconsistent test conditions, which does not easily ensure that Velero releases are measured against the same test criteria.

**Describe the solution you'd like**
Turn the manual test into E2E tests step by step. Propose to include below manual test cases in this ticket.
- [x] Installation – Cover latest 3 Kubernetes versions
- [ ] General Backup and Restore functionality for AWS – including below scenarios
  - Verify that a backup and restore using Volume Snapshots can be performed.
  - Verify that a backup of a cluster workload can be restored in a new cluster.

**Anything else you would like to add:**
The corresponding document need to be updated.
- [ ] Update the Manual Testing Requirements for Velero

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by zubron** [comment]
This is still required.

**Comment by eleanor-millman** [comment]
@danfengliu I assume I should leave the 1.8 milestone since you just added it yesterday?

**Comment by reasonerjt** [comment]
Closing since we have pipeline to cover AWS.  We'll open new issues once we have finalized the support matrix to setup new pipelines to verify on more versions of K8S
