### ISSUE TITLE
velero pod logs and backups are showing Error getting volume snapshotter for volume snapshot location

### ISSUE THREAD

**Issue by mereddy22** [vmware-tanzu/velero#3896]
**Installed Steps:** 
BLOB_CONTAINER=testgkeopsplatform-expc1
SERVICE_ACCOUNT=velero@gcp-velero.iam.gserviceaccount.com
Installed CRD's: velero install --crds-only --dry-run -o yaml | kubectl apply -f -

velero install --provider gcp --plugins velero/velero-plugin-for-gcp:v1.2.0 --bucket $BLOB_CONTAINER  --secret-file ./credentials-velero --backup-location-config serviceAccount=$SERVICE_ACCOUNT --snapshot-location-config apiTimeout=15m

kubectl get pods -n velero
velero-7c6754bf8d-gb7z6   1/1     Running   0          35m

**What did you expect to happen:**

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- kubectl logs -f velero-7c6754bf8d-gb7z6 -n velero | grep error
time="2021-06-24T16:14:58Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/sample-backup error="rpc error: code = Unknown desc = config has invalid keys [apiTimeout]; valid keys are [snapshotLocation project]" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.4.0/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys logSource="pkg/backup/item_backupper.go:449" name=pvc-fc17f35b-a834-4deb-941b-ec3a3e38ec26 namespace= persistentVolume=pvc-fc17f35b-a834-4deb-941b-ec3a3e38ec26 resource=persistentvolumes volumeSnapshotLocation=default
time="2021-06-24T16:14:58Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/sample-backup error="rpc error: code = Unknown desc = config has invalid keys [apiTimeout]; valid keys are [snapshotLocation project]" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.4.0/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys logSource="pkg/backup/item_backupper.go:449" name=pvc-5a26c6a1-18fd-4416-b692-12870837840c namespace= persistentVolume=pvc-5a26c6a1-18fd-4416-b692-12870837840c resource=persistentvolumes volumeSnapshotLocation=default
time="2021-06-24T16:14:58Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/sample-backup error="rpc error: code = Unknown desc = config has invalid keys [apiTimeout]; valid keys are [snapshotLocation project]" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.4.0/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys logSource="pkg/backup/item_backupper.go:449" name=pvc-cb8333a1-a4b7-495d-951c-8dc2f66ff44a namespace= persistentVolume=pvc-cb8333a1-a4b7-495d-951c-8dc2f66ff44a resource=persistentvolumes volumeSnapshotLocation=default
time="2021-06-24T16:14:59Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/sample-backup error="rpc error: code = Unknown desc = config has invalid keys [apiTimeout]; valid keys are [snapshotLocation project]" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.4.0/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys logSource="pkg/backup/item_backupper.go:449" name=pvc-b15064f6-213a-4707-8c7b-ca40c267ced5 namespace= persistentVolume=pvc-b15064f6-213a-4707-8c7b-ca40c267ced5 resource=persistentvolumes volumeSnapshotLocation=default
time="2021-06-24T16:14:59Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/sample-backup error="rpc error: code = Unknown desc = config has invalid keys [apiTimeout]; valid keys are [snapshotLocation project]" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.4.0/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys logSource="pkg/backup/item_backupper.go:449" name=pvc-f803d2f9-cbad-49c0-9775-b42caf4f79dc namespace= persistentVolume=pvc-f803d2f9-cbad-49c0-9775-b42caf4f79dc resource=persistentvolumes volumeSnapshotLocation=default

- velero backup describe sample-backup
Name:         sample-backup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.19.9-gke.1900
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=19+

Phase:  PartiallyFailed (run `velero backup logs sample-backup` for more information)

Errors:    5
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-06-24 16:14:53 +0000 UTC
Completed:  2021-06-24 16:15:09 +0000 UTC

Expiration:  2021-07-24 16:14:53 +0000 UTC

Total items to be backed up:  1164
Items backed up:              1164

Velero-Native Snapshots: <none included>
- velero backup logs sample-backup | grep error
time="2021-06-24T16:14:58Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/sample-backup error="rpc error: code = Unknown desc = config has invalid keys [apiTimeout]; valid keys are [snapshotLocation project]" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.4.0/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys logSource="pkg/backup/item_backupper.go:449" name=pvc-fc17f35b-a834-4deb-941b-ec3a3e38ec26 namespace= persistentVolume=pvc-fc17f35b-a834-4deb-941b-ec3a3e38ec26 resource=persistentvolumes volumeSnapshotLocation=default
time="2021-06-24T16:14:58Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/sample-backup error="rpc error: code = Unknown desc = config has invalid keys [apiTimeout]; valid keys are [snapshotLocation project]" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.4.0/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys logSource="pkg/backup/item_backupper.go:449" name=pvc-5a26c6a1-18fd-4416-b692-12870837840c namespace= persistentVolume=pvc-5a26c6a1-18fd-4416-b692-12870837840c resource=persistentvolumes volumeSnapshotLocation=default
time="2021-06-24T16:14:58Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/sample-backup error="rpc error: code = Unknown desc = config has invalid keys [apiTimeout]; valid keys are [snapshotLocation project]" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.4.0/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys logSource="pkg/backup/item_backupper.go:449" name=pvc-cb8333a1-a4b7-495d-951c-8dc2f66ff44a namespace= persistentVolume=pvc-cb8333a1-a4b7-495d-951c-8dc2f66ff44a resource=persistentvolumes volumeSnapshotLocation=default
time="2021-06-24T16:14:59Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/sample-backup error="rpc error: code = Unknown desc = config has invalid keys [apiTimeout]; valid keys are [snapshotLocation project]" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.4.0/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys logSource="pkg/backup/item_backupper.go:449" name=pvc-b15064f6-213a-4707-8c7b-ca40c267ced5 namespace= persistentVolume=pvc-b15064f6-213a-4707-8c7b-ca40c267ced5 resource=persistentvolumes volumeSnapshotLocation=default
time="2021-06-24T16:14:59Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/sample-backup error="rpc error: code = Unknown desc = config has invalid keys [apiTimeout]; valid keys are [snapshotLocation project]" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.4.0/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys logSource="pkg/backup/item_backupper.go:449" name=pvc-f803d2f9-cbad-49c0-9775-b42caf4f79dc namespace= persistentVolume=pvc-f803d2f9-cbad-49c0-9775-b42caf4f79dc resource=persistentvolumes volumeSnapshotLocation=default

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

time="2021-06-24T16:14:58Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/sample-backup error="rpc error: code = Unknown desc = config has invalid keys [apiTimeout]; valid keys are [snapshotLocation project]" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.4.0/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys logSource="pkg/backup/item_backupper.go:449" name=pvc-fc17f35b-a834-4deb-941b-ec3a3e38ec26 namespace= persistentVolume=pvc-fc17f35b-a834-4deb-941b-ec3a3e38ec26 resource=persistentvolumes volumeSnapshotLocation=default

**Environment:**

- Velero version (use `velero version`): 
- Client:
        Version: v1.6.0
        Git commit: 5bd70fd8eef316d220317245e46dc6016c348dce
Server:
        Version: v1.6.0
- Velero features (use `velero client config get features`):  NOT SET
- Kubernetes version (use `kubectl version`): GKE version: v1.19.9-gke.1900
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by mereddy22** [comment]
is my velero install steps are correct ?

should I add this --use-volume-snapshots=false to avoid those errors on the backup logs?

**Comment by reasonerjt** [comment]
Hi @mereddy22 

I'm new to this project but this message seems pointed out the problem:
```
desc = config has invalid keys [apiTimeout]; valid keys are [snapshotLocation project]" 
```

**Comment by zubron** [comment]
Hi @mereddy22 - @reasonerjt is correct. The `apiTimeout` key you have specified in `--snapshot-location-config` is invalid for GCP. You can find details of the valid config options here: https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/main/volumesnapshotlocation.md.

If you use `--use-volume-snapshots=false`, your volumes will not be backed up. In order to backup your volumes, you will need to pass the correct config values to the `--snapshot-location-config` flag so that the plugin can correctly take snapshots of the volumes, or you will need to configure [restic](https://velero.io/docs/v1.6/restic/) to backup the contents of your volumes to your GCP object storage.

I am going to close this issue as it is a configuration error. Hopefully the above steps will work for you!

**Comment by mereddy22** [comment]
Thank you and I fixed my command and issue is resolved now.

velero install --use-restic --provider gcp --plugins velero/velero-plugin-for-gcp:v1.2.0 --bucket=$BLOB_CONTAINER --secret-file ./credentials-velero --backup-location-config bucket=$BLOB_CONTAINER,serviceAccount=$SERVICE_ACCOUNT --snapshot-location-config snapshotLocation=us-central1,project=$PROJECT
