### ISSUE TITLE
Disable restic maintenanceFrequency

### ISSUE THREAD

**Issue by bdietrich12** [vmware-tanzu/velero#3909]
Hello,

i should like disable the restic maintenanceFrequency on a resticRespository, because it's run by multiple velero/restic on different kubernetes cluster.

I read the documentation, we can precise when run the maintenance like :

spec:
backupStorageLocation: restic-tests
maintenanceFrequency: 168h0m0s

I try ro use :

maintenanceFrequency: Never
maintenanceFrequency: never
maintenanceFrequency: forget

But i can't sync with restic repository...

maintenanceFrequency: 0h0m0s

It run the maintenance anyways.

Is it possible to disable the restic maintenance, because the maintenance (prune command) is running during the velero's backups.

The prune commande lock the restic repositories and velero is not able to performs backups.

**Comment by zubron** [comment]
It's not currently possible to disable the restic maintenance frequency. The frequency is specified as a [`time.Duration`](https://golang.org/pkg/time/#Duration) and if set to a value <= 0, the restic controller will set it to the default value of [once a week](https://github.com/vmware-tanzu/velero/blob/f727e070cb9f7ea27d9b5dcd7ee617e5e7cf6885/pkg/restic/common.go#L45-L47). It's not an ideal workaround, but could you try setting it to a very long interval to avoid the maintenance being run? (The maximum duration represented by a `time.Duration` is approximately 290 years)

One thing to consider is that by disabling the maintenance/pruning, this could result in significantly more storage being used as unused snapshots could be left behind. I don't know if this would also have an impact on restic's performance as the size of the repository grows.

**Comment by dsu-igeek** [comment]
Advice would be to use different buckets per cluster.
