### ISSUE TITLE
-v, --v Level invaild

### ISSUE THREAD

**Issue by guanxingfeng** [vmware-tanzu/velero#3915]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
There is no difference between "velevo get xxx -v (level)"  and  "velevo get xxx"
![image](https://user-images.githubusercontent.com/25924966/124089797-d3ded100-da86-11eb-8864-df467f76c1a5.png)

**What did you expect to happen:**
Display the log debugging information like “kubectl -v xxx”

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.6.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):v1.18.13
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment]
Most of the debug level logs will come from the Velero server. For commands like `get`/`create`/`delete` etc., there is very little that happens on the client side. If there is no debug/verbose output, it means that there are no logs being produced by the client at that level. Most of the processing for these commands takes place on the server and unfortunately we don't have a way to show those server logs through the local client when running the commands.

You can enable debug logs on the server following the instructions here: https://velero.io/docs/v1.6/troubleshooting/#getting-velero-debug-logs
After running your commands, you can examine the logs of the velero deployment using `kubectl logs -n velero deployment/velero` to see if the details you need are there.

I am going to close this issue as I don't think there is anything additional that we will change at this time. Hopefully the instructions above work for you. If you need further help though or have other ideas related to this, we can reopen. Thanks!
