### ISSUE TITLE
Do not display warnings and error messages with the “velero backup describe xxx ” command  -- it should be consistent with "velero restore describe"

### ISSUE THREAD

**Issue by guanxingfeng** [vmware-tanzu/velero#3916]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Do not display warnings and error details with the “velero backup describe xxx ” command
![image](https://user-images.githubusercontent.com/25924966/124092098-14d7e500-da89-11eb-8544-17c9e5c90089.png)

**What did you expect to happen:**
Like the output of “velero restore describe nginx-daily-20210630115745” command
![image](https://user-images.githubusercontent.com/25924966/124092024-01c51500-da89-11eb-8633-7bb9ba1c3b14.png)

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.6.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): v1.18.13
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
@guanxingfeng 

I see this is a issue is an inconsistency of output when describing backup or restore?

**Comment by guanxingfeng** [comment]
@reasonerjt yes.

**Comment by guanxingfeng** [comment]
> @guanxingfeng
> 
> I see this is a issue is an inconsistency of output when describing backup or restore?
