### ISSUE TITLE
Velero cannot restore on aks v1.19.9

### ISSUE THREAD

**Issue by fluffyf-x** [vmware-tanzu/velero#3922]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

- installed velero v 1.6.1 with csi plugin v.0.1.2, velero-plugin-for-microsoft-azure v.1.2.0
- added annotations to `VolumeSnapshotClass`
   ```
   labels:
      velero.io/csi-volumesnapshot-class: "true"
   ```
- added annotation to pvc's backed up Azure File Store 
  ```
  labels:
     velero.io/exclude-from-backup: "true"
  ```
- attempted two paths to restore an AKS cluster back to previous state 
   - used velero to a perform manual backup 
    ```
    velero backup create bkup0702 --include-namespaces <namespace> \
    --snapshot-volumes=true \
    --ttl 72h \
    --volume-snapshot-locations default \
    --storage-location default \
    --include-cluster-resources
    ```
- delete namespace 
- `velero restore create --from-backup bkup0702` would restore the namespace including pv/pvcs

**What did you expect to happen:**
- velero would restore 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
after installation velero marked the backup location as valid
```
time="2021-07-01T20:01:29Z" level=info msg="Backup storage location valid, marking as available" backup-storage-location=default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:121"
time="2021-07-01T20:02:29Z" level=info msg="Validating backup storage location" backup-storage-location=default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:114"
```
creating backups were successful both manually and on a schedule
```          <none>
prod-velero-daily-20210701025717   Completed    0        0          2021-06-30 19:57:17 -0700 PDT   5h        default            <none>
prod-velero-daily-20210630225619   Completed    0        0          2021-06-30 15:56:22 -0700 PDT   1h        default            <none>
snapshots                          Completed    0        0          2021-07-01 18:15:41 -0700 PDT   2d        default            <none>
```
logs show 
```
time="2021-07-01T02:57:30Z" level=info msg="Executing VolumeSnapshotContentBackupItemAction" backup=velero/ghae-velero-daily-20210701025717 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/volumesnapshotcontent_action.go:50" pluginName=velero-plugin-for-csi
...
time="2021-07-01T02:57:30Z" level=info msg="Getting VolumesnapshotContent for Volumesnapshot ghae/velero-data-imagemagic-2-sm5xq" backup=velero/prod-velero-daily-20210701025717 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/volumesnapshot_action.go:91" pluginName=velero-plugin-for-csi
tim
```
the output of --details is a tad long
```
Name:         allsnapshots
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.19.9
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=19

Phase:  Completed

Errors:    0
Warnings:  0

Namespaces:
  Included:  ghae
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  included

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  true

TTL:  72h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-07-01 22:16:07 -0700 PDT
Completed:  2021-07-01 22:17:29 -0700 PDT

Expiration:  2021-07-04 22:16:07 -0700 PDT

Total items to be backed up:  1247
Items backed up:              1247

Velero-Native Snapshots: <none included>
```
velero restore 
```
Errors:
Errors:
  Velero:     <none>
  Cluster:  error restoring mutatingwebhookconfigurations.admissionregistration.k8s.io/aks-webhook-admission-controller: MutatingWebhookConfiguration.admissionregistration.k8s.io "aks-webhook-admission-controller" is invalid: webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun"
  Namespaces: <none>

# details 
            could not restore, customresourcedefinitions.apiextensions.k8s.io "volumesnapshotlocations.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "volumesnapshots.snapshot.storage.k8s.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, persistentvolumes "pvc-35350f96-d786-4e28-bd18-727d344d53da" already exists. Warning: the in-cluster version is different than the backed-up version.
```

This happens regardless of weather the namespace is empty or not; Ive tried both scenarios; Ive attempted to restore with restic. Backup constantly succeeds but restore doesnt.  I am not restoring to a different namespace, or a different cluster or a different region. It is the same cluster, I am restoring a namespace and its associated resources.

**Anything else you would like to add:**

I would really like to get this resolved; due to this issue we are looking for alternatives. One of them being Kasten10. I would like to use velero as I have previously and it worked great.

**Environment:**

- helm version (use `helm version`): 
`version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}`
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
velero helm chart appVersion: 1.6.1, csi plugin and azure plugin versions listed above. 
- Kubernetes version (use `kubectl version`):
- 1.19.9 for client/server
- Kubernetes installer & version:
- Cloud provider or hardware configuration: azure aks
- OS (e.g. from `/etc/os-release`):

**Comment by reasonerjt** [comment]
I noticed this error:
```
 error restoring mutatingwebhookconfigurations.admissionregistration.k8s.io/aks-webhook-admission-controller: MutatingWebhookConfiguration.admissionregistration.k8s.io "aks-webhook-admission-controller" is invalid: webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun"
 ```
 
 @fluffyf-x when you do B/R against an empty NS, could you manage to find the backed up resource representing the resource ` mutatingwebhookconfigurations.admissionregistration.k8s.io/aks-webhook-admission-controller: MutatingWebhookConfiguration.admissionregistration.k8s.io "aks-webhook-admission-controller"`?

**Comment by fluffyf-x** [comment]
@reasonerjt: Thanks for responding :) 

I see it listed in the `describe backup --details`
```
Resource List:
  admissionregistration.k8s.io/v1/MutatingWebhookConfiguration:
    - aks-webhook-admission-controller
    - linkerd-proxy-injector-webhook-config
    ...
```
logs show 
```
time="2021-07-07T02:30:26Z" level=info msg="Getting items for resource" backup=velero/nosnapshot group=admissionregistration.k8s.io/v1 logSource="pkg/backup/item_collector.go:165" resource=mutatingwebhookconfigurations
time="2021-07-07T02:30:26Z" level=info msg="Listing items" backup=velero/nosnapshot group=admissionregistration.k8s.io/v1 logSource="pkg/backup/item_collector.go:291" namespace= resource=mutatingwebhookconfigurations
time="2021-07-07T02:30:26Z" level=info msg="Retrieved 2 items" backup=velero/nosnapshot group=admissionregistration.k8s.io/v1 logSource="pkg/backup/item_collector.go:297" namespace= resource=mutatingwebhookconfigurations
```

after going through restores a couple of times on a few different aks clusters; the pvs are definitely something it doesnt seem to restore with `--include-cluster-resources`, and Im consistently hitting [this line](https://github.com/vmware-tanzu/velero/blob/main/pkg/restore/restore.go#L1290) in the code. 

Any assistance is very appreciated.

**Comment by fluffyf-x** [comment]
@reasonerjt: any ideas?

**Comment by fluffyf-x** [comment]
Is there a way to force velero to replace resources in the cluster?

**Comment by dsu-igeek** [comment]
Velero will not replace resources in the cluster.  That's by design.  There's no need to use --include-cluster-resources to get backup/restore of PVs.  The CSI snapshots are still beta, you should use the Azure plug-in snapshots.
