### ISSUE TITLE
Backup skipped PriorityClass even when it is referenced by Pod

### ISSUE THREAD

**Issue by phuongatemc** [vmware-tanzu/velero#3933]
Steps to reproduce:
- Create a PriorityClass "high-priority" as below:
```
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
```
- Create a Pod and specified "priorityClassName" as "high-priority"
- Run Backup with include-cluster-resources set to nil.  log shows that the priorityclasses being skipped
time="2021-07-06T23:01:42Z" level=info msg="Getting items for resource" backup=velero-ppdm/mysql-2021-07-06-16-01-40-mysql group=scheduling.k8s.io/v1 logSource="pkg/backup/item_collector.go:165" resource=priorityclasses
time="2021-07-06T23:01:42Z" level=info msg="Skipping resource because it's cluster-scoped and only specific namespaces are included in the backup" backup=velero-ppdm/mysql-2021-07-06-16-01-40-mysql group=scheduling.k8s.io/v1 logSource="pkg/backup/item_collector.go:192" resource=priorityclasses
- Restore to a different cluster that does not have the PriorityClass "high-priority" ==> Restore failed to restore Pod with error that it cannot find the PriorityClass.

There was an suggestion in Velero community meeting and in the code comments to write a plugin for Pod and return the PriorityClass high-priority as the AdditionalItems to backup.  However, I think such plugin would be a workaround because the main problem is the Backup datapath (getResourceItems in specific) should pick up all resources being referenced by the Pod and backup them accordingly.

**Comment by reasonerjt** [comment]
This can probably be fixed by introducing a backupItemAction in core velero.

**Comment by phuongatemc** [comment]
We actually still need this.  Instead of writing new plugin, we will enhance the currently internal plugin the backup the PriorityClass if the Pod Spec has reference to it.

**Comment by phuongatemc** [comment]
This is discussed in the meeting today.  We still need it.

**Comment by sseago** [comment]
@phuongatemc Yes, that makes sense. While "make it a BackupItemAction" was proposed above, I think using an existing BackupItemAction that's already being run for pods probably makes even more sense, as we don't really need to run a completely separate action to add more than one type of resources as additional items.

**Comment by phuongatemc** [comment]
PR: https://github.com/vmware-tanzu/velero/pull/4740
I will do a little more tests.
