### ISSUE TITLE
Get random failure when running the E2E test cases

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#3970]
Sometimes we get the random failure when running the E2E test cases with the following error:
Error in `[Scale]` test case:
```
Errors while attempting to uninstall Velero: "rate: Wait(n=1) would exceed context deadline
```

Error in the following test cases
```
Error creating resource ServiceAccount/velero: serviceaccounts "velero" is forbidden: unable to create new content in namespace velero because it is being terminated
```

The first error may be caused by that the timeout for velero uninstallation is too short, we can try to increase the time. Because of this error,  the uninstallation operation isn't completed, but the following test cases try to install velero again and get the second error

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by dsu-igeek** [comment]
We can increase the timeout.  Please see if it's possible to fail the entire test suite on uninstall failure so that no additional tests are run.
