### ISSUE TITLE
Velero uninstall command cannot clean up all resources occasionally

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#3974]
The `uninstall` command is implemented by the following logic:
1. delete the `velero` namespace
2. delete all the CRDs

The root cause is that the API call to delete the namespace is an asynchronous process, which means that when we deleting the CRDs the namespace delete operation is still in progress, and the CRDs are needed for the namespace to list all related resources.

This causes some of the resources inside the `velero` namespace may not be cleaned up, and when we install the `velero` again, these remaining resources may affect the velero with unexpected behavior.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by dsu-igeek** [comment]
You've identified the root of the problem.  The original uninstall waited for the namespace deletion to complete, that got removed post 1.6.  Let's put the wait back in.
