### ISSUE TITLE
Turn off spurious "Persistent volume is not a supported volume type for snapshots, skipping."

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#3991]
"Persistent volume is not a supported volume type for snapshots, skipping." is being received when backing up volumes with Restic.  Investigate and turn this message off.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by adthonb** [comment]
I think it's the information log level. In my opinion, you should not disable it for debugging that PV did not support snapshots and it skips PV with our error.
