### ISSUE TITLE
Unable to delete backup after application is uninstalled

### ISSUE THREAD

**Issue by henrychi2** [vmware-tanzu/velero#4009]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Backup stuck Deleting
```
./velero backup get
NAME          STATUS     ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
zen-backup1   Deleting   0        0          2021-07-27 20:50:43 -0700 PDT   362d      default            <none>
```

Logs show that a delete action is re-queued since an application's CRD is missing
```
oc logs velero-564475877c-b5945

time="2021-07-30T13:33:35Z" level=error msg="Error in syncHandler, re-adding item to queue" controller=backup-deletion error="error invoking delete item actions: failed to resolve resource into complete group/version/resource: myhttpsservices.myhttps.cpd.ibm.com: no matches for myhttps.cpd.ibm.com/, Resource=myhttpsservices" error.file="/opt/app-root/src/github.com/vmware-tanzu/velero/internal/delete/delete_item_action_handler.go:78" error.function=github.com/vmware-tanzu/velero/internal/delete.InvokeDeleteActions key=oadp-operator/zen-backup1-njv78 logSource="pkg/controller/generic_controller.go:140"
```

Application CRD was included in the backup
```
./velero describe backup zen-backup1 --details | grep my
    - myhttpsservices.myhttps.cpd.ibm.com
    - zen/https-cr-sample-01-myhttps-1627430502419000
    - zen/https-cr-sample-01-myhttps-1627430502419000-7bbbc65565
  myhttps.cpd.ibm.com/v1/MyhttpsService:
```

Application CRD no longer exists in system since it was uninstalled
```
# oc get crd | grep my
#
```

**What did you expect to happen:**

Backup delete to be successful

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  1.6.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): v1.19.0+e49167a
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): RHEL 8.2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
@henrychi2 is your kubernetes cluster deployed on vSphere?

**Comment by henrychi2** [comment]
Cluster is on OpenShift

**Comment by ywk253100** [comment]
What plugins yon installed with velero?

**Comment by henrychi2** [comment]
Plugins include
velero-plugin-for-aws
openshift-velero-plugin
velero-plugin-for-csi

**Comment by ywk253100** [comment]
This issue happens only for velero with `DeleteItemAction` plugin registered. 

The [code](https://github.com/vmware-tanzu/velero/blob/v1.7.0/internal/delete/delete_item_action_handler.go#L80) tries to resolve the resource via discovery. If the resource is a CR and the corresponding CRD is removed before performing the backup deleting, the resolving fails with error `no matches for ...`.

If anyone want to reproduce this issue, please note there is [a 5 minutes interval](https://github.com/vmware-tanzu/velero/blob/v1.7.0/pkg/cmd/server/server.go#L409) that the discovery can notice the CRD is removed.
