### ISSUE TITLE
velero 1.6.1 helm install - uploads failing

### ISSUE THREAD

**Issue by aceeric** [vmware-tanzu/velero#4038]
I've installed Velero using the helm chart https://github.com/vmware-tanzu/helm-charts/releases/tag/velero-2.23.3 with Minio as the backing S3 service. This is a Rancher cluster with vsphere CSI volume provisioning.

The images I'm deploying into the cluster are:
- velero-plugin-for-vsphere:v1.1.1
- velero-plugin-for-aws:v1.2.0
- backup-driver:v1.1.1
- data-manager-for-plugin:v1.1.1
- velero-velero:v1.6.0

I'm enabling restic in the helm chart. All the restic pods come up - everything starts cleanly. I take a restic backup by annotating two pods: `kubectl -n mynamespace annotate po -lapp=minio backup.velero.io/backup-volumes=data0,data1,data2,data3`. I'm just trying to do a smoke test and backup the PVs for a minio pod in one namespace into a minio bucket in another namespace.
Then:
```
velero backup create mytest --include-namespaces=mynamespace --include-cluster-resources=false 
```
If I do a `velero backup describe`, the phase is `PartiallyFailed`. The output shows a Started and Completed, but the bottom poprtion has:
```
Resource List: <error getting backing resource list: Get https://minio.velero.svc.cluster.local:443/velero/backups/mytest/mytest-resource-list.json.gz?X-AMz-Algorithm=AWS4-HMAC-SHA256&X-Amc-Credential=minio%2F20210816%2Fdefault%2Fs3%2Fawsr_request&X-Amz-Date=20210816T175439Z&X..... dial tcp: lookup minio.velero.svc.cluster.local on NN.NN.NN.NN:53: no such host>

Restic Backups:
  Failed:
    mynamespace/minio-ss-0-0: data0,data1,data2,data3
    mynamespace/minio-ss-0-1: data0,data1,data2,data3
```
If I describe any of the `snapshots`, they have status `UploadFailed`. If I describe any of the `uploads`, the message is uniformly: `Failed to upload snapshot: ivd: (UUID):(UUID) to durable object storage. Prepare for access failed. The error code is 3014. with error code 3014.`

The error seems to emanate from data manager. If I get the logs for one of the `datamgr-for-vsphere-plugin` daemonset pods, I see:
```
Copying snapshot from local to remote repository
Registering a in-progress cancel function
Registering a on-going cancel function
Closing   Response processing in unexpected state: 3
cannot get thumbprint: SSL error code '151141516', exception: Wrong X.509 Certificate format'
Failed at copying remote registry, error=prepare for access failed. The errorr code is 3014. with error code 3014.
```
And then the process retries. My apologies for the detail omission but I'm air gapped.

If I do a strictly metadata backup, it works fine. So Velero is able to talk to the Minio S3 bucket to populate the backup files into it.

We're running Minio on Rancher, and using the Rancher CA in the `kube-root-ca.crt` `ConfigMap` as the Minio CA - both in the Velero namespace, and in the namespace being backed up. It looks like the data mover is not negotating the TLS handshake with the Velero bucket but - I'm not sure. Any help is appreciated. Thank you.

**Comment by zubron** [comment]
Hi @aceeric - I'm not very familiar with the vSphere plugin, but I'll try to help here.

The vSphere plugin is used to take snapshots of vSphere volumes, however you have stated that you are using restic. By annotating the volumes to be backed up using restic, I wouldn't expect the vSphere snapshotter and data mover to be invoked. Do you want to use restic long term or switch to using vSphere snapshots?

This issue may need to be transferred to the vSphere plugin repo as the error is coming from that plugin, and some similar issues have been reported (https://github.com/vmware-tanzu/velero-plugin-for-vsphere/issues/159). One of the comments mentions a solution which was documented here: https://github.com/vmware-tanzu/velero-plugin-for-vsphere/pull/178/files

Could you please take a look and check if the correct permissions have been set?

**Comment by aceeric** [comment]
Thanks @zubron - In the Helm chart I'm specifying two init containers: one using velero-plugin-for-aws:v1.2.0 and the second using velero-plugin-for-vsphere:v1.1.1. We do in fact want to use the vsphere plugin for snapshotting. Possibly in the Helm chart I want to remove `deployRestic: true` (or change to false). My belief is that - even if I have things mis-configured, the vsphere plugin is what is actually doing the snapshotting in this case based on the errors. I will check the permissions and following up. Thanks.

**Comment by dsu-igeek** [comment]
The 3014 error is a permission denied error.  The Velero Plugin for vSphere uses the same account that the vSphere CSI driver is configured with but needs a couple of extra permissions than the bare minimum to take snapshots.  Please refer here: https://code.vmware.com/docs/11750/virtual-disk-development-kit-programming-guide/GUID-8301C6CF-37C2-42CC-B4C5-BB1DD28F79C9.html for permissions.

**Comment by dsu-igeek** [comment]
Closing for now, please re-open if this doesn't help.
