### ISSUE TITLE
An error occurred: backups.velero.io "nginx-backup" already exists

### ISSUE THREAD

**Issue by willzhang** [vmware-tanzu/velero#4046]
## what happend

i failed access s3 ,so i reinstall velero, is it possible rerun a backup?
```
[root@iZj6cc0krt5qucp7c4truyZ ~]# velero backup get
NAME           STATUS   ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
nginx-backup   Failed   0        0          2021-08-18 17:59:53 +0800 CST   29d       default            <none>
```
everytime it failed ,must i delete and run a new one?
```
[root@iZj6cc0krt5qucp7c4truyZ ~]# velero backup create nginx-backup --include-namespaces ns-panda
An error occurred: backups.velero.io "nginx-backup" already exists
```

## what i want
```
velero backup re-run nginx-backup 
```

**Comment by zubron** [comment]
When creating a backup, Velero creates a `Backup` CustomResource in the cluster. These must have unique names, so it is necessary to delete the failed backup or use a different name on the next attempt.

Similar requests have been made for Velero and unfortunately this is not something that we are likely to address soon as a suitable workaround exists and we are focusing on higher priority asks for the project. Please see this issue comment for more details: https://github.com/vmware-tanzu/velero/issues/2458#issuecomment-839765539
