### ISSUE TITLE
Downward API volume cannot be restored by Restic

### ISSUE THREAD

**Issue by wcochran53** [vmware-tanzu/velero#4053]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I installed a pod which made use of a downward Api volume (Note not labelled as a projected volume).

```
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-downwardapi-volume-example
  labels:
    zone: us-est-coast
    cluster: test-cluster1
    rack: rack-22
  annotations:
    build: two
    builder: john-doe
spec:
  containers:
    - name: client-container
      image: k8s.gcr.io/busybox
      command: ["sh", "-c"]
      args:
      - while true; do
          if [[ -e /etc/podinfo/labels ]]; then
            echo -en '\n\n'; cat /etc/podinfo/labels; fi;
          if [[ -e /etc/podinfo/annotations ]]; then
            echo -en '\n\n'; cat /etc/podinfo/annotations; fi;
          sleep 5;
        done;
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations

```
I backed up the pod successfully and then attempted to restore it

The restore partially failed and gave the following error

```
Errors:
  Velero:  pod volume restore failed: error restoring volume: error running restic restore, cmd=restic restore --repo=s3:s3-us-east-1.amazonaws.com/velero-wc-s3/restic/default --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic c6365541 --target=., stdout=restoring <Snapshot c6365541 of [/host_pods/6008c2ad-39a2-4091-aac1-10b4480e85b3/volumes/kubernetes.io~downward-api/podinfo] at 2021-08-19 10:25:07.013272263 +0000 UTC by root@velero> to .
, stderr=ignoring error for /..data: Symlink: symlink ..2021_08_19_10_23_40.834761830 /host_pods/8ebe79ad-8e2e-4b37-b28a-727c01f90294/volumes/kubernetes.io~downward-api/podinfo/..data: file exists
ignoring error for /annotations: Symlink: symlink ..data/annotations /host_pods/8ebe79ad-8e2e-4b37-b28a-727c01f90294/volumes/kubernetes.io~downward-api/podinfo/annotations: file exists
ignoring error for /labels: Symlink: symlink ..data/labels /host_pods/8ebe79ad-8e2e-4b37-b28a-727c01f90294/volumes/kubernetes.io~downward-api/podinfo/labels: file exists
Fatal: There were 3 errors
```

 

**What did you expect to happen:**
The restore to work and either the symlinks to be overwritten or not backed up.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

```
velero restore describe william-cluster-res-downward-2 --details
Name:         william-cluster-res-downward-2
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:                       PartiallyFailed (run 'velero restore logs william-cluster-res-downward-2' for more information)
Total items to be restored:  7
Items restored:              7

Started:    2021-08-19 11:26:51 +0100 BST
Completed:  2021-08-19 11:26:56 +0100 BST

Warnings:
  Velero:     <none>
  Cluster:    <none>
  Namespaces:
    default:  could not restore, services "kubernetes" already exists. Warning: the in-cluster version is different than the backed-up version.

Errors:
  Velero:  pod volume restore failed: error restoring volume: error running restic restore, cmd=restic restore --repo=s3:s3-us-east-1.amazonaws.com/velero-wc-s3/restic/default --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic c6365541 --target=., stdout=restoring <Snapshot c6365541 of [/host_pods/6008c2ad-39a2-4091-aac1-10b4480e85b3/volumes/kubernetes.io~downward-api/podinfo] at 2021-08-19 10:25:07.013272263 +0000 UTC by root@velero> to .
, stderr=ignoring error for /..data: Symlink: symlink ..2021_08_19_10_23_40.834761830 /host_pods/8ebe79ad-8e2e-4b37-b28a-727c01f90294/volumes/kubernetes.io~downward-api/podinfo/..data: file exists
ignoring error for /annotations: Symlink: symlink ..data/annotations /host_pods/8ebe79ad-8e2e-4b37-b28a-727c01f90294/volumes/kubernetes.io~downward-api/podinfo/annotations: file exists
ignoring error for /labels: Symlink: symlink ..data/labels /host_pods/8ebe79ad-8e2e-4b37-b28a-727c01f90294/volumes/kubernetes.io~downward-api/podinfo/labels: file exists
Fatal: There were 3 errors

: exit status 1
  Cluster:    <none>
  Namespaces: <none>

Backup:  william-cluster-bu-downward-2

Namespaces:
  Included:  default
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Restic Restores:
  Failed:
    default/kubernetes-downwardapi-volume-example: podinfo

Preserve Service NodePorts:  auto

```
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This is the same restic  issue that was indicated as fixed for projected volumes in release 1.6.1. 
https://github.com/vmware-tanzu/velero/issues/3863
The problem is that downward api volumes are not exclusively created using projected volumes.

**Environment:**

- Velero version (use `velero version`):
 velero version
Client:
	Version: v1.6.2
	Git commit: 8c9cdb9603446760452979dc77f93b17054ea1cc
Server:
	Version: v1.6.3
- Velero features (use `velero client config get features`):  features: <NOT SET>
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T03:27:49Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
- Cloud provider or hardware configuration:aws
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment]
Thank you for raising this and providing an example. We did have an issue open to check how Velero interacted with Downward API volumes (https://github.com/vmware-tanzu/velero/issues/3872), and now we know! We should be skipping these like we do with Secret/Config/Projected volumes. We will also need to add a check to not restore these like we did in the fix for #3863.
