### ISSUE TITLE
Velero should support incremental restores

### ISSUE THREAD

**Issue by pradeep288** [vmware-tanzu/velero#4066]
**Describe the problem/challenge you have**
Currently, Velero doesn't support incremental  restore.  What i mean by incremental is if I have restored X already and after some time if i want to restore X+ delta X, velero doesn't have support for this.

**Describe the solution you'd like**
During restore, Velero should find difference between X and  X+ DeltaX and should restore only DeltaX.

**Environment:**

- Velero version (use `velero version`): 1.6.1
- Kubernetes version (use `kubectl version`):1.20
- Kubernetes installer & version:1.20
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):MAC

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
@pradeep288 thanks for the issue.
I'm relatively new to this project, but I found this piece of code:
https://github.com/vmware-tanzu/velero/blob/main/pkg/restore/restore.go#L1240
It seems velero DOES try to modify the resource even it exists during the restore.

Could you please give us a more concrete example regarding the `incremental restore` what kind of resource is failed to be restored when you tried it and what's in the `delta X` ?

**Comment by sseago** [comment]
@reasonerjt If it already exists, the code below that line determines whether the in-cluster resource is different than the resource in the backup. However, only service accounts are actually patched when differences are found. For everything else, the difference between the cluster version being the same and it being different from the backup just changes the log message. Velero doesn't currently attempt to update resources in the general case. When velero runs a restore and there are non-serviceaccount resources that already exist in the cluster, you'll see in velero logs the message from this line:
https://github.com/vmware-tanzu/velero/blob/main/pkg/restore/restore.go#L1290

**Comment by pradeep288** [comment]
**Backup of X:**

Create a source cluster called A
Create a namespace called pradeep-draas
Create a deployment called example with replicas =3
Install Velero and take the backup(b1) using Velero
Create a target Target Cluster called B
Install velero and verify backup b1 exists.
restore the backup (b1) using velero
Ensure namespace pradeep-draas and example with replicas =3 gets restored.

**Backup of X + Delta:**

Switch to cluster A.
Switch to namespace pradeep-draas
Increase the replicas of the example from 3 to 4
Take the backup*(b2)* using Velero
Switch to cluster B.
verify backup b2 exists.
restore the backup(b2) using velero
Ensure namespace pradeep-draas and example with replicas =4 gets restored.
Actual Result:

Velero restores 4 pods but doesn't change the replicaSet with this hence we end up with 3 replicas as replicaSet kills extra pod

```
Namespaces:
    pradeep-draas:  could not restore, configmaps "kube-root-ca.crt" already exists. Warning: the in-cluster version is different than the backed-up version.
                    could not restore, pods "example-d6dcb985-2k6q8" already exists. Warning: the in-cluster version is different than the backed-up version.
                    could not restore, pods "example-d6dcb985-jpsdv" already exists. Warning: the in-cluster version is different than the backed-up version.
                    could not restore, pods "example-d6dcb985-n6kbf" already exists. Warning: the in-cluster version is different than the backed-up version.
                    could not restore, pods "example-d6dcb985-xhvjn" already exists. Warning: the in-cluster version is different than the backed-up version.
                    could not restore, replicasets.apps "example-d6dcb985" already exists. Warning: the in-cluster version is different than the backed-up version.
                    could not restore, deployments.apps "example" already exists. Warning: the in-cluster version is different than the backed-up version.
```

**Comment by dsu-igeek** [comment]
In general we have avoided this because it has the potential to seriously disrupt a working cluster.  Our general advice has been to restore into a new cluster/namespace rather than trying to overwrite an existing installation.  The opposite problem of what you are describing may happen in that case - for example you have increased your replica set to 5 after the backup and 4 was in the backup.  At that point, if we are modifying resources, we would set it back to 4.

@pradeep288 Would you give some examples of use cases for why you would to modify an existing installation with a restore rather than simply creating a new install?

**Comment by codegold79** [comment]
**Some initial thoughts on tackling this issue**

Velero restore uses dynamic client from client-go to create backed up objects on the destination cluster.

Currently, the method called on the dynamic client is "Create" located in [restore.go line 1234](https://github.com/vmware-tanzu/velero/blob/de0fe7ff67c1d9782c20c5b0c90fca7d292cc39e/pkg/restore/restore.go#L1234). Perhaps for this issue, I can create a `velero restore` command flag, `--override` that will instead use client-go's "Update" method:  https://github.com/kubernetes/client-go/blob/2f5d8b0c528db5467159baccddc3f634fcea0747/dynamic/simple.go#L146

**Comment by dymurray** [comment]
I would like to see this feature pushed forwards. I would see some benefit in being able to have more granular control over the backup/restore process to force the updates to a certain subset of resources.

**Comment by dymurray** [comment]
What work is left here for 1.10? My understanding is that `ExistingResourcePolicy` satisfies this use case as you can now restore the delta of the resources in the cluster.

**Comment by reasonerjt** [comment]
I agree with @dymurray 

@pradeep288 could you clarify?

**Comment by lxs137** [comment]
Is `ExistingResourcePolicy=update` means bypass the immutable field validation protection

**Comment by shubham-pampattiwar** [comment]
@lxs137 Not exactly, if you set it to update and you are trying to update an immutable spec then the restore will error for that particular k8s resource.

**Comment by panpan0000** [comment]
@codegold79  your scenario is very good use case of velero: to build a Active-standby cluster. so far thanks to `ExistingResourcePolicy` we come more closer to that goal !

@dymurray  I think the other thing left is some kind of more flexiable "override-policy" --- 
so far only image/sc can be altered when restore(refer to https://velero.io/docs/main/restore-reference/#changing-poddeploymentstatefulsetdaemonsetreplicasetreplicationcontrollerjobcronjob-image-repositories) 
but changing the `pod replicas` to zero or smaller value,  is the need for this scenario.

we can learn from karmada , which provides powerful "override policy"

**Comment by lizhifengones** [comment]
https://github.com/vmware-tanzu/velero/discussions/6867#discussioncomment-7106006

Restoring data in situ should be a very common scenario? Would we consider it?
