### ISSUE TITLE
Improvement: get the latest successful backup for a schedule, not using sort function

### ISSUE THREAD

**Issue by jacklu1024** [vmware-tanzu/velero#4092]
Right now the code to get the latest successful backup for a schedule is to do a timestamp sort first, and then get the latest completed one.

code here: https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/restore_controller.go#L375-L396

In the case of a very long list of backup for a schedule, like a hourly backup that lasts for a year, this sort would be too heavy.
For this case, we could just iterate through the list once, ignore the ones that not completed, and get the latest timestamp one from this list, with O(1) time complexity, instead of a quick sort O(n log n).

If any reviewer thinks this is good to improve, I could have a colleague or myself improve this.

Thanks.

**Comment by dsu-igeek** [comment]
That's going to be O(n) not O(1) (you're iterating over every object in the list).  That's quicker than O(n log n) but not significantly.  With 1 year of hourly backups, that will be 6360 items to sort which, given that the comparison take 1 microsecond (super slow), would be about 55 milliseconds for O(n ln n) and about 6 milliseconds for iteration.  This is not an issue and your proposed solution does not offer significant improvement.

**Comment by jacklu1024** [comment]
Thanks for answering this, and yes it is O(n).

**Comment by jacklu1024** [comment]
Agree O(n) is not much improvement than O(n logn).  And we know quick sort worst case time complexity is O(n *n), so for a 10000 item list, O(n) will use 10 milliseconds, and O (n *n) will use 100 seconds, in worst case.  I understand it is not easy to hit such worst case, so ok to keep it unchanged.
