### ISSUE TITLE
Support updating existing resources on restore

### ISSUE THREAD

**Issue by peterwiggers** [vmware-tanzu/velero#4094]
**Describe the problem/challenge you have**
When executing a restore, velero does not update a resource that already exists. For example, if I change the number of replicas for a deployment, create a backup and restore that backup in a cluster that already has this deployment (from a previous restore), then velero will refuse to update the resource:

```
could not restore, deployments.apps "myapp" already exists. Warning: the in-cluster version is different than the backed-up version.
```

**Describe the solution you'd like**
I'd like velero to update the resource, if it already exists. Just like `kubectl apply`.

**Anything else you would like to add:**
The reason I want to do this, is that I want to keep two clusters in sync, where one is the master and the other the slave. So I'll configure velero to periodically create a backup in the master cluster, and periodically restore the backup in a slave cluster.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by dsu-igeek** [comment]
That's not a use case we're trying to support at the moment.  We are going to be opening up the Velero internals with APIs that would make an rsync style operation more possible, we really want to keep "restore" pretty safe so that if someone tries to restore into the wrong place it doesn't go bad.  I'm going to leave this open but we're not going to take any action in the near term.
