### ISSUE TITLE
Cannot restore "service" with velero build from the main branch

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#4098]
Run restore with velero built from the main branch, get the following errors:
```
error restoring services/kibishii-workload/etcd-client: Service "etcd-client" is invalid: spec.clusterIPs: Invalid value: []string{"100.70.53.8"}: must be empty when clusterIP is empty
error restoring services/kibishii-workload/etcd0: Service "etcd0" is invalid: spec.clusterIPs: Invalid value: []string{"100.66.73.184"}: must be empty when clusterIP is empty
error restoring services/kibishii-workload/etcd1: Service "etcd1" is invalid: spec.clusterIPs: Invalid value: []string{"100.69.23.44"}: must be empty when clusterIP is empty
error restoring services/kibishii-workload/etcd2: Service "etcd2" is invalid: spec.clusterIPs: Invalid value: []string{"100.64.23.70"}: must be empty when clusterIP is empty
```

This is caused by that we bumped up the version of library `k8s.io/api/core/v1` from `v0.19.12` to `v0.20.9` in PR #4022.
There is a new property `ClusterIPs` introduced in `v0.20.9` https://github.com/kubernetes/api/blob/v0.20.9/core/v1/types.go#L4098 and the restore action empties the `ClusterIP` but not for `ClusterIPs` https://github.com/vmware-tanzu/velero/blob/main/pkg/restore/service_action.go#L56

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kycfeel** [comment]
I also noticed this issue too. The services cannot be restored due to:

```
error restoring services/<MY_NAMESPACE>/<MY_SERVICE>: Service "<MY_SERVICE>" is invalid: spec.clusterIPs: Invalid value: []string{"<MY_CNI_IP>"}: must be empty when clusterIP is empty
```

this error.
