### ISSUE TITLE
Expand the "Basic" test case to cover more resources when doing the backup/restore

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#4099]
We run the `Basic` test case on PR's checking but the `Basic` test case only covers the backup/restore of namespaces, this isn't enough to find the potential bugs introduced by the PR, #4098 is a good example.

So we need to expand the `Basic` test case to cover more resources:
1. Run the backup/restore with the kibishii but don't backup volumes(the kind doesn't support backup volumes via both restic or snapshot)
2. Consider the changes in https://github.com/vmware-tanzu/velero/pull/3982 and https://github.com/vmware-tanzu/velero/pull/3944
 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
If we need to make a choice between 1 and 2, I'd vote 2 b/c the scenario in 1 has been covered in other cases.
