### ISSUE TITLE
velero 1.6.2 backup failed with velero plugin for vsphere

### ISSUE THREAD

**Issue by liyan-su** [vmware-tanzu/velero#4103]
**What steps did you take and what happened:**
1. install velero
`
1) kubectl create secret generic vsphere-config-secret --from-file=csi-vsphere.conf --namespace=kube-system
2) velero install --image xxx/vmware-tanzu/velero:v1.6.2_vmware.1 --provider aws --bucket velero --secret-file ./credentials-velero --plugins "xxx/vmware-tanzu/velero-plugin-for-aws:v1.2.1_vmware.1" --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://20.20.x.90:9000,publicUrl=http://20.20.x.90:9000 --snapshot-location-config region=minio
3) velero plugin add xxx/vmware-tanzu/velero-plugin-for-vsphere:v1.1.1_vmware.1
`
2. velero backup failed
`bk-step10-1         PartiallyFailed   2        100        2021-09-02 10:21:57 +0000 UTC   29d       default            <none>`
3. 

**What did you expect to happen:**
successed

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
`time="2021-09-02T08:15:35Z" level=error msg="Error executing hook" backup=velero/bk-1 error="error dialing backend: dial tcp 20.20.1.21:10250: i/o timeout" hookPhase=post hookSource=annotation hookType=exec logSource="internal/hook/item_hook_handler.go:206" name=postgres-wl-42-0 namespace=pv-ns-2 resource=pods
time="2021-09-02T08:15:35Z" level=info msg="1 errors encountered backup up item" backup=velero/bk-1 logSource="pkg/backup/backup.go:427" name=postgres-wl-42-0
time="2021-09-02T08:15:35Z" level=error msg="Error backing up item" backup=velero/bk-1 error="error dialing backend: dial tcp 20.20.1.21:10250: i/o timeout" logSource="pkg/backup/backup.go:431" name=postgres-wl-42-0
time="2021-09-02T08:15:35Z" level=info msg="Backed up 45 items out of an estimated total of 374 (estimate will change throughout the backup)" backup=velero/bk-1 logSource="pkg/backup/backup.go:394" name=postgres-wl-42-0 namespace=pv-ns-2 progress= resource=pods
time="2021-09-02T08:15:35Z" level=info msg="Processing item" backup=velero/bk-1 logSource="pkg/backup/backup.go:354" name=postgres-wl-52-0 namespace=pv-ns-2 progress= resource=pods
time="2021-09-02T08:15:35Z" level=info msg="Backing up item" backup=velero/bk-1 logSource="pkg/backup/item_backupper.go:121" name=postgres-wl-52-0 namespace=pv-ns-2 resource=pods
time="2021-09-02T08:15:35Z" level=info msg="running exec hook" backup=velero/bk-1 hookCommand="[/sbin/fsfreeze --freeze /var/lib/postgresql/data]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=pre hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:124" name=postgres-wl-52-0 namespace=pv-ns-2 resource=pods
time="2021-09-02T08:15:35Z" level=info msg="stdout: " backup=velero/bk-1 hookCommand="[/sbin/fsfreeze --freeze /var/lib/postgresql/data]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=pre hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:171" name=postgres-wl-52-0 namespace=pv-ns-2 resource=pods`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
`root@02d4b4d43fa3:~/liyan-pst/testcases/scalability/1.12.0/velero/report# velero backup describe bk-step10-1
Name:         bk-step10-1
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.21.3+vmware.1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=21

Phase:  PartiallyFailed (run `velero backup logs bk-step10-1` for more information)

Errors:    2
Warnings:  100

Namespaces:
  Included:  pv-ns-1, pv-ns-2, pv-ns-3, pv-ns-4, pv-ns-5, pv-ns-6, pv-ns-7, pv-ns-8, pv-ns-9, pv-ns-10
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-09-02 10:21:57 +0000 UTC
Completed:  2021-09-02 10:42:38 +0000 UTC

Expiration:  2021-10-02 10:21:57 +0000 UTC

Total items to be backed up:  940
Items backed up:              940

Velero-Native Snapshots: <none included>`
- `velero backup logs <backupname>`
`time="2021-09-02T10:27:09Z" level=error msg="Error executing hook" backup=velero/bk-step10-1 error="command terminated with exit code 1" hookPhase=pre hookSource=annotation hookType=exec logSource="internal/hook/item_hook_handler.go:206" name=postgres-wl-42-0 namespace=pv-ns-2 resource=pods
time="2021-09-02T10:27:09Z" level=error msg="Error backing up item" backup=velero/bk-step10-1 error="command terminated with exit code 1" logSource="pkg/backup/backup.go:437" name=postgres-wl-42-0
time="2021-09-02T10:27:09Z" level=info msg="Backed up 73 items out of an estimated total of 988 (estimate will change throughout the backup)" backup=velero/bk-step10-1 logSource="pkg/backup/backup.go:394" name=postgres-wl-42-0 namespace=pv-ns-2 progress= resource=pods
time="2021-09-02T10:27:09Z" level=info msg="Processing item" backup=velero/bk-step10-1 logSource="pkg/backup/backup.go:354" name=postgres-wl-52-0 namespace=pv-ns-2 progress= resource=pods
time="2021-09-02T10:27:09Z" level=info msg="Backing up item" backup=velero/bk-step10-1 logSource="pkg/backup/item_backupper.go:121" name=postgres-wl-52-0 namespace=pv-ns-2 resource=pods
time="2021-09-02T10:27:09Z" level=info msg="running exec hook" backup=velero/bk-step10-1 hookCommand="[/sbin/fsfreeze --freeze /var/lib/postgresql/data]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=pre hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:124" name=postgres-wl-52-0 namespace=pv-ns-2 resource=pods`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
`Client:
        Version: v1.6.2_vmware.1
        Git commit: 8c9cdb9603446760452979dc77f93b17054ea1cc
`
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): v1.21.3
- Kubernetes installer & version:
- Cloud provider or hardware configuration:  
- OS (e.g. from `/etc/os-release`):ubuntu 18.04.3

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by dsu-igeek** [comment]
It looks like your fsfreeze hook is failing.  If you are using the snapshotter there is no need to freeze/unfreeze the file system so I would just remove the hook.  If you want to try to debug it, you could try running /sbin/fsfreeze command with kubectl exec in the appropriate pod.  If you continue to have issues, please include the complete log file, not snippets.  Closing for now, re-open if you need additional help.
