### ISSUE TITLE
Velero backup issue on Azure Redhat Openshift cluster - Authorization issue

### ISSUE THREAD

**Issue by sabarivijay88** [vmware-tanzu/velero#4105]
Installed Velero but backup is failing due to some authorization error Azure Redhat Openshift 4.7 cluster,

Error details:

[root@spapnlti01 ~]# velero backup logs test11
An error occurred: request failed: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:6b7083eb-501e-0049-78b5-a031ed000000
Time:2021-09-03T11:16:28.7949799Z</Message></Error>

**What did you expect to happen:**
Need to run successful backup

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`- 
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`
Logs has been attached here for further analysis.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:** - Azure Redhat Openshift 4.7

-Client:
        Version: v1.6.0
        Git commit: 5bd70fd8eef316d220317245e46dc6016c348dce
Server:
        Version: v1.6.0

[root@spapnltispjmp01 ~]# oc version
Client Version: 4.7.12
Server Version: 4.7.24
Kubernetes Version: v1.20.0+558d959
[Velero logs.txt](https://github.com/vmware-tanzu/velero/files/7105505/Velero.logs.txt)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by dsu-igeek** [comment]
The Velero CLI needs permissions to create custom resources in the `velero` namespace.  Please ensure that you have the correct Kubernetes permissions to read/write resources.  You should be able to use the same Kubernetes context you used to install Velero.  Closing for now, please re-open if you continue to have issues, but we have limited ability to debug your Kubernetes installation.

**Comment by sabarivijay88** [comment]
Hi,

I am configuring backup & restore option using OADP operator on Openshift 4.7 and facing issues while creating Konveyor CR,

[root@spapnltispjmp01 ~]# oc get all -n oadp-operator
NAME                                 READY   STATUS    RESTARTS   AGE
pod/oadp-operator-68b4f7598c-6jtbg   1/1     Running   0          65m
pod/restic-5kkkf                     1/1     Running   0          16m
pod/restic-5n2qd                     1/1     Running   0          16m
pod/restic-7g5f5                     1/1     Running   0          16m
pod/restic-dm5bh                     1/1     Running   0          16m
pod/restic-mtdnp                     1/1     Running   0          16m
pod/restic-zph55                     1/1     Running   0          16m
pod/velero-55fcbbc6f9-l6khg          1/1     Running   0          16m

NAME                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/restic   6         6         6       6            6           <none>          16m

NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/oadp-operator   1/1     1            1           65m
deployment.apps/velero          1/1     1            1           16m

NAME                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/oadp-operator-68b4f7598c   1         1         1       65m
replicaset.apps/velero-55fcbbc6f9          1         1         1       16m

Service is not coming up and trying to configure backup location on azure cloud,

It will be really helpful if you share me the details about konveyor.openshift.io_veleros_crd.yaml  for azure cloud.

I am seeing configuration for aws everywhere and need assistance to configure it on azure cloud.
