### ISSUE TITLE
Provide alternate image registry to dockerhub

### ISSUE THREAD

**Issue by onedr0p** [vmware-tanzu/velero#4106]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]

Hello,

In order to combat dockerhub's imposed rate limits it would be great to host these images on ghcr or quay.io. Are there on any thoughts from the community on this initiation?

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
We may consider to move the images to other registries in the future release.
Please refer to the comment of https://github.com/vmware-tanzu/velero/issues/3871 to workaround this

**Comment by onedr0p** [comment]
Not stale

**Comment by onedr0p** [comment]
Not stale

**Comment by onedr0p** [comment]
I do not use velero anymore and there looks to be zero interest in support another docker registry, closing...
