### ISSUE TITLE
Provide option to edit backup schedule

### ISSUE THREAD

**Issue by pradeepkchaturvedi** [vmware-tanzu/velero#4114]
User wants to edit backup schedule to support blackout window or pause backups for specified duration. 

User wants to Update Schedule CRD, does Velero controller in cluster acts on update for Schedule CRD? User can edit daily backup schedule to Monthly when want to pause backups for few days and then change schedule back to Daily later.

**Comment by ywk253100** [comment]
You can patch the schedule directly, I tried it in my local environment, it works:
```
kubectl patch schedule schedule-name -n velero -p '{"spec":{"schedule":"@every 1m"}}' --type=merge
```
