### ISSUE TITLE
Feature: Allowing arbitrary combinations of include/exclude namespaces, resources and labels

### ISSUE THREAD

**Issue by ThomasSteinbach** [vmware-tanzu/velero#4123]
**Describe the problem/challenge you have**

I would like to backup resources from different namespaces which also have - due to limitations of helm - different labels. Also I would like to include/exclude resources depending on the namespace.

**Describe the solution you'd like**

With Velero it should be possible to

* define resources and label selectors per namespace
* allow conjunction (AND) and disjunction (OR) of label selectors
  * Backup resources with label x and label y
  * Backup resources with either label a OR label b

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
IMHO, allowing arbitrary combinations of include/exclude namespaces, resources and labels is complicated for users to configure the backup rules. Instead, you can apply some customized labels to all resources that need to be back up before performing the backup operation.
But let's see how other community users think about it

**Comment by ThomasSteinbach** [comment]
Thanks for your thoughts @ywk253100 , the problem with labels is that some helm charts are really nasty, as they

* Provide Custom Resource Definitions not properly labeled
* The Docker Containers itself create K8s resources (like config maps) not properly labeled

That is the case for Traefik or Gitlab, as an example.

It would be then easy to backup the whole namespace, the resources reside in. Additionally I want to back up some resources in another namespace, identified by labels. That could be the velero schedules for instance ;) Those shedules have to be defined in the `velero` namespace.
