### ISSUE TITLE
OADP Operator installation - Issue with velero instance creation on azure cloud

### ISSUE THREAD

**Issue by sabarivijay88** [vmware-tanzu/velero#4130]
Hi,

I am configuring backup & restore option using OADP operator on Openshift 4.7 and facing issues while creating Konveyor CR,

[root@spapnltispjmp01 ~]# oc get all -n oadp-operator
NAME READY STATUS RESTARTS AGE
pod/oadp-operator-68b4f7598c-6jtbg 1/1 Running 0 65m
pod/restic-5kkkf 1/1 Running 0 16m
pod/restic-5n2qd 1/1 Running 0 16m
pod/restic-7g5f5 1/1 Running 0 16m
pod/restic-dm5bh 1/1 Running 0 16m
pod/restic-mtdnp 1/1 Running 0 16m
pod/restic-zph55 1/1 Running 0 16m
pod/velero-55fcbbc6f9-l6khg 1/1 Running 0 16m

NAME DESIRED CURRENT READY UP-TO-DATE AVAILABLE NODE SELECTOR AGE
daemonset.apps/restic 6 6 6 6 6 16m

NAME READY UP-TO-DATE AVAILABLE AGE
deployment.apps/oadp-operator 1/1 1 1 65m
deployment.apps/velero 1/1 1 1 16m

NAME DESIRED CURRENT READY AGE
replicaset.apps/oadp-operator-68b4f7598c 1 1 1 65m
replicaset.apps/velero-55fcbbc6f9 1 1 1 16m

Service is not coming up and trying to configure backup location on azure cloud,

It will be really helpful if you share me the details about konveyor.openshift.io_veleros_crd.yaml for azure cloud.

I am seeing configuration for aws everywhere and need assistance to configure it on azure cloud.

**Comment by sseago** [comment]
If this is for oadp-specific configuration issues, it would probably be better to submit an issue under the OADP operator repo: https://github.com/openshift/oadp-operator/issues

In particular, anything relating to the oadp velero configuration CR would be better submitted there than here.

**Comment by sabarivijay88** [comment]
Thanks for your update,

I have raised new issue under OADP operator repo and thanks again.
