### ISSUE TITLE
Do not clean up the resources in the end-to-end testing when get case failure for easy debugging

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#4149]
Currently, all created resources(velero, kibishii workload) are cleaned up no matter the test case failed or not in the end-to-end testing.

We see the `Error verifying kibishii after restore: Failed to verify data generated by kibishii: failed to verify, stderr=/usr/local/bin/verify.sh: line 26: [: : integer expression expected` error several times in the recent nightly testing, but cannot reproduce it manually which is frustrating.

IMO we should keep the resources there when the case is failed for easy further debugging. Although we have dumped the logs with `velero debug` command, keep velero there is still an easier way to get more information other than the logs
Several tasks for achieving this:
- [x] Install velero once for different test cases and do not clean up it after the testing. 
As different test cases may need different velero installation options(e.g. the `APIGroup` case needs to enable the API group feature, the `Upgrade` case needs to reinstall a new version), we need to organize the test cases into several groups based on that and run the groups in different suites
- [ ] Install the kibishii workload in different namespaces for different cases and do not clean up it if the case is failed

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by danfengliu** [comment]
Close it as PR #4801 merged.
