### ISSUE TITLE
Provide more details in documentations on how restore works

### ISSUE THREAD

**Issue by pradeepkchaturvedi** [vmware-tanzu/velero#4150]
Velero documentation does not provide enough details in how restore works https://velero.io/docs/v1.6/how-velero-works/#restores
1. There can be more details on what happens when during restore operation there are resource objects exists in cluster and backup both. Would restore copy objects from backup, would restore skip, would restore merge the object
2. Would Velero restores cluster to backed up state i.e would restore delete objects create after backup
3. If there are objects in cluster with missing annotations/labels and backup has the same objects, would Velero update the cluster resource objects and add missing annotation/labels. does Velero merges changes from backup to cluster objects. If yes, how does it resolves conflicts
4. Does Velero checks the API version for the object and does it affects restore operation
4. What happens if during restore required storage is missing on the target cluster, how does PVs restore affects
5. Does Velero backup and restore objects not in namespace

**Comment by DrumSergio** [comment]
AWS added some documentation about the restore process already, ahead of Velero itself: https://aws.amazon.com/blogs/containers/backup-and-restore-your-amazon-eks-cluster-resources-using-velero/

**Comment by a-mccarthy** [comment]
@Lyndon-Li hi! just checking on this, do you have a rough idea on when you will have time to work on it? Is there anything i can help with? thanks!!

**Comment by Lyndon-Li** [comment]
@a-mccarthy I will start this work next week. I am not sure if we have a template for this kind of document, if so, please help to share it. If not, I will try to create the document by following my own idea first then I will send it to you for your review. Thanks.

**Comment by a-mccarthy** [comment]
@Lyndon-Li sorry for my delayed response on this, we dont have a template at the moment.

**Comment by Lyndon-Li** [comment]
@a-mccarthy It is ok. The draft doc has been completed and shared.
Please help to review it and compose the official doc based on it. For anything more is required or any question, please just comment on the doc.

Thanks.
