### ISSUE TITLE
Restic and Volume snapshot examples in Velero documentation

### ISSUE THREAD

**Issue by pradeepkchaturvedi** [vmware-tanzu/velero#4151]
Installed Velero with below options,
- deployRestic = true
- snapshotsEnabled = true
- configured DefaultSnapshotLocation details
- Not used -default-volumes-to-restic_ flag (using Opt-in approach)
- It would install Restic
- Added few more Backup Storage Locations and Volume Snapshot Locations. 

Restic uses which credential? Credentials created for VolumeSnapshotLocation or Credentials created for BackupStorageLocation

During cluster Backup, How Velero works in each case
1. if there are no pods with annotation. what would happen
- If there are volumes matching with Volume Snapshot Locations provider and matching credentials type
- If no volumes have Volume Snapshot Locations provider and matching credentials type

2. if there are few pods have annotation and few does not have annotation. what would happen
- If there are volumes not having annotation, matches with Volume Snapshot Locations provider and matching credentials type
- If there are few volumes having restic annotation and snapshot location credential type(stored in the cloud-credentials secret) does not match with Pod volumes provider type
- If there are few volumes having restic annotation and snapshot location credential type matches with Pod volumes provider type
- If there few volumes does not annotation and either Volume Snapshot Locations provider type does not match or credentials type does not match

3. If all pods have annotation. what would happen
- If there are few volumes having restic annotation and snapshot location credential type(stored in the cloud-credentials secret) does not match with Pod volumes provider type
- If there are few volumes having restic annotation and snapshot location credential type matches with Pod volumes provider type

It would be great, if we can get example and expected result. 

It seems if restic is enabled with Opt-in approach and there no pods having annotation as well as default credential type does not match, backup itself fails.

**Comment by qiuming-best** [comment]
1.  For Velero, If having multiple VSL, It should specify which volume snapshot location to associate with, whether using resitc or volume snapshot, or it will fail

2.  If specify using volume snapshot in setup
    - Specify nothing, it will be failed as reason 1
       - Specify using restic when creating backup, volume snapshot in setup will be overwritten and using restic
       - Specify using volume snapshot and matched VSL, velero will use volume snapshot
       - Unmatched VSL and using volume snapshot will be failed


3.  If specify using restic in setup
    -  Specify nothing, it will be failed as reason 1
       - Once specify volume snapshot, whether is matching or not, velero will use restic to do backup. Using restic in setup cloud not be overwritten
       - Specify using restic, velero will use restic


4.  Not specified in the setup
    - Specify nothing, it will be failed as reason 1
       - Specify using restic, velero will be using restic
       - Specify using volume snapshot, velero will be using volume snapshot
       -  Annote pod with the opt-in approach will be using restic
       - Specify using volume snapshot and  matched VSL, velero will be using volume snapshot
       - Unmatched VSL and using volume snapshot will be failed

**Comment by qiuming-best** [comment]
@pradeepkchaturvedi @a-mccarthy I've commented

**Comment by qiuming-best** [comment]
[here](https://docs.google.com/document/d/1w4UTJmdZf5cllwvSOdMFx6Yy_e8VZew1k-JigLN2rbI/edit#heading=h.yp9a4f2dyqw2) is the detail document
