### ISSUE TITLE
The debug command failed if the backup/restore log file doesn't exist

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#4157]
If the specified backup or restore log file doesn't exist, running `velero debug --backup` or `veleo debug --restore` will fail.

The backup/restore may fail without uploading the log file or the backup/restore is hang, when users want to run `velero debug` to do debugging in these two cases, the failed command isn't the expected behavior

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
This has a dependency in `crashd`, in the script it calls function `capture_local(velero backup log ....)` to get the backup log.
But the function will throw exception and stop the script from executing if the command returns an error.

I chatted with crashd's maintainer, and he agrees this is a problem, I've opened issue:
https://github.com/vmware-tanzu/crash-diagnostics/issues/219

**Comment by reasonerjt** [comment]
deferring this to post-1.7 due to the depedency.

**Comment by reasonerjt** [comment]
I verified that this will be fixed once #4315 is merged.

**Comment by reasonerjt** [comment]
Closing.
