### ISSUE TITLE
Please add support for azure incremental snapshots to reduce cloud storage costs

### ISSUE THREAD

**Issue by daniloasfigueiredo** [vmware-tanzu/velero#4163]
https://azure.microsoft.com/pt-br/blog/introducing-cost-effective-increment-snapshots-of-azure-managed-disks-in-preview/

**Comment by reasonerjt** [comment]
There may be some trade-off so we wanna refrain from doing incremental snapshot by default

@eleanor-millman 

let's discuss and decide if we want to put this on the roadmap.

**Comment by eleanor-millman** [comment]
Sounds good, @reasonerjt ! Will put on the agenda for the community meeting next week. 

Also, I briefly had https://github.com/vmware-tanzu/velero/issues/4225 open (it is a dupe) but worthwhile to note that it had three upvotes in just a few days.

**Comment by ywk253100** [comment]
The incremental snapshot is supported already since velero azure plugin 1.1.1. Refer to https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/52 for more details
