### ISSUE TITLE
Negative selector not working

### ISSUE THREAD

**Issue by daniloasfigueiredo** [vmware-tanzu/velero#4164]
Hi, we are using the last velero version, ans the negative selector is not working properly, the backup schedule copy all pvcs without any filter. 

velero backup create nginx-backup --selector 'backup notin (ignore)'

Is another way to configure a exclusion based on labels?

**Comment by zubron** [comment]
Hi @daniloasfigueiredo - We'll need more information to diagnose this as I am unable to reproduce this locally.

Could you please provide the following:
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`

Also, could you please provide the yaml for any of the PVC resources that are incorrectly being included in the backups so we can see the labels? `kubectl get pvc <pvcname> -o yaml`
Thanks!

**Comment by daniloasfigueiredo** [comment]
Hi @zubron , thanks your quick response. 

I created the backup schedule with --exclude-namespaces and worked pretty well, and it not more necessary to use negative selector, many thanks.
