### ISSUE TITLE
Partial persistent volume backup

### ISSUE THREAD

**Issue by krzema12** [vmware-tanzu/velero#4167]
### Discussed in https://github.com/vmware-tanzu/velero/discussions/4165

<div type='discussions-op-text'>

<sup>Originally posted by **krzema12** September 20, 2021</sup>
We're researching options for performing a backup of a subset of Cassandra tables. Each table is expressed at least as a certain subtree of files on Cassandra's persistent volume. I'm looking at `--exclude-resources` but it seems to handle only k8s resources, and is not granular enough to point to individual files or directories. Does Velero support creating such partial backup? If no, any fallback ideas that come to your head?</div>

**Comment by reasonerjt** [comment]
Per my understanding, it's not supported, the k8s resources are the units velero handles.

**Comment by dsu-igeek** [comment]
We're moving to using volume snapshots in many cases and that will not support partial backups.  This seems like something that would be better handled using the C* backup.  Eventually we want to integrate better with things like C* backup but that's a future.
