### ISSUE TITLE
Generate "caymanized" builds for 1.7.0

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#4176]
Build the caymanized (signed) versions of the Velero containers and CLI and deliver to Bohan. Also, generate the same for the latest plugin releases.

- [ ] Velero containers/CLI
- [ ] AWS plugin
- [ ] Azure plugin

**Comment by zubron** [comment]
Edited to add the plugins that correspond with this release.

**Comment by danfengliu** [comment]
It's done already.
