### ISSUE TITLE
Document the process of pinning the base image in our Dockerfiles

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/velero#4184]
> How about adding a comment to explain which tag is the digest comes from?

_Originally posted by @ywk253100 in https://github.com/vmware-tanzu/velero/pull/4180#r713774306_

We should add the comment and check for any other documentation that should be updated.

**Comment by reasonerjt** [comment]
I will add comment in Dockerfile and update the release process in documentation.

**Comment by reasonerjt** [comment]
Fixed by https://github.com/vmware-tanzu/velero/pull/4224
