### ISSUE TITLE
CLI `backup-location create` command incorrectly sets empty `credential` field when no credential provided

### ISSUE THREAD

**Issue by adrianmace** [vmware-tanzu/velero#4196]
**What steps did you take and what happened:**
We run Velero Server as an ECS task rather than as a Kubernetes pod. In v1.5.4 our configuration works as intended, and the ECS task's instance profile (and associated IAM permissions) is what is used to access to the S3 bucket storage location. 

After upgrading to v1.6.x with the same configuration, this breaks with the following error:
```
Error getting backup store for this location" backupLocation=xxxx controller=backup-sync error="unable to get credentials: unable to get key for secret: Secret \"\" not found"
```

**What did you expect to happen:**
The velero server should detect the valid AWS credentials via the instance profile; adhering to AWS best practices.

**The output of the following commands will help us better understand what's going on**:

N/A

**Anything else you would like to add:**

This has also been raised as a Q&A by @toddgardner here: https://github.com/vmware-tanzu/velero/discussions/3800

**Environment:**

- Velero version (use `velero version`): 1.6.x
- Velero features (use `velero client config get features`): N/A
- Kubernetes version (use `kubectl version`): 1.21
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): `velero/velero` Dockerfile

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kannamr** [comment]
@adrianmace I faced the same issue. Can you check the nodes IAM policy, if it has permission to assume role.

**Comment by zubron** [comment]
Could you please provide the YAML for your BSL? `kubectl get -n velero -o yaml backupstoragelocations.velero.io <bsl-name>`.

When creating a BSL, it looks like the CLI is incorrectly setting the `credential` field on the BSL with an empty key name when that entire field should be omitted. The code that triggers the error message you are seeing should only be hit when that field is set. As a workaround, you should be able to edit the BSL yaml (using `kubectl edit`) and remove the credential field if it is set.

**Comment by adrianmace** [comment]
@zubron thank you for getting back to me. The output is as follows:
```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  creationTimestamp: "2021-08-09T04:00:23Z"
  generation: 1597
  name: xxxx-xxxx-cluster-backups-xx-xx-xx-backup-location
  namespace: velero
  resourceVersion: "187561805"
  uid: 4edd06e9-1d44-4577-b0ac-abcdefabcdef
spec:
  accessMode: ReadWrite
  objectStorage:
    bucket: xxxx-cluster-backups-xx-xx-xx
  provider: aws
status:
  lastSyncedTime: "2021-09-29T00:29:53Z"
  lastValidationTime: "2021-09-29T00:29:24Z"
  phase: Available
```

**Comment by zubron** [comment]
Thanks for providing the info, @adrianmace. Could you please provide the full logs for the velero pod? `kubectl logs -n velero deployment/velero`. Could you also confirm that you only have one backup storage location? I haven't been able to reproduce this locally. The code that triggers the error should only be called if the credential field is set (which it's not in your BSL): https://github.com/vmware-tanzu/velero/blob/b9a8c0b254909d12965c55a4aadf43d80c3202ff/pkg/persistence/object_store.go#L147-L154

**Comment by adrianmace** [comment]
Hey @zubron this is what stumped me too. I do have multiple storage locations but none of them have that flag set. 
```yaml
apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    creationTimestamp: "2021-08-09T04:00:23Z"
    generation: 1597
    name: xx-xx-cluster-backups-xx-xx-xx-backup-location
    namespace: velero
    resourceVersion: "187566558"
    uid: 4edd06e9-1d44-4577-b0ac-abcdefabcdef
  spec:
    accessMode: ReadWrite
    objectStorage:
      bucket: xx-xx-backups-xx-xx-xx
    provider: aws
  status:
    lastSyncedTime: "2021-09-29T01:04:10Z"
    lastValidationTime: "2021-09-29T01:04:43Z"
    phase: Available
- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    creationTimestamp: "2021-08-09T04:04:51Z"
    generation: 1593
    name: yy-xx-cluster-backups-xx-xx-xx-backup-location
    namespace: velero
    resourceVersion: "187566556"
    uid: b5b8201b-54a4-4720-a1e9-abcdefabcdef
  spec:
    accessMode: ReadWrite
    objectStorage:
      bucket: xx-cluster-backups-xx-xx-xx
    provider: aws
  status:
    lastSyncedTime: "2021-09-29T01:04:42Z"
    lastValidationTime: "2021-09-29T01:04:11Z"
    phase: Available
- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    creationTimestamp: "2019-09-20T02:40:05Z"
    generation: 34005
    labels:
      component: velero
    name: default
    namespace: velero
    resourceVersion: "187566488"
    uid: f3f7eeaa-db4f-11e9-afc3-023116ff0188
  spec:
    config:
      region: xx-xx-xx
    objectStorage:
      bucket: xx-cluster-backups-xx-xx-xx
      prefix: ""
    provider: aws
  status:
    lastSyncedRevision: 9c9527a6-2369-41a5-b2eb-a15a72599570
    lastSyncedTime: "2021-09-29T01:04:10Z"
    lastValidationTime: "2021-09-29T01:04:11Z"
    phase: Available
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

I do not have Velero 1.6 running at the moment so I will work to build out a development environment today and get the logs for you. This may take a few days though.

**Comment by adrianmace** [comment]
So, funny story.. 😅  I spun up a new EKS cluster, restored a velero backup to it, then hooked up a new velero server (using ECS as previously mentioned) and all _just worked!_. I can't seem to replicate this either.

It got me thinking and I'd be interested to get your thoughts on this. We recently upgraded our EKS cluster from 1.16 to 1.21. Is it possible the bug was only affecting the older version of k8s?

**Comment by adrianmace** [comment]
Happy to close this off. I can't replicate the error anymore. I suspect it has something to do with the k8s + velero version combination but do not have the capacity to test further. We've upgraded production without issue now 🥳 

Thank you for your time!

**Comment by zubron** [comment]
Reopening as https://github.com/vmware-tanzu/velero/issues/4196#issuecomment-929565383 still applies. If no credential is specified when creating a new BSL, the credential field should not be set.
