### ISSUE TITLE
change-storage-class plugin not working?

### ISSUE THREAD

**Issue by mseiwald** [vmware-tanzu/velero#4204]
**What steps did you take and what happened:**
I'm in the process of restoring a backup from one cluster to another one. Some PVC still have an old storage class that I want to to have changed during the restore. This is my CM:

```
apiVersion: v1
data:
  vsphere-default: vsphere-csi
kind: ConfigMap
metadata:
  labels:
    velero.io/change-storage-class: RestoreItemAction
    velero.io/plugin-config: ""
  name: velero-change-storage-class-config
  namespace: sci-lib
```

Unfortunately the PVC are still created with the old storace class (vsphere-default).

**What did you expect to happen:**

The storage class should have been changed from vsphere-default to vsphere-csi.

Here are some of the relevant velero logs:

```
time="2021-09-30T08:10:53+02:00" level=info msg="Executing item action for persistentvolumeclaims" logSource="pkg/restore/restore.go:1133" restore=sci-lib/sbi-20210929-1330-20210930081043
time="2021-09-30T08:10:53+02:00" level=info msg="Executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:65" pluginName=velero restore=sci-lib/sbi-20210929-1330-20210930081043
time="2021-09-30T08:10:53+02:00" level=debug msg="Getting plugin config" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:68" pluginName=velero restore=sci-lib/sbi-20210929-1330-20210930081043
time="2021-09-30T08:10:53+02:00" level=info msg="Updating item's storage class name to vsphere-csi" cmd=/velero kind=PersistentVolumeClaim logSource="pkg/restore/change_storageclass_action.go:112" name=pgdata-XXX-postgresql-0 namespace=sbi pluginName=velero restore=sci-lib/sbi-20210929-1330-20210930081043
time="2021-09-30T08:10:53+02:00" level=info msg="Done executing ChangeStorageClassAction" cmd=/velero logSource="pkg/restore/change_storageclass_action.go:118" pluginName=velero restore=sci-lib/sbi-20210929-1330-20210930081043
time="2021-09-30T08:10:53+02:00" level=info msg="Resetting PersistentVolumeClaim sbi/pgdata-XXX-postgresql-0 for dynamic provisioning" logSource="pkg/restore/restore.go:1212" restore=sci-lib/sbi-20210929-1330-20210930081043
time="2021-09-30T08:10:53+02:00" level=info msg="Attempting to restore PersistentVolumeClaim: pgdata-XXX-postgresql-0" logSource="pkg/restore/restore.go:1238" restore=sci-lib/sbi-20210929-1330-20210930081043
```

From the logs it seems it's updating the storage class of `pgdata-XXX-postgresql-0`, however it still ends up with the old storage class and therefore in pending state.

**Environment:**

- Velero version (use `velero version`): v1.6.0
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): v1.20.10
- Kubernetes installer & version: kubeadm 1.20
- Cloud provider or hardware configuration: vsphere 7.0
- OS (e.g. from `/etc/os-release`): CentOS Linux 7

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment]
Hi @mseiwald - Could you please provide the full logs from the velero deployment? The change-storage-class plugin should also have been applied to the PV and we'd need to see the full logs to determine why that didn't happen. Could you please also provide details about your backup and how you have configured velero? Thanks!

**Comment by alekc** [comment]
I am seeing the same behaviour atm with 1.9.4 @zubron this probably should not have been closed as stale

**Comment by lizhaoyangre** [comment]
我在velero1.10.3也发现了这个问题
