### ISSUE TITLE
[ArgoCD][Exclusion] Add a --rejector option to remove object from backup selection.

### ISSUE THREAD

**Issue by JGodin-C2C** [vmware-tanzu/velero#4209]
**Cluster is managed by argoCD and we do not want to backup the argocd-managed objects**

We are using argoCD to manage our cluster. The objects created by argoCD have a specific label ( ie: argocd.argoproj.io/instance: minio ) and we do not want to backup them.

As for today, i did not found any method to reject some of the objects.
This could be a really interesting feature as all the objects managed by helm as well as some kind of labels.

As a sidenote, we would like all objects that are NOT managed by argoCD/helm to be backed up (Thinking about PVs created through a StorageClass )

**Describe the solution you'd like**

The best and  simplest way of doing that would be to create a flag for the backups that looks like the '--selector' flag but instead of calling it '--selector' simply call it '--rejector' that will reject all backups that match the so-called label/value or simply the label key

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by fredleger** [comment]
i think something with `exlude` in the name will be clearer than `rejector` but i totally agree with the use case

**Comment by JGodin-C2C** [comment]
The name `rejector` was chosen to be an antonym of `selector`. `exclude` would ,indeed, do the trick.

**Comment by zubron** [comment]
@JGodin-C2C My understanding is that label selectors in Kubernetes allow to you to filter resources that do _not_ match a particular set of labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors

Have you tried using this approach with the existing selector feature in Velero? I believe this will satisfy your use case, but let us know if it does not. Thanks!
