### ISSUE TITLE
How to restore PV content via velero

### ISSUE THREAD

**Issue by vishumindtree** [vmware-tanzu/velero#4219]
**Not able to restore content to a restored PV using velero**

**Describe the solution you'd like**
[Ability to restore PVC & PV along with its content . Restoring just the state of the PVC is not sufficient]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by zubron** [comment]
Hi @vishumindtree - You have not provided enough detail for us to understand the issue you are seeing. Please fill in the given issue template:

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by zubron** [comment]
If you are using Velero 1.7.0, you can instead run `velero debug <backup name>` and `velero debug <restore name>` to capture the above logs. However, we'll still need information about what steps you took.

**Comment by vishumindtree** [comment]
velero version
Client:
        Version: v1.4.2
        Git commit: 56a08a4d695d893f0863f697c2f926e27d70c0c5
Server:
        Version: v1.4.2
-------------------------------------------------------------------------------------
K8s version is 1.16.3

---------------------------------------

restic version
restic 0.8.3
compiled with go1.10 on linux/amd6

------------------------------------------------------------

$ velero restic repo get -o yaml
apiVersion: velero.io/v1
kind: ResticRepository
metadata:
  creationTimestamp: "2021-10-06T12:51:56Z"
  generateName: jenkins-master-ns-default-
  generation: 3
  labels:
    velero.io/storage-location: default
    velero.io/volume-namespace: jenkins-master-ns
  name: jenkins-master-ns-default-9r2tx
  namespace: velero
  resourceVersion: "331296623"
  selfLink: /apis/velero.io/v1/namespaces/velero/resticrepositories/jenkins-master-ns-default-9r2tx
  uid: d68e7fd4-d402-4571-9094-9d7eda927be3
spec:
  backupStorageLocation: default
  maintenanceFrequency: 168h0m0s
  resticIdentifier: s3:https://XXXXXXXXXXXXXXX:XXXX/vishaltest/restic/jenkins-master-ns
  volumeNamespace: jenkins-master-ns
status:
  message: |-
    error running command=restic init --repo=s3:https://xxxxxxxxxxxxx.xxxxxx.com:9000/vishaltest/restic/jenkins-master-ns --password-file=/tmp/velero-restic-credentials-jenkins-master-ns247118137 --cacert=/tmp/cacert-default017988932 --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: create repository at s3:https://XXXXXXXXXXXXXXXXXX:9000 vishaltest/restic/jenkins-master-ns failed: client.BucketExists: The Access Key Id you provided does not exist in our records.

    : exit status 1
  phase: NotReady

**Comment by vishumindtree** [comment]
vishakumar@VISHAKUMAR-LT1:~$ kubectl logs -n velero -l name=restic
time="2021-10-06T12:45:50Z" level=info msg="Setting log-level to INFO"
time="2021-10-06T12:45:50Z" level=info msg="Starting Velero restic server v1.4.2 (56a08a4d695d893f0863f697c2f926e27d70c0c5)" logSource="pkg/cmd/cli/restic/server.go:62"
time="2021-10-06T12:45:51Z" level=info msg="Starting controllers" logSource="pkg/cmd/cli/restic/server.go:156"
time="2021-10-06T12:45:51Z" level=info msg="Controllers started successfully" logSource="pkg/cmd/cli/restic/server.go:199"
time="2021-10-06T12:45:51Z" level=info msg="Starting controller" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:76"
time="2021-10-06T12:45:51Z" level=info msg="Waiting for caches to sync" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:81"
time="2021-10-06T12:45:51Z" level=info msg="Starting controller" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:76"
time="2021-10-06T12:45:51Z" level=info msg="Waiting for caches to sync" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:81"
time="2021-10-06T12:45:51Z" level=info msg="Caches are synced" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:85"
time="2021-10-06T12:45:51Z" level=info msg="Caches are synced" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:85"
time="2021-10-06T12:45:51Z" level=info msg="Setting log-level to INFO"
time="2021-10-06T12:45:51Z" level=info msg="Starting Velero restic server v1.4.2 (56a08a4d695d893f0863f697c2f926e27d70c0c5)" logSource="pkg/cmd/cli/restic/server.go:62"
time="2021-10-06T12:45:51Z" level=info msg="Starting controllers" logSource="pkg/cmd/cli/restic/server.go:156"
time="2021-10-06T12:45:51Z" level=info msg="Controllers started successfully" logSource="pkg/cmd/cli/restic/server.go:199"
time="2021-10-06T12:45:51Z" level=info msg="Starting controller" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:76"
time="2021-10-06T12:45:51Z" level=info msg="Waiting for caches to sync" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:81"
time="2021-10-06T12:45:51Z" level=info msg="Starting controller" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:76"
time="2021-10-06T12:45:51Z" level=info msg="Waiting for caches to sync" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:81"
time="2021-10-06T12:45:51Z" level=info msg="Caches are synced" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:85"
time="2021-10-06T12:45:51Z" level=info msg="Caches are synced" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:85"
time="2021-10-06T12:45:51Z" level=info msg="Setting log-level to INFO"
time="2021-10-06T12:45:51Z" level=info msg="Starting Velero restic server v1.4.2 (56a08a4d695d893f0863f697c2f926e27d70c0c5)" logSource="pkg/cmd/cli/restic/server.go:62"
time="2021-10-06T12:45:51Z" level=info msg="Starting controllers" logSource="pkg/cmd/cli/restic/server.go:156"
time="2021-10-06T12:45:51Z" level=info msg="Starting controller" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:76"
time="2021-10-06T12:45:51Z" level=info msg="Waiting for caches to sync" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:81"
time="2021-10-06T12:45:51Z" level=info msg="Controllers started successfully" logSource="pkg/cmd/cli/restic/server.go:199"
time="2021-10-06T12:45:51Z" level=info msg="Starting controller" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:76"
time="2021-10-06T12:45:51Z" level=info msg="Waiting for caches to sync" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:81"
time="2021-10-06T12:45:51Z" level=info msg="Caches are synced" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:85"
time="2021-10-06T12:45:51Z" level=info msg="Caches are synced" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:85"
time="2021-10-06T12:45:50Z" level=info msg="Setting log-level to INFO"
time="2021-10-06T12:45:50Z" level=info msg="Starting Velero restic server v1.4.2 (56a08a4d695d893f0863f697c2f926e27d70c0c5)" logSource="pkg/cmd/cli/restic/server.go:62"
time="2021-10-06T12:45:51Z" level=info msg="Starting controllers" logSource="pkg/cmd/cli/restic/server.go:156"
time="2021-10-06T12:45:51Z" level=info msg="Controllers started successfully" logSource="pkg/cmd/cli/restic/server.go:199"
time="2021-10-06T12:45:51Z" level=info msg="Starting controller" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:76"
time="2021-10-06T12:45:51Z" level=info msg="Waiting for caches to sync" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:81"
time="2021-10-06T12:45:51Z" level=info msg="Starting controller" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:76"
time="2021-10-06T12:45:51Z" level=info msg="Waiting for caches to sync" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:81"
time="2021-10-06T12:45:51Z" level=info msg="Caches are synced" controller=pod-volume-restore logSource="pkg/controller/generic_controller.go:85"
time="2021-10-06T12:45:51Z" level=info msg="Caches are synced" controller=pod-volume-backup logSource="pkg/controller/generic_controller.go:85"

**Comment by NisharunnisaShaik** [comment]
Hi Team, 

I am also facing the Similar Issue , We are backing up the Mysql which is having PV & PVC .Everything is being backedup (service,deployment,RS,PV & PVC) but not the Content (Ex:DB's ,Users,Tables) 

```
Kubernetes Deployed on GKE 
Velero Plugin for GCP :1.3.0 
```
Please find the Logs below for the Backup 
```
time="2021-10-19T04:55:57Z" level=info msg="Got volume ID for persistent volume" backup=velero/mysql-19 logSource="pkg/backup/item_backupper.go:462" name=pvc-c6202e3c-2b79-43bc-81d6-1ef1c610ed85 namespace= persistentVolume=pvc-c6202e3c-2b79-43bc-81d6-1ef1c610ed85 resource=persistentvolumes volumeSnapshotLocation=default
time="2021-10-19T04:55:57Z" level=info msg="Getting volume information" backup=velero/mysql-19 logSource="pkg/backup/item_backupper.go:483" name=pvc-c6202e3c-2b79-43bc-81d6-1ef1c610ed85 namespace= persistentVolume=pvc-c6202e3c-2b79-43bc-81d6-1ef1c610ed85 resource=persistentvolumes volumeID=gke-vpd-dev-gke-92f686-pvc-c6202e3c-2b79-43bc-81d6-1ef1c610ed85
time="2021-10-19T04:55:58Z" level=info msg="Snapshotting persistent volume" backup=velero/mysql-19 logSource="pkg/backup/item_backupper.go:489" name=pvc-c6202e3c-2b79-43bc-81d6-1ef1c610ed85 namespace= persistentVolume=pvc-c6202e3c-2b79-43bc-81d6-1ef1c610ed85 resource=persistentvolumes volumeID=gke-vpd-dev-gke-92f686-pvc-c6202e3c-2b79-43bc-81d6-1ef1c610ed85
time="2021-10-19T04:55:59Z" level=warning msg="No volume named mysql-volume found in pod default/mysql-deployment-55cc79bc45-9j7mq, skipping" backup=velero/mysql-19 logSource="pkg/restic/backupper.go:135" name=mysql-deployment-55cc79bc45-9j7mq namespace=default resource=pods
time="2021-10-19T04:55:59Z" level=info msg="Backed up 3 items out of an estimated total of 5 (estimate will change throughout the backup)" backup=velero/mysql-19 logSource="pkg/backup/backup.go:394" name=mysql-deployment-55cc79bc45-9j7mq namespace=default progress= resource=pods
time="2021-10-19T04:55:59Z" level=info msg="Processing item" backup=velero/mysql-19 logSource="pkg/backup/backup.go:354" name=mysql-deployment-55cc79bc45 namespace=default progress= resource=replicasets.apps
time="2021-10-19T04:55:59Z" level=info msg="Backing up item" backup=velero/mysql-19 logSource="pkg/backup/item_backupper.go:121" name=mysql-deployment-55cc79bc45 namespace=default resource=replicasets.apps
time="2021-10-19T04:55:59Z" level=info msg="Backed up 4 items out of an estimated total of 5 (estimate will change throughout the backup)" backup=velero/mysql-19 logSource="pkg/backup/backup.go:394" name=mysql-deployment-55cc79bc45 namespace=default progress= resource=replicasets.apps
time="2021-10-19T04:55:59Z" level=info msg="Processing item" backup=velero/mysql-19 logSource="pkg/backup/backup.go:354" name=mysql-deployment namespace=default progress= resource=deployments.apps
time="2021-10-19T04:55:59Z" level=info msg="Backing up item" backup=velero/mysql-19 logSource="pkg/backup/item_backupper.go:121" name=mysql-deployment namespace=default resource=deployments.apps
time="2021-10-19T04:55:59Z" level=info msg="Backed up 5 items out of an estimated total of 5 (estimate will change throughout the backup)" backup=velero/mysql-19 logSource="pkg/backup/backup.go:394" name=mysql-deployment namespace=default progress= resource=deployments.apps
time="2021-10-19T04:55:59Z" level=info msg="Backed up a total of 5 items" backup=velero/mysql-19 logSource="pkg/backup/backup.go:419" progress=

```

From the Logs i can see a Warning which states that mysql-data volume is not found but we have PVC for the same . Kindly let us know what might went wrong @zubron @carlisia @dsu-igeek


Thanks 
Nisha

**Comment by vishumindtree** [comment]
We still dont have enough information on how to get the PV data backedup.

**Comment by vishumindtree** [comment]
Annotate pod with volume , then only PV content will be backedup & restored
