### ISSUE TITLE
Restoring pv from Restic is not working

### ISSUE THREAD

**Issue by chechuironman** [vmware-tanzu/velero#4222]
I'm using OADP operator, I created a backup with Restic to backup all the PVs on a ns... it created the Restic repo and the podvolumebackup...but when I try to restore it it restores everything except the data...and I don't see any podvolumerestore CR 

any idea?

**Comment by gojeaqui** [comment]
Hello, I'm having the same problem. But I am using the velero instance provided by MTC.

Have you tried opening a ticket with the OADP guys?
