### ISSUE TITLE
velero backup using a mix of restic and csi snapshots

### ISSUE THREAD

**Issue by gorantornqvist** [vmware-tanzu/velero#4228]
**What steps did you take and what happened:**

I am trying to backup a namespace containing a pod with a PVC using a CSI snapshot capable storage class and another pod using a storage class that doesnt provide snapshots.

* With defaultVolumesToRestic: false set for the backup I found that velero tries to create a snapshot for the PVC that uses a SC that doesnt allow snapshots and this causes the backup to hang with message "
Waiting for volumesnapshotcontents snapcontent-5a89aa3b-fbb1-4794-9ef4-450c60986550 to have snapshot handle"
* With defaultVolumesToRestic: true set for the backup I found that velero uses restic to backup the PVC that does support CSI snapshots.

My volumesnapshotclass uses driver: csi.trident.netapp.io and has label velero.io/csi-volumesnapshot-class: "true"

All storageclasses is for provisioner csi.trident.netapp.io and the CSI snapshot capable SC has parameters: snapshots: "true" set and the SCs that doesnt allow snapshots (trident economy driver) has parameters: snapshots: "false"

Can you please clarify the correct backup procedure for this scenario?
I couldnt find anything in the docs about this ...

**What did you expect to happen:**

The PVC using a CSI snapshot capable SC should be backed up using snapshots and the PVC using a SC that doesnt allow for snapshots should be backed up with restic.

**Environment:**

- Velero version (use `velero version`): v1.6.3-konveyor
- Velero features (use `velero client config get features`): NOT SET
- Kubernetes version (use `kubectl version`): v1.21.1+a620f50
- Kubernetes installer & version: Openshift 4.8
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from `/etc/os-release`): CoreOS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by son-la** [comment]
any update on this? I think it's pretty valid use case and workaround I can think of now is to split them by namespace and let two different backups take care of each.

**Comment by blackpiglet** [comment]
To my knowledge, this is not supported by current and coming release of Velero, but, of course, we will consider this need in our future developing process. 
I think it's better for our PM to review this issue first, then we can decide the plan and make a schedule for this. 
Up to now, our PM is still on vacation, so please tune in for update.

**Comment by felfa01** [comment]
A workaround I have gotten to work is that you run your backups with `defaultVolumesToRestic: true` and then specifically opt-out the pods using a SC compatible with CSI snapshots via [annotations](https://github.com/vmware-tanzu/velero/blob/main/site/content/docs/v1.5/restic.md#using-the-opt-out-approach).

**Comment by ghilman27** [comment]
Any update on this? It would be nice to snapshot rook cephfs with csi (which stored inside the cluster by default / not durable) and backup also with restic for disaster recovery or planning migration. 

The workaround from @felfa01 can't solve the problem because by setting `defaultVolumesToRestic: true`, every volumes (including istio sidecar) are backed up, which messed up the entire restore. It would be a pain to manually annotate them rather than annotate a few volumes using opt-in approach.

**Comment by blackpiglet** [comment]
@ghilman27 
There is still no progress in method of mixing several tools in a single backup or restore.
Talking about the existing way, I think the opt-in way can be used as a workaround. This is the document link: [Using opt-in pod volume backup](https://velero.io/docs/v1.7/restic/#using-opt-in-pod-volume-backup)

**Comment by fredleger** [comment]
As discussed in the above issue the opt in way seems to not resolve use cases where you want to mix CSI for local DR and restic for a remote DR.

> My use case: i do want to leverage on CSI snaps to have a local copy but also want an exported copy of volume via restic in case the cloud provider have a major outage (the restic repository is on another cloud provider).

I was thinking to a flag in schedule spec in order to force the type of snapshots you want to use (and have 2 differents shedules for local and remote DR)

## Proposal this won't work !

```yaml
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: csi-snapshots
  namespace: velero
  labels:
    app: velero
spec:
  schedule: 17 2 * * *
  template:
    metadata:
      labels:
        app: velero
    # backup nothing just use CSI snapshots
    includeClusterResources: false
    includedResources: []
    excludedResources: ['*']
    snapshotVolumes: true
    ***
    snapshotPlugin: restic
    ***
    ttl: 26h0m0s
```

**Comment by ThomasSteinbach** [comment]
I think it is absolutely required to allow Velero backups doing both - snapshots of capable volumes and file system backups of volumes snapshots can't be made of.

https://github.com/vmware-tanzu/velero/discussions/6213

**Comment by ThomasSteinbach** [comment]
Would't it be as easy as having an option that allows for additional snapshots here?
https://github.com/vmware-tanzu/velero/blob/main/pkg/backup/item_backupper.go#L470

**Comment by kaovilai** [comment]
Delivered via volumepolicy feature https://velero.io/docs/v1.15/resource-filtering/#supported-volumepolicy-actions
#7664 
https://github.com/vmware-tanzu/velero/issues/6640

**Comment by kaovilai** [comment]
> VolumePolicies allow choosing the type of snapshot (CSI or restic) depending on matched criteria.

and a backup can contain volumes from multiple chosen criteria thus a single backup can already contain both CSI and restic/kopia snapshots.

**Comment by kaovilai** [comment]
> - A user wants to use `snapshot` (volumesnapshots) backup option for all the csi supported volumes and `fs-backup` for the rest of the volumes.


See design for more detail:
https://github.com/vmware-tanzu/velero/pull/6956/files#diff-e7031ade61ec4ab5a81bf97706f42a35460a8b648a57266950b1dd98810193dcR29

**Comment by ibot3** [comment]
@kaovilai 

I don't seem to get this to work. I use the following policy:

```
version: v1
volumePolicies:
- conditions:
    storageClass:
      - csi-cephfs-sc
      - csi-rbd-sc
  action:
    type: fs-backup
- conditions:
    storageClass:
      - csi-cephfs-sc
      - csi-rbd-sc
  action:
    type: snapshot
```

However, the volumes are only being backupped via FS-backup and not via CSI-snapshot.

As snapshots aren't real backups, I want to do both. Snapshots for an easy restore and FS-backups for when the storage-domain (ceph) fails completely.

**Comment by kaovilai** [comment]
As I understand, velero has built in mechanisms to avoid both from happening. If you want both you'll have to open a new feature request.

**Comment by sseago** [comment]
@ibot3 With volume policies the first match is taken. If you had reversed that order, you'd get snapshot instead. Are you trying to do two backups for one volume -- i.e. CSI and restic for the same volume in the same backup? If so, Velero doesn't support that. In your example, you have identical matching criteria for filesystem and snapshot. The stated use case here was that there were certain storage classes that didn't support snapshot and those needed to use filesystem backup. That is supported, but you need to conform the match rules correspondingly -- i.e. list the snapshot-capable storageclasses for snapshot action rules, and the non-snapshot ones for the filesystem rules. Even easier, list snapshot-capable storageclasses in a snapshot rule first, then a catch-all filesystem rule that matches everything.
