### ISSUE TITLE
`velero install --crds-only` does not behave as documented

### ISSUE THREAD

**Issue by sarahhodne** [vmware-tanzu/velero#4236]
**What steps did you take and what happened:**

1. Upgrade to Velero 1.7.0
2. Run `velero install --crds-only` to upgrade CRDs. The `--help` description for `--crds-only` includes "Useful for updating CRDs for an existing Velero install", so I was lead to believe that this would work.
3. The CRD did not upgrade, as the command only seems to create new CRDs, and doesn't touch existing ones.

**What did you expect to happen:**

- The CRDs are upgraded with the latest version, similar to `velero install --crds-only --dry-run -oyaml | kubectl apply -f-`

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

N/A, I think, since this is purely about the Velero client CLI, not the server.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
   ```
   Client:
       Version: v1.7.0
       Git commit: 9e52260568430ecb77ac38a677ce74267a8c2176
   Server:
       Version: v1.7.0
   ```
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): 
   ```
   Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
   Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
   ```
- Kubernetes installer & version: EKS 1.20
- Cloud provider or hardware configuration: EKS
- OS (e.g. from `/etc/os-release`): NixOS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by jenting** [comment]
If nice to have a Velero command to install/upgrade existing CRDs without having to leverage the `kubectl` command.
