### ISSUE TITLE
Document how to delete failed backups

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/velero#4245]
A user noted that they have a lot of Velero backups stuck in deleting state and weren't sure how to force delete them. Another user suggested the solution below. It would be great to get this into the Velero docs.

The situation I have encountered is when the backup failed early on and it was trying to delete resources that didn't really exist.  The only way I found to get it to continue the delete is to  kubectl delete backups.velero.io -n velero <<backup-name>>  and as soon as that completed my backup delete completed.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by a-mccarthy** [comment]
this content seems related to information being added for https://github.com/vmware-tanzu/velero/issues/1712

**Comment by a-mccarthy** [comment]
@eleanor-millman In the troubleshooting docs, i found a topic that (i think) closely relates to this, https://velero.io/docs/v1.8/troubleshooting/#velero-or-a-pod-it-was-backing-up-restarted-during-a-backup-and-the-backup-is-stuck-inprogress. 

Can you provide more information on the command that was being run run or what the command output looks like when a user might see this error? I think it makes sense to add into the troubleshooting page.

**Comment by a-mccarthy** [comment]
so from looking into this more, i think this comment includes some more context, https://github.com/vmware-tanzu/velero/issues/3094#issuecomment-7583220. 

So i think the ask here is for a way to clean up backups that are stuck in the `Deleting` phase. The recommendation is to manually run `backup delete` commend. I'm not exactly clear of the reasons why a backup could get stuck in the deleting phase.

i've opened a PR to add this into the troubleshooting docs

**Comment by ywk253100** [comment]
The issue mentioned here is a dup of https://github.com/vmware-tanzu/velero/issues/4551 and is already fixed by https://github.com/vmware-tanzu/velero/pull/4817. So the doc isn't needed per my understanding

**Comment by a-mccarthy** [comment]
@ywk253100 thank you for the feedback! That sounds reasonable to me, I will close this issue and the PR as well.

**Comment by onobrerodrigo** [comment]
I had a problem with hundreds of Velero backups being generated with failure and I didn't think it was viable to have to delete one by one from my Object Storage, so I decided to do it as follows:

```bash
velero backup get |grep "name-backup" | awk '{print $1,$2}'| egrep -v 'New|Completed' > error_backup.txt
```
And with this TXT file in hand I created a bash with the following:

```bash
for backup in $(cat error_backup.txt); of
   echo "Backup: $backup"
   velero backup delete "$backup" --confirm
done
```

**Comment by arnaudmut** [comment]
Hi  @onobrerodrigo , thanks for sharing your approach. I noticed a small typo in the script you posted. The line `for backup in $(cat error_backup.txt); of `shouldn't be `for backup in $(cat error_backup.txt); do` ?

**Comment by arnaudmut** [comment]
> I had a problem with hundreds of Velero backups being generated with failure and I didn't think it was viable to have to delete one by one from my Object Storage, so I decided to do it as follows:
> 
> ```shell
> velero backup get |grep "name-backup" | awk '{print $1,$2}'| egrep -v 'New|Completed' > error_backup.txt
> ```
> 
> And with this TXT file in hand I created a bash with the following:
> 
> ```shell
> for backup in $(cat error_backup.txt); of
>    echo "Backup: $backup"
>    velero backup delete "$backup" --confirm
> done
> ```

Hi  @onobrerodrigo , thanks for sharing your approach. I noticed a small typo in the script you posted. The line:  `for backup in $(cat error_backup.txt);  of ` shouldn't be  `for backup in $(cat error_backup.txt); do` ?
