### ISSUE TITLE
Add E2E test of backups sync from BSL

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#4253]
**Describe the problem/challenge you have**
Currently test for backups sync  is covered manually.
Test case 1:
1. Deploy test object for backup;
2. Create backup;
3. Uninstall Velero;
4. Install Velero;
5. Check if backup can be sync from BSL to local successfully.

Test case 2:
1. Deploy test object for backup;
2. Create backup;
3. Delete backups from BSL
4. Check if backups are deleted as a result of sync from BSL.

**Describe the solution you'd like**
Test for backups sync should be automated and added into E2E tests.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by eleanor-millman** [comment]
@danfengliu Do we expect this to make 1.8 or should I remove it from the milestone?

**Comment by danfengliu** [comment]
This can not reach 1.8 RC, so replace milestone with 1.9 .
