### ISSUE TITLE
Add e2e tests to prevent future controller namespace mix-ups

### ISSUE THREAD

**Issue by codegold79** [vmware-tanzu/velero#4257]
**Describe the problem/challenge you have**

PR #4251 was recently merged in order to fix a problem introduced during controller modernization (conversion of some controllers to the Kubebuilder framework). @sseago mentioned in a Velero Community meeting that such mix-ups have happened before. @dsu-igeek mentioned such namespace mix-up could be a security risk because Velero requires greater than basic privileges. Add e2e test that ensure Velero controllers will be working in the proper namespaces in future updates.

**Describe the solution you'd like**

Tests requires a certain amount of creativity and the following are just ideas. Feel free to come up with other e2e tests or make changes to my ideas as needed.

I did two different sets of manual e2e tests for PR #4251, one focusing on the server status request (SSR) controller, and another focusing on the backup storage location (BSL) controller. I believe these tests can be automated with e2e tests.

**SSR Test**

- install Velero in namespace, `velero`
- create a test namespace, `ssr-test`
- run command `velero version -n ssr-test` to create an `ssr` object in the `ssr-test` namespace
- run command `velero version -n velero` to create an `ssr` object in the `velero` namespace (be sure to do this second)
- watch the `ssr` object in the `velero` namespace. It should be updated with the velero server and client versions, and then the object should be deleted.
- once the `ssr` object in `velero` is deleted, make sure that the `ssr` in the `ssr-test` namespace is unchanged and not deleted. This means the SSR controller is only working in the namespace it should be.
- delete the `ssr-test` namespace and remaining cleanup actions

**BSL Test**

- install Velero in namespace `velns-1` that connects to a functioning BSL
- install Velero in namespace `velns-2` that fails to connect to a BSL
- watch both Velero BSL statuses: the `velns-1` should be available and the `velns-2` should be unavailable.
- wait 5 minutes. If their statuses don't change, test is successful. The BSL is only working in the namespace it should be.

**Anything else you would like to add:**

There is a problem with the suggested e2e tests. Both require watching for controllers to act, which can take up to 5 minutes each (I'm guessing from the experience I've had with manual tests). If there is a way to trigger the controllers to work right away, that would speed up the tests and we'll be able to control them better.

**Environment:**

- Velero version (use `velero version`): latest/main
- Kubernetes version (use `kubectl version`): whatever is being run on e2e test clusters
- Kubernetes installer & version: whatever is being run on e2e test clusters
- Cloud provider or hardware configuration: various
- OS (e.g. from `/etc/os-release`): various

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
not a stale

**Comment by qiuming-best** [comment]
For the sake of the 1.8 RC deadline, Divided the current issue into two test parts, one is the SSR test. another is the BSL test,
the SSR test is reference to #4522
