### ISSUE TITLE
Issue when using velero with a large cluster

### ISSUE THREAD

**Issue by nsagark** [vmware-tanzu/velero#4259]
**What steps did you take and what happened:**
Hi there,
I am trying to back up one of the clusters in my environment. However the status of backup is Partially failed. We are seeing this happening with just one cluster while it is working fine for all other clusters. I am using velero version 1.1.0. Here is the error that I am seeing. Please suggest if there is anything I could do to fix this issue

velero backup logs daily-20211019010052|grep -v level=info

time="2021-10-19T01:03:12Z" level=error msg="Error listing items" backup=velero/daily-20211019010052 error="rpc error: code = ResourceExhausted desc = grpc: message too large (4516929051 bytes)" error.file="/go/src/github.com/heptio/velero/pkg/backup/resource_backupper.go:227" error.function="github.com/heptio/velero/pkg/backup.(*defaultResourceBackupper).backupResource" group=kyverno.io/v1alpha1 logSource="pkg/backup/resource_backupper.go:227" namespace= resource=reportchangerequests

**What did you expect to happen:**

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
Please try with velero v1.7.1 once it is released. velero v1.7.1 fixes a bug of the pagination support for listing items.
I'm closing this issue, feel free to reopen it if you any further issues
