### ISSUE TITLE
Velero restore doesnt restore the content of the PV on GKE

### ISSUE THREAD

**Issue by NisharunnisaShaik** [vmware-tanzu/velero#4261]
**What steps did you take and what happened:**

Hi Team, 

We have installed velero on our GKE Cluster , We are able to backup everything Including PV,PVC's ,Deployments etc . But we don't see any of our PV content being backed up . Velero is just creating the empty pv's without any configurations or data 

**What did you expect to happen:**

velero restore should also restore the Application Content , For ex: DB data ,Tables etc

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
  please find the  [logs](https://gist.github.com/NisharunnisaShaik/c96e5dd2c668ab65434ebe4fa52326e4)
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
  Please find the [backup details ](https://gist.github.com/NisharunnisaShaik/70103b80252b2cfaf51219501abe372d)
- `velero backup logs <backupname>`
Please find the[ backup logs ](https://gist.github.com/NisharunnisaShaik/2b4d02858482c9bb61d661c67b1104fb)
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
Please find the[ restore details ](https://gist.github.com/NisharunnisaShaik/5e7b001098f11a5ce26991d036e3639c)

**Anything else you would like to add:**
[Installation Guide  ](https://github.com/vmware-tanzu/velero-plugin-for-gcp)
Command Used : `velero install --provider gcp --plugins velero/velero-plugin-for-gcp:latest --use-restic --wait --bucket $BUCKET  --default-volumes-to-restic  --secret-file ./credentials-velero `

**Environment:**

- Velero version (use `velero version`): 
```
Client:
        Version: v1.6.3
        Git commit: 5fe3a50bfddc2becb4c0bd5e2d3d4053a23e95d2
Server:
        Version: v1.6.3
```
- Velero features (use `velero client config get features`): 
`features: <NOT SET>`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.9-gke.1001", GitCommit:"1fe18c314ed577f6047d2712a9d1c8e498e22381", GitTreeState:"clean", BuildDate:"2021-08-23T23:06:28Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: `GCP `

The restore logs is of new backup restore installation . I have pasted our logs that we tried earlier in this [Issue ](https://github.com/vmware-tanzu/velero/issues/4219)
**Vote on this issue!**

I have already posted on Discussions & Slack Channels but there is no help, hence creating an issue

Thanks 
Nisha 

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
@NisharunnisaShaik 
Great. Happy to see your problem is resolved.
Sorry for the late response. I was busy with a internal support in last a few days.

To your previous questions, I think you already figured them out.
I saw you already specified flag "--default-volumes-to-restic" in question description. Does the option not work as expect?

**Comment by blackpiglet** [comment]
Maybe, but needs more information on the Backup and Restore information.

**Comment by kaovilai** [comment]
I recently filed https://github.com/vmware-tanzu/velero/issues/4868 and if there's a PR might help for this case.

**Comment by kaovilai** [comment]
Resolved a case recently with image built with https://github.com/vmware-tanzu/velero/pull/4890 in which no PVRs were created.
