### ISSUE TITLE
Add E2E test of backups deletion once BSL is deleted

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#4262]
As issue #2082 describe, E2E test should cover this scenario.

**Comment by eleanor-millman** [comment]
@danfengliu do you expect this to make 1.8 or should I remove the milestone? Thanks!

**Comment by danfengliu** [comment]
This can not reach 1.8 RC, so replace milestone with 1.9 .

**Comment by danfengliu** [comment]
Close this since PR #4736 is merged.
