### ISSUE TITLE
Add E2E test of backup TTL

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#4264]
Backups that exceed TTL should be deleted, add E2E test to cover this feature.

**Comment by eleanor-millman** [comment]
@danfengliu do you expect this to make 1.8 or should I remove the milestone? Thanks!

**Comment by danfengliu** [comment]
Since GC is triggered by a 1h timer, so it's not a maintainable E2E test to be scripted, so I filed an issue #4464  as a requirement to make timer configurable, then in E2E test script, we can make a verification that if the backups exceeded TTL were cleaned by GC in a shorter time. 

So this issue will be removed from 1.8 milestone.

**Comment by eleanor-millman** [comment]
@qiuming-best should we remove the stale label from this issue?
