### ISSUE TITLE
Azure: don't use storage account key for object storage if SP or MI is provided

### ISSUE THREAD

**Issue by yvespp** [vmware-tanzu/velero#4267]
**Describe the problem/challenge you have**
For security reasons we want to disable the storage account key access for all Azure storage accounts. Doc: https://docs.microsoft.com/en-gb/azure/storage/common/shared-key-authorization-prevent

The Azure plugin supports using service principal or managed identity already but uses it only to list the storage account keys and then uses that to access the blob: https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/velero-plugin-for-microsoft-azure/object_store.go#L215

**Describe the solution you'd like**
The plugin should only use the storage account key if it's provided by the user. It should use service principal or MI directly to access the blob. The newer client supports this: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob#NewContainerClient

**Environment:**
- Velero version (use `velero version`): 1.7.0 
- Kubernetes version (use `kubectl version`): 1.21.2
- Kubernetes installer & version: 1.21.2
- Cloud provider or hardware configuration: Azure AKS
- OS (e.g. from `/etc/os-release`): -

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by yvespp** [comment]
There is a pull request open for some time now: https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/111
If someone has time to test, review or advance it, I would appreciate it!

We use it in production and haven't had issues.

**Comment by ywk253100** [comment]
@yvespp I will take a look. Thanks for the PR

**Comment by eleanor-millman** [comment]
@ywk253100 what was the result? Wondering if we should make this something for 1.10 since it seems a popular ask.

**Comment by reasonerjt** [comment]
This may be pushed out of v1.10 b/c the PR didn't consider the upgrade scenario.

**Comment by blackpiglet** [comment]
Remove from milestone v1.10 for now.

**Comment by ywk253100** [comment]
Fixed by https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/111
