### ISSUE TITLE
Backup hooks fsfreeze example does nothing useful

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#4268]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Working on a related lab project and noticing that creating a file with pre-hook annotation to a pod's mounted pvc, may not exist on restore if pvc is backed up prior to pre-hookCommand execution.

The [fsfreeze example](https://velero.io/docs/v1.7/backup-hooks/) would only do something useful if pvc is guaranteed to backup in between pre and post backup hook of the pod.

**What did you expect to happen:**
Ability to have pod pre-hook command execute, then mounted pvc gets backed up, only then does the post-hook command execute.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

https://gist.github.com/kaovilai/8e9b814e2a85bb91e05921f3e9ed9aff#file-backup-log-L628-L665

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This issue maybe partially closed with https://github.com/vmware-tanzu/velero/issues/4067
At the pod annotation level, there is currently no way to have mounted pvc be backed up in between a pod's pre and post hook.

**Environment:**

- Velero version (use `velero version`):  v1.7.0
- Velero features (use `velero client config get features`): not set
- Kubernetes version (use `kubectl version`):  v1.21.1+f36aa36
- Kubernetes installer & version:
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`): Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kaovilai** [comment]
One universal solution to pvc problem would be, check all pods that will be backed up for pre-post hooks and if those pods also mount pvcs, to backup pvcs between the pre- and post- hooks.

This may assume a pvc belongs to at most one pod.

**Comment by reasonerjt** [comment]
@kaovilai 
I did some tests with the annotation you mentioned.
It seems there is a time-window that the pre-hook command is returned but the content is not persisted to the disk.  
Could you try sleep a few seconds in the `pre.hook.backup.velero.io/command` and check if the file `pathToMountedPVC/lab-pre-backup` is in your restore?

In my test I could see the `lab-pre-backup` in the restore using this file:
https://github.com/reasonerjt/velero/blob/tmp-hook-investigation/examples/nginx-app/with-pv-sleep120.yaml
but I could not see the `lab-pre-backup` in the restore using this file:
https://github.com/reasonerjt/velero/blob/tmp-hook-investigation/examples/nginx-app/with-pv.yaml
