### ISSUE TITLE
Velero should be able to back up Harbor

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/velero#4280]
As a Harbor user, I would like to be able back up and restore my projects, repositories and all OCI images that reside within.
As a Harbor user, I would like to be able back up and restore all my users, groups, robot acounts, and all role based access control policies.
As a Harbor user, I would like to be able back up and restore all my policies such as replication policies, image scanning policies, tag retention and tag immutability policies, garbage collection policies, p2p policies.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by eleanor-millman** [comment]
@reasonerjt Can you please add the link to the Harbor issue so we can track it here? Thanks!

**Comment by euclidsun** [comment]
this seems a requirement for harbor? all the harbor resources are not k8s resources (correct me if i am wrong ), so this is not align with velero's objectives.

**Comment by ywk253100** [comment]
This is already supported in Harbor [v2.6 ](https://github.com/goharbor/harbor/releases/tag/v2.6.0), closing this issue.
