### ISSUE TITLE
Use KMS key in different AWS account using the ARN of key

### ISSUE THREAD

**Issue by mijndert** [vmware-tanzu/velero#4284]
**Describe the problem/challenge you have**
We want to use a centrally generated key in a different AWS account for encrypting our backups. Currently Velero only seems to accept (from the documentation) the ID and not the full ARN of the key making it impossible to use a key that's in a different account than where Velero is operating from.

**Describe the solution you'd like**
Make it possible to give Velero the ARN of a KMS key. If it's already possible in some way, I'd really like to know.

**Anything else you would like to add:**
None.

**Environment:**

- Velero version (use `velero version`): n/a
- Kubernetes version (use `kubectl version`): n/a
- Kubernetes installer & version: n/a
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): n/a

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
I'll verify before v1.10 FC and update the doc as needed.

**Comment by reasonerjt** [comment]
I've verified that you can create the BSL and set the kmsKeyID with the ARN of the key, like this:
```
velero backup-location create kmsbsl --provider aws --bucket my-bucket --config region=us-east-2,kmsKeyId=arn:aws:kms:us-east-2:xxxxxxxxx:key/502b409c-4da1-419f-a16e-eif453b3i49f
```

After that, if you create a backup targeting this BSL the content will be encrypted using this key.

This PR has been opened to clarify in the doc:
https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/126

**Comment by reasonerjt** [comment]
Closing as the PR has been merged.
