### ISSUE TITLE
Document community support for Velero and K8s versions

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/velero#4285]
We need to document the following support policies prominently on velero.io and/or on the Velero repo:

We will best effort support n-1 Velero releases (for example, since we are on 1.7.0, we will support 1.6.x and 1.7.x). If a user asks for help with 1.5.x or below (in this example), then we would ask them to upgrade to a supported version before we further investigate their issue (to best effort).  Note that we will support every patch release in the supported minor releases.

TABLE FOR K8s RELEASES TESTED AGAINST VELERO VERSIONS: We have tested release 1.7.0 on K8s versions x, y, and z. (Ideally, develop a chart showing which Velero versions were tested on which K8s releases).

We expect Velero versions x-y and Kubernetes releases a-b to work, but we will not provide community support for them.

TABLE FOR BREAKING CHANGES: Develop a three column table where the first column are Velero versions and the second column is the lowest Kubernetes version that works (i.e. below that version we know Velero won't work) and the third column is the highest Kubernetes version that works (i.e. above that version we know Velero won't work).

Next step: write document and fill in easy to know values and publicize PR with the community to get feedback.

**Comment by eleanor-millman** [comment]
Also relevant to this discussion: https://github.com/vmware-tanzu/velero#velero-compatabilty-matrix

**Comment by eleanor-millman** [comment]
Community meeting agreed on n-1, to do is to post on slack and send out to distro list for feedback.

**Comment by a-mccarthy** [comment]
@eleanor-millman do you think this issue covers this [slack thread](https://kubernetes.slack.com/archives/C6VCGP4MT/p1646252906768049)? i.e. that Velero verifies/tests upgrades for supported versions of Velero, and a recommendation that folks test their upgrade path before performing the upgrade.

**Comment by eleanor-millman** [comment]
@a-mccarthy yes, I think that is enough for now. We can always open a new issue if you document that and we still have more questions. 

Please tag me on the final PR, then I can send out a notification on slack and to the distro list to make sure folks know of this policy. 

Thanks and sorry for the delay!
