### ISSUE TITLE
Unable to take volume snapshot of openstack cinder csi volumes in OVH

### ISSUE THREAD

**Issue by kusirajiv** [vmware-tanzu/velero#4287]
**What steps did you take and what happened:**
- I have a k8s cluster in OVH. The volume provisioner used in ovh for PVCs is "cinder.csi.openstack.org".  I was trying to  snapshot these CSI backed PVCs in GCP from the steps mentioned in the official doc (https://velero.io/docs/v1.7/csi/) but it is not working as expected. It is also mentioned in the doc that the CSI snapshot feature in velero is still under development and features may not work as expected.  Is this feature working now or is it still under development ? 
- 
**What did you expect to happen:**
- I used velero-plugin-for-csi  as object storage plugin. Here is my values.yaml file.
#########
image:
  repository: velero/velero
  tag: v1.5.3
  pullPolicy: IfNotPresent

  imagePullSecrets: []

cleanUpCRDs: true
podAnnotations: {}

podLabels: {}

resources: {}

dnsPolicy: ClusterFirst

initContainers:  
  name: velero-plugin
  image: velero/velero-plugin-for-csi:v0.1.0
  imagePullPolicy: IfNotPresent
  
priorityClassName: ""

tolerations: []

affinity: {}

nodeSelector: {}

extraVolumes: []

extraVolumeMounts: []

metrics:
  enabled: true
  scrapeInterval: 30s
  scrapeTimeout: 10s

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/metrics"

  serviceMonitor:
    enabled: false
    additionalLabels: {}

installCRDs: false

enableHelmHooks: true

configuration:
  provider: gcp
  backupStorageLocation:
    name: 
    provider:
  
    bucket: gcs_bucket
    caCert:
   
    prefix:
    
    config: {}
   
  volumeSnapshotLocation:
    name: velero
    provider:
   
    config: {}
 

 

  resticTimeout:

  restoreResourcePriorities:
 
  restoreOnlyMode:

'"
  extraEnvVars: {}

  features: EnableCSI

  logLevel:

  logFormat:

  defaultVolumesToRestic:

rbac:
  create: true
  clusterAdministrator: true

serviceAccount:
  server:
    create: true
    name:
    annotations:

cloud:
  cred: {} 
credentials:
 
  useSecret: true
 
  name:
 
  existingSecret:

  secretContents: 
    gcp: "base64_encoded_service_account" 
    aws: 
      access_key: 
      secret_key: 
    azure: ""
 
  extraEnvVars: {}
environment-variables
  extraSecretRef: ""

backupsEnabled: true
snapshotsEnabled: true

deployRestic: false

restic:
  podVolumePath: /var/lib/kubelet/pods
  privileged: false
  priorityClassName: ""
  resources: {}
  tolerations: []

  extraVolumes: []

  extraVolumeMounts: []

  
  dnsPolicy: ClusterFirst
  securityContext: {}
   

configMaps: {}

##################
The expected output is to have the snapshot created in GCP of these CSI backed PVCs.

- `kubectl logs deployment/velero -n velero`

time="2021-10-27T07:10:03Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="unable to locate ObjectStore plugin named velero.io/gcp" logSource="pkg/controller/backup_sync_controller.go:168"

If i change this section of values.yaml
 image: velero/velero-plugin-for-csi:v0.1.0
to 
image: velero/velero-plugin-for-gcp:v1.1.0,

the above error disappears but it works for snapshotting GKE PVCs only. Since, OVH Clusters uses CSI backed PVCs, the official doc suggests to use velero/velero-plugin-for-csi:v0.1.0 image which gives the same above error above. 

**Environment:**

- Velero version :  1.5.3
- Kubectl client version: v1.17.4
- Kubernetes version: v1.20.2
- Cloud provider: OVH 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by dsu-igeek** [comment]
Velero needs two things to take a backup with snapshots - an object store plugin for storing the Velero backup metadata and a volume snapshotter plugin to take the actual snapshots.  For most cloud providers those are combined together, e.g. the GCP plugin contains both an object store plugin and a volume snapshotter plugin.  The CSI plugin only provides volume snapshotting capabilities so it needs to be combined with another plugin to provide the object store interface.  Please try installing both the GCP plugin and the CSI plugin.

Also, be aware that CSI snapshots may not actually create a durable backup that will persist if the local storage is lost.  I think with Ceph, those snapshots will only be kept in the local Ceph storage system.  If you want to just have snapshots you can restore from quickly that's OK, but if you're expecting a backup that will survive the loss of the Ceph system, look at using the Restic integration to back up to the object store.

Closing for now, but please re-open if installing the two plugins doesn't work or you have additional questions.

**Comment by kusirajiv** [comment]
Backup of PVCs in  GKE cluster is working fine but in OVH it's failing. The volume provisioner used in ovh for PVCs is "cinder.csi.openstack.org". I was trying to take volume snapshot of OVH PVCs and store them in GCP. I used both plugins. 
I have used GCP as provider and velero/velero-plugin-for-csi:v0.1.0 as image in initContainer as mentioned in the values.yaml file above. Though it's not working as expected. Please kindly let me know if i'm missing anything here.

**Comment by blackpiglet** [comment]
@kusirajiv 
When using Velero in OpenStack, I think the object storage plugin should be OpenStack specific, which should be [https://github.com/Lirt/velero-plugin-for-openstack](url).
You can find the provider and plugins relation matrix here: [https://velero.io/docs/v1.7/supported-providers/#community-supported-providers](url).
