### ISSUE TITLE
Velero assumes there is v1beta CustomResourceDefintion of Traefik CRDs

### ISSUE THREAD

**Issue by kitos9112** [vmware-tanzu/velero#4290]
**What steps did you take and what happened:**
I've deployed velero to execute daily backup runs leveraging the default configuration as per the Helm chart instructs, nothing super elaborated or overwhelming as I'm still starting with it. Therefore, I suspect there's nothing wrong with the configuration itself as I've verified that both logs and backups are getting stored in the minio-s3 bucket key(s) correctly.

Nevertheless, there's an interesting precise number of 8 errors in the velero logs as all of my backups are partially failing. An example follows:

```sh
time="2021-10-27T20:38:17+01:00" level=info msg="CustomResourceDefinition ingressroutes.traefik.containo.us appears to be v1beta1, fetching the v1beta version" CRD=ingressroutes.traefik.containo.us backup=velero/velero-daily-backup-20211027203729 cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:91" plugin=RemapCRDVersionAction pluginName=velero
time="2021-10-27T20:38:17+01:00" level=info msg="1 errors encountered backup up item" backup=velero/velero-daily-backup-20211027203729 logSource="pkg/backup/backup.go:431" name=ingressroutes.traefik.containo.us
```
There's 1 error event per number of Traefik CRD that exists in my cluster that is attempted to be backed up. It's interesting because velero performs the full backup of those CRD versioned at `v1alpha` previously:

```sh
time="2021-10-27T20:37:44+01:00" level=info msg="Getting items for resource" backup=velero/velero-daily-backup-20211027203729 group=traefik.containo.us/v1alpha1 logSource="pkg/backup/item_collector.go:170" resource=traefikservices
time="2021-10-27T20:37:44+01:00" level=info msg="Listing items" backup=velero/velero-daily-backup-20211027203729 group=traefik.containo.us/v1alpha1 logSource="pkg/backup/item_collector.go:298" namespace= resource=traefikservices
time="2021-10-27T20:37:44+01:00" level=info msg="Retrieved 0 items" backup=velero/velero-daily-backup-20211027203729 group=traefik.containo.us/v1alpha1 logSource="pkg/backup/item_collector.go:350" namespace= resource=traefikservices
```

[Log raw source data](https://gist.github.com/kitos9112/481fb0b3416b37885e119efe54bba007)

**What did you expect to happen:**

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
```sh
❯ k logs deployment/velero -n velero
Found 8 pods, using pod/restic-g988f
time="2021-10-25T23:49:15+01:00" level=info msg="Setting log-level to INFO"
time="2021-10-25T23:49:15+01:00" level=info msg="Starting Velero restic server v1.7.0 (9e52260568430ecb77ac38a677ce74267a8c2176)" logSource="pkg/cmd/cli/restic/server.go:87"
2021-10-25T23:49:15.985+0100    INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
```
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```sh
❯ velero backup describe velero-daily-backup-20211027203729 -n velero
Name:         velero-daily-backup-20211027203729
Namespace:    velero
Labels:       app.kubernetes.io/instance=velero
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=velero
              helm.sh/chart=velero-2.26.1
              velero.io/schedule-name=velero-daily-backup
              velero.io/storage-location=default
Annotations:  helm.sh/hook=post-install,post-upgrade,post-rollback
              helm.sh/hook-delete-policy=before-hook-creation
              velero.io/source-cluster-k8s-gitversion=v1.22.2+k3s2
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=22

Phase:  PartiallyFailed (run `velero backup logs velero-daily-backup-20211027203729` for more information)

Errors:    8
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  168h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-10-27 20:37:35 +0100 BST
Completed:  2021-10-27 20:38:21 +0100 BST

Expiration:  2021-11-03 19:37:35 +0000 GMT

Total items to be backed up:  2025
Items backed up:              2025

Velero-Native Snapshots: <none included>

Restic Backups (specify --details for more information):
  Completed:  2
```
- `velero backup logs <backupname>`
**This is probably something else that needs to be addressed. I'll troubleshoot that later and provide more detail if I'm not able to solve it.**
```sh
❯ velero backup logs velero-daily-backup-20211027203729
An error occurred: gzip: invalid header
```

**Anything else you would like to add:**
After digging a little bit into this logging message I found out that there's a `switch` directive in the code that evaluates the following conditions to interpret the "likely" existence of v1beta CRDs without actually interrogating the API server beforehand. So I wonder if those three conditions (_hasSingleVersion_, _hasNonStructuralSchema_, and _hasPreserveUnkownFields_) are not sufficient when evaluating a v1alpha compliant CRD?

```go
// https://github.com/vmware-tanzu/velero/blob/main/pkg/backup/remap_crd_version_action.go#L90
	switch {
	case hasSingleVersion(crd), hasNonStructuralSchema(crd), hasPreserveUnknownFields(crd):
		log.Infof("CustomResourceDefinition %s appears to be v1beta1, fetching the v1beta version", crd.Name)
		item, err = fetchV1beta1CRD(crd.Name, a.betaCRDClient)
		if err != nil {
			return nil, nil, err
		}
	default:
		log.Infof("CustomResourceDefinition %s does not appear to be v1beta1, backing up as v1", crd.Name)
	}
```

**Environment:**

- Velero version (use `velero version`):  v1.7.0
- Velero features (use `velero client config get features`):  v1.7.0
- Kubernetes version (use `kubectl version`):
```yaml
clientVersion:
  buildDate: "2021-09-15T21:38:50Z"
  compiler: gc
  gitCommit: 8b5a19147530eaac9476b0ab82980b4088bbc1b2
  gitTreeState: clean
  gitVersion: v1.22.2
  goVersion: go1.16.8
  major: "1"
  minor: "22"
  platform: linux/amd64
serverVersion:
  buildDate: "2021-10-05T20:29:50Z"
  compiler: gc
  gitCommit: 3f5774b41eb475eb10c93bb0ce58459a6f777c5f
  gitTreeState: clean
  gitVersion: v1.22.2+k3s2
  goVersion: go1.16.8
  major: "1"
  minor: "22"
  platform: linux/arm64
```
- Kubernetes installer & version: v1.22.2+k3s2
- Cloud provider or hardware configuration: A mix of AMD64 and ARM64 local laptops and raspberry Pi devices. Velero has been running on AMD64 nodes
- OS (e.g. from `/etc/os-release`):
```
root@amd64-node:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by dsu-igeek** [comment]
@ kitos9112 K8s 1.22 no longer supports the older v1Beta1 CRD definition format.  Did you upgrade Kubernetes?  You may need to upgrade the Traefik CRDs or make sure you do not have obsolete CRDs present.  There are two different versions present.  One is the version of the API defined by Traefik, which is v1alpha1.  This is fine.  The other is the version of the CRD definition - previously the CRD itself was a v1beta1 resource, it is now a v1 resource and CRDs themselves need to be updated to the new format, but can continue to define things like a v1alpha1 resource.  The Velero code is attempting to handle the two different formats - in 1.21 it is possible to have both v1beta1 and v1 CRDS, however in 1.22 only v1 CRDs will work.

For the log issue
`velero backup logs velero-daily-backup-20211027203729
An error occurred: gzip: invalid header`
Velero attempts to download the log file using a pre-signed URL to the machine running the client.  With minio setups it's pretty common to have issues like permission problems, Minio host names that are not accessible from the client and certificate issues.  Would you check to see if you can download a file from the bucket to your local machine using either the minio or aws command line?

**Comment by kitos9112** [comment]
Hi @dsu-igeek Thanks for replying!
Yes, I've been upgrading my K3s cluster recently to v1.22. However, all previous CRDs got automatically pruned from my cluster (I cannot find CRDs with the old v1beta1 convention), in fact, I've been using `apiextensions/v1` for Traefik since I installed the cluster back in March this year. They switched to this new apiVersion back in December last year as per their [commit history](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/crds/ingressroute.yaml) to the repository. My understanding is that velero does not interrogate the API server and instead it performs a few internal functions to determine whether or not a v1beta1 exists in the cluster.

In regards to the logs issue, yes I can download the logs using my AWS CLI or even the ingress I expose to access the Minio GUI. Nonetheless, after reading other related GH issues I came to the same conclusion as you, but my `backupStorageLocation` configuration in the helm chart includes the `ingress` URL in the form of `publicUrl` config key.

```yaml
     configuration:
       backupStorageLocation:
         bucket: velero-backups
         config:
           publicUrl: https://minio.<publicDomain>
           region: eu-west-1
           s3ForcePathStyle: true
           s3Url: http://minio.tools:9000 # Inside the cluster
         default: true
         name: default
```

Is there anything I'm missing?

**Comment by blackpiglet** [comment]
Hi, @kitos9112 

For the error log issue, I found some lines from log you uploaded that may indicate the CRD version caused the backup partially fail. 
`time="2021-10-27T20:38:17+01:00" level=info msg="Executing RemapCRDVersionAction" backup=velero/velero-daily-backup-20211027203729 cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:58" pluginName=velero
time="2021-10-27T20:38:17+01:00" level=info msg="CustomResourceDefinition traefikservices.traefik.containo.us appears to be v1beta1, fetching the v1beta version" CRD=traefikservices.traefik.containo.us backup=velero/velero-daily-backup-20211027203729 cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:91" plugin=RemapCRDVersionAction pluginName=velero
time="2021-10-27T20:38:17+01:00" level=info msg="1 errors encountered backup up item" backup=velero/velero-daily-backup-20211027203729 logSource="pkg/backup/backup.go:431" name=traefikservices.traefik.containo.us`

Please verify CRD's API Version. Maybe after conversion, there's still some kept as v1beta1.

For the log issue, I'm not familiar with the BSL history. The thing I can confirm is that, for v1.7.0, I cannot find code in Velero repo to deal with config "publicURL". I am not sure whether there is other components work on this.
Is this error repeatable? If so, you can try to put publicURL value at s3URL.
@dsu-igeek I'm not confident on my conclusion on the log error. Please check whether "publicURL" in BSL config is still working.

**Comment by kitos9112** [comment]
Hi @blackpiglet 

On the CRD version note, I cannot find a practical v1beta1 reference in any of the Traefik CRD. I may have gone nuts but I ran `kubectl get customresourcedefinition` as well as `kubectl api-versions` without observing any v1beta1 stored for Traefik or other piece that caught my attention. I'm pretty sure Traefik is assuming there's a v1beta1 version of these CRDs after skimming through the [code piece](https://github.com/vmware-tanzu/velero/blob/main/pkg/backup/remap_crd_version_action.go#L90) I shared earlier

Regarding the logs, I'll give it a go and comment back. I was aiming to keep those internal comms within my K8s cluster to avoid having to leak that traffic to the outside (despite being encrypted)

**Comment by kitos9112** [comment]
Yes, after configuring my API endpoint for the S3 bucket I can retrieve the logs from the CLI using velero

**Comment by kitos9112** [comment]
@blackpiglet @dsu-igeek 
After re-deploying all Traefik CRDs I managed to get a complete&successful Velero backup. Still not sure what happened, but I wonder if this was related to the way helm approaches `CRDs` as they never get upgraded upon a successful install. 

https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource

**Comment by blackpiglet** [comment]
Great to hear you manage velero to do a successful backup. 
I will also check about the helm and Traefik.

**Comment by stromvirvel** [comment]
I actually have the same problem, with two of my CRDs `helmreleases.helm.fluxcd.io` and `sealedsecrets.bitnami.com`. Both CRDs are deployed under apiVersion `apiextensions.k8s.io/v1`, but for some reason, Velero still says:

```
CustomResourceDefinition sealedsecrets.bitnami.com appears to be v1beta1, fetching the v1beta version
```

And then tries and fails to backup that CRD.

I have another cluster still running on v1.21, and it seems that the CRDs are applied in both, `v1` and `v1beta1`.

```
❯ k get CustomResourceDefinition.v1beta1.apiextensions.k8s.io sealedsecrets.bitnami.com
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
NAME                        CREATED AT
sealedsecrets.bitnami.com   2020-03-02T16:17:55Z
❯ k get CustomResourceDefinition.v1.apiextensions.k8s.io sealedsecrets.bitnami.com
NAME                        CREATED AT
sealedsecrets.bitnami.com   2020-03-02T16:17:55Z
❯ k get CustomResourceDefinition.v1beta1.apiextensions.k8s.io helmreleases.helm.fluxcd.io
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
NAME                          CREATED AT
helmreleases.helm.fluxcd.io   2020-03-09T09:03:58Z
❯ k get CustomResourceDefinition.v1.apiextensions.k8s.io helmreleases.helm.fluxcd.io
NAME                          CREATED AT
helmreleases.helm.fluxcd.io   2020-03-09T09:03:58Z
```

Simply redeploying the CRDs doesn't help, as the `v1beta1` CRDs will not be affected by it.

Also, I've checked the backups before I upgraded to v1.22, and velero indeed backed up the `v1beta1` CRDs only.

**Velero team**, how does Velero decide that it needs to backup `v1beta1` instead of `v1`?
