### ISSUE TITLE
Azure plugin fails to connect to storage container using existing Secret

### ISSUE THREAD

**Issue by HighWatersDev** [vmware-tanzu/velero#4291]
**What steps did you take and what happened:**
I installed Velero on AKS cluster using Azure plugin v1.3.0 using Helm. I'm using STORAGE_ACCOUNT_ACCESS_KEY to connect to the storage. My cluster already has the secret provisioned in the format

```
secret_name = cloud
secret_value = 
AZURE_STORAGE_ACCOUNT_ACCESS_KEY=XXXXXXX
AZURE_CLOUD_NAME=AzurePublicCloud
```
I used `credentials.existingSecret` to specify the secret. When I check the logs of velero container, I see this error:
```
time="2021-10-28T01:01:47Z" level=error msg="Error getting backup store for this location" backupLocation=azure controller=backup-sync error="rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/aaaa-0000-0000-0000/resourceGroups/Backups/providers/Microsoft.Storage/storageAccounts/XXXX/listKeys?%24expand=kerb&api-version=2019-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request\"}" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:217" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:175"

```
**What did you expect to happen:**
The exact same secret works on a different cluster when installed via `velero` command. I'd expect velero pod to be able to authenticate to Azure storage account using the existing secret.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
```
time="2021-10-28T01:09:18Z" level=error msg="Error getting backup store for this location" backupLocation=azure controller=backup-sync error="rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/aaaa-0000-0000/resourceGroups/Backups/providers/Microsoft.Storage/storageAccounts/XXXXX/listKeys?%24expand=kerb&api-version=2019-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request\"}" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:217" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:175"
```
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```
NAME                   AGE
daily-20211027215030   3h20m
daily-20211028010056   10m
```
- `velero backup logs <backupname>`
```
velero backup-location get
NAME    PROVIDER   BUCKET/PREFIX       PHASE     LAST VALIDATED   ACCESS MODE   DEFAULT
azure   azure      aks_cluster   Unknown   Unknown          ReadWrite
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  1.7.0
- Velero features (use `velero client config get features`): NOT SET
- Kubernetes version (use `kubectl version`): 1.21
- Kubernetes installer & version: AKS/1.20.9
- Cloud provider or hardware configuration: Azure

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by HighWatersDev** [comment]
Hi,

Any update on this issue?

**Comment by ywk253100** [comment]
@HighWatersDev Please refer to the comment https://github.com/vmware-tanzu/velero/issues/4825#issuecomment-1097931524, your issue is very likely the same one.

I'm closing this issue, feel free to reopen it
