### ISSUE TITLE
Velero Not able to restore data

### ISSUE THREAD

**Issue by tppalani** [vmware-tanzu/velero#4294]
Even with restic , only the state of the PV is getting stored .

Did you check the data after mounting the volume ? Does it show old data ??

_Originally posted by @vishumindtree in https://github.com/vmware-tanzu/velero/issues/1862#issuecomment-934414402_

**Comment by dsu-igeek** [comment]
Is this the same issue as #4301?  If not, please re-open and add the usual info with logs, etc and a description of the problem.
