### ISSUE TITLE
Azure Plugin doesn't query the correct endpoint for AzureUSGovernmentCloud

### ISSUE THREAD

**Issue by dnnadmins** [vmware-tanzu/velero#4299]
When installing velero with any method (Service Principle, AAD, or storage keys) it always attempts to query https://management.azure.com instead of  https://management.usgovcloudapi.net

Here is the pertinent information to reproduce using keys. (##### is placeholder for valid info)
Deployed from Windows 10 machine to AKS v1.20.9 in usgovvirgnia using velero v1.7.0

The credentials-velero.txt file contains;
AZURE_STORAGE_ACCOUNT_ACCESS_KEY=######################
AZURE_CLOUD_NAME=AzureUSGovernmentCloud

The command being run is;
        velero install `
            --provider azure `
            --plugins velero/velero-plugin-for-microsoft-azure:v1.3.0 `
            --bucket velero `
            --secret-file .\credentials-velero.txt  `
            --backup-location-config resourceGroup=######################,storageAccount=######################,subscriptionId=###################### `
            --use-volume-snapshots=false

The error being generated in the log files

[velero-776dc6df49-rkd7t velero]  time="2021-10-29T14:59:48Z" level=error msg="Error getting a backup store" backup-storage-location=default controller=backup-storage-location error="rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/######################/resourceGroups/######################/providers/Microsoft.Storage/storageAccounts/######################/listKeys?%24expand=kerb&api-version=2019-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Identity not found\"}" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:213" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_storage_location_controller.go:100"

I've also attempted this on all plugin versions from v1.1.1 to 1.30 and added the; 
AZURE_ENVIRONMENT=AzureUSGovernmentCloud
with no sucess.

**Comment by zubron** [comment]
Hi @dnnadmins - Sorry you're having problems with this.

I'm not familiar with running on Azure Government cloud, but a similar issue was reported in #3786, where a solution was to [set `AZURE_ENVIRONMENT=AzureUSGovernmentCloud` in the credentials file](https://github.com/vmware-tanzu/velero/issues/3786#issuecomment-856322042). I see that you're setting that environment variable - did you set in the deployment or in the credentials file?

**Comment by dnnadmins** [comment]
> - did you set in the deployment or in the credentials file?

I set it in the credentials file at the time I did the deployment and it didn't seem to have any effect.

**Comment by zubron** [comment]
In the meantime, we may need to remove the Government cloud from the supported list in this section of the plugin docs: https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#create-service-principal

**Comment by matnav** [comment]
This is still a much needed feature for you USGov bois.

**Comment by ywk253100** [comment]
@matnav Did you try to set the environment variable `AZURE_ENVIRONMENT=AzureUSGovernmentCloud` in the credential file?

**Comment by matnav** [comment]
yes, sorry I got wrapped up with deploying this. This was exactly one of the undocumented things that need to be added to the credential file.

**Comment by matnav** [comment]
Also, huge hard-won lesson is that you need to use the v1.6.0 of velero-plugin-for-microsoft-azure. When I tried to deploy using the latest v1.7.0, it would seem to be fine, but the storage would never connect. It looked like from the logs that it was hitting an endpoint on the commercial side, so it was getting 404 storage account not found
