### ISSUE TITLE
Velero stops listing backups

### ISSUE THREAD

**Issue by bradwinfield** [vmware-tanzu/velero#4300]
Velero (TCE on Docker on Ubuntu) using a minio storage back end. I can take a backup and view the details of the backup. But after 20 or 30 seconds, Velero forgets about it.
TCE 0.9.1
====
$ velero version
I1029 15:44:13.624226 2438816 request.go:655] Throttling request took 1.038612606s, request: GET:https://172.18.0.2:6443/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s
Client:
	Version: v1.7.0
	Git commit: 9e52260568430ecb77ac38a677ce74267a8c2176
Server:
	Version: v1.6.3
# WARNING: the client version does not match the server version. Please update server

==== How to Replicate ====
$ velero backup create nginx3-backup2 --namespace velero --include-namespaces nginx3
$ velero backup describe nginx3-backup2
Name:     nginx3-backup2
Namespace:  velero
Labels:    velero.io/storage-location=minio
Annotations: velero.io/source-cluster-k8s-gitversion=v1.21.2+vmware.1-360497810732255795
       velero.io/source-cluster-k8s-major-version=1
       velero.io/source-cluster-k8s-minor-version=21
Phase: Completed
Errors:  0
Warnings: 0
...
$ velero backup get
NAME            STATUS     ERRORS  WARNINGS  CREATED                        EXPIRES  STORAGE LOCATION  SELECTOR
nginx3-backup2  Completed  0       0         2021-10-27 15:02:54 -0500 CDT  29d      minio             <none>
After 30 seconds...
$ velero backup describe nginx3-backup2
An error occurred: backups.velero.io "nginx3-backup2" not found
====
Looking in my Minio instance, I do see the backup files.
$ velero backup get
returns nothing... I just get the shell prompt back.

$ kubectl get backups -A
No resources found

==== kubectl version ====
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

==== docker version ====
$ docker version
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
...

==== Installation Notes ====
I used TCE 0.9.1 and the velero package. My experience report with the details are here: https://docs.google.com/document/d/1lF-UxoFmsow6f2RASTv7Fcgd74X01ukRZ0hJ-2z54Ic/edit

==== Cloud Provider or Hardware Configuration ====
Running on an Ubuntu 20.04 server 8 Gig RAM
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"

====
Will add logs shortly.

**Comment by dsu-igeek** [comment]
Hi Brad - when you have a chance, please add the logs.

**Comment by bradwinfield** [comment]
[debug.tar.gz](https://github.com/vmware-tanzu/velero/files/7462108/debug.tar.gz)

**Comment by bradwinfield** [comment]
I have cleaned and recreated my entire cluster and re-installed minio and velero. Still, I get the same result. 
I make a backup: $ velero backup create nginx-backup2 --namespace velero --include-namespaces nginx
Backup request "nginx-backup2" submitted successfully.

Then check the status: $ velero backup describe nginx-backup2
Name:         nginx-backup2
...

Then check the status after 30 seconds: $ velero backup describe nginx-backup2
An error occurred: backups.velero.io "nginx-backup2" not found

**Comment by bradwinfield** [comment]
I installed a 'standalone' TCE cluster and got the same results from velero.

**Comment by bradwinfield** [comment]
Log Supplied above.

**Comment by reasonerjt** [comment]
@bradwinfield 
By checking your debug log files bundle it seems that the backup resource do not exist.

Could you please double checking using `kubectl` ?
```
kubectl get backups -n velero
```

If it returns nothing, is it possible anyone or any script is removing the `backup` resource created by velero?
