### ISSUE TITLE
Suport arm64 in the CSI Plugin

### ISSUE THREAD

**Issue by anthr76** [vmware-tanzu/velero#4303]
Currentley only amd64 is published for the CSI Plugin

https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/main/Makefile

This issue tracks the progress to publush a fat manifest with arm64 support as well. Other archs might be worth doing, but not sure how the community feels. This can be easily accomplished with Docker buildx

**Comment by superherointj** [comment]
I also miss arm64 for CSI Plugin.

**Comment by niulechuan** [comment]
> A PR is welcome but we don't have resources to test on the arm infrastructures.

I can convince my boss that he can sponsor an ARM environment. can we talk?

**Comment by kaovilai** [comment]
Apart from test environment, if someone have time, look at
https://github.com/vmware-tanzu/velero-plugin-for-aws/commit/46c18b341f0dcfba468c2b5c254e3eb310defec0
and
https://github.com/vmware-tanzu/velero-plugin-for-aws/commit/fb77a5f5f2ea1c7b1148728debd4112fef7714b9

**Comment by kaovilai** [comment]
I think https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/167/ fixes this issue.

**Comment by kaovilai** [comment]
@blackpiglet can you confirm if https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/167/ fixes this issue?

**Comment by blackpiglet** [comment]
@kaovilai 
https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/167/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R62

I think this PR fixed this issue.
