### ISSUE TITLE
velero gcp plugin points to aws plugin 

### ISSUE THREAD

**Issue by alokhom** [vmware-tanzu/velero#4304]
**What steps did you take and what happened:**

Sources of backup:
only test-nginx namespace with a pvc based nginx pod

Background:
i have deployed 3 velero server pods on a namespace. in the folllowing way. using helm templates from velero helm repo.
- 2 pods velero with gcp plugin one using --default-volumes-to-restic flag and another not using it in the container args
- 1 velero pod with aws plugin for minio backup pointing to minio statefulset in same namespace

I have 3 BSLs.  All are in available state.
- 2 pointing GCP GCS object stores. with independent buckets - one default and one not default. 
- 1 minio object store BSL not default. 

3 schedules  where backing up clashes are rare
- schedule 1 point to default BSL GCP GCS deafult bucket - every 15 mins 
- schedule 2 point to restic BSL GCP GCS restic bucket. - every 7 mins 
- schedule 3 point to minio BSL  - every 11 mins 

I ran velero get backups command and see many backups are completed state on all 3 stores., triggered from schedules.  
But 50% there are partal and failed backups on gcp gcs be it restic and non restic 
partial backups logs are visible 
failed backups logs cannot be taken out as it says no logs found. 
minio backups are 100% ok. no problems in them. 

partially failed backup logs show ----
time="2021-11-01T08:30:17Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/no-restic-gcp-backup-schedule-20211101083016 error="unable to locate VolumeSnapshotter plugin named velero.io/aws" logSource="pkg/backup/item_backupper.go:449" name=pvc-00cfe208-2095-4e2b-a987-f350f542c79e namespace= persistentVolume=pvc-00cfe208-2095-4e2b-a987-f350f542c79e resource=persistentvolumes volumeSnapshotLocation=minio
--- 
it is not expected to show aws plugin  in a gcp backups leading to partial backup. 
for completed backups aws plugin does not show up. 
All these partial an failed backups are specifically seen in the gcp backups only and not in minio backups

**What did you expect to happen:**
gcs backups to be steady and 100% completed every time and not showing aws pugins pointing to minio bsl

**The output of the following commands will help us better understand what's going on**:

velero get backups command
https://gist.github.com/alokhom/7093e9172dfc1bed42869c1d0e5c9fcf

no restic resources.
https://gist.github.com/alokhom/96743686ca5f2d48c4d9d17b19c22c9e

with restic resources.
https://gist.github.com/alokhom/ca8ef09f4164856257e2c347611ac27d

restic with minio.
https://gist.github.com/alokhom/45ac1b4c5b7cf6bffb8820dc066b8620

- `kubectl logs deployment/velero -n velero`
https://gist.github.com/alokhom/6b7d1ee284f3ebdff6647271a69e4f13

- kubectl logs deployment/velero-restic-gcp -n velero
https://gist.github.com/alokhom/e2a051c0f45478f308c9959ea0e7b0ab

-  kubectl logs deployment/velero-restic-minio -n velero 
https://gist.github.com/alokhom/ff33167f24e5f7f1836bda1c7d91cb2f

- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
no restic backup that is partially backed up on gcp gcs
https://gist.github.com/alokhom/3a089285202857ae07412e4615e1729e

no restic with completed backup on gcp gcs
https://gist.github.com/alokhom/2a344e02647216526e25fa47c7c9898e

- `velero backup logs <backupname>`
partial backup log  no restic  on gcp gcs
https://gist.github.com/alokhom/d10b58588665796012f663432033e4db

completed backup log no restic on gcp gcs
https://gist.github.com/alokhom/f8577437698b6fc2e3ed4406b440dc7e

- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
did not come to restore till now

- `velero restore logs <restorename>`
did not come to restore till now

**Anything else you would like to add:**
our idea is to see which takes low space. gcs or minio  ( with or whithout restic ) 
failed backup logs not visible, why ?
https://gist.github.com/alokhom/e9a5fd44481bb475a12d7911b3f492b3

**Environment:**

- Velero version (use `velero version`): 
client ran command with 1.6.3 but now upgraded to 1.7
Client:
        Version: v1.7.0
        Git commit: 9e52260568430ecb77ac38a677ce74267a8c2176
Server:
        Version: v1.7.0

- Velero features (use `velero client config get features`): 
$ velero client config get features
features: <NOT SET>

- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.301", GitCommit:"17ad7bd6afa01033d7bd3f02ce5de56f940a915d", GitTreeState:"clean", BuildDate:"2021-08-24T05:18:54Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1

- Kubernetes installer & version:
gke standard instance on gcp

- Cloud provider or hardware configuration:
gcp with 
 gke  version 1.20.10-gke.301
 node  pool has 2 worker nodes of type e2-standard-4
 no scaleout

- OS (e.g. from `/etc/os-release`):
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_CRASH_ID=Lakitu
KERNEL_COMMIT_ID=490ca207fb0f23bca9d21c04e309502e1ed8b58d
GOOGLE_METRICS_PRODUCT_ID=26
VERSION=89
VERSION_ID=89
BUILD_ID=16108.470.11

**Vote on this issue!**
 :+1

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by dsu-igeek** [comment]
You cannot install multiple Velero instances in the same namespace.  Use a different namespace for each velero instance.
