### ISSUE TITLE
Invalid client secret - Velero

### ISSUE THREAD

**Issue by SoundaryaA3098** [vmware-tanzu/velero#4310]
**What steps did you take and what happened:**
Using velero (v1.7) backup tool, I am trying to backup the cluster data and volume data as I installed velero with restic. I have deployed velero in a k8s cluster in Azure and I use Azure Blob container as backup storage location.

I have created a scheduled backup which takes the full cluster backup once in a week. It's been 3 months that I installed velero and enabled the backup. But in recent days, I'm getting the error logs in velero pod like "Failed to refresh the token and invalid client secret provided"

**NOTE:** The actual expiration of the client secret I provided is till 2023 june.

**What did you expect to happen:**
Scheduling of the backups work until the client secret is originally getting expired.

**The output of the following commands will help us better understand what's going on**:

`kubectl logs deployment/velero -n velero` gives the following error,
 
`level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<subs-id>/resourceGroups/<rg>/providers/Microsoft.Storage/storageAccounts/<storage-acount-name>/listKeys?%24expand=kerb&api-version=2019-06-01: StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. Response body: {\"error\":\"invalid_client\",\"error_description\":\"AADSTSxyzabc: Invalid client secret is provided.\\r\\nTrace ID: <trace-id>\\r\\nCorrelation ID: <correlation-id>\\r\\nTimestamp: 2021-11-03 08:09:17Z\",\"error_codes\":[err-code],\"timestamp\":\"2021-11-03 08:09:17Z\",\"trace_id\":\"<trace-id>\",\"correlation_id\":\"<correlation-id>\",\"error_uri\":\"https://login.microsoftonline.com/error?code=<err-code>\"}" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:217" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:175"`

Velero backups are getting failed and not able to fetch details of the failed backup using "velero describe backup" cmd,

![Screenshot from 2021-11-03 14-16-14](https://user-images.githubusercontent.com/59388030/140031569-612d9f55-be1a-4c74-a8ff-b3fbbbef94a0.png)

**Environment:**

- Velero version (v1.7): 
- Kubernetes version (use `kubectl version`): v1.18.14
- Cloud provider or hardware configuration: Microsoft Azure
- OS (e.g. from `/etc/os-release`): Ubuntu

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
We discussed via slack channel already, the issue was there when you use velero v1.6, so it isn't caused by upgrading.

Could you double-check whether the client secret used by velero is correct or not? You can find the credential in the secret named `cloud-credentials` under `velero` namespace.
