### ISSUE TITLE
Make velero-plugin-for-csi  actually do backup REAL user data

### ISSUE THREAD

**Issue by liyimeng** [vmware-tanzu/velero#4318]
**Describe the problem/challenge you have**

As I understand,  velero-plugin-for-csi  today only backup VolumeSnapshotContent object, but not the REAL user data that the object is pointing to.  This make the plugin is much less useful. 

**Describe the solution you'd like**

velero-plugin-for-csi should backup real user data. This can be done by "mouting"   VolumeSnapshotContent in to a temporary pv, running restic against it.  By doing so, the plugin with be far more useful. 

**Anything else you would like to add:**

I hear that k8s team is discussing to have backup available natively like snapshot in CSI. 
if that happens, It might be duplicated work. But that discussion is just in very early phase, it make sense that velero support backing up user data in a csi snapshot into backup store. 

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
Velero is indeed based on the Kubernetes CSI snapshot: https://velero.io/docs/v1.7/csi/

**Comment by liyimeng** [comment]
@ywk253100 As I understand, the plugin  only backup meta data, i.e. the content of a bundle of yaml files, which is useless as a backup. the plugin should  at lease allow operator specify if it should backup user data as well. In some case, this might be skipped since some storage providers actually store snapshot content in external storage.

**Comment by ywk253100** [comment]
@liyimeng The CSI plugin backups the volume data by taking snapshots for now just like how the cloud provider-specific plugins(aws/azure/gcp) do.

Uploading the snapshot into the storage is in our roadmap and some background work is already in progress.
