### ISSUE TITLE
Support yaml file export for Kubernetes when restored the data

### ISSUE THREAD

**Issue by lianghao208** [vmware-tanzu/velero#4321]
**Describe the problem/challenge you have**

Sometimes we don't need to recover all the resources from velero backup snapshot, but we are not sure which resource to recover. Only when we check the resources list that we can decide which resources we would like to recover.
Is that possible to gernerate a resources list (maybe exported them as yaml files) so that we can easily know the snapshot contents to recover?

**Describe the solution you'd like**

Generate  a resources list  or  exported them as yaml files from velero backup.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
Try `velero backup describe <backupName> --details`, this command includes the backuped resource list
