### ISSUE TITLE
Velero can't detect volume Pod

### ISSUE THREAD

**Issue by fayssaldarif** [vmware-tanzu/velero#4325]
Hello Guys !

I have deployed velero + restric + minio  to backup and restore some namespaces k8s.

But one error has been occured.

`time="2021-11-08T13:43:01Z" level=warning msg="No volume named task-pv-volume found in pod test-namespace/mynginx-56495598d6-b2vwd, skipping" backup=velero/backup1 logSource="pkg/restic/backupper.go:135" name=mynginx-56495598d6-b2vwd namespace=test-namespace resource=pods`

And the PV has been created correctly
```kubectl get pv | grep task
task-pv-volume                             10Gi       RWO            Delete           Bound    test-namespace/nfs-test-namespace-pvc   local-path              23m
```

Backup results.
```
Name:         backup1
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.21.0
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=21

Phase:  Completed

Errors:    0
Warnings:  1

Namespaces:
  Included:  test-namespace
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-11-08 14:42:55 +0100 CET
Completed:  2021-11-08 14:43:02 +0100 CET

Expiration:  2021-12-08 14:42:55 +0100 CET

Total items to be backed up:  17
Items backed up:              17

Resource List:
  apps/v1/Deployment:
    - test-namespace/mynginx
  apps/v1/ReplicaSet:
    - test-namespace/mynginx-56495598d6
  v1/ConfigMap:
    - test-namespace/kube-root-ca.crt
  v1/Event:
    - test-namespace/mynginx-56495598d6-b2vwd.16b595d9ec76f5ee
    - test-namespace/mynginx-56495598d6-b2vwd.16b595da398d3a54
    - test-namespace/mynginx-56495598d6-b2vwd.16b595da8e0ef71e
    - test-namespace/mynginx-56495598d6-b2vwd.16b595da9b89cc4c
    - test-namespace/mynginx-56495598d6-b2vwd.16b595daa97ceacb
    - test-namespace/mynginx-56495598d6.16b595d9af1c82b1
    - test-namespace/mynginx.16b595d9ab1dd006
    - test-namespace/nfs-test-namespace-pvc.16b595d9a59b4c1f
  v1/Namespace:
    - test-namespace
  v1/PersistentVolume:
    - task-pv-volume
  v1/PersistentVolumeClaim:
    - test-namespace/nfs-test-namespace-pvc
  v1/Pod:
    - test-namespace/mynginx-56495598d6-b2vwd
  v1/Secret:
    - test-namespace/default-token-bgnjs
  v1/ServiceAccount:
    - test-namespace/default

Velero-Native Snapshots: <none included>```





**Environment:**

- Velero version (use `velero 1.7.0`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl 1.21.0`):
- Kubernetes installer & version:
- OS : Centos 7

**Comment by fayssaldarif** [comment]
And I have annotate my pod correctly
```
Annotations:  backup.velero.io/backup-volumes: task-pv-volume
              cni.projectcalico.org/podIP: 10.244.14.244/32
              cni.projectcalico.org/podIPs: 10.244.14.244/32
```

**Comment by blackpiglet** [comment]
Hi, @fayssaldarif.

I think the annotation should point to the volume name. Not the PV name.

Please refer to document for detail: [https://velero.io/docs/v1.7/restic/#using-opt-in-pod-volume-backup](using opt in pod volume backup)

**Comment by fayssaldarif** [comment]
Hi @blackpiglet 
Thanks for your response, you are right, need to annotate Pod with the volume name.
I was surprised, velero restric doesn't support the hostPath volume type.
Do you know if velero restric support the local-path provisionner ? 
https://github.com/rancher/local-path-provisioner

``` Local Path Provisioner provides a way for the Kubernetes users to utilize the local storage in each node. Based on the user configuration, the Local Path Provisioner will create hostPath based persistent volume on the node automatically. It utilizes the features introduced by Kubernetes Local Persistent Volume feature, but make it a simpler solution than the built-in local volume feature in Kubernetes. ```

**Comment by blackpiglet** [comment]
@fayssaldarif 
I'm still new to Velero project, so I cannot guarantee local-path provisioner will work, and there is also not documented in the  supported provisioner list document, but, since Velero support local persistent volume, and local path provisioner is based on local persistent volume, I think this maybe work.

**Comment by fayssaldarif** [comment]
@blackpiglet 
Thanks for your help.
I still have the same issue, Velero doesn't support the local-path provisioner also.
I am going to close this issue
