### ISSUE TITLE
velero not support local pv (rancher/local-path-provisioner )

### ISSUE THREAD

**Issue by hamishliu** [vmware-tanzu/velero#4335]
velero install  --provider aws --plugins velero/velero-plugin-for-aws:v1.3.0 --bucket  velero-staging \
--secret-file ./credentials-minio \
--use-restic \
--default-volumes-to-restic \
--use-volume-snapshots=false \
--backup-location-config \
region=us-east-1,s3ForcePathStyle="true",s3Url=http://10.43.254.125:9000

[root@VM-120-187-centos /data/velero]# velero backup describe nginx-example-pvc
Name:         nginx-example-pvc
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.19.7
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=19

Phase:  PartiallyFailed (run `velero backup logs nginx-example-pvc` for more information)

Errors:    1
Warnings:  0

Namespaces:
  Included:  nginx-example
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-11-11 15:47:34 +0800 CST
Completed:  2021-11-11 15:48:41 +0800 CST

Expiration:  2021-12-11 15:47:34 +0800 CST

Total items to be backed up:  11
Items backed up:              11

Velero-Native Snapshots: <none included>

[root@VM-120-187-centos /data/velero]# velero backup logs nginx-example-pvc |grep err
time="2021-11-11T07:47:38Z" level=info msg="Skipping resource because it's cluster-scoped and only specific namespaces are included in the backup" backup=velero/nginx-example-pvc group=rbac.authorization.k8s.io/v1 logSource="pkg/backup/item_collector.go:197" resource=clusterroles
time="2021-11-11T07:47:41Z" level=info msg="stderr: " backup=velero/nginx-example-pvc hookCommand="[/sbin/fsfreeze --freeze /var/log/nginx]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=pre hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:172" name=nginx-deployment-66689547d-w74dq namespace=nginx-example resource=pods
time="2021-11-11T07:48:41Z" level=info msg="stderr: " backup=velero/nginx-example-pvc hookCommand="[/sbin/fsfreeze --unfreeze /var/log/nginx]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=post hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:172" name=nginx-deployment-66689547d-w74dq namespace=nginx-example resource=pods
time="2021-11-11T07:48:41Z" level=info msg="1 errors encountered backup up item" backup=velero/nginx-example-pvc logSource="pkg/backup/backup.go:431" name=nginx-deployment-66689547d-w74dq
time="2021-11-11T07:48:41Z" level=error msg="Error backing up item" backup=velero/nginx-example-pvc error="timed out waiting for restic repository to become ready" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/repository_ensurer.go:181" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryEnsurer).EnsureRepo" logSource="pkg/backup/backup.go:435" name=nginx-deployment-66689547d-w74dq

**Comment by zubron** [comment]
Hi @hamishliu 👋 

Local path provisioner uses hostPath volumes and unfortunately these are not supported by Velero. Please see the following discussion on for more details: https://github.com/vmware-tanzu/velero/discussions/3378.

This is not something that we will be fixing as we are currently not adding any restic specific features and are working on a more general swappable approach for data movement. See #3229.

**Comment by hamishliu** [comment]
thanks!
