### ISSUE TITLE
Velero throwing  Unauthorized error while backing up elasticsearch, kafka (zookeeper ) and post-gres services.

### ISSUE THREAD

**Issue by ankitrao-lightbeam** [vmware-tanzu/velero#4337]
**What steps did you take and what happened:**
Deployed velero setup using the below command, on my EKS cluster, where I have my application deployed.

velero install \
--provider aws \
--plugins velero/velero-plugin-for-aws:v1.2.0 \
--bucket <bucket-name> \
--backup-location-config region=us-east-1 \
--snapshot-location-config region=us-east-1 \
--secret-file velero-creds

Ran the backup command:

velero backup create <backup-name> --include-namespaces <namespace>

**What did you expect to happen:**

Complete backup of my application

**What actually happened'**

Backup completed with state: PartiallyFailed

For services like elasticsearch, kafka (zookeeper) and post-gres, below errors are getting logged:

error getting volume info: rpc error: code = Unknown desc = UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 6444b7b7-47ea-46b7-a983-d2ddfe0d011c" logSource="pkg/backup/backup.go:435.

InvalidVolume.NotFound: The volume 'vol-0xxxx' does not exist

**Anything else you would like to add:**

The velero creds have admin access on the account, so this doesn't seem to be due to incorrect permissions.

**Environment:**

- Velero version (use `velero version`):  Tried both velero/velero-plugin-for-aws:v1.2.0 and v 1.0.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.21
- Kubernetes installer & version:
- Cloud provider or hardware configuration: AWS [ 2 t3.2xlarge instances ]
- OS (e.g. from `/etc/os-release`): Amazon Linux

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment]
Hi @ankitrao-lightbeam :wave: 

That error is coming from the AWS plugin and suggests that the credentials that you are using do not have permissions to fetch EBS volumes. Please ensure that you have [set the correct permissions](https://github.com/vmware-tanzu/velero-plugin-for-aws#Set-permissions-for-Velero) when generating the credentials.

I am going to close this, but if you have further problems with this, let us know and we can reopen.

**Comment by ankitrao-lightbeam** [comment]
Hi @zubron ,

Thank you for the quick revert.
But as already mentioned, I've given Admin permission to the velero user for the time being, till the backup works fine.
I'm still facing the issue with the Admin creds.

I'll still give it a retry and add an according update on the ticket.

- TIA

**Comment by ankitrao-lightbeam** [comment]
[ UPDATE ]

Hi @zubron,

I further verified the  logs post granting admin permissions to the velero user and I've noticed "Voulme not found errors" in the velero logs.

These errors are sepcific to the below services:
elasticsearch, kafka (zookeeper) and post-gres

Can you please provide insights on the same.

-TIA

**Comment by zubron** [comment]
Hi @ankitrao-lightbeam - Could you please provide the full logs of the velero deployment? If you are using Velero 1.7.0, you could instead run `velero debug --backup <backupname>` to provide us with the full details for us to investigate.

Out of curiosity, are your workloads running in `us-east-1`? I'm wondering if the snapshot location is configured incorrectly and those volumes are perhaps in a different region. This could be one reason for them not being found.

**Comment by zubron** [comment]
Closing this issue as we have not had a response to diagnose further. If you need further help, please let us know and it can be reopened. Thanks!
