### ISSUE TITLE
Velero pod crashing due to error "velero-plugin-for-aws: permission denied"

### ISSUE THREAD

**Issue by indrajithgihan** [vmware-tanzu/velero#4339]
**What steps did you take and what happened:**

I am running Velero 1.7.0 in an on-prem K8 cluster with Minio. I am getting error "logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
An error occurred: fork/exec /plugins/velero-plugin-for-aws: permission denied" when running Velero with Minio. The same setup works fine in other clusters and problem happens only in this cluster having same K8 version. I use velero-plugin-for-aws:v1.2.1 and below is the vereo install command:

velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.2.1 \
    --bucket velero \
    --secret-file ./credentials-velero \
    --use-volume-snapshots=false \
    --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://minio-service.velero.svc.cluster.local:9000

**What did you expect to happen:**
Velero pod should run without CrahLoopbackoff

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`

time="2021-11-13T17:54:03Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:175"
time="2021-11-13T17:54:03Z" level=info msg="Starting Velero server v1.7.0 (9e52260568430ecb77ac38a677ce74267a8c2176)" logSource="pkg/cmd/server/server.go:177"
time="2021-11-13T17:54:03Z" level=info msg="1 feature flags enabled []" logSource="pkg/cmd/server/server.go:179"
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-remap-version
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/apiservice
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-pvc-node-selector
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/cluster-role-bindings
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-preserve-fields
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/init-restore-hook
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2021-11-13T17:54:03Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
An error occurred: fork/exec /plugins/velero-plugin-for-aws: permission denied
[root@WCAXMSSTGMN02 ~]# kubectl logs -f velero-7d7fdd64f7-zfwxx -n velero 
time="2021-11-13T18:02:14Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:175"
time="2021-11-13T18:02:14Z" level=info msg="Starting Velero server v1.7.0 (9e52260568430ecb77ac38a677ce74267a8c2176)" logSource="pkg/cmd/server/server.go:177"
time="2021-11-13T18:02:14Z" level=info msg="1 feature flags enabled []" logSource="pkg/cmd/server/server.go:179"
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-remap-version
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/apiservice
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-pvc-node-selector
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/cluster-role-bindings
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-preserve-fields
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/init-restore-hook
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2021-11-13T18:02:15Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
An error occurred: fork/exec /plugins/velero-plugin-for-aws: permission denied

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.7
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.18.20
- Kubernetes installer & version:
- Cloud provider or hardware configuration: On-Prem
- OS (e.g. from `/etc/os-release`): Redhat 7.9

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by indrajithgihan** [comment]
This is due to /var partition mounted as noexec (non-executable) in the worker node. I have remounted the /var partition with exec and it resolved the issue.

mount -o remount,exec /var

@zubron 
Kindly note the above resolution step as I have seen some people experiencing this so you will give this as a clue since this is not an issue related to velero.

**Comment by technerd4357** [comment]
But this is against CIS benchmark standard. We don't want to violate it. Is there any configuration parameter to use someother path instead of /var ?

**Comment by veerendra2** [comment]
Hi, we ran into this issue after using ephemeral volumes for velero server. After seeing this issue and discussion(https://github.com/vmware-tanzu/velero/discussions/3248). we changed dir mounts like below and issues was fixed
```yaml
...
          volumeMounts:
            - name: plugins        # EmtyDir
              mountPath: /plugins

            - name: scratch        # EmtyDir
              mountPath: /scratch

            - name: tmpdir         # EmtyDir
              mountPath: /tmp

            - name: shared-volume    # Ephemeral Volume
              mountPath: /nonexistent

            - name: udmrepo              # EmtyDir
              mountPath: /root/udmrepo

            - name: shared-volume  # Ephemeral Volume     
              mountPath: /root/.cache
 ...
```
