### ISSUE TITLE
Add E2E test of backups deletion

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#4348]
**Describe the problem/challenge you have**

**Describe the solution you'd like**
**Test Case Description:**
Deleted backups are deleted from object storage and backups deleted from object storage can be deleted locally
**Test Steps & Expected Result:**
1. 	Prepare workload as target to backup;
2. 	Install Velero;
3. 	Backup the workload and wait until it’s finished;
4. 	Verify that backup has been synced to object storage using cloud provider CLI;
5. 	Repeat step 2~3 a few rounds to create more backups;
6. 	Delete some of backups locally using velero CLI and make sure deleted backups are no longer existed and undeleted backups are existing locally;
7. 	Verify that deleted backups should be not existing in object storage in a short period of time and undeleted backups should be existing using cloud provider CLI;
8. 	Delete some of backups in object storage using cloud provider CLI;
9. 	Verify that deleted backups can be deleted locally.

Deploy test object for backup;
Create backup;
Uninstall Velero;
Install Velero;
Check if backup can be sync from BSL to local successfully.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by eleanor-millman** [comment]
@danfengliu do you expect this to make 1.8 or should I remove the milestone? Thanks!
