### ISSUE TITLE
Add defaultVolumesToRestic option to Schedule API Documentation

### ISSUE THREAD

**Issue by we10710aa** [vmware-tanzu/velero#4352]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
Currently, we can't set defaultVolumesToRestic in schedule api/ yaml template. In my case, I need to setup two schedules, one is to backup some namespaces with restic, and to backup other namespaces without restic.

I know I can use opt-in approach, but it's not ideal to add annotations to every pod in a namespace.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Add a defaultVolumesToRestic option to schedule api, when set to true, the velero will apply backup with restic.
Default value will be the global setting.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by zubron** [comment]
Hi @we10710aa - The Schedule object [contains a `BackupSpec`](https://github.com/vmware-tanzu/velero/blob/main/pkg/apis/velero/v1/schedule.go#L28-L30) to define the backup that should be run as part of the schedule. Part of this BackupSpec is the [`DefaultVolumesToRestic`](https://github.com/vmware-tanzu/velero/blob/main/pkg/apis/velero/v1/backup.go#L92-L96) option.

This is an issue with our documentation where we document this field in the Backup API definition but not the Schedule definition. Although it's not documented, you should still be able to use it within the YAML for your schedule. Please try that and let us know if it does not work. I will update the title of this issue to explain that it's an issue with the docs. Thanks!

**Comment by we10710aa** [comment]
> Hi @we10710aa - The Schedule object [contains a `BackupSpec`](https://github.com/vmware-tanzu/velero/blob/main/pkg/apis/velero/v1/schedule.go#L28-L30) to define the backup that should be run as part of the schedule. Part of this BackupSpec is the [`DefaultVolumesToRestic`](https://github.com/vmware-tanzu/velero/blob/main/pkg/apis/velero/v1/backup.go#L92-L96) option.
> 
> This is an issue with our documentation where we document this field in the Backup API definition but not the Schedule definition. Although it's not documented, you should still be able to use it within the YAML for your schedule. Please try that and let us know if it does not work. I will update the title of this issue to explain that it's an issue with the docs. Thanks!

I tried add this option and it worked as expected, thanks so much for the help!
