### ISSUE TITLE
Include all fields in marshalling of `SnapshotItemRequest` and `DeleteItemSnapshotRequest` in item_snapshotter_client.go

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/velero#4356]
This is a follow up from #4077.

We need to set the `Params` field in the `SnapshotItemRequest` object, and the `SnapshotMetadata` field in the `DeleteItemSnapshotRequest` in pkg/plugin/framework/item_snapshotter_client.go.

**Comment by eleanor-millman** [comment]
@zubron I am going through all the 1.8 milestone items as requested by @reasonerjt. I assume that this is part of the data mover work and so should stay under 1.8?

**Comment by zubron** [comment]
@eleanor-millman This is a small clean up task raised as part of #4077. It's part of the upload progress work so should stay in the 1.8 milestone.

**Comment by reasonerjt** [comment]
@dsu-igeek  please double check if this is already done.
