### ISSUE TITLE
Allow excluding all volumes of a pod from restic

### ISSUE THREAD

**Issue by timbuchwaldt** [vmware-tanzu/velero#4360]
**Describe the problem/challenge you have**
We have some pods like the prometheus instances created by the operator that have generated volume names, we would like to exclude those from restic backups.

**Describe the solution you'd like**
Add a new annotation to skip all volumes of a pod for a restic backup.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
I think if we are to introduce such annotation, it probably should skip all snapshot actions, not only restic.

**Comment by reasonerjt** [comment]
@timbuchwaldt 
So you mean the annotation `backup.velero.io/backup-volumes-excludes`?
How about we introduce support for `*` ?
So you can skip all the pvc like 
`kubectl -n sample annotate pod/app1 backup.velero.io/backup-volumes-excludes=*`

**Comment by timbuchwaldt** [comment]
Hey! This would be perfect, yes!
