### ISSUE TITLE
Document AWS, Azure, and GCP plugin changes related to CSI

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/velero#4362]
Documentation for the 1.8 release for the following changes:

https://github.com/vmware-tanzu/velero/issues/4108
https://github.com/vmware-tanzu/velero/issues/4109
https://github.com/vmware-tanzu/velero/issues/4110

Please put docs on this change in the AWS, Azure, and GCP plugin repos.

Please make a PR and tag @a-mccarthy as a reviewer. Thanks!

**Comment by reasonerjt** [comment]
The new versions of plugins for AWS, Azure and GCP will be released with the support of snapshotting and restoring the persistent volumes provisioned by CSI driver via the APIs of the cloud providers.  With this enhancement, users can backup and restore the persistent volumes on these could providers without using the CSI plugin, which will remain beta and the feature flag `EnableCSI` will be disabled by default.

For the version of the plugins and the CSI drivers they support respectively please see the table:
| Plugin | Version | CSI Driver |
| --- | ----------- | ---------- |
| velero-plugin-for-aws | v1.4.0 | ebs.csi.aws.com |
| velero-plugin-for-microsoft-azure | v1.4.0 | disk.csi.azure.com |
| velero-plugin-for-gcp | v1.4.0 | pd.csi.storage.gke.io |

**Comment by reasonerjt** [comment]
@a-mccarthy 
Please see the comment above, I don't find a page on the documentation regarding the plugin of cloud providers.

You may want to add this section in the page to describe the overall support status of CSI in velero.

**Comment by a-mccarthy** [comment]
@reasonerjt is there any change in functionality a user would need to do to make this work? or would they do things as they normally would, only now Velero works through the cloud providers APIs to do the snapshot/restore when you run the `velero` command for a CSI provisioned persistent volume?

**Comment by a-mccarthy** [comment]
@reasonerjt I updated the docs with more information for the CSI updates in #4502, https://velero.io/docs/main/csi/. Please reopen this issue if you feel like there is more to add to the docs. thanks!
