### ISSUE TITLE
Confirm that docs reflect correct behavior for "schedule creation through API triggers backup regardless of cron settings"

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/velero#4366]
Please confirm that the docs reflect the correct behaviour for this 1.8 fix: https://github.com/vmware-tanzu/velero/issues/1980

If not or if the docs don't mention this at all, please create a PR for the needed changes and tag @a-mccarthy as a reviewer. Thanks!

**Comment by a-mccarthy** [comment]
@eleanor-millman the docs currently say that a backup will not be taken immediately after creating a scheduled backup, https://velero.io/docs/v1.7/backup-reference/#schedule-a-backup.

**Comment by ywk253100** [comment]
Just like what @a-mccarthy said, the doc already reflects the correct behavior for the fix, I'm closing this issue @eleanor-millman
