### ISSUE TITLE
Documentation for pre and post hooks

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/velero#4367]
Documentation for any user-facing changes introduced by this feature: https://github.com/vmware-tanzu/velero/issues/4067

Please create a PR and tag @a-mccarthy as a reviewer. Thanks!

(Frankie, assigning this to you since I couldn't assign it to @brito-rafa)

Note that we should also mention that this could be used to schedule restores, as one user requested (see this slack chat: https://kubernetes.slack.com/archives/C6VCGP4MT/p1643127620079600)

**Comment by a-mccarthy** [comment]
The parent issue for this has been moved to 1.9. I'll also move this work out of 1.8. @eleanor-millman or @codegold79 please let me know if there is any docs to update for 1.8 :)

**Comment by eleanor-millman** [comment]
As far as I know, that is the right move. Thanks @a-mccarthy !

**Comment by eleanor-millman** [comment]
Closing until/if we do this feature.
