### ISSUE TITLE
application crash caused by permission denied after restore from restic

### ISSUE THREAD

**Issue by jerry-jibu** [vmware-tanzu/velero#4388]
**What steps did you take and what happened:**

background: 
some application in pod, such as database, may do `chown` to mounted PVC to non-root user at first time that filesystem is empty and then start app by the user.

problem:
The pvc backup through restic doesn't preserve the filesystem attributions (uid/gid) on mounted point. This cause the application crashes after restore because  container entry script doesn't call `chown` when mounted filesystem already has data. 

But if PVC is backed up by snapshot, then we don't hit this issue as uid/gid is preserved in PVC.
The difference is that restore from restic creates a new empty PVC and copy data back before application's logic but snapshot is restored from original data. 

**What did you expect to happen:**

Application can start up normally after restic restore

**The following information will help us better understand what's going on**:

velero v1.7.0

Here is an example:

```
$ kubectl apply -f permission.yaml
namespace/permission created
pod/busybox1 created
persistentvolumeclaim/volclaim created
$ kubectl -n permission get pod
NAME       READY   STATUS    RESTARTS   AGE
busybox1   1/1     Running   0          6s

$ kubectl -n permission exec busybox1 -- chown nobody:nobody /nobodysdir   # some initializing code changed owner of pvc root
$ kubectl -n permission exec busybox1 -- ls -ld /nobodysdir
drwxrwxrwx    2 nobody   nobody           6 Nov 18 08:50 /nobodysdir.                 <<<<<<  nobody:nobody is set before backup

$ velero backup create nobody --include-namespaces permission --storage-location minio-bznrv --volume-snapshot-locations minio-ee939e1d-2ad9-41a3-a509-c76b348612c9 --
default-volumes-to-restic
Backup request "nobody" submitted successfully.
Run `velero backup describe nobody` or `velero backup logs nobody` for more details.

kubectl delete permission

$ velero restore create --from-backup nobody
Restore request "nobody-20211118165437" submitted successfully.
Run `velero restore describe nobody-20211118165437` or `velero restore logs nobody-20211118165437` for more details.
$ velero restore get
NAME                    BACKUP   STATUS      STARTED                         COMPLETED                       ERRORS   WARNINGS   CREATED                         SELECTOR
nobody-20211118165437   nobody   Completed   2021-11-18 16:54:37 +0800 CST   2021-11-18 16:54:37 +0800 CST   0        0          2021-11-18 16:54:37 +0800 CST   <none>


$ kubectl -n permission exec busybox1 -- ls -ld /nobodysdir
drwxrwxrwx    2 root     root             6 Nov 18 08:54 /nobodysdir           <<<<< mount point is changed to root:root after restore


permission.yaml:

apiVersion: v1
kind: Namespace
metadata:
  name: permission
---
apiVersion: v1
kind: Pod
metadata:
  namespace: permission
  name: busybox1
  labels:
    app: busybox1
spec:
  containers:
  - image: busybox
    command:
      - tail
      - -f
      - /dev/null
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: vol
      mountPath: /nobodysdir
  restartPolicy: Always
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: volclaim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: permission
  name: volclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
```

**Anything else you would like to add:**

Per my understanding, we could preserve this mount point uid/gi in podvolumebackup and recover it when doing podvolumerestore execution to set correct uid/gid for mount point. 

**Environment:**

- Velero version (use `velero version`):  v1.7.0
- Velero features (use `velero client config get features`):  enable restic + CSI
- Kubernetes version (use `kubectl version`):  v1.18
- Kubernetes installer & version:   v1.19
- Cloud provider or hardware configuration:    X86 VM
- OS (e.g. from `/etc/os-release`):   Centos 7.8

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Thanks for using Velero and report issue.
To my understanding, this is caused by restic not restore file with UID and GID setting. 
I saw restic repo has some similar issues, for example [Also support restoring ownership by name](https://github.com/restic/restic/issues/3572).

If application needs to do something before restore procedure, I think restore pre-hook may be useful.
Please check whether this document can do some help: [velero restore hook](https://velero.io/docs/v1.7/restore-hooks/)

**Comment by jerry-jibu** [comment]
@blackpiglet  Thanks for the help. 

The restic issue you pointed out seems to be different to this one which addresses the concern on mapping between uid/gid and user/group name.
"It would be great, if restic restore would support an option for restoring ownership information from the symbolic user/group names instead of just restoring the uid/gid."


In this case, restic works as expected to save all correct uid/gid records **under** the mount point but NOT the mount point itself which is the root cause.

For example, given a nfs PVC, it mounts the PVC on worknode as `/var/lib/kubelet/pods/d6e238c3-fc4d-4cf9-891b-b204500565ea/volumes/kubernetes.io~nfs/pvc-4c3b9a28-7fc8-4148-99ab-6951a9f5ed8f/`,
the contents under this directory are backed up/restored well.
```
[root@gyj-dev pvc-4c3b9a28-7fc8-4148-99ab-6951a9f5ed8f]# pwd
/var/lib/kubelet/pods/d6e238c3-fc4d-4cf9-891b-b204500565ea/volumes/kubernetes.io~nfs/pvc-4c3b9a28-7fc8-4148-99ab-6951a9f5ed8f
[root@gyj-dev pvc-4c3b9a28-7fc8-4148-99ab-6951a9f5ed8f]# ls -n
...
-rw------- 1 999 999     1679 11月 19 09:03 ca-key.pem     <<<<< no problem
-rw-r--r-- 1 999 999     1115 11月 19 09:03 ca.pem


[root@gyj-dev pvc-4c3b9a28-7fc8-4148-99ab-6951a9f5ed8f]# ls -rlt /var/lib/kubelet/pods/d6e238c3-fc4d-4cf9-891b-b204500565ea/volumes/kubernetes.io~nfs/

drwxrwxrwx 8 root root 4096 11月 19 09:15 pvc-4c3b9a28-7fc8-4148-99ab-6951a9f5ed8f     <<<< this should be restored to 999 as application chown it before backup.
```

Here are related code based on v1.7.  Per my understanding, restic is only responsible for the files or subdirectories under the mount point but not check/preserve the mount point itself.

```go
// pkg/controller/pod_volume_restore_controller.go

func (c *podVolumeRestoreController) restorePodVolume(req *velerov1api.PodVolumeRestore, volumeDir string, log logrus.FieldLogger) error {
	// Get the full path of the new volume's directory as mounted in the daemonset pod, which
	// will look like: /host_pods/<new-pod-uid>/volumes/<volume-plugin-name>/<volume-dir>
	volumePath, err := singlePathMatch(fmt.Sprintf("/host_pods/%s/volumes/*/%s", string(req.Spec.Pod.UID), volumeDir))
        ...
        resticCmd := restic.RestoreCommand(
		req.Spec.RepoIdentifier,
		credsFile,
		req.Spec.SnapshotID,
		volumePath,
	)

```

**Comment by blackpiglet** [comment]
@jerry-jibu 
Thanks for clarification, by far, Velero doesn't support the UID and GID preservation in Restic yet. 
After discussion, we think using a restore post-hook could be a solution for your case.
Post hook will be ran after restore process. In your case, it will a "chown" shell command to set UID and GID accordingly. 

[velero restore hook](https://velero.io/docs/v1.7/restore-hooks/)
