### ISSUE TITLE
remove --crds-version from "velero install" command

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#4389]
**Describe the problem/challenge you have**
#4382 complete velero migration from kubebuilder v2 to v3. After that, only apiextensions.k8s.io/v1 is supported, so there is no need to keep the --crds-version parameter to choose CRD version.

**Describe the solution you'd like**
Open this issue to trace removing the --crds-version parameter task.

**Anything else you would like to add:**
None

**Environment:**

- Velero version (use `velero version`): v1.8
- Kubernetes version (use `kubectl version`): 1.21
- Kubernetes installer & version: kind
- Cloud provider or hardware configuration: none
- OS (e.g. from `/etc/os-release`): MacOS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
Please double check if this param is referenced in the doc and make sure it is removed also.

**Comment by blackpiglet** [comment]
> Please double check if this param is referenced in the doc and make sure it is removed also.

Got it. Checked the document. There is no recording of this parameter in documents.
Close this issue.
