### ISSUE TITLE
Provide API support for getting Velero server configuration status and errors

### ISSUE THREAD

**Issue by JNLiu5** [vmware-tanzu/velero#4405]
When the Velero server is configured with a backup location and authentication details, it attempts to connect to the given backup location and internally logs errors if it fails. For an administrator to determine that Velero is failing to connect, they would have to parse through the logs and find the error themselves.

Velero should support an API to get the details, status, and errors of Velero's current connection to its configured backup location.

It would also be great if this API will be capable of integration with vSphere UI or Tanzu Mission Control.

**Comment by qiuming-best** [comment]
@JNLiu5 currently, we have the cmd `velero backup-location get`, which can check the backup location phase, but it can not get the details when something is wrong with the backup location.

**Comment by eleanor-millman** [comment]
Thanks! We will take a look at this when we do our 1.9 planning in January.

**Comment by a-mccarthy** [comment]
@ywk253100 following up here, do the changes you made here add any fields that should be added to the docs, https://velero.io/docs/v1.8/api-types/backupstoragelocation/? thanks!

**Comment by ywk253100** [comment]
> @ywk253100 following up here, do the changes you made here add any fields that should be added to the docs, https://velero.io/docs/v1.8/api-types/backupstoragelocation/? thanks!

@a-mccarthy The new field `message` is added to the `status` part of BSL CR while the `status` part isn't covered in the doc, so I think I don't need to add it in the doc?
