### ISSUE TITLE
Velero v1.7.0 restic encryption not working

### ISSUE THREAD

**Issue by nunojusto** [vmware-tanzu/velero#4406]
**What steps did you take and what happened:**
Installed v1.7.0 and using s3 bucket destination with default restic password.
I've also tried the workaround and created a different restic kube secret (velero-restic-credentials) and then installed Velero after it, to set a different non-default restic password.

**What did you expect to happen:**
I expected to see all backups encrypted in the s3 bucket. Even if they are with default restic password.
In both cases of my installation all backups are not encrypted. I can browse the s3 bucket with a different tool (s3cmd) and see all files unencrypted.

**The following information will help us better understand what's going on**:

```
Name:         testd-back-1
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.20.6+vmware.1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=20

Phase:  Completed

Errors:    0
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-11-29 10:12:25 +0100 CET
Completed:  2021-11-29 10:12:34 +0100 CET

Expiration:  2021-12-29 10:12:25 +0100 CET

Total items to be backed up:  481
Items backed up:              481

```

**Environment:**
Velero version
```
Client:
        Version: v1.7.0
        Git commit: 9e52260568430ecb77ac38a677ce74267a8c2176
Server:
        Version: v1.7.0
```
Kube versions
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:50:34Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6+vmware.1", GitCommit:"088f01db2ffab397a290be443902918b59ee032c", GitTreeState:"clean", BuildDate:"2021-04-17T01:01:00Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
@nunojusto 
Hi, it seems Velero not support encrypted the files in bucket. Please check with the limitations of Restic in velero document.

[Restic Integration Limitation](https://velero.io/docs/v1.7/restic/#limitations)

**Comment by nunojusto** [comment]
@blackpiglet In my opinion that's not what documentation says.
For me it says the Limitation is on the use of restic password, because it uses only the static default restic password and anyone can decrypt with that pass.
What i'm pointing out as a bug is that even that is not working.

**Comment by blackpiglet** [comment]
Got it. I am new to Velero project, so not sure about the history of how Restic behavior changes. 
I will do a test to find out why.

**Comment by blackpiglet** [comment]
@nunojusto 
Hi, I tested on a local cluster and tried to list the files in OSS. MinIO is used as the object storage provider.

These are commands and output of MinIO client after I did some backup testing on the cluster.
I think the files related to Restic is encrypted under directory velero/restic. Files are plain which should be the backup metadata files under directory velero/backups.

>
# mc ls velero_minio/velero
[2021-12-01 14:28:40 CST]     0B backups/
[2021-12-01 14:28:40 CST]     0B restic/

# mc ls velero_minio/velero/backups/
[2021-12-01 14:29:25 CST]     0B empty/
[2021-12-01 14:29:25 CST]     0B empty1/
[2021-12-01 14:29:25 CST]     0B empty2/
[2021-12-01 14:29:25 CST]     0B testing/

# mc ls velero_minio/velero/backups/testing/
[2021-11-29 20:19:39 CST]    29B testing-csi-volumesnapshotcontents.json.gz
[2021-11-29 20:19:39 CST]    29B testing-csi-volumesnapshots.json.gz
[2021-11-29 20:19:38 CST] 7.5KiB testing-logs.gz
[2021-11-29 20:19:39 CST]    29B testing-podvolumebackups.json.gz
[2021-11-29 20:19:39 CST]   785B testing-resource-list.json.gz
[2021-11-29 20:19:39 CST]    29B testing-volumesnapshots.json.gz
[2021-11-29 20:19:39 CST]  29KiB testing.tar.gz
[2021-11-29 20:19:39 CST] 2.1KiB velero-backup.json

# mc ls velero_minio/velero/restic/
[2021-12-01 14:29:52 CST]     0B default/
[2021-12-01 14:29:52 CST]     0B velero/

# mc ls velero_minio/velero/restic/default/
[2021-11-29 23:34:45 CST]   155B config
[2021-12-01 14:29:58 CST]     0B data/
[2021-12-01 14:29:58 CST]     0B index/
[2021-12-01 14:29:58 CST]     0B keys/
[2021-12-01 14:29:58 CST]     0B snapshots/

# mc ls velero_minio/velero/restic/default/data
[2021-12-01 14:30:02 CST]     0B 00/
[2021-12-01 14:30:02 CST]     0B e6/
[2021-12-01 14:30:02 CST]     0B f8/

# mc ls velero_minio/velero/restic/default/data/00
[2021-11-29 23:34:46 CST]   775B 00bc28326a8b7ddc7679e0eef877c3faaf6feb7ba4a9e2896f9f6ede25714809

**Comment by nunojusto** [comment]
Thank you for your reply and tests.
I'll do another clean install and test it from my side, cause I still have different results.
I'll keep you updated

**Comment by nunojusto** [comment]
New clean install and I also see encryption:
```
$ s3cmd ls s3://velero/restic/velero/data/0c/
2021-12-06 11:31      3377   s3://velero/restic/velero/data/0c/0c621b12d9efb2aeda3e7a1d63cac961f23539fddab46559ec95a54b005cc43c
```
I still don't know what happened before. I'm closing the issue now.
