### ISSUE TITLE
backup statefulset failed with velero 1.6.3 +velero-plugin-for-vsphere:v1.3.0-rc4

### ISSUE THREAD

**Issue by wanghuok** [vmware-tanzu/velero#4411]
**Describe the bug**

backup fails

**To Reproduce**

1. setup tkgi 1.13
2. create a k8s cluster
3. install velero and velero-plugin-for-vsphere:v1.3.0-rc4
4. create 10 namespaces, 100 statefulsets with 1g pv each
5. backup 10 namespaces, 2 namespaces each time
6. the first four backupswere successful. but the last one is PartiallyFailed

**Expected behavior**

[A clear and concise description of what you expected to happen]

backup 10 namespaces successfully

[Please refer to the [Troubleshooting](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/main/docs/troubleshooting.md) page and collect the required information]
`time="2021-11-24T08:54:04Z" level=info msg="running exec hook" backup=velero/a-bk-5 hookCommand="[/sbin/fsfreeze --freeze /var/lib/postgresql/data]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=pre hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:124" name=postgres-wl-10-0 namespace=velero-1g-10 resource=pods
time="2021-11-24T08:54:04Z" level=info msg="stdout: " backup=velero/a-bk-5 hookCommand="[/sbin/fsfreeze --freeze /var/lib/postgresql/data]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=pre hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:171" name=postgres-wl-10-0 namespace=velero-1g-10 resource=pods
time="2021-11-24T08:54:04Z" level=info msg="stderr: " backup=velero/a-bk-5 hookCommand="[/sbin/fsfreeze --freeze /var/lib/postgresql/data]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=pre hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:172" name=postgres-wl-10-0 namespace=velero-1g-10 resource=pods`

`time="2021-11-24T08:57:59Z" level=error msg="Error executing hook" backup=velero/a-bk-5 error="error dialing backend: dial tcp 10.21.5.71:10250: connect: no route to host" hookPhase=pre hookSource=annotation hookType=exec logSource="internal/hook/item_hook_handler.go:206" name=postgres-wl-99-0 namespace=velero-1g-9 resource=pods
time="2021-11-24T08:57:59Z" level=error msg="Error backing up item" backup=velero/a-bk-5 error="error dialing backend: dial tcp 10.21.5.71:10250: connect: no route to host" logSource="pkg/backup/backup.go:437" name=postgres-wl-99-0`

10.21.5.71 is a worker node in the cluster, i have checked that node works fine, and i can ping it too.

[Miscellaneous information that will assist in solving the issu
[abk5.log](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/files/7624575/abk5.log)
[backup-driver-pod.log](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/files/7624656/backup-driver-pod.log)
[velero-pod.log](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/files/7624659/velero-pod.log)
e]

**Comment by ywk253100** [comment]
The `10250` should be the port that kubelet listens on.
According to the log `error dialing backend: dial tcp 10.21.5.71:10250: connect: no route to host`, seems that the worker node can not be accessed from the velero pod.

@wanghuok Could you double-check the network configuration for that?

**Comment by wanghuok** [comment]
Hello, @ywk253100  the env has gone some days ago.  i think the network configuration is ok. because the first 4 backups are successfully, only the last one failed with this error. if the network configuration is not correct, this issue will occurred during the first backup.

**Comment by liyan-su** [comment]
Hi, 
Any update for this issue?

**Comment by dsu-igeek** [comment]
If four backups succeeded and then you get a networking failure this is most likely a networking failure.  If the environment is gone and cannot be checked there's no way to investigate further.

**Comment by liyan-su** [comment]
Hi @dsu-igeek ,
We reproduced this issue in three different environments, we backup 10 ns, step is 2, sometimes backup 5 times were successful.

We also suspected that it might be related to the hooks of fsfreeze, and did a test by removing the hooks, 5 were successful, but we cann't confirm that the hooks are the key issue, however velero documentation supports the hooks of fsfreeze: https://velero.io/docs/v1.7/backup-hooks/
