### ISSUE TITLE
Setting a ttl value to 0 resets the velero backup expiry time to default value.

### ISSUE THREAD

**Issue by kumars17** [vmware-tanzu/velero#4413]
Not sure how to disable TTL, So that auto expiration of backup is disabled and we are allowed to delete backups only manually.

**Comment by ywk253100** [comment]
I don't think velero supports disable TTL at this moment

**Comment by ErikXu** [comment]
Maybe you can set a large duration like 999...h？

**Comment by kumars17** [comment]
Thanks.. will try setting it to a very high value
