### ISSUE TITLE
the backup silently gets stuck if restic has not risen on the node

### ISSUE THREAD

**Issue by ishbuldin** [vmware-tanzu/velero#4422]
**What steps did you take and what happened:**
If restic crashes on the node for one reason or another, then the backups hang in the `NEW` status and do nothing and do not report the problem anywhere, neither in the velero deployment logs, nor in the describe backup

**What did you expect to happen:**
Change backup status to `error` or `wait restic`
Write logs about this event inside the velero pod

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.7.0
	Git commit: 9e52260568430ecb77ac38a677ce74267a8c2176
Server:
	Version: v1.7.0
```
- Velero features (use `velero client config get features`): 
```
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:58:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:51:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```
- OS (e.g. from `/etc/os-release`):
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
When doing volume backup with Restic, Velero creates `podvolumebackup` CRs to the API server and the Restic daemonset takes them from API server and handle. If the restic crashes, the CRs will not be handled by anyone.
So I think the backups hanging in the `NEW` status is the expected behavior.
