### ISSUE TITLE
[Upload Progress Monitoring epic #3533] ItemSnapshotter should ignore PVCs when backup.Spec.SnapshotVolumes is not set

### ISSUE THREAD

**Issue by dsu-igeek** [vmware-tanzu/velero#4425]
**Describe the problem/challenge you have**
Currently, volume snapshots will not be taken unless backup.Spec.SnapshotVolumes is set.  ItemSnapshotter is now being called for any objects that match an ItemSnapshotter and will ignore the flag.

**Describe the solution you'd like**
Velero code needs to skip calling ItemSnapshotters for PVCs if backup.Spec.SnapshotVolumes is not set.

Part of epic #3533 
**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
not a stale
