### ISSUE TITLE
Velero keeps reporting partial failure

### ISSUE THREAD

**Issue by fabricesemti80** [vmware-tanzu/velero#4441]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

- Daily backups keep reporting partial failure.

**What did you expect to happen:**

- Daily backups do not report failure.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 
[bundle-2021-12-10-13-20-59.tar.gz](https://github.com/vmware-tanzu/velero/files/7692988/bundle-2021-12-10-13-20-59.tar.gz)

_If you are using earlier versions:_  

Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

```sh
time="2021-12-10T06:00:43Z" level=info msg="Processing item" backup=velero/velero-daily-backup-20211210060038 logSource="pkg/backup/backup.go:358" name=bazarr-6cd94d897c-2b8r2 namespace=media progress= resource=pods
time="2021-12-10T06:00:43Z" level=info msg="Backing up item" backup=velero/velero-daily-backup-20211210060038 logSource="pkg/backup/item_backupper.go:121" name=bazarr-6cd94d897c-2b8r2 namespace=media resource=pods
time="2021-12-10T06:00:43Z" level=info msg="running exec hook" backup=velero/velero-daily-backup-20211210060038 hookCommand="[/sbin/fsfreeze --freeze /config]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=pre hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:124" name=bazarr-6cd94d897c-2b8r2 namespace=media resource=pods
time="2021-12-10T06:00:43Z" level=info msg="stdout: " backup=velero/velero-daily-backup-20211210060038 hookCommand="[/sbin/fsfreeze --freeze /config]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=pre hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:171" name=bazarr-6cd94d897c-2b8r2 namespace=media resource=pods
time="2021-12-10T06:00:43Z" level=info msg="stderr: fsfreeze: /config: freeze failed: Not supported\n" backup=velero/velero-daily-backup-20211210060038 hookCommand="[/sbin/fsfreeze --freeze /config]" hookContainer=fsfreeze hookName="<from-annotation>" hookOnError=Fail hookPhase=pre hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:172" name=bazarr-6cd94d897c-2b8r2 namespace=media resource=pods
time="2021-12-10T06:00:43Z" level=error msg="Error executing hook" backup=velero/velero-daily-backup-20211210060038 error="command terminated with exit code 1" hookPhase=pre hookSource=annotation hookType=exec logSource="internal/hook/item_hook_handler.go:206" name=bazarr-6cd94d897c-2b8r2 namespace=media resource=pods
time="2021-12-10T06:00:43Z" level=error msg="Error backing up item" backup=velero/velero-daily-backup-20211210060038 error="command terminated with exit code 1" logSource="pkg/backup/backup.go:441" name=bazarr-6cd94d897c-2b8r2
time="2021-12-10T06:00:43Z" level=info msg="Backed up 31 items out of an estimated total of 1269 (estimate will change throughout the backup)" backup=velero/velero-daily-backup-20211210060038 logSource="pkg/backup/backup.go:398" name=bazarr-6cd94d897c-2b8r2 namespace=media progress= resource=pods

```

**Environment:**

- Velero version (use `velero version`): 
fabrice@DESKTOP-FS:~/k8s-cluster-mk4$ velero version
Client:
        Version: v1.7.1
        Git commit: -
Server:
        Version: v1.7.0

- Velero features (use `velero client config get features`): 
fabrice@DESKTOP-FS:~/k8s-cluster-mk4$ velero client config get features
features: <NOT SET>
- Kubernetes version (use `kubectl version`):
fabrice@DESKTOP-FS:~/k8s-cluster-mk4$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:41:42Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4+k3s1", GitCommit:"bec170bc813e342cdba9710a1a71f8644c948770", GitTreeState:"clean", BuildDate:"2021-11-29T17:11:06Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
NAME    STATUS   ROLES                       AGE     VERSION
k8s-0   Ready    control-plane,etcd,master   6d14h   v1.22.4+k3s1
k8s-1   Ready    <none>                      6d14h   v1.22.4+k3s1
k8s-2   Ready    <none>                      6d14h   v1.22.4+k3s1
k8s-3   Ready    <none>                      6d14h   v1.22.4+k3s1
fabrice@DESKTOP-FS:~/k8s-cluster-mk4$ 
- Cloud provider or hardware configuration:
Local hardware
- OS (e.g. from `/etc/os-release`):
Ubuntu 18.04 (management, WSL), Ubuntu 20.04 (kubernetes nodes)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by codegold79** [comment]
> stderr: fsfreeze: /config: freeze failed: Not supported\n

Looks like from your logs that a hook command is failing.

What is it you're expecting the freeze hook to do? Can you verify if you run the freeze hook command in the container that it works?

Some more information on hooks:

https://velero.io/docs/v1.7/backup-hooks/#specifying-hooks-as-pod-annotations

**Comment by fabricesemti80** [comment]
Thanks. Will look into this. It looks like the freeze fails within the pod too

```sh
kah@bazarr-6cd94d897c-2b8r2:/app$ /sbin/fsfreeze --freeze /config
fsfreeze: /config: freeze failed: Operation not permitted
```

Is it possible this is failing because the /config is a made with nfs storageClass....? (I red somwhere fsfreeze does not support nfs mounts...)

**Comment by reasonerjt** [comment]
@fabricesemti80 

yes that maybe the reason for the `Not supported` error in the log.

**Comment by codegold79** [comment]
I need to learn more about storage, as I know nothing about things like NFS mounts (or any other storage devices). But, I am learning about it because this is such an important problem that people have: how to quiesce stateful apps before they are backed up/migrated.

I found this in the [fsfreeze man pages](https://linux.die.net/man/8/fsfreeze):

> fsfreeze - suspend access to an filesystem (Linux Ext3/4, ReiserFS, JFS, XFS). 

I would guess that if NFS is not one of those listed, it would give an error.

Did your search lead you to this popular page: https://stackoverflow.com/questions/67553328/how-do-i-freeze-an-nfs-mount-in-kubernetes-to-snapshot-it-if-fsfreeze-sends-op?

**Comment by fabricesemti80** [comment]
Right... so what course of action is recommended? (I had similar errors when I used rook-ceph for storage too, I took 5hat out from my cluster though, as I do not need distributed storage, having it on one nas/nfs is fine)
- not using fsfreeze (risk inconsistent backups)
- not using nfs (would say this is a no-go due to no better alternative)
- not using Velero
-???

**Comment by reasonerjt** [comment]
@fabricesemti80 

I think you need to find a way to quiesce your app, and trigger that in the hook.
