### ISSUE TITLE
Error while backing up and restoring a sample WordPress installation on AKS

### ISSUE THREAD

**Issue by ishangupta-ds** [vmware-tanzu/velero#4458]
**What steps did you take and what happened:**

* Deployed WordPress on AKS following [https://dzone.com/articles/setup-velero-on-aks](https://dzone.com/articles/setup-velero-on-aks)

* Installed velero via helm

* Created a backup using CLI

* Deleted the WordPress namespace

* Created a restore using CLI

**What did you expect to happen:**

Expected the restore to be completed, app. k8s resources to be restored and application to be running.

**The following information will help us better understand what's going on**:

velero v1.7.0+ support bundle: [google drive upload](https://drive.google.com/file/d/1SFuPh_X6x4CBPIR2uQsQiinFiGgYSGUX/view?usp=sharing)

**Anything else you would like to add:**

1.
```
`name=my-app-wordpress-5bff9c96dd-lz7vc`
 time="2021-12-15T06:49:29Z" level=info msg="1 errors encountered backup up item" backup=velero/wp-backup logSource="pkg/backup/backup.go:412" name=my-app-wordpress-5bff9c96dd-lz7vc
 time="2021-12-15T06:49:29Z" level=error msg="Error backing up item" backup=velero/wp-backup error="error getting volume info: rpc error: code = Unknown desc = compute.DisksClient#Get: Failure responding to request: StatusCode=404 – Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/disks/kubernetes-dynamic-pvc-7bdd9b56-36bf-4e0b-8492-131fdfe3397b' under resource group 'dp-backup-rg' was not found. For more details please go to 
 https://aka.ms/ARMResourceNotFoundFix
 \"" logSource="pkg/backup/backup.go:416" name=my-app-wordpress-5bff9c96dd-lz7vc
```

2.
```
`name=my-app-mariadb-0`
 time="2021-12-15T06:49:29Z" level=info msg="1 errors encountered backup up item" backup=velero/wp-backup logSource="pkg/backup/backup.go:412" name=my-app-mariadb-0
 time="2021-12-15T06:49:29Z" level=error msg="Error backing up item" backup=velero/wp-backup error="error getting volume info: rpc error: code = Unknown desc = compute.DisksClient#Get: Failure responding to request: StatusCode=404 – Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/disks/kubernetes-dynamic-pvc-e6c76450-6d0b-4631-971b-f14ae64221de' under resource group 'dp-backup-rg' was not found. For more details please go to 
 https://aka.ms/ARMResourceNotFoundFix
 \"" logSource="pkg/backup/backup.go:416" name=my-app-mariadb-0
```

Backups phased `PartiallyFailed` as PVs could not be backed up although restore showed status as `Completed`. Post backup only one of the PVs was restored. Also, the number of items restored and to be restored matched. Due to the error, the pod waiting for the PVC went into `Pending` state as both PVC and PV were missing for one of the stateful apps `wp/my-app-WordPress. Errors logged during backup for both PVs (Microsoft.Compute/disks/kubernetes-dynamic-pvc...) but one got restored successfully.

```
❯ kubectl get pv
 NAME CAPACITY ACCESS MODES RECLAIM POLICY STATUS CLAIM STORAGECLASS REASON AGE
 pvc-7bdd9b56-36bf-4e0b-8492-131fdfe3397b 10Gi RWO Delete Bound wp/my-app-wordpress default 20m
 pvc-e6c76450-6d0b-4631-971b-f14ae64221de 8Gi RWO Delete Bound wp/data-my-app-mariadb-0 default 20m
```
 
Post backup:
```
❯ velero get restore
 NAME BACKUP STATUS STARTED COMPLETED ERRORS WARNINGS CREATED SELECTOR
 wp-backup-20211215124759 wp-backup Completed 2021-12-15 12:48:02 +0530 IST 2021-12-15 12:48:04 +0530 IST 0 0 2021-12-15 12:48:01 +0530 IST <none>
```
```
 ❯ kubectl get pvc -n wp
 NAME STATUS VOLUME CAPACITY ACCESS MODES STORAGECLASS AGE
 data-my-app-mariadb-0 Bound pvc-ef4d8866-2ab3-4b74-a559-70c0cc3d9f9a 8Gi RWO default 70s
```
```
 ❯ kubectl get pv
 NAME CAPACITY ACCESS MODES RECLAIM POLICY STATUS CLAIM STORAGECLASS REASON AGE
 pvc-ef4d8866-2ab3-4b74-a559-70c0cc3d9f9a 8Gi RWO Delete Bound wp/data-my-app-mariadb-0 default 79s
```
```
 ❯ kubectl get pods -n wp
 NAME READY STATUS RESTARTS AGE
 my-app-mariadb-0 1/1 Running 0 91s
 my-app-wordpress-5bff9c96dd-5qtbn 0/1 Pending 0 91s
```

**Environment:**

- Velero version (use `velero version`):  
```
Client:
	Version: v1.7.1
	Git commit: -
Server:
	Version: main
```
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"a5e4de7e277a707bd28d448bd75de58b4f1cdc22", GitTreeState:"clean", BuildDate:"2021-11-16T01:09:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
```
installer (managed): AKS (Azure)
version: 1.20.9
```
- Cloud provider or hardware configuration: Microsoft Azure / Node size: Standard_DS2_v2 / 1 node pool (2 nodes)
- OS (e.g. from `/etc/os-release`): `AKSUbuntu-1804gen2containerd-2021.11.06`

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Thanks for using Velero and report issue.

I think several thing needs to be consider to debug:
* Why use main release as Velero server? I think it's better to choose a stable release instead. Main is still under change during develop sprints.
* What is the version of velero azure plugin used? This can be found in Velero deploy's init container image version. 
* Could you please provide the command line and helm value file to  install velero helm chart? I think this may related to Velero fails to talk to Azure API, so we need more information about how Velero is installed, especially about the Azure related configuration.

**Comment by ishangupta-ds** [comment]
> Thanks for using Velero and report issue.
> 
> I think several things need to be considered to debug:
> 
> * Why use main release as Velero server? I think it's better to choose a stable release instead. Main is still under change during develop sprints.
> * What is the version of velero azure plugin used? This can be found in Velero deploy's init container image version.
> * Could you please provide the command line and helm value file used to install velero by helm chart? I think this issue may be related to Velero fail to talk to Azure API, so we need more information about how Velero is installed, especially about the Azure related configuration.


* we were testing the fixes for the following issues so we used the main branch code (build) :
- issue #2308 
- issue #3516 

* image tag for velero azure plugin: `main`


* helm install command:

```
helm install velero vmware-tanzu/velero \
--namespace velero \
--create-namespace \
--set-file credentials.secretContents.cloud=./credentials-velero \
--set configuration.provider=azure \
--set configuration.backupStorageLocation.name=azure \
--set configuration.backupStorageLocation.bucket='azure-blob' \
--set configuration.backupStorageLocation.config.resourceGroup=dp-backup-rg \
--set configuration.backupStorageLocation.config.storageAccount=velerobb0868d986f7 \
--set snapshotsEnabled=true \
--set deployRestic=true \
--set configuration.volumeSnapshotLocation.name=azure \
--set image.repository=velero/velero \
--set image.pullPolicy=Always \
--set initContainers[0].volumeMounts[0].mountPath=/target \
--set initContainers[0].volumeMounts[0].name=plugins
```

after this, we manually set the image by using kubectl as suggested in the [docs](https://velero.io/docs/v1.7/upgrade-to-1.7/)
 the only difference is, we changed the image tag to `main` rather than a specific version. The velero CLI remained at v1.7

The image tag was updated both for velero and the azure plugin.

**Comment by ywk253100** [comment]
AKS creates a new resource group to hold the resources created inside the cluster, it's name is like `MC_yinw-cluster-03_group_1636082172194_yinw-cluster-03_eastus2`. And the `ResourceGroup` in the `--set-file credentials.secretContents.cloud=./credentials-velero` should be this one `MC_xxx`.

Please find your resource group name and try again.

**Comment by ishangupta-ds** [comment]
> AKS creates a new resource group to hold the resources created inside the cluster, it's name is like `MC_yinw-cluster-03_group_1636082172194_yinw-cluster-03_eastus2`. And the `ResourceGroup` in the `--set-file credentials.secretContents.cloud=./credentials-velero` should be this one `MC_xxx`.
> 
> Please find your resource group name and try again.

I have used a separate resource group to backup with sufficient permissions to upload the artefacts post backup. Using the dynamically generated resource group is mandatory?

Upon using the dynamic one, the backup itself fails and no file / blob is uploaded in the azure container

**Comment by ishangupta-ds** [comment]
> AKS creates a new resource group to hold the resources created inside the cluster, it's name is like `MC_yinw-cluster-03_group_1636082172194_yinw-cluster-03_eastus2`. And the `ResourceGroup` in the `--set-file credentials.secretContents.cloud=./credentials-velero` should be this one `MC_xxx`.
> 
> Please find your resource group name and try again.

This seems to work @ywk253100 and @blackpiglet  Thanks for helping out. If the same can be highlighted on the documentation or FAQ for AKS, it would be really helpful. I am closing this issue as it's resolved.

**Comment by ishangupta-ds** [comment]
```
Backup completed with status: Completed
```

```
Total items to be backed up:  510
Items backed up:              510
```

```
Phase:                       Completed
Total items to be restored:  450
Items restored:              450
```

```
❯ kubectl get pods -n wp
NAME                                READY   STATUS    RESTARTS   AGE
my-app-mariadb-0                    1/1     Running   0          67s
my-app-wordpress-5dc5b9dcd4-vmmpx   1/1     Running   0          67s
❯ kubectl get pv -n wp
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                      STORAGECLASS   REASON   AGE
pvc-661f2c90-030e-48a4-94c8-8e7efdd6abf8   10Gi       RWO            Delete           Bound    wp/my-app-wordpress        default                 92s
pvc-942651ad-f98b-41d6-93f2-7a31741e2af3   8Gi        RWO            Delete           Bound    wp/data-my-app-mariadb-0   default                 90s
❯ kubectl get pvc -n wp
NAME                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-my-app-mariadb-0   Bound    pvc-942651ad-f98b-41d6-93f2-7a31741e2af3   8Gi        RWO            default        110s
my-app-wordpress        Bound    pvc-661f2c90-030e-48a4-94c8-8e7efdd6abf8   10Gi       RWO            default        110s
```

The number of items backed up and restored do not match but the app is running and PVs / PVCs were restored successfully .
