### ISSUE TITLE
Backup Storage Location controller may reconcile one item multiple times in a single period

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#4463]
**What steps did you take and what happened:**
Currently, the BSL controller watches BSL resource all events, and there is some buggy logic in the reconcile function.

* After reconcile, the key triggers reconcile will be put in rate-limited work queue immediately. This behavior will trigger multiple reconciles that are not necessary. That will only stop, when the rate-limited function trigger's the exponential back-off, and the back-off time is longer than one minute (By the way, I am still not clear about why only relying on the rate-limited function can let the reconcile loop set exactly to one minute). 
* After more BSL related events happen, there will be more BSL reconciles happen. I think only one reconcile routine is needed in one minute. 

**What did you expect to happen:**
Only one reconcile routine runs, and only runs one time in the period of one minute.

**The following information will help us better understand what's going on**:

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.8
- Velero features (use `velero client config get features`): none
- Kubernetes version (use `kubectl version`): v1.21
- Kubernetes installer & version: docker
- Cloud provider or hardware configuration: Laptop
- OS (e.g. from `/etc/os-release`): OSX

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
During testing on GKE, in some cases, the BSL cannot update the status, after BSL configuration is modified from invalid to valid. 
Need to add a new BSL or recreate the existing BSL to let the status updated to "Available".

**Comment by dsu-igeek** [comment]
Can you write a better description please?  The title does not give any information about what is happening.
