### ISSUE TITLE
[Question]  error executing PVAction for persistentvolumes/pvc 503 not found while Velero fails to restore Jenkins in GKE after migrating backup from thinBackup

### ISSUE THREAD

**Issue by scheung38** [vmware-tanzu/velero#4471]
**What steps did you take and what happened:**

velero restore create fails with: 

`0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
`
**What did you expect to happen:**

velero restore from previous backup of Jenkins pipeline files and folders

**The following information will help us better understand what's going on**:

First velero backup/restore was fine in Jenkins GKE

i.e

`velero backup create jenkins-backup --include-namespaces jenkins --wait
`
then tried migrating more data across from another on-prem Jenkins instance using thinBackup
as zip file:

kubectl cp from ~/Desktop/thinBackup.tgz to <pod-Name-0>:var/jenkins_home/thinBackup/sample_data/thinBackUp.tgz

kubectl exec into pod and extracted into folder where thinBackup restores from 

But now Velero can only backup to completion

but restores: 

`velero restore create --include-namespaces jenkins --from-backup daily-20211221191819
`
results in: 

0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to 

jenkins:

could not restore, pods "idpd-jenkins-0" already exists. Warning: the in-cluster version is different than the backed-up version.
              could not restore, certificaterequests.cert-manager.io "project-dev-vxbnt" already exists. Warning: the in-cluster version is different than the backed-up version.

error executing PVAction for persistentvolumes/pvc-26044f39-dd9f-4678-8540-53a73d2d778e: rpc error: code = Unknown desc = googleapi: Error 404: The resource 'projects/sample-project-257411/global/snapshots/restore-1386c6a9-f386-44f1-bc3fff10-7b75-4791-997e-95194566f627' was not found, notFound

generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

 

**Environment:**

- Velero version (use `velero version`): 1.7.0
- Velero features (use `velero client config get features`):  features: <NOT SET>
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"22",
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GKE Ubuntu
- OS (e.g. from `/etc/os-release`): Mac OSX Monterey 12.1

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
@scheung38 
Could you help to run the command to collect related debug information? `velero debug --backup <backupname> --restore <restorename>`

From the 404 error, I think there may be some issue for the restore related PV's snapshot. Velero cannot find the needed snapshot to restore the PV.

**Comment by scheung38** [comment]
Hi @blackpiglet 

Client:
	Version: v1.7.0
	Git commit: -
Server:
	Version: v1.7.0



backup_describe_jenkins.txt:

Name:         [1mjenkins[0m
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.21.5-gke.1302
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=21

Phase:  [32mCompleted[0m

Errors:    0
Warnings:  0

Namespaces:
  Included:  jenkins
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2022-01-11 16:43:55 +0000 GMT
Completed:  2022-01-11 16:44:01 +0000 GMT

Expiration:  2022-02-10 16:43:55 +0000 GMT

Total items to be backed up:  40
Items backed up:              40

Resource List:
  acme.cert-manager.io/v1/Order:
    - jenkins/ci-ukstats-dev-hwpz4-1229618856
  apiextensions.k8s.io/v1/CustomResourceDefinition:
    - certificaterequests.cert-manager.io
    - certificates.cert-manager.io
    - orders.acme.cert-manager.io
  apps/v1/ControllerRevision:
    - jenkins/idpd-jenkins-59f8799d99
  apps/v1/StatefulSet:
    - jenkins/idpd-jenkins
  cert-manager.io/v1/Certificate:
    - jenkins/ci-ukstats-dev
  cert-manager.io/v1/CertificateRequest:
    - jenkins/ci-ukstats-dev-hwpz4
  discovery.k8s.io/v1/EndpointSlice:
    - jenkins/idpd-jenkins-7g8nn
    - jenkins/idpd-jenkins-agent-9fg4c
  extensions/v1beta1/Ingress:
    - jenkins/ingress-nginx-jenkins
  networking.k8s.io/v1/Ingress:
    - jenkins/ingress-nginx-jenkins
  rbac.authorization.k8s.io/v1/Role:
    - jenkins/idpd-jenkins-casc-reload
    - jenkins/idpd-jenkins-schedule-agents
  rbac.authorization.k8s.io/v1/RoleBinding:
    - jenkins/idpd-jenkins-schedule-agents
    - jenkins/idpd-jenkins-watch-configmaps
  v1/ConfigMap:
    - jenkins/idpd-jenkins
    - jenkins/idpd-jenkins-jenkins-jcasc-config
    - jenkins/kube-root-ca.crt
  v1/Endpoints:
    - jenkins/idpd-jenkins
    - jenkins/idpd-jenkins-agent
  v1/Namespace:
    - jenkins
  v1/PersistentVolume:
    - pvc-62746b4a-c948-4df5-bace-392c1db75ca6
  v1/PersistentVolumeClaim:
    - jenkins/idpd-jenkins
  v1/Pod:
    - jenkins/idpd-jenkins-0
  v1/ResourceQuota:
    - jenkins/gke-resource-quotas
  v1/Secret:
    - jenkins/ci-ukstats-dev
    - jenkins/default-token-z6flj
    - jenkins/github-auth
    - jenkins/idpd-jenkins
    - jenkins/jenkins-token-2b75x
    - jenkins/sh.helm.release.v1.idpd-jenkins.v1
    - jenkins/sh.helm.release.v1.idpd-jenkins.v2
    - jenkins/sh.helm.release.v1.idpd-jenkins.v3
    - jenkins/sh.helm.release.v1.idpd-jenkins.v4
    - jenkins/sh.helm.release.v1.idpd-jenkins.v5
  v1/Service:
    - jenkins/idpd-jenkins
    - jenkins/idpd-jenkins-agent
  v1/ServiceAccount:
    - jenkins/default
    - jenkins/jenkins

Velero-Native Snapshots:
  pvc-62746b4a-c948-4df5-bace-392c1db75ca6:
    Snapshot ID:        gke-idpd2-1a8572ea-dyn-pvc-0c7ad84f-3699-43fb-9b0a-a77aae43a015
    Type:               https://www.googleapis.com/compute/v1/projects/optimum-bonbon-257411/zones/europe-west2-a/diskTypes/pd-standard
    Availability Zone:  europe-west2-a
    IOPS:               <N/A>



restore_describe_jenkins.txt:

Name:         [1mjenkins-20220111175859[0m
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:                       [32mCompleted[0m
Total items to be restored:  37
Items restored:              37

Started:    2022-01-11 17:58:59 +0000 GMT
Completed:  2022-01-11 17:59:04 +0000 GMT

Backup:  jenkins

Namespaces:
  Included:  jenkins
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Preserve Service NodePorts:  auto

**Comment by blackpiglet** [comment]
OK. This may be a corner case. 
In my opinion, 503 error should be related to GCP's disk snapshot resource. 
Not sure what triggered this, but I'm glad that you can make it work with Velero.
