### ISSUE TITLE
[Docs] Failed/PartiallyFailed Orphaned backup will not be removed by ObjectStorageSync

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#4483]
**Describe the problem/challenge you have**
Failed/PartiallyFailed backups hang on Kubernetes although removed from bucket

**Describe the solution you'd like**
Backups that are failed or partially failed should be considered for deletion as well.
https://github.com/vmware-tanzu/velero/blob/d627362abd4da5864cc421e789cf942bf0723ccc/pkg/apis/velero/v1/backup.go#L233
https://github.com/vmware-tanzu/velero/blob/d627362abd4da5864cc421e789cf942bf0723ccc/pkg/apis/velero/v1/backup.go#L237

**Anything else you would like to add:**

Line of code that may need amending to implement this feature: https://github.com/vmware-tanzu/velero/blob/d627362abd4da5864cc421e789cf942bf0723ccc/pkg/controller/backup_sync_controller.go#L342

**Alternatively**: [Object Storage Sync](https://velero.io/docs/v1.7/how-velero-works/#object-storage-sync) docs should mention that only completed backups are deleted.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

cc: @mperetzred @dymurray

**Comment by reasonerjt** [comment]
For a`Failed` backup , it usually does not exist in the bucket, so the backup sync controller should probably not removes it as part of syncing the data.

IMO we should update the doc to clarify it.

**Comment by kaovilai** [comment]
Sounds good to me

**Comment by eleanor-millman** [comment]
@a-mccarthy Do you have enough to do this work, or do you need engineering input? Thanks!

**Comment by sseago** [comment]
I think part of the concern here gets at the root of what the goal of cleaning up expired backups. Obviously the most important reason is storage space in the BSL. But a secondary purpose may be cleaning up the list of backup resources in kubernetes. Currently failed backups and backups with invalid BSLs are not cleaned up, but this could lead to months worth of failed and/or inaccessible backups still clogging the list of returned backups when listing in-cluster backups. We need a way for these to be automatically cleaned up, either by default, or via some feature or configuration flag to have them cleared out when they expire.

**Comment by eleanor-millman** [comment]
@sseago to be clear, are you suggested additional feature work? If so, probably best if you open a separate issue, since this docs issue will be closed once we get the docs updated. But if I misunderstood and you are suggesting different docs updates, then please let me know!

**Comment by sseago** [comment]
@eleanor-millman Ahh -- I think I was mixing up the doc issue (this one) with the related dev issue that we discussed on the call last week. No, I think on the docs side, documenting current behavior is all that this issue needs. The other issue was where we were discussing possible feature work.
