### ISSUE TITLE
The status of BSL isn't updated after updating the credential to an invalid one on Azure

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#4485]
Seems that the BSL's status isn't updated when getting some errors

Steps to reproduce this issue on Azure:
1. Install velero with valid BSL credential, the `PHASE` of BSL is `Available`
2. Update the credential of BSL with a non-existing secret by 
`kubectl patch backupstoragelocation default -p '{"spec":{"credential":{"name":"test", "key":"cloud"}}}' -n velero  --type=merge`
The `PHASE` isn't updated and is still `Available` and get the following error in velero server:
```
time="2022-01-05T03:20:37Z" level=error msg="Error getting a backup store" backup-storage-location=default controller=backup-storage-location error="unable to get credentials: unable to get key for secret: Secret \"test\" not found" error.file="/go/src/github.com/vmware-tanzu/velero/internal/credentials/file_store.go:69" error.function="github.com/vmware-tanzu/velero/internal/credentials.(*namespacedFileStore).Path" logSource="pkg/controller/backup_storage_location_controller.go:100""
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by pradeepkchaturvedi** [comment]
This should be fixed.

**Comment by reasonerjt** [comment]
Similar but different

I created a random secret
```
kubectl -n velero create secret generic creds --from-literal=cloud=invalid
```
 and use `velero` cmd to update the credential
```
velero backup-location set bsl-test --credential=creds=cloud
```
the bsl controller failed to parse the secret to ini file and the BSL's status remains valid, see error message in velero pod's log
```
time="2022-01-08T17:56:16Z" level=info msg="Validating backup storage location" backup-storage-location=default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:114"
time="2022-01-08T17:56:16Z" level=info msg="Backup storage location valid, marking as available" backup-storage-location=default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:121"
time="2022-01-08T17:56:16Z" level=error msg="Error getting a backup store" backup-storage-location=bsl-test controller=backup-storage-location error="rpc error: code = Unknown desc = SharedConfigLoadError: failed to load config file, /tmp/credentials/velero/creds-cloud\ncaused by: INIParseError: unsupported expression {expr {1 STRING 0 [105 110 118 97 108 105 100]} true []}" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:58" error.function=main.getSession logSource="pkg/controller/backup_storage_location_controller.go:100"
```

**Comment by eleanor-millman** [comment]
Additional explanation from a Velero dev that helped me understand this better: Velero is testing the invalid cred and know is it is bad (hence the error message), but the BSL status is not being updated.

**Comment by a-mccarthy** [comment]
@ywk253100, following up here to see if there are any docs that should be improved for this change? From my reading, i don't think there are, but i would like to double check with you. thanks!
