### ISSUE TITLE
Provide "--image-pull-secrets" option with velero install

### ISSUE THREAD

**Issue by ilapogusandeep** [vmware-tanzu/velero#4486]
**Describe the problem/challenge you have**
When pulling an image from private repository, it is a requirement to have a imagePullSecret specified.

**Describe the solution you'd like**
Provide "--image-pull-secrets" option with velero install

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
dup of #3871

**Comment by zubron** [comment]
Closing since this is a duplicate.
