### ISSUE TITLE
Backup process stuck "InProgress" or "PartiallyFailed"

### ISSUE THREAD

**Issue by DavidSanchezAlvarez** [vmware-tanzu/velero#4487]
**What steps did you take and what happened:**
I'm running an EKS cluster in AWS with a bunch of applications on it, and installed Velero to perform backups on an S3 bucket including volumes.
Velero was installed using a Helm Chart version 2.27.0, and installed Velero version v1.6.3.

Velero is running with Restic enabled.

$ k get all
NAME                          READY   STATUS    RESTARTS   AGE
pod/restic-gnqcj              1/1     Running   0          13h
pod/restic-nx8d6              1/1     Running   3          13h
pod/restic-vc6nr              1/1     Running   0          13h
pod/velero-7d6469f7d5-ks64j   1/1     Running   0          4h52m

NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/velero   ClusterIP   172.20.74.182   <none>        8085/TCP   12d

NAME                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/restic   3         3         3       3            3           <none>          12d

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/velero   1/1     1            1           12d

NAME                                DESIRED   CURRENT   READY   AGE
replicaset.apps/velero-55cd5c99c6   0         0         0       12d
replicaset.apps/velero-7d6469f7d5   1         1         1       4h52m

Jenkins consumes an EFS volume.

$ k get pvc -n jenkins
NAME      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
jenkins   Bound    pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf   8Gi        RWO            efs-sc         253d

$ k get pv | grep jenkins
pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf   8Gi        RWO            Retain           Bound      jenkins/jenkins
        efs-sc                   253d
		
$ k get sc
NAME               PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
efs-sc (default)   efs.csi.aws.com         Retain          Immediate              false                  257d
encrypted-gp2      kubernetes.io/aws-ebs   Retain          WaitForFirstConsumer   false                  259d		

Performed the following command in order to launch the backup:

$ velero backup create bckp-jenkins-mgmt-202201041311 --include-namespaces jenkins

After few minutes, the backup process seems to be stuck, and finally timed out and remains in "PartiallyFailed" status or sometimes "InProgress" forever.
In both cases the logs remains the same.

**What did you expect to happen:**
The backup process finishes and final status is "Completed".

**The following information will help us better understand what's going on**:

[Logs can be found here.](https://gist.github.com/DavidSanchezAlvarez/eb42f65cea159ee761368f052955ddee#file-gistfile1-txt)

**Anything else you would like to add:**
We've been able to perform successful backups of some other tools heavier than Jenkins (12.7 GB), Nexus for example (127 GB).

**Environment:**

- Velero version (use velero version):
$ velero version
Client:
        Version: v1.7.0
        Git commit: 9e52260568430ecb77ac38a677ce74267a8c2176
Server:
        Version: v1.6.3 
WARNING: the client version does not match the server version. Please update server

- Velero features (use velero client config get features):
features: <NOT SET>

- Kubernetes version (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1

- Cloud provider or hardware configuration: AWS

- OS (e.g. from /etc/os-release): Amazon Linux 2 EKS
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
The log and resource specs are too long to read in this issue, could you create a gist?

**Comment by DavidSanchezAlvarez** [comment]
> The log and resource specs are too long to read in this issue, could you create a gist?

Updated!. Sorry.

**Comment by peterbosalliandercom** [comment]
Maybe also because of oomkilled problem? https://github.com/vmware-tanzu/velero/issues/4503

**Comment by DavidSanchezAlvarez** [comment]
Hello @peterbosalliandercom .

I don't believe that would be the problem as we are performing backups of much heavier tools (Nexus 130 GB, Jenkins 12.7 GB) without any problem, but there is no way with Jenkins. I'll give it a try just in case, but I'm not optimistic.

Thanks!

**Comment by DavidSanchezAlvarez** [comment]
Added more resources but same result, although getting deeper with the problem I've found this in the PodVolumeBackup logs:

Note: pmo is a homemade plugin for Jenkins.

Status:
  Completion Timestamp:  2022-01-07T09:25:41Z
  Message:               error running restic backup, stderr={"message_type":"error","error":{"Op":"lstat","Path":"/host_pods/b3ea6e9e-a1a9-4b29-b075-ca41d03adf5b/volumes/kubernetes.io~csi/pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf/mount/plugins/pmo/.timestamp2","Err":13},"during":"scan","item":"/host_pods/b3ea6e9e-a1a9-4b29-b075-ca41d03adf5b/volumes/kubernetes.io~csi/pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf/mount/plugins/pmo/.timestamp2"}
{"message_type":"error","error":{"Op":"lstat","Path":"/host_pods/b3ea6e9e-a1a9-4b29-b075-ca41d03adf5b/volumes/kubernetes.io~csi/pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf/mount/plugins/pmo/META-INF","Err":13},"during":"scan","item":"/host_pods/b3ea6e9e-a1a9-4b29-b075-ca41d03adf5b/volumes/kubernetes.io~csi/pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf/mount/plugins/pmo/META-INF"}
{"message_type":"error","error":{"Op":"lstat","Path":"/host_pods/b3ea6e9e-a1a9-4b29-b075-ca41d03adf5b/volumes/kubernetes.io~csi/pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf/mount/plugins/pmo/WEB-INF","Err":13},"during":"scan","item":"/host_pods/b3ea6e9e-a1a9-4b29-b075-ca41d03adf5b/volumes/kubernetes.io~csi/pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf/mount/plugins/pmo/WEB-INF"}
{"message_type":"error","error":{"Op":"lstat","Path":"/host_pods/b3ea6e9e-a1a9-4b29-b075-ca41d03adf5b/volumes/kubernetes.io~csi/pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf/mount/plugins/pmo/images","Err":13},"during":"scan","item":"/host_pods/b3ea6e9e-a1a9-4b29-b075-ca41d03adf5b/volumes/kubernetes.io~csi/pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf/mount/plugins/pmo/images"}
{"message_type":"error","error":{"Op":"lstat","Path":"plugins/pmo/.timestamp2","Err":13},"during":"archival","item":"/host_pods/b3ea6e9e-a1a9-4b29-b075-ca41d03adf5b/volumes/kubernetes.io~csi/pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf/mount/plugins/pmo/.timestamp2"}
{"message_type":"error","error":{"Op":"lstat","Path":"plugins/pmo/META-INF","Err":13},"during":"archival","item":"/host_pods/b3ea6e9e-a1a9-4b29-b075-ca41d03adf5b/volumes/kubernetes.io~csi/pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf/mount/plugins/pmo/META-INF"}
{"message_type":"error","error":{"Op":"lstat","Path":"plugins/pmo/WEB-INF","Err":13},"during":"archival","item":"/host_pods/b3ea6e9e-a1a9-4b29-b075-ca41d03adf5b/volumes/kubernetes.io~csi/pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf/mount/plugins/pmo/WEB-INF"}
{"message_type":"error","error":{"Op":"lstat","Path":"plugins/pmo/images","Err":13},"during":"archival","item":"/host_pods/b3ea6e9e-a1a9-4b29-b075-ca41d03adf5b/volumes/kubernetes.io~csi/pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf/mount/plugins/pmo/images"}
Warning: failed to read all source data during backup
: exit status 3
  Phase:  Failed
  Progress:
    Bytes Done:     13978187287
    Total Bytes:    13978187292

**Comment by DavidSanchezAlvarez** [comment]
Problem finally solved. The quoted plugin was created manually and the permissions were in a weird state and Restic wasn't able to access those files.

pmo:
ls: cannot access 'pmo/.': Permission denied
ls: cannot access 'pmo/..': Permission denied
ls: cannot access 'pmo/WEB-INF': Permission denied
ls: cannot access 'pmo/.timestamp2': Permission denied
ls: cannot access 'pmo/images': Permission denied
ls: cannot access 'pmo/META-INF': Permission denied
total 0
? ? d????????? ? ? ? ?            ? .
? ? d????????? ? ? ? ?            ? ..
? ? d????????? ? ? ? ?            ? images
? ? d????????? ? ? ? ?            ? META-INF
? ? -????????? ? ? ? ?            ? .timestamp2
? ? d????????? ? ? ? ?            ? WEB-INF

Once the permissions were fixed the backup ran until the end with no errors.

**Comment by reasonerjt** [comment]
@DavidSanchezAlvarez 
Glad to know you figured out!
Just curious, any idea why the plugins have wrong permission and did these plugins work if you can't even run `ls`?

**Comment by DavidSanchezAlvarez** [comment]
The plugin was added manually instead of using the GUI of Jenkins..., it resulted in an error and then was added again using the GUI. Some kind of incompatibility seems to be the problem that let the files in that state.

**Comment by DavidSanchezAlvarez** [comment]
Hello all. 

I'm sad to say this, but the problem with the Jenkins backup is back again. The Restic volume backup is getting stuck again at around 30%.

$ velero describe backup sched-jenkins-mgmt-20220511023003 --details | grep -A 1 "In Progress:"
  In Progress:
    jenkins/jenkins-0: jenkins-home (33.12%)
$ velero describe backup sched-jenkins-mgmt-20220510023002 --details | grep -A 1 "In Progress:"
  In Progress:
    jenkins/jenkins-0: jenkins-home (24.82%)
$ velero describe backup sched-jenkins-mgmt-20220508023010 --details | grep -A 1 "In Progress:"
  In Progress:
    jenkins/jenkins-0: jenkins-home (32.24%)

[Describe backup logs](https://gist.github.com/DavidSanchezAlvarez/9eb4ead85a50378e969e63c1c155f277#file-backup-logs)
