### ISSUE TITLE
Unmounted volumes cause backup to be PartiallyFailed

### ISSUE THREAD

**Issue by dkeven** [vmware-tanzu/velero#4495]
**What steps did you take and what happened:**
Create a `backup` that includes a pod with an unmounted volume.
(That is, a pod with the `.spec.volumes` field defined but one or some of the volumes are not mounted by **any** container of the pod.)

The backup eventually ends in the `PartiallyFailed` status, with the following error message:
```
error getting volume path on host: expected one matching path, got 0
```

**What did you expect to happen:**
The backup completes successfully.

**The following information will help us better understand what's going on**:
error logs of the backup:
```
time="2022-01-06T01:14:43Z" level=info msg="Processing item" backup=qiming-backend/back1-nxioy-5j7v8 logSource="pkg/backup/backup.go:358" name=nginx-empz20-bc968444c-69qxr namespace=back progress= resource=pods
time="2022-01-06T01:14:43Z" level=info msg="Backing up item" backup=qiming-backend/back1-nxioy-5j7v8 logSource="pkg/backup/item_backupper.go:121" name=nginx-empz20-bc968444c-69qxr namespace=back resource=pods
time="2022-01-06T01:14:43Z" level=info msg="Executing custom action" backup=qiming-backend/back1-nxioy-5j7v8 logSource="pkg/backup/item_backupper.go:327" name=nginx-empz20-bc968444c-69qxr namespace=back resource=pods
time="2022-01-06T01:14:43Z" level=info msg="Executing podAction" backup=qiming-backend/back1-nxioy-5j7v8 cmd=/velero logSource="pkg/backup/pod_action.go:51" pluginName=velero
time="2022-01-06T01:14:43Z" level=info msg="Done executing podAction" backup=qiming-backend/back1-nxioy-5j7v8 cmd=/velero logSource="pkg/backup/pod_action.go:77" pluginName=velero
time="2022-01-06T01:14:43Z" level=info msg="1 errors encountered backup up item" backup=qiming-backend/back1-nxioy-5j7v8 logSource="pkg/backup/backup.go:431" name=nginx-empz20-bc968444c-69qxr
time="2022-01-06T01:14:43Z" level=error msg="Error backing up item" backup=qiming-backend/back1-nxioy-5j7v8 error="pod volume backup failed: error getting volume path on host: expected one matching path, got 0" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:184" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:435" name=nginx-empz20-bc968444c-69qxr
```

**Anything else you would like to add:**
The PodVolumeBackup spec:
```
spec:
  node: master
  pod:
    kind: Pod
    name: nginx-empz20-bc968444c-69qxr
  tags:
    backup: back1-nxioy-5j7v8
    ns: back
    pod: nginx-empz20-bc968444c-69qxr
    volume: html
  volume: html
```

In my case, there's an `emptyDir` volume named `html` in the `nginx-empz20-bc968444c-69qxr` pod, but the volume is not mounted, so kubelet ignores this volume, and no path under `/var/lib/kubelet` is created for this volume. 

As we can see in this piece of code:
https://github.com/kubernetes/kubernetes/blob/65378e7747a4e81002ba0bf953a20159597f8360/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L293-L298

When the restic daemon tries to backup this volume, it can not find the corresponding path and then throws out an error.
As in:
https://github.com/vmware-tanzu/velero/blob/b6992101a45d80e297615594e15a97c1db258992/pkg/controller/pod_volume_backup_controller.go#L441-L443

**Environment:**

- Velero version (use `velero version`): 1.7.0
- Kubernetes version (use `kubectl version`): 1.21

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by eleanor-millman** [comment]
Additional explanation from a Velero dev that helped me understand this better: 
Very similar to https://github.com/vmware-tanzu/velero/issues/2395 (in 2395, volume not accessible because pod not running, in this issue, volume not accessible because volume not mounted)

**Comment by dkeven** [comment]
I'm closing this issue since it's been fixed.
