### ISSUE TITLE
Docs: clarify that the AWS volume snapshotter does not work between AWS regions

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/velero#4500]
**Describe the problem/challenge you have**
As a Velero user/PM I want to know from the docs that I cannot use the AWS volume snapshotter to migrate data between AWS regions and that I HAVE to use restic.

Let's also document the similar situation in Azure: "Yes, the same limitation applies for Azure. Snapshots can be taken and stored in a different subscriptions, but can only be created in the same region as the original disk."

**Describe the solution you'd like**
I'd like this information to be in the docs, probably on this page: https://velero.io/docs/v1.7/migration-case/

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
@eleanor-millman

 Based on the description, you are not looking for a "yes" or "no" answer.  You know the answer is "no" but you open this issue to make sure it's mentioned in the doc, is my understanding correct?

**Comment by eleanor-millman** [comment]
@reasonerjt sorry, good point! When I made the original issue, I didn't know the answer. I now do, so I edited the title to reflect that. Thanks for clarifying!

**Comment by ross-worth** [comment]
I believe this will also be a limitation in AKS as Azure does not support snapshots across Regions

**Comment by eleanor-millman** [comment]
@ross-worth Thank you for that point! @zubron are you able to confirm this as well? If so, I'll change the description to include that.

**Comment by eleanor-millman** [comment]
Engineering help needed: please confirm if we also have the same limitation in Azure. If so, then we can put both limitations in the docs at the same time.

**Comment by zubron** [comment]
Yes, the same limitation applies for Azure. Snapshots can be taken and stored in a different subscriptions, but can only be created in the same region as the original disk.

I don't know if the same limitation applies for GCP. It seems that snapshots are [global resources](https://cloud.google.com/compute/docs/regions-zones/global-regional-zonal-resources#globalresources) so can be restored from in any region, however they can only be accessed within the same project. I haven't tried this out, and I don't know if Velero supports this configuration.

**Comment by eleanor-millman** [comment]
Thanks for the feedback @zubron ! Let's leave GCP for now and document AWS and Azure since I believe those are the more heavily used plugins.
