### ISSUE TITLE
Basic Annotation E2E test case does not clear created namespace, after test finishes.

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#4504]
**What steps did you take and what happened:**
CREDS_FILE=/root/credentials-velero \
BSL_BUCKET=jxun \
CLOUD_PROVIDER=gcp \
VELERO_CLI=/usr/local/bin/velero \
VELERO_VERSION=main \
VELERO_IMAGE=velero/velero:main \
VELERO_NAMESPACE=velero \
REGISTRY_CREDENTIAL_FILE=/root/docker-config.json \
ADDITIONAL_OBJECT_STORE_PROVIDER=aws \
ADDITIONAL_CREDS_FILE=/root/aws_credentials \
ADDITIONAL_BSL_BUCKET=mqiu-bucket \
GINKGO_FOCUS=Basic \
make test-e2e

After test finished, run kubectl command to retrieve namespace list:
# kubectl get ns
NAME                                                           STATUS   AGE
default                                                        Active   12h
include-namespaces-88ef2bbf-10bd-46de-bba9-80bf3928eb02-0      Active   12h
kube-node-lease                                                Active   12h
kube-public                                                    Active   12h
kube-system                                                    Active   12h
namespace-annotations-7729d5a9-b948-42e9-8f7d-1ea210a80e1d-0   Active   11h

**What did you expect to happen:**
Namespace "namespace-annotations-7729d5a9-b948-42e9-8f7d-1ea210a80e1d-0" is expected to be deleted.

**The following information will help us better understand what's going on**:

- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.8
- Velero features (use `velero client config get features`): none
- Kubernetes version (use `kubectl version`): 1.22
- Kubernetes installer & version: GKE
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): Linux

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
https://github.com/vmware-tanzu/velero/blob/a2b6d06f6189fdbecaa5b344d415a6a3dd56b8e0/test/e2e/basic/resources-check/namespaces_annotation.go#L74-L101

**Comment by qiuming-best** [comment]
@blackpiglet delete namespace method is in the base class(TestCase),  I only delete once without polling waiting and checking because I'm fear of a long time waiting and checking will make the whole e2e process become a more long time.
