### ISSUE TITLE
Trouble creating Velero storage location with storage access key

### ISSUE THREAD

**Issue by am3ience** [vmware-tanzu/velero#4506]
i'm trying to use Velero to backup an AKS cluster but for some reason i'm unable to set the backup location in velero.

i'm getting the error below
![can't find storage key env var](https://user-images.githubusercontent.com/8881409/148637329-980804e2-c6c5-4ac7-ab11-e53c547c6d6b.png)

I used the following commands to get the credential file:

Obtain the Azure Storage account access key
``AZURE_STORAGE_ACCOUNT_ACCESS_KEY=`az storage account keys list --account-name storsmaxdv --query "[?keyName == 'key1'].value" -o tsv`
``

then I create the credential file
```
cat << EOF  > ./credentials-velero
AZURE_STORAGE_ACCOUNT_ACCESS_KEY=${AZURE_STORAGE_ACCOUNT_ACCESS_KEY}
AZURE_CLOUD_NAME=AzurePublicCloud
EOF
```

then my install command is:
```
./velero install \
    --provider azure 
    --plugins velero/velero-plugin-for-microsoft-azure:v1.3.0 \
    --bucket velero \
    --secret-file ./credentials-velero \
    --backup-location-config resourceGroup=resourcegroupname,storageAccount=storageAccount,storageAccountKeyEnvVar=AZURE_STORAGE_ACCOUNT_ACCESS_KEY[,subscriptionId=numbersandlettersandstuff] \
    --use-volume-snapshots=false
```

I can verify Velero created a secret called cloud-credentials, and when I decrypt it with base64 I'm able to see what looks like the contents of my credentials-velero file. for example:
```
AZURE_STORAGE_ACCOUNT_ACCESS_KEY=MYAZURESTORAGEACCOUNTKEY
AZURE_CLOUD_NAME=AzurePublicCloud
```

First time using Velero so i'm at a loss. 

**Environment:**

- Velero version (use `velero version`): 1.7
- Velero features (use `velero client config get features`): velero for azure 
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: azure
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by reasonerjt** [comment]
@am3ience 
To set the credential file correctly, please follow the instructions in https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#setup-azure-storage-account-and-blob-container

**Comment by am3ience** [comment]
I already had a storage account so I just created a blob container using the command in the link you posted.

`az storage container create -n velero --public-access off --account-name nameofstorageaccount`

this was already done before I ran the velero install. Do you think i'm getting the error because my blob storage maybe wasn't created properly?

**Comment by am3ience** [comment]
Figured out the issue, there's a problem in the install command

the [] brackets in this part of the install command was being read, specifically "AZURE_STORAGE_ACCOUNT_ACCESS_KEY[ "
`--backup-location-config resourceGroup=resourcegroupname,storageAccount=storageAccount,storageAccountKeyEnvVar=AZURE_STORAGE_ACCOUNT_ACCESS_KEY[,subscriptionId=numbersandlettersandstuff] \`

changed it to:

`--backup-location-config resourceGroup=resourcegroupname,storageAccount=storageAccount,storageAccountKeyEnvVar=AZURE_STORAGE_ACCOUNT_ACCESS_KEY,subscriptionId=numbersandlettersandstuff \`

and now it works.

Not sure if you guys want to fix the code or adjust the documentation to reflect that bug.

**Comment by ywk253100** [comment]
The `[]` means it's optional.
Glad you fixed it out, I'm closing this issue.
