### ISSUE TITLE
BSL created by velero CLI not work due to invalid default credential parameter

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#4508]
**What steps did you take and what happened:**

`velero backup-location create --backup-sync-period=300s --provider=aws --bucket=velero sync-period-test --config re
gion=minio,s3ForcePathStyle=true;s3Url=https://minio.minio.svc:9000`

The result is 
`velero backup-location get`
`NAME               PROVIDER   BUCKET/PREFIX   PHASE         LAST VALIDATED                  ACCESS MODE   DEFAULT`
`default            aws        velero          Unavailable   2022-01-10 09:48:23 +0800 CST   ReadWrite     true`
`sync-period-test   aws        velero          Unknown       Unknown                         ReadWrite`

**What did you expect to happen:**
Created BSL is validated and enter correct phase.

**The following information will help us better understand what's going on**:
Retrieve the created BSL's yaml by kubectl:
https://gist.github.com/blackpiglet/94373aa8cab338917e8bfc73b614f739
There is an invalid credential parameter in BSL spec:
  credential:
    key: ""

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

After removing the invalid credential parameter, BSL works as expected.
`NAME               PROVIDER   BUCKET/PREFIX   PHASE         LAST VALIDATED                  ACCESS MODE   DEFAULT`
`sync-period-test   aws        velero          Unavailable   2022-01-10 09:54:23 +0800 CST   ReadWrite`

**Environment:**

- Velero version (use `velero version`): v1.8
- Velero features (use `velero client config get features`): None
- Kubernetes version (use `kubectl version`): v1.21
- Kubernetes installer & version: Docker
- Cloud provider or hardware configuration: None
- OS (e.g. from `/etc/os-release`): Darwin

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment]
@blackpiglet Hmm, I thought this was fixed in #4322. Could you confirm if the version of the CLI you are using includes that particular commit?

**Comment by blackpiglet** [comment]
@zubron 
Oh. I verified with main release velero client. The issue is not found.
I tried to verify older version of velero client's compliance with v1.8 Velero server, during the test I triggered this.

**Comment by zubron** [comment]
Great! Thanks for checking :) I just wanted to make sure that the fix was working correctly.
