### ISSUE TITLE
Backup job indefinitely stuck on InProgress state after enabling EnableCSI feature

### ISSUE THREAD

**Issue by marinoborges** [vmware-tanzu/velero#4511]
**What steps did you take and what happened:**
After enabling velero EnableCSI feature (together with [external-snapshotter](https://github.com/kubernetes-csi/external-snapshotter) and [aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver)), backup is randomly getting stuck on InProgress state. 

As a side effect, all other backup jobs on the queue don't run waiting for the one stuck to finish which only happen if velero pod gets restarted.

This issue happens intermittently: sometimes this velero job works fine. When it doesn't get stuck, it finishes with PartiallyFailed status with some warnings and errors but with CSI backups working as expected.

Checking the velero pod logs, there is no error or warning in loop that help to understand why it's being stuck for so long.

**What did you expect to happen:**
I expect the velero job to finish and log the corresponding error.

**The following information will help us better understand what's going on**:
```
$ velero debug --backup velero-full-hourly-20220107000029
2022/01/10 00:35:02 Collecting velero resources in namespace: velero
2022/01/10 00:35:35 Collecting velero deployment logs in namespace: velero
2022/01/10 00:35:57 Collecting log and information for backup: velero-full-hourly-20220107000029
An error occurred: exec failed: Traceback (most recent call last):
  velero-debug-collector:27:20: in <toplevel>
  velero-debug-collector:7:22: in capture_backup_logs
  <builtin>: in capture
Error: capture_local: exit status 1
```

**Anything else you would like to add:**
Output of `velero debug`:
**[bundle-2022-01-10-00-39-49-redacted.tar.gz](https://github.com/vmware-tanzu/velero/files/7840779/bundle-2022-01-10-00-39-49-redacted.tar.gz)**

**Environment:**

- Velero version
```
Client:
	Version: v1.7.0
	Git commit: 9e52260568430ecb77ac38a677ce74267a8c2176
Server:
	Version: v1.7.0
```

- Velero features
`features: <NOT SET>`
- Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: **ClusterAPI  v0.4.5**

- Cloud provider or hardware configuration: **AWS**
- OS (e.g. from `/etc/os-release`): **Ubuntu 18.04**

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
I recommend to use the AWS plugin instead of CSI plugin. 
The CSI plugin is still in beta, so it's possible to meet some error.
The velero-plugin-for-aws already support CSI PV backup and restore in latest version. 
You can try with this image: velero/velero-plugin-for-aws:main

**Comment by marinoborges** [comment]
Thanks for answering @blackpiglet. Cool, that's an unreleased feature yet, right? Is there any estimated time to the next release?

**Comment by marinoborges** [comment]
Velero 1.8 with CSI PV backup just released.
