### ISSUE TITLE
velero partially failed restore GKE

### ISSUE THREAD

**Issue by scheung38** [vmware-tanzu/velero#4524]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

gcloud container clusters create mycluster \                                           
--machine-type n2-standard-4 --num-nodes 1 \
--scopes "https://www.googleapis.com/auth/source.read_write,cloud-platform" --image-type ubuntu_containerd --enable-autoscaling --min-nodes 0 --max-nodes 2

velero backup create jenkins-all-namespaces --wait

kubectl delete namespace jenkins

velero restore create --from-backup jenkins-all-namespaces

Name:         [1mjenkins-all-namespaces-20220112112525[0m
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:                       [31mPartiallyFailed[0m (run 'velero restore logs jenkins-all-namespaces-20220112112525' for more information)
Total items to be restored:  865
Items restored:              865

Started:    2022-01-12 11:25:25 +0000 GMT
Completed:  2022-01-12 11:26:55 +0000 GMT

Warnings:
  Velero:     <none>
  Cluster:  could not restore, customresourcedefinitions.apiextensions.k8s.io "backendconfigs.cloud.google.com" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "backups.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "backupstoragelocations.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "capacityrequests.internal.autoscaling.gke.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "certificaterequests.cert-manager.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "certificates.cert-manager.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "challenges.acme.cert-manager.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "clusterissuers.cert-manager.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "deletebackuprequests.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "downloadrequests.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "frontendconfigs.networking.gke.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "issuers.cert-manager.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "managedcertificates.networking.gke.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "orders.acme.cert-manager.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "podvolumebackups.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "podvolumerestores.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "resticrepositories.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "restores.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "schedules.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "serverstatusrequests.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "serviceattachments.networking.gke.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "servicenetworkendpointgroups.networking.gke.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "storagestates.migration.k8s.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "storageversionmigrations.migration.k8s.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "updateinfos.nodemanagement.gke.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "volumesnapshotclasses.snapshot.storage.k8s.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "volumesnapshotcontents.snapshot.storage.k8s.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "volumesnapshotlocations.velero.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, customresourcedefinitions.apiextensions.k8s.io "volumesnapshots.snapshot.storage.k8s.io" already exists. Warning: the in-cluster version is different than the backed-up version.
  Namespaces:
    nginx-ingress:    could not restore, configmaps "ingress-controller-leader" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, pods "ingress-nginx-controller-54bfb9bb-cz7h7" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, services "ingress-nginx-controller-admission" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, services "ingress-nginx-controller" already exists. Warning: the in-cluster version is different than the backed-up version.
    velero:           could not restore, pods "velero-7b48fc597b-fl86p" already exists. Warning: the in-cluster version is different than the backed-up version.
    cert-manager:     could not restore, pods "cert-manager-release-7597885996-9twtk" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, pods "cert-manager-release-cainjector-76596b5477-jx27q" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, pods "cert-manager-release-webhook-5df4844bb8-c7bg7" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, jobs.batch "cert-manager-release-startupapicheck" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, services "cert-manager-release-webhook" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, services "cert-manager-release" already exists. Warning: the in-cluster version is different than the backed-up version.
    default:          could not restore, services "cert-manager-webhook" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, services "cert-manager" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, services "kubernetes" already exists. Warning: the in-cluster version is different than the backed-up version.
    kube-node-lease:  could not restore, leases.coordination.k8s.io "gke-idpd2-default-pool-2d59eb65-trv5" already exists. Warning: the in-cluster version is different than the backed-up version.
    kube-system:      could not restore, configmaps "cert-manager-cainjector-leader-election" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, configmaps "cert-manager-controller" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, configmaps "cluster-autoscaler-status" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, configmaps "cluster-kubestore" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, configmaps "clustermetrics" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, configmaps "gke-common-webhook-heartbeat" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, configmaps "gke-common-webhook-lock" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, configmaps "ingress-gce-lock" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, pods "event-exporter-gke-5479fd58c8-t8jl8" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, pods "fluentbit-gke-4m8mp" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, pods "gke-metrics-agent-4kswq" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, pods "konnectivity-agent-54447dd65d-plzl7" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, pods "konnectivity-agent-autoscaler-5c49cb58bb-mpc5m" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, pods "kube-dns-697dc8fc8b-mw6hs" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, pods "kube-dns-autoscaler-844c9d9448-zr2s5" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, pods "l7-default-backend-865b4c8f8b-6wpvn" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, pods "metrics-server-v0.4.4-857776bc9c-pjc7c" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, pods "pdcsi-node-lqmwr" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, endpoints "gcp-controller-manager" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, endpoints "managed-certificate-controller" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, endpoints "vpa-recommender" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, leases.coordination.k8s.io "cert-manager-cainjector-leader-election" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, leases.coordination.k8s.io "cert-manager-controller" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, leases.coordination.k8s.io "cluster-autoscaler" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, leases.coordination.k8s.io "kube-controller-manager" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, leases.coordination.k8s.io "kube-scheduler" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, leases.coordination.k8s.io "managed-certificate-controller" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, leases.coordination.k8s.io "snapshot-controller-leader" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, services "default-http-backend" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, services "kube-dns" already exists. Warning: the in-cluster version is different than the backed-up version.
                      could not restore, services "metrics-server" already exists. Warning: the in-cluster version is different than the backed-up version.

Errors:
  Velero:     <none>
  Cluster:  error restoring clusterissuers.cert-manager.io/letsencrypt-prod: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.default.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook"
            error restoring clusterissuers.cert-manager.io/letsencrypt-staging: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.default.svc:443/mutate?timeout=10s": no endpoints available for service "cert-manager-webhook"
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/catch-all: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical flow schemas
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/endpoints: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical flow schemas
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/exempt: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical flow schemas
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/gke-componentstatuses: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical flow schemas
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/kube-controller-manager: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical flow schemas
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/kube-scheduler: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical flow schemas
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/kube-system-service-accounts: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical flow schemas
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/probes: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical flow schemas
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/system-leader-election: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical flow schemas
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/system-node-high: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical flow schemas
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/system-nodes: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical flow schemas
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/workload-leader-election: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical flow schemas
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/catch-all: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical priority level configurations
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/endpoints: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical priority level configurations
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/exempt: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical priority level configurations
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/leader-election: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical priority level configurations
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/node-high: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical priority level configurations
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/system: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical priority level configurations
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/workload-high: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: can't modify cluster-critical priority level configurations
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/workload-low: admission webhook "flowcontrol-guardrails.common-webhooks.networking.gke.io" denied the request: priority level configuration workload-low cannot be added as requested shares 100 exceed available shares by 70; re-allocate shares from other non-cluster-critical priority level configurations and retry
  Namespaces: <none>

Backup:  jenkins-all-namespaces

Namespaces:
  Included:  all namespaces found in the backup
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Preserve Service NodePorts:  auto

**What did you expect to happen:**

complete restore

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
I think this is expected result. 
`velero backup create jenkins-all-namespaces --wait` this command will backup with all namespaces. 
Then delete jenkins namespace and create restore. If the resources in jenkins namespace are restored successfully, the restore works as expected. 

The error messages are triggered by restore is trying to create existing resources.

If you want to avoid this partial failure and error message, you can create backup with parameter --include-namespaces=jenkins. This parameter will backup all resources related to the specified namespace.

**Comment by blackpiglet** [comment]
I reproduced this issue in my testing environment. Not sure whether my case is same as yours.

I have two GKE clusters. Cluster A's version is `v1.23.4-gke.1300`. Cluster B's version is `v1.22.6-gke.1000`.

I created a backup on cluster A, then tried to restore on cluster B. I got error information similar to your. 

```
Errors:
  Velero:     <none>
  Cluster:  error restoring flowschemas.flowcontrol.apiserver.k8s.io/catch-all: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/endpoints: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/exempt: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/gke-clustermetrics: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/gke-common-webhooks: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/gke-components-common: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/gke-componentstatuses: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/gke-glbc: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/gke-managed-certificate-controller: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/gke-master-healthcheck: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/gke-pdcsi-controller: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/global-default: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/konnectivity-server: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/kube-controller-manager: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/kube-scheduler: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/kube-system-service-accounts: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/probes: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/service-accounts: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/system-leader-election: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/system-node-high: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/system-nodes: the server could not find the requested resource
            error restoring flowschemas.flowcontrol.apiserver.k8s.io/workload-leader-election: the server could not find the requested resource
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/catch-all: the server could not find the requested resource
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/endpoints: the server could not find the requested resource
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/exempt: the server could not find the requested resource
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/global-default: the server could not find the requested resource
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/leader-election: the server could not find the requested resource
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/node-high: the server could not find the requested resource
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/system: the server could not find the requested resource
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/workload-high: the server could not find the requested resource
            error restoring prioritylevelconfigurations.flowcontrol.apiserver.k8s.io/workload-low: the server could not find the requested resource
```

**Comment by blackpiglet** [comment]
I closed this issue for now. If my situation is not same with yours, or have any update, please reopen to trace.
