### ISSUE TITLE
Add Astrolabe to the Velero governance doc

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/velero#4525]

**Comment by eleanor-millman** [comment]
@jonasrosland Can you clarify what you mean by this?  Do you just mean under "Code Repositories"? https://github.com/vmware-tanzu/velero/blob/main/GOVERNANCE.md

**Comment by jonasrosland** [comment]
Yup, exactly

**Comment by a-mccarthy** [comment]
@eleanor-millman do we still need this issue?

**Comment by eleanor-millman** [comment]
We can close this for now.
