### ISSUE TITLE
Unable to restore serviceinstances using velero

### ISSUE THREAD

**Issue by nirav-mistry** [vmware-tanzu/velero#4526]
### Discussed in https://github.com/vmware-tanzu/velero/discussions/4515

<div type='discussions-op-text'>

<sup>Originally posted by **nirav-mistry** January 11, 2022</sup>
We are trying to restore namespace using velero backup. 
During the restore we are getting below error which is creating issue in starting application in the namespace. 

error restoring serviceinstances.servicecatalog.k8s.io/abc-in02-env7-runtime/digital-couchbase-service-med2-4fcdd959aa2f2fff4f444d003d760050: admission webhook "validating.serviceinstances.servicecatalog.k8s.io" denied the request: [spec.serviceClassRef: Forbidden: serviceClassRef must not be present on create, spec.servicePlanRef: Forbidden: servicePlanRef must not be present on create]</div>

**Comment by blackpiglet** [comment]
It seems the failure is caused by validation webhook. 
Is it possible to disable the webhook during restore process?

**Comment by blackpiglet** [comment]
@nirav-mistry 
Could you give more detail on the backup k8s cluster environment?
It seems resource triggered error is installed by ServiceCatalog. 
We haven't met this situation yet. 
As ServiceCatalog is already a commonly used way to extend k8s on cloud provider, this issue may be good reference for future Velero use case.

**Comment by nirav-mistry** [comment]
Could you give more detail on the backup k8s cluster environment? -- we are running openshift 4.6 on which are using velero ( version - 1.7 ) to take daily backups. Backup is taken through schedule with default full cluster level backup.
It seems resource triggered error is installed by ServiceCatalog. -- yes, we are using servicecatalog and issue is related to it. 
We want to know if there are methods in velero that can help on restoring servicecatalog resources.

**Comment by blackpiglet** [comment]
Could you provide some hints about ServiceCatalog? 
I'm not familiar with that tech, so could you give how it's installed and how application is installed by ServiceCatalog? How to use ServiceCatalog document on Azure is better.

**Comment by nirav-mistry** [comment]
Service catalogs are basically openshift based implementation for  Open Service Broker API (OSB API) in Kubernetes. Its main role is to provide service broker that microservices/application running in openshift to connect to external third party application like couchbase, elasticsearch, etc. It is deployed at the namespace with custom yaml with service broker resource. 

By the way , in our case we are running openshift service catalog on VMWare based platform ( not on azure ).

**Comment by nirav-mistry** [comment]
Hi Team,

Can someone advise on this issue?

**Comment by blackpiglet** [comment]
Just got back from Chinese Spring Festival Vacation. 
I think this is caused by Webhook configuration. Webhook related resource should be ready before others.
To my knowledge, this is not supported in Velero by now. Velero still cannot separate Webhook from other resource. 
I think maybe the webhook's configuration should be provisioned manually before running the restore command.
