### ISSUE TITLE
Investigate Kopia

### ISSUE THREAD

**Issue by qiuming-best** [vmware-tanzu/velero#4538]
**Describe the problem/challenge you have**
Benefits include getting incremental for vSphere, ability to move away from restic, and perhaps encryption at rest

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by Satsank** [comment]
[CloudCasa](https://cloudcasa.io) Team has done a comparative study between Restic and Kopia as data mover candidates about a year ago when we were designing and implementing our Kubernetes backup service. We are happy to share our observations and feedback(good and bad) on a call if it would help. FWIW, we concluded that Kopia offered more advantages than restic after our analysis and testing. Hope this helps!

**Comment by qiuming-best** [comment]
@Satsank Thanks for your comments. We are hopeful that you could share your experiences with us in our community meeting, What time zone are you in? Is it convenient for you to take participate in the Beijing time zone?

**Comment by qiuming-best** [comment]
@Satsank Do you have any time to share something with us?

**Comment by brovoca** [comment]
How about Borg? I've used it on my own Linux machine for a couple of months now and it's solid.

**Comment by Lyndon-Li** [comment]
In order to make an integration with Velero, we need to consider many points, not only performance and stableness. At present, Kopia seems to meet most of Velero's requirement, that is why we focus on it, though it is possible we try more alternatives in future.

**Comment by qiuming-best** [comment]
[Here](https://docs.google.com/document/d/1BMLuRzEpYWYE-Ci_eLg8gWbjDv4DSyqj/edit) is the document about investigating kopia

**Comment by brovoca** [comment]
@qiuming-best Any possibility of attaching the document in this issue? I don't have a Google account :-)

**Comment by kaovilai** [comment]
[Copy of kopia-restic-comparison.docx.pdf](https://github.com/user-attachments/files/21123755/Copy.of.kopia-restic-comparison.docx.pdf)

Here's copy of the doc.
