### ISSUE TITLE
Azure AKS PVC Snapshots not being taken

### ISSUE THREAD

**Issue by ross-worth** [vmware-tanzu/velero#4553]
Installed using:
```velero install --provider azure --plugins velero/velero-plugin-for-microsoft-azure:latest --bucket velero --secret-file ./credentials-velero.txt --backup-location-config resourceGroup=UKSK01_Velero_Backups,storageAccount=uksk01velerobackups --snapshot-location-config apiTimeout=5m,resourceGroup=MC_escUKSK01_escuksk01_uksouth --features=EnableCSI --deployRestic=true --use-volume-snapshots=true --image velero/velero:v1.7.1```

Ran a backup job attempting to backup a deployment containing a PVC that uses the  disk.csi.azure.com driver in an AKS cluster. In the logs I can find the following issues:

- "No volume ID returned by volume snapshotter for persistent volume" 
- "Persistent volume is not a supported volume type for snapshots, skipping."

```
time="2022-01-19T16:47:36Z" level=info msg="Executing PVCAction" backup=velero/test3 cmd=/velero logSource="pkg/backup/backup_pv_action.go:49" pluginName=velero
time="2022-01-19T16:47:37Z" level=info msg="Backing up item" backup=velero/test3 logSource="pkg/backup/item_backupper.go:121" name=pvc-e2120c0d-0271-4637-9e2f-3ce6b7748461 namespace= resource=persistentvolumes
time="2022-01-19T16:47:37Z" level=info msg="Executing takePVSnapshot" backup=velero/test3 logSource="pkg/backup/item_backupper.go:405" name=pvc-e2120c0d-0271-4637-9e2f-3ce6b7748461 namespace= resource=persistentvolumes
time="2022-01-19T16:47:37Z" level=info msg="label \"topology.kubernetes.io/zone\" is not present on PersistentVolume, checking deprecated label..." backup=velero/test3 logSource="pkg/backup/item_backupper.go:432" name=pvc-e2120c0d-0271-4637-9e2f-3ce6b7748461 namespace= persistentVolume=pvc-e2120c0d-0271-4637-9e2f-3ce6b7748461 resource=persistentvolumes
time="2022-01-19T16:47:37Z" level=info msg="label \"failure-domain.beta.kubernetes.io/zone\" is not present on PersistentVolume" backup=velero/test3 logSource="pkg/backup/item_backupper.go:435" name=pvc-e2120c0d-0271-4637-9e2f-3ce6b7748461 namespace= persistentVolume=pvc-e2120c0d-0271-4637-9e2f-3ce6b7748461 resource=persistentvolumes
time="2022-01-19T16:47:37Z" level=info msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/test3 logSource="pkg/backup/item_backupper.go:458" name=pvc-e2120c0d-0271-4637-9e2f-3ce6b7748461 namespace= persistentVolume=pvc-e2120c0d-0271-4637-9e2f-3ce6b7748461 resource=persistentvolumes volumeSnapshotLocation=default
time="2022-01-19T16:47:37Z" level=info msg="Persistent volume is not a supported volume type for snapshots, skipping." backup=velero/test3 logSource="pkg/backup/item_backupper.go:469" name=pvc-e2120c0d-0271-4637-9e2f-3ce6b7748461 namespace= persistentVolume=pvc-e2120c0d-0271-4637-9e2f-3ce6b7748461 resource=persistentvolumes```
```

**What did you expect to happen:**
Expected a snapshot to be created in the defined resource group.

**The following information will help us better understand what's going on**:
Searches have shown this issue seems to be affecting csi drivers on AKS, GKE, and AWS. So the fix may need to take into account the other cloud providers.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero Version: 
-Client:
        Version: v1.7.1
        Git commit: 4729274d07eae7e788233d5c995d7f45f40c9c61
Server:
        Version: v1.7.1
- Velero features (use `velero client config get features`): 

- Azure AKS 1.21

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
I'm not quite sure it's similar related to this [reason](https://github.com/vmware-tanzu/velero/issues/3341#issuecomment-837536617)

can you please share the output of:
kubectl -n velero get backup <BACKUP_NAME> -oyaml
kubectl -n velero get volumesnapshotlocations -oyaml

**Comment by ross-worth** [comment]
kubectl -n velero get backup <BACKUP_NAME> -oyaml

```apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/source-cluster-k8s-gitversion: v1.21.7
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "21"
  creationTimestamp: "2022-01-19T16:47:26Z"
  generation: 5
  labels:
    velero.io/storage-location: default
  name: test3
  namespace: velero
  resourceVersion: "13908746"
  uid: b49ecad8-c7d4-4d7f-a3a7-dddefb53b3d3
spec:
  defaultVolumesToRestic: false
  hooks: {}
  includedNamespaces:
  - '*'
  labelSelector:
    matchLabels:
      backup: "true"
  metadata: {}
  storageLocation: default
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - default
status:
  completionTimestamp: "2022-01-19T16:47:37Z"
  expiration: "2022-02-18T16:47:26Z"
  formatVersion: 1.1.0
  phase: Completed
  progress:
    itemsBackedUp: 3
    totalItems: 3
  startTimestamp: "2022-01-19T16:47:26Z"
  version: 1```

kubectl -n velero get volumesnapshotlocations -oyaml
I have removed the resource group name from the yaml below.

```apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: VolumeSnapshotLocation
  metadata:
    creationTimestamp: "2022-01-19T16:46:44Z"
    generation: 1
    labels:
      component: velero
    name: default
    namespace: velero
    resourceVersion: "13908384"
    uid: e2641529-934d-42fb-87c7-050291ed82ae
  spec:
    config:
      apiTimeout: 5m
      resourceGroup: <my resourcegroup name removed>
    provider: azure
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""```

**Comment by ywk253100** [comment]
@ross-worth We have added the support for CSI volumes for the Azure plugin in 1.8.
The RC1 build is available at this moment, you can try that with images `velero/velero:v1.8.0-rc.1` and `velero/velero-plugin-for-microsoft-azure:v1.4.0-rc.1`

**Comment by ross-worth** [comment]
Thanks I will give that a try and feed back.

**Comment by brysk** [comment]
Hello, I've been playing  around with new version of velero and velero-plugin on Azure.

```
velero/velero:v1.8.0-rc.1
velero/velero-plugin-for-microsoft-azure:v1.4.0-rc.1
```

I'm able to backup and restore LRS disks created with CSI driver but it's not possible to backup ZRS disks. I've created a new StorageClass for `StandardSSD_ZRS` disks:

```
k get sc managed-csi-zrs -o yaml

allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: managed-csi-zrs
parameters:
  skuname: StandardSSD_ZRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

and when I run velero backup it's unable to snapshot ZRS volume:

```
time="2022-01-25T16:55:34Z" level=info msg="1 errors encountered backup up item" backup=velero/newbackup5 logSource="pkg/backup/backup.go:412" name=nginx-deployment-ccb85775c-ws7r7
time="2022-01-25T16:55:34Z" level=error msg="Error backing up item" backup=velero/newbackup5 error="error getting volume info: rpc error: code = Unknown desc = disk has a nil SKU" logSource="pkg/backup/backup.go:416" name=nginx-deployment-ccb85775c-ws7r7
```

Is there a plan to support Azure ZRS disks?

**Comment by brysk** [comment]
Looks like [velero-plugin-for-microsoft-azure](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/v1.4.0-rc.1/velero-plugin-for-microsoft-azure/volume_snapshotter.go#L29) plugin uses some old Azure SDK version.

ZRS disk types are NOT present on the DiskStorageAccountTypes enum in [2019-07-01 SDK](https://github.com/Azure/azure-sdk-for-go/blob/main/services/compute/mgmt/2019-07-01/compute/enums.go#L326-340)

Newest [2021-11-01 SDK](https://github.com/Azure/azure-sdk-for-go/blob/main/services/compute/mgmt/2021-11-01/compute/enums.go#L384) contains ZRS types on the list. 

Can you update the plugin to use newer SDK?

**Comment by ywk253100** [comment]
@brysk For ZRS disks, let's use https://github.com/vmware-tanzu/velero/issues/4608 to track and seems the PR https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/131 fixes it.

I'm closing this one as the original CSI issue should already been fixed
