### ISSUE TITLE
After deleted a inprogressed restore, all created restore in hang state

### ISSUE THREAD

**Issue by omengye** [vmware-tanzu/velero#4556]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
1. velero create backup nginx-backup1 --include-namespaces testfile
NAME            STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
nginx-backup1   Completed   0        0          2022-01-20 11:01:10 +0800 CST   29d       default            <none>

2. velero create restore n11 --from-backup nginx-backup1
the n11 restore was inprogress, then delete this restore:  
velero delete restore n11

3. velero create restore n12 --from-backup nginx-backup1
NAME   BACKUP          STATUS   STARTED   COMPLETED   ERRORS   WARNINGS   CREATED                         SELECTOR
n12    nginx-backup1   New      <nil>     <nil>       0        0          2022-01-20 13:14:49 +0800 CST   <none>
the status of n12 restore was "New" in hours

**What did you expect to happen:**
the status of n12 restore is "inprogress"

**The following information will help us better understand what's going on**:

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
https://gist.github.com/omengye/b4285c07dd89eab2f15521d7eed9e698

- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
Name:         n12
Namespace:    velero
Labels:       <none>
Annotations:  <none>
Phase:  
Started:    <n/a>
Completed:  <n/a>
Backup:  nginx-backup1
Namespaces:
  Included:  all namespaces found in the backup
  Excluded:  <none>
Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto
Namespace mappings:  <none>
Label selector:  <none>
Restore PVs:  auto

- `velero restore logs <restorename>`
Logs for restore "n12" are not available until it's finished processing. Please wait until the restore has a phase of Completed or Failed and try again.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
Version: v1.7.1

- Velero features (use `velero client config get features`): 
features: <NOT SET>

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
v1.20.2
 
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
@omengye sorry, The log you provided is messy, could you please output the logs once again?

**Comment by omengye** [comment]
@qiuming-best Sorry, i edited output logs to https://gist.github.com/omengye/b4285c07dd89eab2f15521d7eed9e698. thx

**Comment by ywk253100** [comment]
Velero doesn't support canceling an in-progress restore at this moment which means deleting the restore cannot cancel the restoring process. Related issue https://github.com/vmware-tanzu/velero/issues/2098

And Velero handles restores in sequence, so if the last restore doesn't complete, Velero will not pick up the one new.

So your newly created restore is in `New` status because the last one doesn't completed yet.
