### ISSUE TITLE
Clarify how the status of a BSL is updated.

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#4569]
We have user reporting that after updating the credential of a BSL the status is not reflected immediately.

We need to double check the frequency of the update.

**Comment by blackpiglet** [comment]
I opened another issue about this topic. #4463
Maybe we should update the BSL controller logic to run periodically to avoid it.

**Comment by reasonerjt** [comment]
Thanks @blackpiglet 
Could you also check the frequency of updating BSL status?

**Comment by blackpiglet** [comment]
The cycle of BSL refresh during test is 60s, but this is not stable. Sometime it will be shorter, and occasionally it will longer. 

There is no strict timer setting for the frequency. I think this is the controller-time's rate limit queue's limitation. 
We can see from this line:
https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/backup_storage_location_controller.go#L137

After reconcile, the request is added into the loop immediately, so 60 second is the rate limit queue's limitation. 

For BSL case, the cron job way may be better.

**Comment by a-mccarthy** [comment]
@blackpiglet is there any next steps for this issue? reading from the perspective of docs improvements, i dont think there is anything to add right now. Is there more work to be done for this issue? thanks!

**Comment by blackpiglet** [comment]
@a-mccarthy 
Yes, a corner stone modification is made in this PR: https://github.com/vmware-tanzu/velero/pull/4748
When this PR is merged, I can move on to update BSL controller accordingly.
