### ISSUE TITLE
Incorrect API endpoint used when using Azure Government Cloud.

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/velero#4570]
The following was originally posted in https://github.com/vmware-tanzu/velero/issues/3508#issuecomment-787988055

The Azure plugin documentation should be reviewed to check if additional variables need to be set when using Azure Government Cloud. This may be a duplicate of #4299, but the errors seem to be different so will need investigation.

_Originally posted by @theok-nice in https://github.com/vmware-tanzu/velero/issues/3508#issuecomment-787988055_

I tested the new plugin version (v1.1.2) on a AzureUsGovenmentCloud region and get the following

i) Created velero credentials:
cat << EOF > ./credentials-velero
AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
AZURE_CLOUD_NAME=AzureUSGovernmentCloud
EOF

ii)Installed Velero using the below command:
velero install
--provider azure
--plugins velero/velero-plugin-for-microsoft-azure:v1.1.2
--bucket $BLOB_CONTAINER
--secret-file ./credentials-velero
--backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID[,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID]
--snapshot-location-config apiTimeout=<YOUR_TIMEOUT>[,resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID]

iii) Added the below label to velero deployment:
labels:
aadpodidbinding:${IdentityName}
component: velero

```
time="2021-03-01T13:47:00Z" level=info msg="Checking for existing backup locations ready to be verified; there needs to be at least 1 backup location available" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:58"
time="2021-03-01T13:47:01Z" level=error msg="Error getting a backup store" backupstoragelocation=default controller=backupstoragelocation error="rpc error: code = Unknown desc = storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code=\"InvalidAuthenticationTokenAudience\" Message=\"The access token has been obtained for wrong audience or resource 'https://management.azure.com/'. It should exactly match with one of the allowed audiences 'https://management.core.usgovcloudapi.net/','https://management.core.usgovcloudapi.net','https://management.usgovcloudapi.net/','https://management.usgovcloudapi.net'.\"" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:213" error.function=main.getStorageAccountKey logSource="pkg/controller/backupstoragelocation_controller.go:87"
time="2021-03-01T13:47:01Z" level=info msg="No backup locations were ready to be verified" controller=backupstoragelocation logSource="pkg/controller/backupstoragelocation_controller.go:120"
time="2021-03-01T13:47:01Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code=\"InvalidAuthenticationTokenAudience\" Message=\"The access token has been obtained for wrong audience or resource 'https://management.azure.com/'. It should exactly match with one of the allowed audiences 'https://management.core.usgovcloudapi.net/','https://management.core.usgovcloudapi.net','https://management.usgovcloudapi.net/','https://management.usgovcloudapi.net'.\"" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:213" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:168" 
```

I am not sure if there is bug or there is something more missing from the README for the plugin.

**Comment by ywk253100** [comment]
Should already be fixed in the latest release
