### ISSUE TITLE
Docs: clarify that Velero is non-destructive during restore

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/velero#4571]
My understanding is that Velero is non-destructive during a restore.  But, I don't believe that it is called out anywhere in the docs. I would suggest we add something like this to the [restore reference doc](https://velero.io/docs/v1.8/restore-reference/):

During a restore, Velero is non-destructive. That means that Velero will never overwrite a pre-existing resource which has the same name as a resource in the backup it is restoring. Similarly, if a persistent volume exists, Velero will not overwrite the data in it. This behaviour is by design, so that users don't have to worry about accidentally deleting state by overwriting it using Velero.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by eleanor-millman** [comment]
@zubron Can you please review my suggested text and alter it as appropriate to make sure it is correct? Thanks!

**Comment by zubron** [comment]
Looks good, @eleanor-millman! I have a slight suggestion marked in bold below (mostly to highlight that we don't only look at the name when deciding to restore).

> During a restore, Velero is non-destructive. That means that Velero will never overwrite **or replace pre-existing resources with resources from a backup it is restoring**. Similarly, if a persistent volume exists, Velero will not overwrite the data in it. This behaviour is by design, so that users don't have to worry about accidentally deleting state by overwriting it using Velero.

**Comment by sig-abyreddy** [comment]
Hi @eleanor-millman @zubron,

 Is there a way we could control this behavior through flags? We have a use case to replace the existing resources during  the restore process.

**Comment by eleanor-millman** [comment]
@sig-abyreddy I don't believe we do. We really don't want to accidentally delete something using Velero. To get confirmation from a Velero engineer, please open a separate support issue here in Github or try asking on #velero-users channel on the k8s slack. Thanks!

**Comment by yanji09** [comment]
Close it as this is documented in PR #4928.
