### ISSUE TITLE
domain velero.io is expired

### ISSUE THREAD

**Issue by paragor** [vmware-tanzu/velero#4579]
```
curl http://velero.io/ -i

HTTP/1.1 302 Found
Location: http://domain-registrar.storage.googleapis.com/expired.html?velero.io
Date: Wed, 26 Jan 2022 02:47:23 GMT
Content-Type: text/html; charset=UTF-8
Server: ghs
Content-Length: 266
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://domain-registrar.storage.googleapis.com/expired.html?velero.io">here</A>.
</BODY></HTML>
```

**Comment by ywk253100** [comment]
Thanks for reporting. We have noted the IT guys to fix it

**Comment by kferrone** [comment]
was about to report that velero.io is down

**Comment by kaovilai** [comment]
Try https://velero.tig.pw/ meanwhile.

**Comment by kaovilai** [comment]
behind cloudflare so should be DDoS proof

**Comment by kaovilai** [comment]
Official alternate domain name is at https://velero.netlify.app/ but the fixed paths to velero.io won't work.

**Comment by jonasrosland** [comment]
ETA for https://velero.io: Tomorrow morning it should be reachable by everyone, but you can try already right now, as DNS seems to be propagating quite quickly!

**Comment by reasonerjt** [comment]
Closing this issue as the domain is back, thanks @jonasrosland
