### ISSUE TITLE
Document that v1beta1 CRDs will need to be upgraded if restoring on a 1.22+ cluster

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/velero#4592]
The need for this documentation was originally highlighted in #4080.

_Originally posted by @zubron in https://github.com/vmware-tanzu/velero/issues/4080#issuecomment-1024623589_

Velero has a BackupItemAction [`RemapCRDVersion`](https://github.com/vmware-tanzu/velero/blob/b40bbda2d62af2f35d1406b9af4d387d4b396839/pkg/backup/remap_crd_version_action.go#L37-L42) that attempts to determine if a v1 CRD should be backed up using the v1beta1 API (for example, if it was upgraded by the API server). In this case, Velero will use the v1beta1 client to fetch the CRD to store in the backup. If restoring this backup on a 1.22+ cluster, these CRDs will no longer be valid as the v1beta1 API has been removed, and the `preserveUnknownFields` is invalid.

The docs should be updated to include this as a known limitation. To ensure that CRDs are correctly backed up and restored, they should be upgraded to use the v1 APIs prior to backup, or the CRDs can be amended after backup to remove the use of the invalid `preserveUnknownFields` field.

**Comment by mblaschke** [comment]
There are CRDs which are using this feature so it's not a solution.
