### ISSUE TITLE
Velero.io is down

### ISSUE THREAD

**Issue by TLmaK0** [vmware-tanzu/velero#4606]
**What steps did you take and what happened:**
Open browser url 'https://velero.io'

**What did you expect to happen:**

Show velero.io site and documentation

**Anything else you would like to add:**
![image](https://user-images.githubusercontent.com/399935/151758404-3fb24f7b-9c00-41a6-bbbb-7f66a956a7dc.png)

**Comment by kferrone** [comment]
duplicate of this too: https://github.com/vmware-tanzu/velero/issues/4579

**Comment by TLmaK0** [comment]
@kferrone :+1:
