### ISSUE TITLE
Support for zone-redundant storage (ZRS) managed disks

### ISSUE THREAD

**Issue by brysk** [vmware-tanzu/velero#4608]
**Describe the problem/challenge you have**
Velero is currently unable to backup and restore Azure Zone Redundant Disks introduced at March 02, 2021: [Zone Redundant Storage](https://azure.microsoft.com/en-us/updates/zone-redundant-storage-zrs-option-for-azure-managed-disks-in-limited-preview/)

When it tries to backup ZRS volume the following error is thrown:

```
time="2022-01-25T16:55:34Z" level=info msg="1 errors encountered backup up item" backup=velero/newbackup5 logSource="pkg/backup/backup.go:412" name=nginx-deployment-ccb85775c-ws7r7
time="2022-01-25T16:55:34Z" level=error msg="Error backing up item" backup=velero/newbackup5 error="error getting volume info: rpc error: code = Unknown desc = disk has a nil SKU" logSource="pkg/backup/backup.go:416" name=nginx-deployment-ccb85775c-ws7r7
```

Looks like [velero-plugin-for-microsoft-azure](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/v1.4.0-rc.1/velero-plugin-for-microsoft-azure/volume_snapshotter.go#L29) plugin uses some old Azure SDK version.

ZRS disk types are NOT present on the DiskStorageAccountTypes enum in [2019-07-01 SDK](https://github.com/Azure/azure-sdk-for-go/blob/main/services/compute/mgmt/2019-07-01/compute/enums.go#L326-340)

Newest [2021-11-01 SDK](https://github.com/Azure/azure-sdk-for-go/blob/main/services/compute/mgmt/2021-11-01/compute/enums.go#L384) contains ZRS types on the list. 

Possibly easy win to add support for ZRS disks?

**Describe the solution you'd like**
it would be great if velero would be able to snapshot ZRS disks and be able to restore them

**Environment:**

I tried the lastest:

```
velero/velero:v1.8.0-rc.1
velero/velero-plugin-for-microsoft-azure:v1.4.0-rc.1
```
in AKS 1.21.7

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
Should be fixed by https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/131
