### ISSUE TITLE
Domain velero.io is expired

### ISSUE THREAD

**Issue by Keyruu** [vmware-tanzu/velero#4615]
The domain velero.io is expired. I can't seem to read the documentation.

**Comment by murech** [comment]
This is a known issue. Seems to be a duplicate issue. See #4579. Website can be temporary reached here: https://velero.netlify.app/

**Comment by reasonerjt** [comment]
Hi the domain `velero.io` is back.

kudos to @jonasrosland 
I'm closing this issue.
