### ISSUE TITLE
Velero evaluates and processes annotation 'backup.velero.io/backup-volumes' even when --use-restic option is not specified when Velero is installed.

### ISSUE THREAD

**Issue by lautenbde** [vmware-tanzu/velero#4616]
**What steps did you take and what happened:**

Installed Velero without option --use-restic.
Created backup of a namespace with pods being annotated with "backup.velero.io/backup-volumes"
Backup is failing after 4h with timeout: 

"timed out waiting for all PodVolumeBackups to complete" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:172" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:455" name=postgresql-8575b69bf5-czsll"

Note: The backup is of a 3rd party components that comes with Velero annotations out of the box. Removing them is not an option.

**What did you expect to happen:**

Restic related annotations are ignored as restic is not enabled at all (--use-restic is not set at install time).

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

I am sorry, I do not have logs at hand for the moment (customer env).

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Seems there is a related issue open for a while: https://github.com/vmware-tanzu/velero/issues/957

**Environment:**

- Velero version (use `velero version`): v1.7.0 (OADP 0.5.0)
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): OCP 4.8
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
I'm not sure if ignoring is the right thing to do for your case, because your component is from 3rd party and it has the annotation, that may imply the to backup the component the restic MUST be enabled.  To fail early may be better?

Another decision to make is how to detect whether restic is installed.  The flag `--use-restic` is only tracked during installation, adding an env var may help velero server to know if restic is installed but it may increase the possibility for inconsistency.

**Comment by lautenbde** [comment]
@reasonerjt @qiuming-best Similar to the "snapshotVolumes" flag in the Velero schedule CRD maybe this or a similar flag could be added to the Backup CRD . In combination with respecting the flag also for restic based volume backups (see #957) it could do the trick.

**Comment by Lyndon-Li** [comment]
This has been fixed by #5319.
