### ISSUE TITLE
Velero does not show all backups

### ISSUE THREAD

**Issue by ehedei206** [vmware-tanzu/velero#4625]
Hi,

All daily backups are in the s3 bucket. Velero shows random backups every time I run the command in the CLI:

```
LM-Z17DC3E1JGH6:$ kubectl get backups.velero.io -n velero
NAME                                       AGE
velero-dailyclusterbackup-20220209005436   3h17m

LM-Z17DC3E1JGH6:$ kubectl get backups.velero.io -n velero
NAME                                       AGE
velero-dailyclusterbackup-20220205000044   6s
velero-dailyclusterbackup-20220206000045   3s
velero-dailyclusterbackup-20220207000046   1s
velero-dailyclusterbackup-20220209005436   3h18m

LM-Z17DC3E1JGH6:$ kubectl get backups.velero.io -n velero
NAME                                       AGE
velero-dailyclusterbackup-20220201000050   4s
velero-dailyclusterbackup-20220203000051   2s
velero-dailyclusterbackup-20220209005436   3h19m
```

This is running the same command seconds apart. It should pickup at least 13 backups. It picks up a random number every time.

Do you know any idea why the results are inconsistent? 

Thanks

**Comment by ehedei206** [comment]
Thanks for replying @blackpiglet . Yes, they are created by schedule. How can I check if they have owner reference and how could I remove that reference? Since we might need to delete schedules and update them to fit our needs. Thanks!

**Comment by blackpiglet** [comment]
Please reference this issue. 
https://github.com/vmware-tanzu/velero/issues/4456#issuecomment-1011726577

In this issue, the problem is caused by helm chart setting. 
If your setup is not by helm chart, you can find the ownerReference field in Backup yaml by kubectl command to check whether owner reference is set.

**Comment by ehedei206** [comment]
Cool, thanks! It was set to True, I just set it to False and will monitor to see if it keeps happening.

Thanks you

**Comment by ehedei206** [comment]
This is all working now. THank you. I will close this issue.
