### ISSUE TITLE
Restore is not happening successfully for Persistent Volume Claim/ Persistent Volume

### ISSUE THREAD

**Issue by shravankumar88** [vmware-tanzu/velero#4640]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Problem Statement: Jenkins Backup 
1.	Created a namespace with Jenkins and Create a Storage Class, Persistent Volume and Persistent Volume Claim in Jenkins Namespace
a.	kubectl create ns Jenkins
c.	Kubectl apply -f Jenkins-deployment.yaml
d.	Kubectl apply -f Jenkins-service.yaml
2.	Setup a Jenkins in the same namespace, install some plugins, create test credentials, and test the project
3.	Using Velero create a backup 
a.	./velero backup create jenkins20 --snapshot-volumes --include-cluster-resources --include-namespaces jenkins --storage-location azure --wait
4.	Delete the namespace
a.	Kubectl delete ns jenkins
5.	Restore from backup
a.	./velero restore create --from-backup jenkins20 --restore-volumes --include-cluster-resources --include-namespaces jenkins
**What did you expect to happen:**
After restoring Jenkins is restoring, but plugins, credentials and projects are not getting restored. 
**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 
 
_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
./velero version
Client:
        Version: v1.7.1
        Git commit: 4729274d07eae7e788233d5c995d7f45f40c9c61

Server:
        Version: v1.7.1

- Velero features (use `velero client config get features`): 
./velero client config get features
features: <NOT SET>
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"64f59d5ed82b0e695c8c8e8df54854c0f736bc55", GitTreeState:"clean", BuildDate:"2022-01-30T02:57:07Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`):
PRETTY_NAME="Common Base Linux Delridge (quinault)"
NAME="Common Base Linux Delridge"
VERSION_ID="10"
VERSION="10 (quinault)"
VERSION_CODENAME=quinault
ID=cbld
ID_LIKE=debian
HOME_URL="https://aka.ms/cbld"
SUPPORT_URL="https://aka.ms/cbld"
BUG_REPORT_URL="https://aka.ms/cbld"

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
@shravankumar88 I'm not quite sure how you install the Jenkins plugin, credential, and projects, these should be some kind of Kubernetes objects in the Jenkins namespace
