### ISSUE TITLE
Document that Velero works on dual stack

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/velero#4642]
Velero has been tested on IPv4, IPv6, and dual stack. Can we please put that in the docs.

**Comment by a-mccarthy** [comment]
@eleanor-millman do you think its enough to add this as a note to the compatibility matrix, https://github.com/vmware-tanzu/velero#velero-compatibility-matrix? Did you have any page in mind for this change? I think that makes sense as a starting place. I feel like there are a few issues to continue making improvements to our matrix/support statements

**Comment by eleanor-millman** [comment]
@a-mccarthy Fine with me! I don't have a good sense yet of where networking folks might be looking for this info. So let's just put it there and we can move it if folks want it but can't find it.

**Comment by a-mccarthy** [comment]
@eleanor-millman is there a specific Velero version in which this was tested? Do you know if we test this every release, or was it done with a specific release? thanks!

**Comment by eleanor-millman** [comment]
I think @reasonerjt did the testing, so he should be able to answer that. cc @yanji09 @danfengliu who also might have context.

**Comment by yanji09** [comment]
@a-mccarthy It was tested when releasing v1.8.0.

**Comment by a-mccarthy** [comment]
closed by https://github.com/vmware-tanzu/velero/pull/4906
