### ISSUE TITLE
Consistent build process for plugins

### ISSUE THREAD

**Issue by vchrisb** [vmware-tanzu/velero#4647]
**Describe the problem/challenge you have**
The gcp, aws, azure and csi plugins do not all produce multi arch images and use different build workflows, though plugin are very similar in their structure.

**Describe the solution you'd like**
A consistent container image build process and similar Makefile/scripts.

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by vchrisb** [comment]
The CSI plugin is still using go 1.13.
Once updated also to 1.17, the multi arch build from the other plugins could be ported.

**Comment by vchrisb** [comment]
The gcp and aws plugin don't have a changelog target in the Makefile and the `changelog.sh` script is not present.
The csi, azure and main velero on the otherhand do have both.
All of the plugins do have a folder called changelogs.

With the plugins being so similar, IMHO the Makefile and workflows should be as similar as possible.

May I suggest adding the changelog target and script also to the gcp and aws repo?
I can update the open PR for aws plugin and create a new PR for the gcp plugin.

**Comment by reasonerjt** [comment]
@vchrisb Please go ahead.

The maintenance of CSI plugin was paused, we are going to pick it up in the timeframe of v1.9, so I suggest we track the effort separately.

I agree the process for different plugins should be consistent.
