### ISSUE TITLE
Image scan has detect several vulnerabilites

### ISSUE THREAD

**Issue by albertschwarzkopf** [vmware-tanzu/velero#4683]
Trivy image scanner has detect several vulnerabilites:

`trivy image velero/velero:v1.7.1                
2022-02-21T13:02:44.759+0100	INFO	Detected OS: debian
2022-02-21T13:02:44.760+0100	INFO	Detecting Debian vulnerabilities...
2022-02-21T13:02:44.763+0100	INFO	Number of language-specific files: 2
2022-02-21T13:02:44.763+0100	INFO	Detecting gobinary vulnerabilities...

velero/velero:v1.7.1 (debian 10.10)
Total: 29 (UNKNOWN: 0, LOW: 15, MEDIUM: 6, HIGH: 4, CRITICAL: 4)`

[velero.txt](https://github.com/vmware-tanzu/helm-charts/files/8109033/velero.txt)

Could you fix the "CRITICAL" and "HIGH" issues please?

**Environment:**
- helm chart version and app version: Chart-Version 2.27.3 and App-Version v1.7.1 
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from `/etc/os-release`): Bottlerocket

**Comment by ywk253100** [comment]
We'll fix some of the CVEs in v1.7.2, but not all of them will be fixed as some of them are introduced by the base image and restic binary
