### ISSUE TITLE
Backup and restore on Azure AKS across subscriptions

### ISSUE THREAD

**Issue by bryan292** [vmware-tanzu/velero#4688]
**Describe the problem/challenge you have**
We are trying to create a restore on Azure AKS using diferent azure subscrition thant the used for took the backup, we are worndering if this should be possible only using the Azure plugin, since so far we only have been able to do it using restic.

**Describe the solution you'd like**
Been able to restore across subscriptions on Azure only using the azure plugin, no need for restic

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.7.0
- Kubernetes version (use `kubectl version`): 1.21.2
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
Seems it's a dup of https://github.com/vmware-tanzu/velero/issues/4191
