### ISSUE TITLE
Is it possible to restore only a few pods at a time?

### ISSUE THREAD

**Issue by am3ience** [vmware-tanzu/velero#4699]
Hello,

I have a velero backup for my entire cluster but I only need to revert back a few pods in one of the namespaces. Is that possible? Or is the restore only capable of restoring everything?

**Comment by ywk253100** [comment]
There are some options to narrow down the candidates when doing the restore: `--include-namespaces`, `--include-resources`, `--selector`, you can check your pods whether they can be filtered by these options

**Comment by am3ience** [comment]
If I do a restore --include-namespaces <namespace> will velero restore every pod and pv/pvc? or just ones that are missing?

**Comment by ywk253100** [comment]
For the already existing resources, Velero will try to compare them with the restoring ones rather than overwriting them and will report warnings if they are different

**Comment by am3ience** [comment]
ah so I can just delete the problem deployments and velero will just restore the missing deployments/pods ?

**Comment by ywk253100** [comment]
It should be, but backup them first before doing this in case there are some unexpected cases if needed

**Comment by half-life666** [comment]
I think you can use label "velero.io/exclude-from-backup" to exclude any resource you want, e.g., by adding "velero.io/exclude-from-backup=true" to the resource.
