### ISSUE TITLE
Volume was empty so no snapshot was taken

### ISSUE THREAD

**Issue by nanmor** [vmware-tanzu/velero#4700]
Hi @skriss, I meet the same error, but our storage is not AWS, it is a NFS server which based on a ppc64le.
completionTimestamp: '2022-02-24T09:52:19Z'
message: volume was empty so no snapshot was taken
path: >-
/host_pods/1950f55b-1e43-48c8-b049-f8292ed4cb2d/volumes/kubernetes.io~nfs/pvc-e0075e9e-22ed-43dd-bb48-11ad24252f8f
phase: Completed
progress: {}
startTimestamp: '2022-02-24T09:52:18Z'
I checked the restic daemonset pod , it have this volume and not empty
sh-4.4# ls -lar
total 4
drwxrwxrwx. 3 nobody nobody 4096 Feb 24 08:42 pvc-e0075e9e-22ed-43dd-bb48-11ad24252f8f
drwxr-x---. 6 root root 121 Feb 24 09:26 ..
drwxr-x---. 3 root root 54 Feb 24 09:26 .

what can i do next? thanks a lot.

_Originally posted by @nanmor in https://github.com/vmware-tanzu/velero/issues/2007#issuecomment-1049751682_

**Comment by ywk253100** [comment]
Could you try the solution mentioned [here](https://github.com/vmware-tanzu/velero/issues/2007#issuecomment-551904487) that adds the similar mount option to the storage class?

**Comment by nanmor** [comment]
Thanks for your response, but this is come from that issue as I didn't received response in that issue you shared. Luckly, It was resolved by other ways.
