### ISSUE TITLE
Error to backup CRD azurepodidentityexceptions.aadpodidentity.k8s 

### ISSUE THREAD

**Issue by marcuspolus** [vmware-tanzu/velero#4701]
I have cluster kubertes AKS Azure with 1.22.6 release
I have Velero 1.8.0
And when I want backup namespace "kube-system" I have this error : 

velero time="2022-02-25T09:07:18Z" level=error msg="Error backing up item" backup=velero/bck-weu-ns-kube-system-region-weu error="error executing custom action (groupResource=customresourcedefinitions.apiextensions.k8s.io, namespace= ││ , name=azurepodidentityexceptions.aadpodidentity.k8s.io): rpc error: code = Unknown desc = error fetching v1beta1 version of azurepodidentityexceptions.aadpodidentity.k8s.io: the server could not find the requested resource" error.fi ││ le="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:314" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*itemBackupper).executeActions" logSource="pkg/backup/backup.go:416" name=azurepodidentityexcepti ││ ons.aadpodidentity.k8s.io

In 1.22.6 kuberntes version all API are in V1 and or Velero try to fetching this CRD with API in version v1beat1.
Can you help me ?
Thks
Marc

**Comment by marcuspolus** [comment]
velero looks like the CRD is in v1beta1 while it is indeed in V1

velero time="2022-02-25T13:20:27Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/test-kube-system cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:58" pluginName=velero                                    ││ velero time="2022-02-25T13:20:27Z" level=info msg="CustomResourceDefinition azurepodidentityexceptions.aadpodidentity.k8s.io appears to be v1beta1, fetching the v1beta version" CRD=azurepodidentityexceptions.aadpodidentity.k8s.io bac ││ kup=velero/test-kube-system cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:91" plugin=RemapCRDVersionAction pluginName=velero                                                                                              ││ velero time="2022-02-25T13:20:27Z" level=info msg="1 errors encountered backup up item" backup=velero/test-kube-system logSource="pkg/backup/backup.go:412" name=azurepodidentityexceptions.aadpodidentity.k8s.io                         ││ velero time="2022-02-25T13:20:27Z" level=error msg="Error backing up item" backup=velero/test-kube-system error="error executing custom action (groupResource=customresourcedefinitions.apiextensions.k8s.io, namespace=, name=azurepodid ││ entityexceptions.aadpodidentity.k8s.io): rpc error: code = Unknown desc = error fetching v1beta1 version of azurepodidentityexceptions.aadpodidentity.k8s.io: the server could not find the requested resource" error.file="/go/src/githu ││ b.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:314" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*itemBackupper).executeActions" logSource="pkg/backup/backup.go:416" name=azurepodidentityexceptions.aadpodidentit ││ y.k8s.io

**Comment by ywk253100** [comment]
Dup of https://github.com/vmware-tanzu/velero/issues/4080
