### ISSUE TITLE
pod volume backup failed: error getting volume directory name

### ISSUE THREAD

**Issue by bluezd** [vmware-tanzu/velero#4708]
**What steps did you take and what happened:**
I got the following error message while executing `velero backup create busybox-1 --include-namespaces busybox`:

![image](https://user-images.githubusercontent.com/977107/155967401-ee4c9425-9d14-4224-94bd-82bb1a6c0d50.png)

![image](https://user-images.githubusercontent.com/977107/155967576-6cd784cf-eecc-4c10-9322-6a22cee55301.png)

**Environment:**

- Velero version (use `velero version`):  1.8.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): v1.17.4
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): ubuntu 20.04

**Comment by reasonerjt** [comment]
@bluezd 
Looks like velero thinks the PV was provisioned via CSI but cannot find the CSI driver.  Did you deploy your workload and later remove the CSI driver?
Could you provide the debug bundle via `velero debug` so we have more context.

**Comment by bluezd** [comment]
no, I did not remove the CSI driver.
Actually I use nfs external provisioner to provision the persistence volume.

I am not able to generate the debug bundle since there was an error occurred while running the `velero debug`
And this issue seems do *not* exist in version `1.6.2`.

**Comment by reasonerjt** [comment]
@bluezd 
OK I saw you mention velero version is v1.8.0 in the original post...
Could you try to reproduce this issue using velero 1.7+? 
It's not official yet, but we only have bandwidth to support 2 minor releases, now that 1.8 is out, we'll support 1.7 and (more preferably) v1.8, and since v1.7 there is `velero debug`
