### ISSUE TITLE
Replace roadmap.md with a link to the wiki

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/velero#4711]
Please delete all text in roadmap.md and replace with the following text (and make "Velero wiki" linked text to the provided link).

Please go to the Velero wiki (link: https://github.com/vmware-tanzu/velero/wiki) to see our latest roadmap and archived roadmaps.

**Comment by jonasrosland** [comment]
@OrlinVasilev Wanna take this?

**Comment by jonasrosland** [comment]
We should have a single wiki page called roadmap, include the paragraphs in the ROADMAP.md there. Then create a new 1.8 roadmap wiki item for posterity, add the 1.8 content from ROADMAP.md in there. then from the new roadmap wiki page link to 1.8 and 1.9 after the introductory paragraphs.

**Comment by OrlinVasilev** [comment]
will do :)

**Comment by eleanor-millman** [comment]
@OrlinVasilev Is this still on your radar? Thanks!

**Comment by OrlinVasilev** [comment]
roadmap info moved here : https://github.com/vmware-tanzu/velero/wiki/Roadmap
