### ISSUE TITLE
Expired backup that fail to delete should be easy to select.

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#4728]
**Describe the problem/challenge you have**
Allow user to use label to filter failed garbage collected backups
~~Either as a new default behavior, or as a new feature flag, there should be an option for Velero to garbage collect TTL expired backups even if it failed validation for reasons such as invalid BSL.~~

Similar to https://github.com/vmware-tanzu/velero/issues/4483 but instead of ObjectStorageSync, it's the behavior of [garbage collection controller](https://github.com/vmware-tanzu/velero/blob/e69fac153ba60dc5129cdda51480a64fbf47b851/pkg/controller/gc_controller.go)

**Describe the solution you'd like**
Add label to backups when garbage collector errors out
~~New default behavior or new feature flag~~

**Anything else you would like to add:**
It would help with hanging failed validation Backups from "dirtying" the logs since we don't care if it failed validation if it expired anyway.

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
Making it a default may cause issues that the backup CR is removed but the actual data remained in the object storage, and the user will not know it from velero.  
Similarly, if this is exposed as a configuration, the user may set the configuration without fulling aware of the situation he/she may get into in the future.

Therefore, I hope we can control it based on the error type, i.e. we only force remove the backup when certain errors happen.

**Comment by kaovilai** [comment]
Makes sense.

The request I received was specifically around missing bsl error.

Maybe a list of ignoredErrors

**Comment by kaovilai** [comment]
Our internal discussion have another idea to resolve by labelling instead. Enable user to use labelselectors to delete expired backups.

Then it's user's action, not our code.

Maybe allow them to
```
kubectl get backup -l velero.io/deleteFailReason=velero.io/deleteFailReason="BSLNotFound" -oname | kubectl delete backup
```

**Comment by birsanv** [comment]
that would work for me https://github.com/vmware-tanzu/velero/issues/4728#issuecomment-1074413835

**Comment by kaovilai** [comment]
fixed with https://github.com/vmware-tanzu/velero/pull/4757
