### ISSUE TITLE
Latest version moved back to 1.7.2

### ISSUE THREAD

**Issue by georgettica** [vmware-tanzu/velero#4733]
**What steps did you take and what happened:**
I have automation in place to pull the latest version (similar to dependabot) and save it locally.

I noticed that the old value was 1.8.0 and the new is 1.7.2

Was this intentional?

**What did you expect to happen:**

That the version would always go up / there will be a recent GH issue explaining why this happened

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by georgettica** [comment]
See PR here
https://github.com/georgettica/ocm-container/pull/58#event-6214436537

**Comment by blackpiglet** [comment]
Not sure about the change. I checked on https://hub.docker.com/r/velero/velero/tags
The latest tag is pointed to v1.8.0.
![Velero latest tag](https://user-images.githubusercontent.com/59276555/157853734-4dcbc913-3c27-455c-8208-e5b4682d9796.png)
![Velero v1.8.0 tag](https://user-images.githubusercontent.com/59276555/157853757-b5cd2137-63c7-4d35-8946-c7a627e82cbf.png)

**Comment by georgettica** [comment]
But the GitHub releases shows the lastest is not 1.8.0
![Screenshot_20220311-125602~2](https://user-images.githubusercontent.com/11993626/157854870-2e342abe-56a7-4de4-94e6-5d2d731188d5.png)
![Screenshot_20220311-125611](https://user-images.githubusercontent.com/11993626/157854889-8204c4f6-43f0-4473-8d7c-4e8945029aa0.png)

**Comment by blackpiglet** [comment]
I think that's due to we just release v1.7.2 to fix some CVE issues.
We cannot set which one is the latest release. It seems auto-decided by which release has the most up-to-date tag in it.

**Comment by blackpiglet** [comment]
Close issue for now. 
If there is any update, feel free to reopen.

**Comment by georgettica** [comment]
Just letting people know that 1.8.1 is out and the issue is solved (for now)
