### ISSUE TITLE
RequestedRangeNotSatisfiable if server-side replication is enabled in MinIO bucket

### ISSUE THREAD

**Issue by snorwin** [vmware-tanzu/velero#4734]
Dear Velero community,
I have encountered a strange problem and need some hints on what else I could check to solve it.

**What steps did you take and what happened:**

In our setup, Velero has configured an S3 MinIO cluster (with 4 nodes) as the backup storage location. Everything works fine until we try to use a bucket in MinIO that has server-side (i.e. one-sided or two-sided) replication enabled:
```
time="2022-03-10T08:54:55Z" level=error msg="backup failed" controller=backup error="error checking if backup already exists in object storage: rpc error: code = Unknown desc = RequestedRangeNotSatisfiable: Requested Range Not Satisfiable\n\tstatus code: 416, request id: 16DAF91805E3EE53, host id: " error.file="/opt/app-root/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:584" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*backupController).runBackup" key=velero/example-9 logSource="pkg/controller/backup_controller.go:281"
```

Which requirements the S3 storage need to full fill in order to use it as a backup storage location?

**What did you expect to happen:**

Backups to MinIO cluster with  server-side replication enabled should be successful.

**The following information will help us better understand what's going on**:
```
Name:         example-9                                                    
Namespace:    velero                                                       
Labels:       velero.io/storage-location=default                           
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.21.6+bb8d50a      
              velero.io/source-cluster-k8s-major-version=1                 
              velero.io/source-cluster-k8s-minor-version=21                
                                                                           
Phase:  Failed (run `velero backup logs example-9` for more information)   
                                                                           
Errors:    0                                                               
Warnings:  0                                                               
                                                                           
Namespaces:                                                                
  Included:  default                                                       
  Excluded:  <none>                                                        
```

**Environment:**

- Velero version (use `velero version`): v1.6.3-konveyor
- Velero features (use `velero client config get features`):   `<NOT SET>`
- Kubernetes version (use `kubectl version`): v1.21.6+bb8d50a (OpenShift 4.8.28)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
The error is reported due to Velero fails to check whether the backup already exists in S3 compatible storage before Velero tries to create it. 
In my opinion, this is related to how MinIO is setup. 
Not very familiar with MinIO, and it seems many cases can cause the 416 error. I think you would need to take some effort to sort out which suits to your case.

The possibilities are:
* Permission error on MinIO setup: https://github.com/minio/minio/issues/13870
* MinIO proxy error
* Bucket not exists: https://github.com/minio/minio/issues/2117

**Comment by snorwin** [comment]
@blackpiglet thanks for checking, it seems to be an issue how MinIO handles a unexisting key in the `HeadObject` request when replication is enabled. Not sure if it should be fixed in [vmware-tanzu/velero-plugin-for-aws](https://github.com/vmware-tanzu/velero-plugin-for-aws) or [minio/minio](https://github.com/minio/minio).

**Comment by blackpiglet** [comment]
OK. In my opinion, this should be fixed in MinIO. Velero AWS plugin only handle the S3 compatible operation. Shouldn't know the detail of the actual S3 storage provider.

**Comment by snorwin** [comment]
Issue is fixed with https://github.com/minio/minio/issues/14531.
