### ISSUE TITLE
Velero1.8 backup failure Error: The provided subscription identifier xxxxxx-xxx-xxx is malformed or invalid

### ISSUE THREAD

**Issue by liuhename** [vmware-tanzu/velero#4737]
**What steps did you take and what happened:**

Backup PVs On AKS(China Azure Cloud) with velero 1.8.0 and plugin velero-plugin-for-microsoft-azure 1.4.0(https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure)

Error Message:
The provided subscription identifier '12345678-1234-1234-1234-123456789012' is malformed or invalid

My subscription is 12345678-1234-1234-1234-123456789012f. The last letter '**f'** is lostin  the error message

**Comment by liuhename** [comment]
time="2022-03-14T10:18:20Z" level=error msg="Error backing up item" backup=velero/test-20220314 error="error taking snapshot of volume: rpc error: code = Unknown desc = compute.SnapshotsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"InvalidSubscriptionId\" Message=\"The provided subscription identifier '12345678-1234-1234-1234-123456789012' is malformed or invalid.\"" logSource="pkg/backup/backup.go:416" name=alertmanager-asdfdaf-w9hd7

**Comment by qiuming-best** [comment]
@liuhename first, could you verify the subscriptionId configured in crd backupstoragelocations.velero.io, volumesnapshotlocations.velero.io is correct with your subscription? you can use the following command `kubectl get volumesnapshotlocations.velero.io -A -oyaml `,`kubectl get backupstoragelocations.velero.io -A -oyaml`
