### ISSUE TITLE
The volumesnapshotcontent is not removed for the synced backup

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#4760]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
1. Install velero v1.8 on GKE:
```
./velero install     --image velero/velero:v1.8.0     --features=EnableCSI     --provider gcp     --plugins velero/velero-plugin-for-csi:v0.2.0,velero/velero-plugin-for-gcp:v1.4.0     --bucket jt-velero     --secret-file ./credentials-velero-gcp
```
2. Backup some workload in a namespace that has PV provisioned by CSI driver (`pd.csi.storage.gke.io`):
```
./velero backup create kibishii-csi-bak --include-namespaces kibishii
``` 
3. On another cluster run the same command as step 1 to install velero.  A few mins after the installation finishes the backup `kibishii-csi-bak` will be synced and the volumesnapshotcontent are created on the new cluster.

4. On the new cluster delete the synced backup via command:
```
./velero backup delete kibishii-csi-bak 
```
5. After a while the backup is deleted but the volumesnapshotcontent remains.  

**What did you expect to happen:**
The backup is deleted as well as the volumesnapshotcontent.

**The following information will help us better understand what's going on**:

[bundle-2022-03-21-17-49-23.tar.gz](https://github.com/vmware-tanzu/velero/files/8321278/bundle-2022-03-21-17-49-23.tar.gz)

**Environment:**

- Velero version (use `velero version`): 1.8
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):1.22
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
After go through the bundle's information, only found information about backup synced into cluster, but there is no information of backup deletion. 

``` bash
grep -Rin "kibishii-csi-bak" *    
kubecapture/velero.io_v1/velero/backups-202203211749.9907.json:502:                "name": "kibishii-csi-bak",
kubecapture/core_v1/velero/velero-5b55994dcb-8v2z6/velero/velero.log:99:time="2022-03-21T08:56:20Z" level=info msg="Attempting to sync backup into cluster" backup=kibishii-csi-bak backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:212"
kubecapture/core_v1/velero/velero-5b55994dcb-8v2z6/velero/velero.log:100:time="2022-03-21T08:56:20Z" level=info msg="Successfully synced backup into cluster" backup=kibishii-csi-bak backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:242"
kubecapture/core_v1/velero/velero-5b55994dcb-8v2z6/velero/velero.log:101:time="2022-03-21T08:56:21Z" level=info msg="Syncing CSI volumesnapshotcontents in backup" backup=kibishii-csi-bak backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:286"
kubecapture/core_v1/velero/velero-5b55994dcb-8v2z6/velero/velero.log:102:time="2022-03-21T08:56:21Z" level=info msg="Syncing 5 CSI volumesnapshotcontents in backup" backup=kibishii-csi-bak backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:293"
kubecapture/core_v1/velero/velero-5b55994dcb-8v2z6/velero/velero.log:103:time="2022-03-21T08:56:21Z" level=info msg="Created CSI volumesnapshotcontent snapcontent-87283bef-85c9-4094-b5e4-bf75146f61e3" backup=kibishii-csi-bak backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:306"
kubecapture/core_v1/velero/velero-5b55994dcb-8v2z6/velero/velero.log:104:time="2022-03-21T08:56:21Z" level=info msg="Created CSI volumesnapshotcontent snapcontent-a582544f-6792-4003-bdb2-38933c15391e" backup=kibishii-csi-bak backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:306"
kubecapture/core_v1/velero/velero-5b55994dcb-8v2z6/velero/velero.log:105:time="2022-03-21T08:56:21Z" level=info msg="Created CSI volumesnapshotcontent snapcontent-24de5f44-9d8d-435e-a8e1-10db581e3667" backup=kibishii-csi-bak backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:306"
kubecapture/core_v1/velero/velero-5b55994dcb-8v2z6/velero/velero.log:106:time="2022-03-21T08:56:21Z" level=info msg="Created CSI volumesnapshotcontent snapcontent-6083998c-37f4-4262-8abe-d135cc2d0576" backup=kibishii-csi-bak backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:306"
kubecapture/core_v1/velero/velero-5b55994dcb-8v2z6/velero/velero.log:107:time="2022-03-21T08:56:21Z" level=info msg="Created CSI volumesnapshotcontent snapcontent-c6d2ef7c-7672-43e1-ba65-a6f2927ea01d" backup=kibishii-csi-bak backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:306"
```

**Comment by reasonerjt** [comment]
@blackpiglet  thanks for checking the log.

It seems it's due to the `finalizers`:
```
 k get volumesnapshotcontent snapcontent-07941b50-26f8-4aa9-9fbb-f8d8792e9d49 -o yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  creationTimestamp: "2022-03-24T10:50:54Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2022-03-24T10:57:41Z"
  finalizers:
  - snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection
 ......
```

The `deletionTimestamp` indicates the deletion API has been called already.  But according to 
https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/
The API returned 202, but the resource remains.  IMO similar to what's done to `deletionPolicy` we should clear the finalizers should be cleared.

**Comment by blackpiglet** [comment]
Remove finalizer should work, but this finalizer is supposed to be handled by external-snapshotter. In normal case, the external-snapshotter can handle it and remove the finalizer.

If not, there is some potential errors in the VolumeSnapshotContent that cause the controller cannot work expectedly.

**Comment by reasonerjt** [comment]
Seems there are several problems involved in this issue:

1. When the backup sync controller syncs the vsc to the target cluster, the field `VolumeHandle` is carried over and this confuses the ext-snapshot controller, thinking the snapshot should be created:
https://github.com/kubernetes-csi/external-snapshotter/blob/f3d345340e2796b8b74f5bd6ce820879755f3f24/pkg/sidecar-controller/snapshot_controller.go#L75
So we should make update the vsc to reset the `Source` field.
2. Even after the `Source` field is reset, there is still a problem b/c the vsclass may not exist on the target cluster, and the snapshot on the cloud provider will be left as orphaned, so we may consider to sync the vsclass also when syncing the backup.
3. After `1` and `2` are resolved, there may still be a problem: After the backup is deleted on the target cluster, the backup deletion action item will not be triggered on the source cluster and the vsc or vs resources on the source cluster will be left as orphaned.

The item 3 may be a less severe issue because the orphan will be just a record in the k8s cluster and doesn't involve resources on the cloud provider.  We'll handle that issue separately, perhaps by updating the `deleteOrphanedBackups` to delete the vs and vsc created by the backup.
