### ISSUE TITLE
setup pipeline where the csi plugin is enabled

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#4765]
We need to continuously verify the functionality of CSI plugin.

Let's set up a pipeline that has velero installed with CSI enabled, and make sure the test cases to backup and restore workload via snapshot pass.

We can start by Azure as the CSI is enabled by default, please make sure the storage class based based on CSI driver is used when provisioning the workload for testing.

Please check the [doc](https://velero.io/docs/v1.8/csi/) for installation and pre-requisites for snapshot via CSI plugin.

**Comment by danfengliu** [comment]
Close it as PR #4789 merged.
