### ISSUE TITLE
velero backup get result oscillating

### ISSUE THREAD

**Issue by danil-smirnov** [vmware-tanzu/velero#4775]
**What steps did you take and what happened:**

I've deployed the latest chart version into GCP cluster and configured relevant backupStorageLocation. The backup works so far.

When I do `velero backup get` or check `velero_backup_total` metric in the Grafana dashboard, I see oscillating results:

<img width="665" alt="Screenshot 2022-03-24 at 13 41 48" src="https://user-images.githubusercontent.com/27999539/159910308-42af253d-501f-48f8-8ec3-140d1853c314.png">

I.e. every run I see a different list of backups.

**What did you expect to happen:**

When I do `velero backup get` or check `velero_backup_total` metric in the Grafana dashboard, I see consistent results.

**Environment:**

- helm version (use `helm version`): `version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}`
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): `velero-2.29.1 and 1.8.1`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9-gke.1002", GitCommit:"f87f9d952767b966e72a4bd75afea25dea187bbf", GitTreeState:"clean", BuildDate:"2022-02-25T18:12:32Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: `GKE 1.21.9-gke.1002`
- Cloud provider or hardware configuration: `GCP`
- OS (e.g. from `/etc/os-release`):

**Comment by ywk253100** [comment]
@danil-smirnov Could you run `velero backup get` several times and check which backups cause the oscillating?

**Comment by ywk253100** [comment]
BTW, is it possible some backups are expired and garbage collected by Velero when you running the command?

**Comment by danil-smirnov** [comment]
@ywk253100 I'm getting different results every time I run `velero backup get`. I can not identify which of them cause the issue. I can not achieve stability with the command, as you can see on my Grafana chart - the number of backups always jumps up and down. It was this way even with only one daily backup scheduled. Now I have backups scheduled for every 4 hours with the same issue.

**Comment by danil-smirnov** [comment]
@ywk253100 Some of my backups are `PartiallyFailed` - can this be an issue?

**Comment by qiuming-best** [comment]
@danil-smirnov How do you config your grafana metrics query?

**Comment by danil-smirnov** [comment]
@qiuming-best It's just `velero_backup_total`. I see the same oscillating if I do `velero backup get` from the console.
