### ISSUE TITLE
GKE Backing up a dynamically provisioned disk fails. Disk not found

### ISSUE THREAD

**Issue by maartenjanvangool** [vmware-tanzu/velero#4790]
**What steps did you take and what happened:**
I set up a velero backup using the helm chart (v2.28.0) and the GCP plugin (v1.4.1) with a daily backup schedule.

We're making use of regional disks. From what we can tell, volumes that do have topology labels are being backed up, while volumes without them (which seems to be the new standard?) are not being backed up. My first thought was that it has something to do with wrong labeling of pv's, but that does not seem to be the case (see [here](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/950) for more details). 

I'm getting the following error (removed some names):

```
level=error msg="Error backing up item" backup=velero/<name>-velero-velerobackup-20220329230031 error="error getting volume info: rpc error: code = Unknown desc = googleapi: Error 404: The resource 'projects/<project-name>/zones/europe-west4-b/disks/pvc-b0664617-04b9-4db3-aad9-b694d73ec276' was not found, notFound" logSource="pkg/backup/backup.go:416" name=<name>
```

The interesting thing is that this disk _does_ exist in europe-west4-b.

**What did you expect to happen:**
I expect volumes to be backed up.

**The following information will help us better understand what's going on**:
I cannot really provide the full logs. Let me know if there is something specific I need to add.

**Environment:**
- Velero version (use `velero version`): Server: v1.8.0
- Velero features (use `velero client config get features`): gcp plugin 1.4.1
- Kubernetes version (use `kubectl version`): GKE 1.21.6-gke.1503
- Cloud provider or hardware configuration: GKE

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
@maartenjanvangool 
Without having the full log it would be hard to investigate. 
Could it be due to the permission mismatch?  I'm not sure how the API of google could behaves if you request a resource that you don't have access to.  If it's similar to github, the 404 may be due to lack of permission?

@blackpiglet Any insight?

**Comment by blackpiglet** [comment]
@maartenjanvangool 
Looks like there is some version mismatch for regional disk support fix.
Regional disk support is added in v1.8.1 Velero.

There is two part of fixes: 
https://github.com/vmware-tanzu/velero/releases/tag/v1.8.1
https://github.com/vmware-tanzu/velero-plugin-for-gcp/releases/tag/v1.4.1-rc.1

I think if you change Velero image tag from v1.8.0 to v1.8.1, the mismatch would be fixed.

But I am not sure whether this will fix your case. Let's try this first. If there is still some problem, could you please post StorageClass, PVC and PV's yaml here. Of course, velero's log and backup's log are preferred too, if that's possible.

**Comment by maartenjanvangool** [comment]
Well that's a neat coincidence. Seems that the upgrade to 1.8.1 fixes this issue. Now it will backup the pvc's!

Thanks for your responses.
