### ISSUE TITLE
"make update" failed with curl certificate during build-image 

### ISSUE THREAD

**Issue by phuongatemc** [vmware-tanzu/velero#4795]
I checked out velero:main and run "make update" and hit the error below.  It looks like the Makefile try to pull "velero/build-image:a3d196ee" and when it is not available, it will try to build the build-image docker image and failed.

I was able to get around this by modifying Makefile to set BUILDER_IMAGE_TAG = d9f8abc which is the latest velero/build-image tag on https://hub.docker.com/r/velero/build-image/tags  and I was able to build the "make update" successfully.  However, this image tag d9f8abc is 4 months old so it may not fit for development.  

# make update
make[1]: Entering directory '/home/phuong/work/velero'
Trying to pull build-image: velero/build-image:a3d196ee
docker pull -q velero/build-image:a3d196ee || make build-image
Error response from daemon: manifest for velero/build-image:a3d196ee not found: manifest unknown: manifest unknown
make[2]: Entering directory '/home/phuong/work/velero'
[+] Building 2.2s (9/21)
 => [internal] load build definition from Dockerfile                                                                                                                                0.0s
 => => transferring dockerfile: 3.00kB                                                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                                                     0.0s
 => [internal] load metadata for [docker.io/library/golang:1.17](http://docker.io/library/golang:1.17)                                                                                                                      0.6s
 => [ 1/18] FROM [docker.io/library/golang:1.17@sha256:dba09c285770f58d6685b25a0606d72420b0a7525a2338080807d138a258c671](http://docker.io/library/golang:1.17@sha256:dba09c285770f58d6685b25a0606d72420b0a7525a2338080807d138a258c671)                                                              0.0s
 => => resolve [docker.io/library/golang:1.17@sha256:dba09c285770f58d6685b25a0606d72420b0a7525a2338080807d138a258c671](http://docker.io/library/golang:1.17@sha256:dba09c285770f58d6685b25a0606d72420b0a7525a2338080807d138a258c671)                                                                0.0s
 => CACHED [ 2/18] RUN mkdir -p /go/src/k8s.io                                                                                                                                      0.0s
 => CACHED [ 3/18] WORKDIR /go/src/k8s.io                                                                                                                                           0.0s
 => CACHED [ 4/18] RUN git config --global advice.detachedHead false                                                                                                                0.0s
 => CACHED [ 5/18] RUN git clone -b v0.22.2 https://github.com/kubernetes/code-generator                                                                                            0.0s
 => ERROR [ 6/18] RUN curl -sSLo envtest-bins.tar.gz https://go.kubebuilder.io/test-tools/1.22.1/linux/amd64 &&     mkdir /usr/local/kubebuilder &&     tar -C /usr/local/kubebuil  1.4s
------
 > [ 6/18] RUN curl -sSLo envtest-bins.tar.gz https://go.kubebuilder.io/test-tools/1.22.1/linux/amd64 &&     mkdir /usr/local/kubebuilder &&     tar -C /usr/local/kubebuilder --strip-components=1 -zvxf envtest-bins.tar.gz:
#9 1.349 curl: (60) SSL certificate problem: self signed certificate in certificate chain
#9 1.349 More details here: https://curl.se/docs/sslcerts.html
#9 1.349
#9 1.349 curl failed to verify the legitimacy of the server and therefore could not
#9 1.349 establish a secure connection to it. To learn more about this situation and
#9 1.349 how to fix it, please visit the web page mentioned above.
------
error: failed to solve: executor failed running [/bin/sh -c curl -sSLo envtest-bins.tar.gz https://go.kubebuilder.io/test-tools/1.22.1/linux/amd64 &&     mkdir /usr/local/kubebuilder &&     tar -C /usr/local/kubebuilder --strip-components=1 -zvxf envtest-bins.tar.gz]: exit code: 60
Makefile:276: recipe for target 'build-image' failed
make[2]: *** [build-image] Error 1
make[2]: Leaving directory '/home/phuong/work/velero'
Makefile:255: recipe for target 'build-env' failed
make[1]: *** [build-env] Error 2
make[1]: Leaving directory '/home/phuong/work/velero'
Makefile:248: recipe for target 'update' failed
make: *** [update] Error 2

**Comment by reasonerjt** [comment]
@phuongatemc 
I tried to run `make build-image` on my dev and did not reproduce this issue.
```
.....
 => [ 4/18] RUN git config --global advice.detachedHead false                                                                                                                                  0.3s
 => [ 5/18] RUN git clone -b v0.22.2 https://github.com/kubernetes/code-generator                                                                                                             15.7s
 => [ 6/18] RUN curl -sSLo envtest-bins.tar.gz https://go.kubebuilder.io/test-tools/1.22.1/linux/amd64 &&     mkdir /usr/local/kubebuilder &&     tar -C /usr/local/kubebuilder --strip-comp  37.2s
 => [ 7/18] RUN wget --quiet https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.2.0/kubebuilder_linux_amd64 &&     mv kubebuilder_linux_amd64 /usr/local/kubebuilder/bin/ku  32.6s
 => [ 8/18] RUN go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.7.0 
.....
```                   
 
I noticed that the digest of the base image `golang:1.17` was different on my machine:

```
=> [ 1/18] FROM docker.io/library/golang:1.17@sha256:4559df075377e3dba19aa5786b69e6c9a4ef4ffc507332f22e88d5c2f1337eda                                                                       119.3s
 => => resolve docker.io/library/golang:1.17@sha256:4559df075377e3dba19aa5786b69e6c9a4ef4ffc507332f22e88d5c2f1337eda  
 ....          
```
Note that the dgiest  on my env  is `sha256:4559df075377e3dba19aa5786b69e6c9a4ef4ffc507332f22e88d5c2f1337eda`, while in the output you provided it was 
`sha256:dba09c285770f58d6685b25a0606d72420b0a7525a2338080807d138a258c671` it's possible in this base image it has a different trust store so the cert is not trusted when the `curl` command was issued.

If you  remove the base image and retry `make build-image`, things may work.

**Comment by ywk253100** [comment]
Could you try this https://stackoverflow.com/questions/54402673/how-to-fix-ssl-certificate-problem-self-signed-certificate-in-certificate-chai?

**Comment by phuongatemc** [comment]
I now can build velero main.    Close this one.
