### ISSUE TITLE
Memory of restic pod keeps on increasing

### ISSUE THREAD

**Issue by qiuming-best** [vmware-tanzu/velero#4814]
**What steps did you take and what happened:**

Testing on one self-build k8s cluster with 5k pods and volumes, using one script doing backup in a loop continuously, the restic pod's memory keeps on increasing constantly.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/8985337/162110492-67977f24-107a-4a98-a140-234a453953ae.png">

**What did you expect to happen:**
The usage of memory should be up and down in periods and fluctuate around one value instead of keeping on increasing. 

**Environment:**

- Velero version (use `velero version`): v1.8.1
- Kubernetes version (use `kubectl version`): v1.21.0

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
Below is another test that I've done, the restic memory is measured by the `container_memeory_working_set_bytes` metric.

I found that the memory is mainly affected by `container_memoery_cache`, which is because I was doing backup in a loop continuously,  restic would read files on nodes frequently, the operating system caches frequently accessed files, so the `container_memoery_cache` would keep on increasing, which affected `container_memeory_working_set_bytes`.

<img width="941" alt="image" src="https://user-images.githubusercontent.com/8985337/162654038-e509afe1-d70b-4613-889c-4c65a3c20954.png">

**Comment by Lyndon-Li** [comment]
Closing this issue as we are planning to deprecate Restic path, so we are not going to work on performance improvement for Restic path.
