### ISSUE TITLE
Add a structured output to velero backup describe --details

### ISSUE THREAD

**Issue by aslafy-z** [vmware-tanzu/velero#4816]
**Describe the problem/challenge you have**
I'd like to create some reports for Velero backups. Currently, I have to do a `velero backup describe --details` and parse the output to get all the informations I need.

**Describe the solution you'd like**
Add a `--output` arg to allow exporting this report as json or yaml.

**Environment:**

- Velero version (use `velero version`): 1.9.1

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by allenxu404** [comment]
I agree it's helpful to output the result with certain format. Considering the workload, I can add the option `--output json` to command `velero backup describe`first in v1.11.
