### ISSUE TITLE
The storage account access key doesn't work as expected in Azure plugin

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#4825]
A community user follows the guide [here](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#option-3-use-storage-account-access-key) to do the auth with the storage account access key but got failure. Need to double-check whether the doc is correct or not.

[Here](https://kubernetes.slack.com/archives/C6VCGP4MT/p1649087943700159) is the slack thread where the user reports this.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by jasmdk** [comment]
I struggled with this as well until I noticed that I was missing storageAccountKeyEnvVar=AZURE_STORAGE_ACCOUNT_ACCESS_KEY
See this: https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/backupstoragelocation.md
Adding that made it work for me

**Comment by ywk253100** [comment]
@jasmdk Thanks for pointing that out.

Actually, it is documented in the [installation guide](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#install-and-start-velero), but it's easy to be ignored

**Comment by ywk253100** [comment]
I'm closing this issue.
