### ISSUE TITLE
Velero with restic plugin shut down OpenShift cluster with API requests.

### ISSUE THREAD

**Issue by fedextm** [vmware-tanzu/velero#4834]
**What steps did you take and what happened:**

Schedule backup with velero and sometimes it's getting down Openshift cluster with API requests. And we need to disable velero and restic backup processes.  
OpenShift version - 4.8.27. We have a large OpenShift cluster installation with about 100+ nodes, 200 PVC's, more than 3500 pods. 

Velero version - 1.7.1

**What did you expect to happen:**
That's all working normal  without interrupting backup processes and no OpenShift cluster suffering from API requests.

**The following information will help us better understand what's going on**:

Similarly  Issue already have place, but was closed not fixed.
https://github.com/vmware-tanzu/velero/issues/2435#issue-599805462

**Comment by qiuming-best** [comment]
Recently, I've done a test with one self-build cluster, which backed up 5000+ PVC and Pods periodically, the k8s API request seems not affected by the backup

**Comment by shawn-hurley** [comment]
@fedextm what Plugins are you using? and could you post some logs from the backup and /or the backup controller. and/or can you send the velero deployment documentation?
