### ISSUE TITLE
Unable to connect to backup location defined in Azure China

### ISSUE THREAD

**Issue by matt-mi** [vmware-tanzu/velero#4837]
**What steps did you take and what happened:**

After Velero deployed to Azure China with helm chart (with `AZURE_CLOUD_NAME` specified as `AzureChinaCloud` in `credentials-velero`), I created a `BackupStorageLocation` object along with resource group name and storage account name, but I got error logs from velero pod as below

```
time="2022-04-18T07:44:07Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.chinacloudapi.cn/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/<RG-name>/providers/Microsoft.Storage/storageAccounts/<sta-name>/listKeys?%24expand=kerb&api-version=2019-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"AADSTS90002: Tenant 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.\\r\\nTrace ID: xxxxxxxx-9a9a-4062-aa45-649e8e918d00\\r\\nCorrelation ID: xxxxxxxx-45aa-4546-b1e9-a06031e28e69\\r\\nTimestamp: 2022-04-18 07:44:07Z\",\"error_codes\":[90002],\"timestamp\":\"2022-04-18 07:44:07Z\",\"trace_id\":\"xxxxxxxx-9a9a-4062-aa45-649e8e918d00\",\"correlation_id\":\"xxxxxxxx-45aa-4546-b1e9-a06031e28e69\",\"error_uri\":\"https://login.microsoftonline.com/error?code=90002\"} Endpoint https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/token?api-version=1.0" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:217" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:175"
```

From there I can see the login URI prefix is still pointing to Azure global instance rather than Azure China one, is there anything I missed during the setup?

**Environment:**

- Velero version (use `velero version`): v1.8.0
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): v1.22.6
- Kubernetes installer & version: AKS
- Cloud provider or hardware configuration: Azure China

**Comment by Lyndon-Li** [comment]
Looks like you have specified the wrong value for variable AZURE_CLOUD_NAME. Specify as AZURECHINACLOUD instead (all in upper case)

**Comment by matt-mi** [comment]
@Lyndon-Li Thank you for the reply. But to be honest according to step 3 of [Create Service Principle](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#create-service-principal) of azure plugin documentation it depicts the `AZURE_CLOUD_NAME` should be `AzureChinaCloud`. Anyway, let me give a try to see if that's the cure.

**Comment by Lyndon-Li** [comment]
@matt-mi I've also noticed this, I am checking on the doc, will get you back.

**Comment by matt-mi** [comment]
Sure thing, meanwhile I just tried to specify value of `AZURE_CLOUD_NAME` as `AZURECHINACLOUD` and got the same error. Look forward to hearing from you soon, cheers!

**Comment by Lyndon-Li** [comment]
Could you add another environment variable AZURE_ENVIRONMENT = AZURECHINACLOUD and then have a try?

**Comment by Lyndon-Li** [comment]
This looks like a duplicated issue with https://github.com/vmware-tanzu/velero/issues/4299 and https://github.com/vmware-tanzu/velero/issues/3440

**Comment by matt-mi** [comment]
Appreciate your prompt response! Now the error message disappeared after `AZURE_ENVIRONMENT=AZURECHINACLOUD` specified as env var. 

One last question is what's the default value of `AZURE_ENVIRONMENT` for Azure global instance? Since we might want to use one `credentials-velero` file for deployment both in Azure China and Azure global.

**Comment by Lyndon-Li** [comment]
For Azure global, you don't need to specify the variable, it switches to the default value automatically for Azure global

**Comment by matt-mi** [comment]
Thanks for helping on this, I'm closing the issue since it's resolved now.
