### ISSUE TITLE
Warning when no BackupStorageLocation is specified as default

### ISSUE THREAD

**Issue by phuongatemc** [vmware-tanzu/velero#4840]
In our backup workflow, we specify the BackupStorageLocation for each Backup so we don't specify the default BackupStorageLocation.  This causes Velero to put warning below regularly on the Velero log that causes confusion for our customer.  We would like to request an option to suppress this warning.

time="2022-04-18T16:57:16Z" level=warning msg="There is no existing backup storage location set as default. Please see `velero backup-location -h` for options." controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:173"
time="2022-04-18T16:57:16Z" level=warning msg="Unavailable backup storage locations detected: available/unavailable/unknown: 3/1/0, )" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:169"

We also see this error which may relate to the issue that we don't specify the default BackupStorageLocation.
time="2022-04-14T18:56:19Z" level=warning msg="There is no existing backup storage location set as default. Please see `velero backup-location -h` for options." controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:173"
time="2022-04-14T18:56:20Z" level=error msg="Error getting a backup store" backup-storage-location=plc-test-1-irv-11-63-r-294d4-ae3e99981554471d6af3f20dbf06f47b.stagings controller=backup-storage-location error="rpc error: code = Unknown desc = strconv.ParseBool: parsing \"\": invalid syntax" logSource="pkg/controller/backup_storage_location_controller.go:100"

**Comment by Lyndon-Li** [comment]
The cause for the warning log is clear, we will check it against the user case.

For the error log "Error getting a backup store", we don't see its relationship with the above warning log. From the code, the reconcile info collection which prints the warning log is at the last call of Backup Storage Location Controller's Reconciler, if the Reconciler fails to get one BSL, the info is not collected at all, so they are not for the same processing.
Therefore, please help to double check this error log, if it is indeed related with the warning log, please share us more information.

Thanks.

**Comment by reasonerjt** [comment]
This one can be ignored, it's probably due to plugin in DellEMC.:
```
time="2022-04-14T18:56:20Z" level=error msg="Error getting a backup store" backup-storage-location=plc-test-1-irv-11-63-r-294d4-ae3e99981554471d6af3f20dbf06f47b.stagings controller=backup-storage-location error="rpc error: code = Unknown desc = strconv.ParseBool: parsing "": invalid syntax"
```

**Comment by blackpiglet** [comment]
`time="2022-04-14T18:56:20Z" level=error msg="Error getting a backup store" backup-storage-location=plc-test-1-irv-11-63-r-294d4-ae3e99981554471d6af3f20dbf06f47b.stagings controller=backup-storage-location error="rpc error: code = Unknown desc = strconv.ParseBool: parsing "": invalid syntax"`
This log is the reason why there is unavailable BSL. That is related to specific Velero plugin object store init process. 

`time="2022-04-18T16:57:16Z" level=warning msg="Unavailable backup storage locations detected: available/unavailable/unknown: 3/1/0, )" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:169"`

**Comment by blackpiglet** [comment]
Default BSL is used for backup create request which doesn't specify the BSL, then the default BSL will be used, so warning will be logged if no default BSL is specified.

To suppress that warning, set a backup's `spec.default` to `true`, or set backup's `name` to `default`.
What do you think?

**Comment by phuongatemc** [comment]
I tested setting BSL spec.default to true and the warning messages gone.  I will close this bug for now.
