### ISSUE TITLE
Add `ExistingResourcePolicy` support to restore API

### ISSUE THREAD

**Issue by shubham-pampattiwar** [vmware-tanzu/velero#4842]
**Describe the problem/challenge you have**

Velero currently does not support any restore policy on kubernetes resources that are already present in-cluster. Velero skips over the restore of the resource if it already exists in the namespace/cluster irrespective of whether the resource present in the restore is the same or different from the one present on the cluster. It is desired that Velero gives the option to the user to decide whether or not the resource in backup should overwrite the one present in the cluster.

**Describe the solution you'd like**
It is desired to add the functionality to specify whether or not to overwrite the instance of resource in cluster with the one present in backup during the restore process. This can be achieved via introduction of `ExistingResourcePolicy` to restore API for Kubernetes resources.

**Anything else you would like to add:**
Related issues: https://github.com/vmware-tanzu/velero/issues/4066

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
Reopening as this PR is not merged:
https://github.com/vmware-tanzu/velero/pull/4628
