### ISSUE TITLE
Using External Standalone Minio Server for Remote Backup Storage location

### ISSUE THREAD

**Issue by sunibhaikc** [vmware-tanzu/velero#4845]
**What steps did you take and what happened:**
I have setup External Standalone Minio Server for Remote Backup Storage location and using this as "REMOTE" storage location for backup.
Installed the certificates of external MINIO and configured " Manage setup" for external Minio from Backup and Restore UI
Bucket is getting created in the External MINIO but the storage location name "default" status shows "UNAVAIBALE"

**What did you expect to happen:**
Backup to happen and remote storage location "default" to be in available state

DOES VELERO SUPPORT EXTERNAL STANDALONE MINIO OUTSIDE K8 CLUSTER?

**The following information will help us better understand what's going on**:

time="2022-04-19T07:21:03Z" level=info msg="Validating backup storage location" backup-storage-location=default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:114"
time="2022-04-19T07:21:03Z" level=info msg="Initializing restic repository" controller=restic-repo logSource="pkg/controller/restic_repository_controller.go:158" name=edison-core-default-zbqlm namespace=xxxxxxxx

time="2022-04-19T07:21:03Z" level=info msg**="Backup storage location is invalid, marking as unavailable**" backup-storage-location=default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:117"
time="2022-04-19T07:21:03Z" level=warning msg="Unavailable backup storage locations detected: available/unavailable/unknown: 1/1/0, **Backup storage location \"default\" is unavailable: rpc error: code = Unknown desc = SignatureDoesNotMatch:** The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 16E73B2F680CBFDE, host id: )" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:169"

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `time="2022-04-19T08:57:54Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 16E7407858903F60, host id: " error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:361" error.function="main.(*ObjectStore).ListCommonPrefixes" logSourcerror: http: unexpected EOF reading trailer

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v.1.8.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): Client - 1.23 server 1.21
- Kubernetes installer & version:  Client - 1.23 server 1.21
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Ubuntu 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
Are you using self-signed certificate to connect the Minio server? How did you specify the certificate to Velero?

**Comment by Lyndon-Li** [comment]
First of all, Velero support this case "EXTERNAL STANDALONE MINIO OUTSIDE K8 CLUSTER".
If there is a problem with connecting to Minio, it may relate to your certificate and how you specify the certificate to Velero. Please double check this or you can share more details about it.

**Comment by Lyndon-Li** [comment]
@sunibhaikc Is this problem solved? If not, please provide more information.

**Comment by Lyndon-Li** [comment]
Closing this stable issue, if more help is needed, please reopen it. Thanks.
