### ISSUE TITLE
Update the compatibility matrix in the readme.md for 1.9

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/velero#4846]
Update this compatibility matrix for 1.9: https://github.com/vmware-tanzu/velero

Need engineering to fill in which K8s versions will be supported in 1.9 (note that this is just what we think it will work with, NOT what is actually tested and NOT what we guarantee patches for - that is dealt with in this issue - https://github.com/vmware-tanzu/velero/issues/4285).

**Comment by eleanor-millman** [comment]
@yanji09 Can you see if an engineer can quickly answer this so that Abbie can then do the docs work? Thanks!

cc @a-mccarthy

**Comment by yanji09** [comment]
Currently the latest k8s version is 1.23 which we will testing? and k8s 1.24 is coming probably in May. Also we need to considerate what is the oldest version we verified in 1.9.
@danfengliu could you work with Abbie on this?

**Comment by danfengliu** [comment]
@yanji09 @a-mccarthy 

Currently the nightly pipeline covers these 3 Kubernetes version (v1.20.5, v1.21.2, v1.22.5) separately in  vSphere/AWS/Azure, and we will cover  Kubernetes v1.23 manually on Kind k8s cluster.

### vSphere
Kubernetes version: v1.20.5

### AWS
Kubernetes version: v1.21.2

### Azure
Kubernetes version: v1.22.5

**Comment by a-mccarthy** [comment]
@danfengliu thanks for this information! Just to make sure i understand, these are all the Kubernetes versions we test Velero 1.9 against, correct? 

Would it be useful to point folks to the Kubernetes changelog where they can see more information about a Kubernetes versions? https://github.com/kubernetes/kubernetes/tree/master/CHANGELOG

The Kubernetes versions listed in the Velero compatibility matrix are the versions we'd expect to work with the listed Velero version, but the versions listed above are what is actually tested/verified. 

If a user is interested in using a different version of Kubernetes with a given Velero version, we'd recommend that they perform their own testing before installing or upgrading their environment.

**Comment by yanji09** [comment]
@a-mccarthy yes, the k8s 1.20, 1.21, 1.22 are tested in nightly test environment. Later, plan to test with k8s 1.23 and 1.24 via Kind. So eventually 1.9 will be tested on these 5 k8s versions.
