### ISSUE TITLE
Capability to overwrite existing Kubernetes objects 

### ISSUE THREAD

**Issue by indrajithgihan** [vmware-tanzu/velero#4851]
**Describe the problem/challenge you have**

Currently If some resource already exists and differs from one in the backup, Velero will not overwrite it. Velero doesn't overwrite objects in-cluster if they already exist.

**Describe the solution you'd like**

Please provide Velero tool the capability to overwrite Kubernetes objects if they already exist

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):1.8.1
- Kubernetes version (use `kubectl version`):1.21.9
- Kubernetes installer & version: kubeadm 1.21.9
- Cloud provider or hardware configuration: On-prem and AKS
- OS (e.g. from `/etc/os-release`):Ubuntu 18.04.6 LTS / Redhat 7.9 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by Lyndon-Li** [comment]
This is the default behavior of Velero at present, it is to no resource is erroneously overwritten by Velero restore unless it guarantee the safety for sure.

This is like a Requirement for Velero. Could you provide us more details of why you want the behavior change? In which scenario do you think users will benefit the behavior change from?


Thanks.

**Comment by Lyndon-Li** [comment]
There is already an existing PR and issue for this requirement, https://github.com/vmware-tanzu/velero/issues/4842.
Please review it and check whether it meets your requirement.

**Comment by shubham-pampattiwar** [comment]
@indrajithgihan please refer the following:
- Issue link: https://github.com/vmware-tanzu/velero/issues/4842
- Design link: https://github.com/vmware-tanzu/velero/pull/4613
- Implementation link: https://github.com/vmware-tanzu/velero/pull/4628
Please review the above as @Lyndon-Li also mentioned and let us know if it solves your issue.

**Comment by reasonerjt** [comment]
Closing as this will be implemented in v1.9
