### ISSUE TITLE
 installOption terminationGracePeriodSeconds

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#4857]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
People with performance issues may want to fiddle with  customizable terminationGracePeriodSeconds of the Velero Deployment.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
velero CLI install flag `velero install --terminationGracePeriodSeconds=50`
Implement a new pkg/install/deployment.go/podTemplateOption

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by ywk253100** [comment]
Could you describe the requirement in more detail so that we can better understand it?

**Comment by kaovilai** [comment]
@ywk253100 added some more detail.
Does that help?

**Comment by ywk253100** [comment]
I mean to describe why users need this config? Is it used to make sure all in-progress backing up/restoring/other tasks complete before exising?

**Comment by kaovilai** [comment]
@birsanv wanted the ability to configure this for performance testing.

> Is it used to make sure all in-progress backing up/restoring/other tasks completed before exiting?

yes.

**Comment by kaovilai** [comment]
Could be achieved with cpu/mem bump generally but this is another option a user can play with.

**Comment by kaovilai** [comment]
Circling back on this, user was able to resolve issue via increasing CPU request limit so closing this for now.
