### ISSUE TITLE
--cacerts flag not working

### ISSUE THREAD

**Issue by hit3644** [vmware-tanzu/velero#4861]
**What steps did you take and what happened:**
velero get backups --cacert <path>

**What did you expect to happen:**
List all current backups, but I get the message Error: unknown flag: --cacert 

**Environment:**

- Velero version (use `velero version`):  1.8
- Velero features (use `velero client config get features`):  --cacert
- Kubernetes version (use `kubectl version`): 
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by ywk253100** [comment]
The `--cacert` is one flag for `velero install` command, not for `velero backup get`
