### ISSUE TITLE
Expand BSL multiple credentials support to VolumeSnapshotLocations

### ISSUE THREAD

**Issue by sseago** [vmware-tanzu/velero#4862]
**Describe the problem/challenge you have**
Originally the per-BSL credentials support was intended to be added to VolumeSnapshotLocations as well. Some initial work was already done for this but was reverted when the VSL work was de-scoped from a prior release (the AWS plugin work to support this remained in place, though). This issue is for going though with the enhancement.

While the need for multiple sets of credentials is not as obvious for VSLs, there's still a use case for it, especially for users who area already setting credentials on their BSLs. For those users, they may not be using the default credentials at all, as they've modified their workflow to set credentials on each BSL they create. This will allow them to follow the same approach with VSLs.

**Describe the solution you'd like**
VSLs should allow optional credentials in the same way as BSLs, with the default credentials being used when they're not specified.

**Anything else you would like to add:**
A PR to implement this will be submitted shortly.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
Another user case: https://github.com/vmware-tanzu/velero/issues/4115

**Comment by blackpiglet** [comment]
@sseago 
After this change, Looks like VSL could use different credential from BSL. 
Per my understanding, plugins also need to adopt this this change to make it work, right?
Currently, GCP plugin cannot work, if BSL doesn't use the default credential. Azure and AWS plugins share the credential from BSL.

**Comment by sseago** [comment]
@blackpiglet Yes, plugins need to be modified to look for the VSL credentials field like they already do for BSL credentials. The AWS plugin already has this support (this PR allows AWS to use non-default credentials for VSL). Azure will need the same change. I haven't looked at GCP recently, but from what you're saying, it sounds like GCP needs to be adapted for both BSL and VSL credentials.
