### ISSUE TITLE
Add more logging around PodVolumeRestores

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#4868]
**Describe the problem/challenge you have**
Currently debugging an issue where we don't see PodVolumeRestores in the cluster.

It would be extremely helpful to see in the logs where/when this function was returned and if there were any PVR created as a result.

https://github.com/vmware-tanzu/velero/blob/58a8371ca23b89b0b25301ec45acef16c5f40811/pkg/restic/restorer.go#L98

**Describe the solution you'd like**
More logging if volumesToRestore == 0
More logging if volumesToRestore != 0
More logging if there was PVR created or other errors

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
Appreciate it if you can submit a PR containing the enhancement

**Comment by kaovilai** [comment]
yes. Just noting the need here. Will PR if I ever got to it :)
