### ISSUE TITLE
Unable to run Velero install with azure blob

### ISSUE THREAD

**Issue by oldManLemon** [vmware-tanzu/velero#4871]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I am setting up a velero k8's instance using kind to test a restore in a completely separate environment. 

I have my cluster running as a kind cluster. 

I have installed Velero as per instructions on website. 

I have then added my azure configuration, as variables, then I run the following. 
```

velero install \
    --provider azure \
    --plugins velero/velero-plugin-for-microsoft-azure:v1.4.0 \
    --bucket $BLOB_CONTAINER \
    --secret-file /tmp/credentials-velero \
    --backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_NAME,storageAccountKeyEnvVar=AZURE_STORAGE_ACCOUNT_ACCESS_KEY,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID \
    --use-volume-snapshots=false
```

**What did you expect to happen:**

I expected Velero to install or at least make some progress. My results are practically no progress. 

My results are here as they do not include much. 

```
CustomResourceDefinition/backups.velero.io: attempting to create resource
An error occurred:

Error installing Velero. Use `kubectl logs deploy/velero -n velero` to check the deploy logs: Error creating resource CustomResourceDefinition/backups.velero.io: the server could not find the requested resource
```

I then run the suggested command for more information. 
```
 kubectl logs deploy/velero -n velero
Error from server (NotFound): deployments.apps "velero" not found

```

**The following information will help us better understand what's going on**:

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The blob already exists and has backups in there. I wish to test the restore elsewhere. 

**Environment:**

- Velero version (use `velero version`): Version: v1.5.1
        Git commit: 87d86a45a6ca66c6c942c7c7f08352e26809426c
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): v1.23.4
- Kubernetes installer & version: kind
- Cloud provider or hardware configuration:  azure for storage or vmware for machine
- OS (e.g. from `/etc/os-release`): Centos7

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
According to the log `Error creating resource CustomResourceDefinition/backups.velero.io: the server could not find the requested resource`, seems your cluster doesn't support CRD?

**Comment by oldManLemon** [comment]
Could be, I actually got it up and running with the helm chart. I assume the end result is the same, and there I got Custom Resources? Either way I will mark it as closed for myself.
