### ISSUE TITLE
Docker image velero/velero:v1.7.0 and newer doesn't run in GitLab CI due to removal of `sh` shell

### ISSUE THREAD

**Issue by Yggdrasil** [vmware-tanzu/velero#4892]
**What steps did you take and what happened:**
We tried to upgrade from Velero 1.6 to 1.8.1 because 1.6 is failing to back up our recently upgraded Kubernetes 1.22 cluster.

We deploy Velero via GitLab CI by running a job that uses the velero/velero:v1.8.1 Docker image to generate the manifests. This job runs `/velero install ... --dry-run -o yaml > velero.yaml` in that container with several other parameters to output the resulting manifest to a file. These manifests then get deployed to Kubernetes in the next job.

After bumping the image version in our CI job the jobs started failing. It turns out the newer Docker images (after v1.6) appear to have stripped the image, removing the shell. 1.6 still had `/usr/bin/sh` but all shells are missing from 1.7 and up.

This unfortunately makes the Docker image useless for GitLab CI. GitLab currently **requires** a shell in the image to run and simply can't execute binaries directly. See the open issue https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26501. Various attempts to work around this failed, such as overriding the job's `image:entrypoint`. According to the issue, without a built-in shell the Docker image simply can't be used in GitLab CI.

The [docs](https://docs.gitlab.com/runner/executors/docker.html#the-image-keyword) for GitLab CI's Docker executor mention

> The image you choose to run your build in via image directive must have a working shell in its operating system PATH. Supported shells are sh, bash, and pwsh ([since 13.9](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4021)) for Linux, and PowerShell for Windows. GitLab Runner cannot execute a command using the underlying OS system calls (such as exec).
https://docs.gitlab.com/runner/executors/docker.html#the-image-keyword

**What did you expect to happen:**
I expected the velero/velero:v1.8.1 Docker image to have a `sh` command present in its $PATH, so I can use the image in GitLab CI jobs to generate the Kubernetes manifests that will run Velero on our GKE clusters.

By reintroducing the `sh` shell command to the Docker image the image can be run in GitLab CI again.
**The following information will help us better understand what's going on**:
 
The log from a failed GitLab CI job:
```
Running with gitlab-runner 13.1.1 (6fbc7474)
  on gitlab-gce-runner 9XE3qzs8
Preparing the "docker+machine" executor 00:04
Using Docker executor with image velero/velero:v1.8.1 ...
Pulling docker image velero/velero:v1.8.1 ...
Using docker image sha256:09d72f495b29373ffbb366e030301f504f32644c75a4b2f2b5df4680149906cb for velero/velero:v1.8.1 ...
Preparing environment 00:00
Running on runner-9xe3qzs8-project-17733723-concurrent-0 via runner-9xe3qzs8-job-1651730401-e46f4eae...
Getting source from Git repository 00:01
Skipping Git repository setup
Skipping Git checkout
Skipping Git submodules setup
Downloading artifacts 00:01
Downloading artifacts for retrieve-secret-staging (2419065541)...
Downloading artifacts from coordinator... ok        id=2419065541 responseStatus=200 OK token=yTRc4sbN
Executing "step_script" stage of the job script 00:01
ERROR: Job failed (system failure): Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "sh": executable file not found in $PATH: unknown (docker.go:740:0s)
```

A section of our .gitlab-ci.yml file:
```
.generate-manifests:
    stage: generate
    image:
      name: velero/velero:v1.8.1
    variables:
        GIT_STRATEGY: none
        GCP_PROJECT_ID:
        CLUSTER:
        BUCKET:
    artifacts:
      paths:
        - ./velero.yaml
    script:
      - /velero install
        --provider gcp
        --plugins velero/velero-plugin-for-gcp:v1.4.1
        --bucket ${BUCKET}
        --secret-file ./cloud-credentials.json
        --backup-location-config serviceAccount=velero-backup-sa@${GCP_PROJECT_ID}.iam.gserviceaccount.com
        --use-restic
        [...snip...]
        --dry-run -o yaml
        > velero.yaml

generate-manifests-staging:
    extends: .generate-manifests
    stage: generate
    dependencies: [retrieve-secret-staging]
    variables:
        GCP_PROJECT_ID: ${GCP_STAGING_PROJECT_ID}
        CLUSTER: ${GCP_STAGING_CLUSTER_NAME}
        BUCKET: example-bucket-name
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: on_success
        - if: '$CI_COMMIT_BRANCH != "master"'
          when: on_success
        - when: never
```

**Anything else you would like to add:**
Perhaps using alpine as a base image instead of scratch will still keep the image relatively small while providing the base that GitLab requires.

**Environment:**

- Velero version (use `velero version`): 1.8.1
- Kubernetes version (use `kubectl version`): 1.22
- Kubernetes installer & version: GKE
- Cloud provider or hardware configuration: GCP

**Vote on this issue!**

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
This is working as design, we chose to use distroless as the base image to reduce potential CVEs

**Comment by Yggdrasil** [comment]
Ah, I see. Then I'll build my own Velero image for CI purposes.

Thanks for the info in any case.
