### ISSUE TITLE
Velero ability to support random string/suffix for backup resource

### ISSUE THREAD

**Issue by jprecuch** [vmware-tanzu/velero#4900]
**Describe the problem/challenge you have**
Currently when we want to create backup using yaml file we need to specify hardcoded name.
https://velero.io/docs/v1.8/api-types/backup/
However this might be a problem with multiple deployments of the same yaml, because the name can't be reused 

Would it be possible to add some option to automatically generate name/date sufix for the velero name if this function is enabled?

**Describe the solution you'd like**
Add some option to https://velero.io/docs/v1.8/api-types/backup/ to specify/enable suffix that will be on each apply random and allow us to deploy same yaml multiple times with always different suffix 
By default this option would be disabled (or make the suffix automatic for every backup)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by sseago** [comment]
You should be able to use `generateName` instead of `name` for a backup.

**Comment by jprecuch** [comment]
Thanks @sseago  that sounds a good way for this.
