### ISSUE TITLE
Jenkins volume backup stuck at 30%

### ISSUE THREAD

**Issue by DavidSanchezAlvarez** [vmware-tanzu/velero#4907]
**What steps did you take and what happened:**
I'm running an EKS cluster in AWS with a bunch of applications on it, and installed Velero to perform backups on an S3 bucket including volumes.
Velero was installed using a Helm Chart version 2.28.0, and installed Velero version v1.8.0

Velero is running with Restic enabled.
``` bash
$ k get all -n velero
NAME                          READY   STATUS    RESTARTS   AGE
pod/restic-7rrwz              1/1     Running   0          15d
pod/restic-hft9c              1/1     Running   0          2d1h
pod/restic-hp8f6              1/1     Running   0          25h
pod/restic-lt5nr              1/1     Running   2          2d1h
pod/velero-748bd5b5f8-m6j8d   1/1     Running   0          2d1h

NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/velero   ClusterIP   172.20.74.182   <none>        8085/TCP   138d

NAME                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/restic   4         4         4       4            4           <none>          138d

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/velero   1/1     1            1           138d

NAME                                DESIRED   CURRENT   READY   AGE
replicaset.apps/velero-55cd5c99c6   0         0         0       138d
replicaset.apps/velero-6cf476c5cb   0         0         0       75d
replicaset.apps/velero-6d7b885f97   0         0         0       123d
replicaset.apps/velero-748bd5b5f8   1         1         1       2d1h
replicaset.apps/velero-7d6469f7d5   0         0         0       126d
replicaset.apps/velero-858899c87c   0         0         0       123d
replicaset.apps/velero-cf89b49c     0         0         0       75d
```
Jenkins consumes an EFS volume.

``` bash
$ k get pvc -n jenkins
NAME      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
jenkins   Bound    pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf   8Gi        RWO            efs-sc         379d

$ k get pv | grep jenkins
pvc-a3bed87d-f603-46ed-82fc-2a57ad0a7baf   8Gi        RWO            Retain           Bound    jenkins/jenkins
                          efs-sc                   379d

$ k get sc
NAME               PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
efs-sc (default)   efs.csi.aws.com         Retain          Immediate              false                  383d
encrypted-gp2      kubernetes.io/aws-ebs   Retain          WaitForFirstConsumer   false                  385d
```

Schedule created with the following command:
``` bash
$ velero schedule create sched-jenkins-mgmt --schedule="30 02 * * *" --include-namespaces jenkins --ttl 720h0m0s

$ velero get schedules | grep jenkins
sched-jenkins-mgmt               Enabled   2022-04-29 14:02:37 +0200 CEST   30 02 * * *   720h0m0s     6h ago        <none>
```

Once executed, the backup process got stuck, and finally timed out and remains in "PartiallyFailed" status or sometimes "InProgress" forever.
In both cases the logs remains the same.

**What did you expect to happen:**
The backup process finishes and final status is "Completed".

**The following information will help us better understand what's going on**:

[Logs can be found here](https://gist.github.com/DavidSanchezAlvarez/9eb4ead85a50378e969e63c1c155f277#file-backup-logs)

**Anything else you would like to add:**

We've been able to perform successful backups of some other tools heavier than Jenkins (12.7 GB), Nexus for example (127 GB).
We've experienced a similar problem that was solved, [more details here](https://github.com/vmware-tanzu/velero/issues/4487). But now, although it seems to be the same problem, it has been verified that it is not.

**Environment:**

- Velero version (use `velero version`):
$ velero version
Client:
        Version: v1.8.0
        Git commit: a818c97dde2034385d7bf25e0ac2a2e055a0b372
Server:
        Version: v1.8.0 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
- Kubernetes installer & version: Kubernetes 1.21
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):
Amazon Linux 2 EKS
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3⭕amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
I saw one of the Restic pod started two times. 
``` bash
pod/restic-lt5nr              1/1     Running   2          2d1h
```
This could be the reason why backup is always in progress, because after Restic pod restart, it will not handle in-progress PodVolumeBackup anymore. This PR #4893 already give a fix by mark in-progress PVB/PVR failed to avoid hanging backup. This PR is included in v1.9, but it's not released yet. You can try with latest main image of Velero to have a try.

But we still need to figure out why the Restic pod restart during backup. Maybe need to increase the memory limit of Restic DaemonSet pod.

**Comment by DavidSanchezAlvarez** [comment]
Hello @blackpiglet.

Yes, indeed, yesterday evening, before I see this message also realized that one of the pods was restarting and throwing an OOMKilled message:

Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 11 May 2022 16:50:51 +0200
      Finished:     Thu, 12 May 2022 05:08:53 +0200

So I decided to increase 'restic' limits from 6GB to 8GB, and applied the change. The surprise is that this last night the problem happened again, but never consumed 8GB, it consumed 6.5GB at maximum, so I don't know why is suddenly consuming so much memory and why is not reaching the limit.

Is that reasonable or should I start investigating why is the consume increasing so fast?

**Comment by blackpiglet** [comment]
You mean the Restic pod got killed by OOM, even if the memory limit is not hit?
I'm not sure why that happened.
Looks like the Jenkins pod PV's capacity is not big. It looks weird why it consumes more than 6GB. Recently, Velero team did a performance test on Restic. I am looking for the test's document to see whether there is something for reference.

**Comment by DavidSanchezAlvarez** [comment]
Yes, yesterday it seemed so, but I increased again the 'restic' pod limits to 16GB and the backup got the limit and got stuck, in this case at 85%. Today increased the limit to 20GB in order to finally have a backup while keep investigating. Definitely it's a memory consumption problem, but I still need to understand why it increased so fast and where is it coming.

**Comment by blackpiglet** [comment]
@qiuming-best

**Comment by DavidSanchezAlvarez** [comment]
I was reading about setting env var GOGC=10, but I don't know how and where to do that. I assume that has to be done within the restic container, but I don't know how.

[memory usage when backing up directories containing many empty files](https://github.com/restic/restic/issues/2446)
[Restic RAM usage goes through the roof](github.com/vmware-tanzu/velero/issues/4648)

**Comment by qiuming-best** [comment]
> Yes, yesterday it seemed so, but I increased again the 'restic' pod limits to 16GB and the backup got the limit and got stuck, in this case at 85%. Today increased the limit to 20GB in order to finally have a backup while keep investigating. Definitely it's a memory consumption problem, but I still need to understand why it increased so fast and where is it coming.

@DavidSanchezAlvarez  indeed, We did some tests in some scenarios restic will consume lots of memory, especially,  with millions of tiny files and directories to be back up, and how many files and directories were backed up in your environment?

**Comment by qiuming-best** [comment]
> I was reading about setting env var GOGC=10, but I don't know how and where to do that. I assume that has to be done within the restic container, but I don't know how.
> 
> [memory usage when backing up directories containing many empty files](https://github.com/restic/restic/issues/2446) [Restic RAM usage goes through the roof](github.com/vmware-tanzu/velero/issues/4648)

yes, you can use `kubectl edit ds restic -n velero` and setting the container env by GOGC=10

**Comment by Lyndon-Li** [comment]
Closing this issue as Velero is planning to deprecate Restic path, so we are not going to work on performance improvement for Restic path. It is recommended to switch to Kopia path.
