### ISSUE TITLE
Request Benchmarks for Backup & Restore Times

### ISSUE THREAD

**Issue by MoSehsah** [vmware-tanzu/velero#4909]
**Describe the problem/challenge you have**
We are planning DR setup and would like to use Velero. We would like to have a benchmark results for time taken to backup & restore.

**Describe the solution you'd like**
A benchmark report that highlights different cluster sizes in terms of data and nodes, types of PV storages, latency. and the time taken to backup and restore for each combination. 

**Anything else you would like to add:**
N/A

**Environment:**

- Velero version: 1.8.1
- Kubernetes version: 1.20.x and above
- Kubernetes installer & version: -
- Cloud provider or hardware configuration: - 
- OS (e.g. from `/etc/os-release`): - 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by MoSehsah** [comment]
CC @eleanor-millman

**Comment by blackpiglet** [comment]
[Velero with restic b/r performance test](https://docs.google.com/document/d/1-EDvKghsm4NRirW_qoU7jlNXERMq5EC2J6hq7HYyEFA/edit#heading=h.jupki3r4alq)
Put recent performance with Restic result as a reference.

**Comment by qiuming-best** [comment]
As it has already done in v1.9, Maybe it's no need in v1.10

**Comment by eleanor-millman** [comment]
@qiuming-best I'm confused, did you do timing tests for the 1.9 work? If so, is it in the docs? If not, then I think this might be a different issue. Either way, handing off to Euclid (not sure of his Github handle).

**Comment by euclidsun** [comment]
@qiuming-best do you have the issue link for the work done in 1.9? let us mark it as a documentation work as well?

**Comment by reasonerjt** [comment]
Maybe a dup of #5082

**Comment by reasonerjt** [comment]
Let's see if we can publish such data in the wiki of this repository.

**Comment by qiuming-best** [comment]
because we have written one report [Velero with restic b/r performance test](https://docs.google.com/document/d/1-EDvKghsm4NRirW_qoU7jlNXERMq5EC2J6hq7HYyEFA/edit#heading=h.jupki3r4alq) which including B&R benchmarks, So I'm close it
