### ISSUE TITLE
Premium aks one-redundant storage (ZRS) managed disks

### ISSUE THREAD

**Issue by Matusalterway** [vmware-tanzu/velero#4910]
**What steps did you take and what happened:**
The snapshot location doesn"t works on the premium_SSD in ZRS. 

**What did you expect to happen:**

time="2022-05-13T15:42:02Z" level=info msg="1 errors encountered backup up item" backup=velero/alterway-test-full-3 logSource="pkg/backup/backup.go:413" name=pvc-XXX
time="2022-05-13T15:42:02Z" level=error msg="Error backing up item" backup=velero/alterway-test-full-3 error="error getting volume info: rpc error: code = Unknown desc = disk has a nil SKU" logSource="pkg/backup/backup.go:417" name=pvc-XXX

If you are using velero v1.8.1 (see tar.gz)

- Velero version (use `velero version`): 

Client:
        Version: v1.8.0
        Git commit: a818c97dde2034385d7bf25e0ac2a2e055a0b372
Server:
        Version: v1.8.1

- Velero features (use `velero client config get features`): 

features: <NOT SET>

- Kubernetes version (use `kubectl version`):
lient Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"

- Cloud provider or hardware configuration:
- AKS 
- 
- OS (e.g. from `/etc/os-release`):
linux debian

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Matusalterway** [comment]
[bundle-2022-05-13-15-43-56.tar.gz](https://github.com/vmware-tanzu/velero/files/8689154/bundle-2022-05-13-15-43-56.tar.gz)

**Comment by blackpiglet** [comment]
@Matusalterway 
I'm not sure whether this issue is similar to your case #4608

**Comment by ywk253100** [comment]
@Matusalterway I cannot reproduce this issue in my AKS cluster. Is the `skuname` specified in your `StorageClass` used to provision the volumes? And could you check whether the sku name of the disks is there via Azure portal?
