### ISSUE TITLE
velero completion zsh can't work on macOS 12.3.1 (Apple M1 silicon)

### ISSUE THREAD

**Issue by drummerglen** [vmware-tanzu/velero#4912]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
velero completion zsh can't work on macOS 12.3.1 (Apple M1 silicon)
I have been executed`source <(velero completion zsh)`
Other command completion works.
`source <(kubectl completion zsh)`
`source <(helm completion zsh)`

**What did you expect to happen:**
command `velero` + `tab` can work on macOS zsh environment.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.8.1
- Velero features (use `velero client config get features`): nil
- Kubernetes version (use `kubectl version`):nil
- Kubernetes installer & version:nil
- Cloud provider or hardware configuration:nil
- OS (e.g. from `/etc/os-release`):macOS 12.3.1 (Apple M1 silicon)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
I found this issue on cobra: https://github.com/spf13/cobra/issues/1529

Cobra doesn't support source completion way by default.
Helm and kubectl can do that, because they do some modification of cobra's output.

Velero's commended way to do completion is output to a file.
``` bash
Zsh:

# If shell completion is not already enabled in your environment you will need
# to enable it.  You can execute the following once:

$ echo "autoload -U compinit; compinit" >> ~/.zshrc

# To load completions for each session, execute once:
$ velero completion zsh > "${fpath[1]}/_velero"
```

**Comment by blackpiglet** [comment]
After taking another thought on this, I think cobra being carefully on this is reasonable, but Velero can do that with some simple change.
I will create a PR for this.
