### ISSUE TITLE
timed out waiting for all PodVolumeBackups to complete

### ISSUE THREAD

**Issue by prad6588** [vmware-tanzu/velero#4917]
**What steps did you take and what happened:**
While running a Backup it is stuck and timing out after 4 hours. The error in log as below

timed out waiting for all PodVolumeBackups to complete

Error 
time="2022-05-12T15:51:21Z" level=error msg="Error backing up item" backup=velero/cluster-2022-05-12-11-51-11 error="timed out waiting for all PodVolumeBackups to complete" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:177" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:417" 

Backup command used

- ./velero-v1.8.1-linux-amd64/velero backup create cluster-"${datebkp}" --default-volumes-to-restic

**Comment by qiuming-best** [comment]
@prad6588 4hours is the default timeout for restic backup, which means backup one or some of PodVolumes got stuck or restic repository problem. So you need to retrieve some related logs.

Maybe some files sizes in Volumes are huge. or bad networking. you can provide us velero debug logs or velero or restic pod logs for us.

**Comment by prad6588** [comment]
Hi,
[cluster-2022-05-12-11-51-11-logs.zip](https://github.com/vmware-tanzu/velero/files/8713462/cluster-2022-05-12-11-51-11-logs.zip)
[cluster-2022-05-12-11-51-11-logs.zip](https://github.com/vmware-tanzu/velero/files/8713464/cluster-2022-05-12-11-51-11-logs.zip)



Have attached the Backup log

**Comment by qiuming-best** [comment]
@prad6588 I found logs about `error="restic repository is not ready: "`, maybe you should check the connection of BSL

**Comment by prad6588** [comment]
is there anything specific to check in the Backup storage location?  any command required be to be run to verify?

**Comment by prad6588** [comment]
$ ./velero get backup-location
NAME      PROVIDER   BUCKET/PREFIX   PHASE       LAST VALIDATED                  ACCESS MODE   DEFAULT
default   azure      velero          Available   2022-05-18 16:38:25 +0530 IST   ReadWrite     true

**Comment by sseago** [comment]
Have the PodVolumeBackups even started? Often this sort of error comes when something prevents restic from working in the first place. You can look at the podvolumebackup resources and check their status. If there is no status, that means restic didn't start backing it up. It might be that the restic pod on the node where the application pod is running is unhealthy -- coud could check the restic logs on that pod for more information as well.

**Comment by qiuming-best** [comment]
@prad6588 cloud you provide us with more logs about restic pod?

**Comment by prad6588** [comment]
Hello.. Now i am skipping the PV Backup and Restore. I am not running Restic during install. I am trying a velero Backup with PV. I see none of the ingress is getting restored. below is the error. can you please help on the same

error restoring ingresses.networking.k8s.io/referenceproddev/vp-core-service: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://devnginx-ingress-nginx ingresses?timeout=10s": service "devnginx-ingress-nginx-admission" not found

**Comment by fhossfel** [comment]
I am running time into the same problem. I am trying to restore our artifactory instance. Its repository is big but not crazily big -- about 15 GB. The backup takes some time but works:

        Name:         artifactory-backup-chmj6
        Namespace:    velero
        Labels:       velero.io/backup-name=artifactory-backup
                    velero.io/backup-uid=db00ee3c-29b2-43c5-9fb4-37d2b4ad67c3
                    velero.io/pvc-uid=9c02ce6e-4818-4295-b3ef-38e482435def
        Annotations:  velero.io/pvc-name: artifactory-volume-artifactory-0
        API Version:  velero.io/v1
        Kind:         PodVolumeBackup
        Metadata:
        Creation Timestamp:  2022-11-09T16:26:01Z
        Generate Name:       artifactory-backup-
        Generation:          1
        Managed Fields:
            API Version:  velero.io/v1
            Fields Type:  FieldsV1
            fieldsV1:
            f:metadata:
                f:annotations:
                .:
                f:velero.io/pvc-name:
                f:generateName:
                f:labels:
                .:
                f:velero.io/backup-name:
                f:velero.io/backup-uid:
                f:velero.io/pvc-uid:
                f:ownerReferences:
                .:
                k:{"uid":"c95030f2-b50c-4420-9753-485fcd5fb48e"}:
                k:{"uid":"db00ee3c-29b2-43c5-9fb4-37d2b4ad67c3"}:
            f:spec:
                .:
                f:backupStorageLocation:
                f:node:
                f:pod:
                .:
                f:kind:
                f:name:
                f:namespace:
                f:uid:
                f:repoIdentifier:
                f:tags:
                .:
                f:backup:
                f:backup-uid:
                f:ns:
                f:pod:
                f:pod-uid:
                f:pvc-uid:
                f:volume:
                f:volume:
            f:status:
                .:
                f:completionTimestamp:
                f:phase:
                f:progress:
                .:
                f:bytesDone:
                f:totalBytes:
                f:snapshotID:
                f:startTimestamp:
            Manager:    velero-server
            Operation:  Update
            Time:       2022-11-09T16:26:01Z
        Owner References:
            API Version:     velero.io/v1
            Controller:      true
            Kind:            Backup
            Name:            artifactory-backup
            UID:             db00ee3c-29b2-43c5-9fb4-37d2b4ad67c3
        Resource Version:  580037
        UID:               05939daf-59a2-4e71-9c0a-2bcd2c59dc2d
        Spec:
        Backup Storage Location:  default
        Node:                     vmd74678.contaboserver.net
        Pod:
            Kind:           Pod
            Name:           artifactory-0
            Namespace:      artifactory
            UID:            5c50b26c-2c7d-4e99-80f7-ac536590ea8a
        Repo Identifier:  s3:https://eu2.contabostorage.com/cloud-thoughtgang-de/tg/restic/artifactory
        Tags:
            Backup:        artifactory-backup
            Backup - UID:  c95030f2-b50c-4420-9753-485fcd5fb48e
            Ns:            artifactory
            Pod:           artifactory-0
            Pod - UID:     5c50b26c-2c7d-4e99-80f7-ac536590ea8a
            Pvc - UID:     9c02ce6e-4818-4295-b3ef-38e482435def
            Volume:        artifactory-volume
        Volume:          artifactory-volume
        Status:
        Completion Timestamp:  2022-11-09T11:08:52Z
        Phase:                 Completed
        Progress:
            Bytes Done:     16728388691
            Total Bytes:    16728388691
        Snapshot ID:      9cb33b82
        Start Timestamp:  2022-11-09T10:34:33Z
        Events:             <none>

Looking at content and size of the bucket it seems the backup was successful.

However, I cannot restore the content. I get the following error message:

        time="2022-11-09T23:28:35Z" level=info msg="Attempting to restore StatefulSet: artifactory" logSource="pkg/restore/restore.go:1245" restore=velero/artifactory-backup-20221110002823
        time="2022-11-09T23:28:35Z" level=info msg="Restored 51 items out of an estimated total of 51 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:669" name=artifactory namespace=artifactory progress= resource=statefulsets.apps restore=velero/artifactory-backup-20221110002823
        time="2022-11-09T23:28:35Z" level=info msg="Waiting for all restic restores to complete" logSource="pkg/restore/restore.go:551" restore=velero/artifactory-backup-20221110002823
        time="2022-11-10T03:28:25Z" level=error msg="unable to successfully complete restic restores of pod's volumes" error="timed out waiting for all PodVolumeRestores to complete" logSource="pkg/restore/restore.go:1579" restore=velero/artifactory-backup-20221110002823
        time="2022-11-10T03:28:25Z" level=info msg="Done waiting for all restic restores to complete" logSource="pkg/restore/restore.go:567" restore=velero/artifactory-backup-20221110002823
        time="2022-11-10T03:28:25Z" level=info msg="Waiting for all post-restore-exec hooks to complete" logSource="pkg/restore/restore.go:571" restore=velero/artifactory-backup-20221110002823
        time="2022-11-10T03:28:25Z" level=info msg="Done waiting for all post-restore exec hooks to complete" logSource="pkg/restore/restore.go:579" restore=velero/artifactory-backup-20221110002823
        time="2022-11-10T03:28:25Z" level=error msg="Velero restore error: timed out waiting for all PodVolumeRestores to complete" logSource="pkg/controller/restore_controller.go:497" restore=velero/artifactory-backup-20221110002823
        time="2022-11-10T03:28:25Z" level=warning msg="Cluster resource restore warning: could not restore, CustomResourceDefinition \"apps.catalog.cattle.io\" already exists. Warning: the in-cluster version is different than the backed-up version." logSource="pkg/controller/restore_controller.go:511" restore=velero/artifactory-backup-20221110002823

Please note the velar claims that `unable to successfully complete restic restores of pod's volumes` and `timed out waiting for all PodVolumeRestores to complete`.

Interestingly the Rustic pod claims it has completed the restore. Here is the relevant log:

        time="2022-11-09T23:28:45Z" level=info msg="Restore starting" PodVolumeRestore=velero/artifactory-backup-20221110002823-wrcd4 controller=PodVolumeRestore logSource="pkg/controller/pod_volume_restore_controller.go:103" pod=artifactory/artifactory-postgresql-0 restore=velero/artifactory-backup-20221110002823
        time="2022-11-09T23:28:54Z" level=info msg="Restore completed" PodVolumeRestore=velero/artifactory-backup-20221110002823-wrcd4 controller=PodVolumeRestore logSource="pkg/controller/pod_volume_restore_controller.go:132" pod=artifactory/artifactory-postgresql-0 restore=velero/artifactory-backup-20221110002823
        time="2022-11-09T23:28:54Z" level=info msg="Restore starting" PodVolumeRestore=velero/artifactory-backup-20221110002823-wh59x controller=PodVolumeRestore logSource="pkg/controller/pod_volume_restore_controller.go:103" pod=artifactory/artifactory-postgresql-0 restore=velero/artifactory-backup-20221110002823
        time="2022-11-09T23:32:47Z" level=info msg="Restore completed" PodVolumeRestore=velero/artifactory-backup-20221110002823-wh59x controller=PodVolumeRestore logSource="pkg/controller/pod_volume_restore_controller.go:132" pod=artifactory/artifactory-postgresql-0 restore=velero/artifactory-backup-20221110002823

I am not sure what is going on. I have also tried to restore our git repositories the same way: No problem! Same source, same pv type. Only difference is: They are about 1 GB not 15 GB.

I don't want to be pushy but it means that our backup is - at least for the purpose of disaster recovery - completely worthless. If there is any additional information necessary to resolve this please let me now.

**Comment by sseago** [comment]
So in the case where backup succeeded but restore timed out, it looks like the backup took 35 minutes. In my experience, restic performance is slower on restore than on backup. In one test run, for example, I saw that the backup took 25 minutes and the restore took just over an hour. However, from the restic restore logs, it looks like  velero/artifactory-backup-20221110002823-wh59x only took four minutes. What is the status of the PodVolumeRestore? Does that also show success? Does the volume itself have the restored data? Is it possible that the restored pod was bounced by its controller post-restore (does it belong to a Deployment? Something else?)

**Comment by Lyndon-Li** [comment]
Closing this issue as there is no update for long time, feel free to reopen it.
Additionally, Velero is planning to deprecate Restic path, it is recommended to switch to Kopia path.
