### ISSUE TITLE
Link to cloud provider steps broken in backup hooks documentation page

### ISSUE THREAD

**Issue by gsadhani** [vmware-tanzu/velero#4923]
**What steps did you take and what happened:**
Link to cloud provider steps broken in backup hooks documentation page: https://velero.io/docs/v1.8/backup-hooks/

> This example uses [examples/nginx-app/with-pv.yaml](https://github.com/vmware-tanzu/velero/blob/v1.8.0/examples/nginx-app/with-pv.yaml). Follow the [steps for your provider](https://velero.io/docs/v1.8/backup-hooks/cloud-common.md) to setup this example.

The link for the text "steps for your provider" is broken.

**What did you expect to happen:**

The link to take me to a valid page.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
NA

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
NA

**Anything else you would like to add:**
NA

**Environment:**

- Velero version (use `velero version`): 1.8
- Velero features (use `velero client config get features`): NA
- Kubernetes version (use `kubectl version`): NA
- Kubernetes installer & version: NA
- Cloud provider or hardware configuration: NA
- OS (e.g. from `/etc/os-release`): NA

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
@a-mccarthy May you help us to find out why the link is broken? thanks
