### ISSUE TITLE
Update docs to include new --existing-resource-policy flag

### ISSUE THREAD

**Issue by a-mccarthy** [vmware-tanzu/velero#4929]
From [comment](https://github.com/vmware-tanzu/velero/issues/4851#issuecomment-1108617077)
Issue link: https://github.com/vmware-tanzu/velero/issues/4842
Design link: https://github.com/vmware-tanzu/velero/pull/4613
Implementation link: https://github.com/vmware-tanzu/velero/pull/4628

**Comment by a-mccarthy** [comment]
The original PR added the setting into the restore API docs, but since we are making updates to the restore docs as well in https://github.com/vmware-tanzu/velero/issues/4642 and https://github.com/vmware-tanzu/velero/issues/4150, it think its also worth adding this functionality in.

**Comment by reasonerjt** [comment]
This has been documented in the restore reference:
https://velero.io/docs/main/restore-reference/#restore-existing-resource-policy
as well as the API documentation:
https://velero.io/docs/main/api-types/restore/

**Comment by reasonerjt** [comment]
closing this issue as it's been fixed.
