### ISSUE TITLE
Plugin's proto file using Share.proto causes failure in refactoring proto file in plugin versioning

### ISSUE THREAD

**Issue by phuongatemc** [vmware-tanzu/velero#4937]
**What steps did you take and what happened:**
When I refactored proto files in pkg/plugin/proto into directory with appropriate version, I found out that all proto file using Share.proto in the same directory pkg/plugin/proto.  For example BackupItemAction.proto after being moved to its own versioned directory pkg/plugin/proto/backupitemaction/v1 will no longer be in the same directory as Shared.proto so we have to modify the import and all references to Share.proto properly.   By adding option go_package = "github.com/vmware-tanzu/velero/pkg/plugin/generated/backupitemaction/v1"; into the BackupItemAction.proto and adding option option go_package = "github.com/vmware-tanzu/velero/pkg/plugin/generated"; into the Share.proto, I was able to generate code correctly but the output files are under pkg/plugin/generated/github.com/vmware-tanzu/velero/pkg/plugin/generated"

This is the script I used and I had to add command to copy over the output file to where I need them.

protoc pkg/plugin/proto/backupitemaction/v1/*.proto --go_out=plugins=grpc:pkg/plugin/generated/ -I pkg/plugin/proto/
protoc pkg/plugin/proto/*.proto --go_out=plugins=grpc:pkg/plugin/generated/ -I pkg/plugin/proto/
cp -rf pkg/plugin/generated/github.com/vmware-tanzu/velero/pkg/plugin/generated/* pkg/plugin/generated
rm -rf pkg/plugin/generated/github.com

This could be used as a temporary solution but we need a better solution to generate files in the correct directory.

**What did you expect to happen:**

Generated code should be under "pkg/plugin/generated" instead of pkg/plugin/generated/github.com/vmware-tanzu/velero/pkg/plugin/generated

**Comment by sseago** [comment]
I've commented on the implementation PR, but here's the solution here:
1) make sure all proto files have go_package:
For example, BackupItemAction v1:
```
option go_package = "github.com/vmware-tanzu/velero/pkg/plugin/generated/backupitemaction/v1";
```
For non-versioned or shared files:
```
option go_package = "github.com/vmware-tanzu/velero/pkg/plugin/generated";
```
2) When running protoc, use `--go_opt=module=github.com/vmware-tanzu/velero/pkg/plugin/generated`. The "module" go option tells the code generator that we're already in the right subdirectory, so eliminate the prefix specified from the output path:
```
protoc pkg/plugin/proto/*.proto --go_out=plugins=grpc:pkg/plugin/generated/ --go_opt=module=github.com/vmware-tanzu/velero/pkg/plugin/generated -I pkg/plugin/proto/
protoc pkg/plugin/proto/backupitemaction/v1/*.proto --go_out=plugins=grpc:pkg/plugin/generated/ --go_opt=module=github.com/vmware-tanzu/velero/pkg/plugin/generated -I pkg/plugin/proto/
```
Once these things are done, the cp/rm lines can be removed.

**Comment by sseago** [comment]
Proto issues should be resolved once https://github.com/vmware-tanzu/velero/pull/5263 is merged. When that happens, this issue can be closed/completed.
