### ISSUE TITLE
velero server crush when run locally

### ISSUE THREAD

**Issue by jumpapex** [vmware-tanzu/velero#4942]
**What steps did you take and what happened:**
build velero from source velero-1.8.1.tar.gz (with go version go1.18.2 linux/amd64)
go build ./cmd/velero
make local  # manually set GIT_SHA = 18ee078dffd9345df610e0ca9f61b31124e93f50 in Makefile for build

build velero-plugin-for-aws-1.4.1.tar.gz

run velero server with:

AWS_SHARED_CREDENTIALS_FILE=/root/workspace/credentials-velero _output/bin/linux/amd64/velero server --plugin-dir=/root/workspace/velero-plugin-for-aws-1.4.1/_output --log-level=debug

following "Quick start evaluation install with Minio"
kubectl apply -f examples/nginx-app/base.yaml

velero backup create nginx-backup-local-3 --selector app=nginx

then velero server crushed with message:

DEBU[0045] Backup has not expired yet, skipping          backup=velero/nginx-backup-local-3 controller=gc expiration="2022-06-26 19:10:28 +0800 CST" logSource="/root/workspace/velero-1.8.1/pkg/controller/gc_controller.go:131"
time="2022-05-27T19:10:32+08:00" level=info msg="Setting up backup store to persist the backup" backup=velero/nginx-backup-local-3 logSource="/root/workspace/velero-1.8.1/pkg/controller/backup_controller.go:663"
time="2022-05-27T19:10:32+08:00" level=debug msg="looking for plugin in registry" backup=velero/nginx-backup-local-3 kind=ObjectStore logSource="/root/workspace/velero-1.8.1/pkg/plugin/clientmgmt/manager.go:113" name=velero.io/aws
time="2022-05-27T19:10:32+08:00" level=debug msg="found preexisting restartable plugin process" backup=velero/nginx-backup-local-3 command=/root/workspace/velero-plugin-for-aws-1.4.1/_output/velero-plugin-for-aws kind=ObjectStore logSource="/root/workspace/velero-1.8.1/pkg/plugin/clientmgmt/manager.go:124" name=velero.io/aws
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x46625f]

goroutine 608 [running]:
runtime.throw({0x1faefe8?, 0x1?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0015b03e0 sp=0xc0015b03b0 pc=0x436131
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:825 +0x305 fp=0xc0015b0430 sp=0xc0015b03e0 pc=0x44c385
aeshashbody()
        /usr/local/go/src/runtime/asm_amd64.s:1343 +0x39f fp=0xc0015b0438 sp=0xc0015b0430 pc=0x46625f
runtime.mapiternext(0xc00004dfc0)
        /usr/local/go/src/runtime/map.go:934 +0x2cb fp=0xc0015b04a8 sp=0xc0015b0438 pc=0x40fd0b
runtime.mapiterinit(0x8fd4c2?, 0xc0006f47a0?, 0xc000e28a30?)
        /usr/local/go/src/runtime/map.go:861 +0x228 fp=0xc0015b04c8 sp=0xc0015b04a8 pc=0x40f9e8
reflect.mapiterinit(0x911ff6?, 0x1ce01c0?, 0xc00004dfc0?)
        /usr/local/go/src/runtime/map.go:1373 +0x19 fp=0xc0015b04f0 sp=0xc0015b04c8 pc=0x462a59
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
        /root/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:112
github.com/json-iterator/go.(*sortKeysMapEncoder).IsEmpty(0x11?, 0x1a91894?)
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:333 +0x28 fp=0xc0015b0530 sp=0xc0015b04f0 pc=0x905468
github.com/json-iterator/go.(*placeholderEncoder).IsEmpty(0x40aaef?, 0xc0000eeca0?)
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:336 +0x22 fp=0xc0015b0550 sp=0xc0015b0530 pc=0x8fd522
github.com/json-iterator/go.(*structFieldEncoder).IsEmpty(0xc000b42d50, 0x1cd65ba?)
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:118 +0x42 fp=0xc0015b0570 sp=0xc0015b0550 pc=0x9121a2
github.com/json-iterator/go.(*structEncoder).Encode(0xc000b42ea0, 0x413d01?, 0xc00046e840)
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:148 +0x565 fp=0xc0015b0658 sp=0xc0015b0570 pc=0x912805
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0001c3380, 0x1b0cb3d?, 0xc00046e840)
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56 fp=0xc0015b06d0 sp=0xc0015b0658 pc=0x911ff6
github.com/json-iterator/go.(*structEncoder).Encode(0xc0001c3470, 0x0?, 0xc00046e840)
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765 fp=0xc0015b07b8 sp=0xc0015b06d0 pc=0x912a05
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc000a003c0?, 0x0?, 0x0?)
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_optional.go:70 +0xa4 fp=0xc0015b0808 sp=0xc0015b07b8 pc=0x909bc4
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc000bd34f0, 0xc0000eec80, 0xc000bd1f50?)
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x82 fp=0xc0015b0840 sp=0xc0015b0808 pc=0x8fca82
github.com/json-iterator/go.(*Stream).WriteVal(0xc00046e840, {0x1f6ade0, 0xc0000eec80})
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x158 fp=0xc0015b08b0 sp=0xc0015b0840 pc=0x8fbd98
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc000a003c0, {0x1f6ade0, 0xc0000eec80})
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:299 +0xc9 fp=0xc0015b0948 sp=0xc0015b08b0 pc=0x8f2ec9
github.com/json-iterator/go.(*frozenConfig).MarshalIndent(0xc000269860, {0x1f6ade0, 0xc0000eec80}, {0x0?, 0x1c286a0?}, {0x1facb30, 0x2})
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:320 +0x131 fp=0xc0015b09c0 sp=0xc0015b0948 pc=0x8f31b1
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x1a98f02?, {0x232e4a8?, 0xc0000eec80?}, {0x2326540, 0xc000ad1ec0})
        /root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/json/json.go:319 +0x111 fp=0xc0015b0a58 sp=0xc0015b09c0 pc=0xd5ea71
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc00049f900, {0x232e4a8, 0xc0000eec80}, {0x2326540, 0xc000ad1ec0})
        /root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/json/json.go:301 +0xfc fp=0xc0015b0ab8 sp=0xc0015b0a58 pc=0xd5e8fc
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc000a00320, {0x232e4a8?, 0xc0000eec80}, {0x2326540, 0xc000ad1ec0})
        /root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/versioning/versioning.go:244 +0x8fa fp=0xc0015b0e10 sp=0xc0015b0ab8 pc=0xd6395a
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc000a00320, {0x232e4a8, 0xc0000eec80}, {0x2326540, 0xc000ad1ec0})
        /root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/versioning/versioning.go:184 +0x106 fp=0xc0015b0e70 sp=0xc0015b0e10 pc=0xd63006
github.com/vmware-tanzu/velero/pkg/util/encode.EncodeTo({0x232e4a8, 0xc0000eec80}, {0x1fae085?, 0x0?}, {0x2326540, 0xc000ad1ec0})
        /root/workspace/velero-1.8.1/pkg/util/encode/encode.go:50 +0x6e fp=0xc0015b0ec0 sp=0xc0015b0e70 pc=0x14d7eae
github.com/vmware-tanzu/velero/pkg/controller.persistBackup(0xc0000bafc0, 0xc000187410, 0xc000187408, {0x2351aa8, 0xc0010b23c0}, {0xc000e0a680?, 0x40d525?}, {0x0, 0x0, 0x0}, ...)
        /root/workspace/velero-1.8.1/pkg/controller/backup_controller.go:709 +0x92 fp=0xc0015b1090 sp=0xc0015b0ec0 pc=0x198fa32
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).runBackup(0xc00085d8c0, 0xc0000bafc0)
        /root/workspace/velero-1.8.1/pkg/controller/backup_controller.go:669 +0x16f9 fp=0xc0015b16b0 sp=0xc0015b1090 pc=0x198f1f9
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).processBackup(0xc00085d8c0, {0xc00071dc00, 0x1b})
        /root/workspace/velero-1.8.1/pkg/controller/backup_controller.go:275 +0x7e5 fp=0xc0015b1c60 sp=0xc0015b16b0 pc=0x198af65
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).processBackup-fm({0xc00071dc00?, 0x0?})
        <autogenerated>:1 +0x34 fp=0xc0015b1c88 sp=0xc0015b1c60 pc=0x19b2bb4
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).processNextWorkItem(0xc000c52b40)
        /root/workspace/velero-1.8.1/pkg/controller/generic_controller.go:132 +0xeb fp=0xc0015b1e60 sp=0xc0015b1c88 pc=0x199fe6b
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).runWorker(0xc0008f1ea8?)
        /root/workspace/velero-1.8.1/pkg/controller/generic_controller.go:119 +0x25 fp=0xc0015b1e80 sp=0xc0015b1e60 pc=0x199fd45
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).runWorker-fm()
        <autogenerated>:1 +0x26 fp=0xc0015b1e98 sp=0xc0015b1e80 pc=0x19b33c6
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0007b80d0?)
        /root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:155 +0x3e fp=0xc0015b1eb8 sp=0xc0015b1e98 pc=0x1161b1e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x23457f8?, {0x23298e0, 0xc000ae6c30}, 0x1, 0xc000872360)
        /root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:156 +0xb6 fp=0xc0015b1f38 sp=0xc0015b1eb8 pc=0x11619f6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x23457f8?, 0x3b9aca00, 0x0, 0xc0?, 0x1920500?)
        /root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:133 +0x89 fp=0xc0015b1f88 sp=0xc0015b1f38 pc=0x11618e9
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:90
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).Run.func2()
        /root/workspace/velero-1.8.1/pkg/controller/generic_controller.go:92 +0x6e fp=0xc0015b1fe0 sp=0xc0015b1f88 pc=0x199fb0e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0015b1fe8 sp=0xc0015b1fe0 pc=0x468d21
created by github.com/vmware-tanzu/velero/pkg/controller.(*genericController).Run
        /root/workspace/velero-1.8.1/pkg/controller/generic_controller.go:91 +0x45a

Delve print stack:
runtime.throw (/usr/local/go/src/runtime/panic.go:982)
runtime.sigpanic (/usr/local/go/src/runtime/signal_unix.go:825)
github.com/modern-go/reflect2.(*UnsafeMapIterator).HasNext (.:0)
github.com/json-iterator/go.(*sortKeysMapEncoder).IsEmpty (/root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:334)
github.com/json-iterator/go.(*placeholderEncoder).IsEmpty (/root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:336)
github.com/json-iterator/go.(*structFieldEncoder).IsEmpty (/root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:118)
github.com/json-iterator/go.(*structEncoder).Encode (/root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:148)
github.com/json-iterator/go.(*structFieldEncoder).Encode (/root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110)
github.com/json-iterator/go.(*structEncoder).Encode (/root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158)
github.com/json-iterator/go.(*OptionalEncoder).Encode (/root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_optional.go:70)
github.com/json-iterator/go.(*onePtrEncoder).Encode (/root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219)
github.com/json-iterator/go.(*Stream).WriteVal (/root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98)
github.com/json-iterator/go.(*frozenConfig).Marshal (/root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:299)
github.com/json-iterator/go.(*frozenConfig).MarshalIndent (/root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:320)
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode (/root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/json/json.go:319)
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode (/root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/json/json.go:301)
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode (/root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/versioning/versioning.go:244)
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode (/root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/versioning/versioning.go:184)
github.com/vmware-tanzu/velero/pkg/util/encode.EncodeTo (/root/workspace/velero-1.8.1/pkg/util/encode/encode.go:50)
github.com/vmware-tanzu/velero/pkg/controller.persistBackup (/root/workspace/velero-1.8.1/pkg/controller/backup_controller.go:709)
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).runBackup (/root/workspace/velero-1.8.1/pkg/controller/backup_controller.go:669)
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).processBackup (/root/workspace/velero-1.8.1/pkg/controller/backup_controller.go:275)
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).processBackup-fm (:1)
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).processNextWorkItem (/root/workspace/velero-1.8.1/pkg/controller/generic_controller.go:132)
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).runWorker (/root/workspace/velero-1.8.1/pkg/controller/generic_controller.go:119)
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).runWorker-fm (:1)
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1 (/root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:155)
k8s.io/apimachinery/pkg/util/wait.BackoffUntil (/root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:156)
k8s.io/apimachinery/pkg/util/wait.JitterUntil (/root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:133)
k8s.io/apimachinery/pkg/util/wait.Until (/root/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:90)
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).Run.func2 (/root/workspace/velero-1.8.1/pkg/controller/generic_controller.go:92)

**What did you expect to happen:**
the backup should complete successfully.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
No backup information

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Scale deployment down to zero already done with:
kubectl scale --replicas=0 deployment velero -n velero
/root/workspace/velero-1.8.1: velero source code directory
/root/workspace/velero-plugin-for-aws-1.4.1: aws plugin source directory
build from the lastest git source code also has the issue.
deployment velero in Kubernetes works well.

**Environment:**

- Velero version (use `velero version`): 
 1.8.1
- Velero features (use `velero client config get features`): 
 features: <NOT SET>
- Kubernetes version (use `kubectl version`):
 1.23.3
- Kubernetes installer & version:
 N/A
- Cloud provider or hardware configuration:
 N/A
- OS (e.g. from `/etc/os-release`):
Rocky Linux release 8.5 (Green Obsidian)
- Go version
go version go1.18.2 linux/amd64

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
@jumpapex Velero 1.8.1 doesn't support golang 1.18. Could you try to build velero with go 1.17 and test?

**Comment by jumpapex** [comment]
@Lyndon-Li, you are right. after install go 1.7.10, backup completed successfully.

So should we add go lang version support in doc. Thanks!

**Comment by reasonerjt** [comment]
In v1.10 we plan to upgrade the golang so let me re-open it for tracking this.

**Comment by 27149chen** [comment]
@reasonerjt I'm curious what's new in go1.18 that broke it, can you share it? thanks

**Comment by Lyndon-Li** [comment]
The crash seems to be the problem discussed [here](https://github.com/golang/go/issues/48238), so github.com/json-iterator/go should be with version v1.1.12.
Velero 1.8 is using v1.1.11, see [here](https://github.com/vmware-tanzu/velero/blob/release-1.8/go.mod#:~:text=github.com/json%2Diterator/go%20v1.1.11%20//%20indirect), so Velero 1.8 doesn't work with go 1.18
