### ISSUE TITLE
Persistent Volumes backup is not working other than {AZURE_RESOURCE_GROUP} resource group in the cluster

### ISSUE THREAD

**Issue by mayankagg9722** [vmware-tanzu/velero#4947]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

This bug is for azure velero plugin. Repo: https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure

As in the azure velero documenation, "AZURE_RESOURCE_GROUP" env variable is used as the PV RG and we can only backup the PVs witin the same RG. PersistentVolume backups are not working for volumes in different resource groups other than {AZURE_RESOURCE_GROUP}.

Documentation:
https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#get-resource-group-containing-your-vms-and-disks

**What did you expect to happen:**

We have figured out that the RGs while backing up volumes is used from the env variables, can we please take the resourceGroup name from volume handle? currently taken from env variable {AZURE_RESOURCE_GROUP}.

Code line: 
https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/dafb9e36cfe2df41e5ec11446ab94d5871557fb0/velero-plugin-for-microsoft-azure/volume_snapshotter.go#L252

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Logs:**
**https://pastebin.com/qhWwtntZ**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 

Client:
        Version: v1.8.1
        Git commit: 18ee078dffd9345df610e0ca9f61b31124e93f50
Server:
        Version: v1.8.1

- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"10428892c761e8ca8908e71146eea4751feb545b", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:11Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:

Azure Kubernetes Service 1.21.1

- Cloud provider or hardware configuration:

Azure

- OS (e.g. from `/etc/os-release`):
Azure ; Linux ; Standard_DS2_v2 ; 2 nodes

**velero installation command:**
velero install --provider azure --plugins velero/velero-plugin-for-microsoft-azure:v1.4.0,velero/velero-plugin-for-csi:v0.2.0 --bucket test --secret-file '.\credentials-velero.txt' --backup-location-config resourceGroup=mayaggar,storageAccount=mayaggarpremiumsa --snapshot-location-config apiTimeout=5m,resourceGroup=mayaggar,subscriptionId=62b829ee-7936-40c9-a1c9-47a93f9f3965 --image velero/velero:v1.8.1 --features=EnableCSI

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
Seems it's dup of https://github.com/vmware-tanzu/velero/issues/3157
