### ISSUE TITLE
Velero fails to backup the sentinel-data volume from redis namespace

### ISSUE THREAD

**Issue by decipher27** [vmware-tanzu/velero#4948]
We are using aws EKS to host our services and we run daily scheduled backups and noticed partial failues only backing up **sentinel-data** from redis. Other volumes like the redis-data and redis-tmp gets backedup successfully. 
I did a velero describe backup <backup> --details

^ When I describe the backup I see redis-sentinel-data volume fails to get backed up. 
` redis/redis-node-0: sentinel-data
   redis/redis-node-1: sentinel-data
   redis/redis-node-2: sentinel-data`

These are the directories present under sentinel data: 
`I have no name!@redis-node-1:/opt/bitnami/redis-sentinel$ ls
bin  etc  licenses  logs  mounted-etc  tmp`

logs & tmp are empty and etc & mounted-etc contains sentinel/redis config files

We are using velero v1.8.1

 Let me know if you require any additional information.

Thanks you!

**Comment by decipher27** [comment]
Attaching the logs here:
[backup-describe.txt](https://github.com/vmware-tanzu/velero/files/8803369/backup-describe.txt)
[backup-logs.log](https://github.com/vmware-tanzu/velero/files/8803371/backup-logs.log)
[velero.log](https://github.com/vmware-tanzu/velero/files/8803374/velero.log)

**Comment by ywk253100** [comment]
Seems it is a dup of https://github.com/vmware-tanzu/velero/issues/4331, the files cannot be removed during the backing up, this is a known limitation for restic backup
