### ISSUE TITLE
Cross Cluster Restic Restore Failed Due to PVB Status Missing

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#4950]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
1. Backup a workload in cluster A through Restic
2. Create a new cluster Cluster B
3. Restore the workload in Cluster B through Restic
4. Resources are restored but PV file system is not restored

**What did you expect to happen:**
Everything should be restored

**The following information will help us better understand what's going on**:
Restic restore is skipped:
msg="No restic backups found for pod" cmd=/velero logSource="pkg/restore/restic_restore_action.go:101"

If we list the PVB in Cluster B, the PVB can be listed, but the Status fields are empty. Velero cannot find the SnapshotID from PVB.Status, this looks like the direct cause of the skip.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by reasonerjt** [comment]
Let's try to unset the status from subresource.
We should also be careful in future refactor.
