### ISSUE TITLE
Backup stuck in `InProgress`, no error on logs

### ISSUE THREAD

**Issue by headyj** [vmware-tanzu/velero#4952]
**What steps did you take and what happened:**
Since a few days, all my scheduled backups are stuck in `InProgress` for days, without any error in the logs. The last logs concerning the backup in progress are:

```
time="2022-05-30T10:37:46Z" level=info msg="Executing VolumeSnapshotBackupItemAction" backup=velero/velero-cluster-schedule-20220530100341 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/volumesnapshot_action.go:58" pluginName=velero-plugin-for-csi
time="2022-05-30T10:37:46Z" level=info msg="Getting VolumesnapshotContent for Volumesnapshot rabbitmq-test/velero-persistence-rabbitmq-test-server-2-v577c" backup=velero/velero-cluster-schedule-20220530100341 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/volumesnapshot_action.go:91" pluginName=velero-plugin-for-csi
I0530 10:38:19.878897       1 request.go:665] Waited for 1.042707556s due to client-side throttling, not priority and fairness, request: GET:https://10.100.0.1:443/apis/coordination.k8s.io/v1beta1?timeout=32s

```
Unfortunately I cannot provide any other information as the logs on the velero pod are very poor. No error log at all, and the logs that comes after the ones above are not related to the backup itself. Afther the `client-side throttling`, velero seems to behave like no backup are in progress anymore.

**What did you expect to happen:**

Backup should complete, at least with errors

**Anything else you would like to add:**
* The VolumeSnapshot itself seems OK and available.
* I use the latest velero-plugin-for-csi (v0.2.0)
* CRDs are up to date
* I also tried to give velero more CPU and memory
* CSI Snapshots are correctly being created on AWS

**Environment:**

- helm version (use `helm version`): v3.7.2
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): v2.29.6 (also tested with v2.29.7)
- Kubernetes version (use `kubectl version`): v1.21.5 (EKS)
- Kubernetes installer & version:
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):

**Comment by ywk253100** [comment]
Is there any restarting during the period? The in-progress backups will be stuck after velero server restarting, this is a known issue https://github.com/vmware-tanzu/velero/issues/4503

Is this specific to CSI snapshot? Could you try to take a snapshot by AWS plugin?

**Comment by headyj** [comment]
Thank you for your answer

No it didn't, I first thought that this was due to CPU/memory limits (as suggested in another issue), but I already tried to increase it:
```
kubectl get pod -n velero
NAME                      READY   STATUS    RESTARTS   AGE
velero-6bf7645744-tzlrw   1/1     Running   0          25h
```

Both `velero-plugin-for-csi` and `velero-plugin-for-aws` plugins are enabled (which may be not correct), but it was working as-is without any issue one week ago, and it's still working as well on my other EKS cluster, with same config and same versions.

The only difference between my clusters is the load / number of pods and volumes, which is way higher on the one having the velero backup issue

**Comment by ywk253100** [comment]
Maybe it's the same issue with https://github.com/vmware-tanzu/velero/issues/4863, the fix has been merged into main branch, could you try to reinstall Velero with the image `velero/velero:main`?

**Comment by headyj** [comment]
thank you @ywk253100 . I tried to switch to velero:main, and at least now I have some errors:
```
time="2022-06-08T10:07:08Z" level=error msg="Error backing up item" backup=velero/velero-cluster-schedule-20220608100355 error="error executing custom action (groupResource=persistentvolumeclaims, namespace=***, name=****): rpc error: code = Unknown desc = failed to get volumesnapshotclass for storageclass ebs-storage-class: error listing volumesnapshot classes: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:316" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*itemBackupper).executeActions" logSource="pkg/backup/backup.go:417" name=*****
time="2022-06-08T10:07:21Z" level=error msg="Error backing up item" backup=velero/velero-cluster-schedule-20220608100355 error="error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=***, name=*****): rpc error: code = Unknown desc = error getting volume snapshot content from API: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io snapcontent-99e6e19a-c68c-4b8d-bca1-45feed920065)" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:316" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*itemBackupper).executeActions" logSource="pkg/backup/backup.go:417" name=*****

```
The volumesnapshotclass, volumesnapshot and volumesnapshotcontent CRD are ok, and the resources listed above are existing

**Comment by ywk253100** [comment]
@headyj Replace the CSI plugin with the main version `velero/velero-plugin-for-csi:main`, some changes are made on the plugin side as well

**Comment by Mercbot7** [comment]
We are experiencing the same issue in our largest cluster and here is the deal, once the backup stops backing up, with no error or feedback in the logs, even if you delete the offending backup the velero pod will not pick up and start the next job, you have to restart the pod to get it to pick up the next backup.

**Comment by Dizzudin2** [comment]
As far as I know, when the backup is stuck, it wont be shown in the logs.

And the only way for me to troubleshoot is to use describe.
```
daniel@x9031:~$ velero backup describe cluster-full-backup-3 --details
Name:         cluster-full-backup-3
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.23.5+k3s1
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=23

Phase:  InProgress

Errors:    0
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        pod, pvc, pv
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2022-07-25 06:13:04 +0000 UTC
Completed:  <n/a>

Expiration:  2022-08-24 06:13:04 +0000 UTC

Estimated total items to be backed up:  181
Items backed up so far:                 75

Resource List:  <backup resource list not found>

Velero-Native Snapshots: <none included>

Restic Backups:
  Completed:
    ads/control-4c8jb: data, logs, var-run, var-run-managed-secrets
    ads/controldb-0: data, logs, var-run, var-run-managed-secrets
    ads/logsdb-0: data, logs, var-run, var-run-secrets-managed
    ads/logsui-29pnp: data, logs, var-run, var-run-secrets-managed
    ads/metricsdb-0: data, logs, var-run, var-run-secrets-managed
    ads/metricsdc-65mtb: data, logs, var-run, var-run-secrets-managed
    ads/metricsdc-7tbgp: data, logs, var-run, var-run-secrets-managed
    ads/metricsdc-wdvvv: data, logs, var-run, var-run-secrets-managed
    ads/metricsui-7wtf2: data, logs, var-run, var-run-secrets-managed
    ads/se11gdev01-0: data-qdxp38yegfo6c91fcq2bdirq, datalogs-qdxp38yegfo6c91fcq2bdirq, logs-qdxp38yegfo6c91fcq2bdirq, var-run, var-run-secrets-managed
    ads/se11gdev01-1: data-qdxp38yegfo6c91fcq2bdirq, datalogs-qdxp38yegfo6c91fcq2bdirq, logs-qdxp38yegfo6c91fcq2bdirq, var-run, var-run-secrets-managed
    ads/se11gdev01-ha-0: data-ha-qdxp38yegfo6c91fcq2bdirq, logs-ha-qdxp38yegfo6c91fcq2bdirq, var-run, var-run-secrets-managed
    grafana-operator/grafana-deployment-74b4b6d6f-bhctn: grafana-logs, grafana-plugins, grafana-provision-dashboards, grafana-provision-notifiers, grafana-provision-plugins
  New:
    kube-system/metrics-server-ff9dbcb6c-qgks4: tmp-dir
```

From describe I can see my restic backup is stuck at 
```
  New:
    kube-system/metrics-server-ff9dbcb6c-qgks4: tmp-dir
```

This is due to velero trying to backup with restic on a node without restic daemonsets deployed. 

Further details and solution for this is at
https://github.com/vmware-tanzu/velero/issues/2967

**Comment by arunvc** [comment]
Adding toleration to demonsets worked for me

kubectl edit daemonset/restic -n velero

```
      tolerations:
      - key: <yourkey>
        operator: Equal
        value: <yourvalue>
        effect: NoSchedule
```
