### ISSUE TITLE
error fetching volume snapshots metadata: rpc error: code = Unknown desc = Forbidden: Forbidden

### ISSUE THREAD

**Issue by Bharathvijay** [vmware-tanzu/velero#4956]
**What steps did you take and what happened:**
Tried backing up using `velero` + `restic` on a TKG cluster and tried restoring it in a azure cluster. I use minio for storage so using `velero/velero-plugin-for-aws:v1.4.1`

**What did you expect to happen:**
A clean restore of the application

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

```> velero debug  --backup kokoko --restore blasks
2022/05/31 23:53:24 Collecting velero resources in namespace: velero
2022/05/31 23:53:25 Collecting velero deployment logs in namespace: velero
2022/05/31 23:53:26 Collecting log and information for backup: kokoko
2022/05/31 23:53:28 Collecting log and information for restore: blasks
``` 
[bundle-2022-05-31-23-53-23.tar.gz](https://github.com/vmware-tanzu/velero/files/8808122/bundle-2022-05-31-23-53-23.tar.gz)

When doing a restore, it fails instantly.

**Logs from describe of the restore object:**
```
  Failure Reason:        error fetching volume snapshots metadata: rpc error: code = Unknown desc = Forbidden: Forbidden
                         status code: 403, request id: 16F42EEAE1152623, host id:
  Phase:                 Failed
```

**Environment:**

- Velero version (use `velero version`): 1.8.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.21.7
- Kubernetes installer & version: azure
- Cloud provider or hardware configuration: azure
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
What's the version of Velero used to do the backup on the source cluster?

**Comment by barry1011** [comment]
Earlier I tried with `1.6.3`. Later with `1.8.1` as well. Both ended up being the same scenario.

**Comment by ywk253100** [comment]
The error `error fetching volume snapshots metadata` comes from the validation stage that Velero tries to get a file called `backupname-itemsnapshots.json.gz` in the backup storage, could you check whether the file is there(replace the `backupname` with yours)?

**Comment by Bharathvijay** [comment]
![image](https://user-images.githubusercontent.com/7747324/172105651-00313cee-7e7e-4683-b2ed-d841575b53dc.png)
No, I don't see any file marked a <backupname>-itemsnapshots.json.gz

**Comment by ywk253100** [comment]
Sorry for the mistake, it should be the file `backupname-volumesnapshots.json.gz`.

It is there. Can you download the file and is there any special limitation for this file? It's weird that it cannot be accessed

**Comment by Bharathvijay** [comment]
I was able to download it. I extracted it as well and it's empty.

**Comment by reasonerjt** [comment]
@Bharathvijay Have you tried using `aws` cli to download the  file with the same credentials?
Could you also check the logs from the AWS to see if there's the server received the request and returned forbidden error?

**Comment by reasonerjt** [comment]
Closing the due to inactivity.
