### ISSUE TITLE
The readme of plugins is confused for the content of a backup 

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#4970]
Question from @eleanor-millman 
Question about the Azure plugin. It says in the readme on github that:
```
An object store plugin for persisting and retrieving backups on Azure Blob Storage. Content of backup is log files, warning/error files, restore logs.
A volume snapshotter plugin for creating snapshots from volumes (during a backup) and volumes from snapshots (during a restore) on Azure Managed Disks.
```
But what about the K8s resources? I assume they go to the Azure Blob Storage, but the language in the readme doesn't say that. Thoughts?

The readme file of plugins(aws/azure/gcp) should be updated for this part

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
The README of AWS plugin has been updated via https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/148

**Comment by ywk253100** [comment]
The update for Azure plugin: https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/174

**Comment by blackpiglet** [comment]
All plugins are updated. Close.
