### ISSUE TITLE
Support to skip certificate validate when helm install Velero with Restic

### ISSUE THREAD

**Issue by iamjackhu** [vmware-tanzu/velero#4971]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
After helm install Velero with Restic to target cluster, when executing backup/restore, it will report 'x509: certificate signed by unknown authority' issue

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
If provide a parameter to skip certificate validation, then it will be easy to test and validate Velero's functionality. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
I believe this has been fixed in `v1.9`
Let's keep this open until it's reflected in the helm chart.

**Comment by qiuming-best** [comment]
@iamjackhu if fact you can define this flag 'insecure-skip-tls-verify: true' in [config](https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml#L210) to skip tls verify, And it is already supported by velero 1.8.1

**Comment by iamjackhu** [comment]
do you means velero 1.8.1 has supported skip tls verfiy? which arguments for it? 

And meanwhile, does the the helm chart of velero support skipping tls ?

**Comment by qiuming-best** [comment]
> do you means velero 1.8.1 has supported skip tls verfiy? which arguments for it?
> 
> And meanwhile, does the the helm chart of velero support skipping tls ?

@iamjackhu sorry, Here is something I'm mistaken. the restic In velero 1.8.1 is not supported to skip TLS, so even set flag 'insecure-skip-tls-verify: true' in [config](https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml#L210) is not working. 
But in velero 1.9.0 which will probably release next week, We have an upgrade Restic version, it will support skip TLS.

**Comment by qiuming-best** [comment]
once v1.9.0 is released, the helm chart of velero is support skipping TLS by above setting

**Comment by iamjackhu** [comment]
Do you have schedule for release v1.9.0?

**Comment by qiuming-best** [comment]
@iamjackhu v1.9.0 has released, you can have a try

**Comment by iamjackhu** [comment]
ok, will try.

**Comment by iamjackhu** [comment]
@qiuming-test we are using helm-chart of velero to deploy it to target cluster.  What changed on helm-chart for velero v1.9.0?

**Comment by qiuming-best** [comment]
About skip certificate validation, both velero server side and client side should set flag `insecureSkipTLSVerify`
1. Helm install:
set insecureSkipTLSVerify field in values.yaml
```
 backupStorageLocation:
    config:
      insecureSkipTLSVerify: true
```
2. Velero client Command:
for command `velero backup describe`, `velero backup logs` needs add the flag `--insecure-skip-tls-verify`

**Comment by reasonerjt** [comment]
Let's just add a comment to help user understand how to do that
