### ISSUE TITLE
Backup (with Restic opt-out in vSphere) result will be "PartiallyFailed" if default BSL is not provided  

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#4983]
**What steps did you take and what happened:**

There're 2 pod with PV in my workload, when performing Restic opt-out backup, after adding annotation(backup.velero.io/backup-volumes-excludes) to one pod, backup with Restic will not backup this pod, and the other pod's PV should be backed up, and the backup result should be completed successfully. But the backup result is "PartiallyFailed" when no default BSL is provided, and errors are from pluginName=velero-plugin-for-vsphere, it seems no relevant with velero-plugin-for-vsphere plugin since it's a backup by Restic.

```

 v get backup-location
NAME   PROVIDER   BUCKET/PREFIX                PHASE       LAST VALIDATED                  ACCESS MODE   DEFAULT
aws    aws        velero-e2e-testing/default   Available   2022-06-10 09:40:02 +0000 UTC   ReadWrite


v \
--namespace velero create backup bk6 \
--include-namespaces kibishii --wait \
--default-volumes-to-restic \
--storage-location aws

k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                          STORAGECLASS             REASON   AGE
pvc-0c5c0a69-a003-4bd6-9c85-9ca143269214   1Gi        RWO            Delete           Bound    kibishii/kibishii-data-kibishii-deployment-0   kibishii-storage-class            5h49m
pvc-f14de5b5-5774-43bb-a27f-77700ca6c50a   1Gi        RWO            Delete           Bound    kibishii/kibishii-data-kibishii-deployment-1   kibishii-storage-class            5h48m

k -n kibishii  annotate pod/kibishii-deployment-1 backup.velero.io/backup-volumes-excludes=kibishii-data

velero \
--namespace velero create backup bk6 \
--include-namespaces kibishii --wait \
--default-volumes-to-restic \
--storage-location aws

velero get backup
backup1                                            PartiallyFailed    6        2          2022-06-10 08:39:31 +0000 UTC   29d       aws                <none>

k -n velero get podvolumebackups -l velero.io/backup-name=bk6
NAME        STATUS      CREATED   NAMESPACE   POD                     VOLUME          RESTIC REPO                                                                STORAGE LOCATION   AGE
bk6-68jxc   Completed   32m       kibishii    kibishii-deployment-0   kibishii-data   s3:http://10.202.250.206:9000/velero-e2e-testing/default/restic/kibishii   aws                32m
# It's expected that only 1 PV is backed up, because the other one is excluded.

v  backup logs bk6 | grep error
time="2022-06-10T08:40:10Z" level=error msg="failed to create new client with err: Post \"https://10.206.213.15:443/sdk\": dial tcp 10.206.213.15:443: i/o timeout" backup=velero/bk6 cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/common/vsphere/virtual_center.go:125" pluginName=velero-plugin-for-vsphere
time="2022-06-10T08:40:10Z" level=error msg="failed to create govmomi client with err: Post \"https://10.206.213.15:443/sdk\": dial tcp 10.206.213.15:443: i/o timeout" backup=velero/bk6 cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/common/vsphere/virtual_center.go:181" pluginName=velero-plugin-for-vsphere
time="2022-06-10T08:40:10Z" level=error msg="Failed to connect to virtual center while retrieving a instance of it." backup=velero/bk6 cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/common/vsphere/virtual_center.go:81" pluginName=velero-plugin-for-vsphere
time="2022-06-10T08:40:10Z" level=error msg="Could not initialize ivd service, error: Post \"https://10.206.213.15:443/sdk\": dial tcp 10.206.213.15:443: i/o timeout" backup=velero/bk6 cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/ivd/ivd_protected_entity_type_manager.go:63" pluginName=velero-plugin-for-vsphere
time="2022-06-10T08:40:10Z" level=info msg="RetrieveVSLFromVeleroBSLs: Failed to get Velero default backup storage location, attempting to find available BSL" backup=velero/bk6 cmd=/plugins/velero-plugin-for-vsphere error="backupstoragelocations.velero.io \"default\" not found" logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/utils/utils.go:308" pluginName=velero-plugin-for-vsphere
time="2022-06-10T08:40:40Z" level=error msg="Failed to create a Snapshot CR: Phase=SnapshotFailed, err=createSnapshot: Failed at calling SnapshotManager CreateSnapshot from peID : , Error: Could not retrieve components: Could not find subcomponent PEID for pvc:kibishii/kibishii-data-kibishii-deployment-1 kibishii kibishii-data-kibishii-deployment-1: Could not get Protected Entity for PV ivd:701b1893-721a-47cc-881f-81ba3a008b76: GetProtectedEntity from base PETM failed for PEID ivd:701b1893-721a-47cc-881f-81ba3a008b76: Post \"https://10.206.213.15:443/sdk\": dial tcp 10.206.213.15:443: i/o timeout" backup=velero/bk6 cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/backup_pvc_action_plugin.go:160" pluginName=velero-plugin-for-vsphere
time="2022-06-10T08:40:40Z" level=info msg="1 errors encountered backup up item" backup=velero/bk6 logSource="pkg/backup/backup.go:413" name=kibishii-deployment-1
time="2022-06-10T08:40:40Z" level=error msg="Error backing up item" backup=velero/bk6 error="error executing custom action (groupResource=persistentvolumeclaims, namespace=kibishii, name=kibishii-data-kibishii-deployment-1): rpc error: code = Unknown desc = Failed to create a Snapshot CR: Phase=SnapshotFailed, err=createSnapshot: Failed at calling SnapshotManager CreateSnapshot from peID : , Error: Could not retrieve components: Could not find subcomponent PEID for pvc:kibishii/kibishii-data-kibishii-deployment-1 kibishii kibishii-data-kibishii-deployment-1: Could not get Protected Entity for PV ivd:701b1893-721a-47cc-881f-81ba3a008b76: GetProtectedEntity from base PETM failed for PEID ivd:701b1893-721a-47cc-881f-81ba3a008b76: Post \"https://10.206.213.15:443/sdk\": dial tcp 10.206.213.15:443: i/o timeout" logSource="pkg/backup/backup.go:417" name=kibishii-deployment-1

```

**What did you expect to happen:**
Backup should be Completed.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- Velero vSphere plugin version: vsphereveleroplugin/velero-plugin-for-vsphere:v1.3.1
- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
@danfengliu please double check with the dev of vsphere-plugin if they wanna fix it in the plugin code.

The deeper root cause is that vsphere plugin is trying to do too much work in backup item plugin.

**Comment by lintongj** [comment]
> @danfengliu please double check with the dev of vsphere-plugin if they wanna fix it in the plugin code.
> 
> The deeper root cause is that vsphere plugin is trying to do too much work in backup item plugin.

Maybe not. 

My understanding is, the opt-out volume is expected to be backed up by velero-plugin-for-vsphere while all other volumes would be backed up by Restic. Based on the information above, I didn't see any issue with velero-plugin-for-vsphere itself. However, in the test environment with this test, looks like the vSphere connection is not well established, so the snapshot API call to vSphere would fail. Please double check the test environment and try the test again.

**Comment by lintongj** [comment]
As you are aware of, velero supports both opt-in and opt-out approach for restic backup. Along with annotations, `backup.velero.io/backup-volumes` and `backup.velero.io/backup-volumes-excludes`. That is how "hybrid mode" in backup is supported. velero-plugin-for-vsphere has [code](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/3ea7621825ade756a29b6e136873cb43c60841c9/pkg/plugin/backup_pvc_action_plugin.go#L104) to keeps aligned with this. 

In your case, `default-volumes-to-restic` is enabled while one volume is annotated with `backup.velero.io/backup-volumes-excludes`. velero-plugin-for-vsphere would identify it and only backup the excluded volume.

BTW, `--snapshot-volumes` would only apply at the PV level. It would has no effect in velero-plugin-for-vsphere, as we run backup at the PVC level.

**Comment by danfengliu** [comment]
@lintongj  Got it, your comment is very clear for me, I see why this happened, my backup creation command missing the option --snapshot-volumes=false, so "hybrid mode" occurred, I think this is an Velero issue instead of velero-plugin-for-vsphere.
