### ISSUE TITLE
Panic error isn't thrown out in generic controller 

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#4984]
There is a [wg.Wait()](https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/generic_controller.go#L70) inside the `defer` code block in the generic controller. 

If any panic(e.g. [here](https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/generic_controller.go#L101)) occurs, the goroutine will block on the `wg.Wait()` as no one releases the waited goroutines. So the panic error will not be thrown out.

The panic error will be thrown out only when the process is terminated for some reason, e.g. send ctrl+c to the process, this will cause [the context to be canceled](https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/generic_controller.go#L106-L107), so the waited goroutines are released. 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
This will be probably gone when the controllers are all refactored using the kubebuilder v3.

**Comment by blackpiglet** [comment]
GenericController is deleted completely after backup controller adopting the controller-runtime framework.
