### ISSUE TITLE
unable to locate ObjectStore plugin named velero.io/azure issue:3333 / helm install

### ISSUE THREAD

**Issue by omichels** [vmware-tanzu/velero#5001]
(closed) issue:3333  still happens when using helm-charts for intallation

see my incomplete work for a better helm-chart in 
https://github.com/omichels/velero-backup-helm-charts

**Comment by blackpiglet** [comment]
@omichels 
Thanks.
I think the issue should be created in repository https://github.com/vmware-tanzu/helm-charts.
Since you already had a draft of fix, could you help to create a PR, too?

**Comment by omichels** [comment]
@blackpiglet sure, i am working on a PR

**Comment by omichels** [comment]
created a PR

https://github.com/vmware-tanzu/helm-charts/pull/382

**Comment by omichels** [comment]
installing velero via helm-charts on azure results in missing plugins, as the dependency between .Values.initContainers and .Values.configuration.provider is very hard to discover, esp. since there are not sensible defaults in the values.yaml for the major clouds.
