### ISSUE TITLE
new RestoreStatus feature tries to restore status when spec field absent

### ISSUE THREAD

**Issue by sseago** [vmware-tanzu/velero#5007]
**What steps did you take and what happened:**
When `Spec.RestoreStatus` is absent, no status fields should be restored. Current behavior is that when absent, every status field is restored. I created a restore without specifying any restore status includes or excludes, and velero attempted to restore status for everything.

**What did you expect to happen:**
I expected status not to be restored anywhere

**The following information will help us better understand what's going on**:
The implementation tries to create an "exclude all" field by specifying "*" for excludes, but the "*" wildcard is only valid on includes. The fix is to leave this var nil if unspecified, and check for nil when determining whether to restore status.

(PR forthcoming)

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): main
- Kubernetes version (use `kubectl version`): 1.21
- Kubernetes installer & version: Amazon eks
- Cloud provider or hardware configuration: amazon EKS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
reopening till it's cherry-picked to v1.9 branch.

**Comment by qiuming-best** [comment]
[it](https://github.com/vmware-tanzu/velero/pull/5015) has been cherry-picked to v1.9, so close it
