### ISSUE TITLE
Update Kubernetes dependency to 0.24.0

### ISSUE THREAD

**Issue by kcboyle** [vmware-tanzu/velero#5009]
**Describe the problem/challenge you have**
When updating k8s.io to v0.24.0 in my project, I get failures in velero cannot update
Example Error:
```
github.com/vmware-tanzu/velero/pkg/builder
# github.com/vmware-tanzu/velero/pkg/builder
../../go/pkg/mod/github.com/vmware-tanzu/velero@v1.8.1/pkg/builder/object_meta.go:124:7: obj.SetClusterName undefined (type "k8s.io/apimachinery/pkg/apis/meta/v1".Object has no field or method SetClusterName)
make: *** [build-real] Error 2
```

**Describe the solution you'd like**
Update k8s.io components from v0.22.2 to v0.24.0

**Environment:**
N/A

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
@kcboyle 
Thanks for bringing this up. Will do it, but may need to wait for a while. Velero is going to release v1.9 in next week, so except release blocking bug, no other change will go in v1.9.
This will be done on main branch, and it should be included in v1.10 release.

Could you also give more information about how your use case of Velero? Looks like Velero is imported as a library in your project, is that right?

**Comment by reasonerjt** [comment]
I wish to suggest we refrain from updating the k8s.io lib in upstream considering it has to support older version of kubernetes.

**Comment by ywk253100** [comment]
Done by https://github.com/vmware-tanzu/velero/pull/5471 and https://github.com/vmware-tanzu/velero/pull/5472
