### ISSUE TITLE
Restore with --namespace-mappings not changing namespace in spec.claimRef section of PV

### ISSUE THREAD

**Issue by honterlin** [vmware-tanzu/velero#5010]
---
name: Bug report
about: Restore with --namespace-mappings not changing namespace in spec.claimRef section of PV

---

**What steps did you take and what happened:**
Created a backup of namespace gitlab
velero backup create gitlab-backup --include-namespaces gitlab

Restored backup with --namespace-mappings into a new namespace gitlab-clone
velero restore create --from-backup gitlab-backup --namespace-mappings gitlab:gitlab-clone

**What did you expect to happen:**
PVs  to correctly bind with PVCs in new namespace gitlab-clone.
Found spec.claimRef.namespace did not change.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
N/A

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):v1.7.1 4729274d07eae7e788233d5c995d7f45f40c9c61
- Velero features (use `velero client config get features`): 
features: <NOT SET>

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): - RuntimeOS: windows - RuntimeArch: amd64

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
@honterlin 
Hi, I tried to reproduce this with v1.7.1 in my environment, but I didn't meet the problem you described. After reading the remapClaimRefNS code, I think there is a possibility the `--namespace-mappings` parameter value doesn't match. Could you set the log-level to debug to see whether there are more related information printed? 
If I'm right, there should be a log like this 
"Persistent volume does not need to have the claimRef.namespace remapped because it's not claimed by a PVC in a namespace that's being remapped".


``` go
func remapClaimRefNS(ctx *restoreContext, obj *unstructured.Unstructured) (bool, error) {
	if len(ctx.restore.Spec.NamespaceMapping) == 0 {
		ctx.log.Debug("Persistent volume does not need to have the claimRef.namespace remapped because restore is not remapping any namespaces")
		return false, nil
	}

	// Conversion to the real type here is more readable than all the error checking
	// involved with reading each field individually.
	pv := new(v1.PersistentVolume)
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(obj.Object, pv); err != nil {
		return false, errors.Wrapf(err, "error converting persistent volume to structured")
	}

	if pv.Spec.ClaimRef == nil {
		ctx.log.Debugf("Persistent volume does not need to have the claimRef.namespace remapped because it's not claimed")
		return false, nil
	}

	targetNS, ok := ctx.restore.Spec.NamespaceMapping[pv.Spec.ClaimRef.Namespace]

	if !ok {
		ctx.log.Debugf("Persistent volume does not need to have the claimRef.namespace remapped because it's not claimed by a PVC in a namespace that's being remapped")
		return false, nil
	}

	err := unstructured.SetNestedField(obj.Object, targetNS, "spec", "claimRef", "namespace")
	if err != nil {
		return false, err
	}
	ctx.log.Debug("Persistent volume's namespace was updated")
	return true, nil
}
```

**Comment by blackpiglet** [comment]
@honterlin 
Hi, are your problem solved?

**Comment by blackpiglet** [comment]
Close by now. If problem is still there, please reopen for trace again.
