### ISSUE TITLE
The restore stay "New" status (restic)

### ISSUE THREAD

**Issue by STYNET** [vmware-tanzu/velero#5014]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
`velero restore create --from-backup cluster-backup-day-20220616050044 --include-namespaces foo`

**What did you expect to happen:**
Restoring of foo namespace's 

**The following information will help us better understand what's going on**:
The status stay at "New"

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 
```
velero debug --restore  cluster-backup-day-20220616050044-20220616132215
2022/06/16 14:15:23 Collecting velero resources in namespace: velero
An error occurred: exec failed: Traceback (most recent call last):
  velero-debug-collector:23:13: in <toplevel>
  <builtin>: in kube_get
Error: could not initialize search client: invalid configuration: [context was not found for specified context: kubernetes-admin@XXX, cluster has no server defined]

```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
My backup contains PV/PVC with Restic.
I don't remove namespace before restore.

**Environment:**

- Velero version (use `velero version`): v1.8.1 (Client & Server)
- Velero features (use `velero client config get features`): EnableCSI
- Kubernetes version (use `kubectl version`): Client: v1.24.1
- Kubernetes installer & version: Server: v1.22.9
- Cloud provider or hardware configuration: OVH
- OS (e.g. from `/etc/os-release`): unknown

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
@STYNET 
Could you run `velero debug` command without `--restore` parameter to collect log and information?

**Comment by STYNET** [comment]
of course.. but it's same :
```
velero debug
2022/06/16 16:15:42 Collecting velero resources in namespace: velero
An error occurred: exec failed: Traceback (most recent call last):
  velero-debug-collector:23:13: in <toplevel>
  <builtin>: in kube_get

Error: could not initialize search client: invalid configuration: [context was not found for specified context: kubernetes-admin@XXX, cluster has no server defined]
```

**Comment by STYNET** [comment]
I managed to restore like this:
- I restarted the Velero pod
- I previously deleted the namespace before launching the restoration of it.

Question: do you have to delete the namespace before a restore?

**Comment by blackpiglet** [comment]
```
Error: could not initialize search client: invalid configuration: [context was not found for specified context: kubernetes-admin@XXX, cluster has no server defined]
```
I think this is because Velero failed to read a valid kubeconfig from context kubernetes-admin@XXX. Looks like the kubeconfig was changed, and running Velero pod didn't get update, then restart Velero pod resolve the issue.

**Comment by STYNET** [comment]
Thanks blackpiglet.
But I don't think that this a orgin problem.

I use a multiples contexts :
```
$ echo $KUBECONFIG 
~/.kube/config:~/.kube/config:/home/xxxxx/Documents/XXX/k8s-ovh/kubeconfig.yml
```

The context error message disappears if i reconfigure my KUBECONFIG with only one context :
`$ export KUBECONFIG='~/.kube/config:/home/xxxxx/Documents/XXX/k8s-ovh/kubeconfig.yml'`

```
$ velero debug 
2022/06/17 14:54:32 Collecting velero resources in namespace: velero
2022/06/17 14:54:34 Collecting velero deployment logs in namespace: velero
2022/06/17 14:54:35 Generated debug information bundle: ~/bundle-2022-06-17-14-54-32.tar.gz
```

it appears that is a bug Velero ?!

**Comment by blackpiglet** [comment]
Right, the original problem is some different from this one, but it still is related to kubeconfig information.
I cannot confirm right now. I think Velero reading the configuration from a in-cluster way. That should be included in controller-runtime library. I couldn't recall whether it read kubeconfig dynamically.
I can check with that later, but to me, this should be enhanced in controller-runtime related code.
