### ISSUE TITLE
Confusion of option --snapshot-volumes in Velero create backup CLI 

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#5019]
**What steps did you take and what happened:**
According to description in [Velero official doc](https://velero.io/docs/v1.8/how-velero-works/#:~:text=By%20default%2C%20velero%20backup%20create%20makes%20disk%20snapshots%20of%20any%20persistent%20volumes.%20You%20can%20adjust%20the%20snapshots%20by%20specifying%20additional%20flags.%20Run%20velero%20backup%20create%20%2D%2Dhelp%20to%20see%20available%20flags.%20Snapshots%20can%20be%20disabled%20with%20the%20option%20%2D%2Dsnapshot%2Dvolumes%3Dfalse.), the only way to disable disk snapshot feature is by setting the option --snapshot-volumes=false, even if a backup command without option --snapshot-volumes followed by can not disable disk snapshot feature, according to the common sense of semantics of command line, if --snapshot-volumes is not added into command line, it should be equal to `"--snapshot-volumes=false"`, but the fact is it equal to` "--snapshot-volumes=true"` or `"--snapshot-volumes"`, so it's kind of confuse if we are reading command help `--snapshot-volumes optionalBool[=true]            Take snapshots of PersistentVolumes as part of the backup.`, `--snapshot-volumes=true ` seems useless here.

**What did you expect to happen:**
Option 1:
Update Velero CLI help to identify --snapshot-volumes is only used as `--snapshot-volumes=false` or do nothing (which means taking snapshot as default)

Option 2:
Making sense of CLI semantics.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
Let's just update the inline help that the default value is true when the param is not set.

**Comment by blackpiglet** [comment]
@danfengliu 
* I'll update description of parameter `--snapshot-volumes` to state that if the parameter is not present, it will be treated as setting true.
* Per my understanding, the second part of the issue is about this part's grammar: `--snapshot-volumes optionalBool[=true]`. I think this is how `github.com/spf13/flag` works. Parameter `--snapshot-volumes` has `NoOptDefVal` set to `true`. This means if this parameter is present in the command line, but no value is set, `true` will be set as the default value. `github.com/spf13/flag` will print the default value alongside with type.
https://github.com/spf13/pflag/blob/d5e0c0615acee7028e1e2740a11102313be88de1/flag.go#L706-L721

**Comment by danfengliu** [comment]
@blackpiglet  I totally agree your 2 clarifications, I have no objection on using --snapshot-volumes with no value set and as to be true.
