### ISSUE TITLE
CSI snapshot info not in backup description

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#5029]
**What steps did you take and what happened:**
Install velero with CSI feature flag enabled, create backup to include a namespace where there are PVC bound to PV provisioned by EBS CSI driver.
```
./velero backup create csi-test-bak --include-namespaces kibishii-non-csi,kibishii-csi --snapshot-volumes --wait
```

After the backup completes, I don't see CSI snapshot information in the output of 
```
./velero backup describe csi-test-bak
```
Though the CSI plugin seemed to take the snapshot successfully.
**What did you expect to happen:**
I expect there is a line like 
```
CSI Volume Snapshots:  2 included
``` 
in the output.
**The following information will help us better understand what's going on**:

[bundle-2022-06-19-22-48-03.tar.gz](https://github.com/vmware-tanzu/velero/files/8935746/bundle-2022-06-19-22-48-03.tar.gz)

**Environment:**

- Velero version (use `velero version`):  v1.9.0-rc.1 with CSI plugin v0.3.0-rc.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.22
- Kubernetes installer & version: EKS via eksctl 0.99
- Cloud provider or hardware configuration: EKS
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Same issue as #4759 
Need to run `velero client config set features=EnableCSI` to let velero command shows CSI related output.

**Comment by reasonerjt** [comment]
Yes, thanks.

Although I think one option would be too retrieve CSI snapshot information regardless the EnableCSI feature flag, since it's clearly documented in 
https://velero.io/docs/main/customize-installation/#:~:text=edit%20daemonset/restic-,Enable,-client%20side%20features

I think we may keep it as is.

We can open another issue to simplify the setting of feature flag, Ideally it should only set once in the installation.
