### ISSUE TITLE
Skip unmounted volumes from backup rather than erroring out

### ISSUE THREAD

**Issue by gsadhani** [vmware-tanzu/velero#5036]
**Describe the problem/challenge you have**
While backing up an application we observed the following error:

`pod volume backup failed: error getting volume path on host: expected one matching path, got 0`

On debugging it was due to missing volume mounts configuration on the pod. The volume was configured was configured in the `volumes` section but missed in the `volumeMounts` section.

**Describe the solution you'd like**
It would be great if Velero skipped such volumes from the backup rather than erroring out, as the volumes are not really mounted on the pod.

**Anything else you would like to add:**
None

**Environment:**

- Velero version (use `velero version`): 1.8.1
- Kubernetes version (use `kubectl version`): 1.22
- Kubernetes installer & version:
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from `/etc/os-release`): Photon

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
Yep, thanks @qiuming-best 

@gsadhani I believe this can be closed?

**Comment by gsadhani** [comment]
@reasonerjt  thanks for taking a look, the title was misleading, I have fixed it now. Can we skip unmounted volumes from backup?

**Comment by qiuming-best** [comment]
@gsadhani in velero v1.9.0  will fix this issue by skipping the not mounted volume

**Comment by qiuming-best** [comment]
@gsadhani  [here](https://github.com/vmware-tanzu/velero/pull/4497) is the related pr

**Comment by qiuming-best** [comment]
this issue is been fix in this pr https://github.com/vmware-tanzu/velero/pull/4497, so closed now
