### ISSUE TITLE
Support for volume snapshot groups

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#505]
Some storage providers have the ability to coordinate a snapshot across multiple volumes simultaneously. It would be nice if Ark could support this for those providers. We'll need to determine how to model this as well as what the UI/UX looks like.

**Comment by ncdc** [comment]
cc @disrani-px @jbeda @dhanmm @emuetzel

**Comment by rosskukulinski** [comment]
Which storage providers currently offer this feature?

How is this snapshot process different from Ark doing backups across PVs with labelSelector?

**Comment by ncdc** [comment]
I know portworx does. There's an RFE to add it to ceph. I think dotmesh might.

Ark would need to somehow find all the PVs in a group and then issue a provider-specific command to tell the provider to snapshot them as a group. It's an atomic, consistent, single action instead of 1 per PV.

**Comment by rosskukulinski** [comment]
So this would enable atomic backups for things like scale-out databases (mongo, elastic, etc) and/or multi-tier apps that have data consistency problems (e.g. wordpress content + mysql data)?

**Comment by ncdc** [comment]
Yes, any time when you'd want to coordinate an atomic point-in-time snapshot of multiple volumes.

**Comment by dymurray** [comment]
Is this issue a good place to track the Data Protection Working Groups attempt to solve the problem consistency groups?

I am curious if Velero intends to provide first class support for the ability to take a backup that includes an applications entire state at a single moment in time. This is being worked on upstream and I'm wondering if that is the best place to solve this problem or if it's something Velero is interested in solving.

**Comment by skriss** [comment]
@dymurray late in responding here, but ideally I think we want to use/contribute to upstream solutions as much as possible. We definitely do not have a plan/design in mind for this in Velero right now.

**Comment by eleanor-millman** [comment]
Closing because it should fall out of the proposed Astrolabe decoupling.
