### ISSUE TITLE
Integrate with Kopia for pod volume backup/restore

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#5050]
We'll provide a way to integrate with Kopia's uploader and repository for filesystem based backup/restore.  
Along with this work, we'll introduce the concept of "unified repository" to velero, and in the future, use it as the single target for all backup data.

We'll reuse the existing workflow and CR for restic repository, pod volume backup/restore but provide a switch for the code path, so user can choose to use restic(mostly existing code path) or kopia as the technology for the repository.

An investigation has been done in v1.9: https://github.com/vmware-tanzu/velero/issues/4538#issuecomment-1119231618

The tech design (pending on approval):  https://github.com/vmware-tanzu/velero/pull/4926

**Comment by iamjackhu** [comment]
How about the helm chart of velero? 
Has it intergrated with Kopia?

**Comment by qiuming-best** [comment]
@iamjackhu yes, We are working on the helm chart for v1.10.0, and it will be compatible with Resitc at the meantime, it will be integrated with Kopia
