### ISSUE TITLE
Partially failed backup for keycloak application

### ISSUE THREAD

**Issue by mshanmu** [vmware-tanzu/velero#5059]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Backup failed for a keycloak application with the following error,

time="2022-06-28" level=error msg="Error backing up item" backup=velero/keycloak-20220628 error="pod volume backup failed: error creating temp restic credentials file: unable to open credentials file for writing: open /tmp/credentials/velero/velero-restic-credentials-repository-password: no such file or directory" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:184" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:417" name=keycloak-postgresql-postgresql-4

$velero backup describe --details keycloak-20220628 
Name: keycloak-20220628 
Namespace: velero
<snip>
Phase: PartiallyFailed

Errors: 1
Warnings: 0
<snip>
Restic Backups:
Completed:
keycloak/keycloak-postgresql-postgresql-0: data
keycloak/keycloak-postgresql-postgresql-1: data
keycloak/keycloak-postgresql-postgresql-2: data
keycloak/keycloak-postgresql-postgresql-3: data
Failed:
keycloak/keycloak-postgresql-postgresql-4: data
$

As you can see, it is really weird that for first 4 restic backups, it works fine and only the 5th one fails consistently with the credentials error.

This started happening after scaling up the postgres replicas from 4 to 5. Deleting the velero pod did not help.

**What did you expect to happen:**
Backup to succeed

**The following information will help us better understand what's going on**:

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.8.1
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): v1.21.3
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
@mshanmu 
Looks like the dir creation for "/tmp/credentials/velero" failed for the newly joined pod.
Could you check the existence of "/tmp" folder in the new pod and try to create the folders "credentials/velero" and see what happens?

**Comment by mshanmu** [comment]
> @mshanmu Looks like the dir creation for "/tmp/credentials/velero" failed for the newly joined pod. Could you check the existence of "/tmp/credentials/velero" folder in the new pod after the backup fails?

@Lyndon-Li , I don't see /tmp/credentials/velero directory created in any of the postgres pods.

**Comment by Lyndon-Li** [comment]
Could you help to collect Velero log through the `velero debug` command?

**Comment by mshanmu** [comment]
@Lyndon-Li  Re-creating the postgres pod fixed the issue. So, you can close it.
