### ISSUE TITLE
Add a parameter "uploader-type" to velero server

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#5062]
Add the parameter to the command line to velero server to determine the repository type during backup.

We should also make sure that the backup controller can consume this parameter to create bakcuprepsitory CR accordingly.

In this task, we'll make sure the Restic path is not broken.
The actual work to Init and connect to the Kopia repo will be covered in another issue.

**Comment by albrookesplowman** [comment]
We are getting an error when the pod is starting saying that the uploader-type is an unknown flag... We are running the latest version of velero (1.10) but I have tried it with v1.9 and i get the same problem.... Is there a workaround or a solution

**Comment by draghuram** [comment]
Can you describe how you installed Velero? You can edit the deployment and remove the option "--uploader-type" but it is better to understand the root cause first.

**Comment by albrookesplowman** [comment]
We are deploying via the helm chart

**Comment by albrookesplowman** [comment]
We have it in an azure yaml pipeline which simply applies our value.yaml
file to the helm chart in your repo.  We would prefer not to use a modified
helm chart though
