### ISSUE TITLE
File System Uploader - Backup

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#5073]
Epic: #5050 
Design: #4926 

Add the code for File System Uploader backup, include:

- Setup Kopia Uploader for Velero, i.e. Kopia Uploader options and policies for backup
- Call Kopia Uploader to back up a specified path
- Backup snapshot information design, preservation and retrieve
- Backup output to upper layer
- Backup progress monitor and adapter
- UT design and implementation

**Comment by qiuming-best** [comment]
Codes merged
