### ISSUE TITLE
File System Uploader - Restore

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#5074]
Epic: #5050 
Design: #4926 

Add the code for File System Uploader restore, include:

- Setup Kopia Uploader for Velero, i.e. Kopia Uploader options and policies for restore
- Call Kopia Uploader to restore from a specified snapshot ID
- Restore output to upper layer
- Restore progress monitor and adapter
- UT design and implementation

**Comment by qiuming-best** [comment]
codes merged
