### ISSUE TITLE
Velero Kopia Integration - Performance Test & Tuning

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#5082]
Epic: #5050 
Design: #4926 

Do e2e performance testing and tuning after Kopia Uploader & Unified Repository is integrated, include:

- Prepare testing environment
- Code changes for performance tuning
- Generate benchmarks and performance guidance doc

**Comment by qiuming-best** [comment]
[here](https://docs.google.com/document/d/1yA2DndbmYVg6b5wUF0YoyX2qz2MVwDrlCQjyVbt8Jz4/edit?usp=sharing) is the report for performance test
