### ISSUE TITLE
Velero Kopia Integration - Upgrade Verification & Guide

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#5083]
Epic: #5050 
Design: #4926 

Provide a upgrade guide and make sure it works for users using CLI, where he can upgrade velero to v1.10, incl. update the server cli parameters, renaming CRD etc without having to uninstall velero and remove all the CRs in velero's namespace.

Some scenarios need to cover:

- Create backup & restore of a namespace with the old build
- Upgrade to v1.10
- Create (scheduled & non-scheduled) backup & restore of the same namespace with the new build under Restic path
- Create (scheduled & non-scheduled) backup & restore of the same namespace with the new build under Kopia path
- Multiple resources exist: BSL, BackupRepository, backup, restore, schedule, PVB, PVR
- Some resources & flags have been renamed, i.e., NodeAgent daemonset, BackupRepository, default-volumes-to-fs-backup
- The query, modify, delete of these resources should have no problem and the detailed results should be recorded in the doc

Output: Upgrade Guidance Doc

**Comment by reasonerjt** [comment]
The doc work may slip of of FC

**Comment by Lyndon-Li** [comment]
Verification is finished. Guidance doc is being prepared.

**Comment by Lyndon-Li** [comment]
fixed by #5468
