### ISSUE TITLE
Velero Kopia Integration - Backup Sync

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#5086]
Epic: #5050 
Design: #4926 

Add the code change to support for Velero Kopia Integration, include:

- Sync backup created by different paths
- Sync old backup under the new release
- UT

**Comment by reasonerjt** [comment]
This may cause conflict with the task to refactor backup sync controller with kubebuilder v3.
We'll sync with @blackpiglet when start working on this.

**Comment by ywk253100** [comment]
Close this issue as no change is needed.
