### ISSUE TITLE
Restore stuck using restic - Volumes identified by podname

### ISSUE THREAD

**Issue by navilg** [vmware-tanzu/velero#5087]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I had deleted a deployment, pvc and a configmap in a namespace. Many pods running in same namespace controlled by a controller (deployment or rs) were restarted either by deleting pod directly or rollout restart. 

When I tried to restore the deployment, pvc and configmap which I had deleted before, they are restored but the status of restore still in inprogress. When I checked the details, I see that restic is trying to restore other volumes whose pods were restarted and their podname is changed after backup.

This can be reproduced using below steps:

1. Have velero installed and integrated with restic.
2. Create a backup.
3. Restart some of deployments so that new pods come up with new random generated name.
4. Delete one or two deployment, pvc/pv.
5. Try to restore the depleted resources.

This will try to restore other volumes as well whose pods were restarted and created with new names.

**What did you expect to happen:**

Velero/restic should have ignored other volumes. It should not be trying to restore volumes which are already present based on podname.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Command used to restore:

```
velero create restore restore-v1.8.1-202207041327 --from-backup v1.8.1 --include-namespaces=ethan --exclude-resources=ingresses.extensions,ingresses.networking.k8s.io
```

Describe restore:

```
Name:         restore-v1.8.1-202207041327
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:                                 InProgress
Estimated total items to be restored:  239
Items restored so far:                 239

Started:    2022-07-04 07:57:43 +0000 UTC
Completed:  <n/a>

Backup:  v1.8.1

Namespaces:
  Included:  ethan
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        ingresses.extensions, ingresses.networking.k8s.io, nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Restic Restores:
  Completed:
    ethan/jenkins-59665f5457-wj85f: jenkins-home
  New:
    ethan/gitlab-848d544df5-h6qxw: gitlab-pvc
    ethan/keycloak-6c6bcddbb9-xd7dx: theme-volume
    ethan/keycloak-postgres-6564f4586c-pvws6: postgres-pvc
    ethan/mongo-7dbf49f777-z2qbs: mongo-data

Preserve Service NodePorts:  auto
ubuntu@ip-10-0-18-10:~/userscripts/apply_ssl$ velero restore describe restore-v1.8.1-202207041327 --details
Name:         restore-v1.8.1-202207041327
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:                                 InProgress
Estimated total items to be restored:  239
Items restored so far:                 239

Started:    2022-07-04 07:57:43 +0000 UTC
Completed:  <n/a>

Backup:  v1.8.1

Namespaces:
  Included:  ethan
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        ingresses.extensions, ingresses.networking.k8s.io, nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Restic Restores:
  Completed:
    ethan/jenkins-59665f5457-wj85f: jenkins-home
  New:
    ethan/gitlab-848d544df5-h6qxw: gitlab-pvc
    ethan/keycloak-6c6bcddbb9-xd7dx: theme-volume
    ethan/keycloak-postgres-6564f4586c-pvws6: postgres-pvc
    ethan/mongo-7dbf49f777-z2qbs: mongo-data

Preserve Service NodePorts:  auto
```

**Environment:**

- Velero version (use `velero version`): 1.8.1
- Velero features (use `velero client config get features`): None
- Kubernetes version (use `kubectl version`): v1.20.13
- Kubernetes installer & version: kOps 1.20.0
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04 LTS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
@navilg I agree this problem could be possible in real world but I am afraid it is not a valid case that Velero could handle at present:

- If a namespace is backed up, you can restore the entire namespace or part of the resources but keep everything else as is
- If some controllers have been restarted as the current case, the controllers may do anything to the resources, for example, as mentioned in the case, the resources have been recreated and renamed
- If we still do partial restore at this time, Velero has no way to identify the renamed resources. This is simply like:
  - We've backed up an object
  - Then the object is recreated and renamed manually or by another application
  - We do a restore to the object
  - There is no way for any backup solution to identify this change because the change is out of the scope of the backup tool

Therefore, in this case, we should do a full namespace restore instead of partial restore.
If you have any proposal to handle this case, please just suggest.

**Comment by Lyndon-Li** [comment]
I am closing this issue. Feel free to reopen it for any new requirement.
