### ISSUE TITLE
Missing custom label in scheduled backup

### ISSUE THREAD

**Issue by crdemon09** [vmware-tanzu/velero#5090]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

1. Create a schedule policy
2. Insert a custom label to a backup object while backup is In Progress
3. See the backup completed
4. check velero-backup.json file inside backup folder
Result: custom label is missing in velero-backup.json
**What did you expect to happen:**
Expected result: custom label should be present in velero-backup.json

Example of label : custom.label/enabled:true
**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.8.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.21.4
- Kubernetes installer & version: k3s 1.21.4
- Cloud provider or hardware configuration: on-premise
- OS (e.g. from `/etc/os-release`): centos 7

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
You can use `--labels` option to custom the scheduled backup when creating the schedule.

**Comment by crdemon09** [comment]
@ywk253100  I want to modify backup label created by schedule and not set schedule backup.

**Comment by cleverhu** [comment]
I checked for it, the backup which will write to the json file is the copy of origin backup. So it doesn't works when you try to modify it when progress.
