### ISSUE TITLE
Renaming the restic parameters in CLI  and resources 

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#5093]
Per the design of unified backup repository, the daemonSet should be renamed to `node-agent`

There are parameters in installation and other subcommands of velero for restic support.  We need to rename them to more neutral terms, and add new parameters for kopia as needed.

**Comment by reasonerjt** [comment]
@Lyndon-Li can this be closed?

**Comment by Lyndon-Li** [comment]
There is one more open PR connects to this issue #5432, so need to close it after the PR is merged.
