### ISSUE TITLE
velero-plugin-for-aws lateast version (V1.5.0) image docker is failed to mount

### ISSUE THREAD

**Issue by shaynagar1** [vmware-tanzu/velero#5100]
**What steps did you take and what happened:**
Creating a docker file from existing latest image (v1.5.0) and creating container using containerd on linux platform

**What did you expect to happen:**
Working docker container but I got the following error:
```
Error: failed to create containerd container: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount068642443: open /var/lib/containerd/tmpmounts/containerd-mount068642443/etc/passwd: no such file or directory
```

**Anything else you would like to add:**
I think that for some reason this image was build with wrong platform parameter.
In addition, previous version is working correctly. 

**Environment:**
linux

**Comment by ywk253100** [comment]
We changed the base image to `scratch` in v1.5.0 to keep the image thin and contain fewer vulnerabilities. The image contains nothing except the plugin go binary, so no `/etc/passwd` file is there inside the container.

BTW, why do you create an image based the plugin? What's your use case? Does the plugin work with Velero as expected?
