### ISSUE TITLE
velero-plugin-for-csi: docker file cp command broken

### ISSUE THREAD

**Issue by migs35323** [vmware-tanzu/velero#5103]
version 0.3.0 (currently the latest one)

the pod was crashing in kubernetes so i manually grabbed the docker file and tried to run it, i get this output:
cp: can't create '/target/./velero-plugin-for-csi': Permission denied

**Comment by ywk253100** [comment]
Cannot the pod be restarted automatically? Why did you run the container manually?

**Comment by migs35323** [comment]
i am trying to run the plugin in a raspberry pi cluster, ARM64
i cloned the repo, used the make file trying to build the image and when i tried to run in it doesn't work (some fork exec error ), so i tried to manually run the docker hub container in my local machine to troubleshoot and got the above result
from what i could gather the only thing the container does is to copy the plugin file to the target folder which is not working in my case for some reason
