### ISSUE TITLE
File System Uploader - Incremental Backup

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#5106]
Add the code to trigger Kopia Uploader's incremental backup
Verify the behavior is correct for the incremental backup, for example, backup size should comply with data change
Verify data could be restored correctly from an incremental backup
Verify data could be restored correctly from an incremental backup whose parent backup has been deleted

**Comment by qiuming-best** [comment]
I've tested a restore from an increment backup in which the parent backup is deleted, the result is ok. So close it
