### ISSUE TITLE
can move internal/credentials to pkg/credentials ?

### ISSUE THREAD

**Issue by SchoIsles** [vmware-tanzu/velero#5111]
I want to import pkg/restic in my project.
but pkg/restic/repository_manager.go has imported "github.com/vmware-tanzu/velero/internal/credentials",
the velero's internal pkg can't be loaded in my project,
should we move the internal/credentials to pkg/credentials

**Comment by reasonerjt** [comment]
We don't have such plan.
And please be reminded that to incorporate the [unified repository design ](https://github.com/vmware-tanzu/velero/pull/4926)
The whole workflow, including the codepath for restic will be heavily reworked.

**Comment by SchoIsles** [comment]
Thanks!
