### ISSUE TITLE
In version 1.9, the status of BSL is not displayed

### ISSUE THREAD

**Issue by huiyichanmian** [vmware-tanzu/velero#5127]
Description：
When I used version 1.9, the created BSL did not have any status, as shown below:
```shell
kubectl get bsl -n test5
NAME      PHASE   LAST VALIDATED   AGE     DEFAULT
default                            8m23s   true
```
When I switch to 1.8, the status of BSL is normal, as shown below:
```shell
kubectl get bsl -n test3
NAME             PHASE         LAST VALIDATED   AGE   DEFAULT
6-4-info-ad      Available     117s             14d
default          Unavailable   3m50s            14d   true
```

**Comment by blackpiglet** [comment]
@huiyichanmian 
Hi, I tried to reproduce this on my EKS environment with Velero v1.9.0, but it didn't happen.
``` bash
velero install --features=EnableCSI --provider aws --image velero/velero:v1.9.0 --plugins velero/velero-plugin-for-aws:v1.5.0,velero/velero-plugin-for-csi:v0.3.0 --bucket jxun1 --secret-file ~/Documents/credentials-velero-aws --backup-location-config region=us-west-2 --snapshot-location-config region=us-west-2 --use-restic

k get bsl -n velero
NAME      PHASE       LAST VALIDATED   AGE   DEFAULT
default   Available   13s              22s   true

velero version
Client:
	Version: v1.9.0
	Git commit: 6021f148c4d7721285e815a3e1af761262bff029
Server:
	Version: v1.9.0
```

IMO, this looks like Velero doesn't watch on the BSL. I noticed the unvalidated BSL is in namespace test5. Could you please check whether Velero is configured to watch BSL CR in test5 namespace?

**Comment by sseago** [comment]
Also, is Velero installed in "test5" or in "velero"? The BSL needs to be in the same namespace that Velero is installed in.

**Comment by huiyichanmian** [comment]
> Also, is Velero installed in "test5" or in "velero"? The BSL needs to be in the same namespace that Velero is installed in.

velero and BSL are installed in the ”test5“ namespace.

**Comment by huiyichanmian** [comment]
I found the cause of the problem, which is caused by the inconsistency between the client and server versions.

**Comment by huiyichanmian** [comment]
I found the cause of the problem, which is caused by the inconsistency between the client and server versions.Thank you for your comments.
