### ISSUE TITLE
Move velero backups are gone after move velero to another namespace

### ISSUE THREAD

**Issue by chrislinan** [vmware-tanzu/velero#5133]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
I moved velero pod and velero related stuffs from default namespace to 'velero' namespace.
Then I connect to velero pod, and execute:`./velero backup get`, but I can not find the backups.
In my cluster, I can still find the old backup cr in the default namespace, they are not deleted or moved.
Then I try to create a restore from the old backup(located in default namespace) cr `./velero restore create --from-backup xxxxx`
Then error message shows: backup xxxxx can't find.
**What did you expect to happen:**
I don't want to lose my backup after I move velero to another namespace.
I want my backup cr still work, and I can create a restore from that backup cr.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
Client:
        Version: 1.9.0
        Git commit: 3f74f27b855e5b70233ad8dda10241c4ebaae7db-
Server:
        Version:
- Velero features (use `velero client config get features`): 
 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment]
This is actually intentional. If you have two different Velero installs in different namespace, each velero will only watch/process CRs in its own namespace.

**Comment by chrislinan** [comment]
Hi @blackpiglet
Thanks for your help. Actually, when I search in the velero log, I found that velero will sync the missing backup cr from object store. Then Velero will delete the backup cr which is beyond the TTL. That makes sense.
