### ISSUE TITLE
Velero tries to run preHook and postHook on Completed Pods

### ISSUE THREAD

**Issue by haslersn** [vmware-tanzu/velero#5137]
I've seen the following error in the logs of my Velero backups:

```
time="2022-07-21T04:22:03Z" level=error msg="Error executing hook" backup=velero/four-hourly-20220721041203 error="unable to upgrade connection: container not found (\"compute\")" hookPhase=pre hookSource=annotation hookType=exec logSource="internal/hook/item_hook_handler.go:214" name=virt-launcher-dns01-qnk9j namespace=powerdns resource=pods
time="2022-07-21T04:22:03Z" level=error msg="Error executing hook" backup=velero/four-hourly-20220721041203 error="unable to upgrade connection: container not found (\"compute\")" hookPhase=post hookSource=annotation hookType=exec logSource="internal/hook/item_hook_handler.go:214" name=virt-launcher-dns01-qnk9j namespace=powerdns resource=pods
```

`virt-launcher-dns01-qnk9j` is a Pod that is Completed. The KubeVirt VM has been live migrated to another Pod. The Pod `virt-launcher-dns01-qnk9j` is a leftover that stays in Completed state.

**What did you expect to happen:**

Velero restic backup should not run on Completed Pods.

**Environment:**

- Velero server version: 1.9.0
- Velero features: `<NOT SET>`
- Kubernetes version: 1.21.12
- Kubernetes installer & version: kubeadm 1.21
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from `/etc/os-release`): Debian 11, Linux `5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux`

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Thanks. Velero should check pod status before running backup hook commands

**Comment by reasonerjt** [comment]
Shouldn't a `completed` pod be excluded during backup?

**Comment by Shea-D** [comment]
Does the latest version of velero supports backup KubeVirt VMs which in running state? 
I'm using velero version 1.9.1, and I set defaultVolumesToRestic=true (use restic repo with minio). This environment looks normal, I can backup and restore pods with volumes,.
Here are some velero logs when I backup with KubeVirt VM's pod, the log level is info, but the msg looks like error? After restoring from this backup, the VM's DVs were empty.

```
time="2022-10-24T07:47:15Z" level=info msg="Backing up item" backup=openshift-adp/default-backup-3 logSource="pkg/backup/item_backupper.go:123" name=virt-launcher-centos-bm2kv namespace=default resource=pods
time="2022-10-24T07:47:15Z" level=info msg="running exec hook" backup=openshift-adp/default-backup-3 hookCommand="[/usr/bin/virt-freezer --freeze --name centos --namespace default]" hookContainer=compute hookName="<from-annotation>" hookOnError=Fail hookPhase=pre hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:126" name=virt-launcher-centos-bm2kv namespace=default resource=pods
time="2022-10-24T07:47:16Z" level=info msg="stdout: " backup=openshift-adp/default-backup-3 hookCommand="[/usr/bin/virt-freezer --freeze --name centos --namespace default]" hookContainer=compute hookName="<from-annotation>" hookOnError=Fail hookPhase=pre hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:173" name=virt-launcher-centos-bm2kv namespace=default resource=pods
time="2022-10-24T07:47:16Z" level=info msg="stderr: {\"component\":\"freezer\",\"level\":\"info\",\"msg\":\"Starting...\",\"pos\":\"main.go:47\",\"timestamp\":\"2022-10-24T07:47:16.084381Z\"}\n{\"component\":\"freezer\",\"level\":\"info\",\"msg\":\"Exiting...\",\"pos\":\"main.go:93\",\"timestamp\":\"2022-10-24T07:47:16.512932Z\"}\n" backup=openshift-adp/default-backup-3 hookCommand="[/usr/bin/virt-freezer --freeze --name centos --namespace default]" hookContainer=compute hookName="<from-annotation>" hookOnError=Fail hookPhase=pre hookSource=annotation hookTimeout="{30s}" hookType=exec logSource="pkg/podexec/pod_command_executor.go:174" name=virt-launcher-centos-bm2kv namespace=default resource=pods
time="2022-10-24T07:47:16Z" level=info msg="Executing custom action" backup=openshift-adp/default-backup-3 logSource="pkg/backup/item_backupper.go:312" name=virt-launcher-centos-bm2kv namespace=default resource=pods
time="2022-10-24T07:47:16Z" level=info msg="Executing podAction" backup=openshift-adp/default-backup-3 cmd=/velero logSource="pkg/backup/pod_action.go:51" pluginName=velero

```

**Comment by blackpiglet** [comment]
From the log posted, I think there is no error reported running the hook.
Useful information is free started at "2022-10-24T07:47:16.084381Z", and stopped at "2022-10-24T07:47:16.512932Z".

Velero isn't tested in this KubeVirt environment, so I'm not sure about it.
Could you give more information on your failure, especially about the backup hook and restore hook, and explain more about KubeVirt concept, such as DV.

**Comment by Shea-D** [comment]
> From the log posted, I think there is no error reported running the hook. Useful information is free started at "2022-10-24T07:47:16.084381Z", and stopped at "2022-10-24T07:47:16.512932Z".
> 
> Velero isn't tested in this KubeVirt environment, so I'm not sure about it. Could you give more information on your failure, especially about the backup hook and restore hook, and explain more about KubeVirt concept, such as DV.

Thanks for replying! If there is no problem with this log, I want to know when I restore volumes from restic repository, the data of volumes will be written by the init container restic-wait through the pod, right? If so, maybe there is a problem with the other plugin.

**Comment by blackpiglet** [comment]
When using Resitc, Velero will create a PodVolumeRestore CR for each volume included in Restore, and the Restic DaemonSet's replica that is allocated on the same node with the Pod has volume restoring will write data into volume according to the PodVolumeRestore setting. `restic-wait` InitContainer will hold the Pod from running, until PodVolumeRestore turned to `Ready`.

**Comment by Shea-D** [comment]
When I restore from restic, I can't get this object with the command "kubectl get PodVolumeRestore -A". Is this normal? But I can get the PodVolumeBackup. I only found backup messages in the log of restic deamonset's pod without error message. And I didn't find any error message in velero's log either.

**Comment by Shea-D** [comment]
Contributor of KubeVirt tell me that they don't have restic lanes so it is possible that with restic this behavior is problematic. Maybe this is why I couldn't get the PodVolumeRestore. Thank you for replying!

**Comment by haslersn** [comment]
Is it completed? It seems #5211 is the intended fix, but it's not merged.

**Comment by haslersn** [comment]
#5211 is still not merged
