### ISSUE TITLE
Velero runs preHook and postHook on Pods where no backups are configured

### ISSUE THREAD

**Issue by haslersn** [vmware-tanzu/velero#5138]
We have Pods created by KubeVirt. KubeVirt automatically sets the following annotations:

```
post.hook.backup.velero.io/command: '["/usr/bin/virt-freezer", "--unfreeze", "--name",
      "dns01", "--namespace", "powerdns"]'
post.hook.backup.velero.io/container: compute
pre.hook.backup.velero.io/command: '["/usr/bin/virt-freezer", "--freeze", "--name",
      "dns01", "--namespace", "powerdns"]'
pre.hook.backup.velero.io/container: compute
```

On most of these Pods, we don't have restic backups configured, i.e. there's no `backup.velero.io/backup-volumes` annotation. However, Velero still runs the preHook and the postHook.

**What did you expect to happen:**

Only run preHook and postHook if a backup will be taken.

**Environment:**

- Velero server version: 1.9.0
- Velero features: `<NOT SET>`
- Kubernetes version: 1.21.12
- Kubernetes installer & version: kubeadm 1.21
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from `/etc/os-release`): Debian 11, Linux `5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux`

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Hooks and Volume backup are not tied together.
I think your case is valid, but Velero doesn't work like that. Could you work around by filtering the pods not need volume backup.

**Comment by blackpiglet** [comment]
Close for now. Feel free to reopen, when need further investigation.
