### ISSUE TITLE
volume already bound to a different claim after a restore

### ISSUE THREAD

**Issue by rrey-aviatrix** [vmware-tanzu/velero#5141]
**What steps did you take and what happened:**

I created a sample app to test velero with. It is a statefulset with 1 replicas and a pv of 1GB.
I created the a backup with the namespace scope:
```
velero backup create test-rre-2 --include-namespaces backup-test-app
```
which is reported completed:
```
Name:         test-rre-2
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.21.12-eks-a64ea69
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=21+

Phase:  Completed

Errors:    0
Warnings:  0

Namespaces:
  Included:  backup-test-app
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2022-07-21 10:12:16 +0200 CEST
Completed:  2022-07-21 10:12:29 +0200 CEST

Expiration:  2022-08-20 10:12:16 +0200 CEST

Total items to be backed up:  22
Items backed up:              22

Velero-Native Snapshots:  1 of 1 snapshots completed successfully (specify --details for more information)
```

I tested a disaster recovery by deleting the namespace and running the restore command:
```
velero restore create --from-backup test-rre-2 
```
(restore is performed on same cluster) 
The restore ends up in `PartiallyFailed` :
```
[...]
Warnings:
  Velero:     <none>
  Cluster:  could not restore, CustomResourceDefinition "secretstores.external-secrets.io" already exists. Warning: the in-cluster version is different than the backed-up version.
            could not restore, CustomResourceDefinition "servicemonitors.monitoring.coreos.com" already exists. Warning: the in-cluster version is different than the backed-up version.
  Namespaces: <none>

Errors:
  Velero:     <none>
  Cluster:  error waiting on in-cluster persistentvolume pvc-ad8f20d5-06c5-488f-9a05-785b5f2ed827: timed out waiting for the condition
  Namespaces: <none>

Backup:  test-rre-2
[...]
```

The pvc is reported `Pending` and the describe command shows a `FailedBinding` error:
```
[...]
Used By:       backup-test-app-backup-test-app-sts-c8a6fa8f-0
Events:
  Type     Reason         Age                   From                         Message
  ----     ------         ----                  ----                         -------
  Warning  FailedBinding  74s (x26 over 7m28s)  persistentvolume-controller  volume "pvc-ad8f20d5-06c5-488f-9a05-785b5f2ed827" already bound to a different claim.
```

The pv is not showing any error:
```
$kubectl  get pv pvc-ad8f20d5-06c5-488f-9a05-785b5f2ed827           
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                                                 STORAGECLASS    REASON   AGE
pvc-ad8f20d5-06c5-488f-9a05-785b5f2ed827   1Gi        RWO            Retain           Released   backup-test-app/data-backup-test-app-backup-test-app-sts-c8a6fa8f-0   gp3-encrypted            17h
```

**What did you expect to happen:**

A successful restore.

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.8.1
	Git commit: -
Server:
	Version: v1.8.1
```
- Velero features (use `velero client config get features`): 
```
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.11", GitCommit:"5824e3251d294d324320db85bf63a53eb0767af2", GitTreeState:"clean", BuildDate:"2022-06-16T05:39:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
N/A
- Cloud provider or hardware configuration:
`AWS EKS (1.21)`

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
I think this is related how PVC and PV is configured for the testing workload.
Could you share the PVC, PV's yaml?
To me, this may happen when the PVC is bound to a specific PV, and the PV's DeletionPolicy is set to Retain. After workload deletion, the specific PV is released, then it is bound to another PVC. At last, when Restoring, the PV cannot be bound to the restored PVC again.

**Comment by vineetsingh5** [comment]
@blackpiglet I faced similar issue when tried to restore rabbitmq cluster. Here is the pv and pvc yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/selected-node: server0
  creationTimestamp: "2022-07-24T07:33:29Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: rabbitmq
  name: persistence-rabbitmq-server-0
  namespace: rabbitmq
  ownerReferences:
  - apiVersion: rabbitmq.com/v1beta1
    blockOwnerDeletion: false
    controller: true
    kind: RabbitmqCluster
    name: rabbitmq
    uid: 16ba5ce7-08ba-4a04-ba4e-503e9d181778
  resourceVersion: "140669"
  uid: a9f44e31-c29b-413c-bb35-1344494d7cc9
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn-backup-single-replica
  volumeMode: Filesystem
  volumeName: pvc-a9f44e31-c29b-413c-bb35-1344494d7cc9
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  phase: Bound
➜  velero-2.30.1 k  get pv pvc-a9f44e31-c29b-413c-bb35-1344494d7cc9 -oyaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: driver.longhorn.io
  creationTimestamp: "2022-07-24T07:33:32Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/driver-longhorn-io
  name: pvc-a9f44e31-c29b-413c-bb35-1344494d7cc9
  resourceVersion: "8491"
  uid: 31dff410-5a6b-44a2-9ff0-84a9500b3c15
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: persistence-rabbitmq-server-0
    namespace: rabbitmq
    resourceVersion: "8302"
    uid: a9f44e31-c29b-413c-bb35-1344494d7cc9
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      fromBackup: ""
      numberOfReplicas: "1"
      recurringJobSelector: '[ { "name":"uipath-backup", "isGroup":true } ]'
      staleReplicaTimeout: "30"
      storage.kubernetes.io/csiProvisionerIdentity: 1658647557622-8081-driver.longhorn.io
    volumeHandle: pvc-a9f44e31-c29b-413c-bb35-1344494d7cc9
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn-backup-single-replica
  volumeMode: Filesystem
status:
  phase: Bound
➜  velero-2.30.1 k get storageclass longhorn-backup-single-replica -oyaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"longhorn-backup-single-replica"},"parameters":{"fromBackup":"","numberOfReplicas":"1","recurringJobSelector":"[ { \"name\":\"uipath-backup\", \"isGroup\":true } ]","staleReplicaTimeout":"30"},"provisioner":"driver.longhorn.io","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
  creationTimestamp: "2022-07-24T07:25:31Z"
  name: longhorn-backup-single-replica
  resourceVersion: "1453"
  uid: 82e4a043-094f-4d5a-9707-decd0c9bca1d
parameters:
  fromBackup: ""
  numberOfReplicas: "1"
  recurringJobSelector: '[ { "name":"uipath-backup", "isGroup":true } ]'
  staleReplicaTimeout: "30"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

**Comment by rrey-aviatrix** [comment]
@blackpiglet did the manifest I provide helped you in the analysis ?

**Comment by blackpiglet** [comment]
@rrey-aviatrix 
Yes. We think this is related to Statefulset controller's logic. Still working on it.

**Comment by Lyndon-Li** [comment]
@rrey-aviatrix I am afraid this is an expected behavior of kubernetes and Velero:

- If a PV's reclaim policy is set to "Retain", the PV's claimRef field is not cleared even after the binding PVC has been deleted. This is why we see the PV's status is "Released" but the Claim column is still not empty.
- Then when kubernetes is requested to bind the same PV again (that happens at the Velero restore phase), it aborts directly with the error "volume %q already bound to a different claim"
- Velero restore cannot do anything help because it relies on kubernetes PV provision to create the PV

As a direct method to solve this binding problem, we can manually reset the PV's claimRef, however, we don't have time to do this, because Velero fails immediately when it reaches this situation.

As another fact, for a statefulset, it could automatically manage its PVC, that is, when a pod is recreated for any reason, the PVC will be retained, so I don't quite understand why you set the PV's reclaim policy to "Retain". Is it fine to change it for your current test?

**Comment by rrey-aviatrix** [comment]
> As another fact, for a statefulset, it could automatically manage its PVC, that is, when a pod is recreated for any reason, the PVC will be retained, so I don't quite understand why you set the PV's reclaim policy to "Retain". Is it fine to change it for your current test?

The `Retain` is here because as a general rule I don't want data to be erased too easily. So our storage class makes it the default so that an accidental deletion will not be a catastrophe and we could get the data back.
I don't think it would be wise to change that.

But I did not have the whole understanding of how it works and you helped with explanation.

So if I sum up:
- When restoring the backup I should not have the PV still in the cluster because I'm counting on velero to restore the data from the backup.
- If I want to do a partial restore and keep the pv still in the cluster, I should filter what is restored from the backup (avoid the volume restore) and do some glue actions to have the pv/pvc point to each other.

Did I get this right ?

**Comment by Lyndon-Li** [comment]
I tried it locally and could reproduce this problem, so it is a common problem --- for a statefulset, if the PV's reclaim policy is set to "Retain", Velero restore always fails because the PVC cannot bind the PV.

**Comment by Lyndon-Li** [comment]
@rrey-aviatrix To answer your questions:

> When restoring the backup I should not have the PV still in the cluster because I'm counting on velero to restore the data from the backup

Not exactly, even though the old PV exists, Velero could successfully restore the PV from snapshot. 
However, if the PV is in Released status or its claimRef is not empty but the binding PVC cannot be found, Velero will regard the PV in an abnormal status and wait there until a 10 min timeout. After the timeout, Velero will skip restoring the PV.

> If I want to do a partial restore and keep the pv still in the cluster, I should filter what is restored from the backup (avoid the volume restore) and do some glue actions to have the pv/pvc point to each other.

I doubt this. Even though you filter out the PV, Velero restore creates the PVC and other resources directly, since the created PVC is not in a normal status (pending), Velero restore still regard this as an error and the final restore status is still PartialFailed

Conclusively, it is not Velero that could not restore the PV in this case, we cannot do this manually either if we don't remove the old PV. This is rather due to the principle of Kubernetes: we cannot bind a PVC to a PV if the PV is still claimed.

Now I've understand why you need to set the PV's reclaim policy to "Retain", if you still want to keep this behavior, below ways may solve this problem:

- Release the PV before running Velero restore
- Or release the PV one by one during Velero restore, as mentioned above, for each PV, Velero restore wait 10 min for its disappear
- Rename the existing PV manually before Velero restore and release them after a successful Velero restore (I never tried, you can try it out)

**Comment by rrey-aviatrix** [comment]
After I deleted the PV, the restore is working properly and everything is working properly with my test app.
I will continue testing other cases on my side to learn how to restore when/if I find myself in other context.

Thanks for all the info, I'm closing the issue.

**Comment by blackpiglet** [comment]
This issue should be common to volume-using applications, which set volume's `ReclaimPolicy` to Retain by `StorageClass.Spec.ReclaimPolicy` to `Retain` or `PersistentVolume.Spec.PersistentVolumeReclaimPolicy` to `Retain`.
