### ISSUE TITLE
Restore of CRD failed when restoring from cluster of version 1.19 to a cluster of version 1.22 with API Group Versions Feature enabled

### ISSUE THREAD

**Issue by gsadhani** [vmware-tanzu/velero#5146]
**What steps did you take and what happened:**

I tried restoring a backup containing a CRD from a cluster version 1.19 to a cluster of version 1.22. The restore operation failed with error:

```
time="2022-07-21T06:10:48Z" level=error msg="error restoring customresource.xyz.com: the server could not find the requested resource" logSource="pkg/restore/restore.go:1287" restore=velero/b1-20220721114044
```

**What did you expect to happen:**
K8s 1.19 supports CRD API [apiextensions.k8s.io/v1beta1](http://apiextensions.k8s.io/v1beta1)  and  [apiextensions.k8s.io/v1](http://apiextensions.k8s.io/v1), K8s 1.22 supports only [apiextensions.k8s.io/v1](http://apiextensions.k8s.io/v1). Ideally the restore operation should have succeeded as it is the same as [Classic Case A](https://velero.io/docs/v1.8/enable-api-group-versions-feature/#how-the-enable-api-group-versions-feature-works), the backup contains both versions:

```
  apiextensions.k8s.io/v1/CustomResourceDefinition:
    - customresource.xyz.com
...
  apiextensions.k8s.io/v1beta1/CustomResourceDefinition:
    - customresource.xyz.com
```

**The following information will help us better understand what's going on**:
Velero logs: https://gist.github.com/gsadhani/50993337efef19472b2c17dff256be4d

**Environment:**

- Velero version (use `velero version`): 1.8.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.22
- Kubernetes installer & version:
- Cloud provider or hardware configuration: EKS
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
I checked the backup tarball and found the problematic CRD has v1beta1 even in the path 
`resources/customresourcedefinitions.apiextensions.k8s.io/v1-preferredversion/cluster/xxx.json`
For example:
```
cat b1/resources/customresourcedefinitions.apiextensions.k8s.io/v1-preferredversion/cluster/agents.clusters.tmc.cloud.vmware.com.json|jq .apiVersion
"apiextensions.k8s.io/v1beta1"
```

While other CRDs has the v1 version:
```
cat b1/resources/customresourcedefinitions.apiextensions.k8s.io/v1-preferredversion/cluster/securitygrouppolicies.vpcresources.k8s.aws.json|jq .apiVersion
"apiextensions.k8s.io/v1"
```

So the problem happened in the backup phase when the `EnableAPIGroupVersions` is set.  
Seems the problematic CRD was created via the v1b1 API on a v1.19 k8s cluster. 

I'll do more investigation and update in this thread.

**Comment by reasonerjt** [comment]
The root cause is the plugin `RemapCRDVersionAction`, for some CRDs that were created via v1b1 API the plugin will make velero always backup the v1b1 spec regardless of the feature flag `EnableAPIGroupVersions`.

In short term, we'll skip registering this plugin if feature flag `EnableAPIGroupVersions` is set.

In long term, we should consider remove this plugin, I opened #5166
