### ISSUE TITLE
Persistent volume "succeeding backup" when in fact it hasn't

### ISSUE THREAD

**Issue by djs28** [vmware-tanzu/velero#5155]
Noticed that our backups on persistent volumes were not being snapshotted correctly, even when backups looked correct. Hidden in the logs 
`level=info msg="No volume ID returned by volume snapshotter for persistent volume"`

I believe that 			
`log.Infof("No volume ID returned by volume snapshotter for persistent volume")`

should be
`log.WithError(err).Errorf("No volume ID returned by volume snapshotter for persistent volume")`

https://github.com/vmware-tanzu/velero/blob/f68ae92fd03559515497ae3549ed694ae7a7fcf6/pkg/backup/item_backupper.go#L467

**Comment by Lyndon-Li** [comment]
@djs28 
Please provide us more information and the Velero logs. If the snapshot was not completed correctly, the handler of the snapshot will return errors, so it should not go to the log you mentioned. Thanks.

**Comment by qiuming-best** [comment]
I've reproduced it by using AWS plugin to do the volume snapshot for one self-build cluster. 

And the backup result is in complete status but does not snapshot the volume, and it has no error log. So here I've changed the above mentioned info log into error log for easy troubleshooting.

**Comment by qiuming-best** [comment]
@djs28 could you share me what plugin you are using for snapshot?
