### ISSUE TITLE
Not able to migrate a cluster between GCP regions (PVs)

### ISSUE THREAD

**Issue by gbl-michell** [vmware-tanzu/velero#5162]
**What steps did you take and what happened:**
I have a **zonal** GKE cluster running on us-east1-b and I'm trying to restore it into a **regional** cluster on us-central1.
I have installed velero 1.9.0 and the gcp plugin 1.5.0 on both clusters and I was able to backup and restore namespaces and k8s objects without issues. However, the pods that mount to PVs are never being scheduled, and the following message is described:
`Warning  FailedScheduling   87s (x21 over 18m)    default-scheduler   0/3 nodes are available: 3 node(s) had volume node affinity conflict.`
I have tried manually editing the regions inside the PVs but that didn't work. Here's how it is set:
`  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-east1-b
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - us-east1
`

**What did you expect to happen:**
PVs were migrated to new cluster and could be accessed by the pods.

**Environment:**

- Velero version (use `velero version`):  1.9.0
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12-gke.1500", GitCommit:"6c11aec6ce32cf0d66a2631eed2eb49dd65c89f8", GitTreeState:"clean", BuildDate:"2022-05-11T09:25:37Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
`
- Cloud provider or hardware configuration: GKE

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
@gbl-michell yeah, I think it's the nodeAffinity set on pv that makes the scheduler controller prevent pod schedule?
 
Maybe you can reference to this [one](https://stackoverflow.com/questions/51946393/kubernetes-pod-warning-1-nodes-had-volume-node-affinity-conflict)

**Comment by blackpiglet** [comment]
@gbl-michell 
Could you give more details about how you installed Veleo, and the backup and restore commands?

**Comment by sseago** [comment]
Also, are you using snapshots for PV backup or restic? I suspect that with snapshots, the regions must be the same. It might be worth trying with Restic if you're not using it already to see whether this works.

**Comment by gbl-michell** [comment]
I was able to successfully migrate the PVs using restic. Thanks all.

**Comment by blackpiglet** [comment]
@gbl-michell 
Could I close this issue? Looks like the problem described here is resolved.
