### ISSUE TITLE
Disaster Recovery for Kubernetes Windows Cluster resources and Persistent Volumes

### ISSUE THREAD

**Issue by ajitkadari** [vmware-tanzu/velero#5170]
Backup and restore, perform disaster recovery, and migrate Windows Kubernetes cluster resources and persistent volumes.

**Comment by reasonerjt** [comment]
@ajitkadari could you clarify if you need velero to run in windows container?  
If velero continues to be running in linux, for non-restic case the B/R for windows workload may work.  Have you done any test yourself?

**Comment by andyr8939** [comment]
This does work on Windows clusters as I've done exactly this on Windows Azure Kubernetes nodepools to backup and restore workloads across regions.  You do have to run the Velero pod on a linux node, however as AKS System Pool nodes only support linux, you are going to have at least 1 of these nodes anyway, so in a pinch you could run it on that, although its better if you run it on a separate linux nodepool than on system.

**Comment by reasonerjt** [comment]
Closingt this one due to inactivity.
