### ISSUE TITLE
Velero Partial Backup Failure - Pod Volume Backup

### ISSUE THREAD

**Issue by dcardellino** [vmware-tanzu/velero#5182]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I run a scheduled backup (every @1h) to backup a whole namespace and its PVC to AWS S3. The last couple weeks this worked out fine. But suddenly I get `PartiallyFailed` on some backups.

When I do `velero backup logs <backupname> | grep error` I see the following error messages:

```
time="2022-08-05T04:46:23Z" level=error msg="Error backing up item" backup=velero/vault-20220805044251 error="pod volume backup failed: running Restic backup, stderr=unable to create lock in backend: repository is already locked exclusively by PID 1362809 on velero-584cc8fbf-6tdsq by nonroot (UID 65532, GID 65532)\nlock was created at 2022-08-05 04:46:13 (9.38842805s ago)\nstorage ID be900ed1\nthe `unlock` command can be used to remove stale locks\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:199" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:417" name=vault-2
time="2022-08-05T04:46:23Z" level=error msg="Error backing up item" backup=velero/vault-20220805044251 error="pod volume backup failed: running Restic backup, stderr=unable to create lock in backend: repository is already locked exclusively by PID 1362809 on velero-584cc8fbf-6tdsq by nonroot (UID 65532, GID 65532)\nlock was created at 2022-08-05 04:46:13 (10.166383401s ago)\nstorage ID be900ed1\nthe `unlock` command can be used to remove stale locks\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:199" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:417" name=vault-2
```

**What did you expect to happen:**

Velero/Restic backups the data successfull 🤔

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

```

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`


**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]


**Environment:**

- Velero version (use `velero version`):  1.9.0
- Velero features (use `velero client config get features`):  features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.23.9
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: hetznercloud
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.4 LTS (Focal Fossa)


**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
@dcardellino Did you get this problem once or multiple times and each time it complains different PID in the error as an example shown below?
`repository is already locked exclusively by PID 1362809`

**Comment by Lyndon-Li** [comment]
Could you also share the entire Velero log bundle?

**Comment by dcardellino** [comment]
@Lyndon-Li it is multiple times the same PID. Sorry I forgot to upload the bundle on my initial comment:

[bundle-2022-08-05-07-15-27.tar.gz](https://github.com/vmware-tanzu/velero/files/9266385/bundle-2022-08-05-07-15-27.tar.gz)

**Comment by Lyndon-Li** [comment]
@dcardellino From the available log, looks like there are some contest problems among multiple Restic backup process. However, the current log has limited information to indicate the contests.

Therefore, could you help to enable Velero's Debug log level and regenerate the logs when the problem happens?
You can refer to [here](https://velero.io/docs/v1.9/troubleshooting/#:~:text=more%20usage%20details.-,Getting%20velero%20debug%20logs,-You%20can%20increase) for how to increase the log level to Debug

**Comment by dcardellino** [comment]
Sure here it is @Lyndon-Li:
[bundle-2022-08-09-06-32-23.tar.gz](https://github.com/vmware-tanzu/velero/files/9286754/bundle-2022-08-09-06-32-23.tar.gz)

**Comment by Lyndon-Li** [comment]
@dcardellino We need the debug log for both Velero server and Restic daemonset. Therefore, besides changing the log level of Velero server, please also change the log level for Restic daemonset. 

You can edit the Restic daemonset by below command:
`kubectl edit ds -n velero restic`
Then you need to do the same changes(--log-level) as what you have done for Velero server.

Sorry to miss this.

**Comment by Lyndon-Li** [comment]
@dcardellino 
We've just noticed that the lock is taken by another velero pod` velero-584cc8fbf-6tdsq` as shown here:
`unable to create lock in backend: repository is already locked exclusively by PID 1665618 on velero-584cc8fbf-6tdsq`
On the other hand, the current running velero pod's name is `velero-85d456ff69-jvd8r`.

Therefore, could you also run below command to see how many velero pod are running?
kubectl get pod -n velero

**Comment by dcardellino** [comment]
Oh damn.. I found the Issue. I ran another Velero deployment in another cluster with the same credentials. Thanks for your support @Lyndon-Li , but I think deleting this deployment should solve the issue.

I will close the issue for now.
