### ISSUE TITLE
net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by trankchung** [vmware-tanzu/velero#5183]
**What steps did you take and what happened:**
Running the velero command against any GKE cluster throws `net/http: TLS handshake timeout` error. Using `kubectl` have no issue.

```
$ velero install \
        --provider gcp \
        --plugins velero/velero-plugin-for-gcp:v1.5.0 \
        --bucket BUCKET \
        --no-secret \
        --sa-annotations iam.gke.io/gcp-service-account=velero@PROJECT.iam.gserviceaccount.com \
        --backup-location-config serviceAccount=velero@PROJECT.iam.gserviceaccount.com
An error occurred: Get "https://35.226.14.100/api?timeout=32s": net/http: TLS handshake timeout

$ velero backup get
An error occurred: Get "https://35.226.14.100/apis/velero.io/v1/namespaces/velero/backups": net/http: TLS handshake timeout
```

**What did you expect to happen:**
Velero should connects and do its thing.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Command `velero debug` throws the same error as mentioned above.

**Anything else you would like to add:**
The `kubectl` command works fine and I have full permission to this cluster so it's not permission issue. Using `kubeclt` and `k9s` I'm able to work w/ the cluster no problem.

**Environment:**

- Velero version (use `velero version`): v1.9.0
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.24.1
- Kubernetes installer & version: v1.22.8-gke.2200
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`): macOS Monterey 12.5

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
Do you use any http proxy for the connection?
Any could you share more info of your environment? It looks like to be an environment related problem.

**Comment by trankchung** [comment]
I've googled this issue and tried all the suggestions which includes unsetting https_proxy and using no_proxy but none of them work. I don't have any proxy setting set.

What info are you looking for because it's just a GKE cluster. I can connect to it using `kubectl` no problem. Please let me know what info you're looking for and I'll be happy to provide it. Thanks.

**Comment by trankchung** [comment]
It looks like NetSkope was blocking it. Thanks for looking into this.
