### ISSUE TITLE
Velero keeps on calling the deprecated v1beta1/ingresses api

### ISSUE THREAD

**Issue by maartenjanvangool** [vmware-tanzu/velero#5187]
**What steps did you take and what happened:**
We are/were running kubernetes v1.21 in gcp. Google nowadays warns you of deprecated api usage, which in order prevent an upgrade to the newer version, when these deprecated api's are removed. In 1.22, several api's are removed, among them `/apis/extensions/v1beta1/ingresses`. Google warned us that Velero was calling this api. We have no such resources in our cluster (all our ingresses are on the non-deprecated version). 

I asked on [slack](https://kubernetes.slack.com/archives/C6VCGP4MT/p1659518618737779), but was eventually ask to make an issue here. 

We upgraded velero from 1.8.1 to 1.9.0, but that did not resolve the issue. After that, we forced the upgrade on staging to see what would happen. And apparently Velero is _still_ calling this now removed api sometimes. 

According to GCP, Velero is calling the api during backup. But it does not seem to do that every backup. 

**What did you expect to happen:**
I do not want Velero to call deprecated api's if it's not required, or I would like a neat way out of this deadlock. I would understand if Velero makes backups of deprecated resources.

**The following information will help us better understand what's going on**:

I cannot really provide the entire logs, it contains info I cannot disclose. I am seeing this in the logs though: 
```
Waited for 1.047783694s due to client-side throttling, not priority and fairness, request: GET:https://<ip>:443/apis/extensions/v1beta1?timeout=32s
```
This entire api is deprecated/removed, see [here](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122). 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.9.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.21/1.22
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
This message is not printed by Velero directly but by Kubernetes Client-go API.
Velero server refreshes the Kubernetes resources every 5 minute by calling the Client-go API. 
The related Client-go API enumerates the supported API groups and then enumerates the resources under the groups. 

Velero does nothing special, so I guess if one version in a API group is not supported, the version will not be retrieved by Client-go, so nothing wrong will happen.

@maartenjanvangool Could you help to confirm below things:
1. Do you see the warning in Kubernetes v1.21 or v1.22?
2. If you see it in v1.22, is there anything wrong happens?

**Comment by maartenjanvangool** [comment]
1. I'm seeing this warning in 1.22.
2. Well yes, google is still complaining about removed api usage. 

I'm not sure this warning directly relates to my issue. I'll continue monitoring our gcp environment. 

However, if it's called by the go client, shouldn't that library be updated to exclude removed api's or something?

**Comment by blackpiglet** [comment]
There is already an issue to address this #5146, and the fix was already cherry-picked into v1.9.1, but the thing looks a little surprising to me is ingress's API path: `/apis/extensions/v1beta1/ingresses`.

[ingress v1](https://v1-21.docs.kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#http-request)
Ingress API path should be something likes this `/apis/networking.k8s.io/v1/namespaces/{namespace}/ingresses/{name}`.

Looks like Ingress resource's beta version use `extensions/v1beta1` and `networking.k8s.io/v1beta1`. If your cluster contains ingress in group `extensions/v1beta1`, I think you may need to convert the version manually.

**Comment by Lyndon-Li** [comment]
@maartenjanvangool Please check your env as @blackpiglet mentioned.

Besides that, I have two more questions, for this log:
`Waited for 1.047783694s due to client-side throttling, not priority and fairness, request: GET:https://<ip>:443/apis/extensions/v1beta1?timeout=32s`

Question:
1. Do you see this log in v1.21 or v1.22?
2. If you see this in v1.22, could you share several lines of logs around it so that we know the context. You can mask the sensitive info in the log if any. Just a few lines above and below the log is fine.

**Comment by maartenjanvangool** [comment]
@Lyndon-Li 
1. Like I said in my previous comment, I'm seeing this in 1.22. 
2. See below. 
```
{"backup-storage-location":"velero/default","controller":"backup-storage-location","level":"info","logSource":"pkg/controller/backup_storage_location_controller.go:115","msg":"BackupStorageLocations is valid, marking as available","time":"2022-08-08T23:33:38Z"}
{"backup-storage-location":"velero/default","controller":"backup-storage-location","level":"info","logSource":"pkg/controller/backup_storage_location_controller.go:130","msg":"Validating BackupStorageLocation","time":"2022-08-08T23:33:38Z"}
{"backup-storage-location":"velero/default","controller":"backup-storage-location","level":"info","logSource":"pkg/controller/backup_storage_location_controller.go:115","msg":"BackupStorageLocations is valid, marking as available","time":"2022-08-08T23:33:38Z"}
I0808 23:33:42.825910       1 request.go:665] Waited for 1.048432135s due to client-side throttling, not priority and fairness, request: GET:https://10.221.0.1:443/apis/extensions/v1beta1?timeout=32s
{"backup-storage-location":"velero/default","controller":"backup-storage-location","level":"info","logSource":"pkg/controller/backup_storage_location_controller.go:130","msg":"Validating BackupStorageLocation","time":"2022-08-08T23:34:38Z"}
{"backup-storage-location":"velero/default","controller":"backup-storage-location","level":"info","logSource":"pkg/controller/backup_storage_location_controller.go:115","msg":"BackupStorageLocations is valid, marking as available","time":"2022-08-08T23:34:38Z"}
{"backup-storage-location":"velero/default","controller":"backup-storage-location","level":"info","logSource":"pkg/controller/backup_storage_location_controller.go:130","msg":"Validating BackupStorageLocation","time":"2022-08-08T23:34:38Z"}
{"backup-storage-location":"velero/default","controller":"backup-storage-location","level":"info","logSource":"pkg/controller/backup_storage_location_controller.go:115","msg":"BackupStorageLocations is valid, marking as available","time":"2022-08-08T23:34:38Z"}
{"backup-storage-location":"velero/default","controller":"backup-storage-location","level":"info","logSource":"pkg/controller/backup_storage_location_controller.go:130","msg":"Validating BackupStorageLocation","time":"2022-08-08T23:35:38Z"}
```

I'm seeing this kind of log a lot more, and the same message pops up for other api's: 
```
I0808 23:28:39.473092       1 request.go:665] Waited for 1.047359592s due to client-side throttling, not priority and fairness, request: GET:https://<ip>:443/apis/storage.k8s.io/v1beta1?timeout=32s
```

**Comment by maartenjanvangool** [comment]
> 



> There is already an issue to address this #5146, and the fix was already cherry-picked into v1.9.1, but the thing looks a little surprising to me is ingress's API path: `/apis/extensions/v1beta1/ingresses`.



> Looks like Ingress resource's beta version use `extensions/v1beta1` and `networking.k8s.io/v1beta1`. If your cluster contains ingress in group `extensions/v1beta1`, I think you may need to convert the version manually.

It does not contain these resources at all. That's the surprising thing.

**Comment by maartenjanvangool** [comment]
> There is already an issue to address this #5146, and the fix was already cherry-picked into v1.9.1,

I can't really tell from the issue whether or not it's the same as mine, it does look similar though. We'll definately test 1.9.1 upon release to see if that resolves the issue.

**Comment by blackpiglet** [comment]
I will investigate more on this.
Looks like this is related to the discoveryClient of client-go using by Velero to traverse all GVR from kube-apiserver.

**Comment by blackpiglet** [comment]
@maartenjanvangool 
Checked discoveryClient implementation, it iterates through the kube-apiserver's "https://<api-server-ip>/apis/" to discover all available resources.

I checked the resources on my developing GKE v1.22 cluster.

```
kubectl api-resources  | grep v1beta1
ingresses                         ing                                                       extensions/v1beta1                          true         Ingress
flowschemas                                                                                 flowcontrol.apiserver.k8s.io/v1beta1        false        FlowSchema
prioritylevelconfigurations                                                                 flowcontrol.apiserver.k8s.io/v1beta1        false        PriorityLevelConfiguration
nodes                                                                                       metrics.k8s.io/v1beta1                      false        NodeMetrics
pods                                                                                        metrics.k8s.io/v1beta1                      true         PodMetrics
frontendconfigs                                                                             networking.gke.io/v1beta1                   true         FrontendConfig
serviceattachments                                                                          networking.gke.io/v1beta1                   true         ServiceAttachment
servicenetworkendpointgroups      svcneg                                                    networking.gke.io/v1beta1                   true         ServiceNetworkEndpointGroup
podsecuritypolicies               psp                                                       policy/v1beta1                              false        PodSecurityPolicy
csistoragecapacities                                                                        storage.k8s.io/v1beta1                      true         CSIStorageCapacity
```

We can see the APIs you mentioned are listed. By far, I didn't find out a way to distinguish whether the API is deprecated or not.

**Comment by maartenjanvangool** [comment]
When I call on the old api with kubect, I get this: 

```
kubectl get ingresses.extensions 
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
...
ingresses
```
Not sure if this has to do with me using the k8s v1.21 client. 

One more thing, this api _has been removed_ in 1.22. It is deprecated since 1.14, as the message says. My client seems to be simply redirecting to the new ingress api.

**Comment by blackpiglet** [comment]
I also didn't expected.
Of course, the API deprecation and stopping serve are very clear in documents, but it's not easy for code logic to know how to do that. 
By using the discoveryClient from client-go, it's easy to access all the available API available in k8s. I don't whether there will a library function to know the k8s not-serving API list. If not, Velero needs to maintain a list per k8s version to do that.

**Comment by maartenjanvangool** [comment]
It seems to me like a bug in Kubernetes, but I'm not sure. I've asked on slack. See [here](https://kubernetes.slack.com/archives/C09NXKJKA/p1660053130386309).

**Comment by BenTheElder** [comment]
It appears to be specific to GKE (NOTE: had no involvement in this, just learned about it myself, I am not speaking for GKE here) https://github.com/kubernetes/kubernetes/issues/111813#issuecomment-1216008212

The APIs are still deprecated, GKE just seems to have extended user time to migrate off of them by permitting them in 1.22.X-gke until 1.23. Documented here in the migration guide https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-22#ingress-v122

I think as long as you're not actually using the types and velero is just enumerating everything, this is working as intended, and you can ignore the warning. The warnings are just intended to help identify "you're still using this API and it won't be available in a future upgrade", velero hitting _all_ the APIs (I think?) is bound to trigger that.

**Comment by blackpiglet** [comment]
I think this issue can be closed.
