### ISSUE TITLE
 unknown flag: --existing-resource-policy

### ISSUE THREAD

**Issue by rajeevpnair** [vmware-tanzu/velero#5195]
**What steps did you take and what happened:**
when try to restore if an object which is already exist, by default velero will skip that resource, 
i see the  --existing-resource-policy flag is available in the documentation to change this default behavior , **_https://velero.io/docs/v1.9/restore-reference/#restore-existing-resource-policy_** but while using this flag its through unknown flag: --existing-resource-policy

**What did you expect to happen:**
Expect to restore the objects as update to the cluster

**Environment:**

velero version
Client:
        Version: v1.2.0
        Git commit: 5d008491bbf681658d3e372da1a9d3a21ca4c03c
Server:
        Version: v1.8.1
[eic@anjali ~]$

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by rajeevpadinharepattu** [comment]
This can be closed as i see in the new binary this option is available
