### ISSUE TITLE
Running `velero schedule create` with output format results in SIGSEGV

### ISSUE THREAD

**Issue by cschmatzler** [vmware-tanzu/velero#5198]
**What steps did you take and what happened:**
I'd like to integrate my backup schedule into GitOps - as such, having the schedule as a file to apply is important.
To accomplish this, I ran `velero schedule create daily -o yaml --schedule="@every 24h" `.

This results in 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1007f05f0]
```

**What did you expect to happen:**
I expected to have an output of a Kubernetes `Schedule` custom resource describing my schedule.

**Environment:**

- Velero version (use `velero version`): 
```
❯ velero version                                                   
Client:
	Version: v1.9.0
	Git commit: -
Server:
	Version: v1.9.0
```
- Velero features (use `velero client config get features`): 
```
❯ velero client config get features
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
❯ kubectl version --short                          
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.24.3
```
- Kubernetes installer & version: Talos Linux v1.1.2
- Cloud provider or hardware configuration: Hetzner Cloud
- OS (e.g. from `/etc/os-release`): Talos Linux v1.1.2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
Are you using a released version of Velero cli? I didn't see the `Git commit` in the output of `velero version` and I cannot reproduce it in my env

**Comment by cschmatzler** [comment]
It's installed with `brew install velero`.  
Late 2021 M1 Pro MacBook Pro.

**Comment by Va1** [comment]
experiencing the same behaviour with CLI :(

**Comment by ywk253100** [comment]
Please download the Velero CLI from the [Github release page](https://github.com/vmware-tanzu/velero/releases/latest).

The Homebrew isn't updated for recent releases because of the bandwidth of our resources, and It's very likely we'll not support it anymore in future releases, we'll update the documentation after the discussion with community
