### ISSUE TITLE
velero-upgrade-crds unable to run on v1.9.1

### ISSUE THREAD

**Issue by pankajmt** [vmware-tanzu/velero#5265]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Installing velero v1.9.1 via its helm chart version 2.31.3. velero-upgrade-crds fails. 

**What did you expect to happen:**

velero to deploy fine. 

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

helm chart seems to have this code for velero-upgrade-crds
```
          command:
            - /tmp/sh
          args:
            - -c
            - /velero install --crds-only --dry-run -o yaml | /tmp/kubectl apply -f -
```

but the image no longer has `/tmp/sh`?
```
docker run -ti --rm velero/velero:v1.9.1 /tmp/sh
Unable to find image 'velero/velero:v1.9.1' locally
v1.9.1: Pulling from velero/velero
b9f88661235d: Already exists
d7fbeaa2da3f: Already exists
ebc856cf6f53: Already exists
Digest: sha256:f8b9fec77cf2e11c204e7309ee740cae3f694bfb8876bc6a3013fc7ae497e60d
Status: Downloaded newer image for velero/velero:v1.9.1
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/tmp/sh": stat /tmp/sh: no such file or directory: unknown.
```

**Environment:**

- Velero version (use `velero version`): v1.9.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): v1.22.11-gke.400
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by pankajmt** [comment]
i could get the upgradecrds to work, i had the wrong version of velero configured. but would be good to understand how this /tmp/sh stuff works, unless i am off track. (can close this, not closing myself yet as looking to understand).

**Comment by allenxu404** [comment]
> i could get the upgradecrds to work, i had the wrong version of velero configured. but would be good to understand how this /tmp/sh stuff works, unless i am off track. (can close this, not closing myself yet as looking to get attention to understand).

Good to know you made it work at last! Thanks for your info.

**Comment by reasonerjt** [comment]
Thanks @pankajmt I'm closing this issue as usage error.

**Comment by admincasper** [comment]
> i could get the upgradecrds to work, i had the wrong version of velero configured. but would be good to understand how this /tmp/sh stuff works, unless i am off track. (can close this, not closing myself yet as looking to get attention to understand).

@pankajmt @allenxu404 @reasonerjt  I am getting the same error, what do you mean by wrong version of velero configured? Shouldn't `docker run -ti --rm velero/velero:v1.9.1 /tmp/sh` work?
