### ISSUE TITLE
Cherrypick PRs for v1.9.2

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#5266]
This is opened to make sure the PRs are cherry-picked to v1.9.2 release:
#5247 
#4980 
#5236

**Comment by shubham-pampattiwar** [comment]
@reasonerjt Can we add the following PRs for 1.9.2:
https://github.com/vmware-tanzu/velero/pull/5217
https://github.com/vmware-tanzu/velero/pull/5239

**Comment by shubham-pampattiwar** [comment]
Adding another small fix to the list: https://github.com/vmware-tanzu/velero/pull/5336

**Comment by qiuming-best** [comment]
All pr is cherrypicked, and v1.9.2 is released, so closed
