### ISSUE TITLE
Velero 1.9.1 is not creating backups

### ISSUE THREAD

**Issue by siva25081994** [vmware-tanzu/velero#5273]
**What steps did you take and what happened:**
When a schedule is created, Backups are not getting created when installed velero 1.9.1. Also getting a error in velero logs **schedule not found" error="Schedule.velero.io**.

**What did you expect to happen:**
Backups should be created based on the schedule.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
NA

**Anything else you would like to add:**
Schedule is getting created but velero logs says schedule not found.

**Environment:**

- Velero version (use `velero version`): 1.9.1
- Velero features (use `velero client config get features`): NA

- Kubernetes version (use `kubectl version`):  Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-06-22T04:47:11Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:  1.21.10
- Cloud provider or hardware configuration:  Bare Metal
- OS (e.g. from `/etc/os-release`): SUSE Linux Enterprise Server 15 SP4

**Comment by allenxu404** [comment]
According to the current description, I assume the schedule might be removed before the schedule reconcilation was triggered. Could you offer me more information to better locate the problem:

- What does your schedule create command look like? Could you offer me all the options you specify?

- Is there any other errors in the log?

- When this error occurred,  Did you try running `velero get schedules` to see if that schedule was still in the result list?

**Comment by siva25081994** [comment]
1) CRD's are upgraded.
2) kubectl create schedule -n namespace
***
apiVersion: velero.io/v1
kind: Schedule
metadata:
  annotations:
    meta.helm.sh/release-name: name
    meta.helm.sh/release-namespace: namespace
  labels:
    app.kubernetes.io/managed-by: Helm
    dr.ehl.gehc.com/backup_group: test_config
    ehl-app-id: test_services
    ehl-overwrite.1.kind: PersistentVolumeClaim
    ehl-overwrite.1.name: test-claim
    ehl-overwrite.1.namespace: namespace
    ehl-overwrite.2.kind: Deployment
    ehl-overwrite.2.name: test_deploy
    ehl-overwrite.2.namespace: namespace
  name: test-schedule
  namespace: namespace
spec:
  schedule: 00 23 * * 0
  template:
    includedNamespaces:
    - namespace
    labelSelector:
      matchLabels:
        velero: test
    ttl: 24h0m0s
***
This schedule is working is previous verisons of velero fine.
Following the doc for schedule creation https://velero.io/docs/v1.9/api-types/schedule/

3) No other error in the logs other than schedule not found. Since schedule is not found, backups are not getting created.
4) kubectl get schedules -A  I ran and saw all the schedules present there.

**Comment by allenxu404** [comment]
> 1. CRD's are upgraded.
> 
>     2. kubectl create schedule -n namespace
> 
> 
> apiVersion: velero.io/v1 kind: Schedule metadata: annotations: meta.helm.sh/release-name: name meta.helm.sh/release-namespace: namespace labels: app.kubernetes.io/managed-by: Helm dr.ehl.gehc.com/backup_group: test_config ehl-app-id: test_services ehl-overwrite.1.kind: PersistentVolumeClaim ehl-overwrite.1.name: test-claim ehl-overwrite.1.namespace: namespace ehl-overwrite.2.kind: Deployment ehl-overwrite.2.name: test_deploy ehl-overwrite.2.namespace: namespace name: test-schedule namespace: namespace spec: schedule: 00 23 * * 0 template: includedNamespaces: - namespace labelSelector: matchLabels: velero: test ttl: 24h0m0s
> 
> This schedule is working is previous verisons of velero fine. Following the doc for schedule creation https://velero.io/docs/v1.9/api-types/schedule/
> 
>     3. No other error in the logs other than schedule not found. Since schedule is not found, backups are not getting created.
> 
>     4. kubectl get schedules -A  I ran and saw all the schedules present there.

Thanks for your feedback. I have two questions below:

1. What are other schedules' situation? Do they run normally?

2. Did you try reinstalling Velero with latest version?

**Comment by siva25081994** [comment]
1) What are other schedules' situation? Do they run normally? - No schedule is running properly with latest version. Schedules were running fine with older versions only.

2) Did you try reinstalling Velero with latest version? - Yes I have tried reinstalling and issue remains same.

**Comment by cleverhu** [comment]
I tried it with new latest version, it works normally. Could you try by this
`kubectl create ns test`
`kubectl create deploy nginx --image=nginx -n test`
and apply for this yaml:
```
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: schedule-test
  namespace: test
spec:
  schedule: '* * * * *'
  template:
    csiSnapshotTimeout: 60m
    ttl: 24h0m0s
    includedNamespaces:
    - 'test'
    labelSelector:
      matchLabels:
        app: my-dep
```
and record the problems that happens.

**Comment by siva25081994** [comment]
Backups are getting created. But immediate backup is not getting created as velero 1.7.1 version. Is there a option available to take immediate backup when schedule is created.

**Comment by siva25081994** [comment]
Could I get help for creating immediate backups with 1.9.1 velero  version.

**Comment by allenxu404** [comment]
Walking through the code, I find no option related to immediate backup for schedule. Could you tell me what option is specified in velero 1.7.1 to take immediate backup so I can double check that.

**Comment by sseago** [comment]
@allenxu404 That's right. Schedule doesn't run a backup immediately, since when you create the schedule you tell it exactly when you want to run backups. For your schedule, it looks like you want to run it once a week, at 23:00 on Sunday.

If you *also* want to run the backup *right now* using the template from the schedule, you can run `velero backup create --from-schedule <schedule-name>` after creating the schedule.

**Comment by siva25081994** [comment]
Checked velero issues and identified creating immediate backup after schedule creation is bug and it has been rectified.
