### ISSUE TITLE
Support /status subresource on our CRDs when it's beta (v1.11)

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#529]
https://github.com/kubernetes/features/issues/571

**Comment by nikhita** [comment]
@ncdc out of curiosity, with which version of Ark will v1.11 be used?

**Comment by ncdc** [comment]
We're still determining our version matches between Ark and Kubernetes - #596

**Comment by nikhita** [comment]
@ncdc thanks!
