### ISSUE TITLE
manage PersistentVolume restore with update or recreate

### ISSUE THREAD

**Issue by gioppoluca** [vmware-tanzu/velero#5332]
**Describe the problem/challenge you have**
Is a common use case to have the need to restore a previoud point in time of data on a volume from a precise backup.
At the moment it seems that to have the backup overwrite (or recreate) the existing volume we need to remove the volume.

**Describe the solution you'd like**
In this proposal seems that the PersistemVolume is considered a non goal while this is right the need for this use case.
https://github.com/vmware-tanzu/velero/blob/main/design/existing-resource-policy_design.md#high-level-design

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.9
- Kubernetes version (use `kubectl version`): 1.21
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by Lyndon-Li** [comment]
@gioppoluca Which level do you expect to apply the overwrite policy?
1. Apply it to the PV level. That is, if the PV exists, Velero recreates it and write data to it/skip it
2. Apply it to the data level of the PV. For example, the file level, that is, if Velero finds a file already exists, Velero overwrite the file/skip the file. This also means, the PV is still the same existing PV.

@pradeepkchaturvedi Which one do you expect?

**Comment by gioppoluca** [comment]
@Lyndon-Li  the use case is this:
end user request to restore the backup of 3 days ago since he made a mess on the files (deleted things he should not have etc)

This means that the PV exists and works properly but we need to replace the data level with the content of the backup at a specific time.
In the end the technical solution of the restore:
1) destroying the PV and replacing it AND the data content 
2) keeping the PV but replacing the data content
From my perspective are equal but perhaps there are things in the PV and K8S managment or IDs etc that I ignore.
My espectation of a replacement is that not only the PV resource is replaced but also the data layer
Overwrite means that in the content all will be replaced never "skipped" the actual content gets removed and the restored content takes its place.  I have to get the stuff that was actual at the time of the backup I choose.

**Comment by Lyndon-Li** [comment]
@gioppoluca Thanks for the explanation. Give us some time to find the best way to address this in Velero.

**Comment by Lyndon-Li** [comment]
There are some details we need to cover:

1. If the PV is backed up by volumesnapshotter, the PV name is set by Velero, so rename the PV should be possible
2. If the PV is backed up by CSI plugin, the PV is created by CSI driver, so Velero has no way to set the PV's name. However, there should be no such problem, because the CSI driver always creates a new PV with a different name
3. If the PV is backed up by pod volume backup, Velero leverage kubernete's provision mechanism to create the PV when the pod is being created, so the situation depends:
    - If there is no existing released PV in the environment, kubernete's provision creates a new PV and attach to the pod, so there is no such problem
    - If there are existing released PVs, for example, statically created PVs or some PVs' retain policy is not Delete, the restored pod may bind to an exist PV. In this case, Velero needs to overwrite the provision process or its result. This is not a widely used case and the changes are too complicated.

Therefore, looks like only case 1 can be handled and other cases are either without the problem or not widely used.

**Comment by Lyndon-Li** [comment]
@gioppoluca Please let us know which one of the above 1, 2, 3 is your case. Thanks.

**Comment by Lyndon-Li** [comment]
Another approach that could eliminate the complication is doing from the PV data level, that is, when encounters an existing object during the restore, the uploader do the action according to the policy, either overwrite or skip. This requires the uploader's capability.

**Comment by reasonerjt** [comment]
Let's hold this work until the scenario is clarified.

**Comment by Lyndon-Li** [comment]
Closing as there is no further request, feel free to reopen it whenever required.
