### ISSUE TITLE
Restic backup of 200 namespaces partially fails with ensure restic repo timeout error

### ISSUE THREAD

**Issue by shubham-pampattiwar** [vmware-tanzu/velero#5334]
**What steps did you take and what happened:**

While try to backup 200 namespaces using Restic, the backup finished with `PartiallyFailed` status.

**What did you expect to happen:**

Backup to be successfully completed 

**The following information will help us better understand what's going on**:

```
time="2022-08-17T09:06:49Z" level=info msg="1 errors encountered backup up item" backup=openshift-adp/backup-restic-ocs-cephfs-200ns-label logSource="pkg/backup/backup.go:413" name=mariadb-1-5d6hz
time="2022-08-17T09:06:49Z" level=error msg="Error backing up item" backup=openshift-adp/backup-restic-ocs-cephfs-200ns-label error="timed out waiting for restic repository to become ready" error.file="/remote-source/src/github.com/vmware-tanzu/velero/pkg/restic/repository_ensurer.go:180" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryEnsurer).EnsureRepo" logSource="pkg/backup/backup.go:417" name=mariadb-1-5d6hz
time="2022-08-17T09:06:49Z" level=info msg="1 errors encountered backup up item" backup=openshift-adp/backup-restic-ocs-cephfs-200ns-label logSource="pkg/backup/backup.go:413" name=mongodb-1-b6z9z
time="2022-08-17T09:06:49Z" level=error msg="Error backing up item" backup=openshift-adp/backup-restic-ocs-cephfs-200ns-label error="restic repository is not ready: " error.file="/remote-source/src/github.com/vmware-tanzu/velero/pkg/restic/repository_ensurer.go:144" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryEnsurer).EnsureRepo" logSource="pkg/backup/backup.go:417" name=mongodb-1-b6z9z
```

**Anything else you would like to add:**
Current timeout to ensure restic repository to be ready is just [one minute](https://github.com/vmware-tanzu/velero/blob/release-1.9/pkg/restic/repository_ensurer.go#L179), this is not sufficient for large scale backups involving huge number of resources, this timeout needs to be increased, like to 5min, we should also keep this timeout configurable.

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
Per discussion, let's apply the change in PR#5335 to v1.9.2 as a quick fix.

For v1.10 we'll spend some time checking if it still exists and try to find the root cause.
