### ISSUE TITLE
Publish the support for backup created by earlier velero

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#5337]
As a B/R tool, it's common use case that user uses the latest velero to restore a backup that was created by an earlier version, say `n - x`, where the x is the step backwards.

We should be clear about what the `x` should be, to indicate what's the earliest version of velero that we will verify restoring a backup created by it.

**Comment by Lyndon-Li** [comment]
We have covered n - 1

**Comment by reasonerjt** [comment]
Ideally we should verify `n - 2`, I'll double check with other folks in community if it's OK to publish `n - 1` if we don't have bandwidth to cover that in v1.11 timeframe
