### ISSUE TITLE
Snapshots not backing up in Azure

### ISSUE THREAD

**Issue by oldManLemon** [vmware-tanzu/velero#5342]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

`velero backup create myexample --volume-snapshot-locations test --snapshot-volumes`

got an error from the snapshotter 
```
level=error msg="Error getting volume snapshotter for volume snapshot location"  error: code = Unknown desc = unable to get all required environment variables: the following keys do not have values: AZURE_SUBSCRIPTION_ID, AZURE_RESOURCE_GROUP" 
```

**What did you expect to happen:**
Backup with Volumes to be created and stored

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
[bundle-2022-09-14-13-38-38.tar.gz](https://github.com/vmware-tanzu/velero/files/9565993/bundle-2022-09-14-13-38-38.tar.gz)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Currently I am using a kind cluster to test this with a helm wordpress installation. However the results are the same in the production which is admitadly not wordpress but it is a running on VMware and we are backing up the cluster to Azure blobs. I can't get the snapshots to work and I find it odd that I can get the manifests and configs to write to the blob but the snapshotter which is the same location is claiming I don't have the the sub id or resource group. 

**Environment:**

- Velero version (use `velero version`): 1.9.1
- Velero features (use `velero client config get features`):  features: <NOT SET>
- Kubernetes version (use `kubectl version`): 1.23
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Currently Kind Cluster: Produciton is VMware server Centos. 
- OS (e.g. from `/etc/os-release`): Centos7

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
Looks like the azure credential file was not set during the installation. Please follow [here](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#:~:text=%24AZURE_RESOURCE_GROUP.-,Set%20permissions%20for%20Velero,-There%20are%20several) to set the credential file. The credential file will pass the credential related parameters to Velero, including AZURE_SUBSCRIPTION_ID and AZURE_RESOURCE_GROUP

**Comment by Lyndon-Li** [comment]
Close this issue for now, if there is any further followup, please feel free to reopen it.
