### ISSUE TITLE
please add this to docs as signoff isnt working for some reason

### ISSUE THREAD

**Issue by MansM** [vmware-tanzu/velero#5343]
https://github.com/vmware-tanzu/velero/blob/main/site/content/docs/main/api-types/schedule.md

```
# Whether velero should add owner references to the backup objects. Default false. Optional.
useOwnerReferencesInBackup: true
```

its part of crd, but not in docs:
https://github.com/vmware-tanzu/velero/blob/main/config/crd/v1/bases/velero.io_schedules.yaml

**Comment by cleverhu** [comment]
I would like to add new documents to make it more friendly. But this field is only used for cascading deletion, whether to delete backup when deleting schedule.

**Comment by cleverhu** [comment]
I would like to add new documents to make it more friendly. But this field is only used for cascading deletion, whether to delete backup when deleting schedule.

**Comment by cleverhu** [comment]
I would like to add new documents to make it more friendly. But this field is only used for cascading deletion, whether to delete backup when deleting schedule.

**Comment by MansM** [comment]
it also keeps the backups from being pruned by argo when argo annotations (like sync wave) are set on the schedule
