### ISSUE TITLE
Velero 1.9.1: velero.io/exclude-from-backup=true label over PVC does not seem to work

### ISSUE THREAD

**Issue by andy108369** [vmware-tanzu/velero#5349]
The doc suggests:

https://velero.io/docs/v1.9/resource-filtering/#veleroioexclude-from-backuptrue

> velero.io/exclude-from-backup=true
> * Resources with the label velero.io/exclude-from-backup=true are not included in backup, even if it contains a matching selector label.

However, labeling the `PVC` with `velero.io/exclude-from-backup=true` label does not make velero skip it.

Ideas?

**Comment by andy108369** [comment]
Ok, looks like I need this https://github.com/vmware-tanzu/velero/blob/v1.9.1/site/content/docs/v1.9/restic.md#using-the-opt-out-approach

**Comment by andy108369** [comment]
Yep, that worked:

```

$ kubectl -n <NS> get pods -o yaml |grep -B2 claimName
    - name: fiohistory-data
      persistentVolumeClaim:
        claimName: fiohistory-data-fiohistory-0

$ kubectl -n <NS> annotate pod/fiohistory-0 backup.velero.io/backup-volumes-excludes=fiohistory-data
pod/fiohistory-0 annotated
```

**Comment by aarononeal** [comment]
This is not particularly convenient if the PVC is already labelled, and it makes restic/kopia backups behave inconsistently. Is there a reason backups don't honor the PVC label?
