### ISSUE TITLE
Migrate /apis/extensions/v1beta1/ingresses to supported APIs

### ISSUE THREAD

**Issue by navilg** [vmware-tanzu/velero#5351]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I have velero 1.8.1 on GKE cluster. Cluster is on version 1.21. In K8s version 1.22, Some of the APIs are being removed and /apis/extensions/v1beta1/ingresses is one of them. GKE is showing warning to migrate this api to supported api which is originating from velero. 

**What did you expect to happen:**

API /apis/extensions/v1beta1/ingresses must be upgraded to supported API /apis/extensions/v1/ingresses

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.8.1
- Velero features (use `velero client config get features`): NOT SET
- Kubernetes version (use `kubectl version`): 1.21.14
- Kubernetes installer & version: GKE 1.21.14-gke.700
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): Ubuntu

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
This is the same issue with #5187, please refer to the issue for details.

**Comment by blackpiglet** [comment]
@navilg 
Since there is already a similar issue, could we close this one?

**Comment by navilg** [comment]
> @navilg 
> Since there is already a similar issue, could we close this one?

Yes please. Thanks
