### ISSUE TITLE
make test is failing sometimes on TestGetVolumesRepositoryType

### ISSUE THREAD

**Issue by sseago** [vmware-tanzu/velero#5352]
**What steps did you take and what happened:**

run `make test` (mainly seen during PR CI check)
I get the following failure sometimes:
```
--- FAIL: TestGetVolumesRepositoryType (0.00s)
    --- FAIL: TestGetVolumesRepositoryType/mismatch_repository_type (0.00s)
        restorer_test.go:87: 
            	Error Trace:	restorer_test.go:87
            	Error:      	Error message not equal:
            	            	expected: "multiple repository type in one backup, current type fake-type1, differential one [type fake-type2, snapshot ID fake-snapshot-id-2, uploader fake-uploader-2]"
            	            	actual  : "multiple repository type in one backup, current type fake-type2, differential one [type fake-type1, snapshot ID , uploader ]"
            	Test:       	TestGetVolumesRepositoryType/mismatch_repository_type
```
It's inconsistent, though. Re-running tests or pushing another commit to the PR will often cause the error to go away. In the most recent occurance, the CI test failed twice, but passed on the third attempt -- another PR pushed at about the same time passed on the first run.

**What did you expect to happen:**
No CI errors.

**Environment:**

- Velero version (use `velero version`): Last seen with PR ci check against main on 16 Sept 2022

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
Fixed by #5356
