### ISSUE TITLE
Sometimes PVB fails with repo not initialized

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#5358]
After the code refactor for Kopia PVBR, sometimes, the PVB fails and complains "repo not initialized":

time=“2022-09-16T10:53:10Z” level=error msg=“Error backing up item” backup=velero/backup-7ff66b47-e194-4c9e-8ad8-354e42ffbe31 error=“pod volume backup failed: error creating uploader: failed to connect repository: error running command=restic snapshots --repo=s3:s3-us-west-2.amazonaws.com/velero-e2e-testing-1663324273332/default/restic/kibishii-workload --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic --latest=1, stdout=, stderr=Fatal: unable to open config file: Stat: The specified key does not exist.\nIs there a repository at the following location?\ns3:s3-us-west-2.amazonaws.com/velero-e2e-testing-1663324273332/default/restic/kibishii-workload\n: exit status 1” error.file=“/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:223" error.function=“github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes” logSource=“pkg/backup/backup.go:425" name=kibishii-deployment-0

**Comment by sseago** [comment]
I'm seeing the same error in the context of oadp e2e tests after updating to velero main recently.

**Comment by kaovilai** [comment]
related to https://github.com/vmware-tanzu/velero/issues/4421

**Comment by sseago** [comment]
This could be a race condition with backup repository created but not yet ready when PVB fails. In the most recent OADP failure, it looks like the PVB fails about 2 seconds prior to the "last maintenance time" of the backup repository, which is likely when it became ready:
failed PVB completion timestamp:

  Completion Timestamp:  2022-09-19T22:37:59Z

backup repository creation time was only one second before this, and "last maintenance time" (likely when it became ready) was two seconds after this:

  Creation Timestamp:  2022-09-19T22:37:58Z
  Last Maintenance Time:  2022-09-19T22:38:01Z
  Phase:                  Ready

**Comment by Lyndon-Li** [comment]
@sseago See PR #5359, we have found a possible cause of this problem and will let you know when the fix pass Velero E2E test.

**Comment by Lyndon-Li** [comment]
Fixed by #5359
