### ISSUE TITLE
Create example Grafana dashboard

### ISSUE THREAD

**Issue by rosskukulinski** [vmware-tanzu/velero#536]
Once Ark has exposed prometheus metrics (#84 / #531), it would be great if we had an example Grafana dashboard for visualizing the state of Ark.

In the simplest form, this could be checked into the Ark repo.  It could also be published to the Grafana dashboard community (https://grafana.com/dashboards).

Variables:
* Backup Name
* Schedule Name

Potential end-user graphs:
* Gauge showing number of active backups
* Gauge showing number of active restores
* Backup success rate (completions / attempts) over time
* Restore success rate (completions / attempts) over time
* Rate of backups over time
* Rate of restores over time
* {99, 95, 50}% duration for Restores over time
* {99, 95, 50}% duration for Backups over time
* {99, 95, 50} percentiles of backup byte size over time
* {99, 95, 50} percentiles of restore byte size over time

**Comment by rosskukulinski** [comment]
@ashish-amarnath as you're working on #531 and find yourself creating a grafana dashboard to test with, here's an initial take at what some useful graphs might be.

**Comment by ashish-amarnath** [comment]
Good idea!

**Comment by vitobotta** [comment]
Hi! Does a Grafana dashboard for Velero/Ark exist yet? I managed to have Prometheus operator scrape the Velero metrics but I don't know how to use them. Thanks

**Comment by skriss** [comment]
@vitobotta we don't have a sample one, but maybe another use has something they can share.

**Comment by bryanlarsen** [comment]
see also #1136

**Comment by bryanlarsen** [comment]
![Backups   Grafana](https://user-images.githubusercontent.com/32073/61084116-4e763800-a3fb-11e9-95fe-d7c210302d16.png)
![Backups   Grafana(1)](https://user-images.githubusercontent.com/32073/61084121-50d89200-a3fb-11e9-9f73-854ca874695a.png)

**Comment by HaveFun83** [comment]
Hi i created a velero dashboard but the following metrics are missing:
velero_restore_duration_seconds_bucket
velero_restore_tarball_size_bytes

Maybe it will be useful as blueprint. Any suggestions are welcome.

https://gist.github.com/HaveFun83/57b41e85fde4249daab74a9850885f6a#file-kubernetes-_-addons-_-velero-stats-1568113703354-json

**Comment by CarpathianUA** [comment]
> Hi i created a velero dashboard but the following metrics are missing:
> velero_restore_duration_seconds_bucket
> velero_restore_tarball_size_bytes
> 
> Maybe it will be useful as blueprint. Any suggestions are welcome.
> 
> https://gist.github.com/HaveFun83/57b41e85fde4249daab74a9850885f6a#file-kubernetes-_-addons-_-velero-stats-1568113703354-json

Hi @HaveFun83 , thanks for a dashboard!
I see you calculate 'Active backup' with `sum(rate(velero_backup_attempt_total[15m])) / sum(rate(velero_backup_success_total[15m]))`
May I kindly ask you to spread some light on that? Thanks in advnace!

**Comment by HaveFun83** [comment]
> > Hi i created a velero dashboard but the following metrics are missing:
> > velero_restore_duration_seconds_bucket
> > velero_restore_tarball_size_bytes
> > Maybe it will be useful as blueprint. Any suggestions are welcome.
> > https://gist.github.com/HaveFun83/57b41e85fde4249daab74a9850885f6a#file-kubernetes-_-addons-_-velero-stats-1568113703354-json
> 
> Hi @HaveFun83 , thanks for a dashboard!
> I see you calculate 'Active backup' with `sum(rate(velero_backup_attempt_total[15m])) / sum(rate(velero_backup_success_total[15m]))`
> May I kindly ask you to spread some light on that? Thanks in advnace!

the graph should represent @rosskukulinski suggestion:
Gauge showing number of active backups

But you are right this expression makes no sense i changed it

**Comment by vitobotta** [comment]
Hi @HaveFun83 ! Thanks for the dashboard, very useful. What is "Backup Time"? I thought it's the duration but it only shows a flat bar on the zero for me. Also, what does "Backup Success" show in case there are failed backups? Thanks!

**Comment by HaveFun83** [comment]
> Hi @HaveFun83 ! Thanks for the dashboard, very useful. What is "Backup Time"? I thought it's the duration but it only shows a flat bar on the zero for me. Also, what does "Backup Success" show in case there are failed backups? Thanks!

Backup Time shows the "velero_backup_duration_seconds_bucket" metric can you check your Prometheus if there is any data available?

Backup Success rate must be 1 if its below something is wrong.
Failed backups should be visible in "Backup Total Count"

**Comment by ashish-amarnath** [comment]
@mtritabaugh You can work on this if you would like. I am not finding a way to assign this to you either :)

**Comment by mtritabaugh** [comment]
@nrb @ashish-amarnath Please assign this to me, thank you.

**Comment by link-webcreations** [comment]
Hello @mtritabaugh, thanks for working on this topic !!
May I ask you if everything goes well ?
if you already have a draft, I would be glad to test it !

**Comment by invidian** [comment]
I think this would still be very valuable.

**Comment by reasonerjt** [comment]
@allenxu404 Could you also investigate the best way to publish the configuration, like publish it to the grafana official website?

**Comment by allenxu404** [comment]
> Hi i created a velero dashboard but the following metrics are missing: velero_restore_duration_seconds_bucket velero_restore_tarball_size_bytes
> 
> Maybe it will be useful as blueprint. Any suggestions are welcome.
> 
> https://gist.github.com/HaveFun83/57b41e85fde4249daab74a9850885f6a#file-kubernetes-_-addons-_-velero-stats-1568113703354-json

Thanks @HaveFun83 for making a contribution to the first Velero dashboard which was taken as an important reference for me when I made the dashboard. 
I've already finished another dashboard including all the prometheus metrics and uploaded [the template](https://grafana.com/grafana/dashboards/16829-kubernetes-allen-velero/) on Grafana Labs. We will keep updating it based on the development version of Velero. Feel free to contact us if you have any issue with it.

**Comment by aslafy-z** [comment]
If you dig into the yaml, you'll see the datasource variable is called `DS_PROMETHEUS-1` which causes Grafana to error when provisioning it with the dashboards Helm Chart value (see https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L631). Here's the exact error:
![image](https://user-images.githubusercontent.com/8191198/196456824-b365a5a5-7de4-4ba6-8033-881b17434d35.png)
However, it works while importing it using the Grafana UI. 
I think renaming `DS_PROMETHEUS-1` to `DS_PROMETHEUS` might do the trick? 
Also, could this dashboard be integrated into this GitHub repository? It would ease updates and discussions around it.

**Comment by weshayutin** [comment]
@myprc FYI

**Comment by reasonerjt** [comment]
@aslafy-z 

Are you suggesting maintain the grafana configuration in velero repo?

Could you please open an new issue for discussion given the example is considered "done"
