### ISSUE TITLE
SOLVED: config has invalid keys [s3Url s3ForcePathStyle]

### ISSUE THREAD

**Issue by MrDix** [vmware-tanzu/velero#5360]
**What steps did you take and what happened:**
Installed velero via official vmware-tanzu/velero helm chart (chart version 2.31.6, app version 1.9.1).
Activated s3 plugin 1.5.0 via chart values and configured default backup and snapshot locations to baskets on my minio server.

Now I executed:
`velero backup create full-backup.2022-09-19.14-39-56`

`velero backup describe full-backup.2022-09-19.14-39-56` shows:
"Phase:  PartiallyFailed"

S3/minio backup basket shows lots of created files.

In `velero backup logs full-backup.2022-09-19.14-39-56` I see several messages like this (but no other type of critical messages):

`time="2022-09-19T12:40:01Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/full-backup.2022-09-19.14-39-56 error="rpc error: code = Unknown desc = config has invalid keys [s3Url s3ForcePathStyle]; valid keys are [region profile credentialsFile enableSharedConfig]" error.file="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.7.1/pkg/plugin/framework/validation.go:50" error.function=github.com/vmware-tanzu/velero/pkg/plugin/framework.validateConfigKeys logSource="pkg/backup/item_backupper.go:453" name=pvc-ff5afaab-7876-4ccc-9687-17e34b2ee7fa namespace= persistentVolume=pvc-ff5afaab-7876-4ccc-9687-17e34b2ee7fa resource=persistentvolumes volumeSnapshotLocation=default`

Created default BackupStorageLocation looks like this:
```Name:         default
Namespace:    velero
Labels:       app.kubernetes.io/instance=velero
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=velero
              helm.sh/chart=velero-2.31.6
Annotations:  helm.sh/hook: post-install,post-upgrade,post-rollback
              helm.sh/hook-delete-policy: before-hook-creation
API Version:  velero.io/v1
Kind:         BackupStorageLocation
Metadata:
  Creation Timestamp:  2022-09-19T12:34:35Z
  Generation:          221
  Managed Fields:
    API Version:  velero.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:helm.sh/hook:
          f:helm.sh/hook-delete-policy:
        f:labels:
          .:
          f:app.kubernetes.io/instance:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/name:
          f:helm.sh/chart:
      f:spec:
        .:
        f:accessMode:
        f:config:
          .:
          f:region:
          f:s3ForcePathStyle:
          f:s3Url:
        f:objectStorage:
          .:
          f:bucket:
          f:caCert:
        f:provider:
    Manager:      helm
    Operation:    Update
    Time:         2022-09-19T12:34:35Z
    API Version:  velero.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:default:
      f:status:
        .:
        f:lastSyncedTime:
        f:lastValidationTime:
        f:phase:
    Manager:         velero-server
    Operation:       Update
    Time:            2022-09-19T12:34:52Z
  Resource Version:  88794230
  UID:               3f46b667-f89f-4c10-8550-2aa69deb86d2
Spec:
  Access Mode:  ReadWrite
  Config:
    Region:            minio
    s3ForcePathStyle:  true
    s3Url:             https://s3.MYDNS.NAME
  Default:             true
  Object Storage:
    Bucket:   velero-vega-k8s-backups
    Ca Cert:  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUhrekNDQlh1Z0F3SUJBZ0lUTGdDSVRUM2hnN3FmaU9mQUlBQUFBSWhOUFRBTkJna3Foa2lHOXcwQkFRc0YKQURCQk1Rc3dDUVlEVlFRR0V3SkVSVEVUTUJFR0ExVUVDZ3dLUkdGcGJXeGxjaUJCUnpFZE1Cc0dBMVVFQXd3VQpRMjl5Y0MxSmMzTjFhVzVuTFVOQk1ERXRSekl3SGhjTk1qSXdOVEkyTURRek9EUXhXaGNOTWpRd05USTFNRFF6Ck9EUXhXakNCb1RFTE1Ba0dBMVVFQmhNQ1JFVXhHekFaQmdOVkJBZ01Fa0poWkdWdUxWZDFaWEowZEdWdFltVnkKWnpFU01CQUdBMVVFQnd3SlUzUjFkSFJuWVhKME1SOHdIUVlEVlFRS0RCWk5aWEpqWldSbGN5MUNaVzU2SUVkeQpiM1Z3SUVGSE1Rd3dDZ1lEVlFRTERBTkpWRTB4RFRBTEJnTlZCQXNNQkZaRlIwRXhJekFoQmdOVkJBTU1HblpsCloyRXRaR1YyTG1Gd2NDNWpiM0p3YVc1MGNtRXVibVYwTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEEKTUlJQ0NnS0NBZ0VBcTdqcFNWT0o1ZVp6LzEvbExLckxieFJvQ3NCeG9GeXZVaGhLQWpqbU5rTU5GK2h4aUF4cgprVWhaVGlvK2tBSis0SnpPS0FvTWFuL1AwS00yN0NxcW9FTFcxZGg3SHlXMStDMXo4c0pWWEk4NUg0bkNxeEY1ClJoTGlhSm5nTlZOVmZrdTY5ejNDSUZaWGw5QThVSTZpbkdXUDBCSEtJUW9nWmJYQlgvVm8rK1JGYTBOU0tpRGoKaE8xWkRBS292OWFzakR5WStjcmMxbE1HdFAyM1NTaVFlSkdFVmpic0hyQ3EwQmxBd0FVOERCeDVLRFE4L1MwaQpXWm43a2NNZlFtd3VMRGlyeTFRUlFlT3VXWEJzTUlhT2xodWt4dzJyQ29xd1g2cDNSbEpUMlhrcEFuOWh3cXhwCndEbVhHWFJBRjl3RG9aRkhsTWlVbk14eFo0ajlzU1pic2VjZUcxcTVxOWUwZTh0dUtKNzVTTW5GbE9YNWhGVjUKNkRoZXBRVkpKYlkrRWVVVFZnWk5pSUV5bktuRFBERVlPcG1MUG15UjhpMXFkekJCcEdqemFzOW9QYndOWnhDWAo0YWZQSDZNd1FrY1VCNjZURUE5bUt5Q2hEVFNKcy9RNVh0YjhqUVByZFNmYm1GT2xnNUJManJFNkJ0RWFtMmVqCk0rZVFWalcvdVhkSFROS0tjUFJwWkxYVGNwTVJ5WW1HNFNNNTVMRXpHYldBRFd6ck5KSHRmNVZ0aVA1WFBmQ3IKOVZkYUdZeXUrZ3NRVFp0VXRQMVZlbU1lQXJvRzdmU2t3M0RqbUxLQ1IxR2hmSFlwWEREcHlaU1BvdngyYytSNwp2NFFvazVqa205TkJkei8ybnZvNDF3SUdTWVpPVEREclNqOEk2VDB0TTZFNjJkTWhiV3I2TndzQ0F3RUFBYU9DCkFpRXdnZ0lkTUhzR0ExVWRFUVIwTUhLQ0duWmxaMkV0WkdWMkxtRndjQzVqYjNKd2FXNTBjbUV1Ym1WMGdod3EKTG5abFoyRXRaR1YyTG1Gd2NDNWpiM0p3YVc1MGNtRXVibVYwZ2hwMlpXZGhhbWx5WVM1aGNIQXVZMjl5Y0dsdQpkSEpoTG01bGRJSWFkbVZuWVhkcGEya3VZWEJ3TG1OdmNuQnBiblJ5WVM1dVpYUXdIUVlEVlIwT0JCWUVGSWcxClJMTlQ4YURqTzg5cFFjbFZIR3R5QkFkUk1COEdBMVVkSXdRWU1CYUFGRXlTSTlzTlB0QWFPSllSQU96MUpiNHIKQldCeU1FY0dBMVVkSHdSQU1ENHdQS0E2b0RpR05taDBkSEE2THk5d2Eya3VZMjl5Y0hOb1lYSmxaQzV1WlhRdgpZMlJ3TDBOdmNuQXRTWE56ZFdsdVp5MURRVEF4TFVjeUxtTnliREIvQmdnckJnRUZCUWNCQVFSek1IRXdRZ1lJCkt3WUJCUVVITUFLR05taDBkSEE2THk5d2Eya3VZMjl5Y0hOb1lYSmxaQzV1WlhRdllXbGhMME52Y25BdFNYTnoKZFdsdVp5MURRVEF4TFVjeUxtTnlkREFyQmdnckJnRUZCUWN3QVlZZmFIUjBjRG92TDI5amMzQXVZMjl5Y0hObwpZWEpsWkM1dVpYUXZiMk56Y0RBOEJna3JCZ0VFQVlJM0ZRY0VMekF0QmlVckJnRUVBWUkzRlFpR3J1UXExWnhiCmdlMkhHb0tmdUY2RTVaRmFlNEdJd2xpR2d0ZFdBZ0ZrQWdFR01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUMKQmdnckJnRUZCUWNEQVRBT0JnTlZIUThCQWY4RUJBTUNCYUF3SndZSkt3WUJCQUdDTnhVS0JCb3dHREFLQmdncgpCZ0VGQlFjREFqQUtCZ2dyQmdFRkJRY0RBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBTFo1bFhraS95YlRDCnBoc2M3dzVyR3FjNXY5K1BZWGpubkZ4QThOOEk4M2RRQk1OS21SMXczOTVVT1VMdHF5dGMxOUZjeTZkcEpwMkoKSVJjUWNsSDJXSEtIK3l5TXNIdWRVYVNZRzl0WUl5b3BISmhDTmRIT3cwVWl1UGkyZFBzNGN4RkR6Lzl3cjg4UwowZ0lTNnI0STd2MkUvQzVpRU1MRGRCUFJ5NlJhM2hUb3hwM21RcnVSNy9ieXp1Nk53S1NhbDVidlhpWEIxaFVkCnRkTDhTNEVlc3I1enlDWUh1TGYvWXFZSFB3bmVOMnMrbU94cVBrNmwwaFZBWE42TnViMUU5Q2dWdGtCajhhVkoKNHlEaUpRRjAwUHZIWWFabWtMd0liTG1raWVDL0N0cTJld0UyUm1MdzIzNDhldnpiNFU5Vm0rdlpsU1ZuaEZabQpVTEluRTlESjUrSnplaUlWeG9WQkwvZ1VxRjFEVHZkRkM3WVFVOGUxL1d5VkZHUDAvNzF4ZFZSV2ZKRzJ2S3dRCnRIRDBpRnNUVUVXaU1LVGJjanFvMUdNRSszL3E5U2hVUUZTU2V0WlpaNHdGSXZjVklXRGhXWDJvWWp2cDgwWHYKaWxjd1liZkRCbmRIL2QxUmpXWkQ5bEhyVjMrWGNYUStyZ1BQZlZMaGVDcUpCWFpmYkpLYy9pOGhTOVpyaXNobwo3UlhXR1Y3V2lQR0MxSkErNUNoL1J3cnJZVWhxOE1xQ2tVMWJCMXRweWNXbE5JTmdzRk8vbyt0MEFkeEQraDhDCjNtVS9QbDlaZEIvUDkrVDNXcXh1RU5zcHNjOUNSaklVOUNkV01wRU54amE2VGN5T3NUcnFmekRzd0NkSVlvQVQKRFNYeHRmZ1JWbjJOQ0ZFV1lhZ2tHaUVMbUZrM0RDcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  Provider:   aws
Status:
  Last Synced Time:      2022-09-19T14:24:00Z
  Last Validation Time:  2022-09-19T14:24:16Z
  Phase:                 Available
Events:                  <none>
```

I only replaced the DNS name for s3Url in the upper yaml.
For my unskilled eyes the specs section of this default BackupStorageLocation looks good and as content got created in the given S3 backup basket I assume the two config options s3Url and s3ForcePathStyle have been applied.  
Can you point me to the problem the backup job complains about?

**What did you expect to happen:**
A successful creation of the k8s full backup without error messages in the backup log.

**The following information will help us better understand what's going on**:
[bundle-2022-09-19-16-11-22.tar.gz](https://github.com/vmware-tanzu/velero/files/9599854/bundle-2022-09-19-16-11-22.tar.gz)

**Environment:**

- Velero version (use `velero version`): 1.9.1
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): 1.24.2
- Kubernetes installer & version: kubeadm 1.24.2
- Cloud provider or hardware configuration: bare-metal Dell R740 servers for K8S control plane and nodes-
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.5 LTS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
You set wrong config for `VolumeSnapshotLocation`, `s3Url` and `s3ForcePathStyle` aren't the correct configuration for VSL:
```json
{
    "apiVersion": "velero.io/v1",
    "items": [
        {
            "apiVersion": "velero.io/v1",
            "kind": "VolumeSnapshotLocation",
            "metadata": {
                "annotations": {
                    "helm.sh/hook": "post-install,post-upgrade,post-rollback",
                    "helm.sh/hook-delete-policy": "before-hook-creation"
                },
                "creationTimestamp": "2022-09-19T12:34:36Z",
                "generation": 1,
                "labels": {
                    "app.kubernetes.io/instance": "velero",
                    "app.kubernetes.io/managed-by": "Helm",
                    "app.kubernetes.io/name": "velero",
                    "helm.sh/chart": "velero-2.31.6"
                },
                "managedFields": [
                    {
                        "apiVersion": "velero.io/v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:metadata": {
                                "f:annotations": {
                                    ".": {},
                                    "f:helm.sh/hook": {},
                                    "f:helm.sh/hook-delete-policy": {}
                                },
                                "f:labels": {
                                    ".": {},
                                    "f:app.kubernetes.io/instance": {},
                                    "f:app.kubernetes.io/managed-by": {},
                                    "f:app.kubernetes.io/name": {},
                                    "f:helm.sh/chart": {}
                                }
                            },
                            "f:spec": {
                                ".": {},
                                "f:config": {
                                    ".": {},
                                    "f:region": {},
                                    "f:s3ForcePathStyle": {},
                                    "f:s3Url": {}
                                },
                                "f:provider": {}
                            }
                        },
                        "manager": "helm",
                        "operation": "Update",
                        "time": "2022-09-19T12:34:36Z"
                    }
                ],
                "name": "default",
                "namespace": "velero",
                "resourceVersion": "88758962",
                "uid": "ab9ffa43-c555-40f7-8e67-ba5ae57bd9b4"
            },
            "spec": {
                "config": {
                    "region": "minio",
                    "s3ForcePathStyle": "true",
                    "s3Url": "https://s3.vega-dev.app.corpintra.net"
                },
                "provider": "aws"
            }
        }
    ],
    "kind": "VolumeSnapshotLocationList",
    "metadata": {
        "continue": "",
        "resourceVersion": "88790087"
    }
}

```

**Comment by MrDix** [comment]
Hello ywk253100,

Thank you for the fast reply!
Unfortunately I do not get what I have done wrong. I used the official helm chart and set those overwrites:
```
credentials:
  useSecret: true
  existingSecret: velero-s3-secret

configuration:
  provider: aws
  backupStorageLocation:
    bucket: velero-vega-k8s-backups
    config:
      region: minio
      s3ForcePathStyle: true
      s3Url: https://s3.vega-dev.app.corpintra.net
  volumeSnapshotLocation:
    bucket: velero-vega-k8s-snapshots
    config:
      region: minio
      s3ForcePathStyle: true
      s3Url: https://s3.vega-dev.app.corpintra.net

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.5.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /target
      name: plugins
```

The `BackupStorageLocation` got created from the helm chart based on those values.
What is 'VSL' and what did I exactly set wrong here?

Velero full backup created content in the configured `s3Url`/`bucket` and as far as I read the `s3ForcePathStyle` needs to be set to `true` when used with a local minio server.

**Comment by ywk253100** [comment]
`s3ForcePathStyle` and `s3Url` aren't the valid value for VolumeSnapshotLocation: https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml#L265, you should remove them.

BTW, does your underlying storage provider support snapshot? If it doesn't, you don't need to set the VolumeSnapshotLocation at all

**Comment by MrDix** [comment]
Thanx for pointing me into the right direction! :kissing_heart:
I've removed those misconfigurations and backup completes successfully.
My default storage provider is Longhorn and does support snapshots.

One more time: Thank you very much for your great support!

**Comment by mreiche** [comment]
I you don't have VolumeSnapshots, you need to delete the *VolumeSnapshotLocation* CRD as well.

**Comment by giz33** [comment]
@MrDix Hello!
How are you?
I am having the same problem that you had.
I removed the invalid parameters as you did, but now it did not trigger the backup on my Longhorn.
On the Backup Tab on Longhorn UI I check and it didn't generated the backup and also nothing on the longhorn bucket that I created on my Minio.


Thanks in advance for any help.

**Comment by giz33** [comment]
I was able to solve it, I give below the installation snippet that I used to anyone who pass trough the same problem:

helm upgrade --install velero \
    --namespace=velero \
    --create-namespace \
    --set-file credentials.secretContents.cloud=/root/velero/credentials-velero \
    --set configuration.backupStorageLocation[0].provider=aws \
    --set configuration.backupStorageLocation[0].name=default \
    --set configuration.backupStorageLocation[0].bucket=velero \
    --set configuration.backupStorageLocation[0].config.region=client-minio \
    --set configuration.backupStorageLocation[0].config.s3ForcePathStyle=true \
    --set configuration.backupStorageLocation[0].config.s3Url='http://3.74.135.55:32300' \
    --set configuration.backupStorageLocation[0].config.publicUrl='http://3.74.135.55:32300' \
    --set snapshotsEnabled=true \
    --set configuration.volumeSnapshotLocation[0].provider=aws \
    --set configuration.volumeSnapshotLocation[0].name=default \
    --set configuration.volumeSnapshotLocation[0].config.region=client-minio \
    --set configuration.features=EnableCSI \
    --set "initContainers[0].name=velero-plugin-for-aws" \
    --set "initContainers[0].image=velero/velero-plugin-for-aws:v1.6.0" \
    --set "initContainers[0].volumeMounts[0].mountPath=/target" \
    --set "initContainers[0].volumeMounts[0].name=plugins" \
    vmware-tanzu/velero

Tks
