### ISSUE TITLE
Delete backup does not delete Restic data

### ISSUE THREAD

**Issue by eemcmullan** [vmware-tanzu/velero#5366]
**What steps did you take and what happened:**
- create a backup using Restic:
`velero backup create backuptest --include-namespaces mssql-persistent --default-volumes-to-restic=true`

```
velero $ velero describe backup backuptest                                    
Name:         backuptest
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.23.5+b0357ed
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=23

Phase:  Completed

Errors:    0
Warnings:  0

Namespaces:
  Included:  mssql-persistent
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2022-09-20 12:25:55 -0400 EDT
Completed:  2022-09-20 12:26:45 -0400 EDT

Expiration:  2022-10-20 12:25:55 -0400 EDT

Total items to be backed up:  42
Items backed up:              42

Velero-Native Snapshots: <none included>

Restic Backups (specify --details for more information):
  Completed:  1
```

- deleted the backup:

```
velero $ velero delete backup backuptest
Are you sure you want to continue (Y/N)? y
Request to delete backup "backuptest" submitted successfully.

velero $ velero describe backup backuptest                                  
An error occurred: backups.velero.io "backuptest" not found
```

- Restic backup data:

```
velero $ aws s3 ls mybucket/velero/                             
                           PRE restic/
```

```
velero $ aws s3 ls mybucket/velero/restic/mssql-persistent/data/   
                           PRE 32/
                           PRE 37/
                           PRE 38/
                           PRE 46/
                           PRE 53/
                           PRE 6a/
                           PRE 75/
                           PRE a7/
                           PRE c2/
                           PRE e7/
                           PRE f2/

```

**What did you expect to happen:**
The Restic backup data to be deleted.

**Environment:**

- Velero version (use `velero version`): v1.9.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): OCP 4.10.6
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
Restic backup data basically include two parts: the snapshot and the data content (in the `data` folder as you shared). The snapshot is a collection of references to the data contents.

For a Restic backup deletion process, which is also called by Velero's backup deletion, it deletes the snapshot itself only and doesn't touch the data content. After the snapshot is deleted, the related data content will be orphan, and once a maintenance/prune process runs, the orphan data content will be deleted.

That is to say, it is the expected behavior that you don't see files in the `data` folder been deleted.

**Comment by eemcmullan** [comment]
Thank you for the response.

**Comment by ywk253100** [comment]
I'm closing this issue as it works as expected. Feel free to reopen it if you have any further questions
