### ISSUE TITLE
Velero deleted my backup. 

### ISSUE THREAD

**Issue by migs35323** [vmware-tanzu/velero#5381]
**Describe the problem/challenge you have**

My cluster died and after a long time i finally wanted to rescue it.
I did a backup some time ago with velero, and i was about to restore when i just found out velero deleted my backup
now my old deployments are all gone....
there is a default TTL aparently and we can't choose it to be forever.

**Describe the solution you'd like**

hability to keep a backup forever. (TTL: 0 || TTL: false || TTL: disabled)
If possible make it the default setting when someone makes a manual backup (not schedule)
if we are creating a backup manually without rules this usually means we which to keep it and manually delete it if we need...

**Environment:**

- Velero version (use `velero version`): Version: v1.9.1
- Kubernetes version (use `kubectl version`): 1.24
- Kubernetes installer & version: kubeadm
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from `/etc/os-release`): ubuntu server

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by sseago** [comment]
The default ttl can be changed as an arg to the /velero command in the velero deployment. This won't affect existing backups, but it will be used for new backups when that field isn't set. While "forever" isn't a valid Duration value, you could just set it to a really long time. 100 years or so? So instead of the default of `720h0m0s` you could just use a much larger number of hours.

**Comment by migs35323** [comment]
> The default ttl can be changed as an arg to the /velero command in the velero deployment. This won't affect existing backups, but it will be used for new backups when that field isn't set. While "forever" isn't a valid Duration value, you could just set it to a really long time. 100 years or so? So instead of the default of `720h0m0s` you could just use a much larger number of hours.

thank you for the reply, well maybe i could use that meanwhile
the documentation doesn't specify the allowed values, does it allow `100y` as input, or what ranges does it accept?

Also, does that mean i can't change the expiration date on existing backups?

**Comment by ywk253100** [comment]
There is no range for the expiration value.
And you can patch the `expiration` field by `kubectl` to change it for the existing backups.

**Comment by sseago** [comment]
Expiration is defined as a duration -- I think the largest unit in the format is `h` for hours, so you'd need to specify the number of hours -- the 30 day default is specified as "720h0m0s". The upper limit is based on the underlying int64 storage (stored internally in nanoseconds) -- it maxes out somewhere around 290 years.
