### ISSUE TITLE
kubectl -n velero exec -ti deploy/velero -- bash cmd is not working since 1.7.0 but velero doc still use it

### ISSUE THREAD

**Issue by jhuisss** [vmware-tanzu/velero#5385]
When I look through the latest velero doc https://velero.io/docs/v1.9/troubleshooting/, it says 
Confirm that the cloud-credentials secret exists and has the correct content.
$ kubectl -n velero get secrets cloud-credentials
NAME                TYPE     DATA   AGE
cloud-credentials   Opaque   1      11h

But according to https://github.com/vmware-tanzu/velero/releases/tag/v1.7.0, the Velero container images now use [distroless base images](https://github.com/GoogleContainerTools/distroless), and as the [distroless](https://github.com/GoogleContainerTools/distroless) images do not contain a shell, it will no longer be possible to exec into Velero containers using these images.

So it should be a doc error, please update it.

Besides, if velero server pod could contain a shell, it should be more friendly to users.

**Comment by cleverhu** [comment]
I'd like to fix the doc error.

**Comment by ywk253100** [comment]
@cleverhu Thanks!

**Comment by cleverhu** [comment]
@ywk253100 I tried yesterday,I found it hard to exec in the container, not only 'ls' but also the basic command of 'ls' or 'cat' are not existed in the container.Is there some advice to fix the doc?

**Comment by ridgekuhn** [comment]
I'm having trouble with credentials and came here to file the same issue. I can't do this last step since there's no shell or `cat` cmd, so I guess I'm stuck, lol

```
3. Confirm if the correct credentials are mounted into the Velero pod.

$ kubectl -n velero exec -ti deploy/velero -- bash
nobody@velero-69f9c874c-l8mqp:/$ cat /credentials/cloud
<Output should be your credentials>
```

**Comment by ridgekuhn** [comment]
@ VickyWinner I'm very sorry. I did eventually get Velero to work, but I haven't touched the project in several weeks, and I forgot what I was doing wrong or how I fixed it. It looks like there's a new version of Velero out, but the docs still haven't been updated. :(
