### ISSUE TITLE
velero plugin for GCP should support VSL's credential when doing snapshot

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#5391]
With #4864 merged, the user will be able to set a credential in VSL.

The plugin for GCP should be updated to support it.

**Comment by blackpiglet** [comment]
Test done for the change:
1. Do not specify the credential in VSL's spec. Let GCP plugin read the credential from environment variable `GOOGLE_APPLICATION_CREDENTIALS`. 
2. First create secret in `velero` namespace, specify credential in VSL's spec. 
``` bash
kubectl create secret generic -n velero --from-file=/Users/jxun/Documents/credentials-velero-gcp vsl-credential
kubectl -n velero patch VolumeSnapshotLocation default -p '{"spec":{"credential":{"name":"vsl-credential", "key":"cloud-credentials-gcp"}}}' --type=merge
```
