### ISSUE TITLE
Bump to the latest versions due to detection of vulnerability scanning

### ISSUE THREAD

**Issue by VF-mbrauer** [vmware-tanzu/velero#5395]
**Describe the problem/challenge you have**
Bump Framework and Libraries to the latest version as also a lot of CVE's are from 2021-*

**Describe the solution you'd like**
Container Scanner still shows with the latest version a lot of vulnerabilities.

**Anything else you would like to add:**
```
velero/velero:latest (debian 11.4)

Total: 14 (UNKNOWN: 0, LOW: 11, MEDIUM: 2, HIGH: 1, CRITICAL: 0)
**Environment:**
```

```
usr/bin/restic (gobinary)

Total: 8 (UNKNOWN: 2, LOW: 0, MEDIUM: 1, HIGH: 5, CRITICAL: 0)
```

```
velero (gobinary)

Total: 13 (UNKNOWN: 6, LOW: 1, MEDIUM: 2, HIGH: 4, CRITICAL: 0)
```

- Velero version 1.9.2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
@VF-mbrauer 
Thanks for reporting the issue, we do have regular security scan for each release, mainly the CVEs are around libc, and it will be removed once vsphere-plugin has a new release to remove the dependency.

It's known that different scanner may report different CVEs, some of them are false positives.  

Would you mind sending me the detailed scan report, I'm curious about the CVEs in the velero and restic go binary.

**Comment by VF-mbrauer** [comment]
@reasonerjt 
An email has been sent to your email address as mentioned above.
Just let me know if you need something else.
Thanks a lot.

**Comment by VF-mbrauer** [comment]
@reasonerj: Any news here?

**Comment by reasonerjt** [comment]
@VF-mbrauer sorry for the late response we were OOO due to public holiday in China we are triaging the CVEs you sent to me to figure out what will be fixed in the next patch of v1.9.x.
We'll reply you via Email.

**Comment by VF-mbrauer** [comment]
@reasonerjt, Any status update here?

**Comment by Lyndon-Li** [comment]
@qiuming-best Please help to check if all the CVEs have been covered in 1.9.3
