### ISSUE TITLE
Update restic once version with symlink fix is released

### ISSUE THREAD

**Issue by sseago** [vmware-tanzu/velero#5399]
**What steps did you take and what happened:**
A second restic restore into a volume should update the volume to match the backup. There's a bug in current restic releases that will fail to update symlinks if they already exist (and report the failure as a restore failure). Restic PR https://github.com/restic/restic/pull/3780 fixes this. Once this makes it into a Restic release, we should update velero to this restic release to fix the bug in Velero.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
@sseago  thanks we will monitor restic repo closely.

**Comment by qiuming-best** [comment]
@sseago For restic symlink fix pr has not yet released a new version, So we don't bump up restic version in v1.9.3.
 So we modified the milestones to 1.10

**Comment by sseago** [comment]
@qiuming-best Actually we should probably bump it to 1.11, since I don't expect a new restic release will be out before we release 1.10.

**Comment by qiuming-best** [comment]
Restic version has been bumped up, which including the symlink fix issue
