### ISSUE TITLE
Velero backup issue

### ISSUE THREAD

**Issue by renmck** [vmware-tanzu/velero#5402]
Hello,

We have decided to reconfigure our velero backup from minio object storage to ECS and now the backup doesnt work. I got an error: 

time="2022-09-21T10:43:36Z" level=info msg="1 errors encountered backup up item" backup=velero/... logSource="pkg/backup/backup.go:413" name=kapp-controller-c66979988-wgkww
time="2022-09-21T10:43:36Z" level=error msg="Error backing up item" backup= error="restic repository is not ready: error running command=restic init --repo=s3:.../restic/tanzu-system --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: create key in repository at s3:...../restic/tanzu-system failed: client.PutObject: The request signature we calculated does not match the signature you provided. Check your Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details.\n\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/repository_ensurer.go:185" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryEnsurer).EnsureRepo" logSource="pkg/backup/backup.go:417" name=kapp-controller-c66979988-wgkww
Looks like all configuration is good. It's the same like we did when we configured for minio backups. Any  ideas where the issue could be? We are still using backups to minio and there are no problems.

**Comment by Lyndon-Li** [comment]
How did you make the reconfigure?

**Comment by renmck** [comment]
We have created new buckets in the S3 ECS Platform and reconfigured "target location" in the Tanzu.  When I am creating a new backup with target location which I just created the backup stops with the error I have mentioned before.  I made a couple of tests I have excluded "Tanzu namespaces" and System namespaces" and then the backup was successful.  But if I want to backup up everything without any exception the backup fails on volumes backup.

**Comment by reasonerjt** [comment]
@renmck The error looked like an authentication error when restic trying to access the Object Storage.  
Were there any volumes involved in the backup when the backup was successful?

Additionally if you are a VMware customer please contact GSS, the issues are mainly for OSS users.

**Comment by Lyndon-Li** [comment]
I am closing this issue since we haven't get the required info and feel free to reopen it.

**Comment by wenwenxiong** [comment]
i meet the same error  
backup repository is not ready: error running command=restic init --repo=s3:http://minio.local/velero/restic/ns-custom-11-qgasb1 --password-file=/tmp/credentials/ns-mec-middleware/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: create repository at s3:http://minio.local/velero/restic/ns-custom-11-qgasb1 failed: client.BucketExists: The request signature we calculated does not match the signature you provided. Check your key and signing method.
 how to fix this ? restic 's credentials how to custom?
