### ISSUE TITLE
Restore of an already restored backup

### ISSUE THREAD

**Issue by Wolder** [vmware-tanzu/velero#5404]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I created a backup on a namespace. Restored said namespace. Created a backup of the namespace again, and restored it. 
`velero backup create bootstrap-backup-1 --storage-location default --volume-snapshot-locations default --snapshot-volumes --include-namespaces harbor`
Delete PVC's in `harbor` namespace
`velero restore create --from-backup bootstrap-backup-1 --include-namespaces harbor --wait` 

`velero backup create bootstrap-backup-3 --storage-location default --volume-snapshot-locations default --snapshot-volumes --include-namespaces harbor`
Delete PVC's in `harbor` namespace
`velero restore create --from-backup bootstrap-backup-3 --include-namespaces harbor --wait` 

Produces the error in logs:
`Namespace harbor, resource restore error: error restoring persistentvolumeclaims/harbor/data-harbor-redis-0: PersistentVolumeClaim \"data-harbor-redis-0\" is invalid: spec: Invalid value: field.Path{name:\"dataSource\", index:\"\", parent:(*field.Path)(0xc027b35140)}: must match dataSourceRef" logSource="pkg/controller/restore_controller.go:504" restore=velero/bootstrap-backup-3-20220927132320`
Even though dataSource and dataSourceRef are identical from what i can observe.

**What did you expect to happen:**
Restore was successful

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 
[bundle-2022-09-27-13-25-38.tar.gz](https://github.com/vmware-tanzu/velero/files/9654960/bundle-2022-09-27-13-25-38.tar.gz)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The issue seems to be related to the PVC's spec.dataSource and spec.dataSourceRef fields. Prior to the first backup these fields are absent, and only appear after first backup. 

When testing on K8s version 1.23 there was no issue, which makes sense since AnyVolumeDataSource feature flag is default true from 1.24. 

Currently we have discovered two workarounds:
1. Remove dataSource and dataSourceRef from PVC's prior to backing up again
2. Remove dataSource and dataSourceRef from PVC's directly at our backup location

I cannot find any notion of dataSourceRef related to Velero. 

**Environment:**

- Velero version (use `velero version`): Client v1.8.1 Server: v1.9.1
- Velero features (use `velero client config get features`): `<NOT SET>`
- Kubernetes version (use `kubectl version`): v1.24.2
- Kubernetes installer & version: RKE v1.3.13
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): AlmaLinux v8.4

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
Looks like the same issue as #5424 
@Wolder so this happens when you use CSI plugin correct?

**Comment by Wolder** [comment]
Yes correct. I have not experienced this when not using the CSI plugin

**Comment by blackpiglet** [comment]
Add more background information of the volume populator function.
https://kubernetes.io/blog/2021/08/30/volume-populators-redesigned/
https://kubernetes.io/blog/2022/05/16/volume-populators-beta/

PVC's dataSourceRef is introduced in k8s v1.22, and default to enable in k8s v1.24.
PVC's dataSourceRef and dataSource value must be same.
