### ISSUE TITLE
Velero backup are partially failing  with `fail to wait VolumeSnapshot change to Ready` message

### ISSUE THREAD

**Issue by bhargavkeshav** [vmware-tanzu/velero#5413]
**What steps did you take and what happened:**
We are performing daily scheduled backup of velero and now we see backups are partially failing with the below error after waiting for 1 hr( CSI snapshot timeout 1hr).

```
time="2022-09-30T03:03:46Z" level=info msg="Backed up a total of 1072 items" backup=velero/velero-utilities-backup-20220930030035 logSource="pkg/backup/backup.go:405" progress=
time="2022-09-30T04:03:46Z" level=error msg="fail to wait VolumeSnapshot change to Ready: timed out waiting for the condition" backup=velero/velero-utilities-backup-20220930030035 logSource="pkg/controller/backup_controller.go:651"
MacBookPro-bhargavn:Downloads bhargav$ velero backup logs velero-utilities-backup-20220930030035 | grep warn
time="2022-09-30T03:03:44Z" level=warning msg="Additional item was not found in Kubernetes API, can't back it up" backup=velero/velero-utilities-backup-20220930030035 groupResource=volumesnapshotclasses.snapshot.storage.k8s.io logSource="pkg/backup/item_backupper.go:337" name=ebs-csi-snapclass namespace= resource=volumesnapshots.snapshot.storage.k8s.io
```

Velero backup are failing here due to kube client [here](https://github.com/vmware-tanzu/velero/blob/a80c96c8f8634ab8b6711bd28d4ac736a52cda57/pkg/controller/backup_controller.go#L921). We can see velero is triggering the volumesnaphot which intern calls ebs snapshot controller to create the EBS volume snapshot. AWS EBS volume snapshots are getting created for all the volumes and its getting completed well before the timeout(approx less than 10 min). 

Issue is coming when velero is not able to read these completed volumes and updated status. I think volumesnapshots are getting deleted (feature added as part of 1.9.0) by velero snapshot controller before the completion. I have attached the velerosnapshot json which is getting stored in s3, we can clearly see the "readyToUse": false being set for volumesnapshots.

I re-trigger the scheduled backup and with that velero backup was completed successfully.  But still I can see "readyToUse": false is set in the volumesnapshot json created for the new completed backup.

```
MacBookPro-bhargavn:Desktop bhargav$ velero get backup
NAME                                     STATUS            ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
velero-utilities-backup-20220930062219   Completed         0        1          2022-09-30 11:52:19 +0530 IST   9d        default            <none>
velero-utilities-backup-20220930030035   PartiallyFailed   1        1          2022-09-30 08:30:35 +0530 IST   9d        default            <none>
velero-utilities-backup-20220929030034   PartiallyFailed   1        0          2022-09-29 08:30:34 +0530 IST   8d        default            <none>
```

**What did you expect to happen:**

Backup should have completed successfully with all ebs volume snapshot.  

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

[bundle-failed-backup.tar.gz](https://github.com/vmware-tanzu/velero/files/9683296/bundle-failed-backup.tar.gz)
[bundle-retriggered-backup-completed.tar.gz](https://github.com/vmware-tanzu/velero/files/9683297/bundle-retriggered-backup-completed.tar.gz)
[velero-utilities-backup-20220930030035-csi-volumesnapshots.json.gz](https://github.com/vmware-tanzu/velero/files/9683442/velero-utilities-backup-20220930030035-csi-volumesnapshots.json.gz)
[velero-utilities-backup-20220930062219-csi-volumesnapshots.json.gz](https://github.com/vmware-tanzu/velero/files/9683443/velero-utilities-backup-20220930062219-csi-volumesnapshots.json.gz)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  1.9.1
- Velero features (use `velero client config get features`):  features: <NOT SET>
- Kubernetes version (use `kubectl version`): AWS EKS
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.20.15-eks-18ef993
- Kubernetes installer & version:
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):
plugin versions:

velero/velero-plugin-for-aws:v1.5.0
velero/velero-plugin-for-csi:v0.3.0

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by bhargavkeshav** [comment]
Todays backup was successful but I checked the volumesnapshot.json stored in the s3. There are many volumesnapshot with status "readyToUse" is set to false. Is this expected behaviour, velero backup is completed but readyToUse is not set to true.

**Comment by bhargavkeshav** [comment]
Do we have any updates here ?

**Comment by dejwsz** [comment]
still the same issue with velero 1.9.3 and velero/velero-plugin-for-aws:v1.5.2 and velero/velero-plugin-for-csi:v0.3.2

**Comment by dejwsz** [comment]
I tested the same config with velero 1.9.3 and the error is gone

**Comment by blackpiglet** [comment]
@bhargavkeshav 
Please have a try with new release v1.9.3.

**Comment by bhargavkeshav** [comment]
@blackpiglet I will update the velero version to 1.9.3 and test

**Comment by jaqua** [comment]
There is exactly the same error for me. I'm using 1.11.0.
Todays backup failed with the same error which is described in this issue.

If I am running the backup manually `velero backup create test --from-schedule velero-backup` it works as expected. Status completed.

**Comment by blackpiglet** [comment]
@jaqua 
If the manual case works, I think the issue described here should be fixed.
Suggest enlarging the timeout setting with the schedule-created case.

**Comment by jaqua** [comment]
> Suggest enlarging the timeout setting with the schedule-created case

@blackpiglet I don't find the docs where and how to setup the timeout value

This is how my *values.yaml* file looks like - regarding the schedule:

          schedules:
            backup:
              disabled: false
              schedule: "0 0 * * *"
              useOwnerReferencesInBackup: false
              template:
                ttl: "504h"

I don't see where to increase the timeout setting...

**Comment by blackpiglet** [comment]
Please check the Schedule API-type document.

https://velero.io/docs/v1.11/api-types/schedule/

```
spec:
  template:
    # CSISnapshotTimeout specifies the time used to wait for
    # CSI VolumeSnapshot status turns to ReadyToUse during creation, before
    # returning error as timeout. The default value is 10 minute.
    csiSnapshotTimeout: 10m
```
