### ISSUE TITLE
Unable to install velero from local build: failed to create shim: exec: "/velero": stat /velero: no such file or directory

### ISSUE THREAD

**Issue by Miraj50** [vmware-tanzu/velero#5419]
**What steps did you take and what happened:**

My system: WSL Ubuntu 20.04

Steps to reproduce:

1. Run `make local` to create the binary (_output/bin/linux/amd64/velero)
2. Create velero image by running `docker build . -f Dockerfile_cicd -t localvelero:v1`
The contents of Dockerfile_cicd are :
```
FROM gcr.io/distroless/base-debian11:nonroot
COPY /_output /
USER nonroot:nonroot
```
3. Push the image to Azure Container Registry
4. Install velero using its locally downloaded helm chart, but the image pointing to ours
```
image:
  repository: myacr.azurecr.io/localvelero
  tag: v1
```
After running helm install, I 'describe' the failed pod in k9s and I see this error:
`failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/velero": stat /velero: no such file or directory: unknown`

![image](https://user-images.githubusercontent.com/23695844/193889962-a02822d7-8bef-4509-998d-7463056ebe7a.png)

Can someone please tell me if there's something I am missing here? How do I get my local built velero image running?

Thank you!

**What did you expect to happen:**

Velero locally installed and running as if the image in the helm chart pointed to:
```
image:
  repository: velero/velero
  tag: v1.9.0
```

**Comment by blackpiglet** [comment]
Why not running `make container` to generate the docker image, then pushing it to your image registry?

**Comment by Miraj50** [comment]
@blackpiglet , thank you for your response. It had to be built in Azure pipeline, so it was not possible. Nonetheless I figured out that the exact location of the binary is what needs to be copied (and also make it executable). So, in dockerfile it should be `COPY --chmod=0755 /_output/bin/linux/amd64 /`. 

I'll close this issue, but I hope it helps anyone who stumbles into the same problem.
