### ISSUE TITLE
BSL in alternate namespace stuck in Unknown phase

### ISSUE THREAD

**Issue by onepeloton-cody** [vmware-tanzu/velero#5423]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

* I'm using velero 1.9.2 (client and server), with the server installed via Helm chart. Velero is installed in the `velero` namespace.

* I can create a BSL in the `velero` NS and it works as expected: `velero backup-location create my-bsl --provider aws --bucket my-bucket`

* But if I attempt to do this in another namespace, the BSL is created, but it is never assigned a Phase: `velero -n other-namespace backup-location create my-bsl-alt --provider aws --bucket my-bucket`

```
NAME                  PROVIDER   BUCKET/PREFIX                             PHASE     LAST VALIDATED   ACCESS MODE   DEFAULT
my-bsl-alt            aws        my-bucket                                 Unknown   Unknown          ReadWrite
```

* There are no log messages about this interaction in the velero pod logs, nor are there logs messages regarding this alt-namespace bsl

**What did you expect to happen:**

Either:
* the BSL becomes available
OR
* an error message is produced somewhere, either by the cli command or in the velero pod logs

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help`

I'm not permitted to share the info gathered by this command. I can describe my setup in general terms where applicable.

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

Same issue as above: I am not permitted to share raw logs from our deployments.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
Brew package
```
Client:
        Version: v1.9.2
        Git commit: -
Server:
        Version: v1.9.2
```
- Velero features (use `velero client config get features`):  `features: <NOT SET>`
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.21.14-eks-6d3986b
```
- Kubernetes installer & version: see above
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from `/etc/os-release`): MacOS 12.6

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
IMO, this is how Velero works. Velero server's controllers only watch on the CRDs in the specific namespace.
This is because Velero creates the k8s go-client with the namespace specified during installation, so it may not be easy to show the error logs in the Velero pod and the BSL status, but I agree, at least, this should be documented some where.

**Comment by sseago** [comment]
Yes, this is by design. Velero looks only in its own namespace for Velero CRs. You can actually have 2 velero installations, each in a different namespace, and BSLs, Backups, Restores, etc. will only be handled by the velero in the same namespace, not the other velero instance.

**Comment by onepeloton-cody** [comment]
Interesting. This worked for me in the past, with a much older version of velero, 1.6.x I believe. What's the purpose behind requiring a separate velero installation for each namespace? Is it technically infeasible? It seems like a requirement for a lot of extra compute cycles that could be handled by a single pod?

Anyway, thanks for the info, I will adjust my expectations.

**Comment by onepeloton-cody** [comment]
Also, this could indeed be described better in the documentation, or by error messages, since the CLI will happily let you pass alternate NS and even create CRDs there, with nary a message about "installation not found in this namespace."

**Comment by sseago** [comment]
Yes, the docs should probably make it clearer that Velero only looks in the current namespace for CRs. There's no need for a velero installation for each namespace. You can back up any namespace with a single velero. The Velero CRs must be in the namespace that Velero is in, not the namespace that you're backing up. But if you do install velero in two different namespaces, each instance only looks in its own namespace for Velero CRs.

**Comment by sseago** [comment]
As far as I remember, Velero has always only looked in its own namespace for Velero CRs, although there have been bugs in the past when we went through a period of controller refactoring where individual controllers weren't properly namespace-scoped. It may be that for 1.6, Velero was looking for BSLs everywhere, but I don't think the same would have been true for Backups, Restores, etc.

**Comment by onepeloton-cody** [comment]
Ack. Thank you for the quick response. Appreciate it!
