### ISSUE TITLE
Second restore of CSI volume fails due to dataSource doesn't match dataSourceRef

### ISSUE THREAD

**Issue by shubham-pampattiwar** [vmware-tanzu/velero#5424]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Using velero on OCP 4.11(k8s 1.24), I created a PVC that was provisioned using the ODF LVM CSI driver:

```
$ oc get pvc toolbox-container-home -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: topolvm.cybozu.com
    volume.kubernetes.io/selected-node: master1
    volume.kubernetes.io/storage-provisioner: topolvm.cybozu.com
  creationTimestamp: "2022-09-15T15:36:24Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: toolbox-container-home
  namespace: test-volume
  resourceVersion: "10658302"
  uid: ac618f12-b6a5-46ad-ba96-cb5613b9dd7e
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: odf-lvm-loop1-vg
  volumeMode: Filesystem
  volumeName: pvc-ac618f12-b6a5-46ad-ba96-cb5613b9dd7e
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
```
I used velero to back up the PVC and restore it:

```
$ velero backup create --from-schedule test-volume --wait
$ velero create restore --from-backup test-volume-20220914003129 --wait
```
After the restore operation completes, the PVC object looks like this:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    velero.io/backup-name: test-volume-20220914003129
    velero.io/volume-snapshot-name: velero-toolbox-container-home-vf52g
    volume.kubernetes.io/selected-node: master1
    volume.kubernetes.io/storage-provisioner: topolvm.cybozu.com
  creationTimestamp: "2022-09-15T01:43:47Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    velero.io/backup-name: test-volume-20220914003129
    velero.io/restore-name: test-volume-20220914003129-20220914184324
    velero.io/volume-snapshot-name: velero-toolbox-container-home-vf52g
  name: toolbox-container-home
  namespace: test-volume
  resourceVersion: "10590150"
  uid: d29cdc38-5c09-4243-b10c-eed0083332d4
spec:
  accessModes:
  - ReadWriteOnce
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: velero-toolbox-container-home-vf52g
  dataSourceRef:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: velero-toolbox-container-home-vf52g
  resources:
    requests:
      storage: 1G
  storageClassName: odf-lvm-loop1-vg
  volumeMode: Filesystem
  volumeName: pvc-d29cdc38-5c09-4243-b10c-eed0083332d4
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
```
Note that the dataSource and dataSourceRef fields in the above object both point to the VolumeSnapshot velero-toolbox-container-home-vf52g.

Next, I create another backup of this PVC and try to restore it:

```
$ velero backup create --from-schedule test-volume --wait
$ velero create restore --from-backup test-volume-20220914004727 --wait
```

This time the restore operation fails.

```
$ velero restore describe test-volume-20220914004727-20220914151512
...
Errors:
  Velero:     <none>
  Cluster:    <none>
  Namespaces:
    test-volume:  error restoring persistentvolumeclaims/test-volume/toolbox-container-home: PersistentVolumeClaim "toolbox-container-home" is invalid: spec: Invalid value: field.Path{name:"dataSource", index:"", parent:(*field.Path)(0xc07cac41e0)}: must match dataSourceRef
...


**What did you expect to happen:**
Restore to be completed successfully
 
**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`


**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]


**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):


**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Hi, Shubham.
Is the EnableCSI feature turned on when Velero is installed?

**Comment by blackpiglet** [comment]
@akalenyu 
Got it. Already approved your PR.

**Comment by shubham-pampattiwar** [comment]
@akalenyu Thank you for the PR.

**Comment by blackpiglet** [comment]
Add more background information of the volume populator function.
https://kubernetes.io/blog/2021/08/30/volume-populators-redesigned/
https://kubernetes.io/blog/2022/05/16/volume-populators-beta/

PVC's `dataSourceRef` is introduced in k8s v1.22, and default to enable in k8s v1.24.
PVC's `dataSourceRef` and `dataSource` value must be same.

**Comment by VGerris** [comment]
It would be appreciated if info can be added regarding in which release this is available and which dependencies are there. I encountered the same issue and wonder if a bug needs to be files against OADP operator for 4.11 for example, to update the plugin? Any hints on that process? Happy to file a bug/request if needed, thanks.

**Comment by blackpiglet** [comment]
@VGerris 
v1.9.3 and coming v1.10.0 contain this fix.

**Comment by VGerris** [comment]
@blackpiglet thank you for the info. I installed it but I seem to have the same issue:
```
$ velero version
Client:
	Version: v1.9.3
	Git commit: 9a617fe5af9c997d69f8f37a5b40d0462edd9b28
Server:
	Version: v1.9.0-OADP
```
This is on OpenShift 4.11 too.
Does the server need to be updated?
Thank you

**Comment by sseago** [comment]
@VGerris According to the above, your Velero is still on 1.9.0. The client version isn't nearly as relevant, since all backup and restore operations are done on the server.

Also, since you're on OADP, the fix for this will be included in OADP 1.1.1. OADP 1.1 does not have the fix.

**Comment by VGerris** [comment]
@sseago  Thank you for the quick reply. In the mean time I have tested this with Velero 1.9.3 server and client and that works without issues with snapshots. I was not able to make the Restic part work but that seems to be related to proxy setup, something OADP conveniently solves. Do you have contact with RedHat about this ? I will make an effort to land it there from my side, thank you for the help and information!

**Comment by pmakinde** [comment]
I have similar issue on Rancher RKE2 (Kubernetes ver 1.24.7)

All was OK with velero PV snapshot/restore until  upgraded Kubernetes from RKE2 v1.20 to v1.24

Issue was first picked up on velero v1.9.5

downgraded velero to v1.9.3 after reading this thread but datasource/datasourceRef mismatch issue persist.

# velero version

Client:

        Version: v1.9.3

        Git commit: 9a617fe5af9c997d69f8f37a5b40d0462edd9b28

Server:

        Version: v1.9.3

**Comment by pmakinde** [comment]
time="2023-01-16T10:32:10Z" level=error msg="error restoring grafana-rbd-pvc2: PersistentVolumeClaim \"grafana-rbd-pvc2\" is invalid: spec: Invalid value: field.Path{name:\"dataSource\", index:\"\", parent:(*field.Path)(0xc042f229c0)}: must match dataSourceRef" logSource="pkg/restore/restore.go:1388" restore=velero/nginx-web

time="2023-01-16T10:32:10Z" level=error msg="error restoring nginx-pv-cephfs-claim: PersistentVolumeClaim \"nginx-pv-cephfs-claim\" is invalid: spec: Invalid value: field.Path{name:\"dataSource\", index:\"\", parent:(*field.Path)(0xc03ea7ef30)}: must match dataSourceRef" logSource="pkg/restore/restore.go:1388" restore=velero/nginx-web

time="2023-01-16T10:32:11Z" level=error msg="Namespace nginx-web, resource restore error: error restoring persistentvolumeclaims/nginx-web/grafana-rbd-pvc2: PersistentVolumeClaim \"grafana-rbd-pvc2\" is invalid: spec: Invalid value: field.Path{name:\"dataSource\", index:\"\", parent:(*field.Path)(0xc042f229c0)}: must match dataSourceRef" logSource="pkg/controller/restore_controller.go:510" restore=velero/nginx-web

time="2023-01-16T10:32:11Z" level=error msg="Namespace nginx-web, resource restore error: error restoring persistentvolumeclaims/nginx-web/nginx-pv-cephfs-claim: PersistentVolumeClaim \"nginx-pv-cephfs-claim\" is invalid: spec: Invalid value: field.Path{name:\"dataSource\", index:\"\", parent:(*field.Path)(0xc03ea7ef30)}: must match dataSourceRef" logSource="pkg/controller/restore_controller.go:510" restore=velero/nginx-web
