### ISSUE TITLE
Waiting for CSI driver to reconcile volumesnapshot  Retrying in 5s

### ISSUE THREAD

**Issue by msukumaran-korewireless** [vmware-tanzu/velero#5436]
Backup is getting failed with the error:

time="2022-10-12T03:37:25Z" level=info msg="Waiting for CSI driver to reconcile volumesnapshot cmp-test-clh/velero-chi-clh-test-chi-clh-test-shard-0-0-0-d6njm. Retrying in 5s" backup=velero/cmp-test-clh-test cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:169" pluginName=velero-plugin-for-csi

kubectl logs deployment/velero -n velero

Found 24 pods, using pod/restic-dn9nh                                                                                                                                   time="2022-10-12T07:17:59Z" level=info msg="Setting log-level to INFO"                                                                                                  time="2022-10-12T07:17:59Z" level=info msg="Starting Velero restic server v1.9.2 (82a100981cc66d119cf9b1d121f45c5c9dcf99e1-dirty)" logSource="pkg/cmd/cli/restic/server.go:87"                                                                                                                                                                  2022-10-12T07:17:59.567Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}                                       time="2022-10-12T07:17:59Z" level=info msg="Starting metric server for restic at address [:8085]" logSource="pkg/cmd/cli/restic/server.go:177"                          time="2022-10-12T07:18:00Z" level=info msg="Starting controllers" logSource="pkg/cmd/cli/restic/server.go:188"                                                          time="2022-10-12T07:18:00Z" level=info msg="Controllers starting..." logSource="pkg/cmd/cli/restic/server.go:219"                                                       2022-10-12T07:18:00.070Z        INFO    starting metrics server {"path": "/metrics"}                                                                                    2022-10-12T07:18:00.070Z        INFO    controller.podvolumebackup      Starting EventSource    {"reconciler group": "velero.io", "reconciler kind": "PodVolumeBackup", "source": "kind source: /, Kind="}                                                                                                                                      2022-10-12T07:18:00.070Z        INFO    controller.podvolumebackup      Starting Controller     {"reconciler group": "velero.io", "reconciler kind": "PodVolumeBackup"} 2022-10-12T07:18:00.070Z        INFO    controller.podvolumerestore     Starting EventSource    {"reconciler group": "velero.io", "reconciler kind": "PodVolumeRestore", "source": "kind source: /, Kind="}                                                                                                                                     2022-10-12T07:18:00.070Z        INFO    controller.podvolumerestore     Starting EventSource    {"reconciler group": "velero.io", "reconciler kind": "PodVolumeRestore", "source": "kind source: /, Kind="}                                                                                                                                     2022-10-12T07:18:00.071Z        INFO    controller.podvolumerestore     Starting Controller     {"reconciler group": "velero.io", "reconciler kind": "PodVolumeRestore"}2022-10-12T07:18:00.171Z        INFO    controller.podvolumerestore     Starting workers        {"reconciler group": "velero.io", "reconciler kind": "PodVolumeRestore", "worker count": 1}                                                                                                                                                     2022-10-12T07:18:00.171Z        INFO    controller.podvolumebackup      Starting workers        {"reconciler group": "velero.io", "reconciler kind": "PodVolumeBackup", "worker count": 1}

**Environment:**

On Premise with ceph storage

# velero version                                                                                                              Client:                                                                                                                                                                         Version: v1.9.2                                                                                                                                                         Git commit: 82a100981cc66d119cf9b1d121f45c5c9dcf99e1                                                                                                            Server:                                                                                                                                                                         Version: v1.9.2                                                                                                                                             
# velero client config get features    
features: <NOT SET>                                                                                                                                                     # kubectl version                                                                                                             Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}                                                                                           Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.12", GitCommit:"5ec472285121eb6c451e515bc0a7201413872fa3", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}                                                                                          WARNING: version difference between client (1.22) and server (1.17) exceeds the supported minor version skew of +/-1                                                    root@MidhunC-552:/mnt/c/Midhun/velero-kore#

**Comment by allenxu404** [comment]
Is there any error-level message you could provide for us to better troubleshoot?

**Comment by msukumaran-korewireless** [comment]
Linked  https://github.com/vmware-tanzu/velero/issues/5438 @allenxu404

**Comment by draghuram** [comment]
#5438 will not fix timeout issue. See my comment here in this regard: https://github.com/vmware-tanzu/velero/issues/5418#issuecomment-1270158893.

It will help if you can provide more details such as CSI driver being used.

**Comment by midhuns3343** [comment]
> #5438 will not fix timeout issue. See my comment here in this regard: [#5418 (comment)](https://github.com/vmware-tanzu/velero/issues/5418#issuecomment-1270158893).
> 
> It will help if you can provide more details such as CSI driver being used.

> 

Driver is rbd.csi.ceph.com

 - name: DRIVER_NAME
      value: rbd.csi.ceph.com

Below is snapshot controller deployment, I doubt the image used may not be compatible.

kind: Deployment                                                                                                                                                        apiVersion: apps/v1                                                                                                                                                     metadata:                                                                                                                                                                 name: csi-snapshot-controller                                                                                                                                           namespace: kube-system                                                                                                                                                spec:                                                                                                                                                                     replicas: 2                                                                                                                                                             selector:                                                                                                                                                                 matchLabels:                                                                                                                                                              app: csi-snapshot-controller                                                                                                                                        template:                                                                                                                                                                 metadata:                                                                                                                                                                 labels:                                                                                                                                                                   app: csi-snapshot-controller                                                                                                                                        spec:                                                                                                                                                                     serviceAccountName: csi-snapshot-controller-sa                                                                                                                          nodeSelector:                                                                                                                                                             kubernetes.io/os: linux                                                                                                                                               priorityClassName: system-cluster-critical                                                                                                                              tolerations:                                                                                                                                                              - key: "node-role.kubernetes.io/master"                                                                                                                                   operator: "Equal"                                                                                                                                                       value: "true"                                                                                                                                                           effect: "NoSchedule"                                                                                                                                                  - key: "node-role.kubernetes.io/controlplane"                                                                                                                             operator: "Equal"                                                                                                                                                       value: "true"                                                                                                                                                           effect: "NoSchedule"                                                                                                                                                containers:                                                                                                                                                               - name: csi-snapshot-controller                                                                                                                                           image: mcr.microsoft.com/oss/kubernetes-csi/snapshot-controller:v3.0.3                                                                                                  args:                                                                                                                                                                     - "--v=2"                                                                                                                                                               - "--leader-election=true"                                                                                                                                            resources:                                                                                                                                                                limits:                                                                                                                                                                   cpu: 1                                                                                                                                                                  memory: 100Mi                                                                                                                                                         requests:                                                                                                                                                                 cpu: 10m                                                                                                                                                                memory: 20Mi

**Comment by midhuns3343** [comment]
@draghuram Can you also provide steps to manually create a VolumeSnapshot and verify that a corresponding VolumeSnapshotContent is created.

**Comment by midhuns3343** [comment]
> > #5438 will not fix timeout issue. See my comment here in this regard: [#5418 (comment)](https://github.com/vmware-tanzu/velero/issues/5418#issuecomment-1270158893).
> > It will help if you can provide more details such as CSI driver being used.
> 
> > 
> 
> Driver is rbd.csi.ceph.com
> 
> * name: DRIVER_NAME
>   value: rbd.csi.ceph.com
> 
> Below is snapshot controller deployment, I doubt the image used may not be compatible.
> 
> kind: Deployment apiVersion: apps/v1 metadata: name: csi-snapshot-controller namespace: kube-system spec: replicas: 2 selector: matchLabels: app: csi-snapshot-controller template: metadata: labels: app: csi-snapshot-controller spec: serviceAccountName: csi-snapshot-controller-sa nodeSelector: kubernetes.io/os: linux priorityClassName: system-cluster-critical tolerations: - key: "node-role.kubernetes.io/master" operator: "Equal" value: "true" effect: "NoSchedule" - key: "node-role.kubernetes.io/controlplane" operator: "Equal" value: "true" effect: "NoSchedule" containers: - name: csi-snapshot-controller image: mcr.microsoft.com/oss/kubernetes-csi/snapshot-controller:v3.0.3 args: - "--v=2" - "--leader-election=true" resources: limits: cpu: 1 memory: 100Mi requests: cpu: 10m memory: 20Mi

Seeing the below error in snapshot controller:

I1014 09:18:53.061079       1 event.go:282] Event(v1.ObjectReference{Kind:"VolumeSnapshot", Namespace:"clickhouse-test", Name:"test-snapshot", UID:"553a30c9-1401-41c7-b950-d87aff20c842", APIVersion:"snapshot.storage.k8s.io/v1", ResourceVersion:"3028343511", FieldPath:""}): type: 'Warning' reason: 'CreateSnapshotContentFailed' Error creating volume snapshot content object for snapshot clickhouse-test/test-snapshot: create not allowed while custom resource definition is terminating.

**Comment by draghuram** [comment]
Great. It seems that snapshot definitely made progress. External snapshotter is creating VolumeSnapshotContent as expected. It is now up to CSI driver to actually create storage snapshot and update snapshot handle which is not happening. So Velero will wait for 10 minutes (by default) and will  mark the snapshot as failed. 

Can you check if the driver rbd.csi.ceph.com is properly configured? Also, we (at cloudcasa.io) have seen in some cases that VolumeSnapshotClass is not properly configured leading to snapshot failures. For example, VolumeSnapshotClass requires specific parameters such as credentials. Can you copy the output of the following command? If there is any sensitive information, you can mask it.
```$ kubectl get volumesnapshotclasses -o yaml```

Another point to check is whether CSI driver handles "v1" snapshots. If it only works with v1beta1, it will not recognize VolumeSnapshotContent created by Velero. What version of RBS CSI driver are you using?

**Comment by midhuns3343** [comment]
> Great. It seems that snapshot definitely made progress. External snapshotter is creating VolumeSnapshotContent as expected. It is now up to CSI driver to actually create storage snapshot and update snapshot handle which is not happening. So Velero will wait for 10 minutes (by default) and will mark the snapshot as failed.
> 
> Can you check if the driver rbd.csi.ceph.com is properly configured? Also, we (at cloudcasa.io) have seen in some cases that VolumeSnapshotClass is not properly configured leading to snapshot failures. For example, VolumeSnapshotClass may require specific parameters such as credentials. Can you copy the output of the following command? If there is any sensitive information, you can mask it. `$ kubectl get volumesnapshotclasses -o yaml`
> 
> Another point to check is whether CSI driver handles "v1" snapshots. If it only works with v1beta1, it will not recognize VolumeSnapshotContent created by Velero. What version of RBD CSI driver are you using?

RBD CSI driver version is v3.0.0

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-rbd-fast
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: rbd.csi.ceph.com
deletionPolicy: Delete
parameters:
  clusterID: xxx-xxx-xxxx-xxx
  csi.storage.k8s.io/snapshotter-secret-name: csi-rbd-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: ceph-csi-rbd

**Comment by draghuram** [comment]
The VolumeSnapshotClass seems to be fine. Just for the sake of completeness, do confirm that you are seeing a time out message similar to this:

"Timed out awaiting reconciliation of volumesnapshot ..."

If this is indeed happening, I can only think of some problem on the CSI driver side. Either it is not recognizing v1 VolumeSnapshotContent or is running into some errors. Interestingly, I found this commit in 3.3.0 of ceph-csi:

https://github.com/ceph/ceph-csi/commit/d92e084dc17a57c2ce150747c827880b2bf4306e

"With v4.0.0 release of external-snapshotter, we are moving towards v1
from v1beta1 API version"

Does this mean that version 3.0.0 that you are using doesn't work with v1? Perhaps you may want to upgrade the CSI driver and see if it helps. In any case, checking CSI driver logs should help.

**Comment by midhuns3343** [comment]
> The VolumeSnapshotClass seems to be fine. Just for the sake of completeness, do confirm that you are seeing a time out message similar to this:
> 
> "Timed out awaiting reconciliation of volumesnapshot ..."
> 
> If this is indeed happening, I can only think of some problem on the CSI driver side. Either it is not recognizing v1 VolumeSnapshotContent or is running into some errors. Interestingly, I found this commit in 3.3.0 of ceph-csi:
> 
> [ceph/ceph-csi@d92e084](https://github.com/ceph/ceph-csi/commit/d92e084dc17a57c2ce150747c827880b2bf4306e)
> 
> "With v4.0.0 release of external-snapshotter, we are moving towards v1 from v1beta1 API version"
> 
> Does this mean that version 3.0.0 that you are using doesn't work with v1? Perhaps you may want to upgrade the CSI driver and see if it helps. In any case, checking CSI driver logs should help.

Yes, I see a timed-out message:
time="2022-10-18T05:52:47Z" level=info msg="Waiting for volumesnapshotcontents snapcontent-58cfdf88-372c-4136-9ed2-ef0884c2b0b5 to have snapshot handle. Retrying in 5s" 
time="2022-10-18T05:55:17Z" level=error msg="Timed out awaiting reconciliation of volumesnapshot kcloak-cidp-dev/velero-data-kcloak-cidp-dev-db-mysql-0-krv4q

The CSI driver runs as daemon set, is there a way to identify the exact pod that will have the required logs? I looked randomly at few pods and didn't get any information.

Updating CSI driver has a dependency on Kube version, current version is v1.17 and updated CSI drivers requires >v1.22

I tried on a different cluster that has v1beta1 API version, there are no errors in velero and backup shows completed, but it isn't actually backing up the data on pvc's.

**Comment by draghuram** [comment]
If you are testing on 1.17 cluster, I am pretty sure this problem has to do with version of snapshot APIs. You won't be able to use Velero 1.9 as it will only work with v1. If you really want to get this working on 1.17, you need to install Velero 1.8 and also make sure that you use external snapshotter that has v1beta1 CRDs.

**Comment by midhuns3343** [comment]
> If you are testing on 1.17 cluster, I am pretty sure this problem has to do with version of snapshot APIs. You won't be able to use Velero 1.9 as it will only work with v1. If you really want to get this working on 1.17, you need to install Velero 1.8 and also make sure that you use external snapshotter that has v1beta1 CRDs.

Using Velero 1.8 and snapshotter with v1beta1 CRDs, the backup shows no error. It creates volumesnapshot, volumesnapshotcontent and snapshothandle. But looking at remote backup storage location, it doesn't seem to be showing up the actual data size on the files (attached screenshot) and restoring from backup doesn't restore the PVC's.

Below is the volumesnapshotcontent description.

Spec:                                                                                                                                                                     Deletion Policy:  Delete                                                                                                                                                Driver:           rbd.csi.ceph.com                                                                                                                                      Source:                                                                                                                                                                   Volume Handle:             0001-0024-7a24d60d-210f-4bec-8ee6-33d8a7f9ef29-0000000000000001-2ff09960-494c-11ed-b9eb-0e9087507570                                       Volume Snapshot Class Name:  csi-rbd-fast                                                                                                                               Volume Snapshot Ref:                                                                                                                                                      API Version:       snapshot.storage.k8s.io/v1beta1                                                                                                                      Kind:              VolumeSnapshot                                                                                                                                       Name:              velero-chi-clh-test-chi-clh-test-shard-2-0-0-94cfl                                                                                                   Namespace:         cmp-test-clh                                                                                                                                         Resource Version:  3048674646                                                                                                                                           UID:               0102691e-5a22-468d-9c1c-b63888778a31                                                                                                             Status:                                                                                                                                                                   Creation Time:    1666170984000000000                                                                                                                                   Ready To Use:     true                                                                                                                                                  Restore Size:     85899345920                                                                                                                                           Snapshot Handle:  0001-0024-7a24d60d-210f-4bec-8ee6-33d8a7f9ef29-0000000000000001-b37d5971-4f8e-11ed-9c96-da5f84a206ba                                                

![image](https://user-images.githubusercontent.com/88483737/196652764-ad461611-26da-40bf-a74d-b546107c8ebd.png)

**Comment by draghuram** [comment]
The remote storage location will only have tar files containing json specs of all the resources. So their sizes are not going to be big. Note that PV data is not being "copied" to remote storage. Instead, Velero triggers a CSI snapshot which is nothing but a snapshot in the underlying storage. 

As for restore, how are you restoring? There is a flag to include PVs in the restore (I think ``--restore-volumes``).

**Comment by midhuns3343** [comment]
> 

Is there a way to copy the PV data over to remote storage? Using VolumeSnapshotLocation https://velero.io/docs/v1.8/api-types/volumesnapshotlocation/ helps?

Below is the error when trying to restore from backup using the --restore-volumes, the provisioner fails to bring UP the PVC's.

velero create restore --from-backup cmp-test-clh-test --restore-volumes

# kubectl describe pvc chi-clh-test-chi-clh-test-shard-0-0-0                                                                  
Name:          chi-clh-test-chi-clh-test-shard-0-0-0                                                                                                                                                                                                                                                              
StorageClass:  csi-rbd-fast  

Warning  ProvisioningFailed    3m5s (x8 over 16m)   rbd.csi.ceph.com_ceph-csi-rbd-provisioner-c7cc79f6f-cxjlh_47a9f25d-6f2e-4c04-9c4e-9fc469cbd2be  failed to provision volume with StorageClass "csi-rbd-fast": rpc error: code = Internal desc = key not found: no snap source in omap for "csi.snap.f7cd58b8-5032-11ed-97c0-c6e6e26b8532"    Normal   ExternalProvisioning  90s (x63 over 16m)   persistentvolume-controller                                                                     waiting for a volume to be created, either by external provisioner "rbd.csi.ceph.com" or manually created by system administrator

**Comment by draghuram** [comment]
I think it is best to take this discussion out of this issue now that you are past Snapshot time out problem. I suggest you post your questions in Velero google group. But to quickly answer your question about copying data to remote storage, you will need to use Restic backups (https://velero.io/docs/v1.9/restic/). But as I said, let us continue the discussion in Google group.
