### ISSUE TITLE
How does Velero handle server-side HTTP requests?

### ISSUE THREAD

**Issue by VinayVamsi143** [vmware-tanzu/velero#5457]
How does velero validate an input HTTP URL as backupstoragelocation? An attacker may initiate a server-side GET HTTP request in order to have access to internal infrastructure.

**Comment by qiuming-best** [comment]
For the server-side HTTP URL requests
First, we only support `limited` backend storage providers, such as AWS S3, Azure, GCP, etc.
Second, we need to use provider related configuration to `pass the permissions validation` when requesting objects in every provider storage, taking AWS S3 for example, `ak, sk` is needed by S3.
So if masquerading HTTP server, it will fail by validation

But if it's such as S3 compatible HTTP server, the attacker changed the backupstoragelocation configuration, Maybe it's beyond the scope of velero consideration
