### ISSUE TITLE
Add CODEOWNERS files voting

### ISSUE THREAD

**Issue by OrlinVasilev** [vmware-tanzu/velero#5470]
We need to implement CODEOWNERS for the repository based on the maintainers expertise and comfort zone reviewing PRs in specific part of the repository!
Please add yourself (like @OrlinVasilev ) on which high level directory/file and/or lower level you want to be assigned !

Later I'll translate that to CODEOWNERS, since we are not able to properly use teams at the moment we need to specify github handles!

Thank you for your support and being great contributor and maintainer!!
 Top level directories:
├── .github - @OrlinVasilev 
├── _output
├── assets
├── changelogs
├── cmd
├── config
├── design
├── examples - @OrlinVasilev 
├── hack
├── internal
├── pkg
├── site - @OrlinVasilev 
├── test
├── third_party
└── tilt-resources

Top level files:
├── ./ADOPTERS.md - @OrlinVasilev
├── ./CHANGELOG.md 
├── ./CODE_OF_CONDUCT.md - @OrlinVasilev
├── ./CONTRIBUTING.md - @OrlinVasilev
├── ./Dockerfile
├── ./GOVERNANCE.md - @OrlinVasilev
├── ./LICENSE
├── ./MAINTAINERS.md - @OrlinVasilev
├── ./Makefile
├── ./README.md - @OrlinVasilev
├── ./ROADMAP.md - @OrlinVasilev, @pradeepkchaturvedi 
├── ./SECURITY.md
├── ./SUPPORT.md

Or level 2 direcories:
├── _output
│   └── bin
├── assets
│   ├── one-line
│   └── stacked
├── changelogs
│   └── unreleased
├── cmd
│   ├── velero
│   └── velero-restore-helper
├── config
│   ├── crd
│   └── rbac
├── design
│   ├── CLI
│   ├── Implemented
│   └── unified-repo-and-kopia-integration
├── examples
│   ├── minio
│   └── nginx-app
├── hack
│   ├── build-image
│   ├── crd-gen
│   ├── issue-template-gen
│   └── release-tools
├── internal
│   ├── credentials
│   ├── delete
│   ├── hook
│   ├── restartabletest
│   ├── storage
│   ├── util
│   └── velero
├── pkg
│   ├── apis
│   ├── archive
│   ├── backup
│   ├── builder
│   ├── buildinfo
│   ├── client
│   ├── cmd
│   ├── controller
│   ├── discovery
│   ├── features
│   ├── generated
│   ├── install
│   ├── kuberesource
│   ├── label
│   ├── metrics
│   ├── nodeagent
│   ├── persistence
│   ├── plugin
│   ├── podexec
│   ├── podvolume
│   ├── repository
│   ├── restic
│   ├── restore
│   ├── restorehelper
│   ├── test
│   ├── uploader
│   ├── util
│   └── volume
├── site - @OrlinVasilev 
│   ├── assets
│   ├── content
│   ├── data
│   ├── layouts
│   ├── resources
│   └── static
├── test
│   └── e2e
├── third_party
│   └── kubernetes
└── tilt-resources
    └── examples

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by kaovilai** [comment]
@OrlinVasilev I recommend extending this to cover other ["supported by velero team" plugin repos.](https://velero.io/plugins/) as well as https://github.com/vmware-tanzu/helm-charts

**Comment by qiuming-best** [comment]
@OrlinVasilev,  It is basically divided by folder, but PR is committed by functionality and one specific folder may be involved by many functionalities. Maybe two folders are used for one functionality. 
So it is better divided by functionality for maintainers, one PR may related by one maintainer which would be more clear ?

**Comment by OrlinVasilev** [comment]
@kaovilai agreed but we have to start from somewhere :)

**Comment by OrlinVasilev** [comment]
@qiuming-best - agree but that's not the direct intention of this, here we are aiming for direct assignees to specific part of the code not per functionality but per code location. Also there is no easy way to implement but one step of this is our Monday PR triaging that we've decided to do! :) Hope that explains a bit!

**Comment by OrlinVasilev** [comment]
@kaovilai - I see we have https://github.com/vmware-tanzu/velero/blob/main/.github/auto-assignees.yml somehow I missed this one :) maybe CODEOWNERS can compliment that or we cancel that issues :D
@sseago thoughts ?

**Comment by sseago** [comment]
I had a couple questions. How would this work for cases where PRs touch multiple areas (as they often do)? i.e. "This is a controller change, but it also modifies api/crds, since the two things are required together. Would it just include everyone who is listed on any directories included in the PR? Would we still just pick 2 people at random from the list?  Also, I'd think we'd still need the general auto-assignees, in case the PR is limited to a directory which doesn't include at least two people.

**Comment by OrlinVasilev** [comment]
@sseago it's quite similar to auto-assignee but it can also give idea of the folks who is responsible for what! It will assign everyone listed for that particular part of the code!
We can use CODEOWNERS together with auto-assignees to make sure we don't miss PR for review!

**Comment by OrlinVasilev** [comment]
Decided not to go this way!

**Comment by kaovilai** [comment]
https://github.com/velero-io/velero/pull/9998 related
