### ISSUE TITLE
CSI plugin crashes with `--include-resources persistentvolumeclaim` filter

### ISSUE THREAD

**Issue by diegonuevo** [vmware-tanzu/velero#5486]
**What steps did you take and what happened:**

When attempting to create a selective backup with just the PVC volumes with certain label, velero crashes with segment violation. The pod restarts, and the back up is marked as failed, even though the CSI driver actually creates the snapshot successfully:
```
$ velero backup create test-crash --include-namespaces testns --include-resources persistentvolumeclaim --selector backup-policy=include
Backup request "test-crash" submitted successfully.
Run `velero backup describe test-crash` or `velero backup logs test-crash` for more details.
...
$ velero backup get
NAME         STATUS   ERRORS   WARNINGS   CREATED                          EXPIRES   STORAGE LOCATION   SELECTOR
test-crash   Failed   0        0          2022-10-25 10:23:01 +0200 CEST   29d       default            backup-policy=include
```

There are no logs for the backup because of the crash event, so running the `velero backup logs` command returns an error:
```
$ velero backup logs test-crash
An error occurred: file not found
```

Looking at the kubernetes logs for the velero controller, we can observe the crash:
```
time="2022-10-25T07:44:41Z" level=info msg="Returning from PVCBackupItemAction with 1 additionalItems to backup" backup=backup/test-crash cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:152" pluginName=velero-plugin-for-csi
time="2022-10-25T07:44:41Z" level=info msg="Excluding item because resource is excluded" backup=backup/test-crash logSource="pkg/backup/item_backupper.go:101" name=velero-test-pvc-rzfwn namespace=testns resource=volumesnapshots.snapshot.storage.k8s.io
time="2022-10-25T07:44:41Z" level=info msg="Backed up 1 items out of an estimated total of 1 (estimate will change throughout the backup)" backup=backup/test-crash logSource="pkg/backup/backup.go:380" name=test-pvc namespace=testns progress= resource=persistentvolumeclaims
time="2022-10-25T07:44:41Z" level=info msg="Backed up a total of 1 items" backup=backup/test-crash logSource="pkg/backup/backup.go:405" progress=
2022/10/25 07:44:41  info Waiting for CSI driver to reconcile volumesnapshot testns/velero-test-pvc-rzfwn. Retrying in 5s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19c6ecd]

goroutine 1501 [running]:
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).deleteVolumeSnapshot.func1(0xc0002e8000)
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:940 +0xad
created by github.com/vmware-tanzu/velero/pkg/controller.(*backupController).deleteVolumeSnapshot
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:936 +0xf7
```

Upon restart of the pod, velero finds a pending backup InProgress and marks it as failed, since it lacks the context after the restart:
```
time="2022-10-25T07:45:07Z" level=warning msg="get a backup with status \"InProgress\" during the server starting, mark it as \"Failed\"" backup=test-crash logSource="pkg/cmd/server/server.go:971"
```

This seems to happen only when the backup is created with a resource filter matching pvc objects exclusively (`--include-resources persistentvolumeclaim`). If we remove this filter, the backup executes just fine, snapshot included:
```
$ velero backup create test-ok --include-namespaces testns --selector backup-policy=include
Backup request "test-ok" submitted successfully.
Run `velero backup describe test-ok` or `velero backup logs test-ok` for more details.
...
$ velero backup get
NAME         STATUS      ERRORS   WARNINGS   CREATED                          EXPIRES   STORAGE LOCATION   SELECTOR
test-crash   Failed      0        0          2022-10-25 10:23:01 +0200 CEST   29d       default            backup-policy=include
test-ok      Completed   0        0          2022-10-25 10:02:30 +0200 CEST   29d       default            backup-policy=include
```
It also works fine if we include in the filter the pv and the volume snapshot objects:
```
$ velero backup create test-ok-2 --include-namespaces testns --include-resources persistentvolumeclaim,persistentvolume,volumesnapshot --selector backup-policy=include
Backup request "test-ok-2" submitted successfully.
Run `velero backup describe test-ok-2` or `velero backup logs test-ok-2` for more details.
...
$ velero backup get
NAME         STATUS      ERRORS   WARNINGS   CREATED                          EXPIRES   STORAGE LOCATION   SELECTOR
test-crash   Failed      0        0          2022-10-25 10:23:01 +0200 CEST   29d       default            backup-policy=include
test-ok      Completed   0        0          2022-10-25 10:02:30 +0200 CEST   29d       default            backup-policy=include
test-ok-2    Completed   0        0          2022-10-25 12:39:55 +0200 CEST   29d       default            backup-policy=include
```
After doing some tests, I noticed that at the very minimum for the volume backup to succeed, you need to include these resources:
* PersistentVolume
* PersistentVolumeClaim
* VolumeSnapshot

If either pv or volumesnapshot are omitted, it makes velero crash.

**What did you expect to happen:**

I expected the back up to be successfully created, or at least velero not to crash and report an error in the backup logs stating that pv and volumesnapshot resources are required for pvc snapshotting.

**The following information will help us better understand what's going on**:

Unfortunately, I can't share any support bundle or detailed logs for the sake of confidentiality, but hopefully you can reproduce this in your own setups. Also, the logs I shared with the SIGSEV message may be helpful.

**Anything else you would like to add:**

I deployed velero with two plugins:
* CSI plugin to back up volumes with the CSI Volume Snapshot feature (Azure driver)
* AWS plugin to back up kubernetes resource data in an S3 object store

**Environment:**

- Velero version: v1.9.1 (both client and server)
- Plugin versions: velero-plugin-for-csi:v0.3.0, velero-plugin-for-aws:v1.5.0
- Velero features (use `velero client config get features`): `features: EnableCSI`
- Kubernetes version: v1.22.6
- Cloud provider or hardware configuration: Azure AKS

**Comment by Lyndon-Li** [comment]
@blackpiglet Looks like this problem has fixed in the recent patch, could you confirm this and the patch number?

**Comment by diegonuevo** [comment]
As far as I can see the latest available version is v1.9.2. I can't see versions 1.9.3 and 1.10 in the repo.

**Comment by reasonerjt** [comment]
@diegonuevo
They are the upcoming patch and minor releases

**Comment by Lyndon-Li** [comment]
Close this issue as it has been fixed in new patch.
