### ISSUE TITLE
Implement new plugin v2 APIs for VolumeSnapshotter

### ISSUE THREAD

**Issue by weshayutin** [vmware-tanzu/velero#5487]
Implementation for [Design for VolumeSnapshotter v2 API](https://github.com/vmware-tanzu/velero/blob/d310403681cee2b02b4a202fbd2dc19841c9cdd6/design/vsv2-design.md)

Related to:
[Item action progress monitoring design](https://github.com/vmware-tanzu/velero/pull/5108/
)

**Comment by sseago** [comment]
Not stale

**Comment by sseago** [comment]
This should be dropped from 1.11 milestone, since we're only implementing BIA and RIA v2 APIs at this time.
