### ISSUE TITLE
Implement new plugin v2 APIs for BackupItemAction

### ISSUE THREAD

**Issue by weshayutin** [vmware-tanzu/velero#5488]
Implementation for [BackupItemAction v2 design](https://github.com/vmware-tanzu/velero/pull/5382)

Related to: 
[Item action progress monitoring design](https://github.com/vmware-tanzu/velero/pull/5108)

**Comment by sseago** [comment]
Fixed with https://github.com/vmware-tanzu/velero/pull/5442
