### ISSUE TITLE
Review all error handling in Velero CLI

### ISSUE THREAD

**Issue by rosskukulinski** [vmware-tanzu/velero#549]
As we lead up to 1.0, I think it would be helpful to do a comprehensive review of all error handling in the Ark CLIs to ensure we have friendly error messages and associated troubleshooting documentation.

Spun out of #492 and other error related issues.

- [ ] https://github.com/heptio/ark/issues/492

**Comment by skriss** [comment]
Not sure if we should lump this together or not, but we should also review our server log messages & levels. It would be nice for info-level server logging to have a consistent level of information across all controllers.
