### ISSUE TITLE
Implement deferring the upload of backup.json file

### ISSUE THREAD

**Issue by shubham-pampattiwar** [vmware-tanzu/velero#5493]
Related to: https://github.com/vmware-tanzu/velero/pull/5108

**Comment by sseago** [comment]
Not stale, but will probably be closed without implementation, as the latest approved design no longer calls for deferring this. Keeping open until the other implementation tasks are done.

**Comment by sseago** [comment]
Closing, as this was implemented somewhat differently, as per the updated design. backup.json is uploaded as before, but modified during finalize.
