### ISSUE TITLE
Implement the reconciliation logic to ignore Backup and Restores that are not completed

### ISSUE THREAD

**Issue by shubham-pampattiwar** [vmware-tanzu/velero#5496]
Related to: https://github.com/vmware-tanzu/velero/pull/5108

**Comment by sseago** [comment]
This really isn't a separate development task. The backup controller already ignores backups that aren't new. The new async item action progress monitoring controller will only look at waiting backups. Keeping this open for now, but can probably be closed once the other implementation tasks are complete.

**Comment by sseago** [comment]
Closing this, as it didn't end up being a separate development task -- the items described here were part of the BIA and RIA controller work.
