### ISSUE TITLE
add restoreItemAction to handle private registry change between clusters

### ISSUE THREAD

**Issue by wgkingk** [vmware-tanzu/velero#5498]
**Describe the problem/challenge you have**
When migrating across clusters, the target cluster cannot access the private registry of the original cluster.

**Describe the solution you'd like**
Like change-pv-configmap, add a restore action to handle registry changes

**Environment:**

- Velero version (use `velero version`): 1.8.1
- Kubernetes version (use `kubectl version`): 1.22+

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by Lyndon-Li** [comment]
This doesn't look like a general requirement to the restore process, so it is not suitable to have this in Velero's build in restore process, instead, a custom restore action plugin (as documented [here](https://velero.io/docs/main/custom-plugins/)) is better for this purpose.
