### ISSUE TITLE
velero csi volume snapshot backup timed out

### ISSUE THREAD

**Issue by kart2** [vmware-tanzu/velero#5504]
**What steps did you take and what happened:**
Attempted to take a velero backup 

**The following information will help us better understand what's going on**:

time="2022-10-27T08:10:10Z" level=error msg="Timed out awaiting reconciliation of volumesnapshot fea0ee4b-bbf6-4444-b1d6-e493597d46a4/velero--20--20-0-5dw5m" backup=velero/velero-prod-2-20221027020007 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:191" pluginName=velero-plugin-for-csi
time="2022-10-27T08:10:10Z" level=info msg="1 errors encountered backup up item" backup=velero/velero-prod-2-20221027020007 logSource="pkg/backup/backup.go:413" name=timescaledb-20-0
time="2022-10-27T08:10:10Z" level=error msg="Error backing up item" backup=velero/velero-prod-2-20221027020007 error="error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=fea0ee4b-bbf6-4444-b1d6-e493597d46a4, name=velero-20-20-0-5dw5m): rpc error: code = Unknown desc = timed out waiting for the condition" logSource="pkg/backup/backup.go:417" name=timescaledb-20-0

**Environment:**

- Velero version (use `velero version`):  1.9.2
- Kubernetes version (use `kubectl version`): 1.22
- Cloud provider or hardware configuration: EKS
- OS (e.g. from `/etc/os-release`): Ubuntu
- Velero csi plugin : v0.3.1
- aws plugin: v1.5.1

**Comment by Lyndon-Li** [comment]
The default CSI snapshot timeout is 10 min, if the disk size is large, you may need to change the value. The value can be configured by setting the `--csi-snapshot-timeout` flag, see `[here](https://github.com/vmware-tanzu/velero/blob/v1.9.2/site/content/docs/main/examples.md#:~:text=Create%20a%20backup%20with%20PV%20snapshotting)`

**Comment by Lyndon-Li** [comment]
cc @blackpiglet

**Comment by kart2** [comment]
thanks for the update. I will try this option and let you know.

**Comment by draghuram** [comment]
@kart2, Are you trying to backup EBS PVs using CSI? In general, this timeout can occur for the following reasons:

1) External snapshotter is not set up properly so VolumeSnapshotContent is not created.
2) VolumeSnapshotContent is successfully created but CSI driver hasn't created the snapshot and updated "snapshotHandle".
3) The storage snapshot is actually taking more than 10 minutes.

Increasing timeout helps only in (3). In case of (1) and (2), it won't help. First verify if you see VolumeSnapshotContent resource corresponding to the VolumeSnapshot and if so, check CSI driver logs to see if there is any problem in creating snapshot. Also make sure that both external snapshotter and CSI driver can work with "v1" snapshot APIs.

**Comment by blackpiglet** [comment]
@kart2 
Is your problem solved?

**Comment by kart2** [comment]
I am using k8s 1.22. without volume snapshot  CRs the backups are working. I am no longer using those CRs for the backup process.

**Comment by MuriloCouceiro** [comment]
Hey @draghuram, @blackpiglet. I wonder if you can please help me. I'm having this issue in v1.14.0 using smb.csi.k8s.io. 

From what I gathered, my problem is related to 2) from (draghuram) previous comment. I'm seeing the Event() log from the snapshotter-controller "waiting for a snapshot .... to be created by the CSI driver", but nothing connected in csi-smb-controller logs. 

Is this a driver related problem? Or is there a velero configuration that I should look into? 

Note: I also have a nfs.csi.k8s.io which is snapshotting the pvcs as expected.

Kubernetes version: v1.26.5
Snapshot CRDs: v1

**Comment by blackpiglet** [comment]
@MuriloCouceiro 
I think the SMB CSI driver doesn't support taking snapshots yet.
https://github.com/kubernetes-csi/csi-driver-smb/issues/356

**Comment by MuriloCouceiro** [comment]
I came across that issue, however I didn't found its description/alternatives very clear, so I was looking to confirm the configurations on velero side (just to be sure 😄).
However, now looking closely at the issue activity I guess it really is an impossible scenario for now.
Thanks!
