### ISSUE TITLE
Velero's backup sync bug

### ISSUE THREAD

**Issue by Yueyuexin** [vmware-tanzu/velero#5509]
**What steps did you take and what happened:**
Background:
1. There are two workload clusters wc1 and wc2, which deployed velero using the same minio server and bucket for storage.
2. I use velero create a backup file in wc1, but backup Partiallyfailed.
Question:
1. After I delete the partiallyfailed backup files in wc1, minio server also deleted, but the file still exists in wc2 backup list more than 1 day.
2. If the backup file is completed, if I delete in wc1/wc2, the other workload cluster will also be deleted.

**What did you expect to happen:**
If delete backup file in one workload cluster, the same backup file should not exist in backup list in the other workload clusters which deployed velero using the same minio server and bucket for storage. And waiting time should not last more than 1 day.

**The following information will help us better understand what's going on**:

 - wc1 
```
capv@control-plane-node-wc2-source-control-plane-qqcz2 [ ~ ]$ kubectl -n velero exec -it deployment/velero -c velero -- /velero backup get
NAME                    STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
backup-all-pv           Completed   0        2          2022-10-26 15:15:59 +0000 UTC   29d       default            <none>
backup-all-pv-pvc       Completed   0        2          2022-10-26 15:16:42 +0000 UTC   29d       default            <none>
backup-nginx            Completed   0        1          2022-10-26 14:21:05 +0000 UTC   29d       default            <none>
backup-specific-pv      Completed   0        1          2022-10-26 14:09:39 +0000 UTC   29d       default            specific-backup=true
not-includes-cert2      Completed   0        2          2022-10-25 10:53:44 +0000 UTC   28d       default            <none>
not-includes-cert3-cm   Completed   0        2          2022-10-25 10:56:44 +0000 UTC   28d       default            <none>
```
- wc2 
```
capv@control-plane-node-wc2-taget-control-plane-zlndn [ ~ ]$ kubectl -n velero exec -it deployment/velero -c velero -- /velero backup get
NAME                    STATUS            ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
backup-all-pv           Completed         0        2          2022-10-26 15:15:59 +0000 UTC   29d       default            <none>
backup-all-pv-pvc       Completed         0        2          2022-10-26 15:16:42 +0000 UTC   29d       default            <none>
backup-nginx            Completed         0        1          2022-10-26 14:21:05 +0000 UTC   29d       default            <none>
backup-specific-pv      Completed         0        1          2022-10-26 14:09:39 +0000 UTC   29d       default            specific-backup=true
exclude-resource-cert   PartiallyFailed   1        2          2022-10-25 10:50:49 +0000 UTC   28d       default            <none>
no-cert-manager         PartiallyFailed   2        3          2022-10-25 09:13:33 +0000 UTC   28d       default            <none>
not-includes-cert       PartiallyFailed   3        2          2022-10-25 10:41:59 +0000 UTC   28d       default            <none>
not-includes-cert2      Completed         0        2          2022-10-25 10:53:44 +0000 UTC   28d       default            <none>
not-includes-cert3-cm   Completed         0        2          2022-10-25 10:56:44 +0000 UTC   28d       default            <none>
```

**Anything else you would like to add:**
nothing

**Environment:**

velero version
Client:
        Version: v1.8.1_vmware.1
        Git commit: 18ee078dffd9345df610e0ca9f61b31124e93f50
Server:
        Version: v1.8.1_vmware.1

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
@Yueyuexin Please help to upload Velero's debug bundle. Thanks.

**Comment by Yueyuexin** [comment]
sorry, what is debug bundle?

**Comment by Lyndon-Li** [comment]
@Yueyuexin Run `velero debug` in your problematic environment, it will generate a gzip file, upload the gzip to this issue. Thanks.

**Comment by Yueyuexin** [comment]
Use command `kubectl logs backup-driver-59b6dcc49d-bspcq -n velero ` and the other `velero-5dc5cc6d9b-sjzc9` `datamgr-for-vsphere-plugin-9bv74` , and I tar the logs into gzip manually is OK?

**Comment by Yueyuexin** [comment]
Above kubectl command I can use normally.

**Comment by Yueyuexin** [comment]
and velero backup and restore both work normally, just velero debug.

**Comment by Lyndon-Li** [comment]
Then please use `kubectl logs deployment/velero -n velero` to get the log from the both side wc1 and wc2. On wc2, wait some time before collecting the log, for example, 30 min, after deleting the backups from wc1 and minio.

**Comment by Yueyuexin** [comment]
Thank you, Finally I download a velero release in my wc env, and use `velero debug` then.

**Comment by Yueyuexin** [comment]
[wc1-bundle-2022-10-28-09-47-21.tar.gz](https://github.com/vmware-tanzu/velero/files/9887345/wc1-bundle-2022-10-28-09-47-21.tar.gz)
[wc2-bundle-2022-10-28-09-14-55.tar.gz](https://github.com/vmware-tanzu/velero/files/9887347/wc2-bundle-2022-10-28-09-14-55.tar.gz)

The PartiallyFailed backup files `exclude-resource-cert`, `no-cert-manager` and `not-includes-cert` which  are created in wc1, and also deleted in wc1.

**Comment by blackpiglet** [comment]
I think this is caused by backup sync controller filtered the PartialFailed backup intendedly.

``` go
	for i, backup := range backupList.Items {
		log = log.WithField("backup", backup.Name)
		if backup.Status.Phase != velerov1api.BackupPhaseCompleted || backupStoreBackups.Has(backup.Name) {
			continue
		}

		if err := b.client.Delete(ctx, &backupList.Items[i], &client.DeleteOptions{}); err != nil {
			log.WithError(errors.WithStack(err)).Error("Error deleting orphaned backup from cluster")
		} else {
			log.Debug("Deleted orphaned backup from cluster")
			b.deleteCSISnapshotsByBackup(ctx, backup.Name, log)
		}
	}
```

I didn't find the exact purpose or explaination of this behavior in Velero commit history yet.
I think there is a possiblity that Velero failed to handle some cloud provider's volume or snapshot during the backup, although Restic scenario doesn't have the problem. If that is the case, I think Velero couldn't clean the leftover by itself.  Leave the PartiallyFailed backup there, and wait for manual handling is reasonable.
Not sure about the other's opinion about this.

**Comment by Yueyuexin** [comment]
Thanks for your reply. Agree with you. We will keep it as a known issue untill this bug be fixed someday.

**Comment by reasonerjt** [comment]
By checking the code seems it's working as designed.
Removing the candidate label for now and if there's no disagreement, we can close this issue.
