### ISSUE TITLE
AKS - velero BackupStorageLocation "default" is unavailable - rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token

### ISSUE THREAD

**Issue by zohebs341** [vmware-tanzu/velero#5515]
**What steps did you take and what happened:**

I've deployed velero in Azure AKS 1.23.11 and the versions being used in velero is "velero/velero-plugin-for-microsoft-azure:v1.5.0" & "velero/velero:v1.9.2".

[A clear and concise description of what the bug is, and what commands you ran.)

velero pod is up and running. However, in backupstoragelocation phase is "unavailable". I've created a service principal at the subscription level.

Error:
rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Storage/storageAccounts/xxxx/listKeys?%24expand=kerb&api-version=2019-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://x.x.x.x/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F

**What did you expect to happen:**
BackupStorageLocation should be available without any errors and even without errors in a pod.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  
- Client:
        Version: v1.9.2
        Git commit: 82a100981cc66d119cf9b1d121f45c5c9dcf99e1
Server:
        Version: v1.9.2
- Velero features (use `velero client config get features`): 
- velero client config get features
features: <NOT SET>

- Kubernetes version (use `kubectl version`): v1.23.12 Azure AKS
- Cloud provider or hardware configuration: Azure AKS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zohebs341** [comment]
Pod Logs:

time="2022-10-28T19:50:44Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/1/0, BackupStorageLocation \"default\" is unavailable: rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxxxxxx/resourceGroups/xxxxx/providers/Microsoft.Storage/storageAccounts/xxxxx/listKeys?%24expand=kerb&api-version=2019-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Identity not found\"} Endpoint http://x.x.x.x/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:171"


time="2022-10-28T19:50:50Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxxx/resourceGroups/xxxx/providers/Microsoft.Storage/storageAccounts/xxxx/listKeys?%24expand=kerb&api-version=2019-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Identity not found\"} Endpoint http://x.x.x.x/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:217" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:182"

**Comment by zohebs341** [comment]
@Lyndon-Li Can you please check and assist.

**Comment by zohebs341** [comment]
@ywk253100 Hi Yin, Can you please check and assist me on this?

**Comment by zohebs341** [comment]
@ywk253100 Hi Yin, any suggestions on this? As daily backups are failing. Is it a bug? if so, could you please assist me on which version we should use.

Errors:

$ kubectl describe bsl default -n velero
Name:         default
Namespace:    velero
Labels:       component=velero
Annotations:  <none>
API Version:  velero.io/v1
Kind:         BackupStorageLocation
Metadata:
  Creation Timestamp:  2022-10-28T17:25:34Z
  Generation:          11604
  Managed Fields:
    API Version:  velero.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:component:
      f:spec:
        .:
        f:config:
          .:
          f:resourceGroup:
          f:storageAccount:
          f:subscriptionId:
        f:default:
        f:objectStorage:
          .:
          f:bucket:
        f:provider:
    Manager:      velero
    Operation:    Update
    Time:         2022-10-28T17:25:34Z
    API Version:  velero.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:lastValidationTime:
        f:message:
        f:phase:
    Manager:         velero-server
    Operation:       Update
    Time:            2022-10-28T17:25:44Z
  Resource Version:  xxxxxx
  UID:               xxxxxxxxx
Spec:
  Config:
    Resource Group:   xxxxx
    Storage Account:  xxxxx
    Subscription Id:  xxxxx
  Default:            true
  Object Storage:
    Bucket:  xxxxx
  Provider:  azure
Status:
  Last Validation Time:  2022-11-05T19:11:39Z
  Message:               BackupStorageLocation "default" is unavailable: rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Storage/storageAccounts/xxxxx/listKeys?%24expand=kerb&api-version=2019-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F
  Phase:                 Unavailable
Events:                  <none>

**Comment by anshulahuja98** [comment]
,"error_description":"Identity not found"

The plugin is trying to hit the IMDS endpoint directly, from that one guess I can make is that you have only provided the client ID of the SP and the appropriate secret is empty/ incorrectly formatted.


Can you try checking the secret named "cloud-credentials"  inside velero namespace. And copy the data field in the secret, decode it from base64. 
This will show you all the values that you provided. 

Try to see if the secret/password for SP is configured there or not

**Comment by anshulahuja98** [comment]
Try to share what all you "Keys/variables" are configured in the file. That might help debug easily.

**Comment by zohebs341** [comment]
@anshulahuja98 Thanks for your response anshul. I've verified and I can see both client_id and client_secret in both secret and credentials-velero file.

We have used the below key-values at the time of velero installation: The same key values I can see when I decrypt the k8s secret.

AZURE_SUBSCRIPTION_ID
AZURE_TENANT_ID
AZURE_CLIENT_ID
AZURE_CLIENT_SECRET
AZURE_RESOURCE_GROUP
AZURE_CLOUD_NAME

**Comment by anshulahuja98** [comment]
I see, 
Hard to debug, but would try to list down potential troubleshooting steps, if any help you out.
1. Check for any stray whitespaces in the creds file?
2. maybe if you updated the credentials later - after pod spawn, pod might have old state of the secret
Perhaps try deleting the velero "pod", after it respawns, perhaps it has the correct values.

**Comment by VickyWinner** [comment]
@anshulahuja98 were you able to fix this?  I am using pre-existing secret and here is the values.yaml from helm

```yaml
...
    config:
      resourceGroup: centralus-xxxxx
      subscriptionId: 72661385-c651-4789xx
      storageAccount: veleroac
...
credentials:
  useSecret: true
  name: cloud-credentials
  existingSecret: 
  secretContents:
   cloud: |
     AZURE_CLIENT_ID=d2073258-48e4-4c7a-b461xx
     AZURE_CLIENT_SECRET=MJUxUOkjnaiCd136Qxx
     AZURE_SUBSCRIPTION_ID=72661385-c651-4789xx
     AZURE_TENANT_ID=d441ad83-6235-46d6-ab1axx
```

**Comment by VickyWinner** [comment]
What if the error occurs intermittently?  I do have scheduled backups and 10% of the time, these fail with the error message.  
```log
: 'rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization:
      Failed to refresh the Token for request to https://management.azure.com/subscriptions/subxxxx/resourceGroups/rgnamexxxx/providers/Microsoft.Storage/storageAccounts/velero/listKeys?%24expand=kerb&api-version=2019-06-01:
      StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code
      = ''401''. Response body: {"error":"invalid_client","error_description":"AADSTS7000000:
      Invalid client secret provided. Ensure the secret being sent in the request
      is the client secret value, not the client secret ID, for a secret added to
      app ''d2073258-48e4-4c7a-b461-xxxxxxxxxx''.\r\nTrace ID: 1b857978-ca62-4632-b35c-eb565032de00\r\nCorrelation
      ID: 62e43e86-ad18-4ce4-b40b-780caf80af59\r\nTimestamp: 2023-01-05 21:10:28Z","error_codes":[7000215],"timestamp":"2023-01-05
      21:10:28Z","trace_id":"1b857978-ca62-4632-b35c-eb565032de00","correlation_id":"62e43e86-ad18-4ce4-b40b-780caf80af59","error_uri":"https://login.microsoftonline.com/error?code=7000215"}
      Endpoint https://login.microsoftonline.com/xxxxxxxx-6235-46d6-ab1a-89744a91b1d8/oauth2/token?api-version=1.0'
```
Can someone pls suggest troubleshooting route?

**Comment by VickyWinner** [comment]
> @anshulahuja98 were you able to fix this? I am using pre-existing secret and here is the values.yaml from helm
> 
> ```yaml
> ...
>     config:
>       resourceGroup: centralus-xxxxx
>       subscriptionId: 72661385-c651-4789xx
>       storageAccount: veleroac
> ...
> credentials:
>   useSecret: true
>   name: cloud-credentials
>   existingSecret: 
>   secretContents:
>    cloud: |
>      AZURE_CLIENT_ID=d2073258-48e4-4c7a-b461xx
>      AZURE_CLIENT_SECRET=MJUxUOkjnaiCd136Qxx
>      AZURE_SUBSCRIPTION_ID=72661385-c651-4789xx
>      AZURE_TENANT_ID=d441ad83-6235-46d6-ab1axx
> ```

This one got resolved.

**Comment by VickyWinner** [comment]
What if the error occurs intermittently?  I do have scheduled backups and 10% of the time, these fail with the error message.  
```log
: 'rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization:
      Failed to refresh the Token for request to https://management.azure.com/subscriptions/subxxxx/resourceGroups/rgnamexxxx/providers/Microsoft.Storage/storageAccounts/velero/listKeys?%24expand=kerb&api-version=2019-06-01:
      StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code
      = ''401''. Response body: {"error":"invalid_client","error_description":"AADSTS7000000:
      Invalid client secret provided. Ensure the secret being sent in the request
      is the client secret value, not the client secret ID, for a secret added to
      app ''d2073258-48e4-4c7a-b461-xxxxxxxxxx''.\r\nTrace ID: 1b857978-ca62-4632-b35c-eb565032de00\r\nCorrelation
      ID: 62e43e86-ad18-4ce4-b40b-780caf80af59\r\nTimestamp: 2023-01-05 21:10:28Z","error_codes":[7000215],"timestamp":"2023-01-05
      21:10:28Z","trace_id":"1b857978-ca62-4632-b35c-eb565032de00","correlation_id":"62e43e86-ad18-4ce4-b40b-780caf80af59","error_uri":"https://login.microsoftonline.com/error?code=7000215"}
      Endpoint https://login.microsoftonline.com/xxxxxxxx-6235-46d6-ab1a-89744a91b1d8/oauth2/token?api-version=1.0'
```
Can someone pls suggest troubleshooting route?

**Comment by shubham-cardbyte** [comment]
this issue is still coming , i have successfully deployed velero in velero-backups namespace on AKS , it works for 2 days properly and after 2 days suddenly , BSL is unavailable with error message "BackupStorageLocation "default" is unavailable: rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/2c52c575-8054-474c-8aed-2908cc9b316d/resourceGroups/Velero_Backups/providers/Microsoft.Storage/storageAccounts/velero2518b2a99e5c/listKeys?%24expand=kerb&api-version=2019-06-01: StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID"

Can anyone tell me where is the issue?
