### ISSUE TITLE
velero binary will not execute on ubuntu-latest azure devops agent

### ISSUE THREAD

**Issue by michaelsaxbury** [vmware-tanzu/velero#5523]
I downloaded the latest package using powershell core in an Azure CLI task in my azure devops pipeline running on ubuntu-latest build agent. It extracts successfully, and I can see the binary, and that it has exec permissions, but I cannot call velero to perform any actions?

$url = 'https://github.com/vmware-tanzu/velero/releases/latest'
$request = [System.Net.WebRequest]::Create($url)
$response = $request.GetResponse()
$realTagUrl = $response.ResponseUri.OriginalString
$version = $realTagUrl.split('/')[-1].Trim('v')
$version
$realTagUrl

($realTagUrl.split('/')[-1])-linux-arm64.tar.gz"
$realDownloadUrl = $realTagUrl.Replace('tag', 'download') + '/' + $fileName
$realDownloadUrl
"=================="
Invoke-WebRequest -Uri (System.ArtifactsDirectory)/$($fileName)"

Write-Host "rnDownloaded file"
ls

Write-Host "rnExtract the tar"
tar -xvf $fileName

Write-Host "rnExtracted contents"
ls

#Write-Host "rnVelero path:"
#$extractedFolderName = $fileName -replace '.tar.gz', ''
#"$(System.ArtifactsDirectory)/$($extractedFolderName)/velero"

#Write-Host "rnCD to velero path"
#cd $(System.ArtifactsDirectory)/$extractedFolderName
#ls

Write-Host "rnVelero run"
**### #ALL of these fail**
.\velero version
velero version
& velero version
$(System.ArtifactsDirectory)/$extractedFolderName/velero version
$(System.ArtifactsDirectory)/velero-v1.9.2-linux-arm64/velero version

Program 'velero' failed to run: An error occurred trying to start process '/home/vsts/work/r1/a/velero-v1.9.2-linux-arm64/velero' with working directory '/home/vsts/work/r1/a/velero-v1.9.2-linux-arm64'. Exec format errorAt /home/vsts/work/_temp/azureclitaskscript1667250930999_inlinescript.ps1:35 char:1

**- Velero version (use `velero version`): v1.9.2 binary download from github**
https://github.com/vmware-tanzu/velero/releases/download/v1.9.2/velero-v1.9.2-linux-arm64.tar.gz

**- OS (e.g. from `/etc/os-release`):**
2022-10-31T21:27:42.9097933Z Agent name: 'Hosted Agent'
2022-10-31T21:27:42.9098502Z Agent machine name: 'fv-az373-135'
2022-10-31T21:27:42.9098745Z Current agent version: '2.211.1'
2022-10-31T21:27:42.9158447Z ##[group]Operating System
2022-10-31T21:27:42.9158779Z Ubuntu
2022-10-31T21:27:42.9158938Z 20.04.5

**Comment by ywk253100** [comment]
Could you double check your CPU architecture is `arm` or `amd64`?

**Comment by michaelsaxbury** [comment]
I am using azure devops release pipeline agent job which is defined to use Azure Pipelines pool with agent ubuntu-latest. I am not sure if that guarantees arm64 or amd64 every time. My last attempt was on amd64, so the arm64 version i downloaded does not match. I can probably put some logic in to check it and download the correct one if the agents do change.

**Comment by michaelsaxbury** [comment]
incorporated the os architecture syntax into the download url, same issue, cannot seem to execute velero after installation

**Comment by ywk253100** [comment]
Closing this issue as it is resolved
