### ISSUE TITLE
Bump github.com/Azure/azure-sdk-for-go from 61.4.0+incompatible to 67.0.0

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#5560]
Bump github.com/Azure/azure-sdk-for-go from 61.4.0+incompatible to 67.0.0 as dependencybot security upgrade suggest to do so in PR #5557

**Comment by ywk253100** [comment]
Fixed by https://github.com/vmware-tanzu/velero/pull/5709
