### ISSUE TITLE
Enhance error information for backup by publishing backupresults

### ISSUE THREAD

**Issue by anshulahuja98** [vmware-tanzu/velero#5575]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
Refer to discussion in #5200 
Restore as of today exposes a restore results.json file, whereas there is no way for user to figure out backup related errors. 

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Create a backupresults.json which captures all warnings/errors which occurred during execution of backup.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by sseago** [comment]
Not stale

**Comment by reasonerjt** [comment]
Per discussion we should also make sure this is cherry picked to v1.10.x

**Comment by reasonerjt** [comment]
The cherry-pick to v1.10.x has been addressed via #5879
