### ISSUE TITLE
The finalizer isn't restored

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#5580]
Currently, only fields `namespace`, `name`, `labels` and `annotations` of metadata are [restored](https://github.com/vmware-tanzu/velero/blob/v1.9.2/pkg/restore/restore.go#L1705), the `finalizer` isn't in the list, this may cause issue when deleting resources

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
@sseago 
Could you share your opinion on this issue?
Normally the `finalizer` is added by controllers, I'm not if it correct to let velero retain this field, or rather expect controller should add this field as needed.

Since velero has been working like this for years, I'm not sure if not to restore the `finalizer` is by design or a bug.

**Comment by blackpiglet** [comment]
To make the restored resources contain more accurate information, I think keeping information like finalizer is better, but keeping finalizer may cause some behavior change.
Per my understanding, there are two different scenarios involved finalizer:
* Some other controller depends, or cares about the resource has finalizer. This is the stable situation. Finalizer should be kept for this case, and that would not do any harm.
* The resource has finalizer is in a transition state. Not sure what will happen after restore, if the finalizer is added. I think the case needs more consideration.

**Comment by sseago** [comment]
So it seems that there are some cases where restoring finalizers is desired, but in others it could warrant unwanted changes. The easiest way to resolve this would be to add a new restore spec field: `restoreFinalizers` which would default to false but could be set to true. A more elaborate fix would be to provide a list of resource types to restore finalizers for (but allowing "*" as a value if all finalizers should be restored).

**Comment by anshulahuja98** [comment]
If there is consensus on adding this functionality - can I work towards it? The elaborate fix with resource type in which finalizers are to be restored.

**Comment by blackpiglet** [comment]
@anshulahuja98 
Please hold on the developing work. Velero team is still doing investigation on this topic.

**Comment by sseago** [comment]
@blackpiglet Looking back at my earlier comments, I'm thinking the best way forward may be to follow the design of the restore.spec.RestoreStatus field -- where, by default, we don't restore status, but users can use the standard velero included/excludedresources syntax to modify this. We could do the same with a new `spec.RestoreFinalizers` field.

**Comment by killianmuldoon** [comment]
Just to understand this - what cases would a user not want a finalizer restored after backup? It seems like not restoring the finalizer can have major unexpected impact - e.g. orphaned resources - but I'd like to understand when losing the finalizer would have an impact.

**Comment by reasonerjt** [comment]
More generally for the fields in `metadata`, IMO maybe we should do it another way, we explicitly do not include some of the fields like `uid`, `ownerReferences` `resourceVersion`, etc. during the restore, and restore other fields by default?

**Comment by ywk253100** [comment]
Fixed by https://github.com/vmware-tanzu/velero/pull/5853
