### ISSUE TITLE
Does velero support restoring specific objects? 

### ISSUE THREAD

**Issue by OPSTime** [vmware-tanzu/velero#5586]
Does velero support restoring specific objects? For example:

`velero restore create --from-backup backup-2 --include-resources persistentvolumeclaims --include-namespaces test --object-name data-pv1`

**Comment by blackpiglet** [comment]
Cannot just specify the resource name, but you can filter resource by tag with "--selector" parameter.

**Comment by OPSTime** [comment]
But the name should be the most accurate and intuitive。
It should not be complicated to support.

**Comment by blackpiglet** [comment]
I agree, but that is not supported yet.
There is already another issue with requests for a similar using scenario. #5152
