### ISSUE TITLE
Facing error while restoring using Velero

### ISSUE THREAD

**Issue by Vishnu-Priya05** [vmware-tanzu/velero#5592]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Installed velero to backup the PVC's. Created a backup for it and the backup was successful. While restoring the backup, it is partially failed.
Error: error parsing backup contents: directory "/tmp/30672821/resources": does not exist

**What did you expect to happen:**
It should have restored the data from the backup that happened
**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by allenxu404** [comment]
This error suggests that the restore controller can find any resource to be restored , which means that you don't successfully backup the resources. You could double check the existance of the resources from the object storage you specify.

**Comment by Vishnu-Priya05** [comment]
I need to take the backup of PVC alone for a particular namespace. Can you please help in giving the "velero create backup" command for it?

**Comment by Vishnu-Priya05** [comment]
velero backup create backupname --orderedresources 'persistentvolumeclaims=ns1/pvc1'
This is the command I'm using for backing up the PVC data. Can you check and let me know if the above command would work for PVC backup.

**Comment by allenxu404** [comment]
@Vishnu-Priya05  backup/restore PVC is a little complicated and you could either use CSI snapshot or Restic to do that. Please refer to [CSI doc ](https://velero.io/docs/v1.9/csi/) and [Restic doc](https://velero.io/docs/v1.9/restic/) for more information. 

`velero backup create backupname --orderedresources 'persistentvolumeclaims=ns1/pvc1'` is not a correct way to backup PVC. We can further discuss it after you figure out which way fit in with your scenario
