### ISSUE TITLE
Count of Backup Items and Restore Items does not match

### ISSUE THREAD

**Issue by msaklecha** [vmware-tanzu/velero#5596]
I have created backup of the entire EKS which got successfully created . 
When I created restore from that backup , it was successfully created too , but the count of items displayed during backup was not same as Velero when trying to restore .
Is some items skipped during the restore ? Why its a count mismatch.

Below is describe of backup :

Backup Format Version:  1.1.0

Started:    2022-11-16 10:21:13 +0000 UTC
Completed:  2022-11-16 10:21:24 +0000 UTC

Expiration:  2022-12-16 10:21:13 +0000 UTC

Total items to be backed up:  702
Items backed up:              702

Below is describe restore from same backup  : 

Phase:           Completed
Total items to be restored:  646
Items restored:              646

Backup:  firstbackup

Namespaces:
  Included:  all namespaces found in the backup
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Existing Resource Policy:   <none>

Preserve Service NodePorts:  auto

Below commands I used for backup and restore : 

velero create backup firstbackup
velero create restore --from-backup firstbackup

Is the excluded resource in restore is reason for the difference of this count mismatch ?

**Comment by allenxu404** [comment]
Yes, During the restore, we will Iterate through the list of resources and check each of one to see if it need to be restored. The total item to be restored is the result that we recalculate during restore.

**Comment by msaklecha** [comment]
Thanks for the response.
