### ISSUE TITLE
Fails to exclude restic volume backup for specific PV

### ISSUE THREAD

**Issue by navilg** [vmware-tanzu/velero#5597]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I added label `velero.io/exclude-from-backup: true` to a PVC and its PV and created backup. I see in backup description that the restic is still taking backup of that volume (PV).

**What did you expect to happen:**

It should skip the backup of volume data associated with labeled PV.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.8.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.21
- Kubernetes installer & version: GKE 1.21
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by allenxu404** [comment]
Cloud you provide me with description of pod? Here is a [doc](https://velero.io/docs/v1.9/restic/#how-backup-and-restore-work-with-restic) that concerns with the instruction on how to use restic in velero, it might helps you.

**Comment by navilg** [comment]
I have a pod where number of volumes are mounted. Those volumes are dynamically provisioned with storage class. I need to exclude volume backup of one of the volume mounted on that pod.

I added `velero.io/exclude-from-backup: true` label to the PV and PVC of respective volume and created backup again. I see that volume is still getting backed up.

Later I realised, It is just excluding PV and PVC's manifest, not the actual volume data which is inside the PV. 

Now, I have got this done by adding annotation in pod to exclude a volume using opt-out method. But don't labeling a PV should exclude the podvolume mounted on a pod of that respective PV ?

**Comment by allenxu404** [comment]
Good to know you've got this done. As for the question that labeling a PV should exclude the corresponding podVolume, I think it can work this way but I'm not sure we can succeed in tracing its podvolume in any scenario. Plus, since in this case the actual backup target is volume, labeling volume name rather than pv name is more straightforward.

**Comment by reasonerjt** [comment]
Thanks @allenxu404 I'm closing it as usage error.
