### ISSUE TITLE
Config Value for Default Timeouts

### ISSUE THREAD

**Issue by eemcmullan** [vmware-tanzu/velero#5604]
Related issue: https://github.com/vmware-tanzu/velero/issues/5416

There appear to be a few other default timeouts that could cause similar issues as in 5416: creating the backup repo https://github.com/vmware-tanzu/velero/blob/main/pkg/repository/ensurer.go#L108 and waiting for CRDs in restore: https://github.com/vmware-tanzu/velero/blob/main/pkg/restore/restore.go#L863

Apart from these, other timeouts could be introduced in the future. A configurable `timeout` value shared by these timeouts could be created to help prevent further issues. Or it may make more sense to group together related timeouts.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by eemcmullan** [comment]
In order to get a discussion going around this issue, are there other relevant timeout values apart from what I included above? Also, would these fall under a single config value, such as `timeouts` ?

**Comment by blackpiglet** [comment]
Our preferred way to fix this is adding limit of running goroutine's number, e.g. 100 or 50. That will make the API server response faster.

**Comment by eemcmullan** [comment]
I'm not sure if this would fully resolve the issue if the api server is overloaded. Allowing these values to be configured if so seems to be the approach to avoid this.

**Comment by blackpiglet** [comment]
I had some misunderstanding of this issue's PR at first. I thought this timeout is used specifically for the CSI snapshot deletion.
Actually, it's a generic timeout timer that can be used at all the places that need it, and we had some discussion about that in #5416.
