### ISSUE TITLE
Prometheus specifies the listening port, and the backup recovery displays an error

### ISSUE THREAD

**Issue by liangyahong** [vmware-tanzu/velero#5636]
![image](https://user-images.githubusercontent.com/112998504/203952063-6f15423f-151e-423c-b1c7-da504c49990a.png)

**Comment by qiuming-best** [comment]
@liangyahong How do you execute the command of restore? Maybe you should choose not to [preserve NodePorts](https://velero.io/docs/v1.9/restore-reference/#always-preserve-nodeports) when restoring
