### ISSUE TITLE
Velero in DR region doesn't show backups correctly

### ISSUE THREAD

**Issue by jyriatntt** [vmware-tanzu/velero#5637]
---
name: Bug report
about: velero get backups works intermittently and doesn't show all backups when it shows them

---

**What steps did you take and what happened:**
I installed velero in productions AKS with the storage in the DR region and set up backup schedule to back up every 10mins, then I installed it to DR region AKS with the same settings as the production one.

velero get backups in production shows backups taken every ten minutes.

velero get backups in DR sometimes doesn't show anything, sometimes it gives a list of backups but the list is not complete and there are large gaps between the backups it shows (sometimes just missing half an hour, others many hours). 

**What did you expect to happen:**
See the backups created in the production AKS velero in the DR velero

**The following information will help us better understand what's going on**:
Debug bundle attached, it's run on the production environment since it's impossible to do it in DR.
[bundle-2022-11-25-12-40-59.tar.gz](https://github.com/vmware-tanzu/velero/files/10092456/bundle-2022-11-25-12-40-59.tar.gz)

**Environment:**

- Velero version (use `velero version`):v1.9.3 -
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"83d00b7cbf10e530d1d4b2403f22413220c37621", GitTreeState:"clean", BuildDate:"2022-11-09T19:50:11Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version:
- Cloud provider or hardware configuration: Azure AKS
- OS (e.g. from `/etc/os-release`): - RuntimeOS: darwin - RuntimeArch: amd64

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
@jyriatntt  The log file in the debug bundle only contains a short time logs for Velero, could you run the debug command again to collect more logs

**Comment by jyriatntt** [comment]
Hi, hopefully this one has enough log info
[bundle-2022-11-28-11-40-43.tar.gz](https://github.com/vmware-tanzu/velero/files/10102872/bundle-2022-11-28-11-40-43.tar.gz)

**Comment by ywk253100** [comment]
The log file only contains one-hour logs and still cannot find any message about the backup sync logic.
There should be a field `lastSyncedTime` in the status of `BackupStorageLocation`, but didn't find it in your environment.

Could you try v1.10.0 which we did some refactoring with the backup sync controller?

**Comment by jyriatntt** [comment]
Hi,

We just tried with the new version, but we don't get it to install, we get:
unable to get all required config values: the following keys do not have values: resourceGroup

We have all the
[Velero-v1.10-install.log](https://github.com/vmware-tanzu/velero/files/10207807/Velero-v1.10-install.log)
 values set up for
velero install \
    --provider azure \
    --plugins velero/velero-plugin-for-microsoft-azure:v1.6.0 \
    --bucket $BLOB_CONTAINER \
    --secret-file ./credentials-velero \
    --backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID[,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID] \
    --snapshot-location-config apiTimeout=<YOUR_TIMEOUT>[,resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID]

So I don't really see where is the problem, excerpt from the kubernetes logs attached

**Comment by jyriatntt** [comment]
Hello everyone, we finally managed to get the installation working and with the new version the backups now show correctly in the DR region.

Thanks for the help!
