### ISSUE TITLE
Upgrade Restic to v0.14.0 in 1.10 patches

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#5654]
Velero v1.9.4 has bumped up Restic to v0.14.0, in which the repository format V2 is used, refer to [Restic release notes](https://restic.net/blog/2022-08-25/restic-0.14.0-released/) for details.  
Whereas, v1.10 is still with Restic v0.13.1, so if you are using File System Backup, you may encounter problem to restore from backups created by v1.9.4.

Let's upgrade Restic to v0.14.0 in 1.10 patches, otherwise, 1.10 will not support upgrade from 1.9.4

**Comment by qiuming-best** [comment]
I've bumped up restic v0.14.0 to [main](https://github.com/vmware-tanzu/velero/pull/5653) and [release-1.10 ](https://github.com/vmware-tanzu/velero/pull/5655)branch, So I close it.
