### ISSUE TITLE
Velero does not add storage classes as dependant resource while restoring specific namespace

### ISSUE THREAD

**Issue by kkothule** [vmware-tanzu/velero#5666]
Steps:
1. Backup the namespace using vekero
2. Delete the namespace and storage class used in PVCs
3. Restore the namespace 

{"level":"error","logSource":"pkg/controller/restore_controller.go:513","msg":"Namespace test-csi-snapshot, resource restore error: error preparing persistentvolumeclaims/test-csi-snapshot/mysql-pv-claim: rpc error: code = Unknown desc = **Failed to get StorageClass csi-storageclass to check PVC test-csi-snapshot/mysql-pv-claim provisioner: storageclasses.storage.k8s.io \"csi-storageclass\" not found**","restore":"cloudcasa-io/639040b0775172e2351d24e3","time":"2022-12-07T07:29:26Z"}
{"level":"error","logSource":"pkg/controller/restore_controller.go:513","msg":"Namespace test-csi-snapshot, resource restore error: error preparing persistentvolumeclaims/test-csi-snapshot/wp-pv-claim: rpc error: code = Unknown desc = Failed to get StorageClass csi-storageclass to check PVC test-csi-snapshot/wp-pv-claim provisioner: storageclasses.storage.k8s.io \"csi-storageclass\" not found","restore":"cloudcasa-io/639040b0775172e2351d24e3","time":"2022-12-07T07:29:26Z"}

**What did you expect to happen:**

Velero should restore storage class as dependant resource while restoring PVCs

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment]
This would be easy enough to add, but I wonder whether it's desirable. Simply creating a storageclass from backup won't enable that particular storage provider, if the cluster isn't otherwise configured for it. Generally storageclasses are created along with configuring the cluster to enable that particular kind of storage. If the storageclass that your backup needs isn't available where you're restoring, you probably want to configure storage before restoring. Alternatively, you may want to use the change storageclass functionality to re-map volumes to something you have available when restoring.

**Comment by ywk253100** [comment]
I'm closing this issue, feel free to reopen it.
