### ISSUE TITLE
Helm chart was not overwritten

### ISSUE THREAD

**Issue by ox7a59** [vmware-tanzu/velero#5667]
**Problem:**

A full restore would be performed with the `--existing-resource-policy=update` flag.
Statefulset resources were successfully overwritten, but the version of the Helm chart remained the same as it was before the restore.
So Helm again tried to restore the incorrect version of the Statefulset.
Is it possible to somehow update the resources so that the Helm chart is downgraded?

**Environment:**

```
user@host:~$ velero version
Client:
        Version: v1.10.0
        Git commit: 367f563072659f0bcd809bc33507fd75cd722344
Server:
        Version: v1.9.3

user@host:~$ velero client config get features
features: <NOT SET>

user@host:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

AWS EKS version: `v1.21.5-eks-9017834`

**Comment by ox7a59** [comment]
Help please 🙏 
Maybe I'm doing something wrong?

**Comment by ox7a59** [comment]
@ywk253100 yes, I started the recovery, internal resources were restored (Statefulset, services), but the chart version remained the same in the `helm ls -n <>`.

**Comment by ywk253100** [comment]
@ox7a59 Do you have a concrete example to help us better understand the issue?

**Comment by ox7a59** [comment]
I have this problem with Consul chart: https://github.com/hashicorp/consul-k8s
