### ISSUE TITLE
Support Kopia in velero Grafana dashboard

### ISSUE THREAD

**Issue by allenxu404** [vmware-tanzu/velero#5671]
**Describe the problem/challenge you have**
V1.10 has been GA with Kopia integrated into file system backup. We need to support Kopia in current Grafana dashboard as well.

**Describe the solution you'd like**
We need to adjust the current Grafana dashboard based on V1.10 metrics. 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by allenxu404** [comment]
Already done. Check it on Grafana.

**Comment by jemag** [comment]
@allenxu404 could you paste the link to the dashboard code?
Can't seem to find it in the various repositories and can't see any linked pull requests/commits

**Comment by allenxu404** [comment]
@jemag here it is: https://grafana.com/grafana/dashboards/16829-kubernetes-tanzu-velero/ 
Dashboard code is independent to Velero OSS code so there's no PR attached to it but we refer to it on the changelog.

**Comment by jemag** [comment]
@allenxu404 it would be nice if it could be integrated in one of the GitHub repo (doesn't have to be this one) so that the community can create issues on it and contribute with PRs. Otherwise it feels a bit hard to report problems and implement fixes if there is nowhere to submit code changes.

**Comment by allenxu404** [comment]
@jemag It makes sense and I'll take note of it. 
So far, if there is any issue on it, you can raise an issue on this repo and we'll take a look.

**Comment by fenggolang** [comment]
I couldn't find Kopia In Velero in the Grafana dashboard list, only Restic In Velero (dashboard ID 16829)
