### ISSUE TITLE
Panic when using exec restore hooks

### ISSUE THREAD

**Issue by dymurray** [vmware-tanzu/velero#5674]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
When using restore hooks, a recent commit didn't take into account a restore hook not having init container hooks and only using exec hooks. The restore controller tries to validate the hooks and doesn't take into account when initcontainers aren't being used on the hook. Because of this we get a nil panic. Full bug details are [here](https://issues.redhat.com/browse/OADP-1076)

**What did you expect to happen:**
Velero shouldn't crash.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This commit introduced the bug: https://github.com/vmware-tanzu/velero/commit/e8da5df57af1ad590eea10e31cd0c4c9b3c31bed

**Environment:**

- Velero version (use `velero version`): 1.10
- Kubernetes version (use `kubectl version`): 1.24
- Cloud provider or hardware configuration: Openshift

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
@dymurray Could you cherry-pick the fix into the 1.10 branch?

**Comment by dymurray** [comment]
https://github.com/vmware-tanzu/velero/pull/5708
