### ISSUE TITLE
The 1.10 version of the Velero Go package is not backwards compatible

### ISSUE THREAD

**Issue by sgalsaleh** [vmware-tanzu/velero#5681]
**What steps did you take and what happened:**

Since Velero 1.10 renamed “restic” references to “node-agent”, it seems that the Restic CRDs are no longer accessible via Velero's Go Kubernetes clientset. For example, currently we have the following:
```go
veleroClientset.ResticRepositories(<namespace>).List(....
```
to list the available Restic repositories, but in Velero 1.10, that was renamed to:
```go
veleroClientset.BackupRepositories(<namespace>).List(....
```
and it’s not possible to list Restic repositories using the 1.10 Velero Go module, which means that it is backwards incompatible.

Our software needs to support multiple versions of Velero (>1.5) and this makes it impossible to do so since Go doesn’t allow you to include multiple versions of the same Go module.

Is there any reason this wasn’t released as a `/v2` module in order to be able to support pre and post Velero 1.10?

Thanks in advance.

**What did you expect to happen:**

The 1.10 Velero Go package is backwards compatible with Velero versions < 1.10 or is released as a `/v2` version to allow importing it as a separate Go module.

**The following information will help us better understand what's going on**:

N/A

**Anything else you would like to add:**

No

**Environment:**

- Velero version (use `velero version`): 1.10
- Velero features (use `velero client config get features`): N/A
- Kubernetes version (use `kubectl version`): N/A
- Kubernetes installer & version: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from `/etc/os-release`): N/A

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
I believe that's a decision we have made that we break the backward compatibility in v1.10

I think you are right the `v2` is better, but we don't expect this package be used independently.  The reason for this break change is that we consider it internal mechanism and we don't think we have the bandwidth to support multiple versions for such packages.

**Comment by reasonerjt** [comment]
I'll keep this issue open for a couple of weeks for more discussion, if there's no strong opinion I'll close it as `won't fix`
