### ISSUE TITLE
Better to have customized IAM policy setting environment for Velero nightly

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#5682]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
Met a AWS environment issue with Velero v1.9.4.
AWS credential is created with limited IAM permission, but enough for Velero to work.
Restic backup failed by `restic init` with error `client.BucketExists: Access Denied`.
It is introduced due to Velero v1.9.4 upgrade integrated Restic from v0.13.1 to v0.14.0.
This [issue](https://github.com/restic/restic/issues/4085) is created to trace on Restic.
And the [original issue](https://github.com/restic/restic/issues/1477) describe the scenario better.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
It's better that Velero can have some tests with resticted IAM permission scenario, so we can find defect earlier.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.9.4
- Kubernetes version (use `kubectl version`): v1.23
- Kubernetes installer & version: vSphere
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from `/etc/os-release`): Ubuntu

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by danfengliu** [comment]
This test scenario is covered by using AWS restricted credential in EKS pipeline as below.

I just list the key part of AWS credential:
```
        {
            "Sid": "VisualEditor4",
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": "arn:aws:s3:::nightly-eks-test",
            "Condition": {
                "StringLike": {
                    "s3:prefix": "eks/*"
                }
            }
        }
```
