### ISSUE TITLE
Backup repository maintain always fail if Velero pod is restarted for Kopia path

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#5696]
For Kopia path only, if Velero pod restarts for any reason, Backup repository maintain always fails with below error reported:
`time="2022-12-15T08:52:25Z" level=warning msg="error pruning repository" backupRepo=velero/nginx-example-default-kopia-d2wkm error="error to prune backup repo: repo config /home/nonroot/udmrepo/repo-0008b8a4-3eac-4cc6-9345-1ef93599f3a7.conf doesn't exist: stat /home/nonroot/udmrepo/repo-0008b8a4-3eac-4cc6-9345-1ef93599f3a7.conf: no such file or directory" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/udmrepo/kopialib/lib_repo.go:158" error.function="github.com/vmware-tanzu/velero/pkg/repository/udmrepo/kopialib.(*kopiaRepoService).Maintain" logSource="pkg/controller/backup_repository_controller.go:197"`

**Comment by reasonerjt** [comment]
@Lyndon-Li is it b/c the uuid in the path `0008b8a4-3eac-4cc6-9345-1ef93599f3a7` changed after the restart?
