### ISSUE TITLE
Error getting volume snapshotter for volume snapshot location

### ISSUE THREAD

**Issue by hemanthjakkoju** [vmware-tanzu/velero#5704]
**What steps did you take and what happened:**
provider "helm" {
  kubernetes {
    host                   = var.eks_host
    cluster_ca_certificate = base64decode(var.eks_ca_certificate)
    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      args        = ["eks", "get-token", "--cluster-name", var.eks_id]
      command     = "aws"
    }
  }
}

resource "helm_release" "velero" {
  repository       = "https://vmware-tanzu.github.io/helm-charts"
  chart            = "velero"
  name             = "velero"
  namespace        = "velero"
  version          = "2.32.3"
  create_namespace = true

  set {
    name  = "configuration.provider"
    value = "aws"
  }
  set {
    name  = "configuration.backupStorageLocation.name"
    value = "aws-velero"
  }

  set {
    name  = "configuration.backupStorageLocation.config.region"
    value = "us-east-1"
  }
  set {
    name  = "configuration.backupStorageLocation.bucket"
    value = aws_s3_bucket.s3_logging.bucket
  }

  set {
    name  = "initContainers[0].name"
    value = "velero-plugin-for-aws"
  }

  set {
    name  = "initContainers[0].image"
    value = "velero/velero-plugin-for-aws:v1.1.0"
  }
  set {
    name  = "initContainers[0].volumeMounts[0].mountPath"
    value = "/target"
  }
  set {
    name  = "initContainers[0].volumeMounts[0].name"
    value = "plugins"
  }
  set {
    name  = "initContainers[1].name"
    value = "velero-plugin-for-csi"
  }

  set {
    name  = "initContainers[1].image"
    value = "velero/velero-plugin-for-csi:v0.1.1"
  }
  set {
    name  = "initContainers[1].volumeMounts[0].mountPath"
    value = "/target"
  }
  set {
    name  = "initContainers[1].volumeMounts[0].name"
    value = "plugins"
  }
  set {
    name  = "initContainers[1].volumeMounts[0].name"
    value = "plugins"
  }

}

These are my steps to take a backup but I am not able to take a volume snapshot backup. getting this  below error

(time="2022-12-15T18:24:18Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/new15 error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/volume_snapshotter.go:76" error.function="main.(*VolumeSnapshotter).Init" logSource="pkg/backup/item_backupper.go:470" name=pvc-aebc4da1) 

Can you please tell me what the issue ?.

**Comment by reasonerjt** [comment]
@hemanthjakkoju 
Please clarify how you installed velero, looks like you also need to set the region of the volumesnapshotlocation in addition to backupstoragelocation.

If you are installing velero via helm chart, it can be set here:
https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml#L272

**Comment by hemanthjakkoju** [comment]
Hi @reasonerjt , Thanks for your reply. 

I have added 2 steps, as you mention but now it's showing some different errors. BTW I am installing velero in the AWS eks cluster.
This is the step I have added. 

set {
    name  = "configuration.volumeSnapshotLocation.name"
    value = "aws-velero"
  }
  set {
    name  = "configuration.volumeSnapshotLocation.config.region"
    value = "us-east-1"
  }
  set {
    name  = "initContainers[1].image"
    value = "velero/velero-plugin-for-csi:v0.1.1"
  }
  set {
    name  = "initContainers[1].volumeMounts[0].mountPath"
    value = "/target"
  }
  set {
    name  = "initContainers[1].volumeMounts[0].name"
    value = "plugins"
  }
  set {
    name  = "initContainers[1].volumeMounts[0].name"
    value = "plugins"
  }
  
}

Now its shows this error:
Validation errors:  provider aws has more than one possible volume snapshot location, and none were specified explicitly or as a default.

![Screen Shot 2022-12-19 at 10 31 39 AM](https://user-images.githubusercontent.com/111310259/208495245-3b03d7d5-f63b-4810-a424-a29fc669d154.png)

Please need your input.

**Comment by qiuming-best** [comment]
@hemanthjakkoju
1.  I'm not sure about the programming language you use above. it nested helm charts and missing some value settings.

2. you are using the CSI plugin to do the backup. First needs to check whether it's supported by the CSI snapshot.
`failed to get volumesnapshotclass for storageclass efs-sc: error listing volumesnapshot classes: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)`. For the CSI snapshot, it needs to create volumesnapshotclass for storageclass, the error shows the `volumesnapshotclass` is not created. you should check the reason.
