### ISSUE TITLE
velero pod not running after Upgrade to velero 1.10.0 using helm chart

### ISSUE THREAD

**Issue by chnaresh26** [vmware-tanzu/velero#5721]
Hi, I have updated velero from 1.9.0 to 1.10.0. After which the pod in eks cluster is not running and throwing below error. 

An error occurred: [custom resource BackupRepository not found in Velero API group velero.io/v1, Velero custom resources not found - apply **examples/common/00-prereqs.yaml** to update the custom resource definitions]

Unable to find the above file which is mentioned in the the error.

please suggest on how to resolve the issue.

**Comment by blackpiglet** [comment]
Please follow this intruction to uprade Velero from v1.9 to v1.10.
https://velero.io/docs/v1.10/upgrade-to-1.10/

**Comment by chnaresh26** [comment]
Thank you blackpiglet. Its working now.
