### ISSUE TITLE
Enable more linters

### ISSUE THREAD

**Issue by chaunceyjiang** [vmware-tanzu/velero#5726]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

![image](https://user-images.githubusercontent.com/17962021/210059409-02c55a1a-db96-4cfe-a235-c21187c7a5fa.png)

When I run `golangci-lint run` locally, there are a lot of errors, I suggest to enable more linters

**What did you expect to happen:**

 I suggest to enable more linters

**The following information will help us better understand what's going on**:

https://github.com/vmware-tanzu/velero/blob/main/Makefile#L100

E.g. These are non-standard usages.
https://github.com/vmware-tanzu/velero/blob/main/pkg/cmd/server/server.go#L46-L62

import order
1. std package
2. third_party package
3. velero package

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  master
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Could you share what linters you have enabled for your environment?
I think it's reasonable to fix more lint issues, as long as there is no big impact on the code.

**Comment by chaunceyjiang** [comment]
> Could you share what linters you have enabled for your environment?

https://github.com/kubernetes-sigs/cluster-api/blob/main/.golangci.yml#L12-L57

@blackpiglet

**Comment by blackpiglet** [comment]
I think the linter issues reported in the image are raised by `staticcheck`, and this linter is not enabled in Velero yet.

**Comment by reasonerjt** [comment]
Due to the limited time and resources we have, I don't think we have to fix all the issues.

@blackpiglet what about enable `staticcheck` but use the `inclusive list` approach so we don't have too fix ALL the issues it reports in v1.11?

**Comment by chaunceyjiang** [comment]
> Due to the limited time and resources we have, I don't think we have to fix all the issues.

I suggest you can create some issues and set them to `good first issue` to encourage more contributors to participate.
@reasonerjt 


For example create a good first issue for enable `misspell` linter.

**Comment by blackpiglet** [comment]
@chaunceyjiang 
Thanks. I agree. I will create a new issue to trace enabling specific linters.
`misspell` is already enabled yet.

**Comment by chaunceyjiang** [comment]
> misspell is already enabled yet.

Ok, can you remind me where to enable `misspell`?

**Comment by blackpiglet** [comment]
https://github.com/vmware-tanzu/velero/blob/main/golangci.yaml#L226-L232
Velero golangci.yaml has a section to configure `missspell` linter.

**Comment by blackpiglet** [comment]
Close this issue. The linters task is traced in https://github.com/vmware-tanzu/velero/issues/6023
