### ISSUE TITLE
Facing issue while restoring completed backups

### ISSUE THREAD

**Issue by KoushikRhk** [vmware-tanzu/velero#5732]
Hello Everyone!!
configured backups for a kubernetes environment using velero, Backup status is showing as completed. And facing issue while restoring the completed backups

On restoring, all confiigmaps ,pods and namespaces are restored in new environment as expected
Few pods are up and started running. Few are still in init :0/1 state
<img width="636" alt="image" src="https://user-images.githubusercontent.com/121866619/210351506-b8ba85d1-c3a7-4fa4-b1de-75fc4c7d8e32.png">

On doing **kubectl describe pod podname** for the pods , which were in init:0/1 state ,showing the following
<img width="845" alt="image" src="https://user-images.githubusercontent.com/121866619/210351921-de3ed015-0feb-4d98-8c45-919b0e1503bf.png">
I have used the **kubectl logs minio-0 -c restic-wait** I have recieved the following as output
Not found: /restores/minio-data/.velero/8a14a380-0c38-4149-968c-26275aa7721a
Not found: /restores/minio-data/.velero/8a14a380-0c38-4149-968c-26275aa7721a
Not found: /restores/minio-data/.velero/8a14a380-0c38-4149-968c-26275aa7721a
Not found: /restores/minio-data/.velero/8a14a380-0c38-4149-968c-26275aa7721a

Expecting, someone will help us to make those pods to running state
Anyone Please help me regarding the issue mentioned, It will be so helpful for us.

Attaching the support bundle by using '**velero debug  --backup <backupname> --restore <restorename>'** to generate the support bundle , Please review

[backup_bffbank-20221206111139.log](https://github.com/vmware-tanzu/velero/files/10336543/backup_bffbank-20221206111139.log)
[backup_describe_bffbank-20221206111139.txt](https://github.com/vmware-tanzu/velero/files/10336544/backup_describe_bffbank-20221206111139.txt)
[restore_bffbank-20221206111139-20230102140837.log](https://github.com/vmware-tanzu/velero/files/10336545/restore_bffbank-20221206111139-20230102140837.log)
[restore_describe_bffbank-20221206111139-20230102140837.txt](https://github.com/vmware-tanzu/velero/files/10336548/restore_describe_bffbank-20221206111139-20230102140837.txt)
[version.txt](https://github.com/vmware-tanzu/velero/files/10336549/version.txt)

**Environment:**
 velero version
Client:
        Version: v1.9.5
        Git commit: 2b5281f38aad2527f95b55644b20fb169a6702a7
Server:
        Version: v1.9.5

kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7-gke.900", GitCommit:"e35c4457f66187eff006dda6d2c0fe12144ef2ec", GitTreeState:"clean", BuildDate:"2022-10-26T09:25:34Z", GoVersion:"go1.18.7b7", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tuoeg** [comment]
do you use static persistent volume?

**Comment by allenxu404** [comment]
Looks like you're using velero/restic to backup PVs. Could you provide me with more information about PV and storageclass? 
Please note that velero/restic doesn’t support statically provisioned PV in restore process.

**Comment by KoushikRhk** [comment]
Hi @tuoeg & @allenxu404 Thanks for response!!
Please check the below attached details,
These are the pv and storage class yml files
[storageclassconf.txt](https://github.com/vmware-tanzu/velero/files/10357781/storageclassconf.txt)
[pvconf.txt](https://github.com/vmware-tanzu/velero/files/10357783/pvconf.txt)

I have been getting few errors in logs **velero restore logs restorename**. 
errors in restore logs are attached here
[errorsinrestorelogs.txt](https://github.com/vmware-tanzu/velero/files/10357811/errorsinrestorelogs.txt)

Attaching complete logs of restore below
[jansixthrestorelogs.txt](https://github.com/vmware-tanzu/velero/files/10357804/jansixthrestorelogs.txt)

And in Podvolumerestores, Its showing totalbytes and bytesdone as equal ,but status if showing as failed.
<img width="943" alt="podvolumerestores" src="https://user-images.githubusercontent.com/121866619/210943607-c0948cad-96fe-42ba-be02-1ecd6f92d273.png">

Kindly, Please review and help us regarding the restoring issue of backup.It will be very helpful for us!!!
Thank you!!!

**Comment by qiuming-best** [comment]
@KoushikRhk, From the error  reported by Velero restore, Velero failed with restoring symbol link files, here is one [issue](https://github.com/restic/restic/issues/2578) with Restic restore folder with symbol link, for the symbol link error we need Restic upstream release new version to fix it.

**Comment by qiuming-best** [comment]
Restic restore folder with the symbol link is fixed in Restic v0.15.0, and our Velero has already bumped up to  v0.15.0.

**Comment by reasonerjt** [comment]
Thanks @qiuming-best, resolving this one as fixed.
