### ISSUE TITLE
Resolve staticcheck linter reported issues

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#5734]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
#5726 wants to enable more linters for Velero to comply with [cluster-api's standard](https://github.com/kubernetes-sigs/cluster-api/blob/main/.golangci.yml#L12-L57).
There is a significant gap between the cluster-api and Velero GolangCI enabled linters.
By far, `staticcheck` linter reports most issues, so try to resolve those first.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
This is the result of `staticcheck` linter scan result of Velero repository. There are 266 issues.
It looks like there is no whitelist setting available for `staticcheck` linter. `dot_import_whitelist` looks related, but it's used for  dot-importing some external testing packages. It cannot make linter only to choose specific path of Velero code.

We need to resolve most of the reported issues to enable the `staticcheck` linter, because `staticcheck` makes the golangci check halt until timeout on my developing environment.

[staticcheck_result_formatted.json](https://gist.github.com/blackpiglet/1a25e41c7618d95a97e1f98060d25023#file-staticcheck_result_formatted-json)

[staticcheck_result_raw.json](https://gist.github.com/blackpiglet/1a25e41c7618d95a97e1f98060d25023#file-staticcheck_result_raw-json)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
First install staticcheck linter binary, then run the linter to get the scan result.

``` bash
# install staticcheck binary
go install honnef.co/go/tools/cmd/staticcheck@2022.1

# run staticcheck linter
cd ~/go/src/github.com/vmware-tanzu/velero
staticcheck -f json ./... > staticcheck_result_raw.json
```

The result is ouputed as multiple JSONs. Need to integrate them into a JSON array to better display.

``` python
import json

results = []
for line in open('staticcheck_result_raw.json', 'r'):
    results.append(json.loads(line))

out_file = open("staticcheck_result_formatted.json", "w")
  
json.dump(dict1, out_file, indent = 2)
  
out_file.close()
```

Formatted JSON file is a bit long. Can split the file into several shards.
```
split -l 1000 staticcheck_result_formatted.json split_
```

**Comment by reasonerjt** [comment]
Let's target v1.11 to enable the check.  However, there may be too many errors to fix, we'll skip the check for some of the packages and fix the issues iteratively in future patch releases.
