### ISSUE TITLE
The configuration.backupStorageLocation.caCert does not work when perform FS backup by Kopia

### ISSUE THREAD

**Issue by iamjackhu** [vmware-tanzu/velero#5742]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Using kopia to backup the kuberenetes with caCert, the metadata's backup works as expect, but the volumn's backup has the certificate issue. 

**What did you expect to happen:**
The volumn's backup can use the caCert to backup the volumn like as metadata.

**The following information will help us better understand what's going on**:
time="2023-01-06T01:18:32Z" level=error msg="Error backing up item" backup=velero-d70302e4-9d68-4adb-ac1e-4d8c7a074186/manual-20230106t011746653z error="failed to wait BackupRepository: backup repository is not ready: error to init backup repo: error to connect to storage: unable to determine if bucket \"tkg-backup6\" exists: Head \"https://ose5.eng.vmware.com/tkg-backup6/\": x509: certificate signed by unknown authority" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/backup_repo_op.go:83" error.function=github.com/vmware-tanzu/velero/pkg/repository.GetBackupRepository logSource="pkg/backup/backup.go:425" name=nginx-deployment-5b47dbff44-8jgj9
time="2023-01-06T01:30:14Z" level=error msg="Error updating download request" controller=download-request downloadRequest=velero-d70302e4-9d68-4adb-ac1e-4d8c7a074186/manual-20230106t011746653z-cf98c326-d525-412b-834f-08875da9c8ac error="downloadrequests.velero.io \"manual-20230106t011746653z-cf98c326-d525-412b-834f-08875da9c8ac\" not found" logSource="pkg/controller/download_request_controller.go:89"

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
Velero: v1.10.0
k8s version: v1.22.9+vmware.1 
- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
This is a known limitation, see #5123

**Comment by Lyndon-Li** [comment]
Since this is a known limitation, I will close this issue.
For a workaround, you can skip the TLS security check by specifying `insecureSkipTLSVerify` in BSL.Spec.Config
