### ISSUE TITLE
Namespace-only backup skips associated Persistent Volumes

### ISSUE THREAD

**Issue by kreeuwijk** [vmware-tanzu/velero#5745]
**What steps did you take and what happened:**
When a backup is created for a namespace with the options `Include Cluster Resources:  false` and `Snapshot Volumes:  true`, Velero skips backup of the persistent volumes associated to PVCs in this namespace, because these are cluster-scoped resources. This can be confirmed in the logs of the backup:

```
time="2023-01-03T15:33:46Z" level=info msg="Retrieved 1 items" backup=cluster-63a46a1d9346af85ed3f578a/data-migration-2 group=v1 logSource="pkg/backup/item_collector.go:334" namespace=jenkins resource=persistentvolumeclaims
time="2023-01-03T15:33:46Z" level=info msg="Getting items for resource" backup=cluster-63a46a1d9346af85ed3f578a/data-migration-2 group=v1 logSource="pkg/backup/item_collector.go:170" resource=persistentvolumes
time="2023-01-03T15:33:46Z" level=info msg="Skipping resource because it's cluster-scoped" backup=cluster-63a46a1d9346af85ed3f578a/data-migration-2 group=v1 logSource="pkg/backup/item_collector.go:201" resource=persistentvolumes
```
As you can see the PVC is backed up, but PVs are skipped since they are cluster-wide.

As a result, when the backup is restored onto another cluster, all PVCs stay in the `Pending` state forever, since their associated PVs are not restored.

Conversely, this also means that backups with `Include Cluster Resources:  true` set, will back up *all* PVs, even for PVCs in namespaces that are not selected for the backup. Essentially there is no association done by Velero between PVCs and PVs.

**What did you expect to happen:**
I expect Velero to treat PVs as namespaced items, using PVCs to determine the namespace they belong to. Backing up a namespace with `Include Cluster Resources:  false` should still result in PVs associated to PVCs in that namespace to be backed up. The same goes for the restore process.

**Anything else you would like to add:**
Due to the issue above, it is very difficult to create "clean" backups of individual namespaces, omitting cluster-specific configuration that is present in cluster-wide resources. Since PVs are currently only included if cluster-wide resources are backed up as well. it makes restores into another cluster needlessly more complicated due to the restore of undesired cluster-wide resources like mutating admission webhooks. This causes the user to have to limit the types of resources that can be restored from the backup, just to prevent breaking parts of the target cluster.

If Velero was able to include PVs associated to PVCs it selected for backup, it would become much more appealing to use backups with `Include Cluster Resources:  false` configured by default, as those are much safer to restore to a different cluster using only default Velero restore options.

**Environment:**

- Velero version (use `velero version`): 1.9.0
- Velero features (use `velero client config get features`):  <NOT SET>
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4"
- Kubernetes installer & version: kubeadm 1.23.4
- Cloud provider or hardware configuration: Canonical MaaS
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04 LTS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment]
What you want is the default setting for includeClusterResources. If you don't specify it, the value is `nil` and only relevant PVs are included. True includes all PVs, and false includes none.
