### ISSUE TITLE
CSI plugin should work with multiple VolumeSnapshotClasses

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#5750]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
By far, the Velero CSI plugin only works with one VolumeSnapshotClass, and the VolumeSnapshotClass is chosen by label `velero.io/csi-volumesnapshot-class`.
Let's work out a way to let the CSI plugin support multiple VolumeSnapshotClasses.
This issue #5737 give a using scenario of this requirement.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by anshulahuja98** [comment]
Hi @blackpiglet
I am interested in taking this up. 
If no one is working on the proposal currently, can I pick it up?

**Comment by blackpiglet** [comment]
@anshulahuja98 
Sure. Thanks for the contribution.

**Comment by anshulahuja98** [comment]
@reasonerjt as requested in last community meeting, can we please add this design proposal to 1.11 milestone.

**Comment by reasonerjt** [comment]
I'll double-check #5774 and if this is merged this will be fixed in v1.12
