### ISSUE TITLE
Improve documentation around backups failing due to OOM

### ISSUE THREAD

**Issue by Guent4** [vmware-tanzu/velero#5753]
**Describe the problem/challenge you have**
I was experiencing problems with trying to back up a large cluster (~20K pods).
- `velero backup describe` was just telling me that it failed but provided no info
- `velero backup logs` just retuned `An error occurred: file not found`
- Looking through the `velero` pod logs, the only thing that was of real interest (after diffing with the logs of a pod that did succeed in backups) was:
    ```
    time="2023-01-09T19:46:16Z" level=warning msg="get a backup with status \"InProgress\" during the server starting, mark it as \"Failed\"" backup=cron-20230109194736 logSource="pkg/cmd/server/server.go:996"
    ```
- Noticed that the container was restarting.  Looked at the logs of the failed (aka previous) container and noticed that the last two lines were:
    ```
    time="2023-01-09T20:45:00Z" level=info msg="Getting items for resource" backup=velero/cron-20230109204644 group=v1 logSource="pkg/backup/item_collector.go:170" resource=pods
    time="2023-01-09T20:45:00Z" level=info msg="Listing items" backup=velero/cron-20230109204644 group=v1 logSource="pkg/backup/item_collector.go:306" namespace= resource=pods
    ```

After identifying that this was likely a OOM issue, fixing it was easy: passing in values for `velero-pod-mem-request` and `velero-pod-mem-limit` when running `velero install` (I was using the default values before and bumping the mem request to 1Gi and limit to 4Gi allowed the backup to succeed.  However, getting to the point where I was sure that OOM was the issue was the difficulty.

**Describe the solution you'd like**
I think it would be nice to have somewhere in the docs some recommended pod specs based on different cluster sizing.

**Anything else you would like to add:**
Thanks for making a great product!  I've enjoyed using it so far :)

**Environment:**

- Velero version (use `velero version`):
    ```
    > velero version
    Client:
            Version: v1.10.0
            Git commit: 367f563072659f0bcd809bc33507fd75cd722344
    Server:
            Version: v1.10.0
    ```
- Kubernetes version (use `kubectl version`):
    ```
    > kubectl version
    Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", 
    GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", 
    GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12-gke.100", 
    GitCommit:"fd16f64da04c784b85909576a3f7abf4ed49b949", GitTreeState:"clean", BuildDate:"2022-09-22T09:23:33Z", 
    GoVersion:"go1.17.13b7", Compiler:"gc", Platform:"linux/amd64"}
    ```
- Kubernetes installer & version:
- Cloud provider or hardware configuration: See above for GKE version
- OS (e.g. from `/etc/os-release`): GKE COS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by alfredodeluca** [comment]
👍

**Comment by alfredodeluca** [comment]
Had the same issue a few weeks ago. Thanks for that

**Comment by qiuming-best** [comment]
Indeed, We have done some [backup performance tests](https://velero.io/docs/v1.10/performance-guidance/) both for Kopia and Restic.

the test results will vary from different infrastructures, and our tests are limited and couldn’t cover a variety of data scenarios, the test results and analysis are for reference only

**Comment by reasonerjt** [comment]
The current performance guide heavily focuses on the performance of filesystem-level B/R (via restic/kopia)

We should extend the scope to more scenarios, like perf guide and resource consumption on k8s resource B/R.

**Comment by jeremymcgee73** [comment]
I ran into the same issue, thanks for posting this!
