### ISSUE TITLE
Velero deployment 0/1 ready. The client version does not match the server version. Please update server

### ISSUE THREAD

**Issue by ArnoldVanN** [vmware-tanzu/velero#5763]
Hi guys, I followed the exact steps in https://github.com/vmware-tanzu/velero-plugin-for-gcp#setup
The output of `velero version` shows `the client version does not match the server version. Please update server`
Even though they should be compatible judging by the documentation. Client version is 1.10.0 and server plugin image is velero/velero-plugin-for-gcp:v1.6.0.
I'm getting `error: timed out waiting for the condition` on `kubectl logs deploy/velero -n velero`.
Theres no pods created yet either so no logs to be checked.

Any help would be appreciated, thanks!

**Comment by qiuming-best** [comment]
@ArnoldVanN your velero deployment is not in ready status, you should check the error of Velero pod first.

**Comment by ArnoldVanN** [comment]
@qiuming-best there are no pods created by Velero.

**Comment by qiuming-best** [comment]
@ArnoldVanN you could execute this command `kubectl describe deploy velero -n  velero`, and show the output

**Comment by ArnoldVanN** [comment]
Hi, i tried this command before too but wasn't able to get anything useful from it, hopefully you see something I didn't. Since my last comment I've tried completely reinstalling velero by deleting all resources it created and running the installer again, but got the same error.
`Name:                   velero
Namespace:              velero
CreationTimestamp:      Fri, 13 Jan 2023 10:46:00 +0100
Labels:                 component=velero
Annotations:            <none>
Selector:               deploy=velero
Replicas:               1 desired | 0 updated | 0 total | 0 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           component=velero
                    deploy=velero
  Annotations:      prometheus.io/path: /metrics
                    prometheus.io/port: 8085
                    prometheus.io/scrape: true
  Service Account:  velero
  Init Containers:
   velero-velero-plugin-for-gcp:
    Image:        velero/velero-plugin-for-gcp:v1.6.0
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:
      /target from plugins (rw)
  Containers:
   velero:
    Image:      velero/velero:v1.10.0
    Port:       8085/TCP
    Host Port:  0/TCP
    Command:
      /velero
    Args:
      server
      --features=
      --uploader-type=restic
    Limits:
      cpu:     1
      memory:  512Mi
    Requests:
      cpu:     500m
      memory:  128Mi
    Environment:
      VELERO_SCRATCH_DIR:              /scratch
      VELERO_NAMESPACE:                 (v1:metadata.namespace)
      LD_LIBRARY_PATH:                 /plugins
      GOOGLE_APPLICATION_CREDENTIALS:  /credentials/cloud
      AWS_SHARED_CREDENTIALS_FILE:     /credentials/cloud
      AZURE_CREDENTIALS_FILE:          /credentials/cloud
      ALIBABA_CLOUD_CREDENTIALS_FILE:  /credentials/cloud
    Mounts:
      /credentials from cloud-credentials (rw)
      /plugins from plugins (rw)
      /scratch from scratch (rw)
  Volumes:
   plugins:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
   scratch:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
   cloud-credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cloud-credentials
    Optional:    false
Events:          <none>`

**Comment by ArnoldVanN** [comment]
I just deleted the GCP bucket that I tried to use to install Velero last time, and recreated it, this time in the same region as my cluster. Not sure if that's what made the difference but now after running the installer again, Velero seems to be installed correctly.
