### ISSUE TITLE
SnapshotCreationPerVolumeRateExceeded: The maximum per volume CreateSnapshot request rate has been exceeded. Use an increasing or variable sleep interval between requests.

### ISSUE THREAD

**Issue by kart2** [vmware-tanzu/velero#5776]
**What steps did you take and what happened:**
Running velero backup every 15 mins

**What did you expect to happen:**
A succesful backup

**The following information will help us better understand what's going on**:

_If you are using earlier versions:_   1.5.2
time="2023-01-17T17:00:59Z" level=error msg="Error backing up item" backup=velero/velero-prod-4-20230115110021 error="error taking snapshot of volume: rpc error: code = Unknown desc = SnapshotCreationPerVolumeRateExceeded: The maximum per volume CreateSnapshot request rate has been exceeded. Use an increasing or variable sleep interval between requests.\n\tstatus code: 400, request id: c8ddf94c-3567-4d23-b14c-2144ad81f5fd" logSource="pkg/backup/backup.go:455" 

**Environment:**

- Velero version (use `velero version`): 1.5.2
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.20
- Kubernetes installer & version:
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`):

**Comment by kart2** [comment]
Is there a way to increase sleep interval between snapshot requests?

**Comment by Lyndon-Li** [comment]
Could you describe your scenarios? Is this limit reached by one backup or multiple backups?
If the error happens for even one backup, does it mean there are many PVs in the same namespace? If so, there is no way to define the interval from Velero for now.
If the errors happens due to many successive backups, you can increase the interval of the backup/schedule.

**Comment by Lyndon-Li** [comment]
Moreover, Velero 1.5.2 is a very old version, could you try it with the latest version? @kart2

**Comment by Lyndon-Li** [comment]
I am closing this issue for now since we haven't got the required info. Feel free to reopen it.
