### ISSUE TITLE
Error: unknown flag: --uploader-type 

### ISSUE THREAD

**Issue by sawansharma005** [vmware-tanzu/velero#5782]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
While trying to deploy velero chart 3.0.0 on aks 1.25 cluster we are getting Error: unknown flag: --uploader-type.

**What did you expect to happen:**

Pod should come up in running state.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- ` kubectl logs pod/velero-686d56f4c5-bx8f5 -n velero
Defaulted container "velero" out of: velero, create-velero-credentials (init), velero-plugin-for-microsoft-azure (init)
Error: unknown flag: --uploader-type
Usage:
  velero server [flags]

Flags:`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Velero manifest
`apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    component: velero
    helm.sh/chart: velero-3.1.0
  name: velero
  namespace: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: velero
      app.kubernetes.io/name: velero
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
      labels:
        aadpodidbinding: kaas-identity
        app.kubernetes.io/instance: velero
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: velero
        helm.sh/chart: velero-3.1.0
        name: velero
    spec:
      containers:
      - args:
        - server
        - --uploader-type=restic
        command:
        - /velero`

**Environment:**

- Velero version (use `velero version`): v1.9.5
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.25.2
- Kubernetes installer & version: NA
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): Linux

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"

**Comment by albrookesplowman** [comment]
We are also seeing this error.... Is there a workaround or a solution?

**Comment by qiuming-best** [comment]
@albrookesplowman your Velero version is `v1.9.5` which is not supported by Velero chart `3.0.0`.

If you want your helm chart installation still work, you have two options:
- using helm chart version v3.x.x with the Velero version newer than v1.9.x, which would be v1.10.x
- using Velero version v1.10.x with Velero helm chart version less than v3.x.x, which would be v2.x.x

**Comment by albrookesplowman** [comment]
I did try v1.10 with the v3.x.x helm chart but I got the same error.  I have solved the problem by going back to v1.9.x with the last  v2.x.x helm chart.  At some point in the future I will give the v3.x.x & v1.10.x combination another try

**Comment by qiuming-best** [comment]
@albrookesplowman @sawansharma005 could you show me the output of command `kubectl get deploy -n velero -oyaml`

**Comment by satyajeetjoshi1989** [comment]
replying on behalf of sawansharma005
------
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
    creationTimestamp: ""
    generation: 2
    labels:
 
    name: velero
    namespace: velero
    resourceVersion: "3938555"
    uid: 4250503e-4b5e-444d-8280-7b6f62d173b3
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: velero
        app.kubernetes.io/name: velero
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8085"
          prometheus.io/scrape: "true"
        creationTimestamp: null
        labels:
          
      spec:
        containers:
        - args:
          - server
          - --uploader-type=restic
          - --restic-timeout=240m
          command:
          - /velero
          env:
          - name: VELERO_SCRATCH_DIR
            value: /scratch
          - name: VELERO_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: LD_LIBRARY_PATH
            value: /plugins
          - name: AZURE_CREDENTIALS_FILE
            value: /credentials/cloud
          image: velero/velero:v1.9.5
          imagePullPolicy: IfNotPresent
          name: velero
          ports:
          - containerPort: 8085
            name: http-monitoring
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /plugins
            name: plugins
          - mountPath: /scratch
            name: scratch
          - mountPath: /credentials
            name: velero-credenitals-store
        dnsPolicy: ClusterFirst
        initContainers:
        - command:
          - sh
          - -c
          - /tmp/load-credentials.sh;
          image: alpine:3.16.0
          imagePullPolicy: IfNotPresent
          name: 
          resources: {}
          terminationMessagePath: 
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: 
            name: velero-credentials
          - mountPath: 
            name: 
          - mountPath: 
            name: velero-app-configs
          - mountPath:
            name: velero-credenitals-store
        - image: velero/velero-plugin-for-microsoft-azure:v1.5.0
          imagePullPolicy: IfNotPresent
          name: velero-plugin-for-microsoft-azure
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /target
            name: plugins
        priorityClassName: system-cluster-critical
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: velero-server
        serviceAccountName: velero-server
        terminationGracePeriodSeconds: 3600
        volumes:
        - emptyDir: {}
          name: plugins
        - emptyDir: {}
          name: scratch
        - emptyDir:
            medium: Memory
          name: velero-credenitals-store
        - csi:
            driver: ****.****.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: velero-credentials
          name: velero-credentials
        - configMap:
            defaultMode: 511
            items:
            - key: load-credentials
              path: load-credentials.sh
            name: velero-credentials-scripts
          name: velero-credentials-scripts
        - configMap:
            defaultMode: 420
            items:
            - key: AZURE_SUBSCRIPTION_ID
              path: AZURE_SUBSCRIPTION_ID
            - key: AZURE_TENANT_ID
              path: AZURE_TENANT_ID
            - key: AZURE_RESOURCE_GROUP
              path: AZURE_RESOURCE_GROUP
            name: velero-app-configs
          name: velero-app-configs
  status:
    
kind: List
metadata:

**Comment by OceanChen2012** [comment]
> @albrookesplowman @sawansharma005 could you show me the output of command `kubectl get deploy -n velero -oyaml`

@qiuming-best 我遇到了同样的问题，我的k8s版本是v1.22.12，velero版本是v1.5.4，velero-plugin-for-aws版本是v1.1.0;运行命令：kubectl edit deployment velero -n velero，结果如下：
[root@localhost velero-v1.5.4-linux-amd64]# kubectl edit deployment velero -n velero

      serviceAccountName: velero
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: plugins
      - emptyDir: {}
        name: scratch
      - name: cloud-credentials
        secret:
          defaultMode: 420
          secretName: cloud-credentials
status:
  conditions:
  - lastTransitionTime: "2023-06-06T03:36:06Z"
    lastUpdateTime: "2023-06-06T03:36:06Z"
    message: ReplicaSet "velero-6776458b4d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-06-06T05:02:50Z"
    lastUpdateTime: "2023-06-06T05:02:50Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1

**Comment by OceanChen2012** [comment]
@qiuming-best ，我在k8s中安装velero的命令如下：velero install \
 --provider aws \
--image velero/velero:v1.5.4 \
 --plugins velero/velero-plugin-for-aws:v1.1.0 \
 --bucket velero \
 --secret-file ./credentials-velero \
 --use-volume-snapshots=false \
 --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://minio.velero.svc:9000

**Comment by rajamecs** [comment]
Any resolution on this, I am using latest chart 4.0.2 with v1.11.0 sitting on EKS 1.24 facing he same issue Error: unknown flag: --uploader-type

**Comment by rajamecs** [comment]
My bad looking at the deployment yaml, the chart version still says v1.9.2 changed the same to 1.11.0 and gone past that error...
Init Containers:
   velero-plugin-for-csi:
    Image:        velero/velero-plugin-for-csi:v0.5.0
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:
      /target from plugins (rw)
   velero-plugin-for-aws:
    Image:        velero/velero-plugin-for-aws:v1.7.0
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:
      /target from plugins (rw)
  Containers:
   velero:
    Image:      velero/velero:v1.9.2
    Port:       8085/TCP
    Host Port:  0/TCP
