### ISSUE TITLE
resource label selector not work for cluster scope resources.

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#5787]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
When creating a backup, the user can use`LabelSelector/OrLabelSelectors` to filter resources that should be included, but that rule only works for the namespace scope resource, and not for the cluster scope resource, for example, k8s Deployment resource can be selected by the label selector, but StorageClass cannot.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
`LabelSelector/OrLabelSelectors` should also work for cluster scope resources.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by nunojusto** [comment]
This problem happens also for restores when filtering resources with LabelSelector/OrLabelSelectors.
Should I create a new issue or we can use this?

**Comment by sseago** [comment]
@nunojusto I think we can probably use this issue to track the fix for both backup and restore. If the fix ends up getting split into two PRs, then it might make sense to create a second issue for restore, but I suspect that it may be easier to fix both together.

**Comment by blackpiglet** [comment]
https://github.com/vmware-tanzu/velero/blob/main/pkg/backup/item_collector.go#L297-L313
https://github.com/vmware-tanzu/velero/blob/main/pkg/restore/restore.go#L937-L953

@nunojusto 
I think I made some misunderstanding of how Velero uses the label selector with cluster-scoped resources.
According to the code posted up here, I think the cluster-scoped resources can be filtered by the `--selector` parameter. My previous misunderstanding was caused by the cluster-scoped resources are filtered out by other filters setting.

**Comment by reasonerjt** [comment]
Moving this out of v1.12 since this seems a non-issue.
