### ISSUE TITLE
Missing support for arm64 docker images in newer builds. 

### ISSUE THREAD

**Issue by alekc** [vmware-tanzu/velero#5793]
Judging from the docker hub page https://hub.docker.com/r/velero/velero/tags?page=1&name=1.9 it looks like velero images (release ones, so 1.9.x non dev builds) have dropped support for arm64 builds starting from 1.9.4 onwards. 

Confusingly -dev and -rc builds have both amd and arm64 support. 

Is it a wanted behaviour or is there a misconfiguration on some release pipelines?

**Comment by ywk253100** [comment]
The images have been fixed. I'm closing this issue.
