### ISSUE TITLE
Velero : Restore backup failed on another Kubernetes Cluster

### ISSUE THREAD

**Issue by piedai** [vmware-tanzu/velero#5794]
I'm trying to backup a Kubernetes environment with Velero tool. Velero is setuped for using the snapshotvolume from the Dell CSI Unity Array and export it to external block storage Wasabi. The restoration works well on the same cluster after deletion of the content.

I'm encountering a problem when i try to restore the same backup on another cluster (with the same model of Array but another one and another version of Kubernetes Cluster). the issue reside in the snapshot restoration in destination of a PVC.

I got the below error :
**Message: Failed to check and update snapshot content: failed to list snapshot for content velero-velero-data-mysql-0-7275l-qlsnr: "rpc error: code = InvalidArgument desc = Unity client not found for array ckm00203200142"**

Environment :
Kubernetes source cluster : v1.22.5
Kubernetes destination cluster : v1.24.6
Dell CSI Driver : 2.4.0
OS Version : Ubuntu 20.04
Velero :
Features : EnableCSI
Version : v1.10.0

After restoration, the PVC associated of my environment stay in pending :
➜ ~ k get pvc
NAME STATUS VOLUME CAPACITY ACCESS MODES STORAGECLASS AGE
data-mysql-0 Pending unity-block 16h

Output of the new PVC created after the restoration :
➜ ~ k get pvc data-mysql-0 -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
annotations:
backup.velero.io/must-include-additional-items: "true"
velero.io/backup-name: test-restoration
velero.io/volume-snapshot-name: velero-data-mysql-0-7275l
volume.beta.kubernetes.io/storage-provisioner: csi-unity.dellemc.com
volume.kubernetes.io/storage-provisioner: csi-unity.dellemc.com
creationTimestamp: "2023-01-24T17:18:22Z"
finalizers:

    kubernetes.io/pvc-protection
    labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
    backup.velero.io/must-include-additional-items: "true"
    velero.io/backup-name: test-restoration
    velero.io/restore-name: test-restoration-20230124181810
    velero.io/volume-snapshot-name: velero-data-mysql-0-7275l
    name: data-mysql-0
    namespace: test-restoration
    resourceVersion: "14118971"
    uid: 7a7b0b85-497f-4a0a-be14-bb87f09a8a9e
    spec:
    accessModes:
    ReadWriteOnce
    dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: velero-data-mysql-0-7275l
    dataSourceRef:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: velero-data-mysql-0-7275l
    resources:
    requests:
    storage: 8Gi
    storageClassName: unity-block
    volumeMode: Filesystem
    status:
    phase: Pending

**The volumeSnapshot created from the backup is blocked in NOREADYTOUSE**
➜ ~ k get volumesnapshot 
NAME READYTOUSE SOURCEPVC SOURCESNAPSHOTCONTENT RESTORESIZE SNAPSHOTCLASS SNAPSHOTCONTENT CREATIONTIME AGE
velero-data-mysql-0-7275l **false** velero-velero-data-mysql-0-7275l-qlsnr csi-unity.dellemc.com velero-velero-data-mysql-0-7275l-qlsnr 16h

➜ ~ k describe volumesnapshot velero-data-mysql-0-7275l
Name: velero-data-mysql-0-7275l
Namespace: test-restoration
Labels: velero.io/backup-name=test-restoration
velero.io/restore-name=test-restoration-20230124181810
Annotations: backup.velero.io/must-include-additional-items: true
velero.io/csi-driver-name: csi-unity.dellemc.com
velero.io/csi-volumesnapshot-handle: csi-snap-8bc9db31d4-iSCSI-ckm00203200581-38655104580
velero.io/csi-vsc-deletion-policy: Retain
velero.io/vsi-volumesnapshot-restore-size: 8Gi
API Version: snapshot.storage.k8s.io/v1
Kind: VolumeSnapshot
Metadata:
Creation Timestamp: 2023-01-24T17:18:22Z
Finalizers:
snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
Generation: 1
Managed Fields:
API Version: snapshot.storage.k8s.io/v1
Fields Type: FieldsV1
fieldsV1:
f:metadata:
f:finalizers:
.:
v:"snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection":
Manager: Go-http-client
Operation: Update
Time: 2023-01-24T17:18:22Z
API Version: snapshot.storage.k8s.io/v1
Fields Type: FieldsV1
fieldsV1:
f:status:
.:
f:boundVolumeSnapshotContentName:
f:error:
.:
f:message:
f:time:
f:readyToUse:
Manager: Go-http-client
Operation: Update
Subresource: status
Time: 2023-01-24T17:18:22Z
API Version: snapshot.storage.k8s.io/v1
Fields Type: FieldsV1
fieldsV1:
f:metadata:
f:annotations:
.:
f:backup.velero.io/must-include-additional-items:
f:velero.io/csi-driver-name:
f:velero.io/csi-volumesnapshot-handle:
f:velero.io/csi-vsc-deletion-policy:
f:velero.io/vsi-volumesnapshot-restore-size:
f:labels:
.:
f:velero.io/backup-name:
f:velero.io/restore-name:
f:spec:
.:
f:source:
.:
f:volumeSnapshotContentName:
f:volumeSnapshotClassName:
Manager: velero-server
Operation: Update
Time: 2023-01-24T17:18:22Z
Resource Version: 14118969
UID: 81b08d26-c8ac-4a77-9f96-140c14ea8807
Spec:
Source:
Volume Snapshot Content Name: velero-velero-data-mysql-0-7275l-qlsnr
Volume Snapshot Class Name: csi-unity.dellemc.com
Status:
Bound Volume Snapshot Content Name: velero-velero-data-mysql-0-7275l-qlsnr
Error:
**Message: Failed to check and update snapshot content: failed to list snapshot for content velero-velero-data-mysql-0-7275l-qlsnr: "rpc error: code = InvalidArgument desc = Unity client not found for array ckm00203200581"**
Time: 2023-01-24T17:18:22Z
Ready To Use: false
Events:
Screenshots

➜  ~ velero backup describe test-restoration
I0125 13:03:46.453932 1110482 request.go:601] Waited for 1.123943519s due to client-side throttling, not priority and fairness, request: GET:https://172.16.103.193:6443/apis/logging-extensions.banzaicloud.io/v1alpha1?timeout=32s
Name:         test-restoration
Namespace:    infra-velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.22.5
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=22

Phase:  Completed

Errors:    0
Warnings:  1

Namespaces:
  Included:  test-restoration
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

CSISnapshotTimeout:  10m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2023-01-24 17:39:59 +0100 CET
Completed:  2023-01-24 17:40:12 +0100 CET

Expiration:  2023-02-23 17:39:59 +0100 CET

Total items to be backed up:  46
Items backed up:              46

Velero-Native Snapshots: <none included>

CSI Volume Snapshots:  1 included (specify --details for more information)

**Comment by ywk253100** [comment]
I'm unfamiliar with the `Dell CSI Unity Array`, but this issue is very likely related to it.
Could you show me the YAML file of the volume snapshot content?
