### ISSUE TITLE
Velero restic (defaultVolumesToFsBackup=true) reports error for emptyDir

### ISSUE THREAD

**Issue by slawekww** [vmware-tanzu/velero#5805]
**What steps did you take and what happened:**
Use defaultVolumesToFsBackup=true and node daemon to copy volumes content into Azure Storage Account.
  
Once K8S deployment uses **emptyDir**, Velero reports error like:

```
time="2023-01-30T13:43:00Z" level=error msg="Error backing up item" backup=velero/velero-default-20230130134011 error="pod volume backup failed: running backup, stderr=error running restic backup command restic backup --repo=azure:velero:/restic/sock-shop --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic . --tag=pod-uid=0077622c-a48b-4fac-87b0-27c1b88312d4 --tag=volume=workload-socket --tag=backup=velero-default-20230130134011 --tag=backup-uid=0f8befdf-5a40-451d-9568-8328b0a5347b --tag=ns=sock-shop --tag=pod=user-db-b8dfb847c-2dwmq --host=velero --json with error: exit status 1 stderr: Fatal: unable to save snapshot: snapshot is empty\n: error running restic backup command restic backup --repo=azure:velero:/restic/sock-shop --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic . --tag=pod-uid=0077622c-a48b-4fac-87b0-27c1b88312d4 --tag=volume=workload-socket --tag=backup=velero-default-20230130134011 --tag=backup-uid=0f8befdf-5a40-451d-9568-8328b0a5347b --tag=ns=sock-shop --tag=pod=user-db-b8dfb847c-2dwmq --host=velero --json with error: exit status 1 stderr: Fatal: unable to save snapshot: snapshot is empty\n" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:223" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:425" name=user-db-b8dfb847c-2dwmq
```

**What did you expect to happen:**
Backup emptyDir correctly or ignore emptyDir and do not report errors in backup.

**The following information will help us better understand what's going on**:
[bundle-2023-01-30-14-13-35.tar.gz](https://github.com/vmware-tanzu/velero/files/10536515/bundle-2023-01-30-14-13-35.tar.gz)

**Anything else you would like to add:**
N/A

**Environment:**

- Velero version (use `velero version`): 1.10.0
- Velero features (use `velero client config get features`): EnableCSI
- Kubernetes version (use `kubectl version`): v1.26.0
- Kubernetes installer & version: AKS 1.24.6
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): linux/ubuntu provided by AKS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
This is a known issue, and it's already fixed in main and on-going v1.10.1 release. It's fixed in #5711 
Please have a try with main release, or wait for the v1.10.1 release.

**Comment by slawekww** [comment]
Velero v1.10.1 is not released yet and helm chart is not using new version: https://github.com/vmware-tanzu/helm-charts
Let's wait for official release to re-test.

**Comment by blackpiglet** [comment]
@slawekww Hi, v1.10.1 is released. Please have a try.

**Comment by slawekww** [comment]
Confirmed. No errors are seen.
