### ISSUE TITLE
What's the expected behavior when backup command along with --default-volumes-to-fs-backup  and not having --snapshot-volumes

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#5823]
**Describe the problem/challenge you have**
As a precondition that Velero installation is not having both `--default-volumes-to-fs-backup` and `--snapshot-volumes`, what's the expected behavior when backup command along with --default-volumes-to-fs-backup and not having --snapshot-volumes? Per issue #5019, we consider both volumes fs backup and snapshot should be taken, but per issue [#349](https://github.com/vmware-tanzu/velero-plugin-for-vsphere/pull/349/files), snapshot will not be taken.

Other related issues #5019, #5762.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by danfengliu** [comment]
After some discussion, there're some headlines conclusion:
1. No matter if default-volumes-to-fs-backup was set, as long as fs volume backup was taken([opt-in approach](https://velero.io/docs/v1.9/restic/#using-opt-in-pod-volume-backup:~:text=YOUR_BACKUP_NAME%20%2Do%20yaml-,Using%20opt%2Din%20pod%20volume%20backup,-Velero%2C%20by%20default)), snapshot will not be taken on any condition.

**Comment by reasonerjt** [comment]
We'll just clarify the combination situation somewhere in the doc, I recall Pradeep used to open an issue and we have very well clarified it.

**Comment by reasonerjt** [comment]
@danfengliu 
Does the comments under issue https://github.com/vmware-tanzu/velero/issues/4151 answer the question ?

**Comment by danfengliu** [comment]
After discussion with other members, the behavior should be like this: Only 1 backup path will be chosen ,although without  param `--snapshot-volumes` means taking volume snapshot, but param` --default-volumes-to-fs-backup` has the high priority than other backup path.

I don't think the following statement is correct :
`Specify nothing when creating backup, it will be failed as reason 1` in https://github.com/vmware-tanzu/velero/issues/4151#issuecomment-1102183656

Anyway this issue is solved.
