### ISSUE TITLE
Unable to handle CSI driver: efs.csi.aws.com

### ISSUE THREAD

**Issue by llbvvb2001** [vmware-tanzu/velero#5826]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
velero backup create eks.encrypt.cluster
Results in Velero-Native Snapshots: 5 of 6 snapshots completed successfully
Phase: PartiallyFailed (run `velero backup logs test-encrypt-1.03022023` for more information)

**What did you expect to happen:**

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by draghuram** [comment]
Hi, Are you reporting about EFI snapshot not being created? If so, it is expected. EFS CSI driver doesn't implement snapshot interface. See:

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/pkg/driver/controller.go#L432

**Comment by draghuram** [comment]
You will need to use Restic/Kopia to backup EFS PVs.

**Comment by shubham-pampattiwar** [comment]
+1 @draghuram's answer

**Comment by llbvvb2001** [comment]
This is great. But can you advice how to ignore these from being backed up
at all. i.e. if its efs - it should not back up (thereby resulting in no
error).
Reason is , we will be using the EBS backup through AWS backup -
If we restore, we restore the EBS first and then restore the snapshot
through velero.
Do you see this to be valid scenario instead of using restic? and if so,
can you advice how to avoid any of these EFS from being included in backup?

Much appreciated

**Comment by draghuram** [comment]
If I understand you correctly, you would like to skip EFS backup through Velero and back it up using AWS backup? I guess that is certainly feasible though it is always better to backup all related data around same time. But I don't know if Velero as of today allows defining both snapshot and restic/Kopia backups using same Backup definition. 

To skip EFS volumes, you can try setting the label "velero.io/exclude-from-backup=true" as described here: https://velero.io/docs/v1.4/resource-filtering/. Note that there is a discussion going on in #5773 about excluding resources using some fields and that is applicable to your use case.
