### ISSUE TITLE
[CSI Plugin] Make VolumeSnapshotClass label optional

### ISSUE THREAD

**Issue by rnarenpujari** [vmware-tanzu/velero#5833]
**Describe the problem/challenge you have**
As a prerequisite to taking a backup with CSI snapshots, we are required to manually label a volume snapshot class with `velero.io/csi-volumesnapshot-class: "true"` for every every csi driver being used. This seems to be needed in order to disambiguate with class to use in case there are multiple for the same driver.

**Describe the solution you'd like**
It would be nice to have zero configuration since in the common scenario there is probably only a single snapshot class per driver. Even if there are multiple, we could have some arbitrary selection criteria (random, oldest resource, sorted on name, etc.) by default and then allow the user to use the label for more precise behavior.

**Anything else you would like to add:**
[Relevant code](https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/782b33ac2a4a3b984be7beaf40e569db3478c8c5/internal/util/util.go#L124)

**Environment:**

- Velero version (use `velero version`): 1.10.0
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by draghuram** [comment]
You may be interested in #5774. In general, it is better to pick volume snapshot class in a deterministic manner.

**Comment by reasonerjt** [comment]
Likely a dup of #5750

**Comment by reasonerjt** [comment]
This is not a dup b/c the requirement looks for zero-configuration, however, user will need to create a vsClass anyway.

Per discussion with @rnarenpujari , this is a good-to-have but not very high priority.

**Comment by reasonerjt** [comment]
It should be do-able that we fall back to the vsClass as long as there is  no ambiguity
