### ISSUE TITLE
Summarize volumes skipped during backup

### ISSUE THREAD

**Issue by rnarenpujari** [vmware-tanzu/velero#5834]
**Describe the problem/challenge you have**
Especially when performing a full cluster backup, it would be nice to get an idea of which volumes were not backed up in spite of the backup phase reporting Completed. Mainly for volume backup solutions like snapshots (csi and non csi) which only cover a subset of volumes on the cluster.

**Describe the solution you'd like**
May not be feasible to include this in the backup CR's status but would be nice to have in the backup describe (`--details`) output. 

**Anything else you would like to add:**
NA

**Environment:**

- Velero version (use `velero version`): 1.10.0
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
A volume could be skipped for various reasons:  doesn't meet certain selectors, "opt-out", skipped by CSI plugin if it's not provisioned by CSI drivers, etc.

@pradeepkchaturvedi  @rnarenpujari, I don't think we want to explicitly list the skipped volume in all cases, are there any very concrete scenarios we need to address ?

**Comment by pradeepkchaturvedi** [comment]
@reasonerjt We can list of volumes which gets skip based on resource filter or pod annotation. Logs should state all methods used for volume backup (restic/kopia, CSI volume snapshot, storage provider volume snapshot) and list of volume backed up by each method.

**Comment by reasonerjt** [comment]
We probably can introduce some tracker mechanism to move in/out the PV in the backup workflow, and this can be implemented in 2 phases:
1. Print the summary in the logs to get a summary what PVs are skipped.
2. Upload the information in the tracker to object store so we can show them in the output of backup describe.

**Comment by rnarenpujari** [comment]
Hi. Thanks for working on this! I noticed the tracker doesn't work well if SnapshotVolumes is false in the backup. 

For example a backup with no volume backup methods configured: DefaultVolumesToFsBackup as false (opt-in) and SnapshotVolumes as false.
Or DefaultVolumesToFsBackup as true but with the opt-out annotation and SnapshotVolumes as false (PVC gets tracked but then untracked here I think: https://github.com/vmware-tanzu/velero/blob/3e613862e6e40b18bd3044f8f86296840db0c067/pkg/backup/item_backupper.go#L374C2-L374C2)

The above cases do not report any skipped PVs. Wanted to check if this is expected behavior or not.

**Comment by blackpiglet** [comment]
@rnarenpujari 
It looks like the PV should be backed up by the CSI or vSphere plugin, so it's untracked.
Is the PV got backed up as expected by the other plugins in your environment?

**Comment by rnarenpujari** [comment]
> @rnarenpujari It looks like the PV should be backed up by the CSI or vSphere plugin, so it's untracked. Is the PV got backed up as expected by the other plugins in your environment?

This was from some time ago but I think I was mainly talking about volumes that are not backed up by any method (not FSB and not CSI or native snapshotter since .spec.snapshotVolumes is false). Should those also be included in the skipped volumes summary? @pradeepkchaturvedi can you mention what you had in mind for this feature request?
