### ISSUE TITLE
Document Wavefront integration for Velero using Telegraf agent

### ISSUE THREAD

**Issue by soumx** [vmware-tanzu/velero#5851]
Document Wavefront integration for Velero using Telegraf agent

Tanzu Observability/Wavefront is a public facing Observability platform for external customers. When Customers deploy Velero on their own cluster, they should be able to send metrics to TanzuObs for monitoring.

**Comment by reasonerjt** [comment]
Velero exposes a prometheus endpoint, and wavefront can integrate with that:
https://docs.wavefront.com/prometheus.html

I personally don't think that should be part of the OSS documentation.  If it's from some downstream product please contact the product manager via VMware internal channel.
