### ISSUE TITLE
When the cloud-credentials for S3 bucket updated, the Velero service can't read it automatically. 

### ISSUE THREAD

**Issue by iamjackhu** [vmware-tanzu/velero#5866]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
When the cloud-credentials for S3 bucket updated, the Velero service can't read it automatically. 

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Because the S3 bucket's secret key could be refreshed for security, if can't automatically load, then it requires restarting velero service manually. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
If the helm chart of Velero can check the checksum of cloud-credentials, then the reloading will be automatical.  

**Environment:**

- Velero version (use `velero version`): 1.10
- Kubernetes version (use `kubectl version`): v1.19.16
- Kubernetes installer & version: v1.19.16
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): ubunto

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
@iamjackhu 
Please clarify how did you update the creds for S3, did you patch the secret but it didn't work in the next backup after the patch?

**Comment by iamjackhu** [comment]
Delete the old one and create new one with the same secret name in the Velero namespace.
