### ISSUE TITLE
Remove the "subscriptionId" and "resourceGroup" items from the BSL config when installing Velero in E2E test

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#5870]
The `subscriptionId` and `resourceGroup` are not needed anymore in the BSL config after the PR https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/111 merged.
Let's remove them from the BSL config when installing Velero in the E2E test for Azure.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by danfengliu** [comment]
Follow guidance of [Azure doc](https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles-portal), assigned role `Storage Blob Data Contributor` to SP used by nightly test, Velero BSL is available after deletion of items "subscriptionId" and "resourceGroup". 

<img width="504" alt="image" src="https://user-images.githubusercontent.com/44018302/223001596-5876029a-01ae-4dca-af04-c20fdfe2434e.png">

**Comment by danfengliu** [comment]
Close it since Velero function is not ready yet, and no clear plan to achieve this feature. The [PR](https://github.com/vmware-tanzu/velero/pull/5962) for this issue is ready,  so close it anyway.
