### ISSUE TITLE
Velero backup duration using Kopia

### ISSUE THREAD

**Issue by slawekww** [vmware-tanzu/velero#5883]
**Describe the problem/challenge you have**
Noticed during testing, that once uploader=kopia is configured, 
cluster nodes are backup one by one instead of backup them in parallel.
It increases duration of backup for Kopia, especially that node agents are run on each node.

**Describe the solution you'd like**
Consider to run Kopia backup in parallel on all nodes or have it configurable.

**Anything else you would like to add:**
Likely VCPU/Memory for velero deployment would increase, consider more tasks to run on node agents and velero deployment to manage status of agents.

**Environment:**

- Velero version (use `velero version`): 1.10.1 with Kopia uploaded
- Kubernetes version (use `kubectl version`): AKS 1.24.6
- Kubernetes installer & version: 1.24.6
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): Ubuntu 18 as part of AKS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by qiuming-best** [comment]
@slawekww 
We do backup parallelly in each `node agent`, but serially in one `node agent`.

> It increases duration of backup for Kopia

could you share your comparison date of Kopia VS Restic?

**Comment by slawekww** [comment]
@qiuming-best 
Observation is that each `node agent` run backup in sequence for Kopia.
My system performance is 100GB volumes backup within 90min.

CPU metrics for agents:
![image](https://user-images.githubusercontent.com/7189961/220550274-c9a44dc3-b149-4914-8331-d88ebc1bf404.png)

Transmit bandwidth:
![image](https://user-images.githubusercontent.com/7189961/220550653-80725c4b-6980-4111-a86b-9b435e47c543.png)

Based on above metrics, I've noticed that `node agents` backup in sequence and improvement suggestion is to run backup on each node in the same time. I have no performance comparison with restic.

**Comment by Lyndon-Li** [comment]
@slawekww For your above Bandwidth metrics, are the two transmissions generated by `node-agent-2qcqm` and `node-agent-xk7d2` from the same backup? In another words, are they for two PVs from one backup or for two PV from two different backup?

**Comment by slawekww** [comment]
It is one backup which took around 2h: started at 12:55 and completed 14:53.
There are many PVs stored from the same node within one `backup` instance.
I cannot share backup logs due sensitive data.

**Comment by Lyndon-Li** [comment]
1. If PVs are stored in the same node, then they are backed up sequentially.
2. If PVs are in one backup and are in different nodes, they should be backed up in parallel.

If the case is point 2, this is not as the expectation, and we need more info to troubleshoot it. For example, could you collect the podVolumeBackup CRs in the cluster and share us?

**Comment by Lyndon-Li** [comment]
@slawekww 

- If PVs are stored in the same node, then they are backed up sequentially.
- If PVs are in one backup and are in different nodes, they should be backed up in parallel.

If the case is point 2, this is not as the expectation, and we need more info to troubleshoot it. For example, could you collect the podVolumeBackup CRs in the cluster and share us?

**Comment by slawekww** [comment]
Please find velero backup logs:
[velero.log.zip](https://github.com/vmware-tanzu/velero/files/10849916/velero.log.zip)

And current podVolumeBackup CRs (velero-default-20230213000044 has been run at the 13-Feb-2023):
[podvolumes.yaml.zip](https://github.com/vmware-tanzu/velero/files/10849917/podvolumes.yaml.zip)

**Comment by Lyndon-Li** [comment]
I found the clues in the log:
One PodVolumeBackup started at 2023-02-13T13:40:07 and completed at 2023-02-13T14:18:10, this is for pod `vmstorage-0`; the other PodVolumeBackup started at 2023-02-13T14:18:10 and completed at 2023-02-13T14:52:52, this is for pod `vmstorage-1`:

```
  status:
    completionTimestamp: "2023-02-13T14:18:10Z"
    ...
    startTimestamp: "2023-02-13T13:40:07Z"
```

```
  status:
    completionTimestamp: "2023-02-13T14:52:52Z"
    ...
    startTimestamp: "2023-02-13T14:18:10Z"
```

**Comment by Lyndon-Li** [comment]
@slawekww 
This problem comes down to the same problem as #5677, the PodVolumeBackups from two pods are not asynchronous. We will try to fix it in the future release.

**Comment by Lyndon-Li** [comment]
I will close this issue as it is duplicated with #5677
