### ISSUE TITLE
Restores never starts (stuck as New) until I restart velero

### ISSUE THREAD

**Issue by Nicky31** [vmware-tanzu/velero#5885]
**What steps did you take and what happened:**
Almost everytime I try to `velero restore create`, the restore requests stays `News` without any log produced by velero deployment :  

```
velero restore create --from-backup cluster --include-namespaces=apps --namespace-mappings apps:test --include-resources=configmaps,secrets
```

Output of `velero restore get` :  
```
cluster-20230220115451   cluster   New               <nil>                           <nil>                           0        0          2023-02-20 11:54:51 +0100 CET   <none>
```

I did not try to wait longer than 20-30 minutes, howevever it starts quickly after restarting the velero deployment :  
```
cluster-20230220115451   cluster   Completed         2023-02-20 12:03:42 +0100 CET   2023-02-20 12:03:47 +0100 CET   0        3          2023-02-20 11:54:51 +0100 CET   <none>
```

Creating a second restore quickly after is also picked up immediately.  

Could the velero get stuck because of a previous failed restore ? Or a long restore that I deleted because I didn't want to wait for its completion ?  Since i'm testing & documenting our various velero use cases, I indeed create & delete many restores, either unsuccessful or in progress, so maybe this leaves velero in an unclean state ??.

**What did you expect to happen:**
To see the restore phase **InProgress** quickly after `velero restore create`

**The following information will help us better understand what's going on**:

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero` : https://gist.github.com/Nicky31/0720a4d67a3eb54e8120f0f5977172c9
- `velero restore describe <restorename>`  : https://gist.github.com/4a2242ce43a54dd5e201501729cd9cf8.git
- `velero restore logs <restorename>` : https://gist.github.com/Nicky31/d3c5cd758b99ca003712ec817bcea55e

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v1.10.1
- Velero features (use `velero client config get features`):  NOT SET
- Kubernetes version (use `kubectl version`): Client 1.21 & server on 1.19+
- Kubernetes installer & version: Cloud Container Engine
- Cloud provider or hardware configuration:  OBS
- OS (e.g. from `/etc/os-release`): EulerOS 2.0

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
Yes, the new restores are stuck by the previous unfinished even if you have deleted the restore in your CLI.

But when you restart Velero, it will fail all `InProgress` restores at startup.  so Velero will handle the `New` status restore very quickly.

**Comment by Nicky31** [comment]
I get it, thanks.  
So we can't tell Velero to cancel any ongoing restore ?  Why would `restore delete` let him continue anyway ?

**Comment by qiuming-best** [comment]
@Nicky31 Currently, we don't have one mechanism to cancel one restore CR related item in the controller reconcile queue.
Also we currently cannot cancel one internal restore (such as Kopia/Restic restore directory) from Velero.

These make it not easy just delete restore CR to cancel long-time running restore to avoid stuck, but we have a few considerations about it and may be supported in the future.

**Comment by Nicky31** [comment]
Sounds fair.  
Unless you wanna keep this for tracking we can close this !

Thanks @qiuming-best
