### ISSUE TITLE
Finalize namespace inclusion/exclusion UX

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#589]
We currently have `--include-namespaces ns1,ns2,ns3` and `--exclude-namespaces ns4,ns5,ns6` as the means to include and exclude namespaces from a backup and restore. We also have `--selector` as a means to include/exclude across all Kubernetes resources (including namespaces). Let's decide:

1. Should we keep `--include/exclude-namespaces` separate from `--selector`?
1. Should we remove `--include-exclude-namespaces` and just have `--selector`?

**Comment by nrb** [comment]
Given the release of v1.0 in 2019, I'm going to close out this issue.
