### ISSUE TITLE
restore a empty backup with 0 item PartiallyFailed with error parsing backup contents

### ISSUE THREAD

**Issue by jhuisss** [vmware-tanzu/velero#5910]
**What steps did you take and what happened:**
when I try to velero restore a empty backup with 0 item (the backup is successful), the restore become PartiallyFailed with error:
`Velero:   error parsing backup contents: directory "/tmp/3490834435/resources": does not exist`
is this expected? or better to mark the restore successful with 0 item restored? Or 

**What did you expect to happen:**
Better to mark the restore successful with 0 item restored. Or it is more reasonable for the restore to mark complete/fail status while not restore anything and give more meaningful logs.

**The following information will help us better understand what's going on**:
velero 1.9.5

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  1.9.5
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
which is duplicate with https://github.com/vmware-tanzu/velero/issues/3565, and it's already fix in 1.10.x

**Comment by jhuisss** [comment]
Thanks!
