### ISSUE TITLE
Unable to find plugin for nfs

### ISSUE THREAD

**Issue by srikanthrkulkarni** [vmware-tanzu/velero#5917]
Currently I am using Velero Version: v1.8.1 and I wanted to create a backup for NFS share location.

When I have created the Backupstoragelocation in Kubernetes cluster the NFS plugin is not found.

I have tried to install the nfs plugin velero/velero-plugin-for-nfs:v1.0.0 , it looks like plugin is not available. 

Logs: docker.io/velero/velero-plugin-for-nfs:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

velero plugin add velero/velero-plugin-for-nfs:v1.0.0

Could you please help me to understand whether Velero backup is possible for NFS ?

**Comment by sseago** [comment]
Where did you find a link to velero-pljugin-for-nfs? I'm unaware of an object store plugin for NFS. The currently-supported object store plugins are aws/s3, azure, and gcp. Note that if your NFS concern is backing up volume data for NFS volumes, that is supported using kopia/restic, but the backup itself must use a supported object store plugin.
