### ISSUE TITLE
Velero creates a Restic repository per namespace but not per backup

### ISSUE THREAD

**Issue by jhuisss** [vmware-tanzu/velero#5922]
**What steps did you take and what happened:**
I'm using velero 1.9.5, after changing the bucket in BackupStorageLocation, and then trigger backup using restic plugin again, I found that it will not re-create new ResticRepositories and still re-use the legacy one, which will cause the backup partialFail.  The only workaround is manually deleting the legacy ResticRepositories. 

According to https://velero.io/docs/v1.9/restic/#:~:text=Velero%20creates%20a%20Restic%20repository%20per%20namespace%20when%20the%20first%20Restic%20backup%20for%20a%20namespace%20is%20requested. it seems it is by design that the new backup in the same namespace will not trigger a new ResticRepositories, but it is not reasonable in the case like changing to other s3 bucket.

```
[root@tca23-cp /home/admin]# velero restic repo get
NAME                          STATUS   LAST MAINTENANCE
nginx-example-default-kppgd   Ready    2023-02-27 05:49:53 +0000 UTC
[root@tca23-cp /home/admin]# velero restic repo get nginx-example-default-kppgd -oyaml
apiVersion: velero.io/v1
kind: ResticRepository
...
spec:
  backupStorageLocation: default
  maintenanceFrequency: 1m0s
  resticIdentifier: s3:https://**:9000/jhui-velero/restic/nginx-example -----> still use the earlier bucket
  volumeNamespace: nginx-example
status:
  lastMaintenanceTime: "2023-02-27T05:49:53Z"
  phase: Ready
```

**What did you expect to happen:**
Velero creates a Restic repository per per backup.

**Environment:**

- Velero version (use `velero version`):  v1.9.5
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
This is duplicated with #5226 and has been fixed by PR #5768
