### ISSUE TITLE
unable to create lock in backend: repository is already locked exclusively by PID XXXXXX on velero-58944b9cbb-mcqsz by nonroot (UID XXX, GID XXX)

### ISSUE THREAD

**Issue by JebasinghLuccas** [vmware-tanzu/velero#5925]
I am using velero v1.10.0 and getting this errors.  GKE is the environment i am using to backup.  The backup completes with PartiallyFailed status.  

The below is the error: 

time="2023-02-23T22:00:31Z" level=error msg="Error backing up item" backup=velero/velero-jenkinbackup-20230223220024 error="backup repository is not ready: error running command=**restic snapshots** --repo=gs:**<storage location>**/restic/jenkins --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic --latest=1, stdout=, stderr=unable to create lock in backend: repository is already locked exclusively by PID 129810 on velero-6dc8dfd68-nn5hh by  (UID 0, GID 0)\nlock was created at 2023-02-23 13:46:59 (8h13m31.568733738s ago)\nstorage ID ac856a62\nthe `unlock` command can be used to remove stale locks\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/backup_repo_op.go:83" error.function=github.com/vmware-tanzu/velero/pkg/repository.GetBackupRepository logSource="pkg/backup/backup.go:425" name=k8s-terraform-0.13.5-gm60b

The errors are only when it performs restic snapshots. Am i missing any configuration here? Please any help would really be appreciated.

**Comment by Lyndon-Li** [comment]
See the discussion in issue #5268, Restic creates locks in backup storage, and sometimes, the lock will be left and block other operations. At present, we don't have a way to solve the problem ultimately for Restic path.

Since you are using Velero 1.10, could you switch to Kopia path? Kopia doesn't create locks in backup storage, so it doesn't have this kind of problem.

**Comment by JebasinghLuccas** [comment]
Thanks for the information,

Looking at the log below, one thing i noticed was the volumes are being backed up by the pod volume backup hence it skipping the snapshots, and the followed by restic snapshots commands are failed due to lock issue. 

What additional components will be backed up by the restic snapshots? if restic snapshots backup only the volume that is already being backed up by pod volume backup,  i am thinking to ignore these errors. Is it a correct assumption?  Please help me to understand the behavior. 


time="2023-02-28T12:00:07Z" level=info msg="**Backing up all volumes using pod volume backup:** true" backup=velero/velero-jenkinbackup-20230228120007 logSource="pkg/backup/backup.go:208"

time="2023-02-28T12:00:13Z" level=info msg="**Skipping snapshot of persistent volume because volume is being backed up with pod volume backup**." backup=velero/velero-jenkinbackup-20230228120007 logSource="pkg/backup/item_backupper.go:430" name=pvc-7b3526e2-d12c-11e9-8cb0-42010a630004 namespace= persistentVolume=pvc-7b3526e2-d12c-11e9-8cb0-42010a630004 resource=persistentvolumes

time="2023-02-28T12:00:17Z" level=error msg="Error backing up item" backup=velero/velero-jenkinbackup-20230228120007 error="pod volume backup failed: error creating uploader: failed to connect repository: error running command=restic snapshots --repo=gs:path to storage/restic/jenkins --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic --latest=1, stdout=, stderr=unable to create lock in backend: repository is already locked exclusively by PID 7347 on velero-58944b9cbb-mcqsz by nonroot (UID 65532, GID 65532)\nlock was created at 2023-02-28 11:59:08 (1m5.819012736s ago)\nstorage ID 5d047265\nthe `unlock` command can be used to remove stale locks\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:223" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:425" name=jenkins-6b48dc8dc8-zjfwm

time="2023-02-28T12:00:17Z" level=error msg="Error backing up item" backup=velero/velero-jenkinbackup-20230228120007 error="pod volume backup failed: error creating uploader: failed to connect repository: error running command=restic snapshots --repo=gs:path to storage/restic/jenkins --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic --latest=1, stdout=, stderr=unable to create lock in backend: repository is already locked exclusively by PID 7347 on velero-58944b9cbb-mcqsz by nonroot (UID 65532, GID 65532)\nlock was created at 2023-02-28 11:59:08 (1m6.548529171s ago)\nstorage ID 5d047265\nthe `unlock` command can be used to remove stale locks\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:223" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:425" name=jenkins-6b48dc8dc8-zjfwm

time="2023-02-28T12:00:17Z" level=error msg="Error backing up item" backup=velero/velero-jenkinbackup-20230228120007 error="pod volume backup failed: error creating uploader: failed to connect repository: error running command=restic snapshots --repo=gs:path to storage/restic/jenkins --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic --latest=1, stdout=, stderr=unable to create lock in backend: repository is already locked exclusively by PID 7347 on velero-58944b9cbb-mcqsz by nonroot (UID 65532, GID 65532)\nlock was created at 2023-02-28 11:59:08 (1m7.167371303s ago)\nstorage ID 5d047265\nthe `unlock` command can be used to remove stale locks\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:223" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:425" name=jenkins-6b48dc8dc8-zjfwm

time="2023-02-28T12:00:17Z" level=error msg="Error backing up item" backup=velero/velero-jenkinbackup-20230228120007 error="pod volume backup failed: error creating uploader: failed to connect repository: error running command=restic snapshots --repo=gs:path to storage/restic/jenkins--password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic --latest=1, stdout=, stderr=unable to create lock in backend: repository is already locked exclusively by PID 7347 on velero-58944b9cbb-mcqsz by nonroot (UID 65532, GID 65532)\nlock was created at 2023-02-28 11:59:08 (1m7.820429718s ago)\nstorage ID 5d047265\nthe `unlock` command can be used to remove stale locks\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:223" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:425" name=jenkins-6b48dc8dc8-zjfwm

**Comment by sseago** [comment]
```
Looking at the log below, one thing i noticed was the volumes are being backed up by the pod volume backup hence it skipping the snapshots, and the followed by restic snapshots commands are failed due to lock issue.

What additional components will be backed up by the restic snapshots? if restic snapshots backup only the volume that is already being backed up by pod volume backup, i am thinking to ignore these errors. Is it a correct assumption? Please help me to understand the behavior.
```
If we're using restic or kopia to back up a volume, then we skip native or csi snapshots, which is what that log message is telling you.

Restic is only used to back up volumes. The purpose of the PodVolumeBackup is to enable restic or kopia to back up the volume. If you use native or csi snapshots instead of restic/kopia, then the pod volume backup CR is not created.

**Comment by JebasinghLuccas** [comment]
I was upgrading the velero from the version v.1.1.0 to v1.10.0 and was using the same backup location. When i noticed, (velero repo get) the older repo was also there. After changing to a new backup location and redeploy the velero, then the errors are gone.  Thanks for the support.
