### ISSUE TITLE
design for CSI snapshot integration

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#593]
There is an external repo, https://github.com/kubernetes-incubator/external-storage/tree/master/snapshot, that aims to add snapshot/restore functionality to Kubernetes. This may eventually be incorporated into https://github.com/kubernetes/kubernetes/ proper. If it does end up moving into k/k, we need to determine how to handle these resources. We'll also need to consider how to replicate them (if possible).

**Comment by skriss** [comment]
closed by #1661
