### ISSUE TITLE
velero-plugin-for-microsoft-azure returns Confidential Client is not supported in Cross Cloud request with AzureUSGovernment

### ISSUE THREAD

**Issue by nicolaschaillan** [vmware-tanzu/velero#5930]
**What steps did you take and what happened:**

We have installed Velero using the Helm chart on AKS on Azure Government but we are getting an error with the Backup location.

We are using AZURE_CLOUD_NAME=AzureUSGovernmentCloud in credentials file.

helm install velero vmware-tanzu/velero --namespace velero \
--set-file credentials.secretContents.cloud=./credentials-velero-aks \
--set configuration.provider=azure \
--set configuration.backupStorageLocation.name=azure \
--set configuration.backupStorageLocation.bucket='velero-aks' \
--set configuration.backupStorageLocation.config.resourceGroup=sage \
--set configuration.backupStorageLocation.config.storageAccount=chatstorageveleroaks \
--set snapshotsEnabled=true \
--set configuration.volumeSnapshotLocation.name=azure \
--set image.repository=velero/velero \
--set image.pullPolicy=Always \
--set initContainers[0].name=velero-plugin-for-microsoft-azure \
--set initContainers[0].image=velero/velero-plugin-for-microsoft-azure:v1.6.0 \
--set initContainers[0].volumeMounts[0].mountPath=/target \
--set initContainers[0].volumeMounts[0].name=plugins

Error: Confidential Client is not supported in Cross Cloud request.

**What did you expect to happen:**

Work?

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  

time="2023-02-28T15:45:18Z" level=error msg="Error getting backup store for this location" backupLocation=velero/azure controller=backup-sync error="rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.usgovcloudapi.net/subscriptions/ff3af667-030e-4cbf-860a-a545d0113bf5/resourceGroups/sage/providers/Microsoft.Storage/storageAccounts/chatstorageveleroaks/listKeys?%24expand=kerb&api-version=2019-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"AADSTS900382: Confidential Client is not supported in Cross Cloud request.\\r\\nTrace ID: 51e7c999-5d6a-46b5-a2a3-b9c21b4a2a01\\r\\nCorrelation ID: 0a7b2627-f943-4358-b7d6-4d6f03e53229\\r\\nTimestamp: 2023-02-28 15:45:18Z\",\"error_codes\":[900382],\"timestamp\":\"2023-02-28 15:45:18Z\",\"trace_id\":\"51e7c999-5d6a-46b5-a2a3-b9c21b4a2a01\",\"correlation_id\":\"0a7b2627-f943-4358-b7d6-4d6f03e53229\"} Endpoint https://login.microsoftonline.com/10433aac-beb5-4c0d-8191-e544180110ec/oauth2/token?api-version=1.0" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:217" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:100"

Debug logs attached.
[bundle-2023-02-28-15-45-54.tar.gz](https://github.com/vmware-tanzu/velero/files/10852205/bundle-2023-02-28-15-45-54.tar.gz)

**Environment:**

Client:
        Version: v1.10.1
        Git commit: 948b3790d5577dc7e77410a8b80ef7d8a6b00303
Server:
        Version: v1.10.0

- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"9710807c82740b9799453677c977758becf0acbb", GitTreeState:"clean", BuildDate:"2022-12-13T08:17:45Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.24) exceeds the supported minor version skew of +/-1

- Kubernetes installer & version:
- Cloud provider or hardware configuration:

AKS

- OS (e.g. from `/etc/os-release`):

NAME="Common Base Linux Mariner"
VERSION="2.0.20230126"
ID=mariner
VERSION_ID="2.0"
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by gwynforthewyn** [comment]
I see the same issue using the helm chart with Azure gov cloud

**Comment by gwynforthewyn** [comment]
@nicolaschaillan I wrote a fix that might well fix your reported issue here and worked with the vmware team to get it merged. Once the next version of velero's azure plugin is released hopefully you should be good to go.

I don't know the release cadence, but the team managing this plugin has been responsive and helpful, so it should be soon 🙂

**Comment by ywk253100** [comment]
Thanks @gwynforthewyn 
As this is a dup of https://github.com/vmware-tanzu/velero/issues/6196, I'm closing this one
