### ISSUE TITLE
k8s.gcr.io Image Registry Will Be Frozen From the 3rd of April 2023

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#5932]
This repo contain mentions of k8s.gcr.io and should migrate to registry.k8s.io

> If using the new registry domain name is not an option, you can revert to the old domain name for cluster versions less than 1.25. Keep in mind that, eventually, you will have to switch to the new registry, as new image tags will no longer be pushed to GCR.

https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/#i-m-impacted-by-this-change-how-do-i-revert-to-the-old-registry-address

**Comment by reasonerjt** [comment]
Does velero use k8s.gcr.io?

**Comment by blackpiglet** [comment]
Velero is not owned by CNCF now, and the Velero project pushes images to`https://gcr.io/velero-gcp/velero` for internal use.
This change will not impact Velero.
