### ISSUE TITLE
Partially Failed while performing backup v1.10.0

### ISSUE THREAD

**Issue by JebasinghLuccas** [vmware-tanzu/velero#5945]
[bundle-2023-03-02-19-03-05.tar.gz](https://github.com/vmware-tanzu/velero/files/10875985/bundle-2023-03-02-19-03-05.tar.gz)
**What steps did you take and what happened:**

I have installed velero v1.10.0 in GKE to take back up  and restore Jenkins workload running in the same cluster but different namespace. I did it in the testing env and both back up and restore was working like charm. Now i moved this to the production environment. 

**What did you expect to happen:**

The backup should happen with complete state but i am always getting partially failed with one specific issue in prod instances

time="2023-03-01T16:05:52Z" level=error msg="Error backing up item" backup=velero/velero-jenkinbackup-20230301160058 error="pod volume backup failed: running backup, stderr=error running restic backup command restic backup --repo=gs:<google storage Path>/restic/jenkins --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic . --tag=volume=jenkins-home --tag=backup=velero-jenkinbackup-20230301160058 --tag=backup-uid=06c18bee-68b5-4cd9-94ae-8028c544d6ba --tag=ns=jenkins --tag=pod=jenkins-56cd598d89-2lg7s --tag=pod-uid=545dff36-3d6d-44dc-acdb-127fc91d82dd --tag=pvc-uid=7973c9a4-d03e-11e9-bfcf-42010a63000a --host=velero --json with error: signal: killed stderr: : error running restic backup command restic backup --repo=gs:<google storage Path>/restic/jenkins --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic . --tag=volume=jenkins-home --tag=backup=velero-jenkinbackup-20230301160058 --tag=backup-uid=06c18bee-68b5-4cd9-94ae-8028c544d6ba --tag=ns=jenkins --tag=pod=jenkins-56cd598d89-2lg7s --tag=pod-uid=545dff36-3d6d-44dc-acdb-127fc91d82dd --tag=pvc-uid=7973c9a4-d03e-11e9-bfcf-42010a63000a --host=velero --json with error: signal: killed stderr: " error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:223" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:425" name=jenkins-56cd598d89-2lg7s

**Environment:**

- Velero version (use `velero version`):  V1.10.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 
 Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.21.14-gke.14100

- Kubernetes installer & version:
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
Velero file system backup takes significant system resources (CPU, memory, etc) when the data size is large, for details, check [this guide](https://velero.io/docs/v1.10/performance-guidance/). If give less resources to Velero node-agent pod, the pod will be killed by Kubernetes.

It is also a known issue that in some cases, Restic takes irrational system resources.

Therefore, here are two suggestions:
1. Change to Kopia path, check this [doc](https://velero.io/docs/v1.10/file-system-backup/) to see how to configure the Kopia path for file system backup, because Kopia performs better and more stable when the data size is large
2. Configure more memory to Velero node-agent pod

**Comment by JebasinghLuccas** [comment]
Yes that was the issue, when increase the memory resources to velero node-agent pod, the issue disappears. @Lyndon-Li, It was a timely support.
