### ISSUE TITLE
CSI VolumeSnapshot is not ready but Backup phase is marked as Completed

### ISSUE THREAD

**Issue by lxs137** [vmware-tanzu/velero#5957]
**How to reproduce**
- ensure `velero-plugin-for-csi` has been installed
- create Backup with PVC included
- Backup phase is marked as Completed, but VolumeSnapshot 's `readyToUse` is false

**Expect behavior**
- Backup should be Completed after VolumeSnapshot is ready

**Environments**
- velero v1.9.0
- velero-plugin-for-csi v0.3.1

**Comment by anshulahuja98** [comment]
Hi @lxs137 

Can you provide further details using below instructions for us to help you better identify what might have gone wrong?
Copying from the bug issue template

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`


**Anything else you would like to add:**

**Comment by ywk253100** [comment]
@lxs137 Velero waits for the VolumeSnapshots to be ready before marking the backup as completed in v1.9.0+, which version of Velero are you using?

**Comment by lxs137** [comment]
@ywk253100 

velero v1.9.0
velero-plugin-for-csi v0.3.1

I dig into velero design docs, find it is the designed behavior.

https://github.com/vmware-tanzu/velero/blame/main/design/Implemented/csi-snapshots.md#L72
> The plugin will _not_ wait for the `VolumeSnapshot.Status.readyToUse` field to be `true` before returning.
This field indicates that the snapshot is ready to use for restoration, and for different vendors can indicate that the snapshot has been made durable.
However, the applications can proceed as soon as `VolumeSnapshot.Status.CreationTime` is set.
This also maintains current Velero behavior, which allows applications to quiesce and resume quickly, with minimal interruption.

**Comment by blackpiglet** [comment]
@lxs137 
The document should be updated.
From v1.9, Velero made some changes in the CSI workflow to make it more robust for cloud providers, such as Azure, GCP, AWS. The Velero server will wait for all created VolumeSnapshots turned into ReadyToUse before going into the next step of backup.

The function `checkVolumeSnapshotReadyToUse` is used for that purpose.
Could you update the Velero version to v1.9.6 and CSI plugin version to v0.3.4?
There were some bugs fixed since v1.9.6.

**Comment by blackpiglet** [comment]
Close for now. Feel free to reopen, if any progress is made.
