### ISSUE TITLE
Define & document policy for which Kubernetes versions and features we support

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#596]
Define & document a policy for which Kubernetes versions and features we support:

1. What is our minimum required Kubernetes version
1. Do we attempt to do graceful degradation for older Kubernetes versions?
    1. json-schema validation
    1. /status subresources for CRDs
    1. CRD field defaulting

**Comment by Bradamant3** [comment]
Can we get started on this one for 0.10.0? Maybe say something about 0.9.1 for backward compatibility, at least? Changing milestone provisionally.

**Comment by Bradamant3** [comment]
Milestone reverted; oneliner for 0.10 added (see PR #1023 )

**Comment by ncdc** [comment]
xref #529
