### ISSUE TITLE
E2E test for progress monitoring (BIAv2, RIAv2)

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#5970]
Currently, we have e2e testcase to B/R real-world workload and it proved to be useful, some trivial issues have been discovered after PR #5849 is merged.

We should also add e2e testcases  to verify the interaction between BIAv2/RIAv2 for progress monitoring, in order to make sure no regression problem happens when we make updates to the Backup/Restore controllers.

At this moment we don't have plugins that implements v2 interface for progress monitoring, but can leverage the plugin-example proposed in this [PR](https://github.com/vmware-tanzu/velero-plugin-example/pull/66)

**Comment by sseago** [comment]
Yes, this should be possible to implement once the BIAv2/RIAv2 monitoring is merged, as well as https://github.com/vmware-tanzu/velero-plugin-example/pull/66 and a similar RIAv2 example plugin.
