### ISSUE TITLE
`TZ` Env stopped working

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#5976]
**What steps did you take and what happened:**

It appears changes made in https://github.com/vmware-tanzu/velero/pull/2944 to close https://github.com/vmware-tanzu/velero/issues/2061 no longer works due to dockerfile updates that followed.

**What did you expect to happen:**
TZ Env is respected
**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

We're working on a fix for this in a way that works regardless of distro used to run velero by reading this env and respecting it inside go server.

It has also been noted in https://github.com/vmware-tanzu/velero/issues/5426 that we may want schedule generated backup names to respect TZ Env as well.

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
@kaovilai 
The base image used by Velero contains the timezone database data as the same with https://github.com/vmware-tanzu/velero/pull/2944 and Golang [std lib](https://go.dev/src/time/zoneinfo_unix.go) reads the `TZ` env, so seems that the change isn't necessary. Correct me if I'm wrong.

**Comment by kaovilai** [comment]
According to
https://github.com/vmware-tanzu/velero/issues/5426#issuecomment-1281750734

It doesn't work right now.

**Comment by kaovilai** [comment]
So we had hit some issues in our dockerfile which used a different distro.
Now that has been resolved.

The linked PRs may still be useful if others don't want to fix their tzdata installation but still want TZ env to be usable.
