### ISSUE TITLE
Restored PVC hangs in "Pending" state

### ISSUE THREAD

**Issue by Subetov** [vmware-tanzu/velero#5983]
**What steps did you take and what happened:**
- restore trigered with --restore-volumes option
   `velero restore create --from-backup all-backup --include-namespaces test --restore-volumes=true`

**What did you expect to happen:**
PVC is created / bound / restored

**Anything else you would like to add:**
PVC remains in "Pending" state until "volume.beta.kubernetes.io/storage-provisioner" annotation manually added

**Environment:**

- helm version (use `helm version`): v3.10.3
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): velero-3.1.2
- Kubernetes version (use `kubectl version`): v1.24.8
- Storage Provozioner: openebs-zfs / zfs-localpv-2.1.0

**Comment by reasonerjt** [comment]
Please provide the log bundle as suggested in the template.

Please also provide details like are you creating the backup and restore on the same cluster or not, is it b/c on the target cluster there's no default storage class but on the source cluster there is?

**Comment by blackpiglet** [comment]
Close for now. Feel free to reopen if there is any progress made.
