### ISSUE TITLE
Listing storage account access key is still needed for Restic/Kopia to work as expected on Azure

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#5984]
We introduced several [changes](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/111) for the Velero Azure plugin to resolve https://github.com/vmware-tanzu/velero/issues/4267 in v1.11.0 timeframe, but besides the Azure plugin, the support for Azure AD auth is also needed in Restic/Kopia side.

However, Restic/Kopia only supports authentication/authorization by access key and SAS token but not Azure AD at this moment, so in order to work with filesystem backup/restore with Restic/Kopia, listing storage account access key is still needed on Azure.

For users who don't use filesystem backup/restore and cannot list the storage account access key, they can refer to the [doc](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/111/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R158) to workaround it.

[Issue](https://github.com/kopia/kopia/issues/2800) is opened for Kopia.

We'll remove the listing storage account access key completely once Kopia supports auth via Azure AD.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
@ywk253100 
IMO we should consider it as a higher priority as it's an enhancement to security.
Let's see if we can fix it on kopia side.  
But given this has external dependency, let's leave it as candidate for now and triage later.

**Comment by ywk253100** [comment]
We can start the work to fix it on the Kopia side in the 1.12 timeframe, but it is very likely that we cannot make it in v1.12 as this has external dependency.

**Comment by ywk253100** [comment]
Fixed by https://github.com/vmware-tanzu/velero/pull/6686
