### ISSUE TITLE
OOM Killed issue

### ISSUE THREAD

**Issue by IvoTD** [vmware-tanzu/velero#5988]
**What steps did you take and what happened:**

Constantly receiving OOM Killed issue where the pods keeps restarting. The backup still goes through but it keeps restarting after the job is done.
 
Currently using version 1.10.0 in Azure

**What did you expect to happen:**

The pods should not restart after each backup.

**The following information will help us better understand what's going on**:

 So far we have doubled the memory, gave different schedule times for each backup and also tried with both Restic and Kopia uploader types. From what I can see when the backups starts, the pods are using way to much memory in contrast to the file size ( uses up to 3 Gb memory for 150 Mb backup size). 

**Environment:**

- Velero version (use `velero  version`): 1.10.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.24.9
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
@IvoTD
 I believe it's the velero pod got killed and restarted, NOT the node-agent, correct?
Please provide the log bundle so we may understand at what point the pod was OOM killed.

**Comment by Lyndon-Li** [comment]
Closing as no further request, feel free to reopen it.
