### ISSUE TITLE
New scheduled backup gets triggered before last one completes

### ISSUE THREAD

**Issue by navilg** [vmware-tanzu/velero#5989]
**What steps did you take and what happened:**

I have velero schedule which runs every 4 hours. Sometimes backup takes longer than 4 hours to complete. In that case new backup is triggered and that will be in NEW state and get piled up. 

**What did you expect to happen:**

New scheduled backup should not be triggered unless last scheduled backup is completed from same schedule.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.8.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.23
- Kubernetes installer & version: GKE 1.23
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): Ubuntu

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
@blackpiglet 
I believe this has been fixed, please clarify.

**Comment by blackpiglet** [comment]
@navilg 
This issue is fixed by PR #5283. It's included in v1.10.x release.
Could you upgrade the Velero CRD and images, then have another try?
