### ISSUE TITLE
Restore progress is misleading (temporarily)

### ISSUE THREAD

**Issue by rnarenpujari** [vmware-tanzu/velero#5990]
**What steps did you take and what happened:**

The Restore CR contains progress info in terms of number of items restored and the total number of items ([link](https://github.com/vmware-tanzu/velero/blob/117d5e846f115445b881135dcef7462edfe12c01/pkg/apis/velero/v1/restore_types.go#L320)). The restore seems to happen in two passes - in the first pass, the `totalItems` reported is low (56 in my test) and `itemsRestored` reaches this value shortly. Then the second pass starts and `totalItems` is updated to a larger value (~2600 in my case) and eventually `itemsRestored` reaches this value after some time and the restore phase becomes completed.
The point here is that there is a transient state shortly after starting the restore where `itemsRestored == totalItems` even though the restore is not done which can be a bit misleading.

**What did you expect to happen:**

The restore progress to be reported in a single pass where `itemsRestored < totalItems` until the restore completes.

It is already documented that total items will be updated throughout the restore ([link](https://github.com/vmware-tanzu/velero/blob/117d5e846f115445b881135dcef7462edfe12c01/pkg/apis/velero/v1/restore_types.go#L321)) so this is technically not a bug but can perhaps be handled better to avoid this transient incorrect state?

**The following information will help us better understand what's going on**:

NA

**Anything else you would like to add:**

NA

**Environment:**

- Velero version (use `velero version`): 1.9.5
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
We will delay showing the number, so only when there's a relatively accurate number of objects this field will be updated.
