### ISSUE TITLE
Cannot delete restored PV in cloud when deleted from kubernetes cluster

### ISSUE THREAD

**Issue by itsmaniche18** [vmware-tanzu/velero#5994]
Hello,

I have installed Velero in Digital Ocean. Everything is working as expected. 
Problem I faced is when I restore a pv it creates a volume name in DO as **restore-d1c393c6-c531-49ac**. As before the original disk name were stared like pvc-** like **pvc-d17acdc3-8f35-4ab8-**.

As the volumes has reclaim-policy delete. The existing which started with pvc-** gets deleted from the kubernetes cluster and also get deletes in the DO Volumes when I use command.
kubectl delete pv pv-name

But for the restore volumes when I delete the pv from the kubernetes using
kubctl delete pv pv-name. 
It will not be deleted from the DO Volumes as it will be deleted from the kubernetes cluster.

I have attached the image of the Volumes(after restore starts with restore--****) which are not being delete.

![image](https://user-images.githubusercontent.com/21244470/225919903-128ac3e2-7ea6-40ed-97c4-14277bd90d10.png)

My guess is the pv name are different after restore so it's not being deleted or any issue?

Thanks

**Comment by reasonerjt** [comment]
This may be related to how DO implements the storage driver.

I assume you use snapshot to backup/restore the PV, not filesystem-based approach like restic/kopia, right?
Please provide more information, like what version of velero was used, what plugin you used to take the snapshot.

I don't use Digital Ocean, so you may also wanna talk to an engineer from DO for suggestions.

**Comment by itsmaniche18** [comment]
Hello @reasonerjt,
Thanks for the reply.
I guess if I am right the backup taken by velero will be kept as snapshot of volumes as in the picture.
![image](https://user-images.githubusercontent.com/21244470/226075829-ef3f955a-659d-467d-9602-30f11bff5831.png)

Velero Client Version is
Client:
	Version: v1.10.2-rc.1
	Git commit: dcf1b005696506a74fdbe07040e71b62d115e9aa
and Plugin Version is
velero-plugin-1.0.0	

Thanks

**Comment by reasonerjt** [comment]
I'm confused about `velero-plugin-1.0.0`, is it a plugin for Digital Ocean?  That is not maintained by velero maintainers.

Did you install velero via CLI?  How did you install the plugins?

**Comment by itsmaniche18** [comment]
I used the plugin from this [link](https://github.com/digitalocean/velero-plugin/releases/tag/v1.0.0).

Yeah I install velero via CLI.

For more information I used this digitalocean [link](https://www.digitalocean.com/community/tutorials/how-to-back-up-and-restore-a-kubernetes-cluster-on-digitalocean-using-velero) for installing velero and plugins.

Thanks
Manish

**Comment by reasonerjt** [comment]
@itsmaniche18 
Thanks for the reply.
The guide and plugin are not maintained by velero maintainers.  Therefore, I'd suggest you contact DigitalOcean to find out the root cause.

**Comment by itsmaniche18** [comment]
@reasonerjt 

Thanks for the reply.
I succeeded by using [**velero plugin  v1.1.0**](https://github.com/digitalocean/velero-plugin/releases/tag/v1.1.0) 
Before I was using velero-plugin-1.0.0

Thanks
Manish
