### ISSUE TITLE
Bump up Kopia to v0.13

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#5999]
Currently Velero is using 0.10.7. Therefore some Repository interface changes, so require some logic changes in Velero in order to bump up to a higher version of Kopia

**Comment by reasonerjt** [comment]
Moving it out of v1.11 milestone, as it may be less severe than we thought.

**Comment by bitfactory-sem-denbroeder** [comment]
Any ETA on this issue? this is blocking for us because of the known assumerole issue with kopia 0.10.7.

**Comment by Lyndon-Li** [comment]
Fixed by #6248

**Comment by bjb2010** [comment]
> 
There is oom issue in kopia v0.10.7
https://github.com/kopia/kopia/issues/2888

**Comment by XhmikosR** [comment]
@Lyndon-Li We really need this patch :/ Is there any way the patch could be backported to 1.11 or 1.10?
