### ISSUE TITLE
can not backup pvs

### ISSUE THREAD

**Issue by 13567436138** [vmware-tanzu/velero#6007]
**What steps did you take and what happened:**

```
time="2023-03-21T05:33:41Z" level=info msg="1 errors encountered backup up item" backup=velero/nginx-backup logSource="pkg/backup/backup.go:421" name=web-0
time="2023-03-21T05:33:41Z" level=error msg="Error backing up item" backup=velero/nginx-backup error="pod volume backup failed: error creating uploader: failed to connect repository: error running command=restic snapshots --repo=s3:http://192.168.229.159:30612/velero/minio/restic/nginx-example --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic --latest=1, stdout=, stderr=Fatal: unable to open config file: Stat: Access Denied.\nIs there a repository at the following location?\ns3:http://192.168.229.159:30612/velero/minio/restic/nginx-example\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:223" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:425" name=web-0
time="2023-03-21T05:33:41Z" level=info msg="1 errors encountered backup up item" backup=velero/nginx-backup logSource="pkg/backup/backup.go:421" name=web-1
time="2023-03-21T05:33:41Z" level=error msg="Error backing up item" backup=velero/nginx-backup error="pod volume backup failed: error creating uploader: failed to connect repository: error running command=restic snapshots --repo=s3:http://192.168.229.159:30612/velero/minio/restic/nginx-example --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic --latest=1, stdout=, stderr=Fatal: unable to open config file: Stat: The specified key does not exist.\nIs there a repository at the following location?\ns3:http://192.168.229.159:30612/velero/minio/restic/nginx-example\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:223" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:425" name=web-1
time="2023-03-21T05:33:41Z" level=info msg="1 errors encountered backup up item" backup=velero/nginx-backup logSource="pkg/backup/backup.go:421" name=web-2
time="2023-03-21T05:33:41Z" level=error msg="Error backing up item" backup=velero/nginx-backup error="pod volume backup failed: error creating uploader: failed to connect repository: error running command=restic snapshots --repo=s3:http://192.168.229.159:30612/velero/minio/restic/nginx-example --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic --latest=1, stdout=, stderr=Fatal: unable to open config file: Stat: The specified key does not exist.\nIs there a repository at the following location?\ns3:http://192.168.229.159:30612/velero/minio/restic/nginx-example\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:223" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:425" name=web-2

```
**What did you expect to happen:**
`
**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
```
stderr=Fatal: unable to open config file: Stat: Access Denied.\nIs there a repository at the following location?\ns3:http://192.168.229.159:30612/velero/minio/restic/nginx-example
```

**Comment by 13567436138** [comment]
thie file is deleted

**Comment by blackpiglet** [comment]
Then need to delete the CR that represents the Restic repository.
If the Velero version you are using is v1.9.x and earlier, the CR type is ResticRepository.
If the Velero version is v1.10.x, the CR type is BackupRepository.
The CR is created under the namespace where Velero deployment is created. The name should be nginx-example-<BackupStorageLocation-name>-xxxx.
