### ISSUE TITLE
Need recreate method for existing resource policy feature

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#6033]
**Describe the problem/challenge you have**

The design of [existing resource policy](https://github.com/vmware-tanzu/velero/blob/main/design/existing-resource-policy_design.md) and related implementation PR provide a new way for how Velero handles restoring resources already exist in the k8s cluster. 
In this design, two new ways are mentioned: `update` and `recreate`. `update` policy is already implemented, but `recreate` policy is yet to come.
The issue is used for tracing the `recreate` policy implementation.

**Describe the solution you'd like**

**Anything else you would like to add:**

Some requirement for this function from community:
https://kubernetes.slack.com/archives/C6VCGP4MT/p1679489668102599
https://vmware.slack.com/archives/CEX5KS8NP/p1679499104314119

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
Let's clarify what's the concrete usecase where `recreate` policy is needed.

**Comment by blackpiglet** [comment]
This link provides a user case.
Some k8s resources cannot be updated after creation, e.g. StorageClass's spec.

**Comment by reasonerjt** [comment]
This is a dup to #6142
