### ISSUE TITLE
[BIA V2] Backups with in progress async operation could should not be allowed to delete

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#6035]
There is an existing logic in Velero to prevent in progress backups from being deleted:
https://github.com/vmware-tanzu/velero/blob/1d8ca4f2efc512014c14e2e6ea5d6a7980d60fd3/pkg/controller/backup_deletion_controller.go#L160

However, this doesn't work for backups with in progress async operation since at the time of the async operation starts, the normal backup progress quits so `backupTracker` is cleared.

Actually, the backups in the `WaitingForPluginOperations` phase should not be allowed to be deleted as well, otherwise, the ongoing async operation will be orphan.

**Comment by sseago** [comment]
@Lyndon-Li This may be as simple as moving the "remove from backupTracker" code to finalize.
