### ISSUE TITLE
Velero backup failing with timeout error

### ISSUE THREAD

**Issue by snehaljoshi0904** [vmware-tanzu/velero#6036]
**What steps did you take and what happened:**
Previously I was using only velero to take take k8s resource backup and it was working fine. Now I am using velero with restic add-on to backup k8s resources and data. but, now a backup is failing with this  **error=" timed out waiting for all PodVolumeBackups to complete"**.   I have added  --restic-timeout=1440m in velero deployment and tried to take backup. But still, I am getting the same error.

**What did you expect to happen:**
The backup should work without a timeout error.

**Environment:**

- Velero version (use `velero version`): v1.9.1
- Velero features (use `velero client config get features`): not set
- Kubernetes version (use `kubectl version`):v1.24.6
- Kubernetes installer & version:
- Cloud provider or hardware configuration:Azure
- OS (e.g. from `/etc/os-release`): linux/amd64

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by allenxu404** [comment]
Restic timeout error can result from many issues, e.g., volume size and network connection. Could you provide us with velero debug logs to narrow down the issues?
