### ISSUE TITLE
Unsuccessful deletebackuprequests should timeout

### ISSUE THREAD

**Issue by jemag** [vmware-tanzu/velero#6042]
**Describe the problem/challenge you have**
Currently it seems that if a backup is not able to be deleted, the `deletebackuprequest` will simply get stuck `InProgress` and the `backup` itself will be stuck in `Deleting`

This scenario was tested for example by removing velero's service principal (Azure) permissions to delete snapshots, and `deletebackuprequests` stay `InProgress`. For example, difference in `deletebackuprequests` stuck between 2023-03-24 and 2024-03-26:
![image](https://user-images.githubusercontent.com/7985687/228053922-b211bf7e-de84-4ea2-93cb-c6151a050cd1.png)
where we can see that new `deletebackuprequests` are added and none are removed, while they are all stuck `InProgress`.

**Describe the solution you'd like**
I would like for the `deletebackuprequest` to eventually timeout according to a specific/customizable time instead of just looping indefinitely. 

Basically, it could look something like:
- `deletebackuprequest` times out after X time
- `deletebackuprequest` phase now becomes `Failed`
- Increment the metric counter `velero_backup_deletion_failure_total`
- (Potentially also change `backup` phase from `Deleting`?)
- Once in the `Failed` phase, the `deletebackuprequest` should be able to be restarted by the administrator, so that it can once again try to delete the backup within X amount of time

**Anything else you would like to add:**
The problem with the current approach is that it just seems to loop indefinitely and also it will never increment `velero_backup_deletion_failure_total` which might be misleading to administrators, since administrators might expect to be notified by having alerts set on `velero_backup_deletion_failure_total` which never triggers.

**Environment:**

- Velero version (use `velero version`):
```
Client:
        Version: v1.10.2
        Git commit: 7416504e3a8fea40f78bbc4cfefc7c642aafc812
Server:
        Version: v1.10.2
```

- Kubernetes version (use `kubectl version`): v1.24.6
- Kubernetes installer & version: Helm, chart version 3.1.4
- Cloud provider or hardware configuration: AKS
- OS (e.g. from `/etc/os-release`):
 ```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by allenxu404** [comment]
Checked the code and found that backup_deletion_controller had already set the timeout to ensure every deletebackuprequests will be deleted after surviving for 24 hours.
Could you double-check if there's any error logs saying the failure of deleting deletebackuprequests?

**Comment by jemag** [comment]
I don't believe I noticed anything particular in the logs except the forbidden errors since I removed permissions, but I will re-do the test case to be sure (will take some time).

---
That being said @allenxu404 , in the meantime, isn't that 24h timeout only if the phase is "Processed"?:
https://github.com/vmware-tanzu/velero/blob/f031121214b0db421c51ee96e8f52460192f0387/pkg/controller/backup_deletion_controller.go#L129-L141

Sorry if I am missing something, I am fairly new to both Go and the Velero codebase.

**Comment by allenxu404** [comment]
@jemag Yes, you are right. I didn't notice that timeout only works for processed deletebackuprequests. Your concern is valid.

**Comment by reasonerjt** [comment]
@jemag 
I agree that we should make change that the dbr turns to failure and `velero_backup_deletion_failure_total` is increased, instead of stuck in "InProgress"

**Comment by reasonerjt** [comment]
@jemag 

I tried to reproduce the problem on AWS by removing the permission of deleting snapshot from my service account, but I found the Phase of dbr will end up being `Processed`:

```
k describe deletebackuprequests jt-bak-snapshot-2-k5f7f -n velero
Name:         jt-bak-snapshot-2-k5f7f
Namespace:    velero
Labels:       velero.io/backup-name=jt-bak-snapshot-2
              velero.io/backup-uid=2ab5500c-bb44-4baa-a7be-4cd71c81257e
Annotations:  <none>
API Version:  velero.io/v1
Kind:         DeleteBackupRequest
Metadata:
.......
  Backup Name:  jt-bak-snapshot-2
Status:
  Errors:
    error deleting snapshot snap-00d6fbc8f0e6b7b46: rpc error: code = Unknown desc = UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: ifS9jxQWV3PvZLG9yT_uDoxEstScqS7B1Y4hKgqRYvEuKbMeMHZrQoHsmn1HhQDWH7ksXdRGYhsWMkPIyGckv_I78IzY7GkR1epK4us4IqTaBkaMKUDJPAml-cRB46G2TJ05ifD2pq2Xq8LJTv_oMTLcM6poGnKFzQWIhQiXFekynik8NERj97L8zBiOmYKZO7nWQS9KOvsROCMlk_8JjmJruk1S6cJGwFfp9QoNnFb0gBCfYgifyIVryPL0DK9Vv4JwiyDsKJgrB739tiWF0c11Tkj6IUziriMUNmA6znlXXyOiUe0vP76Ia1pM0rTuTX0n0tLyiH5zowXnMLk8fjixI9c1R12FBCdR_H6pygjl3-WrVQCZ-9YHBe3FgqJr7SgcTqbEeOv3x8QDkcUBv5VH1VbJKAorFDBPEVfCYoxlNz5CaH2KwwrWdb6ybwwd8ybD4xpKdY7w1UsFf23b3SgamA6ZIHPcLaC-e8SSX7dykl1xj5z77SMk52Gx2IiVtPYPngys1Iqee6g0i0uV0sq078YRT1X_6u1KkxKQHk6KBze24JxFAisldFhxrVgrKE9iXOY0Gm5QLBEZZpKSO8v1CCxMset8nkdENZChge3-QA6FI4L-ZShjfwAU_FeBn3XR9A7Lv0NMTe5itqQd3_t5Z0taNHnT55gIXCLUCXC54hle1qzNFMktTYuxmb8tzeRu08fUdb0_1aR6Ebx9x0uLVGEppgNBvz6jdQj-OYLY2YPCrEHBDb-rN0MyvMtG3PTNAVzLEO2S18z4heo_qcBBYSz7I6hZRolq05a-ZjlqfcwfqjhDwQd8tCowuxVVweAfLE6Kb89vyfHiVLSLh-02weVqRhMnIzi9sZbQJTuXse_pu1j9yF2Rw4K3WUw_dPZ_Vd4koUvsusPrrChVgaL7GrGp-rrCfK7RM1FN8UtpYBrLF8M_L2e9p0SGg48w9DdlwWg8VadMWt_wKrECoP5Luheg6BuL8MLoSYqGNoxHFh7ziqX-QidMiO23ZTiT_UF-IboHQXjcrwRtlzgBHn-9zDUzx973mTCh9v-S4Ca-zpiD60lq6lxOW69bc5T6MD1Ce1XXlmIcQ7In5LsZMJFy3GHFEoyL2lQfHdmwxT043pNTgP5p31aP3Z4
          status code: 403, request id: 4265ae88-91d6-45ae-8c12-925c19e453e8
  Phase:  Processed
Events:   <none>
```

Checked the code and if velero fails to delete the snapshot, the dbr should still be patched to `Processed` status:
https://github.com/vmware-tanzu/velero/blob/release-1.10/pkg/controller/backup_deletion_controller.go#L304
https://github.com/vmware-tanzu/velero/blob/release-1.10/pkg/controller/backup_deletion_controller.go#L362

Could you try to reproduce the problem and see what's blocking the dbr to be updated to `Processed` ?
I think it's probably OK to let the controller delete expired dbr that is in `InProgress` status but I'm curious what's the root cause on your env that the dbr is stuck in `InProgress`.

**Comment by jemag** [comment]
sorry been pretty busy lately, will try to reproduce soon
