### ISSUE TITLE
Allow certain StorageClasses to be ignored for CSI snapshots

### ISSUE THREAD

**Issue by ctrox** [vmware-tanzu/velero#6051]
**Describe the problem/challenge you have**
Currently the [CSI plugin](https://github.com/vmware-tanzu/velero-plugin-for-csi) just creates a snapshot of all PVCs if their StorageClass has a matching SnapshotVolumeClass based on the provisioner field. This can be problematic for CSI drivers which support different kinds of volumes and not all of them support snapshots. One example for this is the [Nutanix CSI driver](https://portal.nutanix.com/page/documents/details?targetId=CSI-Volume-Driver-v2_6:csi-csi-plugin-storage-c.html) which supports BlockStorage volumes with snapshot support and NFS volumes without snapshot support but they both use the same provisioner `csi.nutanix.com`. What happens now is that Velero will just try to snapshot these NFS PVCs and they just never get ready.

**Describe the solution you'd like**
One idea would be to add a label to the StorageClass to tell the CSI plugin to ignore PVCs of this class.

**Environment:**

- Velero version (use `velero version`):
```
Client:
        Version: v1.10.2
        Git commit: -
Server:
        Version: v1.10.0
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by qiuming-best** [comment]
hello @ctrox,  I'm unsure about our new feature [resource policies](https://velero.io/docs/main/resource-filtering/#resource-policies) could meet your requirement?

we can define the NFS volume source for PV in the resource policies configmap to skip the backup of PV.

**Comment by ctrox** [comment]
Yeah that feature could work, is it also possible to have a resource policy configured in a schedule?

**Comment by qiuming-best** [comment]
> Yeah that feature could work, is it also possible to have a resource policy configured in a schedule?

Yes, also it works for schedule.

**Comment by reasonerjt** [comment]
Closing this one since it's already been delivered in v1.11.

Please open a new issue if you discover any problem
