### ISSUE TITLE
Error while running maintenance on a BackupRepository (restic)

### ISSUE THREAD

**Issue by pbrissaud** [vmware-tanzu/velero#6052]
**What steps did you take and what happened:**
Since 4 days, my scheduled backup are partially failed with errors with restic backup on one special backup repository. I saw this error : 

```
pod volume backup failed: error creating uploader: failed to connect repository: error running command=restic snapshots --repo=gs:xxx:/restic/yyy --password-file=/tmp/credentials/velero-operator/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic --latest=1, stdout=, stderr=unable to create lock in backend: repository is already locked exclusively by PID 894 on velero-7f654b9cf9-tt8kw by nonroot
```

But I saw too multiple warnings when velero tries to running maintenance taks on the same backupRepo : 

```
time="2023-03-29T11:25:29Z" level=info msg="Running maintenance on backup repository" backupRepo=velero-operator/airwealth-default-restic-xhqrz logSource="pkg/controller/backup_repository_controller.go:191"
time="2023-03-29T11:25:29Z" level=debug msg="Pruning repo" backupRepo=velero-operator/airwealth-default-restic-xhqrz logSource="pkg/controller/backup_repository_controller.go:195"
time="2023-03-29T11:25:33Z" level=debug msg="enqueueing resources ..." logSource="pkg/util/kube/periodical_enqueue_source.go:71" resource="*v1.BackupStorageLocationList"
time="2023-03-29T11:25:33Z" level=debug msg="skip enqueue object velero-operator/default due to the predicate." logSource="pkg/util/kube/periodical_enqueue_source.go:92" resource="*v1.BackupStorageLocationList"
time="2023-03-29T11:25:40Z" level=debug msg="Ran restic command" command="restic prune --repo=gs:af-velero-prod:/restic/airwealth --password-file=/tmp/credentials/velero-operator/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic" logSource="pkg/repository/restic/repository.go:121" repository=airwealth stderr= stdout="loading indexes...\nloading all snapshots...\nfinding data that is still in use for 60 snapshots\n"
time="2023-03-29T11:25:40Z" level=warning msg="error pruning repository" backupRepo=velero-operator/airwealth-default-restic-xhqrz error="error running command=restic prune --repo=gs:af-velero-prod:/restic/airwealth --password-file=/tmp/credentials/velero-operator/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic, stdout=loading indexes...\nloading all snapshots...\nfinding data that is still in use for 60 snapshots\n, stderr=: signal: killed" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/restic/repository.go:123" error.function="github.com/vmware-tanzu/velero/pkg/repository/restic.(*RepositoryService).exec" logSource="pkg/controller/backup_repository_controller.go:197"
```

Here's what I try to fix this : 
- scale velero deployment to 0 
- delete lock file 
- running `restic check` locally => no error
- running `restic prune` locally  => no error / no data deleted
- running `restic rebuild-index` locally  => no error
- re-running `restic check` locally => no error
- running `restic unlock` locally to be sure => ok
- scale velero deployment to 1
- Same issues  

I can't find why it works locally but not when velero runs it. It only happens on this backup repo. I tried also to increase requested resource in Kubernetes deployment but it has no effect. 

**What did you expect to happen:**

Maintenance tasks run with no error + backup works aswell 
or at least clear explaination on why `restic prune`  failed 

**Environment:**

- Velero version (no change since 2 months): 
```
Client:
	Version: v1.10.2
	Git commit: -
Server:
	Version: v1.10.0
```
- Velero features : `features: <NOT SET>`
- Kubernetes version : 
```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14-gke.1800", GitCommit:"1eab5b8da4acab130c72aea21eb7ed3e96523ca2", GitTreeState:"clean", BuildDate:"2022-12-07T09:32:46Z", GoVersion:"go1.17.13b7", Compiler:"gc", Platform:"linux/amd64"}
``` 
- Kubernetes installer & version: Helm3 with ArgoCD 
- Cloud provider or hardware configuration: GKE

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by mydoomfr** [comment]
I'm currently dealing with the same issue and managed to resolve the situation using `--remove-all` restic flag which removes all locks, even non-stale ones. So be careful using it and ensure you don't have any backup in progress.

```
unable to create lock in backend: repository is already locked exclusively by PID 191470 on velero-7bf7846555-jx5t9 by nobody (UID 65534, GID 65534)\nlock was created at 2023-04-04 12:07:58
```

```console
restic unlock --remove-all
repository 20a93aaa opened (repository version 2) successfully, password is correct
successfully removed locks
```

Now, you can prune. And don't forget to run a `check` to confirm you have no missing parts.

I'm not sure about the root-cause; It seems a previous velero pod created restic lock and the new velero pod can't remove old lock or don't even try to...

**Comment by pbrissaud** [comment]
Hi @mydoomfr , thanks for your reply. 

I tried what you told me but unfortunately it still doesn't work (all commands work fine but still have the error on velero)

I believe the restic repo is locked because the maintenance task is failing on velero side but don't know why.

**Comment by Lyndon-Li** [comment]
This is a known issue, see #5276.

- As the current behavior of Restic, it creates some exclusive locks during some operation, i.e., maintenance, if the repo is exclusively locked, all other operation are blocked.
- As the current behavior of Velero, it checks the the repo for maintenance periodically, and if the last maintenance fails, it starts a new one at once.

As a result, if the maintenance keeps failing, the repo will keeps being locked.

Two solutions here:
1. Find the cause of the maintenance failure and fix it. Here I see the failure of the maintenance is due to a OOM. If your repo data size is relatively large, Restic prune will take lots of memory during running. Therefore, to fix the problem, you can increase the request limit of Velero server pod
2. If you cannot increase the memory, since you are running Velero 1.10, suggest you try the Kopia path, where Kopia won't add any lock to the repo. For how to change path, see [here](https://velero.io/docs/v1.10/file-system-backup/#how-velero-integrates-with-kopia:~:text=integration%20for%20details.-,Path%20selection,-Velero%E2%80%99s%20FSB%20supports)

**Comment by pbrissaud** [comment]
Hi @Lyndon-Li , 

Thanks for your answer ! I raised the memory request / limit to 2Gi and the error is gone. I will check the next backups. 

Seems to be a high resource consumption for only 2 volumes (50Go + 8Go).

**Comment by omlet05** [comment]
We had same issue after our last upgrade. And a lot of backups failed.

On my side, in a container deployment. I think that a restic prune should restart the whole velero container and not only be killed.
As the lock file is blocking all new backup tasks to be achieved.
