### ISSUE TITLE
Resource policy of skip all PV's provisioned CSI  is not effective

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#6054]
**What steps did you take and what happened:**
Backing up workload with PV provisioned by CSI driver, and apply a resource policy (skip all volumes) on it,  but PV was backed up, it seems resource policy as below is not effective.

### PV
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: ebs.csi.aws.com
    velero.io/original-pv-name: pvc-04d92f25-a317-4d85-a493-da8227fb2c36
    volume.kubernetes.io/provisioner-deletion-secret-name: ""
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
  creationTimestamp: "2023-03-30T07:53:54Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/ebs-csi-aws-com
  labels:
    velero.io/backup-name: backup-storage-class-all-pods-csi-3
    velero.io/restore-name: backup-storage-class-all-pods-csi-3-20230330075350
  name: velero-clone-7c865a31-5ece-4dbc-aa80-b26a89671778
  resourceVersion: "78266"
  uid: b3529e0f-3981-4e20-8d4b-fce001fa3125
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: ebs-claim
    namespace: skip-csi-test-restore
    resourceVersion: "78263"
    uid: 4c989409-081f-498b-941e-531fec6f8362
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1680159776272-8081-ebs.csi.aws.com
    volumeHandle: vol-02736b44156ed41f0
```
### Backup
```
backup=backup-csi-skip-1-pv-10

velero create backup $backup \
--include-namespaces skip-csi-test-restore \
--storage-location default \
--resource-policies-configmap  cm-csi-skip-all-pv \
--wait
Backup request "backup-csi-skip-1-pv-10" submitted successfully.
Waiting for backup to complete. You may safely press ctrl-c to stop waiting - your backup will continue in the background.
..
Backup completed with status: Completed. You may check for more information using the commands `velero backup describe backup-csi-skip-1-pv-10` and `velero backup logs backup-csi-skip-1-pv-10`.
```
### Resource Policy Configmap
```
k get cm -n velero cm-csi-skip-all-pv -o yaml
apiVersion: v1
data:
  cm-csi-skip-all-pv.yaml: |+
    version: v1
    volumePolicies:
    - conditions:
        csi: {}
      action:
        type: skip
    - conditions:
        storageClass:
        - standard
      action:
        type: skip

kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-30T09:19:43Z"
  name: cm-csi-skip-all-pv
  namespace: velero
  resourceVersion: "97115"
  uid: 6abfc065-fa4c-46f5-8d1b-9b6563e2de54
```

**What did you expect to happen:**

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
Close it as it already fixed
