### ISSUE TITLE
Automated Velero performance testing enhancement

### ISSUE THREAD

**Issue by qiuming-best** [vmware-tanzu/velero#6088]
- [ ] Write script pipeline for Automated performance test
- [ ] Performance test code frame 
- [ ] Add test cases
- [ ] Output test result include resource usage and time consuming

**Describe the problem/challenge you have**

Currently, our performance testing cannot be automated. We need to be able to automate our testing, add test cases, generate target test data based on different Velero version features, improve the metric display, and generate performance reports.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
Will determine later as we wanna ensure the delivery of data mover in v1.12 timeframe.

**Comment by mordechai** [comment]
@qiuming-best  I wasn't able to find them in the e2e  or tests folder of the velero repository.  Where can one find the performance tests that need to be automated?  I would be happy to be in touch and contribute to this effort.  Please let me know where I might find more information about these tests.

**Comment by qiuming-best** [comment]
@mordechai Thanks a lot.

Currently, We don't have the performance tests, we already have the E2E test, and UT test, but we don't have the performance test, we are planning to add performance tests in Velero.

we want to have one pipeline similar to the E2E test, adding some test cases similar to E2E. Also, we need to have one generated report to show (CPU, Memory, Disk, etc. )resource usage and time cost.

We want to cover some cases to backup / restore  that cover:
lots of little files test in one pod volumes
lots of pods in one namespace
lots of namespaces with one pod and one
Large file in one pod volume 

@mordechai Any ideas or suggestions?  I'm really glad if you could be involved in this performance test feature

**Comment by qiuming-best** [comment]
now only https://github.com/vmware-tanzu/velero/issues/6502 is opened, and it has one unique issue opened, I'll close this
