### ISSUE TITLE
Schedule management with Helm - Cannot delete schedules

### ISSUE THREAD

**Issue by GeiserX** [vmware-tanzu/velero#6090]
**What steps did you take and what happened:**
I have been testing in more than 10+ clusters and whenever I want to modify the name OR delete the schedule via my `values.yaml` file in Helm, the setting is not respected in the cluster.

**What did you expect to happen:**
I expected the old schedule to be removed.

**Anything else you would like to add:**
I'm using helmfile for the management of Helm releases, and I can clearly see the Schedule object is being removed from Kubernetes in the `helmfile diff` I issue, but then, somehow, the schedule still appears after executing `helmfile apply`. It is appearing both in Velero CLI `velero get schedules` AND when doing `kubectl get schedules`, although this correlation is expected.

**Environment:**

- Velero version (use `velero version`):  1.10.0
- Velero features (use `velero client config get features`):  NOT SET
- Kubernetes version (use `kubectl version`): Different on all clusters, usually 1.23
- Cloud provider or hardware configuration: GKE and EKS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
@DrumSergio Are you using [velero helm repo ](https://github.com/vmware-tanzu/helm-charts)?

If you are doing one upgrade operation, our velero helm repo does not support deleting existing schedules.

**Comment by DrumSergio** [comment]
Hi @qiuming-best , thanks for reaching out.

I'm using in fact `helmfile apply` which internally it's doing a `helm sync`. I'm using as you said, [the official repo](https://artifacthub.io/packages/helm/vmware-tanzu/velero).

Why is it not supported? I can see the Kubernetes objects disappear in the `helmfile diff`. I believe this should be supported, I had many clusters to update and I had to do double the work to delete old schedules dangling.
