### ISSUE TITLE
Multi-namespace-mapping E2E test hit patch endpointslices failure issue frequently

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#6103]
**What steps did you take and what happened:**

Backup 2 namespaces and each namespace has several service resource instances, and restore the 2 namespaces to different  2 namespaces by namesapce-mapping  param, test failed sometime. All this case failure happened on Azure env.

```
ime="2023-04-09T14:11:51Z" level=error msg="error patch for managed fields ns-mp-279a4f698-12e1-4690-88f2-c03966008333/etcd-client-hgh9n: endpointslices.discovery.k8s.io \"etcd-client-hgh9n\" not found" logSource="pkg/restore/restore.go:1516" restore=velero/ns-mp-1ns-mp-279a4f698-12e1-4690-88f2-c03966008333
time="2023-04-09T14:11:51Z" level=info msg="Restored 51 items out of an estimated total of 56 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:669" name=etcd-client-hgh9n namespace=ns-mp-279a4f698-12e1-4690-88f2-c03966008333 progress= resource=endpointslices.discovery.k8s.io restore=velero/ns-mp-1ns-mp-279a4f698-12e1-4690-88f2-c0
```

This issue should be related to PR #6057

**What did you expect to happen:**

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
Fixed by https://github.com/vmware-tanzu/velero/pull/6136, https://github.com/vmware-tanzu/velero/pull/6110 and https://github.com/vmware-tanzu/velero/pull/6135
