### ISSUE TITLE
CSI backup/restore to FS backup/restore fails

### ISSUE THREAD

**Issue by eemcmullan** [vmware-tanzu/velero#6106]
**What steps did you take and what happened:**

- Completed backup/restore with CSI snapshotting enabled
- Complete new FS backup of previously restored volumes from CSI snapshot
- Restore from FS backup 
- Restore fails as PVR never completes, and PVC remains pending with event:

```
failed to provision volume with StorageClass "gp2-csi": error getting handle for DataSource Type VolumeSnapshot by Name velero-mssql-pvc-v787x: error getting snapshot velero-mssql-pvc-v787x from api server: volumesnapshots.snapshot.storage.k8s.io "velero-mssql-pvc-v787x" not found
```

PVC dataSourceRef is reset here: https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/main/internal/restore/pvc_action.go#L71-L81 

Could implement a check for volumes previously restored from CSI, and reset this field again if needed.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment]
I'm wondering whether we should always strip dataSourceRef when saving PVCs. That would resolve this issue, but are there any use cases where we need that in the backup? For CSI use cases, that's set by the CSI restore plugin, so we probably don't need it there.

**Comment by eemcmullan** [comment]
One way to resolve this issue is to clear this field on each backup, as a PVC using a volumeSnapshot as a dataSource is reset during CSI restore. We can utilize the current PVC BIA here to do so. 
PR: https://github.com/vmware-tanzu/velero/pull/6111

**Comment by weshayutin** [comment]
- [ ] openshift/velero:konveyor dev
  - [ ] https://github.com/openshift/velero/pull/257
- [ ]  openshift/velero:oadp-1.1
