### ISSUE TITLE
Volume Snapshot Data Movement - CSI plugin working mode

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#6116]
Support working mode transition and handle the two modes appropriately in CSI plugin:

- Moving snapshot data
- Not moving snapshot data (existing behavior)

**Comment by blackpiglet** [comment]
Fixed by PRs:
https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/181
https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/184
