### ISSUE TITLE
CSI plugin should support backup migrated PVCs

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#6137]
**Describe the problem/challenge you have**

CSI plugin judges a PVC whether is a CSI one by it has a CSI section in SPEC.

https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/5ee80604e580295e9afea51fcf73765b070a9ca7/internal/backup/pvc_action.go#L82-L85

This will rule out the migrated PVC.

**Describe the solution you'd like**

Need a new way to also handle the migrated PVCs.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by anshulahuja98** [comment]
I am not sure if migrated PVCs can be snapshotted by the external snapshotter.
it is not fully clear to me what this issue is meant to tackle.

**Comment by blackpiglet** [comment]
CSI migration is a k8s feature. It's already enabled by default in most of the cloud providers. It means even if PVC declares to use an in-tree volume driver, the k8s cluster still migrates it to the related CSI driver.
The PV generated from CSI migration PVC has some differences from normal CSI PV. It doesn't have a CSI section in spec, but it has a `pv.kubernetes.io/migrated-to` annotation.

https://github.com/vmware-tanzu/velero/issues/5149#issuecomment-1207318947
This link contains some related documents.

**Comment by anshulahuja98** [comment]
yeah
thanks for updating the thread with the issue link
It is a major limitation of CSI for in tree.

**Comment by anshulahuja98** [comment]
We can delink the 1.12 milestone
