### ISSUE TITLE
Update Velero Azure plugin to support AzureDNSZone storageaccount

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#6163]
Currently, the Velero Azure plugin [hardcodes the storage service URLs for different Azure clouds](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/v1.7.0-rc.1/velero-plugin-for-microsoft-azure/common.go#L87), but this isn't always true according to https://techcommunity.microsoft.com/t5/azure-storage-blog/public-preview-create-additional-5000-azure-storage-accounts/ba-p/3465466, we need to update the Velero Azure plugin to address this issue.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
Talked with @anshulahuja98, We will fix the issue with the following approach:
1. Introduce new SA-URI field
2. if SA URI is provided - we attempt to use it, otherwise we do GetProperties to fetch?
[Here my assumption is that almost all common roles that users would have used - would already have /reader permission on SA to do the GET call]
3. But let's say if GetPropeties fails(no permissions) - we fallback to the URL forming mechanism ([xxx.windows.core.net](http://xxx.windows.core.net/))
4. This approach will not lead to any breaking issue for existing users(since we fallback to URL forming) - and for new users we are always smart enough to do GetProperties() without them having to pass URI.
5. In case of power users where we wish to skip the GetProperties call due to ARM throttling - users can pre set the SA URI.

**Comment by anshulahuja98** [comment]
As discussed with @ywk253100 , consider this issue assigned to me.

**Comment by anshulahuja98** [comment]
The plan is also to add a field "UseAAD" to explicitly use AAD. The intention is to maintain current ListKeys behavior. Switching to AAD for BSL will be an opt in feature.
This is because the current ListKeys and AAD approach has different set of permissions required. So migration has to take place over time.
