### ISSUE TITLE
Bump up the version of velero's CRs

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#6168]
We have been adding new features and new fields to the `v1` CRDs.
Although they are backward compatible, it's probably not a very good exercise constantly make changes to the `v1` API.  Considering we have also planned some breaking changes to the schema in the CRDs, like deprecating and removing Restic, removing the redundant filters, we need to have a plan for bumping up the version of CRDs. (for example v1 -> v2alpha1)

This issue is opened to track the decisions and discussions around this topic.

**Comment by sseago** [comment]
We need to be careful to make sure that backups made with v1 CRDs will still restore in versions of vleero using v2alpha1 CRDs. This might mean supporting both CRD versions at once, or it might mean converting the v1 velero CRD yaml from the BSL (backup metadata, pod volume backups, etc.) into v2 before creating the resource.
