### ISSUE TITLE
Error running command=restic prune

### ISSUE THREAD

**Issue by tosnoah** [vmware-tanzu/velero#6169]
**What steps did you take and what happened:**

Velero installed via CLI : 

velero install \
    --provider azure \
    --plugins velero/velero-plugin-for-microsoft-azure:v1.6.1 \
    --bucket velero \
    --secret-file .credentials-velero \
    --backup-location-config resourceGroup=xxx,storageAccount=xxxx \
    --snapshot-location-config apiTimeout=2m,resourceGroup=xxxx,subscriptionId=xxxxx-xxx--xxx--xxxx \
    --default-volumes-to-fs-backup \
    --use-node-agent 

After a Kubernetes upgrade to 1.25.6 from 1.24.9, my velero restic backups are not working anymore. I have a lock issue which prevents applying the restic commands. 

  
![Bildschirm­foto 2023-04-19 um 15 00 43](https://user-images.githubusercontent.com/121792205/233357998-0777456f-8cd3-4b61-9ac0-ece4d22d9480.png)

Things i have tried so far: 

- raised the memory/cpu limit
- Fresh install velero

**What did you expect to happen:**

Restic backups should not fail.

**The following information will help us better understand what's going on**:

Here is my support bundle:
[bundle-2023-04-20-13-48-06.tar.gz](https://github.com/vmware-tanzu/velero/files/11285814/bundle-2023-04-20-13-48-06.tar.gz)

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  1.10.2
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): 1.25.6
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Azure Kubernetes Service
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
@tosnoah 
The problem was due to `stderr=: signal: killed`, the most probable cause is the restic process was killed due to OOM. Therefore, you can increase the memory limit of Velero pod, but how much more memory is needed is not predictable, it depends on the repo data size, snapshot numbers, etc.

**Comment by Lyndon-Li** [comment]
Closing as no further request, feel free to reopen it if required.
