### ISSUE TITLE
Velero stuck with backup in "Phase:  InProgress"

### ISSUE THREAD

**Issue by ZrytyADHD** [vmware-tanzu/velero#6170]
**What steps did you take and what happened:**
Trying to do backup with:
velero backup create tkg-test

**What did you expect to happen:**
Backup to complete

**The following information will help us better understand what's going on**:

Velero version 1.11.0
Client 1.11.0
Kubernetes version v1.23.8 Tanzu

Enviroment apps:
projectcontour from yaml
Prometheus-comunity-stack installed with helm
cert-manager from yaml

Storage: vSAN
Icluding 3 PV, PVS used by Prometheus-comunity-stack

Error log:
`time="2023-04-21T14:45:22Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/0/1)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:194"
time="2023-04-21T14:46:17Z" level=error msg="error updating backup's final status" backuprequest=velero/tkg-test controller=backup error="Backup.velero.io \"tkg-test\" is invalid: status.phase: Unsupported value: \"Finalizing\": supported values: \"New\", \"FailedValidation\", \"InProgress\", \"Completed\", \"PartiallyFailed\", \"Failed\", \"Deleting\"" logSource="pkg/controller/backup_controller.go:311"
time="2023-04-21T14:49:31Z" level=error msg="error updating backup's final status" backuprequest=velero/tkg-test controller=backup error="Backup.velero.io \"tkg-test\" is invalid: status.phase: Unsupported value: \"Finalizing\": supported values: \"New\", \"FailedValidation\", \"InProgress\", \"Completed\", \"PartiallyFailed\", \"Failed\", \"Deleting\"" logSource="pkg/controller/backup_controller.go:311"
`

Editing manualy yaml from backup from InProgress to Completed give me ability to finish backup.
`  metadata: {}
  storageLocation: default
  ttl: 720h0m0s
status:
  expiration: '2023-05-21T14:49:09Z'
  formatVersion: 1.1.0
  phase: InProgress
  startTimestamp: '2023-04-21T14:49:09Z'
  version: 1
`

Storage location is MiniO with TLS on Rhel 9.1
I test on other clear cluster and backup working properly. 
With older version 1.6.1 backup work without problem.

**Comment by iusergii** [comment]
Same issue with Azure StorageAccount

**Comment by ZrytyADHD** [comment]
I test it on other cluster with the same installed app packages and configs from 1st post. 
Everything work fine.
Velero 1.11 
Plugin 1.7.0
So this is not problem with PV and PVCs on vSAN.
Also i check psp policy restircted and priviligied there is no any changes with anyone of them.

**Comment by Lyndon-Li** [comment]
Helm chart for v1.11 is not release yet, so need to manually upgrade the CRDs as mentioned by @bitspire-ci

**Comment by Lyndon-Li** [comment]
Closing as resolved
