### ISSUE TITLE
AuthorizationPermissionMismatch after upgrading to Velero 1.11 and Azure Plugin 1.7

### ISSUE THREAD

**Issue by stromvirvel** [vmware-tanzu/velero#6180]
**What steps did you take and what happened:**

We're running Velero 1.10.2 and with Azure Plugin v1.6.1 perfectly fine. We have the cloud-credentials file mounted to the velero pod. The cloud-credentials contains credentials of a Service Account that has enough permissions to take disk snapshots and write permissions to the Storage Account.

This is the BackupStorageLocation

```yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  creationTimestamp: null
  labels:
    component: velero
  name: default
  namespace: kube-velero
spec:
  provider: azure
  default: true
  objectStorage:
    bucket: k8s-group
  config:
    resourceGroup: core-prod
    storageAccount: redacted
```

After upgrading CRDs to 1.11.0, velero to 1.11.0 and azure plugin to 1.7.0, the velero pod shows the following error:

```bash
time="2023-04-24T13:26:57Z" level=error msg="fail to validate backup store" backup-storage-location=kube-velero/default controller=backup-storage-location error="rpc error: code = Unknown desc = GET https://redacted.blob.core.windows.net/k8s-group\n--------------------------------------------------------------------------------\nRESPONSE 403: 403 This request is not authorized to perform this operation using this permission.\nERROR CODE: AuthorizationPermissionMismatch\n--------------------------------------------------------------------------------\n\ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:36128c6a-e01e-003d-67b0-76197c000000\nTime:2023-04-24T13:26:57.8854736Z</Message></Error>\n--------------------------------------------------------------------------------\n" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/persistence/object_store.go:198" error.function="github.com/vmware-tanzu/velero/pkg/persistence.(*objectBackupStore).IsValid" logSource="pkg/controller/backup_storage_location_controller.go:155"
```

So apparently, velero cannot properly authenticate anymore to the Storage Account, despite no changes to the Service Account's permission were done. Rolling back the changes makes velero functional again.

**What did you expect to happen:**

Velero 1.11.0 and azure plugin 1.7.0 would take the Service Principal to authenticate against the Storage Account as it did with the previous version.

**Environment:**

- Velero version (use `velero version`): v1.11.0
- Velero features (use `velero client config get features`):  not set
- Kubernetes version (use `kubectl version`): 1.24.6

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
@stromvirvel Which way did you use to authenticate Azure according to https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#set-permissions-for-velero? We did some refactoring in v1.11 timeframe for the Azure plugin, there may be regressions introduced by the changes. Appreciate if you could provide more information for us to locate the root cause

**Comment by aolmosj** [comment]
Hi. I'm facing the same error after upgrading the velero helm chart from 2.32.2 (Velero 1.9, azure plugin 1.5.2)to 4.0.1 (Velero 1.11, azure plugin 1.7).

I had to downgrade velero helm chart to 3.1.6 (velero 1.10.2) and the azure plugin to 1.6.1, and there is no auth errors anymore.

**Comment by HansK-p** [comment]
We also had the same issue. Seems the permission "Storage Blob Data Contributor" is needed on the backup storage account. It might be more permissions are also needed (we haven't finalized troubleshooting).

**Comment by stromvirvel** [comment]
@ywk253100 We are using Service Principal as authentication. This is used to authenticate against the AzureRM API to take the snapshots, as well as to get access to the Storage Account. The Service Principal has "Contributor" role on the Storage Account which seemed fine until v1.11. Anyhow, it does not have "Storage Blob Data Contributor" as stated by @HansK-p.

Is it possible that the refactoring requires a particular role set to the Storage Account, other than "Contributor"?

**Comment by ywk253100** [comment]
@stromvirvel @aolmosj @HansK-p Please set `subscription` in the `BackupStorageLocation` to work around this issue at this moment. 
I think this is caused by https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/v1.7.0/velero-plugin-for-microsoft-azure/object_store.go#L260

**Comment by stromvirvel** [comment]
@ywk253100 I'm afraid I don't really understand. Where do we set anything related to subscription within the `BackupStorageLocation` custom resource? Neither in the [docs](https://velero.io/docs/v1.11/api-types/backupstoragelocation/) nor in the CRD I could find anything that points out I could define the subscription. Can you please elaborate?

**Comment by stromvirvel** [comment]
@ywk253100  Thank you! Seems to work perfectly fine now. No errors, and also the storage account contains metadata of a backup test I've created.

**Comment by HansK-p** [comment]
Thx. Works for us too. We still have some issues with PV snapshots after the Velero upgrade, but they do not belong in this ticket.
