### ISSUE TITLE
v1.10 and later - Pod volume backup keeps partial failing for namespaces with pods in completed state

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#6182]
From v1.10, pod volume backup will fail earlier if node-agent pod is not running in the same node where the backing up pod is running, instead of waiting until timeout (by default, 4 hours). Therefore, it does more checks about the status of backing up pod and node-agent pod. However, the checks involves an unnecessary behavior change -- if the backing up pod is not running, that pod volume backup will be marked as fail and the entire backup goes to partially failure.

This will cause the pod volume backup to namespaces with pods in completed status to keep failing.

**Comment by Lyndon-Li** [comment]
Close as completed

**Comment by karan1ngit** [comment]
when will 1.11.1 be released?
