### ISSUE TITLE
backups marked as partially failed, but backups are working

### ISSUE THREAD

**Issue by akshaysgithub** [vmware-tanzu/velero#6186]
Hello,

I am installing Velero via a helm chart with custom values. I can see I have backups getting created in GCP Cloud Storage. But all backups are marked with Partially Failed. The logs indicate no log.warn or log.error. I spent hours looking for it. I saw this issue here: https://github.com/vmware-tanzu/velero/issues/6182
I am also not running any NodeAgent. Can that be the case? 

Helm chart set values: 

`
  set {
    name  = "configuration.backupStorageLocation.name"
    value = "default"
  }

  set {
    name  = "configuration.backupStorageLocation.bucket"
    value = var.velero_bucket_name
  }

  set {
    name  = "metrics.podAnnotations.ad\\.datadoghq\\.com/velero\\.check_names"
    value = "[\"openmetrics\"]"
  }

  set {
    name  = "metrics.podAnnotations.ad\\.datadoghq\\.com/velero\\.init_configs"
    value = "[{}]"
  }

  set {
    name  = "metrics.podAnnotations.ad\\.datadoghq\\.com/velero\\.instances"
    value = "[{ \"prometheus_url\": \"http://%%host%%:8085/metrics\"\\, \"namespace\" : \"${var.velero_namespace}\"\\, \"metrics\": [\"*\"] }]"
  }

 set {
    name  = "initContainers[0].name"
    value = "velero-plugin-for-gcp"
  }

  set {
    name  = "initContainers[0].image"
    value = "velero/velero-plugin-for-gcp:v1.1.0"
  }

  set {
    name  = "initContainers[0].imagePullPolicy"
    value = "IfNotPresent"
  }

  set {
    name  = "initContainers[0].volumeMounts[0].mountPath"
    value = "/target"
  }

  set {
    name  = "initContainers[0].volumeMounts[0].name"
    value = "plugins"
  }

  set {
    name  = "metrics.enabled"
    value = "true"
  }

  set {
    name  = "configuration.provider"
    value = "gcp"
  }

  set {
    name  = "backupsEnabled"
    value = "true"
  }

  set {
    name  = "snapshotsEnabled"
    value = "false"
  }

  set {
    name  = "schedules.backup.schedule"
    value = "0 * * * *"
  }

  set {
    name  = "schedules.backup.template.ttl"
    value = "336h"
  }

  set {
    name  = "resources.requests.cpu"
    value = "1000m"
  }

  set {
    name  = "resources.requests.memory"
    value = "512Mi"
  }

  set {
    name  = "resources.limits.cpu"
    value = "2000m"
  }

  set {
    name  = "resources.limits.memory"
    value = "2048Mi"
  }
`

I had to increase cpu and memory, since I was going into OOM. Where can I find what's going wrong with PartiallyFailed backups?

Thanks a lot. :-)

**Comment by ywk253100** [comment]
Could you run `velero backup describe backup_name` and `velero backup logs backup_name` for the failed backup?
