### ISSUE TITLE
Investigate how to remove the generated legacy client-go code.

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#6190]
v1.12
- [x] Remove from `pkg/cmd` directory part 1 - #6469 
- [x] Remove from `pkg/cmd` directory part 2.

v1.13
- [x] Remove from `pkg/plugin` directory.
- [x] Remove from the rest directories.
- [x] Check with the community.
- [x] Record in the release note.

v1.15
- [ ] Remove the `pkg/generated` directory.
- [ ] Mention the change in the release note.

Backlog
- [ ] Update hack/test.sh to update the excluded packages.

**Describe the problem/challenge you have**

Since all Velero controllers already used the controller-runtime framework, Velero should consider whether to remove the legacy client-go code.
Investigate where those legacy codes are still used, and check whether it's possible to remove those codes.

**Describe the solution you'd like**

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
v1.12 planned tasks are already done.

**Comment by blackpiglet** [comment]
After discussion, the agreement is that the `pkg/generated` should be deprecated first, and then deleted.
The deprecation process is proposed by PR #5532. 
After PR #5532 is merged, I will follow that PR to start the deprecation process.

**Comment by blackpiglet** [comment]
Need to add this deprecation notice in the v1.13 release note.

**Comment by mateusoliveira43** [comment]
@blackpiglet thanks!

should [`pkg/plugin/generated`](https://github.com/vmware-tanzu/velero/tree/main/pkg/plugin/generated) directory also be removed, or just `pkg/generated` directory?

**Comment by blackpiglet** [comment]
We should keep the `pkg/plugin/generated` directory.
The protobuf binary generated the directory. That is not related to the go-client.

**Comment by blackpiglet** [comment]
@sseago @Lyndon-Li @mateusoliveira43 @shubham-pampattiwar @anshulahuja98 
Is this issue also applicable to the deprecation process?

**Comment by kaovilai** [comment]
If this is only dev facing, not user facing, it may not have to be as strict.

**Comment by blackpiglet** [comment]
OK.
I will create a PR to address this issue.

**Comment by sseago** [comment]
Also, we  did deprecate this in 1.13:
```
* The generated k8s clients, informers, and listers are deprecated in the Velero v1.13 release. They are put in the Velero repository's pkg/generated directory. According to the n+2 supporting policy, the deprecated are kept for two more releases. The pkg/generated directory should be deleted in the v1.15 release.
```
The one thing we didn't do was vote on it in an issue, but I think that's fine here. We're still following the more important part which is deprecating 2 releases before removal, especially as @kaovilai said, since this isn't a user-facing feature.
