### ISSUE TITLE
Velero Auth Failing For Azure Govcloud, Velero Appears To Be Choosing Wrong Cloud

### ISSUE THREAD

**Issue by gwynforthewyn** [vmware-tanzu/velero#6196]
**What steps did you take and what happened:**
I created an azure backup resource group, and within that backup resource group I created a storage account and a blob store within that account.

I created a credentials file, and used this command from the docs to install the velero azure plugin:

```bash
export BLOB_CONTAINER=<the blob container>
export AZURE_BACKUP_RESOURCE_GROUP=<the resource group that owns the azure disks backups> 
export AZURE_STORAGE_ACCOUNT_ID=<the id>


velero install \
    --provider azure \
    --plugins velero/velero-plugin-for-microsoft-azure:v1.7.0 \
    --bucket $BLOB_CONTAINER \
    --secret-file ./credentials-velero.txt \
    --backup-location-config resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID \
    --snapshot-location-config apiTimeout=30m,resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP
```

Inside my secrets file I have these variables set:

```
AZURE_SUBSCRIPTION_ID=<my subscription id>
AZURE_TENANT_ID=<my tenant ID>
AZURE_CLIENT_ID=<service principal client id>
AZURE_CLIENT_SECRET=<client secret>
AZURE_RESOURCE_GROUP=<the resource group that owns the azure disks backups> 
AZURE_CLOUD_NAME=AZUREUSGOVERNMENT
```

Note AZUREUSGOVERNMENT.

Velero installs, but then emits these errors:

```
time="2023-04-25T14:46:36Z" level=error msg="Error listing backups in backup store" backupLocation=velero/default controller=backup-sync error="rpc error: code = Unknown desc = GET https://qabackups.blob.core.windows.net/qaaks\n--------------------------------------------------------------------------------\nRESPONSE 401: 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header.\nERROR CODE: InvalidAuthenticationInfo\n--------------------------------------------------------------------------------\n\ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidAuthenticationInfo</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.\nRequestId:b81fac00-501e-0059-7b84-776f6c000000\nTime:2023-04-25T14:46:36.7666370Z</Message><AuthenticationErrorDetail>Issuer validation failed. Issuer did not match.</AuthenticationErrorDetail></Error>\n--------------------------------------------------------------------------------\n" logSource="pkg/controller/backup_sync_controller.go:107"
time="2023-04-25T14:46:36Z" level=error msg="fail to validate backup store" backup-storage-location=velero/default controller=backup-storage-location error="rpc error: code = Unknown desc = GET https://qabackups.blob.core.windows.net/qaaks\n--------------------------------------------------------------------------------\nRESPONSE 401: 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header.\nERROR CODE: InvalidAuthenticationInfo\n--------------------------------------------------------------------------------\n\ufeff<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidAuthenticationInfo</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.\nRequestId:17c2bf3c-e01e-0011-6484-77725b000000\nTime:2023-04-25T14:46:36.8627388Z</Message><AuthenticationErrorDetail>Issuer validation failed. Issuer did not match.</AuthenticationErrorDetail></Error>\n--------------------------------------------------------------------------------\n" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/persistence/object_store.go:198" error.function="github.com/vmware-tanzu/velero/pkg/persistence.(*objectBackupStore).IsValid" logSource="pkg/controller/backup_storage_location_controller.go:155"
time="2023-04-25T14:46:36Z" level=info msg="BackupStorageLocation is invalid, marking as unavailable" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:131"
```

**What did you expect to happen:**

The govcloud variable does not seem to be respected. The URL for our blob store should be:

> qabackups.blob.core.usgovcloudapi.net

But instead it is set to:

> qabackups.blob.core.windows.net

I checked the velero cloud-credentials secret and validated that `AZURE_CLOUD_NAME=AZUREUSGOVERNMENT` is set correctly.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
```
velero version
Client:
	Version: v1.11.0
	Git commit: -
Server:
	Version: v1.11.0
```
- Velero features (use `velero client config get features`): 
```
velero client config get features
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"08d3594304660f86cfbd17bbb862041b4b75fe6c", GitTreeState:"clean", BuildDate:"2023-02-08T17:22:59Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
AKS
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by gwynforthewyn** [comment]
@ywk253100  I've figured this out. There's a docs bug or a code bug or a combination of the two.

The installation instructions for this plugin state that you should put the AZURE_CLOUD_NAME environment variable in the credentials file. This is in the README  on line 260 (https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/README.md?plain=1#L250).

On line 336 of the the object_store.go  file (https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/velero-plugin-for-microsoft-azure/object_store.go#L336), the function `getStorageAccountKey` is called. This function (cf https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/velero-plugin-for-microsoft-azure/object_store.go#L229 for implementation) loads environment variables from the credentialsFile, for authentication purposes and this includes the AZURE_CLOUD_NAME variable per the installation instructions.


But! Earlier in the object_storage controller file on line 326 (https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/velero-plugin-for-microsoft-azure/object_store.go#L326), a comment that AZURE_CLOUD_NAME is being checked by cloudFromName, and the result is assigned to the cloudConfig variable. At this point in the file, the AZURE_CLOUD_NAME variable is nil. 

The behavior in the cloudFromName function is that if `os.Getenv(cloudNameEnvVar)` is an empty string then the public cloud is the default value in the case statement for evaluating clouds. For most users, this is going to be correct, but for folks using govcloud this means that cloudConfig gets initialized with public cloud endpoints, which won't work.

I'm trying a patch out to fix this behavior. Hopefully I can get that attached to this issue within the next hour or two.


_However_,

**Comment by gwynforthewyn** [comment]
@ywk253100 I've opened a PR. I extracted the logic that loads environment variables from the `getStorageAccountKey` function into its own separate function and call that function early in `Init`. Whether you'd like to merge this PR or not, it should illustrate one approach to fixing things.

**Comment by gwynforthewyn** [comment]
@ywk253100 checking in - is there anything I can be doing to help get the PR to fix this merged?

**Comment by epruettFTE** [comment]
@ywk253100 Any chance for ETA when or if this will be merged?

**Comment by gwynforthewyn** [comment]
The PR for this issue has been merged. Once the velero-plugin-for-azure is released with the fix present, I should be able to validate the fix from upstream and close this issue.

**Comment by ywk253100** [comment]
@gwynforthewyn Thanks for the fix!

The fix should already be included in the dev image: `velero/velero-plugin-for-microsoft-azure:main`, you should be able to validate the fix with this image.

I'm going to close this issue, feel free to reopen it if you find any other issues.
