### ISSUE TITLE
FSB metrics: Add additional labels

### ISSUE THREAD

**Issue by iusergii** [vmware-tanzu/velero#6205]
**Describe the problem/challenge you have**
I would like to monitor FSB backup time duration. I'm using kopia for FSB and I can see following metrics:
- pod_volume_operation_latency_seconds
- pod_volume_operation_latency_seconds_gauge

But there is no label which I can use to visualise the backup time trend. Current labels (backupName, operation, pod_volume_backup) are unique. 

**Describe the solution you'd like**
Add additional labels for aggregation - kopis/restic repo name, etc.

**Anything else you would like to add:**
The `latency` string in current metrics is quiet confusing. Is it really corresponds to the name ?  

**Environment:**
- Velero version: `v1.11.0`
- Kubernetes version : `v1.25.5`
- Kubernetes installer & version: `helm`

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by allenxu404** [comment]
Sorry for the delayed reply. IMHO, the current metrics already meet the need you expect. 

`pod_volume_operation_latency_seconds` partitions the latencies in second of completing each FSB  into buckets, and counts the number of letancy that fall into each bucket. Histograms allow you to see how the latencies are distributed across different buckets, which can help to see the trend of backup time taken for FSB.

`pod_volume_operation_latency_seconds_gauge` provides you with the view to monitor FSB backup duration in different senario by presenting latency in second with different labels to be chosen. 

`kopia/restic` repo name can be added as a label in these metrics but I think they may not be helpful in achieving your goal.
