### ISSUE TITLE
Backup Status shows completed while there are failed podvolumebackups

### ISSUE THREAD

**Issue by enpace** [vmware-tanzu/velero#6212]
**What steps did you take and what happened:**

We are running a backup with 122 volumes that we backup via restic. Some include postgres databases, some of these fail for some reason that is not relevant here.

The backup shows **Phase: Completed**

**What did you expect to happen:**

I expect the backup to show **Phase:  PartiallyFailed**

**Anything else you would like to add:**

**Environment:**

- Velero version: 1.11
- Kubernetes version: v1.23.12 (OCP 4.10)
- Cloud provider or hardware configuration: Azure

**Comment by ywk253100** [comment]
@enpace Could you provide the logs of the backup with the `velero debug` command?

**Comment by enpace** [comment]
> @enpace Could you provide the logs of the backup with the `velero debug` command?

Sorry, I cannot, it contains confidential information. but I see that also line 98 of backupper.go is triggered (for every PVC):

```golang
	log.Errorf("No results channel found for pod %s/%s to send pod volume backup %s/%s on", pvb.Spec.Pod.Namespace, pvb.Spec.Pod.Name, pvb.Namespace, pvb.Name)
```
I am now running a velero version built directly from the main branch, and the problem seems to have gone away. It may make sense to wait a little and then clonse this issue.

**Comment by Lyndon-Li** [comment]
Closing as the problem has been resolved. If required, feel free to reopen this issue.
