### ISSUE TITLE
Setting volumes to exclude via backup.velero.io/backup-volumes-excludes

### ISSUE THREAD

**Issue by derekmceachern** [vmware-tanzu/velero#6215]
**Describe the problem/challenge you have**
When testing the annotation `backup.velero.io/backup-volumes-excludes` and specifying multiple volumes the 1.10 documentation indicated

```
backup.velero.io/backup-volumes-excludes=YOUR_VOLUME_NAME_1,YOUR_VOLUME_NAME_2,...
```

I inadvertently used the following:

```
backup.velero.io/backup-volumes-excludes=YOUR_VOLUME_NAME_1, YOUR_VOLUME_NAME_2
```

Note the space between volume 1 and 2. In my instance it excluded volume 1 from the backup as expected but included volume 2.

**Describe the solution you'd like**
Not sure if this is done on purpose but I would like to see this ignore whitspace in volume names and exclude everything listed.

**Environment:**

- Velero version (use `velero version`): v1.9.6
- Kubernetes version (use `kubectl version`): 1.23.8
- Kubernetes installer & version: Tanzu v1.6
- Cloud provider or hardware configuration: 
- OS (e.g. from `/etc/os-release`): Photon

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
From the code, this is the correct behavior, but I also think your suggestion is also valid. k8s labels values don't allow whitespace, so trimming them is also reasonable.
