### ISSUE TITLE
backup-storage-location is not deleting in from velero bucket via velero CLI

### ISSUE THREAD

**Issue by sureshbanyal** [vmware-tanzu/velero#6220]
**What steps did you take and what happened:** 

I have installed velero client and server in my EKS cluster using this 
```
velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.6.0 \
    --bucket mybucketname \
    --backup-location-config region=us-west-2 \
    --snapshot-location-config region=us-west-2 \
    --secret-file ./credentials-velero \
    --use-node-agent \
    --default-volumes-to-fs-backup
```
Again I have created backuplocation inside mybucketname subdirectory using this command 
```
velero backup-location create subdirectory \
		   --provider aws \
		   --bucket mybucketname \
		   --prefix subdirectory
```
 

i have deleted that folder using this command 
```
velero delete backup-location subdirectory
```
, but when i use this command it shows me `An error occurred: find Restic repositories associated with BSL "subdirectory": no matches for kind "ResticRepository" in version "velero.io/v1"`

**What did you expect to happen:**

Sub folder need to delete when i delete using above commands it should delete from my s3 bucket, please have a look quick and let me know quick. need installation guidence as well

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
 recommended way to install velero installation  

**Environment:**

- Velero version (use `velero version`): Client:
        Version: v1.10.2
        Git commit: 7416504e3a8fea40f78bbc4cfefc7c642aafc812
Server:
        Version: v1.10.2

- Velero features (use `velero client config get features`): Client:
        Version: v1.10.2
        Git commit: 7416504e3a8fea40f78bbc4cfefc7c642aafc812
Server:
        Version: v1.10.2

- Kubernetes version (use `kubectl version`): Client Version: v1.24.11-eks-a59e1f0 
- Server Version: v1.24.12-eks-ec5523e
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible" Yes
- :-1: for "There are more important bugs to focus on right now"

**Comment by shubham-pampattiwar** [comment]
@sureshbanyal The command which you are trying to run will not delete your s3 sub-folder, `backup-location` in the command refers to the Velero Custome Resource `BackupStorageLocation` that you configured during the velero install time. For more details please refer `velero delete backup-location --help`.

**Comment by sureshbanyal** [comment]
i used this command too `velero backup-location delete subfolder --confirm` Oops this also not working showing same error 

An error occurred: find Restic repositories associated with BSL "banyalas15-ns": no matches for kind "ResticRepository" in version "velero.io/v1"  i didnot use --default-volumes-to-restic  flag it shows me this error 
**Error: unknown flag: --default-volumes-to-restic**

**Comment by sureshbanyal** [comment]
@shubham-pampattiwar  could you please provide the installation commands see i have downloaded using this docs [https://github.com/vmware-tanzu/velero-plugin-for-aws] (url) downloaded successfully but when i try to delete any storage location which i have created inside my s3 bucket its throwing me this error in jenkins pipeline **An error occurred: find Restic repositories associated with BSL "banyalas19-ns": no matches for kind "ResticRepository" in version "velero.io/v1"** i am requesting anyone immediately respond and assist provide recommended way of installation pod volumes should also need to take backup and needed to restore, once again requesting for immediate response thank you so much.

**Comment by blackpiglet** [comment]
`An error occurred: find Restic repositories associated with BSL "subdirectory": no matches for kind "ResticRepository" in version "velero.io/v1"`

`ResticRepository` is a deprecated Velero resource in v1.10, because `ResticRepository` is replaced with `BackupRepository`. I think you didn't update the CRD definition during the Velero version upgrade from v1.9.x to v1.10.x.

Please follow this document for the Velero version upgrade: https://velero.io/docs/v1.10/upgrade-to-1.10/.

**Comment by sureshbanyal** [comment]
@blackpiglet  i would like to install velero newly with out upgrading please provide document where i need to follow and how to resolve this issue i have already uninstalled from my cluster by using this commands `kubectl delete namespace/velero clusterrolebinding/velero
kubectl delete crds -l component=velero` i will start freshly please assist me thank you.

**Comment by blackpiglet** [comment]
This is the document you need: https://velero.io/docs/v1.10/upgrade-to-1.10/.

**Comment by blackpiglet** [comment]
Velero v1.11.0 was released latest. You can have a try.
I think your previous installation command line is right. Just needs to update plugin version and the Velero CLI version.

```
velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.7.0 \
    --bucket mybucketname \
    --backup-location-config region=us-west-2 \
    --snapshot-location-config region=us-west-2 \
    --secret-file ./credentials-velero \
    --use-node-agent \
    --default-volumes-to-fs-backup
```

Please take this document as a reference.
https://velero.io/docs/v1.11/customize-installation/

And better to uninstall with `velero uninstall` command. This is the `velero uninstall` command's code.  

``` go
// Run removes all components that were deployed using the Velero install command
func Run(ctx context.Context, kbClient kbclient.Client, namespace string) error {
	// The CRDs cannot be removed until the namespace is deleted to avoid the problem in issue #3974 so if the namespace deletion fails we error out here
	if err := deleteNamespace(ctx, kbClient, namespace); err != nil {
		fmt.Printf("Errors while attempting to uninstall Velero: %q \n", err)
		return err
	}

	var errs []error

	// ClusterRoleBinding
	crb := install.ClusterRoleBinding(namespace)
	key := kbclient.ObjectKey{Name: crb.Name}
	if err := kbClient.Get(ctx, key, crb); err != nil {
		if apierrors.IsNotFound(err) {
			fmt.Printf("Velero ClusterRoleBinding %q does not exist, skipping.\n", crb.Name)
		} else {
			errs = append(errs, errors.WithStack(err))
		}
	} else {
		if err := kbClient.Delete(ctx, crb); err != nil {
			errs = append(errs, errors.WithStack(err))
		}
	}

	// CRDs

	veleroLabelSelector := labels.SelectorFromSet(install.Labels())
	opts := []kbclient.DeleteAllOfOption{
		kbclient.InNamespace(namespace),
		kbclient.MatchingLabelsSelector{
			Selector: veleroLabelSelector,
		},
	}
	v1CRDsRemoved := false
	v1crd := &apiextv1.CustomResourceDefinition{}
	if err := kbClient.DeleteAllOf(ctx, v1crd, opts...); err != nil {
		if meta.IsNoMatchError(err) {
			fmt.Println("V1 Velero CRDs not found, skipping...")
		} else {
			errs = append(errs, errors.WithStack(err))
		}
	} else {
		v1CRDsRemoved = true
	}

	// Remove any old Velero v1beta1 CRDs hanging around.
	v1beta1crd := &apiextv1beta1.CustomResourceDefinition{}
	if err := kbClient.DeleteAllOf(ctx, v1beta1crd, opts...); err != nil {
		if meta.IsNoMatchError(err) {
			if !v1CRDsRemoved {
				// Only mention this if there were no V1 CRDs removed
				fmt.Println("V1Beta1 Velero CRDs not found, skipping...")
			}
		} else {
			errs = append(errs, errors.WithStack(err))
		}
	}

	if kubeerrs.NewAggregate(errs) != nil {
		fmt.Printf("Errors while attempting to uninstall Velero: %q \n", kubeerrs.NewAggregate(errs))
		return kubeerrs.NewAggregate(errs)
	}

	fmt.Println("Velero uninstalled ⛵")
	return nil
}
```

**Comment by sureshbanyal** [comment]
@blackpiglet i have installed velero using above command for latest version before install i have complete uninstall velero but it shows me same error `+ /usr/local/bin/velero backup-location delete banyalas30-ns
Are you sure you want to continue (Y/N)? Backup storage location "banyalas30-ns" deleted successfully.
Backup associated with deleted BSL(s) "banyalas30-ns-20230505001901" deleted successfully.
An error occurred: find Restic repositories associated with BSL "banyalas30-ns": no matches for kind "ResticRepository" in version "velero.io/v1"
[Pipeline] }
[kubernetes-cli] kubectl configuration cleaned up` 
my velero version after freshly installed `velero version
Client:
        Version: v1.11.0
        Git commit: 0da2baa908c88ec3c45da15001f6a4b0bda64ae2
Server:
        Version: v1.11.0` cloud you please provide installation command, without using restic i want to install velero. i hope i will not get that error if i didnot take restic backup. My requirement is take backups and keep them inside s3 bucket of their respective folder than delete those via cli without any error if not required i need this please provide command thanks.

**Comment by blackpiglet** [comment]
@sureshbanyal 

https://github.com/vmware-tanzu/velero/blob/release-1.9/pkg/cmd/cli/backuplocation/delete.go#L133-L139
https://github.com/vmware-tanzu/velero/blob/release-1.11/pkg/cmd/cli/backuplocation/delete.go#L133-L139

I think the error is still reported from v1.9.x Velero binary. Please check the code I post above. You can find out the v1.9.x `velero backup-location delete` sub-command will try to find `ResticRepository` associated with the backup.
In v1.11.x, `velero backup-location delete` sub-command will try to `BackupRepository` instead.

Please check whether `/usr/local/bin/velero` this CLI version is also v1.11.0.

**Comment by blackpiglet** [comment]
Close for now. Feel free to reopen if your issue is not resolved.
