### ISSUE TITLE
Does velero support Wasabi s3 

### ISSUE THREAD

**Issue by bittu664** [vmware-tanzu/velero#6221]
Hello velero team , i want to backup my  k8s cluster into wasabi s3 storage , but i didint see any kind of docs for this also there is no plugins for wasabi s3 , so how i can take a backup for this. my k8s cluster is runing on the hetzner cloud. pls guide me for this.

**Comment by blackpiglet** [comment]
Although I didn't try Wasabi cloud storage with the Velero, per my understanding, it should work.

According to Wasabi document https://docs.wasabi.com/docs/working-with-buckets-and-objects, Wasabi cloud storage also have bucket and region setting.
You take this document as an example https://velero.io/docs/v1.11/contributions/minio/.

The provider is also set to AWS. The bucket name is set to your created one and set the `--backup-location-config` according to your environment accordingly.

```yaml
velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.2.1 \
    --bucket velero \
    --secret-file ./credentials-velero \
    --use-volume-snapshots=false \
    --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://minio.velero.svc:9000
```

**Comment by bittu664** [comment]
hello @blackpiglet  i have sucesfully installed velero in my k8s cluster using wasabi storage. here i want to backup my namespace with its pvc but unfortunally its only takes only partial backup it take my pvc volumes. so here what to do , and how to fix this issues.

i used this command to do backup :- 
```
velero backup create demo-backup --include-namespaces okst
```
<img width="1420" alt="Screenshot 2023-05-04 at 12 16 22 AM" src="https://user-images.githubusercontent.com/28609215/236014095-d0c025f2-97e1-42a0-ae73-0e0b30603a7e.png">

<img width="1438" alt="Screenshot 2023-05-04 at 12 12 41 AM" src="https://user-images.githubusercontent.com/28609215/236013937-dfc542cc-1b51-450c-a257-09d1fd09cdf9.png">

**Comment by blackpiglet** [comment]
@bittu664 
You need to tell Velero to back up volumes with an integrated file system uploader.

If you are using Velero older than v1.10, this can be done by `velero backup create demo-backup --include-namespaces okst --default-volumes-to-restic`.

If you are using Velero equal or newer than v1.10, this can be done by `velero backup create demo-backup --include-namespaces okst --default-volumes-to-fs-backup`.

**Comment by blackpiglet** [comment]
Close for now. Feel free to reopen if your issue is not resolved.
