### ISSUE TITLE
velero with restic on-premesis

### ISSUE THREAD

**Issue by vadlakiran** [vmware-tanzu/velero#6224]
**What steps did you take and what happened:**
i have tried to install velero with restic installtion on my on-premises kubernetes cluster but we don't have cloud or minio option to store a backup data, we would like to store the backup data on local file system/ directory.

i have tried to give dummy credentials and and deployed the velero with restic but when i created the backuplocation its not verified as we have given the local directory.
how we can proceed if we don't have the cloud or minio s3 we have on-premises ubunut vanilla kuberenetes cluster installed by kubespray.

**What did you expect to happen:**
I want store a backup of pvc and cluster data into the local directory, please let me know if any plugins are supporting with this requirement and please help to do this.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  v1.7.0
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**
i have tried with hostpath option and got the plugin from below location but still backupstoragelocation  status is unavailable. due to that not able to take a backup
https://github.com/replicatedhq/local-volume-provider/

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
- NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by vadlakiran** [comment]
below is the output of the get pods of velero and restic:

`
NAME                      READY   STATUS    RESTARTS   AGE restic-6htj5              1/1     Running   0          13h restic-89tzb              1/1     Running   0          13h restic-ww9qr              1/1     Running   0          13h velero-6979cbd56b-bmtq9   1/1     Running   0          13h
NAME              PROVIDER   BUCKET/PREFIX               PHASE     LAST VALIDATED   ACCESS MODE   DEFAULT default           noop       local--use-restic           Unknown   Unknown          ReadWrite     true my-local-backup   local      /velero-backup/pvc_backup   Unknown   Unknown          ReadWrite`

if i have used hostpath plugin below is the status of the backupstoragelocation.

`
velero backup-location get
NAME      PROVIDER                  BUCKET/PREFIX                       PHASE         LAST VALIDATED                  ACCESS MODE   DEFAULT
default   replicated.com/hostpath   hostpath-snapshots//velero-backup   Unavailable   2023-05-03 11:23:38 +0530 IST   ReadWrite     true
:~$
`

**Comment by blackpiglet** [comment]
Velero needs an S3-compatible object storage system to work.
https://velero.io/docs/v1.10/locations/#overview

If MinIO and cloud storage are not available, could you set up another S3-compatible service in your on-premise k8s cluster, for example, Longhorn?

**Comment by vadlakiran** [comment]
we don't have Longhorn, we have pvc solution for rook-ceph.
can we create  blob on nexus repo and can use as storagelocation right ?

**Comment by vadlakiran** [comment]
@blackpiglet  i have installed minio one standalone linux vm and i would like to use as backupstorage and i have installed velero with credenitals but its not able to connect minio bucket giving below error.

An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = InvalidArgument: S3 API Requests must be made to API port.
        status code: 400, request id: , host id:

**Comment by vadlakiran** [comment]
@blackpiglet i have changed the port but still getting the same issue, seems to be a bug

**Comment by blackpiglet** [comment]
Could you post more information about your installation?

Need to know the Velero installation commands and the logs. Also, need to know whether MinIO is accessible from the Velero pod.

**Comment by vadlakiran** [comment]
Hi @blackpigle, below command i have used to install the velero

`
velero install \
 --provider aws \
 --plugins velero/velero-plugin-for-aws:v1.4.0 \
 --bucket velero2 \
 --secret-file ./credentials-velero  \
 --use-volume-snapshots=true \
 --backup-location-config region=default,s3ForcePathStyle="true",s3Url=http://locahost:9000 \
 --image velero/velero:v1.4.0  \
 --snapshot-location-config region="default" \
 --use-restic`

**Comment by vadlakiran** [comment]
velero pod logs

time="2023-05-05T05:20:05Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:177"
time="2023-05-05T05:20:05Z" level=info msg="Starting Velero server v1.4.0 (5963650c9d64643daaf510ef93ac4a36b6483392)" logSource="pkg/cmd/server/server.go:179"
time="2023-05-05T05:20:05Z" level=info msg="1 feature flags enabled []" logSource="pkg/cmd/server/server.go:181"
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-remap-version
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pv-from-pvc
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/add-pvc-from-pod
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-pvc-node-selector
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/change-storage-class
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/cluster-role-bindings
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/crd-preserve-fields
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/role-bindings
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service-account
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2023-05-05T05:20:05Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2023-05-05T05:20:05Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:361" namespace=velero
time="2023-05-05T05:20:05Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:367" namespace=velero
time="2023-05-05T05:20:08Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:396"
time="2023-05-05T05:20:13Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:430"
time="2023-05-05T05:20:13Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:437"
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = RequestError: send request failed
caused by: Get "http://locahost:9000/velero1?delimiter=%2F&list-type=2&prefix=": dial tcp localhost:9000: connect: connection refused

**Comment by vadlakiran** [comment]
@blackpiglet  could you please suggest what might be the issue

**Comment by blackpiglet** [comment]
This is an example. You may need to check whether the region setting is correct. By my testing, the working region is `minio`.
And also suggest using a newer version of Velero. v1.11.0 of Velero was just released.

```
velero install \
--provider aws \
--plugins velero/velero-plugin-for-aws:main \
--image velero/velero:main \
--bucket velero \
--backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://minio.minio.svc:9000 \
--snapshot-location-config region=minio \
--secret-file=$HOME/Documents/credentials/credentials-velero-minio
```

**Comment by vadlakiran** [comment]
i am enabeling the restic because we want to take a volumesnapshot/pvc backup of on premises kubernetes cluster, without restic velero will support to take volumesnapshot or pvc bakcup ?

**Comment by blackpiglet** [comment]
Oh, I forgot this is an on-premise environment. Of course, Restic is needed.

**Comment by vadlakiran** [comment]
@blackpiglet i have executed the command which you provided below is the velero logs

`
/kiran/velero/velero$ kubectl get pods -n velero
NAME                      READY   STATUS   RESTARTS   AGE
velero-6d89944d8b-lcrcx   0/1     Error    0          31s
:~/kiran/velero/velero$ kubectl logs -f velero-6d89944d8b-lcrcx -n velero
time="2023-05-05T08:51:30Z" level=info msg="setting log-level to INFO" logSource="pkg/cmd/server/server.go:186"
time="2023-05-05T08:51:30Z" level=info msg="Starting Velero server main (4db1a781fc6745424ccb53c3548a04bf9379b237-dirty)" logSource="pkg/cmd/server/server.go:188"
time="2023-05-05T08:51:30Z" level=info msg="1 feature flags enabled []" logSource="pkg/cmd/server/server.go:190"
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/crd-remap-version
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/pod
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/pv
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/service-account
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/add-pv-from-pvc
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/add-pvc-from-pod
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/admission-webhook-configuration
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/apiservice
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/change-image-name
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/change-pvc-node-selector
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/change-storage-class
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/cluster-role-bindings
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/crd-preserve-fields
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/init-restore-hook
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/job
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/pod
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/pod-volume-restore
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/role-bindings
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/secret
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/service
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/service-account
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/aws
time="2023-05-05T08:51:30Z" level=info msg="registering plugin" command=/plugins/velero-plugin-for-aws kind=ObjectStore logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/aws
time="2023-05-05T08:51:31Z" level=info msg="Metrics server is starting to listen" addr=":8080" logSource="/go/pkg/mod/github.com/bombsimon/logrusr/v3@v3.0.0/logrusr.go:108" logger=controller-runtime.metrics
time="2023-05-05T08:51:31Z" level=info msg="Checking existence of namespace." logSource="pkg/cmd/server/server.go:436" namespace=velero
time="2023-05-05T08:51:31Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:442" namespace=velero
I0505 08:51:33.755391       1 request.go:690] Waited for 1.045932887s due to client-side throttling, not priority and fairness, request: GET:https://10.233.0.1:443/apis/policy/v1beta1?timeout=32s
time="2023-05-05T08:51:35Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:471"
An error occurred: [custom resource BackupRepository not found in Velero API group velero.io/v1, Velero custom resources not found - apply examples/common/00-prereqs.yaml to update the custom resource definitions]
d:~/kiran/velero/velero$
`

**Comment by vadlakiran** [comment]
if your available on slack, can we connect ?

**Comment by blackpiglet** [comment]
I think this is due to the Velero server pod cannot reach the MinIO IP.
Sure. You can find me by searching `jxun@vmware.com`.

**Comment by blackpiglet** [comment]
Close for now. Feel free to reopen, if issue is not resolved.
