### ISSUE TITLE
Add documentation about `status-include-resources` and `status-exclude-resources`

### ISSUE THREAD

**Issue by mkemmerz** [vmware-tanzu/velero#6237]
**Describe the problem/challenge you have**
I found some tutorial about Velero where the flags were used but I was not able to find official documentation about the flags. I had to check the source code and CRD definitions to understand what the flags are doing.

**Describe the solution you'd like**
Velero offers documentation about the flags. They should describe what the status is doing and which sideeffects it might have.

Source Code reference: 
https://github.com/vmware-tanzu/velero/blame/main/pkg/cmd/cli/restore/create.go#L121
CRD reference: https://github.com/vmware-tanzu/velero/blob/15d44724e7911fc3294fc225d8311a3009d81e69/config/crd/v1/bases/velero.io_restores.yaml#L366

**Comment by reasonerjt** [comment]
I found actually there is information about `restoresStatus` in the doc about restore API:
https://velero.io/docs/v1.14/api-types/restore/

Will add a section in `Restore reference` in the doc.
