### ISSUE TITLE
Persist VolumeSnapshotContents before modifying the VolumeSnapshotRef

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#6242]
**Describe the problem/challenge you have**

Velero change the VolumeSnapshotContent's VolumeSnapshotRef information on purpose to cease the CSI snapshot controller reconciling and recreate the paired VolumeSnapshot, because Velero deletes the VolumeSnapshot to make sure the the namespace contains the VolumeSnapshot deletion not affect the snapshot data.

```
% cat bk-csi-1-csi-volumesnapshotcontents.json | jq '.[0].spec.volumeSnapshotRef'
{
  "namespace": "ns-5d03751b-284a-4882-ab01-7f36804bf6d0",
  "name": "name-5d03751b-284a-4882-ab01-7f36804bf6d0"
}
```

The modified VolumeSnapshotContents is persisted. It looks more reasonable to persist with the unmodified VolumeSnapshotContents instead.

**Describe the solution you'd like**

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by kaovilai** [comment]
cc: @eemcmullan @shubham-pampattiwar for awareness

**Comment by draghuram** [comment]
I think that leaving "VolumeSnapshotref" in volume snapshot content should not cause any problems when volume snapshot is deleted, because the behavior is controlled by "deletionPolicy". I haven't tested this explicitly though. 

Also, as per code, there is another change made to volume snapshot content other than snapshot ref. "source" field is also being set (to snapshot handle). Are you still going to keep that change or will that be removed as well?

**Comment by Aabhusan** [comment]
Hello guys @kaovilai @draghuram @blackpiglet @ncdc @aramprice 
can anyone of you guys heko me with this [issue](https://github.com/vmware-tanzu/velero/issues/6241)  ? :pray:

**Comment by blackpiglet** [comment]
After https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/177, CSI plugin uses BackupItemAction v2 instead of v1.

The VolumeSnapshotContents and VolumeSnapshots are backed up without modification, but due to the mechanism of async operation finalization, the data in <backup-name>-csi-volumesnapshot.*.json files are not guaranteed to be same with <backup-name>.tar.gz, because VolumeSnapshot and VolumeSnapshotContent are handled in the async operation of BIA v2. After all async operations completed, the Velero would persist the backup information according to the operations change, but Velero server will only handle the whole back data. It cannot tell the resource's type and put it into specific file.
As a result, the CSI related resources' change happens in the async operation running will not be synced into the  <backup-name>-csi-volumesnapshot.*.json files. By far, there is only one difference, VolumeSnapshot and VolumeSnapshotContent status's `ReadyToUse` is not updated to true.

**Comment by blackpiglet** [comment]
This issue is already fixed by PRs:
https://github.com/vmware-tanzu/velero/pull/6327
https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/177
