### ISSUE TITLE
Metrics for Scheduled Backups

### ISSUE THREAD

**Issue by frostydknight** [vmware-tanzu/velero#6265]
**Describe the problem/challenge you have**

Recently, I encountered an issue with a scheduled backup failing during the validation phase of the backup, resulting in no backup being taken. I resolved that issue but noticed that Velero hadn't incremented the velero_backup_validation_failure_total metric which caused us to never be alerted to the backup issue. I verified my connection to Velero using the troubleshooting steps found [here](https://velero.io/docs/v1.11/troubleshooting/), but it never seems to increment the metric, even when I force an error with a bad schedule. After bringing this up on the Velero-users slack, I was informed that the velero_backup_validation_failure_total metric is only set up to increment in the case of a validation failure on a "backup" resource.

**Describe the solution you'd like**

Ideally, I would like to see these metrics adjusted or new ones created that can appropriately capture the different kinds of backup failures that can occur when running a scheduled backup. So that when a scheduled backup fails during the validation phase it will increment the metric which we can use to alert us of the failure.

**Anything else you would like to add:**

Specific Error I saw and resolved, which we noticed wouldn't increment the metric when creating a backup through a schedule.

```
Phase:	FailedValidation

Validation Errors: Invalid included/excluded namespace lists: invalid namespace " velero": a lowercase RFC 1123 label must consist of a lowercase alphanumeric character or "-", and must start with an alphanumeric character (e.g. 'my-name'. or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')
Invalid included/excluded namespace lists: invalid namespace " kube-system": a lowercase RFC 1123 label must consist of a lowercase alphanumeric character or "-", and must start with an alphanumeric character (e.g. 'my-name'. or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')
```

**Environment:**

- Velero version (use `velero version`): 1.11.0
- Kubernetes version (use `kubectl version`): 1.23.5
- Kubernetes installer & version: helm
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
@frostydknight How did you create the schedule? I see the validation logic on the Velero CLI side, the request should be denied by CLI. Did you create the schedule by some other tools?

**Comment by frostydknight** [comment]
@ywk253100 I am creating the schedule via the helm chart, not the CLI.
