### ISSUE TITLE
Restic backups of persistentvolume are skipped during restore

### ISSUE THREAD

**Issue by CNLHC** [vmware-tanzu/velero#6266]
**What steps did you take and what happened:**

1. Create a backup with only pv and pvc included.
```
 velero backup create prometheus-backup10 \
    --selector app=prometheus  \
    --include-resources pvc,pv  \
    --include-namespaces apm \
    --wait
```

2. Check the backup and the pv and pvc are backed.

```
velero backup describe prometheus-backup10  --details -ojson | jq "{phase,"resourceList":.status.resourceList}"
{
  "phase": "Completed",
  "resourceList": {
    "v1/PersistentVolume": [
      "pvc-f19f0299-6036-4afd-8b89-2dad8b165832"
    ],
    "v1/PersistentVolumeClaim": [
      "apm/main-prometheus-server"
    ]
  }
}
```

3. create a restore on this backup. Notice that I have used the ` --include-cluster-resources ` flag

```
velero restore create restore-8  --from-backup  prometheus-backup10    \
    --namespace-mappings apm:apm-restored6 --wait \
    --include-cluster-resources 
```

4. check the restore status

```
velero restore describe restore-8 --details 

Phase:                       Completed
Total items to be restored:  3
Items restored:              3
Resource List:
  v1/Namespace:
    - apm-restored6(created)
  v1/PersistentVolume:
    - pvc-f19f0299-6036-4afd-8b89-2dad8b165832(skipped)
  v1/PersistentVolumeClaim:
    - apm-restored6/main-prometheus-server(created)
```

**What did you expect to happen:**

The backup data should be copied into the created pv. 

Actually, if I include the pod in the backup, then during restore, the pod will be created with an `init` container and the data will be copied into the `pv`. But If the pod was not included in the backup, the pv data restoring is totally skipped.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):   Version: v1.11.0 (both client and server,         Git commit: 0da2baa908c88ec3c45da15001f6a4b0bda64ae2)
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.25.7+k3s1
- Kubernetes installer & version:  k3s version v1.25.7+k3s1 (f7c20e23)
- Cloud provider or hardware configuration: self hosted k8s
- OS (e.g. from `/etc/os-release`): VERSION="22.04.1 LTS (Jammy Jellyfish)"

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
This is working as designed.
The Restic/Kopia backup/restore path is called podvolumebackup/podvolumerestore, in which case the data is populated via the "initcontainer" of the pod, therefore, you need to have the pod in the backup/restore workflow if you want the data populated during the restore.

**Comment by reasonerjt** [comment]
I'm closing this issue as a usage error.
