### ISSUE TITLE
Support for workload identity

### ISSUE THREAD

**Issue by asubmani** [vmware-tanzu/velero#6272]
**Describe the problem/challenge you have**
Enable support for [Federated identity/workload identity](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview)

**Describe the solution you'd like**
Pod identity is deprecated and AKS now uses "AKS workload Identity"

Please add steps to star using "workload identity" with Velero instead of podidentity.
Workload identity uses MSAL and does not rely on CRD like podidentity does.
https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview 
https://github.com/Azure/AKS/issues/1480

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by anshulahuja98** [comment]
Hi @asubmani 
We'll update the docs post this PR is checked in into Azure Plugin - https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/188

**Comment by anshulahuja98** [comment]
Already tracked as part of  https://github.com/vmware-tanzu/velero/issues/5116
