### ISSUE TITLE
Progress field is missing in status of backup CR

### ISSUE THREAD

**Issue by kkothule** [vmware-tanzu/velero#6275]
**What steps did you take and what happened:**
Ran backup using the below command
velero backup create demo-copy-16 --include-namespaces test-csi-snapshot

**What did you expect to happen:**
The output for for "velero backup get  demo-copy-16 -o yaml"  does not contain status.progress field

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

➜  external ./velero-1.11 backup describe demo-copy-16                                                           
Name:         demo-copy-16
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:  New

Namespaces:
  Included:  test-csi-snapshot
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  

Velero-Native Snapshot PVs:  auto

TTL:  0s

CSISnapshotTimeout:    0s
ItemOperationTimeout:  0s

Hooks:  <none>

Backup Format Version:  

Started:    <n/a>
Completed:  <n/a>

Expiration:  <nil>

Velero-Native Snapshots: <none included>

`➜  external ./velero-1.11 backup get demo-copy-19 -o yaml            
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/source-cluster-k8s-gitversion: v1.24.2
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "24"
  creationTimestamp: "2023-05-16T17:38:22Z"
  generation: 1
  labels:
    velero.io/storage-location: default
  managedFields:
  - apiVersion: velero.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:velero.io/source-cluster-k8s-gitversion: {}
          f:velero.io/source-cluster-k8s-major-version: {}
          f:velero.io/source-cluster-k8s-minor-version: {}
        f:labels:
          .: {}
          f:velero.io/storage-location: {}
      f:spec:
        .: {}
        f:csiSnapshotTimeout: {}
        f:defaultVolumesToFsBackup: {}
        f:hooks: {}
        f:includedNamespaces: {}
        f:itemOperationTimeout: {}
        f:metadata: {}
        f:storageLocation: {}
        f:ttl: {}
      f:status:
        .: {}
        f:completionTimestamp: {}
        f:csiVolumeSnapshotsAttempted: {}
        f:csiVolumeSnapshotsCompleted: {}
        f:expiration: {}
        f:formatVersion: {}
        f:phase: {}
        f:startTimestamp: {}
        f:version: {}
    manager: velero-server
    operation: Update
    time: "2023-05-16T17:38:22Z"
  name: demo-copy-19
  namespace: velero
  resourceVersion: "103477"
  uid: 44bc0db7-9c4f-4796-83c7-3449449d7e93
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: false
  hooks: {}
  includedNamespaces:
  - test-csi-snapshot
  itemOperationTimeout: 1h0m0s
  metadata: {}
  storageLocation: default
  ttl: 720h0m0s
status:
  completionTimestamp: "2023-05-16T15:35:34Z"
  csiVolumeSnapshotsAttempted: 2
  csiVolumeSnapshotsCompleted: 2
  expiration: "2023-06-15T15:35:03Z"
  formatVersion: 1.1.0
  phase: Completed
  startTimestamp: "2023-05-16T15:35:03Z"
  version: 1
`

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
Version: v1.11.0

- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):

1.24.2

- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by anshulahuja98** [comment]
Since when did this start breaking?
Or has it been like this forever?

**Comment by Evesy** [comment]
> Since when did this start breaking? Or has it been like this forever?

For us it stopped working between the 1.10 & 1.11 release

**Comment by kkothule** [comment]
> Since when did this start breaking? Or has it been like this forever?

We started seeing this since the 1.11 release
