### ISSUE TITLE
Backup Repo Reconciler performs too many requests

### ISSUE THREAD

**Issue by Yeicor** [vmware-tanzu/velero#6285]
**Describe the problem/challenge you have**
I am reaching the API request limits of my storage provider daily, due to the continuous checks of Velero for the availability of the BackupStorageLocation.

**Describe the solution you'd like**
A solution would be turning this constant into a configuration parameter (and a configurable value of the helm chart):

https://github.com/vmware-tanzu/velero/blob/b8910749d2d113f5ec64a461d19277529ba28e4a/pkg/controller/backup_repository_controller.go#L44-L45

It may be possible to also reduce the number of API calls performed on each check.

**Environment:**

- Velero version (use `velero version`): v1.11.0
- Kubernetes version (use `kubectl version`): v1.27.1
- Kubernetes installer & version: k3s v1.26.4+k3s1
- Cloud provider or hardware configuration: single Odroid N2+ node
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 11 (bullseye)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by allenxu404** [comment]
BackupRepositoryController won't interact with object storage, Instead, BackupsyncController will. 

So in your case, a possible approach to improve this for now is to create a new backup storage location by running `velero create backup-location -–backup-sync-period=` where option `backup-sync-period` sets the frequency at which velero interact with OS(default value is 1min). And then, you can set this backup storage location as default BSL.

I think the requirement of making this frequency configurable is valid.

**Comment by allenxu404** [comment]
what does 'storage provider' here refer to?

**Comment by Yeicor** [comment]
I use the free tier of [Backblaze](https://www.backblaze.com/) for my remote backups as they provide an S3 REST API. The limit I am reaching is the Daily Class C Transactions, which include the operations s3_get_location and s3_list_objects.

As the number of Class C Transaction increases continuously even though I only have one small nightly backup and I only use this Backblaze account for these backups, I assumed from the velero logs that the continuous checks for the availability of the BackupStorageLocation were the reason I reach the limits and can't access my files at the end of each day.

I don't know the reason why these checks are done periodically, but wouldn't it be better if they are done once right before each backup/restore? In any case, if I can change the frequency of these checks, it would be enough for my use case.

**Comment by allenxu404** [comment]
BackupRepositoryController won't interact with object storage, Instead, BackupsyncController will.

So in your case, a possible approach to improve this for now is to create a new backup storage location with the same configuration as default one by running `velero create backup-location -–backup-sync-period=<your desired frequency> <backup location name>` where option backup-sync-period sets the frequency at which velero interact with OS(default value is 1min). And then, you can set this backup storage location as default BSL by running `velero backup-location set –default  <backup location name>`.

**Comment by Yeicor** [comment]
Thanks! Setting the backup sync period definitely helped. It helped me enough to avoid hitting the daily limits.

However, the Velero server still performs requests every 5 minutes. Maybe it is due to the constant I initially mentioned, which runs the following code every 5 min.

https://github.com/vmware-tanzu/velero/blob/b8910749d2d113f5ec64a461d19277529ba28e4a/pkg/controller/backup_repository_controller.go#L183-L185

I will close this issue since the current behavior is good enough for me.
