### ISSUE TITLE
After running Restic filesystem backup CSI snapshot is present after backup completes.

### ISSUE THREAD

**Issue by dzaninovic** [vmware-tanzu/velero#6286]
**What steps did you take and what happened:**

Create minikube cluster and install addons:
```
$ minikube start -p velero-1.11 --kubernetes-version=1.25.2
$ minikube addons -p velero-1.11 enable csi-hostpath-driver
$ minikube addons -p velero-1.11 enable volumesnapshots

$ kubectl get sc
NAME                 PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-hostpath-sc      hostpath.csi.k8s.io        Delete          Immediate           false                  46s
standard (default)   k8s.io/minikube-hostpath   Delete          Immediate           false                  60s
```

Create a namespace, PVC and pod:
```
$ tee namespace.yaml << END
apiVersion: v1
kind: Namespace
metadata:
  name: test-csi-snapshot
END
$ kubectl apply -f namespace.yaml

$ tee csi-pvc.yaml << END
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
 name: csi-snapclass
 labels:
  velero.io/csi-volumesnapshot-class: "true"
driver: hostpath.csi.k8s.io
deletionPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
  namespace: test-csi-snapshot
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: csi-hostpath-sc
END
$ kubectl -n test-csi-snapshot apply -f csi-pvc.yaml

$ tee csi-app.yaml << END
kind: Pod
apiVersion: v1
metadata:
 name: my-csi-app
 namespace: test-csi-snapshot
spec:
 containers:
   - name: my-frontend
     image: busybox
     volumeMounts:
     - mountPath: "/data"
       name: my-csi-volume
     command: [ "sleep", "1000000" ]
     command: ["/bin/sh"]
     args: ["-c", "while true; do echo Ping>> /data/out.txt; sleep 300; done"]
 volumes:
   - name: my-csi-volume
     persistentVolumeClaim:
       claimName: csi-pvc
END
$ kubectl -n test-csi-snapshot apply -f csi-app.yaml
```

Install Velero v1.11 with AWS and CSI plugin:
```
BUCKET=mybucket
REGION=us-east-1
CREDENTIALS=velero-credentials

$ velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.7.0,velero/velero-plugin-for-csi:v0.3.0 \
    --bucket $BUCKET \
    --backup-location-config region=$REGION \
    --secret-file $CREDENTIALS \
    --uploader-type "restic" \
    --use-node-agent \
    --features EnableCSI
```

Create volume snapshot location:
```
$ velero snapshot-location create local --provider csi-volumesnapshot-class
```

Create backup with FSB and snapshot enabled:
```
$ velero backup create restic-and-snapshot-backup --default-volumes-to-fs-backup --snapshot-volumes --volume-snapshot-locations local
```

Backup details shows both CSI snapshot and Restic backup was done:
```
$ velero backup describe restic-and-snapshot-backup --details
...
Velero-Native Snapshots: <none included>

CSI Volume Snapshots:
Snapshot Content Name: snapcontent-e987bc07-1abe-49cf-8755-4ae0e4405f53
  Storage Snapshot ID: b0d3003b-f5a8-11ed-930a-0242ac110003
  Snapshot Size (bytes): 52428800
  Ready to use: true

restic Backups:
  Completed:
    test-csi-snapshot/my-csi-app: my-csi-volume
    velero/node-agent-98z5q: scratch
    velero/velero-647f87f59-lwzd5: plugins, scratch
```

volumesnapshotcontent is present after the backup.
```
$ kubectl get volumesnapshotcontent snapcontent-e987bc07-1abe-49cf-8755-4ae0e4405f53
NAME                                               READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER                VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT         AGE
snapcontent-e987bc07-1abe-49cf-8755-4ae0e4405f53   true         52428800      Retain           hostpath.csi.k8s.io   csi-snapclass         velero-csi-pvc-d8t56   52m
```

**What did you expect to happen:**
I expected to end up with only Restic backup without the volumesnapshotcontent or "Velero CSI snapshot" as I assume these are temporary and should be cleaned up after the backup.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 
[bundle-2023-05-18-15-24-04.tar.gz](https://github.com/vmware-tanzu/velero/files/11511058/bundle-2023-05-18-15-24-04.tar.gz)

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

Backup resource:
[backup-cr.txt](https://github.com/vmware-tanzu/velero/files/11511072/backup-cr.txt)

Full "velero backup describe" output:
[backup-details.txt](https://github.com/vmware-tanzu/velero/files/11511073/backup-details.txt)

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.11.0
	Git commit: 0da2baa908c88ec3c45da15001f6a4b0bda64ae2
Server:
	Version: v1.11.0
```
- Velero features (use `velero client config get features`): 
```
features: EnableCSI
```
- Kubernetes version (use `kubectl version`):
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:31Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
```
$ minikube version
minikube version: v1.28.0
commit: 986b1ebd987211ed16f8cc10aed7d2c42fc8392f
```
- Cloud provider or hardware configuration: Dell laptop
- OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
If the PVC is not set as "opt-out" for restic, the plugin should not take snapshot.

**Comment by Lyndon-Li** [comment]
@dzaninovic 
The file system backup and CSI snapshot backup are two different backup methods, so they should be mutual exclusive. Specifically, if `default-volumes-to-fs-backup` all volumes should go with file system backup, no CSI snapshot is taken as either final result or intermediate result. However, there are some exceptions:
1. The PVC/PV is opt-out from file system backup
2. The PV is backed by host path
3. The PV is a volume mounting a secret or configMap or download API
4. The PV is a volume mounted as projected volume

**Comment by Lyndon-Li** [comment]
@dzaninovic 
I guess in your env, the host-path PV is being used since CSI driver is `hostpath.csi.k8s.io`. If so, it falls to point 2 as shown above, so the volume will be excluded from file system backup.
Then since `snapshot-volume` is also enabled, the excluded volume will fall back to CSI snapshot backup.

Finally, please confirm if this rule is honored -- `the set of volumes handled by file system backup and the set of volumes handled by CSI snapshot backup should not be overlapped`.

**Comment by dzaninovic** [comment]
@Lyndon-Li,

I have only one 50 MB hostpath PVC on the cluster created only for this test.
```
$ kubectl get pvc -A
NAMESPACE           NAME      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
test-csi-snapshot   csi-pvc   Bound    pvc-c6a202f4-5db6-46de-b821-d8f786b99da5   50Mi       RWX            csi-hostpath-sc   65m
```
PVC is attached to this pod:
```
$ kubectl describe pod my-csi-app -n test-csi-snapshot
Name:         my-csi-app
Namespace:    test-csi-snapshot
...
Volumes:
  my-csi-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  csi-pvc
...
```
This PVC corresponds to this Restic backup report:
```
restic Backups:
  Completed:
    test-csi-snapshot/my-csi-app: my-csi-volume
```
So Restic backup was taken for this hostpath PVC.

I don't see any volumesnapshots:
```
$ kubectl get volumesnapshots -A
No resources found
```
But there is a volumesnapshotcontent that was created by the backup:
```
$ kubectl get volumesnapshotcontent -A
NAME                                               READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER                VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT         AGE
snapcontent-041592fa-2292-45fb-9a97-7a41ef97f75c   true         52428800      Retain           hostpath.csi.k8s.io   csi-snapclass         velero-csi-pvc-zfpsc   75m
```
Corresponding to this Velero backup report:
```
CSI Volume Snapshots:
Snapshot Content Name: snapcontent-041592fa-2292-45fb-9a97-7a41ef97f75c
  Storage Snapshot ID: a5c62efc-f998-11ed-853d-0242ac110003
  Snapshot Size (bytes): 52428800
  Ready to use: true
```
Snapshot Size is matching my PVC size and this is the only PVC on the cluster.

Here are all resources from this run described above:
[backup.txt](https://github.com/vmware-tanzu/velero/files/11548084/backup.txt)
[pod.txt](https://github.com/vmware-tanzu/velero/files/11548085/pod.txt)
[pvc.txt](https://github.com/vmware-tanzu/velero/files/11548086/pvc.txt)
[volumesnapshotcontent.txt](https://github.com/vmware-tanzu/velero/files/11548087/volumesnapshotcontent.txt)
[backup_json.txt](https://github.com/vmware-tanzu/velero/files/11548113/backup_json.txt)

Note: I reran the backup again so UUIDs will be different when compared to the previous run but I followed exactly the same workflow as described before.

**Comment by Lyndon-Li** [comment]
@dzaninovic 
Actually, it is not about the size of the volume, but it is a fact that file system backup doesn't support PV backed by host path, or in another words, if there is a PV backed by host path, the file system backup will skip it.
Then since the PV is skipped by file system backup and you have enabled `snapshot-volume`, the volume will be handled by CSI snapshot backup, so a CSI snapshot will be created.

It is also the expected result that you cannot see the volumesnapshot object after the backup, because Velero will delete the volumesnapshot object after backup finishes.

**Comment by dzaninovic** [comment]
I added another local PVC in test5 namespace which is supported by Restic.

Here is the list of all files on my target test bucket:
```
2023-05-26 17:08:44        484 backups/restic-and-snapshot-backup/restic-and-snapshot-backup-csi-volumesnapshotclasses.json.gz
2023-05-26 17:08:44        676 backups/restic-and-snapshot-backup/restic-and-snapshot-backup-csi-volumesnapshotcontents.json.gz
2023-05-26 17:08:44        562 backups/restic-and-snapshot-backup/restic-and-snapshot-backup-csi-volumesnapshots.json.gz
2023-05-26 17:08:45         27 backups/restic-and-snapshot-backup/restic-and-snapshot-backup-itemoperations.json.gz
2023-05-26 17:08:43      16683 backups/restic-and-snapshot-backup/restic-and-snapshot-backup-logs.gz
2023-05-26 17:08:45       1612 backups/restic-and-snapshot-backup/restic-and-snapshot-backup-podvolumebackups.json.gz
2023-05-26 17:08:45       2958 backups/restic-and-snapshot-backup/restic-and-snapshot-backup-resource-list.json.gz
2023-05-26 17:08:44         49 backups/restic-and-snapshot-backup/restic-and-snapshot-backup-results.gz
2023-05-26 17:08:45         29 backups/restic-and-snapshot-backup/restic-and-snapshot-backup-volumesnapshots.json.gz
2023-05-26 17:08:44     120630 backups/restic-and-snapshot-backup/restic-and-snapshot-backup.tar.gz
2023-05-26 17:08:46       2907 backups/restic-and-snapshot-backup/velero-backup.json
2023-05-26 17:07:00        155 restic/test-csi-snapshot/config
2023-05-26 17:07:05        131 restic/test-csi-snapshot/data/4b/4b436db62a09c539f1973e9b7016508fdbed2f72fb8b82f9e6682f1d2d4e3890
2023-05-26 17:07:05        331 restic/test-csi-snapshot/data/5e/5e8414534fb55dfc452ca83034f5139df572774abf4dc3d8d7b9bc0e4073ec3a
2023-05-26 17:07:05        309 restic/test-csi-snapshot/index/591ef8f64b409c1e7868695f9e544435917b997418cebcb592be6093c0ee5303
2023-05-26 17:07:00        462 restic/test-csi-snapshot/keys/b82630277cf89d6ec1515025fc11b43fef84ffe3cd06060a6c44a49cb9b5bbca
2023-05-26 17:07:05        369 restic/test-csi-snapshot/snapshots/26881672c64d21ab59d96e932f3ac0d956d2ccc520a41c0d65b749a7fc1d07b8
2023-05-26 17:07:11        155 restic/test5/config
2023-05-26 17:07:15      17133 restic/test5/data/9b/9baf49c22758073db1351f721b4f64fc5e873db2940c2a5e2297e5390a92acd8
2023-05-26 17:07:26    6984247 restic/test5/data/d9/d9751f811a5af2746f45f509cab2f93c602a574f65e68e562476e06d1285a8b6
2023-05-26 17:07:26      14078 restic/test5/index/dee4a85bfe436d789aeb7cad16fe176e7f8a2c970db7a098a37011b61125b0a9
2023-05-26 17:07:10        462 restic/test5/keys/b86b15344f34dba491010bd0a50b552db060184cee47abdbbd56b33025feaa98
2023-05-26 17:07:26        378 restic/test5/snapshots/cf696b33a1b041feebe2140d3fd360080a2bedc520819974f678af4e3656d773
2023-05-26 17:07:33        155 restic/velero/config
2023-05-26 17:08:01    2529440 restic/velero/data/03/03ab2931f8bb8beb8a0a627727d7d49a7c9ffac2d26b6aebd7bd3c29415ad159
2023-05-26 17:08:37       2483 restic/velero/data/13/13e9c4933f5810e12029f2997933d8c686fc8568700d01fe728e1780e7909dfa
2023-05-26 17:08:10   17422555 restic/velero/data/43/43eea271c3be63a8b903122bd57d1c453350e2e939ee83e9f8204d0cadc3e4e6
2023-05-26 17:07:48       3035 restic/velero/data/4a/4a305d71cd761e55cc10f197dbc123582b23d8181a34898569aa66d05e0169b4
2023-05-26 17:08:03   17203760 restic/velero/data/51/51615d5d90270debc020ff92b472e41944535ca2ea8ccbf0fcbb5b4170c23797
2023-05-26 17:07:38      33345 restic/velero/data/5a/5afe6080057a835fe23f6c2a55087665264da97c1e8c223ba102448c557c0b40
2023-05-26 17:07:37       6333 restic/velero/data/c5/c57cd048e3ba065881338e1c6ceb145d5f03227e2fe3916ba4733d3dd72a9ea8
2023-05-26 17:07:38       1443 restic/velero/index/3140e96a41bdc281093e6244a83cc56725223695d4e0cebbd718bbdc791166a1
2023-05-26 17:08:31       3980 restic/velero/index/7c30bc35e2a795ad3dc072b400b19fc626c3a3daf718962072d8564618283a6f
2023-05-26 17:08:38        449 restic/velero/index/b053bca3b90856ea276f55bfddb2068efb5ca9570e7278704fa993e397a03db4
2023-05-26 17:07:33        462 restic/velero/keys/510290a5e6f70f384c5bccba86c15c2e68eef79f150fade5f670b76914cb0284
2023-05-26 17:08:38        342 restic/velero/snapshots/1367b59dc3d150397dbe4d1c8099e738e495e563536182498d59d0cc94eec7de
2023-05-26 17:07:38        340 restic/velero/snapshots/31dbf050621da81eb520834de8cfa055a5cd1409b8fe3bbb34238da8840bd8b2
2023-05-26 17:08:31        338 restic/velero/snapshots/cfcc7775194140bd8810fa9000256967b96524b41523e77c98f8076b72fc298b
```
Prefix restic/test-csi-snapshot does not really have any data backed up as Restic does not support hostpath as you said.  Velero documentation also confirms it.
Prefix restic/test5 does have data and that namespace has a local PVC which Velero supports for filesystem backup.

So then the only question is why did Velero report successful Restic backup of hostpath PVC in test-csi-snapshot namespace when no data was backed up?
```
restic Backups:
  Completed:
    test-csi-snapshot/my-csi-app: my-csi-volume  <=====
    test5/mysql-deployment-7d5b588cff-sp9hc: local-volume
    velero/node-agent-tl4zj: scratch
    velero/velero-647f87f59-f2qjk: plugins, scratch
```

**Comment by Lyndon-Li** [comment]
@dzaninovic Please help to collect below information:
1. run `kubectl get podvolumebackup -n velero -o yaml,` and share the output
2. Share the yaml of your PV provisioned by the host-path CSI driver

**Comment by dzaninovic** [comment]
@Lyndon-Li,

I forgot to add data to my hostpath PVC which is why no data was backed up.

I added the data and rerun everything again and here are the resources and logs:
[logs.zip](https://github.com/vmware-tanzu/velero/files/11604050/logs.zip)

Seems like Restic backed up the hostpath PVC data and I still see "CSI Volume Snapshots" reported.

**Comment by blackpiglet** [comment]
@dzaninovic 
Could you try the newer version of the Velero CSI plugin during testing?
The version of the CSI plugin that works with v1.11 Velero should be v0.5.0.
https://github.com/vmware-tanzu/velero-plugin-for-csi#compatibility

**Comment by dzaninovic** [comment]
After using the correct CSI plugin version Velero does not report that it did CSI snapshot backup and only Restic backup was done.
```
CSI Volume Snapshots: <none included>

restic Backups:
  Completed:
    test-csi-snapshot/my-csi-app: my-csi-volume
    velero/node-agent-476v6: scratch
    velero/velero-7658949b9-8knff: plugins, scratch
```
That resolves the issue.

So it looks like on my configuration hostpath is supported for filesystem backup which is different from what it says in Velero documentation https://velero.io/docs/v1.11/file-system-backup/ under "File System Backup" section.
"NOTE: hostPath volumes are not supported, but the local volume type is supported."

**Comment by dzaninovic** [comment]
Everything is resolved so I will close the issue.
Thank you for your help!
