### ISSUE TITLE
velero backup storage location status is unknown

### ISSUE THREAD

**Issue by sureshopsgeek** [vmware-tanzu/velero#6290]
[bundle-2023-05-19-13-25-00.tar.gz](https://github.com/vmware-tanzu/velero/files/11514969/bundle-2023-05-19-13-25-00.tar.gz)
**What steps did you take and what happened:**
I have deployed velero helm chart in one of our clusters and configured an s3 compatible backup storage location.
The scheduled backups are getting completed and backup files are being pushed to the location but the backup storage location status is always unknown and commands like `velero backup logs` are not working.

**What did you expect to happen:**

I expected the BSL status to be available and all velero commands to be working.

**Environment:**

- Velero version (use `velero version`): 1.9.1
- Velero features (use `velero client config get features`): NOT SET
- Kubernetes version (use `kubectl version`): 1.24
- Kubernetes installer & version: kubeadm , 1.24
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): AmazonLinux-2

**Comment by allenxu404** [comment]
There could be various reason for unknown status of backup storage location like credential issues and connectivity issues with the storage provider. You can check the velero logs by executing `kubectl logs` on pods or deployment for further troubleshoot.
