### ISSUE TITLE
On AKS, velero backup storage location status is unavailable

### ISSUE THREAD

**Issue by arminzqm** [vmware-tanzu/velero#6292]
**What steps did you take and what happened:**

1. Follow the plugin README: https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/v1.7.0/README.md to setup the permission for Velero by using a Velero-specific service principal.
2. Deploy velero v1.11.0 + velero-plugin-for-microsoft-azure v1.7.0 on AKS, the backup storage location status is unavailable. 
   Error message: 
```   BackupStorageLocation \"default\" is unavailable: rpc error: code =
      Unknown desc = GET https://velero3cb7b4ded9ca.blob.core.windows.net/velero001\n--------------------------------------------------------------------------------\nRESPONSE
      403: 403 This request is not authorized to perform this operation using this
      permission.\nERROR CODE: AuthorizationPermissionMismatch\n--------------------------------------------------------------------------------\n\uFEFF<?xml
      version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This
      request is not authorized to perform this operation using this permission.\nRequestId:d0c29152-f01e-006f-0331-8a8ad5000000\nTime:2023-05-19T09:11:24.0737029Z</Message></Error>
```
3. The bsl settings:
```  spec:
    accessMode: ReadWrite
    config:
      resourceGroup: k8s-test01
      storageAccount: velero3cb7b4ded9ca
    objectStorage:
      bucket: velero001
    provider: azure
```	

Note: When deploy velero v1.9.3 + velero-plugin-for-microsoft-azure v1.3.1, use the same bsl settings and same credentials-velero file, the bsl status is available.

**Environment:**

- Velero version (use `velero version`): v1.11.0
- Velero features (use `velero client config get features`): <NOT SET>
- Velero plugin for microsoft azure version: v1.7.0
- Kubernetes version (use `kubectl version`): v1.25.4
- Cloud provider or hardware configuration: microsoft-azure

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
Dup of https://github.com/vmware-tanzu/velero/issues/6180, please refer to https://github.com/vmware-tanzu/velero/issues/6180#issuecomment-1532307400 to work around
