### ISSUE TITLE
Could not retrieve CRs or CRDs in Velero server after restore in short while

### ISSUE THREAD

**Issue by qiuming-best** [vmware-tanzu/velero#6293]
**What steps did you take and what happened:**

The CRs or CRD that is synchronized during restore is not available in Velero server, but it is available by kubectl. We use the discovery client in Velero server to periodically [Refresh](https://github.com/vmware-tanzu/velero/blob/main/pkg/restore/restore.go#L682) API resources in k8s API. If a new resource is created within that period, it will not be queried inside velero.

**What did you expect to happen:**
We need to refresh the API resources immediately after restore in the restore controller

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
It seems only impact the scenario if we use velero to do a backup immediately after restore, which is a very corner case and seems OK to be deferred. 
Please provide a more concrete usecase when this problem happens.

**Comment by qiuming-best** [comment]
It maybe similar to https://github.com/vmware-tanzu/velero/issues/6498

**Comment by half-life666** [comment]
Last time when we hit this, it's in `fetchBackupInfo` which is using `backupLister` that used in older version of velero, the latest velero is using standard controller client get, should not hit this problem any more.

**Comment by reasonerjt** [comment]
per latest comment I'm closing this issue.
