### ISSUE TITLE
Label selectors can break restore from CSI Snapshots.

### ISSUE THREAD

**Issue by anshulahuja98** [vmware-tanzu/velero#6294]
**What steps did you take and what happened:**

When restoring from a backup consisting of CSI VolumeSnapshots using a label selector. The label provided was available on the PVC. But the underlying VS did not have the same label.
Hence core velero flow did not restore the VS leading to failure in restore of PVC in csi plugin.

**What did you expect to happen:**
Labels of PVC are applied on the VS, to ensure restore works as expected.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by anshulahuja98** [comment]
@sseago, we can't really do this through RestoreItemActionExecuteOutput  of PVC's RIA. This will be returned after the PVC restoration fails.
VS being present is a pre req to PVC

**Comment by sseago** [comment]
@anshulahuja98 Another possibility would be for the CSI plugin to copy labels from the PVC to the newly-created VS. That wouldn't require any velero core changes, but would it be sufficient to resolve this?

**Comment by anshulahuja98** [comment]
It should be sufficient to resolve the issue, that's what I had called out in the Issue descrip - it won't have back compat with older backups taken, but I think that should be okay.
I'll do the required changes and test it out.

Other folks pl let us know if any concerns with this approach.

**Comment by shubham-pampattiwar** [comment]
@anshulahuja98 you should be able to resolve this issue by adding `VolumeSnapshots` as `includedResources` in your backup CR spec. The `labelSelector` is only used as a filtering criteria when collecting items to be backedup and not when we create and add additional Items in our csi plugin runtime execution.

**Comment by anshulahuja98** [comment]
@shubham-pampattiwar the VS were backed up as expected
but on restore side (with label selectors) - the VS was not restored since it didn't have the labels. ANd hence the PVC didn't find the VS.

I am not sure how your suggestion above solves the issue?

**Comment by anshulahuja98** [comment]
@sseago can you please review the PR to fix this issue.

**Comment by anshulahuja98** [comment]
CC: @blackpiglet for any other inputs/ PR review

**Comment by shubham-pampattiwar** [comment]
@anshulahuja98 I was under the impression that the VS was not present in the backup and hence did not get restored. Anyways, seems like an issue.
