### ISSUE TITLE
Add capability to tag objects put in S3

### ISSUE THREAD

**Issue by mirage2012** [vmware-tanzu/velero#6309]
**Describe the problem/challenge you have**
I cannot put tags on the objects put to s3 while taking a backup of Kubernetes resources.  I need these tags for the following two reasons:
 1) I would like to calculate costs of the backups per team. I use AWS tags for this.
 2) I would like to create AWS IAM policies that check tags on objects in S3 and allow access based on the same. For example, I would like to store all my backups in a single S3 bucket with appropriate bucket prefix. The objects would be tagged with the AWS account id where the Kubernetes cluster exists. (example ownerAccount =456778). 
Now while restoring, the AWS policy would allow access to the object if and only if the request is coming from the account from which the backup was created. 

An example policy to depict the purpose of tags (using terraform datasource):

```
data "aws_iam_policy_document" "s3_tag_access" {
  statement {
    actions = [
      "s3:PutObject",
      "s3:PutObjectTagging",
    ]
    resources = ["*"]
    condition {
      test     = "StringEquals"
      variable = "s3:RequestObjectTag/ownerAccount"
      values   = ["$${aws:PrincipalAccount}"]
    }
  }
  statement {
    actions = [
      "s3:GetObject",
      "s3:GetObjectVersion",
    ]
    resources = ["*"]
    condition {
      test     = "StringEquals"
      variable = "s3:ExistingObjectTag/ownerAccount"
      values   = ["$${aws:PrincipalAccount}"]
    }
  }
}
``` 
**Describe the solution you'd like**
The plugin uses s3manager and that allows putting tags to the objects. Following Pull request is intended to add this feature. 
https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/164

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.11
- Kubernetes version (use `kubectl version`): 1.24
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by mirage2012** [comment]
@reasonerjt I see that the issue is assigned to you. I was wondering if I could request you to take a look at this whenever you have a few minutes. There is a PR as well.

**Comment by reasonerjt** [comment]
@mirage2012 sorry for the late response that PR has conflicts after the AWS SDK is bumped to v2.  Now it's fixed via https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/182
