### ISSUE TITLE
restore etcd to new namespace failed. cause:  pod env exist origin namespace info

### ISSUE THREAD

**Issue by BAMSHK** [vmware-tanzu/velero#6328]
![image](https://github.com/vmware-tanzu/velero/assets/40750078/1b0cab0d-2b91-4a9b-b986-59c1ce5f4e91)

* using helm install etcd

**Comment by qiuming-best** [comment]
@BAMSHK Velero will backup the k8s object including the ENV info on the pod, and it could restore to a new namespace, but it will retain the ENV info as it was, so there's this problem.

**Comment by BAMSHK** [comment]
谢谢了-希望你们快乐

**Comment by qiuming-best** [comment]
I think the problem shown above, I'll close it first
