### ISSUE TITLE
Velero BackupStorageLocation is unknown/unavailable

### ISSUE THREAD

**Issue by ainurbal** [vmware-tanzu/velero#6329]
I have successfully installed Velero with the following script:

velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.7.0 \  (I've tried other versions of the plugin as well)
    --bucket MY-BUCKET-NAME \
    --backup-location-config region=us-west-2 \
    --snapshot-location-config region=us-west-2 \
    --secret-file ./credentials_velero \

Since we are using temporary credentials, I put freshly generated creds (access key id, secret key, session token) into credentials_velero file which creates a secret. 

Velero gets installed and pod is running, however it is unable to find backup-location:

`velero backup-location get
NAME      PROVIDER   BUCKET/PREFIX   PHASE     LAST VALIDATED   ACCESS MODE   DEFAULT
default   aws        velero-v2       Unknown   Unknown          ReadWrite     true`

`kubectl get bsl -n velero -o yaml
apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    creationTimestamp: "2023-05-31T16:43:57Z"
    generation: 2
    labels:
      component: velero
    name: default
    namespace: velero
    resourceVersion: "873495265"
    uid: a61a0b58-d792-493e-a02b-7cddefa276de
  spec:
    config:
      region: us-west-2
    default: true
    objectStorage:
      bucket: velero-v2
    provider: aws
  status:
    lastValidationTime: "2023-05-31T16:46:20Z"
    message: |-
      BackupStorageLocation "default" is unavailable: rpc error: code = Unknown desc = RequestError: send request failed
      caused by: Get "https://velero-v2.s3.us-west-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=": dial tcp: lookup velero-v2.s3.us-west-2.amazonaws.com: i/o timeout
    phase: Unavailable
kind: List
metadata:
  resourceVersion: ""`

Some of the error msg in the logs:

`I0531 16:44:21.765438       1 request.go:690] Waited for 2.847901482s due to client-side throttling, not priority and fairness, request: GET:https://IP/apis/cert-manager.io/v1?timeout=32s
time="2023-05-31T16:44:27Z" level=warning msg="Failed to discover group: metrics.k8s.io/v1beta1" error="an error on the server (\"Internal Server Error: \\\"/apis/metrics.k8s.io/v1beta1?timeout=32s\\\": Unauthorized\") has prevented the request from succeeding" logSource="pkg/discovery/helper.go:220"
time="2023-05-31T16:46:20Z" level=error msg="Error listing backups in backup store" backupLocation=velero/default controller=backup-sync error="rpc error: code = Unknown desc = RequestError: send request failed\ncaused by: Get \"https://velero-v2.s3.us-west-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=backups%2F\": dial tcp: lookup velero-v2.s3.us-west-2.amazonaws.com: i/o timeout" error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:426" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:107"
time="2023-05-31T16:46:20Z" level=error msg="fail to validate backup store" backup-storage-location=velero/default controller=backup-storage-location error="rpc error: code = Unknown desc = RequestError: send request failed\ncaused by: Get \"https://velero-v2.s3.us-west-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=\": dial tcp: lookup velero-v2.s3.us-west-2.amazonaws.com: i/o timeout" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/persistence/object_store.go:198" error.function="github.com/vmware-tanzu/velero/pkg/persistence.(*objectBackupStore).IsValid" logSource="pkg/controller/backup_storage_location_controller.go:155"
time="2023-05-31T16:46:20Z" level=info msg="BackupStorageLocation is invalid, marking as unavailable" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:131"
time="2023-05-31T16:46:20Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/0/1, BackupStorageLocation \"default\" is unavailable: rpc error: code = Unknown desc = RequestError: send request failed\ncaused by: Get \"https://velero-v2.s3.us-west-2.amazonaws.com/?delimiter=%2F&list-type=2&prefix=\": dial tcp: lookup velero-v2.s3.us-west-2.amazonaws.com: i/o timeout)" controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:192"`

**Comment by qiuming-best** [comment]
@ainurbal the error `velero-v2.s3.us-west-2.amazonaws.com:  i/o timeout` means that the velero pod could not connect to the URL, you should check the network of your velero pod

**Comment by qiuming-best** [comment]
I'll close it. for it's just network could not be reachable.
