### ISSUE TITLE
PV Data not getting restored but PV is being created.

### ISSUE THREAD

**Issue by abhaykohli** [vmware-tanzu/velero#6352]
**What steps did you take and what happened:**
1. Installed velero using following paramaters:
velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.6.2 --bucket howdy12 --secret-file ./credentials-velero --use-volume-snapshots=false  --backup-location-config region=ap-south-1 --namespace velero --use-node-agent  --default-volumes-to-fs-backup
2. I have installed this on a minikube cluster with docker as a driver.
3. Created PV and PVC attached to a pod in namespace foo. (Manifet/yml files are attached for the same)

**What did you expect to happen:**
I want my PV data  to be restored, for testing i created a simple **File** in the volume and deleted it after taking backup but the **File** is not restored.
**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 
After executing above command getting this as error
velero debug  --backup backup-test1 --restore restore-test1
2023/06/05 10:38:16 Collecting velero resources in namespace: velero
2023/06/05 10:38:16 Collecting velero deployment logs in namespace: velero
2023/06/05 10:38:16 Collecting log and information for backup: backup-test1
2023/06/05 10:38:17 Collecting log and information for restore: restore-test1
An error occurred: exec failed: Traceback (most recent call last):
  velero-debug-collector:29:8: in <toplevel>
  <builtin>: in archive
Error: archive failed: open /bundle-2023-06-05-10-38-16.tar.gz: permission denied

**Anything else you would like to add:**
I have _created backup_ using command  :
velero backup create backup-test --include-namespaces foo --default-volumes-to-fs-backup --snapshot-volumes --ttl 180h
and before this i have 
_annotated the pod_ using:
kubectl -n foo annotate pod/sample backup.velero.io/backup-volumes=my-pv
FYI: Both PV and PVC are Bound

**Environment:**

- Velero version (use `velero version`): 1.10.3
- Velero features (use `velero client config get features`):  <NOT SET>
- Kubernetes version (use `kubectl version`):Client Version: v1.27.2  || Kustomize Version: v5.0.1 ||Server Version: v1.26.3
- Kubernetes installer & version:
- Cloud provider or hardware configuration:Running on minikube Ec2 t2.medium
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible" 👍
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
@abhaykohli As Velero's default restore policy, the existing items will not be overwritten. Therefore, please try to delete the entire namespace before running the restore.

**Comment by abhaykohli** [comment]
Attached are screenshots of : velero restore get || velero describe backup back1 --details
![back1-v](https://github.com/vmware-tanzu/velero/assets/42304528/ce526a54-718d-46cd-b55d-c15678a16eb8)
![back2-v](https://github.com/vmware-tanzu/velero/assets/42304528/724896f5-8935-46dc-a58d-dcd4f81d1988)
![restore-v](https://github.com/vmware-tanzu/velero/assets/42304528/319b5373-7711-4473-a22e-f57087b60e43)

**Comment by abhaykohli** [comment]
@Lyndon-Li  this is the output of  [kubectl get podvolumerestores -n velero -o yaml]:
piVersion: v1
items:
- apiVersion: velero.io/v1
  kind: PodVolumeRestore
  metadata:
    creationTimestamp: "2023-06-06T08:22:52Z"
    generateName: restore1-
    generation: 1
    labels:
      velero.io/pod-uid: e3a4315a-5254-4cfd-acfe-19790f97905d
      velero.io/pvc-uid: 49ea4db6-32bd-4cf4-9df8-86845445b0d1
      velero.io/restore-name: restore1
      velero.io/restore-uid: 96503908-cd6d-48bc-b990-03fe518e944e
    name: restore1-cbp7m
    namespace: velero
    ownerReferences:
    - apiVersion: velero.io/v1
      controller: true
      kind: Restore
      name: restore1
      uid: 96503908-cd6d-48bc-b990-03fe518e944e
    resourceVersion: "31658"
    uid: 9c1df21e-efaa-4d10-b36c-9468edb2708d
  spec:
    backupStorageLocation: default
    pod:
      kind: Pod
      name: sample
      namespace: foo
      uid: e3a4315a-5254-4cfd-acfe-19790f97905d
    repoIdentifier: s3:s3-ap-south-1.amazonaws.com/howdy12/restic/foo
    snapshotID: 8de47e21
    sourceNamespace: foo
    uploaderType: restic
    volume: my-pv
  status:
    progress: {}
kind: List
metadata:
  resourceVersion: ""

**Comment by Lyndon-Li** [comment]
@abhaykohli Also need the velero log bundle, you can get it by running `velero debug`.

**Comment by abhaykohli** [comment]
> @abhaykohli Also need the velero log bundle, you can get it by running `velero debug`.

Getting this output : An error occurred: error finding Kubernetes API server config in --kubeconfig, $KUBECONFIG, or in-cluster configuration: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

**Comment by Lyndon-Li** [comment]
@abhaykohli 
`velero debug` generates log files in the current directory you run the velero client, looks like you don't have the write permission in the directory (from the output, looks like you are running velero command from /).
Therefore, you may copy velero client to another directory and run it there.

**Comment by abhaykohli** [comment]
@Lyndon-Li  PFA all the files 

[node-agent.log](https://github.com/vmware-tanzu/velero/files/11721099/node-agent.log)
[velero.log](https://github.com/vmware-tanzu/velero/files/11721103/velero.log)
[velero-velero-plugin-for-aws.log](https://github.com/vmware-tanzu/velero/files/11721106/velero-velero-plugin-for-aws.log)
[version.txt](https://github.com/vmware-tanzu/velero/files/11721108/version.txt)

**Comment by Lyndon-Li** [comment]
@abhaykohli 
The node-agent log you collected doesn't contain any job info, Velero node-agent is a daemonset, so you need to collect the logs from all nodes and the jobs info may be in any one of the logs.
Also, make sure that you collect the log when the problem happens, that is, when the restore stuck.

**Comment by abhaykohli** [comment]
@Lyndon-Li  The main problem that i am facing is not that of restore stuck, i cannot restore my pv-data that is the issue.

**Comment by abhaykohli** [comment]
I am deleting the ns but still encountering the same issue
