### ISSUE TITLE
The s3 storage target for the same cluster could not be resolved and connected

### ISSUE THREAD

**Issue by clcc2019** [vmware-tanzu/velero#6372]
<img width="1486" alt="image" src="https://github.com/vmware-tanzu/velero/assets/46099295/80ce380d-729c-4e5a-921f-eeef179d9246">

The s3 storage target for the same cluster could not be resolved and connected
```yaml
velero install \
  --provider aws \
  --bucket tmp \
  --secret-file ./credentials-velero \
  --use-volume-snapshots=true \
  --backup-location-config region=minio,s3ForcePathStyle="true",s3Url="http://10.96.0.205:9000"

```

**Comment by Lyndon-Li** [comment]
This is a known issue.
Velero client is connecting to the backup store directly to get items backed up or persisted together with the backup. If the env where Velero client is running has no network connection to the backup store, some client command will fail, i.e., `velero backup logs`, `velero backup download`, `velero debug`

**Comment by Lyndon-Li** [comment]
This is duplicated with #6167

**Comment by Lyndon-Li** [comment]
Close for duplication
