### ISSUE TITLE
error: SchemaError(io.velero.v1.Restore.spec.hooks.resources.postHooks.init.initContainers): array should have exactly one sub-item

### ISSUE THREAD

**Issue by mrchirumamilla1** [vmware-tanzu/velero#6382]
---
**name**: [Bug report](error: SchemaError(io.velero.v1.Restore.spec.hooks.resources.postHooks.init.initContainers): array should have exactly one sub-item). 
**about**: We have a k8s(version 1.18) cluster with magnum on openstack. As per the Velero documentation latest version of Velero is compatible with k8s version 1.18. I deployed Velero successfully with the helm charts (Chart version: velero-4.0.3 and App version: 1.11.0) with storage location as minio(chart version -8.0.10 and app version latest) and was able to back up the k8s resources. But the other applications' new deployment or upgrading Velero with new values and other applications is failing with the following error:

**_error: SchemaError(io.velero.v1.Restore.spec.hooks.resources.postHooks.init.initContainers): array should have exactly one sub-item_**
I am getting the same error even if i use velero-plugin-for-aws or velero-plugin-for-csi alone.
and folllowing is helm chart install command:

```
helm install velero \
    --namespace=velero \
    --create-namespace \
    --set-file credentials.secretContents.cloud=credentials-minio \
    --set configuration.backupStorageLocation[0].name=default \
    --set configuration.backupStorageLocation[0].provider=aws \
    --set configuration.backupStorageLocation[0].bucket=velero \
    --set configuration.backupStorageLocation[0].config.region=minio-default \
    --set configuration.backupStorageLocation[0].config.s3ForcePathStyle=true \
    --set configuration.backupStorageLocation[0].config.s3Url=http://minio:9000 \
    --set snapshotsEnabled=true \
    --set deployNodeAgent=true \
    --set configuration.features=EnableCSI \
    --set configuration.volumeSnapshotLocation[0].name=default \
    --set configuration.volumeSnapshotLocation[0].provider=aws \
    --set configuration.volumeSnapshotLocation[0].config.region=minio-default \
    --set initContainers[0].name=velero-plugin-for-aws \
    --set initContainers[0].image=velero/velero-plugin-for-aws:v1.7.0 \
    --set initContainers[0].volumeMounts[0].mountPath=/target \
    --set initContainers[0].volumeMounts[0].name=plugins \
    --set initContainers[1].name=velero-plugin-for-csi \
    --set initContainers[1].image=velero/velero-plugin-for-csi:v0.5.0 \
    --set initContainers[1].volumeMounts[0].mountPath=/target \
    --set initContainers[1].volumeMounts[0].name=plugins \
    vmware-tanzu/velero
```

installation of velero helm charts (Chart version: velero-4.0.3 and App version: 1.11.0) with  minio(chart version -8.0.10 and app version latest) on docker-desktop k8s latest version works well.

**Comment by frost52** [comment]
The same issues in different env
k8s server: 1.16
k8s client: 1.27

Installed Velero using the following command

velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.6.2,velero/velero-plugin-for-csi:v0.4.3  --bucket velero --prefix prefix-paht --cacert ./cacrt --use-volume-snapshots=false --backup-location-config publicUrl=https://minio,region=minio,s3ForcePathStyle="true",s3Url=https://minio --secret-file ./secret --image velero/velero:v1.10.3

then I needed to update the deployment, but "edit deployment" got the same error message described above
fortunately, "patch" command worked

might be a "kubectl" issue

**Comment by ywk253100** [comment]
Did you upgrade CRD before upgrading velero deployments?

**Comment by alexvivanov** [comment]
Hello!
I have same problem. 
Velero appVersion: v2.6.2
Legacy kub cluster v1.17.9
I have a fresh install for this cluster.

My workaround
1. `kubectl delete customresourcedefinitions.apiextensions.k8s.io restores.velero.io`
2. sync all except restores.velero.io CRD
3. velero pod not started (CrashLoopBackOff)
An error occurred: [custom resource Restore not found in Velero API group velero.io/v1, Velero custom resources not found - apply examples/common/00-prereqs.yaml to update the custom resource definitions]
4. Sync only restores.velero.io CRD
5. velero pod is going Ready

**Comment by joanyko** [comment]
I confirm the same problem with k8s v1.21.5 and helm 4.1.0

**Comment by printWSL** [comment]
I have same problem.   k8s v1.25.0 and helm 3.5.0

**Comment by bmalynovytch** [comment]
It's a Helm chart issue, not Velero itself.
It seems to be an upgrade issue: removing old restore CRD allows to upgrade without error.

**Comment by zgfh** [comment]
see: https://github.com/elastic/cloud-on-k8s/issues/4737#issuecomment-894092212

this work for me:
```
kubectl patch crd restores.velero.io --type json -p='[{"op": "remove", "path": "/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/hooks/properties/resources/items/properties/postHooks/items/properties/init/properties/initContainers/x-kubernetes-preserve-unknown-fields"}]'
```
