### ISSUE TITLE
Facing issue with golang old version

### ISSUE THREAD

**Issue by kalpanathanneeru21** [vmware-tanzu/velero#6385]
**What steps did you take and what happened:**

having vulnerabilities related to golang versions
<img width="1051" alt="image" src="https://github.com/vmware-tanzu/velero/assets/85505383/8cbe169e-fcc2-42e7-b6cb-7a377108baf7">

**What did you expect to happen:**
Jfrog Xray should pass with out any violations.

**Environment:**

- Velero version (use `velero version`):  v1.10.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): EKS 1.23
- Kubernetes installer & version: AWS
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
Could you try the latest version of 1.10.x instead?

**Comment by kalpanathanneeru21** [comment]
I have tried v1.11.0 also having the same vulnerabilities
