### ISSUE TITLE
[DEVELOPMENT] Duplicated stale job

### ISSUE THREAD

**Issue by mateusoliveira43** [vmware-tanzu/velero#6386]
**Describe the problem/challenge you have**
 
 Velero repository has 2 stale jobs:
 - https://github.com/vmware-tanzu/velero/blob/main/.github/stale.yml (managed by https://github.com/probot/stale, and which is currently doing all the job)
 - https://github.com/vmware-tanzu/velero/blob/main/.github/workflows/stale-issues.yml (managed by https://github.com/actions/stale)

**Describe the solution you'd like**

Choose one of them and delete the other. I suggest the one from https://github.com/actions/stale, as it still receives updates.

**Anything else you would like to add:**

I could work on the resolution of this issue, once maintainers decide which job to keep.

**Environment:**

- Velero GitHub repository 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
Thanks @mateusoliveira43, will let you know after I discuss it with the team

**Comment by ywk253100** [comment]
@mateusoliveira43 Let's use https://github.com/actions/stale

**Comment by mateusoliveira43** [comment]
Alright @ywk253100
Going to try to open the PR later today :smile:
