### ISSUE TITLE
Kopia does not respect AWS credential with restrictive IAM roles

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#6391]
**What steps did you take and what happened:**

An AWS credential with restrictive IAM roles on bucket prefix is not respect by Kopia, this credential has the access(R/W) privileges of bucket-x/prefix-x/, but has no such access privileges of  bucket-x/, this credential is use to isolate users under the same bucket, Kopia should not quit although failing to list the bucket.

Kopia error is like this below: 
`ERROR can't connect to storage: error retrieving storage config from bucket "bucket1": Access Denied`

**What did you expect to happen:**

Backup PV with Kopia successfully with this kind of restrictive IAM role.

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
This problem should be fixed on Kopia side, a Kopia issue is created https://github.com/kopia/kopia/issues/3071

**Comment by reasonerjt** [comment]
@shawn-hurley 

Option 3 will require confidence for the quality of unreleased code.  Let's discuss it in the community mtg.

**Comment by shawn-hurley** [comment]
I am not advocating for any of the options right now, but I did want to bring it up as an option :)

**Comment by sseago** [comment]
Forking kopia will *also* result in us relying on unreleased code, although perhaps it would minimize it. If the velero fork of kopia had a velero release branch with just the commit from the release we're currently using plus a cherry-pick of the PR that fixes the bug, then there would be very little unreleased code, but there would be another repo to maintain (even if only temporarily, as we could stop using it once the fix makes it into a release, in the meantime we'd just need a go mod replace directive to use a tag from the fork repo instead of the upstream release.

**Comment by Lyndon-Li** [comment]
Fixed by #6702 and kopia PR https://github.com/kopia/kopia/pull/3072
