### ISSUE TITLE
Different BSL credentials may conflict when deploying on Azure

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#6393]
Currently, Velero populates the storage credentials into the environment variables and Azure SDK reads them to do the auth.
Similar logic appears in two places of Velero:
- Azure plugin
     - [Populate the crednetial](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/v1.7.0/velero-plugin-for-microsoft-azure/object_store.go#L234)
     - [Azure SDK read from the env](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/v1.7.0/velero-plugin-for-microsoft-azure/object_store.go#L254)

- Repository code
    - [Populate the credential](https://github.com/vmware-tanzu/velero/blob/v1.11.0/pkg/repository/config/azure.go#L57)
    - [Azure SDK read from the env](https://github.com/vmware-tanzu/velero/blob/v1.11.0/pkg/repository/config/azure.go#L95)

However, different BSLs may have different credentials which could be set by the [Credential](https://github.com/vmware-tanzu/velero/blob/v1.11.0/pkg/apis/velero/v1/backupstoragelocation_types.go#L36) field, the credential of one BSL may be overridden by others when dealing the BSLs concurrently, e.g. do the backup and restore with different BSL in the same time.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
@anshulahuja98 That's exactly what I'm thinking of.

The change should appear in three places: Azure plugin, Velero repository code and Kopia, we need to maintain duplicated code if we implement the logic separately. 
Is it possible that we implement a `ConfigCredential` which is like the `EnvironmentCredential` but reads the credentials from a map in upstream Azure SDK? Seems that's pretty reasonable for the code that uses Azure SDK and runs concurrently.

**Comment by anshulahuja98** [comment]
`EnvironmentCredential`  is just a wrapper on top of `NewClientSecretCredential` . We can simply use that.
 
 Are you talking about an implementation similar to `NewDefaultAzureCredential`  instead?

**Comment by anshulahuja98** [comment]
Hmm, it does make sense, but might be slightly difficult to convince the SDK team.
Might need to start a bit of code to see how the interfaces will end up looking like and then we can create an Issue in their repo wiith more details. And see what they think of it.

**Comment by ywk253100** [comment]
Opened an issue for Azure SDK: https://github.com/Azure/azure-sdk-for-go/issues/21061

**Comment by ywk253100** [comment]
Fixed by https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/206 and https://github.com/vmware-tanzu/velero/pull/6686
