### ISSUE TITLE
Restic backups fail for 2nd volume in list

### ISSUE THREAD

**Issue by schaze** [vmware-tanzu/velero#6406]
---
name: Restic backups fail for 2nd volume in list
about: 
When creating a backup with restic integration the 2nd volume in the "backup.velero.io/backup-volumes" annotation always fails.

---

**What steps did you take and what happened:**
I have a namespace with only one deployment. The deployment has multiple different volumes 2 of which I want to backup.
```yaml
      annotations:
        backup.velero.io/backup-volumes: "audiobookshelf-config,audiobookshelf-metadata"
      ...
      ...
         volumeMounts:
          - mountPath: /config
            name: audiobookshelf-config
          - mountPath: /metadata
            name: audiobookshelf-metadata
```

Then I create a backup with:
```bash
> velero backup create abs3 --include-namespaces=audiobookshelf
```

The problem now is that only one of the volumes gets backuped successfully and the other one fails. It is consistently working for the first volume mentioned in the annotation above. If I switch the order in the annotation the one that previously failed is working. Whichever is listed first works.

Error logs from the backup:
```log
time="2023-06-18T12:01:08Z" level=info msg="2 errors encountered backup up item" backup=backup/abs3 logSource="pkg/backup/backup.go:431" name=as-audiobookshelf-56dbd6854d-kvhzh
time="2023-06-18T12:01:08Z" level=error msg="Error backing up item" backup=backup/abs3 error="pod volume backup failed: error running restic backup, stderr=Fatal: Fatal: config cannot be loaded: unsupported repository version\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:250" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:435" name=as-audiobookshelf-56dbd6854d-kvhzh
time="2023-06-18T12:01:08Z" level=error msg="Error backing up item" backup=backup/abs3 error="pod volume backup failed: error running restic backup, stderr=Fatal: Fatal: config cannot be loaded: unsupported repository version\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/podvolume/backupper.go:250" error.function="github.com/vmware-tanzu/velero/pkg/podvolume.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:435" name=as-audiobookshelf-56dbd6854d-kvhzh
```

I do have other schedules for other namespaces in the same way also with multiple volumes in them which are working fine. However they have been created with a way older version (1.6.3) of velero a while ago. The new ones are created with 1.11. I never had any problems in the past with any backups.

**What did you expect to happen:**
Both volumes get backup successully.

**The following information will help us better understand what's going on**:

Debug Bundle:
[bundle-2023-06-18-14-27-20.tar.gz](https://github.com/vmware-tanzu/velero/files/11781467/bundle-2023-06-18-14-27-20.tar.gz)

**Anything else you would like to add:**
I am using a in cluster Minio Server as backend for the backups.

**Environment:**

- Velero version (use `velero version`):v1.11.0 0da2baa908c88ec3c45da15001f6a4b0bda64ae2
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"archive", BuildDate:"2023-05-28T13:03:55Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Lyndon-Li** [comment]
@schaze
Could you double check your env to see if you have successfully upgraded to Velero 1.11 and there is not mix using of older version of Velero with v1.11?

**Comment by schaze** [comment]
@Lyndon-Li I still had the old restic daemonset running in addition to the new nodeagent daemonset. Removed the old daemonset and now everything is working. Sorry for the false alarm & thanks for the hint!

**Comment by schaze** [comment]
User error
