### ISSUE TITLE
backup failing with PartiallyFailed error

### ISSUE THREAD

**Issue by sajuptpm** [vmware-tanzu/velero#6419]
For an automation test, we're trying to take backups of k8s services using velero v1.5.1 and few backups are intermittently getting **PartiallyFailed**. 

**The logs from velero is:**
```
time="2023-06-22T05:12:56Z" level=info msg="1 errors encountered backup up item" backup=edc/sec-postgres-daily-20230622044255 logSource="pkg/backup/backup.go:427" name= edc-postgres-postgresql-58497dcf46-87vvn
time="2023-06-22T05:12:56Z" level=error msg="Error backing up item" backup= edc / sec -postgres-daily-20230622044255 error="timed out waiting for all PodVolumeBackups to complete" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:172" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:431" name= edc-postgres-postgresql-58497dcf46-87vvn
```

**We have tried to add below changes:**

1) Increase the restic-timeout in velero deployment
2) Provide root permissions to restic container to do a volume backup in hostpath/podvolumes
3) Increase pre and post hooks time out in schedule.yaml for backups
4) Upgraded the velero chart version from v1.5.1 to v1.6.3

But none of them is solving the issue.

Could anyone please help on this?

**Environment:**

- Velero version (use `velero version`): 1.5.1
- Kubernetes version (use `kubectl version`): 1.17
- Kubernetes installer & version: 1.17

**Comment by blackpiglet** [comment]
Could get the failed PodVolumeBackup's status?
There should be more information on the failure in the status.

**Comment by sajuptpm** [comment]
apiVersion: velero.io/v1
kind: PodVolumeBackup
metadata:
  annotations:
  ... ...
spec:
  backupStorageLocation: default
  node: xxxxxxxx
  pod:
    kind: Pod
    name: xxxxxxxx
    namespace: xxxxxxxx
    uid: xxxxxxxx
  repoIdentifier: s3:https://<IP>:9000/xxxxxxxx/xxxxxxxx/restic/xxxxxxxx
  tags:
    backup: xxxxxxxx
    backup-uid: xxxxxxxx
    ns: xxxxxxxx
    pod: xxxxxxxx
    pod-uid: xxxxxxxx
    pvc-uid: xxxxxxxx
    volume: data
  volume: data
status:
  completionTimestamp: "2023-06-26T01:29:39Z"
  path: /host_pods/f97fde54-fec1-40b8-9d6f-4dbb415bae52/volumes/kubernetes.io~csi/pvc-54ca528a-2543-41bf-ad30-453981db90f0/mount
  phase: Completed
  progress:
    bytesDone: 129977191
    totalBytes: 129977191
  snapshotID: 509b81a7
  startTimestamp: "2023-06-26T01:24:28Z"

**Comment by blackpiglet** [comment]
The PodVolumeBackup is a successful one.
If your scenario needs to enlarge the PodVolumeBackup timeout setting, you set the `--restic-timeout` parameter in the Velero deployment's command set, for example:

``` yaml
    spec:
      containers:
      - args:
        - server
        - --features=EnableCSI
        - --restic-timeout=8h
```

**Comment by sajuptpm** [comment]
Hi blackpiglet,
We already tried this, but didn't fix PartiallyFailed error.

**Comment by blackpiglet** [comment]
Although your k8s environment version is v1.17, I think Velero v1.7.x or v1.8.x should work.
I also suggest upgrading the Velero version. The Velero team uses the n-2 support policy. v1.5 is already out of supporting scope.

**Comment by blackpiglet** [comment]
Close for not updating for a long time. Feel free to reopen when new information is found.
