### ISSUE TITLE
Velero Backup Partially Failed - AWS Volume Snapshot

### ISSUE THREAD

**Issue by ShubhamGorlewar1** [vmware-tanzu/velero#6421]
**What steps did you take and what happened:**

 I tried to backup  the EKS NS with persistent volume  and sometimes it takes long time to create a snapshot and shows in progress in AWS (1 or 10%) after some time  aws managed to create the snapshot of the volume however in mean time Velero shows **Partially failed**.  

Some time the same scenario works very  fast and  velero show success on backup.
Size of volume are in between 70 - 100 GB.  

**What did you expect to happen:**
 I expect Velero should wait for AWS and double verify weather the snapshot is still in progress or not  and  then show error if any

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_   **Velero Version Version:** v1.11.0
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**ERROR : /persistentvolumes name: /pvc-a52525XXXXXXXXX11eaa5f error: /rpc error: code = Unknown desc = missing region in aws configuration**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"
- 
![image](https://github.com/vmware-tanzu/velero/assets/68949895/11f204ae-0952-44e3-813b-60127f6fd671)

**Comment by blackpiglet** [comment]
`missing region in aws configuration`
I think this is the reason for failure. If you are using `velero install` command line to install Velero, `--snapshot-location-config` needs to set region for AWS snapshotter to work, e.g. `--snapshot-location-config region=us-west-2`.

But I'm not sure why there is a chance of success. If your scenario involves volume data backup, and it's using AWS snapshot instead of file system backup, it should fail.

**Comment by blackpiglet** [comment]
No feedback for a while, close for now. If anything still needs clarification, feel free to open.
