### ISSUE TITLE
Velero doesn't support OpenStack CSI topology

### ISSUE THREAD

**Issue by kayrus** [vmware-tanzu/velero#6440]
**What steps did you take and what happened:**

Create a backup with a snapshot using https://github.com/Lirt/velero-plugin-for-openstack plugin
See `level=info msg="zone info not available in nodeAffinity requirements"` in logs.

**What did you expect to happen:**

Velero should have an ability to support OpenStack CSI topologies:

* `topology.cinder.csi.openstack.org/zone`
* `topology.nfs.manila.csi.openstack.org/zone`
* `topology.ceph.manila.csi.openstack.org/zone`
* `topology.disk.csi.everest.io` from Huawei cloud
* any other custom topology, since CSI driver name depends on the FS type.

Ideally it should be nice to extend the snapshotter plugin interface with the `GetVolumeTopologyKey` method. So each velero plugin can share the topology key it uses.

See also:

https://github.com/vmware-tanzu/velero/blob/bbef180a0f3b02465fb8a83dfdcf726251b2b6ad/pkg/backup/item_backupper.go#L509

https://github.com/vmware-tanzu/velero/blob/bbef180a0f3b02465fb8a83dfdcf726251b2b6ad/pkg/backup/item_backupper.go#L440-L446

https://github.com/vmware-tanzu/velero/issues/103

**Environment:**

- Velero version (use `velero version`): 1.10.1
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): 1.25
- Kubernetes installer & version: 1.25
- Cloud provider or hardware configuration: OpenStack cloud provider 1.25.x
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
Although the `velero-plugin-for-openstack` is not officially supported, I think this is probably easy to implement, would you  contribute?

**Comment by kayrus** [comment]
@reasonerjt it's easy to implement, but the proper way to do this is to to extend the interface, which would cause all plugins to be adjusted. I'm not against to submit the PR, but I think that this is something that maintainer should discuss and approve first.

**Comment by sseago** [comment]
Velero-plugin-for-openstack provides direct support for swift (object store plugin) and cinder (snapshots).

Although in this case, it looks like all of the storage drivers in use for volumes are CSI-based. Would the CSI plugin be an option? The only downside is that until Velero 1.12, you won't get off-cluster backups of volumes, but it might be worth checking to see whether basic CSI snapshot functionality works with these volumes, because if it does, then the data movement currently scheduled for Velero 1.12 should work for you.

**Comment by sseago** [comment]
@kayrus extending a plugin interface is a larger undertaking, requiring a new API version to be proposed, a new implementation of this API, and an adapter layer to allow existing plugins to continue to function without modification. See the work done in Velero 1.11 to support BackupItemActionV2 and RestoreItemActionV2.

**Comment by kayrus** [comment]
@sseago ok, let's keep a new interface for a long-term solution. As for the short-term, I think I can add a couple of common OpenStack CSI zone keys.

**Comment by kayrus** [comment]
@sseago it appeared that topology keys in OpenStack CIS are actually hardcoded, however the Manila driver name could be changed, fortunately it doesn't affect topology key. See a PR submitted, I hope it's clean and simple as much as possible.
