### ISSUE TITLE
Velero Backup Partially Failed - pod is not in expected status

### ISSUE THREAD

**Issue by jack1234-cloud** [vmware-tanzu/velero#6454]
What steps did you take and what happened:
I took a backup using "velero create backup --include-namespaces " and got this error (PartiallyFailed):

Error:

pod is not in the expected status, name_of_pod, namespace, phase=Succeeded: pod is not running

What did you expect to happen:
We expected a backup of completed

The following information will help us better understand what's going on:

If you are using velero v1.7.0+: Velero Version (Client & Server) Version: v1.11.0
Please use velero debug  --backup <backupname> --restore <restorename> to generate the support bundle, and attach to this issue, more options please refer to velero debug --help

If you are using earlier versions:
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com/) or other pastebin is fine.)

kubectl logs deployment/velero -n velero
velero backup describe <backupname> or kubectl get backup/<backupname> -n velero -o yaml
velero backup logs <backupname>
velero restore describe <restorename> or kubectl get restore/<restorename> -n velero -o yaml
velero restore logs <restorename>

Anything else you would like to add:

pod has a status of "COMPLETED"

I see a fix has been pushed as part of https://github.com/vmware-tanzu/velero/issues/2395 - is this included in version 1.11??

Environment:

Velero version (use velero version): Version: v1.11.0
Velero features (use velero client config get features): features NOT SET
Kubernetes version (use kubectl version): 1.21
Kubernetes installer & version: AWS EKS & 1.21
Cloud provider or hardware configuration: aws
OS (e.g. from /etc/os-release): Amazon Linux
Vote on this issue!

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).
Use the "reaction smiley face" up to the right of this comment to vote.

👍 for "I would like to see this bug fixed as soon as possible"
👎 for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
This is a[ known issue](https://github.com/vmware-tanzu/velero/issues/6182) and will be fixed in 1.11.1.

**Comment by jack1234-cloud** [comment]
@Lyndon-Li - when will 1.11. be released?

**Comment by reasonerjt** [comment]
We are holding v1.11.1 for golang 1.20.6 to fix some CVEs.

**Comment by reasonerjt** [comment]
Closing as a dup of #6182

**Comment by karan1ngit** [comment]
> We are holding v1.11.1 for golang 1.20.6 to fix some CVEs.

when will 1.11.1 be released?

**Comment by mateusoliveira43** [comment]
It was released yesterday @karan1ngit :smile: 
https://github.com/vmware-tanzu/velero/releases/tag/v1.11.1
