### ISSUE TITLE
No resticrepositories resource

### ISSUE THREAD

**Issue by sherlant** [vmware-tanzu/velero#6457]
Hi,
i have make a schedule in my cluster, who backup volumes in s3. I have in the s3 bucket the restic repo with my data, but i have no resticrepositories resource in my cluster ?

Any idea ?

thx

**Comment by kkothule** [comment]
@sherlant can you share more details 
velero version:
Command used to install velero:

**Comment by sherlant** [comment]
sure,
my velero version is v1.10.2, and i have installed it on kubernetes cluster 1.21, with the helm chart

**Comment by allenxu404** [comment]
@sherlant Just a heads up, starting from Velero v1.10, the `ResticRepository` resource has been renamed to `BackupRepository`.
