### ISSUE TITLE
Feature to modify/delete volume's [PV's] nodeaffinity region during restore

### ISSUE THREAD

**Issue by sudarshan-sr** [vmware-tanzu/velero#6462]
**Describe the problem/challenge you have**
**Scenario**:
1) Source - EKS cluster with volumes. - Volumes [PV and PVC's] are backed up with velero to S3 bucket
2) Destination - Azure AKS. Volumes [PV and PVC's] are restored using velero.
3) When we create a pod and attach it to the PVC in the destination AKS cluster, we are getting error - "1 node(s) had volume node affinity conflict"
Note: we are using FSB [File System Backup]

If we describe the restored volume [PV] in Azure AKS, it has the nodeAffinity defined in the spec.
The zones are AWS zones - "us-east1a, us-east-1"

![image](https://github.com/vmware-tanzu/velero/assets/84263536/c934a044-8fe7-45fd-b35f-78f0b3a72cce)

**Describe the solution you'd like**

One solution would be - velero to have an ability to modify the volume [PV] during restoration.
In this case an ability to delete/modify the node affinity rules, so that volume/PV restoration from EKS AWS zone - us-east-1 can be done to Azure AKS zone - EastUS. 

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
velero version
Client:
        Version: v1.11.0
        Git commit: 0da2baa908c88ec3c45da15001f6a4b0bda64ae2
Server:
        Version: v1.11.0

- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:39:03Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.5+k3s1", GitCommit:"48e5d2af5bfc69db051d46b6c6b83c46d15a9da5", GitTreeState:"clean", BuildDate:"2022-12-21T00:06:36Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version: EKS and AKS
- Cloud provider or hardware configuration: AWS and Azure
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by anshulahuja98** [comment]
To be supported through #5880 which is underway impl

**Comment by reasonerjt** [comment]
Thanks @anshulahuja98 
I'll keep this open to double check if it's right to remove constraints in certain cases without having to add attributes to the CRs.

**Comment by blackpiglet** [comment]
One thing that needs consideration is different providers may have different zone and region keys.

```
const (
	zoneLabelDeprecated = "failure-domain.beta.kubernetes.io/zone"
	// this is reused for nodeAffinity requirements
	zoneLabel = "topology.kubernetes.io/zone"

	awsEbsCsiZoneKey = "topology.ebs.csi.aws.com/zone"
	azureCsiZoneKey  = "topology.disk.csi.azure.com/zone"
	gkeCsiZoneKey    = "topology.gke.io/zone"
	gkeZoneSeparator = "__"

	// OpenStack CSI drivers topology keys
	cinderCsiZoneKey = "topology.manila.csi.openstack.org/zone"
	manilaCsiZoneKey = "topology.cinder.csi.openstack.org/zone"
)
```

**Comment by anshulahuja98** [comment]
@reasonerjt  / @blackpiglet do we really need this in 1.13?
this is already supported by resourcemodifiers.

Even blackpiglet's concern will be solved.

**Comment by reasonerjt** [comment]
I also think this can be fixed via resourcemodifer.
Just keeping this open to verify and if it works I'll close this PR.

**Comment by SCLogo** [comment]
> resourcemodifiers

can you link docs ?

**Comment by anshulahuja98** [comment]
https://velero.io/docs/main/restore-resource-modifiers/

**Comment by reasonerjt** [comment]
@sudarshan-sr 

FSB in velero normally works with dynamic provisioning in which case the `nodeAffinity` will not be carried over.
Having said that, the link provided by Anshul is capable of modifying the spec of resources during restore.

I'm closing the issue as resolved.

**Comment by PaperElmo** [comment]
is resourcemodifiers supports EBS snapshot? I cannot modify the zone (same region) if using PV snapshot
