### ISSUE TITLE
velero-plugin-for-gcp csi driver types other than pd.csi.storage.gke.io

### ISSUE THREAD

**Issue by richardjennings-occrp** [vmware-tanzu/velero#6470]
**Describe the problem/challenge you have**

velero-plugin-for-gcp does not support csi driver types other than `pd.csi.storage.gke.io`

For example https://github.com/edgelesssys/constellation uses a driver type `gcp.csi.confidential.cloud`.

**Describe the solution you'd like**

I would like to be able to either configure support for `gcp.csi.confidential.cloud` or have it included by default.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
Looks like this issue is already addressed in the PR https://github.com/vmware-tanzu/velero-plugin-for-gcp/pull/146.
This issue can be closed.

**Comment by reasonerjt** [comment]
Closing since this has been fixed in v1.12
