### ISSUE TITLE
Need volume snapshots restored info in restore details

### ISSUE THREAD

**Issue by eastaga** [vmware-tanzu/velero#6478]
**Describe the problem/challenge you have**
Need information on Volume Snapshot restored in restore details.

**Describe the solution you'd like**
Currently we get information of restic volumes restore in restore details
```
velero describe restore restore-with-fsb --details
Name:         restore-with-fsb

Restic Restores:
  Completed:
    csi/app: persistent-storage
```

Can we get similar info for CSI volumes restored?

**Anything else you would like to add:**
The information can be added in similar fashion as that of backup i.e. `DownloadTargetKind `

**Environment:**

- Velero version (use `velero version`): 1.10.0
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
There may be other ways, I'll double check the operation item json generated by CSI plugin.

**Comment by blackpiglet** [comment]
https://github.com/vmware-tanzu/velero/blob/3e613862e6e40b18bd3044f8f86296840db0c067/pkg/cmd/cli/restore/describe.go#L73-L90

For the filesystem restore, the related PVR is retrieved by the k8s client. 
For the short term, it should be OK to also list VolumeSnapshot and DataUpload by k8s client too.

**Comment by reasonerjt** [comment]
With the introduction of `vol-info` to bakckup, we probably can achieve this on client side, by going over the restored PV/PVC and querying the `vol-info` of the backup

**Comment by reasonerjt** [comment]
The idea to get the PVC restore info via `vol-info` from the backup is problematic, the PVC's name and namespace can be changed via resource modifiers.
Additionally, in future there may be difference in details regarding how the PV is handled in backup .vs. restore.

We probably will need to introduce additional metadata to track the information of PV/PVCs and make the workflow more reliable.

Opened issue #7546
