### ISSUE TITLE
Async operation sets backup/restore to Completed status falsely

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#6490]
If a backup has multiple async operations and one operation fails while others are still in-progress, the [code here](https://github.com/vmware-tanzu/velero/blob/17d782f2bb2b6fac427ae77bac7659db3fd2462a/pkg/controller/backup_operations_controller.go#L193), which is used to set the backup to `BackupPhaseWaitingForPluginOperationsPartiallyFailed`, is not executed since the `stillInProgress` is false.
Then later inside `updateBackupAndOperationsJSON`, the error recorded in `itemoperationmap.OperationsForBackup.ErrsSinceUpdate` will be cleared by `itemOperationsMap.UploadProgressAndPutOperationsForBackup` (by its further call to `uploadProgress`).

As a result, no one will set the backup to `BackupPhaseWaitingForPluginOperationsPartiallyFailed` and so the backup get to `BackupPhaseFinalizing` and then `Completed` status.

Restore is the same.

**Comment by sseago** [comment]
@Lyndon-Li good catch -- looks like Restore has the same issue.

**Comment by Lyndon-Li** [comment]
@sseago Thanks for the reminding. I have modified the issue and PR to include the restore case.
