### ISSUE TITLE
BIAv2 error log should say which plugin it came from (when empty).

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#6512]
**Describe the problem/challenge you have**

It is possible to end up with log that looks like this.
```
"time=\"2023-07-17T12:58:45Z\" level=error msg=0 backup=openshift-adp/mysql-twovol-csi-e2e-77421487-24a1-11ee-a705-0a580a81e778 logSource=\"pkg/controller/backup_controller.go:717\""
```

https://github.com/vmware-tanzu/velero/blob/55987c3093c6b0b40eb4f1cf428032c90b68eaa1/pkg/controller/backup_controller.go#L717-L718

While having a full logs with other log levels could potentially help identify the problematic plugin with empty error log, it would be better to have level=error logs contain all the necessary info to debug which plugin is outputting this empty error log.

**Describe the solution you'd like**

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
@kaovilai 
Could you give me some hints on how to generate such "empty error log"?

**Comment by kaovilai** [comment]
We don't know where but it seems like some backup item action was logging empty strings.

Since it looks like this function knows what plugin name is, it's helpful to include plugin name in the log.

**Comment by reasonerjt** [comment]
This is specifical to the returned error message by function `getBackupItemOperationProgress`.

I'll make update to make sure the BIAv2's plugin name included.

**Comment by kaovilai** [comment]
Commit here LGTM https://github.com/reasonerjt/velero/commit/be4c63603e44319a1193625924d6ec1c8d058b60

As to reproducing the issue, I'm not sure I remember how we got here.
