### ISSUE TITLE
PVC restore fails after kubernetes cluster is reset

### ISSUE THREAD

**Issue by rangnar14** [vmware-tanzu/velero#6535]
**What steps did you take and what happened:**
Create a kubernetes cluster using kubeadm and deploy applications (including velero, trident operator, csi related resources) 
using velero , created a backup.
Kubernetes cluster was reset
A new cluster was initiated
velero, trident, csi related resources were deployed
a restore was created using velero using the backup created above

The volume snapshot created but READYTOUSE is false. On describing the VS it says
 Error:
    Message:     Failed to check and update snapshot content: failed to list snapshot for content velero-velero-storage-monitoring-loki-0-jf5kn-4wrn8: "can not find snapshot for snapshotID pvc-5ba3336d-972e-418f-bafb-8136a7525653/snapshot-7981ec17-adb3-435a-a53a-669042e54aee"

Volume snapshot yaml : https://gist.github.com/rangnar14/09439ce9e9abb61466ccfa6e78d1e207
But the snapshot is present in the storage side. 

This happens only if we try to restore after cluster is destroyed and recreated.

If an application is deleted to simulate a disaster and then try to restore, it works fine.

We are using NETAPP ONTAP  trident operator 
**What did you expect to happen:**
All resources in the backup should be restored

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 
When I ran the above, I got the below error
2023/07/21 10:49:56 Collecting velero resources in namespace: core
An error occurred: exec failed: Traceback (most recent call last):
  velero-debug-collector:23:13: in <toplevel>
  <builtin>: in kube_get
Error: could not initialize search client: stat /root/.kube/config: no such file or directory

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml` https://gist.github.com/rangnar14/51659dc595428981f9d84682185204b3
- `velero restore logs <restorename>`   https://gist.github.com/rangnar14/c26c43a98ec38e908cf29bfdb601570b

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Using this version
Client:
        Version: v1.11.0
        Git commit: 0da2baa908c88ec3c45da15001f6a4b0bda64ae2
Server:
        Version: v1.11.0

- Velero features (use `velero client config get features`): 
velero client config get features
features: <NOT SET>
- Kubernetes version (use `kubectl version`):
-WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.15", GitCommit:"2c67202dc0bb96a7a837cbfb8d72e1f34dfc2808", GitTreeState:"clean", BuildDate:"2023-06-14T09:56:11Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.15", GitCommit:"2c67202dc0bb96a7a837cbfb8d72e1f34dfc2808", GitTreeState:"clean", BuildDate:"2023-06-14T09:48:46Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.15", GitCommit:"2c67202dc0bb96a7a837cbfb8d72e1f34dfc2808", GitTreeState:"clean", BuildDate:"2023-06-14T09:54:33Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
On prem 

- OS (e.g. from `/etc/os-release`):
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by rangnar14** [comment]
Volume Snpashot yaml:
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  annotations:
    backup.velero.io/must-include-additional-items: "true"
    velero.io/csi-driver-name: csi.trident.netapp.io
    velero.io/csi-volumesnapshot-handle: pvc-5ba3336d-972e-418f-bafb-8136a7525653/snapshot-7981ec17-adb3-435a-a53a-669042e54aee
    velero.io/csi-vsc-deletion-policy: Retain
    velero.io/vsi-volumesnapshot-restore-size: 12848Ki
  creationTimestamp: "2023-07-21T09:25:41Z"
  finalizers:
  - snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
  generation: 1
  labels:
    velero.io/backup-name: bkp-monitoring-pvc-only-21-07
    velero.io/restore-name: restore-bkp-monitoring-pvc-only-21-07
  name: velero-storage-monitoring-loki-0-jf5kn
  namespace: monitoring
  resourceVersion: "2347"
  uid: 65acf0ad-dc87-4dc2-a144-05f7a2e82eae
spec:
  source:
    volumeSnapshotContentName: velero-velero-storage-monitoring-loki-0-jf5kn-4wrn8
  volumeSnapshotClassName: csi-snapclass
status:
  boundVolumeSnapshotContentName: velero-velero-storage-monitoring-loki-0-jf5kn-4wrn8
  error:
    message: 'Failed to check and update snapshot content: failed to list snapshot
      for content velero-velero-storage-monitoring-loki-0-jf5kn-4wrn8: "can not find
      snapshot for snapshotID pvc-5ba3336d-972e-418f-bafb-8136a7525653/snapshot-7981ec17-adb3-435a-a53a-669042e54aee"'
    time: "2023-07-21T09:25:41Z"
  readyToUse: false

**Comment by sseago** [comment]
If you're using the CSI plugin, the VolumeSnapshotContent remaining in the cluster on backup is needed for restore. This plugin is sufficient when only namespaces are affected, but not for full cluster disaster recovery. The upcoming 1.12 release will introduce a new data mover based on CSI snapshots and the csi plugin which will back up the VolumeSnapshotContents into the BSL. In the meantime, if you need full disaster recovery functionality for volumes, you should use either the filesystem backup feature (using kopia or restic) or if you're using cloud volumes (ebs, azure, gcp), you can also disable the CSI plugin and use the cloud volumesnapshotter plugins.

**Comment by rangnar14** [comment]
When is the release of 1.12 planned for ?

**Comment by shubham-pampattiwar** [comment]
@rangnar14 The GA date for 1.12 is Aug 30th. you can refer the wiki for more details: https://github.com/vmware-tanzu/velero/wiki/1.12-Roadmap

**Comment by rangnar14** [comment]
On this slack thread it was mentioned velero restore is happening fine and to look more on csidriver side

> It seems Velero restore worked as expected. VolumeSnapshotContent's error is the key here and more information may be available in CSI driver logs

The link to the slack thread is
https://app.slack.com/client/T09NY5SBT/C6VCGP4MT/thread/C6VCGP4MT-1689943697.164739
So I got confused a bit.

Can you please checkout the slack thread and help us with some clarifications.

**Comment by blackpiglet** [comment]
@rangnar14 
After testing, in normal cases, deleting VolumeSnapshotContent created by backup doesn't impact the restore.

I guess the error of cannot find the snapshot reported in restore in your scenario is a corner case.
Velero will create VolumeSnapshot and VolumeSnapshotContent for PVC during restore, and the `DeletionPolicy` of VS and VSC is set according to the used VolumeSnapshotClass. I think it's `Delete` in your scenario. After the VSC and VS turned the status `ReadyToUse` to `true`, Velero will recreate the VSC with `DeletionPolicy` set to `Retain` and delete VS. The reason for doing this is to avoid deletion of the namespace of VS causing snapshots to be deleted and backup cannot be used either.

If you delete the VolumeSnapshotContent before Velero recreates the VolumeSnapshotContent, then the described problem happens. Please check whether this is what happened in your scenario.

**Comment by blackpiglet** [comment]
Close for now. If anything is still unclear, feel free to reopen.
