### ISSUE TITLE
Support changing existing backup repository password

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#6537]
After a backup repository is created, users may want to change the repo password.
It is possible for some kind of repositories (i.e., kopia), but not for some others. So this involves below changes:

- The changes in Unified Repository Interface
- A user interface to change repo password, i.e., a command line, instead of the current method -- configuring the secret, because it is less interactive
- An end to end approach for synchronized checking (for repo password is changeable), changing and error handling
- A repo may be used by multiple instance of Velero across multiple clusters, once the password is changed for an existing repo, any instance of Velero that uses the repo will need to use the new password

**Comment by Lyndon-Li** [comment]
We may need to figure out a way to keep the password by Velero, ideally, the password could be saved and retrieved across multiple cluster, i.e., using a KMS. Otherwise, we have no way to get the up-to-date password wherever it is required for each repo.

**Comment by reasonerjt** [comment]
Currently, the secret in k8s stores the password for accessing the backup repo, so we can't change the backup repo's password every time the secret changes.

Additionally, a backup repo may be accessed by multiple velero instances, it's tricky to introduce a mechanism to control which velero is the "admin" of the repo.

If a user wants to change the secret, he/she may download kopia's CLI, access the repo and change the password, then update the secret used by velero so velero can use the new password to access the backup repo.

**Comment by shawn-hurley** [comment]
If this is doable by the CLI, I do wonder if we could create some interface/API to achieve this. The first thing that comes to mind is a sub-resource, but IIRC CRDs don't have access to these yet. 

Just throwing it out there as a possible solution as well.

**Comment by percy78** [comment]
@Lyndon-Li Hi sorry but I believe I encounter the same issue? I've just installed velero catering for our MariaDB galera cluster using PVC on local storage in a RKE2 cluster. 

Issue below?

`error running restic backup command restic backup --repo=s3:http://minio-sr3.tempo-minio-distributed.svc.cluster.local:9000/velero/restic/keycloak --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic . --tag=backup=11-15-20230914144122 --tag=backup-uid=a09d1f5c-72cc-499f-afb3-a287c2da3869 --tag=ns=keycloak --tag=pod=keycloak-db-sr3-0 --tag=pod-uid=4aed6911-f79d-420d-85c8-9973d3d0b1fe --tag=pvc-uid=e9325275-4910-4dee-9085-bcf504e4b413 --tag=volume=data --host=velero --json with error: exit status 1 stderr: Error loading snapshot d09a4801: ciphertext verification failed\ngithub.com/restic/restic/internal/restic.findLatestSnapshot.func1\n\tgithub.com/restic/restic/internal/restic/snapshot_find.go:35\ngithub.com/restic/restic/internal/restic.ForAllSnapshots.func1\n\tgithub.com/restic/restic/internal/restic/snapshot.go:92\ngithub.com/restic/restic/internal/restic.ParallelList.func2\n\tgithub.com/restic/restic/internal/restic/parallel.go:45\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.1.0/errgroup/errgroup.go:75\nruntime.goexit\n\truntime/asm_amd64.s:1598\n"," name: /keycloak-db-sr6-0 error: /pod volume backup failed: running backup,`
