### ISSUE TITLE
Need a confirmation for velero plugin add command

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#6542]
`velero plugin add` may cause the Velero server pod restart, so it is a dangerous operation -- once Velero server restarts, all the ongoing jobs will fail.
Therefore, we need some way of alert and confirmation to users before executing for this command.

**Comment by kaovilai** [comment]
you can assign me this issue!

**Comment by kaovilai** [comment]
unstale

**Comment by kaovilai** [comment]
unstale
