### ISSUE TITLE
alpine can not be pulled in some environments when moving snapshot

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#6561]
We use the `alpine:latest` as the image for the pod in data mover, however, it cannot be pulled in some environments, e.g. airgap env or env reaches the pull limit of Dockerhub.

Besides, we also need to consider the maintenance effort for the new image, e.g. CVE 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
Fixed by #6564
