### ISSUE TITLE
Adding hook command status in backup/restore status or describe command

### ISSUE THREAD

**Issue by eastaga** [vmware-tanzu/velero#6567]
**Describe the problem/challenge you have**
Currently to check if the command in backup/restore hooks got executed successfully or not, we need to browse through the velero logs.

**Describe the solution you'd like**
We can either add the command result in Backup Status or propagate that info in describe command.

**Anything else you would like to add:**
N/A

**Environment:**

- Velero version (use `velero version`): 1.10.3
- Kubernetes version (use `kubectl version`): 1.25
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by sseago** [comment]
I think describe would be the best place for this.

**Comment by anshulahuja98** [comment]
After the PR: https://github.com/vmware-tanzu/velero/pull/6553
We should have the appropriate errors captured in the backup /restore results and hence part of the describe command
we should not need anhy other additional mechanism and rely on backup/restore result where we will focus to properly format the message as part of above PR.

**Comment by allenxu404** [comment]
With the backup/restore result within which the hook errors are already captrured, we can implement this feature following the steps below:

1. Add a unique key to hook errors. This key will enable us to identify if any errors occur during the execution of hooks by checking its presence in the backup/restore result.
2. Add a new field `status` under the hook section in velero backup/restore desrcibe. This `status` field will have two possible values: `failed` and `succeeded` if `status` is set to `failed`, user can refer to the `Errors` section to obtain detailed error messages.

**Comment by Shashank1306s** [comment]
The backup and restore result are only meant to only surface the warning/error that is present in the velero execution under the categories namely namespace, velero, cluster level warning/error.

So, the hooks failure status can be added. the success execution status can be checked in the logs. Also with this PR: #6553, all errors/warning related to hook execution will be floated in the backup/restore result.

**Comment by allenxu404** [comment]
After discussion with @reasonerjt , we think hook execution status should also be included in status of Backup/Restore CR. This inclusion would enable users to be informed of any hook errors without the need to run `Velero describe` separately. Do you have any concerns regarding this proposal? @anshulahuja98 @sseago

**Comment by anshulahuja98** [comment]
> After discussion with @reasonerjt , we think hook execution status should also be included in status of Backup/Restore CR. This inclusion would enable users to be informed of any hook errors without the need to run `Velero describe` separately. Do you have any concerns regarding this proposal? @anshulahuja98 @sseago

@Shashank1306s can you have a look at this?

**Comment by allenxu404** [comment]
Hi @anshulahuja98 @Shashank1306s, Is there a possibility for us to expedite the discussion and reach a decision promptly, as the deadline is approaching?

**Comment by anshulahuja98** [comment]
@allenxu404 do you have a rough contract of how it will show up in the status?

At a high level it does seem like a good idea to put it in status, but with the consideration that the status field will slightly bloat up. 

if in the status we are not able to say populate all details which is informative enough to end user, then it might be better to stick to current approach.

**Comment by allenxu404** [comment]
IMO, the backup/restore status will look like:
```
status:
  completionTimestamp: "xxxx"
  errors: 1
  hookErrors : 1
  expiration: "xxxx"
  formatVersion: 1.1.0
  phase: PartiallyFailed
  progress:
    itemsBackedUp: 16
    totalItems: 16
  startTimestamp: "xxxx"
  version: 1
```
It only stores the number of hook execution errors. If users want to know the details of hook errors, they can run `Velero describe` to get more info in which result already capture all the error messages. 

what's your thoughts? @anshulahuja98 @reasonerjt

**Comment by anshulahuja98** [comment]
similar to other status fields today, we can also add succeeded count perhaps here.
Something like 
HooksAttemptedCount
HookFailedCount

Overall, **I don't have a strong opinion about this**, I am okay either way if put it in status or if we don't.

**Comment by allenxu404** [comment]
> similar to other status fields today, we can also add succeeded count perhaps here.
Something like
HooksAttemptedCount
HookFailedCount

Make sense. Will implement it following this pattern.
