### ISSUE TITLE
Nominate Anshul Ahuja as a maintainer

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#6570]
Anshul (@anshulahuja98) has been active in making contributions to project velero including making improvements and design and implementing new features

A few examples include[ supporting multiple VolumeSnapshotClasses in CSI Plugin](https://github.com/vmware-tanzu/velero/pull/5774)  [ supporting for ResourceModifier (AKA Json Substitutions) in restore flow](https://github.com/vmware-tanzu/velero/pull/6452)

@vmware-tanzu/velero-maintainers Please vote by adding comments to this issue.

**Comment by ywk253100** [comment]
+1

**Comment by Lyndon-Li** [comment]
+1

**Comment by sseago** [comment]
+1

**Comment by qiuming-best** [comment]
+1

**Comment by shubham-pampattiwar** [comment]
+1

**Comment by reasonerjt** [comment]
Since we've reached the majority, I'll add Anshul as a maintainer of project velero.

Congratulations @anshulahuja98

**Comment by anshulahuja98** [comment]
Thank you everyone for your trust!
