### ISSUE TITLE
Backup storage location setting is not work

### ISSUE THREAD

**Issue by qiuming-best** [vmware-tanzu/velero#6572]
**What steps did you take and what happened:**

1. First creating one new bsl named 'bsl-test'
2. Setting the `bsl-test` as default BSL
velero backup-location set bsl-test --default
3. Executing `velero backup-location get` 
```bash
NAME       PROVIDER   BUCKET/PREFIX   PHASE       LAST VALIDATED                  ACCESS MODE   DEFAULT
bsl-test   aws        mqiu-bucket     Available   2023-08-01 14:39:17 +0800 CST   ReadWrite     true
default    aws        mqiu-bucket     Available   2023-08-01 14:38:39 +0800 CST   ReadWrite     true
```
5. Do backup without specify which BSL used
```bash
velero backup create t3 --include-namespaces nginx-example --default-volumes-to-fs-backup --snapshot-volumes=false --wait
```
7. Describe backups shows it still using the `default` BSL instead of the specific one
```bash
velero backup get t3
NAME   STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
t3     Completed   0        0          2023-08-01 14:42:44 +0800 CST   29d       default            <none>
``` 
**What did you expect to happen:**
1. Executing `velero backup-location get`  only shows one BSL as the default 
2. Backup should backed up into the default BSL

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
https://github.com/vmware-tanzu/velero/blob/497543774cac18a3022f1983bce6af1c38a3a509/pkg/controller/backup_controller.go#L356-L373

I think this issue is related to the piece of code.
When a backup doesn't specify the BSL, Velero will first set the selected BSL to the default BSL, which is `default`. Then Velero will list all BSL in the installed namespaces, and return with the first BSL set as default. It looks like the client-go's list result is sorted by the resource's creation time, so the `default` BSL is always the first one.
That's why the new set-as-default BSL operation cannot take effect.

**Comment by blackpiglet** [comment]
I agree the new BSL set to default should come first.
How about we change to collect all BSLs that are set as default, then sort them by creation time? The newest comes first, and if the creation time is the same, sort by name then.

**Comment by shawn-hurley** [comment]
Rather than making this consistent when multiple defaults are used, can we just error and make the user have a single default?

It might be nice to have some validation for this in CEL as well

**Comment by blackpiglet** [comment]
@shawn-hurley 
What CEL is short for? Do you mean to consider adding some checks in other CRUD operations?

I think both of the methods have their own benefit.
Allowing multiple BSLs is more convenient for use, but it can cause some confusion for users who don't expect default BSL change.

Limiting default BSL to only one makes things consistent. We may need to make limitations to BSL creation, update, and deletion. It's a bit less user-friendly to me.

**Comment by reasonerjt** [comment]
How about this:
1. When a BSL is updated as default, the controller will unset other default BSLs
2. Step 1 is not atomic, so BSL controller will periodically queries the BSLs and make sure the most recently updated BSL remains default and the older defauls BSLs will be unset.

**Comment by shawn-hurley** [comment]
for CEL: https://kubernetes.io/blog/2022/09/29/enforce-immutability-using-cel/#basics-of-validation-rules

That might be an excellent place to start, but there is a whole specification that could be of use.

I am trying to figure out how I feel about the old default being unset. One option is for us to see how CSI handled this exact scenario. I would rather have two defaults and make it consistent with what is chosen. 

The question we should ask is, what would be the best user experience?  I think forcing the user to choose the default clearly would lead to the least surprising experience, but I may be incorrect. What do y'all think?

**Comment by sseago** [comment]
If we can do this with validation rules, we won't need to do ugly things like "if a user sets a default, then unset other defaults" which may not be correct behavior. If the second default setting simply fails to create (invalid CR), then the user will need to modify the old default to make it not default before re-attempting to create the new default.

**Comment by qiuming-best** [comment]
@shawn-hurley 
I think both `volume snapshot` and `CSI snapshot` are not related to BSL.
- For `volume snapshot` it will store the volumes to the location[ set by VSL](https://github.com/vmware-tanzu/velero/blob/v1.12.0-rc.1/pkg/backup/item_backupper.go#L570-L592)
- For `CSI snapshot`, The location of snapshots is usually determined by public cloud service providers based on the region where the volume is located

So it would not break the consistency when we change the behavior of the default backup-location?

CEL seems more suitable for static checks and validation of fields within objects. For cases like ours, where we need to determine whether a BSL is already set to default in the environment before creating a new BSL CR, I'm unsure if CEL can accomplish this.

**Comment by shawn-hurley** [comment]
does this mean that we are going to use and create a webhook?

**Comment by draghuram** [comment]
I have always been confused by allowing multiple "defaults" which defeat the purpose of having a default. I agree with the approach described by @qiuming-best.

**Comment by blackpiglet** [comment]
@shawn-hurley 
Not necessarily a webhook, it can also be achieved by the Velero controller.

**Comment by blackpiglet** [comment]
@qiuming-best 
Deleting the BSL scenario should be also considered too, for example, if deleting the default BSL, maybe Velero should block that according to the current discussion.

**Comment by qiuming-best** [comment]
I'll fix this issue:
per our discussion above, the whole logic would be:
- If a default BSL exists, the verification will fail, and the user needs to perform the "unset" operation themselves.
- If a default BSL doesn't exist, the verification will succeed, allowing the setting of a new default BSL.
- If there is no default BSL,  it will fail when the user backup without specifying which BSL is used. (which means we allow users to delete default BSL).

If I've made any mistakes, please don't hesitate to correct me.
