### ISSUE TITLE
The second Restore failed with error "Target PVC xxx has already been bound, abort"

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#6574]
The steps to reproduce the issue:
1. Create a backup with data mover
2. Clear the workload
3. Restore
4. Restore again without clearing the workload

The `DataDownload` failed:
```
kubectl -n velero get datadownload dm-15-wxxw2 -o yaml
apiVersion: velero.io/v2alpha1
kind: DataDownload
metadata:
  creationTimestamp: "2023-08-01T07:31:53Z"
  generateName: dm-15-
  generation: 3
  labels:
    velero.io/async-operation-id: dd-cae130ab-dc87-4225-a0e7-524c2489fc47.a04b4c19-14d1-48b61e3ea
    velero.io/restore-name: dm-15
    velero.io/restore-uid: cae130ab-dc87-4225-a0e7-524c2489fc47
  name: dm-15-wxxw2
  namespace: velero
  ownerReferences:
  - apiVersion: velero.io/v1
    controller: true
    kind: Restore
    name: dm-15
    uid: cae130ab-dc87-4225-a0e7-524c2489fc47
  resourceVersion: "399789"
  uid: 6d428557-4708-4aab-83be-904f6cb931d2
spec:
  backupStorageLocation: default
  operationTimeout: 4h0m0s
  snapshotID: fbeb728a82a278a95275c6778c99daf2
  sourceNamespace: default
  targetVolume:
    namespace: default
    pv: ""
    pvc: etcd0-pv-claim
status:
  completionTimestamp: "2023-08-01T07:31:53Z"
  message: 'error to start restore expose: Target PVC default/etcd0-pv-claim has already
    been bound, abort'
  phase: Failed
  progress: {}
  startTimestamp: "2023-08-01T07:31:53Z"
```

Maybe we should skip the PVC if it already exist?

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
The current way that Velero work with existing objects is as below:

- It tries to create/restore the object arbitrarily
- If the creation fails due to `AlreadyExist`, it ignores the error and continue
- However, when the creation is called, the BIAs associated to the object have already been called, so as the data movers which are launched by the CSI plugin BIA

Therefore, it is more likely that we need to fix this by changing the existing Velero workflow. After all, set aside the current data mover problem, the result is unpredictable when calling BIAs to an already existing object.

**Comment by blackpiglet** [comment]
Checked with normal CSI plugin workflow, and the scenario doesn't cause a problem.
This is the second restore's resource list. The VolumeSnapshot resource failed because the VS already existed.
Just fix for the data mover case is enough.

```
Resource List:
  apps/v1/Deployment:
    - upgrade/hello-app(failed)
  apps/v1/ReplicaSet:
    - upgrade/hello-app-67ccdb8f7c(failed)
  snapshot.storage.k8s.io/v1/VolumeSnapshot:
    - upgrade/velero-kibishii-data-kibishii-deployment-0-hhdj9(failed)
  snapshot.storage.k8s.io/v1/VolumeSnapshotClass:
    - velero(skipped)
  snapshot.storage.k8s.io/v1/VolumeSnapshotContent:
    - snapcontent-9d480967-d8b8-4d72-9862-8d147e3aa7bd(failed)
  v1/ConfigMap:
    - upgrade/kube-root-ca.crt(failed)
  v1/PersistentVolume:
    - pvc-d09ea5d0-b771-46ae-b65f-d74959e81d1d(skipped)
  v1/PersistentVolumeClaim:
    - upgrade/kibishii-data-kibishii-deployment-0(failed)
  v1/Pod:
    - upgrade/hello-app-67ccdb8f7c-hpbmv(failed)
  v1/ServiceAccount:
    - upgrade/default(skipped)
```
