### ISSUE TITLE
Allow contributors to self assign issues

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#6579]
May reduce the need for https://github.com/vmware-tanzu/velero/issues/6545

Self-assigning, Self unassigning.

Immediate alternative: ping maintainers to assign issues.

**Comment by kaovilai** [comment]
cc: @draghuram

**Comment by reasonerjt** [comment]
Thanks @kaovilai could you add link to the bot you mentioned in the community meeting?

**Comment by kaovilai** [comment]
In kubernetes repositories, they can use prow commands to perform tasks in a PR.

See references below. I think consuming a premade github action would make sense as oppose to creating a new bot account + infra that watches the repo.

- [Prow Kubernetes CI/CD system](https://docs.prow.k8s.io/docs/overview/)
- [prow command references](https://prow.k8s.io/command-help)
- usage example https://github.com/kubernetes/test-infra/pull/30264
- [permissions/configurations](https://docs.prow.k8s.io/docs/components/plugins/approve/approvers/)
- A GitHub action that implements prow commands
  - https://github.com/marketplace/actions/prow-github-actions

**Comment by kaovilai** [comment]
[OWNERS file spec](https://go.k8s.io/owners)

**Comment by kaovilai** [comment]
[Interesting commands](https://github.com/jpmcb/prow-github-actions/blob/main/docs/commands.md) we might want if we go with this prow github actions

Commands | Policy | Description
-- | -- | --
/assign [@userA @userB @etc] | anyone | Assign other users (or yourself if no one is specified). Target user must be Org Member, Collaborator, or have previously commented
/unassign [@userA @userB @etc] | anyone | Unassigns specified people (or yourself if no one is specified). Target must have been already assigned.
/uncc [@userA @userB @etc] | anyone | Dismiss review request for specified people (or yourself if no one is specified). Target must already have had a review requested.
/close | Collaborators | closes the issue / PR
/reopen | Collaborators | reopens a closed issue / PR

**Comment by kaovilai** [comment]
Or rather, a simpler option..

[Triage role for the repository.](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization#repository-roles-for-organizations)

> Triage: Recommended for contributors who need to proactively manage issues, discussions, and pull requests without write access

**Comment by etc** [comment]
There are actual users with these names, you know.

**Comment by kaovilai** [comment]
just quoting from a readme oops :)
