### ISSUE TITLE
Wrong indent in "Restore Resource Modifiers" doc

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#6580]
https://github.com/vmware-tanzu/velero/blob/main/site/content/docs/main/restore-resource-modifiers.md?plain=1#L32-L42

![image](https://github.com/vmware-tanzu/velero/assets/5835782/13157853-2e00-45c2-885d-222cfc736c30)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
@anshulahuja98 Could you take a look?

**Comment by anshulahuja98** [comment]
Ack, will shortly send a fix PR.

**Comment by anshulahuja98** [comment]
Raised a PR @ywk253100
