### ISSUE TITLE
Update the status of Restore before removing the storage resources to indicate the actual status

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#6582]
The status of `Restore` isn't updated although I haved runed `velero restore delte` command:

```
velero restore get
NAME    BACKUP   STATUS      STARTED                         COMPLETED                       ERRORS   WARNINGS   CREATED                         SELECTOR
dm-15   dm-11    Completed   2023-08-01 15:31:42 +0800 CST   2023-08-01 15:31:56 +0800 CST   0        4          2023-08-01 15:31:42 +0800 CST   <none>
```
This is confusing, especially when the restore isn't deleted successfully due to some issues.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment]
Hmm. I'm not sure we need a separate deleting phase. It might be better to just check for deletion timestamp in those places that, in this PR, check for deleting phase. The velero restore get CLI output could also display "Deleting" if deletion timestamp is present. That's normally what kubernetes does for this sort of situation. For example kubectl get pods shows the phase value in the status output, except when DeletionTimestamp is set, then it shows Terminating. This avoids needing a special phase for terminating, and avoids needing to make an update to a terminating resource (which could fail if the resource disappears before the Update call is made)
