### ISSUE TITLE
Configuration option for Kopia parallelism.

### ISSUE THREAD

**Issue by iusergii** [vmware-tanzu/velero#6607]
**Describe the solution you'd like**
I'd like to be able to set a number of parallel uploads for the Kopia backup repository. 
Slack [discussion](https://kubernetes.slack.com/archives/C6VCGP4MT/p1691018317118429)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
If I understand correctly, the parallelism setting should be set to control the transfer session for a pv, this can benefit both PVB and Datamover flow, we just need to design how to expose it via CR and CLI.
