### ISSUE TITLE
Velero backup restore failing, and the restoration process is not working as expected.

### ISSUE THREAD

**Issue by shyjustack** [vmware-tanzu/velero#6623]
### Discussed in https://github.com/vmware-tanzu/velero/discussions/6611

<div type='discussions-op-text'>

<sup>Originally posted by **shyju102** August  6, 2023</sup>
Hi all,

**I am stuck with the backup restoration process. When restoring the backup, the PersistentVolume (PV) is not being created automatically. However, if I create the same PV manually, the backup is successfully restored.**

```
root@k8s-master:/data# kubectl get pvc
NAME      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nfs-pvc   Pending                                                     14s
root@k8s-master:/data# kubectl describe pvc nfs-pvc
Name:          nfs-pvc
Namespace:     default
StorageClass:
Status:        Pending
Volume:
Labels:        velero.io/backup-name=webapp01
               velero.io/restore-name=webapp01-20230806092648
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       web-0
Events:
  Type    Reason         Age               From                         Message
  ----    ------         ----              ----                         -------
  Normal  FailedBinding  6s (x4 over 25s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```
root@k8s-master:/data#

**In the second scenario, when I deleted everything except the PV, the PersistentVolumeClaim (PVC) is not bound to the PV**
if i delete the exiting and create new one it is working 
```
root@k8s-master:/data# kubectl get pv
NAME        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM              STORAGECLASS   REASON   AGE
my-nfs-pv   1Gi        RWX            Retain           Terminating   httpd/my-nfs-pvc                           30h
nfs-pv      1Gi        RWX            Retain           Released      default/nfs-pvc                            14m
root@k8s-master:/data# kubectl get pvc
NAME      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nfs-pvc   Pending                                                     2m34s
root@k8s-master:/data# kubectl describe pvc nfs-pvc
Name:          nfs-pvc
Namespace:     default
StorageClass:
Status:        Pending
Volume:
Labels:        velero.io/backup-name=webapp01
               velero.io/restore-name=webapp01-20230806091930
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       web-0
Events:
  Type    Reason         Age                   From                         Message
  ----    ------         ----                  ----                         -------
  Normal  FailedBinding  14s (x12 over 2m37s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
root@k8s-master:/data#
```

_________________
root@k8s-master:~# kubectl delete -f pv.yaml
persistentvolume "nfs-pv" deleted
root@k8s-master:~# kubectl create -f pv.yaml
persistentvolume/nfs-pv created
root@k8s-master:~# kubectl get pvc
NAME      STATUS   VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nfs-pvc   Bound    nfs-pv   1Gi        RWX                           4m26s
root@k8s-master:~#

Thank you.</div>

**Comment by shyju102** [comment]
yes it is on-premise cluster 
we are using NFS share there is no StorageClass

**Comment by sseago** [comment]
With NFS, you'll need to use fs backup (restic/kopia). The main thing with NFS vs. using dynamic provisioning is that since you aren't using a storage class with dynamic provisioning, you need to have available PVs in the cluster before restore so that they can be bound to the PVCs being created at restore time. In contrast, if you were using the gp2 storageclass for ebs volumes, you wouldn't need to have PVs available since the storage provisioner would create them for you.

**Comment by shyju102** [comment]
Hi, we are using Velero Version 11. I think Restic is not supporting this version. In that case, how can we take a full  backup?

**Comment by blackpiglet** [comment]
Restic is supported in Velero v1.11. 
The difference is both Kopia and Restic are supported in Velero as data uploaders from Velero v1.10.
There are some CRD definition changes introduced in v1.10 (https://github.com/vmware-tanzu/velero/releases/tag/v1.10.0. Please check the `breaking changes` section.), but Restic and Kopia should both work in v1.11.x. https://velero.io/docs/v1.11/file-system-backup/

**Comment by shyju102** [comment]
Thanks for the update..,
I just followed the document and created the backup, but while restoring the backup content, it is not restoring.

[Untitled.txt](https://github.com/vmware-tanzu/velero/files/12323818/Untitled.txt)

**Comment by blackpiglet** [comment]
Please try backup adding this parameter `--default-volumes-to-fs-backup`.
This parameter means backup will back volume with FS uploader by default.

**Comment by shyju102** [comment]
Backup is failing while using --default-volumes-to-fs-backup

command : **velero backup create mybackup --default-volumes-to-fs-backup**

Normal backup is working 

**Error** 
root@k8s-master:/data# velero backup describe mybackup
Name:         mybackup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.27.4
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=27

Phase:  PartiallyFailed (run `velero backup logs mybackup` for more information)


Errors:
  Velero:   name: /web-0 error: /pod volume backup failed: running backup, stderr=error running restic backup command restic backup --repo=s3:http://192.168.145.134:9000/k8s/restic/default --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic . --tag=pod-uid=94842d6f-4ffc-4499-95b6-23c3e685967f --tag=pvc-uid=cdc8cbad-a27c-41e0-a654-68fb55c8c6ed --tag=volume=www --tag=backup=mybackup --tag=backup-uid=815f9b72-9c55-4a66-98f6-d6d126dc92a0 --tag=ns=default --tag=pod=web-0 --host=velero --json with error: exit status 3 stderr: {"message_type":"error","error":{},"during":"scan","item":"/host_pods/94842d6f-4ffc-4499-95b6-23c3e685967f/volumes/kubernetes.io~nfs/nfs-pv/data"}
{"message_type":"error","error":{},"during":"scan","item":"/host_pods/94842d6f-4ffc-4499-95b6-23c3e685967f/volumes/kubernetes.io~nfs/nfs-pv/index"}
{"message_type":"error","error":{"Op":"open","Path":"config","Err":13},"during":"archival","item":"/host_pods/94842d6f-4ffc-4499-95b6-23c3e685967f/volumes/kubernetes.io~nfs/nfs-pv/config"}
{"message_type":"error","error":{},"during":"scan","item":"/host_pods/94842d6f-4ffc-4499-95b6-23c3e685967f/volumes/kubernetes.io~nfs/nfs-pv/keys"}
{"message_type":"error","error":{},"during":"archival","item":"data"}
{"message_type":"error","error":{},"during":"scan","item":"/host_pods/94842d6f-4ffc-4499-95b6-23c3e685967f/volumes/kubernetes.io~nfs/nfs-pv/locks"}
{"message_type":"error","error":{},"during":"archival","item":"index"}
{"message_type":"error","error":{},"during":"scan","item":"/host_pods/94842d6f-4ffc-4499-95b6-23c3e685967f/volumes/kubernetes.io~nfs/nfs-pv/snapshots"}
{"message_type":"error","error":{},"during":"archival","item":"keys"}
{"message_type":"error","error":{},"during":"archival","item":"locks"}
{"message_type":"error","error":{},"during":"archival","item":"snapshots"}
Warning: at least one source file could not be read
: error running restic backup command restic backup --repo=s3:http://192.168.145.134:9000/k8s/restic/default --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic . --tag=pod-uid=94842d6f-4ffc-4499-95b6-23c3e685967f --tag=pvc-uid=cdc8cbad-a27c-41e0-a654-68fb55c8c6ed --tag=volume=www --tag=backup=mybackup --tag=backup-uid=815f9b72-9c55-4a66-98f6-d6d126dc92a0 --tag=ns=default --tag=pod=web-0 --host=velero --json with error: exit status 3 stderr: {"message_type":"error","error":{},"during":"scan","item":"/host_pods/94842d6f-4ffc-4499-95b6-23c3e685967f/volumes/kubernetes.io~nfs/nfs-pv/data"}
{"message_type":"error","error":{},"during":"scan","item":"/host_pods/94842d6f-4ffc-4499-95b6-23c3e685967f/volumes/kubernetes.io~nfs/nfs-pv/index"}
{"message_type":"error","error":{"Op":"open","Path":"config","Err":13},"during":"archival","item":"/host_pods/94842d6f-4ffc-4499-95b6-23c3e685967f/volumes/kubernetes.io~nfs/nfs-pv/config"}
{"message_type":"error","error":{},"during":"scan","item":"/host_pods/94842d6f-4ffc-4499-95b6-23c3e685967f/volumes/kubernetes.io~nfs/nfs-pv/keys"}
{"message_type":"error","error":{},"during":"archival","item":"data"}
{"message_type":"error","error":{},"during":"scan","item":"/host_pods/94842d6f-4ffc-4499-95b6-23c3e685967f/volumes/kubernetes.io~nfs/nfs-pv/locks"}
{"message_type":"error","error":{},"during":"archival","item":"index"}
{"message_type":"error","error":{},"during":"scan","item":"/host_pods/94842d6f-4ffc-4499-95b6-23c3e685967f/volumes/kubernetes.io~nfs/nfs-pv/snapshots"}
{"message_type":"error","error":{},"during":"archival","item":"keys"}
{"message_type":"error","error":{},"during":"archival","item":"locks"}
{"message_type":"error","error":{},"during":"archival","item":"snapshots"}
Warning: at least one source file could not be read

**Comment by blackpiglet** [comment]
https://github.com/vmware-tanzu/velero/issues/4072#issuecomment-907989341
I think this is the same as this error.
The error means that Restic cannot find the files that are found during the scan. This usually means the files are deleted after the Restic scan completes.
What is the application using the PV? If the application will constantly write and read files from volumes, it's possible to meet such a problem. You may need to run a filesystem freezing command before running the backup, with a backup pre-hook.

**Comment by shyju102** [comment]
What is the application using the PV? --> Webapplication 
Is it possible to share the exact command for taking the backup?

**Comment by blackpiglet** [comment]
An example of using fsfreeze command in backup hooks can be found here. 
https://velero.io/docs/v1.11/backup-hooks/#hook-example-with-fsfreeze

During the Restic backup process, the NGINX application cannot write data into disk due to fsfreeze command's effect.
