### ISSUE TITLE
velero backups with  node-agent feature throwing warning for pvc resources

### ISSUE THREAD

**Issue by rahul-mereddy** [vmware-tanzu/velero#6624]
**What steps did you take and what happened:**
I'm runnking a GKE private cluster (GKE cluster version: v1.25.10-gke.1400) and running velero Client & Server version: 1.9.1 and storing velero backups is S3 immutable bucket.

Upgraded velero client from 1.9.1 to 1.11.0 and reinstalling velero with --use-node-agent
Command: 
```
velero install \
    --use-node-agent \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.7.1 \
    --bucket $BLOB_CONTAINER \
    --backup-location-config region=us-east-2 \
    --snapshot-location-config region=us-east-2 \
    --secret-file ./credentials-velero \
    --wait
```

while creating full cluster backup I'm seeing Warnings on the backups with -node-agent but if I use restic then my backups are successful without any errors and warnings
```
velero backup get                                                                                                                  
NAME                                   STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
jstc1gkeopsplatform01-20230808120046   Completed   0        0          2023-08-08 07:00:46 -0500 CDT   29d       default            <none>
jstc1gkeopsplatform01-20230807120045   Completed   0        5          2023-08-07 07:00:45 -0500 CDT   28d       default            <none>
jstc1gkeopsplatform01-20230806120044   Completed   0        5          2023-08-06 07:00:44 -0500 CDT   27d       default            <none>
jstc1gkeopsplatform01-20230805120043   Completed   0        5          2023-08-05 07:00:43 -0500 CDT   26d       default            <none>
jstc1gkeopsplatform01-backup           Completed   0        5          2023-08-07 14:27:00 -0500 CDT   29d       default            <none>
jstc1gkeopsplatform01-backup02         Completed   0        0          2023-08-07 15:14:20 -0500 CDT   29d       default            <none>
```

**What did you expect to happen:**
I'm expecting my backups should be completed without any errors and warnings but seeing below warnings when I use -node-agent with 1.7.1 aws plugin

Warning:
```
time="2023-08-06T12:00:58Z" level=warning msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/jstc1gkeopsplatform01-20230806120044 logSource="pkg/backup/item_backupper.go:533" name=pvc-fc17f35b-a834-4deb-941b-ec3a3e38ec26 namespace= persistentVolume=pvc-fc17f35b-a834-4deb-941b-ec3a3e38ec26 resource=persistentvolumes volumeSnapshotLocation=default
time="2023-08-06T12:00:58Z" level=warning msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/jstc1gkeopsplatform01-20230806120044 logSource="pkg/backup/item_backupper.go:533" name=pvc-5a26c6a1-18fd-4416-b692-12870837840c namespace= persistentVolume=pvc-5a26c6a1-18fd-4416-b692-12870837840c resource=persistentvolumes volumeSnapshotLocation=default
time="2023-08-06T12:00:58Z" level=warning msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/jstc1gkeopsplatform01-20230806120044 logSource="pkg/backup/item_backupper.go:533" name=pvc-cb8333a1-a4b7-495d-951c-8dc2f66ff44a namespace= persistentVolume=pvc-cb8333a1-a4b7-495d-951c-8dc2f66ff44a resource=persistentvolumes volumeSnapshotLocation=default
time="2023-08-06T12:01:02Z" level=warning msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/jstc1gkeopsplatform01-20230806120044 logSource="pkg/backup/item_backupper.go:533" name=pvc-e835ae87-50ba-457f-bdca-cca9e51bb011 namespace= persistentVolume=pvc-e835ae87-50ba-457f-bdca-cca9e51bb011 resource=persistentvolumes volumeSnapshotLocation=default
time="2023-08-06T12:01:02Z" level=warning msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/jstc1gkeopsplatform01-20230806120044 logSource="pkg/backup/item_backupper.go:533" name=pvc-f7e839dc-e84a-4416-b4cb-a0b176d9ab94 namespace= persistentVolume=pvc-f7e839dc-e84a-4416-b4cb-a0b176d9ab94 resource=persistentvolumes volumeSnapshotLocation=default
```

**The following information will help us better understand what's going on**:
_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```
velero backup describe jstc1gkeopsplatform01-20230806120044                                                                                                            
Name:         jstc1gkeopsplatform01-20230806120044
Namespace:    velero
Labels:       velero.io/schedule-name=jstc1gkeopsplatform01
              velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.25.10-gke.1400
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=25

Phase:  Completed

Warnings:  <error getting warnings: DownloadRequest.velero.io "jstc1gkeopsplatform01-20230806120044-37b723db-970d-4cfb-9de5-988dbd182c2f" is invalid: spec.target.kind: Unsupported value: "BackupResults": supported values: "BackupLog", "BackupContents", "BackupVolumeSnapshots", "BackupItemSnapshots", "BackupResourceList", "RestoreLog", "RestoreResults">

Errors:  <error getting errors: DownloadRequest.velero.io "jstc1gkeopsplatform01-20230806120044-37b723db-970d-4cfb-9de5-988dbd182c2f" is invalid: spec.target.kind: Unsupported value: "BackupResults": supported values: "BackupLog", "BackupContents", "BackupVolumeSnapshots", "BackupItemSnapshots", "BackupResourceList", "RestoreLog", "RestoreResults">

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2023-08-06 07:00:44 -0500 CDT
Completed:  2023-08-06 07:01:20 -0500 CDT

Expiration:  2023-09-05 07:00:44 -0500 CDT

Velero-Native Snapshots: <none included>
- `velero backup logs <backupname>`
velero backup logs jstc1gkeopsplatform01-20230806120044 | grep warn 
                                                                                                   
time="2023-08-06T12:00:58Z" level=warning msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/jstc1gkeopsplatform01-20230806120044 logSource="pkg/backup/item_backupper.go:533" name=pvc-fc17f35b-a834-4deb-941b-ec3a3e38ec26 namespace= persistentVolume=pvc-fc17f35b-a834-4deb-941b-ec3a3e38ec26 resource=persistentvolumes volumeSnapshotLocation=default
time="2023-08-06T12:00:58Z" level=warning msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/jstc1gkeopsplatform01-20230806120044 logSource="pkg/backup/item_backupper.go:533" name=pvc-5a26c6a1-18fd-4416-b692-12870837840c namespace= persistentVolume=pvc-5a26c6a1-18fd-4416-b692-12870837840c resource=persistentvolumes volumeSnapshotLocation=default
time="2023-08-06T12:00:58Z" level=warning msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/jstc1gkeopsplatform01-20230806120044 logSource="pkg/backup/item_backupper.go:533" name=pvc-cb8333a1-a4b7-495d-951c-8dc2f66ff44a namespace= persistentVolume=pvc-cb8333a1-a4b7-495d-951c-8dc2f66ff44a resource=persistentvolumes volumeSnapshotLocation=default
time="2023-08-06T12:01:02Z" level=warning msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/jstc1gkeopsplatform01-20230806120044 logSource="pkg/backup/item_backupper.go:533" name=pvc-e835ae87-50ba-457f-bdca-cca9e51bb011 namespace= persistentVolume=pvc-e835ae87-50ba-457f-bdca-cca9e51bb011 resource=persistentvolumes volumeSnapshotLocation=default
time="2023-08-06T12:01:02Z" level=warning msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/jstc1gkeopsplatform01-20230806120044 logSource="pkg/backup/item_backupper.go:533" name=pvc-f7e839dc-e84a-4416-b4cb-a0b176d9ab94 namespace= persistentVolume=pvc-f7e839dc-e84a-4416-b4cb-a0b176d9ab94 resource=persistentvolumes volumeSnapshotLocation=default
```

**Anything else you would like to add:**

what is the big difference in restic vs node-agent daemonset?

**Environment:**
- Velero version (use `velero version`): 1.110
- Velero features (use `velero client config get features`): Not Set
- Kubernetes version (use `kubectl version`): 1.27.1
- Kubernetes installer & version: N/A
- Cloud provider or hardware configuration: GCP GKE
- OS (e.g. from `/etc/os-release`): GKE cos-containerd

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
There are several things that need to be clarified in your case.
First, how did you upgrade from v1.9.x to v1.11.0? I saw the information in the backup. This means the `DownloadRequest` CRD is not updated as v1.11.0.
```
Warnings:  <error getting warnings: DownloadRequest.velero.io "jstc1gkeopsplatform01-20230806120044-37b723db-970d-4cfb-9de5-988dbd182c2f" is invalid: spec.target.kind: Unsupported value: "BackupResults": supported values: "BackupLog", "BackupContents", "BackupVolumeSnapshots", "BackupItemSnapshots", "BackupResourceList", "RestoreLog", "RestoreResults">

Errors:  <error getting errors: DownloadRequest.velero.io "jstc1gkeopsplatform01-20230806120044-37b723db-970d-4cfb-9de5-988dbd182c2f" is invalid: spec.target.kind: Unsupported value: "BackupResults": supported values: "BackupLog", "BackupContents", "BackupVolumeSnapshots", "BackupItemSnapshots", "BackupResourceList", "RestoreLog", "RestoreResults">
```
Please take this document as a reference for the Velero version upgrade https://velero.io/docs/v1.11/upgrade-to-1.11/
For your scenario, you need to first upgrade from v1.9.x to v1.10.x: https://velero.io/docs/v1.10/upgrade-to-1.10/, then upgrade from v1.10.x to v1.11.0.

Second, what is GKE private cluster? Is there any difference from the normal GKE clusters?
Since you are using a GKE cluster, normally we use GCP plugin instead of AWS plugin.
```
velero install \
    --provider gcp \
    --bucket jxun \
    --secret-file <secret-file-name> \
    --image velero/velero:main \
    --plugins velero/velero-plugin-for-gcp:main
```

Third, could you give the backup creation commands for both backups having warnings and backups using Restic?
Need to know how the backups are created, and what caused the differences.

**Comment by rahul-mereddy** [comment]
@blackpiglet  I did removed velero from the cluster and reinstalled with velero cli with new version.
I did deleted the velero namespace and removed the velero CRD's from the cluster.

kubectl delete all -n velero --all

kubectl delete crd backups.velero.io backupstoragelocations.velero.io deletebackuprequests.velero.io downloadrequests.velero.io podvolumebackups.velero.io podvolumerestores.velero.io resticrepositories.velero.io restores.velero.io schedules.velero.io serverstatusrequests.velero.io volumesnapshotlocations.velero.io

kubectl delete ns velero.

GKE private cluster are accessible only via authorized networks and private cluster has a control plane private endpoint.

let me know if i want to try anything different with the install process?

**Comment by rahul-mereddy** [comment]
Since you are using a GKE cluster, normally we use GCP plugin instead of AWS plugin?

I'm backing up the velero backups to aws s3 immutable bucket that is why i'm using aws plugin

**Comment by blackpiglet** [comment]
You can delete Velero by `velero uninstall` command. This command will delete CRDs and Velero workload and namespace.

Could you check the backup creation command?
`No volume ID returned by volume snapshotter for persistent volume`
This error means the volume is backed up by the Velero volumesnapshotter plugin, which will call provider-specific snapshot API to create snapshots for volumes.
Because you are using the AWS plugin in the GKE cluster, the Velero AWS plugin cannot call the GCP snapshot API correctly.

I think you need to add this parameter `--default-volumes-to-fs-backup` to `velero backup create` command to let Velero to choose filesystem uploader instead of volumesnapshot for volume data backup.

**Comment by blackpiglet** [comment]
Close for now. Free free to reopen if anything is still unclear.

**Comment by rahul-mereddy** [comment]
I've tested with `--default-volumes-to-fs-backup`  and still it is throwing same errors.

I've rolled my changes back to velero version 1.9.1 and used --restic and backups are completing successfully.

**Comment by blackpiglet** [comment]
The bewildering fact is Velero v1.9.1 worked with the same workload. I thought the old version of Velero should also have the same issue.
Could you please try to collect the debug bundle by running this command for the failed scenario?
`velero debug`

I think the reason why backup throws the error is some pods are annotated to not use the file system backup method.
https://velero.io/docs/v1.11/file-system-backup/#using-the-opt-out-approach If you also install the Velero GCP plugin, the backup should work.
But of course, we can debug deeper why Velero v1.11.x and v1.9.1 have different behavior with the debug bundle.

**Comment by rahul-mereddy** [comment]
velero 1.9.1 install command with backups successful

velero install --use-restic --provider aws --plugins velero/velero-plugin-for-aws:v1.6.0 --bucket $BLOB_CONTAINER --backup-location-config region=us-east-2 --snapshot-location-config region=us-east-2 --velero-pod-mem-request=1024Mi --velero-pod-mem-limit=1024Mi --secret-file ./credentials-velero --wait

NAME                                   STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
jstc1gkeopsplatform01-20230809120047   Completed   0        0          2023-08-09 07:00:47 -0500 CDT   15d       default            <none>
jstc1gkeopsplatform01-20230808120046   Completed   0        0          2023-08-08 07:00:46 -0500 CDT   14d       default            <none>

velero 1..1.1 install command have 5 warnings
velero install --use-node-agent --provider aws --plugins velero/velero-plugin-for-aws:v1.7.1 --bucket $BLOB_CONTAINER --backup-location-config region=us-east-2 --snapshot-location-config region=us-east-2 --velero-pod-mem-request=1024Mi --velero-pod-mem-limit=1024Mi --secret-file ./credentials-velero --wait

NAME                                   STATUS      ERRORS   WARNINGS
jstc1gkeopsplatform01-backup-002       Completed   0        5

[bundle-2023-08-23-08-50-04.tar.gz](https://github.com/vmware-tanzu/velero/files/12419954/bundle-2023-08-23-08-50-04.tar.gz)
[velero-1.9.1-bundle-2023-08-23-08-49-01.tar.gz](https://github.com/vmware-tanzu/velero/files/12419955/velero-1.9.1-bundle-2023-08-23-08-49-01.tar.gz)
[velero-1.11.1-bundle-2023-08-23-08-48-17.tar.gz](https://github.com/vmware-tanzu/velero/files/12419956/velero-1.11.1-bundle-2023-08-23-08-48-17.tar.gz)

Let me know if you need anymore info

**Comment by rahul-mereddy** [comment]
@blackpiglet  any update on the issue?

I've moved my backup plugin to GCP and storing in GCP storage buckets also getting same error

**GKE version (control plane and nodepool): 1.24.14-gke.2700**

`Velero install command: velero install --use-node-agent --provider gcp --plugins velero/velero-plugin-for-gcp:v1.7.1 --bucket=$BLOB_CONTAINER --no-secret --sa-annotations iam.gke.io/gcp-service-account=$SERVICE_ACCOUNT_EMAIL --backup-location-config bucket=$BLOB_CONTAINER,serviceAccount=$SERVICE_ACCOUNT_EMAIL --snapshot-location-config snapshotLocation=us-central1,project=$PROJECT_ID` 
or
`velero install --use-node-agent --provider gcp --features=EnableCSI --plugins velero/velero-plugin-for-gcp:v1.7.1,velero/velero-plugin-for-csi:v0.3.0 --bucket=$BLOB_CONTAINER --no-secret --sa-annotations iam.gke.io/gcp-service-account=$SERVICE_ACCOUNT_EMAIL --backup-location-config bucket=$BLOB_CONTAINER,serviceAccount=$SERVICE_ACCOUNT_EMAIL --snapshot-location-config snapshotLocation=us-central1,project=$PROJECT_ID --velero-pod-mem-request=1024Mi --velero-pod-mem-limit=1024Mi`

I'm seeing my backups  are completed but with warning

`Warning on velero backup logs: level=warning msg="No volume ID returned by volume snapshotter for persistent volume" backup=velero/jsdc1gkesre01-backup-test logSource="pkg/backup/item_backupper.go:537" name=rahul-share-pv namespace= persistentVolume=rahul-share-pv resource=persistentvolumes volumeSnapshotLocation=default`

the above PV has  RWX Access mode and other PV snapshots are successful which they have RWO Access Mode

What is the wrong I'm doing while taking the snapshots of volumes?

**Comment by blackpiglet** [comment]
Sorry, I missed the last update.
After checking, I think the difference between v1.9.x and v1.11.x is expected, because the change is introduced recently https://github.com/vmware-tanzu/velero/pull/5982.

As for the GCP plugin cannot work either case, I think you need to specify the secret file or use a valid token to make it work: https://github.com/vmware-tanzu/velero-plugin-for-gcp#install-and-start-velero.

**Comment by rahul-mereddy** [comment]
@blackpiglet Below is the install command I'm running but in the backup describe **CSI Volume Snapshots: <none included>**
velero install --use-node-agent --provider gcp --features=EnableCSI --plugins velero/velero-plugin-for-gcp:v1.7.1,velero/velero-plugin-for-csi:v0.3.0 --bucket=$BLOB_CONTAINER --no-secret --sa-annotations iam.gke.io/gcp-service-account=$SERVICE_ACCOUNT_EMAIL --backup-location-config bucket=$BLOB_CONTAINER,serviceAccount=$SERVICE_ACCOUNT_EMAIL --snapshot-location-config snapshotLocation=us-central1,project=$PROJECT_ID --velero-pod-mem-request=1024Mi --velero-pod-mem-limit=1024Mi

I've looked for velero pod logs and also described the backup and why CSI volume snapshots are not backup

Name:         rahul-test
Namespace:    velero
Labels:       [velero.io/storage-location=default](http://velero.io/storage-location=default)
Annotations:  [velero.io/source-cluster-k8s-gitversion=v1.24.14-gke.2700](http://velero.io/source-cluster-k8s-gitversion=v1.24.14-gke.2700)
              [velero.io/source-cluster-k8s-major-version=1](http://velero.io/source-cluster-k8s-major-version=1)
              [velero.io/source-cluster-k8s-minor-version=24](http://velero.io/source-cluster-k8s-minor-version=24)
Phase:  Completed
Warnings:
  Velero:     <none>
  Cluster:   resource: /persistentvolumes name: /bnsf-datastore-pv
  Namespaces: <none>
Namespaces:
  Included:  *
  Excluded:  <none>
Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto
Label selector:  <none>
Storage Location:  default
Velero-Native Snapshot PVs:  auto
TTL:  720h0m0s
CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  1h0m0s
Hooks:  <none>
Backup Format Version:  1.1.0
Started:    2023-09-06 09:29:49 -0500 CDT
Completed:  2023-09-06 09:30:33 -0500 CDT
Expiration:  2023-10-06 09:29:49 -0500 CDT
Total items to be backed up:  9015
Items backed up:              9015
Velero-Native Snapshots:  16 of 16 snapshots completed successfully (specify --details for more information)
CSI Volume Snapshots: <none included>

**Comment by blackpiglet** [comment]
@rahul-mereddy 
Could you please check the PV's spec content?
AFAIK, the Velero CSI plugin cannot handle the CSI-migrated volumes, which means that the PV's spec section doesn't have a `CSI` part, Velero will fall back to use Velero native snapshot.
