### ISSUE TITLE
Enable dependabot for github actions again?

### ISSUE THREAD

**Issue by mateusoliveira43** [vmware-tanzu/velero#6628]
**Describe the problem/challenge you have**

Saw this PR https://github.com/vmware-tanzu/velero/pull/6622 and wondered why dependabot for GitHub Actions was removed (it even opened a PR for that change https://github.com/vmware-tanzu/velero/pull/5546). Would it not be good for automating these changes?

**Describe the solution you'd like**

Enabling dependabot again for these situations.

**Anything else you would like to add:**

Did not find any issues/discussions about disabling dependabot for GitHub Actions, please add them (if any).

**Environment:**

- GitHub Actions

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
Needs more input from other contributors on this topic.
My feeling is that `dependabot` will create PR immediately when there is a new version available, and reviewers don't know what is the benefit and whether this is a side-effect of the change.
Although the two mentioned PRs have similar changes, the manually created one is used to address some issues we met.
