### ISSUE TITLE
Document plugin release plans as part of roadmap/milestone

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#6629]
As an outsider, I was not aware that when there's a new velero version, plugins are also bumped.

velero v1.11 to v1.12 would also bump velero-plugin-for-aws to v1.7 to v1.8 as an example.

Would be good to validate this is documented somewhere so new contributors are aware of the customs.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by kaovilai** [comment]
unstale

**Comment by yanggangtony** [comment]
unstale

**Comment by kaovilai** [comment]
unstale
