### ISSUE TITLE
velero-plugin-for-microsoft-azure : tag v1.8.0 missing which is referenced in the plugin docs for using workload identity

### ISSUE THREAD

**Issue by midhun-mohan** [vmware-tanzu/velero#6631]
**What steps did you take and what happened:**

Followed this guide to use velero with workload identity in Azure. 
https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#option-2-use-azure-ad-workload-identity

**What did you expect to happen:**

The installation becomes successful.

_If you are using velero v1.7.0+:_  
` Failed to pull image "velero/velero-plugin-for-microsoft-azure:v1.8.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/velero/velero-plugin-for-microsoft-azure:v1.8.0": failed to resolve reference "docker.io/velero/velero-plugin-for-microsoft-azure:v1.8.0": docker.io/velero/velero-plugin-for-microsoft-azure:v1.8.0: not found`

**Anything else you would like to add:**
Verified from the docker hub and verified that the tag is not present there.
https://hub.docker.com/r/velero/velero-plugin-for-microsoft-azure/tags

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Thanks for spotting the mismatch here.
IMO, v1.8.0 is the released tag for the coming Velero v1.12.0. It's planned to RC in the next week.
I agree this is a bit early to make the change in the document.

**Comment by midhun-mohan** [comment]
@blackpiglet Do you know if any versions older than 1.8.0 supports work load identity?
We did use 1.7.0 which didn't work well with work load identity?

**Comment by blackpiglet** [comment]
Looks like there is no released version supporting it.
Please try with the tag `velero/velero-plugin-for-microsoft-azure:main`.

**Comment by midhun-mohan** [comment]
Do you have a rough estimate on when 1.8.0 will be available ?

**Comment by blackpiglet** [comment]
I think it should be no later than the end of August.

**Comment by blackpiglet** [comment]
@midhun-mohan 
https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/releases/tag/v1.8.0-rc.1
rc.1 tag is released.

**Comment by blackpiglet** [comment]
https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/releases/tag/v1.8.0 is created. Close this issue.
