### ISSUE TITLE
validation error when one provider has more than one VSL

### ISSUE THREAD

**Issue by half-life666** [vmware-tanzu/velero#6633]
**What steps did you take and what happened:**

We have a environment which have 2 s3 storage added as backup repo, suppose it's provider A, B, if both A and B has multiple VSLs created, then we will have validation error like:
```
provider %s has more than one possible volume snapshot location, and none were specified explicitly or as a default
```

In our situation we have created vsl per backup plan, so we end up multiple vsls for each provider, the work around here is to create one VSL for each provider.

But in practise, for provider "aws", most cloud vendor s3 service is compatible with "aws" and their s3 repo are all treated as provider "aws", and each repo should have different VSL. If a new s3 service is added which is not aws compatible, meaning provider is not "aws", such as alibabacloud oss, then we may hit this issue.  

**What did you expect to happen:**
It seems the validation logic is not easy to understand:
- Why one provider can not have multiple VSL?
- Why check other provider?
E.g., if a system have provider A, B, C, and current backup uses A, then it will check B, C instead of A.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

Looking at the code in `validateAndGetSnapshotLocations`, the logic is as follows:
- For current backup cr, it will try to list all vsls from the cluster
- Create a map `providerLocations` with provider as key
- If current backup.Spec BSL is using provider A, then it will check all other providers, such as provider B
- If provider B has more than one VSL, and no default VSL is specified (default VSL is setup from cli), the error will be posted

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
I think there is a workaround to fix this issue.
You can use this parameter in Velero server deployment to configure this default VSL for each provider.

```
velero server -h
...
      --default-volume-snapshot-locations mapStringString   List of unique volume providers and default volume snapshot location (provider1:location-01,provider2:location-02,...)
...
```

`Why check other provider?`
For this question, I guess this is due to the VSL resource doesn't have its own controller, as a result, there is no suitable place to verify the VSL configuration globally by now. Maybe that's the reason why each backup checks the whole cluster's VSLs. What's your opinion about this?
If the previous configuration can make your scenario work, I think there is no need to change the current behavior.

**Comment by half-life666** [comment]
Though the answer does not clear my doubts, but it's OK to not change the current behavior
