### ISSUE TITLE
Technical support for NFS PVC backup & Restore 

### ISSUE THREAD

**Issue by shyju102** [vmware-tanzu/velero#6646]
In our setup, we are running Version 1.11.0. My Kubernetes cluster is on-premise volumes; we have an NFS server and a worker node. While creating the PV, I mentioned the share location and NFS server. Everything is working fine.

Backup is successfully working after I delete the content inside the volume while restoring pod and pvc, but data is not restoring.

_Originally posted by @shyju102 in https://github.com/vmware-tanzu/velero/discussions/6645_

**Comment by reasonerjt** [comment]
Is this a dup of #6623 ?

**Comment by reasonerjt** [comment]
> yes

Hence, let me close this issue as a dup and track via #6623
