### ISSUE TITLE
How to enable Prometheus metrics via "velero install" and not via Helm chart

### ISSUE THREAD

**Issue by spoer78** [vmware-tanzu/velero#6660]
Hi there,

just a quick question, i couldn't find it in you official documentation, which only references the installation via Helm chart.

How can you enable prometheus metrics for velero if you have installed it manually via "velero install" and not via a helm chart? We have an up and running system and would like to enable monitoring, but i cannot find a "clean" way to enable the probes for 8585/metrics.

Help would be highly appreciated.

bye
spoe

**Comment by reasonerjt** [comment]
Currently, you'll need to patch the server pod to set the  `metric-address` parameter to the "velero server" process,
Refer to:
https://github.com/vmware-tanzu/velero/blob/main/pkg/cmd/server/server.go#L213
