### ISSUE TITLE
Option to specify volume backup method order for the backup and restore

### ISSUE THREAD

**Issue by pradeepkchaturvedi** [vmware-tanzu/velero#6669]
Velero allows to backup volumes using FSB and CSI volume snapshot. By default, if both FSB and CSI volume snapshot configured for backup/restore, Velero first uses FSB to backup/restore volumes and then remaining volumes (not backed up using FBS) gets backup using CSI volume snapshot. Due to this, volumes which can be backup using CSI snapshot gets backed using FSB otherwise user need annotate pods manually to skip such volumes from FSB. FSB does not provide crash-consistent copy of for volume.

**Describe the solution you'd like**
Velero should provide option to specify volume backup method order for the backup and restore. It would allow to user to specify using CSI snapshot first. It would first backup volumes using CSI Volume snapshot method which provides crash-consistent volume backup. The volumes nor backed up using CSI snapshot, can be backup using FSB.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by sseago** [comment]
It seems like implementing https://github.com/vmware-tanzu/velero/issues/6640 may meet the main goal here -- it would allow "use CSI for all CSI PVs, use FSB otherwise".

**Comment by blackpiglet** [comment]
There are four types of volume backup:
* Velero native snapshot.
* Filesystem backup.
* CSI snapshot.
* Snapshot data mover.

Is it reasonable to have a general way to set which one is the preferred volume backup method?
Another thing is what should be done if the preferred method is not available, for example, `--default-volumes-to-fs-backup` parameter is set but the node-agent is not installed.

Maybe it doesn't fit this issue's topic. We need to prioritize those four methods when they are available.

**Comment by reasonerjt** [comment]
Seems after #6640 is done this will be resolved, that user will be able to explicitly choose how a volume is handled.

**Comment by reasonerjt** [comment]
Closing as a dup of #6640, after the user can set the snapshot approach in the policy the scenario for this issue will be solved.
