### ISSUE TITLE
Editing a schedule resource immediately triggers a new backup

### ISSUE THREAD

**Issue by u3813** [vmware-tanzu/velero#6685]
**What steps did you take and what happened:**
I edited my velero schedule and immediately afterwards a backup was created automatically.

**What did you expect to happen:**
I expected that my backup would be created at the specified time and not immediately on its own.

**The following information will help us better understand what's going on**:
This seems to be an old bug that was allegedly fixed a while ago. See
- https://github.com/vmware-tanzu/velero/issues/1980
- https://github.com/vmware-tanzu/velero/pull/4281

**Anything else you would like to add:**

Even though the lastBackup status was set in the schedule, the backup was triggered.

Please let me know if any important information is missing here.

**Environment:**

- Velero version (use `velero version`): `v1.11.1`, installed using Helm Release `4.1.4`
- Velero features (use `velero client config get features`):  not set
- Kubernetes version (use `kubectl version`): v1.24.14
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: on premise
- OS (e.g. from `/etc/os-release`): VMware Tanzu

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by allenxu404** [comment]
@u3813 by saying "edited my velero schedule", do you mean update the existing schedule resource by executing `kubectl edit schedule <schedule name>`? If that's the case, I tried reproducing it in my local env and I didn't observe an immediate backup afterwards.

**Comment by allenxu404** [comment]
It's strange, but I'm unable to reproduce this problem on my local environment using version 1.11.1.
