### ISSUE TITLE
Restore from datamover backup returns completed result although CSI plugin is not provided during backup phase

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#6693]
**What steps did you take and what happened:**
Install Velero without CSI plugin provided, and backup some workload with PVs using datamover flag and EnableCSI flag, then restore from the backup and  returns completed result, but PV data is not restored.

**What did you expect to happen:**
In this case, since it's not backed up by any backup mechanism, restore result should be PartiallyFailed to notify users.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
This issue may need to work together with #6595, the both issues need a way to identify volumes backed by CSI volume snapshot (with or without data mover) in Velero restore workflow.

**Comment by reasonerjt** [comment]
Clarification needed for priority of this issue.

**Comment by reasonerjt** [comment]
This will depends on the metadata about volumes mentioned in 
https://github.com/vmware-tanzu/velero/issues/6695#issuecomment-1768017884

**Comment by Lyndon-Li** [comment]
Fixed by #7077
