### ISSUE TITLE
No info for data mover in backup/restore describe

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#6695]
When running `velero backup describe` or `velero restore describe`, the output doesn't include data mover related information, i.e., how many and which volumes have been moved.

**Comment by reasonerjt** [comment]
There are two ways to get such information:
1) Query DataUpload DataDownload via the api-server
2) Download and parse itemoperation.json in a certain way.

**Comment by reasonerjt** [comment]
In v1.13 we'll focus on backup side

We'll introduce extra metadata to track how velero handles pv (how it's backuped, whether it's skipped explicitly etc...).
