### ISSUE TITLE
Data mover doesn't work if velero ns is excluded in restore

### ISSUE THREAD

**Issue by rnarenpujari** [vmware-tanzu/velero#6709]
**What steps did you take and what happened:**
I normally exclude the velero namespace from backups and restores to be on the safe side. If I take a backup with `SnapshotMoveData` as true, it completes successfully and the dataupload CR is created. But when trying to restore the backup, I see the following error
```
time="2023-08-28T06:24:03Z" level=error msg="Fail to restore from DataUploadResult: fail get DataUploadResult for restore: rs-6: no DataUpload result cm found with labels velero.io/pvc-namespace-name=default.my-vol-claim,velero.io/restore-uid=667377ce-b941-4186-a189-d5a95795e3a8,velero.io/resource-usage=DataUpload" Action=PVCRestoreItemAction PVC=default/my-vol-claim Restore=velero/rs-6 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/restore/pvc_action.go:187" pluginName=velero-plugin-for-csi restore=velero/rs-6
```
Looking at the code, the configmap is supposed to be created by the DataUploadRetrieveAction action but the `Executing DataUploadRetrieveAction` log is never seen. Perhaps since the velero ns is excluded from the restore and the dataupload CR is present in that namespace.

My observations:
- If the velero ns is under ExcludedNamespaces in the restore, the issue occurs
- If IncludedNamespaces is used in the restore (not including the velero ns), the issue occurs
- Restore succeeds as long as the velero ns is not excluded in the restore - doesn't matter if the velero ns was excluded from the backup interestingly

**What did you expect to happen:**

Restore to succeed

**The following information will help us better understand what's going on**:

N/A

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.12 rc1
- Velero features (use `velero client config get features`): EnableCSI
- Kubernetes version (use `kubectl version`): v1.26.6
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
Fixed by #6741 and #6742

**Comment by fredgate** [comment]
I have the same problem if I do a restore by setting a resource selector. Without a selector, the restoration goes well.
I use velero `1.12.3`.
```
error preparing persistentvolumeclaims/default/my-pvc: rpc error: code = Unknown desc = fail get DataUploadResult for restore: my-restore-with-selector: no DataUpload result cm found with labels velero.io/pvc-namespace-name=default.my-pvc,velero.io/restore-uid=cf96786c-27ba-4428-baf2-5ffacf017a8b,velero.io/resource-usage=DataUpload
```

**Comment by rob-1126** [comment]
@fredgate I ran onto the same issue on 1.13.0 and filed as https://github.com/vmware-tanzu/velero/issues/7535
