### ISSUE TITLE
Different behavior of Backup and Restore hook execution.

### ISSUE THREAD

**Issue by Shashank1306s** [vmware-tanzu/velero#6721]
**What steps did you take and what happened:**
***Issue 1***
Backup Hook Execution behavior.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-IN style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

onError: Continue  | Case 1: Hooks     are executed successfully. Backup Status: Completed | Case 2: Hooks     execution failed/or has some error Backup Status: PartiallyFailed
-- | -- | --
onError: Fail | Case 1: Hooks     are executed successfully. Backup Status: Completed | Case 2: Hooks     execution failed/or has some error Backup Status: PartiallyFailed

</div>

</body>

</html>
Restore Hook Execution behavior.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-IN style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

onError: Continue  | Case 1: Hooks     are executed successfully. Restore Status: Completed | Case 2: Hooks     execution failed/or has some error Restore Status: Completed
-- | -- | --
onError: Fail | Case 1: Hooks     are executed successfully. Restore Status: Completed | Case 2: Hooks     execution failed/or has some error Restore Status: PartiallyFailed

</div>

</body>

</html>

***Issue 2***
While publishing restore result, all the errors and warning are currently pushed to Velero-level even when it is namespaced level error.
[code path](https://github.com/vmware-tanzu/velero/blob/db6784aa8138a91cc3dbcd766635bd726da78cce/pkg/restore/restore.go#L599C32-L599C32)
![image](https://github.com/vmware-tanzu/velero/assets/63052147/1ccbd39a-2b95-4614-88b1-66b64d8b98f0)

**What did you expect to happen:**
In above table we can see that tthe behaviour of restore is different when onError is set to continue and there is some error in the hooks execution. It only logs the error and shows the restore status as complete [It only returns error when onError is set to fail], where it should not be the case. It should show partially failed state and push the error/ warning in the restore result. In this way we can know that hook was executed or not.

Rather than pushing the error/warning to velero-level bucket, appending the error/warning to their respective bucket (like namespace, velero, cluster) [Code path](https://github.com/vmware-tanzu/velero/blob/db6784aa8138a91cc3dbcd766635bd726da78cce/pkg/util/results/result.go#L22C1-L22C1)
**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

The behavior of backup and restore hook execution should be same (i.e., we can also return error when the restore hook execution fails when OnError is set to Continue). Also for better parsing, we can change the way we are pushing changes in the restore result. Instead of storing error on hookErrs channel {[here](https://github.com/vmware-tanzu/velero/blob/db6784aa8138a91cc3dbcd766635bd726da78cce/pkg/restore/restore.go#L1781C1-L1781C25)}, storing error in Result will be better.
![image](https://github.com/vmware-tanzu/velero/assets/63052147/d77fd364-df95-4237-bfdd-0c7ad32a5be1)

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Just reproduced this issue in my developing environment. 
I tested with the backup post hook and restore exec hook.
I think the difference is caused by how backup and restore calculate errors.
The backup controller counts the error level messages to determine whether the backup has any errors, but the restore controller looks for the `Result` structure. If there is no entry in it, then no error.
```
type Result struct {
	// Velero is a slice of messages related to the operation of Velero
	// itself (for example, messages related to connecting to the
	// cloud, reading a backup file, etc.)
	Velero []string `json:"velero,omitempty"`

	// Cluster is a slice of messages related to backup or restore of
	// cluster-scoped resources.
	Cluster []string `json:"cluster,omitempty"`

	// Namespaces is a map of namespace name to slice of messages
	// related to backup or restore namespace-scoped resources.
	Namespaces map[string][]string `json:"namespaces,omitempty"`
}
```

**Comment by sseago** [comment]
@blackpiglet Counting error/warning messages in logs may result in double-counting. I think we should follow the existing Restore workflow and *always* add to the error/warning struct if something should result in an error/warning. When the hook code was written, very likely someone forgot that Restore handles errors differently. This is similar to the error I introduced in the RIAv2 where errors in plugin execution weren't being listed as plugin errors because I made the same mistake.

**Comment by blackpiglet** [comment]
@sseago 
I agree that counting errors and warning logs in the Restore process may cause double-counting issues, then I will add the error into the `Result` structure to resolve this issue.

**Comment by Shashank1306s** [comment]
I've checked that when hook execution fails with the onError set to continue by changing the code to return the error. The restore goes to partially failed state. Also, currently we are using hooks channel for the floating error related to hook in the restore result.
I have made some improvement for logging #6553, but I can also change this behavior of onError set to Continue to be same as Fail.

**Comment by allenxu404** [comment]
I'm a little uncertain about the direction we're taking with this issue.  As per the the comment of value "Continue":
```
	// HookErrorModeContinue means that an error from a hook is acceptable, and the backup can
	// proceed.
	HookErrorModeContinue HookErrorMode = "Continue"
```
I think if a hook's onError is set to "Continue", the outcome of the hook's execution won't impact the status of the backup/restore. This implies that the behaviour of restore hook execution is correct but the behaviour of backup is not.

Any thought?  @Shashank1306s @blackpiglet @sseago

**Comment by blackpiglet** [comment]
@allenxu404 
I'm not sure about this.
To me, the hook's `onError` setting to `Continue` means that, if the hook fails, it doesn't impact the following hooks of the same pod. The hook's `onError` setting may not be related to the backup's status.

**Comment by allenxu404** [comment]
Yeah, make sense. @blackpiglet @Shashank1306s

**Comment by allenxu404** [comment]
> Rather than pushing the error/warning to velero-level bucket, appending the error/warning to their respective bucket (like namespace, velero, cluster) 

@Shashank1306s To my understanding, the hook error/warning should be included into namespace bucket regarding the fact that hooks are exexcuted on the pod and operations related to pod should be categorized into namespace bucket. 

Is there other particular reason to do that? Since this issue related to #6567, just want to know what you're concerning.

**Comment by Shashank1306s** [comment]
@allenxu404
Adding errors/warning to correct bucket is one thing. 
My other concern is that since during backup operation whenever there is any `failure` in hooks execution and the `OnError` parameter is set to `continue`, the `backupStatus` comes out to be `partiallyfailed`. So, there is a way here to know that something might have failed and we can check the error/warning in backup result.

But in case of restore, the scenario is different as I've stated in this issue above in the table. 

So, the hook execution for restore on `onError = continue` should work in the same way as the hook is working for backup.

As this is only way, the restore status will be `partaillyFailed` and then we can check the restore result for the error/warning related to hook failure.

**Comment by allenxu404** [comment]
@blackpiglet @Shashank1306s I've submitted PR #7022 to address this issue. Please take a look when you have a chance and let me know if any changes are needed before merging.

**Comment by Shashank1306s** [comment]
> I'm a little uncertain about the direction we're taking with this issue. As per the the comment of value `Continue`:
> 
> ```
> 	// HookErrorModeContinue means that an error from a hook is acceptable, and the backup can
> 	// proceed.
> 	HookErrorModeContinue HookErrorMode = "Continue"
> ```
> 
> I think if a hook's onError is set to `Continue`, the outcome of the hook's execution won't impact the status of the backup/restore. This implies that the behaviour of restore hook execution is correct but the behaviour of backup is not. To be more specific, backup status should be `Completed` if the hook's on error is set to `Continue` and hook fails to execute.
> 
> Any thought? @Shashank1306s @blackpiglet @sseago

Hi @allenxu404, can you please also update the description of the `onContinue` and `onFail` in the api in the same PR #7022 . As highlighted above by you, it is confusing and misleading regarding the hook execution bahaviour.

**Comment by allenxu404** [comment]
@Shashank1306s sure, will do.
