### ISSUE TITLE
Resource Modifier should support json merge patch and strategic merge patch

### ISSUE THREAD

**Issue by 27149chen** [vmware-tanzu/velero#6728]
**Describe the problem/challenge you have**
Resource Modifier uses json patch to patch object, but  json patch is not easy to use and has limitations.
For example:
1. if I want to remove an annotation not matter it exists or not, a json merge patch is better (`{"metadata":{"annotations":{"foo":null}}}`)
2. if I want to update a container image by container name, a strategic merge patch should be used

**Describe the solution you'd like**
support json merge patch and strategic merge patch in Resource Modifier

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by anshulahuja98** [comment]
#6344 
https://github.com/vmware-tanzu/velero/issues/6344#issuecomment-1698438585 what are your thoughts on leveraging jq instead to give such capabilities, while possibly keeping the jsonpatch setup intact.

CC @qiuming-best

**Comment by 27149chen** [comment]
I think they are different things, jq can not cover the capabilities which json merge patch or  strategic merge patch can provide

**Comment by 27149chen** [comment]
@reasonerjt  I want to implement this feature, can you assign it to me?

**Comment by anshulahuja98** [comment]
@27149chen I think it would be great if you could pick impl. I can assign it to you.
Can we meanwhile further close on the approach over slack? 
https://kubernetes.slack.com/archives/C021GPR1L3S/p1693808146936179

Had put further points on this, I am trying to see if through whatever enhancements we do to resource modifiers, we are also able to support scenarios in #6344

**Comment by ywk253100** [comment]
Reopen it as the implementation isn't merged
