### ISSUE TITLE
Enable Azure Service Principal Certificate-Based authentication

### ISSUE THREAD

**Issue by PauloGDPeixoto** [vmware-tanzu/velero#6735]
**Describe the problem/challenge you have**
At the moment, only Service Principals with client secret are able to authenticate, but recently, certificate-based authentication is being pushed as a more secure alternative.

**Describe the solution you'd like**
I'd like to be able to authenticate a Service Principal with a certificate.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
Link the official doc for certificate-based authentication: https://learn.microsoft.com/en-us/cli/azure/azure-cli-sp-tutorial-3

**Comment by ywk253100** [comment]
Reopen to track the work on the Azure plugin side

**Comment by ywk253100** [comment]
The issue can be closed once https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/235 is merged
