### ISSUE TITLE
Cannot restore PV content on new PV (`error identifying path of volume: expected one matching path, got 0`)

### ISSUE THREAD

**Issue by KoltesDigital** [vmware-tanzu/velero#6749]
**What steps did you take and what happened:**

1. installed microk8s on a fresh Ubuntu 23.04.
2. enabled microk8s plugins:
    cis-hardening
    community
    dns
    ha-cluster
    helm
    helm3
    hostpath-storage
    metallb
    rbac
    trivy
3. deployed Velero helm chart with `velero/velero-plugin-for-aws:v1.7.0` in `initContainers`, one bucket given in `configuration.backupStorageLocation`, no `configuration.volumeSnapshotLocation`, `deployNodeAgent: true`, `kubectl.image.tag: "1.27"` because Bitnami didn't catch up, and some schedule,
4. deployed any helm chart that has a PVC (e.g. Traefik) having annotated the deployment template with `backup.velero.io/backup-volumes: <volume name>`. It followed that a PV was created whose name was `pvc-<UUID1>`,
5. executed `velero backup create --from-schedule schedule-X`, and waited a bit,
6. observed with `velero backup describe velero-X --details` that there were no errors, all k8s entities have been handled, and PV contents were saved with restic,
7. observed that the bucket contains a new backup "directory" (objects with the same name prefix),
8. observed with `restic snapshots` that a snapshot has been created, with good-looking tags, and whose `paths` property is ` /host_pods/<UUID-X>/volumes/kubernetes.io~local-volume/pvc-<UUID1>`,
9. simulated a disaster: deleted namespace `traefik`, PV got automatically deleted as well,
10. executed `velero restore create --from-backup velero-X --include-namespaces traefik`,
11. observed that a new PV named `pvc-<UUID2>` is created, i.e. **new PV has a different name**,
12. observed the following line in `velero` pod's logs:
    `velero time="..." level=error msg="Velero restore error: pod volume restore failed: error identifying path of volume: expected one matching path: /host_pods/UUID/volumes/*/pvc-<UUID2>, got 0" logSource="pkg/controller/restore_controller.go:491" restore=velero/velero-X`
13. observed that `traefik` pod has a `restore-wait` init container which continuously logs `Not found: /restores/data/.velero/<UUID>` and therefore prevents Traefik to actually start.

**What did you expect to happen:**

No errors, restore should have succeeded.

I do understand that something must be going on to map snapshots to PVs, because pod names are different, PV names are different... Still, I suppose Velero should be able to handle that somehow. Ultimately, pods' deployment have the same name, and pod volume have the same name, so mapping PVs should be possible. With that in mind, I don't understand why the restic snapshot contains the PV name.

Or am I doing something wrong? Could providers force new PV's name? Is some config key missing?

Note that I mentioned Traefik but it did the same with other helm charts.

**Environment:**

- Velero version (use `velero version`): 
    Client:
        Version: v1.11.1
        Git commit: bdbe7eb242b0f64d5b04a7fea86d1edbb3a3587c
    Server:
        Version: v1.11.1

- Velero features (use `velero client config get features`):
    features: <NOT SET>
- Kubernetes version (use `kubectl version`):
    $ microk8s kubectl version
    Client Version: v1.28.0
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.28.0

- Kubernetes installer & version: microk8s
- Cloud provider or hardware configuration: some OVH VPS
- OS (e.g. from `/etc/os-release`): Ubuntu 23.04

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Please check whether this link's guide will do any help: https://github.com/vmware-tanzu/velero/issues/4035#issuecomment-1119092387

**Comment by KoltesDigital** [comment]
@blackpiglet thanks for finding out this trick. It turns out that `/var/lib/kubelet` is a symlink to `/var/snap/microk8s/common/var/lib/kubelet`, so this trick is not needed anymore.

However, this led me to find in the logs that hostPath volumes are not supported by Velero. I disabled the hostpath-storage plugin and instead enabled the openebs plugin, which installs a local volume storage class which does work with Velero (even if it relies on a hostPath... not sure how it works). With this storage volume, backups and restores work well.

Thanks for the project. See you.
