### ISSUE TITLE
why restic backup is much faster than velero

### ISSUE THREAD

**Issue by meijianwei-hub** [vmware-tanzu/velero#6755]
When I use velero1.9.7 with restic to backup the application of mysql, mysql data is about 2G, velero need about three minutes. but I only use restic to backup the same mysql data, it just cost 21s。What the difference of them？
below are my test result：
velero backup time and log screenshot
![image](https://github.com/vmware-tanzu/velero/assets/61965296/7f358f4c-61fb-4d7d-85d3-3179e3c1bd61)
![image](https://github.com/vmware-tanzu/velero/assets/61965296/0ece7a48-6039-42da-bca0-66fd202b25a9)

the restic backup time：
![image](https://github.com/vmware-tanzu/velero/assets/61965296/f2fa3aff-0309-45fe-9907-e652a6d04877)

**Comment by qiuming-best** [comment]
@meijianwei-hub The difference in CPU and Memory limit leads to the performance behavior.
 
 You could try increasing CPU and Memory for Restic pod and check the backup time again.
