### ISSUE TITLE
The restores cannot be removed if the corresponding backups/BSLs are removed

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#6756]
Get the following error if the backup doesn't exist when deleting the restore:
```
time="2023-09-04T06:33:41Z" level=error msg="fail to delete external resources: can't get backup info, backup: bk-1: can't find backup velero/bk-1: Backup.velero.io \"bk-1\" not found" Restore=velero/rs-x logSource="pkg/controller/restore_controller.go:178"
```
Get the following error if the bsl doesn't exist when deleting the restore:
```
time="2023-09-04T09:06:57Z" level=error msg="fail to delete external resources: can't get backup info, backup: bk-2: BackupStorageLocation.velero.io \"aws-loc-2\" not found
```

The restore should be removed first before removing the backup and bsl. This could be implemented by [setting owner reference](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/): bsl owns backup, backup owns restore

BTW, currently, the backups are deleted by Velero CLI when deleting the bsl, if we set the owner of backup as the bsl, the backup removing logic could be removed. 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by allenxu404** [comment]
This bug has already been fixed. Currently restores can be removed if either the bsl or backup doesn't exist. We can see it from this section: https://github.com/vmware-tanzu/velero/blob/d3e5bb7451447b61ea9b985210d0a7c369ec73f8/pkg/controller/restore_controller.go#L674 

Regarding the use case where the restore should be removed first before removing BSL, I have some doubts about its validity. Deleting data is a sensitive operation, and Velero should proceed with caution, only if it receives a clear deletion request from the user, such as running the commands `velero delete restore` and `velero delete backup`. In this case, Velero would cascade-delete the data from both the cluster and the object storage. However, removing BSL does not provide clear information that users expect to delete the relevant restores and backups within its corresponding object storage. Even though these resources might not be reused by Velero, users might still want to keep them for other purposes. So it's better to let user decide if these resources should be removed or not and they can operate on them by simply using the specific object storage command.

I suggest keeping this issue open and seeing user feedback to determine if there is a demand for adding this feature to the Velero.

**Comment by reasonerjt** [comment]
Closing as wont fix as there's not much upvoting.
