### ISSUE TITLE
When backup entire cluster, it will be 'partially failed' for 'daemonset pod not found in running state in node xxx-control-plane-xxx'

### ISSUE THREAD

**Issue by iamjackhu** [vmware-tanzu/velero#6763]
**What steps did you take and what happened:**

Backup entire cluster

**What did you expect to happen:**
The backup successfully

**The following information will help us better understand what's going on**:
The backup's result is 'partially failed'
Because the node-agent can't run on master-node/control-plan as usual, but once the master-node has the PV to backup, then the backup will be 'partially failed'.

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
time="2023-08-21T13:02:40Z" level=error msg="Error backing up item" backup=velero-c929ca60-6584-4e8c-8c3d-66e4d2283f62/manual-20230821t130212294z error="daemonset pod not found in running state in node jed2-cls02-control-plane-node-pool-p9pdh" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/nodeagent/node_agent.go:74" error.function=github.com/vmware-tanzu/velero/pkg/nodeagent.IsRunningInNode logSource="pkg/backup/backup.go:425" name=csi-vcd-controllerplugin-659fd56cd5-wbctm
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): v1.10.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.22
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
@iamjackhu 
> Because the node-agent can't run on master-node/control-plan as usual, but once the master-node has the PV to backup, then the backup will be 'partially failed'.

If you are using the file-system-level backup， the node of volumes that you want to backup must deploy the node-agent.
So you could let the  node-agent tolerant the trains on master nodes

**Comment by iamjackhu** [comment]
If the command 'velero insall ...' can provide the options to tolerate master-node, it will be better for us.
