### ISSUE TITLE
Option to specify number of CSI snapshot to be retained in cluster for quick restore

### ISSUE THREAD

**Issue by pradeepkchaturvedi** [vmware-tanzu/velero#6776]
Velero provides CSI volume snapshot capability. Velero 1.12 would provide data mover capability to move the snapshot data to backup storage location. With option to move snapshot to BSL, Velero would delete the CSI snapshot from the cluster after moving snapshot data to BSL.

- Velero should provide more flexibility for retaining (TTTL) volume backup data (FSB and Snapshot) to BSL

- Velero should provide option to retain the snapshot in cluster while moving snapshot data to BSL
-
- Velero should provide option to retain only last 'N' snapshot per backup schedule to optimize the disk space requirement for cluster. For example, user may want to keep last  5 snapshots in cluster for quick restore in cased of any disaster. User may want to retain last 30 snapshots in BSL for compliance perspective and use them to restore if last 5 snapshot does not have stable state captured
-
- Velero should provide different of TTL for backup of snapshot data to BSL. Snapshot data is usually large user may want to store 0nly last 15 days snapshoot data in BSL. Resource backup size is usually small, user may want to keep last 30 days resource objects.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
@pradeepkchaturvedi we've opened an issue to track the work for retaining local snapshot when Datamover is enabled for a backup:
https://github.com/vmware-tanzu/velero/issues/6240
I'm closing this one as a dup.
