### ISSUE TITLE
Node agent pod has an additional log entry related to "PodVolumeBackup starting" after its marked as completed.

### ISSUE THREAD

**Issue by PrasadJoshi12** [vmware-tanzu/velero#6781]
**What steps did you take and what happened:**
Executed FSB backup with Kopia. Node agent pod has an additional log entry "PodVolumeBackup staring" after it's being marked as completed.

$ oc logs node-agent-2gvzn
me="2023-09-06T10:41:26Z" level=info msg="Async fs backup data path completed" PVB=test-backup-jvpfr controller=PodVolumeBackup logSource="pkg/controller/pod_volume_backup_controller.go:195" pvb=test-backup-jvpfr
time="2023-09-06T10:41:26Z" level=info msg="Action finished" backup=velero/test-backup controller=podvolumebackup logSource="pkg/uploader/provider/kopia.go:91" podvolumebackup=velero/test-backup-jvpfr
time="2023-09-06T10:41:26Z" level=info msg="PodVolumeBackup starting" backup=velero/test-backup controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:104" podvolumebackup=velero/test-backup-jvpfr
time="2023-09-06T10:41:26Z" level=info msg="PodVolumeBackup completed" controller=PodVolumeBackup logSource="pkg/controller/pod_volume_backup_controller.go:225" pvb=test-backup-jvpfr
**time="2023-09-06T10:41:26Z" level=info msg="PodVolumeBackup starting" backup=velero/test-backup controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:104" podvolumebackup=velero/test-backup-jvpfr**
time="2023-09-06T10:41:27Z" level=info msg="FileSystemBR is closed" backup=velero/test-backup controller=podvolumebackup logSource="pkg/datapath/file_system.go:129" podvolumebackup=velero/test-backup-jvpfr user=test-backup-jvpfr

**What did you expect to happen:**
Node agent pod shouldn't have PodVolumeStarting log after it's being completed.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
@PrasadJoshi12  Thanks for your report, I think the log `PodVolumeBackup starting`  is misleading after the backup has already been completed, We will fix it.

**Comment by PrasadJoshi12** [comment]
Thank you @qiuming-best

**Comment by weshayutin** [comment]
@sseago @shubham-pampattiwar @kaovilai FYI

**Comment by yanggangtony** [comment]
Hey , i sent a pr to fix the typos and some code clean.

**Comment by qiuming-best** [comment]
It's already been fixed and also cherry-picked to 1.12.1, so I closed it
