### ISSUE TITLE
Port 8085 should be allocated to the server within the node agent pod.

### ISSUE THREAD

**Issue by allenxu404** [vmware-tanzu/velero#6792]
**What steps did you take and what happened:**
No port is allocated to server within node agent as the output below from executing `kubectl describe daemonset.apps/node-agent` shows :
<img width="1216" alt="image" src="https://github.com/vmware-tanzu/velero/assets/107547364/a907e448-a4af-48dc-a1e2-55e13ba44ee9">

We can also see this issue from log of node agent pod:
```
time="2023-09-08T08:30:26Z" level=info msg="Starting metric server for node agent at address [:]" logSource="pkg/cmd/cli/nodeagent/server.go:230"
```

**What did you expect to happen:**
 The server within node agent pod should expose port 8085 similar to how server within velero pod is configured so that the Promethous pod can scrape the pod volume related metrics from that server via port 8085.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `v1.12`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by allenxu404** [comment]
I will fix it on v1.13.

**Comment by kaovilai** [comment]
Is this also not applicable to 1.12?

**Comment by allenxu404** [comment]
@kaovilai It seems that this issue has been persisting for a long time, and it is still present in version 1.12.

**Comment by allenxu404** [comment]
Close this issue as https://github.com/vmware-tanzu/velero/pull/6784 has been merged.
