### ISSUE TITLE
The Resource 'Microsoft.Compute/disks/pvc-xxx' under resource group 'XXX' was not found.

### ISSUE THREAD

**Issue by minakshibose** [vmware-tanzu/velero#6826]
When trying to create backup of a namespace containing PVC which refers to a disk snapshot or a freshly created PVC in that namespace, we are getting the below error in the logs. 

level=error msg="Error backing up item" backup=velero/14thbackup error="error getting volume info: rpc error: code = Unknown desc = compute.DisksClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/disks/pvc-xxx' under resource group 'XXX' was not found. For more details please go to [https://aka.ms/ARMResourceNotFoundFix\""](https://aka.ms/ARMResourceNotFoundFix/%22%22)

time="2023-09-14T12:05:31Z" level=error msg="Error backing up item" backup=velero/14thbackup error="error getting volume info: rpc error: code = Unknown desc = compute.DisksClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/disks/Disk-16thjune' under resource group 'XXX' was not found. For more details please go to [https://aka.ms/ARMResourceNotFoundFix\""](https://aka.ms/ARMResourceNotFoundFix/%22%22)

**velero version**
Client:
        Version: v1.10.1
        Git commit: 948b3790d5577dc7e77410a8b80ef7d8a6b00303
Server:
        Version: v1.10.1

These PVCs are using Azure Disk as storage and the kind of kubernetes cluster used is AKS. The data contained in these PVCs is that of a postgres database.

**Comment by ywk253100** [comment]
`The Resource 'Microsoft.Compute/disks/Disk-16thjune' under resource group 'XXX' was not found`
Could you double-check which resource group the disk `Microsoft.Compute/disks/Disk-16thjune` is in?

**Comment by minakshibose** [comment]
this was an issue with the configuration at the velero side and has been fixed.
