### ISSUE TITLE
Velero restore is failing for Argocd and Opa, which consists of tmp-dir,static-files,gpg-keyring volumes with error "pod volume restore failed" for kopia and restic

### ISSUE THREAD

**Issue by Meghavenkatesh** [vmware-tanzu/velero#6835]
**What steps did you take and what happened:**
Hi,

I have upgarded the velero version v1.11.1 and azure plugin version v1.7.1 in source cluster ,aws plugin version v1.7.1 in destination cluster using the below command

./velero install --provider azure --bucket velero --secret-file credentials-velero-aks --backup-location-config resourceGroup=$resourcegroup,storageAccount=aksstoragek8s --use-node-agent --use-volume-snapshots=false --plugins=velero/velero-plugin-for-microsoft-azure:v1.7.1 --velero-pod-cpu-limit 1200m --velero-pod-cpu-request 700m --velero-pod-mem-limit 1Gi --velero-pod-mem-request 500Mi  --uploader-type=kopia --default-volumes-to-fs-backup --kubeconfig akskubeconfig

and 

./velero install --provider aws --bucket awsbucket --secret-file credentials-velero-aws --backup-location-config region=eu-west-1 --use-node-agent --use-volume-snapshots=false --plugins=velero/velero-plugin-for-aws:v1.7.1 --uploader-type=kopia --velero-pod-cpu-limit 1200m --velero-pod-cpu-request 700m --velero-pod-mem-limit 1Gi --velero-pod-mem-request 500Mi --default-volumes-to-fs-backup --kubeconfig awskubeconfig

the backup command used is

./velero create backup 18sepaks --kubeconfig akskubeconfig --ttl '240h' --exclude-namespaces kube-system,velero

the backup was successfully completed, the 18sepaks from source it is copied to destination bucket,
while restoring the above backup in destination(aws) cluster
facing below issues,

time="2023-09-18T11:49:06Z" level=error msg="unable to successfully complete pod volume restores of pod's volumes" error="pod volume restore failed: error running restore err=Failed to run kopia restore: Failed to copy snapshot data to the target: restore error: error copying: copy file: error creating file: unable to open snapshot file for /host_pods/bd6fb2f9-811b-4344-aa80-f988a00f51ba/volumes/kubernetes.io~empty-dir/tmp-dir: unable to open object: d7edae38293f7752b67c159f78e378d7: failed to open object with id d7edae38293f7752b67c159f78e378d7: error to open object: content d7edae38293f7752b67c159f78e378d7 not found: object not found: Failed to run kopia restore: Failed to copy snapshot data to the target: restore error: error copying: copy file: error creating file: unable to open snapshot file for /host_pods/bd6fb2f9-811b-4344-aa80-f988a00f51ba/volumes/kubernetes.io~empty-dir/tmp-dir: unable to open object: d7edae38293f7752b67c159f78e378d7: failed to open object with id d7edae38293f7752b67c159f78e378d7: error to open object: content d7edae38293f7752b67c159f78e378d7 not found: object not found" logSource="pkg/restore/restore.go:1699" restore=velero/18sepaks-20230918114846
time="2023-09-18T11:49:08Z" level=error msg="unable to successfully complete pod volume restores of pod's volumes" error="pod volume restore failed: error running restore err=Failed to run kopia restore: Failed to copy snapshot data to the target: restore error: error copying: copy file: error creating file: unable to open snapshot file for /host_pods/cc072d9c-d4bf-4c1a-9df7-f17857c1da33/volumes/kubernetes.io~empty-dir/static-files: unable to open object: bc98fed14a03b7bc3b5d968296868a8a: failed to open object with id bc98fed14a03b7bc3b5d968296868a8a: error to open object: content bc98fed14a03b7bc3b5d968296868a8a not found: object not found: Failed to run kopia restore: Failed to copy snapshot data to the target: restore error: error copying: copy file: error creating file: unable to open snapshot file for /host_pods/cc072d9c-d4bf-4c1a-9df7-f17857c1da33/volumes/kubernetes.io~empty-dir/static-files: unable to open object: bc98fed14a03b7bc3b5d968296868a8a: failed to open object with id bc98fed14a03b7bc3b5d968296868a8a: error to open object: content bc98fed14a03b7bc3b5d968296868a8a not found: object not found" logSource="pkg/restore/restore.go:1699" restore=velero/18sepaks-20230918114846
time="2023-09-18T11:49:11Z" level=error msg="unable to successfully complete pod volume restores of pod's volumes" error="[pod volume restore failed: error running restore err=Failed to run kopia restore: Failed to copy snapshot data to the target: restore error: error copying: copy file: error creating file: unable to open snapshot file for /host_pods/07f7ac49-2bc6-413d-ae17-2ed3adfae093/volumes/kubernetes.io~empty-dir/tmp-dir: unable to open object: a56e6382db5bb09da0859e90b0c417dd: failed to open object with id a56e6382db5bb09da0859e90b0c417dd: error to open object: content a56e6382db5bb09da0859e90b0c417dd not found: object not found: Failed to run kopia restore: Failed to copy snapshot data to the target: restore error: error copying: copy file: error creating file: unable to open snapshot file for /host_pods/07f7ac49-2bc6-413d-ae17-2ed3adfae093/volumes/kubernetes.io~empty-dir/tmp-dir: unable to open object: a56e6382db5bb09da0859e90b0c417dd: failed to open object with id a56e6382db5bb09da0859e90b0c417dd: error to open object: content a56e6382db5bb09da0859e90b0c417dd not found: object not found, pod volume restore failed: error running restore err=Failed to run kopia restore: Failed to copy snapshot data to the target: restore error: error copying: copy file: error creating file: unable to open snapshot file for /host_pods/07f7ac49-2bc6-413d-ae17-2ed3adfae093/volumes/kubernetes.io~empty-dir/gpg-keyring: unable to open object: 72a615e32cd6789288625c5fbed79cc0: failed to open object with id 72a615e32cd6789288625c5fbed79cc0: error to open object: content 72a615e32cd6789288625c5fbed79cc0 not found: object not found: Failed to run kopia restore: Failed to copy snapshot data to the target: restore error: error copying: copy file: error creating file: unable to open snapshot file for /host_pods/07f7ac49-2bc6-413d-ae17-2ed3adfae093/volumes/kubernetes.io~empty-dir/gpg-keyring: unable to open object: 72a615e32cd6789288625c5fbed79cc0: failed to open object with id 72a615e32cd6789288625c5fbed79cc0: error to open object: content 72a615e32cd6789288625c5fbed79cc0 not found: object not found]" logSource="pkg/restore/restore.go:1699" restore=velero/18sepaks-20230918114846

with describe restore

<img width="586" alt="image" src="https://github.com/vmware-tanzu/velero/assets/14858986/9afa01e3-dcb2-430c-974a-7f41d8a420f6">

restore command used is 

./velero create restore --from-backup 18sepaks --exclude-resources MutatingWebhookConfiguration.admissionregistration.k8s.io,ValidatingWebhookConfiguration.admissionregistration.k8s.io --kubeconfig awskubeconfig

the same issue is happening with restic, changes made in installation is "--uploader-type=restic", rest of the command remains same
error:
time="2023-09-05T05:38:33Z" level=error msg="unable to successfully complete restic restores of pod's volumes" error="pod volume restore failed: error running restic restore, cmd=restic restore --repo=azure:velero:/restic/gmp-system --password-file=/tmp/credentials/velero/velero-restic-credentials-repository-password --cache-dir=/scratch/.cache/restic 57a0c6cd --target=., stdout=, stderr=invalid id \"57a0c6cd\": no matching ID found for prefix \"57a0c6cd\"\n: exit status 1" logSource="pkg/restore/restore.go:1579" restore=velero/5septnewgcp1-backup-20230905053801

**What did you expect to happen:**
restore getting successfully completed and argocd,opa to be restored in destination cluster

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

**Anything else you would like to add:**
in this link https://github.com/vmware-tanzu/velero/issues/4133 , it is mentioned that this volume issue will be fixed in the versions above 1.7.0+

**Environment:**

- Velero version (use `velero version`): Version: v1.11.1
- Velero features (use `
[bundle-2023-09-18-13-07-19.tar.gz](https://github.com/vmware-tanzu/velero/files/12648027/bundle-2023-09-18-13-07-19.tar.gz)
velero client config get features`): 
- Kubernetes version (use `kubectl version`): Server Version aws : v1.24.16-eks-2d98532
-server version aks: Server Version: v1.25.6
- Kubernetes installer & version:
- Cloud provider or hardware configuration: 
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
@Meghavenkatesh Did the restore work for the previous version of Velero?

Does the backup contain any other kinds of volumes except emptyDir? Are these volumes restored correctly?

**Comment by Meghavenkatesh** [comment]
Hi  @ywk253100 

Even in the older versions of velero we were facing the same issues, so tried with new version, any volume type with persistent, downward api and empty Dir, except few PVC's everything is getting into error.
![image](https://github.com/vmware-tanzu/velero/assets/14858986/1a888b62-335c-49bd-ac18-2442c280d304)
![image](https://github.com/vmware-tanzu/velero/assets/14858986/cf9d9b94-4a1d-4c54-aafc-08ef10debff3)

**Comment by Meghavenkatesh** [comment]
[bundle-2023-09-21-06-04-46.tar.gz](https://github.com/vmware-tanzu/velero/files/12680870/bundle-2023-09-21-06-04-46.tar.gz)
Sure, have attached the bundle please have a look.

**Comment by Meghavenkatesh** [comment]
[bundle-2023-09-22-06-08-03.tar.gz](https://github.com/vmware-tanzu/velero/files/12697360/bundle-2023-09-22-06-08-03.tar.gz)
Attaching the newly generated bundle.
Thanks

**Comment by ywk253100** [comment]
There are 12 `emptyDir` volumes and corresponding 12 PVBs in the backup. 
All of the PVBs are completed:
- 7 PVBs are completed with message `volume was empty so no snapshot was taken`
- 5 PVBs are completed with data backed up

There are 5 PVRs:
- 4 PVRs are failed with error `error to open object: content xxx not found: object not found`
- 1 PVR is in progress

Seems the snapshots are gone from the repository or cannot be located for some reason.

@Lyndon-Li @qiuming-best Can we provide some Kopia commands to verify that whether the snapshots are still in repository or not?

**Comment by Meghavenkatesh** [comment]
Hi,

Adding to the above issue,argocd,opa pods have projected volumes, empty dir,if these volumes are skipped then the restore is working fine, but as checked in https://github.com/vmware-tanzu/velero/issues/4133 it was mentioned it is known restic behaviour and will be fixed in upcoming 1.7.0 release, is that not fixed or lease let us know if we are missing any step in between while installation.
Thanks

**Comment by Meghavenkatesh** [comment]
Hi All,  

The above issue with empty dir is not occuring now, since we have annotated the pods to exclude backup of empty dir, but right now, we are having issues with the pvc , unable to restore the pvc which is using csi drivers
we also have included csi flags in the velero installation and also cross checked from the cluster to have csi feature enabled from cloud console.
command used: 
velero install --provider gcp --bucket <bucket> --secret-file <secret file> --backup-location-config serviceAccount=<service-account> --use-node-agent --use-volume-snapshots=true --plugins=velero/velero-plugin-for-gcp:v1.8.1,velero/velero-plugin-for-csi:v0.6.1 --velero-pod-cpu-limit 1200m --velero-pod-cpu-request 700m --velero-pod-mem-limit 1Gi --velero-pod-mem-request 500Mi --uploader-type=kopia --default-volumes-to-fs-backup --snapshot-location-config apiTimeout=10m --features=EnableAPIGroupVersions,EnableCSI --node-agent-pod-cpu-request 1500m --node-agent-pod-mem-request 1024Mi --node-agent-pod-cpu-limit 3000m --node-agent-pod-mem-limit 4Gi --kubeconfig <kubeconfig>

Kindly help us to resolve this issue

Thanks in advance.
