### ISSUE TITLE
Creating "Schedule" object manually - doc missing

### ISSUE THREAD

**Issue by tomplus** [vmware-tanzu/velero#684]
**Describe the solution you'd like**

I know that it's possible to create `Schedule` object manually instead of use `ark` command. I use it to deploy all manifests to K8s. In my opinion that possibility should be described in documentation, or maybe I can't found it...

**Anything else you would like to add:**

N/A

**Environment:**

N/A

**Comment by nrb** [comment]
Hi @tomplus,

Are you looking for something like https://heptio.github.io/ark/v0.9.0/output-file-format, but for schedules?

**Comment by tomplus** [comment]
More like this: https://heptio.github.io/ark/v0.9.0/config-definition but for schedules.

**Comment by spiffcs** [comment]
@skriss I can give this a look tonight on my flight - 

I was thinking of adding the reference so it fit the scheme below:

`https://velero.io/docs/v1.1.0/schedule-reference`

<img width="413" alt="Screen Shot 2019-10-01 at 9 53 36 PM" src="https://user-images.githubusercontent.com/32073428/66012653-fd279300-e495-11e9-96c0-4d9bb3964d21.png">

It would be found below `Restore Reference`

**Comment by spiffcs** [comment]
If that isn't the intent of this issue and instead you want coverage for the custom api type of `schedule` I can add that instead under this menu in the same style that you have written the other types:

<img width="923" alt="Screen Shot 2019-10-01 at 10 03 22 PM" src="https://user-images.githubusercontent.com/32073428/66012959-622fb880-e497-11e9-94ca-6a46081fd75b.png">

**Comment by spiffcs** [comment]
PR can be found here #1925
