### ISSUE TITLE
new install to 1.28 missing bitnami/kubectl:1.28

### ISSUE THREAD

**Issue by davhdavh** [vmware-tanzu/velero#6846]
**What steps did you take and what happened:**

Installed new 1.28 cluster, and setup velero.

It starts a pod that tries to load `bitnami/kubectl:1.28` (I assume it uses the version from the cluster).

However, bitnami has not yet made a 1.28 version of this image. 

**What did you expect to happen:**

Pod uses `:latest` instead of assuming that bitnami is totally up2date with current kubernetes versions.

**Environment:**

- Velero version (use `velero version`): 1.7.1
- Kubernetes version (use `kubectl version`): 1.28.2
- Cloud provider or hardware configuration: metal
- OS (e.g. from `/etc/os-release`): debian 12

**Comment by yanggangtony** [comment]
Pardon me if i am wrong.
--------------------------------
Is the ```velero install``` have some association with the bitnami/kubectl:xxx???

**Comment by davhdavh** [comment]
https://github.com/vmware-tanzu/helm-charts/blob/7564a60a891199aff32dc4f34ca9f1e882e18e59/charts/velero/templates/upgrade-crds/upgrade-crds.yaml#L46

**Comment by yanggangtony** [comment]
educated.
@davhdavh 
thanks.
i will look this issue more ...

**Comment by yanggangtony** [comment]
simple to replace  ```
          image: "{{ .Values.kubectl.image.repository }}:{{ template "chart.KubernetesVersion" . }}"
```
to --> 
```
          image: "{{ .Values.kubectl.image.repository }}:latest"
``` may be too rude.

Here need maintainers to confirm that..

**Comment by ywk253100** [comment]
@davhdavh You can specify the tag explicitly: https://github.com/vmware-tanzu/helm-charts/blob/7564a60a891199aff32dc4f34ca9f1e882e18e59/charts/velero/values.yaml#L245

**Comment by davhdavh** [comment]
Still not fixed

**Comment by rlex** [comment]
seems like image is here, but CRD upgrade fails with silent CrashLoopBackOff. No logs in job too.

**Comment by yanggangtony** [comment]
There is a similar issue like that .[https://github.com/vmware-tanzu/velero/issues/6869#issuecomment-1736397520](https://github.com/vmware-tanzu/velero/issues/6869#issuecomment-1736397520). 

@davhdavh 
Would you confirm you just run helm chart direct , and not a sub-chart include the velero's charts.

**Comment by davhdavh** [comment]
directly? No, it is argo-cd that does the deployment (which is semantically slightly different, since argo-cd does something equivalent of running helm --dry-run and applies the yaml generated)
```
dependencies:
  - name: velero
    version: 5.0.2
    repository: https://vmware-tanzu.github.io/helm-charts/
```
We dont touch the `cleanUpCRDs` or `upgradeCRDs`, so it uses the default:
https://github.com/vmware-tanzu/helm-charts/blob/5e87e22fe4cb813742bd6243cb52b3047d59775c/charts/velero/values.yaml#L296

**Comment by yanggangtony** [comment]
Yep , @davhdavh 

So you are using velero in a sub-chart . 

Would you try it as the chart reference [overriding-values-from-a-parent-chart](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart) to override your ```bitnami/kubectl:1.28```

**Comment by yanggangtony** [comment]
@davhdavh 
I mean you should update the values.yaml in your parent chart , its argo's chart , not the velero's chart.

And reference [https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart)](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart)) to update the sub-chart value.


Something like 
```
argo1:
  xxx: xx1
argo2:
  - yy1

velero:
  kubectl.image.tag: xx
```

**Comment by davhdavh** [comment]
Ofcourse that will work, I already did that long time ago.

**Comment by yanggangtony** [comment]
So, what's the problem here?
