### ISSUE TITLE
Replace the base image with paketobuildpacks image

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#6851]
Currently, the base image of Velero is `distroless` which contains several CVEs cannot be fixed timely, we'll switch to `paketobuildpacks` images instead

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by anshulahuja98** [comment]
@ywk253100 can we remove this from 1.13 milestone if this is targeted for 1.12?

**Comment by ywk253100** [comment]
> @ywk253100 can we remove this from 1.13 milestone if this is targeted for 1.12?

@anshulahuja98 It's not targeted for 1.12.0.
It will be done during the 1.13 timeframe and will be cherry-picked for the patch release 1.12.1
