### ISSUE TITLE
useOwnerReferencesInBackup: true is broken

### ISSUE THREAD

**Issue by davhdavh** [vmware-tanzu/velero#6857]
**What steps did you take and what happened:**
When setting useOwnerReferencesInBackup to true, velero is unable to restore `Backup` resoruces unless the `uid` of the parent schedule is the same as when it was created.

Not sure if that is clear... So here in steps:
1. create cluster
2. install velero
3. create schedule with name `x` with useOwnerReferencesInBackup: true
4. wait for schedule to trigger and make a backup
5. destroy cluster
6. create cluster
7. install velero
8. create schedule with name `x` with useOwnerReferencesInBackup: true
9. wait for velero to restore previous `Backup` - FAIL

Logs will gladly say it was a success:

```
time="2023-09-22T04:19:09Z" level=info msg="Found 1 backups in the backup location that do not exist in the cluster and need to be synced" backupLocation=velero/aws controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:135"

time="2023-09-22T04:19:09Z" level=info msg="Attempting to sync backup into cluster" backup=velero-testmeschedule-20230922040030 backupLocation=velero/aws controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:143"

time="2023-09-22T04:19:09Z" level=info msg="Successfully synced backup into cluster" backup=velero-testmeschedule-20230922040030 backupLocation=velero/aws controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:185"
```

Similar problem:
1. create cluster `a`
2. create cluster `b`
3. install velero in both
4. create schedule with name `a` and `b` with useOwnerReferencesInBackup: true where `a` takes backup of cluster `a` resource and similar for `b`.
5. wait for schedule to trigger on `a` and make a backup
6. on `b` wait for velero to restore previous `Backup` for `a` - FAIL

**What did you expect to happen:**

`velero-testmeschedule-20230922040030` is correctly restore as a child of the new `x`.

or

backups made on cluster `a` is visible on cluster `b`.

**The following information will help us better understand what's going on**:

**Anything else you would like to add:**
Other bugs with similar problem:
#4456
#4093

**Environment:**

- Velero version (use `velero version`): 1.11.1
- Velero features (use `velero client config get features`): none
- Kubernetes version (use `kubectl version`): 1.27.3 and 1.28.2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
Fixed by https://github.com/vmware-tanzu/velero/pull/7032
