### ISSUE TITLE
Velero restore stuck during Kopia restoration

### ISSUE THREAD

**Issue by bmalynovytch** [vmware-tanzu/velero#6858]
**What steps did you take and what happened:**

- Created a backup on a cluster
- Created a restore on another cluster (migrating workload)
- Restoration works, Kopia start restoring datas
- Restoration finally get stuck at around 97% (depending on the workload migrated)

**What did you expect to happen:**
Restore should end  correctly in reasonable delay.

**Anything else you would like to add:**
Can't provide logs or resource descriptions for discrepancy reasons.
I migrated tens of workloads using this method, most of them worked without issues but some get stuck with no reason.
To force the restore to end, I delete node agent and velero pod, which makes the restore partially failed, but it seems that data where properly restored. Once the restore is failed, I read the logs and found nothing relevant (no informations abouts Kopia's work)

**Environment:**

- Velero version (use `velero version`): `v1.11.0`
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): `Client: v1.28.1, Server: v1.23.6`
- Kubernetes installer & version: `kubeadm`
- Cloud provider or hardware configuration: VM with 40 vCPU, 96 GB RAM, 1To NVMe storage
- OS (e.g. from `/etc/os-release`): `Rocky Linux 9.2 (Blue Onyx)`

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
The corresponding CRD for Kopia to handle the pod volume restoration is `PodVolumeRestore`, could you check is there any `PodVolumeRestore` stuck or in failed status?

**Comment by bmalynovytch** [comment]
Indeed:
```
  message: get a podvolumerestore with status "InProgress" during the server starting,
    mark it as "Failed"
```

I have none stuck right now, I guess the previous error is only a consequence of restarting the node agent pod while restoration is in progress.

**Comment by sseago** [comment]
Yes, if node agent restarts, in-progress operations in that pod will fail.

**Comment by ywk253100** [comment]
@bmalynovytch 

Could you reproduce it again? When you get stuck, check the status of the `PodVolumeRestore`.

**Comment by qiuming-best** [comment]
@u3813 could you share your steps in detail on restoring stuck and we may help to fix it?
And also which version of Velero do you use?

**Comment by qiuming-best** [comment]
@u3813 Thanks for the logs you provided, the unreasonable closing `golang Channel` leads to the panic, we will consider fixing it in our new release

**Comment by qiuming-best** [comment]
the restore channel was closed by [CheckContext](https://github.com/vmware-tanzu/velero/blob/v1.11.0/pkg/uploader/provider/kopia.go#L82) prior to the defer [function](https://github.com/vmware-tanzu/velero/blob/v1.11.0/pkg/uploader/provider/kopia.go#L187)
The unreasonable logic of closing closed `golang channel`  has been removed in this [PR](https://github.com/vmware-tanzu/velero/commit/623da51494fb83819552bd7257c7668bcde3c489#diff-f79c2f6afc15fc2939b0704adef2a16f0c920fe5cf4fd9074156149168f75cfbL190-L192), it won't have problem from v1.12.0.

**Comment by qiuming-best** [comment]
I closed the issue if having a related issue please reopen it.
