### ISSUE TITLE
Velero plugins depends on Velero's Repository package unnecessarily

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#6859]
Some Velero plugins, i.e., CSI plugin, vSphere plugin are calling some utility function from Velero's Repository package, as a result, the packages that Velero's Repository depends are included in Velero plugins unnecessarily, i.e., kopia, azure-sdk, etc.

**Comment by kaovilai** [comment]
Related
https://github.com/vmware-tanzu/velero/pull/6484

**Comment by 27149chen** [comment]
Velero plugins are also calling interfaces like BIA, RIA, and Server. It is better to seperate the plugin package as an independent go library so that a third party velero plugin can easily import

**Comment by 27149chen** [comment]
The velero apis has the same problem, sometimes I just need the backup/restore sturcts, but i have to import the whole Velero's repository

**Comment by Lyndon-Li** [comment]
@27149chen 

> Velero plugins are also calling interfaces like BIA, RIA, and Server. It is better to seperate the plugin package as an independent go library so that a third party velero plugin can easily import

Could you share more details of what the problem/barrier is when the plugin package stays with Velero?

**Comment by 27149chen** [comment]
> @27149chen
> 
> > Velero plugins are also calling interfaces like BIA, RIA, and Server. It is better to seperate the plugin package as an independent go library so that a third party velero plugin can easily import
> 
> Could you share more details of what the problem/barrier is when the plugin package stays with Velero?

The functionality of A Velero plugin can be tiny, for example, I just want to add an annotation to the restored pod. So I import the RestoreItemActionExecuteInput/RestoreItemActionExecuteOutput and implement my own .Execute() fucntion. But I have to import the whole Velero repo since plugin package go together with other Velero code which is unnecessarily

**Comment by Lyndon-Li** [comment]
@27149chen 
OK. Then it looks like all the two cases come down to the fact that Velero doesn't have a distinguish of public modules/interfaces from internal ones.
It is a good idea to have it, and I think that will be a longer term topic as it involves dramatic changes to the existing code. Please help to open a new issue, let's discuss it separately.

**Comment by 27149chen** [comment]
> @27149chen OK. Then it looks like all the two cases come down to the fact that Velero doesn't have a distinguish of public modules/interfaces from internal ones. It is a good idea to have it, and I think that will be a longer term topic as it involves dramatic changes to the existing code. Please help to open a new issue, let's discuss it separately.

created https://github.com/vmware-tanzu/velero/issues/6878
