### ISSUE TITLE
podvolumebackups still reference Restic in repository ID path (repoIdentifier) after switching to Kopia

### ISSUE THREAD

**Issue by u3813** [vmware-tanzu/velero#6861]
**What steps did you take and what happened:**
I recently switched to the Kopia uploader-type and I noticed that my podvolumebackups still show references to Restic in the repository ID path (repoIdentifier).

**What did you expect to happen:**
I did not expect any references to Restic to appear anymore. I had removed all Restic CRDs and the Restic backuprepository as well. Can someone explain to me why Restic is still showing up in the repository ID path?

**The following information will help us better understand what's going on**:
```
NAMESPACE   NAME                STATUS      CREATED   NAMESPACE    POD             VOLUME     REPOSITORY ID                                       UPLOADER TYPE   STORAGE LOCATION   AGE
velero      myschedule          InProgress   4m       redacted     redacted        redacted  s3:https://redacted/velero/redacted/restic/redacted   kopia          default            4m1s
```

**Anything else you would like to add:**

Please let me know if any important information is missing here.

**Environment:**

- Velero version (use `velero version`): `v1.11.1`, installed using Helm Release `4.1.4`
- Velero features (use `velero client config get features`):  not set
- Kubernetes version (use `kubectl version`): v1.25.12
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: on premise
- OS (e.g. from `/etc/os-release`): VMware Tanzu

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
The repository ID is not used by Kopia path, so it is safe to continue use Kopia path in this way.

However, it is indeed confusing, let me set a more meaningful value of repositoryID for Kopia path.
