### ISSUE TITLE
changed ttl in schedule does not update ttl deletion

### ISSUE THREAD

**Issue by Nello-Angelo** [vmware-tanzu/velero#6868]
**What steps did you take and what happened:**
i created schedule with ttl 3h0m0s and after a time i decided to update it on ttl 24h0m0s but schedule continue delete old backups using old ttl and ignores new value in existing schedule

**What did you expect to happen:**
i would like to update ttl for existing schedule dynamically 

**Environment:**
- Velero version 1.11.1: 
- Velero features velero with node agents: 
- Kubernetes version 1.25.8:
- OS debian 11

**Comment by draghuram** [comment]
This is working as per design. Velero doesn't update old backups with the new TTL value. The new value applies only to future backups.

**Comment by Nello-Angelo** [comment]
In existing schedule?

**Comment by draghuram** [comment]
Yes, new backups created from existing schedules.

**Comment by Nello-Angelo** [comment]
thanks
