### ISSUE TITLE
snapshot-move-data function cannot be used with velero schedule create on v1.12.0

### ISSUE THREAD

**Issue by aki-kamada** [vmware-tanzu/velero#6870]
**What steps did you take and what happened:**
I found that data-mover function doesn't work in "velero schedule create" command on v1.12.0.
A while ago, I opened ticket https://github.com/vmware-tanzu/velero/issues/6820. But, it was not fix yet.

And I confirmed that "velero backup create --snapshot-move-data" work well on v1.12.0. (Environment information wrote this ticket https://github.com/vmware-tanzu/velero/issues/6785)

When velero backup create --snapshot-move-data, HPE Primera storage receved request by delete snapshot from Velero.
But velero create schedule --snapshot-move-data, HPE Primera storage doesn't received request by delete snapshot from Velero.

**What did you expect to happen:**
It should remove snapshotvolume on HPE Storage when we use velero schedule create --snapshot-move-data.

**The following information will help us better understand what's going on**:

```
$ velero schedule create test-schedule-kamada-20230926-105700 --schedule="*/3 * * * *" --snapshot-move-data --selector velerobackup=enable --namespace kube-storage --include-namespaces kong-customplugin

$ velero backup describe --namespace=kube-storage test-schedule-kamada-20230926-105700-20230926020036
Name:         test-schedule-kamada-20230926-105700-20230926020036
Namespace:    kube-storage
Labels:       velero.io/schedule-name=test-schedule-kamada-20230926-105700
              velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.26.6
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=26

Phase:  Completed


Namespaces:
  Included:  kong-customplugin
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  velerobackup=enable

Storage Location:  default

Velero-Native Snapshot PVs:  auto
Snapshot Move Data:          auto
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2023-09-26 11:00:37 +0900 JST
Completed:  2023-09-26 11:00:56 +0900 JST

Expiration:  2023-10-26 11:00:37 +0900 JST

Total items to be backed up:  14
Items backed up:              14

Backup Item Operations:  4 of 4 completed successfully, 0 failed (specify --details for more information)
Velero-Native Snapshots: <none included>
```

**Anything else you would like to add:**

I wrote the information for snapshot-move-data in the past two tickets below. Please let me know if you need any other information.
https://github.com/vmware-tanzu/velero/issues/6820
https://github.com/vmware-tanzu/velero/issues/6820

**Environment:**

- Velero version (use `1.12.0`): 
- Velero CSI plugin version (use `v0.6.0`): 
- Velero s3 plugin version (use `velero-plugin-for-aws:v1.8.0`): 
- Velero features (use `feature: <NOT SET>`): 
- Kubernetes version (use `v1.26.6`):
- OS (e.g. from `20.04.1 LTS`):
- HPE CSI Driver (use `2.3.0`): 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
I just tried with v1.12.0 Velero, and the schedule can create a backup with `SnapshotMoveData` setting correctly.
Please check whether the `velero` binary is the just-released version: https://github.com/vmware-tanzu/velero/releases/tag/v1.12.0

**Comment by aki-kamada** [comment]
@blackpiglet  
Looking at your comment, I noticed an update to the client side velero command.
And I confirmed that velero schedule can work well with --snapshot-data-move. 

Thank you.
