### ISSUE TITLE
Allow filtering by volume type

### ISSUE THREAD

**Issue by Heiko-san** [vmware-tanzu/velero#6871]
**Describe the problem/challenge you have**

I think what most would basically want regarding to PVC backup is the opt-out approach, so no PVC get missed by accident.

We want to use restic backup with opt-out.
This however will also backup all the empty dir volumes etc.
Since those are typically meant to be ephemeral and also since we had some issue when velero tries to restore some of those, we would like to have an option to backup "restic opt-out" but only PVCs, no other volumes (e.g. like empty dir).

I couldn't find a solution for that other then putting annotations on all the pods and even then it seems I can't do "exclude *", instead you would have to name all volumes,

**Describe the solution you'd like**

There should be an option for backup definitions, that says "ok, it's opt-out, but only do PVCs" or "exclude volume type x, y, z" or something.

**Comment by blackpiglet** [comment]
https://github.com/vmware-tanzu/velero/pull/6863
There is a PR working on this. It should be included in the v1.13 release.

**Comment by blackpiglet** [comment]
Since this is already an issue https://github.com/vmware-tanzu/velero/issues/6482 describes this need, close this for now.
