### ISSUE TITLE
PV data not restoring in cross account resource migration

### ISSUE THREAD

**Issue by prasoon-pxc** [vmware-tanzu/velero#6876]
**What steps did you take and what happened:**

**Scenario:--->** 
I have two kubernetes cluster,  dev and staging which is running on two different AWS accounts, I have installed velero on both clusters.

I have created S3-bucket on my dev aws account and give IAM role access to bucket using IRSA , Now I am using that federated role in my staging velero service account to fetch data from dev aws S3 bucket.

**WHAT HAPPENED**

I can able to restore kube-manifests from dev to staging but when I try the same for PV , it gives me error on pod creation 

```
 Warning  FailedAttachVolume  12s  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-f475ddc6-9842-4854-9df6-ec824e121a33" : rpc error: code = Internal desc = Could not get volume with ID "vol-0d53688deae0bace1": InvalidVolume.NotFound: The volume 'vol-0d53688deae0bace1' does not exist.
           status code: 400, request id: 32460546-9e3d-4d4c-ac7c-88bcdff0507f

```
This error is somehow understandable because I am seeing this volume-id gets created in dev aws account instead of stag-aws-account and that's why pvc does not able to bind that volume to pods.

**What did you expect to happen:**

On triggering restore for dev-cluster backup from staging , it should create volume on staging AWS account instead of dev , so that pod can consume it.

**Environment:**

- Velero version (use `velero version`): 

```
Client:
	Version: v1.11.0
	Git commit: 0da2baa908c88ec3c45da15001f6a4b0bda64ae2
Server:
	Version: v1.11.1

```
- Velero features (use `velero client config get features`): 
```
features: <NOT SET>

```
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-2d98532", GitCommit:"222fd0c4adcf243ebeaee986cc0d41a39e570d8f", GitTreeState:"clean", BuildDate:"2023-07-28T16:53:07Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"

**Comment by prasoon-pxc** [comment]
does filesystem backup support using irsa based access for accessing S3-bucket?

**Comment by blackpiglet** [comment]
I think so.

**Comment by prasoon-pxc** [comment]
@blackpiglet thanks, I am able to do PV migration using restic but there are some problems:

- I want to use both restic and aws-plugin for same velero instance and just want to use restic if I want cross-account backup and aws-plugin for same account backup, right now If i tried restic backup it creates volume snapshots backups also with aws plugin.
- Secondly, I also wanted to backup only PV and PVC in some case , I wanted to do it with using selector but it's not working atm I have to annotate pod with particular volume first , and I think simple PV and PVC is not possible without pod volume mount.
- Third, I have two different IAM roles , one for access in same cluster account and second one is for cross-account and I want to annotate my velero service acccount with both IAM roles, but it's not happening right now.

**Comment by blackpiglet** [comment]
* If you don't want the AWS snapshot created, you can disable it by `--snapshot-volumes=false` in the backup creation command.
* Right. If you are using the filesystem backup, at least, pods are needed. I think label selector can only work for resource selection. It cannot be used for volume data backup. You can use `--default-volumes-to-fs-backup` to set the FS backup as the default behavior, then narrow the backup scope, e.g. by namespace filtering. 
* I also don't have a opinion on this. If you can combine the two roles into one, it can be solved.
