### ISSUE TITLE
Velero 1.12.0 is missing on Chocolatey

### ISSUE THREAD

**Issue by DerEnderKeks** [vmware-tanzu/velero#6891]
**What steps did you take and what happened:**

Velero 1.12.0 is missing on Chocolatey. The latest available version there is 1.11.0. (https://community.chocolatey.org/packages/velero)

**What did you expect to happen:**
I expect Velero 1.12.0 to be available on Chocolatey.

**The following information will help us better understand what's going on**:

**Anything else you would like to add:**

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
I released the Velero v1.11.0 with Homebrew, but I didn't try with the Chocolatey, because I didn't have a Windows developing environment setup, but it looks like Chocolatey also has the released version.

I will do the same for the Velero v1.12.0 to see whether that can address your need.

**Comment by blackpiglet** [comment]
Just tried. The brew update PR was already created by others several days ago.
https://github.com/Homebrew/homebrew-core/pull/144815

**Comment by kaovilai** [comment]
> Clearly, there is no relation between Chocolatey and Brew Publish.

Yeah they are two independent opensource package managers

**Comment by kaovilai** [comment]
If Windows is needed, github actions do [provide windows machine you can use](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#using-a-github-hosted-runner:~:text=ubuntu%2Dlatest%2C-,windows%2Dlatest,-%2C%20or%20macos%2Dlatest) to run workflows if necessary.

**Comment by kaovilai** [comment]
Updating workflows would probably make the most sense
https://github.com/adamrushuk/velero-choco/blob/master/.github/workflows/release-choco-package.yml

Ideally via webhooks on velero github release event. but fall back to cronjob.

**Comment by kaovilai** [comment]
Let me know if I could assist

**Comment by blackpiglet** [comment]
Thanks, Tiger.
I think this is not a high-priority issue. The brew and chocolatey release was not a must-have in the Velero release process. 
Standardizing it as a Github action does help, but if it needs quite some effort, we can focus on other tasks first.

**Comment by blackpiglet** [comment]
I gave it a try, but it failed with no permission. The Velero chocolatey package is managed by @adamrushuk. Could you help to create the v1.12.0 version of Velero?

```
PS C:\Users\blackpiglet\Documents\velero> choco push velero.1.12.0.nupkg --source https://push.chocolatey.org/
Chocolatey v0.11.3
Attempting to push velero.1.12.0.nupkg to https://push.chocolatey.org/

Failed to process request. 'Forbidden'.
```

**Comment by adamrushuk** [comment]
Hi @blackpiglet The latest release is status is `Pending Automated Review`. Hopefully it will complete internal testing within an hour or so.

**Comment by blackpiglet** [comment]
@adamrushuk 
Thanks for your contribution and quick response.
This [repository](https://github.com/adamrushuk/velero-choco) gives a very detailed guide.

**Comment by adamrushuk** [comment]
I'll see if I can automate these releases :)

**Comment by blackpiglet** [comment]
Thanks.
Could you also add me to the maintainer list in case any help is needed? My chocolatey profile is https://community.chocolatey.org/profiles/blackpiglet

**Comment by blackpiglet** [comment]
@DerEnderKeks 
https://community.chocolatey.org/packages/velero/1.12.0
The v1.12.0 Velero chocolatey package is ready. Thanks for @adamrushuk effort.
Close this issue.
