### ISSUE TITLE
Velero node agent not found; pod volume backups/restores will not work until it's created" logSource="pkg/cmd/server/server.go:571"

### ISSUE THREAD

**Issue by sachin064** [vmware-tanzu/velero#6900]
using velero plugin for aws v1.6.1 version

getting warning like bellow
time="2023-09-29T14:24:21Z" level=warning msg="Velero node agent not found; pod volume backups/restores will not work until it's created" logSource="pkg/cmd/server/server.go:571"

**Comment by sseago** [comment]
It looks like you're trying to use filesystem backup but without enabling the node agent in the velero install. This isn't related to the AWS plugin.

**Comment by linpanru** [comment]
![image](https://github.com/user-attachments/assets/f8ff34db-d905-4701-aee2-6a78c342b2ff)
![image](https://github.com/user-attachments/assets/98cda8eb-d703-4095-8d25-dccb96e4da90)
 my node agnet is installed , it still have this  log

**Comment by blackpiglet** [comment]
It's weird. Need more information to know why.
But I found the velero pod name seems a bit abnormal. `kg-velero-....`.
