### ISSUE TITLE
Data Upload fails with error "ConcatenateObjects is not supported"

### ISSUE THREAD

**Issue by galbeniluz** [vmware-tanzu/velero#6904]
**What steps did you take and what happened:**
I'm trying to test the new CSI Snapshot Data Movement feature, we are using Velero to backup our KubeVirt environment and virtual machines volumes 

I've got a lot of failed datauploads with the following error 

`Error when processing disk.img: ConcatenateObjects is not supported`

**Environment:**

- Velero version (use `velero version`): v1.12.0
- Velero features (use `velero client config get features`): EnableCSI
- Kubernetes version (use `kubectl version`): v1.23.14
- Kubernetes installer & version: v1.23.14
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): CentOs 7.9

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Duplicated with #6880. This is already fixed in the main and coming v1.12.1.

**Comment by galbeniluz** [comment]
Hi @blackpiglet any estimation on when it will be released?
