### ISSUE TITLE
BackupRepository - error to init backup repo - found existing data in storage location

### ISSUE THREAD

**Issue by ashum81** [vmware-tanzu/velero#6909]
**What steps did you take and what happened:**
Velero creates BackupRepository with error:
`error to init backup repo: error to create repo with storage: error to
    ensure repository storage empty: found existing data in storage location`

```
apiVersion: velero.io/v1
kind: BackupRepository
metadata:
  creationTimestamp: '2023-10-03T05:14:29Z'
  generateName: cdi-backup-location-kopia-
  generation: 3
  labels:
    velero.io/repository-type: kopia
    velero.io/storage-location: backup-location
    velero.io/volume-namespace: cdi
  name: cdi-backup-location-kopia-zkztb
  namespace: velero
  resourceVersion: '101801759'
  uid: 8bbac42e-6a25-44bf-b1e0-7f69f1911d61
spec:
  backupStorageLocation: backup-location
  maintenanceFrequency: 24h0m0s
  repositoryType: kopia
  resticIdentifier: s3:https://s3.mycompany.com/velero-vlg-t22-dc-s/restic/cdi
  volumeNamespace: cdi
status:
  message: >-
    error to init backup repo: error to create repo with storage: error to
    ensure repository storage empty: found existing data in storage location
  phase: NotReady
```

```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade,post-rollback
    helm.sh/hook-delete-policy: before-hook-creation
    meta.helm.sh/release-name: velero
    meta.helm.sh/release-namespace: velero
  creationTimestamp: '2023-08-18T05:28:34Z'
  generation: 127856
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-4.0.2
  name: backup-location
  namespace: velero
  resourceVersion: '101831358'
  uid: 85c5623a-0d3a-4667-94f5-ee96cef91d61
spec:
  accessMode: ReadWrite
  config:
    region: default
    s3ForcePathStyle: 'true'
    s3Url: https://s3.mycompany.com
  default: true
  objectStorage:
    bucket: velero-vlg-t22-dc-s
    caCert: >-
...
  provider: aws
status:
  lastSyncedTime: '2023-10-03T05:35:51Z'
  lastValidationTime: '2023-10-03T05:36:02Z'
  phase: Available
```

I create backup with config:
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: cdi
  namespace: velero
spec:
  includedNamespaces:
  - "cdi"
```

Files are created in the repository:
```
2023-10-03 00:01        30   s3://velero-vlg-t22-dc-s/kopia/cdi/kopia.blobcfg
2023-10-03 00:01      1075   s3://velero-vlg-t22-dc-s/kopia/cdi/kopia.repository
```

cat kopia.repository
```
{
  "tool": "https://github.com/kopia/kopia",
  "buildVersion": "v0-unofficial",
  "buildInfo": "unknown",
  "uniqueID": "A5TnI5ogYkfwZ4yCDtp0Xcs96a1URpg6NEFiI5ZGpnE=",
  "keyAlgo": "scrypt-65536-8-1",
  "encryption": "AES256_GCM",
  "encryptedBlockFormat": "...="
}
```

**Environment:**

- Velero version (use `velero version`): v1.12.0
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`): v1.24.10+rke2r1
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by danfengliu** [comment]
It seems your data in object store has inconsistency issue, could you try to create a new bucket for BackupStorageLocation, is that working?

**Comment by ashum81** [comment]
It does not help. I have created a new S3 bucket, new BSL, new backup with a new storageLocation. The same error.

**Comment by sseago** [comment]
This will happen if the first BackupRepository reconcile fails during Init() -- the backup repo reconcile will error out, log the failure, and set the status accordingly. Then the next reconcile fails Init() because although it's not properly initialized, the kopia dir already has files in it from the prior failed init. You need to find the underlying error.

So you need to empty your S3 bucket again, delete all BackupRepository CRs in your cluster, and then try again. To find the original error, you can do 2 things:
1) watch the backuprepository resource, looking carefully for status changes: `watch -n .2 kubectl get backuprepository -o yaml` -- will be empty at first, then CR will appear, then you'll see status on reconcile. The original error will be there for a few seconds
2) check velero logs for backuprepository-related errors. You should see the root cause appearing on first reconcile, followed by the "existing data" error on subsequent reconciles.

**Comment by ashum81** [comment]
Velero log says that velero unable to create config directory.
```
time="2023-10-03T13:46:59Z" level=error msg="Error backing up item" backup=velero-backup/cdi error="failed to wait BackupRepository: backup repository is not ready: error to init backup repo: error to connect repo with storage: error to connect to repository: unable to write config file: unable to create config directory: mkdir /udmrepo: read-only file system" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/backup_repo_op.go:83" error.function=github.com/vmware-tanzu/velero/pkg/repository.GetBackupRepository logSource="pkg/backup/backup.go:448" name=cdi-mock-7f7dd57cd6-fzp6d
time="2023-10-03T13:46:59Z" level=error msg="Error backing up item" backup=velero-backup/cdi error="failed to wait BackupRepository: backup repository is not ready: error to init backup repo: error to create repo with storage: error to ensure repository storage empty: found existing data in storage location" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/backup_repo_op.go:83" error.function=github.com/vmware-tanzu/velero/pkg/repository.GetBackupRepository logSource="pkg/backup/backup.go:448" name=ub-5f484f8cf8-rsbhd
```
 I use read-only filesystem and velero starts with
```
  volumeMounts:
  - mountPath: /tmp
    name: tmpdir
    ...
volumes:
- emptyDir: {}
  name: tmpdir
  ...
```

**Comment by sseago** [comment]
@ashum81 For kopia, the Velero pod must be able to write to $HOME in order to write out a config file when it initializes the repo. The released Velero image, installed via the velero installer should already be configured with writable $HOME, but if you've modified the config to make that filesystem read-only, that could be the problem.

**Comment by ashum81** [comment]
I install through helm chart.
What is the path for $HOME?
I see another write-enable dir in config:
```
  volumeMounts:
  - mountPath: /tmp
    name: tmpdir
  - mountPath: /scratch
    name: scratch  
    ...
volumes:
- emptyDir: {}
  name: tmpdir
- emptyDir: {}
  name: scratch
  ...
```

**Comment by sseago** [comment]
Are you using the released Velero image? I'm not actually 100% sure what the value for HOME is in the official image, but I know it's set and works. If you're using an alternate image or rebuilding it yourself, then it doesn't really matter what $HOME is set to, as long as $HOME is set and the dir it's set to is writable by the user that the pod runs as.

**Comment by qiuming-best** [comment]
we have the `VELERO_SCRATCH_DIR` used to put the Restic cache into it.

- May we not fix the Kopia cache location by making it configurable in Velero and reusing 'VELERO_SCRATCH_DIR` for Kopia?

- Or should we use `/.cache` as a fixed volume path to mount the Kopia cache to one writeable host system path? which is no need to make the Kopia cache location configurable in Velero.

- Or the user should not make the filesystem read-only for Restic/Kopia would write cache in filesystem

Not sure which one is better.
