### ISSUE TITLE
Error when executing a Velero action due to version incompatibility in Kubernetes CustomResourceDefinitions

### ISSUE THREAD

**Issue by samuelruiz2020** [vmware-tanzu/velero#6915]
Kubernetes Cluster with Velero and a CSI plugin.

Highlighted Problem: Error when executing a Velero action due to version incompatibility in Kubernetes CustomResourceDefinitions (CRDs).

Problem Description:
I am using Velero with a CSI plugin to back up storage volumes in my Kubernetes cluster. When running a backup action, Velero displays the following error:

time="2023-10-02T16:12:17Z" level=info msg="Executing RemapCRDVersionAction" backup=velero/backup-20231002-155123 cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:61" pluginName=velero
time="2023-10-02T16:12:17Z" level=info msg="Exiting RemapCRDVersionAction, the cluster does not support v1beta1 CRD" backup=velero/backup-20231002-155123 cmd=/velero logSource="pkg/backup/remap_crd_version_action.go:89" pluginName=velero
time="2023-10-02T16:02:10Z" level=error msg="Timed out awaiting reconciliation of volumesnapshot infra/velero-bastion-controller-pvc-tx6r9" backup=velero/backup-20231002-155123 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:191" pluginName=velero-plugin-for-csi
time="2023-10-02T16:02:10Z" level=info msg="1 errors encountered backup up item" backup=velero/backup-20231002-155123 logSource="pkg/backup/backup.go:421" name=occne-bastion-controller-c8dbb7dc9-kbjwj
time="2023-10-02T16:02:10Z" level=error msg="Error backing up item" backup=velero/backup-20231002-155123 error="error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=occne-infra, name=velero-bastion-controller-pvc-tx6r9): rpc error: code = Unknown desc = timed out waiting for the condition" logSource="pkg/backup/backup.go:425" name=occne-bastion-controller-c8dbb7dc9-kbjwj

This error seems to be related to the version of CustomResourceDefinitions (CRDs) used by Velero and the Kubernetes cluster. While I have a CRD definition that includes versions v1 and v1beta1, it appears that the cluster only supports version v1. This causes the compatibility issue and the mentioned error.

Actions Taken So Far:

I have checked Velero's configuration but have not found a clear solution to resolve this CRD version incompatibility problem.
I have reviewed Velero's documentation but have not found details on how to address this specific issue.
Request for Assistance:
I need assistance in resolving this CRD version incompatibility problem in Velero. How can I properly configure Velero to work with version v1 of the CRDs instead of v1beta1? Please provide guidance or specific instructions to address this problem and enable Velero to successfully perform backup actions in my Kubernetes cluster.

# Velero chart repo
# from https://github.com/vmware-tanzu/helm-charts/releases
velero_chart: "velero"
velero_chartrepo: "vmware-tanzu"
velero_chartver: "5.0.2"
# Velero CLI
# from https://github.com/vmware-tanzu/velero/releases
velero_tag: "v1.11.1"
velero_gz: "velero-{{ velero_tag }}-linux-amd64.tar.gz"
# images needed for Velero
# Bitnami Kubectl
# from https://hub.docker.com/r/bitnami/kubectl/tags
velero_bitnami_repo: "docker.io/bitnami/kubectl"
velero_bitnami_tag: "1.24"
# Velero Image
velero_repo: "docker.io/velero/velero"
# Velero plugin for CSI
# from https://hub.docker.com/r/velero/velero-plugin-for-csi/tags
velero_plugin_for_csi_repo: "docker.io/velero/velero-plugin-for-csi"
velero_plugin_for_csi_tag: "v0.5.0"

OS:
NAME="Oracle Linux Server"
VERSION="8.8"

**Comment by danfengliu** [comment]
Could you check out this feature [Enable API Group Versions](https://velero.io/docs/v1.12/enable-api-group-versions-feature/)? Does that answer your question?  My understanding is that in your case CRD preferred version is v1beta1 and support version is v1 in the source cluster, the target cluster only support v1, if that is the case then you can use this [Procedure for Using the Enable API Group Versions Feature](https://velero.io/docs/v1.12/enable-api-group-versions-feature/#:~:text=to%20%E2%80%9Cdestination%20cluster%E2%80%9D.-,Procedure%20for%20Using%20the%20Enable%20API%20Group%20Versions%20Feature,-Install%20Velero%20on), or you can correct me on behalf of your case.

**Comment by samuelruiz2020** [comment]
No, this is not the issue , i had considered it, but this not the case. I don't understand very well if this plugin  is just dedicated to work on v1beta1 versions of kubernetes. 
https://github.com/vmware-tanzu/velero-plugin-for-csi/releases/tag/v0.5.0
https://github.com/vmware-tanzu/velero/blob/main/pkg/backup/remap_crd_version_action.go
![image](https://github.com/vmware-tanzu/velero/assets/83136743/22d952e5-2885-4fdd-bb98-f961bcee80f9)

**Comment by samuelruiz2020** [comment]
I followed similar proc as described  in https://github.com/longhorn/longhorn/discussions/3731 but using csi cinder driver.  I am getting also this error: 
thank you for getting back, I did try it out with velero plugin for csi. Unfortunately it did not backup the volume. Citing:  level=info msg="Waiting for volumesnapshotcontents snapcontent-0e6aa017-b55d-449c-a404-adf716e5a8d1 to have snapshot handle. Retrying in 5s" backup=velero-system/gitlab-backup2 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:182" pluginName=velero-plugin-for-csi"

I am triying to applied patch to VolumeSnapshotClass apiVersion: snapshot.storage.k8s.io/v1beta1 currently my VolumeSnapshotClass  has apiVersion: snapshot.storage.k8s.io/v1, using kubernetes 1.26  but on this kubernetes version the api version v1beta1 has been deprecated.

**Comment by danfengliu** [comment]
Plugin remap_crd_version_action was described as "This plugin is only relevant for CRDs retrieved from the v1 endpoint that were installed via the v1beta1", if the cluster does not support v1beta1 CRD, plugin will exit which means this CRD won't be backed up, so it is as expected against your case.

Also there're errors when taking volumesnapshot by CSI plugin, CRD volumesnapshot is using API version V1 since  velero_plugin_for_csi v0.3.0, so can delete your old CRD VolumeSnapshotClass and  re-install it with apiVersion of snapshot.storage.k8s.io/v1, this is an example on Azure cluster:

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: velero
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: disk.csi.azure.com
deletionPolicy: Delete
```
Could you try this, if there're still errors please let me know.

**Comment by samuelruiz2020** [comment]
My volsnptclass looks like above,  I don't understand, so the does it plugin will work only when the kub cluster supports v1beta1?

**Comment by samuelruiz2020** [comment]
Also i have this : 
time="2023-10-05T07:18:33Z" level=error msg="Timed out awaiting reconciliation of volumesnapshot occne-infra/velero-lb-controller-pvc-hbssn" backup=velero/bak-20231005-065742 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:272" pluginName=velero-plugin-for-csi
time="2023-10-05T07:18:33Z" level=info msg="Deleting Volumesnapshot occne-infra/velero-lb-controller-pvc-hbssn" backup=velero/bak-20231005-065742 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:388" pluginName=velero-plugin-for-csi
time="2023-10-05T07:18:33Z" level=info msg="Deleted volumesnapshot with volumesnapshotContent %s/%soccne-infravelero-lb-controller-pvc-hbssn" backup=velero/bak-20231005-065742 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:407" pluginName=velero-plugin-for-csi
time="2023-10-05T07:18:33Z" level=info msg="1 errors encountered backup up item" backup=velero/bak-20231005-065742 logSource="pkg/backup/backup.go:444" name=occne-lb-controller-server-6f456984cf-29bz6
time="2023-10-05T07:18:33Z" level=error msg="Error backing up item" backup=velero/bak-20231005-065742 error="error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=occne-infra, name=velero-lb-controller-pvc-hbssn): rpc error: code = Unknown desc = timed out waiting for the condition" logSource="pkg/backup/backup.go:448" name=occne-lb-controller-server-6f456984cf-29bz6
time="2023-10-05T07:18:33Z" level=info msg="Backed up 85 items out of an estimated total of 1282 (estimate will change throughout the backup)" backup=velero/bak-20231005-065742 logSource="pkg/backup/backup.go:404" name=occne-lb-controller-server-6f456984cf-29bz6 namespace=occne-infra progress= resource=pods
