### ISSUE TITLE
When executing velero backup delete, object data of ${bucket_name}/kopia/${namespace} cannot be deleted from s3 (minio).

### ISSUE THREAD

**Issue by aki-kamada** [vmware-tanzu/velero#6916]
**What steps did you take and what happened:**
When executing velero backup delete, object data of ${bucket_name}/kopia/${namespace} cannot be deleted from s3 (minio).
I confirmed that it can deleted backup/20231002-1656-kamap2 from s3(minio). This problem happen in kopia side.

Yesterday, I opend new discussion "https://github.com/vmware-tanzu/velero/discussions/6910" and shubham-pampattiwar say that it similler to "https://github.com/vmware-tanzu/velero/issues/6575".
But, I seem to this code is already merged in velero 1.12.0.
So, I opened this ticket.

**What did you expect to happen:**
It should delete the PV/snapshot data under kopia directory from s3(minio).

**The following information will help us better understand what's going on**:
I used new parameter "--snapshot-move-data" for backup.
```
$ velero backup create 20231002-1656-kamap2 --snapshot-move-data --selector velerobackup=enable --namespace kube-storage --include-namespaces kamap2
```
 
When I executed velero backup delete, I confirmed that only the backuprepository remained.
```
$ velero repo get --namespace=kube-storage kamap2-default-kopia-5mmvt
NAME                         STATUS   LAST MAINTENANCE
kamap2-default-kopia-5mmvt   Ready    2023-10-04 10:00:40 +0900 JST
```

```
$ kubectl get backuprepository -n kube-storage kamap2-default-kopia-5mmvt -o yaml | kubectl neat
apiVersion: velero.io/v1
kind: BackupRepository
metadata:
  labels:
    velero.io/repository-type: kopia
    velero.io/storage-location: default
    velero.io/volume-namespace: kamap2
  name: kamap2-default-kopia-5mmvt
  namespace: kube-storage
spec:
  backupStorageLocation: default
  maintenanceFrequency: 1h0m0s
  repositoryType: kopia
  resticIdentifier: s3:https://ike-minio4500.xxx.xxx.net/sri-dev-primera/restic/kamap2
  volumeNamespace: kamap2
```

**Anything else you would like to add:**
- How to reproduce
```
##### I I used new parameter "--snapshot-move-data" for backup.
$ velero backup create 20231002-1656-kamap2 --snapshot-move-data --selector velerobackup=enable --namespace kube-storage --include-namespaces kamap2


##### I deleted backup resource by "20231002-1656-kamap2".
$ velero backupo delete 20231002-1656-kamap2 -n kube-storage

##### I confirmed that it was deleted.
$ velero backup get --namespace=kube-storage
NAME                                               STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
20230929-163700-kongskgr                           Completed   0        0          2023-09-29 16:38:00 +0900 JST   25d       default            velerobackup=enable
20230929-171100-kongskgr                           Completed   0        0          2023-09-29 17:11:45 +0900 JST   25d       default            velerobackup=enable
kong-customplugin-backup                           Completed   0        0          2023-09-25 17:08:37 +0900 JST   21d       default            velerobackup=enable
test-schedule-kamada-202310021818-20231002093043   Completed   0        0          2023-10-02 18:30:43 +0900 JST   29d       default            velerobackup=enable


##### I confirmed that backuprepository resource is existing with the name of "kamap2-default-kopia-5mmvt".
$ velero repo get --namespace=kube-storage
NAME                                    STATUS   LAST MAINTENANCE
kamada-default-kopia-gx92k              Ready    2023-10-03 16:55:40 +0900 JST
kamap2-default-kopia-5mmvt              Ready    2023-10-03 17:00:40 +0900 JST
kong-customplugin-default-kopia-zmgcs   Ready    2023-10-03 17:30:40 +0900 JST



##### I confirmed velero log that it was delete 20231002-1656-kamap2. But I found that some objects show error under the kopia/20231002-1656-kamap2 directory.
time="2023-10-02T08:03:30Z" level=info msg="Removing existing deletion requests for backup" backup=20231002-1656-kamap2 controller=backup-deletion deletebackuprequest=kube-storage/20231002-1656-kamap2-db5j7 logSource="pkg/controller/backup_deletion_controller.go:483"
time="2023-10-02T08:03:30Z" level=info msg="invoking DeleteItemAction plugins" item=20231002-1656-kamap2-7phnl logSource="internal/delete/delete_item_action_handler.go:116" namespace=kube-storage
time="2023-10-02T08:03:30Z" level=info msg="Executing DataUploadDeleteAction" backup=20231002-1656-kamap2 cmd=/velero controller=backup-deletion deletebackuprequest=kube-storage/20231002-1656-kamap2-db5j7 logSource="pkg/datamover/dataupload_delete_action.go:33" pluginName=velero
time="2023-10-02T08:03:31Z" level=info msg="Starting to check for items in namespace" logSource="internal/delete/delete_item_action_handler.go:100" namespace=kamap2
time="2023-10-02T08:03:31Z" level=info msg="invoking DeleteItemAction plugins" item=deployment-mount300 logSource="internal/delete/delete_item_action_handler.go:116" namespace=kamap2
time="2023-10-02T08:03:31Z" level=info msg="invoking DeleteItemAction plugins" item=kamap2 logSource="internal/delete/delete_item_action_handler.go:116" namespace=
time="2023-10-02T08:03:31Z" level=info msg="Starting to check for items in namespace" logSource="internal/delete/delete_item_action_handler.go:100" namespace=kamap2
time="2023-10-02T08:03:31Z" level=info msg="invoking DeleteItemAction plugins" item=my-first-pvc300-velero logSource="internal/delete/delete_item_action_handler.go:116" namespace=kamap2
time="2023-10-02T08:03:31Z" level=info msg="Removing PV snapshots" backup=20231002-1656-kamap2 controller=backup-deletion deletebackuprequest=kube-storage/20231002-1656-kamap2-db5j7 logSource="pkg/controller/backup_deletion_controller.go:293"
time="2023-10-02T08:03:31Z" level=info msg="Removing pod volume snapshots" backup=20231002-1656-kamap2 controller=backup-deletion deletebackuprequest=kube-storage/20231002-1656-kamap2-db5j7 logSource="pkg/controller/backup_deletion_controller.go:318"
time="2023-10-02T08:03:31Z" level=info msg="Removing snapshot data by data mover" backup=20231002-1656-kamap2 controller=backup-deletion deletebackuprequest=kube-storage/20231002-1656-kamap2-db5j7 logSource="pkg/controller/backup_deletion_controller.go:326"
time="2023-10-02T08:03:31Z" level=info msg="Founding existing repo" backupLocation=default logSource="pkg/repository/ensurer.go:85" repositoryType=kopia volumeNamespace=kamap2
time="2023-10-02T08:03:32Z" level=info msg="Deleted snapshot 90c17bf3125d2c1bfd7585beea09f8d8, namespace: kamap2, repo type: kopia" logSource="pkg/controller/backup_deletion_controller.go:555"
time="2023-10-02T08:03:32Z" level=info msg="Removing local datauploads" backup=20231002-1656-kamap2 controller=backup-deletion deletebackuprequest=kube-storage/20231002-1656-kamap2-db5j7 logSource="pkg/controller/backup_deletion_controller.go:333"
time="2023-10-02T08:03:32Z" level=info msg="Removing backup from backup storage" backup=20231002-1656-kamap2 controller=backup-deletion deletebackuprequest=kube-storage/20231002-1656-kamap2-db5j7 logSource="pkg/controller/backup_deletion_controller.go:353"
time="2023-10-02T08:03:33Z" level=info msg="Removing restores" backup=20231002-1656-kamap2 controller=backup-deletion deletebackuprequest=kube-storage/20231002-1656-kamap2-db5j7 logSource="pkg/controller/backup_deletion_controller.go:359"
time="2023-10-02T08:03:33Z" level=info msg="Reconciliation done" backup=20231002-1656-kamap2 controller=backup-deletion deletebackuprequest=kube-storage/20231002-1656-kamap2-db5j7 logSource="pkg/controller/backup_deletion_controller.go:446"


----- snip

time="2023-10-03T08:00:40Z" level=info msg="Running maintenance on backup repository" backupRepo=kube-storage/kamap2-default-kopia-5mmvt logSource="pkg/controller/backup_repository_controller.go:285"
time="2023-10-03T08:00:41Z" level=warning msg="active indexes [xn0_02dcbd0f786db8b67ca39513209f22a2-s20197d85c6bd7e85121-c1 xn0_72efdaeab14f9ea3f08c14d266a0cb49-sb8453497be0c47b5121-c1 xn0_b384096e694dc3db59aee2a7a71e2ba1-s7ddd096a2027a547121-c1] deletion watermark 0001-01-01 00:00:00 +0000 UTC" logModule=kopia/kopia/format logSource="pkg/kopia/kopia_log.go:101" sublevel=error
time="2023-10-03T08:00:41Z" level=warning msg="active indexes [xn0_02dcbd0f786db8b67ca39513209f22a2-s20197d85c6bd7e85121-c1 xn0_72efdaeab14f9ea3f08c14d266a0cb49-sb8453497be0c47b5121-c1 xn0_b384096e694dc3db59aee2a7a71e2ba1-s7ddd096a2027a547121-c1] deletion watermark 0001-01-01 00:00:00 +0000 UTC" logModule=kopia/kopia/format logSource="pkg/kopia/kopia_log.go:101" sublevel=error
time="2023-10-03T08:00:41Z" level=info msg="Running quick maintenance..." logModule=kopia/maintenance logSource="pkg/kopia/kopia_log.go:94"
time="2023-10-03T08:00:41Z" level=info msg="Running quick maintenance..." logModule=kopia/kopia/format logSource="pkg/kopia/kopia_log.go:94"
time="2023-10-03T08:00:41Z" level=warning msg="active indexes [xn0_02dcbd0f786db8b67ca39513209f22a2-s20197d85c6bd7e85121-c1 xn0_72efdaeab14f9ea3f08c14d266a0cb49-sb8453497be0c47b5121-c1 xn0_b384096e694dc3db59aee2a7a71e2ba1-s7ddd096a2027a547121-c1] deletion watermark 0001-01-01 00:00:00 +0000 UTC" logModule=kopia/kopia/format logSource="pkg/kopia/kopia_log.go:101" sublevel=error
time="2023-10-03T08:00:41Z" level=info msg="Finished quick maintenance." logModule=kopia/maintenance logSource="pkg/kopia/kopia_log.go:94"
time="2023-10-03T08:00:41Z" level=info msg="Finished quick maintenance." logModule=kopia/kopia/format logSource="pkg/kopia/kopia_log.go:94"
time="2023-10-03T08:01:37Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=kube-storage/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:152"
time="2023-10-03T08:01:38Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=kube-storage/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:137"
I1003 08:01:56.843944       1 request.go:690] Waited for 1.045119366s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/hnc.x-k8s.io/v1alpha2?timeout=32s
time="2023-10-03T08:02:47Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=kube-storage/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:152"
```

It can't delete kopia's object storage from s3(minio).
![202310031815-cantdelete-kopia-object](https://github.com/vmware-tanzu/velero/assets/67887958/b112d746-0085-44cf-9c75-aeeb5ac8e66b)

It can delete well backup/20231002-1656-kamap2 from s3(minio).
![202310031815can-delete-kamap2backup-resource](https://github.com/vmware-tanzu/velero/assets/67887958/2491312f-69fd-49e4-9d49-d399d69966b9)

**Environment:**

- Velero version (use `1.12.0`): 
- Velero features (use `NOT SET`): 
- Kubernetes version (use `v1.26.6`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `Ubuntu 20.04.1 LTS`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by danfengliu** [comment]
Thanks for report this issue! Let me reproduce it first.

**Comment by aki-kamada** [comment]
Please let me know if you need more information.

**Comment by danfengliu** [comment]
Sorry for the late update, I tried to reproduce this issue on main branch build firstly, and I can not reproduce it as my test criteria, here is some key test steps:

1. Backup my workload with --snapshot-move-data parameter:

```
velero --namespace velero create backup backup-test-2 --wait --include-namespaces kibishii-aws --snapshot-move-data --default-volumes-to-fs-backup=false
Backup request "backup-test-2" submitted successfully.
Waiting for backup to complete. You may safely press ctrl-c to stop waiting - your backup will continue in the background.
.................................................................................................
Backup completed with status: Completed. You may check for more information using the commands `velero backup describe backup-test-2` and `velero backup logs backup-test-2`.
```

2. Connect Kopia repository:

```
KOPIA_PASSWORD=<velero-repo-credential> kopia repository connect s3 --bucket=<my-bucket> \
        --prefix=my-bucket-prefix/kopia/my-workload-namespace/ \
        --access-key=<my-access-key> \
        --secret-access-key=<my-secret-access-key> \
        --region=<my-region> 
```

3. Get Kopia manifest:
As you can see there 2 **type:snapshot** records, because I have 2 PVs in my workload namespace.

```
kopia manifest list
a7ae911733a9092307474756ded0f361        239 2023-10-06 14:02:25 UTC type:maintenance
b2dfa4b9e7e3317a6bca4939b7ea2513        420 2023-10-06 14:02:27 UTC type:policy hostname:default path:snapshot-data-upload-download/kopia/kibishii-aws/kibishii-data-kibishii-deployment-0 policyType:path username:default
5ed143a5b684317f920db5382d0794fa        891 2023-10-06 14:02:27 UTC type:snapshot hostname:default path:snapshot-data-upload-download/kopia/kibishii-aws/kibishii-data-kibishii-deployment-0 snapshot-requester:snapshot-data-upload-download snapshot-uploader:kopia username:default velero.io/async-operation-id:du-0752177a-a6e6-4892-84e0-d1141ddac7d4.4f7336ba-a627-4d87c6b32
591c0617832c15f958b52cf5371ddd48        420 2023-10-06 14:02:55 UTC type:policy hostname:default path:snapshot-data-upload-download/kopia/kibishii-aws/kibishii-data-kibishii-deployment-1 policyType:path username:default
b07d5e85f490cc49b509a29e968fc577        892 2023-10-06 14:02:55 UTC type:snapshot hostname:default path:snapshot-data-upload-download/kopia/kibishii-aws/kibishii-data-kibishii-deployment-1 snapshot-requester:snapshot-data-upload-download snapshot-uploader:kopia username:default velero.io/async-operation-id:du-0752177a-a6e6-4892-84e0-d1141ddac7d4.166c9b08-5b06-47f0bf85a
```


5. Then I deleted backup _backup-test-2_
`velero backup delete backup-test-2 --confirm`

6. Get Kopia manifest again:
There is no snapshot in the output.
```
kopia manifest list
a7ae911733a9092307474756ded0f361        239 2023-10-06 14:02:25 UTC type:maintenance
b2dfa4b9e7e3317a6bca4939b7ea2513        420 2023-10-06 14:02:27 UTC type:policy hostname:default path:snapshot-data-upload-download/kopia/kibishii-aws/kibishii-data-kibishii-deployment-0 policyType:path username:default
591c0617832c15f958b52cf5371ddd48        420 2023-10-06 14:02:55 UTC type:policy hostname:default path:snapshot-data-upload-download/kopia/kibishii-aws/kibishii-data-kibishii-deployment-1 policyType:path username:default
```

> It should delete the PV/snapshot data under kopia directory from s3(minio).

So I'm not quite understand your point as above, do you mean snapshot are not deleted? If yes, which object in the object store you are referring? From my test result, snapshot is deleted, and no long exist in Kopia repo.

**Comment by santimar** [comment]
@danfengliu I think i'm facing the same issue.
Backup and restore with snapshot seems to work as intended, the problem is that after the backup is deleted, I would expect the snapshot files to be deleted as well.

If I look at Minio UI though, I can see that files under `kopia/<namespace>` folder are still there.
Also folder in `backup/<namespace>` is not deleted, but at least the folder is empty.

**Comment by aki-kamada** [comment]
Thank you for your follow comment. @santimar 
I had a Japanese National Holidays. So, I delayed reply.

Please let me know what kind of information do you need. I want to write useful information for this problem.

**Comment by santimar** [comment]
After a deeper investigation i found on https://velero.io/docs/v1.12/backup-reference/#deleting-backups
> `kubectl delete backup <backupName> -n <veleroNamespace>` will delete the backup custom resource only and will not delete any associated data from object/block storage
`velero backup delete <backupName> `will delete the backup resource including all data in object/block storage

So it seems that Object storage should be cleaned as well (if using velero CLI), but from my observation it isn't.

**Comment by Lyndon-Li** [comment]
This is what backup deletion does:
1. Delete the items generated for resource backup, that is under the backups/<backup name> folder in the object store
2. Delete the repo snapshot for volume data backup

For 2, the repo snapshot is a root reference to the volume data backed up. Velero delete this reference only. When the reference is deleted, the backed up data turn to orphan, then the repository delete the data according to its own GC policies.
This mean, the backed up volume data is probably not deleted immediately after Velero backup is deleted. How and when is the data deleted varying from different repositories.
At present, Restic and Kopia are the repositories used by Velero's Unified Repository. For Kopia, the data is deleted by Full Maintenance happening every 24 hours; for Restic, the prune operation is for the data deletion, for Velero the prune happens every 7*24 hours.

Furthermore, even though the backed up volume data is deleted, it doesn't mean you see nothing in the object store. The items in the object store are files managed by repositories, they are not pure data, the repository has its own way to manage the files. What you can see is the object store side is reduced.

**Comment by aki-kamada** [comment]
I uploaded picture today's under kopia directory. It's been 9 days, but it looks like the object storage in the directory under kopia has not been deleted.
Is there something wrong with the kopia settings?

![20231011-kopia-minio-velero](https://github.com/vmware-tanzu/velero/assets/67887958/cf3365cc-daa6-4039-b0c5-d82aa5486db2)

First, I confirmed that "xn0_02dcbd0f786db8b67ca39513209f22a2-s20197d85c6bd7e85121-c1" was created at 10/02. And size is "143.0B", timestamp is "10/02 16:57".
Today, I confirmed that "xn0_02dcbd0f786db8b67ca39513209f22a2-s20197d85c6bd7e85121-c1" still exists at 10/11. And size is "143.0B", timestamp is "10/02 16:57".


velero repo still exists for kopia.
```
$ velero repo get --namespace=kube-storage kamap2-default-kopia-5mmvt
NAME                         STATUS   LAST MAINTENANCE
kamap2-default-kopia-5mmvt   Ready    2023-10-11 13:09:43 +0900 JST
```

I show backuprepository.
```
$ kubectl get backuprepository -n kube-storage kamap2-default-kopia-5mmvt -o yaml | kubectl neat
apiVersion: velero.io/v1
kind: BackupRepository
metadata:
  labels:
    velero.io/repository-type: kopia
    velero.io/storage-location: default
    velero.io/volume-namespace: kamap2
  name: kamap2-default-kopia-5mmvt
  namespace: kube-storage
spec:
  backupStorageLocation: default
  maintenanceFrequency: 1h0m0s
  repositoryType: kopia
  resticIdentifier: s3:https://xxx-minio4500.xxxx.xxx.net/sri-dev-primera/restic/kamap2
```

**Comment by aki-kamada** [comment]
> Velero won't empty the object store, the leftovers should be manually removed.

@Lyndon-Li  Thank you very much. I understood delete design by object storage. 
It's mean, this is not a bug. It's design.

**Comment by jack-nix** [comment]
Hi @Lyndon-Li 
Sorry, i dont get it...

> The deletion of the backup won't delete the backup repository, and even you delete the backup repository CR, Velero won't empty the object store, **the leftovers should be manually removed**.

how can this be a sane design decision? if i delete a backup i would expect that the backup-data which was created through velero (kopia/restic) will be deleted too. How can you possibly manually manage all the redundand stale data that amounts through this approach? how do you even know which blobs you have to delete when you have two different backups of a complete namespace with different apps. How do you know which slice can be deleted without corrupting the other valid backup?

**Comment by Lyndon-Li** [comment]
@jack-nix 

> if i delete a backup i would expect that the backup-data which was created through velero (kopia/restic) will be deleted too.

The backup data can be guaranteed to be deleted, see the above comment https://github.com/vmware-tanzu/velero/issues/6916#issuecomment-1756609294

**Comment by jack-nix** [comment]
@Lyndon-Li
The case is simple. 

1. I make a backup of one namespace.
2. MinIO shows me a "backup" and a "kopia" folder with a bucket size of 50GB.
3. I delete the backup via velero CLI `velero backup delete`.
4. MinIO shows me a only a "kopia" folder and a bucket size of 50GB.

please elaborate on this behaviour and how 
> The backup data can be guaranteed to be deleted

**Comment by Lyndon-Li** [comment]
@jack-nix Please check comment https://github.com/vmware-tanzu/velero/issues/6916#issuecomment-1756609294 which explains relationship of` velero backup delete` and repository data GC.

**Comment by jack-nix** [comment]
@Lyndon-Li 
I think you are referring to this statement especially, right?
> For Kopia, the data is deleted by Full Maintenance happening every 24 hours
I made my test 2 days ago. The backuprepository age is 47 hours and the bucket has still 50GB.

**Comment by Lyndon-Li** [comment]
@jack-nix 
Could you share more info like below:
1. How many backups have you run, and how many have you deleted? One blob of repo data may be shared by more than one backups, so if you delete one backup, the data may still be referred by other backups
2. If all the backup have been deleted, could you connect to your Kopia repo and run `kopia snapshot list --all` and share the output?
3. Could you also share the Velero log bundle since the backup repository was created? We need to check if the maintenance had actually started

**Comment by jack-nix** [comment]
@Lyndon-Li 

1.  I am aware of the mentioned issue and therefore i was waiting hard for 1.12
2. i redeployed velero completely to make sure everything is in 1.12 vanilla state before testing the fix
3. there havent been any other backups before or after - there is only one
4. seems i cant manage to connect via CLI, sorry for that but i can see that there is a "kopia.maintenance" file in the repository which is updated every hour, if that helps.
5. i will send the logs asap

**Comment by aki-kamada** [comment]
@danfengliu @Lyndon-Li 

I ran the command below to confirm that the snapshot data was already deleted and understood what the comment meant.

> The deletion of the backup won't delete the backup repository, and even you delete the backup repository CR, Velero won't empty the object store, the leftovers should be manually removed.

If we need delete, we will delete manually.

But, jack-nix still write comment, I don't still close this ticket. 


```
$ ./kopia repository connect s3 --endpoint xxx-minio4500.xxx.xxx.net --bucket sri-dev-primera --access-key $ACCESS_KEY --secret-access-key $SECRET_KEY --disable-tls-verification --prefix=kopia/kamap2/
Enter password to open repository:

Connected to repository.

NOTICE: Kopia will check for updates on GitHub every 7 days, starting 24 hours after first use.
To disable this behavior, set environment variable KOPIA_CHECK_FOR_UPDATES=false
Alternatively you can remove the file "/home/kamada/.config/kopia/repository.config.update-info.json".
```
```
$ ./kopia manifest list
d9d992e9598792553cc28290567ca697        213 2023-10-02 16:57:49 JST type:maintenance
cba834e90d5f32912f903965822e6376        375 2023-10-02 16:57:51 JST type:policy hostname:default path:snapshot-data-upload-download/kopia/kamap2/my-first-pvc300-velero policyType:path username:default

$ ./kopia snapshot list
```

Regards,
Aki

**Comment by jack-nix** [comment]
thanks @aki-kamada for keeping the issue open. for me it can be closed now since i can verify that the deletion of files does work. even if the behaviour and timing of performed actions is somewhat unexpected and still not 100% clear to me. 

big thanks also to @Lyndon-Li for explaining and clarifying things.

**Comment by kaovilai** [comment]
@nemanja1209 did you wait sufficient time for velero to [run maintenance](https://github.com/vmware-tanzu/velero/issues/6916#:~:text=At%20present%2C%20Restic%20and%20Kopia%20are%20the%20repositories%20used%20by%20Velero%27s%20Unified%20Repository.%20For%20Kopia%2C%20the%20data%20is%20deleted%20by%20Full%20Maintenance%20happening%20every%2024%20hours%3B%20for%20Restic%2C%20the%20prune%20operation%20is%20for%20the%20data%20deletion%2C%20for%20Velero%20the%20prune%20happens%20every%207*24%20hours%20(by%20default).)?

**Comment by nemanja1209** [comment]
@kaovilai 
I think that today is 5th day since the first backup.
Here is some additional information about my config:

**Velero server version**: 1.13

**Backup storage location**:
Spec:
  Access Mode:  ReadWrite
  Config:
    Insecure Skip TLS Verify:  true
    Region:                    minio
    s3ForcePathStyle:          true
    s3Url:                     https://my.domain.com:9000
  Default:                     true
  Object Storage:
    Bucket:  velero
  Provider:  aws

**Backup storage repository**:

Spec:
  Backup Storage Location:  default
  Maintenance Frequency:    1h0m0s
  Repository Type:          kopia
  Restic Identifier:        s3:https://my.domain.com:9000/velero/restic/prometheus
  Volume Namespace:         prometheus


There is a backup schedule job:
NAME              STATUS    CREATED                          SCHEDULE      BACKUP TTL   LAST BACKUP   SELECTOR   PAUSED
bckp-prometheus   Enabled   2024-04-15 15:09:14 +0200 CEST   0 */6 * * *   7h0m0s       2h ago        <none>     false

It creates backup every 6 hours and TTL is 7 hours. That means that at some point I have 2 backups (for 1 hour) and after that period only one is left.

Output of **velero backup get** is good, there is only one backup (or two if you execute the command one hour after creation of the last backup):

NAME                             STATUS      ERRORS   WARNINGS   CREATED                          EXPIRES   STORAGE LOCATION   SELECTOR
bckp-prometheus-20240419060013   Completed   0        0          2024-04-19 08:00:31 +0200 CEST   4h        default            <none>

This PVC is big around 30GB.
At this time, after 5 days, Minio shows around 58GB used space and when I enter the bucket, there are files from the first backup.

**Comment by nemanja1209** [comment]
One additional observation:
Currently, there are about 3500 files in the bucket. Maybe the more than a half are from the first backup. It seems that the first backup lasted for about 15min, because the first file is created at 20:00 and the last one at 20:16.

For this 5 days, there were executed around 19 backups (every 6 hours) and each one didn't last for more than 2min. (difference between first and last created file). These files are also still present in the bucket. 

So, the rest 18 backups hold half of the files in the bucket and first one backup other half (rough estimation). It is like the bucket do some kind of versioning (incremental backup). For this bucket, object locking (versioning) is disabled.

**Comment by Lyndon-Li** [comment]
@nemanja1209 
From the first glance, I think @sseago has mentioned the reason. If you have further doubt, please open a new issue since the current issue has been closed as completion.

**Comment by nemanja1209** [comment]
I got the point, but when I disable schedule, delete all backups and wait for a few days, Kopia snapshots are still there.
