### ISSUE TITLE
Regression: Disable blob signing initialization for non SA file results in GCP Workload Identity not working

### ISSUE THREAD

**Issue by Langleu** [vmware-tanzu/velero#6921]
**What steps did you take and what happened:**

I'm upgrading from `velero` 1.11.1 to 1.12.0 and `velero-plugin-for-gcp` from 1.7.1 to 1.8.0.
The GCP plugin introduced this change - https://github.com/vmware-tanzu/velero-plugin-for-gcp/pull/142 - which results in the workload identity injected SA token to not be used for URL signing due to which a lot of velero features are not working anymore including snapshot backups, logs, describing, ....
Removing the related code from the PR and running a custom image fixes the issue as currently the Workload Identity SA is detected as `external_account` and URL signing is not even attempted.

Error:
```
time="2023-10-05T09:37:42Z" level=warning msg="fail to get Backup metadata file's download URL {BackupLog test4}, retry later: rpc error: code = Unknown desc = cannot sign blob using non SA file credentials" controller=download-request downloadRequest=velero-dev/test4-cb2a5ec8-9a29-4b5d-9de2-2cea227abcc0 logSource="pkg/controller/download_request_controller.go:206"
```

**What did you expect to happen:**

I expect to be able to use Workload Identities as I was able to in 1.11.1 and also in 1.12.0 with modifications.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Don't expect too much except timeouts as the URL can't be signed since that step is skipped.
[bundle-2023-10-05-13-27-29.tar.gz](https://github.com/vmware-tanzu/velero/files/12817820/bundle-2023-10-05-13-27-29.tar.gz)

**Anything else you would like to add:**

Looks to me like a regression in the plugin and wasn't ever tested against workload identities.

**Environment:**

- Velero version (use `velero version`): 1.12.0
- Velero features (use `velero client config get features`): NOT SET
- Kubernetes version (use `kubectl version`): v1.27.3-gke.1700 (server) - v1.28.2 (client)
- Kubernetes installer & version: v1.27.3-gke.1700
- Cloud provider or hardware configuration: GCP (GKE)
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kaovilai** [comment]
> Keep in mind that [Workforce Identity Federation Users cannot generate signed URLs](https://cloud.google.com/iam/docs/federated-identity-supported-services#:~:text=workforce%20identity%20federation%20users%20cannot%20generate%20signed%20URLs.). This means, if you are using Workforce Identity Federation, you will not be able to run `velero backup logs`, `velero backup download`, `velero backup describe` and `velero restore describe`.

This is coming from Google cloud documentation.

Can you confirm that the statement is false?

**Comment by kaovilai** [comment]
Although anyone can use existing signed URLs , workforce identity federation users cannot generate signed URLs.

**Comment by kaovilai** [comment]
It didn't work and panicked during initFromKeyFile because `google.JWTConfigFromJSON()` doesn't work with external_account wif credentials.

Can you confirm that initFromKeyFile https://github.com/vmware-tanzu/velero-plugin-for-gcp/pull/142/files#diff-bc262f262dbdc4faf49f17fca5c228c9b4121cb64cc2f327e0d82bd562703bc1R171
Worked with your external_account.

Or are you saying it switched out to external_account during run time so it didn't panic initialization?

**Comment by kaovilai** [comment]
I'd be happy to put a fix up if you can confirm your secret file content is an external_account that has some fields different from wif credentials in the test case here

https://github.com/vmware-tanzu/velero-plugin-for-gcp/pull/142/files#diff-9149b03a8762611be8a6da3610141ac9fe696bb5ab41027907dd875367e88cfdR190

Please paste how your cred looks redacting some info ofc

**Comment by Langleu** [comment]
using the image without the PR additions, it does not panic with a typical Workload Identity setup of having a trust relationship between k8s sa and GCP IAM sa.
I can create backups, including snapshots, look at logs, describe backups, etc.

With the change I run into `cannot sign blob using non SA file credentials`, even though everything works and my assumption is that the setup is treated as `external_account` since workload identities don't result in a typical key file but injects a JWT and the rest is probably SDK implementation of signing the URLs etc.

**Comment by Langleu** [comment]
as mentioned workload identities do not result in this key file that you typically get by exporting a key from your GCP IAM.
You attach an annotation to your SA and the rest is mutating webhook magic of injecting a signed JWT.
Typically the Google SDK picks the info up from the environment variables and can deal with it.

**Comment by kaovilai** [comment]
Not sure how it worked for you but without my change bsl isn't available.
```
time="2023-06-02T19:23:07Z" level=error msg="Current BackupStorageLocations available/unavailable/unknown: 0/1/0, BackupStorageLocation \"wif-test-1\" is unavailable: rpc error: code = Unknown desc = error parsing credentials file; should be JSON: google: read JWT from JSON credentials: 'type' field is \"external_account\" (expected \"service_account\"))" controller=backup-storage-location logSource="/remote-source/velero/app/pkg/controller/backup_storage_location_controller.go:171"
```

**Comment by kaovilai** [comment]
Ok so "key fileless" during init with Google sdk magic parsing some other env..

Would be awesome if you could help me figure out how to detect such env should attempt to sign.. or perhaps always attempt to sign.. I'll have to check if that function was depending on the init function.

**Comment by Langleu** [comment]
I have to say that AWS equivalent called `IAM Roles for Service Accounts` is much easier to detect ... never thought I would ever say that.
For GKE, there is not really a good indicator ... just checked the mutated pod and there's no way to figure it out.
Maybe there's a function?
Opposed to AWS they're not using any envs to configure it.

The SDK is making use of this --> https://cloud.google.com/docs/authentication/application-default-credentials

**Comment by Langleu** [comment]
[In this line](https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/343aa79ddccb2eb06127828f9950337fc83e4aa6/velero-plugin-for-gcp/object_store.go#L155) a new client is created and as they state in the [docs](https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/343aa79ddccb2eb06127828f9950337fc83e4aa6/velero-plugin-for-gcp/object_store.go#L155).
```
By default, each API will use [Google Application Default Credentials](https://developers.google.com/identity/protocols/application-default-credentials) for authorization credentials used in calling the API endpoints. This will allow your application to run in many environments without requiring explicit configuration.
```

That's why the change broke workload identities since you can easily detect the exported SA keyfile but not this whole implicit access.

Why do we have to support `identity federation` anyway or what was the initial PR trying to fix?
As stated in the [docs](https://cloud.google.com/docs/authentication#workload-workforce).
Google uses the terms workload for programmatic access and workforce for user access.

So configuring velero with identity federation should not be done by anyone in the first place.

**Comment by kaovilai** [comment]
For more context on how my team support WIF creds with velero as a workload on OpenShift
https://github.com/openshift/cloud-credential-operator/blob/master/docs/gcp_workload_identity.md

**Comment by Langleu** [comment]
But that whole topic is about `workload identities`, which makes sense since it's programmatic access.
But my assumption is that your customer recoined it to use some externally managed "users/machine-accounts" due to which it becomes `workforce identity federation`.
The docs described approach does have access to signing URLs as it's the typical workload identity procedure.

any chance we can get it fixed? Currently keeping us from upgrading.

Maybe there's a way to detect it, otherwise the default could be to sign and if it fails set a flag, so you wouldn't have to care about the whole auth topic and catch the one exception that's `workforce identity federation`.

I'd also suggest adding a disclaimer in the docs of the plugin to not use it as it looks like a workaround that shouldn't be there in the first place.

**Comment by kaovilai** [comment]
can you paste BSL?
Just wanna confirm my assumptions. PR is up.

**Comment by Langleu** [comment]
can confirm the PR fixes the issue. Thanks 🚀 
Just tried out a backup creation, backup describe, and logs. No errors, snapshot also worked.

BSL
```
NAME      PROVIDER   BUCKET/PREFIX                     PHASE       LAST VALIDATED                   ACCESS MODE   DEFAULT
default   gcp        velero-gcp-project-dev-backups   Available   2023-10-05 16:30:40 +0200 CEST   ReadWrite     true
```

**Comment by kaovilai** [comment]
Cool!

**Comment by kaovilai** [comment]
Updating docs

**Comment by maxdanilov** [comment]
when can one expect this fix to be released?

**Comment by kaovilai** [comment]
Per label:
> Lyndon-Li added the [target/1.12.1](https://github.com/vmware-tanzu/velero/labels/target%2F1.12.1) label [last week](https://github.com/vmware-tanzu/velero/issues/6921#event-10611420693)

**Comment by kaovilai** [comment]
When cherrypick PR is merged https://github.com/vmware-tanzu/velero-plugin-for-gcp/pull/159 and a new plugin release is made?
