### ISSUE TITLE
Velero backup getting failed and pushed partial data

### ISSUE THREAD

**Issue by akshayv3rma** [vmware-tanzu/velero#6929]
**What steps did you take and what happened:**

velero not able to discover the custom.metrics.k8s.io/v1beta1

[root@innm4ltkgbts193 ~]# velero backup logs tkg-fdr-app01 | grep -i error
time="2023-10-09T07:06:08Z" level=warning msg="Failed to discover group: custom.metrics.k8s.io/v1beta1" backup=velero/tkg-fdr-app01 cmd=/velero error="the server is currently unable to handle the request" logSource="pkg/discovery/helper.go:220" pluginName=velero
time="2023-10-09T07:06:53Z" level=warning msg="Failed to discover group: custom.metrics.k8s.io/v1beta1" backup=velero/tkg-fdr-app01 cmd=/velero error="the server is currently unable to handle the request" logSource="pkg/discovery/helper.go:220" pluginName=velero

**What did you expect to happen:**
Velero to do proper backups without any errors

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`

er.go:223"
time="2023-10-09T07:18:56Z" level=error msg="Error updating download request" controller=download-request downloadRequest=velero/tkg-fdr-app01-bd33f66a-4025-43cf-a99a-21df8285320e error="downloadrequests.velero.io \"tkg-fdr-app01-bd33f66a-4025-43cf-a99a-21df8285320e\" not found" logSource="pkg/controller/download_request_controller.go:74"
time="2023-10-09T07:19:32Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:131"
time="2023-10-09T07:19:32Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:116"
time="2023-10-09T07:20:32Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:131"
time="2023-10-09T07:20:32Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:116"
time="2023-10-09T07:21:32Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:131"
time="2023-10-09T07:21:32Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:116"
time="2023-10-09T07:22:32Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:131"
time="2023-10-09T07:22:33Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:116"
time="2023-10-09T07:22:53Z" level=warning msg="Failed to discover group: custom.metrics.k8s.io/v1beta1" error="the server is currently unable to handle the request" logSource="pkg/discovery/helper.go:220"

- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`

- `velero backup logs <backupname>`

time="2023-10-09T07:06:08Z" level=warning msg="Failed to discover group: custom.metrics.k8s.io/v1beta1" backup=velero/tkg-fdr-app01 cmd=/velero error="the server is currently unable to handle the request" logSource="pkg/discovery/helper.go:220" pluginName=velero
time="2023-10-09T07:06:53Z" level=warning msg="Failed to discover group: custom.metrics.k8s.io/v1beta1" backup=velero/tkg-fdr-app01 cmd=/velero error="the server is currently unable to handle the request" logSource="pkg/discovery/helper.go:220" pluginName=velero

- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`

- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 

Client:
        Version: v1.9.5_vmware.1
        Git commit: 2b5281f38aad2527f95b55644b20fb169a6702a7-dirty
Server:
        Version: v1.9.5_vmware.1

- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 

Kustomize Version: v4.5.7

- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by allenxu404** [comment]
It looks like there was some issue with the resource `custom.metrics.k8s.io/v1beta1` that was preventing the cluster API server from processing related requests correctly. Please check if this custom resource functions properly.
