### ISSUE TITLE
TTL countdown starts before the backup gets completed

### ISSUE THREAD

**Issue by stillalearner** [vmware-tanzu/velero#6932]
**What steps did you take and what happened:**

1. Created the DPA with gc frequency set to 1 minute, so that it keeps checking for expired backups every minute.

2. Deployed 2 namespaces, 1 django and other mysql application to backup.

3. Created a single backup for the 2 namespaces, with TTL set to 1 minute as well.

4. Backup finishes in around 100 seconds, but after another 20 seconds, it got deleted.

**What did you expect to happen:**

TTL countdown should start after the backup completion. So it should survive at least 1 minute after completion.

**Anything else you would like to add:**

DPA:

````
apiVersion: v1
items:
- apiVersion: oadp.openshift.io/v1alpha1
  kind: DataProtectionApplication
  metadata:
    creationTimestamp: "2023-10-09T10:50:16Z"
    generation: 2
    name: ts-dpa
    namespace: openshift-adp
    resourceVersion: "143427"
    uid: 94b183b7-002c-4b65-8d3f-d5f7e65bb819
  spec:
    backupLocations:
    - velero:
        credential:
          key: cloud
          name: cloud-credentials-gcp
        default: true
        objectStorage:
          bucket: oadpbucket238243
          prefix: velero
        provider: gcp
    configuration:
      nodeAgent:
        enable: true
        uploaderType: restic
      velero:
        args:
          garbage-collection-frequency: 60000000000
        defaultPlugins:
        - openshift
        - csi
        - gcp
  status:
    conditions:
    - lastTransitionTime: "2023-10-09T10:50:16Z"
      message: Reconcile complete
      reason: Complete
      status: "True"
      type: Reconciled
kind: List
```
`

`$ cat backup.yaml 
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup2
  namespace: openshift-adp
spec:
  hooks: {}
  includedNamespaces:
  - django
  - mysql
  defaultVolumesToFsBackup: true
  storageLocation: ts-dpa-1
  ttl: 1m0s
```
`

**Environment:**
Velero 1.12


**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment]
I actually think that the current behavior is better as-is.  Since TTL is generally on the order of weeks/months, I don't know that the distinction of from backup start vs. from backup completion matters all that much in the real world, but I'd be concerned that changing the behavior that's been in place for years might be more confusing than leaving it as-is.

Also, if the overall point of the policy is to discard data more than x days/weeks/etc old, then backup start time is probably a better reference point, since at least some of the data in the backup will be as old as backup start rather than backup completion.
