### ISSUE TITLE
Velero v1.12.0 has no auth provider found for name "oidc"

### ISSUE THREAD

**Issue by ksudarsh00** [vmware-tanzu/velero#6933]
**What steps did you take and what happened:**

Velero server version: v1.12.0
Velero client version: v1.12.0
Velero client was not able to connect to Velero server when the auth provider is "oidc"

Ran velero --version command  and it threw an error **"An error occurred: no Auth Provider found for name "oidc""**

Velero v1.11.* are working fine when the auth provider is oidc but not working in v1.12.0

Upon debuggging I found out that pkg/client/auth_providers.go is present in v1.11.* but is removed in v1.12.0
v1.11.1 : https://github.com/vmware-tanzu/velero/blob/v1.11.1/pkg/client/auth_providers.go
v1.12.0: https://github.com/vmware-tanzu/velero/tree/v1.12.0/pkg/client

**What did you expect to happen:**

Velero client should be able to connect to Velero server and should display the client and server versions 

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by draghuram** [comment]
See the related thread in Slack: https://kubernetes.slack.com/archives/C6VCGP4MT/p1695924642015059

**Comment by draghuram** [comment]
We will take a look at this issue at CloudCasa. Please assign to @0x113.

**Comment by antrema** [comment]
One solution that work for me: 
Add the following import '_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"' in the appropriate section to the file  "pkg/client/client.go"
```
import (
	"fmt"
	"runtime"

	"github.com/pkg/errors"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"

	"github.com/vmware-tanzu/velero/pkg/buildinfo"
	_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
)
```
And rebuild the CLI:
```
go build -o bin/velero cmd/velero/velero.go
```

**Comment by ksudarsh00** [comment]
This import is present in v1.11.* in auth_providers.go file but is removed in v1.12.0 any reason for that? and when will this change be released.?

**Comment by ksudarsh00** [comment]
Great!!

**Comment by blackpiglet** [comment]
Sorry for the inconvenience, and thanks for reporting and fixing this issue.

The needed file was deleted during fixing revive linter errors.
It was used to resolve the [blank import](https://revive.run/r#blank-imports) warning reported by the revive.
I thought that file was not used, so deleted it.

```
import (
	_ "k8s.io/client-go/plugin/pkg/client/auth/azure"
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
	_ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
)
```
