### ISSUE TITLE
Velero backup create - Restic responds with error: fork/exec /usr/bin/restic: permission denied stderr:

### ISSUE THREAD

**Issue by dbanasia** [vmware-tanzu/velero#6942]
**What steps did you take and what happened:**
I've installed Vellero and wanted to test a backup of simple Nginx app with persistent volume. Unfortunately, the backup failed:

Command to install Vellero:

velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.8.0 \
    --bucket velero \
    --secret-file ./credentials-velero \
    --use-volume-snapshots=true \
	--use-node-agent --uploader-type=restic \
	--snapshot-location-config region=minio \
	--default-volumes-to-fs-backup \
    --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://X.X.X.X:9000
	
Velelero version:

velero version
Client:
        Version: v1.12.0
        Git commit: 7112c62e493b0f7570f0e7cd2088f8cad968db99
Server:
        Version: v1.12.0

Kubernetes version:

kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12", GitCommit:"696a9fdd2a58340e61e0d815c5769d266fca0802", GitTreeState:"clean", BuildDate:"2022-04-13T19:07:00Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12", GitCommit:"696a9fdd2a58340e61e0d815c5769d266fca0802", GitTreeState:"clean", BuildDate:"2022-04-13T19:01:10Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
[root@waw-ncs01bmcbs6-mswe1-0 ~ (Active)]#

Errors:
  Velero:    name: /nginx-test error: /pod volume backup failed: data path backup failed: error running restic backup command restic backup --repo=s3:http://X.X.X.X:9000/velero/restic/test-nginx --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic . --tag=pvc-uid=8875eb08-f9f4-4296-bfc9-9bda6a189e6d --tag=volume=mystorage --tag=backup=my-backup-test-nginx-namespace-ncs01-cbs6 --tag=backup-uid=23c3d617-9096-4417-9ee8-c50e7700b805 --tag=ns=test-nginx --tag=pod=nginx-test --tag=pod-uid=77642a5f-fad3-495e-8a83-64e439461f20 --host=velero --json with error: fork/exec /usr/bin/restic: permission denied stderr:

I've attached the debug log.
[bundle-2023-10-11-12-40-34.tar.gz](https://github.com/vmware-tanzu/velero/files/12869951/bundle-2023-10-11-12-40-34.tar.gz)

Could you please help me with this issue?

**Comment by allenxu404** [comment]
I saw a similar issue:https://github.com/vmware-tanzu/velero/issues/1786, where it was eventually resolved by adding `securityContext: privileged: true` to velero deployment and node agent daemonset. 

Can you try that solution and see if it address the error you're seeing?

**Comment by dbanasia** [comment]
I found the issue and it is SELinux which is guilty one. I've added a proper policy to daemonset and it is working, but the problem is that every PVC has a different policy.

securityContext:
  seLinuxOptions:
    level: "s0:c223,c783"

[root@cluster]# ll -Z /var/lib/kubelet/pods/3b16266c-b8ef-4f1c-a0de-266ff6ecdd6b/volumes/kubernetes.io~csi/pvc-af477a3c-0dcc-45ab-b24b-dcb4f7924bf5/mount
-rw-r--r--. root root system_u:object_r:container_file_t:s0:c223,c783 index.html
drwx------. root root system_u:object_r:container_file_t:s0:c223,c783 lost+found
[root@cluster]# ll -Z /var/lib/kubelet/pods/2301afdf-16d8-41ef-b4a4-3e405fb9506f/volumes/kubernetes.io~csi/pvc-fc4e4d86-5551-42a3-b343-d3851fa8abef/mount
drwxrws---. root  10000 system_u:object_r:container_file_t:s0:c163,c883 lost+found
drwxrws---. 10000 10000 system_u:object_r:container_file_t:s0:c163,c883 mnesia

Regards,

Daniel
