### ISSUE TITLE
On restore, object can fail to create from AlreadyExists and fail to Get with IsNotFound without retry

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#6952]
**Describe the problem/challenge you have**
A custom resource can take some time from create to become Get-able due to some processing inside an apiserver resulting in failed restore for the object and a log like so
```
time="2023-09-15T17:51:09Z" level=error msg="Error retrieving cluster version of isim-dev-restored/postgresql:13-el9: imagestreamtags.image.openshift.io \"postgresql:13-el9\" not found" logSource="/remote-source/velero/app/pkg/res
tore/restore.go:1285" restore=velero/1a885c89-d880-5472-ac25-04e823668177-2023-09-15-10-51-25-isim-dev-restored
```
Example case: https://github.com/openshift/openshift-velero-plugin/issues/204
 <details>
<summary>Problem analysis</summary>

```go
// Get retrieves an image that has been tagged by stream and tag. `id` is of the format <stream name>:<tag>.
func (r *REST) Get(ctx context.Context, id string, options *metav1.GetOptions) (runtime.Object, error) {
...
	image, err := r.imageFor(ctx, tag, imageStream) // <-- this is returning an IsNotFoundError
	if err != nil {
		return nil, err
	}
...}
```
https://github.com/openshift/openshift-apiserver/blob/9573998170f3bb7ae7e946c11b7e9fc414120df4/pkg/image/apiserver/registry/imagestreamtag/rest.go#L127C1-L145C2

which calls
```
// imageFor retrieves the most recent image for a tag in a given imageStreem.
func (r *REST) imageFor(ctx context.Context, tag string, imageStream *imageapi.ImageStream) (*imageapi.Image, error) {
	event := internalimageutil.LatestTaggedImage(imageStream, tag)
	if event == nil || len(event.Image) == 0 {
		return nil, kapierrors.NewNotFound(imagegroup.Resource("imagestreamtags"), imageutil.JoinImageStreamTag(imageStream.Name, tag)) // <-- this is where error originated
	}

	return r.imageRegistry.GetImage(ctx, event.Image, &metav1.GetOptions{})
}
```
https://github.com/openshift/openshift-apiserver/blob/9573998170f3bb7ae7e946c11b7e9fc414120df4/pkg/image/apiserver/registry/imagestreamtag/rest.go#L439C1-L447C2

[which is caused by TagEvent not yet existing](https://github.com/openshift/openshift-apiserver/blob/9573998170f3bb7ae7e946c11b7e9fc414120df4/pkg/image/apiserver/internalimageutil/helpers.go#L285C1-L287C47) due to network speeds etc in processing the imagestreamtag creation
```go
// LatestTaggedImage returns the most recent TagEvent for the specified image
// repository and tag. Will resolve lookups for the empty tag. Returns nil
// if tag isn't present in stream.status.tags.
```
</details>

While this is an OpenShift apiserver specific example, the problem can be described and resolved generically and may apply in other environments.

**Describe the solution you'd like**

A few retries would resolve this issue.
Implementation: https://github.com/vmware-tanzu/velero/pull/6949

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
> While this is an OpenShift apiserver specific example, the problem can be described and resolved generically and may apply in other environments.

Is it really generic?  Seems it's a flaw in the implementation of openshift?  i.e. if a resource is created and returned a 2xx it should be get-able?

**Comment by sseago** [comment]
FYI, we are also seeing this same issue with openshift role bindings.

**Comment by sseago** [comment]
@kaovilai @reasonerjt Another possibility here is we don't retry, but instead of logging this as an error, we just log a warning when this happens. The scenario is "can't create, already exists, but we also can't Get yet" -- I think a warning is appropriate, since  the resource wouldn't be created anyway if Get succeeded. The only thing we lose vs. retry is that we won't be able to apply an "Update" existing resource policy, but for the particular types we've seen this with, "Update" doesn't really make much sense here anyway.

**Comment by kaovilai** [comment]
FYI PR to warn instead of error as an alternative approach to erroring out
https://github.com/vmware-tanzu/velero/pull/7004
