### ISSUE TITLE
velero_backup_last_status: Expose partial failures/warnings

### ISSUE THREAD

**Issue by jkroepke** [vmware-tanzu/velero#6957]
**Describe the problem/challenge you have**
Currently, velero_backup_last_status indicated if a backup is failed or not.

**Describe the solution you'd like**
It would be nice to separate the status between failues, partial failures, and warnings. Based on the status, I have the ability to generate alerts more precisely.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.12
- Kubernetes version (use `kubectl version`): 1.26
- Kubernetes installer & version: AKS
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by yanggangtony** [comment]
Now this metrics ```velero_backup_last_status``` has included in others system for monitor.
Change the value of it meaning , maybe break out the logic with before ..

**Comment by jkroepke** [comment]
@yanggangtony Could you please explain, why?

Add new values (2 = partial; 3 = warning) to that metric without changes existing mapping (0 = fail; 1 = success) is be not a breaking change.

**Comment by yanggangtony** [comment]
0=fail now represent  besides success conditions.  you means ```2= partial failure``` , now included into the 0.
So users will not read the 2, 3 to do the conditions logics.

**Comment by jkroepke** [comment]
And what about warnings?

**Comment by yanggangtony** [comment]
if you means warning represent the 'FailedValidation' , this also included into values=0.

Current the Backup CRD 's status is like this 
```
// BackupPhase is a string representation of the lifecycle phase
// of a Velero backup.
// +kubebuilder:validation:Enum=New;FailedValidation;InProgress;WaitingForPluginOperations;WaitingForPluginOperationsPartiallyFailed;Finalizing;FinalizingPartiallyFailed;Completed;PartiallyFailed;Failed;Deleting
type BackupPhase string
```
, there is not a warning item.

**Comment by jkroepke** [comment]
Thanks for the clarification!
