### ISSUE TITLE
[Feature request] Add a flag to persist snapshots with --snapshot-move-data param

### ISSUE THREAD

**Issue by al-cheb** [vmware-tanzu/velero#6969]
**Describe the problem/challenge you have**
Add a flag to persist snapshots with `--snapshot-move-data` param. In our case we would like to have data backup on S3 to fast recovery a single item and allow to revert snapshots as well.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by kaovilai** [comment]
The only benefit here would be on restore perhaps on the same cluster you don't have to go download from s3 again.

**Comment by al-cheb** [comment]
> The only benefit here would be on restore perhaps on the same cluster you don't have to go download from s3 again.

Agreed, for a large PV with lots of small files (2M+), it's much faster to roll back to a snapshot when waiting to copy from S3.

**Comment by Lyndon-Li** [comment]
There is an existing issue for this #6240. The plan is we will create a design in 1.13 and implement in a future release.

**Comment by Lyndon-Li** [comment]
@al-cheb Please review the original issue and the coming design and leave comments if any of your requirements are not covered.

**Comment by al-cheb** [comment]
> @al-cheb Please review the original issue and the coming design and leave comments if any of your requirements are not covered.

Thank you.That looks good to me. Close in scope of the https://github.com/vmware-tanzu/velero/issues/6240
