### ISSUE TITLE
Create Makefile with podman

### ISSUE THREAD

**Issue by Ladrillo84** [vmware-tanzu/velero#6973]
Hello! 

I would like to propose you an idea to customize the image of Velero. It would be very appropriate to create a Makefile with podman since in the future Docker will be paid and will not be open source.

Thank you!!!

Best regards.

**Comment by mateusoliveira43** [comment]
There is this PR https://github.com/vmware-tanzu/velero/pull/6556 if you want to look for inspiration

**Comment by kaovilai** [comment]
https://github.com/openshift/velero/blob/konveyor-dev/Dockerfile.ubi
We have a dockerfile build able with podman here.

Also note that docker community edition exists and is available for use for free on Linux.

https://forums.docker.com/t/license-to-use-docker-community-edition/114840/2

Only docker desktop are affected by the change.

**Comment by reasonerjt** [comment]
I believe it's safe for us to continue using the docker community edition to release velero.

@Ladrillo84 could you paste the link of the news about `Docker will be paid and will not be open source.` ?

**Comment by Ladrillo84** [comment]
Hello!

Sorry for the inconvenience but it was my mistake, I thought it would be everything related to Docker both desktop and CLI but it will only affect desktop Docker.
