### ISSUE TITLE
release-1.12: Non default s3 credential profiles do not work on Unified Repository Provider (kopia) - after #6598

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#6998]
clone of https://github.com/vmware-tanzu/velero/issues/6996 for release-1.12 branch

**Comment by Lyndon-Li** [comment]
I am adding this issue to 1.12.2 since we cannot catch up with 1.12.1's schedule.

**Comment by kaovilai** [comment]
closed via https://github.com/vmware-tanzu/velero/pull/6997
