### ISSUE TITLE
backup item action changes to objects aren't being persisted in the backup tarball

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero#702]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

1. build sample plugin container image
2. `ark plugin add <my-repo>/ark-plugin-example:latest`
3. `ark backup create foo`

The backed-up items should be annotated, per https://github.com/heptio/ark-plugin-example/blob/master/ark-backupitemaction-log-and-annotate/myplugin.go#L53. They are not.

It looks like https://github.com/heptio/ark/blob/82f1cd87dcc70965ef093872daaca92685dda90c/pkg/backup/item_backupper.go#L312 is to blame, as a pointer is being updated to point to a new location within a helper func, but this only lasts for the scope of the function, so the parent function which actually writes the item to the backup still has a pointer to the original obj.

**Comment by skriss** [comment]
cc @nrb @carlisia @Evesy

**Comment by nrb** [comment]
Sounds reasonable to me.
