### ISSUE TITLE
How to simply check the continuity of schedule backup?

### ISSUE THREAD

**Issue by lizhifengones** [vmware-tanzu/velero#7021]
I deliberately deleted the first backup and found that it would cause the recovery to fail. 
```sh
time="2023-10-26T02:43:16Z" level=error msg="Cluster resource restore error: error executing PVAction for persistentvolumes/pvc-e85334fb-0fcb-4f25-a96f-1dbba4f93f92: rpc error: code = Unknown desc = Failed to restore volume: failed to restor snapshot=inc-backup-20231026015510-20231026000056: failed to restore.. status {Failed}" logSource="pkg/controller/restore_controller.go:552" restore=velero/inc-backup-20231026015510-20231026023056-20231026024215
```
How can I **check** in advance whether the backup package of the schedule continues to exist?

**Comment by qiuming-best** [comment]
I think it's not the action you deleting the former backup that led to the entire backup data being incomplete.

could you show me more details for the error by uploading more logs?

**Comment by lizhifengones** [comment]
> I think it's not the action you deleting the former backup that led to the entire backup data being incomplete.
> 
> could you show me more details for the error by uploading more logs?

Sorry, I didn't save the log. Because of this problem (it may also be caused by my operation), my containerized storage openebs+nfs crashed. (openebs(rwo)+nfs(rwx)+minio+velero+openebs/velero-plugin)，

It wasn't until I uninstalled all components that I realized that restarting the server class might solve the nfs crash problem.

I could try the operation again, but my original intention is to describe it as such, such as a `dry-run` way or a real `check` ability

**Comment by qiuming-best** [comment]
you can describe the backup in detail with the command `velero describe backup $backupName --details` that will show you all resources backed up. and you can check if the backup resources are complete to ensure the normal operation of your service.

**Comment by lizhifengones** [comment]
My schedule has been backed up many times
```sh
inc-backup-20231028015510-20231027200011 Completed 0 0 2023-10-27 20:00:12 +0000 UTC 18d default-bakcup-storage-location openebs.io/velero.backup=true
inc-backup-20231028015510-20231027193011 Completed 0 0 2023-10-27 19:30:11 +0000 UTC 18d default-bakcup-storage-location openebs.io/velero.backup=true
inc-backup-20231028015510-20231027190011 Completed 0 0 2023-10-27 19:00:11 +0000 UTC 18d default-bakcup-storage-location openebs.io/velero.backup=true
inc-backup-20231028015510-20231027183011 Completed 0 0 2023-10-27 18:30:11 +0000 UTC 18d default-bakcup-storage-location openebs.io/velero.backup=true
inc-backup-20231028015510-20231027180011 Completed 0 0 2023-10-27 18:00:11 +0000 UTC 18d default-bakcup-storage-location openebs.io/velero.backup=true
```
Using this command, I did not find the previous/next backup of this backup.
```sh
# kubectl exec -n velero pod/velero-5cbc58894d-696tr -it -- /velero backup describe inc-backup-20231028015510-20231027180011 --details
Name: inc-backup-20231028015510-20231027180011
Namespace: velero
Labels: velero.io/schedule-name=inc-backup-20231028015510
               velero.io/storage-location=default-bakcup-storage-location
Annotations: kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"velero.io/v1","kind":"Schedule","metadata":{"annotations":{},"name" :"inc-backup-20231028015510","namespace":"velero"},"spec":{"paused":false,"schedule":"*/30 * * * *","template":{"includeClusterResources ":true,"includedNamespaces":["openebs"],"includedResources":["persistentvolumeclaims"],"labelSelector":{"matchLabels":{"openebs.io/velero.backup":"true"}}, "snapshotVolumes":true,"storageLocation":"default-bakcup-storage-location","ttl":"504h","volumeSnapshotLocations":["default-volume-snapshot-location"]}}}

   velero.io/resource-timeout=10m0s
   velero.io/source-cluster-k8s-gitversion=v1.25.12+k3s1
   velero.io/source-cluster-k8s-major-version=1
   velero.io/source-cluster-k8s-minor-version=25

Phase: Completed


Namespaces:
   Included: openebs
   Excluded: <none>

Resources:
   Included: persistentvolumeclaims
   Excluded: <none>
   Cluster-scoped: included

Label selector: openebs.io/velero.backup=true

Storage Location: default-bakcup-storage-location

Velero-Native Snapshot PVs: true
Snapshot Move Data: auto
Data Mover: velero

TTL: 504h0m0s

CSISnapshotTimeout: 10m0s
ItemOperationTimeout: 4h0m0s

Hooks: <none>

Backup Format Version: 1.1.0

Started: 2023-10-27 18:00:11 +0000 UTC
Completed: 2023-10-27 18:00:12 +0000 UTC

Expiration: 2023-11-17 18:00:11 +0000 UTC

Total items to be backed up: 0
Items backed up: 0

Resource List:

Velero-Native Snapshots: <none included>
```

Maybe I didn't describe it clearly. I don't care what resources are backed up here.
What I am concerned about is if the data in our object storage is lost, is there a `dry-run` or `check` method to check the continuity of the backup in advance?

**Comment by lizhifengones** [comment]
In other words, whether velero's backup can always be trusted, if it is Complated, whether you specify --from-scheudle or --from-backup to restore the incremental backup package, the entire recovery process should be normal.

**Comment by lizhifengones** [comment]
This is the previous log, I still have reservations
[Uploading restore.log…]()

But I'm not sure if I can reproduce this problem. Even if I reproduce this problem, it should be a problem with the velero plug-in or openebs, so I want to close this issue.
