### ISSUE TITLE
Init container restic-wait is stuck

### ISSUE THREAD

**Issue by katarzynainit** [vmware-tanzu/velero#7024]
**What steps did you take and what happened:**
1. Having velero with restic enabled, a namespace with one deployment (one replica) and pvc mounted to a pod
2. using opt-in approach, pod annotated `backup.velero.io/backup-volumes: volume1`
3. Created backup
4. Removed resources (pvc, deployment)
5. Calling restore with `--include-resources 'pv,pvc,deployment,pod'`
6. All recreated, yet, a pod is stuck on init container
7. Restore status contains:
```
Phase:                       Completed
Total items to be restored:  4
Items restored:              4
```
```
Restic Restores:
  Completed:
    test-ns/test-6cfdbc4f9-hccwf: volume1
```
The created PodVolumeRestore has:
```
status:
  completionTimestamp: "2023-10-26T11:15:49Z"
  phase: Completed
  progress:
    itemsRestored: 4
    totalItems: 4
  startTimestamp: "2023-10-26T11:15:19Z"
``` 
No errors on the restore logs, also none in restic pod performing restore

After manually removing this stuck pod, new one gets created and I see that the files from pvc are restored

**What did you expect to happen:**

Init pod is complete and actual container can start

**Environment:**

- Velero version (use `velero version`): 1.9.0
- Velero features (use `velero client config get features`): --use-restic
- Kubernetes version (use `kubectl version`): 
```
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.24.14-gke.2700
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
@katarzynainit could you check why the pod is stuck on the initial container first? 
if it's not the reason of the environment, you could upload the logs collected by the `velero debug` command

**Comment by katarzynainit** [comment]
Hi

We checked on the node site, and we see that `.velero` folder is created not in the `mount/` path but next to it 

<img width="1246" alt="image" src="https://github.com/vmware-tanzu/velero/assets/45594770/ee4c5446-8fdf-4621-8451-b6af5bc02451">

When we copied `.velero` folder into the `mount/` init container ended without any further issues

Any idea why the `.velero` folder is in wrong place?

**Comment by katarzynainit** [comment]
Found a similar use case: #6489

**Comment by katarzynainit** [comment]
Upgrading velero to 1.9.1 solved the issue :) 

Closing
