### ISSUE TITLE
Incorrect azure domain used with kopia

### ISSUE THREAD

**Issue by rnarenpujari** [vmware-tanzu/velero#7030]
**What steps did you take and what happened:**

Noticed this error when using kopia with an azure bsl

```
time="2023-10-27T09:24:27Z" level=error msg="Error backing up item" backup=velero/bkp-092421 error="failed to wait BackupRepository: backup repository is not ready: error to get repo options: error to get storage variables: error to get azure storage domain: error loading environment from credentials file (/credentials/cloud): Can't separate key from value" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/backup_repo_op.go:83" error.function=github.com/vmware-tanzu/velero/pkg/repository.GetBackupRepository logSource="pkg/backup/backup.go:448" name=minio-56b8d6858b-nxh7w
```

It seems to be reading the wrong credential file (in my case that secret has non azure creds so it fails to parse it).

The azure domain is computed [here](https://github.com/vmware-tanzu/velero/blob/5c4fdfe147357ec7b908339f4516cd96d6b97c61/pkg/repository/provider/unified_repo.go#L514). But in function `getStorageVariables`, `config` is not populated with the credential file containing the per bsl secret data. So instead of using the info from the bsl secret, it uses `AZURE_CREDENTIALS_FILE` env var from the pod manifest which is not desirable.
`config` correctly has the credential file in function `getStorageCredentials` ([link](https://github.com/vmware-tanzu/velero/blob/5c4fdfe147357ec7b908339f4516cd96d6b97c61/pkg/repository/provider/unified_repo.go#L419)) so perhaps the azure domain should be computed in that function instead.

The code was refactored on main so maybe this issue isn't present anymore but should probably be fixed on the 1.12 and older branches.

**What did you expect to happen:**

Velero to use the Azure domain corresponding to `AZURE_CLOUD_NAME` from the bsl secret.

**The following information will help us better understand what's going on**:

NA

**Anything else you would like to add:**

NA

**Environment:**

- Velero version (use `velero version`): 1.12.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
this was removed by https://github.com/vmware-tanzu/velero/pull/6686, we will validate this issue in the new main branch.
