### ISSUE TITLE
Backup.Status.CSIVolumeSnapshotsCompleted < CSIVolumeSnapshotsAttempted or nil when backup phase is completed

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#7047]
**What steps did you take and what happened:**

It is possible for [runBackup function](https://github.com/kaovilai/velero/blob/886e074b55c9c9bab15dda5cbd1fe0976f026760/pkg/controller/backup_controller.go#L612), which is the only place that updates
- Backup.Status.CSIVolumeSnapshotsCompleted
- backup.Status.VolumeSnapshotsCompleted

to finish and move Phase towards and including completion without waiting for XSnapshotsCompleted to all be completed first.

**What did you expect to happen:**
- Backup to eventually (even after completion phase is ok) update its backup.Status.VolumeSnapshotsCompleted

Solutions:
- another controller in the background to update XCompleted status for snapshots
- copy following into other backup_x_controller.go and don't stop processing until backup.Status.VolumeSnapshotsCompleted == backup.Status.VolumeSnapshotsAttempted or timeout
 
 https://github.com/vmware-tanzu/velero/blob/886e074b55c9c9bab15dda5cbd1fe0976f026760/pkg/controller/backup_controller.go#L719
**Anything else you would like to add:**

Original issue: https://issues.redhat.com/browse/OADP-3005

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment]
This is a regression from 1.11 because in 1.11, CSI snapshotting was synchronous, so it was all complete at end of backup_controller processing. Now that waiting for ReadyToUse is done asynchronously, in many cases none of the snapshots are complete when we calculate the number of complete snapshots. Recalculating this one more time in the finalizer controller is probably the easiest way to fix this.

**Comment by allenxu404** [comment]
Hi @kaovilai, Has the PR been merged into release-1.12 yet? If not, could you help cherry-pick it to release-1.12?

**Comment by kaovilai** [comment]
Done! Thanks.
