### ISSUE TITLE
Data upload with Kopia hangs – probably at a certain data transfer size

### ISSUE THREAD

**Issue by michaelturko** [vmware-tanzu/velero#7064]
**What steps did you take and what happened:**

We have a data upload which always hangs. It seems it hangs on a specific data size limit or similar, we had two uploads which hung on the same transfer point:
```
8701958585   15187454896
8433964524   15431974037
```
It appears that it hangs after 8 GB to transfer out of 14 GB, and it seems to be related to a specific PVC.
Other PVCs which are smaller don't seem to have this problem.
This is the Kopia transfer: PVC Snapshot -> Kopia -> S3

When we take a look at the backup, we get:
```
velero describe backup foo-stage-velero-test-data-20231106061033 --details

Backup Item Operations:
  Operation for persistentvolumeclaims bar-test/elasticsearch-data-bar-test-elasticsearch-es-data-0:
    Backup Item Action Plugin:  velero.io/csi-pvc-backupper
    Operation ID:               du-50765c55-e638-432f-a7ad-9fd19e926ad3.3046afb5-ac71-4121a024b
    Items to Update:
                           datauploads.velero.io velero/foo-stage-velero-test-data-20231106061033-qzzr6
    Phase:                 Failed
    Operation Error:       Asynchronous action timed out
    Progress:              8433964524 of 15431974037 complete (Bytes)
    Progress description:  InProgress
    Created:               2023-11-06 07:12:04 +0100 CET
    Started:               2023-11-06 07:12:04 +0100 CET
```

Thoughts:
- Might there be a specific size limit for the data upload?
- Might it be related to Kopia - is there any special option to be added for Kopia to transfer large data size?

**What did you expect to happen:**
Data uploader transfers the data completely, independently of its size.

**Environment:**
- Velero version: v1.12

**Comment by Lyndon-Li** [comment]
@michaelturko 
Neither data upload nor Kopia has the limit on data size. And I don't think this is a common problem, it may be related to your data pattern/environment.
To further troubleshoot the problem, please check below info:

- What is the CPU usage and limit of node-agent pod which is running the data movement?
- What is the data like in the problematic volume, for example, how many files, how many dirs, what is the largest depth of the dirs?
- When the hang happens, can you see disk IOs and network IOs?

**Comment by ivomarino** [comment]
the error we get is:
```
time="2023-12-06T15:04:33Z" level=info msg="Reconcile velero-debug-20231206150122-zls9x" controller=dataupload dataupload=velero/velero-debug-20231206150122-zls9x logSource="pkg/controller/data_upload_controller.go:113"

time="2023-12-06T15:04:33Z" level=info msg="Data upload is in progress" controller=dataupload dataupload=velero/velero-debug-20231206150122-zls9x logSource="pkg/controller/data_upload_controller.go:293"

time="2023-12-06T15:04:33Z" level=info msg="Data upload is being canceled" controller=dataupload dataupload=velero/velero-debug-20231206150122-zls9x logSource="pkg/controller/data_upload_controller.go:295"    <------- No idea why this is happening

time="2023-12-06T15:04:33Z" level=warning msg="Async fs backup data path canceled" dataupload=velero-debug-20231206150122-zls9x logSource="pkg/controller/data_upload_controller.go:421"

1.7018750730449247e+09	INFO	Starting workers	{"controller": "datadownload", "controllerGroup": "velero.io", "controllerKind": "DataDownload", "worker count": 1}

time="2023-12-06T15:04:33Z" level=info msg="Reconcile velero-debug-20231206150122-6f82v" controller=dataupload dataupload=velero/velero-debug-20231206150122-6f82v logSource="pkg/controller/data_upload_controller.go:113"
```

**Comment by Lyndon-Li** [comment]
@ivomarino We need the velero log bundle to tell the cause. But from the current logs, I guess the node-agent pods were oom killed, so the DUs are cancelled after the pods restarted.

So you can increase the node-agent pod memory limit and retry, if the problem persists, just share us the entire log bundle.
