### ISSUE TITLE
Backup/Restore CR status has wrong StartTimestamp and CompletionTimestamp 

### ISSUE THREAD

**Issue by PrasadJoshi12** [vmware-tanzu/velero#7073]
**What steps did you take and what happened:**

1. Installed velero with timezone value set as Asia/Kolkata.
2. Triggered backup of empty namespace
3. Backup CR has older StartTimestamp and completionTimestamp.
```
$ oc get backup test-backup -o yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/resource-timeout: 10m0s
    velero.io/source-cluster-k8s-gitversion: v1.27.6+f67aeb3
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "27"
  creationTimestamp: "2023-11-08T05:57:04Z"
  generation: 6
  labels:
    velero.io/storage-location: default
  name: test-backup
  namespace: openshift-adp
  resourceVersion: "55954"
  uid: df712355-d8ad-4dfb-8710-23a82210a9ea
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: false
  includedNamespaces:
  - test
  itemOperationTimeout: 4h0m0s
  snapshotMoveData: false
  storageLocation: default
  ttl: 720h0m0s
status:
  completionTimestamp: "2023-11-08T05:57:11Z"
  expiration: "2023-12-08T05:57:04Z"
  formatVersion: 1.1.0
  phase: Completed
  progress:
    itemsBackedUp: 18
    totalItems: 18
  startTimestamp: "2023-11-08T05:57:04Z"
  version: 1
```
4. Velero describe and logs command is returning correct values. 
```
$ oc logs velero-6d6bf4cbcd-jhfpx 
Defaulted container "velero" out of: velero, openshift-velero-plugin (init), velero-plugin-for-aws (init), velero-plugin-for-csi (init)
time="2023-11-08T11:24:24+05:30" level=info msg="setting log-level to INFO" logSource="/remote-source/velero/app/pkg/cmd/server/server.go:193"
time="2023-11-08T11:24:24+05:30" level=info msg="Starting Velero server v1.12.1-OADP (-)" logSource="/remote-source/velero/app/pkg/cmd/server/server.go:195"
time="2023-11-08T11:24:24+05:30" level=info msg="1 feature flags enabled [EnableCSI]" logSource="/remote-source/velero/app/pkg/cmd/server/server.go:197"
time="2023-11-08T11:24:24+05:30" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="/remote-source/velero/app/pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/crd-remap-version

```
```
$ velero describe backup test-backup -n openshift-adp
Name:         test-backup
Namespace:    openshift-adp
Labels:       velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.27.6+f67aeb3
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=27

Phase:  Completed


Namespaces:
  Included:  test
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Or label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto
Snapshot Move Data:          false
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2023-11-08 11:27:04 +0530 IST
Completed:  2023-11-08 11:27:11 +0530 IST

Expiration:  2023-12-08 11:27:04 +0530 IST

Total items to be backed up:  18
Items backed up:              18

Velero-Native Snapshots: <none included>
```

**What did you expect to happen:**

Backup.status.StartTimeStamp and completionTimestamp should be same as reported by describe command. 

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment]
From CR:   completionTimestamp: "2023-11-08T05:57:11Z"
From describe: Completed:  2023-11-08 11:27:11 +0530 IST

This looks correct to me. CR shows time as 5:57:11 UTC. Describe shows 11:27:11 UTC+5:30 -- That's in local time, 5.5 hours ahead of UTC. Subtracting that offset puts it at 5:57:11, same as CR.

**Comment by PrasadJoshi12** [comment]
@sseago My assumption was it should report in same format which was specified via TZ env, like it does everywhere(In velero logs, velero describe and velero get backup output)

**Comment by sseago** [comment]
@PrasadJoshi12 If you look at `oc` or `kubectl` output for `get` vs `describe` for non-velero resources you'll see the same thing -- try it with a deployment, for example. `kubectl get -o yaml` shows the timestamp in UTC, and `kubectl describe` shows it in local time. The time is exactly the same, but the format differs. Describe is meant to be human-readable, so it converts the timestamp to local time. But the value in the actual kubernetes resource is in UTC, so that's what you get with `kubectl get -o yaml`

**Comment by sseago** [comment]
Velero is consistent with regular kubernetes behavior here.

**Comment by PrasadJoshi12** [comment]
@sseago thank you so much !

**Comment by ywk253100** [comment]
@PrasadJoshi12 I'm closing this issue, feel free to reopen it if you have any further questions
