### ISSUE TITLE
"No such file or directory" running Kopia backups

### ISSUE THREAD

**Issue by dploeger** [vmware-tanzu/velero#7074]
**What steps did you take and what happened:**
Run a PVC backup using kopia in which some files (like cache files) vanish during the backup.

**What did you expect to happen:**
The log might issue a warning, but the backup runs fine otherwise

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

[bundle-2023-11-08-07-15-48.tar.gz](https://github.com/vmware-tanzu/velero/files/13293478/bundle-2023-11-08-07-15-48.tar.gz)

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
Client:
	Version: v1.11.1
	Git commit: bdbe7eb242b0f64d5b04a7fea86d1edbb3a3587c
Server:
	Version: v1.11.1
- Velero features (use `velero client config get features`): 
features: <NOT SET>
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12+vmware.wcp.1", GitCommit:"4b7b5cdd62eeed2c0f5f3aa39c99a4bc3b6273a7", GitTreeState:"clean", BuildDate:"2022-12-06T07:49:54Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9+vmware.1", GitCommit:"21eeb4527eefb360eb251addc358cea6997e8335", GitTreeState:"clean", BuildDate:"2022-05-04T00:13:17Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
Tanzu
- Cloud provider or hardware configuration:
on-premise VMware Tanzu
- OS (e.g. from `/etc/os-release`):
What OS do you mean? Client or k8s Node?

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by dploeger** [comment]
This also came up in #6297 , but wasn't really handled. We can't use the CSI provider because we're using Tanzu without NSX.

**Comment by Lyndon-Li** [comment]
If you are using fs-backup, this is an expected behavior. fs-backup doesn't guarantee the consistency of the backup data, if the data frequently changes during backup, fs-backup may encounter failures. See the [Velero doc here](https://velero.io/docs/v1.12/csi-snapshot-data-movement/#:~:text=Besides%2C%20Velero%20File%20System%20Backup%20which%20could%20also%20back%20up%20the%20volume%20data%20to%20a%20pre%2Ddefined) for more details.

As mentioned in the doc, you can use CSI snapshot data movement to achieve a crash consistent backup, where the current problem could be eliminated.

As far as I know, CSI snapshot is available in your case, but since you are using Tanzu, you can open Tanzu help tickets for more helps.
