### ISSUE TITLE
DataDownload enters Completed state after it's canceled

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#7078]
**What steps did you take and what happened:**

Create a snapshot-data-move backup, then restore. During restore, cancel the DataDownload by adding `cancel: true` in DataDownload's spec with `kubectl` CLI.

The restore finished with `PartiallyFailed` due to DataDownload cancellation, but the DataDownload's Phase is still `Completed`.

```yaml
apiVersion: velero.io/v2alpha1
kind: DataDownload
metadata:
  creationTimestamp: "2023-11-09T14:35:50Z"
  generateName: 6595-03-20231109223547-
  generation: 8
  labels:
    velero.io/accepted-by: gke-cluster-4-default-pool-076de8e8-5rhs
    velero.io/async-operation-id: dd-7b11f25d-7651-4125-8657-50cfa7805bd8.f7ef0a77-8952-4dd41ef33
    velero.io/restore-name: 6595-03-20231109223547
    velero.io/restore-uid: 7b11f25d-7651-4125-8657-50cfa7805bd8
  name: 6595-03-20231109223547-qfjqz
  namespace: velero
  ownerReferences:
  - apiVersion: velero.io/v1
    controller: true
    kind: Restore
    name: 6595-03-20231109223547
    uid: 7b11f25d-7651-4125-8657-50cfa7805bd8
  resourceVersion: "124832488"
  uid: eb3cfb2d-8434-4a5e-80f9-5e626542cdb5
spec:
  backupStorageLocation: default
  cancel: true
  operationTimeout: 10m0s
  snapshotID: e32f543a8db6214acfeabb92eaa288a6
  sourceNamespace: upgrade
  targetVolume:
    namespace: restore
    pv: ""
    pvc: my-pvc
status:
  completionTimestamp: "2023-11-09T14:36:22Z"
  node: gke-cluster-4-default-pool-076de8e8-5rhs
  phase: Completed
  progress: {}
  startTimestamp: "2023-11-09T14:35:50Z"
```

**What did you expect to happen:**
The canceled DataDownload Phase should be `Canceled`.

**The following information will help us better understand what's going on**:
[bundle-2023-11-09-22-51-09.tar.gz](https://github.com/vmware-tanzu/velero/files/13309575/bundle-2023-11-09-22-51-09.tar.gz)

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): main
- Velero features (use `velero client config get features`): CSI
- Kubernetes version (use `kubectl version`): v1.26.6
- Kubernetes installer & version: GKE
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): Ubuntu

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
Below is the main logs:

time="2023-11-09T14:36:18Z" level=info msg="Data download is being canceled" controller=datadownload datadownload=velero/6595-03-20231109223547-qfjqz logSource="pkg/controller/data_download_controller.go:290"

time="2023-11-09T14:36:22Z" level=info msg="Data download is marked as Completed" controller=DataDownload datadownload=6595-03-20231109223547-qfjqz logSource="pkg/controller/data_download_controller.go:374"
- Why the DD CR is complete:
when Data download is `InProgess` phase:
we first cancel the DR, but  data download completed asynchronously shortly. then Set the  canceled DR into completed in callback function `OnDataDownloadCompleted`

- Why the restore CR is PartiallyFailed:
   In `(p *PVCRestoreItemAction) Progress` CSI plugin, it check that DD CR is Canceled (before `Completed`)and set the progress.Err with below
   `progress.Err = fmt.Sprintf("DataDownload is canceled")`
   
  then restore_operations_controller will set Restore CR into RestorePhasePartiallyFailed after check related operations as it exist on operation error.

**Maybe we should also check the terminal status of related CR at the beginning of every call backup function in datapath**

**Comment by reasonerjt** [comment]
Per discussion there's no race condition in datapath so the analysis in[ this thread ](https://github.com/vmware-tanzu/velero/issues/7078#issuecomment-1882560315)may be inaccurate.

We still need RCA.

**Comment by qiuming-best** [comment]
```golang
func (fs *fileSystemBR) StartBackup(source AccessPoint, realSource string, parentSnapshot string, forceFull bool, tags map[string]string, uploaderConfig map[string]string) error {
	if !fs.initialized {
		return errors.New("file system data path is not initialized")
	}

	go func() {
		snapshotID, emptySnapshot, err := fs.uploaderProv.RunBackup(fs.ctx, source.ByPath, realSource, tags, forceFull,
			parentSnapshot, source.VolMode, uploaderConfig, fs)

		if err == provider.ErrorCanceled {
			fs.callbacks.OnCancelled(context.Background(), fs.namespace, fs.jobName)
		} else if err != nil {
			dataPathErr := DataPathError{
				snapshotID: snapshotID,
				err:        err,
			}
			fs.callbacks.OnFailed(context.Background(), fs.namespace, fs.jobName, dataPathErr)
		} else {
			fs.callbacks.OnCompleted(context.Background(), fs.namespace, fs.jobName, Result{Backup: BackupResult{snapshotID, emptySnapshot, source}})
		}
	}()

	return nil
}
```
RunBackup is already finished, and the logic has already gone into the `OnCompleted` function, the cancel action won't work. so the `datadownload` would be in completed status.

the cancel action could work if `RunBackup` is still running.
