### ISSUE TITLE
Velero Azure VSL error: config has invalid keys [subscriptionId]

### ISSUE THREAD

**Issue by chrislinan** [vmware-tanzu/velero#7084]
**What steps did you take and what happened:**

1. use Velero 1.12.1 and velero Azure plugin 1.8.1
2. Back up a PV

**What did you expect to happen:**
Velero PV backup success

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

velero backup describe:
```
Phase:  PartiallyFailed (run `velero backup logs testbackup11` for more information)
 
 
Errors:
  Velero:     <none>
  Cluster:   resource: /persistentvolumes name: /pv-shoot--hc-dev--micaz-haas-26969aee-ea88-41f0-9314-156d3fe10ffb error: /rpc error: code = Unknown desc = config has invalid keys [subscriptionId]; valid keys are [resourceGroup apiTimeout resourceGroup incremental tags credentialsFile]
             resource: /persistentvolumes name: /pv-shoot--hc-dev--micaz-haas-a9fd5ccc-7b20-4267-85aa-489971971029 error: /rpc error: code = Unknown desc = config has invalid keys [subscriptionId]; valid keys are [resourceGroup apiTimeout resourceGroup incremental tags credentialsFile]
             resource: /persistentvolumes name: /pv-shoot--hc-dev--micaz-haas-85523b17-0915-49cf-9ff5-574b31bf655a error: /rpc error: code = Unknown desc = config has invalid keys [subscriptionId]; valid keys are [resourceGroup apiTimeout resourceGroup incremental tags credentialsFile]
             resource: /persistentvolumes name: /pv-shoot--hc-dev--micaz-haas-a14da77f-7f5e-4336-9ab1-68cfcac30597 error: /rpc error: code = Unknown desc = config has invalid keys [subscriptionId]; valid keys are [resourceGroup apiTimeout resourceGroup incremental tags credentialsFile]
             resource: /persistentvolumes name: /pv-shoot--hc-dev--micaz-haas-3a51fb83-3ddc-4785-b0c6-549a47fd1116 error: /rpc error: code = Unknown desc = config has invalid keys [subscriptionId]; valid keys are [resourceGroup apiTimeout resourceGroup incremental tags credentialsFile]
  Namespaces: <none>
```

It looks like, in the latest version, VSL config doesn't contain the key 'subscriptionId' anymore.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.12.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
@chrislinan I cannot reproduce it in my env and also checked the [code](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/v1.8.1/velero-plugin-for-microsoft-azure/volume_snapshotter.go#L92) it shouldn't report such error
