### ISSUE TITLE
Comment out empty placeholder `configuration.backupStorageLocation` and `configuration.volumeSnapshotLocation` from helm chart default values

### ISSUE THREAD

**Issue by deefdragon** [vmware-tanzu/velero#7088]
**Describe the problem/challenge you have**

The way I am using terraform and infra as code require me to declare all of my locations as seperate steps later down the line, instead of having them built into the helm deployment. 

The fact that the default values includes the set of empty placeholder locations means that you have to take the unintuitive step of setting `configuration.volumeSnapshotLocation` and `configuration.volumeSnapshotLocation` to null. These examples _should_ be included in the default values for documentation purposes, but should be commented out to allow the user to set them as desired, not requiring the null override. 

**Describe the solution you'd like**
The currently existing array placeholders commented out to allow a default deployment not create the locations unless explicitly set to do so.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.12, chart 5.1.3
- Kubernetes version (use `kubectl version`): 1.28
- Kubernetes installer & version: 1.28
- Cloud provider or hardware configuration: Kubeadm
- OS (e.g. from `/etc/os-release`): ubuntu

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
@qiuming-best 
Could you help to take a look?

@deefdragon 
I'm not sure about the suggestion. In most cases, there is still a need to have at least a BSL, because the Velero server needs a BSL to take backup and restore.

**Comment by deefdragon** [comment]
I do have backup storage locations. I just create them _separate_ from the helm chart velero deployment.

My infra code has one stage that deploys all of the operators, CRDs etc (which includes velero), then a second that deploys the stuff that _uses_ those operators & CRDS, which is where I add the BSLs, the schedules, etc.

**Comment by blackpiglet** [comment]
I see. The helm chart should still have a default BSL and VSL because that will guarantee the chart can work in most cases, but the helm chart can add a new option to let the user choose whether the default BSL and VSL should be created and the default value is true.

**Comment by deefdragon** [comment]
Unfortunately, the issue is that as is, the defaults _don't_ work in most cases. They cause the template to crash out as you are _required_ to override certain default values that were left empty in the BSL/VSL config (Name and Provider IIRC). The velero helm chart is the only chart I've ever encountered to have this.

The velero helm chart default values should probably install approximately the same configuration that would be installed with the `velero install` command (without any -- flags applied). In regards to BSLs/VSLs, IIRC, this results in none being created. (The install docs even redirect to the [supported storage providers](https://velero.io/docs/v1.12/supported-providers/) page).

While I understand the desire to have the helm chart deploy everything to get velero working out of the box, even if the helm chart does have some form of default BSL, that BSL cant function as the chart would have no idea what to set for location or credentials, meaning it would be permanently unavailable. I think the better new user experience would be to have the user have no storage location as opposed to a default, non-functional one.

**Comment by blackpiglet** [comment]
Do have some points. The BSL and VSL need some customized information to work as expected, and Velero cannot know that by default, which means the default BSL and VSL cannot work.

@qiuming-best @jenting 
What's your opinion?
