### ISSUE TITLE
Velero DataUpload empty although CSI Snapshot backup completed successfully

### ISSUE THREAD

**Issue by pavlovnicola** [vmware-tanzu/velero#7103]
**What steps did you take and what happened:**
After installing/configuring Velero with CSI enabled, I tried to backup a specific namespace that has PVC.
The backup succeeded but I do not see datauploads items when I run:
`kubectl -n velero get datauploads`  

**What did you expect to happen:**
I expected to see items under datauploads.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  Yes. I am using velero helm velero-5.1.3
Please use 
[bundle-2023-11-15-11-16-07.tar.gz](https://github.com/vmware-tanzu/velero/files/13362750/bundle-2023-11-15-11-16-07.tar.gz)

Command that I used to backup:
`velero backup create nginx-snapshot-backup-44 --storage-location velero-aws --volume-snapshot-locations velero-aws --include-namespaces nginx-snapshot --snapshot-volumes --snapshot-move-data=true`

**Environment:**

- Velero Version:
Client:
        Version: v1.12.0
        Git commit: 7112c62e493b0f7570f0e7cd2088f8cad968db99
Server:
        Version: v1.11.1
- Velero features: EnableCSI
- Kubernetes 1.24
- VSphere VSAN CSI Plugin

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
I think the Velero server version is not correct.
The snapshot data mover feature is introduced in the Velero v1.12.0 release.
https://velero.io/docs/v1.12/csi-snapshot-data-movement/

**Comment by pavlovnicola** [comment]
Hi @blackpiglet 

Thanks for the reply.
I just tested it with v.12.0. I still do not see any datauploads.

`Client:
        Version: v1.12.0
        Git commit: 7112c62e493b0f7570f0e7cd2088f8cad968db99
Server:
        Version: v1.12.0
rppt@nicolap:~# kubectl -n velero get datauploads
No resources found in velero namespace.
`

**Comment by blackpiglet** [comment]
@pavlovnicola 
Please help to collect the debug bundle to help investigate.

**Comment by pavlovnicola** [comment]
@blackpiglet 

PFA the debug bundle.

[bundle-2023-11-17-10-30-39.tar.gz](https://github.com/vmware-tanzu/velero/files/13389227/bundle-2023-11-17-10-30-39.tar.gz)

**Comment by blackpiglet** [comment]
```
Velero-Native Snapshot PVs:  auto
Snapshot Move Data:          auto
Data Mover:                  velero
```

In the backup describe output, the snapshot move data flag value is not set to true.

**Comment by pavlovnicola** [comment]
@blackpiglet 

Here is the command I have used:

`velero backup create nginx-snapshot-backup-54 --storage-location velero-aws --volume-snapshot-locations velero-aws --include-namespaces nginx-snapshot --snapshot-move-data`

**Comment by pavlovnicola** [comment]
@blackpiglet 

I was able to get it working. In values.yaml file, I added the following lines:
`snapshotsEnabled: true 
  features: EnableCSI
  defaultSnapshotMoveData: true
  defaultVolumeSnapshotLocations: "velero.io/aws:velero-aws"`

I can see datauploads as completed.

When I try to restore now on another K8s cluster that is running on a different VSphere DC, it is failing. I do not see datadownloads.

`error preparing persistentvolumeclaims/nginx-snapshot/nginx-logs: rpc error: code = Unknown desc = Failed to get Volumesnapshot nginx-snapshot/velero-nginx-logs-vcqqs to restore PVC nginx-snapshot/nginx-logs: volumesnapshots.snapshot.storage.k8s.io "velero-nginx-logs-vcqqs" not found`

**Comment by blackpiglet** [comment]
It seems there is still some inconsistency.
For the snapshot data moved backup, the restore doesn't need the CSI VolumeSnapshots to work.
The Velero server will read the data in the object storage by the integrated Kopia library.

Please collect the debug bundle for the restore.
