### ISSUE TITLE
Disk Type Change Request by snapshot backup

### ISSUE THREAD

**Issue by michael1011101** [vmware-tanzu/velero#7108]
**Describe the problem/challenge you have**

In our landscape, we use the `snapshot backup` to backup and restore resources. Now we have a scenario where we need to restore the disk to another disk type with Velero.

**Describe the solution you'd like**

1. Add another storage class with new disk type.
2. Add velereo restore item action configmap.
3. Backup resources (PV) with velero.
4. Delete resources in k8s.
5. Restore from backup.
6. The disk type of PV is changed.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): v1.11.0 or more

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
I assume, by saying using `snapshot backup`, you are using the Velero-native snapshot to backup volume's data. The reason that the disk type cannot be changed is that Velero patches the PV resource during the restore, not dynamically creating it.

Please try with the CSI plugin to backup and restore the volume.
https://velero.io/docs/v1.12/csi/

**Comment by michael1011101** [comment]
Hi @blackpiglet , If I enable the CSI plugin, does it mean the backup method can be only used by `CSI backup`?
Can we choose which backup method to use by some way?

**Comment by blackpiglet** [comment]
There are two major types of how Velero backs up the volume content.
First is the snapshot type. It includes the Velero-native snapshot and the CSI snapshot.
Second is the filesystem backup. It supports using Restic and Kopia as the uploader.

The two major types can mix in one backup. 
You can choose the volume backing up by filesystem backup with the opt-in and opt-out methods.
https://velero.io/docs/main/file-system-backup/#to-back-up

There is no method to choose which volumes should be backed up by the snapshot way yet.

Even for the snapshot way, if the CSI feature is enabled and the CSI plugin is installed, but the PV is a CSI migrated one, the Velero server will fall back to the Velero-native snapshot way.

**Comment by michael1011101** [comment]
Hi @blackpiglet ,
I tried with [CSI Snapshot support in veleor](https://velero.io/docs/v1.12/csi/#installing-velero-with-csi-support). 
Create one `volumesnapshotclasses.snapshot.storage.k8s.io` named `default` with label `velero.io/csi-volumesnapshot-class: "true"` and driver `driver: disk.csi.azure.com`.
Create velero backup with following yaml file.
```
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/csi-volumesnapshot-class_disk.csi.azure.com: "default"
  name: testbackup9
spec:
  includedNamespaces:
  - default
  includedResources:
  - pv
  - pvc
  - replicasets
  labelSelector:
    matchLabels:
      service_instance_id: abcd
```

But in the details of the backup, it still use the native snapshot.
```
; velero backup describe testbackup9 --details

Name:         testbackup9
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"velero.io/v1","kind":"Backup","metadata":{"annotations":{"velero.io/csi-volumesnapshot-class_disk.csi.azure.com":"default"},"name":"testbackup9","namespace":"velero"},"spec":{"includedNamespaces":["default"],"includedResources":["pv","pvc","replicasets"],"labelSelector":{"matchLabels":{"service_instance_id":"abcd"}}}}

  velero.io/csi-volumesnapshot-class_disk.csi.azure.com=default
  velero.io/source-cluster-k8s-gitversion=v1.26.7
  velero.io/source-cluster-k8s-major-version=1
  velero.io/source-cluster-k8s-minor-version=26
...
Velero-Native Snapshots:
  pv-shoot--xxxxxx
    Snapshot ID:       xxxx
    Type:               Premium_LRS
    Availability Zone:  ***
    IOPS:               <N/A>

CSI Volume Snapshots: <none included>
```

**Comment by blackpiglet** [comment]
The reason is the PV is in a CSI-migrated format.
That means the PV doesn't contain a `spec.CSI` in its yaml. 
The CSI plugin cannot handle that format PV, and the Velero serve will fall back to the native snapshot.

Another option is to use the filesystem uploader to backup the volume data.

**Comment by blackpiglet** [comment]
Yes. CSI backup cannot support backing up the CSI-migrated PV.

Got it. Although, IMO, the native snapshot doesn't mean working in a dynamic PV-creating way in restore, let's check whether there are also other users who need this feature.

**Comment by michael1011101** [comment]
Glad to hear that. Please let me know if you have any progress.

**Comment by blackpiglet** [comment]
Please refer to this issue.
https://github.com/Azure/azure-cli/issues/23895

It's already been fixed, but only the main branch has it yet.

**Comment by blackpiglet** [comment]
Is it related to the Velero issue?

**Comment by blackpiglet** [comment]
The previous CSI Azure issue looks like an Azure CSI plugin issue.
@michael1011101 Is your issue fixed?

**Comment by devaroqu** [comment]
@blackpiglet  not related to Velero more related to this also  https://github.com/Azure/azure-cli/issues/23895

**Comment by blackpiglet** [comment]
@devaroqu 
For creating snapshots with the Azure CLI in the VM scenario, I'm afraid I cannot fix that. 
This Github repository focuses on the Velero issues, the Azure CLI issues are not in the scope.
