### ISSUE TITLE
Restic persistent volume backup from Kubernetes PreStop Hook (when pod is in 'Terminating' status)

### ISSUE THREAD

**Issue by area51b** [vmware-tanzu/velero#7112]
**Describe the problem/challenge you have**
When attempting to trigger a backup of a K8s persistent volume (PV) using Restic from the preStop hook of a pod, the pod status is in Terminating status and this prevents Restic from successfully taking the backup on persistent volumes. (related to fix: https://github.com/vmware-tanzu/velero/pull/4584)

**Describe the solution you'd like**
If we allow restic backupper to take the backup the PVs even if the pod status is Terminating, it will allow us to take proper backup before the pod is terminated. This is helpful to take a backup of pods running for specific purpose and removed after that. Use case I am working on is to backup the JupyterHub notebook once the user finishes their work and stop the server.  

**Environment:**

- Velero version (use `velero version`): 1.12 (OpenShift OADP Operator 1.2.3)
- Kubernetes version (use `kubectl version`): v1.24.16+6981c04
- Kubernetes installer & version: OpenShift 4.11.50
- Cloud provider or hardware configuration: N.A
- OS (e.g. from `/etc/os-release`): Red Hat Enterprise Linux CoreOS (RHCOS)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
IMO, this is against how Velero works now. The Velero server will skip the pods having the deletion timestamp.
During deletion, I'm not sure whether the Velero filesystem uploader can always access the mounted volumes.

Pod in the preStop hook can be deleted after the grace period expires, and the filesystem backup can be time-consuming.

**Comment by area51b** [comment]
The pod termination grace period can be adjusted based on the estimated time required for filesystem backup. If there are no implementation issues like the Velero filesystem uploader accessing the mounted volumes, I would recommend to consider this enhancement.

**Comment by blackpiglet** [comment]
https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks

Per the document, it seems the preStop hook is not reliable. The user cannot set the preStop hook's timeout period.
If the pod's grace period is not longer than the backup creation period, the backup may be killed before completion.
