### ISSUE TITLE
How to view the size of backup content

### ISSUE THREAD

**Issue by renl123** [vmware-tanzu/velero#7113]
Unable to see the file size after backup using commands "velero backup describe <backup-name> --detail "

**Comment by blackpiglet** [comment]
Could you give more information about your backup type and the environment?
Please follow this template to provide more detail for debugging: https://github.com/vmware-tanzu/velero/blob/main/.github/ISSUE_TEMPLATE/bug_report.md.

**Comment by renl123** [comment]
What steps did you take and what happened:
After performing the backup operation, using the "velero backup describe <backup-name> --detail " command did not display the backup size.

What did you expect to happen:
Using the "velero backup describe <backup-name> --detail " command can display the backup size of every source and total size.

Environment:
velero v1.12.1

**Comment by blackpiglet** [comment]
@renl123
I think this is a fair enough request. 
By saying `display the backup size of every source and total size`, what does the source mean?
Velero can display the snapshot's size and the filesystem uploaded data size.

The missing information is the overall Velero backup metadata file size.

**Comment by blackpiglet** [comment]
Is this issue related to your request?
https://github.com/vmware-tanzu/velero/issues/6506

**Comment by renl123** [comment]
velero backup describe tst --details
Name:         tst
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.27.0
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=27

Phase:  Completed


Namespaces:
  Included:  test-renliang7
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Or label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto
Snapshot Move Data:          false
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2023-11-16 18:10:40 +0800 CST
Completed:  2023-11-16 18:10:52 +0800 CST

Expiration:  2023-12-16 18:10:40 +0800 CST

Total items to be backed up:  15
Items backed up:              15

Resource List:
  apps/v1/ControllerRevision:
    - test-renliang7/mysql-nfsstorage-74bf57fc79
    - test-renliang7/mysql-nfsstorage20231010restore-74bf57fc79
  apps/v1/StatefulSet:
    - test-renliang7/mysql-nfsstorage
    - test-renliang7/mysql-nfsstorage20231010restore
  v1/ConfigMap:
    - test-renliang7/kube-root-ca.crt
  v1/Event:
    - test-renliang7/mysql-nfsstorage20231010restore-0.178c9d2a3c3c20fa
    - test-renliang7/mysql-nfsstorage20231010restore-0.178c9d59906733db
  v1/Namespace:
    - test-renliang7
  v1/PersistentVolume:
    - pvc-115b86ee-df8f-4293-b4f9-5ba93f1f4c21
    - pvc-58f80d6b-1475-48c7-beb0-933f02b55523
  v1/PersistentVolumeClaim:
    - test-renliang7/mysql-nfs-mysql-nfsstorage20231010restore-pvc
    - test-renliang7/mysql-nfs-pvc
  v1/Pod:
    - test-renliang7/mysql-nfsstorage-0
    - test-renliang7/mysql-nfsstorage20231010restore-0
  v1/ServiceAccount:
    - test-renliang7/default

Velero-Native Snapshots: <none included>

kopia Backups:
  Completed:
    test-renliang7/mysql-nfsstorage-0: mysql-data


-----------------------------------------------
The above backup uses file system backup, but the description lacks a description of the backup size

**Comment by blackpiglet** [comment]
@renl123 
Need to know more details of the information you want to know?
For example, your scenario uses which type of volume data backing up methods? Snapshot or filesystem upload.
Which volume data size do you want to know? The size of the volume or the size of the volume's backup(after de-duplicate and compression).

**Comment by antoweb** [comment]
Hello, if you open the podvolumebackup crd with edit in openlens or yaml via cli you can see for example

  phase: Completed
  progress:
    bytesDone: 55976887035
    totalBytes: 55976887035
  snapshotID: 3a6a08c56cee188877b510ad709d79a6
  startTimestamp: '2025-03-25T11:29:50Z'
