### ISSUE TITLE
velero version 1.12.1 failed with error "An error occurred: unknown flag: --use-restic"

### ISSUE THREAD

**Issue by subhankar-banerjee** [vmware-tanzu/velero#7123]
[rke@kube-master rke-k8s]$ velero version
Client:
        Version: v1.12.1
        Git commit: 5c4fdfe147357ec7b908339f4516cd96d6b97c61
<error getting server version: no matches for kind "ServerStatusRequest" in version "velero.io/v1">
[rke@kube-master rke-k8s]$ 

I was trying to install the Velero server on the rancher k8s cluster ( Rancher Kubernetes: v1.25.9-rancher2 ) backend storage is Ceph RBD .  I was using Velero version 1.12.1 but I am getting an error: An error occurred: unknown flag: --use-restic

velero install command ---

velero install \
--provider aws \
--plugins velero/velero-plugin-for-aws:v1.8.1 \
--bucket rancher-k8s-backup \
--secret-file ./credentials-minio \
--use-volume-snapshots=false \
--use-restic \
--backup-location-config \
region=minio,s3ForcePathStyle="true",s3Url=http://<my_machine_ip>:9000

**Comment by blackpiglet** [comment]
https://github.com/vmware-tanzu/velero/releases/v1.10.0
Please check the Velero v1.10.0 release note. The `--use-restic` is renamed to `--use-node-agent`.
