### ISSUE TITLE
permission issue -> compute.disks.get'

### ISSUE THREAD

**Issue by yossibalan** [vmware-tanzu/velero#7124]
**What steps did you take and what happened:**

I got this error in the velero pod

{"backup":"velero/velero-rook-data-20231119150028","error.message":"error getting volume info: rpc error: code = Unknown desc = googleapi: Error 403: Required 'compute.disks.get' permission for 'projects/sap-gcp-cp-devx-in30-prod/zones/asia-south1-b/disks/pv--34601b2e-da76-4bf0-975f-2290a2a59dda', forbidden","level":"error","logSource":"pkg/backup/backup.go:435","msg":"Error backing up item","name":"rook-ceph-mon-au","time":"2023-11-19T15:00:34Z"

**What did you expect to happen:**
Not to get this error

in the IAM the user has the roles

limited-credentials@sap-gcp-cp-devx-in30-prod.iam.gserviceaccount.com | limited-credentials | Owner/ Viewer

I looked on the viewer logs and it is include the compute.disks.get
in the storage permissions

limited-credentials@sap-gcp-cp-devx-in30-prod.iam.gserviceaccount.com | limited-credentials | storage adminStorage Object Admin | No inheritance, for role storage admin sap-gcp-cp-devx-in30-prod |   |  

<br class="Apple-interchange-newline">

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Client:
        Version: v1.12.1
        Git commit: -
Server:
        Version: v1.11.0

- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.9", GitCommit:"d1483fdf7a0578c83523bc1e2212a606a44fd71d", GitTreeState:"clean", BuildDate:"2023-09-13T11:32:41Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.9", GitCommit:"d1483fdf7a0578c83523bc1e2212a606a44fd71d", GitTreeState:"clean", BuildDate:"2023-09-13T11:25:26Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by yossibalan** [comment]
This is the result of the backup k get backup velero-rook-data-20231119150028  -n velero -o yaml                                                       ⎈ shoot--prod-gcp--in30-prod 17:18:35
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade,post-rollback
    helm.sh/hook-delete-policy: before-hook-creation
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"velero.io/v1","kind":"Schedule","metadata":{"annotations":{"helm.sh/hook":"post-install,post-upgrade,post-rollback","helm.sh/hook-delete-policy":"before-hook-creation"},"labels":{"app.kubernetes.io/instance":"velero","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"velero","helm.sh/chart":"velero-4.0.3"},"name":"velero-rook-data","namespace":"velero"},"spec":{"schedule":"0 * * * *","template":{"includedNamespaces":["rook-ceph"],"includedResources":["volumesnapshotcontents","volumesnapshots","persistentvolumeclaims","persistentvolumes","secrets","services","configmaps"],"snapshotVolumes":true,"ttl":"72h"}}}
    velero.io/source-cluster-k8s-gitversion: v1.26.9
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "26"
  creationTimestamp: "2023-11-19T15:00:28Z"
  generation: 4
  labels:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-4.0.3
    velero.io/schedule-name: velero-rook-data
    velero.io/storage-location: default
  name: velero-rook-data-20231119150028
  namespace: velero
  resourceVersion: "706383151"
  uid: 1cf96355-ec81-4e85-9e5a-4afc7d9de884
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: false
  hooks: {}
  includedNamespaces:
  - rook-ceph
  includedResources:
  - volumesnapshotcontents
  - volumesnapshots
  - persistentvolumeclaims
  - persistentvolumes
  - secrets
  - services
  - configmaps
  itemOperationTimeout: 1h0m0s
  metadata: {}
  snapshotVolumes: true
  storageLocation: default
  ttl: 72h0m0s
  volumeSnapshotLocations:
  - default
status:
  completionTimestamp: "2023-11-19T15:00:40Z"
  errors: 12
  expiration: "2023-11-22T15:00:32Z"
  formatVersion: 1.1.0
  phase: PartiallyFailed
  startTimestamp: "2023-11-19T15:00:32Z"
  version: 1

**Comment by blackpiglet** [comment]
The error message is:
```
"error getting volume info: rpc error: code = Unknown desc = googleapi: Error 403: Required 'compute.disks.get' permission for 'projects/sap-gcp-cp-devx-in30-prod/zones/asia-south1-b/disks/pv--34601b2e-da76-4bf0-975f-2290a2a59dda', forbidden"
```

Please check whether this volume can be accessed by the user credential you are using.

This is the Velero GCP plugin needs permission list:
https://github.com/vmware-tanzu/velero-plugin-for-gcp#create-custom-role-with-permissions-for-the-velero-gsa

**Comment by yossibalan** [comment]
@blackpiglet  Thanks for the support . I am new in velero. how I can check that the volume can be  accessed by the user credential you are using. about the access I added in the Iam/admin view to my user the roles : Compute Engine Service Agent ,Owner, Viewer

**Comment by blackpiglet** [comment]
You can get the GCP role's content by `gcloud I am roles describe` command.

```
$ gcloud iam roles describe velero.server --project velero-gcp                                                              [15:02:37]
etag: BwYBiQOpCM0=
includedPermissions:
- compute.disks.create
- compute.disks.createSnapshot
- compute.disks.get
- compute.projects.get
- compute.snapshots.create
- compute.snapshots.delete
- compute.snapshots.get
- compute.snapshots.useReadOnly
- compute.zones.get
- iam.serviceAccounts.signBlob
- storage.objects.create
- storage.objects.delete
- storage.objects.get
- storage.objects.list
name: projects/velero-gcp/roles/velero.server
stage: ALPHA
title: Velero Server
```

**Comment by NoamGaloz** [comment]
Hi @blackpiglet, Is that role supposed to be added to the **service** **account** that is being used by Velero?

**Comment by blackpiglet** [comment]
Yes.

**Comment by yossibalan** [comment]
I created user and it worked
