### ISSUE TITLE
Error thrown not from Velero

### ISSUE THREAD

**Issue by NoamGaloz** [vmware-tanzu/velero#7127]
**What steps did you take and what happened:**

I used the command 'kubectl logs..' over my velero pod and found this logs:

I1120 12:04:38.946507       1 request.go:690] Waited for 1.046462618s due to client-side throttling, not priority and fairness, request: GET:https://api.stg-cent.apigw-cry.internal.canary.k8s.ondemand.com:443/apis/services.cloud.sap.com/v1alpha1?timeout=32s
I1120 12:09:44.699026       1 request.go:690] Waited for 1.044391079s due to client-side throttling, not priority and fairness, request: GET:https://api.stg-cent.apigw-cry.internal.canary.k8s.ondemand.com:443/apis/node.k8s.io/v1?timeout=32s
I1120 12:14:50.451175       1 request.go:690] Waited for 1.044982531s due to client-side throttling, not priority and fairness, request: GET:https://api.stg-cent.apigw-cry.internal.canary.k8s.ondemand.com:443/apis/scheduling.k8s.io/v1?timeout=32s
I1120 12:19:56.202707       1 request.go:690] Waited for 1.044676062s due to client-side throttling, not priority and fairness, request: GET:https://api.stg-cent.apigw-cry.internal.canary.k8s.ondemand.com:443/apis/fed.solo.io/v1?timeout=32s
I1120 12:25:01.954802       1 request.go:690] Waited for 1.04485511s due to client-side throttling, not priority and fairness, request: GET:https://api.stg-cent.apigw-cry.internal.canary.k8s.ondemand.com:443/apis/cert.gardener.cloud/v1alpha1?timeout=32s
I1120 12:30:07.707067       1 request.go:690] Waited for 1.044854944s due to client-side throttling, not priority and fairness, request: GET:https://api.stg-cent.apigw-cry.internal.canary.k8s.ondemand.com:443/apis/networking.istio.io/v1alpha3?timeout=32s
I1120 12:35:13.459273       1 request.go:690] Waited for 1.045265383s due to client-side throttling, not priority and fairness, request: GET:https://api.stg-cent.apigw-cry.internal.canary.k8s.ondemand.com:443/apis/fed.gloo.solo.io/v1?timeout=32s
I1120 12:40:19.210592       1 request.go:690] Waited for 1.044707247s due to client-side throttling, not priority and fairness, request: GET:https://api.stg-cent.apigw-cry.internal.canary.k8s.ondemand.com:443/apis/cert-manager.io/v1?timeout=32s

I already did an investigation and found that the error 'Waited for __ due to client-side throttling, not priority and fairness.." comes from k8s client: https://github.com/kubernetes/client-go/blob/84a6fe7e4032ae1b8bc03b5208e771c5f7103549/rest/request.go#L625

But the k8s client has a lot of uses in Velero so it gives me no hint as to its source in Velero or reason.

**What did you expect to happen:**

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.12.1
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by mateusoliveira43** [comment]
I faced a similar problem in one project. Here what we did in our project https://github.com/openshift/oadp-operator/pull/1205

Since you are seeing more then one message, maybe this needs to be addressed to only create one client per run.

But to remove the message, that would need some new configuration I believe (instead of Velero just increasing GPS and burst by itself).

**Comment by NoamGaloz** [comment]
Not sure what you mean by creating one client per run. I'm using Velero as is, with no intervention at the code...

**Comment by mateusoliveira43** [comment]
When Velero starts, it seems instead of creating an instance of kubernetes client (which triggers each message you see) and using everywhere else, it creates more then one (once every time it needs?). Just pointing out what could be happening, for someone interested in trying to tackle this issue

**Comment by NoamGaloz** [comment]
@ywk253100 Any idea?
