### ISSUE TITLE
Velero backup not working with Ceph storage on-premises for Kubernetes PVC 

### ISSUE THREAD

**Issue by subhankar-banerjee** [vmware-tanzu/velero#7145]
I have installed Velero 1.12.1 on-premises to take Kubernetes PVC backup  

[rke@kube-master ~]$ velero version
Client:
        Version: v1.12.1
        Git commit: 5c4fdfe147357ec7b908339f4516cd96d6b97c61
Server:
        Version: v1.12.1
[rke@kube-master ~]$ 

backend storage used **Ceph 13.2.10**

Valero install command ---

velero install \
--provider aws \
--plugins velero/velero-plugin-for-aws:v1.8.1 \
--bucket rancher-k8s-backup \
--secret-file ./credentials-minio \
--use-volume-snapshots=false \
--use-node-agent \
--backup-location-config \
region=minio,s3ForcePathStyle="true",s3Url=http://10.128.0.55:9000

Installation is fine, the minio setup is all good, even I am even able to create and restore backup .....
I was using the Velero FSB process... but unfortunately data was not able to be in 2nd cluster, there is no error in the log 

now the question is whether this setup will work like Kubernetes with Ceph storage on-premises.

initially, I tested Jenkins migration from one cluster to another cluster, I can't see the Jenkins data like build history when I open Jenkins in UI in 2nd cluster but the application is copied ...

then I tried with a simple Neginx html page store in PVC that also didn't work ...

I can see the PVC is part of the backup in 1st cluster when taking a backup --

v1/Namespace:
    - nginx-storage
  **v1/PersistentVolume:
    - pvc-6cef2247-4eef-4a72-b4b5-2f9824f56532
  v1/PersistentVolumeClaim:
    - nginx-storage/nginx-pv-claim**
  v1/Pod:
    - nginx-storage/nginx-deployment-9874454f9-qfdl2
    - nginx-storage/nginx-deployment-9874454f9-qn9bm
  v1/Service:
    - nginx-storage/nginx-service

I can see this message in 2nd cluster --

[rke@kube-master-1 ~]$ velero describe restore nginxpvc-restore --details
Name:         nginxpvc-restore
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:                       Completed
Total items to be restored:  13
Items restored:              13

Started:    2023-11-24 23:55:13 +0000 UTC
Completed:  2023-11-24 23:55:14 +0000 UTC

Warnings:
  Velero:     <none>
  Cluster:    <none>
  Namespaces:
    nginx-storage:  could not restore, ConfigMap "kube-root-ca.crt" already exists. Warning: the in-cluster version is different than the backed-up version

Backup:  nginxpvc

Namespaces:
  Included:  all namespaces found in the backup
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io, csinodes.storage.k8s.io, volumeattachments.storage.k8s.io, backuprepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Or label selector:  <none>

Restore PVs:  true

Existing Resource Policy:   <none>
ItemOperationTimeout:       4h0m0s

Preserve Service NodePorts:  auto

Resource List:
  apps/v1/Deployment:
    - nginx-storage/nginx-deployment(created)
  apps/v1/ReplicaSet:
    - nginx-storage/nginx-deployment-9874454f9(created)
  discovery.k8s.io/v1/EndpointSlice:
    - nginx-storage/nginx-service-wj9xq(created)
  networking.k8s.io/v1/Ingress:
    - nginx-storage/nginx-ingress(created)
  v1/ConfigMap:
    - nginx-storage/kube-root-ca.crt(failed)
  v1/Endpoints:
    - nginx-storage/nginx-service(created)
  v1/Namespace:
    - nginx-storage(created)
  v1/PersistentVolume:
    - pvc-6cef2247-4eef-4a72-b4b5-2f9824f56532(skipped)
  v1/PersistentVolumeClaim:
    - nginx-storage/nginx-pv-claim(created)
  v1/Pod:
    - nginx-storage/nginx-deployment-9874454f9-qfdl2(created)
    - nginx-storage/nginx-deployment-9874454f9-qn9bm(created)
  v1/Service:
    - nginx-storage/nginx-service(created)
  v1/ServiceAccount:
    - nginx-storage/default(skipped)

another question is whether both Kubernetes cluster version has to be the same then only velero migration will work. is that something mandatory rule for velero migration?

let me know whether I am missing anything while performing this task ...

**Comment by reasonerjt** [comment]
We need to double check the backup spec, pvb/pvr CRs 

Please provide the debug bundle with backup and restore name specified in the parameters.

**Comment by subhankar-banerjee** [comment]
find the details --

backup command:  velero backup create nginxpvc --include-namespaces nginx-storage --wait
restore command:  velero restore create nginxpvc-restore --from-backup nginxpvc --restore-volumes=true

[bundle-2023-11-27-08-36-39.tar.gz](https://github.com/vmware-tanzu/velero/files/13471729/bundle-2023-11-27-08-36-39.tar.gz)

**Comment by subhankar-banerjee** [comment]
can someone please confirm where could be the issue, I have shared all the details as requested

**Comment by draghuram** [comment]
The flag "--default-volumes-to-fs-backup=true" has nothing to do with whether the backup goes to on-prem or to cloud. There are different ways of enabling file system backups and they are documented here: https://velero.io/docs/v1.12/file-system-backup/#to-back-up. Of course, docs can always be improved and feel free to submit a PR.
