### ISSUE TITLE
Make BackedUpItems thread safe

### ISSUE THREAD

**Issue by anshulahuja98** [vmware-tanzu/velero#7148]
**Describe the problem/challenge you have**

Tracking issue to make BackedUpItems thread safe. 

**Describe the solution you'd like**

If we wish to achieve any level of concurrency across backup operations or restore operations, we need to make sure all of the intermediate trackers which are used are thread safe such that they don't run into concurrency issue. 

Similar to the impl of SkippedPvTracker - https://github.com/vmware-tanzu/velero/blob/a9e80d585ad83884e271d595d3aba0b21bb01da3/pkg/backup/pv_skip_tracker.go#L43
We need to implement BackupUpItems tracker 
https://github.com/vmware-tanzu/velero/blob/5d81317d5e0c4efc91e76cdbaad56ce21eed2456/pkg/backup/item_backupper.go#L170C1-L171C63
 with mutex lock such that multiple operations can update the status in parallel without concurrency issues.
Setting ground work for: https://github.com/vmware-tanzu/velero/issues/6165 | https://github.com/vmware-tanzu/velero/pull/6860

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
@anshulahuja98 I know we had some discussion but could you add more details in this issue to make it more self-contained?

**Comment by anshulahuja98** [comment]
Updated the issue description.
@reasonerjt we can mark this as backlog for now, we don't need to track in 1.14
I'll meanwhile try to get someone from my team to work on this.

**Comment by sseago** [comment]
Reassigning to myself since this is needed for https://github.com/vmware-tanzu/velero/issues/8334
