### ISSUE TITLE
Add more hooks info to backup/restore CR

### ISSUE THREAD

**Issue by allenxu404** [vmware-tanzu/velero#7154]
**Describe the problem/challenge you have**
With the PR(https://github.com/vmware-tanzu/velero/pull/7117) merged, backup/restore CR has `hooksAttempted` and `hooksFailed` as two initial hook metadata. We could adding more hook info to  backup/restore CR to help track the status of hooks. 

**Describe the solution you'd like**
With the hooksTracker introduced in PR(https://github.com/vmware-tanzu/velero/pull/7117), we can track additional details like hook error information and skipped hooks.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by allenxu404** [comment]
@anshulahuja98  After further review, I think it's best to leave the hook information as-is without adding separate fields for hook errors and skipped hooks:

As for hook errors, currently the information around hook errors  are already captured in backup log and restore result and displayed prominently under `Errors` section in backup/restore describe output. Putting those errors again under the `Hook status` section may lead to repetitive data when viewing describe output.

As for skipped hooks, currently any hooks that are not eventually executed are counted as failed hooks and the detailed error messages are recorded to help user know they are skipped . Add a separate skipped hooks field could potentially confuse users because skipped hooks are already included in `hooksFailed` field. 
https://github.com/vmware-tanzu/velero/blob/ff456804309f54f0e49f4e23a10a5a6298631211/internal/hook/wait_exec_hook_handler.go#L239

What's your thought?

**Comment by anshulahuja98** [comment]
That's seems fine for now.
Over time however we can look into improving the error logs related to hooks, anywhere we see discrepancy.

CC: @Shashank1306s to share if he has any thoughts.

**Comment by allenxu404** [comment]
> Over time however we can look into improving the error logs related to hooks, anywhere we see discrepancy.

Agreed.

I will modify the doc related to hooks to clarify the hook information we currently collect.
