### ISSUE TITLE
Implement or discard from design "--pod-volume-backup-uploader" install flag.

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#7155]
https://github.com/vmware-tanzu/velero/blob/b8604b6a89d11fe54a1228c51c52947bc2d2e636/design/Implemented/unified-repo-and-kopia-integration/unified-repo-and-kopia-integration.md?plain=1#L436

**Comment by sseago** [comment]
This is currently handled via the `--uploader-type` and `--default-volumes-to-fs-backup` options -- best thing to do is probably to just remove references to "pod-volume-backup-uploader" in the design doc.

**Comment by yanggangtony** [comment]
>> best thing to do is probably to just remove references to "pod-volume-backup-uploader" in the design doc
I will do the clean work .
