### ISSUE TITLE
unknown flag: --use-restic

### ISSUE THREAD

**Issue by pbs-jyu** [vmware-tanzu/velero#7160]
**What steps did you take and what happened:**

installed Velero client with V1.12.2.  My storage is DELL Isilon.  I did not find a storage plugin for it.  So I tried to install velero with a tag of "--use-restic" and got an error of "unknown flag".  run "velero install --help"  did not show "use-restic".  I have tried Velero client V1.11 same error.  I have checked the compatibility it shows those two versions are supported for Kubernetes V1.26.       

**What did you expect to happen:**

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): v1.12.2
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):  v1.27 for client.  V1.26 for server
- Kubernetes installer & version:
- Cloud provider or hardware configuration:  We are running eks anywhere on prem.  We use S3 for object backup.
- OS (e.g. from `/etc/os-release`):  admin machine is ubuntu. 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by mateusoliveira43** [comment]
This flag is from old version of Velero, use `--uploader-type=restic`

Reference: https://velero.io/docs/v1.12/upgrade-to-1.12/#upgrade-from-version-lower-than-v1100

**Comment by mateusoliveira43** [comment]
For maintainers, I think this is the third time someone asks about this old flag, can we do something to have this more clear in the docs?

**Comment by pbs-jyu** [comment]
Hi, Mateus  thanks a lot for your prompt response. 

I'm thinking use the following:
	  --use-node-agent \
	  --uploader-type restic
	  
it will be something like:	  
velero install \
    --provider aws \
    --use-node-agent \
    --plugins velero/velero-plugin-for-aws:v1.8.2 \ 
    --bucket my-bucket \
    --secret-file ./my-credentials-velero.yaml \
    --backup-location-config region=us-east-1 \
    --snapshot-location-config region=us-east-1 \
    --uploader-type restic

**Comment by yanggangtony** [comment]
I saw there is still some test code to compatible the ```---use-restic and --uploader-type=restic``` . 
Still need a clean code for test-codes.

**Comment by pbs-jyu** [comment]
We use Dell isilon.  There is no snapshot plugin for it.  without Restic, We can restore the pod/deployment, but we can’t restore the PVC.  I have installed the Velero with Restic which allowed me restore the pod in a functioning stage which has the PVC mounted and everything seems fine.  But We also end up backup tounds of informtion from the Isilon shares to S3 bucket.  We need is to restore any of the pods which has the mounts to the pvc in a previous working stage.  But do not want to backup our storage content to S3.  Any solution to this?

**Comment by Lyndon-Li** [comment]
@pbs-jyu 
Looks like the original issue has been solved. By the way, Velero is now having Kopia as the default uploader and deprecating Restic, so it is recommended to switch to Kopia uploader.

For the second question, as far as I can understand, you are requesting to back up pods, PVCs and PVs objects but not back up the data in the volume, if my understanding is right, for fs-backup, you can just use the [opt-out options](https://velero.io/docs/v1.12/file-system-backup/#using-the-opt-out-approach:~:text=the%20two%20approaches.-,Using%20the%20opt%2Dout%20approach,-In%20this%20approach) to filter out the volumes from the backup, then the data will not be backed up.

**Comment by Lyndon-Li** [comment]
@pbs-jyu Since the original problem has been solved, I will close the current issue. For any further questions about the second topic, please feel free to open a new issue.
