### ISSUE TITLE
Velero backup not working for Jenkins backend Ceph storage on-premises for Kubernetes PVC 

### ISSUE THREAD

**Issue by subhankar-banerjee** [vmware-tanzu/velero#7166]
I have installed Velero 1.12.1 on-premises to take Kubernetes PVC backup for Jenkins 

[rke@kube-master ~]$ velero version
Client:
Version: v1.12.1
Git commit: https://github.com/vmware-tanzu/velero/commit/5c4fdfe147357ec7b908339f4516cd96d6b97c61
Server:
Version: v1.12.1
[rke@kube-master ~]$

backend storage used Ceph 13.2.10

Valero install command ---

velero install
--provider aws
--plugins velero/velero-plugin-for-aws:v1.8.1
--bucket rancher-k8s-backup
--secret-file ./credentials-minio
--use-volume-snapshots=false
--use-node-agent
--backup-location-config
region=minio,s3ForcePathStyle="true",s3Url=http://10.128.0.55:9000/

Jenkins running fine in the K8s cluster, able to access UI from the browser, and able to run the build without any error but while taking backup I am able to get this error ---

[rke@kube-master rke-k8s]$ velero backup create jenkinspvc --default-volumes-to-fs-backup=true --include-namespaces mm-ops-jenkins --wait
Backup request "jenkinspvc" submitted successfully.
Waiting for backup to complete. You may safely press ctrl-c to stop waiting - your backup will continue in the background.
.....
Backup completed with status: PartiallyFailed. You may check for more information using the commands `velero backup describe jenkinspvc` and `velero backup logs jenkinspvc`.
[rke@kube-master rke-k8s]$

[rke@kube-master rke-k8s]$ velero backup describe jenkinspvc
Name:         jenkinspvc
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.25.9
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=25

Phase:  PartiallyFailed (run `velero backup logs jenkinspvc` for more information)

Warnings:
  Velero:     <none>
  Cluster:    <none>
  Namespaces:
    mm-ops-jenkins:   resource: /pods name: /mm-jenkins-0

Errors:
  Velero:    name: /mm-jenkins-0 error: /pod volume backup failed: error to initialize data path: error to boost backup repository connection default-mm-ops-jenkins-kopia: error to connect backup repo: error to connect repo with storage: error to connect to repository: repository not initialized in the provided storage
             name: /mm-jenkins-0 error: /pod volume backup failed: error to initialize data path: error to boost backup repository connection default-mm-ops-jenkins-kopia: error to connect backup repo: error to connect repo with storage: error to connect to repository: repository not initialized in the provided storage
             name: /mm-jenkins-0 error: /pod volume backup failed: error to initialize data path: error to boost backup repository connection default-mm-ops-jenkins-kopia: error to connect backup repo: error to connect repo with storage: error to connect to repository: repository not initialized in the provided storage
             name: /mm-jenkins-0 error: /pod volume backup failed: error to initialize data path: error to boost backup repository connection default-mm-ops-jenkins-kopia: error to connect backup repo: error to connect repo with storage: error to connect to repository: repository not initialized in the provided storage
             name: /mm-jenkins-0 error: /pod volume backup failed: error to initialize data path: error to boost backup repository connection default-mm-ops-jenkins-kopia: error to connect backup repo: error to connect repo with storage: error to connect to repository: repository not initialized in the provided storage
  Cluster:    <none>
  Namespaces: <none>

Namespaces:
  Included:  mm-ops-jenkins
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Or label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto
Snapshot Move Data:          false
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2023-11-30 08:30:10 +0000 UTC
Completed:  2023-11-30 08:30:15 +0000 UTC

Expiration:  2023-12-30 08:30:10 +0000 UTC

Total items to be backed up:  68
Items backed up:              68

Velero-Native Snapshots: <none included>

kopia Backups (specify --details for more information):
  Failed:  5
[rke@kube-master rke-k8s]$ 

debug bundle attached

[bundle-2023-11-30-08-31-27.tar.gz](https://github.com/vmware-tanzu/velero/files/13510430/bundle-2023-11-30-08-31-27.tar.gz)

**Comment by Lyndon-Li** [comment]
Please follow [this comment](https://github.com/vmware-tanzu/velero/issues/7157#issuecomment-1833138094) and share the screenshot of velero/kopia/<backing up namespace> prefix of your object store.

**Comment by subhankar-banerjee** [comment]
I am doing FSB backup and restore between 2 clusters... but currently backup is failing

**Comment by subhankar-banerjee** [comment]
for the object store, I used Minio, because It failed so I can't see Kopia in object store 

![image](https://github.com/vmware-tanzu/velero/assets/64698759/351c45d4-adfd-4b3f-bf35-305701faf88e)

**Comment by Lyndon-Li** [comment]
This is the cause, the kopia data has disappeared somehow, so fs-backup cannot connect to the existing backup repository for backup.
To fix this problem, just delete the backuprepository CR and retry a new backup.

**Comment by subhankar-banerjee** [comment]
but how can I delete that repo I am unable to find the command using : velero repo --help

**Comment by subhankar-banerjee** [comment]
thanks, I resolved the issue ...
