### ISSUE TITLE
Restore failed because of patch labels returns not found

### ISSUE THREAD

**Issue by 27149chen** [vmware-tanzu/velero#7180]
**What steps did you take and what happened:**

1. there is a deployment with 3 replicasets (a, b, c) and set the revision limit to 3
2. backup it and restore it to another cluster
3. update the deployment in both cluster, replicasets become to bcd(source), and bce(target)
4. backup it and restore it again with override policy
5. reatore failed

**What did you expect to happen:**

restore succeeded

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

problem is in function `updateBackupRestoreLabels`, it tries to patch replicaset labels, but the replicaset is already deleted by k8s, so a not found error returns

possible steps:
1. velero restores replicaset c and finds it is exsiting
2. velero updates replicaset c labels
3. velero restores replicaset d
4. velero restores replicaset b and finds it is exsiting
5. **k8s delete replicaset b because current replica count is 4**
6. velero updates replicaset b labels and returns not found

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by danfengliu** [comment]
Hi @27149chen , what's the version you're using? I'm not able to reproduce it on main branch as you can see test steps below:

Source Cluster: 
--------------------------------------------
First deployment:
1. a: nginx-deployment-6c879ddf5 
2. b: nginx-deployment-5d58c48c78
3. c: nginx-deployment-54cb5dd97 
--------------------------------------------
After a deployment update:
1. d: nginx-deployment-799b8cff6
2. b: nginx-deployment-5d58c48c78
3. c: nginx-deployment-54cb5dd97 
--------------------------------------------
```
$ k get rs -n $ns
NAME                          DESIRED   CURRENT   READY   AGE
nginx-deployment-54cb5dd97    2         2         2       9s
nginx-deployment-5d58c48c78   0         0         0       29s
nginx-deployment-6c879ddf5    0         0         0       72s
$ velero create backup --include-namespaces nginx-example backup-ns-1 --wait
Backup request "backup-ns-1" submitted successfully.
Waiting for backup to complete. You may safely press ctrl-c to stop waiting - your backup will continue in the background.
.....
Backup completed with status: Completed. You may check for more information using the commands `velero backup describe backup-ns-1` and `velero backup logs backup-ns-1`.
$  k edit deploy -n $ns
Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "nginx" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/nginx-deployment edited
$  k get rs -n $ns
NAME                          DESIRED   CURRENT   READY   AGE
nginx-deployment-54cb5dd97    1         1         1       97s
nginx-deployment-5d58c48c78   0         0         0       117s
nginx-deployment-6c879ddf5    0         0         0       2m40s
nginx-deployment-799b8cff6    2         2         1       2s
$  k get rs -n $ns
NAME                          DESIRED   CURRENT   READY   AGE
nginx-deployment-54cb5dd97    0         0         0       101s
nginx-deployment-5d58c48c78   0         0         0       2m1s
nginx-deployment-799b8cff6    2         2         2       6s
$  velero create backup --include-namespaces nginx-example backup-ns-1-after --wait
Backup request "backup-ns-1-after" submitted successfully.
Waiting for backup to complete. You may safely press ctrl-c to stop waiting - your backup will continue in the background.
....
Backup completed with status: Completed. You may check for more information using the commands `velero backup describe backup-ns-1-after` and `velero backup logs backup-ns-1-after`.

```

Target Cluster:

--------------------------------------------
Restored for the first time and have a deployment update:
1. e: nginx-deployment-6f87c86798
2. b: nginx-deployment-5d58c48c78
3. c: nginx-deployment-54cb5dd97 
--------------------------------------------
After restore from backup of updated deployment:
As you can see "d" and "c" are restored with no error.
1. d: nginx-deployment-799b8cff6
2. c: nginx-deployment-54cb5dd97  
3. e: nginx-deployment-6f87c86798 (is not in backup so it stays as it is newer "b" in backup, "b" is deleted according to revisionHistoryLimit: 2 in deployment)
--------------------------------------------
```
$ velero create restore --from-backup backup-ns-1 --wait
Restore request "backup-ns-1-20231211043410" submitted successfully.
Waiting for restore to complete. You may safely press ctrl-c to stop waiting - your restore will continue in the background.
.
Restore completed with status: Completed. You may check for more information using the commands `velero restore describe backup-ns-1-20231211043410` and `velero restore logs backup-ns-1-20231211043410`.
$ k1 get rs -n nginx-example
NAME                          DESIRED   CURRENT   READY   AGE
nginx-deployment-54cb5dd97    2         2         0       13s
nginx-deployment-5d58c48c78   0         0         0       13s
nginx-deployment-6c879ddf5    0         0         0       13s

$ k1 edit deploy -n nginx-example
Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "nginx" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/nginx-deployment edited

$  k1 get rs -n nginx-example
NAME                          DESIRED   CURRENT   READY   AGE
nginx-deployment-54cb5dd97    1         1         0       64s
nginx-deployment-5d58c48c78   0         0         0       64s
nginx-deployment-6c879ddf5    0         0         0       64s
nginx-deployment-6f87c86798   2         2         1       2s

$  k1 get rs -n nginx-example
NAME                          DESIRED   CURRENT   READY   AGE
nginx-deployment-54cb5dd97    0         0         0       65s
nginx-deployment-5d58c48c78   0         0         0       65s
nginx-deployment-6f87c86798   2         2         2       3s

$ k1 get rs -n nginx-example
NAME                          DESIRED   CURRENT   READY   AGE
nginx-deployment-54cb5dd97    0         0         0       79s
nginx-deployment-5d58c48c78   0         0         0       79s
nginx-deployment-6f87c86798   2         2         2       17s

$ velero create restore --from-backup backup-ns-1-after  --existing-resource-policy=update --wait
Restore request "backup-ns-1-after-20231211043559" submitted successfully.
Waiting for restore to complete. You may safely press ctrl-c to stop waiting - your restore will continue in the background.
..
Restore completed with status: Completed. You may check for more information using the commands `velero restore describe backup-ns-1-after-20231211043559` and `velero restore logs backup-ns-1-after-20231211043559`.
$ k1 get rs -n nginx-example
NAME                          DESIRED   CURRENT   READY   AGE
nginx-deployment-54cb5dd97    0         0         0       2m4s
nginx-deployment-6f87c86798   0         0         0       62s
nginx-deployment-799b8cff6    2         2         2       15s

```

**Comment by 27149chen** [comment]
it is not 100% repreducable, see the `possible steps`, only when k8s deleted the rs before velero tries to change its label

**Comment by danfengliu** [comment]
Yes, normally, patch label should be a step in the restore item transaction, but in this case, patch label failure might a expected behavior, it should not affect restore result, this is indeed a bug, and we will working on fix it carefully since there are other situation involved.
