### ISSUE TITLE
Offload CSI snapshots to S3 without privileged access / hostpath

### ISSUE THREAD

**Issue by dmaggo** [vmware-tanzu/velero#7188]
**Describe the problem/challenge you have**

Offload CSI snapshots to another back up location such as S3 requires privileged activation and access to hostpath. See https://velero.io/docs/main/csi-snapshot-data-movement/

**Describe the solution you'd like**

Wouldn't it be possible in cases where the storage provider supports native snapshot (e.g. vsphere csi driver), that Velero does not need to access the volume over a hostpath? 
As e.g. like Portworx do it https://docs.portworx.com/portworx-backup-on-prem/use-px-backup/backup-restore/create-backup/backup-csi-snapshots#offload-csi-snapshots-to-back-up-location

Or am I missing something and there are reasons why Velero cannot go this way?

Thanks

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by draghuram** [comment]
CloudCasa also offloads snapshots to S3 by directly creating a PVC from the snapshot and mounting it in a mover Pod. This way, you don't need privileged access. I think Velero does create a temporary Pod but actual backup still happens from the node agent Pod which requires privileged access. I believe this allows existing file system code to be used but I will let maintainers to chime in.

**Comment by dmaggo** [comment]
In our company, enabling privileged access in our TKGi infrastructure violates our compliant specifications, so I cannot use the Datamover. Unfortunately, this leaves us with the copied (backup) PVs in the vsphere CNS and you cannot create as many of these copies as you want.

**Comment by Lyndon-Li** [comment]
@dmaggo If you are a TKG user, please contact TKG supports for helps, they will give more and better help.

**Comment by dmaggo** [comment]
From the documentation: https://velero.io/docs/main/csi-snapshot-data-movement/

VMware Tanzu Kubernetes Grid Integrated Edition (formerly VMware Enterprise PKS)

You need to enable the Allow Privileged option in your plan configuration so that Velero is able to mount the hostpath.

The hostPath should be changed from /var/lib/kubelet/pods to /var/vcap/data/kubelet/pods

hostPath:
  path: /var/vcap/data/kubelet/pods

**Comment by Lyndon-Li** [comment]
Velero + vsphere-plugin doesn't go through CSI snapshot data movement, so it doesn't require host-path.

**Comment by dmaggo** [comment]
Maybe I understand it all wrong, but even in the "Install Velero Sphere Plugin" documentation it says that "allow privileged" must be enabled. Can you or someone else please explain to me what the misunderstanding is?

![image](https://github.com/vmware-tanzu/velero/assets/38687952/61a6597c-2caf-44ca-a966-8e53a0cacb95)

**Comment by Lyndon-Li** [comment]
@draghuram
Velero+vsphere-plugin doesn't go the same path with Velero data mover so it doesn't require host-path access. This is all I know, but this document is out of my knowledge and the scope of Velero upstream. Please confirm it with TKG supports.

**Comment by Lyndon-Li** [comment]
About the other topic (doing data mover in a pod), we are planning to do similar things in a larger scope to solve some more problems, see issue #7198.

**Comment by Lyndon-Li** [comment]
Looks like we have reach the agreement for the both topics, then I will close this issue and keep #7198 open.
Feel free to reopen this issue for any further requests.
