### ISSUE TITLE
restore-wait (restic) data not found

### ISSUE THREAD

**Issue by alexfouche** [vmware-tanzu/velero#7192]
_(looks similar to #669 which was closed due to lack of activity)_

**What steps did you take and what happened:**

I am restoring pod and associated PVC (Restore object in the pastbin below)

Backup were  done with FSB (Restic) for PVC volumes (using Longhorn PVC provisionner in case that matters)

The restoring process for `pod,pvc,pv` works, PVC is created, PV is provisionned properly, ...

Within the restored pod, the container for FSB restore called `restore-wait` starts with a lot of these messages (like one every second, i should have printed the timestamps), until finally the backup is found and Restic restores data.

Then a permission issue as the last message, which i do not know comes from where

```
(...) tens and tens of Not found messages

Not found: /restores/data/.velero/95f378aa-464c-4fb9-9246-88aa310e4db8
Not found: /restores/data/.velero/95f378aa-464c-4fb9-9246-88aa310e4db8

(...) again and again and again

Not found: /restores/data/.velero/95f378aa-464c-4fb9-9246-88aa310e4db8
Not found: /restores/data/.velero/95f378aa-464c-4fb9-9246-88aa310e4db8
Not found: /restores/data/.velero/95f378aa-464c-4fb9-9246-88aa310e4db8
Found /restores/data/.velero/95f378aa-464c-4fb9-9246-88aa310e4db8All restic restores are done
unlinkat /restores/data/.velero/95f378aa-464c-4fb9-9246-88aa310e4db8: permission denied
Stream closed EOF for aftest9/blabla-elasticsearch-master-0 (restore-wait)
```

**What did you expect to happen:**

I expect the usual Restic restore outputs, and not any of these weird repeating messages, which in the end show the backup is found anyway

I have experience with Restic and Restic restores outside of Velero and Kubernetes, and Restic restores its "snapshots" from its repository. Never have i seen these kind of message, and to me these do not seem to belong to Restic, but rather some Velero message

The restore seems to be fine though, and data is there.

**The following information will help us better understand what's going on**:

pastebin: [velero restore describe aftest9 --details](https://pastebin.com/61NYCvgS)

**Environment:**

```
# velero version
Client:
	Version: v1.12.2
	Git commit: 06d12dec4030703cb46b2699ca434cdabd9edbb0
Server:
	Version: v1.12.2
```

**Comment by blackpiglet** [comment]
@alexfouche 
Except for the `permission denied` error, I think there is no error for the restic-restore-helper process.
`/restores/data/.velero/95f378aa-464c-4fb9-9246-88aa310e4db8`
This is the expected PodVolumeRestore `done file` generated by the `node-agent` process.
There are a lot of `not found` message because the `restic-restore-helper` check the `done file` every second.

IMO, the `permission denied` error is raised because the `restic-restore-helper` InitContainer's privilege is lower than the `node-agent` pod's.

**Comment by alexfouche** [comment]
Well OK, makes sense, if you are a technical person aware of how Velero
internals work and happen to have read this ticket ;-)

Otherwise, I do not think this is very user friendly, I am astonished that
I am the only one to report it.

Can these messages be reworked to make it more relevant that the Velero
process is still waiting for FSB/restic to complete, instead of looking
frightening that backup may be missing?
And that this is simply an expected permission problem in the context of
the pod?

Le mar. 12 déc. 2023, 11:14, blackpiglet ***@***.***> a
écrit :

**Comment by blackpiglet** [comment]
Sure. I will make some changes to the log content.

Although there is no simple solution, I wouldn't argue that this permission issue is expected. 
I'll see if I can use lower priority to create the completed file on the node-agent side to fix the issue.

**Comment by ckittelmann** [comment]
Just to confirm: 
we also facing the permission issue since update from 1.11.1 to 1.12.3. After rollback everything works fine again

**Comment by blackpiglet** [comment]
@ckittelmann 
I did a test with the v1.11.1 Velero. I also met the permission issue.

``` bash
$ k -n restore logs hello-app-7b5945ddc5-rzpdp -c restore-wait -f  
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Not found: /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3
Found /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3All restic restores are done
unlinkat /restores/sdk-volume/.velero/0eb4c2f4-d55b-4913-bf91-e33a7754a4c3: permission denied
```

There is a ConfigMap to set the restore-helper's running user setting. I think we can use that to resolve the permission issue.
https://velero.io/docs/v1.13/file-system-backup/#customize-restore-helper-container

**Comment by ckittelmann** [comment]
@blackpiglet you are right! 
We didn't saw this before as the restore-wait init container was not crashing when unlinkat fails with permission denied.

```
$ kubectl logs storage-test -c restore-wait -f -n velero
Not found: /restores/data/.velero/42658092-5082-4cfe-aaf7-28350730c0f1
...
Not found: /restores/data/.velero/42658092-5082-4cfe-aaf7-28350730c0f1
Found /restores/data/.velero/42658092-5082-4cfe-aaf7-28350730c0f1All restic restores are done
unlinkat /restores/data/.velero/42658092-5082-4cfe-aaf7-28350730c0f1: permission denied
```

After update to 1.12.3 the restore-wait container crashes when unlinkat failes with permission denied

We will check the ConfigMap settings, at the moment we don't have this ConfigMap

Thx @blackpiglet!

**Comment by sarahdepillis** [comment]
What was the resolution for this? I am getting the same permission denied error but do already have the config map in place.

**Comment by blackpiglet** [comment]
@sarahdepillis 
https://github.com/vmware-tanzu/velero/issues/7192#issuecomment-1916005694
Please check this comment.

**Comment by jwittekind** [comment]
Hey everyone,

i'm using velero 1.16.1 with bitnami chart 10.0.8.
Now i'm experiencing the same issue:

````
The filesystem restore done file /restores/data/.velero/1588ee6f-2d16-4bd5-ae00-5efb950ecdb9 is not found yet. Retry later.
The filesystem restore done file /restores/data/.velero/1588ee6f-2d16-4bd5-ae00-5efb950ecdb9 is not found yet. Retry later.
The filesystem restore done file /restores/data/.velero/1588ee6f-2d16-4bd5-ae00-5efb950ecdb9 is not found yet. Retry later.
The filesystem restore done file /restores/data/.velero/1588ee6f-2d16-4bd5-ae00-5efb950ecdb9 is not found yet. Retry later.
The filesystem restore done file /restores/data/.velero/1588ee6f-2d16-4bd5-ae00-5efb950ecdb9 is not found yet. Retry later.
Found the done file /restores/data/.velero/1588ee6f-2d16-4bd5-ae00-5efb950ecdb9
Found the done file /restores/empty-dir/.velero/1588ee6f-2d16-4bd5-ae00-5efb950ecdb9
All restic restores are done
unlinkat /restores/data/.velero/1588ee6f-2d16-4bd5-ae00-5efb950ecdb9: permission denied
````

I tried to apply the mentioned solution via a config map in terraform:

```
resource "kubernetes_manifest" "restic_restore_config" {
  manifest = {
    apiVersion = "v1"
    kind       = "ConfigMap"
    metadata = {
      name      = "restic-restore-action-config"
      namespace = "velero"
      labels = {
        "velero.io/plugin-config" = ""
        "velero.io/restic"        = "RestoreItemAction"
      }
    }
    data = {
      secCtxRunAsUser                = "0"
      secCtxRunAsGroup               = "0"
      secCtxAllowPrivilegeEscalation = "true"
    }
  }
}
```

Unfortuntely i do not see this taking effect on my init containers.
They still fail. Do i have to configure the `runAsUser`, `runAsGroup` and `allowPrivilegeEscalation` in my initContainer of velero-plugin-for-aws or other `securityContext`?
