### ISSUE TITLE
Microservice Velero's data movement activities

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#7198]
There are some cases require Velero's data movement activities to be in a dedicate microservice in a dedicate pod:

- Velero's fs-backup/restore, snapshot data mover requires to access volume data through host path (and even privileged mode in some environments), which makes challenge to some users
- Velero accesses the backup storage from either Velero server pod or node-agent pods, including the resource data upload/download, fs-backup and data mover. Consequently, when the backup storage must be represented by a Kubernetes flavor volume (i.e., persistent volume, e.g., nfs storage, COSI), the volume must be mounted to either Velero server pod or node-agent pods, which causes Velero server/node-agent restart, this is almost not accepted
- There may be requirements to control resource (i.e., cpu, memory) request/limit in a granular manner, e.g., control them per backup/restore of a volume
- This increases the resilience, crash of one activity won't affect the others
- This prevents unnecessary full backup. Velero's fs uploaders support file level incremental backup by comparing the file name and metadata. However, at present the files are visited by host path, while pod and PVC's ID are part of the host path, so once the pod is recreated, the same file is regarded as a different file since the pod's ID has been changed.

If we can make VGDP instances and the backup storage direct accesses as dedicate microservices in dedicate pods, the above problem will be solved

**Comment by reasonerjt** [comment]
This is a valuable improvement, but I'm not sure if we can finish all the dev work in v1.14.  Therefore, let's use this issue to track the design work, and we'll revisit it before feature freeze to see if we can implement it in v1.14.
