### ISSUE TITLE
The DataUpload backup cannot find parent snapshot case not work expectedly

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#7209]
**What steps did you take and what happened:**

There should be such log printed in the node-agent pod
```
Failed to load previous snapshot xxxxxx from kopia, fallback to full backup
```

But the following logs are printed.
```
time="2023-12-14T15:29:13Z" level=info msg="Starting backup" controller=dataupload dataupload=velero/1-1-13-8-2-qdspw logSource="pkg/uploader/provider/kopia.go:145" parentSnapshot= path="/host_pods/952e02fd-a800-4fc4-a746-5d3827b1e47a/volumes/kubernetes.io~csi/pvc-0247c836-737e-4891-9bbf-31f8198bdc1a/mount" realSource=upgrade/my-pvc
time="2023-12-14T15:29:13Z" level=info msg="Start to snapshot..." controller=dataupload dataupload=velero/1-1-13-8-2-qdspw logSource="pkg/uploader/kopia/snapshot.go:243" parentSnapshot= path="/host_pods/952e02fd-a800-4fc4-a746-5d3827b1e47a/volumes/kubernetes.io~csi/pvc-0247c836-737e-4891-9bbf-31f8198bdc1a/mount" realSource=upgrade/my-pvc
time="2023-12-14T15:29:13Z" level=info msg="Searching for parent snapshot" controller=dataupload dataupload=velero/1-1-13-8-2-qdspw logSource="pkg/uploader/kopia/snapshot.go:258" parentSnapshot= path="/host_pods/952e02fd-a800-4fc4-a746-5d3827b1e47a/volumes/kubernetes.io~csi/pvc-0247c836-737e-4891-9bbf-31f8198bdc1a/mount" realSource=upgrade/my-pvc
time="2023-12-14T15:29:24Z" level=info msg="Reconcile 1-1-13-8-2-qdspw" controller=dataupload dataupload=velero/1-1-13-8-2-qdspw logSource="pkg/controller/data_upload_controller.go:113"
time="2023-12-14T15:29:24Z" level=info msg="Data upload is in progress" controller=dataupload dataupload=velero/1-1-13-8-2-qdspw logSource="pkg/controller/data_upload_controller.go:292"
time="2023-12-14T15:29:32Z" level=info msg="Created snapshot with root kddd6faf958f2682276174c6806bdf946 and ID c4555a5e8443bccde3fcd989b8a54ede in 18s" controller=dataupload dataupload=velero/1-1-13-8-2-qdspw logSource="pkg/uploader/kopia/snapshot.go:297" parentSnapshot= path="/host_pods/952e02fd-a800-4fc4-a746-5d3827b1e47a/volumes/kubernetes.io~csi/pvc-0247c836-737e-4891-9bbf-31f8198bdc1a/mount" realSource=upgrade/my-pvc
time="2023-12-14T15:29:32Z" level=info msg="Async fs backup data path completed" dataupload=1-1-13-8-2-qdspw logSource="pkg/controller/data_upload_controller.go:360"
```

IMO, this piece of code is questionable. The DataUpload snapshot creation scenario doesn't pass in the parent snapshot ID.
https://github.com/vmware-tanzu/velero/blob/ea6c8ca127644fcbad831b02bd7df103906af540/pkg/controller/data_upload_controller.go#L347

**What did you expect to happen:**

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
This is as the expectation. 
Data mover backup's behavior around here is different from fs-backup:

1. For fs-backup, the parent snapshot ID is retrieved by Velero from the previous PVB and passed down to VGDP and finally to Kopia uploader
2. However, Kopia uploader has the ability to automatically retrieve the parent snapshot(s) from the repository. So Velero built-in data mover(VBDM) just gives empty string to the VGDP

So "Failed to load previous snapshot" error only happens to fs-backup or the cases that a parent snapshot is provided to VGDP. We keep this difference for back compatibility consideration for fs-backup, because Restic path doesn't support this, so in future, we can remove it.

**Comment by blackpiglet** [comment]
Close.
This is not a functional issue.
It's hit during the E2E test. The E2E test case has already been modified accordingly.
