### ISSUE TITLE
Fail to backup using Azure native snapshot with useAAD enabled

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#7210]
**What steps did you take and what happened:**

1. Install Velero with cmd below:
```
velero install \
    --provider azure \
    --plugins velero/velero-plugin-for-microsoft-azure:main\
    --bucket mybucket \
    --secret-file ./credentials-velero \
    --backup-location-config useAAD="true",resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,storageAccount=$AZURE_STORAGE_ACCOUNT_ID,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID \
    --snapshot-location-config apiTimeout=30s,resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP,subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID \
     --use-node-agent --use-volume-snapshots

2. Backup a workload which has PVs using Azure native snapshot;
3. Got `PartiallyFailed` result and logs with errors as below:
```
  Cluster:   resource: /persistentvolumes name: /pvc-c16084bd-ee38-461e-ad06-66c275fc2284 message: /Error getting volume snapshotter for volume snapshot location error: /rpc error: code = Unknown desc = config has invalid keys [subscriptionId]; valid keys are [resourceGroup apiTimeout resourceGroup incremental tags credentialsFile]
             resource: /persistentvolumes name: /pvc-e72226b7-4aab-47e4-a817-8ac0f2706032 message: /Error getting volume snapshotter for volume snapshot location error: /rpc error: code = Unknown desc = config has invalid keys [subscriptionId]; valid keys are [resourceGroup apiTimeout resourceGroup incremental tags credentialsFile]
             resource: /persistentvolumes name: /pvc-2191a989-8d83-4746-b787-b038286f9495 message: /Error getting volume snapshotter for volume snapshot location error: /rpc error: code = Unknown desc = config has invalid keys [subscriptionId]; valid keys are [resourceGroup apiTimeout resourceGroup incremental tags credentialsFile]
             resource: /persistentvolumes name: /pvc-6d57d452-ca33-434c-bb6a-937c2a23977c message: /Error getting volume snapshotter for volume snapshot location error: /rpc error: code = Unknown desc = config has invalid keys [subscriptionId]; valid keys are [resourceGroup apiTimeout resourceGroup incremental tags credentialsFile]
             resource: /persistentvolumes name: /pvc-8218f6c6-94e5-4c1a-89e6-7c864acd5356 message: /Error getting volume snapshotter for volume snapshot location error: /rpc error: code = Unknown desc = config has invalid keys [subscriptionId]; valid keys are [resourceGroup apiTimeout resourceGroup incremental tags credentialsFile]
`

**What did you expect to happen:**
Backup with `Completed` status.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
@danfengliu You can remove the `subscriptionId` from VSL config to workaround it, I'll fix it
