### ISSUE TITLE
Getting error for velero restore describe command with Velero CLI v1.12.2

### ISSUE THREAD

**Issue by ranjeetsingh-23** [vmware-tanzu/velero#7213]
Getting error while running  following command with Velero CLI v1.12.2

`Resource List:  <error getting restore resource list: DownloadRequest.velero.io "cs-restore-20231215090725-e439987a-a151-44c1-bde6-8008b0af8d97" is invalid: spec.target.kind: Unsupported value: "RestoreResourceList": supported values: "BackupLog", "BackupContents", "BackupVolumeSnapshots", "BackupItemSnapshots", "BackupResourceList", "RestoreLog", "RestoreResults", "CSIBackupVolumeSnapshots", "CSIBackupVolumeSnapshotContents">`

**velero restore describe restore-myapp --details**

```
Name:         restore-myapp
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:                       Completed
Total items to be restored:  4
Items restored:              4

Started:    2023-12-15 01:07:25 -0800 PST
Completed:  2023-12-15 01:08:02 -0800 PST

Backup:  backup-myapp

Namespaces:
  Included:  test-namespace
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io, csinodes.storage.k8s.io, volumeattachments.storage.k8s.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <********>

Or label selector:  <none>

Restore PVs:  auto

Existing Resource Policy:   <none>
ItemOperationTimeout:       0s

Preserve Service NodePorts:  auto

Resource List:  <error getting restore resource list: DownloadRequest.velero.io "cs-restore-20231215090725-e439987a-a151-44c1-bde6-8008b0af8d97" is invalid: spec.target.kind: Unsupported value: "RestoreResourceList": supported values: "BackupLog", "BackupContents", "BackupVolumeSnapshots", "BackupItemSnapshots", "BackupResourceList", "RestoreLog", "RestoreResults", "CSIBackupVolumeSnapshots", "CSIBackupVolumeSnapshotContents">

```

**Comment by qiuming-best** [comment]
@ranjeetsingh-23 Have you ever updated the CRD when you installed or upgraded Velero?

**Comment by qiuming-best** [comment]
`xxx is invalid: spec.target.kind: Unsupported value xxx` which I think it's @ranjeetsingh-23 upgraded the CRD but didn't upgrade Velero which leads to the incompatible error.

So we may need the verification of @ranjeetsingh-23 first.

**Comment by gagareg** [comment]
We have the same problem, although we installed velero recently, and did not touch it at all. 

```
Client:
        Version: v1.13.0
        Git commit: 76670e940c52880a18dbbc59e3cbee7b94cd3352
Server:
        Version: v1.11.0
# WARNING: the client version does not match the server version. Please update server
```

```
backuprepositories                                                     velero.io/v1                           true         BackupRepository
backups                                                                velero.io/v1                           true         Backup
backupstoragelocations             bsl                                 velero.io/v1                           true         BackupStorageLocation
datadownloads                                                          velero.io/v2alpha1                     true         DataDownload
datauploads                                                            velero.io/v2alpha1                     true         DataUpload
deletebackuprequests                                                   velero.io/v1                           true         DeleteBackupRequest
downloadrequests                                                       velero.io/v1                           true         DownloadRequest
podvolumebackups                                                       velero.io/v1                           true         PodVolumeBackup
podvolumerestores                                                      velero.io/v1                           true         PodVolumeRestore
restores                                                               velero.io/v1                           true         Restore
schedules                                                              velero.io/v1                           true         Schedule
serverstatusrequests               ssr                                 velero.io/v1                           true         ServerStatusRequest
volumesnapshotlocations            vsl                                 velero.io/v1                           true         VolumeSnapshotLocation
```

How can we fix the issue?

**Comment by qiuming-best** [comment]
@gagareg I am not quite sure of your problem. I could not reproduce it If your problem is `error getting restore resource list` with Server v1.11.0 and Clien v1.13.0. Or you could try the same version with the Velero server and client.

But if your problem is `# WARNING: the client version does not match the server version. Please update server`, you should keep the client version to match the server version.

**Comment by qiuming-best** [comment]
@gagareg @ranjeetsingh-23 If you're upgrading Velero from an older version you could follow this [instruction](https://velero.io/docs/v1.13/upgrade-to-1.13/)

**Comment by gagareg** [comment]
@qiuming-best 
Thank you for replying. We have already updated from 4 to 5 version.  Currently, it works as expected. 

However, I can't understand why this has happened? We have not touched Velero helm chart, there has been
only 1 release. We have pinned all versions as much as possible.

**Comment by alievrouw** [comment]
> @gagareg I am not quite sure of your problem. I could not reproduce it If your problem is `error getting restore resource list` with Server v1.11.0 and Clien v1.13.0. Or you could try the same version with the Velero server and client.
> 
> But if your problem is `# WARNING: the client version does not match the server version. Please update server`, you should keep the client version to match the server version.

I had a similar problem and was able to resolve it by having a CLI version at or below the server version.

**Comment by gagareg** [comment]
> > @gagareg I am not quite sure of your problem. I could not reproduce it If your problem is `error getting restore resource list` with Server v1.11.0 and Clien v1.13.0. Or you could try the same version with the Velero server and client.
> > But if your problem is `# WARNING: the client version does not match the server version. Please update server`, you should keep the client version to match the server version.
> 
> I had a similar problem and was able to resolve it by having a CLI version at or below the server version.

It looks weird,  everything has been broken because of higher version of the CLI, right?. 

Additionally, the schedule and backup resources generated using YAML files, not by executive velero create backup. I really want to understand why it has happened because we have lost all backups.

**Comment by qiuming-best** [comment]
Using the Velero CLI to create a backup or schedule, the Velero CLI will generate the schedule and backup resources ([CR](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/)). 

If your Velero CLI is higher than the Velero server, it will generate some fields in the schedule and backup resources that could not recognized by the Velero server.

@gagareg

**Comment by qiuming-best** [comment]
It's just one issue related to the user using one old CRD, there would not be any code changes.
