### ISSUE TITLE
velero restore PV with the same image name and cannot finish snapshot restore 

### ISSUE THREAD

**Issue by aldelsa** [vmware-tanzu/velero#7223]
**What steps did you take and what happened:**

I am working on the snapshot/backup/restore feature in velero and it is awesome. However, I noticed that when I create a backup of the kubernetes namespace including snapshot and restore it (I have previously removed everything from the namespace including PV and Ceph images), velero restore the PV with the same name as the image I have already removed. This does not allow Ceph to supply you with a new rbd image for the `datadownload` to restore the snapshot from S3.

**What did you expect to happen:**
Execute `velero restore create --from-backup test-backup-movedata` and restore complete, even if not exists PV.

**Environment:**
- Velero version:  v1.12.0
- Velero features:  EnableCSI
- Kubernetes version: v1.24.13

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
From the workflow of Velero generic restore, the PV is dynamically provisioned, which is regarded as a new volume creation request by the storage. Therefore, I don't quite understand what the `velero restore the PV with the same name as the image I have already removed` means.
Moreover, I don't have Ceph env on hand, so I don't know how a PV connects a Ceph image. Basically, a PV takes a volumeHandle which is interpretable by the storage.

Therefore, could you give more elaborations around the questions above?

**Comment by reasonerjt** [comment]
Marking it as "defer candidate" due to lack of information, and this looks like a behavior of the snapshotter rather than velero.

**Comment by aldelsa** [comment]
Sorry for the delay.  I've been doing the same battery of tests and I've noticed that the PVC stays in "Pending" for a while:

```
$ k get pvc
NAME         STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS              AGE
nginx-logs   Pending                                      csi-rbd-sc   10s

---

$ k describe pvc nginx-logs
Name:          nginx-logs
Namespace:     test-velero
StorageClass:  csi-rbd-sc
Status:        Bound
Volume:        pvc-9cf5c22c-5cda-42f6-a1e6-76521ea20ee2
Labels:        app=nginx
               velero.io/backup-name=pruebas-backup-movedata-aldelsa
               velero.io/restore-name=pruebas-backup-movedata-aldelsa-20240207134218
               velero.io/volume-snapshot-name=velero-nginx-logs-pb5ht
Annotations:   backup.velero.io/must-include-additional-items: true
               pv.kubernetes.io/bind-completed: yes
               volume.beta.kubernetes.io/storage-provisioner: rbd.csi.ceph.com
               volume.kubernetes.io/storage-provisioner: rbd.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       nginx-deployment-5bfc8c9f6f-8txc4
Events:
  Type     Reason                Age                From                                                                                                                   Message
  ----     ------                ----               ----                                                                                                                   -------
  Normal   ExternalProvisioning  37s (x3 over 52s)  persistentvolume-controller                                                                                            waiting for a volume to be created, either by external provisioner "rbd.csi.ceph.com" or manually created by system administrator
  Normal   Provisioning          36s (x6 over 52s)  rbd.csi.ceph.com_workspace-bs-ceph-csi-ceph-csi-rbd-provisioner-8667998b77-c2jl7_b0bee4a6-6324-4dec-966d-184793c2f32e  External provisioner is provisioning volume for claim "test-velero/nginx-logs"
  Warning  ProvisioningFailed    36s (x6 over 52s)  rbd.csi.ceph.com_workspace-bs-ceph-csi-ceph-csi-rbd-provisioner-8667998b77-c2jl7_b0bee4a6-6324-4dec-966d-184793c2f32e  failed to provision volume with StorageClass "csi-rbd-sc": claim Selector is not supported
  Warning  FailedBinding         35s                persistentvolume-controller                                                                                            volume "pvc-9cf5c22c-5cda-42f6-a1e6-76521ea20ee2" already bound to a different claim.

````
But after a few minutes it manages to bind if the application works correctly.

Thanks for you support
