### ISSUE TITLE
CSI-RBD-Provisioner not working for mster node with RKE Kubernetes cluster

### ISSUE THREAD

**Issue by subhankar-banerjee** [vmware-tanzu/velero#7224]
I am using the below versions ---

RKE version: v1.4.3 , 
RKE k8s client : v1.27.4 , 
RKE k8s server : v1.24.10  
Docker 20.10

while running the integration with K8s and CEPH 13.2.2, all works fine except csi-rbdplugin-provisioner.yaml , when I was running https://raw.githubusercontent.com/ceph/ceph-csi/master/deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml , it didn't run successfully for master node ..

I have 1 Master & 2 Worker nodes. when I run csi-rbdplugin-provisioner it runs fine for both worker nodes but it didn't run successfully for the master node, I got the below error --

default-scheduler 0/3 nodes are available: 1 nodes had untolerated taint {node-role.kubernetes.io/controlplane: true} 2 node(s) didn't match pod anti-affinity rules. preemption: 0/3 nodes are available: 1 Preemption is not helpful for scheduling,2  node(s) didn't match pod anti-affinity rules.

I can see the Master node having this ---

`Taints:             node-role.kubernetes.io/etcd=true:NoExecute
                    node-role.kubernetes.io/controlplane=true:NoSchedule`

so **csi-rbdplugin-provision** has replicas: 3, so that is the reason it started to schedule pods on master but it failed because the master had **NoSchedule** taint ..

now the query is whether csi-rbdplugin-provisioner needs to run on master.? or it only needs to run in worker nodes.....
if it needs to run on master only then do I need to change any configuration settings in csi-rbdplugin-provisioner.yaml file? or change replicas=2, as I have 2 workers and 1 master ?

**Comment by Lyndon-Li** [comment]
Ceph csi-rbdplugin-provisioner is a component of Ceph and doesn't belong to Velero. Therefore, please seek helps from Ceph.
