### ISSUE TITLE
No warning for PV backup when all backup paths are disabled

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#7235]
**Describe the problem/challenge you have**
1. Backing up workload with PVs using `velero backup create <my-backup> --default-volumes-to-fs-backup=false --snapshot-volumes=false`;
2. Got `Completed` result and no warning in backup description.

**Describe the solution you'd like**
Got `Completed` result and with warning in backup description.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by danfengliu** [comment]
Here is another similar scenario:

Install velero with `--features EnableCSI` but no CSI plugin was installed, in this case the actual behavior is backup with `Completed` result and no warning in backup description, giving warning should be  a proper behavior.

**Comment by reasonerjt** [comment]
This is probably already fixed.  I'll double check.

**Comment by reasonerjt** [comment]
The volumeinfo.json uploaded to the bsl has marked the PVC as "skipped".
It also has the flags in the output of `velero backup describe xxx`.

Per discussion, we agreed that we don't want to add warning messages as the user may intentionally set the flags as false, and it's easy for the user to figure out via the command.  

Therefore, I'm closing this issue as won't fix.
