### ISSUE TITLE
backups are not deleting once ttl time is done.

### ISSUE THREAD

**Issue by Prahalnp5** [vmware-tanzu/velero#7242]
backups are not deleted once ttl time is done. all the backups are still present even after the expiration time is finished. 

I tried to delete the pod as deployment will create a pod again, once the pod is running all the backups with older ttl(expiration values) were deleted successfully.

Can you please resolve this issue as soon as possible please!!!

![Capture](https://github.com/vmware-tanzu/velero/assets/151530112/a164dd19-e9fa-4cf2-a33d-a0ee38b6c6e8)

**Comment by Lyndon-Li** [comment]
Velero's backup GC runs every 1 hour, so the max delay for deleting the expired backup is 1 hour. Therefore, this looks correct as the expected behavior.

**Comment by reasonerjt** [comment]
This is working as expected, closing this issue.
