### ISSUE TITLE
Backup storage space is not fully released after all backups have been deleted under Kopia path

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#7246]
During backup, Kopia uploader periodically (every 45 min by default) creates incomplete snapshots, these snapshot won't be recorded by Velero backup and should be deleted automatically after the complete snapshot finishes or after some time (4 hours by default) or after some accumulations (3 by default). Therefore, there must be some incomplete snapshots left since they don't meet the deletion criteria -- longer than 4 hours && no more than 3 in total.
As another case, if the backup doesn't complete but some incomplete snapshots have been created, then if no more backups are commenced, there will be 3 incomplete snapshots left forever.

**Comment by reasonerjt** [comment]
Let's make sure this is covered in documentation since it's the behavior of kopia.
