### ISSUE TITLE
Backup with CSI Snapshot Data Movement enabled does not cleanup intermediate PV when persistentVolumeReclaimPolicy: Retain

### ISSUE THREAD

**Issue by djocas-nortal** [vmware-tanzu/velero#7252]
**What steps did you take and what happened:**

I'm using Velero to take backup of OKE k8s cluster resources and Persistent Volumes. We have a default storage class configured with Reclaim Policy = Retain.
```
➜  /tmp kubectl get storageclass | grep default
oci-bv-encrypted-retain (default)   blockvolume.csi.oraclecloud.com   Retain          WaitForFirstConsumer   true                   301d
```

Backup with Snapshot Data Movement enabled completes successfully:  DataUpload process seemed to completed fine, also I can see file in object store bucket

```
NAME                                 STATUS      STARTED   BYTES DONE   TOTAL BYTES   STORAGE LOCATION   AGE     NODE
velero-ad-hoc-20231227090032-4n6rd   Completed   5h23m     216666112    216666112     oci-default        5h23m   ***
velero-ad-hoc-20231227090032-dbrhj   Completed   5h24m     86954235     86954235      oci-default        5h24m   ***
velero-ad-hoc-20231227090032-j6wj2   Completed   5h26m     99250953     99250953      oci-default        5h26m   ***
velero-ad-hoc-20231227090032-mq9j5   Completed   5h23m     69948169     69948169      oci-default        5h23m   ***
velero-ad-hoc-20231227090032-rfcsd   Completed   5h25m     48394491     48394491      oci-default        5h25m   ***
velero-ad-hoc-20231227090032-s4qpn   Completed   5h27m     116453627    116453627     oci-default        5h27m   ***
```

However noticed that intermediate PVs (storage class with Reclaim Policy = Retain), most probably used by DataMovers are left in the cluster while the corresponding PVCs are removed:

```
➜  /tmp kubectl get pv | grep velero
csi-2ff0a0e0-d505-404a-a7c5-fc1a5b9d7a54   50Gi       RWO            Retain           Released   velero/velero-ad-hoc-20231227090032-dbrhj                                                                 oci-bv-encrypted-retain            5h18m
csi-387ac58d-8b0a-489f-9af7-7dbe4228279b   50Gi       RWO            Retain           Released   velero/velero-ad-hoc-20231227090032-4n6rd                                                                 oci-bv-encrypted-retain            5h16m
csi-4796df52-e33c-45ca-8a05-057473bedfbe   50Gi       RWO            Retain           Released   velero/velero-ad-hoc-20231227090032-mq9j5                                                                 oci-bv-encrypted-retain            5h17m
csi-47f8da9d-f71f-4608-921f-59b3b4042a0a   50Gi       RWO            Retain           Released   velero/velero-ad-hoc-20231227090032-s4qpn                                                                 oci-bv-encrypted-retain            5h20m
csi-b0ed21e0-b55f-4b23-85fd-b88bc390a351   50Gi       RWO            Retain           Released   velero/velero-ad-hoc-20231227090032-rfcsd                                                                 oci-bv-encrypted-retain            5h19m
csi-c752cb32-daf7-40ab-8d88-086382b51ec4   50Gi       RWO            Retain           Released   velero/velero-ad-hoc-20231227090032-j6wj2                                                                 oci-bv-encrypted-retain            5h19m
```

**What did you expect to happen:**

All intermediate k8s resources created during backup, including PVC/PV would be cleaned-up.

**Anything else you would like to add:**

I suspect this is due to the fact that backed-up volumes are using StorageClass with persistentVolumeReclaimPolicy: Retain

**Environment:**

- Velero version (use `velero version`): v1.12.2
- Velero features (use `velero client config get features`):  EnableCSI
- Kubernetes version (use `kubectl version`): v1.25.4
- Kubernetes installer & version: OKE managed k8s
- Cloud provider or hardware configuration: Oracle Cloud, OKE
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by anshulahuja98** [comment]
Went through the code, https://github.com/vmware-tanzu/velero/blob/78bd67aa1de52e700df3462670536ca704e3f7c8/pkg/exposer/csi_snapshot.go#L332

We will need to Patch the PV of the intermediate PVC with "Delete" policy after creation
OR in the place where we cleanup this PVC, we can first patch PV with Delete policy and delete. https://github.com/vmware-tanzu/velero/blob/78bd67aa1de52e700df3462670536ca704e3f7c8/pkg/exposer/csi_snapshot.go#L259

First route might be better since the second flow has more generic code.

**Comment by qiuming-best** [comment]
Maybe we should also handle the intermediate PV in Restore with CSI snapshot data movements

**Comment by anshulahuja98** [comment]
Makes sense @qiuming-best

**Comment by ywk253100** [comment]
cc @Lyndon-Li

**Comment by qiuming-best** [comment]
> Went through the code,
> 
> https://github.com/vmware-tanzu/velero/blob/78bd67aa1de52e700df3462670536ca704e3f7c8/pkg/exposer/csi_snapshot.go#L332
> 
> We will need to Patch the PV of the intermediate PVC with "Delete" policy after creation OR in the place where we cleanup this PVC, we can first patch PV with Delete policy and delete.
> 
> https://github.com/vmware-tanzu/velero/blob/78bd67aa1de52e700df3462670536ca704e3f7c8/pkg/exposer/csi_snapshot.go#L259
> 
> First route might be better since the second flow has more generic code.

It's not suitable to patch the PV in `createBackupPVC`, for PV may not be created. 
So I put the logic to the place where the PVC deletion, which could ensure PV is created
