### ISSUE TITLE
Velero does not stop running restic maintenance after manually deleting backups and repository

### ISSUE THREAD

**Issue by lupa95** [vmware-tanzu/velero#7257]
**What steps did you take and what happened:**
We are running Velero with File system backup enabled. Our backup repository location is Azure Blob Storage. During the initial setup, we started using restic for the FSB and later switched to Kopia. 

Our backups are configured with 30 days retention and our last 30 backups are only done with Kopia. Due to some issues mentioned in https://github.com/vmware-tanzu/velero/issues/6928, we have deleted all old backups, which used restic as well as the restic directory on Azure Blob storage manually. This was done to get rid of backups, that were stuck in a _deleting_ state.

This is caused the next problem: Velero tries to run periodic maintenance on the repository with restic. Since all restic files are removed (all backups with restic, as well as the restic directory in the blob container) Velero logs a lot of errors about those missing. We use the container logs for monitoring purposes and the amount of error logs caused by restic are a big problem for us.

Example output of errors:

```velero time="2024-01-02T09:38:32Z" level=info msg="Running maintenance on backup repository" backupRepo=velero/example logSource="pkg/controller/backup_repository_controller.go:285"
velero time="2024-01-02T09:38:32Z" level=error msg="Restic command fail with ExitCode: 1. Process ID is 5468, Exit error is: exit status 1" logSource="pkg/util/exec/exec.go:66"
velero time="2024-01-02T09:38:32Z" level=warning msg="error pruning repository" backupRepo=velero/example error="error running command=restic prune --repo=azure:my-container:/restic/my-backup --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: unable to open config file: blob.GetProperties: HEAD https://mystorageaccount.blob.core.windows.net/my-container/restic/my-backup/config\n--------------------------------------------------------------------------------\nRESPONSE 404: 404 The specified blob does not exist.\nERROR CODE: BlobNotFound\n--------------------------------------------------------------------------------\nResponse contained no body\n--------------------------------------------------------------------------------\n\nIs there a repository at the following location?\nazure:my-container:/restic/my-backup\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/restic/repository.go:123" error.function="github.com/vmware-tanzu/velero/pkg/repository/restic.(*RepositoryService).exec" logSource="pkg/controller/backup_repository_controller.go:291"
velero time="2024-01-02T09:38:33Z" level=error msg="Restic command fail with ExitCode: 1. Process ID is 5481, Exit error is: exit status 1" logSource="pkg/util/exec/exec.go:66"
velero time="2024-01-02T09:38:33Z" level=error msg="Error checking repository for stale locks" backupRepo=velero/velero-mystorageaccount-restic-nbvg5 error="error running command=restic unlock --repo=azure:my-container:/restic/velero --password-file=/tmp/credentials/velero/velero-repo-credentials-repository-password --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: unable to open config file: blob.GetProperties: HEAD https://mystorageaccount.blob.core.windows.net/my-container/restic/velero/config\n--------------------------------------------------------------------------------\nRESPONSE 404: 404 The specified blob does not exist.\nERROR CODE: BlobNotFound\n--------------------------------------------------------------------------------\nResponse contained no body\n--------------------------------------------------------------------------------\n\nIs there a repository at the following location?\nazure:my-container:/restic/velero\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/restic/repository.go:123" error.function="github.com/vmware-tanzu/velero/pkg/repository/restic.(*RepositoryService).exec" logSource="pkg/controller/backup_repository_controller.go:184"
```

**What did you expect to happen:**
Velero stops running restic maintenance on a repository, that does not contain any restic related backups anymore.

**Anything else you would like to add:**

The installation is done with Helm and we have set `configuration.uploaderType: kopia` in the Helm values.
**Environment:**

- Velero version (use `velero version`): v1.12.2
- Kubernetes version (use `kubectl version`): 1.25.6

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
@lupa95 
How about deleting the corresponding Restic BackupRepository?
I think after removing the BackupRepository, the Velero server should not trigger maintenance anymore.

**Comment by lupa95** [comment]
@blackpiglet thank you for the hint, this solved my problem!

I was not aware that Velero had CRDs, which track the repositories, silly me :)

Closing issue, since it is solved.
