### ISSUE TITLE
Velero backup getting stuck "InProgress"

### ISSUE THREAD

**Issue by viswaselvamazure** [vmware-tanzu/velero#7285]
**What steps did you take and what happened:**
Velero backups, whether scheduled or manually triggered, sometimes get stuck in the in progress phase. When I ran velero backup describe <backup-name> I realized that the values of Estimated total items to be backed up: and Items backed up so far: are same, Kopia backup failed.  The below command is used for velero install on the cluster.

velero install --provider azure --plugins velero/velero-plugin-for-microsoft-azure:v1.8.0 --bucket velero --secret-file credentials-velero.yaml --backup-location-config resourceGroup=<resource-group-name>,storageAccount=<storageaccount-name> --use-volume-snapshots=false --velero-pod-cpu-limit="0" --velero-pod-mem-limit="0" --velero-pod-mem-request="0" --velero-pod-cpu-request="0" --use-node-agent --privileged-node-agent --default-volumes-to-fs-backup

If I open the azure storage account container to verify the backed up files, and check the velero-backup.json file, I can see the below status.
"status": {
    "version": 1,
    "formatVersion": "1.1.0",
    "expiration": "2024-02-06T11:21:58Z",
    "phase": "FinalizingPartiallyFailed",
    "startTimestamp": "2024-01-07T11:21:59Z",
    "errors": 1,
    "progress": {
      "totalItems": 48,
      "itemsBackedUp": 48
    }
But, when I run "Velero get backups" getting the status as InProgress only.

**What did you expect to happen:**

1. Velero should backup all manifests and volumes.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
Name:         veletotest
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.25.12+26bab08
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=25

Phase:  InProgress

Namespaces:
  Included:  pvc-test2
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Or label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto
Snapshot Move Data:          auto
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2023-12-14 10:45:40 +0300 +03
Completed:  <n/a>

Expiration:  2024-01-13 10:45:40 +0300 +03

Estimated total items to be backed up:  34
Items backed up so far:                 34

Velero-Native Snapshots: <none included>

- `velero backup logs <backupname>`
An error occurred: logs for backup "veletotest" are not available until it's finished processing, please wait until the backup has a phase of Completed or Failed and try again

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  1.12.2
- Velero features (use `velero client config get features`):  features: <NOT SET>
- Kubernetes version (use `kubectl version`): Client Version: 4.10.55 (Azure Redhat Openshift Cluster)
- Kubernetes installer & version: v1.25.12+26bab08
- Cloud provider or hardware configuration: Azure RedHat Openshift Cluster
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Duplicate issue with #7287. Close.
