### ISSUE TITLE
node-agents don't start on rke2

### ISSUE THREAD

**Issue by mierea** [vmware-tanzu/velero#7286]
**What steps did you take and what happened:**

On a fresh velero installation the node agents fail with error:

```
An error occurred: unexpected directory structure for host-pods volume, ensure that the host-pods volume corresponds to the pods subdirectory of the kubelet root directory
```
**What did you expect to happen:**
node-agents to run
**The following information will help us better understand what's going on**:

**Environment:**

- Velero version (use `velero version`): Version: v1.12.2
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):  v1.25.16+rke2r1
- Kubernetes installer & version:
- Cloud provider or hardware configuration: self-hosted
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.3 LTS (Jammy Jellyfish)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
https://velero.io/docs/v1.13/file-system-backup/#configure-node-agent-daemonset-spec
Please follow this document to customize your node-agent configuration. For Rancher, the kubelet's pods directory is `/opt/rke/var/lib/kubelet/pods`.

**Comment by mierea** [comment]
Hi @blackpiglet,

The directory is  /var/lib/kubelet/pods (my nodes are using Ubuntu not RancherOS).

I will close the ticket as after multiple restarts it started to work and I cannot reproduce the issue anymore.

**Comment by FredNass** [comment]
If you're facing this issue, restarting the hosts (drain then init 6) on which node-agents won't start solves it.
