### ISSUE TITLE
CI: Codecov failed upload

### ISSUE THREAD

**Issue by mateusoliveira43** [vmware-tanzu/velero#7288]
**What steps did you take and what happened:**
Sometimes, the CI for PRs fails with Codecov failed upload [example](https://github.com/vmware-tanzu/velero/actions/runs/7448863317/job/20264155800?pr=7173), which is not directly related to code changes introduced by the PR.

**What did you expect to happen:**

CI not to fail.

**The following information will help us better understand what's going on**:

Not related.

**Anything else you would like to add:**
Not at the moment.

**Environment:**

- CI for main branch

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
This is normally caused by intermittent problem in Github backend and retry will resolve the problem.

Have you had a chance to retry?

**Comment by mateusoliveira43** [comment]
I think as non maintainer of the project, I do not have permission to retry jobs. Or there is a command to do that?

**Comment by kaovilai** [comment]
> I think as non maintainer of the project, I do not have permission to retry jobs. Or there is a command to do that?

You would force push to trigger retry of jobs.

**Comment by kaovilai** [comment]
To retry keeping current changes.

```
git commit --amend --no-edit --signoff && git push --force
```

**Comment by mateusoliveira43** [comment]
That is a valid workaround, but do not know if a good one. Project CI seems to take some minutes to run, so would retry all that just for a specific flake failure

**Comment by kaovilai** [comment]
> That is a valid workaround, but do not know if a good one. Project CI seems to take some minutes to run, so would retry all that just for a specific flake failure

It's the only workaround for people without collaborators permission
