### ISSUE TITLE
What's the expected behavior when creating additional BSL when using AWS IRSA as Velero installation credential

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#7290]
**Describe the problem/challenge you have**

In EKS cluster, when install Velero with service account of IRSA instead of secret file, BSL and VSL are all using this SA for credential, what if we need other BSL, `--credential` should not be used in `velero create backup-location` in this case, we should document it.

**Describe the solution you'd like**

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
IMO the credentials set in additional BSL should have higher priority than the IRSA setting.
This is a dup of #7302
