### ISSUE TITLE
Velero version 1.13?

### ISSUE THREAD

**Issue by sathakatheef** [vmware-tanzu/velero#7310]
**What steps did you take and what happened:**
We are looking to upgrade to k8s version 1.28 and based on the [compatibility matrix](https://github.com/vmware-tanzu/velero?tab=readme-ov-file#velero-compatibility-matrix) **where is the release for velero version 1.13** (as it is mentioned as the tested version)? The latest release is currently showing as [v1.12.3](https://github.com/vmware-tanzu/velero/releases/tag/v1.12.3).

**Comment by reasonerjt** [comment]
It's updated as part of preparation of rc.1, v1.13.0-rc.1 will be tagged early next week, and

**Comment by reasonerjt** [comment]
Closing the issue as the question's been answered.
