### ISSUE TITLE
Need a way to trace the resource usage of plugin processes

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#7313]
**Describe the problem/challenge you have**

There is no way to know the processes' resource usage inside the Velero pod, especially the plugin processes.
This makes the OOM issue debugging difficult, and it's not easy to know how much resource is consumed by the plugins.

**Describe the solution you'd like**

It's better not to introduce a new third-party tool. 
Looks like there is no Golang package can do that. 

Maybe the Velero server can do that by going through the `/proc/<proc-id>/stat` periodically and registering the data as a metric.

https://linux.die.net/man/5/proc

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
Per discussion, we prefer this addressed by using 3rd party tools.
