### ISSUE TITLE
Cant access kopia repo with cli tool

### ISSUE THREAD

**Issue by CrimsonFez** [vmware-tanzu/velero#7316]
I'm trying to access my kopia snapshots manually.
I tried `kopia repository connect s3 --bucket=ord-k8s-backups --access-key=asdf --secret-access-key=asdf --endpoint=asdf --prefix=kopia/keycloak-prod` and entering the password `static-passw0rd`

I'm getting the error: `ERROR error connecting to repository: repository not initialized in the provided storage`

**Comment by Lyndon-Li** [comment]
Try this prefix `--prefix=kopia/keycloak-prod/`

**Comment by CrimsonFez** [comment]
It works
I can't believe I didn't think of that...
Thank you!
