### ISSUE TITLE
The Velero server OOM when running scale test with informer cache enabled

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#7323]
The scale test case creates 2500 empty namespaces (one serviceaccount and configmap are created automatically for each namespace), back them up, and restore them.

With informer cache enabled, 7500 factories are created for namespaces/serviceaccounts/configmaps which need about 600MB of memory while without informer cache only 200MB is needed.

```
time="2024-01-14T17:00:34Z" level=info msg="[debug] Creating factory for /v1, Resource=serviceaccounts in namespace nstest-05044523-2375" logSource="pkg/restore/restore.go:1082" restore=velero/restore-nstest-05044523
time="2024-01-14T17:00:34Z" level=info msg="[debug] Creating factory for /v1, Resource=serviceaccounts in namespace nstest-05044523-413" logSource="pkg/restore/restore.go:1082" restore=velero/restore-nstest-05044523
time="2024-01-14T17:00:34Z" level=info msg="[debug] Creating factory for /v1, Resource=serviceaccounts in namespace nstest-05044523-621" logSource="pkg/restore/restore.go:1082" restore=velero/restore-nstest-05044523
time="2024-01-14T17:00:34Z" level=info msg="[debug] Creating factory for /v1, Resource=serviceaccounts in namespace nstest-05044523-1252" logSource="pkg/restore/restore.go:1082" restore=velero/restore-nstest-05044523
time="2024-01-14T17:00:34Z" level=info msg="[debug] Creating factory for /v1, Resource=serviceaccounts in namespace nstest-05044523-1847" logSource="pkg/restore/restore.go:1082" restore=velero/restore-nstest-05044523
time="2024-01-14T17:00:34Z" level=info msg="[debug] Creating factory for /v1, Resource=serviceaccounts in namespace nstest-05044523-1906" logSource="pkg/restore/restore.go:1082" restore=velero/restore-nstest-05044523
time="2024-01-14T17:00:34Z" level=info msg="[debug] Creating factory for /v1, Resource=serviceaccounts in namespace nstest-05044523-2014" 
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
Even after we've fixed the issue we should add a release note that velero may use more memory due to the introduction of informer-cache.
