### ISSUE TITLE
ingress restore failed

### ISSUE THREAD

**Issue by learner0810** [vmware-tanzu/velero#7330]
**What steps did you take and what happened:**

The resoult-list information for backup ingress is as follows
```
{"extensions/v1beta1/Ingress":["velero/dao-ingress"],"networking.k8s.io/v1beta1/Ingress":["velero/dao-ingress"],"v1/Namespace":["velero"]}
```
The ingress version in the restored cluster is networking.k8s.io/v1
```
ingressclasses                                 networking.k8s.io/v1                   false        IngressClass
ingresses                         ing          networking.k8s.io/v1                   true         Ingress
```

I encountered two problems, the first problem is that there is no version networking.k8s.io/v1beta1 for ingress resource in the restore cluster, which causes it to be stuck in WaitForCacheSync all the time, so I turned on disable-informer-cache, and then I encountered the second problem Creating the The version of the created resourceClient is still networking.k8s.io/v1beta1, so the apiserver can't create the resource successfully.  

![image](https://github.com/vmware-tanzu/velero/assets/39400425/fbf67599-2ba9-4217-8261-9bdd3d261284)

![image](https://github.com/vmware-tanzu/velero/assets/39400425/a632595a-d407-4049-8fd2-061690dec4d3)

```bash
kubectl -n velero logs -f velero-55dc564f96-rpbjr

time="2024-01-18T03:54:27Z" level=info msg="Getting client for networking.k8s.io/v1beta1, Kind=Ingress" logSource="pkg/restore/restore.go:1007" restore=velero/velero-plugin-for-ingress
time="2024-01-18T03:54:27Z" level=info msg="restore status includes excludes: <nil>" logSource="pkg/restore/restore.go:1372" restore=velero/velero-plugin-for-ingress
time="2024-01-18T03:54:27Z" level=info msg="Executing item action for ingresses.networking.k8s.io" logSource="pkg/restore/restore.go:1379" restore=velero/velero-plugin-for-ingress

time="2024-01-18T03:54:27Z" level=error msg="error restoring dao-ingress: the server could not find the requested resource" logSource="pkg/restore/restore.go:1690" restore=velero/velero-plugin-for-ingress
```

**What did you expect to happen:**

ingress successfully restored

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.12.2
	Git commit: 06d12dec4030703cb46b2699ca434cdabd9edbb0
Server:
	Version: v1.12.2
```
- Velero features (use `velero client config get features`): 
```
       - args:
          - server
          - --uploader-type=restic
          - --disable-informer-cache=true
          command:
          - /velero
```
- Kubernetes version (use `kubectl version`):
back cluster
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:58:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"7c28a83e67cb506f9df948d7b23698f8f9c279b8", GitTreeState:"clean", BuildDate:"2021-07-15T08:58:53Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
restore cluster
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by allenxu404** [comment]
Maybe restore-resource-modifiers can help if the version of ingress resource can't be changed in destination cluster.
Please refer to the doc for more info: https://velero.io/docs/v1.12/restore-resource-modifiers/

**Comment by learner0810** [comment]
> Maybe restore-resource-modifiers can help if the version of ingress resource can't be changed in destination cluster. Please refer to the doc for more info: https://velero.io/docs/v1.12/restore-resource-modifiers/

Thanks for the reply, I'm trying

**Comment by reasonerjt** [comment]
We believe the resource modifier can solve the problem, I'm closing this issue as fixed.
