### ISSUE TITLE
`existingResourcePolicy` validation outside CLI

### ISSUE THREAD

**Issue by mateusoliveira43** [vmware-tanzu/velero#7347]
**What steps did you take and what happened:**
Created a restore using kubectl command and set existingResourcePolicy to "batman". Restore succeed without mentioned wrong existingResourcePolicy.

**What did you expect to happen:**
Warn user that is not a valid existingResourcePolicy and present user with available options.

Validation present in CLI command
https://github.com/vmware-tanzu/velero/blob/270b1de6a1fbfd672b2c88f46ed1ffbbdfac864c/pkg/cmd/cli/restore/create.go#L424-L429

**Anything else you would like to add:**
As previously discussed, we do not want to add enum validation in CRD, as there are plans to add more options to that field in the future https://github.com/vmware-tanzu/velero/issues/6142 

So, its best to add validation through code

**Environment:**

- Velero version (use `velero version`): 1.12

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kaovilai** [comment]
👋

**Comment by kaovilai** [comment]
unstale
