### ISSUE TITLE
[EKS] Restoration using CSI Snapshot data movement fails with repository corruption

### ISSUE THREAD

**Issue by awsvikram** [vmware-tanzu/velero#7354]
**What steps did you take and what happened:**

I'm trying to perform a cross region EKS restoration which includes persistent volumes. I'm using the CSI snapshot data movement feature and could see the data upload completed without any issues. However, while restoring I could see the persistent volume is being created fresh and data download doesn't run.

Error Message : 
 restore:  error preparing persistentvolumeclaims/restore/ebs-claim-gp3: rpc error: code = Unknown desc = Failed to get Volumesnapshot restore/velero-ebs-claim-gp3-2llmd to restore PVC restore/ebs-claim-gp3: volumesnapshots.snapshot.storage.k8s.io "velero-ebs-claim-gp3-2llmd" not found

**What did you expect to happen:**
I would expect the restore to start the data download process which in turn will create the persistent volume with data intact from the backup storage location (s3) 
**The following information will help us better understand what's going on**:
Source EKS Cluster : 1.24
Backup storage location : S3
Destination EKS cluster : 1.27
Backup storage location :  S3 ( cross region replicated bucket)
[bundle-2024-01-25-03-20-36.tar.gz](https://github.com/vmware-tanzu/velero/files/14046406/bundle-2024-01-25-03-20-36.tar.gz)

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  Client 1.12.3, Server : 1.12.3
- Velero features (use `velero client config get features`): EnableCSI
- Kubernetes version (use `kubectl version`): Source : 1.24, Destination : 1.27
- Kubernetes installer & version:
- Cloud provider or hardware configuration:AWS
- OS (e.g. from `/etc/os-release`): Amazon [Linux](url)

Debug bundle uploaded

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
@awsvikram Through the log you provided, It seems you are using the CSI snapshot but not CSI snapshot data movement.

So how is your backup and restore command?

**Comment by blackpiglet** [comment]
@awsvikram 
First, please check the version of CSI plugin you are using. The Velero v1.12.3's matching CSI plugin version should be v0.6.3.

Second, could you give more details about the PV and PVC resources included in the backup?
From the backup information, the PVs are in CSI-migrated format, which is `PV.spec` doesn't have `CSI` section. As a result, the PV data backup fell back to the Velero native snapshot way, but I'm not sure why the CSI plugin also created the DataUpload for the corresponding PVC resources. That's not expected.
It's better to have the PV and PVC yaml for debug.

**Comment by awsvikram** [comment]
Thanks for the swift response @blackpiglet .. I'm using the 0.6.0 csi plugin. Let me know if you want me to use 0.6.3 and try this again. I'm also attaching the pv and the pvc manifest:

`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  creationTimestamp: "2023-05-04T14:44:19Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: nginx
  name: www-web-0
  namespace: default
  resourceVersion: "137637876"
  uid: ee1d2c63-99ce-475f-a0fd-0850639f5310
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-sc-gp3
  volumeMode: Filesystem
  volumeName: pvc-ee1d2c63-99ce-475f-a0fd-0850639f5310
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
`
Persistent volume

`apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: ebs.csi.aws.com
    volume.kubernetes.io/provisioner-deletion-secret-name: ""
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
  creationTimestamp: "2023-05-04T14:44:22Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/ebs-csi-aws-com
  name: pvc-ee1d2c63-99ce-475f-a0fd-0850639f5310
  resourceVersion: "41766389"
  uid: d1303453-f5dd-4f44-a8af-3ce3fa7ad7fd
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: www-web-0
    namespace: default
    resourceVersion: "41766307"
    uid: ee1d2c63-99ce-475f-a0fd-0850639f5310
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1678124931587-8081-ebs.csi.aws.com
    volumeHandle: vol-0b83b0411e6c6330b
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.ebs.csi.aws.com/zone
          operator: In
          values:
          - us-east-1c
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ebs-sc-gp3
  volumeMode: Filesystem
status:
  phase: Bound
`

**Comment by blackpiglet** [comment]
Thanks. The PV is not CSI-migrated. It's weird that Velero backed up the PV as the Velero native snapshot.
Please have another try with v1.12.3 Velero and v0.6.3 CSI plugin, and please also set the `--snapshot-move-data` flag for the backup. The backup in the uploaded bundle's `SnapshotMoveData` is set as `Auto`. Not sure what went wrong.

**Comment by awsvikram** [comment]
With the suggested steps, I'm getting a new error and the data uploads fail as well.

`Message:               error to initialize data path: error to boost backup repository connection default-default-kopia: error to connect backup repo: error to connect repo with storage: error to connect to repository: repository not initialized in the provided storage`

**Comment by blackpiglet** [comment]
`repository not initialized in the provided storage`
This error means the Kopia cannot read the `kopia.repository` file from the backup repository.
Please check whether the specified file can be found in the Object Storage.
The file should be in the sub-directory <bucket-name>/kopia/<namespace-name>/kopia.repository.

If the file is missed, the backup repository is broken. To make it work again, either try to whether the file can be found back, or please delete the BackupRepository, data in the Object Storage, then create a new backup.

**Comment by awsvikram** [comment]
thanks @blackpiglet ..after deleting the backup repository and doing a fresh backup and restore with the latest version, things worked..

**Comment by blackpiglet** [comment]
Close for now, because this described issue here is resolved.
