### ISSUE TITLE
Ability to ignore Velero client configuration file for e2e

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#7355]
...Perhaps something that e2e should be able to turn off via a flag `--ignore-home-config`
```
❯ cat ~/.config/velero/config.json
{"namespace":"some-custom-ns"}
```

_Originally posted by @kaovilai in https://github.com/vmware-tanzu/velero/pull/7353#discussion_r1465815521_

**Comment by reasonerjt** [comment]
I don't think we need to add this extra flag for e2e, the assumption is that the e2e should be executed on a clean environment which will not have the pre-existing config.json.

**Comment by kaovilai** [comment]
This can be worked around by including namespaces in each e2e test scenario [like here](https://github.com/vmware-tanzu/velero/pull/7353/files#diff-20efa1941b33a2f5fac0a31f9781ac5a15099b85a79b026d33a2da7f1180f826R938)
