### ISSUE TITLE
Support to update the backup Async Operation result in the VolumeInfo metadata

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#7357]
**Describe the problem/challenge you have**

In v1.13, a new backup metadata file, volumeinfo, was created to record the PV and the PVC information included in the backup, but one thing still missing is the PV and PVC information updated in the backup async operation.

Create this issue to trace the request to include the async operation update into the VolumeInfo metadata file.

**Describe the solution you'd like**

The straightforward way is to update the VolumeInfo metadata file in the backup finalizing state, but this method goes further against the backup repository data immutability requirement.
A possible alternative is creating new metadata to contain both the original VolumeInfo metadata and the async operation update. The new metadata will take precedence when existing. If the new metadata doesn't exist, then the old VolumeInfo metadata file should be used.

Will create a design for this issue.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
@anshulahuja98 FYI.

**Comment by anshulahuja98** [comment]
thank you for tracking this!

**Comment by reasonerjt** [comment]
There's concern about the immutability of backup files.  Let's revisit it later but we can't commit it in v1.14 at this moment.

**Comment by blackpiglet** [comment]
The conclusion is patching the async operation result into the existing volumeinfo metadata.
