### ISSUE TITLE
Generate an Event on Backup/Restore Failure

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#7358]
**Describe the problem/challenge you have**

A kubernetes event generated for backup/restore failure would give a more accurate representation as to errors that happened while using velero.

It would survive a velero pod restart unlike the metrics endpoint.

User may have to adjust events TTL to make them live long enough for review.

**Describe the solution you'd like**

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by Lyndon-Li** [comment]
Discussed in #6606, see more details there.

**Comment by weshayutin** [comment]
@kaovilai thanks for writing this up, not sure which issue work will fold into but this is def something customers want! ++

**Comment by kaovilai** [comment]
Closing as duplicate
