### ISSUE TITLE
velero server will crash when there is no bsl named `default`

### ISSUE THREAD

**Issue by wrype** [vmware-tanzu/velero#7359]
**What steps did you take and what happened:**

Run velero server with no bsl, then the server will crash with an error: `An error occurred: backupstoragelocations.velero.io "default" not found` .

**What did you expect to happen:**

velero server can run with no bsl.

**The following information will help us better understand what's going on**:

refer code in `setDefaultBackupLocation`: https://github.com/vmware-tanzu/velero/blob/1034d6aee0b32b6ec0dbe4203902cd1d465ec950/pkg/cmd/server/server.go#L469

**Anything else you would like to add:**

**Environment:**

in branch `main` and `release-1.13`

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
@wrype  I think it's the server getting an error when startup then exists, but not crash.

Velero server would run following the command `velero server xx`. if not specifying the option `--default-backup-storage-location`, the value would be 'default'. then it will hit the errors you mentioned.

So if you don't have one bsl with `default` name, you should specify it with another name that you have.

**Comment by wrype** [comment]
Right that. But velero-server-1.12 can run with no bsl.
I think the new version should keep the same behavior.

**Comment by qiuming-best** [comment]
@wrype Why do you want the Velero server to run without BSL? 
we did make some changes in the default BSL settings. Before v1.13, Velero could set multiple default BSLs we make that there is only one default BSL.

We've changed the default BSL selection logic, I will check the situation when there is no BSL.

**Comment by wrype** [comment]
I think this scenario: first I start the velero server with no bsl config, then I configure a bsl when storage is ready.
But in new version, velero server will exist with an error at first time.

**Comment by qiuming-best** [comment]
This way of setting BSL is in your product environment or just for testing?  may it be a less common usage?

**Comment by wrype** [comment]
Our use case is deploying velero server (no BSL) on k8s first, then when users have backup requirements, they will buy S3 buckets by themselves. After that we start to configure BSL.

**Comment by qiuming-best** [comment]
@wrype What's your detailed step of setting BSL?
You will create one BSL When the user buys S3 buckets, then set the BSL as one default.
Or do you create one BSL and specify the BSL whenever doing a backup?

**Comment by wrype** [comment]
> @wrype What's your detailed step of setting BSL? You will create one BSL When the user buys S3 buckets, then set the BSL as one default. Or do you create one BSL and specify the BSL whenever doing a backup?

When the user buys S3 buckets, I will create one BSL and set one default.

**Comment by qiuming-best** [comment]
thanks for your information, I'll fix this issue recently.

**Comment by mateeyow** [comment]
Getting this error as well, I'm having the same setup as @wrype, it should show error but should not crash the pod.

**Comment by miriamfrom** [comment]
Great that a solution for this will be in place for v1.13.1. We also had problems with our pod crashing, however, this was not due to a lack of BSLs, but due to us renaming our BSLs with more descriptive names than "default". Unfortunately, the pod still crashes looking for a BSL called "default". Our current workaround is just adding an extra BSL named "default", however this is confusing, as this will not actually be the default BSL.

**Comment by qiuming-best** [comment]
@miriamfrom you may not need to create one extra BSL named "default", Instead, you can specify the Velero server deployment start parameter with `velero server xxx  --default-backup-storage-location $your-exist-bsl`

**Comment by miriamfrom** [comment]
@qiuming-best, thanks for the suggestion. I tried looking into using --default-backup-storage-location, but the documentation said that the use of this value was deprecated, and suggested using the `--default` flag for `velero backup-location` instead. I also think I tested setting the `--default-backup-storage-location`, but that it did not help with the issue I was facing.

**Comment by qiuming-best** [comment]
@miriamfrom do you mean that `velero server xxx  --default-backup-storage-location $your-exist-bsl` not work for you?

I've tried with `1.13.0`, and it is ok when specifying the default BSL in Velero server:
I only have one BSL with the name 'test'.
I specify the Velero server deployment start parameter with velero server  --default-backup-storage-location=test
It works as below:
<img width="926" alt="image" src="https://github.com/vmware-tanzu/velero/assets/8985337/ae1329f9-fb9c-4063-9f78-5be971ee89d2">

**Comment by draghuram** [comment]
I just installed 1.13.0 and ran into this issue. I never create BSL as part of the installation because I try to keep installation and configuration as two separate steps. Any idea when 1.13.1 will be released?

**Comment by qiuming-best** [comment]
@draghuram  v1.13.1 will be released shortly, but the release date is not announced.

**Comment by qiuming-best** [comment]
The fix has been merged, and it will released in v1.13.1.
If having any other related problem please re-open it
