### ISSUE TITLE
TTL for podVolumeBackup Resources

### ISSUE THREAD

**Issue by ugur99** [vmware-tanzu/velero#7362]
**Describe the problem/challenge you have**

For large clusters; not well managed `opt-out` backup approach or frequent scheduled backups with long TTL can cause accumulation of large number of `podVolumeBackup` resources in the etcd database. As far as I can see; podVolumeBackups are used to discover of the volumes that need to be backed up by kopia or restic. After the backup process these resources are not used anymore; except for the troubleshooting purposes in any case of failures. I believe that if we can set a TTL for these resources that will determine how long these resources will be kept in the cluster after the backup is completed would be a better approach regardless of TTL of the backups. That way; for the backups to have long TTL in large clusters would not cause high podVolumeBackup resources in the etcd database.

**Describe the solution you'd like**

TTL for podVolumeBackup resources, regardless of the TTL of the backups. And a controller to clean up these expired podVolumeBackup resources in the cluster, so that anyone, regardless of their level of experience with Velero, can easily use the filesystem backup approach without too much load on the etcd database.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by Lyndon-Li** [comment]
We cannot fix the problem by simply adding a TTL to PVB CR, some other functionalities, i.e., restore, incremental backup and backup deletion are using the PVB CRs in the cluster; moreover, backup sync also syncs the CRs back whenever they are missing in the current cluster.
To solve the problem, we need a systematic solution that removes the runtime dependencies from the aforementioned functions, which needs dramatic changes. On the other hand, fs-backup is a legacy method and gradually replaced by snapshot data movements.
Therefore, we will not take this as high priority, we can improve it with some other changes when available.

**Comment by sseago** [comment]
"podVolumeBackups are used to discover of the volumes that need to be backed up by kopia or restic." -- this is not quite correct. Velero backup process determines which voumes need to be backed up and then creates PodVolumeBackups (PVBs) -- this is the CR that actually tells the node agent to run the backup, and their status stores the outcome of that process (succeeded, errored out, etc.)

**Comment by sseago** [comment]
@Lyndon-Li hmm. I'm wondering whether we should just delete the PVB when the associated backup is deleted. I'm not sure there's any code that references a PVB once backup is gone. I *think* (but I'm not sure) that the PodVolumeBackup CR isn't needed by restic or kopia when dealing with future/subsequent backups of the same volume to get incremental functionality, although obviously we'd need to investigate first.

**Comment by Lyndon-Li** [comment]
@sseago The PVB will be deleted when the associated backup is deleted. Here I think the issue requests to delete the PVB before the backup expires.
