### ISSUE TITLE
add a bsl option that can specify prefix of backup tarball

### ISSUE THREAD

**Issue by wrype** [vmware-tanzu/velero#7367]
**Describe the problem/challenge you have**

I wish to add a bsl option that can specify the prefix of tarball under backups within the bucket.

In order to use diff tool like winmerge conveniently.

Diff "backup1" and "backup2" downloaded from bucket using winmerge,  the backup tarball prefix is configured as "backup", the result like this:

![Snipaste_2024-01-12_20-59-51](https://github.com/vmware-tanzu/velero/assets/19252088/b0cd980b-8cc7-46d7-bc72-9a6c45f7d1e9)
![Snipaste_2024-01-12_21-02-50](https://github.com/vmware-tanzu/velero/assets/19252088/6ed69ccb-b4b7-485a-8936-64e00e8cd4b2)

**Describe the solution you'd like**

Refer to PR #7361

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
I'm not sure how widely winmerge is used with velero backup tarballs.

I don't think this usecase justifies an update on the upstream, you may edit the tarball the way you like after it's downloaded and it's beyond the scope of velero.

Additionally, adding prefix in bsl only solve a very particular case when you want to compare backup tarballs in different backup locations, the filename will again look the same if want to compare the backup tarballs from the same bsl.

I'd propose we close this issue as `won't fix`.

**Comment by wrype** [comment]
In my use case, when I have to restore using velero, I wish to check what happened first.

I think the fastest way is to create a backup, then download the latest 2 backups from s3 and use diff tool find the difference.

Keeping same tarball filename is needed, when have a requirement to find difference between different backups.

Refer to the code: https://github.com/vmware-tanzu/velero/blob/2f25c2590831f8eb11ef8ebd8db6963b59c6cd5d/pkg/persistence/object_store_layout.go#L77

The backup content saved in tarball using `backup` name, so I should rename every tarballs manually, before use diff tool.

Therefore adding a prefix option is the choice without effort, it can keep compatible with old version as well.
