### ISSUE TITLE
v1.13.0 changes velero_backup_last_status metric

### ISSUE THREAD

**Issue by wanddynosios** [vmware-tanzu/velero#7378]
**What steps did you take and what happened:**

After upgrading to velero v1.13.0, the velero_backup_last_status metric seems to have changed.

Before, the metric was constant:
<img width="2520" alt="Bildschirmfoto 2024-02-02 um 10 34 27" src="https://github.com/vmware-tanzu/velero/assets/67467325/7d5ce2c9-813f-44ee-9091-9ce399d095d5">

Now, it is constantly increasing until the next backup is run:
<img width="2543" alt="Bildschirmfoto 2024-02-02 um 10 28 21" src="https://github.com/vmware-tanzu/velero/assets/67467325/615f8a5c-817c-4fdc-81c3-ca1ee9fe9de6">

The last backup did complete without any issues:
````
velero-my-backup-20240202020000   Completed   0        0          2024-02-02 03:00:00 +0100 CET   27d       default            <none>
`````

**What did you expect to happen:**
The metric stays the same.

**The following information will help us better understand what's going on**:
The issue occurs directly after the update, without a new backup being created.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  v1.13.0
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.28.4-eks-8cb36c9
- Cloud provider or hardware configuration: aws eks 1.28
- OS (e.g. from `/etc/os-release`): amazon_linux:2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by pixiono** [comment]
Hi,

I also took a look into this issue.
I found this [PR](https://github.com/vmware-tanzu/velero/pull/6838/files), which has changed the behavior of the metric. The merge has also been published with the new release: [Release diff](https://github.com/vmware-tanzu/velero/compare/v1.12.2...v1.13.0?diff=unified&w=).

I assume that the value is now increased by 1 with each reconciliation instead of returning 1 as default.

**Comment by allenxu404** [comment]
@pixiono Yes, the code changes this [PR](https://github.com/vmware-tanzu/velero/pull/6838/files) appears to be in conflict with the existing logic in schedule_controller:
https://github.com/vmware-tanzu/velero/blob/3b8370e13c48c794467c34c93fb3a591e3d19afd/pkg/controller/schedule_controller.go#L105
the value of `velero_backup_last_status` metrics increases everytime the schedule controller reconciles.

I will fix it, thanks for reporting.
