### ISSUE TITLE
Make pkg/install/Deployment podTemplateOptions bool functions accept bool param

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#7379]
**Describe the problem/challenge you have**

Since [podTemplateOptions](https://github.com/vmware-tanzu/velero/blob/main/pkg/install/deployment.go#L32C46-L32C48) is not exported, it is not possible to form an array of podTemplateOptions to pass to install.Deployment().

Anyone using this package would require each exported function that returns an unexported type to be used directly in install.Deployment().

Thus it would be good to make these functions flexible for use by other go packages.

**Describe the solution you'd like**

Either make all bool related funcs accept bool param, or export the type so an array can be formed dynamically.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
@kaovilai Could you explain a bit about `make all bool related funcs accept bool param`? Why does this help with your requirements?

**Comment by kaovilai** [comment]
unstale

**Comment by kaovilai** [comment]
unstale
