### ISSUE TITLE
[velero-plugin-for-aws:v1.9.0] Uploading backup to object lock enabled S3 bucket failed due to Content-MD5 header

### ISSUE THREAD

**Issue by XiaoshiWang** [vmware-tanzu/velero#7400]
**What steps did you take and what happened:**
I upgraded velero helmchart from 5.1.0 to 5.3.0 and also the image tag of velero-plugin-for-aws in chart from v1.8.0 to v1.9.0. After upgrade the backups cannot be uploaded to the S3 bucket anymore with following failure: 
`Content-MD5 OR x-amz-checksum- HTTP header is required for Put Object requests with Object Lock parameters`

Our bucket is object lock enabled but there was no issue with earlier velero versions. I also tried changing the velero-plugin-for-aws image back to v1.8.0 then all start working again. In the [changes between v1.8.0 and v1.9.0](https://github.com/vmware-tanzu/velero-plugin-for-aws/compare/v1.8.0...v1.9.0) I haven't found any lines directly related to this issue. Could someone elso also take a look? Thanks a lot!

**What did you expect to happen:**
The backup to object lock enabled S3 bucket should still be working with image velero-plugin-for-aws:v1.9.0

**Anything else you would like to add:**
I also tried changing the velero-plugin-for-aws image back to v1.8.0 then all start working again. In the [changes between v1.8.0 and v1.9.0](https://github.com/vmware-tanzu/velero-plugin-for-aws/compare/v1.8.0...v1.9.0) I haven't found any lines directly related to this issue. Could someone elso also take a look? Thanks a lot!

**Environment:**

- Velero version (use `velero version`): 1.13.0
- Kubernetes version (use `kubectl version`): 1.28.5
- Cloud provider or hardware configuration: AWS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
It may relate to the AWS SDK version bump in v1.9.x.
https://github.com/vmware-tanzu/velero-plugin-for-aws/commit/b75ce19cb263d6d93d31bd1ccc9a7e48907b84cf

@XiaoshiWang Could you give more information about your scenario?
* The object lock is applied to the bucket or some prefixes/objects in the bucket?
* Could you help to collect the Velero bundle by `velero debug` to help investigate?

**Comment by blackpiglet** [comment]
@XiaoshiWang 
Thanks for reporting this issue. We have already reproduced it in the testing environment. 
No need for the debug bundle.

**Comment by XiaoshiWang** [comment]
Hi @blackpiglet ,
thank you so much for the quick response! Is there any fix to this issue planned yet?

**Comment by reasonerjt** [comment]
@XiaoshiWang 
I'll try to fix it in the next patch of aws-plugin (v1.9.1), which is to be released with velero v1.13.1

**Comment by XiaoshiWang** [comment]
@blackpiglet This sounds perfect. Much thanks again for the quick response and quick fix!

**Comment by reasonerjt** [comment]
I've verified the fix against your internal pipeline, and submitted a PR for plugin v1.9.1:
https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/193

@XiaoshiWang 
To give us more confidence, could you help verify the fix in your environment?
The patched image for AWS plugin: `danieljt/velero-plugin-for-aws:fix-7400-1`

**Comment by reasonerjt** [comment]
PR for main branch: https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/194

**Comment by XiaoshiWang** [comment]
Hi @reasonerjt I'm happy to confirm that with the image you provided `danieljt/velero-plugin-for-aws:fix-7400-1` velero backups with our object lock enabled S3 buckets are succeesful. Do you have any specific date of release?
Thanks again to you and the whole velero developer team!

**Comment by reasonerjt** [comment]
@XiaoshiWang 
Many of us are out of office for Chinese New Year so I can't give an accurate estimation
IMO v1.13.1 should be around mid-March

**Comment by danfengliu** [comment]
@reasonerjt This issue also exists in v1.12 according to test result of 1.12 nightly.

**Comment by reasonerjt** [comment]
Resolving the issue as the PRs have been merged.
