### ISSUE TITLE
Merge csi plugin into velero repo

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#7408]
With CSI-snapshot being more and more commonly used, we should consider merging the repo https://github.com/vmware-tanzu/velero-plugin-for-csi into https://github.com/vmware-tanzu/velero such that users will not need to install the csi plugin when installing velero.

This may save some release overhead and we may still turn on/off the feature by using the feature flag `EnableCSI`

**Comment by draghuram** [comment]
It will be great to merge CSI plug-in. But I cm curious why EnableCSI flag is still needed. If users want to control snapshot type, it should be from Backup CR ideally.

**Comment by blackpiglet** [comment]
After the CSI plugin merges into the Velero code base, then the feature option is unnecessary.
But the deprecation of existing feature flags may need a gap of two releases, so there is a period that the flag is still kept.

**Comment by sseago** [comment]
@reasonerjt The second one is the longer-term sticking point. If we removed enableCSI we'd need to replace it with something like useCSI which would do the same thing.

**Comment by reasonerjt** [comment]
> The second one is the longer-term sticking point. If we removed enableCSI we'd need to replace it with something like useCSI which would do the same thing.

I'm hoping at some point by default CSI will always have higher priority, unless the PV is provisioned by non-CSI driver, or explicitly annotated to use native volume snapshotter

**Comment by draghuram** [comment]
> > why EnableCSI flag is still needed...
> 
>     1. We don't wanna remove the flag right away for compatibility.
> 
>     2. There's use case of PV provisioned by public cloud provider that a user may wanna take snapshot via native snapshotter rather than CSI, this is currently is controlled by this flag

"EnableCSI" flag controls non-CSI snapshotting? That doesn't sound right. Isn't it?

**Comment by blackpiglet** [comment]
It sounds more like the future expected behavior. By then, there is already no `EnableCSI` feature flag.
