### ISSUE TITLE
Volume Snapshot attempted on orphaned PVCs without VolumeSnapshotLocations

### ISSUE THREAD

**Issue by pschichtel** [vmware-tanzu/velero#7417]
**What steps did you take and what happened:**

I have velero setup to backup everything by default unless explicitly excluded using labels. I use restic to backup my data even though I use CSIs that support snapshots (ceph-rbd and ceph-cephfs), so I have a BackupStorageLocation (ceph-rgw backed), but no VolumeSnapshotLocations. Backups of in-use PVCs are performed as expected using restic. However when PVCs are orphaned (e.g. left-over from a helm-chart or after a migration to a new PVCs), velero tries to perform volume snapshots on these PVCs, which fails because no VolumeSnapshotClass is configured and properly labeled:

```
error="error executing custom action (groupResource=persistentvolumeclaims, namespace=namespace-name, name=pvc-name): rpc error: code = Unknown desc = failed to get volumesnapshotclass for storageclass csi-name: error getting volumesnapshotclass: failed to get volumesnapshotclass for provisioner rbd.csi.ceph.com, ensure that the desired volumesnapshot class has the velero.io/csi-volumesnapshot-class label" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/backup/item_backupper.go:380" error.function="github.com/vmware-tanzu/velero/pkg/backup.(*itemBackupper).executeActions" logSource="pkg/backup/backup.go:461" name=pvc-name
```

**What did you expect to happen:**

Velero should either not backups the PVC or backup it exactly as it would if the PVC was in use.

**Environment:**

- Velero version (use `velero version`): 
  ```
  Client:
  	Version: v1.13.0
  	Git commit: 76670e940c52880a18dbbc59e3cbee7b94cd3352
  Server:
  	Version: v1.13.0
  ```
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
Seems that adding a warning message rather than falling back to snapshot is a reasonable option for the orphaned PVCs.

**Comment by ywk253100** [comment]
After reading the code, taking CSI snapshot for the PVCs that are not covered by filesystem backup is the expected behavior. You can skip this by adding `--snapshot-volumes=false` option when taking backup.

Closing this issue and remove from 1.14 milestone.
