### ISSUE TITLE
Unable to exclude Event from a velero backup of a namespace

### ISSUE THREAD

**Issue by vishalc95** [vmware-tanzu/velero#7428]
**What steps did you take and what happened:**
I am trying to take backup of all the objects of a namespace of K8s except events. But even though I executed below command , events were present in the backup ->

velero backup create tenant-ns-backups --exclude-namespaces trident,velero,blossom-analytics-system,blossom-system,certify-system-ns,default,ingress-nginx,jenkins-master-ns,jenkins-system,kube-public,jenkins-upgrade-ns,kube-node-lease,kube-system,kube-public,logging,monitoring,nvidia-device-plugin **--exclude-resources Pod,Event

**
I was able to exclude pods backup from the namespace but events couldn't be excluded

**What did you expect to happen:**

**I didnt expect events to be present in the backup **:

_

**Environment:**

 velero version
Client:
        Version: v1.8.0
        Git commit: a818c97dde2034385d7bf25e0ac2a2e055a0b372
Server:
        Version: v1.8.0

=======

K8s version -- 1.22.8

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
Should format as `resource.group`: try `events.events.k8s.io` instead.

BTW, Velero 1.8.0 is a pretty old version, suggest to use the latest one.
