### ISSUE TITLE
Velero describe restore error should show line of code (stacktrace) for the error if available

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#7430]
**Describe the problem/challenge you have**

```
Errors:
  Velero:   error getting namespace sraghave-clu1: timed out waiting for the condition
            error getting namespace sraghave-clu1: timed out waiting for the condition
            error getting namespace sraghave-clu2: timed out waiting for the condition
            error getting namespace sraghave-clu2: timed out waiting for the condition
  Cluster:    <none>
  Namespaces: <none>
```

**Describe the solution you'd like**

restore logs has following
```
time="2024-02-10T16:30:48Z" level=error msg="Velero restore error: error getting namespace sraghave-clu2: timed out waiting for the condition" logSource="/remote-source/velero/app/pkg/controller/restore_controller.go:553" restore=open-cluster-management-backup/restore-acm-acm-credentials-schedule-20240209100035
```

I would like the error to be like this instead
```
Errors:
  Velero:   error getting namespace sraghave-clu1: timed out waiting for the condition logSource="/remote-source/velero/app/pkg/controller/restore_controller.go:553"
            error getting namespace sraghave-clu1: timed out waiting for the condition logSource="/remote-source/velero/app/pkg/controller/restore_controller.go:553"
            error getting namespace sraghave-clu2: timed out waiting for the condition logSource="/remote-source/velero/app/pkg/controller/restore_controller.go:553"
            error getting namespace sraghave-clu2: timed out waiting for the condition logSource="/remote-source/velero/app/pkg/controller/restore_controller.go:553"
  Cluster:    <none>
  Namespaces: <none>
```

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
IMHO, stack trace is more useful for the developers but not for the end uses. 
The stack trace is already contained in the logs, right?

**Comment by kaovilai** [comment]
> already contained in the logs, right?

Only if you are able to see the container (or restore) logs. If user reported the issue, they most likely have the backup/restore describe so it's easier at first glance to get a sense of what went wrong.
