### ISSUE TITLE
Since Velero v1.12.0 and newer, backing up a non-existing namespace is now reporting as "Completed" instead of "Failure" this affects our failed alerts

### ISSUE THREAD

**Issue by egondalia** [vmware-tanzu/velero#7431]
**Velero Version 1.11.1 and older output STATUS worked ok, either a Failed or PartiallyFailed running below:  (see results below)**

1. Velero Versions =< 1.11.1 - Create backup of a **non-existing NameSpace** (status fails ok)

`velero backup create mybackup1-11.1-and-older --include-namespaces 'nonexisting1ns' --include-resources '*' --include-cluster-resources=true`

Results
```
velero get backup
NAME                                             STATUS                ERR   WARN   CREATED                         
mybackup1-11.1-and-older                         **PartiallyFailed**   1     0          2024-02-14 09:44:05 +0000 UTC   

```
###########################################################################################

**Running the same command on Velero Version(s) greater than 1.12.0 (status now shows  "Completed" but should show as failure because the namespace does not exist)**

2 Velero Version above > 1.11.1 - Backup of a non-existing NameSpace (shows Completed should state failure BUG)

`velero backup create mybackup1-12-0-and-above --include-namespaces 'nonexisting1ns'' --include-resources '*' --include-cluster-resources=true
`
Results

(Note the 2nd job should states a failure but shows up Completed, the Namespace does not exist but still completes)
```
velero get backup
NAME                                              STATUS            ERR   WARN   CREATED                         
mybackup1-11.1-and-older                      PartiallyFailed       1     0          2024-02-14 09:44:05 +0000 UTC   
mybackup1-12-0-and-above                       **Completed**         0     0          2024-02-14 10:03:51 +0000 UTC   

```
**What did you expect to happen:**
The second job should also have failed or reported as PartiallyFailed like previous versions of Velero did, any version above 1.11.1 is now outputs the Status as Completed instead of failed (note: The Namespace I am backing up does not exist so should continue to fail on newer version)

**Comment by ywk253100** [comment]
The change was introduced by https://github.com/vmware-tanzu/velero/pull/6320

**Comment by ywk253100** [comment]
#6320 removed the logic to check the existence of namespaces

**Comment by ywk253100** [comment]
Create a PR to fix this issue: https://github.com/vmware-tanzu/velero/pull/7569
After the PR merged, the backup will report a validation error if the specified namespaces don't exist
