### ISSUE TITLE
Update latest update on the Homepage

### ISSUE THREAD

**Issue by smyja** [vmware-tanzu/velero#7436]
**Describe the problem/challenge you have**

Latest release information points to an older version
https://velero.io/blog/velero-1.11/
**Describe the solution you'd like**

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by ywk253100** [comment]
We don't post new blogs for every release. Please check the [release](https://github.com/vmware-tanzu/velero/releases) page for the latest information.

**Comment by smyja** [comment]
Then you probably should remove it from that homepage.
