### ISSUE TITLE
how to install a FIPS Compliant velero version in Redhat clusters.

### ISSUE THREAD

**Issue by Naveen-Kamagani** [vmware-tanzu/velero#7448]
how to install a FIPS Compliant velero version in Redhat clusters.

**Environment:**
Redhat clusters - 8 or 9 versions

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by shubham-pampattiwar** [comment]
@Naveen-Kamagani you can install FIPS compliant velero via OADP (OpenShift API for Data Protection) Operator on Openshift/Red Hat Clusters.
OADP Operator docs: https://docs.openshift.com/container-platform/4.14/backup_and_restore/application_backup_and_restore/oadp-intro.html
Upstream OADP Operator project: https://github.com/openshift/oadp-operator

**Comment by Naveen-Kamagani** [comment]
@shubham-pampattiwar which crypto package is used in OADP operator, could you please provide more specifics if you have any idea ?

**Comment by shubham-pampattiwar** [comment]
@Naveen-Kamagani This is what I could find for Support for FIPS cryptography: https://docs.openshift.com/container-platform/4.14/installing/installing-fips.html
