### ISSUE TITLE
Restored pod with PVR failed to connect to the kube-apiserver

### ISSUE THREAD

**Issue by bluzarraga** [vmware-tanzu/velero#7457]
**What steps did you take and what happened:**

1. Backup pod with PVC and restore post hooks
2. Run restore
3. Restore "Completes" but the post hook fails with error code 1 and the pasted error below

This example is running a script that runs a simple pg_restore command on an existing keycloak edb pod, but the keycloak-backup pod is completely cut off from the kube api. In order to run this pg_restore command, we need to exec into the running postgres pod which is why we need access to the kube api. I can create a new deployment that binds to the same PVC and manually run the script inside the newly deployed pod but the pod created by velero during the restore will never connect. I have noticed that the only difference in pod definition when recreating the pod is the removal of the restic init container which I suspect to be involved somehow. I have also found that once this issue is hit on a cluster, no amount of deleting and recreating the restored resources and the restore objects will change the outcome. Once I hit this issue, I always hit this issue and it prevents restore of this resource on this cluster.

Example of error:
>time="2024-02-02T17:43:26Z" level=info msg="stdout: [INFO] Mode is set to restore, beginning restore process.\n" hookCommand="[sh -c /keycloak/br_keycloak.sh restore int-oadp int-oadp]" hookContainer=keycloak-br hookName="<from-annotation>" hookOnError=Fail hookPhase=post hookSource=annotation hookTimeout="{5m0s}" hookType=exec logSource="/remote-source/velero/app/pkg/podexec/pod_command_executor.go:173" pod=int-oadp/keycloak-backup-7cd87fb7f4-gwzkz restore=openshift-adp/ben-investigation-1time="2024-02-02T17:43:26Z" level=info msg="stderr: E0202 17:40:26.823349      13 memcache.go:238] couldn't get current server API group list: Get \"https://172.30.0.1:443/api?timeout=32s\": dial tcp 172.30.0.1:443: i/o timeout\nE0202 17:40:56.824932      13 memcache.go:238] couldn't get current server API group list: Get \"https://172.30.0.1:443/api?timeout=32s\": dial tcp 172.30.0.1:443: i/o timeout\nE0202 17:41:26.826748      13 memcache.go:238] couldn't get current server API group list: Get \"https://172.30.0.1:443/api?timeout=32s\": dial tcp 172.30.0.1:443: i/o timeout\nE0202 17:41:56.827363      13 memcache.go:238] couldn't get current server API group list: Get \"https://172.30.0.1:443/api?timeout=32s\": dial tcp 172.30.0.1:443: i/o timeout\nE0202 17:42:26.828493      13 memcache.go:238] couldn't get current server API group list: Get \"https://172.30.0.1:443/api?timeout=32s\": dial tcp 172.30.0.1:443: i/o timeout\nE0202 17:42:56.829524      13 memcache.go:238] couldn't get current server API group list: Get \"https://172.30.0.1:443/api?timeout=32s\": dial tcp 172.30.0.1:443: i/o timeout\nE0202 17:43:26.831342      13 memcache.go:238] couldn't get current server API group list: Get \"https://172.30.0.1:443/api?timeout=32s\": dial tcp 172.30.0.1:443: i/o timeout\nUnable to connect to the server: dial tcp 172.30.0.1:443: i/o timeout\n" hookCommand="[sh -c /keycloak/br_keycloak.sh restore int-oadp int-oadp]" hookContainer=keycloak-br hookName="<from-annotation>" hookOnError=Fail hookPhase=post hookSource=annotation hookTimeout="{5m0s}" hookType=exec logSource="/remote-source/velero/app/pkg/podexec/pod_command_executor.go:174" pod=int-oadp/keycloak-backup-7cd87fb7f4-gwzkz restore=openshift-adp/ben-investigation-1time="2024-02-02T17:43:26Z" level=error msg="Error executing hook" error="command terminated with exit code 1" hookPhase=post hookSource=annotation hookType=exec logSource="/remote-source/velero/app/internal/hook/wait_exec_hook_handler.go:173" pod=int-oadp/keycloak-backup-7cd87fb7f4-gwzkz restore=openshift-adp/ben-investigation-1 

Example of difference between pods with and without restic init container:
![image](https://github.com/vmware-tanzu/velero/assets/31223504/b7c84235-7f9e-4917-bfbd-00973b8e77dc)

**What did you expect to happen:**
Succesful completion of restore or at least a PartiallyFailed output instead of Completed.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 
[bundle-2024-02-21-13-24-03.tar.gz](https://github.com/vmware-tanzu/velero/files/14365255/bundle-2024-02-21-13-24-03.tar.gz)

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

We are using velero via OADP 1.3. From what I can tell, this issue only happens when restoring pods with post restore hooks and I typically notice it when running OC commands (which is a kubectl wrapper for openshift). This is a very nasty bug that essentially bricks our ability to restore to a cluster that sees this problem. The problem is intermittent but once a cluster hits it once, it almost never works again.

**Environment:**

- Velero version (use `velero version`): 1.12.1-OADP
- Velero features (use `velero client config get features`):  <NOT SET>
- Kubernetes version (use `kubectl version`): v1.27.9+e36e183
- Kubernetes installer & version: OpenShift 4.14.10
- Cloud provider or hardware configuration: amd64
- OS (e.g. from `/etc/os-release`): RHEL 8.8

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
For the Velero v1.12.x filesystem restore, the `restore-wait` InitContainer is created for the restore PodVolume mounted Pods.
That InitContainer is used as a checker for whether the volume data is restored completely before starting the pod.
I don't think that is related to the kube-api connection issue.

What is the post restore hook content?
Please also check whether this address is accessible in the restored pod. `[https://172.30.0.1:443/api?timeout=32s](https://172.30.0.1/api?timeout=32s%5C)`

**Comment by bluzarraga** [comment]
The post restore hook runs a script that does the following:
- checks for a job to have completed, waits until completion
- patch secret with value from backup
- determine primary postgres pod
- copy over dump file from restored PVC/pod into postgres pod
- exec into postgres pod and run pg_restore
- restart a different pod upon successful pg_restore to pick up restored data

Each of those commands requires the use of the OC cli. The reason I think it is related to the initContainer is that is the only difference I can see between the restored pod and the pod I create and I can always run OC commands when I create the pod myself.

I had to recreate on a new cluster but I got the same result and it points to the same IP address which seems to be the master kube api address. The first pod is the restored pod (note the inclusion of the init container) and took the full 32 seconds before timing out. The second pod is pod I created after and immediately presented the error below.
```
[root@<cluster>]# oc exec -it keycloak-backup-8648fc5dc6-xvhbw bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "keycloak-br" out of: keycloak-br, restore-wait (init)
bash-4.4$ curl https://172.30.0.1:443/api?timeout=32s
curl: (7) Failed to connect to 172.30.0.1 port 443: Connection timed out
bash-4.4$ exit
exit
command terminated with exit code 7
[root@<cluster>]# oc exec -it keycloak-backup-6c75b848c6-729rx bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
bash-4.4$ curl https://172.30.0.1:443/api?timeout=32s
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
bash-4.4$ 
```

IP address explanation:
```
[root@<cluster>]# oc get service
NAME         TYPE           CLUSTER-IP   EXTERNAL-IP                            PORT(S)   AGE
kubernetes   ClusterIP      172.30.0.1   <none>                                 443/TCP   24h
openshift    ExternalName   <none>       kubernetes.default.svc.cluster.local   <none>    24h
```

**Comment by blackpiglet** [comment]
I still don't think the InitContainer is the problem, but the restored keycloak pod has some volume data restored with it too.
That could cause the issue.
Please check which volumes are backed up and restored, and what's in it.

**Comment by bluzarraga** [comment]
I was using the keycloak as an example because I had it readily available on my cluster but I have seen this problem with other pods with the following criteria:
- bound PVC
- post restore hook
- OC command run in post restore hook

I do not think it is specifically related to keycloak

**Comment by bluzarraga** [comment]
@blackpiglet I understand there is a timezone difference that could drag this issue out, what other info can I provide to help with this investigation? This problem has hamstrung my ability to consistently restore multiple components and I am interested in resolving it as swiftly as possible.

**Comment by bluzarraga** [comment]
It looks like it could be a general connectivity problem as trying to curl google results in an error but when I try from the pod I created it returns a response from google:
```
[root@api.o1-708962.cp.fyre.ibm.com ~]# oc exec -it keycloak-backup-8648fc5dc6-xvhbw bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "keycloak-br" out of: keycloak-br, restore-wait (init)
bash-4.4$ curl www.google.com
curl: (6) Could not resolve host: www.google.com
bash-4.4$ exit
exit
command terminated with exit code 6
[root@api.o1-708962.cp.fyre.ibm.com keycloak]# oc exec -it keycloak-backup-6c75b848c6-w4xjb bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
bash-4.4$ curl www.google.com
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/logos/doodles/2024/casimir-funks-140th-birthday-6753651837110355-l.png" itemprop="image"><meta content="Casimir Funk's 140th Birthday" property="twitter:title"><meta content="Casimir Funk's 140th Birthday! #GoogleDoodle" property="twitter:description"><meta content="Casimir Funk's 140th Birthday! #GoogleDoodle" proper
[etc, etc, etc]
```

**Comment by blackpiglet** [comment]
I'm trying to figure out what could go wrong in your scenario.

* Because you are facing a network issue in your restored workload, and the workload volume data is backed up by filesystem backup, I suggest you try snapshot volume backup if your environment supports that.
* Please check whether there are any network policies configured in the k8s environment. https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by blackpiglet** [comment]
@shubham-pampattiwar @kaovilai 
Could you help also to take a look at this issue?
I'm uncertain about whether this is OpenShift-specific.
The filesystem uploader backs the restored workload's volume data, but the restored workload cannot access the kube-apiserver.

**Comment by weshayutin** [comment]
@bluzarraga perhaps https://issues.redhat.com/ is a more appropriate place to log the issue.

**Comment by sseago** [comment]
@bluzarraga Are you restoring to a different cluster than you backed up from? There was an issue with the openshift plugin in OADP that caused this problem on cross-cluster restores. We were omitting the ReplicaSet from restore to allow the Deployment to create a new one, which works fine for same-cluster restores, but in cross-cluster restores, the ReplicaSet ends up with a different name if it's recreated from scratch, but it's fine if restored normally. That will prevent the orphaned pod problem if you're restoring to a different cluster, although I don't know if it will solve the rest of your problem. This fix will be released in OADP 1.3.1.

**Comment by sseago** [comment]
@bluzarraga "Is it possible to not restore the pod while still restoring its data and allowing the deployment to create a pod to mount to this restored data?"

With restic/kopia fs-backup, this is not possible, because if a pod is not mounting the volume, then the node agent will not have access to that volume either, since the node agent uses mount propagation to access volumes mounted by pods on the same node. Also, if we didn't restore the pod, then you would be unable to run post-restore hooks.

**Comment by bluzarraga** [comment]
> Are you restoring to a different cluster than you backed up from? There was an issue with the openshift plugin in OADP that caused this problem on cross-cluster restores

Yes, this is from one cluster to a different cluster. I will try excluding the restore of the replicaset and see if that makes a difference.

> With restic/kopia fs-backup, this is not possible

This is how I thought it worked but wanted to confirm. Theoretically, if we block the replicaset and pod from being restored and the deployment is instead restored, would the pod ultimately created by this deployment be "recognized" by restic for the restore to take place?

**Comment by sseago** [comment]
"This is how I thought it worked but wanted to confirm. Theoretically, if we block the replicaset and pod from being restored and the deployment is instead restored, would the pod ultimately created by this deployment be "recognized" by restic for the restore to take place?"

No -- this fails for two reasons:
1) The pod may not have the same name as the restored pod, but the PodVolumeRestore created is based on pod name, so it will never look for a pod with a different name.
2) The restic-wait init container won't be in the pod.

Also, you won't get pod hooks, since pod hooks only run on pod restore.

**Comment by sseago** [comment]
But again, this may all just work once you get the pod duplication fix. One thing to try -- if you restore the pod but not the Deployment, you won't get a duplicated pod, I wonder whether that would work, not as a complete solution for you, but if this works, it's a good indication that the ReplicaSet plugin fix will resolve this.

**Comment by bluzarraga** [comment]
I went and recreated the issue again while trying to exclude both the deployment and the replicaset from being restored. Unfortunately this has not made a difference. The pod is restored and I can exec into it and see the data it requires was also restored but it is still disconnected from the apiserver and unable to run oc commands or run curl commands.

**Comment by sseago** [comment]
@bluzarraga ok, so I guess that's good and bad news. The good news is that the ReplicaSet/pod duplication issue is not causing the network problem and the pod issue will go away once you're on the next version with the bug fix. The bad news is that we still don't have any idea what's causing the apiserver issue. It doesn't seem like it could be a velero problem -- velero just creates the pod, if the pod is having connection issues within the cluster, it seems more like a cluster issue. One more thing to check, though -- can you compare the pod yaml post-restore (where you can't connect) with the pod yaml in the backup cluster where it was working. I wonder whether there are any other differences there. Also, are there possibly other resources that are necessary for your pod to be fully functional that were not restored?

Also, if you create a completely different Deployment manually in the restore cluster for the same application, does the pod work there? If you get the same error, then I guess then it's clear the problem isn't a velero one. If it works, then maybe the pod yaml differences between the working and non-working will give a clue. Maybe there is some env var or other reference in the pod that has a wrong value for the restore cluster.

**Comment by bluzarraga** [comment]
@sseago so presently our workaround is to create a new deployment that binds to the restored pvc and run the script from the pod created by this new deployment and this works consistently. The problem only seems to be with the initial pod created during the restore. 

From what I can tell comparing the two pod yamls, the only difference is the restic init container, everything else looks the same.

**Comment by bluzarraga** [comment]
I have developed a very simple way to recreate this problem without having to install IBM specific workloads. Assuming velero/OADP setup, you can take the following steps to recreate the problem locally.
1. clone my forked repo: https://github.com/bluzarraga/ibm-common-service-operator/tree/simple-recreate
2. navigate to https://github.com/bluzarraga/ibm-common-service-operator/tree/simple-recreate/velero/schedule/simplerecreate
3. edit each file in the directory so it can be applied (should just need to fill in namespace and storage class values within <>)
4. apply files to backup cluster
5. create backup object that looks for label foundationservices.cloudpak.ibm.com=simple-recreate-data. You could also use the file https://github.com/bluzarraga/ibm-common-service-operator/blob/simple-recreate/velero/schedule/schedule-common-services.yaml
6. complete backup
7. on a separate cluster, create the same namespace, deploy the same storage class, and setup velero/OADP
8. run the restore using https://github.com/bluzarraga/ibm-common-service-operator/blob/simple-recreate/velero/restore/restore-simple-recreate.yaml

It may take a couple tries, I see this issue intermittently and not every time. Please let me know if this is possible because if it is it could be easier than the back and forth we have had so far.

**Comment by atanasmatev** [comment]
Hello @bluzarraga ,
 I am facing exactly the same issue with the IBM CS-DB restore. When I use the backed up deployment, it spins up a pod, but the pod can't reach the API. I tried your workaround (deleted the deployment and created a new one from scratch), and it worked. It is strange that the IBM Cloud PAK Foundational Services backup and restore documentation explicitely mentions this scenario for CS-DB and Zen DB. And the workaround they provide is to create a new Job that they provide in their Git which basically does the same. Did you manage to find the root cause of this issue? I tend to believe that it is Velero related also.
