### ISSUE TITLE
velero-plugin-for-csi sometimes backups PVC even when disabled

### ISSUE THREAD

**Issue by UAntBou** [vmware-tanzu/velero#7460]
**What steps did you take and what happened:**

We use velero to backup our clusters, without the volumes. Sometimes (not frequently) we have 1 PVC which is backed up among all other PVCs which are not backed up (what we want).  

**What did you expect to happen:**

Avoid all PVC backups. For information these PVCs are linked to a StatefulSet.

**The following information will help us better understand what's going on**:

You can see that the PVC 4 is creating a backup while the PVC 5 (and all others) does not.

```
{"log":"time=\"2024-02-08T04:02:06Z\" level=info msg=\"Executing custom action\" backup=velero/$BACKUP_NAME logSource=\"pkg/backup/item_backupper.go:325\" name=pvc-$STATEFULSET-4 namespace=$NAMESPACE resource=persistentvolumeclaims\n","stream":"stdout","time":"2024-02-08T04:02:06.513086562Z"}
{"log":"time=\"2024-02-08T04:02:06Z\" level=info msg=\"Starting PVCBackupItemAction\" backup=velero/$BACKUP_NAME cmd=/plugins/velero-plugin-for-csi logSource=\"/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:58\" pluginName=velero-plugin-for-csi\n","stream":"stdout","time":"2024-02-08T04:02:06.513968579Z"}
{"log":"time=\"2024-02-08T04:02:06Z\" level=info msg=\"Fetching storage class for PV $STORAGECLASS\" backup=velero/$BACKUP_NAME cmd=/plugins/velero-plugin-for-csi logSource=\"/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:102\" pluginName=velero-plugin-for-csi\n","stream":"stdout","time":"2024-02-08T04:02:06.545386672Z"}
[...]

{"log":"time=\"2024-02-08T04:02:06Z\" level=info msg=\"Executing custom action\" backup=velero/$BACKUP_NAME logSource=\"pkg/backup/item_backupper.go:325\" name=pvc-$STATEFULSET-5 namespace=$NAMESPACE resource=persistentvolumeclaims\n","stream":"stdout","time":"2024-02-08T04:02:06.6632995Z"}
{"log":"time=\"2024-02-08T04:02:06Z\" level=info msg=\"Starting PVCBackupItemAction\" backup=velero/$BACKUP_NAME cmd=/plugins/velero-plugin-for-csi logSource=\"/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:58\" pluginName=velero-plugin-for-csi\n","stream":"stdout","time":"2024-02-08T04:02:06.664255818Z"}
{"log":"time=\"2024-02-08T04:02:06Z\" level=info msg=\"Volume snapshotting not requested for backup velero/$BACKUP_NAME\" backup=velero/$BACKUP_NAME cmd=/plugins/velero-plugin-for-csi logSource=\"/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:62\" pluginName=velero-plugin-for-csi\n","stream":"stdout","time":"2024-02-08T04:02:06.66437642Z"}
```

**Anything else you would like to add:**

This code seems to be skipped sometimes for the same backup : https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/v0.5.0/internal/backup/pvc_action.go#L61-L64

**Environment:**

- Velero version (use `velero version`): v1.11.0
- Velero features (use `velero client config get features`): features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.25.12
- Kubernetes installer & version: Rancher v2.7.6
- velero-plugin-for-csi v0.5.0 (but the code seems to be the same in the latest release)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by shubham-pampattiwar** [comment]
What does your Backup CR look like ?

**Comment by blackpiglet** [comment]
@UAntBou 
If it's possible, please help to collect the debug bundle by `velero debug`.

**Comment by UAntBou** [comment]
Hello @shubham-pampattiwar , we use Schedules so here is the configuration we have : 

```
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: $BACKUP_NAME
  namespace: velero
spec:
  schedule: 0 * * * *
  template:
    defaultVolumesToFsBackup: false
    excludedNamespaces: ...
    excludedResources: ...
    includeClusterResources: true
    includedNamespaces: ...
    metadata: ...
    snapshotVolumes: false
    storageLocation: default
    ttl: 168h0m0s
```

Hello @blackpiglet , I reviewed the content of the archive created by your command and it contains a lot of information I can't share, sorry

**Comment by blackpiglet** [comment]
@UantBou
Understood that.
I suggest upgrading the Velero and the CSI plugin version to 1.30.0 and v0.7.0.
That release includes a PR to fix the CSI feature enabling check logic.
https://github.com/vmware-tanzu/velero/pull/7077

**Comment by UAntBou** [comment]
Thank you for your reply, I'll switch to the new versions and open a new issue if the bug is still present.
