### ISSUE TITLE
glibc version mismatch in velero-upgrade-crds

### ISSUE THREAD

**Issue by ariep** [vmware-tanzu/velero#7462]
**What steps did you take and what happened:**
While attempting to `helm upgrade` velero -- not actually upgrading velero, just changing some helm values -- the pre-upgrade hook `velero-upgrade-crds` fails consistently:
```
# kubectl logs -n velero velero-upgrade-crds-lf5j9
Defaulted container "velero" out of: velero, kubectl (init)
/tmp/sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/sh)
/tmp/sh: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/sh)
```

**What did you expect to happen:**
I expect the upgrade hook to succeed -- and do nothing, as this is not an actual upgrade.

**The following information will help us better understand what's going on**:
`velero debug` doesn't seem relevant here as there is no backup or restore involved.

**Anything else you would like to add:**

I know my velero version is a bit old -- we're managing a fleet of clusters and have to take some extra steps first because of breaking changes in velero 1.12.

**Environment:**

- Velero version (use `velero version`):
  ```
  # velero version
  Client:
          Version: v1.11.1
          Git commit: bdbe7eb242b0f64d5b04a7fea86d1edbb3a3587c
  Server:
          Version: v1.11.1
  ```
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): `Server Version: v1.28.2+k3s1`
- Kubernetes installer & version: k3s
- Cloud provider or hardware configuration: Greenhost
- OS (e.g. from `/etc/os-release`): Debian 11

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by fishgrimsby** [comment]
After reading [this issue](https://github.com/vmware-tanzu/helm-charts/issues/550) I found that setting the following in my values.yaml let me get past the problem:

```
kubectl:
      image:
        repository: docker.io/bitnami/kubectl
        tag: 1.26.14-debian-11-r6
```

**Comment by DavidS-ovm** [comment]
This is https://github.com/vmware-tanzu/helm-charts/issues/537

**Comment by anushkafer** [comment]
> After reading [this issue](https://github.com/vmware-tanzu/helm-charts/issues/550) I found that setting the following in my values.yaml let me get past the problem:
> 
> ```
> kubectl:
>       image:
>         repository: docker.io/bitnami/kubectl
>         tag: 1.26.14-debian-11-r6
> ```

This works for me!

**Comment by samuelv8** [comment]
This image isn't available anymore. I get the following error

```
Failed to pull image "docker.io/bitnami/kubectl:1.26.14-debian-11-r6": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/bitnami/kubectl:1.26.14-debian-11-r6": failed to resolve reference "docker.io/bitnami/kubectl:1.26.14-debian-11-r6": docker.io/bitnami/kubectl:1.26.14-debian-11-r6: not found
```

This is likely because bitnami has cut the free access to pinned images. I've changed to the legacy repository to make it work.
```
kubectl:
      image:
        repository: docker.io/bitnamilegacy/kubectl
        tag: 1.26.14-debian-11-r6
```
