### ISSUE TITLE
velero restore describe with --details option does not show PodVolumeRestore info

### ISSUE THREAD

**Issue by yipng** [vmware-tanzu/velero#7464]
**What steps did you take and what happened:**

The restore describe command below does not display the kopia or restic Restores info when --details option is specified.
The backup was a file system backup using kopia path

`velero restore describe --details restore-test -n openshift-adp`

**What did you expect to happen:**

It should display the info, e.g.:

```
kopia Restores:
  Completed:
    testns/my-edb-2: pgdata
```

**Anything else you would like to add:**

I believe this source code line is the issue:

https://github.com/vmware-tanzu/velero/blob/e1222ffd740a9a685a5bba898107ad28a6c6f633/pkg/cmd/cli/restore/describe.go#L77

It should use **velerov1api.RestoreNameLabel** instead of **velerov1api.BackupNameLabel**

**Environment:**

- Velero version v1.13.0
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"ac58b184e8bf6ad7a8e5d387ec4f76bc2b7c3d9a", GitTreeState:"clean", BuildDate:"2023-09-18T19:44:04Z", GoVersion:"go1.19.10 X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.12+ba5cc25", GitCommit:"cd33b979be9160c25e490d60aecc9c17920f959f", GitTreeState:"clean", BuildDate:"2023-09-12T08:34:39Z", GoVersion:"go1.19.10 X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64"}
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Thanks for pointing this out. I will create a PR to fix it.

**Comment by navilg** [comment]
@blackpiglet Which version has this fix ?

**Comment by blackpiglet** [comment]
Both v1.13.x and v1.14.x have the fix.

**Comment by navilg** [comment]
Thanks @blackpiglet I see it in 1.14.0
