### ISSUE TITLE
Velero backup creation struck at "In Progress "Phase

### ISSUE THREAD

**Issue by medivyaa** [vmware-tanzu/velero#7471]
Hi There,

We are trying to take velero backup on our AKS cluster (version "1.27.3") by using below command.

**velero backup create <backupname> \
--include-namespaces '*' \
--include-resources '*' \
--include-cluster-resources=true**

Velero plugin version: **1.7.1**
Velero version: **1.11.1**

The backup state is in progress state, though all the backup items present in cluster are backed up.

![image (13)](https://github.com/vmware-tanzu/velero/assets/83200478/d6d6b8f5-e76a-4ece-92e7-e43c8f021396)
![image (12)](https://github.com/vmware-tanzu/velero/assets/83200478/d03fd2c4-66cd-4387-9c24-caf4fa7fd517)

**Comment by reasonerjt** [comment]
1. Is it reproducible?
2. What's the status of velero pod, was it restarted when the backup is inProgress and the controller failed to update the status via reconciliation?
3. Have you been able to check the log for velero pod?
4. Do you get successful backup if you narrow down the scope of backup, for example, backup only a few namespaces?

**Comment by medivyaa** [comment]
Please find the screenshot below.
![image](https://github.com/vmware-tanzu/velero/assets/83200478/33d5ae47-cda7-4073-9cb4-1a743b5a7662)

Please connect with bdudeja@dxc.com & divya.javangula@dxc.com  for further details.

**Comment by medivyaa** [comment]
Hi ,

Any workaround or suggestion for the above. 
Your response is highly valuable.

**Comment by reasonerjt** [comment]
More details are needed to help us understand the problem.

Please answer the questions in [this comment](https://github.com/vmware-tanzu/velero/issues/7471#issuecomment-1965583715)
