### ISSUE TITLE
Velero expects a BSL named default 

### ISSUE THREAD

**Issue by rumeshmadhusanka** [vmware-tanzu/velero#7473]
**What steps did you take and what happened:**

I upgraded Velero from 1.11 to 1.13.0.
I had created BSL and VSL both in names other than "default"
After upgrading to 1.13 Velero pod starts failing with the error <i>backupstoragelocations.velero.io "default" not found</i>:

```
time="2024-02-27T09:29:01Z" level=info msg="Found custom resource" kind=DataDownload logSource="pkg/cmd/server/server.go:534"
time="2024-02-27T09:29:01Z" level=info msg="Found custom resource" kind=DataUpload logSource="pkg/cmd/server/server.go:534"
time="2024-02-27T09:29:01Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:552"
time="2024-02-27T09:29:01Z" level=warning msg="Velero node agent not found; pod volume backups/restores will not work until it's created" logSource="pkg/cmd/server/server.go:624"
An error occurred: backupstoragelocations.velero.io "default" not found
```
After creating an identical BSL named default, Velero pod starts.

**What did you expect to happen:**

**The following information will help us better understand what's going on**:
I created the VSL though the Helm chart, and want to use the same VSL without creating a second "default" BSL or deleting the original BSL

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
Client:
	Version: v1.13.0
	Git commit: -
Server:
	Version: v1.13.0
- Velero features (use `velero client config get features`):  `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): 1.29
- Kubernetes installer & version: Helm, 1.13
- Cloud provider or hardware configuration: AWS S3, EKS, IRSA
- OS (e.g. from `/etc/os-release`): Amazon Linux

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
This is a duplicate issue with #7359. 
Please try with the main release Velero image as a temporary solution.
The planned v1.13.1 will contain the fix.

**Comment by rumeshmadhusanka** [comment]
Thank you!.
Closing this issue as this is a duplicate
