### ISSUE TITLE
Velero restore error: timed out waiting for all PodVolumeRestores to complete - Kopia - Restore shows "PartiallyFailed"

### ISSUE THREAD

**Issue by DileepAP** [vmware-tanzu/velero#7480]
**What steps did you take and what happened:**
Using Velero v1.12 with AWS plugin v1.8.2, all PV's are local volumes based on openebs and i am using "--default-volumes-to-fs-backup" and kopia is used.

**What did you expect to happen:**
Expect the restore comes be competed successfully, it always shows "PartiallyFailed"
[Uploading bundle-2024-02-29-04-15-47.tar.gz…]()

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): v1.12
- Velero features (use `velero client config get features`): Kopia,  velero-plugin-for-aws:v1.8.2, "--use-node-agent --default-volumes-to-fs-backup --privileged-node-agent" use these options as the PV's are local volumes based on openebs
- Kubernetes version (use `kubectl version`): v1.28.6
- Kubernetes installer & version: microk8s / snap
- Cloud provider or hardware configuration: Hypervisors  - Hyper-V 
- OS (e.g. from `/etc/os-release`): Red Hat Enterprise Linux 8.9 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
@DileepAP 
The debug bundle is not uploaded. The link is empty.

**Comment by DileepAP** [comment]
[bundle-2024-02-29-04-15-47.tar.gz](https://github.com/vmware-tanzu/velero/files/14451462/bundle-2024-02-29-04-15-47.tar.gz)
[bundle-2024-02-29-04-15-47.tar.gz](https://github.com/vmware-tanzu/velero/files/14451465/bundle-2024-02-29-04-15-47.tar.gz)

**Comment by DileepAP** [comment]
debug bundle uploaded.

**Comment by blackpiglet** [comment]
``` json
        {
            "apiVersion": "velero.io/v1",
            "kind": "PodVolumeRestore",
            "metadata": {
                "creationTimestamp": "2024-02-28T16:40:00Z",
                "generateName": "bdhpbrdhvvm1fullbkp2-20240228163841-",
                "generation": 1,
                "labels": {
                    "velero.io/pod-uid": "47638f44-c590-4ba0-8c44-d18a320ad2d6",
                    "velero.io/restore-name": "bdhpbrdhvvm1fullbkp2-20240228163841",
                    "velero.io/restore-uid": "f839c57b-9f01-431e-9450-608aad4d5493"
                },
                "name": "bdhpbrdhvvm1fullbkp2-20240228163841-xc6js",
                "namespace": "velero",
                "ownerReferences": [
                    {
                        "apiVersion": "velero.io/v1",
                        "controller": true,
                        "kind": "Restore",
                        "name": "bdhpbrdhvvm1fullbkp2-20240228163841",
                        "uid": "f839c57b-9f01-431e-9450-608aad4d5493"
                    }
                ],
                "resourceVersion": "13120",
                "uid": "d7de18d8-5d4c-4845-8713-a0bd458483d5"
            },
            "spec": {
                "backupStorageLocation": "default",
                "pod": {
                    "kind": "Pod",
                    "name": "metrics-server-848968bdcd-7k822",
                    "namespace": "kube-system",
                    "uid": "47638f44-c590-4ba0-8c44-d18a320ad2d6"
                },
                "repoIdentifier": "s3:https://bdhpbrdhvvm8.stg.baxter.com:7443/velero-bucket/restic/kube-system",
                "snapshotID": "0cbd44f249aac4de2b2f046f2a07aa03",
                "sourceNamespace": "kube-system",
                "uploaderType": "kopia",
                "volume": "tmp-dir"
            },
            "status": {
                "progress": {}
            }
```

``` json
        {
            "apiVersion": "velero.io/v1",
            "kind": "PodVolumeRestore",
            "metadata": {
                "creationTimestamp": "2024-02-28T16:40:07Z",
                "generateName": "bdhpbrdhvvm1fullbkp2-20240228163841-",
                "generation": 1,
                "labels": {
                    "velero.io/pod-uid": "db91f079-a2ea-4215-98dc-6463a52ca01f",
                    "velero.io/restore-name": "bdhpbrdhvvm1fullbkp2-20240228163841",
                    "velero.io/restore-uid": "f839c57b-9f01-431e-9450-608aad4d5493"
                },
                "name": "bdhpbrdhvvm1fullbkp2-20240228163841-jqxg5",
                "namespace": "velero",
                "ownerReferences": [
                    {
                        "apiVersion": "velero.io/v1",
                        "controller": true,
                        "kind": "Restore",
                        "name": "bdhpbrdhvvm1fullbkp2-20240228163841",
                        "uid": "f839c57b-9f01-431e-9450-608aad4d5493"
                    }
                ],
                "resourceVersion": "13354",
                "uid": "68066e18-7923-4dda-888e-602dde9bc33d"
            },
            "spec": {
                "backupStorageLocation": "default",
                "pod": {
                    "kind": "Pod",
                    "name": "velero-7f8f7558bc-2pvdj",
                    "namespace": "velero",
                    "uid": "db91f079-a2ea-4215-98dc-6463a52ca01f"
                },
                "repoIdentifier": "s3:https://bdhpbrdhvvm8.stg.baxter.com:7443/velero-bucket/restic/velero",
                "snapshotID": "ed4b3cca936afeac9b24ec9d04e8276e",
                "sourceNamespace": "velero",
                "uploaderType": "kopia",
                "volume": "plugins"
            },
            "status": {
                "progress": {}
            }
        }
```
