### ISSUE TITLE
Why is the job type that restores complete skipped?

### ISSUE THREAD

**Issue by zikysc** [vmware-tanzu/velero#7483]
## Question

When I restore from minio, the kind of  jobs are skipped. Why? How should I make it also be created when restoring?
It will cause my pod to fail to start normally

![image](https://github.com/vmware-tanzu/velero/assets/88381723/432aeb24-9950-4818-b18b-fb112c6d85ce)

![image](https://github.com/vmware-tanzu/velero/assets/88381723/0faece5f-5260-4764-9f2b-cd77435b128b)

## Version
  Client:
	Version: v1.12.4
	Git commit: 7d8417b2c58792422ed6dd4b4c0cf3848b0beb56
  Server:
	Version: v1.12.4

**Comment by reasonerjt** [comment]
It's velero's design to skip the completed jobs.

b/c for the completed jobs, the result has already been persisted, and it should not be executed again during the restore.

Could you explain why the pod depends on a job to start normally?  If it always requires the job, you should consider to turn it into an initContainer

**Comment by synonez** [comment]
It's the init Container, but pod startup seems to check the job directly
![image](https://github.com/vmware-tanzu/velero/assets/88381723/a4f9db4c-e50d-4774-a312-1ec153c68016)
![image](https://github.com/vmware-tanzu/velero/assets/88381723/7f26ffa1-09fe-4dac-8d67-0063597a28d7)

**Comment by reasonerjt** [comment]
@synonez 
IMO this does not justify the change on velero, re-executing a job during restore can be problematic b/c jobs are usually not idempotent.
To workaround, perhaps you can manually create before the restore.

**Comment by synonez** [comment]
Or, is there any other way to realise it?

**Comment by reasonerjt** [comment]
You'll need to understand how the pod in your workload works.
For example, maybe if you don't set the `job-wr` param, it won't wait for any jobs?  If that's the case you can leverage [resource modifier](https://velero.io/docs/v1.13/restore-resource-modifiers) in velero to remove the args during restore.

**Comment by synonez** [comment]
Yes, I found that job is defined in init Containers

```yaml
Init Containers:
   check-migrate-job:
    Args:
      job
      auth-migrate-1
```

**Comment by reasonerjt** [comment]
@synonez 

Based on the discussion, I don't think there's much that velero can do to fix your problem.
Let me know if you still need help in this issue.
