### ISSUE TITLE
Restore-wait permission denied or runing cleanup too early 

### ISSUE THREAD

**Issue by sarahdepillis** [vmware-tanzu/velero#7485]
**What steps did you take and what happened:**

1. Running a restore with the following values in the config map allows the pods to be restored but the restore-wait container never detaches unless I kill the pod after a restore in which it will come back up without the resore-wait container. The restore-wait logs show a permission denied error when trying to run the `unlinkat` command at the end so I'm thinking that may be preventing it from detaching.
```
   allowPrivilegeEscalation: false
   readOnlyRootFilesystem: true
   runAsUser: 1001
   runAsGroup: 999
```

2. I have tried modifying the configmap in multiple ways including changing it to have runAsUser: 0 or runAsGroup: 0 or allowPrivilegeEscalation: true or even readOnlyRootFilesystem: false. The only thing that showed different behavior was runAsUser: 0. However when this was the setting, one of the pods would run a velero cleanup (from logs: `restore-wait Deleted /restores/mattermost-config/.veleroDone cleanup .velero folder)` before the other 3 pods were initialized and so they would get stuck with a `Init:CreateContainerConfigError`.

**What did you expect to happen:**
The restore-wait containers would finish successfully and detach.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): v1.13.0
- Velero features (use `velero client config get features`):
- Kubernetes version (use `kubectl version`): v1.29.1
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
> However when this was the setting, one of the pods would run a velero cleanup (from logs: restore-wait Deleted /restores/mattermost-config/.veleroDone cleanup .velero folder) before the other 3 pods were initialized and so they would get stuck with a Init:CreateContainerConfigError.

Could you give more information about your scenario?
IMO, the deletion of the done file means the PodVolumeRestore succeeded. Why does that make other pods stuck?

**Comment by seism0saurus** [comment]
It seems I hit the same error.

I wanted to test a restore of a Postgres database with a PVC. The postgres DB is located in the lakefs namespace.
Therefore I created a backup with `velero backup create lakefs --include-namespaces lakefs  --wait`.
After the backup is created I try to restore the backup to a new namespace: `velero restore create --from-backup lakefs --namespace-mappings lakefs:lakefs-backup`. The restore itself is finished successfully.
The PVC is created and also the pod but the **restore-wait** container inside the pod never finishes. The state is **running.** It shows this errors. They just repeat more often.
```
The filesystem restore done file /restores/data/.velero/1e50f29e-dbbc-47c0-867a-030683166aeb is not found yet. Retry later.
ERROR looking filesystem restore done file /restores/data/.velero/1e50f29e-dbbc-47c0-867a-030683166aeb: stat /restores/data/.velero/1e50f29e-dbbc-47c0-867a-030683166aeb: permission denied
ERROR looking filesystem restore done file /restores/data/.velero/1e50f29e-dbbc-47c0-867a-030683166aeb: stat /restores/data/.velero/1e50f29e-dbbc-47c0-867a-030683166aeb: permission denied
ERROR looking filesystem restore done file /restores/data/.velero/1e50f29e-dbbc-47c0-867a-030683166aeb: stat /restores/data/.velero/1e50f29e-dbbc-47c0-867a-030683166aeb: permission denied
ERROR looking filesystem restore done file /restores/data/.velero/1e50f29e-dbbc-47c0-867a-030683166aeb: stat /restores/data/.velero/1e50f29e-dbbc-47c0-867a-030683166aeb: permission denied
ERROR looking filesystem restore done file /restores/data/.velero/1e50f29e-dbbc-47c0-867a-030683166aeb: stat /restores/data/.velero/1e50f29e-dbbc-47c0-867a-030683166aeb: permission denied
.
.
.
```
The **postgres** container itself keeps **waiting**.

The cluster is a k3s v1.30.3+k3s1. The PVC is local-path. Velero is 1.14.0.

Do you need any other information to look into this?

**Comment by blackpiglet** [comment]
https://github.com/vmware-tanzu/velero/issues/7192#issuecomment-1916005694

Please check this comment for resolution.

**Comment by seism0saurus** [comment]
Sorry to ask that here but how do I configure the Config Map, if I have multiple deployments in the cluster and they use different users?
As far as I have understood, there is only one Config Map so I can only use one user for restore.

I tried 0, which is normally root, but that didn't have the right permissions.
```
      secCtx: |
        capabilities:
          drop:
            - ALL
          add: [ ]
        allowPrivilegeEscalation: true
        readOnlyRootFilesystem: false
        runAsUser: 0
        runAsGroup: 0
```

**Comment by blackpiglet** [comment]
It seems the controller-runtime client retrieving the ConfigMap was not limited by the namespace, so, in your scenario, the Velero deployments can share the same ConfigMap.

``` yaml
      secCtx: |
        allowPrivilegeEscalation: true
        runAsUser: 0
        runAsGroup: 0
```

How about trying with this configuration?

**Comment by seism0saurus** [comment]
Thanks. It's working.
