### ISSUE TITLE
VGDP snapshot leak when uploader fails to back up partial files

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#7503]
As the configured behavior of uploader (kopia/restic), if some individual files fail to be backed up, the repo snapshot can still be created and the fails are reported as errors which are passed to the backup controllers.

When backup controllers see the errors, it marks the PVBs/DUs as failed. And the repo snapshot IDs are not recorded, as a result, the repo snapshots are not deleted during backup deletion.

**Comment by qiuming-best** [comment]
After our discussion, we reached one agreement:

Once the uploader backup one specific file, we failed the backup immediately (Kopia has one option to fail fast)
