### ISSUE TITLE
Test operation fails even though the path exists (Restore Resource Modifiers)

### ISSUE THREAD

**Issue by sedatsencan** [vmware-tanzu/velero#7517]
**Description**:
I encountered an issue with the test operation in a Velero restore operation. Even though the path exists, the test operation fails, preventing subsequent operations from being executed. Here are the details of the issue:

**Issue Details**:

**Context**: 
I'm performing a Velero restore operation where I'm applying a JSON Patch to modify certain fields in Kubernetes resources.

**Problem**: 
When including a test operation to verify the existence of a path (/spec/template/spec/containers/0/env), the operation fails even though the path exists in the resource.

**Expected Behavior**: 
The test operation should pass successfully since the specified path exists in the resource.

**Observations**:
When removing the test operation, the subsequent add operation succeeds, indicating that the path is indeed present in the resource.
The error message from Velero indicates that the test operation fails, but it doesn't provide specific details on why it fails.

**Steps to Reproduce**:
Perform a Velero restore operation with a JSON Patch including a test operation to verify the existence of a specific path.
Observe that the test operation fails despite the path existing in the resource.

```version: v1
resourceModifierRules:
- conditions:
    groupResource: deployments.apps
    namespaces:
    - staging
  patches:
  - operation: test
    path: "/spec/template/spec/containers/0/env"
  - operation: add
    path: "/spec/template/spec/containers/0/env/-"
    value: "{\"name\": \"SPRING_PROFILES_ACTIVE\", \"value\": \"testing\"}"
```
The yaml I use is as above. Here, when I remove the operation test step, it is added successfully. But the restore process ends with partition failed. So I added a test step to solve this. If there is an env path, I want it to add it.

**By the way, I also tried adding things like value: "", value: null to the test operation in yaml, but it still gives an error.**

Log:
```
time="2024-03-13T11:52:35Z" level=info msg="Test operation failed for JSON Patch testing value /spec/template/spec/containers/0/env failed: test failed" logSource="internal/resourcemodifiers/json_patch.go:66" restore=velero/staging-12-03-2024-20240313145214
time="2024-03-13T11:52:35Z" level=info msg="Test operation failed for JSON Patch testing value /spec/template/spec/containers/0/env failed: test failed" logSource="internal/resourcemodifiers/json_patch.go:66" restore=velero/staging-12-03-2024-20240313145214
time="2024-03-13T11:52:35Z" level=info msg="Test operation failed for JSON Patch testing value /spec/template/spec/containers/0/env failed: test failed" logSource="internal/resourcemodifiers/json_patch.go:66" restore=velero/staging-12-03-2024-20240313145214
time="2024-03-13T11:52:35Z" level=info msg="Test operation failed for JSON Patch testing value /spec/template/spec/containers/0/env failed: test failed" logSource="internal/resourcemodifiers/json_patch.go:66" restore=velero/staging-12-03-2024-20240313145214
```
How can I resolve this situation?

**Additional Information**:
Velero Version: 1.13
Kubernetes Version: 1.29

**Comment by anshulahuja98** [comment]
Can you repro the same test through kubectl and see what is the output.
kubectl patch pod valid-pod -type='json’ -p=’[{“op”: “replace”, “path”: “/spec/containers/0/image”, “value”:“new image”}]’

You can change above example for test operator.

**Comment by sedatsencan** [comment]
Actually, the fault here is not the patch. The testing phase fails. When I delete the test operation, the patch is successful. I expect this test operation to work like an if block, but it doesn't.
