### ISSUE TITLE
Use the aggregated discovery to discover the groups/resources

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#7526]
Currently, Velero creates a discovery client when starting up, fetches the API groups every 5 minutes and caches them.
When a backup is created, Velero iterates the cached groups and fetches the resource types for every group and then fetches the objects for every resource type.

Kubernetes introduces a new accept header `Accept: application/json;as=APIGroupDiscoveryList;v=v2beta1;g=apidiscovery.k8s.io` in APIs `api`/`apis` to support returning an aggregated discovery document for all groups/resources in one request.
And Etag is also supported in the new API.
Refer to the [design](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/3352-aggregated-discovery/README.md).

With the new machinesm, we can refactor the discovery process to avoid useless interactions with API server and improve the performance for backing up Kuerbernetes resources.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kaovilai** [comment]
unstale

**Comment by kaovilai** [comment]
unstale

**Comment by reasonerjt** [comment]
This would be a good enhancement given it's GA in new versions of k8s.
We'll need to decide whether we need to fallback for older versions of k8s.
