### ISSUE TITLE
Use of x-amz-sdk-checksum-algorithm breaks B2 compatibility and potentially others

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware-tanzu/velero#7534]
Updating to 1.9.1 has caused an issue where backups would fail

Error is:
```
time="2024-03-14T03:08:27Z" level=error msg="Error uploading log file" backup=general-20240314030015 bucket=sgenov error="rpc error: code = Unknown desc = error putting object backups/general-20240314030015/general-20240314030015-logs.gz: operation error S3: PutObject, https response error StatusCode: 400, RequestID: 5f661300e40af83d, HostID: adcpuLWujbiNvknckbjw=, api error InvalidArgument: Unsupported header 'x-amz-sdk-checksum-algorithm' received for this API call." error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:253" error.function="main.(*ObjectStore).PutObject" logSource="pkg/persistence/object_store.go:252" prefix=
time="2024-03-14T03:08:27Z" level=info msg="Initial backup processing complete, moving to Finalizing" backup=velero/general-20240314030015 logSource="pkg/controller/backup_controller.go:743"
time="2024-03-14T03:08:27Z" level=error msg="backup failed" backuprequest=velero/general-20240314030015 controller=backup error="rpc error: code = Unknown desc = error putting object backups/general-20240314030015/velero-backup.json: operation error S3: PutObject, https response error StatusCode: 400, RequestID: 3d41eca53502596e, HostID: adU1uYGvDbotvN3dybgQ=, api error InvalidArgument: Unsupported header 'x-amz-sdk-checksum-algorithm' received for this API call." logSource="pkg/controller/backup_controller.go:288"
time="2024-03-14T03:08:27Z" level=info msg="Updating backup's final status" backuprequest=velero/general-20240314030015 controller=backup logSource="pkg/controller/backup_controller.go:307"
time="2024-03-14T03:09:19Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=velero/backblaze controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:141"
time="2024-03-14T03:09:20Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=velero/backblaze controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:126"
```

[bundle-2024-03-15-14-03-56.tar.gz](https://github.com/vmware-tanzu/velero/files/14615201/bundle-2024-03-15-14-03-56.tar.gz)

**Environment:**

- Velero version (use `velero version`): 

Client:
        Version: v1.13.0
        Git commit: 76670e940c52880a18dbbc59e3cbee7b94cd3352
Server:
        Version: v1.13.0

- Velero features (use `velero client config get features`): 

features: <NOT SET>

- Kubernetes version (use `kubectl version`):

Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0+k3s1

- Cloud provider or hardware configuration:

on-prem

- OS (e.g. from `/etc/os-release`):

ubuntu 22.04

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Michaelpalacce** [comment]
I think there is a chance the support bundle is with 1.9.0 cause I reverted, but you can see the error above

**Comment by Michaelpalacce** [comment]
Also Wasabi seems to be broken with 1.9.1, I get a different error tho:

"You did not provide the number of bytes specified by the Content-Length HTTP header"

**Comment by mymasse** [comment]
We are also running into with the 1.9.1 AWS plugin on Purestorage, we seem to be able to upload but backups are stuck in the Finalizer state and velero logs reports `Error getting backup item operations` with an error `gzip: invalid header`.

Reverting to 1.9.0 solves the issue.

I think once this commit https://github.com/vmware-tanzu/velero-plugin-for-aws/commit/c3ed86b57a4720ff957e76fb873be063b94bad01 is released we should be able to disable to the checksum.

**Comment by pschichtel** [comment]
Ceph RGW S3 is also broken with:

```
rpc error: code = Unknown desc = error putting object ...: operation error S3: PutObject, https response error StatusCode: 400, RequestID: ..., HostID: ... api error XAmzContentSHA256Mismatch: UnknownError
```

**Comment by pschichtel** [comment]
I'm not entirely sure, but ceph's checksumming support is either incomplete or broken with a few PRs pending on the topic. terraform apparently introduced an option to skip checksum verification to work around this limitation in various S3 implementations: https://github.com/hashicorp/terraform/issues/34086

**Comment by reasonerjt** [comment]
@Michaelpalacce 
Thanks for writing up the issue.

I'll cherrypick the change to the v1.9.2 plugin to make it possible not to set the checksum header.  
Before that, please continue using the v1.9.0 plugin.  The only change in v1.9.1 plugin is adding the checksum header.

**Comment by notz** [comment]
I also experienced the same problem with OVH managed S3 offering: 

`operation error S3: PutObject, https response error StatusCode: 400, RequestID: tx95b92dd8bb4d4da487761-0065f279d9, HostID: tx95b92dd8bb4d4da487761-0065f279d9, api error InvalidArgument: Invalid Argument`

Reverting to 1.9.0 fixed the issue.

**Comment by reasonerjt** [comment]
https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/197

Is submitted, after v1.9.2 user will need to explicitly set the `checksumAlgorithm` as empty string `""` in the BSL to skip adding the checksum header
