### ISSUE TITLE
Transfer uploading images from GCR to GAR

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#7538]
**Describe the problem/challenge you have**

The Velero Github action uploads the built image to GCR for PR merging and release cutting.
The GCR service will be deprecated with Google Artifact Registry in the future: https://cloud.google.com/container-registry/docs/deprecations/container-registry-deprecation.

The GCR deprecation deadline is May 15, 2024.

**Describe the solution you'd like**

The Artifact Registry can host the GCR address.
https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr#transition-options
https://cloud.google.com/artifact-registry/docs/transition/setup-gcr-repo#limitations

We can migrate the images from GCR to GAR, and then let the GAR host the origin GCR address instead.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
Unstale

**Comment by kaovilai** [comment]
> The GCR deprecation deadline is May 15, 2024.

anything broken now?

**Comment by blackpiglet** [comment]
Not yet.
The `gcr.io` is not deprecated yet.
It gives more time to figure out the way to migrate to the `gar.io`.

**Comment by blackpiglet** [comment]
unstale

**Comment by blackpiglet** [comment]
The plan is to use JFrog to replace the gcr.io, so this issue is not needed.
