### ISSUE TITLE
E2E - Backup deletion test with repo snapshots

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#7545]
During backup deletion, if there are volume data backups (i.e., fs-backup, data movement), the repo snapshot is deleted. So the repo snapshot deletion should be covered in E2E. And considering #7281, in the backup, there should be more than 1 move backups.

**Comment by danfengliu** [comment]
Check existence of CR `DeleteBackupRequest` after backup deletion, `DeleteBackupRequest` should not exist anymore.
