### ISSUE TITLE
"backup.velero.io/backup-volumes" annotation does not work properly

### ISSUE THREAD

**Issue by javiermmenendez** [vmware-tanzu/velero#7550]
**What steps did you take and what happened:**

- I have installed velero on version 1.13 on my OpenShift cluser. I have a namespace and in it I have a Deployment, It has several pvcs. But I only want backup for only one of them. I put the annotation (**backup.velero.io/backup-volumes**), an as value the name of the "**volumen**".  Finally what I see is that the backup includes all pvcs, the one I want, but also the others which I don`t what to be backed up.
- I can see velero trying to backup all volumes in velero pod log:
`time="2024-03-21T20:46:17Z" level=info msg="pod pcr-dev/pcr-liferay-787ddd4fc4-8hzsm has volumes to backup: [liferay-data liferay-imagenesusuarios liferay-seguros liferay-deploy liferay-osgi-modules liferay-osgi-war liferay-osgi-marketplace-override pcr-nginx-cache]" backup=ops-velero/backup-pcr-dev-20240321204604 logSource="pkg/podvolume/backupper.go:172" name=pcr-liferay-787ddd4fc4-8hzsm namespace=pcr-dev resource=pods`

**What did you expect to happen:**

- I expect only the volume in the annottation to be backed up

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

In order to send more information, these are the options used in my velero installation: 

```
velero install \
    --namespace=ops-velero \
    --provider aws \
    --use-node-agent\
    --prefix=cluster-opo \
    --uploader-type=restic \
    --default-volumes-to-fs-backup=false \
    --default-snapshot-move-data=false \
    --use-volume-snapshots=false \
    --velero-pod-mem-limit=4Gi \
    --plugins=velero/velero-plugin-for-aws:v1.9.0 \
    --bucket=pruebavelero \
    --backup-location-config region=eu-south-2 \
    --secret-file=./credentials-velero

```

**Environment:**

- Velero version (use `velero version`): 
`➜  ~ (⎈|opo:ops-velero) velero version -n ops-velero
Client:
        Version: v1.13.1
        Git commit: ea5a89f83b89b2cb7a27f54148683c1ee8d57a37
Server:
        Version: v1.13.1
`
- Velero features (use `velero client config get features`): 
`➜  ~ (⎈|opo:ops-velero) velero client config get features -n ops-velero 
	features: <NOT SET>	`
- Kubernetes version (use `kubectl version`):
`➜  ~ (⎈|opo:ops-velero) oc version 
Client Version: 4.10.0-202208150436.p0.ge29d58e.assembly.stream-e29d58e
Server Version: 4.10.28
Kubernetes Version: v1.23.5+012e945`
- Cloud provider or hardware configuration:
S3 Storage from AWS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
@javiermmenendez 
To make the annotation work, it should be applied to the pod mounting the target volume, and both the `--default-volumes-to-fs-backup` and `--snapshot-volumes` parameters should be `false` for the backup or the schedule.

**Comment by javiermmenendez** [comment]
I used the resquested parameters (`--default-volumes-to-fs-backup` and `--snapshot-volumes`) and the result is the same:

- backup creation command:

` velero backup create --from-schedule backup-pcr-dev --default-volumes-to-fs-backup=false --snapshot-volumes=false -n ops-velero`

- backup yaml:

`apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"velero.io/v1","kind":"Schedule","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"ops-velero"},"name":"backup-pcr-dev","namespace":"ops-velero"},"spec":{"schedule":"55 1 * * *","template":{"defaultVolumesToFsBackup":true,"includeClusterResources":false,"includedNamespaces":["pcr-dev"],"includedResources":["pods"],"labelSelector":{"matchLabels":{"rnf.storage.onrecovery":"restoreLastBackup"}},"snapshotVolumes":false,"storageLocation":"default","ttl":"24h0m0s"}}}
    velero.io/resource-timeout: 10m0s
    velero.io/source-cluster-k8s-gitversion: v1.23.5+012e945
    velero.io/source-cluster-k8s-major-version: "1"
    velero.io/source-cluster-k8s-minor-version: "23"
  creationTimestamp: "2024-03-22T12:21:24Z"
  generation: 3
  labels:
    app.kubernetes.io/instance: ops-velero
    velero.io/schedule-name: backup-pcr-dev
    velero.io/storage-location: default
  name: backup-pcr-dev-20240322122124
  namespace: ops-velero
  resourceVersion: "3727300987"
  uid: 94a8a23b-7ffa-4e9d-8a08-571babd28509
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: true
  hooks: {}
  includeClusterResources: false
  includedNamespaces:
  - pcr-dev
  includedResources:
  - pods
  itemOperationTimeout: 4h0m0s
  labelSelector:
    matchLabels:
      rnf.storage.onrecovery: restoreLastBackup
  metadata: {}
  snapshotMoveData: false
  snapshotVolumes: false
  storageLocation: default
  ttl: 24h0m0s
status:
  expiration: "2024-03-23T12:21:24Z"
  formatVersion: 1.1.0
  phase: InProgress
  progress:
    totalItems: 1
  startTimestamp: "2024-03-22T12:21:24Z"
  version: 1`

- Same message in log:
`time="2024-03-22T12:21:37Z" level=info msg="pod pcr-dev/pcr-liferay-787ddd4fc4-bvdt4 has volumes to backup: [liferay-data liferay-imagenesusuarios liferay-seguros liferay-deploy liferay-osgi-modules liferay-osgi-war liferay-osgi-marketplace-override pcr-nginx-cache]" backup=ops-velero/backup-pcr-dev-20240322122124 logSource="pkg/podvolume/backupper.go:172" name=pcr-liferay-787ddd4fc4-bvdt4 namespace=pcr-dev resource=pods`

- Same result, all volumes are included in FS backup
