### ISSUE TITLE
Restore a cluster from a Backup after deleting all the cluster 

### ISSUE THREAD

**Issue by DelaunayAntoine** [vmware-tanzu/velero#7551]
**What steps did you take and what happened:**
Hi, so I was working on my k8s cluster locally and accidentally typed the wrong command line `kubectl delete namespace -n test - - all` 
And it deleted all my namespace on my cluster (the different namespace that was not immutable) 
For my backup I was trying to make a velero - minio pair. Backuping my cluster with a schedule backup on a minio. 
Minio is working on a NFS storage that keep all the data. 
After deleting my different namespace,(including namespace for minio and velero) I did go to my NFS storage and retrieve my archived minio backup and download the archive with all the backup inside. 
After that I relaunched my velero namespace with the specified pod and tried to restore my cluster with the archive backup I downloaded. 
Not working. 
Try to upload the archive on minio (which I relaunched) but velero doesn't see the archived backup I uploaded inside 

**What did you expect to happen:**
Want to restore a cluster with the archive backup (it's a directory with all the backup inside). I wonder if it's possible to do it this way 

**The following information will help us better understand what's going on**:
I already tried to check get backups several time but it never gave me any result. 
To summarize I deleted all the namespace I was working on. I got back the archive backup on the NFS storage. After that I didn't get any resource on how to restore with archive backup. 

Thanks for taking the time to read that. 

--backup cluster --restore restore  

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):  1.13.0
- Velero features (use `velero client config get features`):  NOT SET
- Kubernetes version (use `kubectl version`): Client version : 1.22.6 
Server version : 1.26.1
- Kubernetes installer & version: go version 1.16.12 and go 1.19.5
- Cloud provider or hardware configuration: got a NFS storage that stock all the data and each PV and PVC are all getting storage from this 
- OS (e.g. from `/etc/os-release`): working on a k8s cluster inside a VMware environment 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by qiuming-best** [comment]
Do you mean that you synchronized all files in the old bucket to another new bucket and reinstalled Velero with the new bucket but backups are not synchronized with the new bucket?

Not sure what is you mean by downloading the archive with all the backups inside and uploading the relaunched minio.

Velero will auto-sync backups into the cluster if you install Velero with one bucket containing backups.

**Comment by DelaunayAntoine** [comment]
To your question, yes I mean exactly that, getting all my backups et upload on a new bucket in minio et synchronized velero with this new bucket.

I mean, i retrieve the data backups inside the nfs storage (it keeps everything), I did get the repository "backups". And then on my new bucket inside minion upload this repositery inside the new buckets.

It might come from the architecture of my repositery inside the minio bucket with what you told me.

Architecture :
backup-cluster(my bucket inside minio) - > backups-> backups-> backup-test-all-> backup-test-all-csi-volumesnapshotclasses.json.gz (etc..) 

Can you tell if it's the correct path for backup file inside the bucket? 

Thank you for your prompt response

**Comment by DelaunayAntoine** [comment]
> Do you mean that you synchronized all files in the old bucket to another new bucket and reinstalled Velero with the new bucket but backups are not synchronized with the new bucket?
> 
> Not sure what is you mean by downloading the archive with all the backups inside and uploading the relaunched minio.
> 
> Velero will auto-sync backups into the cluster if you install Velero with one bucket containing backups.

To your question, yes I mean exactly that, getting all my backups et upload on a new bucket in minio et synchronized velero with this new bucket.

I mean, i retrieve the data backups inside the nfs storage (it keeps everything), I did get the repository "backups". And then on my new bucket inside minion upload this repositery inside the new buckets.

It might come from the architecture of my repositery inside the minio bucket with what you told me.

Architecture :
backup-cluster(my bucket inside minio) - > backups-> backups-> backup-test-all-> backup-test-all-csi-volumesnapshotclasses.json.gz (etc..)

Can you tell if it's the correct path for backup file inside the bucket?

Thank you for your prompt response

**Comment by DelaunayAntoine** [comment]
> Do you mean that you synchronized all files in the old bucket to another new bucket and reinstalled Velero with the new bucket but backups are not synchronized with the new bucket?
> 
> Not sure what is you mean by downloading the archive with all the backups inside and uploading the relaunched minio.
> 
> Velero will auto-sync backups into the cluster if you install Velero with one bucket containing backups.

So i have tried to do like you said but its not working.

Here is my archive with all the backups i got from the nfs storage 
![image](https://github.com/vmware-tanzu/velero/assets/60431929/ad8d671c-aa46-4a85-b49f-77a6b3ef54f4)

I tried to run some test to get the correct path inside the minio backup and created a backup for my app "pinot".
On the same repositery inside MinIO i uploaded my archive inside like that : 
![image](https://github.com/vmware-tanzu/velero/assets/60431929/ce9aff57-f412-4e2c-b42d-6dbdf4c21c5e)

But when i try to get backup like you said, velero doesnt seems to reconize the backup 
![image](https://github.com/vmware-tanzu/velero/assets/60431929/b67e0628-7288-46f5-be93-cb8aea0733ab)

I hope it help you to see better, ask me any question i will try to respond as clearly as possible

**Comment by qiuming-best** [comment]
Could you provide me with the velero server pod (velero-6f6cxxxx) logs? Maybe some errors occurred when syncing backups in the Velero server.

**Comment by DelaunayAntoine** [comment]
> Could you provide me with the velero server pod (velero-6f6cxxxx) logs? Maybe some errors occurred when syncing backups in the Velero server.

So here are the logs, I put the last errors because they repeat in loop. Let me know if you have more information
`time="2024-03-25T07:09:15Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=velero/backup-vel controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:126"
time="2024-03-25T07:09:17Z" level=info msg="Found 1 backups in the backup location that do not exist in the cluster and need to be synced" backupLocation=velero/backup-vel controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:136"
time="2024-03-25T07:09:17Z" level=info msg="Attempting to sync backup into cluster" backup=backups-cluster-20240319231047 backupLocation=velero/backup-vel controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:144"
time="2024-03-25T07:10:15Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=velero/backup-vel controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:141"
time="2024-03-25T07:10:15Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=velero/backup-vel controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:126"
time="2024-03-25T07:10:17Z" level=info msg="Found 1 backups in the backup location that do not exist in the cluster and need to be synced" backupLocation=velero/backup-vel controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:136"
time="2024-03-25T07:10:17Z" level=info msg="Attempting to sync backup into cluster" backup=backups-cluster-20240319231047 backupLocation=velero/backup-vel controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:144"
I0325 07:10:41.653827       1 request.go:690] Waited for 1.048317171s due to client-side throttling, not priority and fairness, request: GET:https://10.43.0.1:443/apis/storage.k8s.io/v1?timeout=32s
time="2024-03-25T07:11:15Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=velero/backup-vel controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:141"
time="2024-03-25T07:11:15Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=velero/backup-vel controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:126"
time="2024-03-25T07:11:17Z" level=info msg="Found 1 backups in the backup location that do not exist in the cluster and need to be synced" backupLocation=velero/backup-vel controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:136"
time="2024-03-25T07:11:17Z" level=info msg="Attempting to sync backup into cluster" backup=backups-cluster-20240319231047 backupLocation=velero/backup-vel controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:144"
time="2024-03-25T07:12:15Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=velero/backup-vel controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:141"
time="2024-03-25T07:12:15Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=velero/backup-vel controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:126"
time="2024-03-25T07:12:17Z" level=info msg="Found 1 backups in the backup location that do not exist in the cluster and need to be synced" backupLocation=velero/backup-vel controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:136"
time="2024-03-25T07:12:17Z" level=info msg="Attempting to sync backup into cluster" backup=backups-cluster-20240319231047 backupLocation=velero/backup-vel controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:144"
time="2024-03-25T07:13:15Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=velero/backup-vel controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:141"
time="2024-03-25T07:13:15Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=velero/backup-vel controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:126"
time="2024-03-25T07:13:17Z" level=info msg="Found 1 backups in the backup location that do not exist in the cluster and need to be synced" backupLocation=velero/backup-vel controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:136"
time="2024-03-25T07:13:17Z" level=info msg="Attempting to sync backup into cluster" backup=backups-cluster-20240319231047 backupLocation=velero/backup-vel controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:144"
`

I also have a problem with minio where I can't upload files larger than 1MB directly to minio. These files are in the directory `backups-cluster-20240319231047.tar.gz. `
So maybe it doesn't detect the files inside so it doesn't want to synchronize. But normally velero should at least be able to recognize the added backup directory I think.

**Comment by qiuming-best** [comment]
@DelaunayAntoine I've tried to upload backups into one new bucket, and installed velero with one new bucket. it works to sync the backup. there must be something wrong with `backup-sync` controller to detect your files.
could you open the debug log and generate the velero server log again?

```yaml
kubectl edit deployment/velero -n velero
...
   containers:
     - name: velero
       image: velero/velero:latest
       command:
         - /velero
       args:
         - server
         - --log-level # Add this line
         - debug       # Add this line
...
```

**Comment by DelaunayAntoine** [comment]
@qiuming-best So here are the serve logs tell me if you found anything. I totally agree with you, it's supposed to work because I created a new bucket on minio after recreating my cluster to back up the cluster and when I change bucket (so backupstoragelocation) my backups appear well.

[logs-velero-serv.txt](https://github.com/vmware-tanzu/velero/files/14754668/logs-velero-serv.txt)

**Comment by qiuming-best** [comment]
@DelaunayAntoine  I found one log with `backup backups-cluster-20240319231047 doesn't exist in backup store, skip`

it means that velero `backup-sync controller` could not find `velero-backup.json` in your bucket which led to the backup not being synchronized.

So there may be some architecture incorrect in your bucket.

Below is your architecture:
Architecture :
backup-cluster(my bucket inside minio) - > backups-> backups-> backup-test-all-> backup-test-all-csi-volumesnapshotclasses.json.gz

below is my architecture in Object storage:
<img width="691" alt="image" src="https://github.com/vmware-tanzu/velero/assets/8985337/752a9ff1-bdd7-4612-90a6-f666d4054e78">

The bucket name is 'velero-mqiu', `backups` is the sub-directory.
I have a backup named `b2` which is the sub-directory of `backups`

**Comment by DelaunayAntoine** [comment]
@qiuming-best You can close this file because I understand better where the problem comes from. By recreating a file with the necessary fields, velero was able to detect the backup. 
Thanks for all
