### ISSUE TITLE
Failure Reason: found a backup with status "InProgress" during the server starting

### ISSUE THREAD

**Issue by florianbeer** [vmware-tanzu/velero#7568]
**What steps did you take and what happened:**

- Uninstalled Velero
- Created a new bucket and new access credentials
- Installed Velero v1.13.1
- Created a backup using `velero create backup nl-test`
- Backup failed with the following reason:

```
$ kubectl get backup/nl-test -n nl-velero -o yaml | grep -A1 failureReason
  failureReason: found a backup with status "InProgress" during the server starting,
    mark it as "Failed"
```

**What did you expect to happen:**

Backup should run to completion without an issue.

**The following information will help us better understand what's going on**:

[bundle-2024-03-26-11-20-00.tar.gz](https://github.com/vmware-tanzu/velero/files/14756838/bundle-2024-03-26-11-20-00.tar.gz)

**Environment:**

- Velero version (use `velero version`):  v1.13.1 (ea5a89f83b89b2cb7a27f54148683c1ee8d57a37)
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): v1.18.2
- OS (e.g. from `/etc/os-release`): Debian 11

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment]
This error message means that there was an in-progress backup when the velero pod started. This can only happen if the velero pod crashes or shuts down while  backup is running, so you need to look into why your velero pod crashed. Check for restarts, etc. Note that backup start time was *before* the start of the attached velero pod log, indicating that a velero restart has occurred. If you run a second backup, does the pod crash again, or does the backup complete? Could be memory/resource issues on the pod, etc.

**Comment by florianbeer** [comment]
After I uninstalled and re-installed velero I started a manual backup before defining the schedule.
Manual backups and schedule are working now on this new installation.
Still not sure what caused the container to crash initially but closing this for now.

**Comment by silenceper** [comment]
@sseago Should the restart of velero pod not affect normal backup, because node-agent is normal?

**Comment by kaovilai** [comment]
>not affect normal backup

if you mean not marking backup as fail, the answer is no.

Velero currently cannot handle being restarted while a backup is in-progress. The backup needs to be marked as failed so user know to trigger another one if they still need a backup.
