### ISSUE TITLE
Enable linters for test files

### ISSUE THREAD

**Issue by mateusoliveira43** [vmware-tanzu/velero#7581]
**What steps did you take and what happened:**

Linter command/CI job does not check or enforce all linter configuration rules on test files of the project.

**Missing linters for test files:**

- [x] ginkgolinter https://github.com/vmware-tanzu/velero/pull/7565
- [ ] dupword
- [x] bodyclose https://github.com/vmware-tanzu/velero/pull/7596
- [ ] errcheck
- [ ] goconst
- [ ] gosec
- [ ] govet
- [x] gosimple https://github.com/vmware-tanzu/velero/pull/7592
- [ ] nilerr
- [x] noctx https://github.com/vmware-tanzu/velero/pull/7591
- [ ] staticcheck
- [ ] stylecheck
- [x] unconvert https://github.com/vmware-tanzu/velero/pull/7608
- [ ] unparam
- [ ] unused

**Anything else you would like to add:**

Related to https://github.com/vmware-tanzu/velero/issues/6023

**Environment:**

- development environment 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kaovilai** [comment]
unstale
