### ISSUE TITLE
velero backup disappear after backup completed about 10s?

### ISSUE THREAD

**Issue by fish-ops-Y** [vmware-tanzu/velero#7605]
install 
use this commond to install , use cos(tencent storage)
velero install --provider aws --image velero/velero:v1.12.0-rc.1 --plugins velero/velero-plugin-for-aws:v1.2.1 --bucket xxxx --secret-file ./credentials-velero --use-volume-snapshots=false --backup-location-config region=ap-beijing,s3ForcePathStyle="false",s3Url=https://cos.ap-beijing.myqcloud.com/velero/

make  backup 
[root@k8s-iot shell]# velero backup create 32-backup-test --include-namespaces iot,app
Backup request "32-backup-test" submitted successfully.
Run `velero backup describe 32-backup-test` or `velero backup logs 32-backup-test` for more details.
[root@k8s-iot shell]# velero backup get
NAME             STATUS      ERRORS   WARNINGS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
32-backup-test   Completed   0        0          2024-04-01 17:59:40 +0800 CST   29d       default            <none>
[root@k8s-iot shell]# 
[root@k8s-iot shell]# velero backup get
[root@k8s-iot shell]# 
## backup disappear

[root@k8s-iot ~]# kubectl get backup -n velero 
NAME             AGE
32-backup-test   2s
[root@k8s-iot ~]# 
[root@k8s-iot ~]# kubectl get backup -n velero 
NAME             AGE
32-backup-test   5s
[root@k8s-iot ~]# kubectl get backup -n velero 
NAME             AGE
32-backup-test   12s
[root@k8s-iot ~]# kubectl get backup -n velero 
No resources found in velero namespace.
[root@k8s-iot ~]# velero get backups
[root@k8s-iot ~]# 
[root@k8s-iot ~]# 
[root@k8s-iot ~]# kubectl get pods -n velero 
NAME                      READY   STATUS    RESTARTS   AGE
velero-5cdc68975b-4nssm   1/1     Running   0          150m
## pod is ok and the log has no error.

![image](https://github.com/vmware-tanzu/velero/assets/24754886/7c3e8338-5010-45ab-9039-72fc5ea6b97f)
but the backup  showed on my cos，so  what happend?  and why ?  please help me  to figure out this . really thanks

**Comment by kaovilai** [comment]
check velero pod logs for any sign of processing deletion requests..

It's probably either very short TTL you have set in the backup, or a pre-existing deletebackuprequest in the cluster.

**Comment by sseago** [comment]
"velero/velero:v1.12.0-rc.1 --plugins velero/velero-plugin-for-aws:v1.2.1"
Why are you using the pre-release of 1.12? 1.12.4 is now out. (as is 1.13.1). Also, 1.2.1 AWS plugin corresponds with velero 1.6, you want 1.8.2 with Velero 1.12 (or 1.9.1 with Velero 1.13) -- check the velero-plugin-for-aws readme for version correspondence)

**Comment by fish-ops-Y** [comment]
@kaovilai really thanks. 
here is some deletion requests 
```
[root@k8s-iot ~]# kubectl logs velero-5cdc68975b-4nssm -n velero | grep delete | head 
Defaulted container "velero" out of: velero, velero-velero-plugin-for-aws (init)
time="2024-04-01T07:38:08Z" level=info msg="registering plugin" command=/velero kind=DeleteItemAction logSource="pkg/plugin/clientmgmt/process/registry.go:101" name=velero.io/dataupload-delete
time="2024-04-01T07:38:14Z" level=info msg="Starting EventSource" controller=deletebackuprequest controllerGroup=velero.io controllerKind=DeleteBackupRequest logSource="/go/pkg/mod/github.com/bombsimon/logrusr/v3@v3.0.0/logrusr.go:108" source="kind source: *v1.DeleteBackupRequest"
time="2024-04-01T07:38:14Z" level=info msg="Starting EventSource" controller=deletebackuprequest controllerGroup=velero.io controllerKind=DeleteBackupRequest logSource="/go/pkg/mod/github.com/bombsimon/logrusr/v3@v3.0.0/logrusr.go:108" source="kind source: *v1.DeleteBackupRequestList"
time="2024-04-01T07:38:14Z" level=info msg="Starting Controller" controller=deletebackuprequest controllerGroup=velero.io controllerKind=DeleteBackupRequest logSource="/go/pkg/mod/github.com/bombsimon/logrusr/v3@v3.0.0/logrusr.go:108"
time="2024-04-01T07:38:14Z" level=info msg="Starting workers" controller=deletebackuprequest controllerGroup=velero.io controllerKind=DeleteBackupRequest logSource="/go/pkg/mod/github.com/bombsimon/logrusr/v3@v3.0.0/logrusr.go:108" worker count=1
time="2024-04-01T07:40:19Z" level=info msg="Getting items for resource" backup=velero/32-backup group=velero.io/v1 logSource="pkg/backup/item_collector.go:196" resource=deletebackuprequests
time="2024-04-01T07:40:19Z" level=info msg="Listing items" backup=velero/32-backup group=velero.io/v1 logSource="pkg/backup/item_collector.go:323" namespace=app resource=deletebackuprequests
time="2024-04-01T07:40:19Z" level=info msg="list for groupResource deletebackuprequests.velero.io was not paginated" backup=velero/32-backup logSource="pkg/backup/item_collector.go:496"
time="2024-04-01T07:40:19Z" level=info msg="Retrieved 0 items" backup=velero/32-backup group=velero.io/v1 logSource="pkg/backup/item_collector.go:354" namespace=app resource=deletebackuprequests
time="2024-04-01T07:40:19Z" level=info msg="Listing items" backup=velero/32-backup group=velero.io/v1 logSource="pkg/backup/item_collector.go:323" namespace=iot resource=deletebackuprequests
```
but i don't excute any delete command in my cluster.  how can i fix it

**Comment by blackpiglet** [comment]
@fish-ops-Y 
https://velero.io/docs/main/contributions/minio/#set-up-server
Please check this document.
`s3ForcePathStyle` value should be set to `true`.

**Comment by fish-ops-Y** [comment]
@blackpiglet  yes. i tried this before  and that is ok.but the cloud provider dose not support this by now

**Comment by ywk253100** [comment]
Dup of https://github.com/vmware-tanzu/velero/issues/7268
