### ISSUE TITLE
Velero with kopia restore failure

### ISSUE THREAD

**Issue by saiharshitachava** [vmware-tanzu/velero#7613]
**What steps did you take and what happened:**
We installed velero v1.12.4 with kopia on EKS 1.25 cluster 

Its a similar setup which is mentioned here with CRR enable on the S3 buckets
https://github.com/aws-samples/amazon-eks-crossregion-dr-velero/tree/main

The source cluster pvc and pv backup went fine and when we tried restore on the destination cluster.. workloads did get restored but the the persistent volumes dint . They are in pending state (only two of them restored out of 10)

**What did you expect to happen:**
Expected a successful restore on all persistent volumes

**Anything else you would like to add:**
We saw this error in velero logs
ime="2024-03-28T14:41:51Z" level=warning msg="failed to open repository: unable to create shared content manager: error loading indexes: error downloading indexes: error loading index blob xn0_01e1dcc1eeaefe4be66b5de97fbd8f9c-s28b9646d8590ece5126-c1: decrypt blob: error decrypting BLOB xn0_01e1dcc1eeaefe4be66b5de97fbd8f9c-s28b9646d8590ece5126-c1: unable to decrypt content: cipher: message authentication failed" logModule=kopia/kopia/repo logSource="pkg/kopia/kopia_log.go:101" sublevel=error

**Comment by Lyndon-Li** [comment]
The error log indicates the repo password being used is not correct.
Velero always use a hardcode repo password and never change. So if you never changed the password through Kopia command or changed the `velero-repo-credentials` secret, it may indicate a data corruption of the Kopia repo.

Since you are using AWS S3 cross region replication feature, could you further check if you have configured it correctly and the bucket data have been correctly replicated?

**Comment by saiharshitachava** [comment]
We have not manually changed any credentials 
It did restore two PVs as part of the same restore and started giving this error post that 
When kopia logs are checked it says 
 'error to prune backup repo: error to maintain repo: error to run maintenance
    under mode auto: snapshot GC failure: error running snapshot gc: unable to find
    in-use content ID: error processing snapshot root: error verifying k629a2db07844dc72fea5717c2c4cc43b:
    error getting content info for k629a2db07844dc72fea5717c2c4cc43b: content not
    found'

**Comment by Lyndon-Li** [comment]
This error also indicates that the repo data is not all there --- the index is there but the content is not.
Then consider how to assure the aforementioned condition `the repo data are all available in the bucket on the DR site before you can run the Velero restore`. You may need to check the details of AWS S3 cross region replication, or simply, you can wait for long enough time after AWS S3 cross region replication is trigger and before running the restore.

For the current repo on the DR site, the data has already been broken, so you have to clear all the data in the bucket on the DR site and rerun the replication.
