### ISSUE TITLE
The backup nfs storage class is skipped over PVC. Procedure

### ISSUE THREAD

**Issue by zhangdeshuai1999** [vmware-tanzu/velero#7672]
I backup my entire ns in my k8s cluster, velero backup create <backup-test> --include-namespaces <test>. Then I looked at the backup logs and found that the pvc had been skipped.  （I saved the backup to minio
，My storage class is nfs
）

<img width="1172" alt="图片" src="https://github.com/vmware-tanzu/velero/assets/141296859/9051ca13-94ad-4a53-906a-b3b5a0ca1ad1">

<img width="1043" alt="图片" src="https://github.com/vmware-tanzu/velero/assets/141296859/538adfd0-77ee-4181-a947-be6935b973cf">

**Comment by kaovilai** [comment]
You need to be using [File System Backup](https://velero.io/docs/v1.13/file-system-backup/#:~:text=using%20EFS%2C%20AzureFile%2C-,NFS,-%2C%20emptyDir%2C%20local%2C%20or) or [CSI Snapshot Data Movement](https://velero.io/docs/v1.13/csi-snapshot-data-movement/#:~:text=you%E2%80%99re%20using%20EFS%2C-,NFS,-%2C%20emptyDir%2C%20local%2C%20or)

No other methods in velero supports NFS volume.

**Comment by zhangdeshuai1999** [comment]
velero backup create NAME --snapshot-move-data OPTIONS...

**Comment by reasonerjt** [comment]
Looks like this is working as expected.
You chose to use velero to backup the PV via volumesnapshotter plugin and there's no volumesnapshotter for nfs.

Please consider using FS level backup as tiger suggested.

Let me know if you need more help.

**Comment by zhangdeshuai1999** [comment]
> 看起来这正在按预期工作。 您选择使用 velero 通过volumesnapshotter 插件备份PV，并且没有适用于nfs 的volumesnapshotter。
> 
> 请考虑按照 Tiger 的建议使用 FS 级备份。
> 
> 如果您需要更多帮助，请告诉我。
Is there any case?

**Comment by zhangdeshuai1999** [comment]
> 看起来这正在按预期工作。 您选择使用 velero 通过volumesnapshotter 插件备份PV，并且没有适用于nfs 的volumesnapshotter。
> 
> 请考虑按照 Tiger 的建议使用 FS 级备份。
> 
> 如果您需要更多帮助，请告诉我。

You mean to use File System Backup for backup, is there any case that can be used, I think I need help.

**Comment by reasonerjt** [comment]
@zhangdeshuai1999 
https://velero.io/docs/v1.13/file-system-backup/

**Comment by zhangdeshuai1999** [comment]
![图片](https://github.com/vmware-tanzu/velero/assets/141296859/a6f6a87b-8b52-46bf-8ff0-5e05e66380a7)
This is the process I install, whether I backup file storage class's ns, or I backup ceph block storage's ns. My velero backup describe state is normal without any error, but the following error will occur when I check in logs. After restoring to invalid ns, I find that the data in my pv does not exist.
<img width="1209" alt="图片" src="https://github.com/vmware-tanzu/velero/assets/141296859/d7ffcbcb-d7ed-4e13-9960-75050af36d87">

**Comment by blackpiglet** [comment]
The error means the Velero backup still tried to back volume by the Velero-native snapshot.
https://velero.io/docs/v1.13/file-system-backup/#to-back-up
Please check this section. Either use the opt-in or the opt-out way to filter the volumes back-up by filesystem uploader.

**Comment by zhangdeshuai1999** [comment]
> 该错误意味着 Velero 备份仍尝试通过 Velero 本机快照备份卷。 [https://velero.io/docs/v1.13/file-system-backup/#to-back-up ](https://velero.io/docs/v1.13/file-system-backup/#to-back-up)请检查此部分。 使用选择加入或选择退出的方式来过滤文件系统上传程序备份的卷。

I have tried choosing to join or exit, but there is still a problem.

**Comment by zhangdeshuai1999** [comment]
> 该错误意味着 Velero 备份仍尝试通过 Velero 本机快照备份卷。 [https://velero.io/docs/v1.13/file-system-backup/#to-back-up ](https://velero.io/docs/v1.13/file-system-backup/#to-back-up)请检查此部分。 使用选择加入或选择退出的方式来过滤文件系统上传程序备份的卷。

   nroad:   resource: /pods name: /dstp-cas-service-5b8d6f5785-fjblv message: /volume volume-uvvnjm is declared in pod nroad/dstp-cas-service-5b8d6f5785-fjblv but not mounted by any container, skipping

Errors:
  Velero:    name: /ioc-postgres-0 message: /Error backing up item error: /pod volume backup failed: get a podvolumebackup with status "InProgress" during the server starting, mark it as "Failed"


This is an error during join or exit execution

**Comment by reasonerjt** [comment]
@zhangdeshuai1999 
What do you mean by "join or exit"?   

To make sure you understand how to use fs backup, could you install velero v1.13.2, try create a workload with one namespace and one PVC with your NFS storageclass and backup that namespace?

If that still fails please collect the debug bundle and we can take a look.

**Comment by sseago** [comment]
> Errors: Velero: name: /ioc-postgres-0 message: /Error backing up item error: /pod volume backup failed: get a podvolumebackup with status "InProgress" during the server starting, mark it as "Failed"

This means that the node agent restarted in the middle of processing a volume. When that happens, the volume backup cannot be restarted, so it will be marked failed.
