### ISSUE TITLE
The default uploader type in Velero install not consistent with Velero server command

### ISSUE THREAD

**Issue by qiuming-best** [vmware-tanzu/velero#7673]
**Describe the problem/challenge you have**

**Describe the solution you'd like**

If a user does not specify the uploader type in `Velero install` command when installing the default uploader would be Kopia,
If a user does not specify the uploader type in Velero Helm chart when installing the default uploader would be Restic.

The reason is the default uploader type in `Velero install` is Kopia, while the default uploader type in `Velero server` is Restic.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
This was discovered in helm chart, but I think we should make the code in velero server to be more consistent.

**Comment by reasonerjt** [comment]
The default value on server code is for compatibility with CRs created by older version.

**Comment by qiuming-best** [comment]
The setting for uploader in `velero server` has two entries
1. Velero install
2. helm chart
For both `velero install` and helm chart the default uploader type is `kopia`, so we may not need to make changes.
