### ISSUE TITLE
Restored PVs are empty when restoring with --include-resources pvc,pv

### ISSUE THREAD

**Issue by FredNass** [vmware-tanzu/velero#7705]
**What steps did you take and what happened:**

When restoring a backup with --include-resources pvc,pv, the PVs are restored empty (no files in them).
When restoring the same backup without --include-resources pvc,pv, PVs are restored along with their files.

Not sure if this is expected or not but I'd like to be able to restore only PVCs/PVs without restoring all other resources.

Command ran to restore from backup JOB="velero-quotidien-20240418123219"
```
velero restore create --from-backup $JOB --include-namespaces ul-logs --namespace-mappings ul-logs:$JOB --include-resources pvc,pv --include-cluster-resources=true --restore-volumes=true
Restore request "velero-quotidien-20240418123219-20240419100404" submitted successfully.
```

**What did you expect to happen:**

PVs being restored with their contents when using CLI option --include-resources pvc,pv

**The following information will help us better understand what's going on**:

```
velero debug  --backup velero-quotidien-20240418123219 --restore velero-quotidien-20240418123219-20240419100404
```
[bundle-2024-04-19-10-10-44.tar.gz](https://github.com/vmware-tanzu/velero/files/15037147/bundle-2024-04-19-10-10-44.tar.gz)

**Environment:**

- Velero version (use `velero version`): 
```
 % velero version                                                                                                 
Client:
	Version: v1.13.1
	Git commit: ea5a89f83b89b2cb7a27f54148683c1ee8d57a37
Server:
	Version: v1.13.0
```

- Velero features (use `velero client config get features`): 
```
 % velero client config get features
features: <NOT SET>
```

- Kubernetes version (use `kubectl version`):
```
 % kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.14+rke2r1
WARNING: version difference between client (1.29) and server (1.26) exceeds the supported minor version skew of +/-1
```
- Kubernetes installer & version:
```
Rancher 2.8.3 and RKE2 v1.26.14+rke2r1
```
- Cloud provider or hardware configuration:
```
VMware vSphere 8
```

- OS (e.g. from `/etc/os-release`):

```
[root@peda-prod-agent-698d4a6c-q47js ~]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Vote on this issue!**

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
This is working as expected, b/c the backup was using filesystem-level-backup where a PVC need to be bound to a pod before velero can copy the files into it.

**Comment by FredNass** [comment]
Thank you. I thought about that but thought this had been working in the past. Obviously not.
Couldn't Velero spawn a pod of its own with the new PV attached and restore the files in the PV?

Sorry if this has been discussed in the past and I'm not aware of.

**Comment by sseago** [comment]
@FredNass That could be done, although it would be a fairly significant amount of extra work. You'd need to include pods in the backup -- for volumes which already have pods, we'd need to use those, since RWO volumes can't be mounted twice. Then Velero  would need to figure out which volumes were fs-backup volumes and not attached to a pod, and build a dummy pod for ech of those PVCs at the beginning of backup processing, label those pods as a temporary pods, then run the backup. We'd need a new post-backup step to delete those temporary pods once they're backed up. On restore, everything would work normally, except post-restore we'd need to delete the restored temporary pods.

**Comment by kaovilai** [comment]
> it would be a fairly significant amount of extra work.

The spawning pod to copy file already exists for the CSI Data Mover, just need to copy that over to normal FSB.

**Comment by sseago** [comment]
> > it would be a fairly significant amount of extra work.
> 
> The spawning pod to copy file already exists for the CSI Data Mover, just need to copy that over to normal FSB.

That's true, but the other things would still be needed -- the logic around finding which included PVCs don't have pods, the need to include pods in the backup, etc. But yes, for the "spawn a pod" step above, we can reuse some of the logic there.

**Comment by reasonerjt** [comment]
@FredNass 
Now that the question in the issue has been answered.
If you want velero to support the specific scenario you mentioned, would you mind opening a new issue and we can discuss under the new issue?

I personally don't think that should be a priority for velero but I'm open for discussion.

**Comment by FredNass** [comment]
@reasonerjt Done. Let me know if it needs modifications.
