### ISSUE TITLE
Need a confirm flag for velero plugin add CLI

### ISSUE THREAD

**Issue by danfengliu** [vmware-tanzu/velero#7726]
**Describe the problem/challenge you have**
In E2E test, `velero plugin add ` CLI is involved in additional BSL test, so we need a` -y/-n` flag and `-n `as the default input for this CLI so that no Human-Computer Interaction is needed for automatic tests.

```
installPluginCmd cmd =/velero/workspace/velero-e2e-test/e2e/velero/test/e2e/../../_output/bin/linux/amd64/velero --namespace velero plugin add velero/velero-plugin-for-aws:main
velero plugin add may cause the Velero server pod restart, so it is a dangerous operation
once Velero server restarts, all the ongoing jobs will fail.
Are you sure you want to continue (Y/N)? error reading user input: EOF
```

**Describe the solution you'd like**

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by kaovilai** [comment]
Thank you!

**Comment by kaovilai** [comment]
Related to #7566
