### ISSUE TITLE
ceph-csi to s3 snapshot movement

### ISSUE THREAD

**Issue by thomasklosinsky** [vmware-tanzu/velero#7743]
**Describe the problem/challenge you have**
We are using ceph-csi as storage backend and want to use velero for backups. It's nicely creating snapshots of the pvs but not transferring them (as images?) to s3 backup storage location.

**Describe the solution you'd like**
would be awesome to rbd export the volume snapshot and put that to the s3 bucket.

**Environment:**

- Velero version (use `velero version`): v1.13.2
- Kubernetes version (use `kubectl version`): v1.30.0
- Kubernetes installer & version: -
- Cloud provider or hardware configuration: -
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04 LTS

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by sseago** [comment]
This is already available in Velero 1.12 and newer. Make sure that the node agent is configured, and then add `--snapshot-move-data` to tell Velero to copy snapshot data to the BSL.

**Comment by thomasklosinsky** [comment]
thanks. got that part working!
