### ISSUE TITLE
The repo maintenance job should support node selector

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#7758]
The repository maintenance jobs may be running for some time and consume substantial resource.

Like datamover, we should support node-selector for these jobs.  Ideally we should reuse the data structures of node selectors for data mover and provide a similar user experience in terms of setting the node selectors.

**Comment by blackpiglet** [comment]
IMO, reuse the ConfigMap mentioned in [this design](https://github.com/vmware-tanzu/velero/blob/main/design/Implemented/node-agent-affinity.md) to [generate the maintenance Job](https://github.com/vmware-tanzu/velero/blob/c827fd0c6b55aa0068c6d99024c6ca5eca78ffa3/pkg/repository/maintenance.go#L71) is enough.

I am checking with the issue reporter whether that is acceptable.

**Comment by blackpiglet** [comment]
First, if we create a configuration for the repository maintenance Job, related information should be all put there, not only the node selector, for example, the Job's resource configuration should be considered too.

Second, is it reasonable to make the node selection configuration per BackupRepository? It's a bit overkill for the node selection, but the resource configuration could differ for different BackupRepositories.
