### ISSUE TITLE
Upgrade robfig/cron Library to Support Time Zones

### ISSUE THREAD

**Issue by yuanqijing** [vmware-tanzu/velero#7792]
**Describe the problem/challenge you have**

Currently, Velero uses robfig/cron library version v1.1.0 which does not support time zone specification for scheduled tasks. Upgrading to robfig/cron version v3.0.0 or higher will allow us to leverage time zone features, providing more flexibility in scheduling backups and other tasks based on different time zones.

**Describe the solution you'd like**

To implement this feature, the robfig/cron library should be upgraded to v3.0.0 or higher. 

**Anything else you would like to add:**

Here's an example of how the updated cron scheduling might look with time zone support:
`velero schedule create NAME --schedule="CRON_TZ=Asia/Tokyo 30 04 * * *"`

**References**:
[robfig/cron v3 documentation ](https://pkg.go.dev/github.com/robfig/cron/v3#section-readme)

**Environment:**

- Velero version (use `velero version`): Version: v1.13.2
- Kubernetes version (use `kubectl version`): v1.22.15
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
unstale
