### ISSUE TITLE
The statuses of the CRs should be updated when got errors during the reconciling

### ISSUE THREAD

**Issue by ywk253100** [vmware-tanzu/velero#7799]
Currently, some of the controllers only log the errors rather than update them into the status of CRs, this causes
1. Confuse, users don't know what happened to the CR as the status is stuck in in-progress
2. Hard to debug, need to check the logs to find out what happened
3. Hard for the downstream projects to integrate because the downstream projects may depend on the status to decide what is the next step. 

For example, if the BSL is unavailable, the `DeleteBackupRequest` is stuck in `InProgress` status

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kaovilai** [comment]
Perhaps this should be added to or follow up to #7207? or have this be epic containing #7207
