### ISSUE TITLE
IncludedNamespaces in restore do not restore cluster scoped resources included by backup IncludedNamespaces

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#7808]
For namespaced backups, related cluster-scoped resources are pulled in -- such as clusterroles and clusterrolebindings
For namespaced restores, though, those related cluster-scoped resources are excluded.

_Originally posted by @PieterVoet in https://github.com/vmware-tanzu/velero/discussions/7797#discussioncomment-9456798_

**Comment by ywk253100** [comment]
@kaovilai Seems the issue has already been resolved?

**Comment by kaovilai** [comment]
User resolved their immediate issue but @sseago and I think there may be some usability enhancements to make include/exclude behave the same on restore as backup.

**Comment by ywk253100** [comment]
@kaovilai Could you change the description of this issue to clarify why the include/exclude behaviour is inconsistent for backup and restore and which part needs to improve?

**Comment by kaovilai** [comment]
unstale
