### ISSUE TITLE
Velero not remove volumeName of PVC when restore from GKE

### ISSUE THREAD

**Issue by anngdinh** [vmware-tanzu/velero#7836]
**What steps did you take and what happened:**

I have a GKE cluster, this is all script I run:
```bash
# Install wordpress use PV
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install wordpress bitnami/wordpress \
    --set mariadb.primary.persistence.enabled=true \
    --set mariadb.primary.persistence.storageClass=standard-rwo \
    --set mariadb.primary.persistence.size=20Gi \
    --set persistence.enabled=false \
    --namespace tantm3

# Annotate to use FSB
kubectl -n tantm3 annotate pod/wordpress-mariadb-0 backup.velero.io/backup-volumes=data

# Use S3 of a local cloud
velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.9.0 \
    --use-node-agent \
    --use-volume-snapshots=false \
    --secret-file ./credentials-velero \
    --bucket demo \
    --backup-location-config region=hcm03,s3ForcePathStyle="true",s3Url=https://hcm03.vstorage.vngcloud.vn

# Backup completed
velero backup create ns --exclude-namespaces velero,gke-managed-system,gmp-public,gmp-system \
    --include-cluster-resources=false \
    --wait
```

In target cluster, I have install velero, have storage class ssd-3000, have mapping storage class below
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: change-storage-class-config
  namespace: velero
  labels:
    velero.io/plugin-config: ""
    velero.io/change-storage-class: RestoreItemAction
data:
  standard-rwo: ssd-3000
```
Then I restore it:
`velero restore create --item-operation-timeout 1m --from-backup ns`

**What did you expect to happen:**
It stuck in pending create PV because pvc have volumeName field.
```bash
NAMESPACE    NAME                       STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
tantm3       data-wordpress-mariadb-0   Pending   pvc-828c4069-7b38-43d7-b6c0-c7d0c910bbd5   0                         ssd-3000       <unset>                 2m5s
```
I have check, it use the same name with my GKE cluster.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): v1.13.2
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`):`Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1`
- Kubernetes installer & version:
- Cloud provider or hardware configuration: migrate from GKE  -> VNGCLOUD
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by anngdinh** [comment]
I found that pvc will not delete volumeName if in restore not contain the PV.

**Comment by mmohamed** [comment]
Hello, did you find a solution ?
