### ISSUE TITLE
Backup finalizer hangs with "gzip: invalid header" error

### ISSUE THREAD

**Issue by ameerdtm** [vmware-tanzu/velero#7839]
**What steps did you take and what happened:**
Clean install of velero; wiped the s3 bucket.  Run a backup, hangs in the Finalizing state and logs show "gzip: invalid header" errror.  The S3 storage is Pure Flashblade and not AWS S3.  This same configuration (velero and aws plug-in) is working with velero 1.11.

**What did you expect to happen:**
The backup to succeed without error.

**The following information will help us better understand what's going on**:
Attaching debug from backup. 

**Anything else you would like to add:**
Have tried removing, clearing S3 bucket, and running again with same error.  AWS plugin is the recommended verson for v1.13.2

**Environment:**

- Velero version (use `velero version`):
   Client:
	Version: v1.13.2
	Git commit: 4d961fb6fec384ed7f3c1b7c65c818106107f5a6
    Server:
	Version: v1.13.2
- Velero features (use `velero client config get features`):   features: <NOT SET>
- Kubernetes version (use `kubectl version`):  Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.15"
- Kubernetes installer & version:  Spectrocloud
- Cloud provider or hardware configuration:  VMware
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Please check whether your AWS plugin version is v1.9.2.
https://github.com/vmware-tanzu/velero-plugin-for-aws/releases/tag/v1.9.2
In v1.9.2, the AWS plugin can support passing an empty string to `checksumAlgorithm`. In that way, the checksum is skipped for Velero's interaction with the OSS.

**Comment by ameerdtm** [comment]
> Please check whether your AWS plugin version is v1.9.2. https://github.com/vmware-tanzu/velero-plugin-for-aws/releases/tag/v1.9.2 In v1.9.2, the AWS plugin can support passing an empty string to `checksumAlgorithm`. In that way, the checksum is skipped for Velero's interaction with the OSS.

Yes, using the v1.9.2 version of the plug in:
velero/velero-plugin-for-aws:v1.9.2 50b9c6222000
Id:     353046a0175f74216db29be82fd1ea21da02d1b87bf4f8b1fadd32fdee30e30c
Digest: sha256:69b54e9210bd8a7e58197b23099ac49cf841780666e48ce24f04e6ef27a1a4b5

**Comment by blackpiglet** [comment]
Could you help to collect the debug bundle by running command `velero debug`?

**Comment by ameerdtm** [comment]
Yes, I attached the debug file here.  I'll try to attach it again.

**Comment by blackpiglet** [comment]
No, I couldn't find the bundle. Please consider using [gist](https://gist.github.com/).

**Comment by ameerdtm** [comment]
Thank you for the recommandation.  Please file the debug file in the gist.
https://gist.github.com/ameerdtm/59d7ca23bc404eb4d587eefbb0535825

**Comment by ameerdtm** [comment]
Are you able to download the bundle?

**Comment by ameerdtm** [comment]
I am going to be OOO for the next week and a half; please leave this issue open if you need more information from me.  Thank you.

**Comment by blackpiglet** [comment]
Yeah, I can download the bundle, but I didn't find more information than the "gzip: invalid header" in the bundle.
I think it's still related to the AWS SDK version bump.

**Comment by ameerdtm** [comment]
It appears that I was hitting this issue, with a Pure Storage S3 endpoint, and the fix is to explictly not set a header checksum.  Thanks.

https://github.com/vmware-tanzu/velero/issues/7534

https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/197/files#diff-9b87db42a9f0c061fbece1dcef102333e7bef47638f1bef069a3c82e204f8ee3

**Comment by anmolkhemuka** [comment]
@blackpiglet why is it that we only need to set the checkup explicitly to empty string for aws plugin version 1.9.2, is it solved in later versions, do we have to set it to empty string for all versions later than 1.9.2

**Comment by kaovilai** [comment]
>  do we have to set it to empty string for all versions later than 1.9.2

yes.

**Comment by anmolkhemuka** [comment]
@kaovilai But currently I am using velero 1.15 with aws plugin 1.11.0 and I am not setting the checksum as empty string, but still I am not facing any error during restore. Was this changed in any later versions.

**Comment by kaovilai** [comment]
> I  am not setting the checksum as empty string, but still I am not facing any error during restore.

Not everyone requires changes to accomodate their setup. SDK change came in around velero 1.14 [per doc](https://github.com/vmware-tanzu/velero-plugin-for-aws?tab=readme-ov-file#non-aws-s3-compatible-provider-known-issues-with-plugin-v110x-aws-sdk-go-v2).

**Comment by cszixin** [comment]
> Please check whether your AWS plugin version is v1.9.2. https://github.com/vmware-tanzu/velero-plugin-for-aws/releases/tag/v1.9.2 In v1.9.2, the AWS plugin can support passing an empty string to `checksumAlgorithm`. In that way, the checksum is skipped for Velero's interaction with the OSS.

but why should set checksumAlgorithm to an empty string?

**Comment by kaovilai** [comment]
Because aws default from sdk has changed and not all s3 compatible works with it
https://github.com/vmware-tanzu/velero/issues/8265
