### ISSUE TITLE
Feature Request: Relabel backed up Resources

### ISSUE THREAD

**Issue by mmueller-rs** [vmware-tanzu/velero#7848]
**Describe the problem/challenge you have**
We're using Velero to back up Resources in a Kubernetes Cluster that are managed by ArgoCD. ArgoCD uses Labels to specify resources that are managed by it, see [ArgoCD Labels](https://argo-cd.readthedocs.io/en/stable/user-guide/annotations-and-labels/#labels).
When restoring Resources like a StatefulSet using a Namespace-mapping, the Label `argocd.argoproj.io/instance` is added to the restored resource. ArgoCD then sees that labelled resource and thinks that it's responsible for it, and as it's not aware of such a resource within that new namespace, it immediately deletes it.

**Describe the solution you'd like**
When restoring Resources, I'd like to do a Label-Mapping similar to the [Namespace-mapping](https://velero.io/docs/v1.8/restore-reference/#restoring-into-a-different-namespace).

**Anything else you would like to add:**
Other examples where Relabeling might be necessary:
* PodAntiAffinity, see [Kubernetes-documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity): When restoring a StatefulSet/Deployment with PodAntiAffinity enabled, the restored resources will count into the AntiAffinity, unless the labels are changed. If the PodAntiAffinity for example says that new pods should not be scheduled in Availability-Zones where pods of the same type are already deployed, you suddenly need double as much Availability-Zones.
* Similar tools with operators that manage a specific workload

**Environment:**

- Velero version (use `velero version`): v1.13.2
- Kubernetes version (use `kubectl version`): v1.26.15
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by draghuram** [comment]
Can you see if this helps?
    https://velero.io/docs/v1.14/restore-resource-modifiers/

**Comment by draghuram** [comment]
Great. I think it would be great if this info can be added to the docs. Sort of like "restore modification recipes". I will see if I can figure out the best place to make those changes.

**Comment by draghuram** [comment]
CC @anshulahuja98.

**Comment by anshulahuja98** [comment]
Sounds like a good idea to add more docs @draghuram
