### ISSUE TITLE
Makefile target to help create changelog file.

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#7865]
**Describe the problem/challenge you have**

Makes it easier to correctly add new unreleased changelogs to correct dir.

**Describe the solution you'd like**

A placeholder file that will persists the changelogs/unreleased dir

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
I believe you can create the `unreleased` dir when you wanna add the first changelog file after branch cut?

**Comment by kaovilai** [comment]
I could yes. but it could be error prone as I could mistype unreleased.
An alternative would be a script to generate this dir.

Not a big issue. I could add my script to one of the gitignore dirs.

**Comment by kaovilai** [comment]
unstale? if the change in #8104 is ok with you.

**Comment by kaovilai** [comment]
I have made [my own zsh function](https://github.com/kaovilai/dotfiles/blob/c934a7f0526c8ccc7fa604a0d0b7c06c695c902f/zsh/util.zsh#L21) to complete this functionality.. so I am closing this issue but will leave PR open for discussion.

Any automations enhancements per https://github.com/vmware-tanzu/velero/discussions/6514 should be brought up as a separate new issue.
