### ISSUE TITLE
Restoring a backup with no pods is PartiallyFailed with error: `fail to patch dynamic PV, err: context deadline exceeded`

### ISSUE THREAD

**Issue by shubham-pampattiwar** [vmware-tanzu/velero#7866]
**What steps did you take and what happened:**

- Install Velero 1.14 (rc in this case)
- Create a backup with no pods(scaled down the replicas to 0 for deployments involved), but include the volumes (via csi snapshot method, non-datamover)
- Delete application ns
- Restore from the backup
- Restore is partially failed with `fail to patch dynamic PV, err: context deadline exceeded`
- Note that the StorageClass used in this scenario has `VolumeBindingMode` as `WaitForFirstConsumer`

**What did you expect to happen:**
- In earlier versions of velero, ie. before velero 1.14, the restore described above was not  marked `PartiallyFailed` because there was no [`Finalizing` Phase for Restore Operation](https://github.com/vmware-tanzu/velero/issues/7183) that tried to[ patch the PV](https://github.com/vmware-tanzu/velero/pull/7504)
- In our scenario as the StorageClass  has `VolumeBindingMode` as `WaitForFirstConsumer`, the PV will be in pending state as there are no pods in the backup and this is turn will fail the PV patch part in restore operation after the timeout, thus marking the Restore partially failed.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by shubham-pampattiwar** [comment]
Re-opening for 1.14 cherry-pick PR https://github.com/vmware-tanzu/velero/pull/8006

**Comment by Lyndon-Li** [comment]
Close as completed.
