### ISSUE TITLE
Make the storage class of the datamover PV configurable

### ISSUE THREAD

**Issue by heiko-ma** [vmware-tanzu/velero#7882]
**Describe the problem/challenge you have**

Currently, when backing up volumes using the CSI-datamover in a geo distributed cluster with longhorn storage, the PV for the datamover gets the same storage class as the original PV. This poses a problem as our production volumes are set to have 3 replicas which results in the datamover PV to be replicated before the backup can start. In the most cases the replication is fast enough but we have one PV with 50GB size which has to be replicated via WAN before the backup. This results in the operation timing out sometimes

**Describe the solution you'd like**

It should be possible to configure the storage class of the datamover PV so that we can use a strict-local SC to prevent the replication during the backup process.

**Environment:**

- Velero version (use `velero version`): v.13.1
- Kubernetes version (use `kubectl version`): v1.27.12+rke2r1
- Cloud provider or hardware configuration: OnPremise on virtual machines
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by Lyndon-Li** [comment]
Dup with #7700

**Comment by heiko-ma** [comment]
Closed as already requested.
