### ISSUE TITLE
Support stopping the failed pipeline and keep the test bed

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#7883]
**Describe the problem/challenge you have**

It's possible that the E2E test case could fail. 
The current logic continues on the next test case, and the failed test environment is destroyed because the next test case environment is set up.
Although the current E2E code already tries to print much information about the failed test, it's still important to let the developers or the testers have a chance to investigate the failed test bed.

**Describe the solution you'd like**

Suggest adding a new flag called `--bail-out` to tell the E2E script to skip the following tests when there is a failed test.
`--bail-out`'s default value is false. The feature is turned on when it's set to true.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
unstale

**Comment by kaovilai** [comment]
I like this!
