### ISSUE TITLE
Phase 1 implementation for backup performance improvements

### ISSUE THREAD

**Issue by sseago** [vmware-tanzu/velero#7900]
**Describe the problem/challenge you have**
This includes implementation of Phase 1, as described in https://github.com/vmware-tanzu/velero/issues/7474

ItemBlock model, ItemBlockAction plugin type, and backup logic refactoring to make use of these.

What is not included is the worker thread changes to allow processing of multiple items at the same time.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by sseago** [comment]
This will be implemented in several PRs. Tentative PR plan:
1) ItemBlockAction (IBA) plugin type 
2) Implement IBA plugins for internal velero plugins (pod/pvc/pv/etc)
3) ItemBlock model and backup workflow changes

**Comment by shubham-pampattiwar** [comment]
not stale

**Comment by blackpiglet** [comment]
unstale
