### ISSUE TITLE
Repo maintenance job is not started if there are orphan jobs before Velero server restarts

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#7906]
This is a side effect of issue #7753.
After Velero server restarts, the running maintenance job goes orphan because of #7753.
When Velero server runs a new maintenance job, it checks if there are running maintenance jobs, if so, it aborts creating a new job.
As a result, after Velero server restarts, no new maintenance job could be started until all the orphaned & running maintenance jobs complete

**Comment by reasonerjt** [comment]
Resolving it as a dup of #7753, as long as the orphaned job is adopted there won't be such issues.
