### ISSUE TITLE
error getting backup volume info: - context deadline exceeded

### ISSUE THREAD

**Issue by edhunter665** [vmware-tanzu/velero#7939]
**What steps did you take and what happened:**
When trying to describe a backup or restore it takes long time until in runs into an error similar to 
<error getting backup volume info: Get "https://xxx.xxx.int/tanzu-velero-backup/backups/backup09/backup09-volumeinfo.json.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=6lpdesbK8STCD6zA0ptO%2F20240626%2Fminio%2Fs3%2Faws4_request&X-Amz-Date=20240626T145524Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&x-id=GetObject&X-Amz-Signature=a3e2ed0451b69cdb91a41a1ead1ad59e297f64e8885ca666e3f1222e764de105": context deadline exceeded>

**What did you expect to happen:**
Backup volume info correctly displayed

**The following information will help us better understand what's going on**:
It worked in the beginning. Same issue on different backup locations (MinIO), on different kubernetes clusters on different versions. Happens also on new installations.

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

**Environment:**

- Velero version (use `velero version`): 1.14 (also happens on 1.13)
- Velero features (use `velero client config get features`):  NOT SET
- Kubernetes version (use `kubectl version`): 1.28 (also happens on 1.27 and 1.26)
- Kubernetes installer & version: Tanzu Kubernetes Grid
- Cloud provider or hardware configuration: vSphere with Tanzu 8.0U2

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
`context deadline exceeded`
This error usually means the CLI fails to connect to the object storage.
Could you check whether you can download the VolumeInfo metadata from that link directly at where you run the Velero CLI?

**Comment by edhunter665** [comment]
Thank  you for that.
However, when testing today the error is magically gone. No changes were made.
We will keep an eye on that but for now this can be closed.

**Comment by edhunter665** [comment]
solved
