### ISSUE TITLE
Cloudflare R2 backup fails

### ISSUE THREAD

**Issue by e3b0c442** [vmware-tanzu/velero#7940]
**What steps did you take and what happened:**

* Installed Velero with CSI snapshots enabled via Helm Chart
* Created a BackupStorageLocation referring to a Cloudflare R2 bucket: `velero backup-location create cloudflare --provider aws --bucket REDACTED --config region=auto --config s3Url=https://REDACTED.r2.cloudflarestorage.com --credential velero=cloudflare`
* Created a backup `velero backup create test-backup -n NAMESPACE -l KEY=VALUE --snapshot-move-data -w`
* Receive `Backup completed with status: Failed. You may check for more information using the commands `velero backup describe test-backup` and `velero backup logs test-backup`.`

**What did you expect to happen:**
Backup fully succeeded
**The following information will help us better understand what's going on**:

[bundle-2024-06-26-19-24-08.tar.gz](https://github.com/user-attachments/files/16006044/bundle-2024-06-26-19-24-08.tar.gz)

**Anything else you would like to add:**

Logs show error `operation error S3: PutObject, https response error StatusCode: 501, RequestID: , HostID: , api error NotImplemented: STREAMING-UNSIGNED-PAYLOAD-TRAILER not implemented`. Trying to show the logs gives "file not found."

**Environment:**

- Velero version (use `velero version`): 1.140.0
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): ```Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6```
- Kubernetes installer & version: Talos v1.7.5
- Cloud provider or hardware configuration: Bare metal on-prem
- OS (e.g. from `/etc/os-release`): Talos Linux v1.7.5

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
This is because the AWS plugin bumped the AWS SDK version to v2, and some S3-compatible object storage didn't follow the S3 interface.

Please reference to this issue https://github.com/vmware-tanzu/velero/issues/7839.

**Comment by e3b0c442** [comment]
I was able to get this working tonight by setting the `checksumAlgorithm` flag. It may be worth documenting this specific case.

**Comment by MohammedNoureldin** [comment]
Velero 1.17.0 works currently with R2 S3 storage.
