### ISSUE TITLE
velero-plugin-for-aws v1.9 and aws-sdk-go-v2 Upload not working on OVH Object Storage, Invalid Argument

### ISSUE THREAD

**Issue by genjudev** [vmware-tanzu/velero#7952]
**What steps did you take and what happened:**
velero update to v1.13, velero-plugin-for-aws update from v1.8 to v1.9

**What did you expect to happen:**
s3 upload Working

**The following information will help us better understand what's going on**:
velero-plugin-for-aws switched to aws-sdk-go-v2
with the aws cli v2 we had no complication

Error:
time="2024-06-28T13:56:59Z" level=error msg="Error uploading log file" backup=<BACKUP> bucket=<BUCKET> error="rpc error: code = Unknown desc = error putting object backups/<PATH>-logs.gz: operation error S3: PutObject, https response error StatusCode: 400, RequestID: tx8097d8716a824688b5614-00667ec12b, HostID: tx8097d8716a824688b5614-00667ec12b, api error InvalidArgument: Invalid Argument." error.file="/go/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:280" error.function="main.(*ObjectStore).PutObject" logSource="pkg/persistence/object_store.go:256" prefix=

**Anything else you would like to add:**
Downgrade to v1.8 will fix the problem. Velero can be updated.

**Environment:**
OVH https://www.ovhcloud.com/
- managed kubernetes service version 1.28.3-2
- object storage s3 (swift)

Plugin Version | Velero Version
-- | --
v1.9.x | v1.13.x
v1.8.x | v1.12.x

**Comment by mateusoliveira43** [comment]
There are some similar issues related by other users

velero-plugin-for-aws updated default value of `checksumAlgorithm` field in BackupStorageLocations (BSLs) from `""` (no checksum calculation) to `CRC32` algorithm (Reference https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/release-1.9/backupstoragelocation.md)

Can you try using an empty string for that field to see if your problem is fixed?

**Comment by sseago** [comment]
Note that you need 1.9.2 or later for the checksumAlgorithm param to work.

**Comment by genjudev** [comment]
> There are some similar issues related by other users
> 
> velero-plugin-for-aws updated default value of `checksumAlgorithm` field in BackupStorageLocations (BSLs) from `""` (no checksum calculation) to `CRC32` algorithm (Reference https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/release-1.9/backupstoragelocation.md)
> 
> Can you try using an empty string for that field to see if your problem is fixed?

Because its not my personal system I have no access till monday. I will update you next week. Thanks for your help.

**Comment by sseago** [comment]
@genjudev Also note  that Velero 1.14 was just released (with v1.10 AWS plugin) -- if 1.9.2 plugin is still not working for you, it might be worth upgrading to the latest and trying there as well.

**Comment by genjudev** [comment]
Hello,

> There are some similar issues related by other users
> 
> velero-plugin-for-aws updated default value of `checksumAlgorithm` field in BackupStorageLocations (BSLs) from `""` (no checksum calculation) to `CRC32` algorithm (Reference https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/release-1.9/backupstoragelocation.md)
> 
> Can you try using an empty string for that field to see if your problem is fixed?



> Note that you need 1.9.2 or later for the checksumAlgorithm param to work.

we tried backing up with v1.9.2 and set the value of `checksumAlgorithm` to an emtpy string.

this works fine. Thanks!!

> @genjudev Also note that Velero 1.14 was just released (with v1.10 AWS plugin) -- if 1.9.2 plugin is still not working for you, it might be worth upgrading to the latest and trying there as well.

Thanks for the information.
