### ISSUE TITLE
Bump Ginkgo to v2

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#7961]
**Describe the problem/challenge you have**

Bump Ginkgo to v2, and resolve potential conflicts.
https://onsi.github.io/ginkgo/MIGRATING_TO_V2#major-changes

**Describe the solution you'd like**

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by kaovilai** [comment]
I think #7957 should be part of this issue just because without it, you cannot remove v1 references.

**Comment by blackpiglet** [comment]
Agree.

**Comment by blackpiglet** [comment]
> I think #7957 should be part of this issue just because without it, you cannot remove v1 references.

After bumping the Ginkgo to v2, I found although the `RunSpecsWithDefaultAndCustomReporters` function is deprecated,  it's not treated as an error, instead, it's treated as `RunSpecs` in v2.
It's OK to separate them into two tasks.
