### ISSUE TITLE
Invalid function(NewWithClient) call in kopialib

### ISSUE THREAD

**Issue by dev-a-z** [vmware-tanzu/velero#7968]
Hi colleagues,
I'm trying to bump the Velero version to v1.14.0 but failed when I built
my version is:
- go: 1.22.4
- github.com/vmware-tanzu/velero: v1.14.0
- github.com/kopia/kopia v0.16.0

I think NewWithClient does not exist in [kopia](https://github.com/kopia/kopia/blob/v0.16.0/repo/blob/azure/azure_storage.go)

Could you please take a look? Thanks in advanced

https://github.com/vmware-tanzu/velero/blob/5c413ec3a9231dae7bad34f1ff3d24be01079a7d/pkg/repository/udmrepo/kopialib/backend/azure/azure_storage_wrapper.go#L69

**Comment by dev-a-z** [comment]
Hi @reasonerjt, the error message as follows:
```
# github.com/vmware-tanzu/velero/pkg/repository/udmrepo/kopialib/backend/azure
/Users/dev-a-z/.gvm/pkgsets/go1.22.4/global/pkg/mod/github.com/vmware-tanzu/velero@v1.14.0/pkg/repository/udmrepo/kopialib/backend/azure/azure_storage_wrapper.go:69:26: undefined: azure.NewWithClient
```
I guess the workaround seems to be in the code line [here](https://github.com/vmware-tanzu/velero/blob/28d64c2c529f33510a68200c129012a163777a67/go.mod#L178), Is that right?

**Comment by Lyndon-Li** [comment]
@dev-a-z
Why don't you directly include `velero` package where the appropriate version of `kopia` package is included.

**Comment by dev-a-z** [comment]
@Lyndon-Li 
Yes, The solution you provided will work well, but the `NewWithClient` function is deprecated in Kopia so It should be removed as a legacy from Velero. Anyway, there's a several workarounds for me. thanks for the answer!
