### ISSUE TITLE
Restore of PV fails when CSI snapshot and Data-Move is in use

### ISSUE THREAD

**Issue by edhunter665** [vmware-tanzu/velero#7975]
**What steps did you take and what happened:**
We are using Velero to backup our Kubernetes clusters on vSphere with Tanzu. We are using CSI snapshots to backup our persistent volumes. These backups are moved to MinIO. We are using vSphere CSI driver csi.vsphere.vmware.com
We are using the StorageClasses coming from Supervisor cluster. Backup is working fine in any case.
When bindingMode is set to Immediate we cannot restore from backup when Data-Move is used. It fails because the PVs cannot be restored because of "claim Selector is not supported".
Same restore works when using StorageClass with bindingMode set to WaitForFirstConsumer.

When backup is taken without Data Move or when done file-based the restore also works fine.

**What did you expect to happen:**

Successful restore when using Data Move and StorageClass with bindingMode Immediate.

StorageClasses:
<img width="1042" alt="image" src="https://github.com/vmware-tanzu/velero/assets/173908778/e0dd085c-6267-4898-9655-83f33483a4b2">

Error on PV creation:
![image](https://github.com/vmware-tanzu/velero/assets/173908778/c21841f5-d8bf-4e4d-a7dc-e44cf692a017)

**Environment:**

- Velero version (use `velero version`): 1.14
- Kubernetes version (use `kubectl version`): 1.27, 1.28

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
> the PVs cannot be restored because of "claim Selector is not supported".

This is expected as a normal behavior of data mover restore. Therefore, this is not the cause of the restore failure.

**Comment by Lyndon-Li** [comment]
@edhunter665 In order to further troubleshoot, please share the velero bundle by running `velero debug`

**Comment by Lyndon-Li** [comment]
@edhunter665 
> We are using the StorageClasses coming from Supervisor cluster

Are you using Velero data mover to backup the Supervisor cluster?

**Comment by edhunter665** [comment]
> @edhunter665 In order to further troubleshoot, please share the velero bundle by running `velero debug`

[bundle-2024-07-03-13-53-29_2.zip](https://github.com/user-attachments/files/16084530/bundle-2024-07-03-13-53-29_2.zip)

**Comment by edhunter665** [comment]
> @edhunter665
> 
> > We are using the StorageClasses coming from Supervisor cluster
> 
> Are you using Velero data mover to backup the Supervisor cluster?

No, Velero data mover is used for backups of Tanzu Guest Cluster

**Comment by Lyndon-Li** [comment]
`"message": "found a dataupload velero/restore01-sdcgl with expose error: Pod is unschedulable: 0/4 nodes are available: persistentvolumeclaim \"restore01-sdcgl\" not found. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling... mark it as cancel"`

This should be the same as #7898. Please wait for 1.14.1 for the fix. For now, you can use 1.13.x until 1.14.1 is available.

**Comment by realjump** [comment]
Thanks for the quick reply - I'm reassured that this is already known.
