### ISSUE TITLE
Support AWS Roles Anywhere

### ISSUE THREAD

**Issue by changhyuni** [vmware-tanzu/velero#7981]
**Describe the problem/challenge you have**
I want to use AWS ROLES ANYWHERE to handle AWS authentication How should I use AWS ROLES ANYWHERE?

**Describe the solution you'd like**
support aws roles anywhere

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by reasonerjt** [comment]
@changhyuni 
It was not on my radar, is that a new feature in AWS? 
I'll spend some time to read [this doc ](https://docs.aws.amazon.com/rolesanywhere/latest/userguide/introduction.html)but currently I don't think we wanna support it in v1.15.
From the perspective of velero, is it essentially to allow configuring a cert in the BSL and use it to call AWS APIs?

**Comment by kaovilai** [comment]
I believe it's closely related to iam role tokens we already support in velero. Just perhaps a different way of obtaining the tokens.

It's related to the enableSharedConfig in AWS bsl today.

**Comment by changhyuni** [comment]
@kaovilai @reasonerjt 
I know velero use aws defaultCredential 
https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/26bf6253ff0d74f8e5ce6aeb3053f31b7a297a99/velero-plugin-for-aws/config.go#L79

We're looking to authenticate with the AWS S3 API on-premises using AWS ROLES ANYWHERE. However, the current process requires mounting the certificate and ROLES ANYWHERE binaries onto a Velero pod, which is quite cumbersome.

**Comment by kaovilai** [comment]
> current process requires mounting the certificate and ROLES ANYWHERE binaries onto a Velero pod, which is quite cumbersome.

Can you link an example process that would not require mounting cert and binaries?

**Comment by changhyuni** [comment]
@kaovilai 
I researched it, but it appears that the "aws-go-sdk" does not yet support this feature. It looks like I'll need to use the binary instead.. I'll close this issue
https://github.com/aws/rolesanywhere-credential-helper
