### ISSUE TITLE
Using the same key in secrets for different S3 Storages results in kopia data not getting written

### ISSUE THREAD

**Issue by fgleixner** [vmware-tanzu/velero#7984]
**What steps did you take and what happened:**
Created 2 Backup locations that point to 2 different minio servers using different credentials:
```
kubectl create secret generic -n velero cred1 --from-file=pass=cred1file
velero backup-location create loacation1 --provider=aws --credential=cred1=pass --config s3Url=https://s3-1.backup.net,.....
kubectl create secret generic -n velero cred2 --from-file=pass=cred2file
velero backup-location create loacation2 --provider=aws --credential=cred2=pass --config s3Url=https://s3-2.backup.net,.....
```

The first backup location was long time in use. As i added the 2nd backup location the backup to this location failed moving data to kopia.
The folder "backups" got created and filled with backups, but the folder kopia didnt get created

Errors:
```
 Operation for persistentvolumeclaims prometheus/prometheus-mon-prometheus-kube-promet-prometheus-db-prometheus-mon-prometheus-kube-promet-prometheus-0:
    Backup Item Action Plugin:  velero.io/csi-pvc-backupper
    Operation ID:               du-07b67a29-ee01-4c9b-ba6f-24a1c22af41d.751e2016-cba6-476892628
    Items to Update:
                           datauploads.velero.io velero/daily-backup-folio-misc-nasbsb-20240705094633-hxtgq
    Phase:                 Failed
    Operation Error:       error to initialize data path: error to ensure backup repository bvb-s3-backup-folio-prometheus-kopia: failed to wait BackupRepository: context deadline exceeded
    Progress description:  Failed
    Created:               2024-07-05 11:48:27 +0200 CEST
    Started:               2024-07-05 11:48:27 +0200 CEST
    Updated:               2024-07-05 12:12:33 +0200 CEST
```

I could fix it by changing the key "pass" of the secret and in the switch --credential to any other string on one of the two backup location configurations and secrets.

Somehow the credentials are mixed when kopia is started?

**Environment:**

- Velero version (use `velero version`): 1.13.2
- Velero features (use `velero client config get features`): EnableCSI
- Kubernetes version (use `kubectl version`): 1.28.6
- Kubernetes installer & version: kubespray
- Cloud provider or hardware configuration: on premises
- OS (e.g. from `/etc/os-release`): SLES 15.5

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
> As i added the 2nd backup location the backup to this location failed moving data 

Do you mean the backup failed to the old location or to the new location?

**Comment by Lyndon-Li** [comment]
Could you share the entire velero bundle by running `velero debug`?

**Comment by fgleixner** [comment]
The backup failed with the new location. At the moment i cannot reproduce the issue. But the Access Key for the 2nd location has permissions changed: The access key was not able to read the list of buckets. This has been changed recently.
So my guess: Following conditions have to be fulfilled to reproduce the error:
- The secret key of two different backup locations have to be the same (the key of the secret, not the secret)
- The permissions of the access key of the failing backup location disallow listing buckets, but it perfectly can read and writhe into the bucket.

**Comment by Lyndon-Li** [comment]
> The secret key of two different backup locations have to be the same

This is not required. The key and the secret name together identifies the secret. So the duplicated key won't result in mix of the secrets.

> The permissions of the access key of the failing backup location disallow listing buckets, but it perfectly can read and writhe into the bucket

This should have been fixed.

Let us know if you can reproduce it and also share the velero debug bundle.

**Comment by fgleixner** [comment]
At the moment i am happy, that backups work, and i will not try to reproduce it, as this would take too much time at the moment. For me it is OK to close the issue at the moment. If i re-encounter, i will re-open.

**Comment by Lyndon-Li** [comment]
Close as not reproducible
