### ISSUE TITLE
No volume ID returned by volume snapshotter for persistent volume

### ISSUE THREAD

**Issue by ithesadson** [vmware-tanzu/velero#7990]
**What steps did you take and what happened:**

I installed velero with helm and then when I took backup I saw that I could not take backup of PVs.

**What did you expect to happen:**
Successfully taking PV and PVC backups.

**The following information will help us better understand what's going on**:
I deployed velero with the following command.

helm install velero \
  --namespace velero \
  --create-namespace \
  --set-file credentials.secretContents.cloud=credentials-velero \
  --set configuration.backupStorageLocation[0].name=default \
  --set configuration.backupStorageLocation[0].provider=aws \
  --set configuration.backupStorageLocation[0].bucket=velero-bucket \
  --set configuration.backupStorageLocation[0].config.region=minio \
  --set configuration.backupStorageLocation[0].config.s3ForcePathStyle=true \
  --set configuration.backupStorageLocation[0].config.s3Url=http://xxxx:xxxx\
  --set snapshotsEnabled=true \
  --set configuration.volumeSnapshotLocation[0].name=default \
  --set configuration.volumeSnapshotLocation[0].provider=aws \
  --set configuration.volumeSnapshotLocation[0].config.region=minio \
  --set initContainers[0].name=velero-plugin-for-aws \
  --set initContainers[0].image=velero/velero-plugin-for-aws:v1.10.0 \
  --set initContainers[0].volumeMounts[0].mountPath=/target \
  --set initContainers[0].volumeMounts[0].name=plugins \
  vmware-tanzu/velero

- `kubectl logs deployment/velero -n velero`
![image](https://github.com/vmware-tanzu/velero/assets/56589824/5fef9977-8425-4e20-8a0b-966d2b8d83e8)

- `velero backup describe <backupname>`
![image](https://github.com/vmware-tanzu/velero/assets/56589824/75f111ef-dcdc-4a38-8265-2357290ed7aa)

**Anything else you would like to add:**

When I restore the backup, the harbor namespace comes back and I can access it without any problem. But the only problem is that the PVs are recreated, so I lose access to the previous data.
It does not return any error when taking a backup, I only get a warning as in the image I uploaded.
Am I missing something? Thanks in advance for your help.

**Environment:**
- velero version
Client:
	Version: v1.14.0
	Git commit: 2fc6300f2239f250b40b0488c35feae59520f2d3
Server:
	Version: v1.14.0
- velero client config get features
features: <NOT SET>
- kubectl version
Client Version: v1.29.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.5
- cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by shubham-pampattiwar** [comment]
I think there might be an issue with your VolumeSnapshotLocation(VSL) Config. Whats is the Status of the VolumeSnapshotLocation configured for this Velero install ? Is it available ? Are the Volumes that you are trying to backup compatible with the VSL configured ? I see VSL config region as `minio`, I am not sure if minio can be used as a VSL, maybe thats the issue here. 

Also, Alternatives to VSL for backing up volumes are:
- CSI Snapshots: https://velero.io/docs/v1.14/csi/ 
- CSI Snapshot Mover: https://velero.io/docs/v1.14/csi-snapshot-data-movement/
- FileSystem Backup: https://velero.io/docs/v1.14/file-system-backup/

**Comment by sseago** [comment]
@shubham-pampattiwar That's right -- an AWS VolumeSnapshotLocation is specifically for EBS snapshots in AWS -- and any EBS volumes being backed up will be in a region that is not "minio", so it won't be a match for any volumes in the backup.

**Comment by ithesadson** [comment]
> I think there might be an issue with your VolumeSnapshotLocation(VSL) Config. Whats is the Status of the VolumeSnapshotLocation configured for this Velero install ? Is it available ? Are the Volumes that you are trying to backup compatible with the VSL configured ? I see VSL config region as `minio`, I am not sure if minio can be used as a VSL, maybe thats the issue here.
> 
> Also, Alternatives to VSL for backing up volumes are:
> 
> * CSI Snapshots: https://velero.io/docs/v1.14/csi/
> * CSI Snapshot Mover: https://velero.io/docs/v1.14/csi-snapshot-data-movement/
> * FileSystem Backup: https://velero.io/docs/v1.14/file-system-backup/

I deployed velero again using filesystem backup and did not get any error while taking backup. Harbor data was returned.
But when I looked at the backup restore logs, it said skipped for PVs. Do you have any idea about this issue?

![image](https://github.com/vmware-tanzu/velero/assets/56589824/4cc6af54-09d4-4d76-aedf-63ac660e6ba9)

How i install velero:
```
velero install \
  --provider aws \
  --image velero/velero:v1.14.0 \
  --plugins velero/velero-plugin-for-aws:v1.10.0 \
  --bucket velero-bucket \
  --secret-file ./credentials-velero \
  --use-node-agent \
  --use-volume-snapshots=false \
  --uploader-type restic \
  --default-volumes-to-fs-backup \
  --namespace velero \
  --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://xxxx:xxxx
  ```

**Comment by ithesadson** [comment]
The harbor data within the example namespace is being backed up using podvolumebackup. Since there are no remaining issues, I am closing this issue.

![image](https://github.com/vmware-tanzu/velero/assets/56589824/59a57246-22cb-4cc5-9af3-8426ff5cb423)

**Comment by sseago** [comment]
@ithesadson PVs are skipped because with fs-backup, upon PVC creation a new PV is provisioned by the cluster to copy fresh data into.
