### ISSUE TITLE
Resource status restore doesn't work for resources which has been exist, even though existingResourcePolicy is set to update

### ISSUE THREAD

**Issue by nfyxhan** [vmware-tanzu/velero#7994]
**What steps did you take and what happened:**

a resource  is exist in the cluster,edit its metadata and status, and then restore it, only metadata can be update, but status not
```yaml
metadata:
    labels: 
       someunsync: true
status: 
    message: unsync
```

**What did you expect to happen:**
both of the metadata and status should be update

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
Status restore is not enabled by default, you should use `--status-include-resources` restore flag to enable status restore for the specified resources.

**Comment by Lyndon-Li** [comment]
An open issue requesting the doc for `--status-include-resources`, #6237

**Comment by nfyxhan** [comment]
> #6237
`--status-include-resources` can work when the first time to restore, the second time can't work  if I do not delete the resources which are the first time to restore

**Comment by Lyndon-Li** [comment]
The existingResourcePolicy doesn't cover restore of status, if this is required in your case, just share more details of your scenarios, so that we can prioritize the requirement.

**Comment by nfyxhan** [comment]
> The existingResourcePolicy doesn't cover restore of status, if this is required in your case, just share more details of your scenarios, so that we can prioritize the requirement.

We've modified the code here to rebuild a binary package that bypasses both of these issues
- https://github.com/vmware-tanzu/velero/issues/7993
- https://github.com/vmware-tanzu/velero/issues/7994
<img width="1313" alt="image" src="https://github.com/vmware-tanzu/velero/assets/15644272/90d2d10c-69f7-4e1d-af49-5ba20584fcf4">

**Comment by kaovilai** [comment]
So perhaps call this `update+status`?

Or would this fit under existing `update`?

wdyt @shubham-pampattiwar

**Comment by shubham-pampattiwar** [comment]
@kaovilai I believe more details around the scenarios why we need this would help. The initial thought of ExistingResourcePolicy was around object's metadata and spec I believe. Also, IMO status of CR is something that is updated/patched by its controller.

**Comment by nfyxhan** [comment]
I have two clusters A and B, the first time I restore the CRD of cluster A to cluster B, and then the controller runs in cluster B for a period of time, and then restore the CRD to cluster A, the status needs to be restored. @Lyndon-Li @shubham-pampattiwar

**Comment by Lyndon-Li** [comment]
@nfyxhan
We agree that the status should be restored in order to make the behavior consistent with the metadata restore; however, we also think status restore is seldomly required.
Could you share your concrete requirement on status restore? Your requirement will help us to prioritize our tasks.
