### ISSUE TITLE
Backup Restore PartiallyFailed

### ISSUE THREAD

**Issue by giz33** [vmware-tanzu/velero#7996]
**What steps did you take and what happened:**
I have succesfully installed Velero with Longhorn integration.
So far so good it creates the snapshots succesfully on longhorn and also restore my PVC with success, but all my backups restore ends up with a Partially Failed message with the following error:

Errors:
  Velero:     <none>
  Cluster:  CSI modules are not ready for restore. Check CSI feature is enabled and CSI plugin is installed
  Namespaces: <none>

I use Longhorn 1.4.0
Kubernetes 1.21
Velero 1.14 or Main(IDK which version it install by default)

**What did you expect to happen:**

Backup restore complete successfully message

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

I can't attach because I don't have SSH connection to this server to extract the file, I access ir via RDS on Azure.

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.14 or Main
- Velero features (use `velero client config get features`):  NOT SET
- Kubernetes version (use `kubectl version`):
- Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12+rke2r2", GitCommit:"696a9fdd2a58340e61e0d815c5769d266fca0802", GitTreeState:"clean", BuildDate:"2022-04-28T19:10:14Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12+rke2r2", GitCommit:"696a9fdd2a58340e61e0d815c5769d266fca0802", GitTreeState:"clean", BuildDate:"2022-04-28T19:10:14Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version: RKE2 1.21
- Cloud provider or hardware configuration: On premises
- OS (e.g. from `/etc/os-release`):
- Rocky Linux 8

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
> CSI modules are not ready for restore. Check CSI feature is enabled and CSI plugin is installed

This seems not be printed by velero. Could you share where you see this message?

**Comment by giz33** [comment]
@Lyndon-Li first thank you for answering and helping.
Here are the print where I see the output:

![image](https://github.com/vmware-tanzu/velero/assets/19286616/a57bca51-c7af-4b79-ba40-c062a2f08ac6)

**Comment by Lyndon-Li** [comment]
I think you are not using 1.14 velero server, I can see this error message in 1.13 code only, so just check the client and server version, make sure they are the same and retry the backup and restore.

**Comment by giz33** [comment]
Hello!
Thanks again for answering.
I was using the version 13.1 of Velero Client and Velero on version 13.2.
I upgraded the client to version 13.2 to be equal the Velero Server but the same problem occurs.

Velero version:
![image](https://github.com/vmware-tanzu/velero/assets/19286616/94c9dc0c-bbfa-4f7a-90a2-9c23e265e83f)

Client Velero version:
![image](https://github.com/vmware-tanzu/velero/assets/19286616/7c0df624-151d-41ff-823c-a53ddf7a2579)

Thanks in advance.

**Comment by blackpiglet** [comment]
I suggest updating the plugin versions too. 
The AWS plugin version should be v1.9.x and the CSI plugin version should be v0.7.x.

https://github.com/vmware-tanzu/velero-plugin-for-csi?tab=readme-ov-file#compatibility
https://github.com/vmware-tanzu/velero-plugin-for-aws?tab=readme-ov-file#compatibility

**Comment by giz33** [comment]
I tried to install it like this:

helm upgrade --install velero --namespace=velero --create-namespace --set-file credentials.secretContents.cloud=/root/velero/credentials-velero --set configuration.backupStorageLocation[0].provider=aws --set configuration.backupStorageLocation[0].name=default --set configuration.backupStorageLocation[0].bucket=velero --set configuration.backupStorageLocation[0].config.region=my-minio --set configuration.backupStorageLocation[0].config.s3ForcePathStyle=true --set configuration.backupStorageLocation[0].config.s3Url=http://minio-endpoint.client.com/ --set configuration.backupStorageLocation[0].config.publicUrl=http://minio-endpoint.client.com/ --set snapshotsEnabled=true --set configuration.volumeSnapshotLocation[0].provider=aws --set configuration.volumeSnapshotLocation[0].name=default --set configuration.volumeSnapshotLocation[0].config.region=my-minio --set configuration.volumeSnapshotLocation[0].bucket=longhorn --set configuration.volumeSnapshotLocation[0].config.region=my-minio --set configuration.volumeSnapshotLocation[0].config.s3ForcePathStyle=true --set configuration.volumeSnapshotLocation[0].config.s3Url=http://minio-endpoint.client.com/ --set configuration.volumeSnapshotLocation[0].config.publicUrl=http://minio-endpoint.client.com/ --set "initContainers[0].name=velero-plugin-for-aws" --set "initContainers[0].image=velero/velero-plugin-for-aws:v1.9.0" --set "initContainers[0].volumeMounts[0].mountPath=/target" --set "initContainers[0].volumeMounts[0].name=plugins" --set configuration.features=EnableCSI vmware-tanzu/velero

Now the POD started successfully, but when I trigger the backup it gives me the following errors:


POD Velero Server:
![image](https://github.com/vmware-tanzu/velero/assets/19286616/a3e5e932-9f5e-40b6-8fb4-19ff5dbd921a)

Velero backup output:
Backup request "csi-b2" submitted successfully.
Waiting for backup to complete. You may safely press ctrl-c to stop waiting - your backup will continue in the background.
..........................
Backup completed with status: Failed. You may check for more information using the commands `velero backup describe csi-b2` and `velero backup logs csi-b2`.
root@arbuedlvsixt19 [DEV] velero-v1.14.0-linux-amd64 # velero backup describe csi-b2
Name:         csi-b2
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.21.12+rke2r2
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=21

Phase:  Failed (run `velero backup logs csi-b2` for more information)

Errors:    0
Warnings:  2

Namespaces:
  Included:  csi-app2
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Or label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto
Snapshot Move Data:          false
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2024-07-11 10:25:49 -0300 -03
Completed:  <n/a>

**Comment by giz33** [comment]
Already tried with aws plugin version 1.10.
helm upgrade --install velero --namespace=velero --create-namespace --set-file credentials.secretContents.cloud=/root/velero/credentials-velero --set configuration.backupStorageLocation[0].provider=aws --set configuration.backupStorageLocation[0].name=default --set configuration.backupStorageLocation[0].bucket=velero --set configuration.backupStorageLocation[0].config.region=my-minio --set configuration.backupStorageLocation[0].config.s3ForcePathStyle=true --set configuration.backupStorageLocation[0].config.s3Url=http://minio-endpoint.client.com/ --set configuration.backupStorageLocation[0].config.publicUrl=http://minio-endpoint.client.com/ --set snapshotsEnabled=true --set configuration.volumeSnapshotLocation[0].provider=aws --set configuration.volumeSnapshotLocation[0].name=default --set configuration.volumeSnapshotLocation[0].config.region=my-minio --set configuration.volumeSnapshotLocation[0].bucket=longhorn --set configuration.volumeSnapshotLocation[0].config.region=my-minio --set configuration.volumeSnapshotLocation[0].config.s3ForcePathStyle=true --set configuration.volumeSnapshotLocation[0].config.s3Url=http://minio-endpoint.client.com/ --set configuration.volumeSnapshotLocation[0].config.publicUrl=http://minio-endpoint.client.com/ --set "initContainers[0].name=velero-plugin-for-aws" --set "initContainers[0].image=velero/velero-plugin-for-aws:v1.10.0" --set "initContainers[0].volumeMounts[0].mountPath=/target" --set "initContainers[0].volumeMounts[0].name=plugins" --set configuration.features=EnableCSI vmware-tanzu/velero


Didn't work.Same error on POD Velero Server when trigger backup
 =/

**Comment by giz33** [comment]
Solved using the version 1.14 on client and Server.
And for the last errors, solved using version 1.6 of aws plugin, maybe some incompatibility with new version of the plugin with my Minio version(minio/minio:RELEASE.2022-05-08T23-50-31Z.hotfix.3d64b976d).

Now I got other error.
When I try to execute a full backup of my cluster excluding the PVC with the following command:

```velero schedule create full-backup --include-namespaces='*' --schedule="0 5 * * 1" --exclude-resources persistentvolumeclaims```

```velero backup create --from-schedule full-backup --wait```

I got the following error:

```time="2024-07-11T14:02:12Z" level=info msg="Backed up 10509 items out of an estimated total of 12597 (estimate will change throughout the backup)" backup=velero/full-backup-20240711140042 logSource="pkg/backup/backup.go:451" name=kubelet-runtime-errors namespace=monitoring progress= resource=servicelevelobjectives.pyrra.dev
time="2024-07-11T14:02:29Z" level=error msg="backup failed" backuprequest=velero/full-backup-20240711140042 controller=backup error="rpc error: code = Unknown desc = error putting object backups/full-backup-20240711140042/full-backup-20240711140042.tar.gz: MultipartUpload: upload multipart failed\n\tupload id: 2427f7c1-3a7a-4fa0-8cc5-74bc9fa80a8f\ncaused by: RequestError: send request failed\ncaused by: Put \"http://minio-endpoint-hml-client.client.com/velero/backups/full-backup-20240711140042/full-backup-20240711140042.tar.gz?partNumber=9&uploadId=2427f7c1-3a7a-4fa0-8cc5-74bc9fa80a8f\": read tcp 10.42.5.253:57562->4.74.134.53:80: read: connection reset by peer" logSource="pkg/controller/backup_controller.go:288"
time="2024-07-11T14:02:57Z" level=warning msg="Failed to discover group: packages.operators.coreos.com/v1" error="the server is currently unable to handle the request" logSource="pkg/discovery/helper.go:225```

**Comment by giz33** [comment]
I solved the problem of MultiPartUpload changing the configuration to point instead of my URL to the IP:NodePort.
I tried to put the below parameters on my Ingress and on my IngressController Configmap = 
nginx.ingress.kubernetes.io/proxy-body-size: "0"

But didn't work.
It only worked after I pointed the Velero to a NodeIP:NodePort on my cluster.

If someone have an idea about what I can try on the ingress to solve this, I would like to know.


Thank you so much for everyone who helped me here so far.

**Comment by giz33** [comment]
I was able to solve it, I give below the installation snippet that I used to anyone who pass trough the same problem:

helm upgrade --install velero
--namespace=velero
--create-namespace
--set-file credentials.secretContents.cloud=/root/velero/credentials-velero
--set configuration.backupStorageLocation[0].provider=aws
--set configuration.backupStorageLocation[0].name=default
--set configuration.backupStorageLocation[0].bucket=velero
--set configuration.backupStorageLocation[0].config.region=client-minio
--set configuration.backupStorageLocation[0].config.s3ForcePathStyle=true
--set configuration.backupStorageLocation[0].config.s3Url='http://3.74.135.55:32300/'
--set configuration.backupStorageLocation[0].config.publicUrl='http://3.74.135.55:32300/'
--set snapshotsEnabled=true
--set configuration.volumeSnapshotLocation[0].provider=aws
--set configuration.volumeSnapshotLocation[0].name=default
--set configuration.volumeSnapshotLocation[0].config.region=client-minio
--set configuration.features=EnableCSI
--set "initContainers[0].name=velero-plugin-for-aws"
--set "initContainers[0].image=velero/velero-plugin-for-aws:v1.6.0"
--set "initContainers[0].volumeMounts[0].mountPath=/target"
--set "initContainers[0].volumeMounts[0].name=plugins"
vmware-tanzu/velero


What I need to do is to remove some parameters that are no longer supported:
--set configuration.volumeSnapshotLocation[0].bucket=longhorn          
--set configuration.volumeSnapshotLocation[0].config.s3ForcePathStyle=true     
--set configuration.volumeSnapshotLocation[0].config.s3Url="http://IP:PORT"    
--set configuration.volumeSnapshotLocation[0].config.publicUrl="http://IP:PORT"

I understand that if I configured correctly the CSI plugin, snapshotclass and longhorn.
Velero will trigger it on Longhorn that will automatically search for a bucket named longhorn on Minio.

I also forget to put the parameter  --set configuration.features=EnableCSI


Now everything is good(Backups with PVC enabled and backups with no PVC backup enabled):

![image](https://github.com/vmware-tanzu/velero/assets/19286616/414e30b6-0aa0-4e5f-bafa-13173740826c)




Tks

**Comment by giz33** [comment]
I was able to solve it, I give below the installation snippet that I used to anyone who pass trough the same problem:

helm upgrade --install velero
--namespace=velero
--create-namespace
--set-file credentials.secretContents.cloud=/root/velero/credentials-velero
--set configuration.backupStorageLocation[0].provider=aws
--set configuration.backupStorageLocation[0].name=default
--set configuration.backupStorageLocation[0].bucket=velero
--set configuration.backupStorageLocation[0].config.region=client-minio
--set configuration.backupStorageLocation[0].config.s3ForcePathStyle=true
--set configuration.backupStorageLocation[0].config.s3Url='http://3.74.135.55:32300/'
--set configuration.backupStorageLocation[0].config.publicUrl='http://3.74.135.55:32300/'
--set snapshotsEnabled=true
--set configuration.volumeSnapshotLocation[0].provider=aws
--set configuration.volumeSnapshotLocation[0].name=default
--set configuration.volumeSnapshotLocation[0].config.region=client-minio
--set configuration.features=EnableCSI
--set "initContainers[0].name=velero-plugin-for-aws"
--set "initContainers[0].image=velero/velero-plugin-for-aws:v1.6.0"
--set "initContainers[0].volumeMounts[0].mountPath=/target"
--set "initContainers[0].volumeMounts[0].name=plugins"
vmware-tanzu/velero

What I need to do is to remove some parameters that are no longer supported:
--set configuration.volumeSnapshotLocation[0].bucket=longhorn
--set configuration.volumeSnapshotLocation[0].config.s3ForcePathStyle=true
--set configuration.volumeSnapshotLocation[0].config.s3Url="http://ip:PORT/"
--set configuration.volumeSnapshotLocation[0].config.publicUrl="http://ip:PORT/"

I understand that if I configured correctly the CSI plugin, snapshotclass and longhorn.
Velero will trigger it on Longhorn that will automatically search for a bucket named longhorn on Minio.

I also forget to put the parameter --set configuration.features=EnableCSI

Now everything is good(Backups with PVC enabled and backups with no PVC backup enabled):



![image](https://github.com/vmware-tanzu/velero/assets/19286616/1482e132-99d0-41ef-89a3-bdf64146d687)


Tks
