### ISSUE TITLE
Restore namespace remapping should adjust references to remapped namespaces

### ISSUE THREAD

**Issue by ncdc** [vmware-tanzu/velero#80]
If a backup contains references to namespace `src` object `foo`, and we're using a namespace mapping to remap namespace `src` to `dst`, any items that reference `src` or `src/foo` probably should be adjusted to point at `dst` instead. Things I can think of:
- pv.spec.claimRef
- rolebinding.subjects[*].namespace
- clusterrolebinding.subjects[*].namespace

suggestion from https://twitter.com/timoreimann/status/907703134553853952

**Comment by rosskukulinski** [comment]
This should probably be done around the same time as #192.  Both relate to cloning a namespace within a cluster.

**Comment by skriss** [comment]
See #1954 for a specific instance of the role-bindings issue.

**Comment by alexander-demichev** [comment]
@skriss I can add restore actions for cluster role bindings and role bindings that should swap namespace references.

**Comment by skriss** [comment]
@alexander-demichev that sounds like a reasonable step to me, thanks!
