### ISSUE TITLE
PV snapshot was skipped when use `EnableCSI` flag

### ISSUE THREAD

**Issue by chrislinan** [vmware-tanzu/velero#8000]
**What steps did you take and what happened:**

use EnableCSI feature in Velero, and backup PV, but this PV backup was skipped and I can find the reason from here: https://github.com/vmware-tanzu/velero/blob/release-1.12/pkg/backup/item_backupper.go#L519 

**What did you expect to happen:**
PV snapshot succeed. And I am confused. 
From what I know, the CSI volume snapshot function was supported in AWS, Azure and GCP plugin, that means we don't need to install CSI plugin anymore.

And I assume that When I use the feature `enable CSI`, the PV will take a CSI snapshot, I don't need to install the CSI plugin, but This log confused me: https://github.com/vmware-tanzu/velero/blob/release-1.12/pkg/backup/item_backupper.go#L519 

Actually, the PV snapshot was skipped. Could you help give me some guide?

Compared with the above,  we have another PV, which was transformed from `aws-ebs-dynamic-provisioner` to CSI, and this PV has two annotations:
```
kubernetes.io/createdby: aws-ebs-dynamic-provisioner
pv.kubernetes.io/provisioned-by: ebs.csi.aws.com
```
This PV can take a snapshot successfully because it has no `CSI` section in its Spec.

```
Phase:  Completed

Errors:    0
Warnings:  0

Namespaces:
  Included:  monitoring
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  app=alertmanager

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2024-07-11 11:21:47 +0800 CST
Completed:  2024-07-11 11:21:57 +0800 CST

Expiration:  2024-08-10 11:21:47 +0800 CST

Total items to be backed up:  72
Items backed up:              72

Velero-Native Snapshots:  2 of 2 snapshots completed successfully (specify --details for more information)
```

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.12
- Velero features (use `velero client config get features`): EnableCSI
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
https://github.com/vmware-tanzu/velero/blob/release-1.12/pkg/backup/item_backupper.go#L519

This line means Velero skips to snapshot the Volume by Velero-native snapshot. That doesn't mean the CSI plugin doesn't back up the volume data.

Velero supports two ways of snapshot. One is the Velero-native snapshot, which takes a snapshot by calling the cloud provider's snapshot API. The other way is the CSI snapshot. That creates a snapshot by the CSI way.

Velero will first try to take the snapshot by the CSI way when the `EnableCSI` feature is enabled, but if the CSI plugin fails to do the snapshot, Velero will fall back to the Velero-native snapshot way. That makes sure the volume can be backed up on error. That's also the reason why Velero needs to check whether to skip the Velero-native snapshot on the `EnableCSI` feature is enabled scenario.

**Comment by chrislinan** [comment]
Thanks for your help. Do I need to install CSI plugin?
I am using Velero 1.12, and aws plugin version is 1.8.1. Because AFAIK, the CSI plugin's function was already implemented in AWS plugin?  
https://velero.io/docs/v1.14/csi/ 
> Note: The AWS, Microsoft Azure, and Google Cloud Platform (GCP) Velero plugins version 1.4 and later are able to snapshot and restore persistent volumes provisioned by a CSI driver via the APIs of the cloud provider, without having to install Velero CSI plugins. See the [AWS](https://github.com/vmware-tanzu/velero-plugin-for-aws), [Microsoft Azure](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure), and [Google Cloud Platform (GCP)](https://github.com/vmware-tanzu/velero-plugin-for-gcp) Velero plugin repo for more information on supported CSI drivers. From v1.14, no need to install the CSI plugin, because it is integrated into the Velero code base.

**Comment by chrislinan** [comment]
> This line means Velero skips to snapshot the Volume by Velero-native snapshot. That doesn't mean the CSI plugin doesn't back up the volume data. 

Yes, that is reasonable, I expected the CSI snapshot created,  but it wasn't.  Then I guess, I need to install CSI plugin ?

**Comment by blackpiglet** [comment]
If you are using the Velero v1.12, you need to install the Velero CSI plugin. 
For Velero v1.14, the Velero CSI plugin is already merged into the Velero code base, that's the reason why v1.14 doesn't require CSI plugin installation.

**Comment by chrislinan** [comment]
> Velero will first try to take the snapshot by the CSI way when the EnableCSI feature is enabled, but if the CSI plugin fails to do the snapshot, Velero will fall back to the Velero-native snapshot way

For this I still have a question, I am using Velero 1.12, and I use the `EnableCSI` feature, but I didn't install the CSI plugin. Then the PV backup failed for the CSI snapshot. 

But the Velero-native snapshot was taken neither. It's not the behavior described in this sentences: `but if the CSI plugin fails to do the snapshot, Velero will fall back to the Velero-native snapshot way`

**Comment by blackpiglet** [comment]
Please check whether the `--snapshot-location-config` was set correctly.
To make the native snapshot work, at least, the region parameter should be set.
https://github.com/vmware-tanzu/velero-plugin-for-aws?tab=readme-ov-file#install-and-start-velero

**Comment by chrislinan** [comment]
Thanks for your help, it's clear to me. I will close this issue.
