### ISSUE TITLE
Issue with Restoring Specific Data within PVC using Velero

### ISSUE THREAD

**Issue by ithesadson** [vmware-tanzu/velero#8007]
**What steps did you take and what happened:**

1- I performed a backup with Velero, including Persistent Volumes (PVs), and completely deleted a namespace that included a web service with a web interface. When I restored from the backup, the namespace, including the PV data, was successfully recreated and accessible via the web interface.
2- I tried a different scenario where I deleted specific data within a Persistent Volume Claim (PVC) while keeping the PVC itself intact. Upon attempting to restore from the backup, the specific data that was deleted did not get restored.

**What did you expect to happen:**
When restoring from a backup, Velero should restore the specific data within the PVC that was deleted, regardless of whether the PVC itself was deleted or not.

**Anything else you would like to add:**

StorageClass : Used Longhorn
Velero server installation steps:
`
velero install \
  --provider aws \
  --image velero/velero:v1.14.0 \
  --plugins velero/velero-plugin-for-aws:v1.10.0 \
  --bucket K8S-BACKUP \
  --secret-file ./credentials-velero \
  --use-node-agent \
  --use-volume-snapshots=false \
  --uploader-type restic \
  --default-volumes-to-fs-backup \
  --namespace velero \
  --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://URL:PORT
`

**Environment:**

- $ velero version
`
Client:
        Version: v1.14.0
        Git commit: 2fc6300f2239f250b40b0488c35feae59520f2d3
Server:
        Version: v1.14.0
`
- $ velero client config get features: 
` 
features: <NOT SET>
`

- $ kubectl version
`
Client Version: v1.29.5
Server Version: v1.29.5
`
- $ cat /etc/os-release
`
NAME="Rocky Linux"
VERSION="9.3 (Blue Onyx)"
`
**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
Currently this is not supported. PR #7345 will cover this requirement.
