### ISSUE TITLE
Expose PVPatchMaximumDuration timeout for custom configuration

### ISSUE THREAD

**Issue by shubham-pampattiwar** [vmware-tanzu/velero#8020]
**What steps did you take and what happened:**

Performed restore operation for 1000 pods via CSI  using SC ocs-storagecluster-cephfs 
Restore PartiallyFailed
```
Errors:
  Velero:     <none>
  Cluster:    <none>
  Namespaces:
    datagen-single-ns-1000pods-cephfs:  fail to patch dynamic PV, err: context deadline exceeded, PVC: pvc-perf-datagen-7-13-1gi-1000-hfs-16, PV: pvc-4290d7d3-08a2-46f7-b1c5-2a68edaea968
                                        fail to patch dynamic PV, err: context deadline exceeded, PVC: pvc-perf-datagen-7-13-1gi-1000-hfs-159, PV: pvc-93c5e34b-7c47-402e-9988-90c0eb8888b5
                                        fail to patch dynamic PV, err: context deadline exceeded, PVC: pvc-perf-datagen-7-13-1gi-1000-hfs-158, PV: pvc-3edc4194-3136-4ce5-9a5e-bde1c7d005a4
                                        fail to patch dynamic PV, err: context deadline exceeded, PVC: pvc-perf-datagen-7-13-1gi-1000-hfs-165, PV: pvc-f7cac250-8bfa-4964-a23b-d7ffffb2ea37
                                        fail to patch dynamic PV, err: context deadline exceeded, PVC: pvc-perf-datagen-7-13-1gi-1000-hfs-160, PV: pvc-9c2e50c9-c7a6-436e-afff-90015f5f7fc3
                                        fail to patch dynamic PV, err: context deadline exceeded, PVC: pvc-perf-datagen-7-13-1gi-1000-hfs-163, PV: pvc-45b3a3fe-89a6-46a6-a1e6-1078e8553e17
                                        fail to patch dynamic PV, err: context deadline exceeded, PVC: pvc-perf-datagen-7-13-1gi-1000-hfs-333, PV: pvc-c02003d2-7c79-4b73-9158-a89f52093813
                                        fail to patch dynamic PV, err: context deadline exceeded, PVC: pvc-perf-datagen-7-13-1gi-1000-hfs-471, PV: pvc-65512743-edfd-4379-b6af-85361114e86c
                                        fail to patch dynamic PV, err: context deadline exceeded, PVC: pvc-perf-datagen-7-13-1gi-1000-hfs-475, PV: pvc-7a152cea-db2e-45b4-b16d-01a6b2efbf31
                                        fail to patch dynamic PV, err: context deadline exceeded, PVC: pvc-perf-datagen-7-13-1gi-1000-hfs-583, PV: pvc-515faa02-8e41-4a96-b809-8779743c2fd5
Backup:  backup-csi-datagen-single-ns-1000pods-cephfs
Namespaces:
  Included:  all namespaces found in the backup
  Excluded:  <none>
```
**What did you expect to happen:**
Restore to complete successfully 

Root cause: lack of an override for [PVPatchMaximumDuration](https://github.com/vmware-tanzu/velero/blob/35c90f16728cf62d6d7574637da48ceea11cda34/pkg/controller/restore_finalizer_controller.go#L49) timeout, need to expose this as a velero server arg so that users can configure.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by shubham-pampattiwar** [comment]
Proposed solution draft PR: https://github.com/vmware-tanzu/velero/pull/8021

**Comment by Lyndon-Li** [comment]
Reopen for cherry-pick.

**Comment by Lyndon-Li** [comment]
Completed
