### ISSUE TITLE
regression: aws-sdk-go-v2 bump removed region hint breaking GetBucketRegion

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#8022]
**What steps did you take and what happened:**

The bump removed [region hint](https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/177/files#diff-7ba4f8953b70f82b66f6ba15ea753c9bb847d2e01173baaef65574f60e57d86cL40-L41) which is required in environments where ~/.aws/credentials do not specify credentials or specified region.

```
time="2024-07-12T17:30:17Z" level=error msg="Failed to determine bucket's region bucket: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX, error: operation error S3: HeadBucket, resolve auth scheme: resolve endpoint: endpoint rule error, Invalid region: region was not a valid DNS name." backup-storage-location=openshift-adp/ts-velero-test-1 cmd=/plugins/velero-plugin-for-aws controller=backup-storage-location logSource="/opt/app-root/src/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:153" pluginName=velero-plugin-for-aws
```

Per following
https://github.com/aws/aws-sdk-go-v2/blob/4599f78694cabb6853addabc6f92cb197fdb5647/feature/s3/manager/bucket_region.go#L45-L47
AWS will make a request to bucketname.s3.\<regionHint\>.amazonaws.com/
Where region hint is obtained via config which in local dev machine could be loaded from ~/.aws/credentials so unit tests if any won't fail but in a container/k8s environment where cred file is not specified it may not work.

This bug affects users who do not specify region in their BSL config and rely on automatic region discovery.

**What did you expect to happen:**
Not error

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by kaovilai** [comment]
target v1.14.2?

**Comment by reasonerjt** [comment]
> target v1.14.2?
v1.14.1 is still WIP so I think it we can ship it in v1.14.1 (plugin v1.10.1)
