### ISSUE TITLE
Velero backup is failing partially with pod volumes have no associated PVCs errors

### ISSUE THREAD

**Issue by rkunalan** [vmware-tanzu/velero#8042]
**What steps did you take and what happened:**
We are trying to update the Velero from v1.13.2(chartVersion - v1.6.7) to v1.14.0 (chartVersion - v1.7.2) and getting some PVC related error while performing the Velero backups. This is working fine on v1.13.2. When I checked some of these pod volumes all of them are using `emptyDir` volume type. I have a resource filtering config map to skip this volume type. On this version it is not working as expected.

**What did you expect to happen:**
Velero backup should work without errors. Now it is partially failing.

**The following information will help us better understand what's going on**:

The debug bundle is attached for troubleshooting - [bundle-2024-07-23-14-39-50.tar.gz](https://github.com/user-attachments/files/16353120/bundle-2024-07-23-14-39-50.tar.gz).

**Anything else you would like to add:**
Our resource filtering config map is below.
```
version: v1
volumePolicies:
- conditions:
    nfs: {}
  action:
    type: skip
- conditions:
    volumeTypes:
      - emptyDir
  action:
    type: skip
```

**Environment:**

- Velero version (use `velero version`): v1.7.2
- Velero features (use `velero client config get features`): Not set
- Kubernetes version (use `kubectl version`): 1.25.7
- OS (e.g. from `/etc/os-release`): VMware Photon OS/Linux

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
Duplicate with #7929 
Sorry for the inconvenience. This is fixed in the main branch and the planning v1.14.1.

**Comment by rkunalan** [comment]
No worries, @blackpigle. Thanks for the fix.

**Comment by blackpiglet** [comment]
Then close this issue for now, because it's already triaged in others.
