### ISSUE TITLE
Override current pv data with new restore

### ISSUE THREAD

**Issue by TheCodingSheikh** [vmware-tanzu/velero#8047]
the first restore creates the pv, pvc, pods etc.. when restoring a second time with a new backup, the new data is not restored in the pv. what i'm doing is deleting the pods so that they are created again with the initContainer (velero-restore-helper) and it will add the new data that was backed up from original pv.
is there a better solution to this?

**Comment by sseago** [comment]
@TheCodingSheikh Currently, the workaround you describe is the only option. There's a design proposal to implement what you're asking for, though: https://github.com/vmware-tanzu/velero/pull/7481

**Comment by TheCodingSheikh** [comment]
@sseago thanks
I read that using csi snapshot backup will make it work, is this claim true?
I haven't honestly tried yet with csi, i just want to confirm.
Im using rook ceph fyi

**Comment by sseago** [comment]
@TheCodingSheikh you will need to delete the PVC for restore from CSI snapshot, since snapshots can't update existing volumes. And you'll need to delete the pod since the PVC won't actually be removed until the mounting pod is gone.
