### ISSUE TITLE
Deprecate Restic

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#8072]
Here is the plan to deprecate Restic from Velero data path (for fs-backup since Restic is used by fs-backup only) according to the [deprecation policy](https://github.com/vmware-tanzu/velero/blob/main/GOVERNANCE.md#:~:text=maintainers%20from%20Velero-,Deprecation%20Policy,-Deprecation%20Process):

- The deprecation process starts from 1.15 following the deprecation policy
- For 1.15, the information of Restic being deprecated will be added to fs-backup doc and release note
- For 1.15 and 1.16, if Restic is used by the backup, the backup still creates and succeeds
- For 1.17 and 1.18, backup with Restic will be disabled, but users are still allowed to restore from their previous Restic backups
- From 1.19, both Restic backup and restore will be disabled for fs-backup

**Comment by Lyndon-Li** [comment]
@reasonerjt @blackpiglet @ywk253100 @sseago @shubham-pampattiwar @anshulahuja98

**Comment by sseago** [comment]
We should also include deprecation warnings in 1.15/1.16:
1) Installer will issue a warning when uploader-type=restic is passed
2) Server will log a warning on startup when uploader-type=restic is passed
3) Backup will log a warning when run with uploaderType set to restic.

**Comment by sseago** [comment]
+1 to deprecating Restic in 1.15

**Comment by Lyndon-Li** [comment]
> 1. uploader-type

Sure, will do these in the code changes.

**Comment by Lyndon-Li** [comment]
> We should also include deprecation warnings in 1.15/1.16:
> 
> 1. Installer will issue a warning when uploader-type=restic is passed
> 2. Server will log a warning on startup when uploader-type=restic is passed
> 3. Backup will log a warning when run with uploaderType set to restic.

Sure, will do these in the code changes.

**Comment by Lyndon-Li** [comment]
> 1. Installer will issue a warning when uploader-type=restic is passed

For this one, I think we may not able to generate a warning for a parameter with specific value. So could we do it for CLI only? cc @reasonerjt

**Comment by anshulahuja98** [comment]
I have no opinion on restic deprecation, please assume I am okay with majority.

**Comment by shubham-pampattiwar** [comment]
+1 to deprecating Restic plan

**Comment by ywk253100** [comment]
+1 to deprecating Restic plan

**Comment by blackpiglet** [comment]
+1 to deprecating Restic plan

**Comment by reasonerjt** [comment]
+1 to deprecating Restic plan

**Comment by reasonerjt** [comment]
> For this one, I think we may not able to generate a warning of a parameter with specific value for Helm install. So could we do it for Velero CLI only? cc @reasonerjt

Let's make sure about the warning in CLI only.

**Comment by pradeepkchaturvedi** [comment]
+1 for Restic deprecation plan. Lets ensure:
- call out deprecation on respective release notes (1.15, 1.16...)
- update velero doc sections accordingly
- installer as well as when backup created using restic, deprecation warning shown in logs & CLI output. 
- if Velero loose any functionality due to restic deprecation, call out in doc sections accordingly

**Comment by Lyndon-Li** [comment]
> +1 for Restic deprecation plan. Lets ensure:
> 
> * call out deprecation on respective release notes (1.15, 1.16...)
> * update velero doc sections accordingly
> * installer as well as when backup created using restic, deprecation warning shown in logs & CLI output.
> * if Velero loose any functionality due to restic deprecation, call out in doc sections accordingly

For 1, will do it in a dedicate PR for release notes of 1.15, as well as 1.16~1.19
For 2 and 3, they have been included in PR #8096
For 4, no functionality loose for 1.15 and 1.16, will do it for 1.7~1.19

**Comment by Skaronator** [comment]
Sorry to abuse this issue but I'm unable to find any informations _why_ Restic will be deprecated and what benefits Kopia brings.

**Comment by kaovilai** [comment]
> why Restic will be deprecated

https://github.com/vmware-tanzu/velero/issues/4538
https://github.com/restic/restic/issues/2282
etc.

Performance, no locking issues (a bunch of issues opened here were restic lock issues) are main ones for me.

**Comment by kaovilai** [comment]
[Copy of kopia-restic-comparison.docx.pdf](https://github.com/user-attachments/files/21123731/Copy.of.kopia-restic-comparison.docx.pdf)

Here is a copy of the document [mentioned](https://github.com/vmware-tanzu/velero/issues/4538#issuecomment-1119231618) in 4538
