### ISSUE TITLE
Restore logs indicate that a resource is restored as it should, but it's not

### ISSUE THREAD

**Issue by mimmi-gjems** [vmware-tanzu/velero#8075]
**What steps did you take and what happened:**

Trying to restore an Argo CD app project:

`velero restore create <restore-name> --from-backup <backup-name> --namespace-mappings argocd:argocd-restore --include-namespaces argocd --include appprojects.argoproj.io`

The restore logs indicate that the restore operation succeeded, but the resource is not present in the new `argocd-restore` namespace.

An excerpt of the output from `velero restore logs <restore-name>`:
`
[...]
time="2024-08-01T13:57:25Z" level=info msg="Attempting to restore AppProject: default" logSource="pkg/restore/restore.go:1487" restore=velero/restore-20240625-20240801
time="2024-08-01T13:57:25Z" level=info msg="the managed fields for argocd-restore/default is patched" logSource="pkg/restore/restore.go:1688" restore=velero/restore-20240625-20240801
time="2024-08-01T13:57:25Z" level=info msg="Restored 1 items out of an estimated total of 1 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:778" name=default namespace=argocd-restore progress= resource=appprojects.argoproj.io restore=velero/restore-20240625-20240801
[...]
`

Running `kubectl get appproject -n argocd-restore` shows `No resources found in argocd-restore namespace.`.

**What did you expect to happen:**

Expected to find the app project in the new `argocd-restore` namespace, or at least get some log information that could be used for troubleshooting.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

This issue occured in a customer's environment, and I've not been able to reproduce the scenario in a test environment, so it's difficult to supply logs.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): v1.14.0
- Velero features (use `velero client config get features`): `features: <NOT SET>`
- Kubernetes version (use `kubectl version`): v1.28.10
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by sseago** [comment]
Is it possible that something deleted that resource after it was created? From the log excerpt, the post-creation Patch call to update managed fields returned successfully (if the resource did not exist, it would have gotten a NotFound error). This also means that the earlier create call also completed successfully. Seems like something must have deleted it afterwards. If you watch the `kubectl get call` while running the restore, maybe you'll see it created and then deleted again?
```
watch -n 0.1 kubectl get appproject -n argocd-restore
```
