### ISSUE TITLE
Error with --snapshot-move-data Flag in Velero with Rook-Ceph Storage backup time

### ISSUE THREAD

**Issue by jayrajmeh0** [vmware-tanzu/velero#8092]
Description
I am encountering an issue while attempting to back up and restore pods using Velero with Rook-Ceph as the storage backend. The error occurs when using the --snapshot-move-data flag for CSI snapshot data movement. Detailed steps and error messages are provided below.

Steps to Reproduce

- Setup Environment:
Velero configured with Rook-Ceph as the storage backend.
Kubernetes cluster managed by Kubespray.
- Backup Pod:
Execute the backup command with the --snapshot-move-data flag.
velero backup create media6 --snapshot-move-data
- Encounter Error:
Backup process fails

Current Issue
The backup  processes fail with an error stating partially failed.

Expected Outcome
• Successful backup of pods using the --snapshot-move-data flag with Velero and Rook-Ceph.
• Successful restore of the backed-up data without encountering the DataUpload error.

Actual Outcome
• The backup process fails with an error related to partially failed.

Additional Information
• Current Environment:
- Kubernetes cluster managed by Kubespray.
- Velero for backup  operations.
- Rook-Ceph as the storage backend.

Request for Assistance
I would appreciate guidance on the following:
1. Any additional configuration steps or best practices for using the --snapshot-move-data flag with Velero and Rook-Ceph.
2. Clarification on whether this is a known issue and if there are any patches or updates available to address it.

I have now installed the node-agent, and it is running. I attempted to back up, but I'm encountering a error.

![Screenshot_752](https://github.com/user-attachments/assets/9e05007b-383c-477e-8c1f-5a946f2eeec7)
![Screenshot_749](https://github.com/user-attachments/assets/906a14d7-bf76-4e51-8c85-b01c6b125a1c)
![Screenshot_751](https://github.com/user-attachments/assets/8f540c60-2b44-4037-948b-2967f89ab355)
![Screenshot_750](https://github.com/user-attachments/assets/d4ec2051-df04-4943-9626-97baa36dd759)

Here is the related bundle file:
[bundle-2024-08-06-17-38-42.tar.gz](https://github.com/user-attachments/files/16510054/bundle-2024-08-06-17-38-42.tar.gz)

**Comment by Lyndon-Li** [comment]
Dup with #7898

**Comment by jayrajmeh0** [comment]
@Lyndon-Li I don’t understand; there’s nothing related to my current issue.

**Comment by Lyndon-Li** [comment]
Here is the error associated to the partially failed backup:
`"message": "found a dataupload velero/media6-fj8fl with expose error: Pod is unschedulable: 0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.. mark it as cancel",`

**Comment by jayrajmeh0** [comment]
@Lyndon-Li You have no idea

`"message": "found a dataupload velero/media6-fj8fl with expose error: Pod is unschedulable: 0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.. mark it as cancel",`

 why this issue occurred, and the error message displayed does not provide a solution. The issue #7898 lacks any description for resolution. Is it possible that the problem lies in my installation steps or elsewhere? Any guidance to help resolve this issue would be appreciated.

**Comment by Lyndon-Li** [comment]
There is no resolution/workaround, you have to wait the release of 1.14.1 or you need to downgrade to 1.13.x

**Comment by jayrajmeh0** [comment]
@Lyndon-Li This means that the issue 

`"message": "found a dataupload velero/media6-fj8fl with expose error: Pod is unschedulable: 0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.. mark it as cancel"`,

did not occur in version 1.13.x, and my backup process was executed using the --snapshot-move-data flag, correct?

**Comment by Lyndon-Li** [comment]
Yes

**Comment by jayrajmeh0** [comment]
@Lyndon-Li Thank you! I will check it and keep you updated.

**Comment by jayrajmeh0** [comment]
@Lyndon-Li Following your suggestion, I used version 1.13.2. After installing it and attempting to back up with the --snapshot-move-data flag, the backup status completed without any errors. However, the snapshot data was not moved as expected. I also checked the MinIO S3 bucket, and there was no Kopia folder created for the snapshot backup. In short, this is not meeting my requirements. Do you have any solutions related to this issue?

![Screenshot_754](https://github.com/user-attachments/assets/340514f7-1126-4457-860a-a57a9c8c6230)
![Screenshot_755](https://github.com/user-attachments/assets/2e151fe9-11dc-44a4-b46e-48736502444e)
![Screenshot_756](https://github.com/user-attachments/assets/6da142f5-2797-4c5e-ac2e-6771d0c97458)
![Screenshot_758](https://github.com/user-attachments/assets/85509aa2-e740-43ec-bdd0-41b992409a4e)
![Screenshot_757](https://github.com/user-attachments/assets/aeaeee31-3d76-4853-a333-b807627aaa7c)
![Screenshot_759](https://github.com/user-attachments/assets/6eb9d38b-37cf-4373-af66-9bb35189da0f)
![Screenshot_760](https://github.com/user-attachments/assets/7b431524-aa24-4e72-b47b-8ffe11a10457)
![Screenshot_761](https://github.com/user-attachments/assets/0c3bcc24-d5af-4e3e-a26c-13b6f551e806)

Here is the related bundle file:
[bundle-2024-08-07-15-23-09.tar.gz](https://github.com/user-attachments/files/16521723/bundle-2024-08-07-15-23-09.tar.gz)

**Comment by Lyndon-Li** [comment]
For Velero prior to 1.14, you need to add CSI plugin in installation if you want to use data mover feature.

**Comment by jayrajmeh0** [comment]
@Lyndon-Li  I'm encountering this error related to volume snapshots and classes, even though I've already defined them in my namespace.
 
![Screenshot_762](https://github.com/user-attachments/assets/c4b9d9e3-4c9f-4026-b052-40d84a06127e)
![Screenshot_763](https://github.com/user-attachments/assets/72a1fd40-37cd-4b95-a3fe-90c46af238f5)
![Screenshot_764](https://github.com/user-attachments/assets/20fa61d5-7343-4e5a-a0ae-6e68fece4e5b)
![Screenshot_765](https://github.com/user-attachments/assets/9ebf01c0-d425-4817-97f5-fed67d2aa84b)

Here is the related bundle file:
[bundle-2024-08-07-17-03-56.tar.gz](https://github.com/user-attachments/files/16522862/bundle-2024-08-07-17-03-56.tar.gz)

**Comment by sseago** [comment]
@jayrajmeh0 You're using version 0.1.1 of the CSI plugin. For Velero 1.13 you need 0.7.x.

**Comment by jayrajmeh0** [comment]
**@Lyndon-Li & @sseago Thank you both for your guidance and assistance with the backup process. I was able to take a snapshot backup using the flag --snapshot-move-data , which proves that I successfully completed this task.**

![Screenshot_773](https://github.com/user-attachments/assets/a616c95e-c953-4811-9319-12950b7d385a)
![Screenshot_774](https://github.com/user-attachments/assets/cc536e01-04f8-44c9-85fd-b2fee8665b80)
![Screenshot_775](https://github.com/user-attachments/assets/55a66b6f-1ceb-4dfb-80b3-9a22818e23e4)
![Screenshot_776](https://github.com/user-attachments/assets/cdef23e4-ea43-48d6-87e2-6ac13ff1ab05)
![Screenshot_777](https://github.com/user-attachments/assets/40b82f0a-d556-4345-afd5-8e9e65557a00)
![Screenshot_783](https://github.com/user-attachments/assets/2b5e9214-c1be-46b3-9dc4-90a7521b8b22)

**The backup process has been successfully completed. However, when I removed the namespace associated with the backup shown in the screenshot above, I encountered an issue during my next task, which is restoring using Velero. The details of the issue are as follows:**

![Screenshot_778](https://github.com/user-attachments/assets/3cef7389-b1ee-4468-9565-d7340ced34be)
![Screenshot_780](https://github.com/user-attachments/assets/7fcc7db2-fe03-4adf-8bdc-4c80cecd5384)
![Screenshot_781](https://github.com/user-attachments/assets/6e4666f3-d539-46ba-ae26-c40b6299fd5f)

Here is the related bundle file:
[bundle-2024-08-08-12-08-27.tar.gz](https://github.com/user-attachments/files/16539034/bundle-2024-08-08-12-08-27.tar.gz)

**Comment by reasonerjt** [comment]
By checking the logs I found following error messages:
```
time="2024-08-08T06:25:44Z" level=info msg="BackupStorageLocations is valid, marking as available" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:126"
time="2024-08-08T06:25:53Z" level=error msg="fail to get DataDownload: fail to list DataDownload: etcdserver: leader changed" Action=PVCRestoreItemAction Namespace=velero OperationID=dd-4703bc72-cbef-4a31-a0bf-8a3ad433d90f.be3cfbe8-fe0a-41d7f03b9 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/restore/pvc_action.go:240" pluginName=velero-plugin-for-csi
time="2024-08-08T06:25:53Z" level=info msg="Marking restore mongo-20240808115503 FinalizingPartiallyFailed" logSource="pkg/controller/restore_operations_controller.go:186" restore=velero/mongo-20240808115503
```

So it seems a random issue in etcd, if the problem is highly reproducible, you may want to check if there's any resource or perf issue in your cluster.

**Comment by jayrajmeh0** [comment]
@reasonerjt 
I have checked all the pods, and everything looks good without any errors during the restore process. Can you help me resolve the issue in more detail?

**@Lyndon-Li @sseago @reasonerjt** 
**Additionally, I have another question related to Velero and Ceph storage. Currently, I have a three-node Kubernetes cluster with Ceph storage. If any of these three nodes were to be destroyed and my database backup is stored in the cloud using Velero, can I restore it to a new Kubernetes environment? What are the prerequisites for this, particularly concerning Ceph storage pools and OSDs? Do I need to set up the same names or configurations for Velero to restore everything correctly?**

**Comment by jayrajmeh0** [comment]
@Lyndon-Li 
**I successfully backed up one cluster and used the --snapshot-move-data flag to restore the backup on a second cluster. The restore process completed without any issues, and all statuses showed as successful. However, when I checked the MongoDB pod in the namespace of the new cluster, it was not functioning properly and encountered some issues.**

![Screenshot_822](https://github.com/user-attachments/assets/4940e67b-2003-475a-97fa-fa7ef073e2ca)
![Screenshot_823](https://github.com/user-attachments/assets/f8bf49cf-c591-45c3-b149-206aa0ab5f60)
![Screenshot_827](https://github.com/user-attachments/assets/f5d6ab66-8892-47f3-ad0c-eab13776d22c)
![Screenshot_828](https://github.com/user-attachments/assets/d1ec02df-2972-4ef8-86d7-7a79d094ea88)
![Screenshot_824](https://github.com/user-attachments/assets/e9f9be1f-b037-4a8f-a7d0-5f08e834eff3)
![Screenshot_825](https://github.com/user-attachments/assets/015e94b7-d654-485b-974f-db12beafbefc)

Here is the related bundle file:
[bundle-2024-08-16-16-45-06.tar.gz](https://github.com/user-attachments/files/16636478/bundle-2024-08-16-16-45-06.tar.gz)

**Comment by reasonerjt** [comment]
@jayrajmeh0 

As for the latest issue, it seems the infrastructure where you restore the mongo DB does not meet the requirement of mongoDB.
I suggest you read the links in the error message to understand why it failed.  IMO it is beyond the scope of velero.
