### ISSUE TITLE
maintenance job fails always for a single schedule with: "maintenance must be run by designated user"

### ISSUE THREAD

**Issue by mosesdd** [vmware-tanzu/velero#8110]
**What steps did you take and what happened:**

Created a schedule to backup a namespace months ago, since these maintenance jobs exist they're always failing for this single schedule.

> 2024-08-13T06:08:56.162189300Z time="2024-08-13T06:08:56Z" level=info msg="Succeeded to open repo for maintenance" logSource="pkg/repository/udmrepo/kopialib/lib_repo.go:172"
2024-08-13T06:08:56.920458025Z time="2024-08-13T06:08:56Z" level=error msg="An error occurred when running repo prune" error="failed to prune repo: error to prune backup repo: error to maintain repo: error to run maintenance under mode auto: maintenance must be run by designated user: " error.file="/go/src/github.com/vmware-tanzu/velero/pkg/repository/udmrepo/kopialib/lib_repo.go:219" error.function="github.com/vmware-tanzu/velero/pkg/repository/udmrepo/kopialib.(*kopiaMaintenance).runMaintenance" logSource="pkg/cmd/cli/repomantenance/maintenance.go:72"

**What did you expect to happen:**
Maintenance jobs succeeds as for the other schedules

**Environment:**

- Velero version (use `velero version`):  v1.14.0
- Velero features (use `velero client config get features`): <NOT SET>
- Kubernetes version (use `kubectl version`):  v1.28.9

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by mosesdd** [comment]
Fixed it myself, somehow there was no maintenance owner set so I did manually:

> kopia maintenance set --owner=default@default

After to connecting with

> kopia repository connect s3 --bucket=velero --access-key=ACCESS_KEY --secret-access-key=SECRET_ACCESS_KEY --endpoint=mini:9000 --prefix=kopia/$NAMESPACE/

**Comment by lrstanley** [comment]
Running into the exact same issue. I could easily fix manually, but I'd imagine this should be automatic?

**Comment by adamcharnock** [comment]
Just ran into this too. Existing cluster & velero install, but with a newly added namespace.

The above commands resolved the issue
