### ISSUE TITLE
Configurable password per backup location to enhance security with Kopia encryption

### ISSUE THREAD

**Issue by mpryc** [vmware-tanzu/velero#8137]
**Describe the problem/challenge you have**

By default Kopia uses [AES256-GCM-HMAC-SHA256 encryption](https://kopia.io/docs/advanced/encryption/) to secure and authenticate the contents of its repositories. This encryption is applied at the repository level and is protected by the password provided during repository creation..

Currently Kopia does not allow to disable encryption, which is stated by Kopia creator [here](https://kopia.discourse.group/t/is-there-any-way-to-disable-encryption/807/2)

On the other hand, Velero utilizes a static password defined in the [keys.go](https://github.com/vmware-tanzu/velero/blob/f63b71448324cf29a5366d365a1ceea900150f23/pkg/repository/keys/keys.go#) file. This static password approach undermines the encryption provided by Kopia, potentially compromising the security and effectiveness of the encryption mechanism.

The inability to disable encryption, combined with the use of a static password, results in unnecessary CPU and memory usage for encryption.

**Describe the solution you'd like**
Introduce per `BackupStorageLocation`  configuration option, possibly via `Secret` that can be used as Kopia repository encyrption password.

If this configuration is not provided, the current static password defined in the [keys.go](https://github.com/vmware-tanzu/velero/blob/f63b71448324cf29a5366d365a1ceea900150f23/pkg/repository/keys/keys.go#), to preserve current behavior. 

**Anything else you would like to add:**
1. The ask here is *not* to provide global configuration for such password, but per BSL, so different Kopia Repositories may utilize different passwords provided by the users.
2. Does this needs to be also consumed in other then `BackupStorageLocation` objects?

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by Lyndon-Li** [comment]
Dup with #5443.
