### ISSUE TITLE
Support previewing diffs of backup resources vs current resources

### ISSUE THREAD

**Issue by lwabish** [vmware-tanzu/velero#8148]
**Describe the problem/challenge you have**

Is it possible to offer a command for users to compare  the diffs between backuped resources and current resources. With the help of this command we can better understand what to restore to minimize the risk.

maybe something like this:
```bash
> velero backup diff backup-XXX

Deleted Resouces:
...

Modified Resources:
...
```

**Anything else you would like to add:**

Maybe the diff feature of argocd is a good example.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by blackpiglet** [comment]
IMO, this is a duplicate of #448.

**Comment by lwabish** [comment]
> IMO, this is a duplicate of #448.

Yeah, same problem but different approach. 
I'll keep an eye on that issue.
