### ISSUE TITLE
velero-helper binary not included in release artifacts

### ISSUE THREAD

**Issue by einheber-seed** [vmware-tanzu/velero#8153]
**What steps did you take and what happened:**

Downloaded https://github.com/vmware-tanzu/velero/releases/download/v1.14.1/velero-v1.14.1-linux-amd64.tar.gz

> % tar -tvf velero-v1.14.1-linux-amd64.tar.gz 
> -rw-r--r--  0 root   root    10255 Aug 21 23:46 velero-v1.14.1-linux-amd64/LICENSE
> -rw-r--r--  0 root   root     2599 Aug 21 23:46 velero-v1.14.1-linux-amd64/examples/minio/00-minio-deployment.yaml
> -rw-r--r--  0 root   root      521 Aug 21 23:46 velero-v1.14.1-linux-amd64/examples/nginx-app/README.md
> -rw-r--r--  0 root   root     1262 Aug 21 23:46 velero-v1.14.1-linux-amd64/examples/nginx-app/base.yaml
> -rw-r--r--  0 root   root     2375 Aug 21 23:46 velero-v1.14.1-linux-amd64/examples/nginx-app/with-pv.yaml
> -rwxr-xr-x  0 root   root 101412456 Aug 26 01:28 velero-v1.14.1-linux-amd64/velero

**What did you expect to happen:**

Archive should contain both velero and velero-helper

**Comment by Lyndon-Li** [comment]
It is not required. `velero-helper` is an internal binary used by velero server, not a client tool

**Comment by einheber-seed** [comment]
Are you saying this distribution doesn't contain the server?  The container at docker.io/velero/velero contains both velero and velero-helper.  When working with snapshots, it's attempting to run /velero-helper pause.

**Comment by ywk253100** [comment]
@einheber-seed The Github release page only contains the Velero CLI binary (although the CLI and server are contained in the same binary), the server stuff are all delivered as docker images in Dockerhub.
