### ISSUE TITLE
Missed kopia backup errors in log

### ISSUE THREAD

**Issue by ruslansalikhov** [vmware-tanzu/velero#8154]
**What steps did you take and what happened:**

I have an application which created lock files in storage (which cannot be read by other processes). When I try to backup this PV, backup partially failes, in backup description I see next that my volume is failed:

```
Pod Volume Backups - kopia:
    Completed:
      ....
    Failed:
      namespace/app-0: volume-pvc

```

and in logs I just see generic error, and nothing else (nothing useful, just other info messages)

```
time="2024-08-27T06:57:23Z" level=error msg="pod volume backup failed: data path backup canceled: PVB is canceled" backup=velero/backup logSource="pkg/podvolume/backupper.go:328"
```

root cause I was able to find in output of node agent logs

```
time="2024-08-27T06:56:53Z" level=error msg="Error when processing version/db/dbex.lck: permission denied" backup=velero/backup controller=podvolumebackup logSource="pkg/uploader/kopia/progress.go:86" parentSnapshot=15d0371107957fcfb4510acab5858cd3 path="/host_pods/6209a030-a23b-4930-87f8-e4845146c8b2/volumes/kubernetes.io~csi/pvc-3568115c-540d-4251-87c8-089469fa08ef/mount" podvolumebackup=velero/..... realSource=
```

**What did you expect to happen:**

I expected that details will be stored in backup logs (available via velero backup logs command). Otherwise it is difficult to find correct node agent and analyze whole output (especially if it was restarted)

**Environment:**

- Velero version v1.14.0 and v1.14.1

**Comment by Lyndon-Li** [comment]
It is the designed behavior that Velero server and node-agent hold their log separately. However, you should find the cause from the PVB CR which is a formal place in terms of UX, comparing to the logs.
