### ISSUE TITLE
--default-repo-maintain-frequency is not working even with changed value

### ISSUE THREAD

**Issue by dharanui** [vmware-tanzu/velero#8156]
velero version 1.14.1
helm version 7.0.0
setting the defaultRepoMaintailfrequency which is currently one hour to 6h is not coming into effect and still the jobs are spinning up every hour.

Datauploads are failing after almost an hour with error message saying "token expired" we suspect it is due to the maintainence job?

**Comment by ywk253100** [comment]
Could you check the `BackupRepository` CR to make sure the maintain frequency is configured correctly or not?
```
kubectl -n velero get backuprepository <name> -o yaml
```

**Comment by dharanui** [comment]
yes it did not reflect there by itself..had to delete them and restart velero.

But token expired issue is still not getting resolved

**Comment by ywk253100** [comment]
@dharanui Let's use https://github.com/vmware-tanzu/velero/issues/8173 to track the token expired issue.

So the repo maintain frequency issue is resolved, right? I'm closing this issue, feel free to reopen it.
