### ISSUE TITLE
Velero is not backing up PVC data from Node's local File system

### ISSUE THREAD

**Issue by umarfarooq-git** [vmware-tanzu/velero#8161]
**What steps did you take and what happened:**
Tried to take backup of PV and PVC using Velero but PVC data is not getting copied. PV and PVC created by Rancher local-path provioner.

**What did you expect to happen:**
I want the Velero backup should copy the pod's volume as well. Rancher local-path provioner creates volume at FS node. Goal is to restore these volumes on node's FS.

In General, It is required to prepare a complete K8S cluster backup. ETCD for overall cluster and Velero for stateful applications.

**The following information will help us better understand what's going on**:
I have a K8S cluster consisting of one master . Ansible-AWX is deployed in the cluster using HELM which have following details.

![image](https://github.com/user-attachments/assets/4e09a916-d306-44e0-8fec-bc1d9f73e50b)
 Provisioner is storing volums at /opt/local-path-provisioner/. PV and PVC details are below,
![image](https://github.com/user-attachments/assets/de68ab99-0695-4197-bffd-ad4d61570b1e)

Velero backed by Minio server is deployed in K8S cluster like below and Velero is using Kopia.
```
velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.6.1 \
    --bucket k8s \
    --secret-file ./credentials-velero \
    --use-node-agent \
    --use-volume-snapshots=false \
    --backup-location-config region=minio,s3ForcePathStyle=true,s3Url=minio-server
```
Then took the backup like below.
```
velero backup create 14-backup \
    --include-namespaces awx \
    --include-resources pv,pvc,pod \
    --selector app.kubernetes.io/instance=postgres-15-awx-demo \
    --snapshot-volumes=false \
	--default-volumes-to-fs-backup \
    --wait
``` 
It completed successfully, But It doesn't contain any volume for the pod.
![image](https://github.com/user-attachments/assets/8b854a32-a428-4970-8706-8b83ca5724b9)

I have latest velero version: Version: v1.14.0
There is nothing importnat in logs. kubectl logs deployment/velero -n velero
![image](https://github.com/user-attachments/assets/7b3472ec-2441-45f9-a260-7ff03becce7e)

**Anything else you would like to add:**
I believe, I am missing something. But I read DOCS there is not any more info related to this. 
OR
Is it reaaly possible to backup a PVC being used by postgres, along with its data.

**Comment by ywk253100** [comment]
Velero doesn't support `hostPath` volumes: https://velero.io/docs/v1.14/file-system-backup/#limitations
Make sure you don't use the `hostPath` volumes in order to work with Velero

**Comment by umarfarooq-git** [comment]
Yes, I got it. That's the limiation of Restic or Kopia to backup from local file system.
