### ISSUE TITLE
velero-plugin-for-aws:v1.10.0 + IBM s3 storage = api error XAmzContentSHA256Mismatch

### ISSUE THREAD

**Issue by contributorr** [vmware-tanzu/velero#8203]
**What steps did you take and what happened:**
I upgraded helm chart 6.0.0 (velero 1.13.0, velero-plugin-for-aws:v1.9.0) to helm chart 7.2.1 (velero 1.14.1, velero-plugin-for-aws:v1.10.0) and backups started failing.

level=error msg="backup failed" backuprequest=velero-system/<XXX> controller=backup error="rpc error: code = Unknown desc = error putting object backups/<XXX>/velero-backup.json: operation error S3: PutObject, https response error StatusCode: 400, RequestID: <XXX>, HostID: <XXX>, api error XAmzContentSHA256Mismatch: The provided 'x-amz-content-sha256' header does not match what was computed." logSource="pkg/controller/backup_controller.go:287"

**What did you expect to happen:**
Backups completing as usual.

**Anything else you would like to add:**
I tried a workaround with configuration.backupStorageLocation.config.checksumAlgorithm: "" and it seems to work. Is there any downside by setting this option?

Once I downgraded helm chart to 6.0.0, velero to 1.13.0 including velero-plugin-for-aws to v1.9.0 - backups started working again. 

It seems like the issue started from velero-plugin-for-aws v1.9.1 due to https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/193

Thank you.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
It seems IBM object store calculates the content-sha256 differently from AWS.
Setting `configuration.backupStorageLocation.config.checksumAlgorithm: ""` is the only way to workaround it.

> Is there any downside by setting this option?
I don't think it's a downside provided the checksum is unreliable.

**Comment by contributorr** [comment]
Thanks
