### ISSUE TITLE
Annotate resource restore status patched to the restored resource

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#8205]
**Describe the problem/challenge you have**

Example usecase:
- A Velero restore a resource _Milk_ without status (where velero will further patch status to *Fresh* from backup)
- A **grocery controller** watches _Milk_ resource and processes the _Milk_ spec containing an expiry date, marking _Milk_ *Expired*
- The Velero restore is successful but the _Milk_ resource's status is already  *Expired*
- The Velero restore patch is performed to update the  _Milk_  resource to  *Fresh*  but **grocery controller** will update status of Milk to  *Expired* again because of **grocery controller**'s watch

**Describe the solution you'd like**

When Velero is configured to restore resource `status` and patch is successful, it would be good to know if status was patched by velero.
This can be helpful to troubleshoot where k8s resource is being watched by another controller and patched status is performed after another controller has already changed the restored resource's status

Without this change it is hard to tell if Velero patched status as *Fresh* or not.

With this change, the resource, if patch is successful will have annotation `velero.io/resource-restore-status-patched` with value of the original status that was patched restored.

If status fail to patch due to a conflicting controller (ie. grocery controller)
`velero.io/resource-restore-status-patched` would be nil
`velero.io/resource-restore-status-failed-to-patch` will have the error message that contains error and also what status was going to be patched.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
> Without this change it is hard to tell if Velero patched status as Fresh or not.

Sorry but I disagree, I believe if the user chooses to patch the status of "Milk" during restore we should assume velero always patches it.  For more confidence, we can add a message in the restore logs.
IMHO it's not necessary to add extra information to the restored object just for debugging corner cases.
