### ISSUE TITLE
spec.config.region for VolumeSnapshotLocation and BackupStorageLocation in velero-plugin-for-microsoft-azure

### ISSUE THREAD

**Issue by hsunwenfang** [vmware-tanzu/velero#8209]
In AWS setting
https://github.com/vmware-tanzu/velero-plugin-for-aws
There are spec.config.region

https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/main/volumesnapshotlocation.md?plain=1#L29
and
https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/main/backupstoragelocation.md?plain=1#L40

But spec.config.region is not in https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure

https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/volumesnapshotlocation.md
and
https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/backupstoragelocation.md

Can we add support for this?
thanks!

**Comment by ywk253100** [comment]
The `ResourceGroup` or `StorageAccount` is assigned the region during the creation, so there is no need to identify them with a region. Could clarify why you need the region in the config?

**Comment by hsunwenfang** [comment]
Thanks @ywk253100 
The goal is to backup pvc to k8s cluster in another region
Where Snapshot / Disk should be created in the target region as well.
[Similar Ask]
https://github.com/vmware-tanzu/velero/discussions/4811

Thanks!

**Comment by anshulahuja98** [comment]
Azure does not provide support to create snapshot in a different region
Snapshots are created in same region as source disk.

**Comment by anshulahuja98** [comment]
On the other hand, the storage account you chose for BSL is created in a specific region and this input is not required.

**Comment by ywk253100** [comment]
@hsunwenfang Closing the issue, feel free to reopen it if you have further questions.
