### ISSUE TITLE
time="2024-09-12T09:56:32Z" level=warning msg="Velero node agent not found; pod volume backups/restores will not work until it's created" logSource="pkg/cmd/server/server.go:567".     

### ISSUE THREAD

**Issue by Srija-ravi** [vmware-tanzu/velero#8212]
**What steps did you take and what happened:**

**What did you expect to happen:**

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Srija-ravi** [comment]
time="2024-09-12T10:08:56Z" level=error msg="Reconciler error" controller=downloadrequest controllerGroup=velero.io controllerKind=DownloadRequest downloadRequest="{\"name\":\"nginx-backup-9ff46c67-0b26-49c9-948e-59b460402f53\",\"namespace\":\"velero\"}" error="unsupported download target kind \"BackupVolumeInfos\"" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/persistence/object_store.go:589" error.function="github.com/vmware-tanzu/velero/pkg/persistence.(*objectBackupStore).GetDownloadURL" logSource="/go/pkg/mod/github.com/bombsimon/logrusr/v3@v3.0.0/logrusr.go:123" name=nginx-backup-9ff46c67-0b26-49c9-948e-59b460402f53 namespace=velero reconcileID="\"c01d7295-c6c2-4601-8118-b8e07c0137d6\""
time="2024-09-12T10:09:26Z" level=info msg="Validating BackupStorageLocation" backup-storage-location=velero/default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:152"

**Comment by Srija-ravi** [comment]
I have created velero and restic deployment files and which were running successfully , but when i do backup i am getting this , 



when i look into restic logs i am getting the above issue , 

ackup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:137"
sravik158@INSML-52DPMD6M crds % velero backup describe nginx-backup          


Name:         nginx-backup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.29.7-eks-2f46c53
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=29+

Phase:  Failed (run `velero backup logs nginx-backup` for more information)


Namespaces:
  Included:  velero
  Excluded:  <none>

Resources:
  Included:        configmaps
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Or label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto
Snapshot Move Data:          auto
Data Mover:                  velero

TTL:  720h0m0s

CSISnapshotTimeout:    0s
ItemOperationTimeout:  0s

Hooks:  <none>

Backup Format Version:  

Started:    <n/a>
Completed:  <n/a>

Expiration:  <nil>

Backup Volumes:
  <error getting backup volume info: Get "https://86F41FBB1702E144292913AFC0BA0B3C.gr7.us-west-2.eks.amazonaws.com/apis/velero.io/v1/namespaces/velero/downloadrequests/nginx-backup-95cdb9cf-f121-422d-95f1-9224e973c435": context deadline exceeded>

**Comment by Srija-ravi** [comment]
sravik158@INSML-52DPMD6M crds % kg pods -n velero
NAME                                          READY   STATUS    RESTARTS      AGE
lab-main-d-aor-restic-ews1-w94hf              1/1     Running   1 (11m ago)   18m
lab-main-d-aor-velero-ews1-56876984d7-4cmmd   2/2     Running   1 (11m ago)   18m
lab-main-d-aor-velero-ngx1-6bd569b7ff-b2kwn   1/1     Running   0

**Comment by ywk253100** [comment]
Seems your Velero CRDs are out of date according to the error `error="unsupported download target kind "BackupVolumeInfos"`, could you clean up the current Velero installation by running `velero uninstall` and re-install it again? And make sure use the version of Velero CLI with Velero server.
