### ISSUE TITLE
Option support for maintenance Job ttlafterfinished

### ISSUE THREAD

**Issue by msfrucht** [vmware-tanzu/velero#8273]
**Describe the problem/challenge you have**
Even with the number of maintenance jobs decreased using existing options to only keep 1 per Job our environments have a significant number of maintenance jobs due to hundreds of namespaces with kopia backups. And still want to keep them around for a certain period of time in case of failure.

**Describe the solution you'd like**
Kubernetes 1.23 added to the Job object the field .spec.ttlSecondsAfterFinished

This is used to automatically cleanup Job objects after finishing. An option to set this after finishing would keep our environment cleaner while still giving a chance review existing maintenance job results and resource usage.

I am aware the minimum version of Kubernetes is 1.18 as of Velero 1.14. And as a result, cannot be implemented until the minimum version of Kubernetes is increased to the appropriate level. This is not a high priority items. 

**Anything else you would like to add:**
Existing maintenance job log collection, cleanup, and rudimentary analysis can be handled with some basic scripting in a container connected to a CronJob.

**Environment:**

- Velero version (use `velero version`): 1.14
- Kubernetes version (use `kubectl version`): 1.29
- Kubernetes installer & version: v1.27.10+c79e5e2
- Cloud provider or hardware configuration: OpenShift
- OS (e.g. from `/etc/os-release`): Red Hat Enterprise Linux 8.6 (Ootpa)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by Lyndon-Li** [comment]
dup with #7923. In future, we will remove the preserved maintenance jobs and use another way to preserve the maintenance results and logs for troubleshooting. Or in another word, we will delete the maintenance job once it completes.

**Comment by ywk253100** [comment]
Closing this issue as it's a dup, let's use #7923 to track
