### ISSUE TITLE
Velero CRDs do not have `subresources.status`

### ISSUE THREAD

**Issue by mateusoliveira43** [vmware-tanzu/velero#8285]
**What steps did you take and what happened:**

When writing code around Velero CRDs I noticed that I can not use `controller-runtime` `StatusClient` with them. I get the following error:

```go
k8sClient.Status().Update(ctx, veleroBackup)
// backups.velero.io "name..." not found error
```

**What did you expect to happen:**

Developers are able to use `controller-runtime` `StatusClient` with Velero CRDs.

**Anything else you would like to add:**

Issue about similar problem that  Velero itself is facing https://github.com/vmware-tanzu/velero/issues/6016

To fix the problem, just need to add the comment `+kubebuilder:subresource:status` in CRD generation code. Documentation reference: https://book.kubebuilder.io/reference/generating-crd#status

🚨 This change, without other changes, may break Velero, as with it, it does not allow Spec and Status change together. But since it is a anti-pattern, it should be avoided.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
This is by design. 
Because the backup sync controller syncs the backup CRs (both the backup spec and status) from the backup store to the cluster, this is easier to create the CRs (both the spec and status) in one call without enabling the subresource.

**Comment by kaovilai** [comment]
See also: https://github.com/vmware-tanzu/velero/pull/4972
