### ISSUE TITLE
pkg/repository/config/aws.go: GetAWSBucketRegion: missing region hint

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#8296]
**What steps did you take and what happened:**

Clone of _regression: aws-sdk-go-v2 bump removed region hint breaking GetBucketRegion #8022_ which fixed aws-plugin only.
This issue scope is velero repo pkg/repository/config/aws.go: GetAWSBucketRegion

Without fixing, you will encounter following when creating FSB/Velero Built-In Data Mover backup
```
Errors:
  Velero:    name: /postgresql-1-9xl5g message: /Error backing up item error: /failed to wait BackupRepository, errored early: backup repository is not ready: error to get identifier for repo django-ts-dpa-1-kopia-qg56w: failed to detect the region via bucket: oadp98581bxgnc: operation error S3: HeadBucket, resolve auth scheme: resolve endpoint: endpoint rule error, Invalid region: region was not a valid DNS name. 
```

discovered via https://issues.redhat.com/browse/OADP-5029
**What did you expect to happen:**

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by reasonerjt** [comment]
setting the target to v1.15.1 per discussion under the PR:
https://github.com/vmware-tanzu/velero/pull/8297#issuecomment-2426731983
