### ISSUE TITLE
Backup: Add annotations via client

### ISSUE THREAD

**Issue by alromeros** [vmware-tanzu/velero#8350]
**Describe the problem/challenge you have**

Currently, there is no way to specify annotations when creating a backup via the velero client. This limitation can be challenging particularly when developing additional behavior in third-party plugins. While we can use labels to specify some functionality, annotations seem more appropriate.

**Describe the solution you'd like**

It would be ideal to introduce a --annotations flag to the create command, similarly to the existing --labels flag. This would allow users to specify key-value pairs for annotations directly at the time of backup creation.

**Anything else you would like to add:**

I'm open to work on this feature but I'd like to know if the maintainers are ok with this idea and if they think adding annotations to the backup (or even restore) objects is something desirable.

Thanks!

**Comment by kaovilai** [comment]
Would this override current backup label or annotations or be additional annotations?

**Comment by alromeros** [comment]
> Would this override current backup label or annotations or be additional annotations?

The idea is mainly to have this option during backup creation, something like `velero backup create --annotations=...`..If there's a plan to add annotations after creation I guess we could make it so it doesn't override the current ones.

**Comment by kaovilai** [comment]
ok so this is annotation of backups.velero.io object, not things in the backup.

**Comment by sseago** [comment]
@kaovilai Right -- this is a proposal to add a missing feature to the CLI -- currently if you want annotations on your backup CR you have to create the CR manually. Basically the  same functionality as `--labels` (not `--labelSelector`) but for annotations instead of labels.

**Comment by kaovilai** [comment]
FWIW I am ok with this :D

**Comment by reasonerjt** [comment]
I'm not very against this, but as for

> This limitation can be challenging particularly when developing additional behavior in third-party plugins. While we can use labels to specify some functionality, annotations seem more appropriate.

Could you give a more concrete example?

**Comment by alromeros** [comment]
> @alromeros Thank you for proposing this idea.
> 
> I'm not very against it, but as for
> 
> > This limitation can be challenging particularly when developing additional behavior in third-party plugins. While we can use labels to specify some functionality, annotations seem more appropriate.
> 
> Could you give a more concrete example?

Sure, for example, I have this PR in the Velero plugin for Kubevirt where we want to allow users to optionally skip consistency-related check if they are only interested in backing up for metadata purposes: https://github.com/kubevirt/kubevirt-velero-plugin/pull/285. This makes way more sense as an annotation, but we are using a label due to difficulties with the client.
