### ISSUE TITLE
EKS: backups fail when running on Bottlerocket nodes

### ISSUE THREAD

**Issue by pedro-m-andrade-alb** [vmware-tanzu/velero#8360]
**What steps did you take and what happened:**

Cluster backups fail when the nodes use a Bottlerocket AMI, but not when they use Amazon Linux 2 AMI.

```
velero create backup backup-test --snapshot-move-data --exclude-namespaces actions-runner,actions-runner-controller,cert-manager,default,kube-node-lease,kube-public,kube-system
```

**What did you expect to happen:**
Backups finish without errors.

**The following information will help us better understand what's going on**:
We have some clusters running with Bottlerocket nodes and others with Amazon Linux 2 nodes. All backup tests in the Bottlerocket clusters failed, using the same command and configuration as the AL2 clusters, where the backups finished without errors.

Furthermore, we changed some AL2 clusters into Bottlerocket and the backups started to fail. 

Dataupload error:
`error to initialize data path: error to boost backup repository connection default-ffwk-kopia: error to connect backup repo: error to connect repo with storage: error to connect to repository: repository not initialized in the provided storage`

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 
[bundle-2024-10-29-10-23-43.tar.gz](https://github.com/user-attachments/files/17555414/bundle-2024-10-29-10-23-43.tar.gz)

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
Client:
        Version: v1.14.1
        Git commit: 8afe3cea8b7058f7baaf447b9fb407312c40d2da
Server:
        Version: v1.14.1
- Velero features (use `velero client config get features`): 
features: <NOT SET>

- Kubernetes version (use `kubectl version`):
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.8-eks-a737599

- Cloud provider or hardware configuration:
AWS EKS

- OS (e.g. from `/etc/os-release`):
NAME=Bottlerocket
ID=bottlerocket
VERSION="1.25.0 (aws-k8s-1.29)"
PRETTY_NAME="Bottlerocket OS 1.25.0 (aws-k8s-1.29)"
VARIANT_ID=aws-k8s-1.29
VERSION_ID=1.25.0
BUILD_ID=388e1050
HOME_URL="https://github.com/bottlerocket-os/bottlerocket"
SUPPORT_URL="https://github.com/bottlerocket-os/bottlerocket/discussions"
BUG_REPORT_URL="https://github.com/bottlerocket-os/bottlerocket/issues"

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
The backups failed because:
`error to initialize data path: error to boost backup repository connection default-ffwk-kopia: error to connect backup repo: error to connect repo with storage: error to connect to repository: repository not initialized in the provided storage`

Looks like something wrong happens to the object store and the repo data was not there.
You can delete the `backuprepository` CRs and retry the backup.

**Comment by pedro-m-andrade-alb** [comment]
We retried the backup with Bottlerocket nodes after deleting the `backuprepository`, and it failed with the error:
`data path backup failed: Failed to run kopia backup: Failed to upload the kopia snapshot for si default@default:snapshot-data-upload-download/kopia/ffwk/grafana-pvc: permission denied`

This test was done again in the same cluster but with AL2 nodes instead, and the backup finished successfully.

**Comment by kaovilai** [comment]
Probably related to https://github.com/vmware-tanzu/velero/issues/8249.

Please see fixes there.

**Comment by kaovilai** [comment]
> Bottlerocket has an always-enabled, enforced, restrictive [SELinux](https://selinuxproject.org/page/Main_Page) policy for the mutable filesystem that helps prevent containers from executing dangerous operations, even when running as root.

[src](https://bottlerocket.dev/#:~:text=Bottlerocket%20has%20an%20always%2Denabled%2C%20enforced%2C%20restrictive%20SELinux%20policy%20for%20the%20mutable%20filesystem%20that%20helps%20prevent%20containers%20from%20executing%20dangerous%20operations%2C%20even%20when%20running%20as%20root.)

**Comment by sseago** [comment]
@kaovilai this is on 1.14 not 1.15, so I don't think the backupPVC issue is relevant. I think in this case, the `--privileged-node-agent` install flag may be all that's needed.

**Comment by pedro-m-andrade-alb** [comment]
Adding the `--privileged-node-agent` flag fixed the problem, and the backups now work with Bottlerocket nodes. Thank you all for the help. The issue can be closed.
