### ISSUE TITLE
Combine e2e-test-kind and crd-verify-kind workflow files.

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#8384]
can be a separate PR, but this file and `.github/workflows/e2e-test-kind.yaml` have a lot of duplication 

It would be better to merge then together?

_Originally posted by @mateusoliveira43 in https://github.com/vmware-tanzu/velero/pull/8375#discussion_r1834457700_
            

we would copy crd-check job over to the e2e-test-kind workflow file.

**Comment by blackpiglet** [comment]
I will create a PR to fix this.
Thanks for spotting this issue. @mateusoliveira43
