### ISSUE TITLE
Add E2E cases for skipping emptyDir volumes in VolumePolicy logic

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#8386]
**Describe the problem/challenge you have**

Should add new E2E automation test cases to verify VolumePolicy should skip getting PV for PVC like emptyDir.
The original issue is #7929.

**Describe the solution you'd like**

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
If there's a UT this is probably not needed.

**Comment by blackpiglet** [comment]
https://github.com/vmware-tanzu/velero/blob/v1.15.0/internal/volumehelper/volume_policy_helper_test.go#L555-L580
There was already a UT case covered this scenario.

**Comment by blackpiglet** [comment]
Per previous comments, close as `won't fix`.
