### ISSUE TITLE
Add E2E cases for supporting node selector for repo maintenance job

### ISSUE THREAD

**Issue by blackpiglet** [vmware-tanzu/velero#8389]
**Describe the problem/challenge you have**

Should add new E2E automation test cases to verify the repository maintenance Jobs supporting node selection.

The feature's issue is #7758.
The feature's design is https://github.com/vmware-tanzu/velero/blob/main/design/Implemented/repo_maintenance_job_config.md.

**Describe the solution you'd like**

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by reasonerjt** [comment]
This is probably also covered by UT.

**Comment by blackpiglet** [comment]
The UT cases are https://github.com/vmware-tanzu/velero/blob/1d4f1475975b5107ec35f4d19ff17f7d1fcb3edf/pkg/repository/maintenance_test.go#L266.

**Comment by blackpiglet** [comment]
Per previous comments, close as `won't fix`.
