### ISSUE TITLE
Velero build for Windows

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#8415]
Build Velero image for Windows
Build multiple platform manifest to include Linux image and Windows image

Links to #8289

**Comment by kaovilai** [comment]
windows also has arm64 now. do we want to add to goreleaser?

**Comment by Lyndon-Li** [comment]
> windows also has arm64 now. do we want to add to goreleaser?

This is not with high priority. Windows' pace on ARM is not stablized yet, we can do this when we see the full vision where Windows server, Windows virtualization and container also support ARM. Then we can deliver the client and container image together.
