### ISSUE TITLE
Velero server deployment on Windows

### ISSUE THREAD

**Issue by Lyndon-Li** [vmware-tanzu/velero#8416]
Deploy and run Velero server deployment on Windows node

Links to #8289

**Comment by reasonerjt** [comment]
@Lyndon-Li Let's write a design to clarify how we plan to handle the manifests to deploy the pod on Windows nodes.

**Comment by Lyndon-Li** [comment]
> @Lyndon-Li Let's write a design to clarify how we plan to handle the manifests to deploy the pod on Windows nodes.

OK, a separate issue for the overall design of Windows support is opened, #8429

**Comment by Lyndon-Li** [comment]
As discussed, we don't need a design for Velero deployment considering the scale of the changes.
The primary points of changes have been included in the description of PR #8504.
