### ISSUE TITLE
Data upload is been canceled

### ISSUE THREAD

**Issue by SCLogo** [vmware-tanzu/velero#8488]
**What steps did you take and what happened:**
We have velero 1.15.0 with kopia. Data mover enabled. Back is aws. Sometimes I see dataupload is been cancelled

```
apiVersion: velero.io/v2alpha1
kind: DataUpload
metadata:
  creationTimestamp: "2024-12-05T06:09:05Z"
  generateName: velero-hourly-20241205060051-
  generation: 4
  labels:
    velero.io/accepted-by: i-048b5b25b16cae984
    velero.io/async-operation-id: du-3fe2dd8f-13e4-48e0-86c9-69d3dfaad582.13499861-b33e-4c339bd32
    velero.io/backup-name: velero-hourly-20241205060051
    velero.io/backup-uid: 3fe2dd8f-13e4-48e0-86c9-69d3dfaad582
    velero.io/pvc-uid: 13499861-b33e-4c38-ac84-f3a1f0368cb1
  name: velero-hourly-20241205060051-x6nd7
  namespace: velero
  ownerReferences:
  - apiVersion: velero.io/v1
    controller: true
    kind: Backup
    name: velero-hourly-20241205060051
    uid: 3fe2dd8f-13e4-48e0-86c9-69d3dfaad582
  resourceVersion: "373513216"
  uid: 223ae86b-c492-409e-89b5-71cddb65091b
spec:
  backupStorageLocation: default
  cancel: true
  csiSnapshot:
    snapshotClass: backup
    storageClass: storageclass
    volumeSnapshot: pod_to_be_backed
  dataMoverConfig:
    ParallelFilesUpload: "10"
  datamover: velero
  operationTimeout: 10m0s
  snapshotType: CSI
  sourceNamespace: test
  sourcePVC: sourcens
  status:
  completionTimestamp: "2024-12-05T06:09:25Z"
  message: Dataupload is in Accepted status during the node-agent starting, mark it
    as cancel
  phase: Canceled
  progress: {}
  startTimestamp: "2024-12-05T06:09:25Z"
```

**What did you expect to happen:**
able to do a backup without issues
**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

**Environment:**

- Velero version (use `velero version`):  1.15.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):

```
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.30.4
```
- Kubernetes installer & version: kops 1.30.0
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`): ubuntu

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
This is the expected behavior that the `DataUpload` is canceled when node agent restarting

**Comment by SCLogo** [comment]
I did not see any restart on that time

**Comment by SCLogo** [comment]
any of the node agents restart / come up? or the node agent which accepted the upload ?

**Comment by ywk253100** [comment]
Th node agent which accepted the upload

**Comment by dharanui** [comment]
Same issue observed with any node-agent restart. Not only the one which accepted du.

**Comment by ywk253100** [comment]
@dharanui Sorry for the mistake. The `DataUpload` is canceled if any node-agent restart.
Maybe we can do some improvement for this part. @Lyndon-Li

**Comment by Lyndon-Li** [comment]
> @dharanui Sorry for the mistake. The `DataUpload` is canceled if any node-agent restart. Maybe we can do some improvement for this part. @Lyndon-Li

Opened a separate issue #8534 to track this requirement

**Comment by ywk253100** [comment]
I'm closing this one, let's track the effort in #8534, feel free to reopen it if you have any further questions.
