### ISSUE TITLE
push.yml: Upgrade from google-github-actions/setup-gcloud@v0

### ISSUE THREAD

**Issue by kaovilai** [vmware-tanzu/velero#8523]
https://github.com/vmware-tanzu/velero-plugin-for-aws/actions/runs/12388809515/job/34580589641#step:5:10

More fixes needed by upping from [unsupported](https://github.com/vmware-tanzu/velero-plugin-for-aws/actions/runs/12388809515/job/34580589641) gcloud auth
```
Error: The v0 series of google-github-actions/setup-gcloud is no longer maintained. It will not receive updates, improvements, or security patches. Please upgrade to the latest supported versions: 
```

_Originally posted by @kaovilai in https://github.com/vmware-tanzu/velero/issues/8522#issuecomment-2550877507_

**Comment by reasonerjt** [comment]
This has been fixed by https://github.com/vmware-tanzu/velero-plugin-for-aws/pull/237/files

Closing.
