### ISSUE TITLE
defaultRepoMaintainFrequency not being applied in official helm chart 

### ISSUE THREAD

**Issue by 2fst4u** [vmware-tanzu/velero#8543]
**What steps did you take and what happened:**
I noticed the repo maintenance jobs were happening every hour, and after a while the free usage on my B2 bucket got reached which prevented the jobs form working. This led me to investigate.

I set the `configuration.defaultRepoMaintainFrequency` to "24h" and it accepted the value but doesn't seem to be working. When I run `kubectl get deployment velero -n velero -o yaml | grep -A5 args:` I get
```
      - args:
        - server
        - --uploader-type=kopia
        - --default-repo-maintain-frequency=24h
        - --features=EnableCSI
        - --keep-latest-maintenance-jobs=3
```

Which shows it being applied, but the job keeps running every hour.

**What did you expect to happen:**
Job runs only 24 hours.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`
I'm on another device but if this is required I can get it and add it to a comment.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 1.15
- Velero features (use `velero client config get features`): enable CSI 
- Kubernetes version (use `kubectl version`): v1.31.4+k3s1
- Kubernetes installer & version: k3s
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from `/etc/os-release`): Ubuntu 24.04.1

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by Lyndon-Li** [comment]
The Unified Repo defines the policy for maintenance frequency as below:
1. Velero queries the frequency from the repo through Unified Repo interface, if a valid value is returned, Velero uses the value
2. Otherwise, Velero gets the frequency from users configuration, and use the value

For Kopia repo, it returns 1 hour for the Unified Repo interface, so 1 hour is always used.

Maintenance is a critical operation to the repo, and the repo knows well about how and when to go to the maintenance, this is why the policy goes like that.

**Comment by 2fst4u** [comment]
Where is this "unified repo interface"? I don't understand.

I understand it's important but I don't really get what it's actually doing and as mentioned, I'm hitting my free tier limit so it's failing anyway. Why can't I change this value?

**Comment by Lyndon-Li** [comment]
See [this design](https://github.com/vmware-tanzu/velero/blob/main/design/Implemented/unified-repo-and-kopia-integration/unified-repo-and-kopia-integration.md) for more details of Unified Repo and repo maintenance.

**Comment by 2fst4u** [comment]
Ok but I don't follow why this means I can't change the value. Why is the value even in the chart if it does nothing?

And ultimately, how can I resolve my issue of it being too frequent for my environment?

**Comment by Lyndon-Li** [comment]
> I'm hitting my free tier limit so it's failing anyway

Actually, I don't understand why changing the default maintenance frequency could solve your current problem --- one of the functionalities from repo maintenance is to delete the unused data and free your space, if you don't run maintenance, the unused data never gets deleted and your repo's performance gets downgrade and even denies of service.

**Comment by 2fst4u** [comment]
I ran two test backups yesterday, then woke up today and the maintenance jobs have used my class C access limit and haven't made any changes. Are you saying the jobs should do nothing if there's nothing to change? It worked so frequently that the bucket is now denying access for the day.

**Comment by Lyndon-Li** [comment]
> Why is the value even in the chart if it does nothing?

As indicated by its name `defaultMaintenanceFrequency`, it is used by users to set a frequency when the repo doesn't give any indication, or when the repo doesn't implement the `DefaultMaintenanceFrequency` method of Unified Repo interface.

**Comment by 2fst4u** [comment]
> > Why is the value even in the chart if it does nothing?
> 
> As indicated by its name `defaultMaintenanceFrequency`, it is used by users to set a frequency when the repo doesn't give any indication, or when the repo doesn't implement the `DefaultMaintenanceFrequency` method of Unified Repo interface.

Sorry these terms are too over my head for me to understand what it actually means for me.

**Comment by Lyndon-Li** [comment]
> Are you saying the jobs should do nothing if there's nothing to change?

Yes, the maintenance needs to reads/writes data to your bucket until it finish its due work, then if nothing is further changed in the repo, the following maintenance will do nothing, no matter how frequent they run.

> the maintenance jobs have used my class C access limit

This means in order for maintenance to finish its due work, it has to use that many access. You must let it finish it, otherwise, the next maintenance still does the same thing.
However, if you disable maintenance forever, your repo will get infunctional gradually.

So instead of changing the frequency/disable it, you need to change your bucket limit.

**Comment by 2fst4u** [comment]
So is it possible the read access is using up the access limit just checking what needs to be done?

**Comment by Lyndon-Li** [comment]
> So is it possible the read access is using up the access limit just checking what needs to be done?

It is possible to run out it by the specific operations in the repo maintenance, the repo maintenance is a heavy operation in terms of data read/write.
However, it is hard to define what is `just checking what needs to be done`, from users perspective you may see no change to the repo data, but it actually done lots of checks.

**Comment by 2fst4u** [comment]
Fair enough. I guess that's my lack of understanding at fault. Thanks.
