### ISSUE TITLE
Add --default-volume-snapshot-locations flag to `ark server` command

### ISSUE THREAD

**Issue by skriss** [vmware-tanzu/velero#864]
example --default-volume-snapshot-locations aws:aws-default,rook:rook-default,...

- add the flag to the cobra command
- add a field to the server struct to store the value
- flag validation: ensure there's exactly one default location for each volume provider
    - ensure each provider exists, and each location exists
    - list all VolumeSnapshotLocations, get a unique list of providers, ensure there's one default per provider
- pass the list of default VSLs into each controller that needs it

**Comment by skriss** [comment]
@wwitzel3 you doing OK here? Haven't heard from you in awhile :)

**Comment by wwitzel3** [comment]
@skriss Yep, I've been trying to workout a good way to write tests here and haven't come up with any. I will squash things down and get a PR up shortly so it can start getting reviewed.

**Comment by wwitzel3** [comment]
I was reviewing #873 and it looks like that is doing some of the things I assumed this was doing. Specifically the `pass the list of default VSLs into each controller that needs it`.

It seems this is doing that for the `BackupController`. Should I rebase of that PR? @skriss is this right?

**Comment by carlisia** [comment]
Wait... I was doing this as part of my PR. Oh gosh. @wwitzel3 if you have started this, I have code that could be useful, particularly https://github.com/spf13/pflag/issues/182.

**Comment by wwitzel3** [comment]
@carlisia No, you're good. I will get my PR up that binds and validates the default volume snapshot locations and then follow up with PRs for the other controllers. This works out because I just accidentally torched my controller changes in commit clean up attempt anyway.

**Comment by skriss** [comment]
lol. @wwitzel3 I'd say don't bother with PRs for the other controllers, it can just be done inline with #807 #805 #808
