### ISSUE TITLE
ark failing to start

### ISSUE THREAD

**Issue by DP19** [vmware-tanzu/velero#881]
**What steps did you take and what happened:**
I installed ark in amazon's EKS and was able to migrate one of our clusters, however now all backups are failing so i went ahead and tried to get it re-installed and now i'm seeing the same errors I saw before.

"An error occurred: unable to retrieve the complete list of server APIs: admissionregistration.k8s.io/v1alpha1: the server could not find the requested resource, batch/v2alpha1: the server could not find the requested resource"

**What did you expect to happen:**
ark to startup

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/ark -n heptio-ark`

time="2018-09-26T20:20:01Z" level=info msg="setting log-level to INFO"
time="2018-09-26T20:20:01Z" level=info msg="Starting Ark server v0.9.6" logSource="pkg/cmd/server/server.go:101"
time="2018-09-26T20:20:01Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:264" namespace=heptio-ark
time="2018-09-26T20:20:01Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:270" namespace=heptio-ark
An error occurred: unable to retrieve the complete list of server APIs: admissionregistration.k8s.io/v1alpha1: the server could not find the requested resource, batch/v2alpha1: the server could not find the requested resource

**Environment:**

- Ark version (use `ark version`):  0.9.6
- Kubernetes version (use `kubectl version`): v1.10.3
- Kubernetes installer & version:
- Cloud provider or hardware configuration: aws/EKS
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
@DP19 could you please paste/gist the following?
```
kubectl get --raw /
kubectl get --raw /apis
kubectl get --raw /apis/admissionregistration.k8s.io/
kubectl get --raw /apis/admissionregistration.k8s.io/v1alpha1
kubectl get --raw /apis/batch
kubectl get --raw /apis/batch/v2alpha1
```

**Comment by DP19** [comment]
kubectl get --raw /

{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/",
    "/apis/admissionregistration.k8s.io",
    "/apis/admissionregistration.k8s.io/v1alpha1",
    "/apis/admissionregistration.k8s.io/v1beta1",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/apis/apiregistration.k8s.io",
    "/apis/apiregistration.k8s.io/v1",
    "/apis/apiregistration.k8s.io/v1beta1",
    "/apis/apps",
    "/apis/apps/v1",
    "/apis/apps/v1beta1",
    "/apis/apps/v1beta2",
    "/apis/ark.heptio.com",
    "/apis/ark.heptio.com/v1",
    "/apis/authentication.k8s.io",
    "/apis/authentication.k8s.io/v1",
    "/apis/authentication.k8s.io/v1beta1",
    "/apis/authorization.k8s.io",
    "/apis/authorization.k8s.io/v1",
    "/apis/authorization.k8s.io/v1beta1",
    "/apis/autoscaling",
    "/apis/autoscaling/v1",
    "/apis/autoscaling/v2beta1",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/batch/v1beta1",
    "/apis/batch/v2alpha1",
    "/apis/certificates.k8s.io",
    "/apis/certificates.k8s.io/v1beta1",
    "/apis/events.k8s.io",
    "/apis/events.k8s.io/v1beta1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/apis/monitoring.coreos.com",
    "/apis/monitoring.coreos.com/v1",
    "/apis/networking.k8s.io",
    "/apis/networking.k8s.io/v1",
    "/apis/policy",
    "/apis/policy/v1beta1",
    "/apis/rbac.authorization.k8s.io",
    "/apis/rbac.authorization.k8s.io/v1",
    "/apis/rbac.authorization.k8s.io/v1beta1",
    "/apis/storage.k8s.io",
    "/apis/storage.k8s.io/v1",
    "/apis/storage.k8s.io/v1beta1",
    "/healthz",
    "/healthz/autoregister-completion",
    "/healthz/etcd",
    "/healthz/ping",
    "/healthz/poststarthook/apiservice-openapi-controller",
    "/healthz/poststarthook/apiservice-registration-controller",
    "/healthz/poststarthook/apiservice-status-available-controller",
    "/healthz/poststarthook/bootstrap-controller",
    "/healthz/poststarthook/ca-registration",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/healthz/poststarthook/kube-apiserver-autoregistration",
    "/healthz/poststarthook/rbac/bootstrap-roles",
    "/healthz/poststarthook/start-apiextensions-controllers",
    "/healthz/poststarthook/start-apiextensions-informers",
    "/healthz/poststarthook/start-kube-aggregator-informers",
    "/healthz/poststarthook/start-kube-apiserver-informers",
    "/metrics",
    "/openapi/v2",
    "/swagger-2.0.0.json",
    "/swagger-2.0.0.pb-v1",
    "/swagger-2.0.0.pb-v1.gz",
    "/swagger.json",
    "/swaggerapi",
    "/version"
  ]


kubectl get --raw /apis

{"kind":"APIGroupList","apiVersion":"v1","groups":[{"name":"apiregistration.k8s.io","versions":[{"groupVersion":"apiregistration.k8s.io/v1","version":"v1"},{"groupVersion":"apiregistration.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"apiregistration.k8s.io/v1","version":"v1"},"serverAddressByClientCIDRs":null},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":null},{"name":"apps","versions":[{"groupVersion":"apps/v1","version":"v1"},{"groupVersion":"apps/v1beta2","version":"v1beta2"},{"groupVersion":"apps/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"apps/v1","version":"v1"},"serverAddressByClientCIDRs":null},{"name":"events.k8s.io","versions":[{"groupVersion":"events.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"events.k8s.io/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":null},{"name":"authentication.k8s.io","versions":[{"groupVersion":"authentication.k8s.io/v1","version":"v1"},{"groupVersion":"authentication.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"authentication.k8s.io/v1","version":"v1"},"serverAddressByClientCIDRs":null},{"name":"authorization.k8s.io","versions":[{"groupVersion":"authorization.k8s.io/v1","version":"v1"},{"groupVersion":"authorization.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"authorization.k8s.io/v1","version":"v1"},"serverAddressByClientCIDRs":null},{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"},{"groupVersion":"autoscaling/v2beta1","version":"v2beta1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":null},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"},{"groupVersion":"batch/v1beta1","version":"v1beta1"},{"groupVersion":"batch/v2alpha1","version":"v2alpha1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":null},{"name":"certificates.k8s.io","versions":[{"groupVersion":"certificates.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"certificates.k8s.io/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":null},{"name":"networking.k8s.io","versions":[{"groupVersion":"networking.k8s.io/v1","version":"v1"}],"preferredVersion":{"groupVersion":"networking.k8s.io/v1","version":"v1"},"serverAddressByClientCIDRs":null},{"name":"policy","versions":[{"groupVersion":"policy/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"policy/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":null},{"name":"rbac.authorization.k8s.io","versions":[{"groupVersion":"rbac.authorization.k8s.io/v1","version":"v1"},{"groupVersion":"rbac.authorization.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"rbac.authorization.k8s.io/v1","version":"v1"},"serverAddressByClientCIDRs":null},{"name":"storage.k8s.io","versions":[{"groupVersion":"storage.k8s.io/v1","version":"v1"},{"groupVersion":"storage.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"storage.k8s.io/v1","version":"v1"},"serverAddressByClientCIDRs":null},{"name":"admissionregistration.k8s.io","versions":[{"groupVersion":"admissionregistration.k8s.io/v1beta1","version":"v1beta1"},{"groupVersion":"admissionregistration.k8s.io/v1alpha1","version":"v1alpha1"}],"preferredVersion":{"groupVersion":"admissionregistration.k8s.io/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":null},{"name":"apiextensions.k8s.io","versions":[{"groupVersion":"apiextensions.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"apiextensions.k8s.io/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":null},{"name":"ark.heptio.com","versions":[{"groupVersion":"ark.heptio.com/v1","version":"v1"}],"preferredVersion":{"groupVersion":"ark.heptio.com/v1","version":"v1"},"serverAddressByClientCIDRs":null},{"name":"monitoring.coreos.com","versions":[{"groupVersion":"monitoring.coreos.com/v1","version":"v1"}],"preferredVersion":{"groupVersion":"monitoring.coreos.com/v1","version":"v1"},"serverAddressByClientCIDRs":null}]}


kubectl get --raw /apis/admissionregistration.k8s.io/

{"kind":"APIGroup","apiVersion":"v1","name":"admissionregistration.k8s.io","versions":[{"groupVersion":"admissionregistration.k8s.io/v1beta1","version":"v1beta1"},{"groupVersion":"admissionregistration.k8s.io/v1alpha1","version":"v1alpha1"}],"preferredVersion":{"groupVersion":"admissionregistration.k8s.io/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":null}


kubectl get --raw /apis/admissionregistration.k8s.io/v1alpha1

Error from server (NotFound): the server could not find the requested resource


kubectl get --raw /apis/batch

{"kind":"APIGroup","apiVersion":"v1","name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"},{"groupVersion":"batch/v1beta1","version":"v1beta1"},{"groupVersion":"batch/v2alpha1","version":"v2alpha1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":null


kubectl get --raw /apis/batch/v2alpha1

Error from server (NotFound): the server could not find the requested resource

**Comment by ncdc** [comment]
This sounds like an EKS issue. Do you think Ark should ignore Kubernetes apiserver issues such as this, where it says an API exists, but we can't query it?

**Comment by DP19** [comment]
@ncdc After i looked at it more i thought it was an EKS issue as well and opened a ticket with amazon, looks like they may have made some changes since i put ark in our cluster on Friday and today. But yes i do think we should probably ignore these api's (especially the alpha ones) since they may change dramatically and shouldn't really be used a production cluster

**Comment by ncdc** [comment]
What if a beta or GA API has this issue? Should ark pattern-match for alpha and ignore alpha API errors but fail for beta/GA?

@heptio/ark-team would appreciate your input too!

**Comment by DP19** [comment]
So after some back and forth with aws support, I was able to figure out what was happening.

We used ark to migrated one of our clusters out of rancher and into eks. I stood up the new cluster and installed ark then restored the cluster into eks. In the backup .json files within the tar's there were references to apiservices.apiregistration.k8s.io and within that folder it had backed up those two alpha apis that were present in our rancher cluster. It restored these to the new one but they were not active in the eks cluster which caused a lot of issues, not only with ark itself but with other pods depending on getting info from apiservices. I went ahead and was able to delete these references and everything was back to normal.

kubectl delete apiservices v1alpha1.admissionregistration.k8s.io
kubectl delete apiservices v2alpha1.batch

kubectl get --raw /apis/batch

{"kind":"APIGroup","apiVersion":"v1","name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"},{"groupVersion":"batch/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":null}

kubectl get --raw /apis/apiregistration.k8s.io

{"kind":"APIGroup","apiVersion":"v1","name":"apiregistration.k8s.io","versions":[{"groupVersion":"apiregistration.k8s.io/v1","version":"v1"},{"groupVersion":"apiregistration.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"apiregistration.k8s.io/v1","version":"v1"},"serverAddressByClientCIDRs":null}

You may want to consider a better way to handle these restores of this type because this may happen for others.  @ncdc

**Comment by splisson-altair** [comment]
I'm getting a similar error:
$ kubectl logs deployment/ark -n heptio-ark
time="2018-10-10T21:14:04Z" level=info msg="setting log-level to INFO"
time="2018-10-10T21:14:04Z" level=info msg="Starting Ark server v0.9.7" logSource="pkg/cmd/server/server.go:101"
time="2018-10-10T21:14:04Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:264" namespace=heptio-ark
time="2018-10-10T21:14:04Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:270" namespace=heptio-ark
An error occurred: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server has received too many requests and has asked us to try again later

$ kubectl get --raw /apis/metrics.k8s.io/v1beta1
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"metrics.k8s.io/v1beta1","resources":[{"name":"nodes","singularName":"","namespaced":false,"kind":"NodeMetrics","verbs":["get","list"]},{"name":"pods","singularName":"","namespaced":true,"kind":"PodMetrics","verbs":["get","list"]}]}

**Comment by splisson-altair** [comment]
sure, I ll open a separate issue
