### ISSUE TITLE
"Function not implemented" in restic backing up Azure Files volumes

### ISSUE THREAD

**Issue by erjosito** [vmware-tanzu/velero#887]
**What steps did you take and what happened:**
Hi there,

I am using ark 0.9 with AKS 1.11.2 in Azure, and I am trying to back up a PV in Azure Files over restic. I already tested backing up disk-based PVs without restic, no issue there. I did the restic configuration as per the documentation, with a different bucket (blob container) in my storage account. I annotated a pod using a PVC based on Azure Files, but the backup up failed

**What did you expect to happen:**

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/ark -n heptio-ark`
```
time="2018-09-28T09:21:06Z" level=info msg="Starting backup" backup=heptio-ark/nginx-file-backup logSource="pkg/controller/backup_controller.go:339"
time="2018-09-28T09:21:17Z" level=info msg="Initializing restic repository" controller=restic-repository logSource="pkg/controller/restic_repository_controller.go:138" name=nginx-file namespace=heptio-ark
time="2018-09-28T09:24:43Z" level=info msg="Backup completed" backup=heptio-ark/nginx-file-backup logSource="pkg/controller/backup_controller.go:401"
time="2018-09-28T09:24:44Z" level=error msg="backup failed" error="pod volume backup failed: error running restic backup, stderr=error: NodeFromFileInfo: Listxattr: xattr.List access.log : function not implemented\nerror: NodeFromFileInfo: Listxattr: xattr.List error.log : function not implemented\nerror: NodeFromFileInfo: Listxattr: xattr.List hellofromazure.txt : function not implemented\nerror: NodeFromFileInfo: Listxattr:
xattr.List helloworld.txt : function not implemented\nFatal: unable to save snapshot: snapshot is empty\n: exit status 1" key=heptio-ark/nginx-file-backup logSource="pkg/controller/backup_controller.go:280"
```
Output from `k -n heptio-ark logs pod/restic-stj4h`:
```
E0928 09:24:38.705635       1 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 1649; INTERNAL_ERROR
time="2018-09-28T09:24:39Z" level=info msg="Backup starting" backup=heptio-ark/nginx-file-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:167" name=nginx-file-backup-mchvk namespace=heptio-ark
time="2018-09-28T09:24:41Z" level=error msg="Error running command=restic backup --repo=azure:restic:/nginx-file --password-file=/tmp/ark-restic-credentials-nginx-file590027696 --cache-dir=/scratch/.cache/restic . --tag=backup=nginx-file-backup --tag=backup-uid=14915b3c-c2ff-11e8-8dc0-0a58ac1f08b3 --tag=ns=nginx-file --tag=pod=nginx-deployment-5d8578694f-x54st --tag=pod-uid=54e1f828-c2fb-11e8-8dc0-0a58ac1f08b3 --tag=volume=ngi
nx-logs --hostname=ark, stdout=, stderr=error: NodeFromFileInfo: Listxattr: xattr.List access.log : function not implemented\nerror: NodeFromFileInfo: Listxattr: xattr.List error.log : function not implemented\nerror: NodeFromFileInfo: Listxattr: xattr.List hellofromazure.txt : function not implemented\nerror: NodeFromFileInfo: Listxattr: xattr.List helloworld.txt : function not implemented\nFatal: unable to save snapshot: sna
pshot is empty\n" backup=heptio-ark/nginx-file-backup controller=pod-volume-backup error="exit status 1" error.file="pod_volume_backup_controller.go:219" error.function="(*podVolumeBackupController).processBackup" logSource="pkg/controller/pod_volume_backup_controller.go:219" name=nginx-file-backup-mchvk namespace=heptio-ark
```
* `ark backup describe <backupname>` or `kubectl get backup/<backupname> -n heptio-ark -o yaml`

```
Name:         nginx-file-backup
Namespace:    heptio-ark
Labels:       <none>
Annotations:  <none>
Phase:  Failed
Namespaces:
  Included:  *
  Excluded:  <none>
Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto
Label selector:  app=nginxfile
Snapshot PVs:  auto
TTL:  720h0m0s
Hooks:  <none>
Backup Format Version:  1
Started:    2018-09-28 11:21:06 +0200 DST
Completed:  2018-09-28 11:24:43 +0200 DST
Expiration:  2018-10-28 10:21:06 +0100 STD
Validation errors:  <none>
Persistent Volumes: <none included>
Restic Backups (specify --volume-details for more information):
  Failed:  1
```

* `ark backup logs <backupname>`
* `ark restore describe <restorename>` or `kubectl get restore/<restorename> -n heptio-ark -o yaml`
* `ark restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Ark version (use `ark version`):  0.9.6
- Kubernetes version (use `kubectl version`): 1.11.2
- Kubernetes installer & version: AKS, created with `az aks create`
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by skriss** [comment]
Hi @erjosito, it looks like your volume might be empty? Can you try again after making sure there are some files in there?  I will also look at adding some code to handle this situation better (restic returns an error if you try to back up an empty directory).

**Comment by ncdc** [comment]
Or is this a filesystem-specific issue?

**Comment by erjosito** [comment]
@skriss There are some files in the volume. If you look at the error message of the restic pod you can see the filenames there (the two default files access.log and error.log, plus a helloworld.txt file)

**Comment by skriss** [comment]
ah, ok. let me take another look at this and get back to you

**Comment by ncdc** [comment]
That's what this looks like to me. Whatever filesystem Azure Files is using doesn't seem to support extended attributes. Can you exec into the pod and run `mount`?

**Comment by ncdc** [comment]
xref https://github.com/restic/restic/issues/1800

**Comment by ncdc** [comment]
@erjosito you might try adding `nouser_xattr` to your storageclass's `mountOptions`

**Comment by erjosito** [comment]
@ncdc `nouser_xattr` did the trick, now it works. It might have been caused by the new functionality Microsoft has introduced in Azure Storage for AAD-controlled access (ACLs). Thanks a lot!

**Comment by ncdc** [comment]
@Bradamant3 this is something we may want to consider documenting

**Comment by jbmassicotte** [comment]
@ncdc I realize this is an old thread, but would you mind having a look at https://github.com/vmware-tanzu/velero/issues/2898. Somewhat similar to what erjosito reported: restic failing to backup volumes of type AzureFile. And I did use the nouser_xattr option, but no success.

**Comment by ncdc** [comment]
@nrb @carlisia

**Comment by carlisia** [comment]
Sure thing, it's on the list.

**Comment by jbmassicotte** [comment]
@carlisia How do I turn on debugging? I see the '-v level' option. To be used with 'velero install' or with 'velero backup create'? And what value should I use? 
I tried a few things without success.

**Comment by carlisia** [comment]
https://velero.io/docs/v1.4/troubleshooting/#getting-velero-debug-logs

**Comment by jbmassicotte** [comment]
@carlisia Please see explanation of the problem in my last comment on https://github.com/vmware-tanzu/velero/issues/2898. I am looking for a recommendation on a ‘permanent solution’.

**Comment by carlisia** [comment]
@jbmassicotte there is no need to add to that ticket as well as this ticket. Anything to address your issue will happen on @2898.
