### ISSUE TITLE
RFE: ability to restore one or more items by name

### ISSUE THREAD

**Issue by dirtbag** [vmware-tanzu/velero#904]
This is more of a design question. I know that ark is designed to be a disaster recovery product, but we are wondering if there is a way to pick and choose kubernetes objects to restore? Say for instance, somehow one of our ingresses gets deleted/damaged and we do a restore, It will try to restore the entire cluster (or just the namespace that we specify). Is there a way to restore individual pieces like an ingress?  I found the   "--include-resources"  in the restore docs, but I couldn't find a complete list of whats allowed to be specified there.   Also, is there something that documents how ark tries to do the restore when objects are already there? I did some restore tests after deleting certain parts of the pod like secrets or other objects and it seems like ark will not restore the object if it is already existing.  

thanks/regards,
db

**Comment by wwitzel3** [comment]
Hi db,

Ark has a `--include-namespaces` flag which lets you choose which namespaces from the backup to restore. But there is no way to selectively restore specific objects. As for what Ark does if some of the objects are present, it will skip and log, an example of what that output might look like is in the [restore debugging guide](https://heptio.github.io/ark/v0.9.0/debugging-restores).

My current recommendation would be to have a set of backups that only include what you might find yourself wanting to selectively restore instead of one large backup that holds everything. This has the added benefit of not having to remember which command flags to use, since that information was coded in to the each backup when it was created.

That said, I think we can consider per-item restoration as an enhancement to Ark.

**Comment by ncdc** [comment]
> I found the "--include-resources" in the restore docs, but I couldn't find a complete list of whats allowed to be specified there

It's anything you can specify to `kubectl get` - e.g. `pods`, `deployments`, `secrets`, and so on.

**Comment by dirtbag** [comment]
Thanks, that is helpful!

-db

**Comment by skriss** [comment]
xref #2043

**Comment by jnaulty** [comment]
a useful argument when creating velero backups is the `--selector`
```
velero backup create --help | grep selector                                                                                                   
  -l, --selector labelSelector                          only back up resources matching this label selector (default <none>)
```
You can label a resource you want backed up and use the selector argument to specify it in the `velero backup` command.

**Comment by hmz** [comment]
@jnaulty @ncdc Yes that is an option but I can not label dinamically provisioned disks on creation time -> https://github.com/kubernetes/kubernetes/issues/58413 so having that kind of an enhancement in Velero would realy help.

**Comment by chancez** [comment]
This seems essential. I want to restore a single PVC, not all of them. Restoring all of them is almost worse than simply having one that I have to restore manually because restoring the others will unnecessary revert them back to their state when snapshotted last.

**Comment by prasenforu** [comment]
Valid point @chancez 

@ncdc @skriss Any update ?

**Comment by konvergence** [comment]
Hi all,

I have a namespace with 2 statefulsets One for Tomcat and One postgres.
I try to restore only postgres with the following workflow :

scale 0 tomcat and scale 0 postgres
delete pvc-postgres

run velero restore.

Normally Velero should not restore existing objects.
Bu here velero stay freezed during restore of the pvc-tomcat ? why ?

It should not try restore pvc-tomcat if it ever exist ....
By this way you shoud be able to restore only pvc-postgres

**Comment by shurik-io** [comment]
@konvergence 

Use a more specific restore command using tags and resource types, so you ensure only trying to restore what you want. I know it should skip existing things, but I prefer to define what I like to restore. You also can define multiple labels or using the restore command multiple times for each label, as you like.

An example:
```
labels='foo=postgres'
velero restore create \
--from-backup "$backup" \
--restore-volumes=false \ # activate if you restore the pv in include-resources
--include-namespaces $namespace \
--include-resources statefulset.app,secret,pvc,service,<more resources if needed> \
--selector $labels \
--wait \
--show-labels
```

**Comment by konvergence** [comment]
Ok, fine
But how to restore only one pvc and not all ?

**Comment by konvergence** [comment]
oh... sorry, I understand
`foo=postgres` is the label on all my components for postgres

So I can restore them.

Thanks

**Comment by shurik-io** [comment]
> oh... sorry, I understand
> `foo=postgres` is the label on all my components for postgres
> 
> So I can restore them.
> 
> Thanks

Exactly, but in your label in use, and it should only restore the pvc. As well adjust the `--include-resource pvc` not to catch other resources as well.

**Comment by eleanor-millman** [comment]
Closing because labels can be used as a workaround.

**Comment by chancez** [comment]
@eleanor-millman not really, not everything always supports allowing users to configure labels out of the box. I think this is still needed. Of course it's easy to say "just make the thing support labels" but sometimes you're taking vendor's helm charts, and then forking them, etc. Is this feature really that contentious?

**Comment by shurik-io** [comment]
> @eleanor-millman not really, not everything always supports allowing users to configure labels out of the box. I think this is still needed. Of course it's easy to say "just make the thing support labels" but sometimes you're taking vendor's helm charts, and then forking them, etc. Is this feature really that contentious?

I want to add here; that if you have objects without labels, it will be hard to restore without labels. (legacy'ness happens as well).

**Comment by chancez** [comment]
> legacy'ness happens as well
exactly. Say you forgot to add labels, then you add them, but realize later you need to restore a backup from before you have labels? Too bad 🤷 Guess you're out of luck.

**Comment by chancez** [comment]
Perhaps if it's a matter of priority, then this issue should be opened and labels could be used to indicate priority on issues?

**Comment by eleanor-millman** [comment]
@chancez We have some other things on the drawing board that would address this but in a different manner.
